### ISSUE TITLE
Missing documentation for FRIGATE_RTSP_PASSWORD

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [blakeblackshear/frigate#1001]
I am having issues discovering exactly where the FRIGATE_RTSP_PASSWORD variable is configured.

MY expectation, is this would be documented in the configuration page located here: https://blakeblackshear.github.io/frigate/configuration/index

However, it is not documented here.

It is, however, very loosely documented on the installation page.
https://github.com/blakeblackshear/frigate/blob/9d2469549f5b8cb8591b01027b9b0f2462fb09b8/docs/docs/installation.md

I purpose the documentation to be updated to better reflect available environment variables in the configuration documentation.

**Comment by paularmstrong** [comment]
Please feel free to open a PR: https://blakeblackshear.github.io/frigate/contributing#documentation
