### ISSUE TITLE
Crying Detection not working

### ISSUE THREAD

**Issue by pappasaj** [blakeblackshear/frigate#10116]
I have the audio detector on and enabled for one of my IP cameras.  A lot of the different audio detection is working just fine, except for the Crying one.  I have a 15 month old son and have the IP camera in his room, but not matter how long or how loud he cries it never triggers that audio event.

**Describe the solution you'd like**
I would like to understand why the crying detection doesn't seem to work.

**Describe alternatives you've considered**
I'm looking into FFmpeg for home assistant to at least see if I can get an alert when a sustained decibal level is reached for a specific amount of time.

**Comment by NickM-27** [comment]
This is not a feature request. Please create a support discussion.
