### ISSUE TITLE
[FR] - Separate folders for currently recording and stored recording files

### ISSUE THREAD

**Issue by artlov** [blakeblackshear/frigate#1013]
It would be nice to have separate folders for currently recorded and already stored files. It helps to mount already recorded files to the external storage (e.g. NAS) and leaving file capturing to the local instance.
For example, today we have this setup:
```
root@a05602958a69:/opt/frigate# ls -lah /media/frigate/recordings/
total 49M
drwxr-xr-x 3 root root 4.0K Apr 20 11:43 .
drwxr-xr-x 4 root root 4.0K Apr  8 14:50 ..
drwxr-xr-x 6 root root 4.0K Apr 20 00:01 2021-04
-rw-r--r-- 1 root root 5.3M Apr 20 11:43 aicam-20210420114323.mp4
-rw-r--r-- 1 root root 1.1M Apr 20 11:43 ezviz-20210420114324.mp4
-rw-r--r-- 1 root root 7.1M Apr 20 11:43 hdipc-20210420114325.mp4
-rw-r--r-- 1 root root  15M Apr 20 11:43 hik1-20210420114323.mp4
-rw-r--r-- 1 root root  15M Apr 20 11:43 hik2-20210420114323.mp4

```   
If we do mount /media/frigate/recordings to the NAS, then actual  being writing *.mp4 files will be moved over network as well, which probably not good from performance view.
Would be nice to have one additional folder before YYYY-MM (2021-04) folder, like (just example of idea):
`/media/frigate/recordings/stored/2021-04`
In this case we can mount  `/media/frigate/recordings/stored` to the external storage and give possibility to increase amount of stored recorded days (NAS have way bigger storage than local HA host)

**Comment by blakeblackshear** [comment]
The files are moved from the initial location to the new location anyway. Won't that copy operation be the same amount of bandwidth?
