### ISSUE TITLE
Tensorrt-stable image reinitialized each time container starts

### ISSUE THREAD

**Issue by gelato** [blakeblackshear/frigate#10140]
Right now each time container starts download_yolo.sh is executed, which downloads weights (140+mb occasionaly on 30kbps from github) and converts model. So basically this defeats the whole purpose of running frigate in the container. This makes nvidia setup with embedded models pretty much unusable in containerized environments. And deepstack combo because of http requests will be even slower than using cpu as a detector, i think... Nvidia solution already has tensorrt-stable separate image, maybe it is ok to bake in a few models to avoid redownloading them each time container starts?

**Comment by gelato** [comment]
Can you please tell me what kind of config part regulates that? Currently i'm mounting /data on persistent volume and that's it. Every other volume is ephemeral. And yes, i'm using k8s, if that matters...

**Comment by NickM-27** [comment]
/config needs the entire directory mounted as /config/model_cache/... is where models are cached.
