### ISSUE TITLE
Only get HA notification on first entry into zone

### ISSUE THREAD

**Issue by cliffjao** [blakeblackshear/frigate#1015]
I seem to have it mostly setup but based on the documentation, I can't seem to figure out how to only get 1 notification upon first entry into a zone. Based on the examples in the docs, my phone buzzes with several updates as the object moves around within the zone.

**Comment by MattEng0** [comment]
Are you using Node-Red at all or just HA Automation to send the notifications? 

Walthowd has a great flow for Node-Red which rate limits the messages being sent:
[Node-RED Notification flow for Home Assistant Companion (IOS) users](https://github.com/blakeblackshear/frigate/discussions/940)

**Comment by cliffjao** [comment]
> Are you using Node-Red at all or just HA Automation to send the notifications?
> 
> Walthowd has a great flow for Node-Red which rate limits the messages being sent:
> [Node-RED Notification flow for Home Assistant Companion (IOS) users](https://github.com/blakeblackshear/frigate/discussions/940)

I'm using straight HA, but I figured out a way to rate limit using Delay.
