### ISSUE TITLE
[Frigate 0.13] libyolo_layer.so in the tensorrt container is compiled only for "modern" GPUs

### ISSUE THREAD

**Issue by jaharkes** [blakeblackshear/frigate#10151]
I've been running Frigate in a docker container with tensortrt decoder on an old former steam machine desktop which has a builtin GTX980 (maxwell generation?) GPU that is not replaceable.

Everything was working fine until I upgraded Frigate to 0.13, but then nothing seemed to work unless I disabled detection.

The various logged errors about keyerrors with negative numbers and recording managers not keeping up have been reported before, here are some of the similar issues I've found so far #7384 #9608 #9742 #9807. I went through all the suggested steps, upgrading nvidia drivers to the latest version, tried different yolo models, etc.  Nothing fundamentally improved things. I tried rebuilding models with USE_FP16=false, but even when it seemed the keyerrors were solved, detections were in odd locations and consistently had confidence scores well over 100%.

After a lot of digging I found that there were 2 things that needed to be corrected to get everything to work normally.

The most important one is that I had to rebuild the libyolo_layer.so library. During the rebuild it picked the correct GPU architecture which happens to be compute_50 on my system. My guess is that the original libyolo_layer.so version in the container happens to be compiled for whatever GPU the developer or CI system happens to have and that it is not quite as old so it still works for most people.

I copied my custom compiled version to both `/usr/local/lib` and `/usr/local/src/tensorrt_demos/plugins` and removed/rebuilt the cached trt models that were previously converted with the original libyolo_layer library. There were still several warnings during the rebuild about fp16 and I had to define USE_FP16=false to get rid of those. Not sure if that change really made a big difference or not. Setting just the USE_FP16=false environment was definitely not enough when I had tried that earlier before rebuilding the libyolo_layer library.

Anyway, with the now rebuilt libyolo_layer.so and re-converted trt models my system is working fine, I tried both the yolov4-288 and yolov7-320 models and have had no issues with either of them.

I'm guessing modifying tensorrt_demos/plugins/Makefile to always include compute_50 in the NVCCFLAGS might just create a fat binary version of libyolo_layer that will work for everyone independent of what kind of GPU happens to be installed in the container build host.

**Comment by jaharkes** [comment]
I'm not an nvidia compiler expert, but from my brief research it looks like it should be possible to build a single binary that at least supports all architectures (although it may not be optimized for any specific one) by setting `computes=50 60 70 80 90` in the Makefile that builds libyolo_layer.so.
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#virtual-architecture-feature-list

https://kaixih.github.io/nvcc-options/
> Compatibility:
>    -arch=compute_Xa is compatible with -code=sm_Xb when a≤b
>   -arch=compute_X* is incompatible with -code=sm_Y*

**Comment by NateMeyer** [comment]
Good find.  This wasn't an issue before because the libyolo_layer was built as part of the setup instructions for TRT on 0.12, so it always used the user's GPU compute level.  I'll take a look at the nvcc flags and see if there is a good way to do that universally for the CI build.  One bloated library is sure to be better than making every user download the whole toolchain to recompile it.

**Comment by NateMeyer** [comment]
> I don't know that we would want to use a custom compiled version of the library as that may cause other issues for other users.

We already build libyolo_layer.so as part of the docker build process.  It is mostly an extra cuda kernel to transform the output of the yolo model to something more usable.

**Comment by NickM-27** [comment]
ah good to know, thanks for the clarification

**Comment by NateMeyer** [comment]
@NickM-27 , if I submitted a PR that adds the `computes="50 60 70 80 90"` to the libyolo_layer.so script, should that target master or dev?  I view it a little more as a bug fix for maxwell cards on 0.13.  We'll need a couple people who've had problematic Maxwell cards to test also.

This `computes` value would only be set for the amd64 trt build, not jetpack.  I don't think those have had issues with this? But it wouldn't be hard to also add a unique set of compute flags for each of those either.

**Comment by NickM-27** [comment]
@NateMeyer we can defer to @blakeblackshear but currently I don't believe another bug fix update is planned so probably dev is my guess.

**Comment by blakeblackshear** [comment]
Can a patched file be mounted over the old one for now? There are a relatively small number of downloads of the tensorrt builds and an even smaller number with this issue. I would target dev for now. We could always add it to master later.

**Comment by posssson** [comment]
@jaharkes Thank you very much for your solution, I was stuck for 4 days :)

**Comment by NateMeyer** [comment]
> Can a patched file be mounted over the old one for now? There are a relatively small number of downloads of the tensorrt builds and an even smaller number with this issue. I would target dev for now. We could always add it to master later.

I can throw together a gist with instructions to rebuild and mount the updated library for v0.13

**Comment by NateMeyer** [comment]
@jaharkes Can you proof read this gist and make sure this works for you? Thanks!

https://gist.github.com/NateMeyer/a689b4462e57b3de0ebcc40e6538fc03

**Comment by jaharkes** [comment]
Works like a charm.
