### ISSUE TITLE
frigate 0.13 high cpu usage and ram usage browsing clips

### ISSUE THREAD

**Issue by mogim0gi** [blakeblackshear/frigate#10186]
I have noticed CPU usage increase sometimes in frigate, i have managed to replicated it when browsing history of Events, this goes to a point where frigate is completely unresponsive, after a while it seems to go back to normal. 

It is not related to detection resolution. Any ideas how to troubleshoot ?

<img width="446" alt="image" src="https://github.com/blakeblackshear/frigate/assets/64898710/e585d01d-4d64-41b4-bac7-4ccdfd8b9105">

<img width="820" alt="image" src="https://github.com/blakeblackshear/frigate/assets/64898710/b4299331-7a83-44f5-98fd-9dfc9b68c453">

**Comment by NickM-27** [comment]
this is not a feature request. You should create a support discussion and answer all of the question
