### ISSUE TITLE
Better timeline

### ISSUE THREAD

**Issue by deanfourie1** [blakeblackshear/frigate#10202]
**Describe what you are trying to accomplish and why in non technical terms**
Would love to see a better timeline, especially for the motion part. Events is great, it clearly displays the event, along with image to show the event, but fails to show any recorded "motion" in the timeline

**Describe the solution you'd like**
Would be great to see some sort of indicator for motion in the timeline. Im not sure if you've seen the timeline for other apps like,

- Scrypted
- Unifi Protect

They have really clean, easy to understand timelines of the recorded data, although these platforms done do the events, they do motion and the way that motion is displayed in the timeline makes it super easy to see where there is motion and where there is not.

**Describe alternatives you've considered**
There are none other then to use the current timeline which just shows the time?

**Additional context**
Love frigate, got it running nice and smoothly. Would just love to see this feature to take it up that extra notch!

Thanks the frigate team! Love your work!

![image](https://github.com/blakeblackshear/frigate/assets/71812804/f2b7808c-e356-4fd3-a1ea-e06f65199723)

![image](https://github.com/blakeblackshear/frigate/assets/71812804/7caa05b8-9864-4dc7-b7f3-a3f99929ce68)

![image](https://github.com/blakeblackshear/frigate/assets/71812804/c407b36d-001c-44ba-b2ba-71a3579b0d3f)

**Comment by NickM-27** [comment]
The UI is currently being rewritten for 0.14 and this will be one of the main components. The timeline has already been implemented so this can be closed.

**Comment by deanfourie1** [comment]
Excellent news, look forward to it.

Thanks

**Comment by deanfourie1** [comment]
any idea on a rough release date?
