### ISSUE TITLE
PCI-e Coral TPU not recognized (possibly proxmox related?)

### ISSUE THREAD

**Issue by R5fan** [blakeblackshear/frigate#1020]
**Describe the bug**
Since USB corals are out of stock everywhere, I got a M.2 PCIe version. It is detected in proxmox, I passed it through to the VM, but Frigate doesnt seem to detect it and the detector crashes.

**Version of frigate**
1.13

**Config file**
relevant part:
```detectors:
  coral:
    type: edgetpu
    device: pci 
```

**Frigate container logs**
```
detector.coral                 INFO    : Starting detection process: 34
frigate.edgetpu                INFO    : Attempting to load TPU as pci
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate.mqtt                   INFO    : MQTT connected
frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...

```

**Computer Hardware**
 - OS: proxmox
 - Install method: Addon
 - Virtualization: Proxmox
 - Coral Version: PCIe
 - Network Setup: wired

**Additional context**
Proxmox did detect the coral card, but did not offer to pass through the PCIe device from the GUI.  I had to manually add it in the VM config file, and I have no way of knowing 100% certain if that worked. More details here:
https://www.reddit.com/r/Proxmox/comments/mo7f99/trouble_passing_through_pcie_device_coral/gu7ge1g/

**Comment by R5fan** [comment]
oops, misclick, issue still open :)

**Comment by digiblur** [comment]
Can you see the /dev/apex_0  ?

**Comment by efirestone** [comment]
I'm running into the same thing (I think). 

My setup:
- Mini PCIe version of the Coral
- Proxmox 5.4.106-1-pve
- Home Assistant (OS) image running supervisor-2021.04.0
- Frigate 1.13 installed as an HA Add-On

Status So Far:
- The Coral (1ac1:089a) shows up in Proxmox via `lspci`
- `/dev/apex_0` does NOT show up in Proxmox, despite using [these](https://coral.ai/docs/m2/get-started#1-install-the-pcie-driver) instructions, including the workaround at the bottom (which was required). I suspect this is the issue, but don't know how to resolve it
- The PCI device is passed through to the HA VM
- The Coral shows up in HA via `lspci` (note that `lspci` is only available via a true shell, not via the Terminal/SSH add-on)
- `/dev/apex_0` also does not show up here

So, I think the root issue is that `/dev/apex_0` isn't showing up in Proxmox, but I'm not sure why. It's also possible that the driver doesn't need to be installed on the host and we just need `/dev/apex_0` to show up within HA (but again, not sure why it doesn't). I'm a bit out of my depth here though, so hopefully this helps someone with more knowledge.

**Comment by R5fan** [comment]
> Can you see the /dev/apex_0 ?

I can see it in ubuntu when I pass through the pcie card to an ubuntu VM running on proxmox. I can not see it in proxmox itself, and Im not sure how to check in HA OS, but going by what @efirestone says, probably not.

**Comment by R5fan** [comment]
It take it back. While I did see /dev/apex_0 in my ubuntu VM, and considered installing frigate on ubuntu, none of the coral examples worked. So I followed the instruction to blacklist gasket and apex, and install the prebuilt driver, and now I no longer see /dev/apex_0. 

In short, the PCIe card doesnt seem to work in an ubuntu VM under proxmox either, so the culprit does seem to be proxmox.

**Comment by efirestone** [comment]
To check in the HA VM:
- Use the shell for the HA VM from the Proxmox UI
- When it gives you the numbered list of options (after logging in as root), type `login`
- You should be in a "real" shell with full access to the HA VM (and not stuck inside a Docker container like when going through an add on)
- From here you can run `lspci`

**Comment by efirestone** [comment]
In case it's useful, here's `lspci -vvv` in Proxmox:
```
06:00.0 System peripheral: Device 1ac1:089a (prog-if ff)
        Subsystem: Device 1ac1:089a
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 18
        Region 0: Memory at d0100000 (64-bit, prefetchable) [size=16K]
        Region 2: Memory at d0000000 (64-bit, prefetchable) [size=1M]
        Capabilities: [80] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 256 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
                        ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset- SlotPowerLimit 26.000W
                DevCtl: Report errors: Correctable- Non-Fatal- Fatal- Unsupported-
                        RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+
                        MaxPayload 256 bytes, MaxReadReq 512 bytes
                DevSta: CorrErr- UncorrErr- FatalErr- UnsuppReq- AuxPwr- TransPend-
                LnkCap: Port #1, Speed 5GT/s, Width x1, ASPM L0s L1, Exit Latency L0s <64ns, L1 <1us
                        ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
                LnkCtl: ASPM Disabled; RCB 64 bytes Disabled- CommClk-
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 5GT/s, Width x1, TrErr- Train- SlotClk- DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Range ABCD, TimeoutDis+, LTR+, OBFF Not Supported
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR+, OBFF Disabled
                LnkCtl2: Target Link Speed: 5GT/s, EnterCompliance- SpeedDis-
                         Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
                         Compliance De-emphasis: -6dB
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete-, EqualizationPhase1-
                         EqualizationPhase2-, EqualizationPhase3-, LinkEqualizationRequest-
        Capabilities: [d0] MSI-X: Enable- Count=128 Masked-
                Vector table: BAR=2 offset=00046800
                PBA: BAR=2 offset=00046068
        Capabilities: [e0] MSI: Enable- Count=1/32 Maskable- 64bit+
                Address: 0000000000000000  Data: 0000
        Capabilities: [f8] Power Management version 3
                Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
                Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [100 v1] Vendor Specific Information: ID=1556 Rev=1 Len=008 <?>
        Capabilities: [108 v1] Latency Tolerance Reporting
                Max snoop latency: 3145728ns
                Max no snoop latency: 3145728ns
        Capabilities: [110 v1] L1 PM Substates
                L1SubCap: PCI-PM_L1.2+ PCI-PM_L1.1+ ASPM_L1.2+ ASPM_L1.1+ L1_PM_Substates+
                          PortCommonModeRestoreTime=10us PortTPowerOnTime=10us
                L1SubCtl1: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1-
                           T_CommonMode=0us LTR1.2_Threshold=0ns
                L1SubCtl2: T_PwrOn=10us
        Capabilities: [200 v2] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES- TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr+
                AERCap: First Error Pointer: 00, GenCap+ CGenEn- ChkCap+ ChkEn-
        Kernel driver in use: vfio-pci
        Kernel modules: apex
```

**Comment by R5fan** [comment]
Mine looks the same. I dont think frigate developers can do much about this, given that it also doesnt seem to work in a plain ubuntu VM (feel free to try, I may have missed something). But I would appreciate if this was kept open, given that USB corals are 22 weeks out according to mouser, so HA+frigate users will need an alternative and hopefully someone can make this work with the PCIe cards on proxmox.

**Comment by efirestone** [comment]
Inside the Frigate Docker container, I get this:
```
00:10.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a] (prog-if ff)
        Subsystem: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
        Flags: bus master, fast devsel, latency 0, IRQ 11
        Memory at 80010c000 (64-bit, prefetchable) [size=16K]
        Memory at 800000000 (64-bit, prefetchable) [size=1M]
        Capabilities: <access denied>
```

The container is not privileged (in the Docker sense), but I did try turning HA's Protection Mode off and that made no difference.

Also worth noting that the HA VM doesn't have apt installed so there's no obvious way to install the drivers directly in the VM. Passing through `/dev/apex_0` from the Proxmox host seems like the necessary path, but that will require getting `/dev/apex_0` to actually show up.

**Comment by MaleNurse** [comment]
So it's not entirely a driver issue, at least.  While `gasket-dkms` isn't baked into the image, even after I added it I still had no luck. Permissions took a bit of finagling, but after making them happy it took adding `/lib/modules:/lib/modules` into the container's volumes declaration to make `lspci` completely stop complaining. The weird thing is that, after all this was done, the [Getting Started example](https://coral.ai/docs/m2/get-started/#4-run-a-model-on-the-edge-tpu) worked just fine in the container despite Frigate throwing the same errors. For context, I'm running a Windows Server 2019 host using DDA PCIe passthrough to an Ubuntu 20.04 Hyper-V guest which is running docker. Anyway, I'm a novice at best here, so that's as far as I've gotten for the moment.

**Comment by MaleNurse** [comment]
Here's the final missing bit that got mine to finally work ([credit to u/neyneyT on reddit](https://www.reddit.com/r/Proxmox/comments/n34f8q/proxmox_vm_ubuntu_2004_frigate_2x_google_coral_tpu/))

Configure Frigate config.yml

Hash out or delete the existing CPU detectors and replace with the following:
```
detectors:
  coral_pci:
    type: edgetpu
    device: pci
```
or if you have 2 or more:
```
  coral_pci1:
    type: edgetpu
    device: pci:0
  coral_pci2:
    type: edgetpu
    device: pci:1
```
note: coral_pci1 is just a label. It’s not doing anything more than giving the device a friendly name.

**Comment by digiblur** [comment]
@MaleNurse yup. Hence this example add

https://github.com/blakeblackshear/frigate/pull/1009

**Comment by R5fan** [comment]
I just saw this being posted on reddit:
https://www.reddit.com/r/Proxmox/comments/n34f8q/proxmox_vm_ubuntu_2004_frigate_2x_google_coral_tpu/

Someone managed to get it working on proxmox, but in a ubuntu VM running a frigate container, and using a M2 to PCIe adapter (My x86 box happens to have the right M.2 slot for my m2 coral and no other PCIe slots anyhow).

Best I can tell, the instructions are essentially the same ones I already followed, aside from an extra line in  blacklist-apex.conf `options vfio-pci ids=1ac1:089a`
 and using a qm command to pass through the PCIe card instead of editing the conf file in pve. I didnt expect either to make a difference and it doesnt seem to. 

I havent tried it again using an ubuntu VM instead of HA OS, I dont expect it to work any better than my last attempt, but I have no idea why.

**Comment by nayneyT** [comment]
Hi. I hope that you do not mind me chirping in on this issue.

RE: R5fan - the extra line basically blacklists the device ID entirely from Proxmox. Its a bolt and braces approach but blacking gasket and apex will suffice.

As for your issues it appears the physical hardware is visible and accessible to HA OS as shown by the lspci outputs. However, it appears the driver is not loading and as as such you don't get apex_0 etc.

The latest Ubuntu/Debian has working Apex drivers and don't need updating (unless you really want to) to the latest ones.  The instructions are based on Ubuntu/Debian APK binaries and can be found here: [https://www.coral.ai/docs/m2/get-started](https://www.coral.ai/docs/m2/get-started) 

As for HA OS it looks to me like it's built on a customised buildroot distribution without the apex driver. [https://github.com/home-assistant/operating-system](https://github.com/home-assistant/operating-system). 

It heavily customised and as such there is no apt or build tools included. I think it has APK but I maybe wrong. You might be able to build the drivers from the source code. See the following GitHub page: [https://github.com/google-coral/libedgetpu](https://github.com/google-coral/libedgetpu) 

I've never run HA OS so unfortunately I cannot comment further but maybe somebody has had success building snd installing the Coral Driver in buildroot that HA OS runs on or building it and adding the driver afterwards to run in 'user-space'.

Regards,

nayneyT

**Comment by nayneyT** [comment]
It appears HA have accepted a pull request by GitHub user ryddler.

https://github.com/home-assistant/operating-system/pull/1263

https://github.com/blakeblackshear/frigate/issues/1066#issuecomment-835168125

Download the latest Dev image and the Coral devices should work now in HA OS.

**Comment by nayneyT** [comment]
I can confirm that the driver is now present in v6.0rc1 of HAOS https://www.reddit.com/r/Proxmox/comments/n7nfem/proxmox_hassos_frigate_google_coral_tpu/

**Comment by R5fan** [comment]
Finally got around trying this, and indeed with HAOS 6.0 this now works! I do get a warning in the log file but Im not sure it is important:
```
frigate.app                    INFO    : Capture process started for tuin: 43
frigate.app                    INFO    : Capture process started for karkot: 46
W :131] Could not set performance expectation : 46 (Inappropriate ioctl for device)
detector.coral                 INFO    : Starting detection process: 33
frigate.edgetpu                INFO    : Attempting to load TPU as pci
frigate.edgetpu                INFO    : TPU found
```
This is under proxmox. Anyone know what it means or should I care?

**Comment by ozett** [comment]
just for the record: 

get/check PCI-ID of coral-tpu with ```lspci -nnk```
and the hint is to disable pci sleep state:
https://www.reddit.com/r/VFIO/comments/l5awg0/using_google_coral_mpcie_tpu_in_qemu_vm/
with  extra line in blacklist-apex.conf ```options vfio-pci ids=1ac1:089a```

i fiddling to get this going today with a second m2 edge-tpu... lets see if the hints help out.

**Comment by FlexxFR** [comment]
I'm also hitting the same issue. Running the frigate docker on Ubuntu on Proxmox.
I followed this guide: https://www.reddit.com/r/Proxmox/comments/n34f8q/proxmox_vm_ubuntu_2004_frigate_2x_google_coral_tpu/
and succesfully passed the PCIe to the UbuntuVM, also within the container I can see /dev/apex_0

root@030ac612f3af:/opt/frigate# ls -al /dev/apex_0
crw-rw---- 1 root 1001 120, 0 Sep 13 22:07 /dev/apex_0
root@030ac612f3af:/opt/frigate# lspci -nnk


[2021-09-13 22:14:00] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral_pci:
Traceback (most recent call last):....bla bla

I tried various detector configurations but every TPU will fail.:
https://blakeblackshear.github.io/frigate/configuration/detectors

I have a M.2 Dual Edge TPU
https://coral.ai/docs/m2-dual-edgetpu/datasheet/

Any ideas

**Comment by teaching-innovation** [comment]
Sort of related but using USB edgetpu with Proxmox and Homeassistant OS. Still debugging bits and pieces but wanted to comment to say passing USB thru the port instead of the device.

frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-04-30 22:51:29] frigate.edgetpu                INFO    : TPU found

**Comment by vlar** [comment]
Since I struggled so much to get my PCIE coral working from a PCI into LXC in Docker. 
Maybe my post will help someone as I hadn't found this anywhere. 

Here my lxc conf file: 

`lxc.mount.entry: /dev/apex_0 dev/apex_0 none bind,optional,create=file 0, 0
#lxc.hook.mount: /root/hookcoral.sh
lxc.cgroup2.devices.allow: c 120:* rwm
lxc.apparmor.profile: unconfined
lxc.cgroup2.devices.allow: a
lxc.mount.auto: cgroup:rw
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.cgroup.devices.allow: c 243:* rwm

lxc.idmap = u 0 0 1
lxc.idmap = g 0 0 1
lxc.idmap = u 1 100000 65536
lxc.idmap = g 1 100000 65536
`


I had a permission issue in the /dev/apex_0 file in both the LXC container and therefore also the Docker one.

` 
root@DeepStack:/home/frigate# ls -al /dev/apex_0
crw-rw---- 1 nobody nogroup 120, 0 Aug  1 14:19 /dev/apex_0`

And of course: 

`root@DeepStack:/home/frigate# sudo chown root:root /dev/apex_0
chown: changing ownership of '/dev/apex_0': Operation not permitted`


I mapped the user to the root one of the host (which for sure reduce security to an extend I'm not sure to understand so be aware but if the LXC cage is broken the whole system is compromised). 

After the mapping process it worked and boy, it is a victory! I still prefer running docker within a LXC than Side by side of Proxmox. 

`root@DeepStack:~# ls -al /dev/apex_0
crw-rw---- 1 root root 120, 0 Aug  1 14:19 /dev/apex_0`

**Comment by nkgiovannivl** [comment]
> Since I struggled so much to get my PCIE coral working from a PCI into LXC in Docker. Maybe my post will help someone as I hadn't found this anywhere.
> 
> Here my lxc conf file:
> 
> `lxc.mount.entry: /dev/apex_0 dev/apex_0 none bind,optional,create=file 0, 0 #lxc.hook.mount: /root/hookcoral.sh lxc.cgroup2.devices.allow: c 120:* rwm lxc.apparmor.profile: unconfined lxc.cgroup2.devices.allow: a lxc.mount.auto: cgroup:rw lxc.cgroup2.devices.allow: c 226:0 rwm lxc.cgroup2.devices.allow: c 226:128 rwm lxc.cgroup2.devices.allow: c 29:0 rwm lxc.cgroup2.devices.allow: c 189:* rwm lxc.cgroup.devices.allow: c 243:* rwm
> 
> lxc.idmap = u 0 0 1 lxc.idmap = g 0 0 1 lxc.idmap = u 1 100000 65536 lxc.idmap = g 1 100000 65536 `
> 
> I had a permission issue in the /dev/apex_0 file in both the LXC container and therefore also the Docker one.
> 
> ` root@DeepStack:/home/frigate# ls -al /dev/apex_0 crw-rw---- 1 nobody nogroup 120, 0 Aug 1 14:19 /dev/apex_0`
> 
> And of course:
> 
> `root@DeepStack:/home/frigate# sudo chown root:root /dev/apex_0 chown: changing ownership of '/dev/apex_0': Operation not permitted`
> 
> I mapped the user to the root one of the host (which for sure reduce security to an extend I'm not sure to understand so be aware but if the LXC cage is broken the whole system is compromised).
> 
> After the mapping process it worked and boy, it is a victory! I still prefer running docker within a LXC than Side by side of Proxmox.
> 
> `root@DeepStack:~# ls -al /dev/apex_0 crw-rw---- 1 root root 120, 0 Aug 1 14:19 /dev/apex_0`

Hi, below other way to create the PCI Coral TPU with rigths:

On LXC Container has wrong permissions (nobody nogroup):
```
root@lxc-net-servs:/# ls -la /dev/apex_0
crw-rw---- 1 nobody nogroup 120, 0 Sep  6 10:24 /dev/apex_0
```

Change to Proxmox node!!:

Confirm the cgroup (120)
```
root@pmox00:/# ls -la /dev/apex_0
crw-rw---- 1 root apex 120, 0 Sep  6 10:24 /dev/apex_0
```

Create a Node and change permissions:

```
root@pmox00:/# mkdir -p /lxc/102010/devices

root@pmox00:/# cd /lxc/102010/devices

root@pmox00:/lxc/102010/devices:/# mknod -m 660 apex_0 c 120 0

root@pmox00:/lxc/102010/devices/# chown 100000:100020 apex_0

root@pmox00:/lxc/102010/devices# ls -la apex_0
crw-rw---- 1 100000 100020 120, 0 Sep  6 22:01 apex_0
```

On LXC config file add::
```
lxc.mount.auto: cgroup:rw
lxc.cgroup2.devices.allow: c 120:* rwm
lxc.mount.entry: /lxc/102010/devices/apex_0 dev/apex_0 none bind,optional,create=file 0,0
```
restart LXC and start frigate docker, in logs I found!

```
2023-09-06 22:20:19.187332418  [2023-09-06 22:20:19] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-09-06 22:20:19.187519113  [2023-09-06 22:20:19] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```
