### ISSUE TITLE
[feature request] Storage error handling & watchdog mqtt topic

### ISSUE THREAD

**Issue by Dinth** [blakeblackshear/frigate#10227]
**Describe what you are trying to accomplish and why in non technical terms**
Hi. Ive got a fairy complex storage setup for frigate with multiple things which may go wrong i believe. Unfortunately Frigate is not very good at handling problems with its storage, nor at reporting them.
For example:
* sometimes if the share goes RO (due to a raid error) Frigate stops showing any footage from any cameras, even live one
* sometimes if the share goes RO (due to something messing up with permissions) Frigate stops saving clips - it still registers events and makes snapshots, just no clips. 

In both cases, no issues are reported to me until i actually open frigate and check if the cameras are working and if the clip which i need is saved. 
This leaves me without footage sometimes for days, but also without an easy way to troubleshoot the issues as i dont know when they are happening. 

**Describe the solution you'd like**
Firstly, a better way of handling all kinds of errors and issues should be implemented. If storage goes down, this shouldnt prevent live feed. If ffmpeg processes crash they should be restarted. Frigate should check if the saved clips are actually saved.
Secondly, some kind of MQTT watchdog topic should be implemented which should flag if Frigate and all the cameras are working correctly or if there's an issue.
I believe BlueIris - with its primitive MQTT support - can be configured to do this, so for a mqtt-native NVR like Frigate this is a must-have IMO.

**Comment by NickM-27** [comment]
On the error handling front I don't think there is much to be done. Frigate already restarts ffmpeg processes that fail and it already knows when recording segments can not be written to and puts that in the logs. 

MQTT statuses for storage makes sense

**Comment by AliveDevil** [comment]
Regarding storage:
I think I'd have a feature like the Kerberos.io Agent/Vault-setup.
Kerberos.io Agent stores recordings locally, but when paired with a Kerberos.io Vault it'll push all recordings to that - and optionally deletes them locally, on sucessful upload.
If Frigate had a local scratch-dir (or using the tmp-folder) where recordings are stored until they are pushed to the persistent storage, that may be a network share of sorts, would eliminate in-transit data-loss in case of network interruptions, or remote storage issues.
