### ISSUE TITLE
Feature Request: Password protect RTMP streams

### ISSUE THREAD

**Issue by efirestone** [blakeblackshear/frigate#1023]
**Describe the bug**
Right now the re-broadcast RTMP streams don't appear to have an option for password protection. I'd like to protect those streams, similar to how the source streams are protected. For my purposes a single user/password for all re-broadcast streams works great.

**Version of frigate**
1.13

**Comment by blakeblackshear** [comment]
I don't plan to add any auth to frigate directly. You can run an nginx proxy with basic auth in front of it.
