### ISSUE TITLE
[Feature Request] Motion boundary heatmap / publish motion boundaries over MQTT

### ISSUE THREAD

**Issue by nagisa** [blakeblackshear/frigate#10247]
**Describe what you are trying to accomplish and why in non technical terms**

I would like to build a heat map of detected motion boundaries and their sizes in hopes that it would help me to tune my camera parameters more effectively than carefully watching for the brief blips of red rectangles on the debug view.

It is important that a full boundary is represented for each detection, as the boundary size can help to determine which parameter – the threshold, the contour area or some other to tune.

**Describe the solution you'd like**

For me a sufficient solution would be to see each detection be published in MQTT as a quadruple of `(x, y, w, h)`. I'd be then able to push these detections to something like influxDB for inspection.

There could be an option on the mqtt configuration to allow enabling or disabling this, in case users wanted to reduce the amount of traffic on their broker.

**Describe alternatives you've considered**

Having the debug window accumulate an interactive heatmap would be neat. I thought, however, that it may be much more development effort to implement something like this. Not to mention that some mechanism to publish just the bounding boxes would be a necessary prerequisite anyway.

**Additional context**

**Comment by NickM-27** [comment]
I don't think we want to be publishing to mqtt that much, and I'm not sure we would want to have some special debug option for it.

We have some ideas for the current UI rewrite that may include heat maps while reviewing motion data so it can be simple to see where the motion occurred

**Comment by bob454522** [comment]
I understand how complex this request could be (so i get the reasoning).   That said any kind of data points (outputted as raw text or as graphics/images) would be very useful (and yet another unique to frigate NVR feature).  IE: heatmaps of where motion is initially detected (or most frequently detected)-  either in a graphical form, or even as raw X/Y Coordinates for the user to then process / graph on their own.  (or another example of datapoints - the latest gen Axis brand cameras can show a line overlay of where a detected object has traveled)

or an ability to get get data points from the "time in area" feature ive seen mentioned (btw time in area is a feature that newest generation Axis branded cameras support, on the camera itself) - ie:   https://www.youtube.com/watch?v=a_DzE2JFZ68  (this video features the "Time in area" function but you can also see the line overlay of where a detected object has traveled, in it as well).

This is more of a wish list / neat feature, As I do realize how difficult and complicated something like this is to pull off.   Thank you for frigate!!

**Comment by bobergmartin-ai** [comment]
This is a great idea. I found it slightly annoying to wait for a windy day and then sit and stare at the debug view, effectively building a "motion heat map" in my mind. Voting +1 for this
