### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by aacostarua** [blakeblackshear/frigate#10277]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to be able to view timeline per camera on HA. 

**Describe the solution you'd like**
Allow toggle for each camera to enable timeline. Show events in timeline.

**Describe alternatives you've considered**
Going to another software I guess not sure of any workarounds as I need a timeline to pass regulations for my business.

**Additional context**

**Comment by NickM-27** [comment]
We are currently rewriting the UI and the timeline has already been implemented. 

Also, the frigate hass card has supported a timeline for some time  https://github.com/dermotduffy/frigate-hass-card
