### ISSUE TITLE
Send to Frigate+ behavior

### ISSUE THREAD

**Issue by ronbruins** [blakeblackshear/frigate#10300]
I want to be able to quickly sent event images to frigate plus. Now the following is happening:

**option 1:**
- click sent to Frigate+ -> select this is / this is not
- wait for it to finish so the pop up window closes
or **option 2:**
- click sent to Frigate+ -> select this is / this is not
- quickly click 'close' and click sent to frigate+ from another event
- click the 'this is / is not' 

However when using option 2, when the first image finished uploading it also closes the second pop up window.

**Describe the solution you'd like**
It would be better to have something like:
- When clicking the 'this is / this is not' the window closes and a new 'send to frigate+' can be selected. 
- The finished upload should not interfere with the newly opened 'send to frigate+'

**Comment by NickM-27** [comment]
The ui is being rewritten for 0.14 and this is already the way it works in the new implementation. Therefore closing this issue.

**Comment by andreasavg** [comment]
I second this. I send through multiple images per day and having the modal pop up tends to be slower. We could even have two buttons, on the main event tile, one for this is a $1 and one for this is not a $1.
