### ISSUE TITLE
Request: an option in the Logs to either "Jump to Bottom", or show in Reverse order

### ISSUE THREAD

**Issue by supermarkert** [blakeblackshear/frigate#10309]
**Describe what you are trying to accomplish and why in non technical terms**
I've had my Frigate install going for a few weeks, and still working through trying to reduce errors (this may be a lost cause due to Wifi issues, but that's not what I'm trying to solve here).
The issue is that there are times when the logs get sporadically flooded with many random errors, which makes navigating the log difficult. If I try to view on mobile, I need to scroll down for dozens and dozens of "pages". If I let it go for several days, there may be enough errors that I simply can't get to the bottom to check what the latest issues are.
Again, I know I should do what I can to reduce errors, but I've also seen notes in some threads where some errors are to be expected (especially with Reolink cameras, etc.).  And the log doesn't seem to ever "reset" at any point, so it just keeps getting longer indefinitely?

**Describe the solution you'd like**
I'd like either a button at the top of the logs page that allows me to "Jump to the Bottom", or an option in my config that populates the logs in reverse order.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by NickM-27** [comment]
Thanks for the request. We are currently working rewriting the UI for 0.14 and a jump to bottom button for logs has already been implemented. Therefore, closing this issue
