### ISSUE TITLE
Zoom in on camera view

### ISSUE THREAD

**Issue by timgurske** [blakeblackshear/frigate#10325]
One feature I use constantly on BlueIris installs is using the scroll wheel to zoom in on the live or recorded videos. This helps when you have 4k cameras but the monitor isn't large enough to see all the details that are being captured.

Please add an ability to use the scroll wheel to zoom in on a portion of the video.

**Comment by NickM-27** [comment]
Thanks for the request, user closed this for some reason but I reopened it as there is an existing request for this. Feel free to leave a 👍 and any details there https://github.com/blakeblackshear/frigate/issues/4137
