### ISSUE TITLE
Snapshot error for Frigate

### ISSUE THREAD

**Issue by alexdelprete** [blakeblackshear/frigate#1032]
Frigate is working fine on my NUC+Coral+HA.

The problem I'm having is that when I take an HA Snapshot, the only addon that never gets through is Frigate. This is what I'm seeing in the supervisor log:

> 21-04-27 22:30:10 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_grafana
> 21-04-27 22:30:10 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_vscode
> 21-04-27 22:30:13 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_vscode
> 21-04-27 22:30:13 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on e141bb7c_blueriiot2mqtt
> 21-04-27 22:30:13 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon e141bb7c_blueriiot2mqtt
> 21-04-27 22:30:13 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_portainer
> 21-04-27 22:30:13 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_portainer
> 21-04-27 22:30:13 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_zwavejs2mqtt
> 21-04-27 22:30:13 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_zwavejs2mqtt
> 21-04-27 22:30:14 INFO (SyncWorker_3) [supervisor.docker.addon] Export image 1f3d020e/amd64-addon-hassos_ssh_configurator_addon to /data/tmp/tmps5m35v7p/image.tar
> 21-04-27 22:30:14 INFO (SyncWorker_3) [supervisor.docker.addon] Export image 1f3d020e/amd64-addon-hassos_ssh_configurator_addon done
> 21-04-27 22:30:14 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 1f3d020e_hassos_ssh_configurator_addon
> 21-04-27 22:30:24 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 1f3d020e_hassos_ssh_configurator_addon
> 21-04-27 22:30:24 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_ssh
> 21-04-27 22:30:24 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_ssh
> 21-04-27 22:30:31 INFO (SyncWorker_2) [supervisor.docker.addon] Export image ccab4aaf/amd64-addon-frigate to /data/tmp/tmpxxnveudp/image.tar
> 21-04-27 22:30:31 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't write tar file /data/tmp/tmpxxnveudp/image.tar: 500 Server Error for http+docker://localhost/v1.41/images/ccab4aaf/amd64-addon-frigate:1.13/get: Internal Server Error ("file integrity checksum failed for "usr/lib/x86_64-linux-gnu/libLLVM-11.so.1"")
> 21-04-27 22:30:31 ERROR (MainThread) [supervisor.snapshots.snapshot] Can't create snapshot for ccab4aaf_frigate
> 21-04-27 22:30:31 INFO (MainThread) [supervisor.snapshots] Snapshotting 19f55ea3 store folders
> 21-04-27 22:30:31 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder ssl
> 21-04-27 22:30:31 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder ssl done
> 21-04-27 22:30:31 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder share
> 21-04-27 22:30:31 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder share done
> 21-04-27 22:30:31 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
> 21-04-27 22:31:26 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
> 21-04-27 22:31:26 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder addons/local

Any help to fix this is appreciated, thanks in advance.

**Comment by blakeblackshear** [comment]
I don't use HassOS snapshots, so I am not sure what is happening here. There is no reason to backup the docker image itself for frigate since it writes all state to the media folder. You should always be able to safely delete it and rebuild.

**Comment by alexdelprete** [comment]
> I don't use HassOS snapshots, so I am not sure what is happening here. There is no reason to backup the docker image itself for frigate since it writes all state to the media folder. You should always be able to safely delete it and rebuild.

Yes, that's what I'm doing now when I need to restore, I reinstall frigate since all the config is in the config.yml file, and that is being backed up fine.

Out of curiosity: why does the config use a .yml extension instead of .yaml? :)

**Comment by blakeblackshear** [comment]
No particular reason. Both are common.
