### ISSUE TITLE
Can you split the config into multiple files?

### ISSUE THREAD

**Issue by errolsancaktar** [blakeblackshear/frigate#1033]
Just wondering if it would be possible and if so how to split the config to use the standard *.d setup in linux?

**Comment by blakeblackshear** [comment]
Why would you want to do this?

**Comment by kdknigga** [comment]
It would be a nice boost to modularity and organization to be able to break out global settings and individual camera settings into individual files.  I'm not sure how well yaml lends itself to that kind of thing, though.

**Comment by errolsancaktar** [comment]
Basically this.  it would be ideal to have the global stuff in config.yml and a sub directory called config.d which would allow you to separate the cameras and potentially even create logical groups.  I would imagine that it would be fine as Homeassistant has this Functionality.

Thanks!

**Comment by JasonSwindle** [comment]
I agree; I'm about to have 15 cameras on this setup, and being able break cameras or zones or something would be nice. The power to do imports like HA does would be most valuable.

**Comment by herostrat** [comment]
Home Assistant implements it this here:
https://github.com/home-assistant/core/tree/dev/homeassistant/util/yaml

It is basically the solution outlined here: https://stackoverflow.com/a/9577670

Just if someone wants to tackle it.

**Comment by JasonSwindle** [comment]
This issue is not stale, just a long running feature request.

**Comment by ElMoribond** [comment]
I don't think that will ever be possible.
It is much easier to manage the configuration of a software in a single file rather than several.
Even though they're all in the same directory.

The solution is simple I think,
it would be necessary to be able to activate/deactivate a camera via MQTT and/or HTTP.

Maybe one day it will be possible. It would be good.
That would add a lot of scenarios possibility...

**Comment by trythatagain** [comment]
I'd like this option as well, I run Frigate just in a Docker no HA, I'd like a global file, and then a file for each camera, for me this would make editing files a lot easier.
