### ISSUE TITLE
Easy way to share a camera stream

### ISSUE THREAD

**Issue by gatorreina** [blakeblackshear/frigate#10363]
Is there an easy way that I can share a camera stream with my neighbors upstairs so that they can see who's outside the building entrance or if  a package has been delivered without giving them full access to Frigate?

For example is there a way to re-stream a camera to a URL that they could access from a browser?

I have am studying Birdseye restream but it seems that would require giving them access to my network.

I know HomeAssistant can probably do this but I was hoping for a more simple way as I know very little about HA and they are even less tech savy than me.

**Comment by jakubsuchybio** [comment]
I think you can completely skip frigate and give them the camera link. Frigate can maybe help you restream the camera on http? If the camera doesn't support that. Restream will also help with the load on the camera, because then i doesn't need to stream to the multiple places.

**Comment by gatorreina** [comment]
My cameras are connected to a switch, along with the linux computer running Frigate, which is then plugged into my wifi router. Accordingly, the cameras are on a different network. I am only able to access my cameras directly by plugging into the switch so as far as I understand providing direct access to the cameras would be even more difficult. Re-streaming to http sounds like something that would be useful however I do not know how to do that or whether Frigate allows for it.

**Comment by jakubsuchybio** [comment]
Ah, so the neighbors are not on your local network and they have their own internet connection different from yours?

- If they are local its easy, you just give them local ip of your camera and they can view it directly.

- If they are on different internet connection than you, then you would have to either have public IP for them to see you and then you would have to NAT some port on your public IP to the camera's IP. Or if you have the same internet provider, they might have a setup where they have metropolic IPs so the ppl nearby could see each other and then you would do the same NAT but not from your public IP but from your metropolic ip.

**Comment by bazylhorsey** [comment]
I would not recommend @jakubsuchybio option 2
_If they are on different internet connection than you, then you would have to either have public IP for them to see you and then you would have to NAT some port on your public IP to the camera's IP. Or if you have the same internet provider, they might have a setup where they have metropolic IPs so the ppl nearby could see each other and then you would do the same NAT but not from your public IP but from your metropolic ip._

You need some protection, this is how people got ahold of everyone's camera data in the 2010's. 
You'll either want a VPN (tailscale is super easy and secure), or keep it private only.
If you decide you really want it on the public network via port forward, make sure you have a strong user/pass for the streams which can be configured in frigate (or go2rtc). You can also set up stronger authentication through something like a proxy (traefik, nginx, apache) to whitelist IP's or locations.

**Comment by gatorreina** [comment]
First and foremost thank you for the ideas. What if I add a second mini pc plugged into my router running frigate with a minimal configuration that just streams those two cameras. I create a guest network on my router and make that linux box the only machine on the guest network. I then give them the password to the network and the url to the frigate setup?

**Comment by kiney** [comment]
are you using go2rtc with frigate?
Might be easiest to use go2rtc and _not_ frigate for publishing the streams to your neighbours.
You can probably even avoid port forwarding, VPN and all that buy piggy-backing on e.g. telegram:
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#publish-stream

**Comment by gatorreina** [comment]
Currently my frigate config does not use go2rtc and I know nothing about it. I nonetheless appreciate the suggestion and will look into go2rtc.

**Comment by yodaphone** [comment]
> Is there an easy way that I can share a camera stream with my neighbors upstairs so that they can see who's outside the building entrance or if a package has been delivered without giving them full access to Frigate?
> 
> For example is there a way to re-stream a camera to a URL that they could access from a browser?
> 
> I have am studying Birdseye restream but it seems that would require giving them access to my network.
> 
> I know HomeAssistant can probably do this but I was hoping for a more simple way as I know very little about HA and they are even less tech savy than me.

you can do it multiple ways

1. give them the rtsp url and ask them to use VLC to view the stream. No frigate involved.
2. install a simple RTSP server (mediamtx) and feed the stream to that and publish it on a webpage 
3. do something like this https://forums.wyze.com/t/rtsp-stream-to-view-on-local-website-using-web-browser/102730
