### ISSUE TITLE
Unable to downgrade to v0.12.1

### ISSUE THREAD

**Issue by siri10086** [blakeblackshear/frigate#10390]
Downgrading to v0.12.1 in Docker prompts ghcr.io/blakeblackshear/frigate:v0.12.1
Unable to find image 'ghcr.io/blakeblackshear/frigate:v0.12.1' locally
docker: Error response from daemon: manifest unknown.
  And stable-v0.12.1 does not work either
ghcr.io/blakeblackshear/frigate:stable-v0.12.1
Unable to find image 'ghcr.io/blakeblackshear/frigate:stable-v0.12.1' locally
docker: Error response from daemon: manifest unknown.
How should I downgrade?

**Comment by NickM-27** [comment]
There is no v in the image name
