### ISSUE TITLE
Ability to ignore objects that do not travel through frame/or do not enter *multiple* zones

### ISSUE THREAD

**Issue by raintonr** [blakeblackshear/frigate#10414]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to ignore detected objects that seem to appear instantly in frame without actually travelling through the frame so that I can reduce false positives.

**Describe the solution you'd like**

I think an option that would be very useful would be: when an object is first detected it should not be considered valid/active/whatever and an event should not be created unless the object actually moves in consecutive frames. Ie. it moves `x` pixels over `y` frames.

**Describe alternatives you've considered**

Currently I can only find the `inertia` (zones) setting that might help here, but that is only to do with how many frames an object is in zone before being confirmed there.

I have also looked at the `required_zones` (MQTT, events). I already have several zones configured for our cameras as those can be used for detection in an external system (MQTT). I have that system ignore objects unless they have been in multiple zones. This seems to work well externally, but that doesn't help Frigate recordings. I built this code with rules linking adjacent zones - even zones from different cameras can be considered in this way - and it works well. Maybe `required_zones` could somehow be augmented to have some simple AND/OR logic in there that could work?

**Additional context**

An example event: Sometimes dirt/snow/rain on the lens confuses the detector...

![image](https://github.com/blakeblackshear/frigate/assets/3794098/876c707f-b389-4e08-825f-24043649a4a3)

In this example an object appeared almost directly in the centre of the frame and appeared to stay motionless for some time (in this example, around 15 minutes) before the lens cleared. For slow frame rates and fast moving objects I guess that is possible but in most situations this should be impossible.

Frigate correctly marked the object as motionless 17 seconds after it appeared but did mark it as active a few times, however, the bounding box barely moved.

**Comment by raintonr** [comment]
Is there some kind of sensitivity around how far (how many pixels) an object needs to move then? Rather than the current 'number of frames'?

**Comment by NickM-27** [comment]
it's not about pixels, it is about the IoU of the bounding box. Once the IoU of the bounding boxes is low enough it is considered moved. The logic behind this has already been improved for 0.14

**Comment by raintonr** [comment]
IoU, pixels, whatever... so long as there's a way to specify sensitivity think that would solve this one.

Good to know improvements coming. If you happen to have link(s) to the issue(s) around that would be good to see.

**Comment by NickM-27** [comment]
There is no way for a user to specify sensitivity, this is one of those things that is better for frigate to handle internally and make improvements to become smarter. The docs to explain a certain value and what that value means would be very long and likely complicated
