### ISSUE TITLE
When "No frames have been received, check error logs", reflect true FPS in system/API

### ISSUE THREAD

**Issue by ghust** [blakeblackshear/frigate#10415]
**Describe what you are trying to accomplish and why in non technical terms**
As I'm troubleshooting some issues with cameras disconnecting, I have added frigate to zabbix monitoring. 
One of the checks is the camera FPS.  I thought I could use this to spot anomalous behaviour
However:

![image](https://github.com/blakeblackshear/frigate/assets/11678058/b094ff04-0668-46c3-9f27-d673e5100438)

![image](https://github.com/blakeblackshear/frigate/assets/11678058/4825c80f-137b-4a27-a86a-fec1a36e5d94)

**Describe the solution you'd like**
I need a way of identifying the error through API/monitoring

**Describe alternatives you've considered**

I realize this is a symptom, however this monitoring check will allow me to gather logs to create a good support request. 

**Additional context**

**Comment by NickM-27** [comment]
This is already how frigate works. If a stream fails then the camera_fps will be set to 0. There can be cases where it shows no frames received because outdated frames are still being pocessed

**Comment by SuperMaximus1984** [comment]
Can "No frames have been received" message be displayed due to insufficient GPU power? System shows 100% load, but at the same time VRAM is 50% free. What do I need to upgrade in order to avoid this?
I have this message received during windy days, when most of my cameras that have trees in focus, seem to overload the system. I have TensorRT YoloV7x model running.

**Comment by NickM-27** [comment]
Yes, it could be due to the detector failing to process frames

**Comment by SuperMaximus1984** [comment]
> Yes, it could be due to the detector failing to process frames

Hi Nick! Do you know if my GPU is a culprit here? I've tried replacing go2rtc with a different version, but no luck...

**Comment by SuperMaximus1984** [comment]
> Do you have skipped frames on the system page while this happens?

Yeah, I do. Not many, but 2-3 frames skipped - that's a regular picture.
I have GTX1650, which should be fine for 8 cameras, at least I though so lately... before I added another camera

**Comment by NickM-27** [comment]
seems likely to be the issue then
