### ISSUE TITLE
Add support for vehicle types

### ISSUE THREAD

**Issue by Suleiman700** [blakeblackshear/frigate#10464]
Hi there,
I would like to say thanks for your hard work on Frigate :)

I would like to ask for a feature to add support for vehicle types, like 'Truck, Tractor, Car, Bike ...etc' and not only 'Car'
So users can search for more types and will be easier to find the scene we are looking for

**Comment by NickM-27** [comment]
The current default model supports truck and car but truck is relabeled as car because they often swap labels many times making things inaccurate. 

The model is trained on the COCO dataset so new labels can not be added.
