### ISSUE TITLE
Ability to unselect all sub labels (currently only select seems available) and remove sublabels

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#10471]
**Describe what you are trying to accomplish and why in non technical terms**
I am trying to do the reverse a show all sub labels and I don't think it's available currently.
I am also trying to remove sub labels but not sure how this can be done (can it be done using MQTT?)

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by NickM-27** [comment]
this already exists, you just press the blue focus button
![Screen Shot 2024-03-15 at 06 11 28 AM](https://github.com/blakeblackshear/frigate/assets/14866235/aa091219-7d69-4bec-8df1-3b01b470fea7)

**Comment by atv2016** [comment]
Ah, but that's not what I mean. I mean yes it does that but I want the opposite of show all, e.g. I want to unselect all the sub labels. Because if I have a lot, that is a lot of work right now :-)

Maybe I am misunderstanding the show all, but I would have thought there would be a deselect button as well to counter the 'show all'.

**Comment by NickM-27** [comment]
> Maybe I am misunderstanding the show all, but I would have thought there would be a deselect button as well to counter the 'show all'.

I am not talking about show all I am talking about the blue focus button. Its entire purpose is to select only that label. 

You can do that too, just select `None` in the sub label menu

> And what about removing sub labels, is that a possibility (ideally using MQTT) ?

sub labels come from the event db. You can remove an event using the api.
