### ISSUE TITLE
Record events with honouring motion mask

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#10470]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to record events with motion masks intact, so I don't see the timestamp I am blanking out for example.

**Describe the solution you'd like**
Record as per what I see when motion mask is active

**Describe alternatives you've considered**
I could strip it out on CCTV but not all systems support that.

**Additional context**

**Comment by blakeblackshear** [comment]
You can already do this with ffmpeg arguments on the record stream or in go2rtc. However, any modifications to the recorded stream will require fully decoding and encoding the stream again. Doing this in real time even for modest resolutions requires substantial processing power and often results in lost quality in the image. There is no way around this.

**Comment by atv2016** [comment]
Cool, I'll get do it in the CCTV system then if available. Thanks!
