### ISSUE TITLE
Improve send to frigate+ ui

### ISSUE THREAD

**Issue by IetIesAai** [blakeblackshear/frigate#10491]
Going through a backlog of events to submit these to frigate+, as I'm not always able to do so shortly after detection. Say you are submitting event 1, and it is uploading in the background, and you click on the button to "Send to Frigate+" on event 2, and the dialog opens where you have to choose "this is a x"/"this is not a x"/close. If at that time the upload of event1 finishes in the background, the open dialog will close. If this happens at more or less the moment you wanted to click one of the buttons in the dialog, you are now clicking open another event in the list. If you weren't, you'll have to reopen the send to dialog of the event you were actually wishing to upload.  This quickly becomes frustrating :-) 
Thei ssue doesn't happen if you wait for each previous event to finish uploading, which slows you down significantly if you have a longish queue of events you wish to submit.

Hopefully the ui can be improved not to close the open dialog or not to refresh the send to/edit in frigate+ button while a dialog is open.

**Comment by NickM-27** [comment]
The UI is currently being rewritten and this has already been implemented https://github.com/blakeblackshear/frigate/pull/10273
