### ISSUE TITLE
Using Unifi Cameras without RTSPX or go2rtc - for documentation

### ISSUE THREAD

**Issue by Puma7** [blakeblackshear/frigate#10505]
For the documentation of Unifi cameras:

To integrate UniFi cameras with Frigate using RTSP instead of RTSPS, modify the camera's URL as follows: Convert the protocol from `rtsps` to `rtsp`, change the port from `7441` to `7447`, and remove any query parameters such as `?enableSrtp`. This adaptation enables the direct use of the RTSP stream with Frigate through FFmpeg, simplifying the setup by eliminating the need for Go2RTC.

**Example:**

Original RTSPS URL:
```
rtsps://192.168.1.1:7441/CnhLKtvnsIOsgV15?enableSrtp
```

Modified for RTSP:
```
rtsp://192.168.1.1:7447/CnhLKtvnsIOsgV15
```

This streamlined approach facilitates easier integration of UniFi cameras into your Frigate surveillance system.

**Comment by NickM-27** [comment]
to be clear, the use of go2rtc is highly recommended due to better quality live views in frigate and the streams being available in home assistant. The use of go2rtc is recommended in general for this reason

**Comment by Puma7** [comment]
> to be clear, the use of go2rtc is highly recommended due to better quality live views in frigate and the streams being available in home assistant. The use of go2rtc is recommended in general for this reason

Thank you for your response. Indeed, you're spot on. I aimed to compile this information as a helpful resource for others who might encounter similar issues with using go2rtc as a backup solution.
