### ISSUE TITLE
Feature proposal - regions/areas to ignore

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#106]
One of my cameras are monitoring my front lawn and during winter there is a gap in my bushes towards the street that detects objects.

Would it be possible to implement a feature to be able to ignore certain parts of the camera view? 

Thanks! <3

**Comment by miikkajo** [comment]
Please see config example,
you can use mask image to disable detection

    ################
    ## Optional mask. Must be the same dimensions as your video feed.
    ## The mask works by looking at the bottom center of the bounding box for the detected
    ## person in the image. If that pixel in the mask is a black pixel, it ignores it as a
    ## false positive. In my mask, the grass and driveway visible from my backdoor camera 
    ## are white. The garage doors, sky, and trees (anywhere it would be impossible for a 
    ## person to stand) are black.
    ################
    # mask: back-mask.bmp

**Comment by tubalainen** [comment]
> Please see config example,
> you can use mask image to disable detection
> 
> ```
> ################
> ## Optional mask. Must be the same dimensions as your video feed.
> ## The mask works by looking at the bottom center of the bounding box for the detected
> ## person in the image. If that pixel in the mask is a black pixel, it ignores it as a
> ## false positive. In my mask, the grass and driveway visible from my backdoor camera 
> ## are white. The garage doors, sky, and trees (anywhere it would be impossible for a 
> ## person to stand) are black.
> ################
> # mask: back-mask.bmp
> ```

How can I define a certain area of the camera view using the "mast" option? Or have I missed something?

**Comment by tubalainen** [comment]
@miikkajo did you have any idea how to solve the "ignore a certain part of the camera view" issue?

**Comment by scstraus** [comment]
You make a black and white image the same size as your camera feed and mark things in white that you want to analyze and things in black that you don't want to analyze. Then you provide the path to this image in your config and frigate will ignore the parts you marked in black.

**Comment by tubalainen** [comment]
> You make a black and white image the same size as your camera feed and mark things in white that you want to analyze and things in black that you don't want to analyze. Then you provide the path to this image in your config and frigate will ignore the parts you marked in black.
> 
> This feature request should be closed as the feature has existed for quite some time already and is clearly listed in the documentation.

Thanks for the clarification. Now I do understand how to use the optional mask feature.
The documentation text and the example was not clear enough for me to understand how it works. Sure, English is my second language so yea, it can be my own short comings.

I will close this "feature request" and also make a proposal to update the details on the option.
