### ISSUE TITLE
Custom events are not propagated to MQTT

### ISSUE THREAD

**Issue by ristoavila** [blakeblackshear/frigate#10618]
**Describe what you are trying to accomplish and why in non technical terms**
I want to have mqtt event when custom event is received, with the event details. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
PIR / contact sensor triggers and is routed to specific camera to flag the event. I would like to receive same event with snapshot / video details similar to other detection events.

**Comment by NickM-27** [comment]
This is on purpose. The vast majority of fields for mqtt events don't apply to custom events. Also, you as the user are creating the event so you can fire some other automation along with it. 

Custom events are also going to be changing in the upcoming version of frigate that would make this change incompatible as well.
