### ISSUE TITLE
ONVIF/preset aware object masks & zones for PTZ autotracking

### ISSUE THREAD

**Issue by robby-dermody** [blakeblackshear/frigate#10644]
I've been playing around with PTZ autotracking/ONVIF integration. In this scenario I have a PTZ camera and a separate spotter camera. I'd like the spotter camera to move the PTZ camera to a different location preset if an object is recognized by the spotter. This is the scenario raised in the frigate documentation at https://docs.frigate.video/configuration/autotracking/#usage-applications

Doing this is straightforward enough. My question is: once the PTZ camera moves to the new scene, could the object masks frigate has for it (which would be programmed for its default/home preset) prevent object recognition -- and therefore effectively autotracking -- from occurring on the new scene it's moved to if the objects are within applicable masks when the camera is repositioned? OR, would the object be ignored if it fell outside of any of the `required_zones` zones, which were set for the default scene and not this repositioned scene?

If so, would it make sense to add the ability for object masks and zones to be context aware, i.e. integrating zone logic with ONVIF (if enabled for a particular camera) and allowing masks/zones to only apply if the camera is residing at a specific preset?

This might appear to be too much of a niche usecase, but it seems that it could prevent autotracking from working well in any case where the PTZ is moved off of the default intended scene.

**Comment by NickM-27** [comment]
It wasn't originally geared towards this but I think https://github.com/blakeblackshear/frigate/issues/3621 serves as a good issue to track this and its original idea. I'd recommend leaving a 👍 and additional comments if you would like on that issue
