### ISSUE TITLE
Garbage Bin Model 

### ISSUE THREAD

**Issue by thinkjk** [blakeblackshear/frigate#10656]
Hello,

I would love it if Frigate would be able to detect garbage bins! This would help with automation related to taking the garbage in and our as well we theft of garbage bins. Similar to this image:  
![garbage_bins](https://github.com/blakeblackshear/frigate/assets/8870252/f17481f9-1044-4fd0-b1ee-d68193541e31)

I'm happy to label with my Frigate+ subscription.

Thank you!

**Comment by NickM-27** [comment]
The default model is based on the COCO dataset so labels can not be added. Frigate+ label requests should go to the Frigate+ discussion
