### ISSUE TITLE
coral pci not working

### ISSUE THREAD

**Issue by tung256** [blakeblackshear/frigate#1066]
i bought this chip https://www.amazon.com/SOM-System-Modules-Accelerator-Integrate/dp/B0844WRL58/
inserted into my laptop that is running HomeAssistant OS(NUC img).
my frigate.yml file has this:
detectors:
  coral:
    type: edgetpu
    device: pci

strangely, Frigate error log shows: No EdgeTPU detected.
what went wrong?

**Comment by HITChris** [comment]
https://coral.ai/docs/m2/get-started/

**Comment by nayneyT** [comment]
> Look at the instructions for the device you purchased. I believe it requires kernel drivers that are not included in HassOS.

I believe the author of Frigate is correct. Although we should be able to recompile the kernel using buildbase with the apex/gasket/staging drivers included in the kernel or as external .ko modules. I don't run HA OS but it is on my list of things to try and get coral devices to work on.

**Comment by nayneyT** [comment]
A good place to start will be here https://github.com/home-assistant/operating-system/pull/1263/commits/67b3ce408600102083e2b1c0e802f204cc11f600

**Comment by nayneyT** [comment]
![Screenshot_20210508-082002](https://user-images.githubusercontent.com/37027153/117530664-4b880680-afd6-11eb-97a6-6d76f499ceaa.jpg)

It looks like it's included in the Dev branch. Somebody has already pulled and HA have accepted the changes.

**Comment by tung256** [comment]
> h

thank you so much! i will try the latest dev img. recompiling it myself is out of my pay grade

**Comment by nayneyT** [comment]
I can confirm that the driver is now present in v6.0rc1 of HAOS https://www.reddit.com/r/Proxmox/comments/n7nfem/proxmox_hassos_frigate_google_coral_tpu/

**Comment by tung256** [comment]
hello. what's the command to update within HassOS terminal?
im using OS 5.13 now. no option to update to OS 6 in the gui.
in terminal, i tried this command but it does not work: 
ha core update --version=6.0.rc1

**Comment by nayneyT** [comment]
To update to the latest core you'd need to do the following:

`ha core update --version 2021.5.1`

but you'll still be on OS Version 5.13

You will need to join the dev branch to update to Release Candidate (RC). https://www.home-assistant.io/common-tasks/os/#update

Join the dev channel

`ha supervisor options --channel dev`

Reload the supervisor

`ha supervisor reload`

Update Home Assistant core to the latest dev version

`ha core update`

I don't know if joining the dev-branch will update the latest OS version.

All the usual disclaimers - this is bleeding-edge code blah blah blah

Take a backup of your configuration first and you'll be fine.

I will install it on a VM now and get back to you

Regards,
nayneyT

**Comment by nayneyT** [comment]
I don't use HAOS but here I my findings:

Starting with OS 5.13
Home Assistant Core 2021.5.1

ha supervisor options --channel dev
ha supervisor reload
ha os update

Home Assistant will reboot.

Following restart HAOS will be as follows:

OS Version: Home Assistant OS 6.0.dev20210504
Home Assistant Core: 2021.5.1

![image](https://user-images.githubusercontent.com/37027153/117544920-f78f1900-aff9-11eb-8d03-d6c9b887d6cc.png)

Drivers are available as shown in the screenshot above

**Comment by tung256** [comment]
error:error raise form OTA webserver: 404

guess the website is down?  will try again in 1 hour.  thanks!

**Comment by nayneyT** [comment]
Once you've completed the second command (after switching to dev channel and restarting the Supervisor) you can switch back to the GUI and complete the update if you prefer.

![image](https://user-images.githubusercontent.com/37027153/117567163-2efcd480-b091-11eb-8fe4-33219adede4a.png)

Click to Update the Operating System

In the system logs (scroll to the bottom of the log) and you should see it completing the download and completing the upgrade e.g.

`21-05-09 09:39:18 INFO (MainThread) [supervisor.hassos] Fetch OTA update from https://os-builds.home-assistant.io/6.0.dev20210504/haos_ova-6.0.dev20210504.raucb
`

You will lose connection for a while but after a couple of minutes you'll see the new version

![image](https://user-images.githubusercontent.com/37027153/117567273-e5f95000-b091-11eb-8ca3-c4c95fc2d221.png)


I'm guessing the server was down when you completed the update but the URL is shown above so you could test by visiting in a browser.

Regards,

nayneyT

**Comment by tung256** [comment]
still have error. will try again later
![image](https://user-images.githubusercontent.com/37672036/117572922-2b724900-b0a3-11eb-9f02-1d77471aa112.png)

**Comment by tung256** [comment]
once someone on the team from HA renamed a file as seen here, i was able to update!
![image](https://user-images.githubusercontent.com/37672036/117650949-54581400-b15f-11eb-9091-42ada8c64d76.png)


i am happy to say TPU fully detected in the PCI slot now in OS 6. awesome. thanks for your time patience too!
![image](https://user-images.githubusercontent.com/37672036/117651074-81a4c200-b15f-11eb-8d4d-1db69a167367.png)

**Comment by nayneyT** [comment]
Awesome. Its often not what, but who you know. Ask the right questions to the right people and things get resolved.

Great perseverance from yourself in getting your issue resolved. Enjoy Frigate and HAOS v6.0.

**Comment by jdesai61** [comment]
With the latest OS release supporting coral, I have this working on my Intel NUC with M2.E PCI card. However, OI noticed that the following warning 

```
frigate.app                    INFO    : Camera processor started for patio: 41
frigate.app                    INFO    : Camera processor started for backyard: 42
detector.coral_pci             INFO    : Starting detection process: 38
frigate.edgetpu                INFO    : Attempting to load TPU as pci
frigate.app                    INFO    : Capture process started for patio: 43
frigate.app                    INFO    : Capture process started for backyard: 45
W :131] Could not set performance expectation : 40 (Inappropriate ioctl for device)
frigate.edgetpu                INFO    : TPU found
```
I have also noticed that inference time has gone from 6+msec (running on same HW with a separate ubuntu VM in PROXMOX) to 18+msec (with hassos supervisor-2021.06.3 and PROXMOX)
