### ISSUE TITLE
System freeze

### ISSUE THREAD

**Issue by aurany** [blakeblackshear/frigate#107]
When using the 0.5.0-rc<1-3>, with the Coral USB plugged in, my computer "freezes". I'm not sure exactly what happens but the SSH connection to my headless Ubuntu server dies and i am not able to reconnect. A reboot is necessary. The logfiles doesn't help me (docker logs / syslog / kern.log). When using the same image without the Coral USB (=CPU version) the computer doesn't freeze, frigate is running but the object detection is not working.

The 0.4.0-beta is working fine.

Ubuntu server 18.04.4 LTS
HFX PowerNAS 2011 (i3, 4gb RAM)
Coral USB

3 cameras (5 fps, 1280*720), 4 regions in total

**Comment by blakeblackshear** [comment]
Can you try going through the getting started guide from the coral docs to see if this issue is specific to frigate?

**Comment by aurany** [comment]
I went through the guide again (last time was about a year ago) and as you might expect - it hangs! I’m not sure what they have changed and sadly it appears to be hard to debug :(

This is not a frigate problem.

**Comment by Tuckie** [comment]
I realize that this is closed, but have you tried a different usb port or over a powered hub? Maybe your box is having problems powering the coral over usb?

**Comment by aurany** [comment]
> I realize that this is closed, but have you tried a different usb port or over a powered hub? Maybe your box is having problems powering the coral over usb?

I don’t think it should be necessary because everything is working pretty fine when using the beta4. I’ve had some problems with the beta4 also (accelerator USB ”lost”/blocked after a couple of days) and I have tried a powered hub to solve this with no success. I have tried all USB ports also.

**Comment by aurany** [comment]
Update: USB Accelerator works fine when using the Edge TPU Python API but not tflite API.

**Comment by zewelor** [comment]
Can confirm exact same issue, rpi4 with coral results in ssh hang. @aurany I've installed monit, maybe it could help in future to auto restart ssh, in case of freeze.

**Comment by aurany** [comment]
> Can confirm exact same issue, rpi4 with coral results in ssh hang. @aurany I've installed monit, maybe it could help in future to auto restart ssh, in case of freeze.

Does it work if you connect the USB Accelerator to a USB2-port? For some reason the USB Accelerator and tflite API combo only works on USB2 (on my system). I will try to replace the standard cable and see if that helps.

**Comment by zewelor** [comment]
I only tested usb3. My rpi with coral is 200km away from me, so can't test now. Will be able in few months, but then it will be solved already I hope. If its not working on USB3, do you have latest rpi VLI firmware ? Also I got usb drive connected, to usb2, and had to turn on some usb quirks, for rpi4, to make it work. Maybe something with this ?

**Comment by hawkeye217** [comment]
@aurany I'm having the same issue as you with any of the 0.5.0-rc's and later.  My 0.4.0-beta Docker image still works great but 0.5.x hangs the system at a future time (in my observation usually between 1-3 days after it's started) with nothing visible in the logs to indicate a problem.

Were you able to ever find a fix?

**Comment by aurany** [comment]
> @aurany I'm having the same issue as you with any of the 0.5.0-rc's and later. My 0.4.0-beta Docker image still works great but 0.5.x hangs the system at a future time (in my observation usually between 1-3 days after it's started) with nothing visible in the logs to indicate a problem.
> 
> Were you able to ever find a fix?

No, I use USB2. I think the problem is related to the tflite API or maybe a combination of tflite/hardware. I think Frigate moved from the Python API to tflite between 0.4 and 0.5. Frigate is working fine for me on USB2 with 3 cameras. The only issue I have is that the queue sometimes explode. Therefore I monitor the queue length in HA and run "docker restart frigate" when the queue length > 100 for > 1 minute.

**Comment by hawkeye217** [comment]
Makes sense. I have my Coral plugged into a USB3 port, I could try 0.5.x on a USB2 port.

@blakeblackshear Did you move to tflite with 0.5.x as @aurany said?  Looks more and more to be a Google issue rather than a Frigate one.

**Comment by blakeblackshear** [comment]
It was required in order to support CPU-only in addition to the Coral. 0.5.x was nearly a complete rewrite, so it's hard to say if it's a Google issue. Next time it freezes up with 0.5.1 make sure you check the logs. I am already handling the scenario where tflite freezes up.

**Comment by hawkeye217** [comment]
Alright, thanks @blakeblackshear. I'll pull 0.5.1 right now and plug my Coral back into USB3. I'll open a new issue if I have anything in the logs when it freezes.

**Comment by hawkeye217** [comment]
Well, it had been a while (over 2 weeks!) since a system freeze and I had hoped that 0.5.1 had fixed it.  But alas, last night around 4:30am the entire system froze and I woke up to the Coral fast blinking again as it has in the past.  There is absolutely nothing in the logs - the timestamps show a reconnect with the camera at 11:28pm (which was expected because of an automation that runs in Home Assistant) and then the reboot of the system at 7:26am.  

```
2020-06-19 23:28:14.41922724 ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -use_wallclock_as_timestamps 1 -i rtsp://mycam/rtsp -f rawvideo -pix_fmt rgb24 pipe:
2020-06-20 07:26:16.03354194 On connect called
2020-06-20 07:26:17.04493689 ffprobe -v panic -show_error -show_streams -of json "rtsp://mycam/rtsp"
```

I've rebooted and now I've plugged the Coral into a USB2 port on the machine to see if that affects anything.  If it still ends up freezing on USB2, I may just got back to 0.4.0-beta, which I had running for months without issue.  

Definitely seems more like a Google issue, @blakeblackshear.  Frigate didn't seem to know anything about what happened.

**Comment by hawkeye217** [comment]
So it's been over 3 weeks on the same configuration but with the Coral plugged into USB2, and there's been no system freezing.  Other than inference times being better on USB3 (~8ms) compared to USB2 (~25ms), I noticed no differences.  

I'm going to plug back into USB3 for a while to see if I can get any kind of error at all, if it freezes again.

**Comment by blakeblackshear** [comment]
I have seen some issues in other places related to power usage. The Coral will draw more power when it is running faster over USB3. Do you have other USB devices plugged in that would draw power too? I think it needs 600mA and some motherboards have issues with high power draw. You could also try a powered USB hub.

**Comment by hawkeye217** [comment]
Interesting, and that makes sense.  The machine is an older Dell Optiplex i5.  I have a few things plugged into the other USB ports - a mouse, a Bluetooth dongle, and an RTL-SDR dongle.  Might be worth trying a powered USB hub... Though all worked well for months on USB3 and 0.4.0-beta.

**Comment by blakeblackshear** [comment]
0.4.0 would have topped out a a much lower FPS. 0.5.0 was a complete rewrite to use multiple processes.
