### ISSUE TITLE
Frigate Plus - Multiselect Images to "Send to Frigate+"

### ISSUE THREAD

**Issue by cslipaco** [blakeblackshear/frigate#10706]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to multiselect images to "Send to Frigate+" so that I can mass report images as either a false positive together (Not an objectType) OR as the correct objectType and send to Frigate+ at once.

**Describe the solution you'd like**
I would like to be able to have the multiselect option, then when I have items selected, I would have two options to bulk report and send to Frigate+ - either "This is not the correct object type." or "This is the correct object type."

This way you could optimize the process to better train models in a more efficient manner.

**Describe alternatives you've considered**
An alternative would be - after submitting an image to Frigate+ (click on Send to Frigate+, then choose whether false positive or not, then click the Close button before it is finished uploading) and then click the "Send to Frigate+" button for the next image, once the previous image has uploaded, it will close the modal for the current image you were trying to send to Frigate+.  This makes the process tedious when trying to be quick.

**Comment by NickM-27** [comment]
The UI is currently being rewritten to make the reporting faster and more streamlined. I don't think reporting groups is optimal as it will greatly increase the risk of reporting incorrectly if the image does not show up large. I believe the improvements to speed up the flow should satisfy this request.

**Comment by cslipaco** [comment]
> The UI is currently being rewritten to make the reporting faster and more streamlined. I don't think reporting groups is optimal as it will greatly increase the risk of reporting incorrectly if the image does not show up large. I believe the improvements to speed up the flow should satisfy this request.

Thanks for letting me know!  I did consider that it would potentially increase the chance of false reports; however, I if I am not mistaken (and I most certainly might be) - the process is not complete until you verify in Frigate+ and choose to teach the model that it is not the correct object type, was the correct object type, add more objects, etc.?  I was just trying to think of a faster way to get them to Frigate+.  The onus would still be on the individual reporting images to try to be as accurate as possible.

But if the UI is being rewritten, I am super excited for this!  Thanks so much to everyone working so diligently on this project!!!
