### ISSUE TITLE
Frigate+ doesn't produce tensorrt models

### ISSUE THREAD

**Issue by robby-d** [blakeblackshear/frigate#10721]
Hello, I have an existing frigate `tensorrt` install powered by an NVIDIA RTX A2000. Object recognition works fine using the standard YOLO models. I signed up for Frigate+, uploaded and classified a several hundred images, and built a custom model. Looking at the available models page from this training, I only see an `edgetpu` and `cpu` models, and nothing available for `tensorrt`. I can imagine this is because the `tensorrt` models need to be compiled for the correct GPU architecture, etc. Are there any plans to make these images available, or allow me to compile the correct `tensorrt` image myself? As it currently is, I've paid for and sunk around 4 hours into a product I can't use. 

I've looked at the documentation I can find and the existing issues and don't see any mention of this...maybe I missed something. Happy to be a tensorrt beta tester if that's needed. Thanks!

**Comment by NickM-27** [comment]
The main Frigate+ page on the docs covers this https://docs.frigate.video/plus/
![Screen Shot 2024-03-28 at 06 58 52 AM](https://github.com/blakeblackshear/frigate/assets/14866235/d7ccc4cd-3c62-4d88-b709-d4987aca9ec6)

You can see on the roadmap that tensorrt support will come later. Issues here are not a place to request features for Frigate+

**Comment by robby-d** [comment]
apologies, not sure how I could have missed that. I'll sit tight on this.
