### ISSUE TITLE
Modify the logo icon so the Add-Ons page can indicate activity

### ISSUE THREAD

**Issue by fouram** [blakeblackshear/frigate#10725]
I want to be able to tell at a glance on the Add-Ons page if Frigate is running. I current cannot do this because the logo is black and white.

A splash of color perhaps? Blue background? anything to prevent the icon from being fully grayscale and looking exactly the same when Frigate is running and is not.

Here is an example of Frigate when it is not running:
![image](https://github.com/blakeblackshear/frigate/assets/533951/a6343186-32d0-4858-91b5-2251104af6a6)
Just kidding, it's running just fine

I've also considered asking HASS devs to put a little activity indicator in the corner of the cards on this page to display Add-On status, that way no one has to compromise their branding to work around this problem. But as that is a more complex solution, I thought I'd also make this recommendation first.

**Comment by fouram** [comment]
I should mention: Nothing but love for a fantastic add-on, best DVR I've used and I've tried em all (well most)

**Comment by NickM-27** [comment]
This is not a request for frigate, but a request for the addon https://github.com/blakeblackshear/frigate-hass-addons
