### ISSUE TITLE
Frigate Web UI Fails To Start on Dev Container

### ISSUE THREAD

**Issue by mitchross** [blakeblackshear/frigate#1076]
**Describe the bug**
When pulling down Frigate v9 into the docker dev container and running npm install && npm start, the web application crashes.
**Version of frigate**
v0.9

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Frigate container logs**
```
snowpack

  http://localhost:8080 • http://172.19.0.3:8080
  Server started in 34ms.

▼ Console

[snowpack] Error: The service was stopped
[@snowpack/plugin-esbuild] [500] /dist/index.js
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6330506/117751201-af7f1a80-b1e2-11eb-9e2b-207cc6418238.png)

**Computer Hardware**
 - OS:Windows 10 and MacOS

**Comment by hunterjm** [comment]
Different OS, but that doesn’t matter. What is the output in the vscode terminal window you tried to start in?

**Comment by hunterjm** [comment]
Do you have the backend currently running in a different terminal?

**Comment by hunterjm** [comment]
@mitchross - If you had run `npm install` previously outside the container, try deleting `node_modules` and installing from scratch inside the container.

**Comment by mitchross** [comment]
> @mitchross - If you had run `npm install` previously outside the container, try deleting `node_modules` and installing from scratch inside the container.

@hunterjm Bingo! This is the trick... I wonder if docker file / compose could check and delete this before running? Not a docker expert but seems like it should be able to remove if its there. Otherwise have to caveat it in the install notes. Thanks for the help!
