### ISSUE TITLE
Can Frigate Trigger Events Based on Specific Image Content Percentages?

### ISSUE THREAD

**Issue by dan246** [blakeblackshear/frigate#10766]
Is it possible for Frigate to trigger events based on the percentage of an image occupied by a specific element? For instance, can it be configured to only send events if smoke occupies more than 30% of the visual frame? If this functionality exists, how can one implement it? Can such adjustments be made solely through configuration changes? Thanks for any insights or guidance on this matter.

**Comment by moskovskiy82** [comment]
There is min and max_area already in the config file. Just do a simple math and calculate the min_area in pixels :)

**Comment by dan246** [comment]
> 設定檔中已經有 min 和 max_area 。只需做一個簡單的數學計算併計算最小面積（以像素為單位）:)

I'm looking to create an API that can track events, for example, only sending a notification if there's 30% smoke in the camera view for over five seconds. Calculating the area seems a bit complicated since each camera might track different labels and the area occupied can vary (with each additional label requiring a new calculation for min_area and max_area). Also, can the duration a label appears be configured in the settings? Currently, I'm capturing timestamps through the code and am looking for a more convenient approach.

**Comment by moskovskiy82** [comment]
> > 設定檔中已經有 min 和 max_area 。只需做一個簡單的數學計算併計算最小面積（以像素為單位）:)
> 
> I'm looking to create an API that can track events, for example, only sending a notification if there's 30% smoke in the camera view for over five seconds. Calculating the area seems a bit complicated since each camera might track different labels and the area occupied can vary (with each additional label requiring a new calculation for min_area and max_area). Also, can the duration a label appears be configured in the settings? Currently, I'm capturing timestamps through the code and am looking for a more convenient approach.

Check out frigate docs on MQTT - time calculation can be easily taken from them.
Sorry but looks kinda funny - you are writing an API to track events. The creator of frigate already gave you all the instruments but you don't want to do any calculations yourself and want a more convenient approach? Sound more like a Pull request shall be done ) No offense )
