### ISSUE TITLE
Frigate Crashes After Latest HA Upgrade to 2024.4

### ISSUE THREAD

**Issue by b24home** [blakeblackshear/frigate#10828]
**Describe what you are trying to accomplish and why in non technical terms**
Frigate is crashing.  Logs here: https://pastebin.com/naZehzA0

**Describe the solution you'd like**
Frigate running smoothly.

**Describe alternatives you've considered**
Restarted and rebooted. 

**Additional context**
Was working fine until the upgrade. Nothing has changed except that upgrade.

**Comment by b24home** [comment]
Extra logs from Core:

This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:259
integration: Frigate (documentation, issues)
First occurred: 12:00:26 PM (53 occurrences)
Last logged: 12:12:20 PM

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name has no usable address]
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.3', 5000)]
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')

This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:244
integration: Frigate (documentation, issues)
First occurred: 12:08:22 PM (3 occurrences)
Last logged: 12:08:52 PM

Timeout error fetching information from http://ccab4aaf-frigate:5000/api/stats:

This error originated from a custom integration.

Logger: custom_components.frigate
Source: helpers/update_coordinator.py:347
integration: Frigate (documentation, issues)
First occurred: 12:01:07 PM (11 occurrences)
Last logged: 12:08:02 PM

Error fetching frigate data:

**Comment by NickM-27** [comment]
this is not a feature request. You should make a support issue
