### ISSUE TITLE
Support 24-Hour Time Format in Export Feature

### ISSUE THREAD

**Issue by FusselTV** [blakeblackshear/frigate#10859]
### Goal
Align the export feature's time format with the UI time_format setting, enabling 24-hour format support to match user preferences and improve usability.

### Desired Solution
Modify the export feature to recognize and adhere to the UI's time_format setting, allowing exports to reflect either a 12-hour or 24-hour time format based on user configuration. (browser setting)

### Alternatives Considered
Users manually converting time from 12-hour to 24-hour format post-export, though this approach is error-prone and inconvenient.

### Additional Context
Current export functionality is limited to AM/PM format, which can lead to confusion or extra steps for users accustomed to a 24-hour clock.

**Comment by NickM-27** [comment]
Frigate is currently undergoing a UI rewrite and as part of that the export feature adheres to the 24 hour time configuration https://github.com/blakeblackshear/frigate/commit/5b5606cb8a5013c8c329e27367071a48adf3ebc6
