### ISSUE TITLE
SQLite WAL files periodic truncate

### ISSUE THREAD

**Issue by mnaiman** [blakeblackshear/frigate#10862]
**Describe what you are trying to accomplish and why in non technical terms**
I have one instance, which has 3mil records in recordings table, rotating recordings based on free space.
After several days/weeks, database file has 1GB (fine) and WAL grows to 14GB (no reason)

**Describe the solution you'd like**
Periodic (hourly?, daily?) run - VACUUM; PRAGMA wal_checkpoint(TRUNCATE);
WAL is after that zero.

**Comment by mnaiman** [comment]
BTW: restart of container (app) does the same job with truncating WAL, but I dont want to restart regularly security solution.

**Comment by NickM-27** [comment]
It should be handled automatically https://www.sqlite.org/compile.html#default_wal_autocheckpoint

**Comment by mnaiman** [comment]
Maybe it should be handled, but it is obviously not handled :)
5 hours ago I truncated m WAL from 14GB to 0, now it is back 0,5GB.
I have 12 cameras with continuous recording, this is why its generate to db those 3mil records.

**Comment by NickM-27** [comment]
Will have to check what the default peewee config is

**Comment by mnaiman** [comment]
After reading docs - maybe data is moved from wal to db file, but wal itself is not truncated.
https://www.sqlite.org/c3ref/wal_checkpoint_v2.html
Yes questions is what is default checkpoint action.

**Comment by NickM-27** [comment]
The WAL isn't truncated but it is instead written over so it still shouldn't increase in size past a few MB. Based on section 6 it seems that the issue here is that Frigate has many concurrent readers and writers thus the auto checkpoint will not be run.

**Comment by lhcl** [comment]
Great to see this coming: my WAL file is currently 14GB.  I have 14 cameras enabled.

**Comment by gilesm2** [comment]
Great to see this coming: my WAL file is currently 14GB. I have 14 cameras enabled.
