### ISSUE TITLE
Add inked out area in live view and recordings

### ISSUE THREAD

**Issue by alve89** [blakeblackshear/frigate#10930]
**Describe what you are trying to accomplish and why in non technical terms**
Due to legal regulations (in Germany, may be also in the whole EU and in other countries) you're not allowed to film public areas. Even if you're not recording the specific area, passers-by can complain about they could have been filmed.
So it would be great if you can specify areas (like the motion masks) which are inked out completely (both in stream and in recording).

**Describe the solution you'd like**
The debug stream displays the following after adding a motion mask (the left black area is the timestamp, the right one is the public area):
![image](https://github.com/blakeblackshear/frigate/assets/11487054/606b8d6b-223a-4b92-807b-9e8d56f4c0db)

Why not adding such black areas statically in the streams and the recordings?

**Describe alternatives you've considered**
I thought this could be managed directly within the cameras UI but it can't.

**Additional context**
As conclusion: Public areas should be able to be masked and can't be seen anywhere afterwards.

**Comment by NickM-27** [comment]
You can already do this via ffmpeg output args, but it requires re-encoding the stream which is cpu and GPU intensive so in general is not recommended

In general, it is recommended to just buy cameras that support this directly.
