### ISSUE TITLE
Netatmo Presence Stream: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures

### ISSUE THREAD

**Issue by Dreamoffice** [blakeblackshear/frigate#1094]
**Describe the bug**
A clear and concise description of what your issue is.
I'm running the Home Assistant integration and i would like to usw the
watchdog.back                  INFO    : Terminating the existing ffmpeg process...
watchdog.back                  INFO    : Waiting for ffmpeg to exit gracefully...
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
ffmpeg.back.detect             ERROR   : Option stimeout not found.
ffmpeg.back.clips_record       ERROR   : Option stimeout not found.

**Version of frigate**
Output from `/api/version`
Current version: 1.13
**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: 192.168.1.43
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

cameras:
  back:
    ffmpeg:
      inputs:
        - path: http://192.168.1.105/++++++++netatmo-ID++++++++/live/files/medium/index.m3u8
          roles:
            - detect
            - rtmp
        - path: http://192.168.1.105/++++++++netatmo-ID++++++++/live/files/high/index.m3u8
          roles:
            - clips
            - record
    width: 1280
    height: 720
    fps: 5
```

**Frigate container logs**
```
{
  "cameras": {
    "back": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": false,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i http://192.168.1.105/++++++++netatmo-ID++++++++/live/files/medium/index.m3u8 -c copy -f flv rtmp://127.0.0.1/live/back -r 5 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i http://192.168.1.105/++++++++netatmo-ID++++++++/live/files/high/index.m3u8 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/back-%Y%m%d%H%M%S.mp4",
          "roles": [
            "clips",
            "record"
          ]
        }
      ],
      "fps": 5,
      "frame_shape": [
        720,
        1280
      ],
      "height": 720,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 120,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "back",
      "objects": {
        "filters": {
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": null,
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": false,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "width": 1280,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.43",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "user"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
<img width="765" alt="Bildschirmfoto 2021-05-13 um 13 58 44" src="https://user-images.githubusercontent.com/35889916/118122783-99947400-b3f3-11eb-9f41-abba1e2c2827.png">

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows] Home assistant newest Version
 - Install method: [e.g. Addon, Docker Compose, Docker Command] Home Assistant Add-on
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None] Coral Stick
 - Network Setup: [e.g. Wired, WiFi] Wired

**Camera Info:**
 - Manufacturer: [e.g. Dahua] Netamo
 - Model: [e.g. IPC-HDW5231R-ZE] Presence
 - Resolution: [e.g. 720p] 1080p
 - FPS: [e.g. 5]

**Additional context**

**Comment by blakeblackshear** [comment]
You will need to modify your ffmpeg parameters because these appear to be HLS streams rather than standard rtsp feeds. Can you provide info about your streams frrom ffprobe and or VLC?

**Comment by Dreamoffice** [comment]
how can i get these informations?

**Comment by Dreamoffice** [comment]
<img width="505" alt="Bildschirmfoto 2021-05-13 um 14 16 13" src="https://user-images.githubusercontent.com/35889916/118124379-c9dd1200-b3f5-11eb-854e-47aef76894b2.png">

**Comment by Dreamoffice** [comment]
<img width="507" alt="Bildschirmfoto 2021-05-13 um 14 17 23" src="https://user-images.githubusercontent.com/35889916/118124492-f2fda280-b3f5-11eb-88d7-de1f3be7b71c.png">

**Comment by Dreamoffice** [comment]
i entered 
`cameras:
  back:
    ffmpeg:
      inputs:
        - path: http://192.168.1.105/netatmo-id/live/files/high/index.m3u8
          roles:
            - detect
            - rtmp
            - clips
            - record
          input_args :
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -strict
            - experimental
            - -fflags
            - +genpts+discardcorrupt
            - -use_wallclock_as_timestamps
            - '1'


    width: 1920
    height: 1280
    fps: 5`

now i have a colorful picture.
<img width="722" alt="Bildschirmfoto 2021-05-13 um 15 51 46" src="https://user-images.githubusercontent.com/35889916/118135431-4d513000-b403-11eb-867d-f33c582cb0c0.png">

**Comment by blakeblackshear** [comment]
Your width and height need to match the resolution of your camera feed.

**Comment by Dreamoffice** [comment]
Now it is running. the resolution was wrong. these are the correct ones
`width: 1920
height: 1080
fps: 5``

**Comment by WanderingStar** [comment]
This was really confusing to me because of the formatting. I think the way to do this is with a single line:
```
  input_args: -avoid_negative_ts  make_zero  -fflags  nobuffer  -flags  low_delay  -strict  experimental  -fflags  +genpts+discardcorrupt  -use_wallclock_as_timestamps  '1'
```
But somehow the yaml and markdown got confused. The single line works for me.
