### ISSUE TITLE
Camera grouping for Birdseye

### ISSUE THREAD

**Issue by neutralvibes** [blakeblackshear/frigate#10987]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to assign cameras to one or more groups. This would facilitate an overview of cameras for particular areas, such as internal, external, etc... via birdseye view

**Describe the solution you'd like**
I imagine an example configuration would be as follows:-

~~~yml
cameras:
  frontgate1: ...etc
    ffmpeg:
    groups: external
  backview1: # ...etc
    ffmpeg:
    groups: external
  playfields1:
    ffmpeg:
    groups: external
  class1a: 
    ffmpeg:
    groups: classrooms
  class2b: 
    ffmpeg:
    groups: classrooms
  poolview1: 
    ffmpeg:
    groups: swim
  poolview2: 
    ffmpeg:
    groups: swim
  poolview3: 
    ffmpeg:
    groups: 
      - swim
      - external

~~~

 In birdseye view the group may perhaps be selected via a dropdown box with the **all** option as a default, or maybe from the sidebar. This would facilitate a more sophisticated multi-monitor view if desired or simply a more targeted view of the areas of interest. Everything else would work the same way, just the cameras viewable would be filtered if/when required. It may be preferable to add the group field directly to the birdseye dict for reasons I am unaware of. I think the ability to group cameras may offer benefits far beyond this particular request in the future should it be adopted, unless I just drunk to much tequila while thinking about this, which is not uncommon I should add.

**Describe alternatives you've considered**
Multiple frigate instances is an overkill and would not offer future flexibility.

**Additional context**

**Comment by NickM-27** [comment]
this is already support as part of the UI for frigate 0.14
