### ISSUE TITLE
Add sanity check for Frigate Config related to referenced zone names

### ISSUE THREAD

**Issue by moandcompany** [blakeblackshear/frigate#11014]
I would like for Frigate's automatic configuration check to apply a sanity check to referenced `zone` names in camera configuration definitions when the `required_zones` condition is used.
- When a zone name is referenced in `required_zones` for a given camera definition, but the zone name used has not been defined for that camera, the configuration sanity check should reject the configuration as erroneous due to an invalid/undefined zone reference.
- Extra Credit related to zone definitions in general:  It would also be useful to have the configuration sanity checker reject zone definitions that are invalid or out-of-bounds for a given camera's detect stream resolution/dimensions.

Context:  (Frigate 0.13.2) I had made a configuration change to an active system where I removed a camera's zone definition, that was previously referenced in `required_zones` and discovered a week+ later that no events were recorded on that camera due to Frigate (technically correctly/working as intended) discarding otherwise detected events due to the lack of positive zone condition match.

**Comment by NickM-27** [comment]
Worth mentioning that as part of the new UI required_zones field is all set in the UI so this is likely not much of a problem, but I agree it makes sense that frigate would throw an error if it was configured this way.

> It would also be useful to have the configuration sanity checker reject zone definitions that are invalid or out-of-bounds for a given camera's detect stream resolution/dimensions.

this isn't really relevant now that all zone coordinates are stored in relative form not absolute resolution form
