### ISSUE TITLE
Add "truck" object type to Frigate+ models

### ISSUE THREAD

**Issue by gunnaraas** [blakeblackshear/frigate#11013]
**Describe what you are trying to accomplish and why in non technical terms**
My project's use case requires distinguishing between personal cars & commercial vehicles (semis, box trucks). I am seeking to use computer vision & image recognition to detect prohibited freight trucks that use a local residential street as a shortcut between industrial & railyard area and a local highway, and to log time & date, image, and other details (I believe it should be possible to capture license plate number, DOT number, company name or logo - if visible in the video, correct?). 

It would be helpful if the Frigate+ models distinguished between personal cars, which are allowed on this street, and freight trucks - which are banned. 

**Describe the solution you'd like**
Addition of new object label type to Frigate+ 

**Describe alternatives you've considered**
I'm still in the exploratory stages of this project, am open to alternatives or recommendations for the best way to accomplish this task.

**Comment by NickM-27** [comment]
this is not the correct place to request features for Frigate+, the Frigate+ discussion should be used for this
