### ISSUE TITLE
fullscreen on recording page not working on ios

### ISSUE THREAD

**Issue by ivanjx** [blakeblackshear/frigate#11089]
**Describe what you are trying to accomplish and why in non technical terms**
on ios i cant make the recording page video element to go full screen either by turning the phone to landscape mode or manually clicking the full screen icon. pip button is working normal though.
full screen works fine on the events page.

**Describe the solution you'd like**
be able to view the video in full screen on the recording page.

**Describe alternatives you've considered**

**Additional context**
iOS 17.4.1

**Comment by NickM-27** [comment]
This is already fixed in the new ui
