### ISSUE TITLE
Recording Function - Certain Time

### ISSUE THREAD

**Issue by topa-LE** [blakeblackshear/frigate#11105]
Hello, thank you very much for the NVR. However, I miss the option of only activating the recording function at certain times. For example, I would like to use a time window from **01:00 to 06:00** in the morning.

https://docs.frigate.video/configuration/record/#configuring-recording

Thank you very much! Best Regards

**Comment by NickM-27** [comment]
This can be done using mqtt or the API, for example using home assistant integration or node red. This allows direct control vs Frigate building in options for this
