### ISSUE TITLE
Smooth timelapse, not just motion.

### ISSUE THREAD

**Issue by awisur** [blakeblackshear/frigate#11112]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to export a full day's timelapse regardless of motion.

**Describe the solution you'd like**
I would like to export a timelapse for a period regardless of motion, so I could get a smooth run of the day, and not stuttering skipping hours without motion. Also I would like a dropdown to override the length of the timelapse, of how long you want 1 hour to be playedback as. e.g. 24 hour = 1 hour etc.

**Describe alternatives you've considered**
A separate program/docker to take a snapshot of the stream and create a timelapse that way, seems cumbersome.

**Comment by NickM-27** [comment]
this is already possible in the next version of frigate using the previews and timeline scrubbing, previews could also support exporting
