### ISSUE TITLE
Delete / Archive Frigate+ models

### ISSUE THREAD

**Issue by pseudoacacia** [blakeblackshear/frigate#11111]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to hide or delete unused Frigate+ models so that I can more easily identify the current model(s).

**Describe the solution you'd like**

My list of trained Frigate+ models is getting very long (especially with both a CPU and EdgeTPU version for each training). I would like a method to select older or otherwise unused items from the list to be deleted or moved to a separate list / page. While I appreciate the ability to access older models, the page is getting cluttered and I know that most of the models listed are never going to be used by me again. It's a minor thing, but would appreciate some cleanup mechanism even if it's just aesthetic.

**Describe alternatives you've considered**

* Most recent model being highlighted separate from the list.
* Models being hidden behind expanding headers for each base model or creation year or target detector types.
* Models table having sort/filter headings that remember user preferences.
* Number of models retained being limited to a small number (e.g., only three most recent).

**Comment by NickM-27** [comment]
Requests for the Frigate+ dashboard should be made on the Frigate+ discussion
