### ISSUE TITLE
Multiple birdeye streams

### ISSUE THREAD

**Issue by markfrancisonly** [blakeblackshear/frigate#11114]
I use Home Assistant to view to all my live camera Frigate feeds on various devices, Android tablets, iPhones, and Windows desktops, etc. Recently, I've started recording the Frigate birdseye (re)stream as well. My birdseye setup consolidates feeds from around 20 cameras, providing the capability to watch multiple cameras simultaneously at specific times of interest. However, its fixed orientation view (landscape) is not ideal for some devices or situations.

Requesting an enhancement to Frigate's functionality to allow the creation of multiple birdseye view streams: This would enable custom composite streams via a single WebRTC connection, addressing issues with multiple concurrent webrtc connections. The ability to define multiple birdeyes views could be used to support different device orientations (landscape and portrait), different screen resolutions, and differing multi-cam views on low-resource wireless devices that have difficulty maintaining multiple connections, and reassembling multiple full-resolution cameras feeds into a composite. 

This request might be implemented with camera groups e.g. [issue #10987](https://github.com/blakeblackshear/frigate/issues/10987).  Since I'm running my frigate solution on modern hardware, I’d like to take advantage of my system resources and would appreciate the flexibility to record and live stream multiple birdseye views independent of the frigate ui.

**Comment by NickM-27** [comment]
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/6531

**Comment by markfrancisonly** [comment]
> this is a duplicate of https://github.com/blakeblackshear/frigate/issues/6531

Awesome. This appears to be low hanging fruit

**Comment by brukutu** [comment]
> it is actually somewhat complicated due to the way things work internally as well as the challenge of making a configuration that would be backwards compatible.
> 
> We have introduced a config migration scheme as part of 0.14 so that will be helpful on that front. I imagine the new UI with camera groups will satisfy this need for most use cases and then the users that need a portable stream for other devices can use the multiple birdseye views which would be implemented in a future frigate version (maybe 0.15)


I see here that multiple bird eyes was planned for 0.15? 
I can’t seem to find the feature, I take it has not been done yet? 
Thank you.
