### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by JoshC1994** [blakeblackshear/frigate#11118]
![image](https://github.com/blakeblackshear/frigate/assets/85683627/3ddff6c8-0d32-42f6-bce6-83fa52f4368d)

This need to be amened to include the basic code that needs to be written into the file to make it start. 

mqtt:
  enabled: False

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect

**Comment by NickM-27** [comment]
The docs are linked to and that shows what is needed. The next version of Frigate won't require any config to start
