### ISSUE TITLE
Change Events > Cameras > Show all to Show all / Hide all

### ISSUE THREAD

**Issue by alve89** [blakeblackshear/frigate#11152]
**Describe what you are trying to accomplish and why in non technical terms**
This button works only "one way", it checks all checkboxes. If you only want one camera to be selected, you need to manually uncheck all boxes. It would be helpful to uncheck all boxes with one click,

**Describe the solution you'd like**
Why not use the button as state changer: 
State1: Button has label `Show all` > click checks all boxes > activate state2
State2: Button has label `Hide all` > click unchecks all boxes > activate state1

**Describe alternatives you've considered**
Manually unchecking all boxes

**Additional context**
![image](https://github.com/blakeblackshear/frigate/assets/11487054/fa6ec479-fd7b-4750-bbf4-73701b845f74)

**Comment by hawkeye217** [comment]
Better camera selection is already implemented in the upcoming version of Frigate.

**Comment by NickM-27** [comment]
Also worth mentioning that the blue button on the right already works this way

**Comment by alve89** [comment]
> Also worth mentioning that the blue button on the right already works this way

You mean the `Show all` button? I can't confirm (neither Safari, FF, Chrome) in v0.13.2. Multiple click never unchecks the boxes.

Or do you mean another button...?
