### ISSUE TITLE
When launching a review alert/detection, apply pre/post record buffers to video clip

### ISSUE THREAD

**Issue by nwish** [blakeblackshear/frigate#11158]
**This is for 0.14**

@NickM-27 this is just a FR for what I mentioned in the discussion thread if you recall.  

Currently, clicking on a review alert or detection thumbnail directs the user to the full resolution recording.  However, the recording starts at the frame the object was detected on and does not apply pre/post capture buffer times.  To the end user, the result is that the recording seemingly starts late, as the object is already there, and sometimes on its way out of the frame already.  

I believe the buffer times should apply when launching an "event" (clicking on thumbnail), and reflect on the timeline somehow as well.

**Comment by NickM-27** [comment]
Thanks, this was implemented in https://github.com/blakeblackshear/frigate/pull/11143

**Comment by nwish** [comment]
Actually hey @NickM-27 I just tested this and it looks like the buffers apply when launching from the main review area, but when launching an event from within a camera history view, the buffers do not apply.

**Comment by NickM-27** [comment]
To be clear you mean pressing an event in the filmstrip or pressing the segment in the timeline?

**Comment by nwish** [comment]
Filmstrip.  It appears that pressing the bottom of the timeline segment will start the recording at the beginning of the buffer,
