### ISSUE TITLE
[FR] Events based on audio level

### ISSUE THREAD

**Issue by nabahr** [blakeblackshear/frigate#1117]
Is there any plan to add audio level detection for events? One use case that I have is using a camera in the nursery and using audio detection to tell me when the baby is awake. The best cheap solution I've found so far was the Eufy camera, but with their recent security issues, I've cut that camera off from the internet and it appears that I've lost audio detection along with it. This is the only feature left that is stopping me from being able to fully transition over to Frigate and I think it would be quite useful for many other situations as well.

**Comment by blakeblackshear** [comment]
I hadn't considered it yet, but I like the idea.

**Comment by apaperclip** [comment]
I wonder if the audio stuff mentioned at google io 21 could be used to trigger based on what sound was detected.  Not sure if tflite can do it or if its any good at processing audio.  https://www.youtube.com/watch?v=a553D0s7HeE&t=2377s

**Comment by helmbrandt** [comment]
this is a major feature im interested in, makes nonsmart doorbells triggers!

**Comment by ebaschiera** [comment]
> Is there any plan to add audio level detection for events? One use case that I have is using a camera in the nursery and using audio detection to tell me when the baby is awake. The best cheap solution I've found so far was the Eufy camera, but with their recent security issues, I've cut that camera off from the internet and it appears that I've lost audio detection along with it. This is the only feature left that is stopping me from being able to fully transition over to Frigate and I think it would be quite useful for many other situations as well.

As a temporary workaround, you could buy a Yi camera, that can be "hacked" with [roleoroleo's firmware](https://github.com/roleoroleo/yi-hack-Allwinner-v2) and keep it disconnected from the internet. It has sound detection feature. And it's also integrated with Home Assistant!

**Comment by NickM-27** [comment]
This is supported in 0.13
