### ISSUE TITLE
Feature Req: Historic Motion Box Event Scanning (Willing to Pay)

### ISSUE THREAD

**Issue by zacheryph** [blakeblackshear/frigate#11205]
I am not even sure what to call this feature, but would be willing to pay for it.

**Describe what you are trying to accomplish and why in non technical terms**
Cameras have motion masks so you don't get inundated with useless events that don't pertain to you. However... sometimes, on rare occasions, something may happen within the motion mask that you do want to see. Sometimes this is easy, like an object moved/disappeared, so you can skim the content quickly to figure out when it happened (and see what happened.) But sometimes, there is no obvious tell tale for this.

I'd like to be able to _re-scan_ historic video given a specific selection (or "negative-mask") to list "events" that happened in that time. These do not necessarily need to become saved events, just viewable for the time you're on that screen. (but there could be an option to save these events)

**Describe the solution you'd like**
It'd be nice to have a screen that you can;
* pick a camera 
* mark an area (like you do a zone or mask)
* select a time frame

This would then scan through the historic video within the selected time frame, ignoring the cameras motion masks, and using the selected area to scan & list _events_ you can then view. I do understand this would be a little compute intensive and take some time depending n whatever hardware a user has.

**Describe alternatives you've considered**
Sitting down and watching 24 hours of video 🤣 

**Additional context**

**Comment by NickM-27** [comment]
> Cameras have motion masks so you don't get inundated with useless events that don't pertain to you.

This is incorrect, that is not what motion masks are supposed to be used for. That is what required zones are designed to be used for. I would suggest following the docs https://docs.frigate.video/configuration/zones#restricting-events-to-specific-zones
