### ISSUE TITLE
Reduce the video player format

### ISSUE THREAD

**Issue by MiJo112** [blakeblackshear/frigate#11247]
Is it possible to reduce the video player format in Cameras and Recordings views for portrait format cameras?
When portrait format cameras and landscape format cameras are used, extreme scrolling is always necessary. It would be good if a maximum height could be set for the preview windows. 
Ideally as high as other cameras. But this should be configurable.
![image](https://github.com/blakeblackshear/frigate/assets/35043404/57184d67-e998-4098-8bf4-3a03c96cdf33)

**Comment by NickM-27** [comment]
This is already done in the new UI for the next version
