### ISSUE TITLE
[FR] Possibility to add audio into clip from diffferent souce url

### ISSUE THREAD

**Issue by michelebossa** [blakeblackshear/frigate#1126]
Hi All,
I have two urls feeds one with image and another with audio stream can i add this second into clip?

I see the documentation but i think  remove -an it is work only on rtsp with audio embedded.
![image](https://user-images.githubusercontent.com/38975058/119000427-6588f800-b98b-11eb-9880-a1f46177db7e.png)

Thanks

**Comment by blakeblackshear** [comment]
If you can find an example ffmpeg command to combine these two streams into a single mp4, frigate should be able to do the same for you since it's just running an ffmpeg process under the hood for intake.

**Comment by michelebossa** [comment]
I have tried this command and it is worked
ffmpeg -i rtsp://192.168.1.22/ch0_1.h264 -i rtsp://192.168.1.22/ch0_2.aac -c:v copy -c:a aac output.mp4

How can add this into my onwn configuration?

**Comment by michelebossa** [comment]
Nobody can help me?

Thanks

**Comment by blakeblackshear** [comment]
Try adding the additional `-i rtsp://...aac` to the end of the default input args.

**Comment by michelebossa** [comment]
I have tried to add these input arg:

![image](https://user-images.githubusercontent.com/38975058/123427383-d6dc4c00-d5c4-11eb-90ef-960ce5d19c98.png)

but i recive:
![image](https://user-images.githubusercontent.com/38975058/123427430-e8255880-d5c4-11eb-82d9-d4f42afffd11.png)

I have mistake something?
