### ISSUE TITLE
Issue with LAview doorbell camera

### ISSUE THREAD

**Issue by blakebeef1** [blakeblackshear/frigate#1133]
Guessing there is a config setting for this but not finding the right one.
frigate.video                  INFO    : doorbell: ffmpeg process is not running. exiting capture thread...
ffmpeg.doorbell.detect         ERROR   : [rtsp @ 0x5584fc7548c0] Missing PPS in sprop-parameter-sets, ignoring
ffmpeg.doorbell.detect         ERROR   : [rtsp @ 0x5584fc7548c0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
ffmpeg.doorbell.detect         ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
ffmpeg.doorbell.detect         ERROR   : [NULL @ 0x5584fc7bb500] Unable to find a suitable output format for 'probesize 2147483647'
ffmpeg.doorbell.detect         ERROR   : probesize 2147483647: Invalid argument
ffmpeg.doorbell.clips          ERROR   : [rtsp @ 0x559a99b52b00] Missing PPS in sprop-parameter-sets, ignoring
ffmpeg.doorbell.clips          ERROR   : [rtsp @ 0x559a99b52b00] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
ffmpeg.doorbell.clips          ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
ffmpeg.doorbell.clips          ERROR   : [NULL @ 0x559a99bb86c0] Unable to find a suitable output format for 'probesize

**Comment by blakeblackshear** [comment]
That error message doesn't tell me much. Can you provide the info requested in the issue template?

**Comment by blakebeef1** [comment]
Thanks. Here is the info I could grab.  sorry I am pretty new and learning yet so just let me know if anything else would help


**Describe the bug**
Camera is green screen and getting the above error messages.   VLC says 384*512 for the resolution.

**Version of frigate**
Output from `/api/version`

**Config file**
Include your full config file wrapped in triple back ticks.
```detectors:
  coral:
    type: cpu
mqtt:
  host: host
  user: USER
  password: PW
  client_id: frigate
  port: 1883
  topic_prefix: frigate
  stats_interval: 60
ffmpeg:
  input_args: >-
    -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt
    -use_wallclock_as_timestamps 1
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: 'rtsp://user:pw@192.168.1.122:554/h264/ch01/sub/av_stream'
          roles:
            - detect
        - path: 'rtsp://user:PW@IP:554/h264/ch01/main/av_stream'
          roles:
            - clips
      input_args:
        - -avoid_negative_ts
        - -fflags
        - probesize 2147483647 
        - '1'
    fps: 5
    height: 480
    width: 704
    objects:
      track:
        - person
        - dog
        - cat
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.85
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will make motion detection more sensitive to smaller
  # moving objects.
  contour_area: 100
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 1/6th of the original frame height)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 180
  # Optional: Configuration for the jpg snapshots written to the clips directory for each event
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  #  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  # timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  # bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  # crop: False
  # Optional: height to resize the snapshot to (default: original size)
  # height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  # required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    # objects:
      # person: 15

#  filters:
#    person:
#      min_area: 10000
#      max_area: 1000000
#      threshold: 0.92


**Frigate container logs**
```
{
  "cameras": {
    "doorbell": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": false,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts -fflags probesize 2147483647 1 -i rtsp://admin:CQSRQN@192.168.1.122:554/h264/ch01/sub/av_stream -r 5 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        },
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts -fflags probesize 2147483647 1 -i rtsp://admin:CQSRQN@192.168.1.122:554/h264/ch01/main/av_stream -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/doorbell-%Y%m%d%H%M%S.mp4",
          "roles": [
            "clips"
          ]
        }
      ],
      "fps": 5,
      "frame_shape": [
        480,
        704
      ],
      "height": 480,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "doorbell",
      "objects": {
        "filters": {
          "cat": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 100000,
            "min_area": 5000,
            "min_score": 0.5,
            "threshold": 0.85
          }
        },
        "mask": null,
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": false,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "width": 704,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {
      "frigate.mqtt": "DEBUG"
    }
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.107",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "MQTT"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

**Frigate stats**
```json
not sure where to grab?
```

**FFprobe from your camera**

Run the following command and paste output below
```
not having luck installing
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Computer Hardware**
 - OS: ova  HA OS
 - Install method: believe its docker in the os host
 - Virtualization: virtual machine manager
 - Coral Version: none
 - Network Setup: wired but this camera is wireless

**Camera Info:**
 - Manufacturer: LA view
 - Model: doorbell  LV-PDB1630-U
 - Resolution: 720  3MP
 - FPS: 15 runns smooth on other software 

**Additional context**
Add any other context about the problem here.

**Comment by blakeblackshear** [comment]
The error message is complaining about the custom `probesize 2147483647` args you added. It doesn't look like those are valid ffmpeg args there.

Also, the width and height in your config will need to match your camera resolution.

**Comment by blakebeef1** [comment]
Have it working better but the screen looks like a rainbow now
{
  "cameras": {
    "doorbell": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": false,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 75
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel info -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://USR:PW@192.168.1.122:554/h264/ch01/sub/av_stream -r 15 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "fps": 15,
      "frame_shape": [
        1536,
        2048
      ],
      "height": 1536,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "doorbell",
      "objects": {
        "filters": {
          "cat": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 100000,
            "min_area": 5000,
            "min_score": 0.5,
            "threshold": 0.85
          }
        },
        "mask": null,
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": false,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "width": 2048,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {
      "frigate.mqtt": "DEBUG"
    }
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.107",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": "MQTT"
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}

**Comment by blakebeef1** [comment]
Here are the settings and not sure which one helped but its closer.

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - info
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: 'rtsp://USR:PW@192.168.1.122:554/h264/ch01/sub/av_stream'
          roles:
            - detect
    fps: 5
    height: 1536
    width: 2048
    objects:
      track:
        - person
        - dog
        - cat
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.85

**Comment by blakeblackshear** [comment]
The "rainbow" effect is almost always because the height/width in the frigate config doesn't match the camera's resolution.

**Comment by blakebeef1** [comment]
I should have it matching per the manual.  Getting some errors after its been up and running for a little while:

dup=27 drop=357 speed=1.04x    
ffmpeg.doorbell.detect         ERROR   : frame=  336 fps=5.2 q=-0.0 size=   96768kB time=00:01:07.20 bitrate=11796.5kbits/s dup=27 drop=359 speed=1.03x    
ffmpeg.doorbell.detect         ERROR   : frame=  340 fps=5.2 q=-0.0 size=   97920kB time=00:01:08.00 bitrate=11796.5kbits/s dup=27 drop=363 speed=1.04x    
ffmpeg.doorbell.detect         ERROR   : frame=  343 fps=5.2 q=-0.0 size=   98784kB time=00:01:08.60 bitrate=11796.5kbits/s dup=27 drop=365 speed=1.04x    
ffmpeg.doorbell.detect         ERROR   : frame=  345 fps=5.2 q=-0.0 size=   99360kB time=00:01:09.00 bitrate=11796.5kbits/s dup=27 drop=368 speed=1.03x    
ffmpeg.doorbell.detect         ERROR   : frame=  348 fps=5.2 q=-0.0 size=  100224kB time=00:01:09.60 bitrate=11796.5kbits/s dup=27 drop=371 speed=1.03x    
ffmpeg.doorbell.detect         ERROR   : frame=  351 fps=5.2 q=-0.0 size=  101088kB time=00:01:10.20 bitrate=11796.5kbits/s dup=27 drop=374 speed=1.04x    
ffmpeg.doorbell.detect         ERROR   : frame=  353 fps=5.2 q=-0.0 size=  101664kB time=00:01:10.60 bitrate=11796.5kbits/s dup=27 drop=376 speed=1.03x    
ffmpeg.doorbell.detect         ERROR   : frame=  356 fps=5.2 q=-0.0 size=  102528kB time=00:01:11.20 bitrate=11796.5kbits/s dup=27 drop=379 speed=1.04x    
ffmpeg.doorbell.detect         ERROR   : frame=  358 fps=5.2 q=-0.0 size=  103104kB time=00:01:11.60 bitrate=11796.5kbits/s dup=27 drop=381 speed=1.03x    
ffmpeg.doorbell.detect         ERROR   : [rtsp @ 0x56203440d780] Undefined type (31)
ffmpeg.doorbell.detect         ERROR   : frame=  361 fps=5.2 q=-0.0 size=  103968kB time=00:01:12.20 bitrate=11796.5kbits/s dup=27 drop=384 speed=1.03x    
ffmpeg.doorbell.detect         ERROR   : frame=  361 fps=4.8 q=-0.0 size=  103968kB time=00:01:12.20 bitrate=11796.5kbits/s dup=27 drop=384 speed=0.953x    
ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x562034432e40] left block unavailable for requested intra4x4 mode -1
ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x562034432e40] error while decoding MB 0 25, bytestream 25964
ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x562034432e40] concealing 217 DC, 217 AC, 217 MV errors in I frame
ffmpeg.doorbell.detect         ERROR   : rtsp://USR:PW@192.168.1.122:554/h264/ch01/sub/av_stream: corrupt decoded frame in stream 0
ffmpeg.doorbell.detect         ERROR   : frame=  393 fps=5.2 q=-0.0 Lsize=  113184kB time=00:01:18.60 bitrate=11796.5kbits/s dup=54 drop=390 speed=1.04x    
ffmpeg.doorbell.detect         ERROR   : video:113184kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
