### ISSUE TITLE
Storage Overview Breakout: Recordings vs Events vs Snapshots vs Saved

### ISSUE THREAD

**Issue by f1d094** [blakeblackshear/frigate#11353]
Right now the Data subsection Storage overview only lists a cumulative total disk usage for recordings and snapshots. This is not useful for tuning purposes, as there is no breakout provided to describe how much of the storage is being consumed according to which retention mechanism.

Use case example: I just had my server run out of disk and had no idea which setting to change to make a difference. It is all guesswork. Was it my 14day retention policy for all motion? Or was it my 90 day policy for events? Reducing the retain setting by 33% for each and  the expire_interval to 1min changed nothing and still no indication which was the offender. Eventually I worked it out but it took many many iterations of incrementing each setting individually and restarting the server...

A stacked graph should be presented with markers showing how much of the disk is used by which retention rule, with markers  or color banding to show where records overlap. For example, this server's disk space is being consumed largely by events:
```
Recordings: 1
Events: 2
Snapshots: 3
Saved: 4

        50GB 290GB   1TB             1.42TB
1.42TB |=4====3=======1================2
```
Or in this instance the server has a lot of data retained because of the record->retain setting:
```
Recordings: 1
Events: 2
Snapshots: 3
Saved: 4

        50GB 290GB          1.2TB    1.42TB
1.42TB |=4====3===============2========1
```

With the above information it would be easy to tell the impact of each of the settings which would have saved a lot of time. Since each user's use-case is going to be different, it is important for each to be able to analyze which type data is consuming what portion of the overall total.

**Comment by nwish** [comment]
I think you’ll find that with the way .14 works, the need to identify these things will be far less important.  Plus, they’ve already added disk usage data on a per camera basis so that at least provides some extra insight.

**Comment by NickM-27** [comment]
The 0.14 storage page shows cumulative recordings as well as per camera recordings. 

While cameras can have the same retention settings their encoding settings are often different or even when they are the same it still results in different amounts of storage used. 

Recordings in the vast majority of cases will be much more significant to storage usage than snapshots or previews (new in 0.14)
