### ISSUE TITLE
[UI] Screen to solve the goal "why was this review item created"

### ISSUE THREAD

**Issue by NickM-27** [blakeblackshear/frigate#11399]
**Describe what you are trying to accomplish and why in non technical terms**

In the 0.14 UI review items are much more efficient at displaying and allowing the review of periods of time. However, they obfuscate some of the details / information that allows a user to understand why a review item was created.

**Describe the solution you'd like**

Add a screen that allows the user to see the bounding boxes that were detected for a specific object or review time to better understand why a false positive occurred, object was considered active, object was lost, etc.

**Comment by jftanner** [comment]
To slightly add to this: it would also be awesome to submit to Frigate+ from there, once bounding-boxes are available.

In trying out the new Review feature (also with a new model, because I do science wrong), I find that many of the events are tagged with an object that's not in them (usually person or cat, because my dogs are confusing), but it's difficult for me to _do_ anything about it. I then need to look through the Frigate+ tab, which is a lot noisier.

**Comment by BradFD** [comment]
Please add bounding boxes toggle in the UI so I can figure out what triggers false positives.

**Comment by cagivacode** [comment]
Just switched to .14,,,,and yes I have some false positives (probablly new plant growth) but I can't really tell from the image.
Usually means adjusting the minimum threshold for an item base on changed environment, so "why" it was triggered would be helpful.

**Comment by bagobones** [comment]
Going to list out the UI troubleshooting things I think are missing, both new and old. This over laps other comments but wanted to dump a list as maybe this all gets re-vamped together.


1. No longer see scores for detections so no way to tune thresholds
2. No longer see bounding boxes so no way to troubleshoot zone boundaries
3. No longer see any travel timeline like in 0.13 showing zones. Important to see if odd travel is due to bound box jumps etc.
4. Still no audio troubleshooting tools, we need a debug for detected audio labels and the volume for tuning.
5. No tool for debugging the new zone loitering_time and inertia

**Comment by ivanjx** [comment]
i hope this also include bounding boxes for each objects instead of just one random object from the entire clip

**Comment by ostracizado** [comment]
True, without the bounding box the utility of max/min_area/score becomes somewhat redundant - even more for new cameras.
And also true that in HA you can still check it in the frigate folders, but it makes the process quite tricky.

**Comment by NickM-27** [comment]
An initial improvement towards this has been added for the next version being a side panel that shows the objects, scores, zones, and snapshot for each object (assuming snapshots are enabled)

**Comment by Nooton92** [comment]
Is this just for analyzing false positives? I have been having false negatives lately but I can't review the footage to see why without bounding boxes.

Events are triggered just not alerts though so hopefully this new feature will be useable at the event level so I can fix my false negatives.

**Comment by hawkeye217** [comment]
Yes, this will be available with the Explore view in the upcoming version of Frigate.

**Comment by Nooton92** [comment]
Awesome. Any news on a release window? There has been a spike in break ins in my area and I want to try and find time everything as soon as I can.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pvillanyi** [comment]
> An initial improvement towards this has been added for the next version being a side panel that shows the objects, scores, zones, and snapshot for each object (assuming snapshots are enabled) [#13063](https://github.com/blakeblackshear/frigate/pull/13063)

Whet will this implemented? Sound really good. I'm missing the old snapshots where I could see the scores.
We still have the snapshots in Media, but there is no chance to read the score...

**Comment by hawkeye217** [comment]
This has already been implemented and is available in Frigate 0.15, currently in beta.

**Comment by fplanque** [comment]
I am on System 0.15.0-cea210d

> An initial improvement towards this has been added for the next version being a side panel that shows the objects, scores, zones, and snapshot for each object (assuming snapshots are enabled) [#13063](https://github.com/blakeblackshear/frigate/pull/13063)

But how does one open that side panel? The only way I find is to click on the little "person" ou "dog" icon on the top left of a review thumbnail. Extremely tedious to move the mouse to such a small target every time, considering the list of snapshotted objects is what I want to see first (before reviewing the whole video if and only if needed).

- Once I view the video of an event I see no button to open that sidebar....
- Also personally, I'd like to have that sidebar open by default and view it every single time before looking at the actual video).
- Also I'd love to be able to click on a snapshotted object to jump forward in the video (so I can save time not watching less interesting lead in)


> This has been implemented in [#13550](https://github.com/blakeblackshear/frigate/pull/13550) and will be available in Frigate 0.15.
> 
> Snapshots should be enabled in your config for the best experience. Clicking/tapping on the gray "chip" on a review item in the Review pane will bring up a panel with a list of tracked objects, scores, and entered zones that caused the review item to be created. Each object can then be examined further by clicking/tapping the "View object lifecycle" button and scrolling/swiping through the significant moments that Frigate kept track of.

I don't find that gray "chip" item anywhere! What am I missing?
