### ISSUE TITLE
Get streams to home assistant from separate frigate computer

### ISSUE THREAD

**Issue by gurkburk76** [blakeblackshear/frigate#1139]
So i'm in a bit of a pickle for the moment, i have my coral tpu in another computer (i run a docker there that works well) and not in the one where i run home assistant.
I run the HA HACS component in HA to get my sensors and all that, but i would like a way to see my live streams and recordings from Ha the same way i can when/if i use the HA component but i'm failing to find a way to do that.
Trying to address the camera.* entities does not work, is it supposed to? That would facilitate a lot.

**Comment by blakeblackshear** [comment]
Make sure you expose 1935 on the machine running frigate and enable rtmp. You should be able to view the video feeds in HA similar to when you connect directly to the camera via the automatic camera entities.

**Comment by gurkburk76** [comment]
Yeha that was easy, why didn't i think of that .. :D Many thanks!
