### ISSUE TITLE
tpu drops of the buss, container stops working

### ISSUE THREAD

**Issue by gurkburk76** [blakeblackshear/frigate#1141]
So i left frigate and went to bed, when i woke up frigate (webpage rather) wasen't responding.
I investigated the (docker) logs further and found that it wasen't detecting the TPU ans was in a restarting loop of sorts.
It would seem that sometime during the night the usb port or part of the hub stopped chatting with the rest of the system, example:

root@1cpu-greenserver:~/frigate# lsusb
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

And after a reboot od the system:

root@1cpu-greenserver:~# lsusb
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 18d1:9302 Google Inc.		* <------- part that crapped out
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 2109:3431 VIA Labs, Inc. Hub	* <------- part that crapped out
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

And consequently the container didin't want to play along anymore, is there/can there be added some kind of gracefull fallback mechanism to cpu detecting/offloading if case this happens, so the system at least runs propperly even if the tpu stops working? It stopps my 24/7 recordings as well so that's unfortunate.

I'm not sure if it's a hardware problem (stick plugged into 3.0 usb port) but i'll try switching stuff around into other ports the comming days and see if it can be easily fixed, i just want to hear if there are others with similar problems and possible fixed for it. 
Running on debian kernel 5.4.114

**Comment by blakeblackshear** [comment]
Seems like this is usually related to power issues. Probably worth opening a FR for graceful fallback to CPU and ensuring 24/7 recordings still work alongside issues with detection.

**Comment by gurkburk76** [comment]
I'm getting a powered usb hub, hopefully that will fix it.
