### ISSUE TITLE
[UI/nit] Logs, "Jump to Bottom" button colors

### ISSUE THREAD

**Issue by xconverge** [blakeblackshear/frigate#11476]
Recently and on dev-e91f3d8 I noticed this button may not have the right style? I could see how it could potentially be the right style, but something seems a little off by it, maybe just BG color, maybe just FG color, hard for me to know for sure (I also haven't checked all themes, but maybe it is just the Nord theme I happen to be using?)

![image](https://github.com/blakeblackshear/frigate/assets/4219348/734ae553-8814-4442-a62e-27e3ab7612ed)

Definitely close this if it is intended but I wanted to just point it out in case

**Comment by NickM-27** [comment]
No that seems like a remnant of the old colors

**Comment by xconverge** [comment]
This is another one maybe, when checking I checked the default dark theme and saw this bright blue, another one that I am honestly only 50% sure if it is intentional 

<img width="1014" alt="Screenshot 2024-05-21 at 7 09 24 PM" src="https://github.com/blakeblackshear/frigate/assets/4219348/54f6f441-90a6-4cb5-8c5c-d90fbdb8edb7">

**Comment by NickM-27** [comment]
That is correct, same as the other dialogs in the UI
