### ISSUE TITLE
Config Migration Fails on Read-Only Files

### ISSUE THREAD

**Issue by epichb** [blakeblackshear/frigate#11534]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to leverage the automated config migration from <0.14 to 0.14 even if the original config is mounted as a read-only file, so that I can successfully upgrade to the newer application version.

**Describe the solution you'd like**
Frigate should detect non-writable config files early, and provide the user with an alternative to the automated migration.

**Describe alternatives you've considered**
Several possible solutions come to mind:

* Dump the config file into the log-stream if updating the original file fails, and instruct the user to perform the config migration manually
  *  Potential issues with clear-text passwords
* Create a second file, and prompt the user to replace the original manually
  *  Problematic in ephemeral environments, such as containers
* Offer  a semi-automatic approach, providing the user with a subcommand to the application, that can perform the migration without having to start the core application

**Additional context**
Currently, Frigate tries to [overwrite](https://github.com/blakeblackshear/frigate/blob/3f171e7670aef11ad1b7861afa0e336c6e379083/frigate/util/config.py#L46) the existing configuration upon migration. This fails if the configuration is present as a read-only file, for example when mounted from a ConfigMap using the [Helm Chart](https://artifacthub.io/packages/helm/blakeblackshear/frigate). Additionally, creating a separate [versioning file](https://github.com/blakeblackshear/frigate/blob/3f171e7670aef11ad1b7861afa0e336c6e379083/frigate/util/config.py#L61) is likely to cause further complications, by introducing an unexpected persistent state beyond the media and database storage. In my opinion, including the configuration version inside the config itself, or relying on the database to store the last seen config version would be preferable.

**Comment by epichb** [comment]
This would probably more correctly be classified as a bug, however, the "New issue" options only allowed for enhancement issues.

**Comment by NickM-27** [comment]
Most of the time the entire config directory is read only so Frigate can't write to another file either. The log is also not conducive to copy and pasting. If you want frigate to write a file then don't make it read only, even if only temporarily to allow it to update.

**Comment by epichb** [comment]
I can see your point. One remaining gripe I have is the `.version` file. Do you envision users manually managing this file as well? In that case, maybe it would be helpful to document the migration procedure in the release notes for 0.14.0, or, if it already exists in the beta documentation, make it a little more prominent. Right now, the notes only reference the automatic upgrade.

**Comment by NickM-27** [comment]
version is now kept inside of the config file instead of a separate file.

You can also use frigate via command line and the `--validate-config` argument to just have frigate run the migrations without trying to run itself
