### ISSUE TITLE
Allow passthrough of api call to camera

### ISSUE THREAD

**Issue by Xelaph** [blakeblackshear/frigate#11531]
**Describe what you are trying to accomplish and why in non technical terms**
I want my camera's to be on a separate physical network from the normal network for security reasons. We have a Hikvision doorbell and to locally detect if the button of the doorbell is pushed, you can curl a request to camera_ip/ISAPI/VideoIntercom/callStatus?format=json. I'd like to automate this using Home Assistant, so I can get a notification if the doorbell is pushed. Currently this is possible because the doorbell is on the same network as my Home Assistant instance, but in the future I want to put the cameras on a separate network.

**Describe the solution you'd like**
The ideal solution is an option to pipe api calls for the camera through frigate to the camera. I don't know if this is possible.

**Describe alternatives you've considered**
An ability to read this through MQTT would be a great alternative.

**Additional context**
-

**Comment by NickM-27** [comment]
This doesn't seem like something that is actually a frigate use case, more like something for home assistant that wants to be channeled through frigate.

**Comment by jftanner** [comment]
My suggestion, @Xelaph, would be to run a tiny proxy on whatever box you use for Frigate. If you're using Docker, for example, you could spin up an NGINX container that can relay _only_ specific calls (such as your `callStatus` endpoint).
