### ISSUE TITLE
Request via WebUI to record a specific timeframe in the future

### ISSUE THREAD

**Issue by maxdd** [blakeblackshear/frigate#11555]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to have the possibility to plan in advance for a recording.
Sometimes i know that something will happen in a specific timeframe and it would be great to record that moment

**Describe the solution you'd like**
Ideally i would like for the WebUI to have a menu that allows to specify a date and a duration in order to start the recording

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by NickM-27** [comment]
I would suggest that frigate should be configured to just record what is interesting by default. For example by using required zones, object types, etc. Can you describe a scenario where you would want to schedule a recording for something that wouldn't be caught by a typical recording retention

**Comment by maxdd** [comment]
In my case i have a camera behind a "see-through" gate and its resolution allows to understand whether a specific vehicle or person is behind the gate although for a detection algoritm this is not that simple.
Typical use case is the courier which claims a delivery in a specific time/date which is far from being the truth :D

**Comment by NickM-27** [comment]
This could be automated using the manual events API and some automation platform like home assistant. 

In general the recommendation is that storage is inexpensive and setting up constant or even motion based recording would catch what is desired here, also possible that object based recording would work as well. It is not often that users know something worth recording will be happening in the future and at what point it will be happening. Especially like you say where that timing is not guaranteed.

I don't believe this is something that makes sense for us to implement, will leave this open for now and see if other users with other use cases chime in

**Comment by maxdd** [comment]
I don't use HA and i'm not really planning to use it in my setup.
The "recording feature" is a sporadic event that you know for sure it should happen, the recording proves whether the event happened or not.
It is also really helpful when you know that a lengthy thing will happen and you don't want for it to be splitted in 50 videos only because in some "cases" the detection was no triggering the recording.
Frigate is indeed event based although i think that before being a heavily AI based system it is first of all an NVR system.

**Comment by NickM-27** [comment]
Some of your comments aren't relevant anymore with the new UI coming in the next version https://github.com/blakeblackshear/frigate/discussions/11136

**Comment by NickM-27** [comment]
API is https://docs.frigate.video/integrations/api#post-apieventscamera_namelabelcreate

**Comment by NickM-27** [comment]
I am referring to the fact that separate detected objects are not split into separate events in the UI anymore and also frigate has many more features for reviewing footage not based on object detection

**Comment by maxdd** [comment]
I see the following in the new doc

`Using Frigate UI, HomeAssistant, or MQTT, cameras can be automated to only record in certain situations or at certain times.`

Does this imply to have a specific "record" config (e.g. the mode) or is it flexibile also in case record is configured for motion?

**Comment by rodrigogonegit** [comment]
What @maxdd quotes above from the doc also is a bit unclear to me. How exactly can we achieve scheduled recordings via Frigate's UI?

**Comment by NickM-27** [comment]
You can manually control the recording state in frigate ui or you can automate it uses MQTT (also software like home assistant)

**Comment by rodrigogonegit** [comment]
Got you, thanks for clarifying. It reads as if doable directly through Frigate's UI - or at least it does for me.
