### ISSUE TITLE
AMD Renoir GPU VAAPI Decoding

### ISSUE THREAD

**Issue by paulmorabito** [blakeblackshear/frigate#1162]
Hi,

Am currently running latest Proxmox with Kernel 5.11 and an AMD 4650G CPU. Kernel correctly detects and loads GPU driver:

```
[    3.871881] [drm] amdgpu kernel modesetting enabled.
[    3.872149] amdgpu: Topology: Add CPU node
[    3.872209] fb0: switching to amdgpudrmfb from EFI VGA
[    3.872350] amdgpu 0000:03:00.0: vgaarb: deactivate vga console
[    3.872392] amdgpu 0000:03:00.0: enabling device (0006 -> 0007)
[    3.872450] amdgpu 0000:03:00.0: amdgpu: Trusted Memory Zone (TMZ) feature disabled as experimental (default)
[    3.873354] amdgpu 0000:03:00.0: amdgpu: Fetched VBIOS from VFCT
[    3.873356] amdgpu: ATOM BIOS: 113-RENOIR-033
[    3.874798] amdgpu 0000:03:00.0: amdgpu: VRAM: 512M 0x000000F400000000 - 0x000000F41FFFFFFF (512M used)
[    3.874800] amdgpu 0000:03:00.0: amdgpu: GART: 1024M 0x0000000000000000 - 0x000000003FFFFFFF
[    3.874802] amdgpu 0000:03:00.0: amdgpu: AGP: 267419648M 0x000000F800000000 - 0x0000FFFFFFFFFFFF
[    3.874892] [drm] amdgpu: 512M of VRAM memory ready
[    3.874894] [drm] amdgpu: 3072M of GTT memory ready.
[    4.763695] amdgpu 0000:03:00.0: amdgpu: RAS: optional ras ta ucode is not available
[    4.787726] amdgpu 0000:03:00.0: amdgpu: RAP: optional rap ta ucode is not available
[    4.788611] amdgpu 0000:03:00.0: amdgpu: SMU is initialized successfully!
[    4.818261] snd_hda_intel 0000:03:00.1: bound 0000:03:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])
[    4.863137] amdgpu: Topology: Add dGPU node [0x1636:0x1002]
[    4.863146] amdgpu 0000:03:00.0: amdgpu: SE 1, SH per SE 2, CU per SH 18, active_cu_number 27
[    4.865249] fbcon: amdgpudrmfb (fb0) is primary device
[    4.991067] amdgpu 0000:03:00.0: [drm] fb0: amdgpudrmfb frame buffer device
[    5.003952] amdgpu 0000:03:00.0: amdgpu: ring gfx uses VM inv eng 0 on hub 0
[    5.003958] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
[    5.003960] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
[    5.003961] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 5 on hub 0
[    5.003963] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 6 on hub 0
[    5.003964] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 7 on hub 0
[    5.003965] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 8 on hub 0
[    5.003966] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 9 on hub 0
[    5.003968] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 10 on hub 0
[    5.003970] amdgpu 0000:03:00.0: amdgpu: ring kiq_2.1.0 uses VM inv eng 11 on hub 0
[    5.003974] amdgpu 0000:03:00.0: amdgpu: ring sdma0 uses VM inv eng 0 on hub 1
[    5.003975] amdgpu 0000:03:00.0: amdgpu: ring vcn_dec uses VM inv eng 1 on hub 1
[    5.003977] amdgpu 0000:03:00.0: amdgpu: ring vcn_enc0 uses VM inv eng 4 on hub 1
[    5.003978] amdgpu 0000:03:00.0: amdgpu: ring vcn_enc1 uses VM inv eng 5 on hub 1
[    5.003979] amdgpu 0000:03:00.0: amdgpu: ring jpeg_dec uses VM inv eng 6 on hub 1
[    5.014332] [drm] Initialized amdgpu 3.40.0 20150101 for 0000:03:00.0 on minor 0
[    5.880075] amdgpu 0000:03:00.0: amdgpu: Unsupported power profile mode 0 on RENOIR
```

/dev/dri looks like:
```
ls -l /dev/dri
total 0
drwxr-xr-x 2 root root         80 Jun  1 12:04 by-path
crw-rw---- 1 root video  226,   0 Jun  1 12:18 card0
crw-rw---- 1 root render 226, 128 Jun  1 12:18 renderD128
```

I set up a Debian Buster LXC, passed through /dev/dri and installed Frigate docker image. Within the container, vainfo reports:

```
vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver '"radeonsi"'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/"radeonsi"_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

Mesa drivers are:
```
apt search mesa
Sorting... Done
Full Text Search... Done
mesa-va-drivers/now 20.2.6-0ubuntu0.20.04.1 amd64 [installed,local]
  Mesa VA-API video acceleration drivers
```

And when running frigate, I get the following:

```
ffmpeg.livingroom.detect       ERROR   : [AVHWDeviceContext @ 0x5599ee0c2300] Failed to initialise VAAPI connection: -1 (unknown libva error).
ffmpeg.livingroom.detect       ERROR   : Device creation failed: -5.
ffmpeg.livingroom.detect       ERROR   : [h264 @ 0x5599ee008d40] No device available for decoder: device type vaapi needed for codec h264.
```

I've followed the guide [here](https://forum.proxmox.com/threads/amd-ryzen-7-renoir-4750g-apu-and-igpu-pass-thru-to-windows-10-guest.84849/page-3) and looked also at Jellyfin [docs](https://jellyfin.org/docs/general/administration/hardware-acceleration.html) and suspect it's probably something with ffmpeg, mesa libraries in the docker image. I'm not really sure what/where though.

**Comment by paulmorabito** [comment]
In the same LXC container, using the Jellyfin docker with the [AMD mod](https://github.com/linuxserver/docker-mods/tree/jellyfin-amd), vainfo reports:

```
root@ad8c3be77bc8:/# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.11 (libva 2.11.0)
vainfo: Driver version: Mesa Gallium driver 21.1.1 - kisak-mesa PPA for AMD RENOIR (DRM 3.40.0, 5.11.17-1-pve, LLVM 12.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

And transcoding works. I guess it's something to do with the mesa driver and possibly other related libraries. Is it possible to upgrade the docker image with these? I'm more than happy to test.

**Comment by paulmorabito** [comment]
I've done the following now:

```
apt-get update
apt-get install software-properties-common
sudo add-apt-repository ppa:kisak/kisak-mesa
apt dist-upgrade
apt-get update
```

This installs the latest mesa drivers but still no luck (same error as before). Comparing to the Jellyfin container, libva2 is much more recent:

```
libva2/focal,now 2.11.0+i557~u20.04 amd64 [installed,automatic]
  Video Acceleration (VA) API for Linux -- runtime
```

I'm not sure where they got these packages from as they're not in the 20.04 repo but these are much more recent than in the Frigate container (2.6). Any ideas?

**Comment by blakeblackshear** [comment]
Look at the jellyfin dockerfiles. If you can track this down, we can definitely add it to frigate.

**Comment by paulmorabito** [comment]
@blakeblackshear 

I've created a docker container with LIBVA_DRIVER_NAME="radeonsi" set. Start container and get a bash shell then run these commands:

```
apt-get update && apt-get upgrade
apt install curl
curl -s https://repositories.intel.com/graphics/intel-graphics.key | apt-key add -
echo 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main' > /etc/apt/sources.list.d/intel-graphics.list
apt-get update && apt-get upgrade
apt-get install -y --no-install-recommends at intel-media-va-driver-non-free libfontconfig1 libfreetype6 libssl1.1 mesa-va-drivers
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439
echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu focal main" > /etc/apt/sources.list.d/kisak-mesa-focal.list
apt-get update
apt-get install -y mesa-vdpau-drivers mesa-va-drivers mesa-vdpau-drivers libdrm-radeon1

```

I suspect only mesa-va-drivers are needed from the intel repo but in any case, it does install an updated libva.

At the conclusion of above, frigate is still not working. However, within a shell in the container if you do the following:

```
root@54bd082aac1f:/opt/frigate# LIBVA_DRIVER_NAME="radeonsi"
root@54bd082aac1f:/opt/frigate# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.11.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.11 (libva 2.11.0)
vainfo: Driver version: Mesa Gallium driver 21.1.2 - kisak-mesa PPA for AMD RENOIR (DRM 3.40.0, 5.11.17-1-pve, LLVM 12.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

Then VAAPI seems to work. I thought to stop and restart the container thinking that with LIBVA_DRIVER_NAME="radeonsi" in the compose it would work but it doesn't. Instead, it gives:

```
ffmpeg.livingroom.detect       ERROR   : [AVHWDeviceContext @ 0x557084a996c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
ffmpeg.livingroom.detect       ERROR   : Device creation failed: -5.
ffmpeg.livingroom.detect       ERROR   : [h264 @ 0x5570849dad40] No device available for decoder: device type vaapi needed for codec h264.
ffmpeg.livingroom.detect       ERROR   : Device setup failed for decoder on input stream #0:0 : Input/output error
```

vainfo reports:

```
root@54bd082aac1f:/opt/frigate# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.11.0
libva info: User environment variable requested driver '"radeonsi"'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/"radeonsi"_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

But again, if I get a terminal in the container and set LIBVA_DRIVER_NAME="radeonsi" again, it will make vainfo correctly load the driver. I'm not sure why it's not working on container initialization and in theory, with vainfo working, this should also work in Frigate.

Is there a way to restart frigate from within the container or to try to get it to load the driver? Anything else you can think of?

**Comment by paulmorabito** [comment]
@blakeblackshear have you had any time to look into this? I'm afraid I've hit a dead end. The packages from my previous reply do seem to get the Renoir decoder to be identified and working. I've tried to restart Frigate but it is never able to work. 

I'm more than happy to help you test and troubleshoot any issues from this.

**Comment by blakeblackshear** [comment]
It's difficult because I don't have any of the hardware needed to reproduce this. I'm not sure there is much I can do here. Note that frigate itself doesn't know about or care about that environment variable. Frigate spawns an external ffmpeg process, and it should behave the same as when you run ffmpeg manually in the container with the same parameters.

**Comment by paulmorabito** [comment]
@blakeblackshear I understand. Do you know the exact ffmpeg command frigate is running?

The reason I ask is because hardware decoding seems to be working in the container. After I follow the steps from my previous post, I can do:

```
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i /media/file.mkv -f null -
``` 

And hardware acceleration is working on the ffmpeg decoding process (within the container) for x264 even though it still doesn't work for frigate itself.

I'm not sure why I need to set "LIBVA_DRIVER_NAME="radeonsi" again to get it working from command line though (possibly its not set for the logged in terminal environment?). 

Another option would be to make an image with the new/upgraded packages from above post with a different tag and I can test with it?

**Comment by blakeblackshear** [comment]
It's in the web UI under debug.

**Comment by paulmorabito** [comment]
> It's in the web UI under debug.

Ran the command from debug into the command line and runs fine (spews out a load of binary but no error messages).

So the question is, why does it work from the command line and not in frigate? The only difference is I am re-setting the "LIBVA_DRIVER_NAME="radeonsi" ENV before running. Is there some way to append this to the command in frigate just to test?

**Comment by blakeblackshear** [comment]
You can add `> /dev/null` to the end to clear up all the raw output. Have you tried setting the env var [here](https://blakeblackshear.github.io/frigate/configuration/advanced#environment_vars)?

**Comment by paulmorabito** [comment]
> You can add `> /dev/null` to the end to clear up all the raw output. Have you tried setting the env var [here](https://blakeblackshear.github.io/frigate/configuration/advanced#environment_vars)?

That did it, it’s working now!

Is it possible to get the libraries added to the main image?

**Comment by blakeblackshear** [comment]
As long as it doesn't break anything else, it shouldn't be a problem.

**Comment by paulmorabito** [comment]
> As long as it doesn't break anything else, it shouldn't be a problem.

Am happy to help test and debug so just let me know. Thank you again.

**Comment by utkarshjain00** [comment]
I'm seeing similar issue on a i5-11400 with Intel Graphics. Any image tag to test this with?

**Comment by paulmorabito** [comment]
Not aware of an issue but you can follow my instructions from [here](https://github.com/blakeblackshear/frigate/issues/1162#issuecomment-853648337). Additionally, you will need to change the LIBVA_DRIVER_NAME to not being radeonsi.

**Comment by utkarshjain00** [comment]
My case is similar to your in that more libraries need to be included in the image. I have everything working by modifying the container but ideally this step should not be needed. 

Hardware: Intel i5-11400 with Intel UHD 730 integrated gpu. 
Proxmox with kernel 5.11.21-1-pve
LXC container on template ubuntu-21.04-standard, renderD and USB passthrough
Docker running inside the LXC container running frigate

Inside LXC container I could get vainfo working but not inside frigate. Setting driver name alone didn't work either. I needed these steps:

```
apt-get update && apt-get upgrade
apt install curl
curl -s https://repositories.intel.com/graphics/intel-graphics.key | apt-key add -
echo 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main' > /etc/apt/sources.list.d/intel-graphics.list
apt-get update && apt-get upgrade
apt-get install -y --no-install-recommends at intel-media-va-driver-non-free libfontconfig1 libfreetype6 libssl1.1 mesa-va-driver

```

At this point, vainfo works and frigate works too. I then installed intel-gpu-tools and verified gpu is actually being used using inte_gpu_top. CPU and power consumption dropped too. 

I was hoping these changes can be added to the main image and I can help test them and help remove these additional steps.
