### ISSUE TITLE
[UI] - keep "show reviewed" slider ON / enabled

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#11621]
**Describe what you are trying to accomplish and why in non technical terms**
I would like the "show reviewed" slider to stay on (ie either via a cookie/ remembering the on off state set by the user, permanently, or via a enable/disable setting in the config file (or settings gui).

Currently, the default is for this to be OFF (understandable), however if you switch it on and then reload the page (firefox ctrl+r) it switches back to off again. 

![image](https://github.com/blakeblackshear/frigate/assets/60830628/961f9e45-4306-4841-b6b3-7c10ef910a47)

---------------------------
(unrelated to issue above): **Additional context**
un related:  WOW! What an amazing amount of time and work that has been put into frigate version 14 beta, the devs took an already unique and cutting edge (state of the art) product and totally revamped and improved its interface and functionality. **I encourage anyone using frigate to realize that we only have this because of the non compensated time and effort put forth by primarily two or three individuals, and I encourage you to donate to the project and to the devs** (which you can do via the Github main page for frigate).

if you are curious as to the amount of time and effort improving frigate from v13 to v14-beta took, see the Github commits, click on ANY of the commits, and realize there are nearly 3,000+ of these!  (then donate):
https://github.com/blakeblackshear/frigate/commits/dev/

Frigate rivals commercial software NVR solutions that cost hundreds of dollars per camera + 100s of dollars per year in maintenance!!.
https://github.com/blakeblackshear/frigate
![image](https://github.com/blakeblackshear/frigate/assets/60830628/c2c3fa80-654e-4fb6-822a-3315f3bb3132)

**Comment by rroller** [comment]
Related to this, viewed events might be missed by others in the multiuser case if the UI defaults to hiding reviewed. Imagine a husband and wife checking to see if a package was delivered. One might review the events before the other — they’ed always need to enable reviewed. The little event clips at the top of the default page are also impacted by this (I wish they didn’t go away after viewing)

**Comment by mrplow** [comment]
> Related to this, viewed events might be missed by others in the multiuser case if the UI defaults to hiding reviewed. Imagine a husband and wife checking to see if a package was delivered. One might review the events before the other — they’ed always need to enable reviewed. The little event clips at the top of the default page are also impacted by this (I wish they didn’t go away after viewing)

Following this issue for this specific use case ;)

**Comment by NickM-27** [comment]
the multi user use case will likely just change the reviewed behavior to be kept track of per-user as opposed to a simple boolean on / off field

**Comment by Mincka** [comment]
Could it work with HA Proxy Addon?
I mean, if we authenticate once on Frigate through the proxy addon, would it keep the cookies associated to the connected HA user on ingress?
