### ISSUE TITLE
[Feature Request]: EASY EAI Hailo-8 AI support

### ISSUE THREAD

**Issue by ArtemVladimirov** [blakeblackshear/frigate#11663]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use [EASY EAI Hailo-8 AI](https://aliexpress.ru/item/1005006303788306.html) in Frigate so that I can have an alternative to Coral Edge TPU. EASY EAI Hailo-8 has high performance (26 TOPS) with ultra low power consumption (2.5W)

**Describe the solution you'd like**
Native support of EASY EAI Hailo-8 AI accelerator

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by NickM-27** [comment]
Frigate supports many alternatives to using a coral including rockcip npu https://docs.frigate.video/configuration/object_detectors

The device mentioned here seems like a niche device that would be a great candidate for a community supported detector https://docs.frigate.video/development/contributing-boards

**Comment by thestu90** [comment]
8L is available, but I can't get my 8 working. Can you confirm if the 8 will be working soon please?

**Comment by NickM-27** [comment]
yes, multiple users have setup the 8 and confirmed it works

**Comment by thestu90** [comment]
Apologies, I just dug deeper! I see it was in the December Beta version. 

So keen to try! 

Thank you!
