### ISSUE TITLE
Offload hardware acceleration to another server

### ISSUE THREAD

**Issue by moozhub** [blakeblackshear/frigate#11674]
**Describe what you are trying to accomplish and why in non technical terms**
As the topic suggested, I'd like to offload hardware acceleration to a different server that is known to have hardware acceleration enabled

**Describe the solution you'd like**
[rffmpeg](https://github.com/joshuaboniface/rffmpeg) is one, there may be others.

**Describe alternatives you've considered**
Haven't tried any

**Additional context**
None at this time.

**Comment by NickM-27** [comment]
Similar to remote object detection, I think the latency here would be problematic. I also can't really see a situation where you would want to offload ffmpeg decoding but not offload object detection, so I don't see a practical scenario where this would be usable.

**Comment by moozhub** [comment]
I have multiple VMs: 1 docker, and another that transcodes other things. Since I don't need object detection on anything other than frigate, I'd leave it plugged into the docker setup. In my use case, doesn't make sense to have both a docker container and other things running on the same VM. But point taken on the potential latencies.

**Comment by mr-ransel** [comment]
In the pursuit of giving frigate on macos support for hardware acceleration, I'm going to take a stab at getting a modified frigate+rffmpeg docker container running to do the hardware acceleration outside of docker, but still locally on the same machine. This should make the latency much more tolerable, and possibly unlock hardware acceleration on MacOS apple silicon. If it does indeed work, a similar approach could be possible for object detection with some effort; I'll add it to my list of devious schemes.

**Comment by moozhub** [comment]
@mr-ransel thanks for reconsidering, think the idea of offloading these tasks would benefit from a flexibility standpoint. Let me know if you'd like me to try a few tests.
