### ISSUE TITLE
[FR] Add a download link for event clip

### ISSUE THREAD

**Issue by jmedlin** [blakeblackshear/frigate#1168]
It would be useful for me to have a download link for events in the web UI.  Currently there isn't a good way to download a clip to a mobile phone.  I think this would be helpful for quickly sharing recorded clips (hopefully of something funny rather than a robbery).

It would be even cooler to be able to download clips directly from the Home Assistant media browser, but I feel this is probably outside the scope of this project.

**Comment by paularmstrong** [comment]
Android has this built in to the overflow menu (three vertical dots) and works both in the Frigate web app and Home Assistant media browser.

**Comment by jmedlin** [comment]
Unfortunately iOS does not.

![IMG_9925](https://user-images.githubusercontent.com/483304/120669456-78a4c900-c45d-11eb-8ffc-e2ce808a88fc.PNG)

**Comment by jmedlin** [comment]
Submitted a pull request for this feature: https://github.com/blakeblackshear/frigate/pull/1171
