### ISSUE TITLE
[Beta UI] Mobile view: Timestamp not legible when scrubbing through timeline

### ISSUE THREAD

**Issue by Plawasan** [blakeblackshear/frigate#11689]
Frigate 0.14.0-beta2, on mobile (Chrome on Android), when you tap and hold on the timeline, the red timestamp shows up in the page header (as I assume it's intended to, so that it's not hidden under your finger) however it does not fit its container and ends up being shown on two lines, making it not legible. Same thing happens both in landscape and portrait orientation.

![image](https://github.com/blakeblackshear/frigate/assets/73796046/edf5ef9b-fedc-483a-b7a9-d2a9e3e1b4d7)

Btw when opening an issue here, there's no template for a bug, only for a feature and a security issue.

**Comment by NickM-27** [comment]
You should submit it as a support issue. 

In this case this was already fixed yesterday
