### ISSUE TITLE
Frigate in the cloud

### ISSUE THREAD

**Issue by jiiins** [blakeblackshear/frigate#117]
Hi Blake,

Would it bes possible to run Frigate on a Google Cloud machine, using Google Cloud's TPU instead of a Coral?

**Comment by blakeblackshear** [comment]
I would assume some modifications would be necessary, but I haven't looked into it.

**Comment by TomK** [comment]
@jiiins did you look into this?  i've got a Coral on backorder with 11 months estimated shipping 🤦‍♂️

**Comment by NickM-27** [comment]
> @jiiins did you look into this?  i've got a Coral on backorder with 11 months estimated shipping 🤦‍♂️

https://github.com/blakeblackshear/frigate/issues/3449
