### ISSUE TITLE
Erroneous exports are stuck “loading” forever

### ISSUE THREAD

**Issue by nwish** [blakeblackshear/frigate#11701]
Running .14 dev branch (bccffe6).  This happened early on and I was able to get rid of it by modifying the database.  However, I think there should be some kind of check or ability to delete these.

Sometimes exports get goofy (for whatever reason, in my screenshot below it looks like the beginning timestamp is… well, valid but not?  Not sure.  The logs for this are long gone and I can’t reproduce it now.

Anyway, the export is stuck there with the spinning wheel of death.

Could we add a way to delete them if they error?  Or add a check? 

Thx!  

![IMG_3290](https://github.com/blakeblackshear/frigate/assets/17681279/7b2a3944-d6a5-4311-8f81-ff58f7d6ac6b)

**Comment by NickM-27** [comment]
There are checks for failed exports. Without logs or reproducibility I'm not sure how this can be fixed.

**Comment by nwish** [comment]
> There are checks for failed exports. Without logs or reproducibility I'm not sure how this can be fixed.

Okay no worries, I'll get you logs on a reproduction.  I've had it happen a few times when messing with exports so I'm sure I'll grab another one soon.

**Comment by NickM-27** [comment]
exports that are in progress can be deleted now if they are not actively being written to

**Comment by heisenberg2980** [comment]
@NickM-27 I have a bunch of exports that failed some months ago, and they are stuck there. I don´t see any option to delete them (maybe because I requested them before that option was implemented), is there a way to delete them?

![image](https://github.com/blakeblackshear/frigate/assets/58039006/72ffc23e-d2c7-43ce-9100-bf75f788308a)

**Comment by NickM-27** [comment]
just delete the files in the file system

**Comment by heisenberg2980** [comment]
> just delete the files in the file system

I can´t believe it was that easy, thanks @NickM-27
