### ISSUE TITLE
Link directly to events or review page (0.14+)

### ISSUE THREAD

**Issue by rhyst** [blakeblackshear/frigate#11707]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to go directly to an event (or even just the recording page for a particular camera) so that I can link home assistant based event notifications on my phone directly to the event footage.

**Describe the solution you'd like**
A way to specify an event or camera review page in the url when loading Frigate.

**Describe alternatives you've considered**
When navigating in Frigate I had a look for URL changes but it seems like this is not surfaced.

**Additional context**
This is related to the new UI (0.14+).

**Comment by NickM-27** [comment]
This is already supported. Url is `frigate_access/review?id={REVIEW_ID}`
