### ISSUE TITLE
[0.14.0 Beta 2] Mark reviewed also at the top of the screen (or jump to the bottom)

### ISSUE THREAD

**Issue by ronbruins** [blakeblackshear/frigate#11756]
It would be nice to have the mark for review button at the top of the screen as well, or a jump button that moves directly to the bottom of all events. Now I have to scroll through endless events to reach the bottom. 

E.g. this morning I went through the footage of last night, but all events from yesterday were still there as well. As nothing out of the ordinary happened, I just want to clear all events (mark fro review) but now I have to scroll all the way down

**Comment by NickM-27** [comment]
I'd suggest if you have detections that are not relevant then you should tweak the detections to only include things you find worth looking at. The point is that it's at the bottom because after scrolling through the items all ones that weren't looked at are ready to be marked as reviewed.

**Comment by ronbruins** [comment]
Detecting can become relevant when they would appear so. In a situation like this: All are at work and we come home and nothing happened, so all detections are more or less irrelevant and they can be marked as reviewed. 
Now we come home and the car I damaged, bike is stolen, or we want to see if there has been a delivery or something. Now the detections are relevant. So if I would have tweaked detections I would not have seen these events.

**Comment by NickM-27** [comment]
> OR have a selector that selects all and then contextual actions like "Mark Reviewed" and any other that makes sense

this already exists

**Comment by iursevla** [comment]
In which version? @NickM-27 
Because I don't find any place to select all

**Comment by NickM-27** [comment]
you can use ctrl + a or cmd + a to select all

**Comment by ronbruins** [comment]
14 beta 4On 29 Jul 2024, at 17:25, Rui Alves ***@***.***> wrote:﻿
In which version? @NickM-27
Because I don't find any place to select all

**Comment by iursevla** [comment]
Solved, the dev tag I was using wasn't as new as I thought it was. For some reason I used a 1.5months old tag. Using the latest one we have that `Cmd + a` action working. 

Thanks @NickM-27
