### ISSUE TITLE
Motion detection defaults don't work well for low resolution substreams

### ISSUE THREAD

**Issue by charlesmunger** [blakeblackshear/frigate#1176]
**Describe the bug**
A clear and concise description of what your issue is.
The default motion detection configuration appears tuned for a 1080p stream at 5fps. However, my ReoLink RLC-410 provides a 640x480 substream at 7fps. So with 1080p, you'd get the following default configuration:

```json
"fps": 5,
"frame_shape": [
  1080,
  1920
],
"height": 1080,
"motion": {
  "contour_area": 100,
  "delta_alpha": 0.2,
  "frame_alpha": 0.2,
  "frame_height": 180,
  "threshold": 25
},
```

Very reasonable. The contour size tracks a reasonable, small portion of the resized image - the resized frame height is still large enough to not lose thin things like legs. However, configure that substream:

```json
"fps": 7,
"frame_shape": [
  480,
  640
],
"height": 480,
"motion": {
  "contour_area": 100,
  "delta_alpha": 0.2,
  "frame_alpha": 0.2,
  "frame_height": 80,
  "threshold": 25
},
```

We now have a tiny, 80 pixels high image to do motion detection on. But the `contour_area` has not scaled - so we need 6.8 times the area to trigger motion compared to the 1080 stream. Similarly, the `frame_alpha` and `delta_alpha` have not changed - so to the motion detector, it looks like the objects are moving a lot slower.

My proposal:
1. Change `delta_alpha` and `frame_alpha` from constant defaults to 1/fps
2. Change `contour_area` from a constant default to `scaled width * scaled height * 0.00173611111` (or some more reasonable constant value, possibly taking into account masked area)
3. Change `frame_height` from default `height/6` to `max(height/6, 180)`

There are risks; changing the alpha rates might make motion detection worse if the default values were working well already despite being very different from the framerate, or if `contour_area` was configured explicitly to match the automatic scaled value of `frame_height`. And the increased frame height might increase CPU for people with small substreams like I have. But overall, I think this would result in the configuration that seems to have been originally intended, and it certainly works better on my cameras.

**Version of frigate**
0.8.4-5043040

**Comment by blakeblackshear** [comment]
I'm not so sure about adjusting the alpha rates, but the contour area and frame height make sense.
