### ISSUE TITLE
Automatic Daily Recordings Export with Timelapse

### ISSUE THREAD

**Issue by gorfreed** [blakeblackshear/frigate#11765]
Yes, I am aware that this question was most likely asked a hundred times already, but I've been up and down all the documentation and simply cannot get a straight answer for this feature which is essential for a security cam system.

At the end of the day, I want my Frigate to export the daily recordings of a camera in the format configured in my config (as timelapse video). I can manually trigger this with an API call and the GUI on the web portal works terrific too. HOWEVER, it is not automatic and I have to sit there and wait until the process is complete.... For each camera. 

Of course, that makes that feature completely useless in the day-to-day, so I want to ask you for how to create this daily export automatically. Possible the API call would be the easiest solution, but it requires the timestamp parameters by default:

POST /api/export/<camera>/start/<start-timestamp>/end/<end-timestamp>

How can I send the request simply for yesterday's 24 hours at the start of a new day?

**Comment by NickM-27** [comment]
This can be done automatically with a system like home assistant, NodeRED, or even a simple bash script + cron job. 

It is also worth mentioning that in the next version of frigate the UI supports scrubbing recordings quickly automatically which replaces the need of time-lapses for many users.

**Comment by gorfreed** [comment]
@NickM-27 Could you please point me to a working example where a bash script + cron job combination is being used? I cannot find any and was unable to reproduce this setup so far.

**Comment by NickM-27** [comment]
https://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses/ would be a good starting point. There's not much special about calling Frigate's api. Just need to get the start and end timestamp then make the api request in the script

**Comment by gorfreed** [comment]
@NickM-27 I think you misunderstood my issue completely. I have no troubles using cron or writing http requests. My problem is that the specific endpoint of frigate I am aiming at expects/requires date parameter in unix that I don't know how to produce if said export is supposed to run daily for the last 24 hours (hence the unix parameter would always be different).

**Comment by gorfreed** [comment]
POST /api/export/<camera>/start/<start-timestamp>/end/<end-timestamp>

**Comment by NickM-27** [comment]
You just need to get the epoch time https://stackoverflow.com/questions/1092631/get-current-time-in-seconds-since-the-epoch-on-linux-bash and add 24 hours (in seconds) to it

**Comment by gorfreed** [comment]
I see. I guess that means I don't get around coming up with some kind of script/backend that does that calculation for each call then? I cannot simply have it triggered by other tools that are only capable of sending out requests as configured.
