### ISSUE TITLE
Delete button on "frigate +" view

### ISSUE THREAD

**Issue by mabed-fr** [blakeblackshear/frigate#11776]
**Describe what you are trying to accomplish and why in non technical terms**
There are certain images that I do not want to send to frigate+ can we add a button to remove one or more images (exclude)

**Comment by nwish** [comment]
They're not submitted until you submit them.

**Comment by coldkevin** [comment]
this actually would be helpful. I have quite a few images inside my frigate+ tab that dont have an image associated with them so i havent submitted it in fear of messing up the model. I havent found a way to delete them and I cant find where theyre stored locally to remove them
![Screenshot 2024-06-09 225916](https://github.com/blakeblackshear/frigate/assets/21207285/4dcb8050-0713-4c6f-a583-3e92cd5ef75b)

**Comment by mabed-fr** [comment]
> They're not submitted until you submit them.

Yes it's true but why keep them?



> this actually would be helpful. I have quite a few images inside my frigate+ tab that dont have an image associated with them so i havent submitted it in fear of messing up the model. I havent found a way to delete them and I cant find where theyre stored locally to remove them 

This is a problem that I have too

**Comment by XKali** [comment]
Could be really usefull.

**Comment by mbrinkley1234** [comment]
A delete button would be very handy (as long as it allows deletion of lots of photos).  I have lots of images on the frigate + page that I don't want to submit as I have had a new model built recently and don't really care about images before that new model.  

As an additional tool to help, a date filter on that page would also get the job done (just filter out old images I don't care about).
 
While we are talking about that page, how about adding a link to the actually frigate + review website that we can click and be redirected?

**Comment by taky-taky** [comment]
A batch remove option would be great. I am completely satisfied with the accuracy of the detection for now. We will see if it will be the same under other conditions in the winter. Until then, I don't want to upload any more images, so a mass delete button would either be great or an option to turn off image collection completely.

**Comment by NickM-27** [comment]
You can turn off collection by disabling snapshots

**Comment by taky-taky** [comment]
I thought the snapshot was necessary for some other function, but I tried it and it is a suitable solution for my usage conditions. Not sure if it is for the others. Maybe we should read the docs more attentively..
“For users with Frigate+ enabled, snapshots are accessible in the UI in the Frigate+ pane to allow for quick submission to the Frigate+ service."
Other option it to temporarily disable the frigate plus option

**Comment by edalquist** [comment]
I'd like to be able to retain snapshots for record keeping for a long time (they are small and cheap to store) but then have a way to "dismiss" snapshots from the Frigate+ UI. I generally only go and submit images to Frigate+ that are either wrong, or unique correct views. Maybe I'm incorrect here but I'm assuming it isn't helpful to send 100s of images that are all slight variants of the same scene and object set.

Being able to dismiss images (similar to dismissing events) would make the process of periodically reviewing Frigate+ images for interesting data a lot easier. Right now I just try to remember the last date that I did a review for and review up to that point in my snapshots.

**Comment by NickM-27** [comment]
I don't think trying to view every frigate+ image is an efficient way to go about it. The filters there allow for sorting and filtering on score which is the best way to find false positives as well as low scoring true positives

**Comment by edalquist** [comment]
Agreed, and I use the filters, but there isn't a date filter or a way to say "I've submitted everything I want to from the set of snapshots"

**Comment by mbrinkley1234** [comment]
> I don't think trying to view every frigate+ image is an efficient way to go about it. The filters there allow for sorting and filtering on score which is the best way to find false positives as well as low scoring true positives

So wouldn't it make sense to add a date filter to the frigate + page?
