### ISSUE TITLE
Export broken in dev branch

### ISSUE THREAD

**Issue by sorenisanerd** [blakeblackshear/frigate#11785]
On the `dev` branch (commit d2787d43086cd53a3c5cace89116b255eeb1c3a0), I see this error:

```
Exception in thread Thread-2132:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/record/export.py", line 172, in run
    thumb_path = self.save_thumbnail(export_id)
  File "/opt/frigate/frigate/record/export.py", line 77, in save_thumbnail
    ) < datetime.datetime.now().astimezone(datetime.timezone.dst).replace(
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'method_descriptor'
```

https://github.com/blakeblackshear/frigate/blob/d2787d43086cd53a3c5cace89116b255eeb1c3a0/frigate/record/export.py#L77

**Comment by NickM-27** [comment]
Issues should not be used for this, please submit a bug

**Comment by sorenisanerd** [comment]
Uh... Issues are bugs. Does Frigate use an external bug tracker?

**Comment by NickM-27** [comment]
There is a bug template linked in the issue creation page. In any case, this bug is fixed in a PR that was just put up
