### ISSUE TITLE
Nighttime Detection

### ISSUE THREAD

**Issue by vanheerdena** [blakeblackshear/frigate#118]
Hello, thank you for your work on this project. I have the project running on my rasp pi 4 thanks to @kpine. Using the default config file I get the following Debug stats:
{"back":{"detection_fps":5.7,"fps":6.5,"skipped_fps":0.0},"coral":{"detection_queue":0,"detection_start":0.0,"fps":5.7,"inference_speed":19.53},"plasma_store_rc":null,"tracked_objects_queue":0}

My issue is that inside in colour I seem to get ok detection, but outside at night using IR lighting the detection it is very poor. Looking at the video stream - movement is not shown well at all see - [https://youtu.be/V4Q7yNjx5Ns](https://youtu.be/V4Q7yNjx5Ns)
Even if I stand still - no detection happens see - [https://youtu.be/qN1nEJPzubY](https://youtu.be/qN1nEJPzubY)

Any ideas for improving the accuracy. Maybe changing the frame rate settings, or a setting related to greyscale?

**Comment by blakeblackshear** [comment]
I will be looking at improving detections and reducing false positives after I get the next release stable.

**Comment by OptimusGREEN** [comment]
yes i dont seem to be getting any detection on night vision.

**Comment by scstraus** [comment]
It works for me on night vision. Not quite as well as during the day, but it works.

**Comment by vanheerdena** [comment]
Thanks for the reply. Reading a bit more, it seems night-time detection of objects / pedestrians is a much less well understood / studied problem. In case it is useful, here is a paper and dataset called NightOwl from Oxford University. 
[](http://www.robots.ox.ac.uk/~vgg/publications/2018/Neumann18b/neumann18b.pdf)
[](https://www.nightowls-dataset.org/)


There seem to be other night time data sets out there which might also be useful listed in the following paper:
_Singha, A., & Bhowmik, M. K. (2019). Moving Object Detection in Night Time: A Survey. 2019 2nd International Conference on Innovations in Electronics, Signal Processing and Communication (IESC). doi:10.1109/iespc.2019.8902385_

**Comment by JonGilmore** [comment]
@vanheerdena so I have no issues at all with my nighttime person detection. what hardware are you using for cameras? I'm using poe hikvision cams and my nighttime detection works _wayyy_ better than I would have ever imagined it to.

**Comment by vanheerdena** [comment]
@JonGilmore I also have poe hikvisions cams, so your comment is great news. Could I ask what settings you are using in your config file? I am just using the default settings provided in the example.

**Comment by JonGilmore** [comment]
@vanheerdena here's my config: https://github.com/JonGilmore/frigate-config/blob/master/config.yml
I'm not doing anything crazy here, just using the out of the box defaults. here's an example of a config a camera config: 

![image](https://user-images.githubusercontent.com/7232986/77811964-25bacf00-706c-11ea-95bf-f6578b5e67c2.png)

**Comment by scstraus** [comment]
I have to echo Jon’s sentiments. I also have hikvisions, and it’s pretty solid at night. Not quite as good as day but not off by much. I do have external IR illuminators and security lights outside, though, so it gets quite a clear picture to work from even if it’s in “night vision” mode, though. I’m sure that helps. The default illuminators built into the cameras only illuminated a small part of the picture, I’m sure it wouldn’t have worked as well with those.

**Comment by JonGilmore** [comment]
this is off topic, but @scstraus - what external IR illuminators are you using?

**Comment by scstraus** [comment]
2 different types I found on Amazon.co.uk. There aren’t that many of them there, if you search you will find the same ones.

**Comment by scstraus** [comment]
I think it was this one https://www.amazon.co.uk/KKmoon-Illuminator-Security-Infrared-Waterproof/dp/B01M10RZ98/ref=mp_s_a_1_fkmr0_2?keywords=uv+illuminator+outdoor&qid=1585559375&sr=8-2-fkmr0
and this one

https://www.amazon.co.uk/Almabner-Infrared-Illuminator-Outdoor-Waterproof/dp/B082WZ4QMK/ref=mp_s_a_1_fkmr2_2?keywords=uv+illuminator+outdoor&qid=1585559375&sr=8-2-fkmr2

Some with high 90 degree for close and some with 45 degree for far away
