### ISSUE TITLE
Recordings UI fails when no recordings exist

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#1180]
The current recordings UI doesn't gracefully handle when there are no recordings. It seems to get stuck loading recordings in an infinite loop.

![image](https://user-images.githubusercontent.com/569905/120902095-06bab400-c604-11eb-8bfb-99b45c50a2f8.png)

@hunterjm

**Comment by hunterjm** [comment]
This can be closed.
