### ISSUE TITLE
[UI] Bring back "Star tagging" on events

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#11828]
**Describe what you are trying to accomplish and why in non technical terms**
In 0.13.x there was an option to "star mark" a event, the event was saved (not pruned/purged) including the corresponding clip.

**Describe the solution you'd like**
I would love for the "Star marking" possibility of events to be brought back to the new UI.

**Describe alternatives you've considered**
Rollback to 0.13.x ...

**Additional context**
N/A

**Comment by NickM-27** [comment]
Exported events are used instead. There are searchable and more portable making them easier to use than starred events were
