### ISSUE TITLE
[FR] 24/7 record clip length

### ISSUE THREAD

**Issue by mr-manuel** [blakeblackshear/frigate#1183]
Hello,

would it be possible to add an option to define the length of the clips in the 24/7 recordings? Actually every clip is only 1 minute long and I'd like to increase to 15 minutes.

**Comment by mr-manuel** [comment]
Actually, it can already be achieved by changing the `output_args`:

```
      output_args:
        record: -f segment -segment_time 900 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
```

**Comment by blakeblackshear** [comment]
Keep in mind that you will lose the entire segment if ffmpeg's connection to your camera is interrupted. The default is 1 minute to minimize data loss. This will also break the upcoming recordings UI.

**Comment by mr-manuel** [comment]
Thank you for the details
