### ISSUE TITLE
API: access secrets directly

### ISSUE THREAD

**Issue by jhvst** [blakeblackshear/frigate#11870]
Currently there is a bug affecting, e.g., NixOS: https://github.com/blakeblackshear/frigate/discussions/11324

This issue stems from these lines: https://github.com/blakeblackshear/frigate/blob/962d213699dd6a08fb2be59fc3e8b2736321b465/frigate/api/auth.py#L90-L96

Certain distributions like NixOS create a per-process user to services like frigate. Often, secrets in the run directory are then given on per-process basis. Coincidentally, this means that the read capabilities of the `/run/secrets` folder is reserved for root only. Instead, the access pattern is such that services read their corresponding environment variables directly from the folder, such as `/run/secrets/FRIGATE_JWT_SECRET`.

To address this issue, the listing logic should be removed. This seems to make little sense anyway since the file is read directly later anyway: if the file does not exist, the read should fail.

Without this change, frigate process on NixOS and distributions with similar secret management logic will run into a Python crash on startup, because frigate tries to scan secrets it should not have access to.

**Comment by blakeblackshear** [comment]
Thanks for reporting. 

Genuinely honest question as we are trying to maintain a good workflow around bug reports. How did you submit this issue without selecting a template?

We have a specific link for bug reports on the new issue page, but this was submitted as a generic issue instead.

![Screenshot_20240611-062515.png](https://github.com/blakeblackshear/frigate/assets/569905/1088ce21-d349-44b0-a7b5-0ff1d863cc69)

**Comment by jhvst** [comment]
This issue was submitted by going to the code, lining up a piece of code, and then clicking on "submit issue" using the GitHub web UI.

**Comment by blakeblackshear** [comment]
Thanks.

I'm not very familiar with NixOS. Does it look like the following would work?

```python
    elif os.path.isdir("/run/secrets") and os.path.isfile(
        os.path.join("/run/secrets", JWT_SECRET_ENV_VAR)
    ):
```

**Comment by jhvst** [comment]
Personally, I would just try to open the filepath directly and fallthrough if it does not open up. I.e., to me, checking whether the directory exists seems redundant if you are then reading a file within it anyway (in other words, reading a file successfully implies that the directory exists).
