### ISSUE TITLE
Video Loss Detection

### ISSUE THREAD

**Issue by rodrigojfernandez** [blakeblackshear/frigate#11886]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to detect when a camera stop working

**Describe the solution you'd like**
A boolean sensor that activates when the screen is black

**Describe alternatives you've considered**

**Additional context**
Want to be able to detect when a camera is or was broken in order to trigger the alarm

**Comment by NickM-27** [comment]
this is already supported. It can be used by looking for the camera entity being `unavailable` or checking if `camera_fps == 0`

**Comment by rodrigojfernandez** [comment]
Thanks Nicolas.

Regards

Rodrigo Fernández
________________________________
De: Nicolas Mowen ***@***.***>
Enviado: martes, 11 de junio de 2024 13:55
Para: blakeblackshear/frigate ***@***.***>
Cc: rodrigojfernandez ***@***.***>; Author ***@***.***>
Asunto: Re: [blakeblackshear/frigate] Video Loss Detection (Issue #11886)


this is already supported. It can be used by looking for the camera entity being unavailable or checking if camera_fps == 0
