### ISSUE TITLE
Export - Automatically remove fiels created after X days

### ISSUE THREAD

**Issue by alanRfol** [blakeblackshear/frigate#11891]
**Describe what you are trying to accomplish and why in non technical terms**
I would find it very hand to be able to automatically remove export files created after X days

**Describe the solution you'd like**
Like the retention config setting can we have the ability to automatically remove exports created after  X days ?

**Describe alternatives you've considered**
manually remove via UI can take longtime if you have many files.

**Additional context**
Home Assistant can call the creation of a export file but cant call a delete. As I use home assistance to create exports then my firgate disk can fill up quikcly.

**Comment by NickM-27** [comment]
The point of exports is that they're not managed by frigate automatically, they are to be stored indefinitely. You otherwise should just use the built in frigate retention configuration

**Comment by alanRfol** [comment]
thanks for the quick update. I was hoping this could go in as a feature request as would be good to be able to delete many exports at a time / any over X days.

just keeps my disk with space.

**Comment by NickM-27** [comment]
why are you creating so many exports? why are you okay with them being deleted without seeing them? it doesn't sound like you are using the export feature for its intended purpose
