### ISSUE TITLE
Height of stream in webbrowser not correct

### ISSUE THREAD

**Issue by thrust15** [blakeblackshear/frigate#119]
Hi,

I have an RTSP stream of 640x480 from my camera's into frigate. However, when I go to http://IP/front I get an 640x**360** stream. I've been trying to provide height and width in the config but it doesn't change

The snapshots are in the correct resolution though, so it only seems to be the stream.

I tried using the stable and the 0.5.1-RC2 version

My config:
```yaml
web_port: 5000

mqtt:
  host: 172.17.0.1
  topic_prefix: frigate
  user: User # Optional -- Uncomment for use
  password: Password # Optional -- Uncomment for use

objects:
  person:
    min_area: 1000
    max_area: 100000
    threshold: 0.75

cameras:
  front:
    ffmpeg:
      input: rtsp://user:pw@192.168.1.29:554/h264Preview_01_sub
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    height: 480
    width: 640
    take_frame: 1
    objects:
      person:
        min_area: 1000
        max_area: 100000
        threshold: 0.75
    fps: 4
    snapshots:
      show_timestamp: False
  back:
    ffmpeg:
      input: rtsp://user:pw@192.168.1.30:554/h264Preview_01_sub
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    height: 480
    width: 640
    take_frame: 1
    objects:
      person:
        min_area: 1000
        max_area: 100000
        threshold: 0.75
    fps: 4
    snapshots:
      show_timestamp: False

**Comment by ManuelPerrot** [comment]
Actually I think its a feature for the debug url, you can change it like this:
http://url:5000/camera?fps=5&h=480

**Comment by thrust15** [comment]
I tried, but the width scales with the custom height. so I still don't have the correct ratio, the image looks a bit squashed.

**Comment by ManuelPerrot** [comment]
> I tried, but the width scales with the custom height. so I still don't have the correct ratio, the image looks a bit squashed.

Ah yes that's correct, it works the same for me. The code is forcing a 16/9 ratio:
https://github.com/blakeblackshear/frigate/blob/8507bbbb31429ae30f156040910bb46ceb935573/detect_objects.py#L294

I think this url is only meant for debugging.
I will let the code owner decide if he wants to provide a url with the native camera aspect ratio.

**Comment by scstraus** [comment]
Yes, this is true for my portrait orientation cameras too. They are defined correctly as 1920 high by 1080 wide, but the debug stream shows them squashed into landscape orientation. Not a huge issue as everything sent to MQTT is fine, but would be nice to have it fixed.

**Comment by blakeblackshear** [comment]
This has been fixed.
