### ISSUE TITLE
Larger snapshots on live cam view

### ISSUE THREAD

**Issue by Gollam** [blakeblackshear/frigate#11902]
I am testing the new beta. One thing I noticed is the camera images are too small for me when viewing on desktop. I don't know if this maximum picture size is intentional or not, but I only have 4 cameras, and a large monitor, so these only take only 1/4 of the screen currently. It would be awesome if they'd fill the screen more.

Current UI:
![image](https://github.com/blakeblackshear/frigate/assets/765342/a5440ec9-1172-4788-8e41-733cf358c566)

What I would expect:
![image](https://github.com/blakeblackshear/frigate/assets/765342/bf9397d2-c6b0-4497-b11c-42a9cba42460)

**Comment by NickM-27** [comment]
You can create a camera group and customize it however you want
