### ISSUE TITLE
S3 / Minio support

### ISSUE THREAD

**Issue by mzac** [blakeblackshear/frigate#1192]
I was thinking that it might be interesting to add support for S3 / Minio object storage support instead of mounting a file path for the media directory?  I keep running into permission issues and this could be a good way to leverage an external tool to do all the file management.

Minio is an open source object storage similar to Amazon's S3 service meaning you can host it on your own system.  All the calls to Minio are API calls so it might not be hard to integrate this into the code.

https://github.com/minio/minio

Also, having full Amazon S3 support could allow images and videos to be stored in the cloud.

Thoughts?

**Comment by savikko** [comment]
I am using rclone to mount dropbox to one folder on filesystem. Then frigate will save files directly to my dropbox.
Of course target can be s3 as well.
