### ISSUE TITLE
Stream of camera from last event

### ISSUE THREAD

**Issue by MStapelfeldt** [blakeblackshear/frigate#11935]
**Describe what you are trying to accomplish and why in non technical terms**
I'm using HA and on my default Dashboard I'm displaying some cameras to have a quick view, what's going on around the house. Now I have 8 cameras working, but not enough room on dashboard to see a camera where nothing is to see.

**Describe the solution you'd like**
I would like to have a stream to display in a card from the camera, where the last event was detected. As example:
```
  - type: picture-entity
    entity: camera.frigate_lastevent_cam
    show_state: false
    show_name: false
    camera_view: auto
```
This could be `Events/PAST EVENTS` view in Frigate. So if there is an Event, the entity stays with this camera, until something new happens.

**Describe alternatives you've considered**
expose Birdseye as stream to Display in Frontend/Dashboard. This could be stream like `camera.frigate_birdeye`

**Additional context**

**Comment by NickM-27** [comment]
birdseye can already be displayed in HA dashboard using the frigate card, or HA if birdseye restreaming is enabled

there are also image.___ entities which show the last objects that were detected along with the entity holding the time when that happened.
