### ISSUE TITLE
Separate PTZ Camera control pane in the birdseye view.

### ISSUE THREAD

**Issue by teymur1988** [blakeblackshear/frigate#11966]
**Describe what you are trying to accomplish and why in non technical terms**
When birdseye has like 5 cameras enabled and cameras have onvif enabled on them as well, the controls are popping up on the side in birdseye view. Cause the PTZ control buttons take considerable room on the page, I have to scroll down and loose the camera view to control the last camera for example.

**Describe the solution you'd like**
1. If the PTZ control pane was separate to the birdseye view so that the controls could be scrolled but the video remained on the page.

**Comment by hawkeye217** [comment]
This is already implemented in a much better way in the next version of Frigate (0.14), currently in beta.

**Comment by teymur1988** [comment]
Oh, wow. Can't wait then! Thanks for letting me know! This can be closed then.
