### ISSUE TITLE
Support Raspberry Pi AI Kit with Hailo

### ISSUE THREAD

**Issue by askpatrickw** [blakeblackshear/frigate#11961]
**Describe what you are trying to accomplish and why in non technical terms**
Would like to use the new official RPI AI Kit & Hailo with Frigate.

**Describe the solution you'd like**
Add support for the Hailo as a detector.

https://www.raspberrypi.com/documentation/accessories/ai-kit.html#object-detection

**Describe alternatives you've considered**
Can't get the Pineberry Ai board and Coral to work reliably, mostly due to the Coral libaries.

**Additional context**
Google seems to have abandoned the Coral libraries, so more a more diverse set of boards would be ideal.

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/11663#issuecomment-2141808697

**Comment by askpatrickw** [comment]
Not sure I would consider this device to be "niche". But let's see if any other Frigate users find and comment on this issue (or open dupes).

**Comment by NickM-27** [comment]
Relative to the highly utilized detectors like coral and Intel openvino it is. Even tensorrt is relatively niche (< 10% of total users)

**Comment by NickM-27** [comment]
And the rpi in general is not a recommended platform for frigate, especially rpi5 which is missing hardware h264 decoders

**Comment by geerlingguy** [comment]
(Just a note: The AI Kit has only been available for a couple weeks, and is only just now showing up in physical retail locations.)

I've been running two Frigate instances on two Pi 5's for a few months now, one I've tested up to 3 4K Annke cameras just fine—they output H.265 (the feed I use for detection is 480p, and I record 24x7 full 4K stream). The other is pulling in two H.264 streams from Hikvision cameras, and I've had zero issues on either. I've moved the 2nd one over to a CM4 just for convenience getting it into my rack though.

Running USB Corals currently but I hope to use the Hailo-8L eventually :)

I know the Hailo devs haven't been focused as much on opening up access to their dev tooling until very recently, but I think they're keen on getting the Hailo-8L working great with Frigate too. It would be awesome if I could walk into Micro Center, walk out with a $130 little Pi+AI kit, and have a perfect Frigate box for 2-4 cameras (maybe more? My systems aren't even hitting 50% CPU).

**Comment by NickM-27** [comment]
To be clear, closing this feature request just means I don't think this support is something that Frigate maintainers will work on because it will affect so few users, when there are literally hundreds of feature requests that will affect all or a majority of frigate users. 

In any case, frigate has a [community supported boards](https://docs.frigate.video/development/contributing-boards) framework so should the Hailo devs or anyone else want to contribute and maintain the detector code then this would be supported.

**Comment by geerlingguy** [comment]
Totally get that; just on the "affect so few users" point, it remains to be seen whether the AI Kit will spark the Pi + Hailo to be a widely-available and widely-supported solution for low-power inference, or if Hailo and/or RPi will drop the ball and make it a flop.

In the former case, I could see the combo to be as popular as (if not more popular than) USB Coral + Pi, as builds can be a lot more compact with a little flat PCIe HAT.

**Comment by NickM-27** [comment]
right, such options are already possible with another community supported board RKNN in things like OrangePi for example.

**Comment by n2kbg** [comment]
Just another perspective- I found this issue because I was searching to see how soon Frigate would support the Pi AI kit. I was going to buy one to replace my NUC/Coral system. I was not expecting the answer to be "never".

**Comment by NickM-27** [comment]
I don't know why you are interpreting the answer as "never", there are already a handful of community supported detectors and multiple people have expressed interest in creating a community supported detector for this hardware

**Comment by victorhooi** [comment]
Just putting this for posterity, in case other people find this thread.

It seems like recently (i.e. July 2024) - support for Hailo-8L was added - yay! 😀:

* https://github.com/blakeblackshear/frigate/pull/12431
* https://github.com/blakeblackshear/frigate/pull/12820

The commit mentions support for the "Raspberry Pi 5 with Hailo-8L AI Kit". (I assume they haven't tested with just using the Hailo-8L M.2 card on other PCs).

It also mentions inference speeds are `17-21 ms for the SSD MobileNet Version 1 model.` - I believe the Coral TPU is around 10ms, right?

I'm not sure if that's some kind of fundamental limitation of the Hailo-8L, or something due to the models being used, or something that can be optimised for?

**Comment by NickM-27** [comment]
I implemented support for amd64 in a commit after that. It's possible the model used is not quantized, difficult to directly compare them.

**Comment by victorhooi** [comment]
Ahh - nice!

I did find this from Hailo's docs:

https://github.com/hailo-ai/hailo_model_zoo/blob/master/docs/OPTIMIZATION.rst

From what I can see, we're just downloading the pre-compiled models provided by Hailo from S3:

https://hailo-model-zoo.s3.eu-west-2.amazonaws.com/ModelZoo/Compiled/v2.11.0/hailo8l/ssd_mobilenet_v1.he

I would assume they've already run the `optimize` step on these public models - but I suppose it's worth checking

(This [comment](https://github.com/hailo-ai/hailo_model_zoo/issues/84#issuecomment-1938758684) seems to imply they are doing it - although maybe that's how I'm reading it?)

I don't Hailo-8L hardware currently - but maybe it's something I can get, and compare it against my existing Coral TPUs =).

**Comment by mbwhite** [comment]
Fresh kit sat on my desk now; will report back how it goes :-)
(pi 5, halio ai kit from pineboards, plus nvme)

**Comment by evanjrowley** [comment]
Two even more powerful versions were released today: https://www.raspberrypi.com/news/raspberry-pi-ai-hat/

I ordered one and will report back on how well it works.

**Comment by luckylinux** [comment]
@evanjrowley: Any Update ? I am about to pull the Trigger on 1 or 2 of them.

@NickM-27: the support for amd64 that you added for the Hailo-8L 13 TOPS ... Does that also include the Hailo-8, i.e. the 26 TOPS ? And can multiple Hailo-8[L] Detectors be used at the same Time, just like multiple Corals (according to the Configuration File Examples for Detectors) ?

**Comment by blakeblackshear** [comment]
Yes. I have a Hailo-8 and can confirm it is supported.

**Comment by luckylinux** [comment]
I actually went ahead a few hours ago and bought 2 of them :rofl: 

Unfortunately the current System where I'm running Frigate inside a Virtual Machine doesn't cut it ... I cannot pass through some PCIe slots with the Detector and, on the other Hand, the passed-through AMD RX 6600 GPU crashes the VM every 7 Days or so.

That's why I'm trying to build a Dedicated System (without using KVM Virtual Machine) with Intel Xeon E3-1245 v3 (yes, old, but with Integrated GPU for Transcoding) and those Hailo-8 and/ro Hailo-8L Detectors :smiley:

**Comment by evanjrowley** [comment]
> Yes. I have a Hailo-8 and can confirm it is supported on amd64 at least.

That's awesome! How do you verify that it is working?

I have the 26 TOPS version installed on a Raspberry Pi with Frigate 0.15.0 beta.

**Comment by blakeblackshear** [comment]
I'm not sure what you mean. If you configure a Hailo detector type in Frigate and it doesn't crash on startup then it's working.

**Comment by luckylinux** [comment]
Damn it :cry:. I just received the Raspberry AI HAT+ Hailo-8 and it is SOLDERED directly into the Raspberry Pi Hat.

That's a MAJOR Difference compared to how the previous Raspberry AI HAT was :(.

Seems like I completely wasted my money now, as I would need to buy a Raspberry PI 5 as well.

Or some kind of Mechanical + PCIe Cable Adapter :-1:.

**Comment by luckylinux** [comment]
@blakeblackshear: how good is multiple Hailo-8 / Hailo-8L Support though ? Like running 2 (or 3 or 4 :rofl:) in "Parallel" at the same Time ? Will all of them be used or only a single one ?

**Comment by NickM-27** [comment]
multiple can be used at the same time

**Comment by luckylinux** [comment]
I am thinking of sending back the Hailo-8 and buying a bunch of Hailo-8L which I can then use as M.2 Directly. More expensive (per Item: 80 EUR for the Hailo-8L M.2 vs 125 EUR for the Hailo-8 Soldered) but then I could avoid a bunch of DIY Reverse Adapters etc.

I hate to send back Stuff as it's extra Tasks, but so would be to build a custom-made adapter to be able to run at barely PCIe x1 Speeds ...

**Comment by geerlingguy** [comment]
@luckylinux - They still sell the original Kit (which has the socketed adapter), but that can be confusing how one is an M.2 edition, and the other is soldered down.

There are a couple FFC to PCIe adapters out there:

  - https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/663
  - https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/661

But none are available for purchase anywhere at this time. They're quite useful for people debugging Pi PCIe devices, but not really for much else!

**Comment by roblamoreaux** [comment]
I just got a Raspberry Pi AI kit, but installed the HAILO M.2 card in a dual M.2 adapter I already had my SSD in. I am running Home assistant on a Raspberry Pi 5 and hope to use the AI to get frigate to efficiently monitor 2 or 3 cameras.

I can get Frigate 15 Beta1 running without the Hailo detector configured, And Home Assistant lists the Hailo hardware. 

But when I configure the Hailo it crashes with the log messages  below. Any idea of what I am doing wrong or if this will work?

`2024-11-15 00:51:01.368056656  Process detector:hailo8l:
2024-11-15 00:51:01.368061656  Traceback (most recent call last):
2024-11-15 00:51:01.368063064    File "/opt/frigate/frigate/detectors/plugins/hailo8l.py", line 72, in __init__
2024-11-15 00:51:01.368063990      self.target = VDevice()
2024-11-15 00:51:01.368069342  NameError: name 'VDevice' is not defined
2024-11-15 00:51:01.368070046  
2024-11-15 00:51:01.368071138  During handling of the above exception, another exception occurred:
2024-11-15 00:51:01.368072823  
2024-11-15 00:51:01.368073935  Traceback (most recent call last):
2024-11-15 00:51:01.368102343    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-11-15 00:51:01.368105009      self.run()
2024-11-15 00:51:01.368106102    File "/opt/frigate/frigate/util/process.py", line 41, in run_wrapper
2024-11-15 00:51:01.368106935      return run(*args, **kwargs)
2024-11-15 00:51:01.368108009    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-11-15 00:51:01.368154159      self._target(*self._args, **self._kwargs)
2024-11-15 00:51:01.368156270    File "/opt/frigate/frigate/object_detection.py", line 109, in run_detector
2024-11-15 00:51:01.368175530      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-11-15 00:51:01.368177585    File "/opt/frigate/frigate/object_detection.py", line 61, in __init__
2024-11-15 00:51:01.368178715      self.detect_api = create_detector(detector_config)
2024-11-15 00:51:01.368179807    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-11-15 00:51:01.368180604      return api(detector_config)
2024-11-15 00:51:01.368181733    File "/opt/frigate/frigate/detectors/plugins/hailo8l.py", line 105, in __init__
2024-11-15 00:51:01.368182659      except HailoRTException as e:
2024-11-15 00:51:01.368197012  NameError: name 'HailoRTException' is not defined
2024-11-15 00:51:01.371586280  [2024-11-14 19:51:01] detector.hailo8l               INFO    : Starting detection process: 413
2024-11-15 00:51:01.371684690  [2024-11-14 19:51:01] frigate.detectors.plugins.hailo8l INFO    : Initializing Hailo device as PCIe
2024-11-15 00:51:01.371709264  [2024-11-14 19:51:01] frigate.detectors.plugins.hailo8l INFO    : A model file already exists at /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef not downloading one.
2024-11-15 00:51:01.413910687  [2024-11-14 19:51:01] frigate.app                    INFO    : Output process started: 429
`

**Comment by NickM-27** [comment]
you should create your own issue

**Comment by luckylinux** [comment]
OK I finally (!) managed to get it working under Proxmox VE / Debian Bookworm Host + Podman Rootless (although on a separate Note the Intel iGPU cannot be monitored due to stats Permission Issues).

I have this in my Frigate `config.yml`, but how do I tell it to use the 3 Available Hailo-8L Devices ?

```
detectors:
  hailo0:
    type: hailo8l
    device: PCIe
    model:
      path: /config/model_cache/h8l_cache/ssd_mobilenet_v1.hef
```

For reference this is Podman `compose.yml` Excerpt for the Devices Section:
```
   devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel
      - /dev/dri/card0:/dev/dri/card0
      - /dev/hailo0:/dev/hailo0
      - /dev/hailo1:/dev/hailo1
      - /dev/hailo2:/dev/hailo2
```

I assume only one Detector is being used or ? How can one check that either on the Host (using `hailortcli` ?) or in Frigate Container ?

**Comment by maciekish** [comment]
Hi, do i understand it correctly that Halio-8 is supported on Pi5 now?

**Comment by NickM-27** [comment]
In 0.15 yes
