### ISSUE TITLE
[UI] No scrollbar in new player (0.14)

### ISSUE THREAD

**Issue by andrey-skat** [blakeblackshear/frigate#12009]
**Describe what you are trying to accomplish and why in non technical terms**
In the new version of the player, the scrollbar has been replaced with scroll buttons. I guess it have been done to unify it with the motion timeline interface which records continuously. However on events page the absence of a scrollbar is less convenient as it prevents scrubbing through the video, viewing the duration of it,  seeing current video position (Also when the network speed is slow, old scrollbar indicated that the video was still loading. Now it appears as if the video has ended).

**Describe the solution you'd like**
Can scrollbar be returned to events player?

**Comment by NickM-27** [comment]
Not sure what you mean by the events page?

**Comment by drulia** [comment]
yep, I just updated to 0.14 and got confused for a moment right away, all videos as far as I can see have hidden controls and doesn't even show length of video. Like I click on alert video and there no indication about length of it. Have to right click -> show controls to be able to see it.

**Comment by NickM-27** [comment]
on the initial review screen when you hover there is a progress bar below the item. When you click an item it brings you into the recordings player which shows the timeline on the right what you are looking at currently. there is no "video length" as these are just broken up into hour long chunks.

**Comment by andrey-skat** [comment]
> Not sure what you mean by the events page?

History -> Events. History page with event thumbnail on right panel

> on the initial review screen when you hover there is a progress bar below the item. When you click an item it brings you into the recordings player which shows the timeline on the right what you are looking at currently. there is no "video length" as these are just broken up into hour long chunks.

When I click on camera -> History -> Events there is no progress bar. 
By video length I mean event length.

**Comment by NickM-27** [comment]
I see what you are referring to now. The events list will have items with a blue border while they are currently playing, it's mainly designed to have a consolidated list of what happened without needing to scroll through the timeline. The timeline is better suited for seeing when events happened and jumping around to them and knowing their length.

**Comment by twister36** [comment]
@andrey-skat are you referring to this? Frigate v14 on left and Frigate v13 on right. The video timeline scroll is missing
![image](https://github.com/user-attachments/assets/1b2eb3dc-c19a-4e5d-ab81-f2a2f52823ae)

**Comment by NickM-27** [comment]
@twister36 you use the timeline on the right (desktop) or bottom (mobile) to scrub the video

**Comment by twister36** [comment]
> @twister36 you use the timeline on the right (desktop) or bottom (mobile) to scrub the video

Yes, I just noticed this. I also notice that it seems to have a general capture of the entire history of my camera(s). How much storage is this using??

**Comment by NickM-27** [comment]
The previews are very efficient, 1 hour long preview takes up less space than a single event snapshot
