### ISSUE TITLE
Select all in reviewed

### ISSUE THREAD

**Issue by kdill00** [blakeblackshear/frigate#12041]
Hey guys, hope your all doing well!  I’ve been playing with 14 and im curious if the mark all as reviewed button could be moved to the top on mobile or a select all button included at the top?   When reviews pile up it becomes impossible on mobile to reach the bottom without setting filters over and over.  I have a couple locations where alerts will be in the hundreds to thousands every day and mass editing would be very useful as I have employees with only mobile access when they are on the floor.  If im missing something let me know.  Thanks for all you guys do blake, nick, hawkeye.

**Comment by hawkeye217** [comment]
Just merged https://github.com/blakeblackshear/frigate/pull/12044 which should allow you to use Ctrl-A on desktop browsers to select all of the review items at once.

**Comment by ofcedwards** [comment]
Not sure if this is intentional, but with the latest dev image this feature requires ctrl-a on Mac as well instead of the more typical cmd-a.

**Comment by NickM-27** [comment]
addressed in latest commit
