### ISSUE TITLE
Hailo 8L support 

### ISSUE THREAD

**Issue by akurze11** [blakeblackshear/frigate#12053]
Describe what you are trying to accomplish and why in non technical terms
I want to use Frigate with the new Raspberry Pi AI kit which used the Hailo 8L chip and is considerably faster than the Coral USB stick

Describe the solution you'd like
Native support

Describe alternatives you've considered
Coral - too slow

Additional context
No

**Comment by hawkeye217** [comment]
There has been a recent discussion about this here: https://github.com/blakeblackshear/frigate/discussions/2050

This board would be a good candidate for one of the [Community Supported Boards](https://docs.frigate.video/development/contributing-boards/). The maintainers don't have any bandwidth (nor do they have the hardware) to support this themselves.
