### ISSUE TITLE
a warning message in Home Assistant related to the Frigate (Full Access) Beta add-on. 

### ISSUE THREAD

**Issue by younescht** [blakeblackshear/frigate#12069]
### Description
I am receiving a warning message in Home Assistant related to the Frigate (Full Access) Beta add-on. The warning states that the add-on has full device access and selective device access in the configuration, which may be a security concern.

### Warning Message
2024-06-19 21:40:46.646 WARNING (SyncWorker_1) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate (Full Access) Beta

**Comment by NickM-27** [comment]
this is not a feature request, and has already had an issue created on the addon repo

**Comment by younescht** [comment]
> this is not a feature request, and has already had an issue created on the addon repo

thank you. i ll be check
