### ISSUE TITLE
Easier way in Frigate+ UI to indicate the correct label for a mis-identified object

### ISSUE THREAD

**Issue by emelarnz** [blakeblackshear/frigate#12119]
**Describe what you are trying to accomplish and why in non technical terms**
When verifying false positives / mis-identified images in the Frigate+ user interface it is necessary to create an (often identical) box and add the correct label. An easier way to do this that is keyboard friendly and doesn't require re-drawing the box would speed up Frigate+ verification.

**Describe the solution you'd like**
Click on an existing false-positive box and easily add the correct tag, rather than having to draw another box. Adding the correct label alongside the incorrect one would be easiest, but duplicating the box would be more flexible in case a minor adjustment to the box boundaries is required. 

**Describe alternatives you've considered**
Really just whether to add a second box for the correct label, or add a second label to the existing box. The former seems more flexible when the original box is not well positioned, but I'm not sure how important that would be for training.

**Additional context**
Making verification easier/quicker would encourage me to spend more time verifying in Frigate+.

![image](https://github.com/blakeblackshear/frigate/assets/4415320/28bee314-bd54-4e69-8231-42aa0bb7d6a9)

**Comment by NickM-27** [comment]
Frigate+ specific feature requests should be made in the frigate+ discussion
