### ISSUE TITLE
In events, Labels, Select All should change from select-all to deselect-all

### ISSUE THREAD

**Issue by haydonryan** [blakeblackshear/frigate#12128]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to look at events that are labelled as "everything" and then "person"

**Describe the solution you'd like**
the select all button should go from select all to deselect all - a common UI trait.

**Describe alternatives you've considered**
None :)

**Additional context**
Would also love "deer", "Squirrel" as options.

**Comment by NickM-27** [comment]
This is already supported, use the blue box button
