### ISSUE TITLE
Timelapse - Save One or more image(s) a day etc

### ISSUE THREAD

**Issue by justinyounger** [blakeblackshear/frigate#12171]
**Describe what you are trying to accomplish and why in non technical terms**
Not a huge priority I am sure, but it would be really cool to run a long term time-lapse export or specialized recording. Something like a single or handful of photos a day.

**Describe the solution you'd like**
I dont think this would work as an export like now, since most people dont save recordings for...years. But maybe this is a different kind of camera recording method, where you set a time to take a photo and file type to save a single image a day or maybe multiple a day. Then you could have a long term image time lapse. 

Just an idea!

**Comment by NickM-27** [comment]
I don't think this really fits inside of the use case of an NVR. There are also endless permutations of ways users might want this to behave / be done. Frigate supports resrreaming and a snapshot api either of which could be utilized by external software to accomplish this task.
