### ISSUE TITLE
Expose recording stream rather than detect stream to HomeAssist

### ISSUE THREAD

**Issue by itispip** [blakeblackshear/frigate#12193]
**Describe what you are trying to accomplish and why in non technical terms**
Detect stream is usually small, lagged and low quality; Recording stream is high resolution. In frigate, when 1 camera has 2 stream for detect and record respectively, only the detect stream was exposed to HomeAssistant Live View. This is not pleasant user experience.

**Describe the solution you'd like**
Expose the recording stream as main camera for Home Assist live may, detect stream do thing in back-end only & for new "Person" picture only.

**Describe alternatives you've considered**
Have manually exposed both camera stream in HA dashboard, it works but just comparatively not so user friendly comparing to Frigate implement a change.

**Additional context**
No.

**Comment by NickM-27** [comment]
This is entirely up to how you configure frigate, either stream can be configured to be used in home assistant
