### ISSUE TITLE
[UI] Ability to view more than 24 hours of review items

### ISSUE THREAD

**Issue by ofcedwards** [blakeblackshear/frigate#12265]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use the calendar filter on the reviews screen to view more than 24 hours of reviews at one time. The other filters available allow for narrow selections (such as a specific object in a specific zone) that may not occur on every calendar day. If I only had 5 detections that match the filters across 30 days, I'd like to see all of them at once instead of clicking on each day until I find them.

**Describe the solution you'd like**
Allow a time range selection on the calendar filter. Start date and end date would be fine, no need to add specific times.

**Describe alternatives you've considered**
Using filters on the Frigate+ view to find all matching snapshots, reading the timestamp, navigating back to the reviews screen, then filtering to the correct dates one at a time.

**Additional context**
I believe the current 24h limitation is probably due to the added timeline. The timeline could either scroll continuously for the entire time range or be hidden if the selection is greater than 24h.

**Comment by NickM-27** [comment]
The review screen is designed for the 24 hour, daily review use case. A separate screen designed for searching different detections across date ranges has already been implemented for 0.14.1
