### ISSUE TITLE
HA locking up when running USB Coral on Pi4

### ISSUE THREAD

**Issue by brianlaucis** [blakeblackshear/frigate#1230]
Currently have frigate running on a VM on a IMac using the CPU as detectors and it works sending the MQTT data to the broker on the primary HA Rasp pi4. 
 
When I run Frigate on the primary HA (Rasp Pi4 ((SSD Supervised)) using a Coral USB. When motion is being processed it causes the primary HA to lock up and losses connection. The only was to get HA back up is to remove power and power back up.  I've tried two different Coral USB sticks. I've tried two different sources of power. and even the power supply pit doesn't shows any issues after restarting the Rasp Pi. 

Version of frigate
1.13 (HA)

**Config file**

```mqtt:
  host: 192.168.86.53
  user: mqtt
  password: suppersecret123

cameras:
  frontyard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://Vadmin45:1234@192.168.86.56:554/h264Preview_04_sub
          roles:
            - detect
    width: 640
    height: 360
    fps: 5
    detect:
      max_disappeared: 5
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 75,135,125,131,123,96,75,97
            - 267,62,282,63,281,38,266,38
            - 313,52,330,52,330,31,316,30
          min_score: 0.5
          threshold: 0.7
        dog:
          mask:
            - 75,135,125,131,123,96,75,97
          min_score: 0.4
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain: 
        default: 4
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://Vadmin45:1234@192.168.86.56:554/h264Preview_03_sub
          roles:
            - detect
    width: 640
    height: 360
    fps: 5
    detect:
      max_disappeared: 5
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 363,360,0,360,0,177,236,72,382,26,547,60,592,128
        person:
          min_score: 0.5
          threshold: 0.6
        dog:
          min_score: 0.4
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain: 
        default: 4
  frontdoor_cam:
    ffmpeg:
      inputs:
        - path: rtsp://Vadmin45:1234@192.168.86.56:554/h264Preview_02_sub
          roles:
            - detect  
    width: 640
    height: 360
    fps: 5
    detect:
      max_disappeared: 5
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 139,62,171,57,167,0,146,23
            - 47,148,79,135,82,78,40,81
            - 295,49,290,22,254,22,264,53
          min_score: 0.5
          threshold: 0.6
        dog:
          min_score: 0.4
          threshold: 0.5
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain: 
        default: 4

detectors:
  coral:
    type: edgetpu
    device: usb
```

**Frigate container logs**
```
Startup of logs startup show nothing abnormal. It starts fine. 
```

**Computer Hardware**
 - OS: [Raspberry Pi 4, 4GB RAM, booting off SSD]
 - Install method: [Addon]
 - Virtualization: [None]
 - Coral Version: [USB]
 - Network Setup: [Wired]

**Camera Info:**
 - Manufacturer: [Reolink]
 - Model: [RLC 810A
 - Resolution: [640 X 360]
 - FPS: [5]

**Comment by brianlaucis** [comment]
Startup Logs:
 
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera frontyard_cam has rtmp enabled, but rtmp is not assigned to an input.
frigate.app                    WARNING : Camera driveway_cam has rtmp enabled, but rtmp is not assigned to an input.
frigate.app                    WARNING : Camera frontdoor_cam has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for frontyard_cam: 41
detector.coral                 INFO    : Starting detection process: 38
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Camera processor started for driveway_cam: 42
frigate.app                    INFO    : Camera processor started for frontdoor_cam: 44
frigate.app                    INFO    : Capture process started for frontyard_cam: 46
frigate.app                    INFO    : Capture process started for driveway_cam: 51
frigate.app                    INFO    : Capture process started for frontdoor_cam: 52
frigate.edgetpu                INFO    : TPU found

**Comment by blakeblackshear** [comment]
> I've tried two different sources of power.

What two different sources have you tried? From my understanding, it doesn't matter what power supply you plug directly into the Pi. This sounds exactly the same as issues others have solved by switching to an externally powered USB hub for the Coral.

**Comment by brianlaucis** [comment]
I used the P.S that came with the CANA kit (3.5A) and I've used the USB 3.0 plug on my cyberpower UPS (3.0A).  I'm not opposed to getting a power USB hub. I'll be going out today I'll see if I can locate one and give it a try.

**Comment by brianlaucis** [comment]
Added a powered hub.  It's been running fine since yesterday. The only thing that concerns me is it's appears to have caused a memory-leak ![image](https://user-images.githubusercontent.com/40279388/122651389-18b94e00-d0fe-11eb-9e8c-7dbd4674c69e.png)
