### ISSUE TITLE
Feature Request: Restore Snapshot Deletion Button in Frigate Beta

### ISSUE THREAD

**Issue by XKali** [blakeblackshear/frigate#12314]
**Description:**

In the stable version of Frigate, a convenient button exists to delete individual snapshots directly from the interface. This functionality is highly valuable for maintaining a clean event list. However, in the current beta version, this button appears to be missing.

**Request:**

I would like to request the reinstatement of the snapshot deletion button in the Frigate beta. Ideally, this button would not only remove the snapshot file from the "clips" directory but also delete the corresponding entry from the database, ensuring a complete removal of the event data.

**Rationale:**

The ability to easily delete snapshots is crucial for efficient event management and storage optimization. The absence of this button in the beta version forces users to manually delete files and potentially leaves orphaned entries in the database.

**Additional Notes:**

- If possible, please consider adding a confirmation prompt before deleting a snapshot to prevent accidental deletions.
- It would be beneficial if the snapshot deletion button could be integrated into the context menu for each event, providing a streamlined user experience.

Thank you for considering this feature request. I believe it would greatly enhance the usability and functionality of the Frigate beta.

**Comment by NickM-27** [comment]
Thanks for the request. Events are no longer directly user interactable as review items are separate. I don't really see a reason why a user needs to delete snapshots manually, they take up very little space relative to recordings and the recommendation is to let them be cleaned up as expected.

The UI does support deleting of review items which deletes the thumbnail, db entry, and relevant recordings
