### ISSUE TITLE
Frigate 0.14 Click frigate icon to return "Home"

### ISSUE THREAD

**Issue by SavageAUS** [blakeblackshear/frigate#12331]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to click the frigate icon in the top left to return "home"
![Screenshot 2024-07-08 122259](https://github.com/blakeblackshear/frigate/assets/17326832/a7f526ce-2b22-4f0c-a3bd-2101ee82d122)

**Comment by hawkeye217** [comment]
Depending on the screen, view, or device, the Frigate logo is not always displayed, so the UX would be inconsistent. The Live dashboard is the "home" screen in 0.14 - just tap the camera icon below the logo to return "home".

**Comment by mjalindahl** [comment]
So, I agree with @SavageAUS, that clicking on the frigate icon should return you to home.  I, myself, after using the beta tried to click on it, and so did my dad when I upgraded his setup to v14 a few days later.  He asked "why can't I click on the main icon and get back home?"

So, while I get the whole "viewpoint" thing, on both desktop and mobile, the icon is displayed, so I don't think it would be much trouble to add the hyperlink to the logo.

I defy you to send me one website where clicking on the main logo doesn't return you to home.  It's common UX at this point.

**Comment by hawkeye217** [comment]
Sure, that's fair. I've put up a PR (https://github.com/blakeblackshear/frigate/pull/12379) to make the logo in the sidebar on desktops clickable.
