### ISSUE TITLE
/api/frigate/notifications/ for clip display 404: Not Found

### ISSUE THREAD

**Issue by auBusinessDaD** [blakeblackshear/frigate#1234]
When trying to include the image of an event, It doesn't show. When I try to use the URL it brings up a 404 error, and the url from the frigate dashboard that does show the image is not using the same url.

Frigate Version - 1.13

https://HA_URL/api/frigate/notifications/1623910005.021053-7iiqpu/thumbnail.jpg - results in 404: Not Found error

https://HA_URL/api/hassio_ingress/N74k75Arm72N3s8BaDUO7aky7pdGd0DR6gDXHysq2SM/clips/CAMERA_NAME-1623910005.021053-7iiqpu.jpg - is the URL from the Frigate NVR dashboard which is showing the correct image.

(I replace the URL and CAMERA NAME for security ;) )

**Comment by blakeblackshear** [comment]
Have you installed and configured the [Frigate integration](https://github.com/blakeblackshear/frigate-hass-integration)?

**Comment by auBusinessDaD** [comment]
That was what I was missing. Thanks! I saw it mentioned in the docs on the integrations documentation page, but there wasn't a link and I couldn't find it. Thanks for helping! Great work on this btw! amazing stuff.
