### ISSUE TITLE
Bulk selection on /plus page in 0.14

### ISSUE THREAD

**Issue by rwlove** [blakeblackshear/frigate#12340]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to select multiple snapshots and mark all of them as "This is a <object>" or "This is not a <object>".

**Describe the solution you'd like**
UI elements to select multiple and mark as positive or false positive.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by NickM-27** [comment]
the lack of option is deliberate. Doing bulk selection increases the odds that a user submits something incorrectly or does not look at the snapshot in the larger dialog and may miss that something is a true or false positive. This would also complicate things further once frigate+ editing is built in to the frigate webUI

**Comment by NickM-27** [comment]
Once the annotation is built in I imagine this flow will be further improved as well.
