### ISSUE TITLE
Request for Advanced analytics and logging

### ISSUE THREAD

**Issue by borgqueenx** [blakeblackshear/frigate#12356]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have advanced logging and analytics, so i can improve the reliability of frigate as NVR.

**Describe the solution you'd like**
Able to analyse why sometimes footage is unable to play or has not been properly recorded and find out the cause.

**Describe alternatives you've considered**
I check the logs, but this file is extremely short and full of details i do not need.

**Additional context**
Just some tools would be great to improve frigate bug/fault-finding.

**Comment by blakeblackshear** [comment]
Logs are the right tool for this. Any time frigate is unable to keep a recording segment that should be kept according to your config, its going to log an error message and everything it knows about why it failed.

Playback issues are often entirely browser related and Frigate has no idea that failure occurred.
