### ISSUE TITLE
[UI] Missing detect/snapshot/record/audio status in live/all cameras view

### ISSUE THREAD

**Issue by danthel** [blakeblackshear/frigate#12368]
**Describe what you are trying to accomplish and why in non technical terms**
In v13 we had the ability to easily see the status of detect/snapshot/record for each camera and enable/disable them from cameras view.
In v14 we only seem to have recording status in the live/all cameras view, the small red dot (that also seem to be bugged, only visible on 2 out of 8 cameras).

**Describe the solution you'd like**
Reintroduce the detect/snapshot/record & audio icons in the live/all cameras view for easy status overview and manipulation of these settings.

**Comment by NickM-27** [comment]
The red dot indicates is the camera is seeing motion or not. 

All of these toggles are visible on the single camera live view

**Comment by danthel** [comment]
Yes, I'm aware that the toggles are visible on the individual cameras.
If you have a large amount of cameras it is however very inefficient having to go to each camera to see the settings or simply get a good overview of the these settings for all cameras, having the icons available in the live/all cameras view would make it so much easier.
