### ISSUE TITLE
Alternative EdgeTPU Models for Surveillance Cams

### ISSUE THREAD

**Issue by fti7** [blakeblackshear/frigate#1237]
Hi,

i know its not directly related to the Frigate Software since i can swap the used ML Models underneath.
But i really want to ask if someone knows alternative EdgeTPU/TFLITE Models (Free or even Commercial) which are specifically made for Surveillance Cams.
 
Like a very reduced amount of Objects, but which are important for this use case.
e.g. optimized for:
- Infrared Images (The current Model sometimes detects Persons/Ghosts in the Night)
- Optimized Person Detection for Persons which are somehow masked
- Different kind of Weapons (knife, guns etc) (Might be useful for People living in the States)
- Fire
- Water Floods
- Different Kind of (dangerous) Animals 

Thx,
Frank

**Comment by blakeblackshear** [comment]
I haven't seen anything, which is why I am [creating some](https://github.com/blakeblackshear/frigate/discussions/1043)

**Comment by TheSleepySlee** [comment]
Hi Blake, can you clarify which model (& version) is in the latest release?
I see it seems new mobiledet release:
https://github.com/google-coral/test_data/

**Comment by fti7** [comment]
Damn. I didnt checked the Github Discussion Page. Im sorry for that
Sounds really promising. Looking forward to use this service!

**Comment by ozett** [comment]
[found here ](https://github.com/neuralet/neuralet/issues/132)intersting dataset for training: https://researchdata.edu.au/saivt-soft-biometric-saivt-softbio/671976

![image](https://user-images.githubusercontent.com/5937811/140651641-d29e1dc3-24c1-4410-a42f-82c195df0655.png)

**Comment by ozett** [comment]
there is a first model for playing around https://github.com/blakeblackshear/frigate/discussions/1043#discussioncomment-1751636
