### ISSUE TITLE
Green screen

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#1238]
Hi Blake, hope you're well. Its been a long time since we last spoke.

Today i had no other choice but to create a new home assistant setup (a regular sudo apt update last night in ubuntu crashed my whole system and i couldnt recover. this time instead of ubuntu 20.10 i made a fresh install of home assistant os 6.0). And then i restored my home assistant backup. everything works well except my 2nd camera is not working at all. I changed nothing in either the config.yaml or the frigate.yml. its very strange. Its very similar to the issue #1095. So the ONLY difference to my previous setup in which frigate with both cameras were working flawlessly is the OS of the host system. Could this be causing the issue?

FYI - the camera feed is working fine.

![image](https://user-images.githubusercontent.com/30929896/122437376-f1497080-cf99-11eb-8616-04bd56d3c0ed.png)

![image](https://user-images.githubusercontent.com/30929896/122437413-f9a1ab80-cf99-11eb-9be2-aae816318906.png)

![image](https://user-images.githubusercontent.com/30929896/122437789-5604cb00-cf9a-11eb-8c54-b54d549a874e.png)

![image](https://user-images.githubusercontent.com/30929896/122437880-6cab2200-cf9a-11eb-812d-09dc8ac07916.png)

config.yml:

detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
mqtt:
#  host: core-mosquitto.local.hass.io
  host: 192.168.178.125
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: Sike45cem!!99
ffmpeg:
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:KDROSK@192.168.178.209:554/h.264'
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 4
    motion:
      mask: >-
        -0,0,1920,0,1920,1080,1490,1080,1659,694,690,270,121,417,345,1080,0,1080
    detect:
      enabled: true
      max_disappeared: 10
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask: >-
            -2,1,1920,0,1920,1080,1490,1080,1678,653,547,227,533,73,354,86,370,292,116,340,285,1012,680,1014,678,1080,0,1080
    zones:
      car:
        coordinates: 343,1058,1477,1080,1654,683,776,252,123,394

  Package:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:HAEPIT@192.168.178.19:554/h.264'
          global_args: '-hide_banner -loglevel error'
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 4
    motion:
      mask:
        - 0,1080,1433,1080,1920,1080,1405,459,1191,706,993,422,1240,273,1438,492,1920,1080,1920,0,0,0
        - 1680,1080,1920,1080,1920,739,1393,338,1291,391
    detect:
      enabled: true
      max_disappeared: 10
    clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      height: 175
      retain:
        default: 10
        objects:
          person: 15
    mqtt:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      height: 270
    objects:
      track:
        - person
    zones:
      box:
        coordinates: 1240,718,1540,494,1235,252,946,370

database:
  path: /media/frigate/clips/frigate.db
logger:
  default: info
  logs:
    frigate.mqtt: error

**Comment by asemev** [comment]
update: after i updadted the eeprom of the raspberrypi 4 to the latest version, the frigate is now working properly. probably unrelated and its just that stars are aligned now :)

**Comment by mattncsu** [comment]
@asemev FYI-your passwords were in your paste

**Comment by asemev** [comment]
@mattncsu Thank you so much. removed them.
