### ISSUE TITLE
My dog is 95% certain a person...

### ISSUE THREAD

**Issue by huuub** [blakeblackshear/frigate#124]
Just bad luck?
![image](https://user-images.githubusercontent.com/8821259/80088649-1771ad00-855d-11ea-9d2c-6aa9e992b516.png)

**Comment by blakeblackshear** [comment]
If you save that video clip, I can look for ways to filter out these kinds of false positives. I need 30 seconds of footage before that happens. The other way to fix it would be to train your own model, but I haven't done that yet.

**Comment by niemyjski** [comment]
Mine detected my cat as a person 91% I can try getting video but I'd need to crop a lot of things out..
![image](https://user-images.githubusercontent.com/1020579/81574855-f20ddd00-936b-11ea-8a11-0765ec53950a.png).

Any tips on using a custom model with frigate? I want to detect when the food dish is empty.

**Comment by idittansikte** [comment]
I think the best way (most efficient) is to retrain the used model with a custom dataset. I've done that (small dataset of 1000 images recorded with my cctv-camera) and improved the detection with at least 30%. This is a fairly easy (but time consuming creating the dataset) process following the coral guide: https://coral.ai/docs/edgetpu/retrain-detection.

**Comment by Sangoku** [comment]
Any chance we could use double take to retrain our dogs? :D
