### ISSUE TITLE
Cameras - Friendly Name or Title and Sorting of Cameras

### ISSUE THREAD

**Issue by nicoleise** [blakeblackshear/frigate#12400]
It seems odd that this feature request does not exist, but I did search with as many terms as I could think of. Please excuse me, if this is already asked. 

**What?**
I'd like to be able to specify a name, custom title or "friendly name" for each camera in the config file. I'd like this "friendly name" to show in the GUI and to be a part of the payload in MQTT messages pertaining to the camera. 

I'd also like to be able to either specify an order (optional and ideal) or at least to have the alphabetic sorting of cameras done on basis of the friendly name. 

**Why?**
In my native language, we frequently use letters that don't always play well with computers, like æ, ø, å. We also like spaces, dashes or and such, to make stuff easier to comprehend, but that's more of a human thing and less of a locale. 

Naming cameras with spaces and strange letters did not go down well with Frigate in my first setup attempt. Therefore, I've taken to using an English (no funny characters) and computer-friendly (e.g. no spaces) naming convention. This cured any issues, and also allows me to easily double check that the camera name and the path/IP corresponds, since I've systematised the IPs based on the same convention.

This is all fine, but it's not very user friendly. For example, if my wife simply wants to check the driveway, it would be simpler to find a camera labelled "Driveway", and since it's typically the most used camera, it would be nice if it was the first in the list. This could be solved easily by naming it "01 - Driveway", as this maintains readability and alphabetically should place the camera first in the list. But now it's not as computer-friendly with both dashes and spaces, ignoring the fact that Driveway in my language is Indkørsel, with one of those pesky, weird letters. Thus it's likely to provoke errors left and right. 

It may be, that it's a "me-problem" because our house layout is significantly more complex than average, but on the other hand it seems like the ability to assign a friendly name for use in notifications and UI would make sense. And when it's a simple user-defined string rather than the actual name of an entity, it shouldn't cause any grievance. 

I get that this probably hasn't been given much attention seeing as Frigate was never really intended to have it's own GUI, but... well... it does. :)

**Example**
In config, a camera could appear as such:
`CAMe03-West:
    title: "01 - Indkørsel"
    ffmpeg:
      inputs:
      - path: rtsp://user:password@10.10.40.22/live`

Or even better (if also implementing the ability to optionally define a custom order to show cameras):
`CAMe03-West:
    title: "Indkørsel"
    order: 1
    ffmpeg:
      inputs:
      - path: rtsp://user:password@10.10.40.22/live`

I'd then expect to have to refer to this camera through UI, MQTT or whatever as "CAMe03-WEST", but I'd expect than in the UI and in notifications sent to users the camera would be shown as "01 - Indkørsel" in the first example or "Indkørsel" in the latter example, the point being that if no custom order is implemented, I would shift this camera to the first position by naming it 01 at first. And if a custom order is allowed, I wouldn't need the 01, and could simply name the camera what it is showing - the driveway. 

Frigate isn't the easiest of experiences in terms of setup, but I think most of us doesn't mind that very much. The primary issue is whether this complexity is only "behind the scenes" (and thus that it's possible to create a simple UI experience for other users like family members), or if the complexity "forces itself" in to the view of ordinary users. 

So when I open Frigate, the first thing that happens currently is that I'm shown a long list of thumbnails with strange names on them.

**Comment by NickM-27** [comment]
Sorting in the UI is already supported. This is done for the main dashboard as 

```
ui:
  order: 3
```

and in 0.14 the camera groups order is customizable in the UI 

It is recommended to name cameras as driveway_cam for example. In the UI the _ are already converted to spaces.
