### ISSUE TITLE
Cool down timer for RTSP stream not being available

### ISSUE THREAD

**Issue by agrieco** [blakeblackshear/frigate#12438]
**Describe what you are trying to accomplish and why in non technical terms**

Running 0.14.0.beta4.  I don't know if this behavior changed recently or not. 

I have a wyze-bridge up and running and working.  However, one of the wyze-bridge the cameras is down.  As a result, Frigate can talk via RTSP to the wyze-bridge software but the response back is that the camera is not available:
 WRN [rtsp] error="streams: wrong response on DESCRIBE" stream=<streamname>

That is all fine.  However, Frigate seems to loop, continually retrying as fast as possible.    These Warn messages fill the logs.

frigate  | 2024-07-14 12:07:35.038271608  12:07:35.038 WRN [rtsp] error="streams: wrong response on DESCRIBE" stream=<stream>
frigate  | 2024-07-14 12:07:35.064888421  12:07:35.064 WRN [rtsp] error="streams: wrong response on DESCRIBE" stream=<stream>
frigate  | 2024-07-14 12:07:35.169381884  12:07:35.169 WRN [rtsp] error="streams: wrong response on DESCRIBE" stream=<stream>
frigate  | 2024-07-14 12:07:35.194478647  12:07:35.194 WRN [rtsp] error="streams: wrong response on DESCRIBE" stream=<stream>

**Describe the solution you'd like**
Recommend a cooldown option for this situation where there is an exponential backoff up to a configurable max.

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment]
The logs you are showing there are go2rtc logs, you can configure the timeout in the go2rtc config
