### ISSUE TITLE
Show score for events in UI

### ISSUE THREAD

**Issue by tmjpugh** [blakeblackshear/frigate#12494]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to see scores for events displayed in the UI.

**Describe the solution you'd like**
When looking at events at http://FrigateServer:5000/review when I mouse over the events it would be nice to have the event stats displayed like Max Score and detected object.   These details could also be shown as static text above, below or 

**Additional context**
I use frigate score to determine which events should send notification to my phone.  Currently this is impossible to debug based on historical data.  It must be debugged live.  i am looking for a method to look at past events/detection and determine if:
-if was not notified of event that met score
-if I should adjust the score I use for notification
-If I should adjust frigate parameters.  You can use live to adjust this but it is more useful to see result for historical events/detection and make small adjustments over time.  It is a pain to drive a car around home to live debug detection.  Would be more useful if I can look at cars detected in the past and make adjustments.

**Comment by NickM-27** [comment]
This can be done now via the frigate+ screen if enabled. Otherwise this is already implemented for the next version as part of the search screen, and https://github.com/blakeblackshear/frigate/issues/11399 is relevant as well.
