### ISSUE TITLE
Option to show event names when reviewing them

### ISSUE THREAD

**Issue by sebastian-bartkowiak** [blakeblackshear/frigate#12506]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to see name of events when reviewing them (on top of "Live" screen, where preview of last events is displayed, on the "Review" screen and on camera history screen when right sidebar is switched to event mode) so that I can distinguish them more easily.

**Describe the solution you'd like**
I think the description is pretty self-explanatory, maybe one addition - I think it would be good idea to have this option configurable (either with GUI or with YAML), with default of no event names - probably most of the users only have "person" events and showing string "person" with every item would only bring more mess into the GUI.

**Describe alternatives you've considered**
As far as I can see event names are visible when hovering event icon, but that is not really user-friendly, besides not being doable at all on mobile.

**Additional context**
None required, I belive.

**Comment by NickM-27** [comment]
For now this is working as expected, the icons portrait what was detected and can be hovered if clarification is needed
