### ISSUE TITLE
More than 24 hours in timeline scrub 

### ISSUE THREAD

**Issue by spikked27** [blakeblackshear/frigate#12522]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to scrub more than the last 24 hours, I have 30 days recorded but can only scrub up to 24 hours in the past 

**Describe the solution you'd like**
Increase the period of history you can scrub to match the amount of recording you have.  Maybe increase the scrub speed the longer you are scrolling too

**Comment by NickM-27** [comment]
This is working as expected, the timeline is not build for long term scrubbing across multiple days. There will be more views in the future designed for finding what you are looking for and linking to that point in time

**Comment by spikked27** [comment]
Is having a multi day scrub a significant departure from the normal (designed) function of the timeline?  i.e. something that can be user specified via the config potentially?

**Comment by NickM-27** [comment]
Yes, that would require a number of changes to indicate what day you're looking at, faster scrubbing, and other issues in the code that would make it a lot more complicated. It was never designed to work that way, we have plans for more pages / functions in the future
