### ISSUE TITLE
Suggestion: Follow SEMVER

### ISSUE THREAD

**Issue by Teagan42** [blakeblackshear/frigate#12524]
**Describe what you are trying to accomplish and why in non-technical terms**
I want to be able to check the version of Frigate to know whether a release includes breaking changes, minor changes, or patches.

**Describe the solution you'd like**
Version 0.14 brings a complete overhaul of the user interface and introduces breaking changes, but it is released as a `minor` change. Since this project is widely used, it should be considered for release as version 1.0.0.

**Describe alternatives you've considered**
An alternative approach could be to use date-based versions like Home Assistant. Although this provides slightly more informative versioning than the current scheme, it is not as meaningful as semantic versioning (semver).

**Additional context**
That's all.

**Comment by NickM-27** [comment]
The leading 0 means it is in the initial development phase and can have breaking changes at any time

https://semver.org/

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

This is still the case, we do our best to avoid breaking changes but in each of the previous releases there have been breaking changes,  behavior changes, etc.

0.14 is a major step towards something that could resemble a 1.0 release but there are still many things that need to fall into place and other things that need to be reworked before that happens.
