### ISSUE TITLE
Use Frigate+ to Identify false sublabels like you can with labels

### ISSUE THREAD

**Issue by moblsu** [blakeblackshear/frigate#12540]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to mark sub labels in the same way I do labels. IE: "This is not Fedex". I am receiving a lot of false positives for "UPS" and "Fedex". I am not certain the best way to train the model.

**Describe the solution you'd like**
If there can be an additional option in the "Submit to Frigate+" section. Below "This is a car" and "This is not a car", add "This is [SUBLABEL]" and "This is not [SUBLABEL]". Assuming this will help train the model.

**Describe alternatives you've considered**
I currently mark items that are identified with the false positive sublabel as "This is a car" and then go into Frigate+ and verify/submit the image without the "Fedex" label applied. I also mark items that are positive for the sublabel as "This is a car" and then go into Frigate+ to add the "Fedex" sub-label before marking verify/submit.

**Additional context**
I think the above covers it.

**Comment by NickM-27** [comment]
This already exists, you just submit the image and don't mark the logo.

**Comment by NickM-27** [comment]
The reason for this is because the logos don't have their own region so there is no benefit to saying "this is not FedEx" since either way labeling the car and not labeling the logo will train the model.

**Comment by moblsu** [comment]
Apologies, I don’t think I understand your reply. I’ve seen a bounding box around license_plate, I’ve not noticed if there is one around fedex. Are you saying that that data is not tracked and thus there is no way to state “this is not fedex”? I believe I remember seeing an explanation like this before regarding the amount of data required to track individual components within the image, but was not sure if that was the same for this instance.

The second comment “either way labeling the car and not labeling the logo will train the model” is stating that my best option is to do as I am. Where I mark the vehicle “this is a car” and then accept the image in Frigate+ without adding any extra labels for “fedex” or “ups”?

**Comment by NickM-27** [comment]
> Where I mark the vehicle “this is a car” and then accept the image in Frigate+ without adding any extra labels for “fedex” or “ups”?

Yes, that is the correct way

**Comment by moblsu** [comment]
Thank you for the quick response, understood now.
