### ISSUE TITLE
Feature request: Use either substream or main stream for viewing

### ISSUE THREAD

**Issue by mcarson75** [blakeblackshear/frigate#1256]
One feature that Blue Iris has that is very useful is that it uses the substream when viewing multiple cameras and the main stream when you then click on an individual camera.  This maximizes bandwidth efficiency.  I would like to see this feature in the Frigate GUI as well, and even better in Lovelace in Home Assistant.  Currently I have a page in Home Assistant showing all of my cameras from Frigate, but when I click on one to view in detail I still get the low-res substream.  I would love it if I could click on a camera and then see the full-res version.

**Comment by blakeblackshear** [comment]
Do you have the stream component enabled in home assistant? It should already work that way.

**Comment by mcarson75** [comment]
I do have the stream component enabled in Home Assistant.  I am viewing the camera with a picture glance card in Lovelace, which only gives me the low resolution substream if I click on it.  Viewing the entity directly does the same thing - I only get the substream.

My config.yml is set up to use the substream for detection and the main stream for clips.  I do not have rtmp or recording enabled.

How should it be setup to allow Home Assistant to show the sub stream in small views but the main stream when enlarged?

**Comment by blakeblackshear** [comment]
HA uses the RTMP feed from frigate if its available for a higher resolution feed. Just add the RTMP role to the feed you want to display when you click to play in HA.

**Comment by mcarson75** [comment]
I can confirm that this works.  I did notice that I also needed to change the picture glance card to display the "Auto" camera view instead of "Live" or it always displayed the high resolution feed.

Great work on anticipating my feature request in advance!

**Comment by mcarson75** [comment]
I'm going to reopen this because, after playing with this some more, it still isn't what I'm looking for.  HA will use the RTMP feed, yes, but it uses it for everything.  Thus, I have a Lovelace page defined with all six cameras, and if I have RTMP enabled for all of them on the high-res stream, it shows the high-res stream for all six in the one view.  This makes it jumpy and not smooth.  What I would like is for HA to show the low-res stream in the small view, but when you click on the picture glance card (or whatever kind of card I would need to use), only then would it show the high-res view.

If I switch the picture glance card to "Auto" instead of "Live" then it shows the low-res stream in the picture glance card, but it only updates every 10 seconds.  I want to see the live stream in low-res.

**Comment by blakeblackshear** [comment]
That sounds like a Home Assistant feature request.
