### ISSUE TITLE
Add query string "id" to GET /api/review

### ISSUE THREAD

**Issue by lukicsl** [blakeblackshear/frigate#12606]
I want to be able to query review by review id so that I can get reviews by their id.

I am using openhab/habapp to process incomming events in order to generate pushover messages containing thumbnail, snapshot and clip. 
My event trigger is delivered by mqtt getting reviews id. Because of the nature of openhab items an possible race conditions, I would like the to do further processing using GET /api/review once I extract the id from the reviews mqtt message.

**Comment by NickM-27** [comment]
This already exists https://github.com/blakeblackshear/frigate/blob/51a1526146d995734b1c69d863697e91c35725fc/frigate/api/review.py#L97

**Comment by lukicsl** [comment]
You are so fast, the docu is now updated too, 18 mins ago
