### ISSUE TITLE
Add camera name label to pre-loader

### ISSUE THREAD

**Issue by globalenergys** [blakeblackshear/frigate#12634]
**Describe what you are trying to accomplish and why in non technical terms**
I was recently viewing my frigate remotely whilst away, however with the terrible wifi connectivity it took a while to load the camera previews which I had to wait for until I could select the specific camera I wanted to view.

**Describe the solution you'd like**

Adding a camera name label in the preview would allow me to navigate to the camera I'm interested in viewing without having to wait for all of the previews to load.
![frigate](https://github.com/user-attachments/assets/0241b648-28fe-4da8-ae74-f9f6b6b2c680)

**Additional context**
Screenshot attached of the loading screens on bad wifi

**Comment by supermarkert** [comment]
Personally, I'd like the option to see the labels all the time. Currently it only seems to show up when there's an error and no video. 

![image](https://github.com/user-attachments/assets/4ee3a1a5-798a-468f-acf0-e6bf3a9034b1)
