### ISSUE TITLE
An option to change the time format from a 12-hour to a 24-hour clock

### ISSUE THREAD

**Issue by tomerh2001** [blakeblackshear/frigate#12646]
**Describe the solution you'd like**
An option in the setting to select a 24-hour or a 12-hour clock.

<img width="107" alt="image" src="https://github.com/user-attachments/assets/edd34afd-7441-4636-9f24-604043534e87">

I'm from Israel, and here, we're used to using a 24-hour clock and much less a 12-hour AM/PM clock.

I find it annoying to read the time in the timeline, as 08:40 PM is 20:40 for me.

I would very much appreciate an option to select a time format.

+ Bonus: You could also add an option to select the date formats since I write dates as 27/08/2024 instead of 08/27/2024.

**Comment by NickM-27** [comment]
This already exists under `ui -> time_format`

**Comment by tomerh2001** [comment]
> This already exists under `ui -> time_format`

Where? The closest thing I found is this
<img width="410" alt="image" src="https://github.com/user-attachments/assets/85041fdd-3300-4c7c-b00b-88e7139ac17c">

**Comment by NickM-27** [comment]
The setting is only available in the yaml config for now
