### ISSUE TITLE
[HW Accel Support]:Pi5 ffmpeg issue not working all of a sudden, requiring git hub update version or something like that

### ISSUE THREAD

**Issue by Lulugaot** [blakeblackshear/frigate#12655]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/12653

<div type='discussions-op-text'>

<sup>Originally posted by **Lulugaot** July 28, 2024</sup>
### Describe the problem you are having

Ffmpeg error, states no frames, not recording apparently. Still shows cars on dashboard with person detected in zones from two days ago. After finally getting frigate running two weeks ago it ran fine until about two or three days ago with ffmpeg error saying something about going to git hub for update or something. Sorry for not having more detailed info, it took about two or three weeks in getting the hardware and setting it up, installing home assistant, frigate add-on, basic configuration with a lot of Google searches and you tube videos and it finally worked consistently for about two weeks and on July 26 got the ffmpeg errors and now frigate does not work. I have 8GB Pi5, Pi5 official M.2 nvme hat, 1 TB Corsair 2230 MP600 SSD, Google Coral USB, Frigate automation notification add-on. It worked on my Pi3 B V1.2 but stuttered a little when viewing it live, so that's why I bought the Pi5 etc. I repurposed the Pi3 bought and added two 1TB SSD drives and installed them using Open media vault as my NAS on it, which has been working fine. Sorry for the long post. I can't seem to find the answer to this ffmpeg error or if it's going to be updated and when a solution is available as I am going to stop wasting so much time to correct this at the moment. Home Assistant has been fine but I have turned the Pi5 with the frigate add-on off for the time being.

### Version

13.2

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-rpi-64-h264
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

_No response_</div>

**Comment by NickM-27** [comment]
This is not a feature request
