### ISSUE TITLE
Continuous live stream on dashboard without requiring detection

### ISSUE THREAD

**Issue by kensand** [blakeblackshear/frigate#12682]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to have a live stream of all my cameras on my dashboard without requiring that they detect motion to begin streaming.

**Describe the solution you'd like**
I would like to add a toggle either on the settings page or in the config.yml that enables this continuous live stream.

**Describe alternatives you've considered**
Currently my workaround is simply lowering motion detection threshold to 1 so that the cameras are all active all the time, but this isn't ideal for a variety of reasons (more compute required, renders object detection impossible, etc).

**Additional context**
I'm happy to take a crack at a PR for it, Just wanted info on how you would prefer it be implemented before I do so.

**Comment by kensand** [comment]
It looks like the desired effect can be achieved by setting `showStillWithoutActivity`  variable to false in the `LiveDashboardView`.

https://github.com/blakeblackshear/frigate/blob/599dd7eecb9bc3226362740d47a3d1297d17fccd/web/src/components/player/LivePlayer.tsx#L47

https://github.com/blakeblackshear/frigate/blob/599dd7eecb9bc3226362740d47a3d1297d17fccd/web/src/views/live/LiveDashboardView.tsx#L371-L383

Of course we would want a setting toggle for it, but I'll start by setting that to false and building my own image.

Advice on where that setting toggle should reside would be appreciated.

**Comment by NickM-27** [comment]
What's the point of showing a live view when no motion is occurring? It's the same thing as showing the still image except it uses more server resources, bandwidth, etc. 

This is covered in the FAQ as well and I don't think we're looking to add an option for this.

**Comment by kensand** [comment]
There may be motion under the threshold that is still occurring. There may also be motion that is masked but the user still wants to monitor.  Also just ensuring that your cameras are still running is another benefit. 

I don't see any harm in offering the user a setting for this (defaulting to current behavior of course)...

I am happy to do the work to make this change, I was just hoping to get a little input from maintainers as to where that setting should reside to avoid doing extraneous work.

**Comment by kensand** [comment]
Another counterpoint is: Why offer recording full time if no motion is detected?

https://docs.frigate.video/configuration/record#most-conservative-ensure-all-video-is-saved

**Comment by NickM-27** [comment]
For now this can be achieved by configuring birdseye to use continuous mode and creating a dashboard with birdseye as the camera. This is much more efficient to stream than each camera individually.

> There may be motion under the threshold that is still occurring. There may also be motion that is masked but the user still wants to monitor.  

These both sound like cases where a camera is not configured correctly according to a users desires for what is considered interesting motion.

> Also just ensuring that your cameras are still running is another benefit. 

The UI shows alerts in the status bar and an error image over the camera when it is not running correctly. 

> I don't see any harm in offering the user a setting for this (defaulting to current behavior of course)...

Because it's not just an option. We also have to ensure that the UI works well with this option enabled. We already have had to make a number of optimizations due to issues when a high number of cameras were live, especially when using jsmpeg instead of restreaming. This would further that problem. It's also another option that we'd need to maintain as more changes are made to the UI. 

> Another counterpoint is: Why offer recording full time if no motion is detected?

Sometimes it is required when filing a police report, the recording has to be continuous and can't have any cuts which is feedback we've received many times for users running continuous recording.

**Comment by kensand** [comment]
> For now this can be achieved by configuring birdseye to use continuous mode and creating a dashboard with birdseye as the camera. This is much more efficient to stream than each camera individually.

Individual cameras cannot be resized to a user's preference in birdseye mode. Also, it may be more efficient in terms of bandwidth, but spinning up an additional FFmpeg process to stitch together the cameras themselves is not more efficient in terms of CPU usage.

> These both sound like cases where a camera is not configured correctly according to a users desires for what is considered interesting motion.

Interesting motion is different from slow motion. Whether a user chooses to set the threshold high should be up to them and independent of whether the live stream plays continuously.

> The UI shows alerts in the status bar and an error image over the camera when it is not running correctly.

Sure, fair enough, although a camera could feasibly be still providing a stream without the image changing due to some hardware malfunction.

> Because it's not just an option. [...] It's also another option that we'd need to maintain as more changes are made to the UI.

It is a ~30 line change without much complexity added; I'll have a PR for you shortly. If you still choose to ignore it, so be it, I guess I'll have to maintain my own fork.

> We also have to ensure that the UI works well with this option enabled. We already have had to make a number of optimizations due to issues when a high number of cameras were live, especially when using jsmpeg instead of restreaming. This would further that problem.
   
It would be set to the current functionality by default; if a user is experiencing optimization issues, they have successfully shot themselves in the foot. I will include a warning about that in the setting description within my PR.
 
Sometimes functionality is going to beyond a server's capacity. This is already a consideration, as I am sure you are aware. Whether that threshold is reached faster or slower because of user configuration is not something you can try to control. I appreciate the optimization that has been done to the UI, I really do, but to limit user configurability in the name of optimization doesn't make sense.

**Comment by NickM-27** [comment]
> Individual cameras cannot be resized to a user's preference in birdseye mode. Also, it may be more efficient in terms of bandwidth, but spinning up an additional FFmpeg process to stitch together the cameras themselves is not more efficient in terms of CPU usage.

the CPU usage of birdseye is less than the CPU usage of restreaming each of those cameras in go2rtc, especially as the number of cameras goes up.

> Sometimes functionality is going to beyond a server's capacity. This is already a consideration, as I am sure you are aware. Whether that threshold is reached faster or slower because of user configuration is not something you can try to control. I appreciate the optimization that has been done to the UI, I really do, but to limit user configurability in the name of optimization doesn't make sense.

it is not about optimization in the sense that users shouldn't be able to do something if it isn't perfectly optimized. But we can't offer an option that doesn't work well for half of users, because then we will get lots of support requests / bug reports and this takes up our time that could be spent on new features. We have only had a couple users leave feedback to request an option for this, the majority of the feedback we have received about this has been that the switching is really well done and works smoothly.

Feel free to get other maintainers opinions are if you submit a PR 👍

**Comment by kensand** [comment]
Created discussion #12697 to follow up. If anyone is looking for more info on this feature, please discuss it there.

**Comment by Social-Loafer** [comment]
How can I make this change? I very much prefer to see my cameras running consistently.

**Comment by NickM-27** [comment]
You'll need to wait for 0.16

**Comment by Social-Loafer** [comment]
Thank you much!

**Comment by Joloxx9** [comment]
> You'll need to wait for 0.16

So 0.16 is here(RC1) but I am not able to see thatnoption anywhere?

**Comment by NickM-27** [comment]
See the release notes https://github.com/blakeblackshear/frigate/releases/tag/v0.16.0-rc1

**Comment by Joloxx9** [comment]
> See the release notes https://github.com/blakeblackshear/frigate/releases/tag/v0.16.0-rc1

Thank, I found only the option to create additional group and set it up in it, does that mean there are no option for such thing in the standsrd one?

**Comment by hawkeye217** [comment]
Yes, [as the docs indicate](https://deploy-preview-16390--frigate-docs.netlify.app/configuration/live/#streaming-options-on-camera-group-dashboards), you should use a camera group to customize any of the streaming settings.
