### ISSUE TITLE
Option to disable events at top of live view in 14+

### ISSUE THREAD

**Issue by lygris** [blakeblackshear/frigate#12685]
**Describe what you are trying to accomplish and why in non technical terms**
I would like a setting to disable the past event clips at the top of the new cameras page. I usually left birdseye up to keep on eye out for amazon or other packages and would only look when a stream would pop up. I like the new camera view but with the gifs constantly moving my eyes are constantly drawn to the screen for motion. I think enough people would benefit from an option for this.

**Comment by NickM-27** [comment]
Only unreviewed alerts show at the top. If something is showing there that is not important to you, then you likely don't have alerts configured correctly. Or you can just mark it as reviewed and it won't show.

There is already an option to disable the gif if you only want there to be an image.
