### ISSUE TITLE
Record snasphot with one stream and detect with another

### ISSUE THREAD

**Issue by Pascal66** [blakeblackshear/frigate#1269]
Is it possible ?

ie there's no snapshots roles like for clips

**Comment by blakeblackshear** [comment]
No. Frigate only decodes the detect stream, so snapshots must be created from the stream with detect assigned.

**Comment by Pascal66** [comment]
Thank you.
So I've to detect with the main stream 1920x1080 to have a full snapshot.
But (for me) the second stream 640x360 is enough for detection, the cpu usage and for the bandwith
And not for the snapshot :)
