### ISSUE TITLE
Deleting Recordings

### ISSUE THREAD

**Issue by deputyd0ng** [blakeblackshear/frigate#1270]
My recordings folder is 2+TB, I have removed the recording option in my config and restarted the container, but it does not seem to be deleting any of my recordings.

I am running frigate on unraid with a coral USB, I would like to purge all of my recordings, I cant manually delete them in explorer, and theres no management in the webui.

How can I purge the recordings?  Going forward I just want to use clips.

**Comment by ElMoribond** [comment]
With such a problem you should provide, at a minimum, your configuration file.
The answer to your question is probably in [doc](https://blakeblackshear.github.io/frigate/configuration/cameras/#247-recordings).
You should probably read it again.

**Comment by blakeblackshear** [comment]
I would set the retain for recordings to 1 day and they should get cleaned up. You can try 0 days, but I am not sure if that will work.

**Comment by hunterjm** [comment]
> I would set the retain for recordings to 1 day and they should get cleaned up. You can try 0 days, but I am not sure if that will work.

0 days works (have used it before in testing)

**Comment by Henke19822** [comment]
I can see that this issue have been closed due to inactivity. I do think I experience the same thing as I have a rentention period of 1 day, but have a lot of older stuff in my library.

**Comment by githubDiversity** [comment]
I can second that setting the retain to 0 does not help using the current stable version.

`record:
  enabled: True
  events:
    retain:
      default: 0

snapshots:
  retain:
    # Required: Default retention days (default: shown below)
    default: 0
    # Optional: Per object retention days
    objects:
      person: 0
`

then save and restart and the storage is still showing ;


Recordings & Snapshots | 4.62 GB | 7.17 GB

I will purge the host folders completly and start over but I am not sure that might have unintended side effects

**Comment by NickM-27** [comment]
> then save and restart and the storage is still showing ;
> 
> Recordings & Snapshots | 4.62 GB | 7.17 GB

That is showing storage usage of the enitire drive not what Frigate is using specifically

**Comment by githubDiversity** [comment]
yes you must be correct as I just completly purges the host folders related to frigate and started over by downloading a fresh docker image of frigate.

still



Recordings & Snapshots | 4.05 GB | 7.17 GB
-- | -- | --


This is not intuitive for new users I'd guess.
Is that really intended to work like this? If so what would be the rationale behind it?

**Comment by Waank1** [comment]
I am having the same issue, it may be because I mapped a network drive to \\media (on host machine) so I could easily delete large groups of files instead of one at a time using Media.  I have tried everything including deleting and reinstalling Frigate.
