### ISSUE TITLE
Review timeline/events option for 24 hours format

### ISSUE THREAD

**Issue by mx-vatte** [blakeblackshear/frigate#12701]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to toggle the review timeline/events time format between AM/PM and 24 hours format so that I can choose the time format that I'm used/located to. 

**Describe the solution you'd like**
An additional toggle switch to choose between AM/PM and 24 hours time format inside the general settings. Maybe below Calendar with the headline Time format.

**Describe alternatives you've considered**
I searched inside git if there is already a solution or feature request.

**Additional context**
Not in scope yet.

**Comment by hawkeye217** [comment]
This is already possible via an option in your frigate config file. 

`ui -> time_format`
