### ISSUE TITLE
Adding Object Counter and Tracker

### ISSUE THREAD

**Issue by charithmadhuranga** [blakeblackshear/frigate#12708]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to  count the objects for particular class and track their path in particular region  I have mark.

**Describe the solution you'd like**

In the ui given the options to draw a region in the camera feed and add a counter to selected classes.Also a option to add tracker like botsort,bytetrack or deepsort in the ui  for selected classes

**Comment by NickM-27** [comment]
this already exists. all zones have a count and this information is published via MQTT

**Comment by NickM-27** [comment]
Frigate already does object tracking as well
