### ISSUE TITLE
Mask & Zone Creator not working

### ISSUE THREAD

**Issue by Pascal66** [blakeblackshear/frigate#1271]
Describe the bug:

On Chrome or Firefox  it is not possible to create masks or zones using the frigate mask & zone creator.
Clicks on the image aren't recognised, no points can't be set.
Not working in home assistant integration
Not working in web ui port 5000

Version of frigate
 0.8.4-5043040

Just this error in console :
```
Uncaught TypeError: e is undefined
    g http://192.168.1.36:5000/dist/routes/CameraMap.KpZNo76OKHnm.js:14
    Preact 73

```

**Comment by Pascal66** [comment]
Resolved.

**Comment by Homas** [comment]
On 0.9 RC5 I see the same issue (Chrome, Safari, Firefox on MacOS). 

Chrome:
`CameraMap.-LxSn76V-_-H.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'reduce')
    at Object.clickfalse (CameraMap.-LxSn76V-_-H.js:14)
    at HTMLDivElement.ne (preact.module-ff55218f.bKiDWaS-1sUZ.js:1)`

Firefox:
`Uncaught TypeError: e is undefined
    m http://192.168.45.114:5000/dist/routes/CameraMap.-LxSn76V-_-H.js:14`
