### ISSUE TITLE
Static objects "re-detected" after periods without motion detected

### ISSUE THREAD

**Issue by brewtangclan** [blakeblackshear/frigate#1273]
**Describe the bug**
Static objects (e.g., parked vehicles) are detected as new when motion is detected after long periods (several seconds) without motion.

**Version of frigate**
0.8.1-D376F6B

**Computer Hardware**
 - OS: Jetson Nano (2GB) Developer Kit Firmware
 - Install method: Docker Command
 - Virtualization: Docker
 - Coral Version: USB (x2)
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Amcrest
 - Model: IP8M-T2599EW
 - Resolution: 4k
 - FPS: 5

**Additional context**
It seems that the lack of motion / object detection not being run is interpreted as "no objects detected",  beyond the "max_disappeared" threshold, causing Frigate to treat the previously-detected objects as no longer present. Next motion event (unrelated to the object in question) triggers object detection, which detects the object.

Ideally, when there are "active" object detections (still present as of the last time object detection was run) but no motion, to either infer that any detected objects are still present at the location they were last detected, or not count motionless/detectionless frames toward the max_disappeared threshold.

**Comment by blakeblackshear** [comment]
This is by design in the current version. There are already several related issues open.

**Comment by arshsingh** [comment]
Is there any way to differentiate stationary objects in the event data? I've setup notifications with home-assistant, but if there's a car parked in the driveway it keeps sending notifications for it every few minutes.

**Comment by blakeblackshear** [comment]
Not really. The best option for now is discussed here: https://github.com/blakeblackshear/frigate/discussions/1128
