### ISSUE TITLE
Calculating time specific object have been in the specific zone

### ISSUE THREAD

**Issue by charithmadhuranga** [blakeblackshear/frigate#12746]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to  calculate the time specific object have been in a specific zone.

**Describe the solution you'd like**
timer function  can be enable or disable for specific zones for specific objects.all data can be access through mqtt events

**Comment by NickM-27** [comment]
This is already possible via /events and /reviews in MQTT. I think it would be better to understand the use case to see if there is a need for something more specific to be implemented

**Comment by charithmadhuranga** [comment]
how can I calculate the time.Can you give some guidance

**Comment by charithmadhuranga** [comment]
I am trying to profile suspicious people hanging around my land.If someone suspicious hanging long time around my property it will inform me with a snapshot and how many time they spend there

**Comment by NickM-27** [comment]
This is already supported with the loitering time feature in 0.14
