### ISSUE TITLE
Space in camera name

### ISSUE THREAD

**Issue by noelhibbard** [blakeblackshear/frigate#1275]
Is it possible to have a space in the camera name? I tried this syntax:
```
cameras:
  "Back Porch":
```

It sort of works but I see some log output that isn't good:
```Argument 'Porch-20210624015106.mp4' provided as input filename, but '/media/frigate/recordings/Back' was already specified.```

Seams these are some places that handle the space okay but not others.

Seems like something like this would be a better solution:
```
cameras:
  back_porch:
    nickname: "Back Porch"
```

Then it could use back_porch in the filesystem, API and database and the only place the "nickname" would be used would be the WebUI.

**Comment by blakeblackshear** [comment]
It is easy enough to translate `back_porch` to `Back Porch` programmatically. The integration already does that in many places within home assistant.

**Comment by noelhibbard** [comment]
@blakeblackshear I haven't loaded HA yet so I wasn't aware of that. Thanks
