### ISSUE TITLE
Authentication session revocation

### ISSUE THREAD

**Issue by FusselTV** [blakeblackshear/frigate#12756]
**Describe what you are trying to accomplish and why in non-technical terms**
When I delete a user account or change its password in the new user management system for the authenticated port, the current session of a user who is already logged in with the old password or a deleted account should be invalidated.

**Describe the solution you'd like**
Ideal Solution:
After a user’s password is changed or the user is deleted, the user should be redirected to the login screen and there is a session overview:
![WhatsApp Image 2024-08-04 at 16 38 15](https://github.com/user-attachments/assets/a813d4d7-646c-4331-a064-6aa82208b8c9)

**Describe alternatives you've considered**
I understand that the ideal solution might be complicated to implement due to the need for constant checks if the user is still authenticated or the implementation of events. Additionally, there are many other features that would bring more benefits to Frigate than an over-engineered authentication process.

It would be sufficient if, when a password is changed or a user is deleted, a notification appears (similar to the notifications when you export a clip) informing that after the next restart, every user will need to re-authenticate.

**Additional context**
With reliable session revocation implemented, the authenticated port could be used to expose Frigate directly via a reverse proxy to the internet. My previous solution was setting up Authelia for authentication. Without this feature, I wouldn't feel comfortable exposing Frigate directly through this port because I can’t be sure if there is still an authenticated session on some computer. Also, when a user should no longer have access, they can still access the cameras.

**Comment by blakeblackshear** [comment]
You already have complete control over this with the existing implementation. 

The following config will ensure the user still exists in the database every minute when the token is refreshed:

```yaml
auth:
  session_length: 300
  refresh_time: 240
```

**Comment by blakeblackshear** [comment]
You can also always regenerate your JWT secret token which will instantly invalidate all sessions.

Just delete the `.jwt_secret` file in your config directory and restart.

**Comment by FusselTV** [comment]
What disadvantages would there be when this token is automatically rotated? When any password for any user is changed, this would already accomplish a session revocation for all users.

**Comment by blakeblackshear** [comment]
I'm not entirely sure what your question is. The downside to refreshing the token more often is that it requires more frequent database calls to ensure the user is still valid.

**Comment by FusselTV** [comment]
My original issue request was to invalidate all user sessions when the password for the user is changed. If I understood correctly, there is already a system with JWT tokens. So theoretically, it could be implemented to rotate the token when a password is changed, and then all active sessions would be invalidated. This would be a nice security feature and provide ease of use to the user because they wouldn't need to know that they have to delete the secret file.

**Comment by billksun** [comment]
@FusselTV I think you might have misunderstood the reference between JWT tokens and the JWT secret token (or just JWT secret).

If I understand correctly, when you login, you are issued a JWT token which allows you to remain logged in for the lifetime of the session specified in `session_length`. This JWT token is generated using the JWT secret. When you delete a user, that user will need to re-authenticate when the `session_length` is reached. I'm not sure about a password reset (depends on implementation).

When you rotate the JWT secret, it invalidates the JWT token from _all users_, not just the sessions belonging to one user. This will force _all_ users to re-authenticate.

So I think for your use case, shortening the `session_length` (while keeping `refresh_time` to a shorter value) is the best way to force users re-authenticate sooner than later. Again, I'm not sure if a password reset invalidates the JWT token, but you should be able to test it out easily.
