### ISSUE TITLE
Re-add download buttons to new (0.14) UI

### ISSUE THREAD

**Issue by PripyatAutomations** [blakeblackshear/frigate#12763]
**Describe what you are trying to accomplish and why in non technical terms**
A few of my cameras unfortunately output h.265 video which cannot be changed. My usual solution was to just download the clip and view it if snapshot was interesting

**Describe the solution you'd like**
Maybe I missed this - but I'm not seeing any way to download clips/snapshots directly without going into export. Could this be re-added in the new UI?

**Comment by NickM-27** [comment]
You can export any review item by right clicking or time period using the export button. It is then possible to download from there.

**Comment by NickM-27** [comment]
Downloading directly was inefficient and caused problems for users, exports is the way to do this.
