### ISSUE TITLE
Deep link to Review for a particular camera

### ISSUE THREAD

**Issue by rgregg** [blakeblackshear/frigate#12776]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to create a bookmark/URL that takes me to the Review page with a particular camera selected so that I can easily jump to reviewing information for specific cameras. I could do this in 0.13, but now in 0.14 it always defaults to All Cameras and there don't seem to be query parameters to let you specify the camera to show when the page loads.

**Describe the solution you'd like**
I'd like to have an easy way to bookmark / link to the Reviews page with a particular camera selected. Ideally, the browser URL would refresh when I change the camera selection in a way that was obvious, perhaps with ?camera=foo appended to the URL. Then bookmarking this link would allow me to quickly jump to review the events for the same camera.

This is also part of my HA configuration - I have buttons that launch the Frigate UI for each camera - worked great in 0.13 but now these URLs land back on the default page in 0.14 and there don't seem to be easy ways to set them up again.

**Comment by ikout** [comment]
From what I can see that's available, all you need to do is add the Camera name as a Hashtag.
ie. http://<IP>/#camera_name

**Comment by NickM-27** [comment]
That's live view not review

**Comment by nwish** [comment]
I’d love to see this too, but with the added functionality to generate a link to a specific review item, so that it can be easily shared.

**Comment by hasnaat-k** [comment]
This still isn't possible? I can't link to a reviewed clip

**Comment by hawkeye217** [comment]
> This still isn't possible? I can't link to a reviewed clip

Click on the gray chip in the corner of a Review item and use the Share button in the Review Item Details pane.

**Comment by hasnaat-k** [comment]
> > This still isn't possible? I can't link to a reviewed clip
> 
> Click on the gray chip in the corner of a Review item and use the Share button in the Review Item Details pane.

That's fair, didn't know that was a thing.

I guess my only concern now is: using that link for sharing isn't very useful to give to people who are not users within Frigate as it will send them to the login page.

Do you think there's something that can be done with these shared links to be accessible through a closed-off public facing view?

**Comment by NickM-27** [comment]
I think it would make sense to do that, feel free to make a feature request

**Comment by hasnaat-k** [comment]
I have created the feature request
https://github.com/blakeblackshear/frigate/issues/19003
