### ISSUE TITLE
Plugin system to extend the frigate functions and detectors

### ISSUE THREAD

**Issue by charithmadhuranga** [blakeblackshear/frigate#12780]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to add my own custom detectors or functions as a plugin to frigate  

**Describe the solution you'd like**

Like in the home assistant custom component that can load as a plugin in to frigate to extend the capabilities  or add new feature to frigate

**Comment by NickM-27** [comment]
This already exists as the community supported detectors. https://docs.frigate.video/development/contributing-boards
