### ISSUE TITLE
[Feature] Object Tracking

### ISSUE THREAD

**Issue by ukrolelo** [blakeblackshear/frigate#1278]
Whouldn't it be nice if there was additional menu option unber (Cameras,Event,Debug) Lets say object tracking?

It would show the cameras which have detected objects with live feeds.
Lets say you have 8 cameras around the house, now you need to click on each and look or go see events.
If it could automaticaly show/hide the cameras which detected object and just put on the screen :)
So when i go around the house, it would just hide/show the cameras where i am.

**Comment by blakeblackshear** [comment]
Duplicate of #338
