### ISSUE TITLE
Export Event Directly?

### ISSUE THREAD

**Issue by moogoos** [blakeblackshear/frigate#12802]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to export the event that I am watching, or the event that I am reviewing 

**Describe the solution you'd like**
When reviewing an event based on a tag, like, "bark". I would like to click the export button and be able to export that exact event. Not sure this is possible as I think the event is just a time in a timeline and not its own artifact.

**Describe alternatives you've considered**
None

**Additional context**

[Image](https://imgur.com/a/8MsmN3k)

**Comment by hawkeye217** [comment]
You can export a review item directly already. See question 6 in the Usage FAQ. https://github.com/blakeblackshear/frigate/discussions/12724

**Comment by moogoos** [comment]
Thanks had no idea that was there
