### ISSUE TITLE
Can't start docker container: disk I/O error

### ISSUE THREAD

**Issue by robcos** [blakeblackshear/frigate#1280]
**Describe the bug**
A clear and concise description of what your issue is.
```
 * Starting nginx nginx
   ...done.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
```

** docker script **
```
docker run -d \
  --privileged \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  -v $CONF/media:/media/frigate \
  -v $CONF/config:/config \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='password' \
  -p 5000:5000 \
  -p 1935:1935 \
  blakeblackshear/frigate:stable-amd64
```

**Version of frigate**
Output from `/api/version`

blakeblackshear/frigate:stable-amd64

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
logger:
  default: debug
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
mqtt:
  host: duboce
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: MacOs
 - Install method: Docker Command
 - Virtualization:Virtualbox
 - Coral Version: None
 - Network Setup: Wifi

**Additional context**

**Comment by blakeblackshear** [comment]
The sqlite database is stored in the media/clips folder. This error is usually related to a permissions issue or because you are using a network drive. Can you tell me more about what the location on the host machine is like for this volume mapping? 
```
-v $CONF/media:/media/frigate
```

**Comment by robcos** [comment]
```
@Mac-Pro:~/src/docker/homeassistant:master$ chmod -R g+w frigate/media/
@Mac-Pro:~/src/docker/homeassistant:master$ chmod -R o+w frigate/media/
@Mac-Pro:~/src/docker/homeassistant:master$ sh frigate.sh 
 * Starting nginx nginx
   ...done.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
@Mac-Pro:~/src/docker/homeassistant:master$ ls -al frigate/media
total 0
drwxrwxrwx  4 robcos  staff  128  9 May 16:13 .
drwxr-xr-x  4 robcos  staff  128  9 May 16:13 ..
drwxrwxrwx  5 robcos  staff  160  9 May 16:14 clips
drwxrwxrwx  2 robcos  staff   64  9 May 16:13 recordings
@Mac-Pro:~/src/docker/homeassistant:master$ ls -al frigate/media/clips/
total 128
drwxrwxrwx  5 robcos  staff    160  9 May 16:14 .
drwxrwxrwx  4 robcos  staff    128  9 May 16:13 ..
-rw-rw-rw-  1 robcos  staff  32768  9 May 16:13 frigate.db
-rw-rw-rw-  1 robcos  staff  32768 25 Jun 14:14 frigate.db-shm
-rw-rw-rw-  1 robcos  staff      0  9 May 16:14 frigate.db-wal
@Mac-Pro:~/src/docker/homeassistant:master$ ls -al frigate/media/recordings/
total 0
drwxrwxrwx  2 robcos  staff   64  9 May 16:13 .
drwxrwxrwx  4 robcos  staff  128  9 May 16:13 ..
```

**Comment by robcos** [comment]
The folders are writables (as you can see) as there are some files in it.

**Comment by robcos** [comment]
Any ideas on what can be wrong? I can't figure out how to debug this

**Comment by blakeblackshear** [comment]
This is the home directory on the primary disk of your Mac?

**Comment by coledeck** [comment]
I am having the same issue when using a `9p` virtio filesystem in a VM (underlying filesystem being shared is BTRFS). Directory is fully writable, and every file is 777 permissions (for testing) but still no.

By creating a new directory on the 9p filesystem and using that one instead, frigate will work exactly once, then after a reboot of the container or VM leads to the same error again.

**Comment by jpstach** [comment]
@robcos Did you ever resolve this? I am having the same issue. I have tried many different permissions settings on my /media/frigate directory to no avail.

**Comment by robcos** [comment]
Nope

**Comment by dewgenenny** [comment]
I'm experiencing this issue too :( Anyone have tips?

**Comment by goshi0** [comment]
Ok Here in the same boat, first a description
trying to run frigate into a docker inside a proxmox vm wich is also running a OMV instance, OMV manages a JBOD where is the destination volume of /media/frigate

things I have tried and didnt work:

- I am using stable, but the last beta shows the same error
- change all permission of mounted folders -> no changes
- also i tried to mount the volume in a non related frigate dir and check permissions, all ok and even created a dummy sqlite db wich a can edit without problem.
things I have tried and worked 

  - If you dont pass the volume, frigate works perfectly :

example 
```
frigate:
    container_name: frigate
   # privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0-beta2
    shm_size: "64mb" # update for your cameras based on calculation above
    #devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/dockers/frigate/config/config.yml:/config/config.yml:ro
      - /srv/5fba792b-8c5a-4e2e-9572-66ea9ec631f2/Camaras:/media/frigate
      #- /srv/5fba792b-8c5a-4e2e-9572-66ea9ec631f2/Camaras:/prueba
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5001:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

Posible workaround, dont pass the media dir, and when the docker launches exec it and mount the media dir via nfs, also if you dont store clips it will work without problem.

Thank you and sorry 

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:43:25] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:43:25] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:43:25] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:43:32] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:43:32] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:43:32] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:43:38] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:43:38] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:43:38] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:43:46] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:43:46] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:43:46] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:43:53] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:43:53] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:43:53] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:44:01] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:44:01] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:44:01] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:44:13] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:44:13] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:44:13] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:44:25] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:44:25] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:44:25] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:44:45] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:44:45] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:44:45] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:45:18] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:45:18] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:45:18] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:46:16] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:46:16] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:46:16] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:47:22] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:47:22] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:47:22] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:48:29] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:48:29] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:48:29] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:49:35] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:49:36] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:49:36] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:50:42] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:50:42] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:50:42] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:51:48] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
disk I/O error
Starting migrations
[2022-06-09 23:51:48] peewee_migrate                 INFO    : Starting migrations
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-06-09 23:52:55] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)
Starting migrations
[2022-06-09 23:52:55] peewee_migrate                 INFO    : Starting migrations
[2022-06-09 23:52:55] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
disk I/O error
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by Shurov** [comment]
As a (IMO) proper workaround - mount the DB file separately on the host itself (not the network share as the clip recordings), it can be somewhere near the `config.yml` file.
I have the following mappings:
```
./config.yml:/config/config.yml
./frigate.db:/media/frigate/frigate.db
/mnt/nvr/clips:/media/frigate/clips
/mnt/nvr/recordings:/media/frigate/recordings
```
Just make sure to create beforehand the file named `frigate.db` on the host in the mounting location. Otherwise docker will mount it as a folder and not as a single file by default.

**Comment by blakeblackshear** [comment]
There are specific recommendations in the documentation for this: https://docs.frigate.video/installation#storage

**Comment by F0rged** [comment]
> As a (IMO) proper workaround - mount the DB file separately on the host itself (not the network share as the clip recordings), it can be somewhere near the `config.yml` file. I have the following mappings:
> 
> ```
> ./config.yml:/config/config.yml
> ./frigate.db:/media/frigate/frigate.db
> /mnt/nvr/clips:/media/frigate/clips
> /mnt/nvr/recordings:/media/frigate/recordings
> ```
> 
> Just make sure to create beforehand the file named `frigate.db` on the host in the mounting location. Otherwise docker will mount it as a folder and not as a single file by default.

I had the same issue.  Running Frigate in Docker on top of proxmox, with a mounted zfs volume.  I do have open media vault running and its hosting files from the same zfs partition and pool etc, but that volume is just mounted straight up..

In any case, mounting the clips, recordings and frigate.db individually seemed to solve that particular issue.  Now Im running into a strange storage space issue but looks like theres a separate thread for that.

**Comment by XtremeOwnageDotCom** [comment]
Wouldn't exactly call it a proper fix- but.... 

Deleting everything and restarting it fixes it.... until the next update breaks it, or another random corruption issue breaks it.... or, it just breaks again....

**Comment by balbee9** [comment]
I'm still a rookie to github but i was able to fix this on my set up. I have mergerfs running on my host and I had to remove the direct_io option from /etc/fstab. After that, I was able to use the mounted directory.

**Comment by ObjectiveTruth** [comment]
I had this issue and indeed doing individual volume mounts helped (I'm using cifs shares). 

However, then instead of Disk I/O error, I got a message from ffmpeg "no space left on device".
Turns out my disk quota was set too low and indeed my share was full.. oops 😄

**Comment by mpeter50** [comment]
I have ran into the same issue after I moved all Frigate data from the super-constrained storage of the VM where it runs, to my storage array thats accessible through a virtiofs mount.

It seems the problem is that sqlite does not like when you want to use a WAL-mode database through network, or such virtual filesystems: https://sqlite.org/forum/forumpost/6a0e396a2b8aa8e56001ddc1c618b90bee37465b7f47dc978f456b71d9525949
I havent found whats the reason for it, maybe its that virtiofs does not provide full support for file locking ([1](https://lists.gnu.org/archive/html/qemu-devel/2022-01/msg03280.html), [2](https://github.com/yt-dlp/yt-dlp/issues/6823)), but thats not important.

Whats important is that such databases must stay local, meaning inside the VM/original system, and not be used through a network or virtiofs mount. As the above forum post suggests, [Jellyfin docs](https://jellyfin.org/docs/general/administration/storage/) also mention at the very beginning that the database file must stay local.

@blakeblackshear considering the traffic under this issue, would you please consider to mention this limitation of the database file somewhere [here](https://docs.frigate.video/frigate/installation/#storage)? It may be useful to have the database path override config option be mentioned too.

Finally, my solution was to keep the volume that stores `/config` stay in the VM. It does not take that much space anyway. Just dont forget when making backups that not everything is stored on your main storage array..
