### ISSUE TITLE
Select more than one day when reviewing

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#12808]
**Describe what you are trying to accomplish and why in non technical terms**
When I want to filter on a camera + zone + object type it would be great to be able to select a larger time span than 24 hours. In the calendar popup, being able to select more than one day (just like when booking a flight/hotel room).
Why - Cause ive got issues with badgers, deer and other wild life that is destroying my garden. And by filtering this way I would quickly get an overview on where and how the damage to my property happened. And - a plus for me, when I am away being able to review certain zones + objects in a zone for a larger duration than 24 hours.

**Describe the solution you'd like**
Selecting a greater time span that 24 hours. Like this:
![image](https://github.com/user-attachments/assets/bcad03e7-0e04-4678-8210-d36f3dd97c26)

**Describe alternatives you've considered**
Selecting every day, applying the filters and review. More clicks :)

**Additional context**
One offender eating my peas :)
![image](https://github.com/user-attachments/assets/96dc7e7b-3599-4c52-a0c1-49c44a7c1af6)

**Comment by NickM-27** [comment]
This is done intentionally, the timeline and other features don't work well across multiple days. There is a separate view already implemented for 0.15 that will allow searching of objects across larger periods of time.

**Comment by StingerTopGun** [comment]
Not beeing able to see more that 24h at a time is quite inconvenient for me too.
I only have one camera with low frequency of events, sometimes 0 events a day.

In the past i just quickly scrolled through the "Events" page every few days to check what was happening.
Now i need to manually click through every single day on the calendar to see the alerts.

I'm looking forward to the new view in 0.15, hopefully it can help me quickly review the alerts of multiple days at once.

But still, Frigate is one heck of a NVR, thanks!

**Comment by v4u6h4n** [comment]
I would also appreciate being able to review more than 24 hours of footage at a time. I have to manually scrub through the previous 24 hours of footage every day, but I can't reliable start the review at the same time each day, so I have to switch days back and forth to make sure all the footage has been reviewed, which is quite clunky.

Perhaps a compromise that does not impact performance, if that is the main issue, would simply be to add a down or up arrow button to the start and end of the current timeline that would just jump you to the same timestamp in the previous/next day. This would skip needing to navigate to the day in the calendar, then scroll down to the same position manually.
