### ISSUE TITLE
Notifications without Homeassistant

### ISSUE THREAD

**Issue by Slanistaw** [blakeblackshear/frigate#12813]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to recieve notifications without the need of Homeassistant or any other need of mqtt. It would be nice to get notifications to pushover or telegram etc.

**Describe the solution you'd like**
A possibility to use curl commands when object is detected with a directlink to the event. That would give users many choices of platform to use.

**Comment by NickM-27** [comment]
This is already implemented for 0.15 using web push. If you want notifications through other services you should use https://github.com/0x2142/frigate-notify
