### ISSUE TITLE
Time format in UI

### ISSUE THREAD

**Issue by 7floor** [blakeblackshear/frigate#12834]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to view times everywhere in UI using format I'm used to, i.e. in a 24-hour format instead of 12-hour AM/PM. Like, 17:43 instead of 5:43 PM.

**Describe the solution you'd like**
Either allow browser to format time / toLocaleTimeString() /, or allow it to be configured (similar to 1st day of week that is configurable already)

**Describe alternatives you've considered**
None

**Additional context**
Frigate 14.0

**Comment by NickM-27** [comment]
This is already supported via the time_format config option

**Comment by hawkeye217** [comment]
```
ui:
  time_format: 24hour
```
