### ISSUE TITLE
Frigate 0.14 : keep thumbnail/snapshot for exported event in the export tab, generate thumbnail for clips exported from timeline

### ISSUE THREAD

**Issue by hafx** [blakeblackshear/frigate#12865]
**Describe what you are trying to accomplish and why in non technical terms**
In the "review" tab we have a thumbnail for each event with the image of the person/cat/dog/etc. provides a good indication of what triggered the event.

**Describe the solution you'd like**
I would like to keep this thumbnail also when we export the event as well. Because once exported, the thumbnail is no longer the image with the person/cat/dog/etc.

**Additional context**
I have also no thumbnail for clips exported from timeline manually. For example sometimes a person should be detected and I have no record for this event, I don't know why but in this case I have to export manually from the timeline if I want to keep a record.
![no thumb](https://github.com/user-attachments/assets/98f4f470-2a3b-4a80-ba02-e2e3aec16fe8)

**Frigate version**
I just upgraded from 0.13 to 0.14

**Comment by NickM-27** [comment]
If you have exported after using 0.14 and there is no thumbnail that would be a bug.

I did think about using the review item thumbnail when implementing this feature, but didn't end up doing that. I think it does make sense though.

**Comment by hafx** [comment]
Thanks a lot for adding the feature I requested. I really appreciate your hard work on this!
