### ISSUE TITLE
Adjust dashboard for cameras that are not 16:9

### ISSUE THREAD

**Issue by PilaScat** [blakeblackshear/frigate#12882]
![image](https://github.com/user-attachments/assets/a843c94c-fc8c-40ba-81af-b654fdcf170d)

**Comment by NickM-27** [comment]
There's no way to avoid wasted space at some place when mixing cameras with different aspect ratios. This is working as expected

**Comment by rockenrooster** [comment]
I am having this same issue. The UI forces everything to "snap" to a grid. Can we disable this grid snapping? I have a mix of 16:9 and 4:3 cameras and all my 4:3 cameras have black bars causing so much wasted space

**Comment by rockenrooster** [comment]
@PilaScat 

See my comment here about a workaround to fix this issue: https://github.com/blakeblackshear/frigate/issues/12620#issuecomment-2781207381
