### ISSUE TITLE
Docker dev container fails - missing documentation - ( release-0.9.0 )

### ISSUE THREAD

**Issue by Sinamics** [blakeblackshear/frigate#1289]
**Describe the bug**
Trying to run the docker dev container ( release-0.9.0 ), but it fails. 
I have cloned frigate to /opt in my windows WSL with ubuntu, i then start the composer up or "vscode open in container", but it fails with message
```yaml
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
ERROR: Service 'dev' failed to build
```

I also tried to change the dockerfile in docker-compose to `dockerfile: docker/Dockerfile.base` , but it fails as well:
```yaml
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "blakeblackshear/frigate-ffmpeg:-amd64": invalid reference format
ERROR: Service 'dev' failed to build
```

**Version of frigate**
release-0.9.0

**Computer Hardware**
 - Windows WSL-Ubuntu
 - vscode with remote ext.
 - Docker v20.10.5
 
 
 Any documentation on how to start the dev container properly would be much appreciated.

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/contributing.md

**Comment by Sinamics** [comment]
Totalt missed that one.
Just spinned up the container and everything is working just fine. 

Thank you.
