### ISSUE TITLE
Home Assistant Add-on 

### ISSUE THREAD

**Issue by niemyjski** [blakeblackshear/frigate#129]
Is there any plans into making this available via a home assistant add-on? I was starting to look into this but didn't know if someone already had this working

**Comment by blakeblackshear** [comment]
I plan to make an official one eventually. Someone created an unofficial and posted it in this thread: https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/814

Not sure if it works well.

**Comment by niemyjski** [comment]
Amazing thanks for that! I'll try and do pr's to his GitHub repo and maybe he can transfer it to a frigate org :-)
