### ISSUE TITLE
Expose the number of alerts/detections pending review to Home Assistant

### ISSUE THREAD

**Issue by PHLAK** [blakeblackshear/frigate#12907]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to access the number of alerts/detections pending review in Home Assistant so that I can display these on my dashboard and/or use them in automations.

**Describe the solution you'd like**

Exposing numbers sensor with the number of pending alerts and detections to Home Asssistant via the Frigate add-on (e.g. `number.alerts_to_review` and `number.detections_to_review`).

**Describe alternatives you've considered**

Possible alternative sensor names could be `number.pending_alerts` and `number.pending_detections` respectively.

**Additional context**

N/A

**Comment by NickM-27** [comment]
this will be decently complicated as we'll essentially need to update MQTT any time the review items are added or marked as review from anywhere. and will get even more complicated once per-user reviews are added.

**Comment by d-steve** [comment]
In the meantime, you can pull this from the Frigate API via a RESTful sensor (https://www.home-assistant.io/integrations/sensor.rest/)

Example config for unreviewed alerts, polled once a minute
```
 - platform: rest
    resource: http://<homeassistant:5000>/api/review?reviewed=0&severity=alert
    timeout: 5
    scan_interval: 60
    name: frigate_alerts_unreviewed
    unique_id: frigate_alerts_unreviewed
    method: GET
    value_template: "{{ fvalue_json|length }}"
```
