### ISSUE TITLE
When viewing a Camera, choosing Settings->Camera settings should default to the camera being viewed

### ISSUE THREAD

**Issue by supermarkert** [blakeblackshear/frigate#12904]
**Describe what you are trying to accomplish and why in non technical terms**
When I'm viewing a camera, often I want to adjust Zones or do some Debugging. When I choose Settings -> Camera Settings, it always defaults to the first camera in my list. So I always have to go to the menu in the upper right and choose the camera I was just vieweing.

**Describe the solution you'd like**
I'd like it to default to whatever camera I was viewing. If I wasn't viewing a camera, then it can default to the first camera

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by immkg** [comment]
I have added the PR https://github.com/blakeblackshear/frigate/pull/13159 which implements the change.
