### ISSUE TITLE
Quick link buttons & bounding boxes to review UI

### ISSUE THREAD

**Issue by ristoavila** [blakeblackshear/frigate#12919]
**Describe what you are trying to accomplish and why in non technical terms**
The new UI is awesome! The concept of alert & detections is really nice.

I'm only missing one feature which is to enable detection boxes and entry / exit / events of the detections when reviwing the videos. Similar how the old viewing used to be.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment]
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/11399
