### ISSUE TITLE
HAOS intergration addon issue

### ISSUE THREAD

**Issue by robbyzg** [blakeblackshear/frigate#1294]
**Describe the bug**
Frigate NVR works excellent, no errors, detects and records clips and snapshots.
Addon installed through HACS, everything was working fine for 2 days, after that cameras that were created by addon per object dont refresh snaps anymore.
They are stuck on snaps from 2 days ago. In the folder new clips/snaps are regularly created and can be viewed through SMB and web interface.
What gives?!
No errors in the logs.
Also at the same time automation to the app stopped working.
Any help/opinions?!

**Version of frigate**
0.8.4-5043040

**Config file**

```mqtt:
  host: 192.168.1.189
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

cameras:
  street:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.1.14:554/Streaming/Channels/101
          roles:
          - detect
          - clips
        #- path: rtsp://admin:pass@192.168.1.14:554/Streaming/Channels/102
          #roles:
          #- clips
    width: 2688
    height: 1520
    fps: 5
    #best_image_timeout: 15
    clips: 
      enabled: True
      pre_capture: 5
      post_capture: 5
      retain:
        default: 1
    objects:
      track:
      - person
      - dog
      - cat
      - bird
    snapshots:
      enabled: True
      timestamp: True
      retain:
        default: 1
      
detect:
  max_disappeared: 25
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
    
```

**Frigate container logs**
```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera street has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 38
frigate.app                    INFO    : Camera processor started for street: 42
frigate.app                    INFO    : Capture process started for street: 43
detector.cpu2                  INFO    : Starting detection process: 40
```

**Frigate stats**
```{
  "detection_fps": 5.9, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 56.21, 
      "pid": 38
    }, 
    "cpu2": {
      "detection_start": 1624807892.655874, 
      "inference_speed": 58.02, 
      "pid": 40
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 4156.6, 
        "mount_type": "tmpfs", 
        "total": 4169.5, 
        "used": 12.9
      }, 
      "/media/frigate/clips": {
        "free": 15177.5, 
        "mount_type": "ext4", 
        "total": 62659.6, 
        "used": 44909.2
      }, 
      "/media/frigate/recordings": {
        "free": 15177.5, 
        "mount_type": "ext4", 
        "total": 62659.6, 
        "used": 44909.2
      }, 
      "/tmp/cache": {
        "free": 4097.4, 
        "mount_type": "tmpfs", 
        "total": 4169.5, 
        "used": 72.0
      }
    }, 
    "uptime": 1320, 
    "version": "0.8.4-5043040"
  }, 
  "street": {
    "camera_fps": 5.0, 
    "capture_pid": 43, 
    "detection_fps": 5.9, 
    "pid": 42, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }
}
```

**Computer Hardware**
 - OS: HA
 - Install method: Official
 - Virtualization: Proxmox
 - Coral Version: None
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Hikvision
 - Model: DS-2CD2143G0-I
 - Resolution: 2688*1520
 - FPS: 5

**Comment by blakeblackshear** [comment]
> cameras that were created by addon per object dont refresh snaps anymore

The addon doesn't create any entities. The integration creates entities. What is the name/entity_id of the camera that isn't updating?

**Comment by robbyzg** [comment]
> > cameras that were created by addon per object dont refresh snaps anymore
> 
> The addon doesn't create any entities. The integration creates entities. What is the name/entity_id of the camera that isn't updating?

none of these
camera.street_bird
camera.street_dog
camera.street_cat
camera.street_person

camera.street works fine and updates as far as i see without any issues.

only the ones that should be syncing with new taken snapshots per object are not!
as i mentioned, snapshots and clips are taken and can be accessed through interface or smb without any issues.

**Comment by blakeblackshear** [comment]
Those entities are updated via MQTT. Do the switches created for turning on/off detection, snapshots, and clips work? Are other MQTT messages working for notifications?

**Comment by robbyzg** [comment]
I reinstalled MQTT and its updating again. Thank you for your prompt help. I want to say huge thank you for this project, you project is so good that i am leaving behind BI. Thank you!
