### ISSUE TITLE
FR: Have number keys be a keyboard shortcut for PTZ Presets.

### ISSUE THREAD

**Issue by Kev1000000** [blakeblackshear/frigate#12959]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to trigger PTZ presets using the numbers on my keyboard as quick shortcuts.

**Describe the solution you'd like**
Pressing "1" on keyboard invokes the first preset, "2" preset 2, and so on.  

**Describe alternatives you've considered**
Using the num keys 1-9 would of course limit you to only shortcut to 9 presets, but I don't think most folks are going to have more than 9 presets normally.

**Comment by wootapa** [comment]
This would be really nice. Blue Iris is doing this and it works great. It also does "," and "." for previous and next camera.
