### ISSUE TITLE
Timelapse Export

### ISSUE THREAD

**Issue by xekil** [blakeblackshear/frigate#12957]
Hello, 

I used to do timelapse exports over a given period, I could see in the changelog that Timelapse is no longer available in the UI but the API is still available. 

How to use it to do an export ?

Thanks in advance

**Comment by NickM-27** [comment]
this is not a feature request

**Comment by xekil** [comment]
and if I modify my question can you add the timelapse export?

**Comment by NickM-27** [comment]
This is covered in the FAQ, if you create a discussion question we'd be happy to help show you how to use the API for this

**Comment by xekil** [comment]
Ok thank you
