### ISSUE TITLE
Allow other camera views when scrubbing/reviewing

### ISSUE THREAD

**Issue by sshaikh** [blakeblackshear/frigate#12966]
**Describe what you are trying to accomplish and why in non technical terms**
I want to add footage from other cameras when reviewing an event (or even scrubbing through history) so I can see alternative contexts while reviewing footage.

**Describe the solution you'd like**
Be able to select a camera group or camera and add them to the current view.

**Describe alternatives you've considered**
At the moment we have to check a time stamp on one camera and then manually check it on another.

**Additional context**
None

**Comment by hawkeye217** [comment]
This is already the way History view works. When reviewing historical footage, your other cameras will show as smaller thumbnails. To switch to another camera, simply click or tap it. 

See the [guided demo](https://app.supademo.com/showcase/clvi4jyof0kpfh7gr9921vsb7) and this [helpful walkthrough video from a user](https://www.youtube.com/watch?v=iJa3dNEO5qQ).

**Comment by sshaikh** [comment]
Got it - the other cameras seem to disappear depending on screen size so I missed them during my testing.
