### ISSUE TITLE
Turn off the review at the top of the Live Dashboard

### ISSUE THREAD

**Issue by SteveRMann** [blakeblackshear/frigate#12964]
**Describe what you are trying to accomplish and why in non technical terms**
If it's in the docs, I can't find it.
How do I turn off the review at the top of the Live Dashboard?

**Describe the solution you'd like**
The review at the top of the Live Dashboard is very annoying and distracting.  If there is nothing moving in the cameras, seeing a constant review of prior motion detected is extremely distracting. Where is the option to turn this off?

**Describe alternatives you've considered**
Don't use Frigate.  I am using the custom Frigate card in Home Assistant, but it's slow and sometimes cameras go offline. The Frigate app  is much more stable.

**Comment by hawkeye217** [comment]
The filmstrip on the Live dashboard cannot be disabled. If it's too distracting, you can go to Settings --> General and turn off the "Show Alerts Video" switch to show a thumbnail instead of a looping video.

**Comment by NickM-27** [comment]
Only alerts show up in the filmstrip. If you find the things that show up at the top not important then that may indicate that the config should be adjusted for what is an alert
