### ISSUE TITLE
m.2 coral support

### ISSUE THREAD

**Issue by mcristina422** [blakeblackshear/frigate#1297]
**Describe the bug**
When running in a docker container on a host where the coral is installed as a m.2 device Frigate fails to load. The [install instructions](https://coral.ai/docs/m2/get-started/#2a-on-linux) appear to have a few extra drivers needed.

I think the differences are `gasket-dkms` and section 3.
>If the user account you'll be using does not have root permissions, you might need to also add the following udev rule, and then verify that the "apex" group exists and that your user is added to it:
```
sudo sh -c "echo 'SUBSYSTEM==\"apex\", MODE=\"0660\", GROUP=\"apex\"' >> /etc/udev/rules.d/65-apex.rules"
sudo groupadd apex
sudo adduser $USER apex
```

**Version of frigate**
0.8.4

**Frigate container logs**
```
frigate    | frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate    | frigate.edgetpu                INFO    : No EdgeTPU detected.
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
frigate    |     delegate = Delegate(library, options)
frigate    |   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
frigate    |     raise ValueError(capture.message)
frigate    | ValueError
frigate    | 
frigate    | During handling of the above exception, another exception occurred:
frigate    | 
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate    |     self.run()
frigate    |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate    |     self._target(*self._args, **self._kwargs)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
frigate    |     object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
frigate    |   File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
frigate    |     edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
frigate    |   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
frigate    |     raise ValueError('Failed to load delegate from {}\n{}'.format(
frigate    | ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate    | 
frigate    | frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...

```

**Comment by blakeblackshear** [comment]
Are you saying that after installing the driver on the host, it still doesn't work? Several others are running these versions of the Coral without issues.

**Comment by engineeringw4r** [comment]
My M.2 coral is working fine on a Jetson Nano 4GB.  I did install the driver in the host per the coral website.  My frigate docker compose file has:
     devices:
      - /dev/apex_0:/dev/apex_0

Note:  While the M.2 coral supports to TPU units...the Jetson PCIe M.2 only supports 1.

**Comment by mcristina422** [comment]
@blakeblackshear thanks for confirming this works for others, I couldn't tell in my searches

Ah, sorry, after looking at this with fresh eyes @engineeringw4r pointed it out and I never mounted the device into the container, but even with this added I still get the same error log

```
devices:
- /dev/apex_0:/dev/apex_0
```

On the host I have the driver installed and can run the [example](https://coral.ai/docs/m2/get-started/#4-run-a-model-on-the-edge-tpu) so I'm not sure what I'm overlooking. This is an x86 PC with it installed as a m.2, a USB coral works fine with frigate on my PI4

**Comment by mcristina422** [comment]
Ah, oops, you need to define which [detector](https://blakeblackshear.github.io/frigate/configuration/detectors) to use. After adding this to my frigate config it works!
```
detectors:
  coral1:
    type: edgetpu
    device: pci:0
```

**Comment by jasonmhite** [comment]
@mcristina422 Which version of the Coral m.2 board were you using? The one with a single Coral or the one with two?

I have the dual version and I'm trying to get it working with the Jetson Nano 4Gb as well but I'm not having any luck. I know I can't use both with the Jetson's m.2 slot, but I thought it was supposed to still work as a single.
