### ISSUE TITLE
Exports: Sort by creation time, not alphebetically

### ISSUE THREAD

**Issue by ItsMeRitch** [blakeblackshear/frigate#12986]
**Describe what you are trying to accomplish and why in non technical terms**
When I look at the export page, I want to see my exports with the latest one at the top and oldest at the bottom, not alphabetically. 

![Screenshot 2024-08-12 at 12 33 55](https://github.com/user-attachments/assets/7344d2e4-facb-4d71-a5f9-1f413f646eb4)

In the screenshot, I have just exported the bottom and top export respectively.

**Comment by hawkeye217** [comment]
You're running Frigate 0.13. Exporting has been improved in 0.14, the current stable version of Frigate. You can rename exports and thus sort them however you would like.

**Comment by ItsMeRitch** [comment]
@hawkeye217 Thank you!
