### ISSUE TITLE
Have ability to delete exported clips from iOS (browser or  HASS app)

### ISSUE THREAD

**Issue by leonbrag** [blakeblackshear/frigate#13001]
It appears the only way to delete exported clip is using desktop browser. Delete button shows on mouse hover. 
![image](https://github.com/user-attachments/assets/df956ca1-1bb6-4758-bccc-0f83d6b3d4a3)

It appears that with Frigate HASS integration or using browser, there is no way to delete exported clip. There is only ability to download exported clip to device.

can this be added?
thanks

**Comment by NickM-27** [comment]
This is already fixed
