### ISSUE TITLE
Support for base_url config option to move frigate off the server "/" location

### ISSUE THREAD

**Issue by bdoiron74** [blakeblackshear/frigate#13006]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to host frigate behind a reverse proxy, and a path of my choosing. For example, I would like:

http://localhost/frigate

However, as much as I try, I cannot get frigate to stop loading resources from the wrong path as it expects to find everything at "/"

**Describe the solution you'd like**

grafana has a config option 'root_url' that I set to 'http://localhost/grafana'
nodered has 'httpNodeRoot' that I set to '/nodered'
got2rtc  has a 'base_path' option that I set to "/go2rtc"

**Describe alternatives you've considered**
I could not find a similar option in the reference config for frigate. I did try using sub filtering within my nginx location config, but wasn't able to get it to work.

**Additional context**

**Comment by NickM-27** [comment]
This is already supported, there have also been recent fixes for auth when running it this way https://github.com/blakeblackshear/frigate/discussions/12814

**Comment by bdoiron74** [comment]
Some additional comments:
- I'm proxying the unauthenticated port if that matters (:5000)
- I'm using docker-compose, image: ghcr.io/blakeblackshear/frigate:stable

If this is supported, how do I configure the base url?

Maybe add a note to [this page](https://docs.frigate.video/guides/reverse_proxy/) that describes how to set a base url for various installation methods?

**Comment by bdoiron74** [comment]
found the answer [here](https://github.com/blakeblackshear/frigate/discussions/3996)
