### ISSUE TITLE
snapshot viewing

### ISSUE THREAD

**Issue by ivanjx** [blakeblackshear/frigate#13018]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to view the snapshots like in the older 0.13

the current ui only shows one person in case the detector detects multiple people at the same time.

**Describe the solution you'd like**

**Describe alternatives you've considered**
HA integration can still show the snapshots but i hate that ui very much.

**Additional context**

**Comment by hawkeye217** [comment]
Snapshots have been deprecated in the 0.14 UI. See the [FAQ](https://github.com/blakeblackshear/frigate/discussions/12724), Usage question 8.

**Comment by ivanjx** [comment]
well i have 2 zones called inside and outside. inside zone has alert. sometimes there are one person on each zone at the same time and frigate for some reason picks the outside person as thumbnail for the alert view.

so thats the reason then. i still consider this a downgrade.

**Comment by ivanjx** [comment]
> but also less helpful than having a combined thumbnail and easy to view video preview that quickly shows what exactly happened

this is wrong. the thumbnail will only show one person but actually there could be more person or dogs moments later and completely missed. i know you can preview quickly with a mouse hover... but iphones and androids do not have mouse cursor.

maybe there should be an indicator or something that multiple objects are present in a single item.

**Comment by NickM-27** [comment]
> but iphones and androids do not have mouse cursor.

on mobile you can swipe to the right to view the same thing

**Comment by NickM-27** [comment]
if multiple objects are visible and active at the same time, the thumbnail do its best to include all of them

**Comment by ivanjx** [comment]
who would have known...

**Comment by hawkeye217** [comment]
> > on mobile you can swipe to the right to view the same thing
> 
> who would have known...

To be clear, this is mentioned in the release notes.

> The new Review area implements a scrollable grid of thumbnails alongside a timeline where a hover or swipe begins a preview playback.

**Comment by ivanjx** [comment]
imo a good ui is a ui that is not obscure in any way. writing it in a release not is not an excuse most non technical people do not read release notes anyway.

**Comment by hawkeye217** [comment]
Thanks for your feedback.

**Comment by ivanjx** [comment]
it might be an oversight but on ios the very quick preview does not work (it just displays a still image). maybe because ios limits the playback speed to 2x on safari engine.

**Comment by NickM-27** [comment]
we already handle that, it works fine in our testing on iOS including my iPhone and iPad

**Comment by ivanjx** [comment]
hmm maybe frigate does not detect the browser correctly? i use vivaldi and embedded home assistant web view and they both fail but it works fine on safari.

**Comment by ivanjx** [comment]
i know but i think the detection should be iphone or ios instead of just safari on ios. i just downloaded chrome but even it also fail to play the quick preview.

**Comment by NickM-27** [comment]
viewing previews works fine on my iPhone using the chrome browser

**Comment by ivanjx** [comment]
tried everything still no luck. chrome on ios just does not want to play it. here is my chrome's user agent:

`Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/127.0.6533.107 Mobile/15E148 Safari/604.1`

any chance that you are in the EU and using the non webkit chrome?

**Comment by NickM-27** [comment]
No I am in the US, and it works on current hour as well as previous hour previews for me

**Comment by ivanjx** [comment]
is it possible to not merge different objects in the same camera if the zones arent the same?

**Comment by NickM-27** [comment]
No, multiple review items can not exist during the same period of time and this is working as designed.

**Comment by ivanjx** [comment]
but they are on different zones and most of the time they dont cross between each zones. please do not ignore the zones because they exist for a reason. unless im misunderstanding how zones work.

**Comment by NickM-27** [comment]
Because the activity that occurred was designated by you as a user. This way you only review each period of time once and in the timeline a period of time can only be an alert or detection not both. Everything becomes more complicated with what you're suggesting.

**Comment by ivanjx** [comment]
but my alert designation is only for a specific zone and frigate still includes other zones unnecessarily.

imagine if alert zone has a person for 5 secs and then 2 seconds later after the person left there are constant people walking for 5 minutes straight. the alert would now be 5+ minute.

i have the clip with me right now but wont share for obvious reason.

**Comment by NickM-27** [comment]
It could also be the same person doing yard work and going on / off camera. It's still valid. If it was marked as an alert then something worthy of an alert occurred. This is working as intended because again, only reviewing a period of time once was one of the main principles of the new UI. 

This won't be changing. Perhaps the thumbnail selection can get smarter in the future.

**Comment by ivanjx** [comment]
yea thats a valid case but in my case nothing was on the alert zone after the person already left and the alert clip keep recording to accommodate the non alert zone activity.

but yea at least pick the object from the actual alert zone for the alert clip instead of picking the last one (or however it is programmed now).
