### ISSUE TITLE
[Feature Request] - Specify DB location

### ISSUE THREAD

**Issue by D34DC3N73R** [blakeblackshear/frigate#1302]
**Describe the feature**
Would it be possible to store the db files somewhere besides /media/frigate/clips/? I like to store my clips in an encrypted cloud mount, and my rclone copy script pauses when files are in use, so naturally, it gets hung up on the db files. I've tried manually passing each db file as separate volumes, but that still creates 0 byte files in /media/frigate/clips/. 

**Version of frigate**
N/A

**Config file**
N/A

**Frigate container logs**
N/A

**Frigate stats**
N/A

**FFprobe from your camera**
N/A

**Screenshots**
N/A

**Computer Hardware**
N/A

**Camera Info:**
N/A

**Additional context**
N/A

**Comment by blakeblackshear** [comment]
https://blakeblackshear.github.io/frigate/configuration/advanced#database

**Comment by D34DC3N73R** [comment]
Thanks, I must have missed that.
