### ISSUE TITLE
Secrets Management and Masking

### ISSUE THREAD

**Issue by jared-bloomer** [blakeblackshear/frigate#13026]
**Describe what you are trying to accomplish and why in non technical terms**
I would like the ability to mask credentials and other secrets in my config.yml as to not expose any secrets in my configuration file. 

**Describe the solution you'd like**
An Example would be instead of having plain text credentials in an rtsp stream URL I could interject Secrets instead so that

this
`rtsp://username:password@192.168.0.2:554`

becomes this
`rtsp://!secret[username]:!secret[password]@192.168.0.2:554`

**Describe alternatives you've considered**
Docker Secrets could in theory be used But it is still not the most secure way to go about secrets management. I would prefer the secrets file be encrypted so that it can be comitted to a git repo or someplace more public without being readable. Something like Ansible-Vault is a good example of this. 

**Additional context**
N/A

**Comment by NickM-27** [comment]
this is already possible https://docs.frigate.video/configuration/#environment-variable-substitution
