### ISSUE TITLE
[Feature Request] Add possibility to define storage for clips/recordings (on NAS)

### ISSUE THREAD

**Issue by Tokn59** [blakeblackshear/frigate#1304]
Is your feature request related to a problem? Please describe.
No issue except clips take up a lot of space after a while

Describe the solution you'd like
The possibility to store all Frigate media on a NAS via a share (?) I use Synology.
Describe alternatives you've considered
Not really found one yet, manual copy is not an optimal solution

Additional context
Add a folder location ? Share ? FTP ?

**Comment by blakeblackshear** [comment]
Can you provide the information about your setup requested in the issue template? Your options depend on how you run frigate.

Others using synology do it like this: https://github.com/blakeblackshear/frigate/discussions/1047

**Comment by mcarson75** [comment]
Not the OP, but this is one of the reasons I am still using Blue Iris for 24/7 storage of clips.  I have a 500GB SSD that I run the OS on, with a 2TB spinny disk.  Blue Iris initially stores videos on the SSD, and then moves them to the hard drive before finally deleting the oldest.  These are defined by space, not by time, so I can be sure I don't run out of space - I allocate 300GB on the SSD and 1700GB on the hard drive for instance.

Frigate doesn't currently have a way to manage storage across multiple drives like this.

**Comment by blakeblackshear** [comment]
HassOS doesn't provide a way to mount a network drive for frigate to use. You have to move the entire data partition to another drive: https://github.com/home-assistant/operating-system/blob/master/Documentation/partition.md#using-datactl-to-move-the-data-partition

**Comment by Tokn59** [comment]
Thank you. That's a way but not for what I intended to do (store clips and recordings on NAS) but I understand this is due to HASSOS limitations as you describe. Maybe I can write some script that accesses the Frigate data from a PC and moves the files to NAS via a share. Not sure ... Anyway .. thank you for sharing this great piece of software ! Very impressive ! I do notice it doesn't like cats (they are always identified as dogs) (smiley)

**Comment by trythatagain** [comment]
Not a complete answer, but I run frigate in a docker and use the following for my volumes:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/trythat/appconfig/frigate:/config #/config.yml:ro
      - /media/main/frigate/recordings:/media/frigate/recordings
      - /media/small/frigate/clips:/media/frigate/clips 
 As you can see I use 2 different drives, seems to be working well.

**Comment by omayhemo** [comment]
> HassOS doesn't provide a way to mount a network drive for frigate to use. You have to move the entire data partition to another drive: https://github.com/home-assistant/operating-system/blob/master/Documentation/partition.md#using-datactl-to-move-the-data-partition

I'd like to see something like this added to the add-on.
Here's an example of another add-on that links to a UNC
https://github.com/thomasmauerer/hassio-addons/tree/master/samba-backup

**Comment by alnavasa** [comment]
I am running Home assistant on a VM with just 128GB of space, 

However, I also have a Synology NAS were I would like to store frigate clips, 
I don't plan on installing frigate on that Synology NAS OS.

Would it be possible? 

I don't think it is a strange request, considering many users use low power low storage solutions for Home assistant and also have a NAS at home.

I have already moved the backups of home assistant to be automatically performed to a samba share device (Synology NAS) so I HA can do backups to a samba share, I guess it can also store video recordings. 

I am also planing on moving the database from HA to that Synology NAS (which its possible to be done since I have already read others have done it)

**Comment by scadaguru** [comment]
> Not a complete answer, but I run frigate in a docker and use the following for my volumes: volumes: - /etc/localtime:/etc/localtime:ro - /home/trythat/appconfig/frigate:/config #/config.yml:ro - /media/main/frigate/recordings:/media/frigate/recordings - /media/small/frigate/clips:/media/frigate/clips As you can see I use 2 different drives, seems to be working well.

I like this idea to have two different drives, one for clips and another for recordings. Hopefully this undocumented feature will not break in future!

**Comment by blakeblackshear** [comment]
It's already not a feature in the latest version. There are no longer any mp4 files created for clips. It's all just recordings.
