### ISSUE TITLE
[debugging feature request] Record clip with bounding box

### ISSUE THREAD

**Issue by Pascal66** [blakeblackshear/frigate#1305]
Bounding box in stream.
Permit to create zones and "max_area" "min_area" in 1 mn

**Comment by blakeblackshear** [comment]
The bounding boxes are in the mjpeg stream.

> Permit to create zones and "max_area" "min_area" in 1 mn

I have no idea what you mean by this.

**Comment by Pascal66** [comment]
Can I record this stream ?

**Comment by blakeblackshear** [comment]
You can use ffmpeg to record it by using frigate's mjpeg endpoint as an input. This cannot be done directly in frigate, and I have no plans to add this functionality.

**Comment by LucaZiegler** [comment]
It would be a nice feature, when in a recoding motions have these boxes like in the snapshots, so it's easier to see.
