### ISSUE TITLE
[FR] Optionally save motion frames to filesystem

### ISSUE THREAD

**Issue by fl42** [blakeblackshear/frigate#13067]
Hello,

**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to save to filesystem motion frames sent to detectors.
This would help to collect a set of frames seen by the AI model, which ultimately can facilitate fine-tuning or other improvements to the model.

**Describe the solution you'd like**
A configuration option for saving frames sent to detectors in a local folder.
Ideally, frames would be saved to `{save_path}/{camera_name}/{label}/{timestamp}.jpg`
Where `{label}` is the label returned by the detector (e.g. person, car), or `no_detection` if the detector has returned no object.

As we generally expect there to be many more `no_detection` than detections, it would be useful to be able to randomly select a part of the negative samples rather than saving them all.

In term of implementation, adding a code [here](https://github.com/blakeblackshear/frigate/blob/f6b61c26ae0a17e4e6e8e4d74f0491281f62ad88/frigate/object_detection.py#L70) could do the job (asynchronously to avoid slowing down the detection pipeline?).

**Describe alternatives you've considered**
Perform full-time recording and run Frigate's motion detection algorithm to extract motion frames from the recorded segments.
This would require running Frigate's motion detection algorithm outside Frigate, which can be tricky?

**Additional context**
I don't know if this should be integrated into Frigate, or if it's more appropriate to build a script external to Frigate that reads the recorded segments and extract the motion frames from them?
One advantage of an external script is that it allows different motion detection parameters (threshold, contour area) to be easily tested on the same video, which could help to select the best parameters.
What is your opinion?

If a do a PR for the feature (either as integrated into Frigate or ad-hoc script), any chance to get it merged? ;)

Thank you for this awesome project!

**Comment by NickM-27** [comment]
this will use way too many resources to be something that runs by a config option. As someone who has done this often to debug different things while developing, there are way too many frames to be useful and it is often necessary to apply some kind of filter inside of the code to be able to only have files written for frames that meet certain conditions. 

This should be done externally or via development / code changes

**Comment by fl42** [comment]
In that case, you absolutely must not integrate it into Frigate.
I'm going to develop an ad-hoc script for that.
I'd be happy to make a PR to reference the script in the documentation if anyone wants to try it out!

Thank you for the quick reply.
