### ISSUE TITLE
[Feature Request] HTTP request on detection

### ISSUE THREAD

**Issue by Christofo** [blakeblackshear/frigate#1307]
The ability to have an HTTP request fired off when there is a detection would be fantastic. I currently use Synology Surveillance Station and Homebridge with homebridge-camera-ffmpeg. Both of these allow events to be triggered via a HTTP request.

**Comment by blakeblackshear** [comment]
You should be able to use Nodered or Homeassistant to make http calls based on the mqtt topics.

**Comment by Christofo** [comment]
That is a good option. It would be great to have it right in Frigate, to reduce complexity and any delay in the automation.

I created this: https://github.com/Christofo/sssAI a while back to address the common complaint of Surveillance Station motion detection being quite bad. Frigate is a MUCH better option though.
