### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by roofuskit** [blakeblackshear/frigate#131]
Getting a slew of errors when I start Frigate. Camera is streaming find and I can test it with VLC. 

```
/arrow/cpp/src/plasma/store.cc:738: Disconnecting client on fd 7


On connect called


/arrow/cpp/src/plasma/store.cc:1226: Allowing the Plasma store to use up to 0.4GB of memory.


/arrow/cpp/src/plasma/store.cc:1253: Starting object store with directory /dev/shm and huge page support disabled


Camera_process started for test: 20


Starting detection process: 19


Starting process for test: 20


ffprobe -v panic -show_error -show_streams -of json "rtsp://192.168.1.35:8554/stream"


 * Serving Flask app "detect_objects" (lazy loading)


 * Environment: production


   WARNING: This is a development server. Do not use it in a production deployment.


   Use a production WSGI server instead.


 * Debug mode: off


{'error': {'code': -111, 'string': 'Connection refused'}}


Process Process-2:


Traceback (most recent call last):


  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap


    self.run()


  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run


    self._target(*self._args, **self._kwargs)


  File "/opt/frigate/frigate/video.py", line 153, in track_camera


    frame_shape = get_frame_shape(ffmpeg_input)


  File "/opt/frigate/frigate/video.py", line 41, in get_frame_shape


    video_info = [s for s in info['streams'] if s['codec_type'] == 'video'][0]


KeyError: 'streams'


F :1133] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]


/arrow/cpp/src/plasma/store.cc:738: Disconnecting client on fd 7
```

**Comment by walthowd** [comment]
Looks like the camera refused the network connection from frigate? 

Can you sanitize and post your config as well --Also try hardcoding your height and width, that will skip the ffprobe.

Finally, if that doesn't work, shell into your docker container and try running ffmpeg manually and see if it can connect.

**Comment by roofuskit** [comment]
I already have the video size hard coded. Any idea why I could connect to the stream with VLC but FFMPEG gets booted?

> web_port: 5000
> 
> mqtt:
>   host: MY MQTT SERVER)
>   topic_prefix: frigate
>   # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
>   # user: username # Optional
>   #################
>   ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
>   ##   password: '{FRIGATE_MQTT_PASSWORD}'
>   #################
>   # password: password # Optional
> 
> #################
> # Default ffmpeg args. Optional and can be overwritten per camera.
> # Should work with most RTSP cameras that send h264 video
> # Built from the properties below with:
> # "ffmpeg" + global_args + input_args + "-i" + input + output_args
> #################
>  #ffmpeg:
>    #global_args:
>      #- -hide_banner
>      #- -loglevel
>      #- panic
>    #hwaccel_args: []
>    #input_args:
>      #- -avoid_negative_ts
>      #- make_zero
>      #- -fflags
>      #- nobuffer
>      #- -flags
>      #- low_delay
>      #- -strict
>      #- experimental
>      #- -fflags
>      #- +genpts+discardcorrupt
>      #- -vsync
>      #- drop
>      #- -rtsp_transport
>      #- tcp
>      #- -stimeout
>      #- '5000000'
>      #- -use_wallclock_as_timestamps
>      #- '1'
>    #output_args:
>      #- -f
>      #- rawvideo
>      #- -pix_fmt
>      #- rgb24
> 
> ####################
> # Global object configuration. Applies to all cameras
> # unless overridden at the camera levels.
> # Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
> # All labels from the model are reported over MQTT. These values are used to filter out false positives.
> # min_area (optional): minimum width*height of the bounding box for the detected person
> # max_area (optional): maximum width*height of the bounding box for the detected person
> # threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
> ####################
> objects:
>   track:
>     - person
>   filters:
>     person:
>       min_area: 5000
>       max_area: 100000
>       threshold: 0.5
> 
> cameras:
>   test:
>     ffmpeg:
>       ################
>       # Source passed to ffmpeg after the -i parameter. Supports anything compatible with OpenCV and FFmpeg.
>       # Environment variables that begin with 'FRIGATE_' may be referenced in {}
>       ################
>       input: rtsp://192.168.1.35:8554/stream
>       #################
>       # These values will override default values for just this camera
>       #################
>       # global_args: []
>       # hwaccel_args: []
>       # input_args: []
>       # output_args: []
>     
>     ################
>     ## Optionally specify the resolution of the video feed. Frigate will try to auto detect if not specified
>     ################
>       height: 1640
>       width: 1232
> 
>     ################
>     ## Optional mask. Must be the same aspect ratio as your video feed.
>     ## 
>     ## The mask works by looking at the bottom center of the bounding box for the detected
>     ## person in the image. If that pixel in the mask is a black pixel, it ignores it as a
>     ## false positive. In my mask, the grass and driveway visible from my backdoor camera 
>     ## are white. The garage doors, sky, and trees (anywhere it would be impossible for a 
>     ## person to stand) are black.
>     ## 
>     ## Masked areas are also ignored for motion detection.
>     ################
>     # mask: back-mask.bmp
> 
>     ################
>     # Allows you to limit the framerate within frigate for cameras that do not support
>     # custom framerates. A value of 1 tells frigate to look at every frame, 2 every 2nd frame, 
>     # 3 every 3rd frame, etc.
>     ################
>     take_frame: 1
> 
>     ################
>     # The expected framerate for the camera. Frigate will try and ensure it maintains this framerate
>     # by dropping frames as necessary. Setting this lower than the actual framerate will allow frigate
>     # to process every frame at the expense of realtime processing.
>     ################
>     fps: 5
> 
>     ################
>     # Configuration for the snapshots in the debug view and mqtt
>     ################
>     snapshots:
>       show_timestamp: True
> 
>     ################
>     # Camera level object config. This config is merged with the global config above.
>     ################
>     objects:
>       track:
>         - person
>       filters:
>         person:
>           min_area: 5000
>           max_area: 100000
>           threshold: 0.5

**Comment by blakeblackshear** [comment]
Your width and height are indented under ffmpeg. You need to pull them up one level so they are even with ffmpeg.

**Comment by roofuskit** [comment]
> Your width and height are indented under ffmpeg. You need to pull them up one level so they are even with ffmpeg.

Thanks that seems to have done it, am I looking at normal logs now? is it functioning?


```
On connect called

/arrow/cpp/src/plasma/store.cc:1226: Allowing the Plasma store to use up to 0.4GB of memory.


/arrow/cpp/src/plasma/store.cc:1253: Starting object store with directory /dev/shm and huge page support disabled


Camera_process started for test: 20


Starting detection process: 19


Starting process for test: 20


 * Serving Flask app "detect_objects" (lazy loading)


 * Environment: production


   WARNING: This is a development server. Do not use it in a production deployment.


   Use a production WSGI server instead.


 * Debug mode: off


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.35:8554/stream -f rawvideo -pix_fmt rgb24 pipe:


test: ffmpeg_process is still running but didnt return any bytes


test: ffmpeg_process exited unexpectedly with 1


Terminating the existing ffmpeg process...


Waiting for ffmpeg to exit gracefully...


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.35:8554/stream -f rawvideo -pix_fmt rgb24 pipe:


F :1133] HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback]


/arrow/cpp/src/plasma/store.cc:738: Disconnecting client on fd 6


test: ffmpeg_process exited unexpectedly with 1


Terminating the existing ffmpeg process...


Waiting for ffmpeg to exit gracefully...


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.35:8554/stream -f rawvideo -pix_fmt rgb24 pipe:


test: ffmpeg_process exited unexpectedly with 1


Terminating the existing ffmpeg process...


Waiting for ffmpeg to exit gracefully...


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.35:8554/stream -f rawvideo -pix_fmt rgb24 pipe:


test: ffmpeg_process exited unexpectedly with 1


Terminating the existing ffmpeg process...


Waiting for ffmpeg to exit gracefully...


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.35:8554/stream -f rawvideo -pix_fmt rgb24 pipe:


test: ffmpeg_process exited unexpectedly with 1


Terminating the existing ffmpeg process...


Waiting for ffmpeg to exit gracefully...


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.35:8554/stream -f rawvideo -pix_fmt rgb24 pipe:


test: ffmpeg_process exited unexpectedly with 1


Terminating the existing ffmpeg process...


Waiting for ffmpeg to exit gracefully...


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.35:8554/stream -f rawvideo -pix_fmt rgb24 pipe:
```

**Comment by blakeblackshear** [comment]
Still looks like ffmpeg is unable to connect to your camera. Not sure why VLC can connect but ffmpeg can't. Are you running frigate on the same machine as VLC?

**Comment by roofuskit** [comment]
> Still looks like ffmpeg is unable to connect to your camera. Not sure why VLC can connect but ffmpeg can't. Are you running frigate on the same machine as VLC?

That's what I thought, looks like it's still failing.

They are on separate machines, I can ping the camera from the machine and it works. Can't ping from inside the container because of the lack of traceroute.

**Comment by roofuskit** [comment]
Tried a different RTSP server and it connected. It appears that now it doesn't see the Coral device. I know the coral device works I have a rest server setup and have tested it.

```
On connect called


/arrow/cpp/src/plasma/store.cc:1226: Allowing the Plasma store to use up to 0.4GB of memory.


/arrow/cpp/src/plasma/store.cc:1253: Starting object store with directory /dev/shm and huge page support disabled


Camera_process started for test: 20


Starting detection process: 19


Starting process for test: 20


eating ffmpeg process...


ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.32:8554/unicast -f rawvideo -pix_fmt rgb24 pipe:


 * Serving Flask app "detect_objects" (lazy loading)


 * Environment: production


   WARNING: This is a development server. Do not use it in a production deployment.


   Use a production WSGI server instead.


 * Debug mode: off


No EdgeTPU detected. Falling back to CPU.
```
