### ISSUE TITLE
Frigate+ Page Auto Refresh

### ISSUE THREAD

**Issue by lazyjai** [blakeblackshear/frigate#13152]
**Describe what you are trying to accomplish and why in non technical terms**
On the Frigate+ Page in version 0.14.0-da913d8, i've notice it auto-refreshes every number of seconds. This makes it hard to scroll through and submit items for positive re-tagging/fale positive as you get part way down and it refreshes to the top.

**Describe the solution you'd like**
I would like an option to disable auto-refresh on the page to make reviewing of all images easier.

**Describe alternatives you've considered**
A toggle, or disable of auto-refresh on the page; where it only shows the captured snapshots at the point of generation of the page.

**Additional context**
None at this time.

**Comment by NickM-27** [comment]
There is no auto refresh functionality here, what browser are you using and how often does it happen

**Comment by lazyjai** [comment]
Google Chrome v127.0.6533.120.
It does not hapen at a fixed interval.
It happens on both my desktop and laptop.
I have a video screen recording of it occuring, i'll see if I can post it somewhere.

**Comment by lazyjai** [comment]
I've uploded the video to a google drive folder [here](https://drive.google.com/drive/folders/1odCAxmHZ6AWDz4oqYS9LkWi5knZPDLwk?usp=drive_link).

**Comment by NickM-27** [comment]
fixed in latest commit

**Comment by lazyjai** [comment]
Thank you!
