### ISSUE TITLE
RTSP stream crazy after a while

### ISSUE THREAD

**Issue by SMAW** [blakeblackshear/frigate#1316]
I have a few camera's that are connected to my BlueIris system (Windows 10 Baremetal), from my BlueIris system I feed my Frigate system with RTSP of the BlueIris servers (RPI 4GB with USB Coral) for A.I. Detection which then uses MQTT. After starting the docker container all camera's work fine, but after a while (random times) suddenly the screen looks like described here: 
https://blakeblackshear.github.io/frigate/troubleshooting#my-mjpeg-stream-or-snapshots-look-green-and-crazy 

In BlueIris everything looks fine when the issue happens on Frigate. After a restart of the container, everything is fine again.

I tried if it happens if I restart the camera (maybe something changes in the feed of BlueIris to the PI, but that doesn't seem to be the issue.

Is there any way to do a check on this, let the container or camera feed of the camera restart itself or is it maybe a bug?

**Comment by blakeblackshear** [comment]
Are you using the recommended settings for Blue Iris? https://blakeblackshear.github.io/frigate/configuration/cameras#blue-iris-rtsp-cameras

**Comment by SMAW** [comment]
That seemed to be the issue,  it's running a few days perfectly now!  I think I misser the articles. Thanks! And keep up the great work regarding Frigate!!
