### ISSUE TITLE
Scroll bar on Log

### ISSUE THREAD

**Issue by Waank1** [blakeblackshear/frigate#13168]
in 0.14 there is no scroll bar in the log view 

**Describe the solution you'd like**
Add a scroll bar

**Describe alternatives you've considered**
downloading the file to a more readable app

**Additional context**

**Comment by NickM-27** [comment]
this is working as expected, the page up / down buttons can be used and there is the ability to filter items. The logs page is loaded gradually so a scrollbar would cause issues

**Comment by Waank1** [comment]
Thanks, just seemed that 0.13 had one...
