### ISSUE TITLE
Bring back the possibility to jump to specific point in time

### ISSUE THREAD

**Issue by krojew** [blakeblackshear/frigate#13176]
**Describe what you are trying to accomplish and why in non technical terms**
In the old UI, jumping to a recording at a specific date/time required literally two clicks: recordings -> hour. Now to get a similar result I need to click: camera -> history -> date filter -> scroll through the timeline -> hour. This is a lot of unnecessary steps, especially for people needing to do this often. In fact, the new UX doesn't fit such use case so much, it makes Frigate almost unusable and there's a need to use external integrations.

**Describe the solution you'd like**
Either:

1. Bring back the possibility to quickly jump to a specific hour, without going through the timeline.
2. Add an option to switch to the old UI.

**Describe alternatives you've considered**
Tried using the reviews tab, but it's even worse: the amount of actions needed is not lower, but also there's no possibility to view recordings on full screen.

**Comment by NickM-27** [comment]
Are you using object detection? The goal of the UI is to save time by not needing to view full recordings as often because the review items make it quicker to see what occurred (and we have received a lot of positive feedback about this).

Using object detection the review items allow you to jump directly to when that activity occurred. There is also the motion tab that allows easily seeing when motion occurred and jumping to the recordings at that time. 

If you are not using object detection I can see how that would be less useful, but Frigate is specifically designed for that use case.

Scrolling the timeline provides more information about what occurred where the old hours picker did not. It was also very problematic as often, users did not realize they could click on the hours to view them and we heard negative feedback on it often. 

If the old UI is preferred then 0.13 is still available

**Comment by krojew** [comment]
@NickM-27 I'm not using object detection on some cameras, just motion. I cannot use reviews, because they do not support fullscreen. The motion tab has the problem I described. Therefore, I don't know why you closed it, since the current UI doesn't save time in cases where only motion detection is used - it does the exact opposite. The lack of a vertical scrollbar on the motion timeline also makes it a chore to jump to specific time.

**Comment by NickM-27** [comment]
What do you mean reviews do not support full screen? The point of reviews is to get a general idea of what happened and see if the main recordings need to be viewed (which does support full screen). I don't see how the reviews limit anything, it is just additional information. 

> The motion tab has the problem I described.

That would be a bug or a configuration issue, we've requested more information there. we've not had any other users report this issue.

**Comment by krojew** [comment]
> FYI - you can scroll the timeline with your mouse wheel or with a swipe on mobile. You don't need to drag the handle to get the timeline to scroll.

I know, but it's very slow on a 4k display, while also being very inconvenient, especially compared to a simple click in the previous UI. Those might seem like small things, but if you use Frigate quite often or simply in a professional setting, they matter a lot.

> What do you mean reviews do not support full screen? The point of reviews is to get a general idea of what happened and see if the main recordings need to be viewed (which does support full screen). I don't see how the reviews limit anything, it is just additional information.

Let's consider a basic use case for people watching recordings on cameras - they typically want to have the best view possible with the possibility to jump around as efficiently as possible. The reviews tab doesn't meet the first point because of lack of fullscreen, while also not meeting the second due to having to use the timeline, which contrary to what was stated, only increases time needed to jump to a specific point.

> > The motion tab has the problem I described.
> 
> That would be a bug or a configuration issue, we've requested more information there. we've not had any other users report this issue.

I meant the number of actions needed to watch a recording - instead of two, it's now five, and you have to do it each time to watch something. For example, if you want to show something to a colleague, you need to go through it, wasting time for everyone involved.

**Comment by hawkeye217** [comment]
> I know, but it's very slow on a 4k display, while also being very inconvenient, especially compared to a simple click in the previous UI. Those might seem like small things, but if you use Frigate quite often or simply in a professional setting, they matter a lot.

I have a 4k display, and scrolling with the mouse wheel does not feel slow at all. We have not had any other reports of this either. But if you can provide a screen recording to describe what you're experiencing, that would be helpful to see, perhaps there are improvements that can be made.

**Comment by hawkeye217** [comment]
> Let's consider a basic use case for people watching recordings on cameras - they typically want to have the best view possible with the possibility to jump around as efficiently as possible. The reviews tab doesn't meet the first point because of lack of fullscreen, while also not meeting the second due to having to use the timeline, which contrary to what was stated, only increases time needed to jump to a specific point.

As @NickM-27 said, the Frigate UI was redesigned with several use cases in mind. If you haven't read Blake's initial post on it from several months ago, it may be helpful for you to understand why Frigate 0.14 now works the way it does.

https://github.com/blakeblackshear/frigate/discussions/11136

0.13 will always remain available if you prefer to use that UI to review your footage.

**Comment by NickM-27** [comment]
Everything that happens on your camera is not going to be important. The review allows you to quickly see what happened without needing to use the full recordings. Then if something unexpected occurs it's quick to jump to those recordings. 

We've received a lot of positive feedback about the time people have saved with the new UI. We fully understand not everyone will use software the same way and it doesn't fit every use case. Thanks for your honest feedback.

We will be happy to look into specific pain points, like scrolling, to see what can be improved
