### ISSUE TITLE
Frigate 0.14 new UI and ultra widescreen

### ISSUE THREAD

**Issue by kaminoer** [blakeblackshear/frigate#13186]
**Describe what you are trying to accomplish and why in non technical terms**
First of all I wanted to thank you for the 0.14 update! The new UI is gorgeous and the upgrade procedure went smoothly. The only issue is that when using ultra widescreen setups, many sections of the UI are padded to the left which can quickly strain one's neck. Here's how the settings menu looks like in 3440x1440:
![frigate_UW](https://github.com/user-attachments/assets/4fd5a98a-faeb-41ff-a0c6-21e6a37223d2)

**Describe the solution you'd like**
Would it be possible to center the UI? Or at least add an optional toggle that would center the UI?

**Describe alternatives you've considered**
A workaround is to resize the browser window and place it in the middle of the screen but a built in support for ultrawide would be much appreciated.

**Comment by bagobones** [comment]
As a fellow ultrawide user I tend to run the UI of most web apps as half screen width unless I am looking at a large set of data or video then I full screen it.

However I do agree that centering config elements is nice when done well for small screens like this.
