### ISSUE TITLE
Feature Request - Allow date / month filtering in the gui

### ISSUE THREAD

**Issue by mannp** [blakeblackshear/frigate#1318]
I am running frigate (great NVR btw) via docker and it has a dedicated share for its clips.

### Problem / issue

If I need to go back to a particular day / month to get a clip I am unable to filter the gui by month or day so have to resort to going straight to disk to find the incident I need.

it is then more of a challenge to find the clip without an image of the video itself.

it would be great to be able to select the day / month for frigate to load, as manually going back a month in the gui takes a good while to do.

Thanks for your consideration :)

**Comment by mannp** [comment]
I should add that I can filter via the api using the following;

`/events?camera=cameraname&label=car&zone=zone_drive&has_clip=1&before=1620169800&after=1620083400
`
Which gives me the clips between 4th and 5th May 2021 👍🏻 but converting the dates to int isn't that intuitive :)

**Comment by Sinamics** [comment]
I was looking for this feature myself, and im currently trying to get this implemented.
Would a `From` - `To` date field be sufficant enough?

![2021-07-05_23-21-24.jpg](https://imgshare.io/images/2021/07/05/2021-07-05_23-21-24.jpg)

**Comment by mannp** [comment]
Thats great news 🙂

That looks good to me.

The defaults are important for me too, in that if it could default to 'today' or 'this week' or 'month.

I have quite a large backlog and viewing the events takes a very long time to display now, when I usually just want to quickly see the events for today.

Hope that makes sense.

**Comment by Sinamics** [comment]
Events page fetch the last 25 events by default, and fetch another 25 for each time you scroll down to end of page. 

I see no reason to change that behaviour. Events page is quite snappy as it is.

**Comment by mannp** [comment]
Fair enough but I guess that is yours...mine has become very slow loading the events page with 7 cameras.

**Comment by nicw** [comment]
I would love this! One of my 7 cameras captures a lot of people, and when I want to just see what occurred overnight, it can take a few minutes to scroll/wait. Also tricky is that tapping into each video, and then returning, resets the scrollview.

While the date picker is a good starter, I think a draggable timeline is the way to go evolutionarily, as the word 'NVR' is suggesting.

**Comment by mannp** [comment]
> I would love this! One of my 7 cameras captures a lot of people, and when I want to just see what occurred overnight, it can take a few minutes to scroll/wait. Also tricky is that tapping into each video, and then returning, resets the scrollview.

This is my scenario exactly and I also suffer the scrollview issue when trying to focus in on the video where I need to be. 

The scrollview I guess is a separate issue and perhaps frigate processes every event before it displays the first 25, as the speed of display is slow when there are a larger number of events.

**Comment by nicw** [comment]
And to see the date (very relevant) I would also move the Score column further right or remove it from this view, given we've all defined our thresholds. And if we are curious, it shows on the specific event screen.

**Comment by gururise** [comment]
Is this still being worked on? One of the most sorely missed features (IMHO).

**Comment by Sinamics** [comment]
Agree, this is a "must have" feature. I can take a look this weekend and see if im able to create a PR, or at least a draft for review.

**Comment by NickM-27** [comment]
Closing this due to https://github.com/blakeblackshear/frigate/pull/2428
