### ISSUE TITLE
Video panzoom image reset

### ISSUE THREAD

**Issue by neutralvibes** [blakeblackshear/frigate#13210]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 
I love the video panzoom addition to the new UI to enable enlarging areas of interest. I did the same with a previous camera project a few years ago and was wondering how to get it into frigate, and there it is! For me, the only thing missing is a reset/home button to revert the panned/zoomed image to its original state efficiently.

**Describe the solution you'd like**

When the panzoom script is enabled for a video, either always show an icon button to revert to full video view, or only show the icon when the view has been altered. This icon button could be placed either with the video controls, or in one of the corners.

**Describe alternatives you've considered**

Perhaps some sort of click sequence, or added to the right click menu. Can't really see an alternative otherwise. The icon is a method I have used in a previous project and still works for me now. 

**Additional context**

Makes it quick and easy to reset the image rather than mouse fiddling or finger spreading. Thanks in advance for considering.

**Comment by NickM-27** [comment]
I haven't felt a need for this at all, just scrolling out with the mouse or pinching out on mobile has always been easy to do without any issues, the view recenters itself after.

**Comment by neutralvibes** [comment]
First, great quick response. Now, I am using a laptops with a track pad, and they are unfortunately not all equal. It can take a few pinches to get things back at times, on both them. Some mice wheels can also develop strange jumps. 

The mention of right click was just an effort at another possibility.

You and your fellow contributors are doing great works, thanks. I have found the method I described working well for me in all scenarios, but I appreciate you may feel differently if you have never had to deal with these issues.

**Comment by NickM-27** [comment]
for laptops, pinching is not really the best way to use it. Just using the two fingers up and down (the scroll gesture) will work much more effectively
