### ISSUE TITLE
Add zone info back into event review

### ISSUE THREAD

**Issue by sundansx** [blakeblackshear/frigate#13230]
I want to be able to see the zones that were triggered in event view like previous versions

**Describe the solution you'd like**
I would like a way to display this information for troublshooting event issues.  The filter setting does not give me confidence.  I have a clip that was recorded on an event that fits the filters, but when I look at the mqtt message it only shows one of the two zones in the json that the filter was set for.  If the event showed the event zone like it used to I would be more confident of the source.  maybe somethign like shown below.  It would also be nice to be able to see the event id so I can track that to the json mqtt message.

**Describe alternatives you've considered**
I have used the filter on the review page and it does not match the json message at the same timestamp.  

**Additional context**
![image](https://github.com/user-attachments/assets/b4042b77-6551-4160-89db-bbeb2dc2f437)

**Comment by NickM-27** [comment]
This has already been implemented for 0.15

**Comment by sundansx** [comment]
great, thanks.
