### ISSUE TITLE
[SR] Nginx proxy config for Frigate

### ISSUE THREAD

**Issue by bkupidura** [blakeblackshear/frigate#1325]
Is there a way to deploy nginx (or any other http proxy) in the front of Frigate?

I plan to add some basic auth for Frigate.

Current nginx.conf:

```
        location /frigate/ {
            proxy_pass http://10.0.120.51:5000/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Ingress-Path /frigate;

        }
```

Basicaly WebUI is loaded, but all hrefs are ignorig `X-Ingress-Path`, this is causing problems with webpage refresh.

Href example:

```
        <a role="button" aria-disabled="false" tabindex="0" class="whitespace-nowrap flex items-center space-x-1  transition-opacity text-blue-500 hover:bg-blue-500 hover:bg-opacity-20 focus:bg-blue-500 focus:bg-opacity-40 active:bg-blue-500 active:bg-opacity-40 font-sans inline-flex font-bold uppercase text-xs px-2 py-2 rounded outline-none focus:outline-none ring-opacity-50 transition-shadow transition-colors focus:ring-2 cursor-pointer" href="/events?camera=cam1_kitchen">Events</a>
```

**Comment by cjd** [comment]
Nginx reverse proxy works fine as long are you are serving via root (not a sub path)
I had a try of getting things working under a subpath but the assumption that it will be served on / is embedded all over the place - so in the end I setup a separate virtual host for it

**Comment by bkupidura** [comment]
Thanks, I was hoping that there is some undocumented (like X-Ingress-Path) env/header/anything to replace root_dir inside Frigate WebUI.

**Comment by blakeblackshear** [comment]
I run it on a separate subdomain, but that header _should_ work for serving at a different path. That is how the home assistant addon works.

**Comment by bkupidura** [comment]
I dont have a way to check where hrefs are pointing in HASS. But i would expect that they will behave same way.

For now i go with dedicated domain for Frigate.
