### ISSUE TITLE
Frigate 0.14 event review functionality

### ISSUE THREAD

**Issue by klonwar** [blakeblackshear/frigate#13261]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have more convenient way to rewind small events so that I can select the position I am interested in in the video recording.

**Describe the solution you'd like**
I see it like an additional horizontal progressbar on event review page that will give me option to navigate only from the start of the event to the end of the event. It should be synced with right-side timeline progressbar to keep the 0.14 idea of recordings review.

At least it should give option to scroll through event regardless of what is before and after it. Ideally it should also show info about objects detecting time and zone entering time, like in 0.13.

**Describe alternatives you've considered**
1. Alternative way is to give option for user to zoom in/out right-side timeline. Maybe even to create some button that will apply zoom automatically to fit the selected event or do it automatically after selecting event in Review, since you want to review some specific event, not the whole recordings.
2. As for showing object / zone detections, it can be placed on the timeline too, but I'm afraid there will be too many info, so it should be visible only when timeline zoom is enabled / some checkbox is checked ('show detections on timeline').

**Additional context**

Some kind of idea how it may look
![image](https://github.com/user-attachments/assets/b9cf00e2-682d-41b4-9a50-e051d56b4a80)

About previous version:

Since in 0.13 each event was a separate video file, you could easily scroll through the specific event, select a specific position on the progressbar. Right now it's nearly impossible to rewind specific event if it's a small one, because right side progressbar has too much sensitivity. And it's great for reviewing recordings in general, but not convenient for specific events.

It's really important, because when you see some suspicious activity in the middle of the event you may want to review it once more, but now you have to view the entire event from the beginning. Or clicking on +- 10s buttons, which is very inconvenient if the event is several minutes long.

In 0.13 there was an option to navigate to the position in the event when object enter/leave specific zone. This was very useful and I would very much like to have such a thing in the new version.

Maybe you've already considered something like this and you have some plans for the future?

**Comment by hawkeye217** [comment]
Yes, timeline zooming and a screen to see why review items were created are both pinned feature requests here. 

In the meantime it’s worth mentioning that you can use the arrow keys on your keyboard to more slowly scrub through footage in history view.
