### ISSUE TITLE
Wrong object selected when multiple in the scene but in masked region

### ISSUE THREAD

**Issue by Anx2k** [blakeblackshear/frigate#1326]
**Describe the bug**
For one of my cameras, I have a road which is masked out (so no detection happens) at the top of the image - but I've had several instances where a vehicle is correctly detected within the monitored camera region, but a vehicle in the masked region is what is used as the thumbnail.  I suspect that the vehicle on the road might have a higher match, but obviously it would be ideal if matches within the masked region are not used for the thumbnail. 

**Version of frigate**
0.8.4-5043040

**Config file**

```mqtt:
  host: ha-ip
  user: mqtt-user
  password: mqtt
cameras:
  camera_front:
    ffmpeg:
      inputs:
        - path: rtsp://name:password@ip:554/Streaming/Channels/101
          roles:
            - clips
            - rtmp
            - detect
    width: 3072
    height: 1728
    fps: 5
    objects:
        track:
            - person
            - car
            - motorcycle
    snapshots:
        enabled: True
        retain:
            default: 10
    clips:
        enabled: True
        pre_capture: 5
        post_capture: 5
        retain:
            default: 10
    motion:
        mask:
            - 0,0,1450,0,1438,208,664,240,471,428,0,542
detectors:
    cpu1:
        type: cpu
    cpu2:
        type: cpu
    cpu3:
        type: cpu
    cpu4:
        type: cpu

```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```{
  "camera_front": {
    "camera_fps": 5.1, 
    "capture_pid": 61, 
    "detection_fps": 0.0, 
    "pid": 50, 
    "process_fps": 5.1, 
    "skipped_fps": 0.0
  }, 
  "detection_fps": 0.0, 
  "detectors": {
    "cpu1": {
      "detection_start": 0.0, 
      "inference_speed": 61.12, 
      "pid": 35
    }, 
    "cpu2": {
      "detection_start": 0.0, 
      "inference_speed": 67.26, 
      "pid": 36
    }, 
    "cpu3": {
      "detection_start": 0.0, 
      "inference_speed": 77.57, 
      "pid": 38
    }, 
    "cpu4": {
      "detection_start": 0.0, 
      "inference_speed": 66.7, 
      "pid": 41
    }
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 1014.0, 
        "mount_type": "tmpfs", 
        "total": 1039.4, 
        "used": 25.4
      }, 
      "/media/frigate/clips": {
        "free": 23159.1, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 8534.9
      }, 
      "/media/frigate/recordings": {
        "free": 23159.1, 
        "mount_type": "ext4", 
        "total": 33066.6, 
        "used": 8534.9
      }, 
      "/tmp/cache": {
        "free": 946.5, 
        "mount_type": "tmpfs", 
        "total": 1039.4, 
        "used": 93.0
      }
    }, 
    "uptime": 250174, 
    "version": "0.8.4-5043040"
  }
}
```
**Screenshots**
In all of these examples, the care on the driveway is what triggered the detection, but the car on the road in the background is what was used as the thumbnail:

![Example1](https://user-images.githubusercontent.com/35139253/124424273-9fd00e00-dd1b-11eb-9754-82a64b474308.jpg)
![Example2](https://user-images.githubusercontent.com/35139253/124424284-a52d5880-dd1b-11eb-9648-31650ff291bc.jpg)
![Example3](https://user-images.githubusercontent.com/35139253/124424292-a78fb280-dd1b-11eb-8b63-79a00f27ed47.jpg)

**Computer Hardware**
 - Ubuntu
 - HACS
 - VMWare
 - None
 - Wired

**Camera Info:**
 - Annke
 - C800
 -  3072x1728
 - 5

**Comment by blakeblackshear** [comment]
Motion masks only filter motion. The only way to avoid this would be to create an object mask to eliminate all detections in unwanted areas. Keep in mind that it will never see cars in those areas, so cars that do ultimately go in the driveway will have shorter clips and some may be missed.

**Comment by Anx2k** [comment]
Ah, I see, it wasn't clear to me in the documentation that it would work like that.  It would be cool at some point if you calculated the overlap between the two n-gons (mask and detection), and then allowed some deweighting to be applied, so it would be possible to tune out these hits.

Great app btw, really impressed with how it performs, and the integration with HA is great - I have it emailing me when detections happen and attaching the thumbnails and screenshots, and it's super handy.
