### ISSUE TITLE
Ignore large scene changes

### ISSUE THREAD

**Issue by Kedryn** [blakeblackshear/frigate#13260]
I want to have large scene changes (a light in the camera view turning on or off, IR switching at night) to be ignored by the movement detection.

As others NVR, i think a camera option like "ignore motion when more than xx% scene changes" has to be introduced

I tried to play with lightning_threshold, from 0.8 to 0.3, but without any success. At night, when the garage or outside main entrace lights are turned on by a movement detection, then never really turn off again. When timer passed, both lights turns off, but then Frigate detect the lights off and IR on switch as a movement, and turno lights on again.

**Comment by NickM-27** [comment]
This is what the lightning threshold is for. If you think it's not working correctly then it should be created as a bug

**Comment by Kedryn** [comment]
I have it at 0.3 but still motion is detected.
This evening i'l make some videos and create the bug

**Comment by NickM-27** [comment]
motion is gradual, it is likely that motion is detected because only some pixels change in the first frame and then more change in the next frame then the lightning threshold is triggered. I would not recommend using the motion sensor as a direct input for lights to be turned on or off, better to have a cooldown

**Comment by NickM-27** [comment]
> It's not gradual.

How do you know? Have you watched the debug view frame by frame? I'm talking on a frame by frame level not generally. If the first frame isn't changing more than 30% of the pixels then the lightning threshold won't be triggered
