### ISSUE TITLE
Camera trigger a PTZ camera

### ISSUE THREAD

**Issue by rvw83** [blakeblackshear/frigate#13278]
**Describe what you are trying to accomplish and why in non technical terms**
if someone enters my driveway, and camera 1 detect motion, i would like to trigger camera2 (PTZ) to turn to the driveway

**Describe the solution you'd like**
the camera at the driveway of my house is a static camera,  if this camera detect motion, it would be nice it can trigger a PTZ camera to turn to the driveway for an X time or for as long as motion is detected (e.g. by triggering a preset) when the motion is stopped, or the time is over, the PTZ camera can return to the last preset, or a predefined preset.

**Comment by NickM-27** [comment]
this can be done in any automation platform like HomeAssistant, NodeRED, or a simple script. I am not sure if this type of feature fits in to Frigate itself or not

**Comment by rvw83** [comment]
> this can be done in any automation platform like HomeAssistant, NodeRED, or a simple script. I am not sure if this type of feature fits in to Frigate itself or not

thats right, i can try it with my HomeAutomation, but it would be nice if it becomes as a feature in Frigate, so all my camera intelligence are at one place :-)

**Comment by matiasba** [comment]
> this can be done in any automation platform like HomeAssistant, NodeRED, or a simple script. I am not sure if this type of feature fits in to Frigate itself or not

I mean, it's a common use case of PTZ cameras. The documentation even says as much. I don't think that is unreasonable to expect that an NVR could trigger an action like that without an external automation software.

**Comment by rvw83** [comment]
> > this can be done in any automation platform like HomeAssistant, NodeRED, or a simple script. I am not sure if this type of feature fits in to Frigate itself or not
> 
> I mean, it's a common use case of PTZ cameras. The documentation even says as much. I don't think that is unreasonable to expect that an NVR could trigger an action like that without an external automation software.

I can indeed set in my NVR that the PTZ camera goes to a certain preset when another camera triggers an "alarm", but the problem is that I cannot set anywhere that the PTZ goes back to another position when the "alarm" or motion is stopped, or after for example an "X" seconds
