### ISSUE TITLE
Be able to review more footage in Timeline view

### ISSUE THREAD

**Issue by vertex-github** [blakeblackshear/frigate#13273]
Ive got recordings for my cameras going back 2 weeks.  Using the timeline view I only seem to be able to scroll back in time via the UI for 24 hours.  Is this a setting Im overlooking or is this intentional?

Furthermore, it would be great if there was a zoomed out view of the timeline to allow more rapid review of earlier days - currently I have to drag and scroll through each minute/hour at a time in order to get back 24 hours.  It would be nice if there was a quicker way to get access to events/recordings from further back in time.

**Comment by NickM-27** [comment]
this is working as expected, the timeline is not designed to work over more than 24 hours, there will be a separate view for doing more historical review. 

there is already a separate feature request for zooming of the timeline

> currently I have to drag and scroll through each minute/hour at a time in order to get back 24 hours. It would be nice if there was a quicker way to get access to events/recordings from further back in time.

there is no need to drag, just scroll and then click where you want to view
