### ISSUE TITLE
Show the type of detected object in the event list

### ISSUE THREAD

**Issue by mccasian** [blakeblackshear/frigate#13308]
Hello,

While reviewing the event list, i see the type of detected object as mini(super mini) icon. When it's a person or a bike, it's easy, but some icons I just can't figure out what they mean, except if i'm playing with filters. Also, I am not an every day "reviewer" so i might forgot from time to time what some rare icons are meaning.

![image](https://github.com/user-attachments/assets/0fe5b343-36b7-4614-877b-9ee8a3491ae5)

I would like to either have the object type directly written next to the snapshot, or at least be able to see the object type while hovering the mouse over the icon.

Thank you
Casian

**Comment by NickM-27** [comment]
The icon you're pointing to is the catch all icon for things that don't have a specific icon. You can hover to see all of the labels

**Comment by mccasian** [comment]
ok, i got what the icon means, but hovering the mouse does nothing on camera history; tested with safari, firefox and inspected with web inspector.
Hovering does work in Review menu, but in my scenario, the camera history(events) is what I need, and there is missing.

**Comment by NickM-27** [comment]
ah yeah, we can add that

**Comment by mccasian** [comment]
that would be great. Thank you.
