### ISSUE TITLE
Events Tab Missing

### ISSUE THREAD

**Issue by drtanzil** [blakeblackshear/frigate#13311]
Dear Team,

Thank you for your great work. The recent update has broken events tab. 
Previously, events were well-organized, displaying detected photos of individuals along with accompanying text. 
Now, everything is in video format with no text information. 
Users who rely on Frigate for surveillance typically review the events tab to quickly see all detected faces at a glance. Unfortunately, this valuable feature is missing in the latest update, and navigating the grid and camera filters has become more complicated.

I kindly request that you address these UI/UX issues.

**Comment by NickM-27** [comment]
This is working as expected. The face names can be seen by hovering the chips with object icons. 

It has already been implemented for 0.15 to have a separate pane to view each snapshot (if enabled) and other details of the review item

**Comment by Vistritium** [comment]
But where is the bounding box that shows what triggered the event? I don't see it in new ui and it's crucial for us because we are fighting false positives all the time and now I don't know what element triggered the false positive 😩

**Comment by NickM-27** [comment]
this is covered in the FAQ, there is no view for this in 0.14, it has already been added in for 0.15
