### ISSUE TITLE
Documentation update for Synology NAS + Coral TPU to resolve coral not connecting for older NAS's running DSM 7.2.1

### ISSUE THREAD

**Issue by igiannakas** [blakeblackshear/frigate#13333]
On my Synology 716+II running DSM 7.2.1-69057 Update 5 I run into an issue getting my Coral TPU to work with Frigate 0.14, where the TPU would not initialise correctly and it would not be recognised by Frigate.

The below reflects my experience in how I managed to resolve this and I would like to request an update to the documentation to save other users the headache of troubleshooting it.

**Setup workflow:**
1. Plug in the coral TPU in any of the USB ports on the NAS
2. Open the control panel - info screen. The coral TPU would be shown as a generic device. 
3. Initialise the docker container with Coral TPU enabled in the config
4. The TPU would be detected but a few moments later it would disconnect.
5. Restart the container - the coral TPU would not be detected
6. Unplug and plug back in - the coral TPU would be detected again as a generic device...

**Troubleshooting:**
What is happening is that when the coral TPU is plugged in for the first time, it is detected as a generic device. When frigate runs, from what I understand it initialises the device and writes a firmware or something similar to it (as seen in the dmesg log). This changes the device identifier from the generic device to USB Device - google inc. 

**However in the process of doing so, the device gets disconnected from the NAS and is not re-initialised!** This means if you restart the frigate container, the device cannot be found as the bus has not initialised it.

If you unplug it, it gets reset to the generic device and it is recognised again. However, restarting the frigate container, means it gets re-initialised with the detection firmware and the device is disconnected yet again.

**How to fix it?**
1. Plug in the coral TPU in any of the USB ports on the NAS
2. Open the control panel - info screen. The coral TPU would be shown as a generic device. 
3. Start the docker container with Coral TPU enabled in the config
4. The TPU would be detected but a few moments later it would disconnect.
5. **While leaving the TPU device plugged in, restart the NAS using the reboot command in the UI. Do NOT unplug the NAS/power it off etc.**
6. Open the control panel - info scree. The coral TPU will now be recognised as a  USB Device - google inc
7. Start the frigate container. Everything should work now!

**Final remarks:**

I have 2 Synology NAS devices - a DS716+II and a DS1019+. Both are running DSM 7.2.1-69057 Update 5 which as of this writing is the latest version. However the  DS716+II  runs a very old kernel and Synology appears not to have updated it (3.10.108). The DS1019+ runs kernel 4.4.302+.

On the DS1019+ this issue I believe did not occur. Probably because the newer kernel re-initialised the device when the Coral firmware was updated. The DS716+II doesnt.

**So so save you some headache, try starting the frigate container twice, with the device plugged in and with a reboot of the NAS in between!**

**Comment by igiannakas** [comment]
Awesome thank you 🙏🏻👍🏻 hope it saves someone the headache :)

**Comment by NickM-27** [comment]
Thanks for sharing the solution

**Comment by BasicWalker** [comment]
@igiannakas would you mind sharing your Synology and frigate docker compose and config.yml? i have the same hardware as you and frigate is very unstable.
