### ISSUE TITLE
integrate IMOU cameras without rstp

### ISSUE THREAD

**Issue by Whastie** [blakeblackshear/frigate#13354]
I have some IMOU cameras that are integrated into Home Assistant with the native ONVIF integration.
In this integration you do not have access to the rstp or ip address of the cameras, but to the name of the sensor directly in home assistant.

I would like to be able to integrate the name of the sensor that the camera has in the cameras section in frigate so that I can integrate it.
Is this possible?
Do you have a solution for this?

thanks

![image](https://github.com/user-attachments/assets/58be6c04-91bc-4ffe-a1ef-7c46554f611e)
![image](https://github.com/user-attachments/assets/06b86e76-03fa-4ee6-a602-ea6fe8125665)

**Comment by hawkeye217** [comment]
You can use the ONVIF source with go2rtc and then configure the camera using the go2rtc sources in Frigate.

https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-onvif
https://docs.frigate.video/guides/configuring_go2rtc/

**Comment by Whastie** [comment]
Thanks for the reply, sorry for my lack of knowledge on this subject.

But I don't know the address of the camera via onvif because in the home assistant integration I only have the name of the entity: "camera.com_amarillo_profile001"

Can I integrate the camera into frigate with only this sensor? Can you give me an example?

Thanks

**Comment by hawkeye217** [comment]
No, that is a Home Assistant sensor name and has nothing to do with Frigate. 

The link I provided to go2rtc tells you how to do auto discovery to get the address.
