### ISSUE TITLE
Frame by frame playback

### ISSUE THREAD

**Issue by nsprawling** [blakeblackshear/frigate#13376]
**Describe what you are trying to accomplish and why in non technical terms**
The current playback controls in 0.14 don't (that I can see, I might be thick!) offer fine grained playback; the smallest increment by which you can move footage back and forth is 10s.

**Describe the solution you'd like**
When reviewing footage for details like number plates and faces, the ability to move frame by frame through footage would make seeking detail in images or identifying i frames far easier.

**Comment by NickM-27** [comment]
you can already use the up and down arrows on the keyboard to go back and forth 1 second. Frame by frame is not possible in a browser, see https://github.com/blakeblackshear/frigate/discussions/12448#discussioncomment-10051238
