### ISSUE TITLE
Use deci-fp16-yolonas model from Frigate 14 on older version Frigate 13.2

### ISSUE THREAD

**Issue by flyzet-prog** [blakeblackshear/frigate#13379]
Is that possible to use newer deci-fp16-yolonas model in Frigate 13.2.0 instead of old one Yolo8?Any advantage?
I tried Frigate 14, and i like accuracy of new models, but main think that i use Frigate 13.2 is that i can catch all events, every single person. Unfortunately i can't see all peoples that came across on Frigate 14 because now its unified into one alert or detection. Would be great if where possibility to chose algorithm like on older version Frigate 13.2.  
Thank you devs

**Comment by NickM-27** [comment]
No, this requires the newer openvino version
