### ISSUE TITLE
Green Screen when adding multiple cameras

### ISSUE THREAD

**Issue by alanpilz** [blakeblackshear/frigate#1346]
I have 7 Dahua Cameras connected to a NVR, each running two streams, one for High Res playback (1920x1080), and one low res for detection. (640x480) with H.264 compression.

When I add the 7th camera, it appears as a green screen. After I reboot my system, sometimes a different camera is shown with the Green Screen, seems to be random.

I have temporarily removed all but 3 cameras and everything is working well. Today I installed a Google Coral and tried activating the 7 cameras again. Same issue returned, and the systems grinds to a halt. Need to reboot my Pi to be able to do anything as all screens are non responsive.

frigate.yml

`front_door:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://homeassist:homeassist123@192.168.1.200:554/cam/realmonitor?channel=2&subtype=1
          roles:
            - detect
        - path: rtsp://homeassist:homeassist123@192.168.1.200:554/cam/realmonitor?channel=2&subtype=0
          roles:
            - clips
            - record
            - rtmp
    width: 640
    height: 480
    fps: 5
    objects:
      track:
        - person
    record:
      enabled: True
      retain_days: 10
    clips:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      retain:
        default: 3
    motion:
      mask:    
        - 640,480,640,453,452,454,453,480`

Detector info

`detectors:
  coral:
    type: edgetpu
    device: usb`

Running on a Rasp Pi4 4Mb with a 480Gb M2 SSD (Argon One M2 Case) with a recently added Coral attached to USB3.0

_Originally posted by @alanpilz in https://github.com/blakeblackshear/frigate/discussions/546#discussioncomment-983688_

**Comment by blakeblackshear** [comment]
I'm guessing you used the convert to issue feature. Please post the information requested in the issue template in this issue: https://github.com/blakeblackshear/frigate/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by alanpilz** [comment]
Done.. this can be closed
