### ISSUE TITLE
Custom Model

### ISSUE THREAD

**Issue by kcarriello** [blakeblackshear/frigate#135]
I'm trying to add custom model but I'm getting the error: "ValueError: Cannot set tensor: Dimension mismatch.". It could be a noob question, sorry, I'm starting learning TF. Any clue will be appreciated. 

I'm mounting model using docker -v, keeping labels as is and mounting TPU model only

**Comment by walthowd** [comment]
Can you post the model,  your docker run command or compose file?

**Comment by kcarriello** [comment]
i'm using portainer for docker control, i'm sure the problem is not related to the volume mounting on docker. 

I'm using "EfficientNet-EdgeTpu (L)" EDGE TPU MODEL from this site: https://coral.ai/models/

**Comment by scstraus** [comment]
Portainer still requires parameters with which is creates the docker run. Best is to use portainer with docker compose, then it’s very clear what you’re doing and you can get help debugging it.

**Comment by kcarriello** [comment]
I'm sure the problem is not with mounting point, I can check the correct file is being mounted using the docker console. Since my last try I investigate the probable root cause for the "Dimension mismatch", I found that the model I was using was 299x299, frigate expect 300x300, also, I tried another model 300x300, but git "Index" error, which seems to me that frigate uses COCO and the model was using iNature, is my assumption correct? I now have a COCO model, 300x300 which ran fine on frigate. Any suggestion on convert non mobile model to use on frigate? I'm get some false-positives, mainly when detecting my dog as person.

**Comment by rb2k** [comment]
I also just tried to hook a custom model into frigate:

I used this model I trained: https://github.com/rb2k/sqwrlmodel

But I end up with:

```
Process Process-33:


Traceback (most recent call last):


  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap


    self.run()


  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run


    self._target(*self._args, **self._kwargs)


  File "/opt/frigate/frigate/edgetpu.py", line 126, in run_detector


    detections = object_detector.detect_raw(input_frame)


  File "/opt/frigate/frigate/edgetpu.py", line 90, in detect_raw


    self.interpreter.set_tensor(self.tensor_input_details[0]['index'], tensor_input)


  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 399, in set_tensor


    self._interpreter.SetTensor(tensor_index, value)


  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter_wrapper.py", line 109, in SetTensor


    return _interpreter_wrapper.InterpreterWrapper_SetTensor(self, i, value)


ValueError: Cannot set tensor: Dimension mismatch. Got 300 but expected 320 for dimension 1 of input 578.
```

**Comment by blakeblackshear** [comment]
It is. The custom models much match the input and output shape of the builtin model.

**Comment by rb2k** [comment]
And to clarify: That is just the current code, not an actual framework limitation.
We already have to resize the input to that size, so it would just have to figure out what the size of the model is and then use that as the resizing param all over the place, right?

**Comment by Buzztiger** [comment]
Love the idea to use frigate as a squirrel counter. Perhaps we can somehow share our custom trained models that work out of the box with frigate.

**Comment by blakeblackshear** [comment]
Yea. It is definitely possible to have that be a variable.
