### ISSUE TITLE
Updating database location prevent frigate starting

### ISSUE THREAD

**Issue by palinf** [blakeblackshear/frigate#13531]
https://github.com/blakeblackshear/frigate/blob/e80322dab75981f8bab3ddaa4667d1cb9ee087fb/frigate/app.py#L250

Do not use os.rename instead use shutil.move
https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link

This could lead in certains setup to prevent frigate starting.

**Comment by NickM-27** [comment]
I'd suggest submitting a PR

**Comment by NickM-27** [comment]
This has been removed
