### ISSUE TITLE
frigate crash in hassio when clicking on the UI

### ISSUE THREAD

**Issue by SeerKan** [blakeblackshear/frigate#1356]
Hey, installed frigate, configured 1 camera with tpu coral, everything starts ok but when I click the frigate UI it crashed with the error: https://paste.ubuntu.com/p/GDNf3QSzHV/ (my google fu didn't help, so if anybody has any idea... :) )

My configuration (tried with both coral and cpu, same thing, also tried to comment out everything except the camera with 1 path and detect).

`mqtt:
  host: 192.168.86.147
  user: hassio
  password: pass

cameras:
  curte_fata:
    ffmpeg:
      inputs:
        - path: rtsp://hassio:pass@192.168.86.87:554/Streaming/channels/402/
          roles:
            - detect  
        - path: rtsp://hassio:pass@192.168.86.87:554/Streaming/channels/401/
          roles:
            - clips
    width: 849
    height: 480       
    fps: 5
    objects:
      track:
        - person
    snapshots: 
      timestamp: True
      bounding_box: True        
      retain:
        default: 7

detectors:
  coral:
    type: edgetpu
    device: usb`

<img width="1118" alt="Screenshot 2021-07-10 at 17 35 23" src="https://user-images.githubusercontent.com/17612078/125166679-624d0400-e1a5-11eb-9e89-e2a2154da42d.png">

**Comment by lawm** [comment]
What camera model?
Can you try other resolution?

Your log shows:
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-jhawztrk/opencv/modules/imgproc/src/color.simd_helpers.hpp:108: error: (-215:Assertion failed) sz.width % 2 == 0 && sz.height % 3 == 0 in function 'CvtHelper'

Maybe it can't handle 849 width

**Comment by SeerKan** [comment]
@lawm you are right, not sure where I got that width from but I feel dumb :)

However, for guys like me, a better error to help figure this out faster would be awesome.
