### ISSUE TITLE
Change Valid Sign-in Session Duration

### ISSUE THREAD

**Issue by WeetbixNMilk** [blakeblackshear/frigate#13564]
**Describe what you are trying to accomplish and why in non-technical terms**
I want to change how often I am required to sign-in to the WebUI that requires verification. (typically port 8971). For example, instead of a login that stays valid for 2 days, set it to 2 weeks.

**Describe the solution you'd like**
Either a config option in the yaml file or WebUI to change login duration validity.

**Describe alternatives you've considered**
Without removing Frigate's built in security and trusting a reverse proxy with auth, I don't think this is possible.

**Additional context**
Please let me know if this is impossible, unwanted or not planned.

Much appreciated.

**Comment by NickM-27** [comment]
this is already implemented with the `session_length` config
