### ISSUE TITLE
Birdseye background since 0.14 is gray instead of black. I'd like to request it return to true black.

### ISSUE THREAD

**Issue by ksheyman** [blakeblackshear/frigate#13583]
**Describe what you are trying to accomplish and why in non technical terms**
After recent updates, the new UI shows the birdseye feed with a white frigate logo in the center surrounded by a tiny black box, with the remainder of the idle background being dark gray (not true black). In previous versions the birdseye background was entirely black, which made it very nice to display on OLED screens. I even bought an OLED tablet for just this reason. But since the recent update even OLED screens have most of the screen lit all the time because of the gray background. I'd like to see the birdseye background return to true black.

**Describe the solution you'd like**
Return the birdseye background to true black.

**Describe alternatives you've considered**
I tried to make my own custom docker image replacing the current birdseye logo with one with a black background but I haven't been able to get it working (because I don't really know what I'm doing).

**Additional context**
You guys rule!

**Comment by NickM-27** [comment]
nothing changed with birdseye itself, it is just that jsmpeg in the webUI changed display modes to fix unrelated issues. If birdseye is restreamed then it will show the way you want.

**Comment by ksheyman** [comment]
Thank you Nick, however I was just recently advised on Reddit to disable birdseye restream to fix video issues. 

https://old.reddit.com/r/frigate_nvr/comments/1f43cmt/birdseye_in_014/

**Comment by NickM-27** [comment]
We can see what @hawkeye217 thinks about enabling webgl for birdseye, not sure though

**Comment by hawkeye217** [comment]
I'm not fully convinced the jsmpeg renderer is the cause of your issue, specifically because of this: https://github.com/phoboslab/jsmpeg/issues/114

> Funny enough, results of the WebGL Renderer are now identical with the Canvas2D Renderer - which probably was correct the whole time. Closing this as solved. Thanks!

But it still could be, because that issue is pretty old. 

Do you run Home Assistant? If so, can you try looking at birdseye on the tablet in question using the [Frigate card](https://github.com/dermotduffy/frigate-hass-card)?

**Comment by hawkeye217** [comment]
So after some tests, the jsmpeg Canvas2d renderer is in fact causing the issue. Black doesn't seem to be rendered in the same way as with WebGL.

I'll look a bit more into seeing if we can work around this.

**Comment by ksheyman** [comment]
> I'm not fully convinced the jsmpeg renderer is the cause of your issue, specifically because of this: [phoboslab/jsmpeg#114](https://github.com/phoboslab/jsmpeg/issues/114)
> 
> > Funny enough, results of the WebGL Renderer are now identical with the Canvas2D Renderer - which probably was correct the whole time. Closing this as solved. Thanks!
> 
> But it still could be, because that issue is pretty old.
> 
> Do you run Home Assistant? If so, can you try looking at birdseye on the tablet in question using the [Frigate card](https://github.com/dermotduffy/frigate-hass-card)?

Yes I do, I had to re-enable restream in order to get the birdseye camera entity in HA. I'm not at home to use the tablet but I pulled it up on my phone (also AMOLED) and it does appear to be a true black background when viewed thru HA. Isn't this the rtsp stream tho (not jsmpeg)?

**Comment by hawkeye217** [comment]
Birdseye without restream (as jsmpeg) is possible in the Frigate card, but no worries at this point. I've been able to reproduce what you're seeing.

**Comment by hawkeye217** [comment]
I've reverted to the WebGL renderer for the birdseye camera only, so this should solve your issue. The fix will be available in the next version of Frigate.

**Comment by ksheyman** [comment]
> I've reverted to the WebGL renderer for the birdseye camera only, so this should solve your issue. The fix will be available in the next version of Frigate.

Thanks a lot @hawkeye217, it was worth the wait! The problem is gone in 0.15b1.

**Comment by hawkeye217** [comment]
Great! Happy to help.
