### ISSUE TITLE
growing temporal offset

### ISSUE THREAD

**Issue by scantineau** [blakeblackshear/frigate#136]
I have some trouble with frigate... I don't understand why but my camera timestamp is different from frigate timestamp and this difference is growing.

I've been experiencing this with my rpi4 and so I decided to test it on my desktop which is a Ryzen 5 2600X and my graphic card is a GeForce GTX 1050.

Of course this difference is not in the same proportions between my rpi4 (up to 1 minute) and my desktop (up to 5 seconds), but it exists !

So, maybe the problem is in my configuration but I don't know how to debug it...

**Comment by Buzztiger** [comment]
Do the cam and the computer that runs frigate sync via ntp?

**Comment by scantineau** [comment]
I did not check this since when I connect to :5000 with my phone and say hello to my cam, I do not see myself in real time.

**Comment by blakeblackshear** [comment]
What version are you running and what is the FPS and resolution of your camera?

It always starts as realtime? You can look at the timestamps under `frame_info` at the `/debug/stats` endpoint for your camera to see how far frigate thinks it is behind. `read` is the most recent frame from ffmpeg, and `process` is the frame it just finished processing. The difference between the two values should tell you how many seconds behind frigate is in processing.

**Comment by scantineau** [comment]
I changed a bit my config and got a working state with my desktop.
Today I came back to my rpi4 and used the same config. 
I can tell you my camera is a 2Mpx and seems to be 12fps.

What I experience is that after about an hour, I have 13 seconds of difference between the two timestamps. And those 13 seconds are real since when I connect to the 5000 port, I can see myself exactly 13 seconds after going in front of my camera.
![Screenshot from 2020-05-21 09-04-11](https://user-images.githubusercontent.com/8235116/82532661-20e13b80-9b42-11ea-8a29-8c0320e20031.png)

But what I cannot explain is why frigate seems to be synchronized between detected and processed frames : {"detect":1590044621.094271,"process":1590044621.094271,"read":1590044621.094271}

Full json here: 
{"coral":{"detection_start":0.0,"fps":0.0,"inference_speed":16.78,"pid":23},"plasma_store_rc":null,"terrassecouverte":{"camera_fps":12.3,"detection_fps":0.0,"ffmpeg_pid":100,"frame_info":{"detect":1590044621.094271,"process":1590044621.094271,"read":1590044621.094271},"pid":36,"process_fps":12.4,"read_start":1590044621.115511,"skipped_fps":0.0}}

Thanks for your help

**Comment by Buzztiger** [comment]
So on the PC no accumulated lag but only on the Pi? Which Pi container are you running? The one from @kpine?

**Comment by scantineau** [comment]
Yep in its last version !

**Comment by blakeblackshear** [comment]
And it is realtime on your PC? What does the camera_fps say on your PC?

**Comment by scantineau** [comment]
Yes it is realtime on my PC. It's the same camera_fps (~12fps).

Yesterday I put a second camera in my configuration and this morning, I got something similar... 
First cam : 13 seconds as yesterday
Second cam : almost 1 minute !
![Screenshot from 2020-05-22 07-37-11](https://user-images.githubusercontent.com/8235116/82634954-60219200-9bff-11ea-959b-d9e3419bbd5d.png)

But : 
{"coral":{"detection_start":0.0,"fps":0.0,"inference_speed":20.25,"pid":21},"plasma_store_rc":null,"portedevant":{"camera_fps":8.3,"detection_fps":0.0,"ffmpeg_pid":307,"frame_info":{"detect":1590126018.402899,"process":1590126018.402899,"read":1590126018.402899},"pid":39,"process_fps":8.3,"read_start":1590126018.428885,"skipped_fps":0.0},"terrassecouverte":{"camera_fps":8.2,"detection_fps":0.0,"ffmpeg_pid":287,"frame_info":{"detect":1590126018.368872,"process":1590126018.368872,"read":1590126018.368872},"pid":38,"process_fps":8.2,"read_start":1590126018.389727,"skipped_fps":0.0}}

You may notice that the fps are lower (~8 instead of ~12).
I'm now gonna change my configuration and set them to 8 and see what happens...

**Comment by scantineau** [comment]
A bit disappointed this morning... 

The stream delivered by the :5000 is stuck (for both cameras), and not at the same time.

but frigate does not seem to be stuck ! 

{"coral":{"detection_start":0.0,"fps":0.0,"inference_speed":21.84,"pid":205},"plasma_store_rc":null,"portedevant":{"camera_fps":9.9,"detection_fps":0.0,"ffmpeg_pid":334,"frame_info":{"detect":1590173856.006319,"process":1590173855.898507,"read":1590207479.857554},"pid":39,"process_fps":9.5,"read_start":0.0,"skipped_fps":9.9},"terrassecouverte":{"camera_fps":9.9,"detection_fps":0.0,"ffmpeg_pid":314,"frame_info":{"detect":1590169445.382904,"process":1590169445.251859,"read":1590207479.942087},"pid":38,"process_fps":0.1,"read_start":0.0,"skipped_fps":9.9}}

Only the "read" property is changing for both.

I killed processes 38 and 39 and both stream came up again without restarting the container.

Is it possible to "debug" the incoming stream ? I suspect the problem is from the ffmpeg process...
