### ISSUE TITLE
Requesting the old UI

### ISSUE THREAD

**Issue by drtanzil** [blakeblackshear/frigate#13611]
After using the new UI for some time, I’ve found that it doesn’t provide a smooth experience. 
The overall UI and UX feel cluttered, and specific features, like reviewing individual cameras and scrolling, have become quite cumbersome.

Could you please consider reverting to the old UI or offering an option to switch back to it while continuing to receive updates?
Its been a great software, but the recent UI feels horrible to me.

Thank you for your consideration.

Best regards,

**Comment by NickM-27** [comment]
Overall the feedback on the new UI has been overwhelmingly positive. We have also made changes for 0.15 to improve some areas where we have gotten the most feedback on the new UI.

the old docker image still exists, you can go back to running that if you prefer it.

**Comment by PavloveVR** [comment]
https://www.youtube.com/watch?v=uiFLqqKkj3M
While @drtanzil didn't provide much detail as to why 0.15 UI feels worse, the request is sound. Please include a toggle option to switch the UI, people shouldn't have to intentionally run an outdated version because of UI changes.

**Comment by drtanzil** [comment]
@PavloveVR : Thank you for sharing the link. The video explanation is accurate. Frigate was an excellent tool until the release of this new UI. I also went through the comments section and noticed that many users share similar experiences and feedback.

It’s unfortunate that the Frigate team seems to have compromised a good piece of software with these changes. I'm not sure where the positive feedback is coming from, as everyone I know who uses Frigate is facing issues with the new UI. -with @NickM-27

**Comment by NickM-27** [comment]
There are many posts and discussions on forums as well as the many release posts on GitHub here. 

https://github.com/blakeblackshear/frigate/discussions/12829

https://www.reddit.com/r/selfhosted/comments/1ezmnr5/frigate_v0140_a_brand_new_ui_huge_improvements/

https://www.reddit.com/r/frigate_nvr/comments/1fei7gb/014_is_a_huge_jump_in_the_ui_however_i_hope_we/

We also have gotten a lot of positive feedback from users that have reached out privately as well. 

Like it says on https://github.com/blakeblackshear/frigate/discussions/14331#discussioncomment-10935414 we were aware of the gaps and have already addressed a lot of these for the next version of Frigate.
