### ISSUE TITLE
[FR] allow MMB to work in event review page to open the even in a new tab

### ISSUE THREAD

**Issue by TomW1605** [blakeblackshear/frigate#13668]
**Describe what you are trying to accomplish and why in non technical terms**
i want to be able to go through the review tab and easily open events in new tabs to review in greater detail

**Describe the solution you'd like**
when i middle mouse button click on an event it opens in a new tab like a standard web link

**Describe alternatives you've considered**
right now i am opening a new tab for review, finding the event i am interested in and opening it before switching back to the first tab to continue skimming other events

**Additional context**
this is pretty standard web behaviour so implementing it here makes sense

**Comment by NickM-27** [comment]
I've always seen the middle mouse button enable a dragging scroll feature, I've never heard of it being used to click something. 

The review page will go back to where you left off when you press the back button so even if you scrolled down the spot won't be lost. In general this is the advantage of hovering to view the preview as well.

**Comment by TomW1605** [comment]
> Looks like this is custom behavior

lol, it is absolutely *not* a custom behaviour. it has been the default in every browser on every system since i started using computers. it also works within Windows for creating new explorer windows (MMB click on explorer in the task bar) and in almost anything else that has windows or tabs. try it and you will see (unless you are on the review page).

the example given in this [Microsoft Support artical](https://support.microsoft.com/en-au/topic/what-are-the-default-buttons-and-wheel-assignments-for-my-mouse-47f656a8-72d0-63ec-8d1d-dda7122bef6b) goes all the way back to IE7 describing this exact action: "You can press the wheel like a button to access more features. In some programs, you can use middle-click for program-specific features. For example, in Internet Explorer 7, **you can middle-click a link to open the link in a new tab**."


> The review page will go back to where you left off when you press the back button so even if you scrolled down the spot won't be lost. In general this is the advantage of hovering to view the preview as well.

that helps but dosnt work with the way some people want to work. i dont want to be going back and forth between the pages, expecially when the review page changes because i have now reviewed things and reloaded the page. additionally it dosnt always work if, while revewing the event, i switch cameras or have to navigate away, such as to change zone settings.

i dont think this will be a hard thing to implement, if you are simply not wanting to devote resources to it i am happy to take a look. as it is now the review page is unusable for advanced users who expect something that behaves like a link in every other respect to also adhere to this standard

**Comment by NickM-27** [comment]
Tried a few different sites, looks like it does work when specifically hovering over links but for example doesn't work in gmail hovering on an email. 

> as it is now the review page is unusable for advanced users who expect something that behaves like a link in every other respect to also adhere to this standard

Throughout the last 5 months with dev & beta testing as well as full release, we have received mountains of feedback and not a single person has mentioned this until now. So I disagree that it is "unusable for advanced users". 

In any case, will reopen as it seems this can be implemented without disrupting other functionality using the `auxClick` event https://stackoverflow.com/questions/41110264/middle-button-click-event

**Comment by TomW1605** [comment]
for some reason this only seems to work when you MMB click on the preview scrub bar. it dosnt work on the thumbnail or the preview image.

**Comment by NickM-27** [comment]
What browser are you using? I'm not seeing that, it works anywhere on the image

**Comment by TomW1605** [comment]
im using chrome on windows. although i just tried firefox and it is doing the same thing

**Comment by NickM-27** [comment]
I can try that later but on chrome and Safari on Mac I can MMB anywhere and it opens up. the click listener is on the same place that the main click listener is on

**Comment by TomW1605** [comment]
just tested and your right, it works fine in chrome on my mac. no idea why it wouldent work in windows but then does work for that one spesific element

**Comment by TomW1605** [comment]
ok, think i have worked it out. it dosnt work when "Show Reviewed" is on. with that off it works fine

**Comment by NickM-27** [comment]
I am able to reproduce the issue on chrome, doesn't seem like show reviewed has anything to do with it

**Comment by TomW1605** [comment]
intresting, it consistantly works with show reviewed off and dosnt with it on for me
