### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by older-fox** [blakeblackshear/frigate#1367]
Hello, I try to install this application on homeassistant OS and import the custom repo according to the documentation
Just let you know that the HomeAssistant OS is a new installation without any config

And Here is my problem:

1. doc said that need MQTT to work, But I really don't know how to install & config it on HAOS, due to the system itself didn't give me any place to upload/install MQTT
2. doc said that I need create a config file but I don't know what I should write, and log tell me can't connect to MQTT wich is I don't have it.
3. I keep reciveing HTTP 502 Error from the frigate web panel, I checked the Devolop panel(F12) seems like it trying to load config or something, but it just return 502 error. it almost blowed up my browser

Can I get any useful help pls?
That's my firest time use HomeAssistant. Didn't know a lot of it, I tried my best, I'm sorry to trouble you

**Comment by lawm** [comment]
I suggest you follow a guide like https://peyanski.com/home-assistant-frigate-integration/

It will show you how to install Mosquitto, an MQTT Broker, as an add-on through the HA web interface. 

You do need MQTT working in order for Frigate to startup, so start with that first.
