### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by Afterdark1st** [blakeblackshear/frigate#1368]
Fist let me say i love Frigate for the most part it works very well under hassio.
I would like to know how to store the output files to a separate drive i.e. not the main hass ssd drive? 

 - Coral Version: PCIe
 - Network Setup: Wired
  coral_pci:
    type: edgetpu
    device: pci
  

**Version of frigate**
Current version: 1.13

**Config file**
,,, mqtt:
  host: ************
  user: ********
  password: ******

cameras:
  ****_***t:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://********@*******04/
          roles:
            - detect
            - clips
            - record
    width: 2560
    height: 1440
    fps: 5
    objects:
      track:
        - person
        - car
        - bus
        - bicycle
        - motorcycle
      filters:
        car:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
          mask:
            - 0,250,0,426,667,298,666,123
            - 1476,134,1168,86,1169,0,1497,33
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    clips:
      enabled: true
      retain:
        default: 2
    record:
      enabled: true
      retain_days: 7 ``

**Additional context**

The system work as expected its just the amount of data stored on the main drive
    i am using linux debian i have tried Symbolic links?

**Comment by blakeblackshear** [comment]
If you are running frigate with docker, you can mount whatever volumes you want at the media location in the container.

**Comment by Afterdark1st** [comment]
Hi no i was not running in docker i will switch to that now thanks for the advice
