### ISSUE TITLE
Use variable substitution always even without quotes

### ISSUE THREAD

**Issue by RedFoxy** [blakeblackshear/frigate#13692]
**Describe what you are trying to accomplish and why in non technical terms**
Variable substitution is a very convenient function of configuration, in particular it allows you to keep a clean configuration file and share it publicly without giving out private information.I use variable substitution pretty much everywhere, but there are some entries, particularly those that require entering numbers, such as port values, or entering hosts, such as onvif, that do not allow you to use ' and “ as they consider it part of the hostname nor can you use the variable directly {FRIGATE_ONVIF_HOST} as an error is returned in the configuration.

Examples:

Not valid
host: {FRIGATE_DOOR_CAM_IP}
or
host: “{FRIGATE_DOOR_CAM_IP}”
or
host: '{FRIGATE_DOOR_CAM_IP}'
or
port: {FRIGATE_DOOR_CAM_ONVIF_PORT}

Valid
onvif:
  host: 192.168.0.31
  port: 8080
  user: '{FRIGATE_CAM_USER}'
  password: '{FRIGATE_CAM_PASS}'

**Describe the solution you'd like**
Have the ability to use variable substitution even for numeric-only fields and without ' or “ or that the conversion as much as ' or ” are present takes them into account to avoid problems as in the case of the Onvif Host

**Comment by NickM-27** [comment]
The docs state which fields support the substitution, this isn't an issue with the type of the field. https://docs.frigate.video/configuration/#environment-variable-substitution

Quotes are required because {} is an inherent yaml feature so the quotes must be used to avoid the direct handling.

**Comment by RedFoxy** [comment]
I know but if you try to use "{FRIGATE_ONVIF_HOST}" or '{FRIGATE_ONVIF_HOST}' on onvif host you'll get an error because it put the quotas on the hostname

**Comment by NickM-27** [comment]
No, it's not because the quotes are there. It's because onvif host is not a field that allows variable substitution

**Comment by RedFoxy** [comment]
I'm asking to make it to allow variable substitution on it and other variables like port

**Comment by tonsV2** [comment]
This seems to be duplicated here: https://github.com/blakeblackshear/frigate/issues/15622
