### ISSUE TITLE
False positive clips

### ISSUE THREAD

**Issue by walthowd** [blakeblackshear/frigate#137]
Here is an issue to track false positives that are currently occurring with animals. Attached is a clip from today with a squirrel that was identified as a human. 

![squirrel](https://user-images.githubusercontent.com/864569/82474802-35b1c680-9a91-11ea-8e05-e5141ae73d7f.jpg)

[false-positive-squirrel.zip](https://github.com/blakeblackshear/frigate/files/4658254/false-positive-squirrel.zip)

I'm running 0.5.1RC4 with a Coral TPU

**Comment by Buzztiger** [comment]
To be honest I think that is not directly an issue with frigate. The coral model used is a default one. As with all boiler plate NN one needs to further train the network with the actual application data to reduce false positives. 

Especially with a distorted cam image from fish eye lenses common in security cameras. 

My backyard cam recognises sometimes my BBQ or a distant car as a person. Same for the front cam.

So plan of attack would be to store all detection 
images  (furry friends included) and then cross-train the model teaching it what's not a person. 

As a short fix you could play with the min max size settings, unless you have human sized squirrels in which case you might want to be alerted anyway.

**Comment by walthowd** [comment]
Yup, I agree @Buzztiger. This is just intended as file repository though for requested samples for future development. 

https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/1516?u=walt

**Comment by blakeblackshear** [comment]
There is still room for improvement in frigate. I can look at things like speed of the object, overlap with other types of objects, and mean/median/etc of scores as objects are tracked across several frames. I want to reduce false positives as much as possible by addressing some of the low hanging fruit. Those improvements will carry over for custom models too.

**Comment by Buzztiger** [comment]
@walthowd @blakeblackshear understood, that makes sense.

I've got some preliminary notes and working tests on coral cross-training mostly for facial recognition NNs. As frigate is really coming along great (currently part of my home security setup together with HA) I can try (kids/work/pandemic permitting) to write something up specifically targeting coral and frigate. For that a repo with false positives would of course be really helpful.

This could be a chapter in the frigate docs as I assume the false positives would be a main issue for most users ( I slightly turned my BBQ in the end to remove that false positive) and would need ultimately specific tuning to the users camera conditions and setup.

**Comment by mcondren** [comment]
[spider-97percent-person.zip](https://github.com/blakeblackshear/frigate/files/4671939/spider-97percent-person.zip)

Attached clip of my resident spider who will crawl just in front of the lens in the middle of the night. Setting off my alarm notification. This happens regularly and I’m not sure why the white blur is being detected as 97% person. It is really close to the lens so it bypasses my size filter. Looks bigger than it is.

**Comment by angoyd** [comment]
Here is a furry person. Don´t have a sequence but just the picture, if it helps.
![image](https://user-images.githubusercontent.com/24973859/83393074-7a752000-a3f6-11ea-98fb-e81e4aa32359.png)

**Comment by walthowd** [comment]
More squirrels! 

[more-squirrels.zip](https://github.com/blakeblackshear/frigate/files/4712176/more-squirrels.zip)

**Comment by shockerengr** [comment]
![IMG_20200615_141537_164](https://user-images.githubusercontent.com/7873507/84696946-e5544a00-af12-11ea-97d8-c70e9b0f1847.jpg)
Here's a plant that's 93% person.

Note, the frigate stream is only 1024x576 5 fps instead of the full res that my camera system records at.  

[Courtyard - June 15, 2020, 10_44_29 AM.zip](https://github.com/blakeblackshear/frigate/files/4782464/Courtyard.-.June.15.2020.10_44_29.AM.zip)

**Comment by niemyjski** [comment]
This made me 😂🤣. Is there anything we can do to help resolve these issues?

**Comment by TheNico14** [comment]
![cat](https://user-images.githubusercontent.com/37806502/84824640-909ef500-b020-11ea-948a-7a09e2c3c228.jpg)
It happens very rarely but I have several similar situations, if they can help, I'll upload them. 
[cat.zip](https://github.com/blakeblackshear/frigate/files/4788945/cat.zip)

**Comment by mcondren** [comment]
My spider was back last night. 
![894B45A4-3FE1-40C4-89C8-EB2B0CFBB165](https://user-images.githubusercontent.com/32523269/84828818-a8f91a80-aff4-11ea-858e-a1bdf0ac4568.jpeg)

**Comment by jshank** [comment]
Can anyone provide a quick gist or write-up on how to tune the models?

![shadow_person](https://user-images.githubusercontent.com/515808/87331701-46117b00-c4ef-11ea-80d1-6b2d3fec1474.png)

**Comment by walthowd** [comment]
@jshank Probably, don't want to clutter up this thread but hit us up on the HA forum thread. Most people find ~ 85% confidence rate is a pretty good starting point for the person detection. Beyond that in the current release tuning is limited and is all covered in the README -- Future versions will potentially allow some other tflite models that provide better accuracy and Blake has a few ideas to weed things out directly in Frigate too.

**Comment by scstraus** [comment]
Yeah 73% is way too low. You will get tons of false positives.

**Comment by jshank** [comment]
Thanks @walthowd and @scstraus. I've increased the threshold to 85%. I'm still getting 95% matches on neighborhood cats. I'm hoping to gather the false positives and retrain the models but not sure where to start.

@walthowd - Is the disussion [Local realtime person detection for RTSP cameras](https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras) the best place to discuss?

```
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.85 # <----
```

**Comment by niemyjski** [comment]
yeah I set mine to .96% and it seems to do the trick LOL

**Comment by scstraus** [comment]
Increase your minimum detection size to be larger than cats.

**Comment by scstraus** [comment]
I just double checked, and I've been running a .77 threshold for quite a long time, which I found to be a good tipping point. I only get occasional false positives from neighbors cats who come by at night (maybe 10% of the time they visit), or random birds or spiders once a month. I filter all those out with min_area.. It's set a bit larger than I like, but no real human would be able to get up to the house without triggering the detection. If I owned a pet, I'm sure it would be a much bigger issue. Hopefully Blake will work some magic on this so I can go back to smaller min_size someday.

**Comment by ebendl** [comment]
Here's my dog being detected as a person with 90%+ certainty. Granted, she was rolling around on the grass in weird shapes...

I upped the minimum area to 6000 from 4000 after this. I must say, one thought is that if it detected an object as a dog/cat and then a second later as a person, perhaps regard that as a false positive? One would have to weigh in how often actual people are detected as dogs/cats though. 

![2020-08-11 9h24 Backyard](https://user-images.githubusercontent.com/52312239/89877313-35bcf080-dbc0-11ea-940c-8039412c794f.png)
[2020-08-11 9h24 Backyard.zip](https://github.com/blakeblackshear/frigate/files/5055843/2020-08-11.9h24.Backyard.zip)

**Comment by cwallace** [comment]
Is it possible to have frigate only trigger when an object has been detected for x frames? Most of these false positives go away very quickly. I'd prefer detection of 80% confidence over 10 frames versus 95% confidence in one frame.

**Comment by blakeblackshear** [comment]
It actually requires 2 frames currently. I have been accumulating false positives so I can test different thresholds like that.

**Comment by k2xl** [comment]
> It actually requires 2 frames currently. I have been accumulating false positives so I can test different thresholds like that.

Can this be configured?

**Comment by k2xl** [comment]
> > It actually requires 2 frames currently. I have been accumulating false positives so I can test different thresholds like that.
> 
> Can this be configured?

Also related to this, does frigate update the score per this fact? Two frames in a rows with a score of 70% each frame should be higher than one frame at 70%.

 Probably a bayes rule situation?

**Comment by blakeblackshear** [comment]
That statement is no longer true. See here for an explanation: https://github.com/blakeblackshear/frigate/issues/2330#issuecomment-980337268

I tested many different approaches with thousands of video samples and this worked best.
