### ISSUE TITLE
[Feature request] Search / Filter more than 24hrs or multiple days faster.

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#13725]
**Describe what you are trying to accomplish and why in non technical terms**
The 0.14 UI seems to only allow looking at a day at a time, however if for example something is noticed well after the fact being able to go back and search a week quickly would be useful.

**Describe the solution you'd like**
I would like to be able to select a range of days with my filters and see event snapshots

**Describe alternatives you've considered**

An alternative might be to just put forward and back buttons beside the date picker to QUICKLY move days forward and backward saving two / three clicks.

**Additional context**
Let me know if I am missing something in the 0.14 UI that allows this?

**Comment by NickM-27** [comment]
this is already implemented with the new explore page
