### ISSUE TITLE
Request: camera specific prompts for genai

### ISSUE THREAD

**Issue by roger-** [blakeblackshear/frigate#13740]
I'd like to provide some prior description of what my camera is pointing at to improve the text descriptions. 

So if I could prepend a camera specific description to the prompt I think that would help. Something like "this camera is in a garage with a door to the house on the left".

Another idea is to pass the AI model a “nominal frame” so it can focus things that are different in the scene.  This nominal frame would be fixed per camera and taken in good lighting, etc.

**Comment by hawkeye217** [comment]
Yes, this is a good idea. I'll have a PR up shortly.
