### ISSUE TITLE
Out Of Memory after ffmpeg crash

### ISSUE THREAD

**Issue by SabatoArdolino** [blakeblackshear/frigate#13762]
Hi to all 
I've a "little" problem with my frigate. 
I've installed frigate as addon on my home assistant Server (N95 with 16GB RAM).
From 2/3 weeks I see a "strange" issue. For unknow reason ffmpeg stop working and I see on shell that the process consume a lot of CPU (more than 100%) and at the same time the RAM consuming increase until 100%. At this point the server was unresponsable and the only way to resume work is hard shutdown (press power button). As workaround I configure an automation that in case the RAM consuming is over 80% restart the docker of frigate.
Is it a know issue ? if yes how can i fix it ? 
if not how can I set a limit for CPU consuming of ffmpeg ? 
I've this issue only if I activate and deactivate  the motion detection

This is my configuration 

mqtt:
  host: xxx.xxx.xxx.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: XXXXXXXXXXX

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

record:
  sync_recordings: true
  enabled: true
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 10
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 7

cameras:
  Camera:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        #record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://xxx.xxx.xxx.xxx:8554/Camera
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://xxx.xxx.xxx.xxx:8554/Camera_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
    live:
      stream_name: Camera_sub

**Comment by hawkeye217** [comment]
This is not a feature request. Please open a support discussion with the required details.
