### ISSUE TITLE
It does not recognize objects quickly, or when it is moving fast, such as a car.

### ISSUE THREAD

**Issue by milandzuris** [blakeblackshear/frigate#1376]
mqtt:
    host: 192.168.0.2
    user: d********
    password: a*****
    stats_interval: 60

  cameras:
    driveway_camera:
      ffmpeg:
        inputs:
          - path: rtsp://admin:********@192.168.0.200:554//h264Preview_01_sub
            roles:
              - detect
          - path: rtsp://admin:********@192.168.0.200:554//h264Preview_01_main
            roles:
              - clips
              - rtmp
      width: 640
      height: 480
      fps: 5

      objects:
        track:
          - person
          - car
          - dog
          - cat
          - bicycle
          - motorcycle
          - backpack
          - umbrella
          - handbag
          - skateboard
          - bottle
          - cup
          - cell phone
          - suitcase
          - skateboard
          - tennis racket
          - bottle
          - wine glass
          - fork
          - knife
          - spoon
          - bowl
          - banana
          - apple
          - sandwich
          - orange
          - broccoli
          - carrot
          - hot dog
          - pizza
          - donut
          - cake
          - chair
          - teddy bear
          - airplane
          - bird

        filters:
          car:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          cat:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          person:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          dog:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          bicycle:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          motorcycle:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          cell phone:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          bottle:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          bakcpack:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          umbrella:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          handbag:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          airplane:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          bird:
            min_area: 0
            threshold: 0.1
            min_score: 0.1
          cup:
            min_area: 0
            threshold: 0.1
            min_score: 0.1

        filters:
          car:
            mask:
              - 138,480,640,480,640,182,524,142,457,109,421,89,360,102,304,148,317,196,296,210,227,174,117,194,49,244,86,352

      motion:
        threshold: 20
        contour_area: 20

      zones:
        street:
          coordinates: 183,111,251,88,427,103,640,149,640,102,450,64,269,57,206,58,144,61,39,80,25,94,50,138
        field:
          coordinates: 188,69,202,98,181,109,98,124,53,138,31,96
        home:
          coordinates: 0,480,640,480,640,189,464,139,261,98,184,109,51,136,25,95,0,110
        stairs:
          coordinates: 38,192,78,197,80,218,44,231,0,201,0,151
        gate:
          coordinates: 188,69,202,98,181,109,98,124,53,138,31,96

      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 3

  detectors:
    cpu1:
      type: cpu

**Comment by JavaMachine** [comment]
I have the same issue, when someone runs quickly in POV of camera, frigate does not trigger.

I thought maybe 5 FPS for detection is not enough, but found out this:

> 5 frames per second should be adequate. Higher frame rates will require more CPU usage without improving detections or accuracy

**Comment by blakeblackshear** [comment]
It takes 3 frames for an object to be confirmed as not a false positive, so higher frame rates can help for very fast moving objects. With higher frame rates, having a Coral is even more critical.
