### ISSUE TITLE
[Feature] Allowing to inverse masks

### ISSUE THREAD

**Issue by brujoand** [blakeblackshear/frigate#1377]
For most cases I find the mask generator to be super easy to use. However on one of my cameras I basically have noise on all the edges and I only care about movement in the 50% center of the image. Creating a mask for this is kind of tedious and if we could create inverse masks this would be much simpler. Would this be possible and an acceptable approach?

**Comment by trythatagain** [comment]
Nice idea, I could use this as I too only need small areas. Just being able to mask the bits I DO want to be monitored.
