### ISSUE TITLE
Frigate appears to start then stop quickly with errors in the logs

### ISSUE THREAD

**Issue by TomBeech85** [blakeblackshear/frigate#1379]
I'm new to Frigate. I've got it set up as per docs with a very basic config, but I can only seem to get it to work for a few seconds before the UI becomes unresponsive, being presented with a loading animation on my camera. Below is my config and the logs.

I download the repo straight into my custom_components directory. Home assistant is running in VMWare Workstation.

![image](https://user-images.githubusercontent.com/85169303/125438272-6e257b19-466a-4ef0-ad9b-f477fd7bbb3e.png)

![image](https://user-images.githubusercontent.com/85169303/125438229-dd0452a5-f05a-4cd8-942b-014ac6f08911.png)

**Comment by TomBeech85** [comment]
I needed to use the following lines as I'm not using a Coral box. This might need to be put in the docs?

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

**Comment by rodpayne** [comment]
I also received this error when I first installed.  This might be a good default to have for the brand new user who is trying out the software before buying a Coral box.  Or maybe it could detect the absence of the hardware and switch the default.
