### ISSUE TITLE
Feature Request: Integration with Kubernetes

### ISSUE THREAD

**Issue by pixeldrew** [blakeblackshear/frigate#138]
I have been doing a bit of research in getting Tensorflow lite models into kubeflow along with adding support for edge TPU's for inference. There was recently a patch added to https://github.com/adaptant-labs/k8s-dt-node-labeller to help identify nodes in a cluster that support specific device id's (ie, edge tpu's like coral)

I haven't been through your architecture too deeply but was wondering if you would have an idea about how difficult it would it be to support clustering with kubernetes? Considering you already use compose, would it be possible to adapt your usage of TF to a kubeflow pipeline?

**Comment by blakeblackshear** [comment]
You should be able to use that to schedule the frigate pod on a node that matches the selector. I don't think any architecture changes are needed for it.

**Comment by pixeldrew** [comment]
I'll give a crack to try and convert some docker-compose examples. I'm wondering about the config.yaml you have as to how to correctly add that as a config in k8, i'll let you know if I run into any problems.

**Comment by blakeblackshear** [comment]
This should help you get started: https://github.com/billimek/billimek-charts/tree/master/charts/frigate
