### ISSUE TITLE
Automatically delete all older clips, snapshots, events,etc. through the frigate app

### ISSUE THREAD

**Issue by Lulugaot** [blakeblackshear/frigate#13808]
Would like the ability to be able to automatically delete video clips, events, snapshots, recordings etc. , user selectable criteria such as older recordings before a certain date directly from the UI to prevent my SSD which is on my NAS Pi3 running OMV 6 from getting full (storage wise) or perhaps the option to overwrite the older files when storage gets full. My frigate instance runs on my Pi5 as an add-on through Home Assistant and I created the frigate folder on my NAS and had been working fine. But my 1 TB SSD fills up even with 7 day retention of files. My NAS does have two 1 TB SSD's one of which is for frigate as stated above and the other is used for Home assistant backups. The Pi 5 is used for home assistant with the frigate add-on running from an official Pi NVME hat using a Corsair 1 TB NVME SSD M.2 drive. It would probably be a lot easier to automatically do it through the UI instead of going into OMV and deleting older frigate files from its folder. I also don't know if it's possible since that db folder is not on the same machine running HA even though the files are saved there. I am stuck trying to come up with something like an automation to maybe do it automatically since I have no clue in attempting to write a script to do it for me. I am pretty computer savvy but I'm lost at the moment. Thank you and sorry about the long rant. Frigate runs excellent since last update 14 on my Pi 5 using the Coral along with the frigate notifications blueprint, kudos to all involved from this community and much respect as well.

**Comment by NickM-27** [comment]
Frigate already automatically deletes recordings when storage becomes full

https://docs.frigate.video/configuration/record#will-frigate-delete-old-recordings-if-my-storage-runs-out

Otherwise you just need to configure retention that makes sense for your storage

**Comment by Lulugaot** [comment]
Thank you !  Wasn't sure it would delete the files which are on my NAS , not my other pi running home assistant with the frigate add-on which does not have the files saved to it.
