### ISSUE TITLE
Remove 15 second minimum MQTT stat interval for audio sound level metering purposes

### ISSUE THREAD

**Issue by devnullblackcat** [blakeblackshear/frigate#13843]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to decrease the minimum MQTT stat interval so that I can plot the audio data using Home Assistant with much greater accuracy.

**Describe the solution you'd like**
Remove the hardcoded 15 second minimum MQTT stat interval.

**Comment by NickM-27** [comment]
It only applies to /stats, the audio topic is separate. The limit is also intentional for stats
