### ISSUE TITLE
Any option to limit camera(s) access per user?

### ISSUE THREAD

**Issue by SuperMaximus1984** [blakeblackshear/frigate#13877]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to limit camera / Frigate UI access per user. Is it possible to configure user/group policy in 0.14?

**Describe the solution you'd like**
User 1 has access to Camera Group 1, User 2 has access to Camera Group 2 and so on. Some user can see Events, some not.

**Comment by hawkeye217** [comment]
Roles/groups already has a pinned feature request and is planned for a future version. This is a duplicate of https://github.com/blakeblackshear/frigate/issues/6614
