### ISSUE TITLE
Mark items as reviewed in top bar of the page

### ISSUE THREAD

**Issue by goedh452** [blakeblackshear/frigate#13870]
On the review-page the button "Mark these items as reviewed" is at the bottom of the page. It takes a lot of scrolling when there are several hundreds of clips. Most of the time a glance at the top dozen of clips is want you would want to review. Putting the button in the top bar of the page would prevent te scrolling. Since the top bar is always visible, the button the there when you need it.

**Comment by NickM-27** [comment]
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/11756

**Comment by timguy99** [comment]
Sorry about that. I did do a search before posting but strangely didn't find anything.

With all the threads though it looks like all were just closed saying not implementing. Was it decided this is NOT a good feature? Odd to me but whatever, everyone has different opinions.

**Comment by NickM-27** [comment]
Yes, like it says in the original issue that was linked if you have a lot of images that are not relevant / worth reviewing then this is a config issue and you should configure the alerts and detections to match what is desired. Marking items as reviewed when you have not even checked the images makes no sense, they have not been reviewed in any way.

**Comment by timguy99** [comment]
This is a trap that a lot of developers and product people make. They THINK they know best how a user is going to use something and try to force them down those very rigid paths even if the user has legitimate other use cases or use the product slightly differently than it is intended.

**Comment by NickM-27** [comment]
Right, and if you want to do that then you can use keyboard shortcuts to select all and mark as reviewed. It doesn't make sense to have a button that encourages a user to use it in a way that doesn't make sense.

**Comment by hawkeye217** [comment]
For reference, the keyboard shortcut is Ctrl/Cmd-A to select all, then "R". Although this works to quickly dismiss review items, it is done inefficiently right now and will be improved in the next release.

**Comment by timguy99** [comment]
This must be in a newer version cause I have no select options that I can see. Also, wondering how that would work on iOS, probably won't. I'll look to upgrading soon.
