### ISSUE TITLE
UI to respect 401 headers, allowing handling external authentication expiry 

### ISSUE THREAD

**Issue by neutralvibes** [blakeblackshear/frigate#13898]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 
UI to detect when calls it makes to the api are no longer authorised and reload the page. This would then allow external proxy authentication methods to prompt for re-authentication.

**Describe the solution you'd like**
I would like the handling of 401 errors to be handled in javascript for all api calls, with the intention of recognising the user is no longer authorised. On detection, the frontend will fully reload the page by redirecting to its full URL. It may be preferable to display a page with the status presented and a link. This will enable the authentication provider utilised by a proxy server to kick in. In my particular case oauth.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by blakeblackshear** [comment]
This is already supported. https://docs.frigate.video/configuration/authentication#login-page-redirection

**Comment by neutralvibes** [comment]
> This is already supported. https://docs.frigate.video/configuration/authentication#login-page-redirection

Can you suggest a simple example for this using traefik
