### ISSUE TITLE
FEATURE REQUEST: In the Review page, clicking on the video stream should perform same play/pause function of the play/pause button

### ISSUE THREAD

**Issue by chrislawso** [blakeblackshear/frigate#13921]
FEATURE REQUEST: In the Review page, clicking on the video stream should perform same play/pause function of the play/pause button. (edit: pressing keyboard spacebar does perform play/pause function.)

Currently, a user must first find and recognize how to play or pause, next they must move mouse cursor to and click the small play/pause button at the lower middle part of screen. For some users these steps to play and pause may be challenging.

Adding the above feature requests, if possible, would offer similar user experience to other streaming software and streaming websites.

Other observation, currently double clicking left mouse button zooms into the video stream in Live and Review mode, which I don't know if it conflicts with the above feature request. Pinching on laptop trackpad is alternate method that also performs zoom in.

**Comment by NickM-27** [comment]
Spacebar already does this to be clear

**Comment by chrislawso** [comment]
> Spacebar already does this to be clear

You are absolutely correct. I don't know why I thought it did not work. 
I tested now in edge, chrome, firefox and spacebar does this.
