### ISSUE TITLE
Add metrics endpoint

### ISSUE THREAD

**Issue by IAmKonni** [blakeblackshear/frigate#13980]
I would like Frigate to expose the metrics available in the UI as metrics endpoint. So everyone can monitor CPU usage, GPU usage, counted objects, storage, cameras, etc. via prometheus and grafana.

**Describe the solution you'd like**
Expose all available stats as metrics endpoint (`/metrics`).

**Describe alternatives you've considered**
Scraping the UI and exposing it on my own.

**Comment by NickM-27** [comment]
this already exists https://docs.frigate.video/integrations/api#get-apistats
