### ISSUE TITLE
Green distorted screen 

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1400]
I add two cameras and one shows distorted green and other kinda of double image black and white.  What am I doing wrong?

This is my setup:
Frigate docker installed on Ubuntu / intel core -5 mini desktop.
one  wyzecam, v2 and one wyzecam pan with rtsp firmware.  able to see the rtsp feed using vlc fine.
but on frigate web ui, it looks distored green.

![image](https://user-images.githubusercontent.com/19213088/126094520-6a6e3e7d-2b39-417f-8e7d-ae34d6535fce.png)

**Frigate docker-compose:**
  frigate:
    container_name: frigate
    image: blakeblackshear/frigate:0.8.4-amd64
    privileged: true
    shm_size: '100m'
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ${DOCKERDIR}/frigate/config:/config
      - ${DOCKERDIR}/frigate/dri:/dev/dri
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDIR}/frigate/media:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 75000000 ## 75MB, good for 3 1080p cameras with 10s of cache each, this depends on your setup.
    ports:
      - 5000:5000
    restart: unless-stopped

**Frigate config:**
mqtt:
  host: 192.168.99.3
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
cameras:
  reef:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.90.13:8554/reef
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 2
  front:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.90.4/live
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 2

detectors:
  cpu:
    type: cpu

**Comment by balajeek** [comment]
Here is the log from frigate:

frigate.video                  INFO    : front: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
watchdog.front                 INFO    : No frames received from front in 20 seconds. Exiting ffmpeg...
watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.front                 INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
watchdog.front                 INFO    : No frames received from front in 20 seconds. Exiting ffmpeg...
watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures 
(this above line repeats dozen times)

frigate.video                  INFO    : front: ffmpeg sent a broken frame. PyMemoryView_FromBuffer(): info->buf must not be NULL
frigate.video                  INFO    : front: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : [h264 @ 0x563b4b536c80] error while decoding MB 22 41, bytestream -
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.front.detect            ERROR   : [rtmp @ 0x563b4b628c80] Cannot open connection tcp://127.0.0.1:1935
ffmpeg.front.detect            ERROR   : rtmp://127.0.0.1/live/front: Immediate exit requested
watchdog.front                 INFO    : No frames received from front in 20 seconds. Exiting ffmpeg...
watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.front                 INFO    : FFmpeg didnt exit. Force killing...

**Comment by lawm** [comment]
Check the resolution

**Comment by balajeek** [comment]
You are right, changing the resolution to 1080 worked for both the camera's.
Thank you so much.

**Comment by balajeek** [comment]
Also wondering if I have to set the fps to how much the wyzecam fps is, their spec says 15fps day, 10fps night.
thank you.
