### ISSUE TITLE
 Default Sort Order for Exports or Sort Selector

### ISSUE THREAD

**Issue by cdmichaelb** [blakeblackshear/frigate#14026]
**Describe what you are trying to accomplish and why in non-technical terms:**

- I want the exported files to be organized in a way that makes it easy to find and review them. Currently, when I export files, they are sorted alphabetically by default. This can be confusing and inefficient, especially when dealing with multiple files from different dates and times. I believe sorting the exports by date and time, with the most recent files appearing first, would make it much easier to locate the files I need. 

- Additionally, having the option to choose how the files are sorted through a drop-down selector would provide flexibility for different users' preferences.

**Describe the solution you'd like:**
I would like the default sort order of exported files to be based on the date and time they were created or captured, with the most recent files listed first. This chronological sorting would help in quickly identifying the latest exports. Furthermore, implementing a drop-down selector that allows users to choose their preferred sort order—such as by date/time, alphabetical, or file size—would make the system more user-friendly and customizable.

**Describe alternatives you've considered:**

- I've considered manually renaming the exported files to include the date and time so they sort correctly when listed alphabetically. However, this process is time-consuming and not practical when dealing with large numbers of files. Also, it doesn't work as expected.

- Another alternative is manually sorting the files in my file explorer after export, but this adds extra steps and doesn't solve the issue of quickly finding files immediately after export within the application.

**Additional context:**
Having exports sorted by date and time is particularly useful in scenarios where multiple files are generated over short periods, such as continuous camera recordings or sequential event logs. For instance, if I export footage from several cameras covering an event that occurred between 08:25:13 and 08:45:33, I need the files to appear in order, so I can easily reconstruct the sequence of events:

If these files are sorted alphabetically, they may not appear in the order of the events, making it harder to analyze the footage. A default sort by date/time, or the ability to select the sort order, would greatly enhance usability.

**Comment by NickM-27** [comment]
Exports in the UI are sorted by the date they were created already

**Comment by cdmichaelb** [comment]
> Exports in the UI are sorted by the date they were created already
> 
> https://github.com/blakeblackshear/frigate/blob/f4f3cfa91152952c1a96a9bc721fa3e1b270a9b8/frigate/api/export.py#L28

~~Does that not include time? Because they do seem to actually be by date, but then they seem to be random (perhaps?)~~

**I see now it sorts by date → alphabetical.**
I would then change my feature request to change that to date → time → alphabetical. (Or a given selector)


Below, I was writing this before I realized it was definitely doing it date → alphabetical. But essentially it shows that they are not in order of creation or true date/time.

From my screenshot, 1-7 were created first, before I decided to change how I was naming them. 5 definitely came after 4 because I realized I exported the wrong times.

If they were sorting by time in addition to date, the order should be something like:

??, ??, 09,  08
17, 18, 17 ,14
13, 10, 11, 12
01, 02, 03, 04
??, ??, 06, 05

Sorry, 13→16 aren't included in the below but didn't make it on the screenshot. ?? And ?? Can be presumed to be 13, 14? But I don't think it really matters at that point.

![image](https://github.com/user-attachments/assets/f8bd711f-e919-44a3-80d1-7c525dff991d)

**Comment by NickM-27** [comment]
in this case `date` is the unix timestamp (so it represents a specific second in time) and that is what they are sorted on. and it is the timestamp of the recording start time, not the time that it is created

**Comment by cdmichaelb** [comment]
> in this case `date` is the unix timestamp (so it represents a specific second in time) and that is what they are sorted on. and it is the timestamp of the recording start time, not the time that it is created

Ah yea, that's it. Sorry lol. I just realized 1-4 actually have time stamps that are a few second more recent, I didn't set them at the same exact times when I went to change the naming scheme I was using.
