### ISSUE TITLE
Synchronize Recorded Streams Using RTCP Sender Reports (SR)

### ISSUE THREAD

**Issue by vosaica** [blakeblackshear/frigate#14070]
**Describe what you are trying to accomplish and why in non technical terms**
I want to synchronize recorded video streams from multiple cameras so that the footage from each camera is aligned in time.

**Describe the solution you'd like**
I would like Frigate to incorporate a method for using RTCP Sender Reports (SR) from cameras to synchronize recorded video streams.

**Describe alternatives you've considered**
Alternatively, I hope there could be a way to extract RTCP SR data and include the timestamps in the metadata of the footage.

**Additional context**
Since Frigate relies on FFmpeg, to my knowledge, FFmpeg cannot access RTCP SR data directly through the binary. It seems that another program is needed to listen to the streams and capture this information.

**Comment by NickM-27** [comment]
If ffmpeg doesn't support this then I really don't see a path to implementing it. 

Personally, my cameras are very well synchronized and scrubbing through footage a car is in the exact same place on multiple cameras. I don't really see a need to support this especially if there is going to be such a high burden to implement, add configuration, and somehow sync this up with ffmpegs recording segment creation.
