### ISSUE TITLE
RFE: Keyboard shortcuts during alert review 

### ISSUE THREAD

**Issue by cidrblock** [blakeblackshear/frigate#14095]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to navigate the alerts and detections with the keyboard

**Describe the solution you'd like**
1) Introduce a keyboard shortcut to scroll the alerts and detections 
-or-
2) Update the main windows of alerts/detections when the timeline is scrolled as the keyboard can be used to scroll within the timeline (PG Up/PG down/space bar)

**Describe alternatives you've considered**
Use the mouse scroll wheel

**Additional context**
The UI refactor and workflow changes are absolutely awesome.  The only issue is now I feel obligated to review all alerts and detections daily.  Introducing keyboard shortcuts to speed the review and markinging reviewed of alerts and detections would save several seconds every day and improve my qualiity of life.  

Seriously, TY for everything you have done.

**Comment by NickM-27** [comment]
> The only issue is now I feel obligated to review all alerts and detections daily. 

well, that is kind of the idea in general. If you find yourself reviewing things you don't care about then that can likely be improved by adjusting the config to not save review items in those cases. 

One of the main advantages of the review UI is to hover over the review items to see the preview and quickly understand what happened. Keyboard shortcuts as the entire workflow would miss out on this and IMO it would be slower to use a keyboard to view these vs just moving the mouse and hovering where you want to view. 

I think it would help to have specifics on what time would be saved and where

**Comment by cidrblock** [comment]
We've got a number of cameras that cover almost the entire property. This includes areas where we would normally expect to see family, cars and dogs moving around, as expected, throughout the day,

For instance on a givien day one or two of our cars may go up and down the driveway, as well as an amazon delivery and/or UPS truck.

So for now, we've configured everything to not detect stationary objects (parked cars) and hopefully impossible scenarios (a car on the deck).

Given the placement of the cameras and resolution, I don't think even a custom model could differentiate between a family members or unexpected pedestrian visitor.

My current workflow is to alert on everything and quickly scroll through the list once or twice a day. Given the unhovered alerts are zoomed in, I can scroll through a list of 200-300 daily alerts and quickly identify if the activity is expected based on the object.

I have considered focusing more on the perimeter with narrower bands but I would miss the internal activity which is equally important when sharing the residence with elderly individuals whose activty I like to see.

I was simply hoping that a down arrow or Pg down bkey could scroll the main alert window, but even in focus it does not. The time line does, but the main window doesn't update whn the timeline is scrolled.

**Comment by maglub** [comment]
In a different project I started using the javascript based "mousetrap" at https://github.com/ccampbell/mousetrap, which at a first glance might feel a bit outdated. But, then I found this documentation for the Gitlab product, where they mention that they are using this javascript integration: https://docs.gitlab.com/ee/development/fe_guide/keyboard_shortcuts.html

That could be a way forward, perhaps?

**Comment by hawkeye217** [comment]
This feature has already been implemented in the dev branch and will be available in the next version of Frigate.
