### ISSUE TITLE
Add support for the upcoming Particle Tachyon SBC

### ISSUE THREAD

**Issue by raenrfm** [blakeblackshear/frigate#14137]
**Describe what you are trying to accomplish and why in non technical terms**
I will be building a NAS around the new upcoming Particle Tachyon (due to ship 1st quarter 2025) and they have said they would be interested in helping to port Frigate to their platform which contains a 12 TOPS AI engine which is roughly 4 times more powerful than the Coral.

**Describe the solution you'd like**
I would like to be able to run Frigate on the Particle Tachyon and utilize it's powerful AI processing.

**Describe alternatives you've considered**
Adding a Coral to the Tachyon, but that seems unnecessary considering the Tachyon already has an AI processor

**Additional context**
https://www.kickstarter.com/projects/particle-iot/tachyon-powerful-5g-single-board-computer-w-ai-accelerator/description

Quote from one of their collaborators:
The Tachyon should outperform Coral as the on-board NPU is ~12 TOPS whereas Coral is ~4 TOPS. We'll have to test it to see if real-life performance matches that but it should definitely be possible to achieve the same degree of performance. The Frigate project would have to be ported to Tachyon but that's something we'd love to support!

-Zach Supalla

**Comment by NickM-27** [comment]
this would be done as a community supported board https://docs.frigate.video/development/contributing-boards

**Comment by raenrfm** [comment]
So are you saying I would have to develop it myself?

**Comment by NickM-27** [comment]
not necessarily you, but someone. Like it says in the linked docs

> There are many SBCs (small board computers) that have a passionate community behind them, Jetson Nano for example. These SBCs often have dedicated hardware that can greatly accelerate Frigate's AI and video workloads, but this hardware requires very specific frameworks for interfacing with it.
>
> This means it would be very difficult for Frigate's maintainers to support these different boards especially given the relatively low userbase.
>
> The community support boards framework allows a user in the community to be the codeowner to add support for an SBC or other detector by providing the code, maintenance, and user support.

**Comment by raenrfm** [comment]
Ok I can't seem to find what you're talking about, the information in there is for someone who will be developing for the board themselves.  Is there a forum I can post the suggestion in for this group?

**Comment by profporridge** [comment]
@raenrfm the community supported board system is a great way to allow communities to add support for different platforms without impacting the core of the project. Of course,  software doesn't write itself (yet) but I'm sure that there are many developers who would be happy to lend a hand in exchange for an engineering sample or two.

**Comment by raenrfm** [comment]
So would I just put it out there and wait for someone to bite and then
arrange to speak to the engineering team at Particle?

**Comment by profporridge** [comment]
@raenrfm is there an email that interested developers can reach you at?

**Comment by raenrfm** [comment]
@profporridge I wouldn't give it out here but in a PM.  I don't have the board yet, that is coming in the new year.  I would think that any dev would want to speak to Particle directly as they have already stated that they would support anyone who wants to port Frigate to use their Tachyon board.
