### ISSUE TITLE
Time based Alerts/Detection settings

### ISSUE THREAD

**Issue by alelio** [blakeblackshear/frigate#14146]
**Describe what you are trying to accomplish and why in non technical terms**
I love the new Review system! After having used it for a couple of days though I think it can be further optimized so to reduce the amount of Alerts that needs to be reviewed.
Suppose I have a space that has known Person traffic during the day, but not during the night. As it is, I need to leave Person enabled as Alert in a specific zone, causing a large number of unnecessary alerts during the day. I'd still want these to be captured as Detections, but not as Alerts during the day; during the night instead, any Person entering the area should trigger an alert.
The "security profile" of various zones often changes between day and night, and this system would perfectly capture that without the need of extra scrutiny.

**Describe the solution you'd like**
The new Alerts/Detection system can be further improved by adding time-controls to the existing per-object and per-zone alerts vs detections setups. 
This can be achieved by allowing the possibiltiy in the camera config (and ideally UI) to setup a matrix where each object (Person, Car, Etc) by each zone (Door vs Sidewalk) can be classified as Alert, Detection or neither (ideally, for full flexibility) for each hour of the day.
EDIT: To clarify, a 24 columns table should be presented (for each hour of the day), with a variable number of rows, depending on the Objects/Zones configured for the specific camera.
If only specific Objects are set for a zone, only the specified Object/Zone combination for that zone should be presented.
The defaults can be set as per the global default, as presently done.

**Describe alternatives you've considered**
I have considered leveraging other applications to achieve this (HA, possibly through MQTT). However this seems best handled natively in Frigate.

**Additional context**
I can see this being applicable to uses in both residential and commercial setting.
Thanks again for giving Frigate to the world!

**Comment by supermarkert** [comment]
FYI, there is a related feature request to expose enable/disabling Alerts via MQTT, so then you could schedule it via Home Assistant any way you wish.
https://github.com/blakeblackshear/frigate/issues/13038

**Comment by NickM-27** [comment]
yeah, I don't think it makes sense for Frigate to implement time based directly. Every user has their own context and inputs they want to use. For example a common one might be sunset. This is something that is best handled via external automation tools

**Comment by sergiobaiao** [comment]
> yeah, I don't think it makes sense for Frigate to implement time based directly. Every user has their own context and inputs they want to use. For example a common one might be sunset. This is something that is best handled via external automation tools

I can think of one reason for the time based detection. and it's quite simple. Think about a shopping mall. During the day, it's normal to have lots of lots of people walking around, so detection doesn't make sense, but during the night there should be no movement whatsoever, and so detection must be enabled. Think about 20K people being detected, the CPU/GPU usage shall reach extreme levels. If we could say it should only record during day, but at night detect/alert also, it would be awesome

**Comment by NickM-27** [comment]
Right, but that can already be done with the API / MQTT and any cron job, automation software, etc. Which is the main point here

**Comment by sergiobaiao** [comment]
But Only for the notifications, not the detection itself. It's useless to
have detection enabled consuming cpu/gpu/power in a time period where
detection is not needed.  The only possible way I could think to make it
work actually is to have two different configurations and create some kind
of automation to stop the service, switch the configuration files, then
start it again. Not very productive and subject to failures...just my
two cents

Enviado do meu IPhone
