### ISSUE TITLE
Is it possible to trigger a record event externally ?

### ISSUE THREAD

**Issue by muzzak123** [blakeblackshear/frigate#1414]
I find Frigate very useful and the interface is great but I've noticed it often misses events at night. 
When I look at the Detection FPS I see that it does go up, so the motion is detected, but it appears the object is not recogcnised by Frigate and nothing is recorded.
Hence I was wondering if there was a way to externally trigger an event and thus create a recording manually.
eg if "Detection FPS" goes above x then record on camera z for the next y seconds ?

**Comment by blakeblackshear** [comment]
There is no way to do this currently.
