### ISSUE TITLE
Small Documentation issue for HTTP API - Exports (says to delete by name, but requires id)

### ISSUE THREAD

**Issue by accessiblepixel** [blakeblackshear/frigate#14177]
So the documentation page
https://docs.frigate.video/integrations/api#delete-apiexportexport_name

It says to delete an export use the export name (which to get you have to query /api/exports but that's also not on the api documentation page) but I found out that it's actually looking for the id, not the name.

For example (from /api/exports):
``{"camera":"02-front-entrance","date":1728223422.6098619,"id":"02-front-entrance_9quj58","in_progress":false,"name":"02-front-entrance_o658u7","thumb_path":"/media/frigate/clips/export/02-front-entrance_9quj58.jpg","video_path":"/media/frigate/exports/02-front-entrance_o658u7.mp4"}``

Trying to delete (with DELETE /api/exports/<name>) by the name listed ``02-front-entrance_o658u7`` is unsuccessful ``Export not found.`` but deleting by the id ``02-front-entrance_9quj58`` is successful.

So I believe that ``DELETE /api/export/<export_name>`` should read ``DELETE /api/export/<export_id>``

Thank you, and I apologise if this is posted in the wrong way/format - The bug reporting page was asking many things about my setup that didn't seem relevant for a documentation issue :)

**Comment by NickM-27** [comment]
Thanks, this will be fixed in the next version where API documentation will be shown using swagger and generated automatically from the api definition

**Comment by hawkeye217** [comment]
Fixed in https://github.com/blakeblackshear/frigate/pull/14178
