### ISSUE TITLE
0.5.1: Bus error (core dumped) python3.7 -u detect_objects.py

### ISSUE THREAD

**Issue by niemyjski** [blakeblackshear/frigate#142]
0.5.0 was working pretty good. After a few minutes of running (within a half hour) it crashed with the following error: Any ideas on how to increase the log level?
```
Starting process for storage_room: 81
 * Serving Flask app "detect_objects" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
./run.sh: line 7:    18 Bus error               (core dumped) python3.7 -u detect_objects.py
```

**Comment by blakeblackshear** [comment]
Is this still happening?

**Comment by niemyjski** [comment]
Yep :( I moved back to 0.5.0 for the time being.

**Comment by blakeblackshear** [comment]
Not sure what is different about your setup that could cause this.

**Comment by niemyjski** [comment]
Running 10th i7 gen nuc with the usb stick on Ubuntu 20 lts using the ha docker addon. Only thing I can think of is maybe shm-size which I don’t know how to set but I only have two cameras going into it currently.

**Comment by niemyjski** [comment]
I just noticed these in my 0.5.0 logs maybe this has something todo with the crashes on 0.5.1 (maybe the queue has no messages and quits)?

```
/arrow/cpp/src/plasma/store.cc:738: Disconnecting client on fd 11
/arrow/cpp/src/plasma/store.cc:738: Disconnecting client on fd 9
/arrow/cpp/src/plasma/store.cc:738: Disconnecting client on fd 10
/arrow/cpp/src/plasma/store.cc:738: Disconnecting client on fd 8
Process for living_room is not alive. Starting again...
Camera_process started for living_room: 204516
Process for storage_room is not alive. Starting again...
Starting process for living_room: 204516
```

**Comment by knobunc** [comment]
I just got around to trying Frigate and hit this.  I dropped to a lower resolution stream.  I suspect the SHM size is the culprit, but since I'm using the unofficial add-on to run it, it's not easy to set.

**Comment by niemyjski** [comment]
@knobunc yeah, apparently to set the shm size via the add-on we need to actually make HA supervisor changes. I've been super busy and haven't been able to get around to it, but nice catch if this is it.
