### ISSUE TITLE
The coral is very slow. It always shows 162ms

### ISSUE THREAD

**Issue by nguyenvanchiem** [blakeblackshear/frigate#14200]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/14199

<div type='discussions-op-text'>

<sup>Originally posted by **nguyenvanchiem** October  8, 2024</sup>
I install latest version (0.14.1) and have coral ls /dev/apex* show /dev/apex_0
The basic config in Frigate
mqtt:
enabled: false
detectors: # <---- add detectors
coral:
type: edgetpu
device: pci
cameras:
test: # <------ Name the camera
enabled: true
ffmpeg:
inputs:
- path: rtsp://192.168.1.44:39423/a42e6c77cee82b0f # <----- The stream you want to use for detection
roles:
- detect
detect:
enabled: false # <---- disable detection until you have a working camera feed
version: 0.14

But the coral is alsway high. The coral is very high as image below. it is alsway 162. Do you have advice for this case?
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/c1498d06-727d-466e-8e1e-e23c58153672">
<img width="760" alt="image" src="https://github.com/user-attachments/assets/91cfccd3-9334-481a-9b67-bed05d6c3050">
</div>

**Comment by NickM-27** [comment]
stop creating issues from the discussion, you get support in the discussion

**Comment by zee-shany** [comment]
i'm having similar issue after i upgraded to 0.14. I have 2 coral USB TPU and both used be at 20 inference speed, now they are at 120.. where can i get support/ which discussion is pointed above?

**Comment by NickM-27** [comment]
nothing changed regarding the coral between releases. You get support by creating a support discussion
