### ISSUE TITLE
Add a custom meta field per camera to be appended to mqtt events topic

### ISSUE THREAD

**Issue by phillmac** [blakeblackshear/frigate#14275]
I have cameras where the name is changed often but I have a DB indexed by camera serial and I would like to have a static reference as well as the camera name in the mqtt events feed

I'd like to be able to add an key  & value e.g. cameraSerial in the config per camera that is appended verbatim to the mqtt  events feed 

I had a quick look at the mqtt communication module however I could not make heads or tails of how to go about it.

**Comment by phillmac** [comment]
https://gitpay.me/#/task/960

**Comment by NickM-27** [comment]
I think more information is needed, why do the names of cameras change? Why do you need to configure it Frigate this extra data, do you not already know it on the other side of MQTT?

I don't think it makes sense for Frigate to send arbitrary data along with all camera MQTT messages

**Comment by phillmac** [comment]
@NickM-27 
Why does the name of the cameras change? 
 - Because they are portable and the display name of the cameras change depending on location. 
 
Do you not know it already on the other side of MQTT?
 - No, there is a very real chance that the names will no longer match. The canonical identifier for the camera is the serial.
 - Alternately having a 'display nick name' option that shows in the web UI and elsewhere might solve the problem. 
 - The serial number doesn't mean anything to a human so its not practical to use that as the displayed name, it would make frigate next to unusable with anything more than a couple of cameras

**Comment by NickM-27** [comment]
It just doesn't make sense, maybe I'm misunderstanding. If you know the name of the camera to put into a friendly name field in the config why not just put that name in the existing name field in the config.

**Comment by phillmac** [comment]
I tried that, everything went to hell in a handbasket. None of the live feeds would load anymore. 
The every part of the api started throwing http 500 errors
I could load the bare UI itself but nothing more.

I couldn't find how to use it in the full config reference so im guessing it no longer works?

**Comment by pnogemane** [comment]
Is the issue still available to pick up?
