### ISSUE TITLE
Addons link goes to HA docs, should it go to Frigate Addons Repo?

### ISSUE THREAD

**Issue by askpatrickw** [blakeblackshear/frigate#14293]
https://github.com/blakeblackshear/frigate/blob/6e332bbdf8600dc22a297d5098281d6e3d141f69/docs/docs/frigate/installation.md?plain=1#L6

The link in the docs goes to https://www.home-assistant.io/addons, should it instead go to https://github.com/blakeblackshear/frigate-hass-addons?tab=readme-ov-file#installing?

Happy to make the PR, just want to know the fix is desired first.

**Comment by NickM-27** [comment]
No, the link is there to define what a hassos addon is. There are specific instructions below that say how to install the addon

**Comment by askpatrickw** [comment]
Ah.. well I was just following along and clicking that link took me to a dead end so I ended up searching. 

I see now later in the docs there's a section for this... might be better to link to that AND in there have a link to what Adds On are.

https://docs.frigate.video/frigate/installation#home-assistant-addon
