### ISSUE TITLE
frigate detector: worked fine when its cpu, but after install of coral, nothing changed

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1430]
thanks for the developers of frigate, my long time wish for an awesome program like this to host it locally in my home rather than in cloud.  I wish i had come across this while ago.

So i setup frigate and using it for last 3 days with 3 1080p cameras, all seem to functioning fine, only things was my cpu usage was 280% according to docker stats, and swap was 90%

So i ordered coral and got it in 2 days, today i was not sure should i just plug it in on my nuc/ubuntu and update the yaml or follow the coral.ai document to install for linux.

Anyway first i plugged it and changed the yaml to
detectors:
  coral:
    type: edgetpu
    device: usb

immediately cup % came down to 2% and i thought thats it, then on frigate log i notice edgeTPU not found error.
So i went ahead followed the coral.ai step 1 only to install the edgetpu runtime std, restarted the ubuntu, started frigate
checked the frigate log and it shows:
frigate.edgetpu                INFO    : TPU found

but my docker stats cpu usage for frigate still shows 189%

what am I doing wrong?

**Comment by balajeek** [comment]
This morning i tried to check the cpu% few times and it shows in the range of 65%, Is this normal ?
I was under impression it should be less than 5% !

Also since i have the HASS integration too, there is a sensor called Coral Inference Speed which is in the range of 10ms, that tells me coral is indeed processing, isn't !

In the docker and its in the docker-compose yaml like this, but still don't understand why cpu usage is that high.

devices:
  - /dev/bus/usb:/dev/bus/usb

**Comment by blakeblackshear** [comment]
The Coral only does one part of processing in Frigate. It only runs object detection. The video still has to be decoded by ffmpeg, motion detection must still be performed, and any locations where object detection will be run need to be resized and prepped for the Coral. Everything else runs on the CPU or GPU if you have hwaccel enabled for ffmpeg. Frigate doesn't run object detection all the time, but when it does, your CPU load should increase much less with a Coral. 

I think I saw you are using Wyzecams. You should have your fps set to 5 in your frigate config, and you should be using hwaccel args for ffmpeg if possible.

Also, be sure frigate is triggering on unwanted motion such as timestamps.

**Comment by balajeek** [comment]
I am still not convinced about the cpu usage as you can see below:
I have 3 1080p cameras, only 2 are set for detection and clips/snapshots.

![image](https://user-images.githubusercontent.com/19213088/127375859-c87b25b5-e00f-418e-85c0-fb14c58cbaed.png)

**Comment by balajeek** [comment]
Update on this:

I got a chance to add some mask on two cameras by masking all the trees and plants which constantly have motion.
To my surprise that bought the cpu to avg 40% below.  its been running like for 2+ hours. I hope this helps.

Thank you Blake.
