### ISSUE TITLE
Passwords are shown in frigate's logs

### ISSUE THREAD

**Issue by tyzbit** [blakeblackshear/frigate#1431]
**Describe the bug**
RTSP credentials are shown in Frigate logs.  This can be a security risk, depending on the user's setup.

**Version of frigate**
Output from `/api/version`
0.8.4-5043040

**Comment by highaltidude** [comment]
If someone is viewing your logs from Frigate I'd say security was breached a few steps ago.

**Comment by tyzbit** [comment]
- Users share logs from their instance all the time especially for troubleshooting and it's up to them to scrub credentials before sharing, which is not made obvious anywhere.
- I ship logs off to a 3rd party service, which is common especially in enterprise environments so anyone with access to those logs will see those credentials.
- If the logs are saved anywhere, a user would be unaware that they need to protect those logs with the same sensitivity as protecting their config (for example, if they had a web server hosting the logs).
- Someone shoulder surfing while someone is reading the logs could see the credentials.
- In case the argument is made that the cameras should be firewalled so "who cares about seeing credentials for a camera you can't access", it's probably more common than you think that people have internet-facing cameras that one could use the credentials against.
- People often reuse credentials, so if you can grab the credentials from the camera if the user has poor security practices an attacker could pivot to their email and further compromise them from there.
- Finally it's just plain poor security practice to output sensitive information in logs.

Hopefully this helps clarify why this is a bug.  Happy to discuss further.

**Comment by blakeblackshear** [comment]
Definitely a bad practice. When the opportunity arises for a simple solution, I will strip them out. If you are reusing sensitive passwords for your rtsp cameras on a private network, then you have much bigger problems. This won't be a high priority, but may be simple to do at some point. If others feel this is a major concern, they are welcome to submit a PR.

**Comment by PrplHaz4** [comment]
I agree this is a concern, and have seen other open source projects start to address it lately.

Some other mitigations/recommendations:
- use read(view)-only users on your cameras
- run an rtsp proxy in front of all cameras
