### ISSUE TITLE
Expose Edge TPU temperature

### ISSUE THREAD

**Issue by pdecat** [blakeblackshear/frigate#1433]
**Describe the request**

Would it be possible to expose the temperature of the Edge TPU devices in frigate API? And then expose at as an entity in the Home Assistant integration?

I did not find it in the libedgetpu API, but it is available from sysfs in [Millidegree Celsius](https://coral.ai/docs/pcie-parameters/#read-the-edge-tpu-temperature):
```
root@hassio:~# docker exec -ti addon_ccab4aaf_frigate sh -c "cat /sys/class/apex/apex_*/temp"
66050
72300
```

**Version of frigate**
N/A

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
detectors:
  coral0:
    type: edgetpu
    device: pci:0
  coral1:
    type: edgetpu
    device: pci:1
```

**Frigate container logs**
N/A

**Frigate stats**
N/A

**FFprobe from your camera**
N/A

**Screenshots**
N/A

**Computer Hardware**
 - OS: Debian 10 amd64
 - Install method: Home Assistant addon with supervisor
 - Virtualization: KVM/Qemu
 - Coral Version: Dual Edge TPU m.2 PCIe
 - Network Setup: Wired

**Camera Info:**
N/A

**Additional context**
N/A

**Comment by ardysusilo** [comment]
`# configuration.yaml
sensor:
  - platform: command_line
    name: Coral PCI Temperature
    command: "cat /sys/class/apex/apex_0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}" `

**Comment by pdecat** [comment]
@ardysusilo this works great, thanks!

**Comment by PrplHaz4** [comment]
I think the original request is still valid, as the sysfs node is not accessible to hass when it's running in a separate container/host from frigate (and does not seem very portable in general).

**Comment by NickM-27** [comment]
I believe this is done and closable? It’s exposed in the stats endpoint and I’ve added the sensor in https://github.com/blakeblackshear/frigate-hass-integration/pull/313

**Comment by pdecat** [comment]
Hi @NickM-27, I can report it is working fine, thanks!

Note: I had to manually enable the Apex temperature sensors as they were all unavailable by default:

![image](https://user-images.githubusercontent.com/318490/189475905-9b17dc26-b5da-48d7-8401-e4f7313bd977.png)

![image](https://user-images.githubusercontent.com/318490/189476004-f8a6e30e-f925-4136-b6c2-ab18c1610827.png)

![image](https://user-images.githubusercontent.com/318490/189476036-721b6854-3dbe-4619-a741-00b5cd6509c3.png)
