### ISSUE TITLE
Two lens camera sending data over one stream

### ISSUE THREAD

**Issue by lakime** [blakeblackshear/frigate#14427]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to split view from my camera into two cameras, as I got some Chinese cam, which is giving view from 2 lens in one rtsp stream

**Describe the solution you'd like**
I can try to crop it via ffmpeg, or try to play with some input ffmpeg parameters, but whenever I do that, frigate fails 

cameras:
  przod_prawo: # <------ Name the camera
    enabled: true
    ffmpeg:
      hwaccel_args:
        - -c:v:1
        - hevc_vaapi
      inputs:
        - path: rtsp://blabla:lb@192.168.0.xxx:554/rtsp 
 

whenever I do add some customer input_args - camera is failing to start

**Comment by NickM-27** [comment]
You will need to use ffmpeg to split the stream, you should create a support discussion
