### ISSUE TITLE
Enhancement: Move the checkmark "button" to the upper left hand corner

### ISSUE THREAD

**Issue by maglub** [blakeblackshear/frigate#14440]
I want to be able to not move the mouse when clicking the checkmark when reviewing the events in the "default view", where the events are smaller thumbnails above the tiles of video feeds.

In my setup, the small thumbnail videos are of different width due to different aspect ratios of my cameras. So I have to slightly move the mouse to click the checkmark between events.

If the checkmark would be on the top left corner, they would always align, and I could just click away without having to adjust the mouse pointer.

Another solution would be to add a keyboard shortcut to mark the leftmost thumbnail as reviewed. I would love that!

**Comment by hawkeye217** [comment]
As an alternative, you can use the select all keyboard shortcut (Ctrl/Cmd-A) from the Review screen and then click the "Mark as reviewed" button in the top bar.

**Comment by ItIsSeven** [comment]
This is a really annoying issue to me, can this be reopened?

**Comment by ItIsSeven** [comment]
@hawkeye217 @blakeblackshear

**Comment by NickM-27** [comment]
this was implemented recently

**Comment by ItIsSeven** [comment]
@NickM-27 I recently updated to 0.16.2-4d58206 (current latest) & I still have this issue

Is it intended to be pushed in a future update?

Thank you!

**Comment by NickM-27** [comment]
it will be part of 0.17

**Comment by ItIsSeven** [comment]
@NickM-27 Yep, I see it now, thanks!

https://github.com/blakeblackshear/frigate/pull/19787/commits/6e10fc21c377d75d37b928c37c575d53504ac625
