### ISSUE TITLE
Improve documentation for Frigate+ onyx models

### ISSUE THREAD

**Issue by baffles** [blakeblackshear/frigate#14453]
I just set up my first Frigate+ model, and it seemed more difficult than the docs made it out to be. I'm using openvino on an Intel iGPU. The docs made it look like you only needed to set the path to `plus://<id>` for the model. However, I received various errors along the way, such as `[GPU] The tensor size is not equal to model, can't set input tensor with index: 0, because model input (shape=[1,300,300,3]) and tensor (shape=[1,3,320,320]) are incompatible`.

Coming from using the stock SSDLite MobileNet model, the _full_ set of steps I ended up with was:

1. Comment out/remove the model in the `detectors`/`ov` section
2. Be sure to specify `width` and `height` of 320 in the model section (compared to 300 for MobileNet)
3. Specify an `input_tensor` of `nchw` (compared to `nhwc` for MobileNet)
4. Specify an `input_pixel_format` of bgr (same as MobileNet)
5. Also commented out the original `path` (duh) and `labelmap_path` (not mentioned, but I think necessary)

I'm not sure how much if this was necessary, but I needed to piece this together myself to get the model functioning. It would probably be good to formally document this to make it more clear, at least for openvino users.

**Comment by NickM-27** [comment]
None of this is needed. If the model is set as the plus model and the other model fields are not set then it is that easy. If you're not seeing that then you should create a support discussion

**Comment by baffles** [comment]
That is not true. I tried with only the path set to the plus model and received the error above. But whatever. If you want to just close the ticket without getting further information, then I won't contribute back to Frigate. Good luck!

**Comment by hawkeye217** [comment]
The issues queue on this repo is used for feature requests, which is why it was closed. If you open a support discussion, we would appreciate further information as to why you had to take these particular steps. Frigate should be taking care of it for you automatically.

**Comment by NickM-27** [comment]
The error above specifically indicates that the model width / height is set to 300 which is incorrect and not the default value or the plus model value so it is clear that the value is being set in the config like I suggested. 

We'd be happy to help by getting more info and seeing what can be made more clear if you create a support discussion as has been suggested.

**Comment by baffles** [comment]
I don't necessarily need support though since things are working now; perhaps I should have filed a bug report instead? I had received another error beforehand that was similar, I think related to the `input_tensor` value (default is `nhwc` but I needed to set it to `nchw` for the plus model). Presumably easy to repro, unless there's something strange about my setup.

**Comment by blakeblackshear** [comment]
If you are using a plus model, you shouldn't have any other values set under the `model`. Your model config should look like this with nothing other than the path specified:

```yaml
model:
  path: plus://<your_model_id>
```

**Comment by baffles** [comment]
I understand. That did not work for me though, `input_tensor` seems to default to the wrong value in that case.

**Comment by NickM-27** [comment]
when you use `plus://` the model is downloaded along with the proper config, so the correct values are used. We are aware of multiple users running openvino & onnx models this way (including myself) so we know it works correctly. The reason for the suggestion to create a support discussion is so we can get appropriate info like the config that reproduces the issue you are seeing, the specific full set of logs, etc.

**Comment by baffles** [comment]
Actually it seems to be working now; though what you said to do is what I did do initially. My initial logs have rotated away though, so I don't have them anymore, so I don't have any useful information or a repro to provide now unfortunately.

Anyhow, sorry for my abrasiveness the other day, and thanks for the work you've all done with this great project!
