### ISSUE TITLE
No / Broken Frame, Guessed Channel Layout for input stream - what does this error means?

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1445]
I have frigate latest up and running with 3 cameras (named: front, driveway, reef), with coral usb on intel i5 NUC, i do see this errors from the log and wondering what is this about, something to do with the camera itself or frigate !

watchdog.front                 INFO    : No frames received from front in 20 seconds. Exiting ffmpeg...
watchdog.front                 INFO    : Waiting for ffmpeg to exit gracefully...
frigate.video                  INFO    : front: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : front: ffmpeg sent a broken frame. read of closed file
frigate.video                  INFO    : front: ffmpeg process is not running. exiting capture thread...
ffmpeg.front.detect            ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.front.detect            ERROR   : [flv @ 0x55c6e9f67c00] Failed to update header with correct duration.
ffmpeg.front.detect            ERROR   : [flv @ 0x55c6e9f67c00] Failed to update header with correct filesize.

... and this keep repeating.

**Comment by jasonpstokes** [comment]
Can you can view the streams in VLC using your input stream path? And have you checked the video image size in VLC, to confirm you specified the correct dimensions for your detect stream in your Frigate config?

It would be helpful if you followed the instructions for posting an issue, and listed your config and how you are running it...

**Comment by blakeblackshear** [comment]
I think I remember from a separate issue that you are using Wyzecams. These are notoriously unstable, so you will see these errors when the camera sends corrupt data. Frigate should keep trying to recover.

**Comment by balajeek** [comment]
> Can you can view the streams in VLC using your input stream path? And have you checked the video image size in VLC, to confirm you specified the correct dimensions for your detect stream in your Frigate config?
> 
> It would be helpful if you followed the instructions for posting an issue, and listed your config and how you are running it...

Yes vlc stream showed fine.

**Comment by balajeek** [comment]
> I think I remember from a separate issue that you are using Wyzecams. These are notoriously unstable, so you will see these errors when the camera sends corrupt data. Frigate should keep trying to recover.

I was thinking the same, may be i should upgrade my cameras.

**Comment by unrly** [comment]
I'm running Wyze as well and see these a lot too.

While I don't have any experience yet with it (wasn't able to get it up and running successfully a few weeks back) https://github.com/mrlt8/docker-wyze-bridge gives an alternative method of creating an RTSP stream for Wyze. The developer is very active, and it seems to be working for some. There's also an excellent YouTube video on the setup: https://www.youtube.com/watch?v=NkhFgy0SYJ4

I'd be very curious to hear if this helps! I haven't had the change myself to get back to it, but I feel the RTSP would be much more stable than the crappy Wyze firmware.

**Comment by balajeek** [comment]
> I'm running Wyze as well and see these a lot too.
> 
> While I don't have any experience yet with it (wasn't able to get it up and running successfully a few weeks back) https://github.com/mrlt8/docker-wyze-bridge gives an alternative method of creating an RTSP stream for Wyze. The developer is very active, and it seems to be working for some. There's also an excellent YouTube video on the setup: https://www.youtube.com/watch?v=NkhFgy0SYJ4
> 
> I'd be very curious to hear if this helps! I haven't had the change myself to get back to it, but I feel the RTSP would be much more stable than the crappy Wyze firmware.

indeed i am using the wyzebridge on two camers, specially the v3 version where there is not official version of rtsp firmware from wyze, i searched and ended up wyze-bridge and set it up. Its a great program and as you mention the developer is very helpful.  My wyze pan camera already have rtsp firmware on it and accessing it directly with the wyze bridge, may be i should flash non-rtsp firmware and then use with with wyzebridge to see if it makes any help.
 thanks for the feedback anyway and I appreciate it.

**Comment by unrly** [comment]
Are you seeing those errors on your v3 camera?

I see a ton of them on the rtsp firmware v2s that I have (3 of them), was curious if the bridge would clean it up a bit or not. I figured I'd change the firmware to the non-rtsp as well if I got the bridge up and running properly, but if it doesn't solve too many of the issues I may forego it since a nightly automated reboot of the cameras seemed to help out quite a bit.

**Comment by balajeek** [comment]
V3 is fine and no errors , only the pan gives ‘type’ error.   If anything t does not work I may change the camera brand.

**Comment by blakeblackshear** [comment]
It does appear that the wyze bridge is using the video from wyze's cloud. The video goes from the camera, to the cloud, to that bridge, and then to frigate. If the internet goes out, so does the video feed. I'm sure it also adds some level of delay. I'm guessing this is the same method used by tiny cam pro.

**Comment by unrly** [comment]
Good point about the delay. I hadn't really considered that but I wonder if the LAN mode would help with that? I didn't ever test tinycam's delay, but he's supposedly adding an RTSP server this summer (which would be another great alternative for Wyze users if the delay isn't too significant).

**Comment by balajeek** [comment]
I turned off the modem and i still got the stream from wyze bridge, my iphone wyze app couldn't login though.
so that tells me the stream by wyzebridge is local.

I hunch is the wyze pan camera has something do with it, time to change that.

**Comment by balajeek** [comment]
I turned off the modem and i still got the stream from wyze bridge, my iphone wyze app couldn't login though.
so that tells me the stream by wyzebridge is local.

my hunch is the wyze pan camera has something do with it, time to change that.
