### ISSUE TITLE
mount custom labelmap.txt when using home assistant add-on

### ISSUE THREAD

**Issue by kcarriello** [blakeblackshear/frigate#1446]
**Describe the bug**
I can't bind the /labelmap.txt volume when using the Home Assistant add-on

**Version of frigate**
0.8.4-5043040

**Additional context**
I need to detect truck, so labelmap.txt needs to have "7  truck" and not "7  car", If I bind the volume using manual editing (using portainer, for example), every time I restart the add-on it gets replaced by the original labelmap.txt, there's no way to bind labelmap.txt, at least I couldn't figure out one way to customize the labelmap.txt.

**Comment by blakeblackshear** [comment]
Coming in the next version, but I think you will find that the models aren't reliable at distinguishing between car and truck.

**Comment by kcarriello** [comment]
Great, tks. In fact I have success when doing that, basically tuning detection size, it is quite accurate.
