### ISSUE TITLE
Improvement: use camera's motion detection to reduce CPU usage

### ISSUE THREAD

**Issue by amznestebanpapp** [blakeblackshear/frigate#1452]
Not a bug, just an improvement that can be made.

Please correct me if I am wrong. My understanding is that currently, motion is done purely on CPU. That has still to be done since the motion box is sent for detection. However, there is no need to do motion detection in the CPU if there is no motion in e.g. the whole frame. 

Most security cameras implement some motion detection algorithm. Downside is that a user would have to  configure motion detection in the camera to match the zones/regions of frigate or do motion detection in the whole frame (that would be my choice). In the future, frigate could configure the motion settings of the camera, however, I expect that to not be very standard across cameras (although ONVIF seems to allow it).

An initial implementation (and potentially the only needed one) is to do this through ONVIF. Despite some cameras implement their own API to query this information, most of them also implement ONVIF. My suggestion is to go that route.
Homeassistant has an ONVIF integration: https://www.home-assistant.io/integrations/onvif/ and it exposes `tns1:VideoSource/MotionAlarm` which is what we would be interested in. 
The integration uses https://github.com/hunterjm/python-onvif-zeep-async, so Frigate can use the latter and just care about `tns1:VideoSource/MotionAlarm` for the time being. 
I suggest to make this a configurable option to reduce the burden of what frigate has to detect and figure out.

So, frigate would receive the frames and do rtmp. It would (based on configuration) subscribe to the camera's motion event and only trigger CPU motion if the camera's motion event triggered. The algorithm of keeping doing detection while there is motion on CPU/AI detection can stay that way. This should reduce CPU motion detection on all cases where the cameras are not detecting any motion (which is a big portion of the time).
I dont expect this to delay anything, it may delay a frame or two the initial detection of the CPU motion, but since its already buffering for the clips, it could "rewind" them. Since not all cameras will be doing motion detection all the times, and this only affects to the beginning of the detection, I dont expect CPU usage to be unmanageable.  

BTW, thank you much for the project!!!, really helpful and has simplified my previous implementation enormously.

**Comment by blakeblackshear** [comment]
The events from the camera would probably be too slow and wouldn't tell frigate where the motion occurred. Also, not all cameras support this. You are almost certainly overestimating the CPU overhead of the motion detection. Most of the CPU overhead is in decoding the video feed. The motion detection is already very lightweight because it doesn't need to be that accurate.

**Comment by amznestebanpapp** [comment]
Bare with me since I am not an expert on this...
From what I can tell, most NVR systems use the events from the camera (e.g. qnap's qvrpro). Definitely something that should be measured/tried before fully implemented.

I estimated the CPU usage was coming from the beginning of the pipeline, not necessarily all due to motion detection. The thing is, you need to decode the frame to do motion detection. What my suggestion is aiming at, is that you don't even need to decode unless you get an event from the camera. When the event from the camera arrives, you kick the exact pipeline you currently have.

As an experiment, I turned off rtmp in all cameras which should leave just the process->detect part of the pipeline. For 7 cameras at 2688x1520 and 5fps, the addon CPU (on an Intel Core i7 8559U) usage is 43-45% with some peaks at 90%. I have 2 corals, so all inference should not be putting any burden in the CPU.
So, most of the CPU usage, should be coming from decoding+motion detection. Here is a graph of CPU usage, I disabled rtmp and restarted the frigate container, you can see the two drops there:
<img width="1590" alt="Screen Shot 2021-07-31 at 3 36 40 PM" src="https://user-images.githubusercontent.com/81431996/127753967-f4694f86-33a9-4589-9219-f2962a6252fb.png">

I also think that I am not bounded by inference, in all cameras, the detection fps is higher than the process fps, this is just for one of the cameras:
<img width="1666" alt="Screen Shot 2021-07-31 at 3 23 36 PM" src="https://user-images.githubusercontent.com/81431996/127753751-619d737c-0d62-4fb2-b2ed-282dbdee8fa6.png">

My suggestion was not to stop doing motion detection on the CPU. I understand that is still needed to feed inference. And to do motion detection, the frame has to be decoded.
My suggestion was to gate the whole pipeline with the event from the camera. If no motion events from the camera arrive, there is nothing to do. When a motion event arrives, the whole pipeline has to be kicked in: decoding kicks in, CPU motion detection kicks in and potentially inference.

I understand that there will be cameras that dont support this, thats why I was suggesting to do it with a setting (ideally the system could detect if the camera supports it, but I dont think is worthy to get into that). NVRs like QVRPro seem to have a database with specific APIs to get that data from. Totally not expecting that. 
Maybe that is something that can be scripted and let the user be in charge of that detection (would be just for advanced users). 

I will do some prototypes to try this concept out. I can add the ONVIF HA integration and only enable/disable detection in frigate based on the event.

**Comment by blakeblackshear** [comment]
There isn't a practical way to turn off decoding and turn on quickly. Also, motion detection requires a baseline, so you can't just start it on demand. It takes several frames to determine what is motion and what isn't.

There is also overhead for preparing parts of the frame for object detection. It has to be cropped and converted to a different pixel format.

**Comment by tve** [comment]
The nice thing here is that a path like you describe would also allow other external triggers, such as PIR or light barriers.

But I'm having a hard time seeing how to organize the video feed into frigate. It seems to take ffmpeg quite some time to start up a live feed, plus some cameras don't do well with more than one feed. If you don't start a feed from the camera you have to read a clip from disk cache, but I don't know whether you can consume a clip before it's finished (i.e. have frigate read a clip that is still being written by the permanent ffmpeg). It sounds quite messy and fragile to coordinate, at some point the current "cobbling together" of ffmpeg processes just doesn't work and you need to write a real app that connects to cameras, buffers frames in memory, and does the whole nine yards...

**Comment by tve** [comment]
BTW, are you using HW decoding with ffmpeg? And have you looked at which processes use the most CPU? That would already tell you how much you could possibly save...

**Comment by amznestebanpapp** [comment]
yeah, definitely needs experimentation, I am not claiming it will work... but if it does, even with some constraints (e.g. takes a second to start detecting) it will alleviate CPU usage significantly. 
To reduce the latency of the change was thinking to increase the framerate.

@tve Yes, I am using HW decoding. I also have a jetson nano around and that one has a more powerful H264 decoder, but it wont handle 7 cameras anyway... 

BTW, CPU usage is not a concern right now for my case, this whole thing is just something that occurred to me that I thought could benefit the project.. Is not blocking me and I am very happy with the functionality/performance of the project.

**Comment by jdesai61ilu** [comment]
This is not exactly what is being asked here, but it would be nice to be able record clips on a group of cameras when there is motion detected (with PIR, frigate, ONVIF, other).

**Comment by R5fan** [comment]
I want to second this suggestion. I understand it may not be viable in all situations, but very often it will be, and a few seconds delay do not matter when someone is entering my driveway. My camera's also have line crossing detection, which works reasonably well, is very fast, but its triggered by everything including birds and spiders and occasionally shadows. It would be nice to be able to use the camera's detection features to trigger frigate and identify the object.

**Comment by ozett** [comment]
i use hikvision-events with python on my own-code for motion from camera. afterward do the AI-detection.
but its only a hikvision feature... 

https://github.com/fbradyirl/hikvision
