### ISSUE TITLE
To jump straight to the event on Timeline

### ISSUE THREAD

**Issue by AriaGen** [blakeblackshear/frigate#14549]
**Describe what you are trying to accomplish and why in non technical terms**
I have 2 zones, Out of my driveway is set as a detection event, my driveway is an alert.
I had a persion out side my driveway, it triggered a detection and away it went.
Whilst that was happening, another person (the postie) entered my driveway. It triggered the alert event.
When I clicked on the snapshot of the postman, to see what he had got for me, it took me to the point in time of which the first person appeared. (She had been there for a while).
I understand that events now get merged into one continuous event, for the implementation of the timeliness, great.
It also doesn't show the snapshot of the first person in my detections anymore.

**Describe the solution you'd like**
I would like the alert to take precedence and the timeline jump straight to it.

**Describe alternatives you've considered**
Scrolling to find it, but if it's an actual you're being broken into event, I'd like to find it immediately.

**Additional context**
![Screenshot_20241023_115203_Chrome](https://github.com/user-attachments/assets/818b6b38-8560-4c9d-adc2-2551451e7892)

**Comment by NickM-27** [comment]
Only a single review item can exist for a period of time on a single camera. If there was activity the whole time then it is an alert, there is no way for these to be separated. The same could happen if there are multiple people walking through your driveway, either could be more important. This is working as intended.

**Comment by AriaGen** [comment]
Yes. And as I'm watching the footage of someone on my driveway, I'd see that there could be more than one person enter.. I do usually tend to watch the whole thing. The point is, surely something that is deemed as an alert, should be classed as a higher viewing priority, and people would want to watch that bit first. Would you not yourself?

How about addtional markers on the timeline, so show when a 2nd/3rd object was detected within that same detection? So we have a point of reference to snap to?

**Comment by NickM-27** [comment]
> The point is, surely something that is deemed as an alert, should be classed as a higher viewing priority, and people would want to watch that bit first. Would you not yourself?

The only way that would work is if after you watched the alert part it jumped back in time to watch it second which wouldn't make sense. 

You can already scrub to see what happened quickly and perhaps view the full recordings if something important happened.
