### ISSUE TITLE
New recommended cameras

### ISSUE THREAD

**Issue by cryd-s** [blakeblackshear/frigate#14555]
**Describe what you are trying to accomplish and why in non technical terms**
Please provide some more camera options, especially since there are no recommended cameras available in Germany.

**Describe the solution you'd like**
more recommended cameras in section

**Describe alternatives you've considered**
do not know which are good

**Additional context**
...

**Comment by NickM-27** [comment]
we can only fully recommend cameras that we have used personally, there are plenty of other places to find recommended cameras. If you have any questions about a specific camera then feel free to create a discussion on it
