### ISSUE TITLE
control retention cleanup process execution time

### ISSUE THREAD

**Issue by HelixX23** [blakeblackshear/frigate#14580]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to reduce the spin up amount on my archive drives so that I can increase the lifetime of these drives.
I have an UnRaid Server where i write all recordings to a SSD cache drive. Every night i move all the recordings to my archive HDD drives.
I found that frigate is deleting old recordings and clips as soon as the "retain flag" got hit (or at least every 5 minutes). 
As a result the HDD drive has an increased amount of spin up events for only deleting old files... 

**Describe the solution you'd like**
It would be nice to have a setting, that the retention cleanup process is only running once, twice or several times a day

**Describe alternatives you've considered**
As an alternative i was thinking to buy a new SSD cache drive to keep the frigate data away from the archive HDD drives.

**Additional context**
Here is a log from my recent archive HDD activity...

** Disk 3 **
Oct 25 12:26:14 DELETE => /mnt/disk3/Media/frigate/clips/previews/Tuerklingel/1728982800.yyyy-yyyy.xxxx.mp4
Oct 25 12:26:14 DELETE => /mnt/disk3/Media/frigate/clips/review/thumb-Tuerklingel-1728984472.yyyy-xxxx.webp
Oct 25 12:26:14 DELETE => /mnt/disk3/Media/frigate/clips/review/thumb-Tuerklingel-1728985187.yyyy-xxxx.webp
Oct 25 12:26:14 DELETE => /mnt/disk3/Media/frigate/clips/review/thumb-Tuerklingel-1728985296.yyyy-xxxx.webp
Oct 25 12:26:14 DELETE => /mnt/disk3/Media/frigate/clips/review/thumb-Tuerklingel-1728985413.yyyy-xxxx.webp
Oct 25 12:40:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728556724.yyyy-xxxx.jpg
Oct 25 12:40:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728556724.yyyy-xxxx-clean.png
Oct 25 12:40:10 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728556731.yyyy-xxxx.jpg
Oct 25 12:40:10 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728556731.yyyy-xxxx-clean.png
Oct 25 12:50:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728557133.yyyy-xxxx.jpg
Oct 25 12:50:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728557133.yyyy-xxxx-clean.png
Oct 25 12:50:10 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728557140.yyyy-xxxx.jpg
Oct 25 12:50:10 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728557140.yyyy-xxxx-clean.png
Oct 25 12:55:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728557528.yyyy-xxxx.jpg
Oct 25 12:55:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728557528.yyyy-xxxx-clean.png
Oct 25 13:00:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728557891.yyyy-xxxx.jpg
Oct 25 13:00:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728557891.yyyy-xxxx-clean.png
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558286.yyyy-xxxx.jpg
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558286.yyyy-xxxx-clean.png
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558294.yyyy-xxxx.jpg
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558294.yyyy-xxxx-clean.png
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558296.yyyy-xxxx.jpg
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558296.yyyy-xxxx-clean.png
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558298.yyyy-xxxx.jpg
Oct 25 13:05:10 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728558298.yyyy-xxxx-clean.png

**Comment by NickM-27** [comment]
This already exists as the expire_interval config

**Comment by HelixX23** [comment]
Thank youuu very much :+1: 

I tried to set the setting expire_interval from default 60 minutes to 600 minutes and restarted frigate.
Now the deletion of the .mp4 and .webp files disappeared from the HDD activities list, but the .png and .jpg files are still present.

Did i miss something?


```
record:
  expire_interval: 600
```

Disk Activity:

```
** Disk 3 **
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728569980.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728569980.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728569988.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728569988.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728569993.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728569993.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569885.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569885.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569910.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569910.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569982.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569982.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569982.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728569982.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728570013.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728570013.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728570013.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728570013.yyyy-xxxx-clean.png
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728570020.yyyy-xxxx.jpg
Oct 25 16:20:26 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728570020.yyyy-xxxx-clean.png
Oct 25 17:15:27 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728573041.yyyy-xxxx.jpg
Oct 25 17:15:27 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728573041.yyyy-xxxx-clean.png
Oct 25 17:15:27 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728573072.yyyy-xxxx.jpg
Oct 25 17:15:27 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728573072.yyyy-xxxx-clean.png
Oct 25 17:15:27 DELETE => /mnt/disk3/Media/frigate/clips/Hausflur_DG-1728573116.yyyy-xxxx.jpg
Oct 25 17:15:27 DELETE => /mnt/disk3/Media/frigate/clips/Hausflur_DG-1728573116.yyyy-xxxx-clean.png
Oct 25 17:20:27 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728573487.yyyy-xxxx.jpg
Oct 25 17:20:27 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728573487.yyyy-xxxx-clean.png
Oct 25 17:30:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728574013.yyyy-xxxx.jpg
Oct 25 17:30:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728574013.yyyy-xxxx-clean.png
Oct 25 17:30:28 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728574021.yyyy-xxxx.jpg
Oct 25 17:30:28 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728574021.yyyy-xxxx-clean.png
Oct 25 18:00:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728575921.yyyy-xxxx.jpg
Oct 25 18:00:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728575921.yyyy-xxxx-clean.png
Oct 25 18:20:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577047.yyyy-xxxx.jpg
Oct 25 18:20:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577047.yyyy-xxxx-clean.png
Oct 25 18:20:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577129.yyyy-xxxx.jpg
Oct 25 18:20:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577129.yyyy-xxxx-clean.png
Oct 25 18:20:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577215.yyyy-xxxx.jpg
Oct 25 18:20:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577215.yyyy-xxxx-clean.png
Oct 25 18:25:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577483.yyyy-xxxx.jpg
Oct 25 18:25:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728577483.yyyy-xxxx-clean.png
Oct 25 18:25:28 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728577496.yyyy-xxxx.jpg
Oct 25 18:25:28 DELETE => /mnt/disk3/Media/frigate/clips/Tuerklingel-1728577496.yyyy-xxxx-clean.png
Oct 25 18:35:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728578118.yyyy-xxxx.jpg
Oct 25 18:35:28 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728578118.yyyy-xxxx-clean.png
Oct 25 18:40:29 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728578420.yyyy-xxxx.jpg
Oct 25 18:40:29 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728578420.yyyy-xxxx-clean.png
Oct 25 18:40:29 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728578420.yyyy-xxxx.jpg
Oct 25 18:40:29 DELETE => /mnt/disk3/Media/frigate/clips/eingangstuer-1728578420.yyyy-xxxx-clean.png
```


Here is my config:

```
logger:
  logs:
    frigate.record: debug

mqtt:
  host: .............

birdseye:
  enabled: true
  mode: objects
  quality: 1

record:
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 600

detectors:
  coral:
    type: edgetpu
    device: usb

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: true
  # Optional: save a clean PNG copy of the snapshot image (default: shown below)
  clean_copy: true
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: false
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: true
  # Optional: crop the snapshot (default: shown below)
  crop: true
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 15

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
................
go2rtc:
................


version: 0.14
camera_groups:
  Birdseye:
    order: 1
    icon: LuBird
    cameras: birdseye
```

**Comment by NickM-27** [comment]
the config only applies to recordings, there is no config for images yet but there is a feature request for that already. 

However, it would be better to store the images on a cache pool in unraid (this is what I do) since otherwise any time you open the UI the disks will just spin up which defeats the purpose

**Comment by HelixX23** [comment]
> This already exists as the expire_interval config



> the config only applies to recordings, there is no config for images yet but there is a feature request for that already.
> 
> However, it would be better to store the images on a cache pool in unraid (this is what I do) since otherwise any time you open the UI the disks will just spin up which defeats the purpose

good idea,
thank you for the fast reply,
could you give me a hint how you separate these file locations in unraid?

**Comment by NickM-27** [comment]
![Screen Shot 2024-10-25 at 11 14 54 AM](https://github.com/user-attachments/assets/17294162-83a6-4f73-b984-8cdca63615fc)

**Comment by HelixX23** [comment]
thank youuuuu :1st_place_medal:
