### ISSUE TITLE
Import Users from Home Assistant

### ISSUE THREAD

**Issue by potelux** [blakeblackshear/frigate#14592]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to import the users already built in Home Assistant so that I can minimize duplicate efforts.

**Describe the solution you'd like**
I want to be able to install the Frigate NVR addon and go to the settings panel to see a list of the users I have already created in Home Assistant.  Perhaps they would be disabled by default, but the users would already be in the system and would remain synchronized to the list of users made in Home Assistant.

**Describe alternatives you've considered**
I have considered duplicating the effort by creating users twice, but this requires remembering to create/delete users in both places every time.

**Additional context**
I am not certain this is even possible.  Perhaps it first requires Home Assistant to support RBAC.

**Comment by NickM-27** [comment]
I don't think this is possible, frigate has no way of knowing what users are in HA or their passwords. Even if frigate could get the users, not having passwords would make that rather pointless. You can already use a proxy to create users for frigate and in a future version these will automatically be added to the DB.

**Comment by potelux** [comment]
> I don't think this is possible, frigate has no way of knowing what users are in HA or their passwords. Even if frigate could get the users, not having passwords would make that rather pointless. You can already use a proxy to create users for frigate and in a future version these will automatically be added to the DB.

Thank you for the quick reply.  It seems my hunch was right.  This is dependent on Home Assistant adding a more robust user system.  I currently use an authentication proxy with URL path restrictions to simulate RBAC on Home Assistant.  I will instead integrate Frigate into that system.
