### ISSUE TITLE
x265 Support?

### ISSUE THREAD

**Issue by ne0ark** [blakeblackshear/frigate#146]
Anyone tried with x265 camera? All you need to do is add libx265 to ffmpeg?

**Comment by tubalainen** [comment]
Got the 4K Annke C800 inbound - will report next week. :)

**Comment by ne0ark** [comment]
@tubalainen How did you enable the support?

**Comment by tubalainen** [comment]
> @tubalainen How did you enable the support?

I do not know, the camera is in the mail. I can report back as soon as I have it in my hand.

**Comment by tubalainen** [comment]
> @tubalainen How did you enable the support?

Yes. It works out of the box. Just tested my cam with frigate.

(PS, it is not recommended to run a stream 4K in 12,5 FPS ;) )

**Comment by ne0ark** [comment]
My 4k stream is running at 14 FPS 4k.

**Comment by ne0ark** [comment]
@tubalainen Did you optimize https://github.com/blakeblackshear/frigate/blob/master/docs/DEVICES.md ffmpeg params for x265?
