### ISSUE TITLE
Feature request: Add "buymeacoffee" link.

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#147]
Please @blakeblackshear I´d like to show my appreciation to your hard work.
Please add a link so that I can buy you some cups of coffee´s

https://www.buymeacoffee.com/

**Comment by scstraus** [comment]
He used to have one, but now you can do it directly through github. Just go to his github page and sponsorship options are there.

**Comment by tubalainen** [comment]
Missed that one - thanks.
