### ISSUE TITLE
Clarification of AVX requirements for CPU in the docs

### ISSUE THREAD

**Issue by spotlesscoder** [blakeblackshear/frigate#14712]
I guess for acceptable streaming performance (even without object / motion detection), AVX capable CPU is required.
I would expect this fact to be written down explicitly here: 
https://docs.frigate.video/frigate/hardware

**Comment by NickM-27** [comment]
The AVX requirement is for running tflite, only very old CPUs that wouldn't be good candidates for running frigate don't support this.

**Comment by halacs** [comment]
Is it possible to use frigate on old hardware with no AVX instruction set? Currently I get segmentation fault.

**Comment by NickM-27** [comment]
Not officially but there are community supported builds with the requirement removed

**Comment by halacs** [comment]
Can you please mention one worth to try?

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate-hass-addons/tree/main/frigate_oldcpu

**Comment by sanimalp** [comment]
just to address this further, I have been trying to run frigate on fairly old hardware I use for such things as home automation, and cannot get the basic docker compose suggested by the docs to even start on a machine without AVX. put up a PR to address this in the docs: https://github.com/blakeblackshear/frigate/pull/17575
