### ISSUE TITLE
0.15.0-beta1 - Filters in Explore page for Frigate+

### ISSUE THREAD

**Issue by calederer** [blakeblackshear/frigate#14769]
I believe in 0.15-beta1 the frigate+ page was eliminated and incorporated into the new explore page.
Would it be possible to add a filters on the explore page for:
1. Snapshots that have not been submitted to frigate+
2. Score range

This would bring back some of the functions the friage+ page had that i utilized for submitting to frigate+

**Comment by NickM-27** [comment]
Score range is already implemented

**Comment by tubalainen** [comment]
Cannot find the "bird" icon below "Exported" in 0.15.0 beta 1. I have checked by API key and env. variable.
Should I post a separate issue on this or would this issue (point 1) be sufficient? 
![image](https://github.com/user-attachments/assets/4e15a045-dc4a-43d3-8f77-66841672da31)

**Comment by NickM-27** [comment]
The explore page has buttons to submit to frigate+ on the cards as well as in the detail dialog

**Comment by tubalainen** [comment]
> The explore page has buttons to submit to frigate+ on the cards as well as in the detail dialog

Cannot find any buttons on the explore page....
![image](https://github.com/user-attachments/assets/44f0b0f7-c022-4d3f-baf5-d32f8b6c8939)

Cannot find any in the details either...
![image](https://github.com/user-attachments/assets/702be049-11d3-403c-9dec-8bdaa35579d2)

EDIT: OH! Found it after I enabled "Description" under settings.
![image](https://github.com/user-attachments/assets/e63e3cd3-2bb9-4f93-91c2-55a751931218)

**Comment by NickM-27** [comment]
You just push the arrow on the right of the items to view the expanded list. 

Or you can change the default grid type to unfiltered grid

**Comment by tubalainen** [comment]
> You just push the arrow on the right of the items to view the expanded list.
> 
> Or you can change the default grid type to unfiltered grid

Ahh! Okok. Now I found it. Thanks. A bit hidden :)

**Comment by hawkeye217** [comment]
Added in https://github.com/blakeblackshear/frigate/pull/14909 and https://github.com/blakeblackshear/frigate/pull/14397
