### ISSUE TITLE
Support for TLS/SSL for MQTT server.

### ISSUE THREAD

**Issue by rwifall** [blakeblackshear/frigate#1477]
**Describe the bug**
I have my MQTT server configured for connections via TLS/SSL

Frigate does not connect to my server and on my server I get the following errors in the mosquitto log when frigate tries to connect:
```
1628350648: New connection from REDACTED_IP_ADDRESS on port 8883.
1628350648: OpenSSL Error[0]: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
1628350648: Socket error on client <unknown>, disconnecting.
```

I'm running mosquito and other clients can connect to it fine, such as home assistant, MQTT.fx, etc.

I suspect this could be replicated using the mosquitto test server host: test.mosquitto.org port:8883, but I haven't yet setup a test instance of frigate to try.
For more details: [https://test.mosquitto.org](https://test.mosquitto.org)

*Desired result:*
Frigate connects to the MQTT server via TLS/SSL

**Version of frigate**
0.8.4

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: REDACTED.HOST.COM
  port: 8883
  topic_prefix: frigate
  client_id: frigate
  user: REDACTED_USER
  password: REDACTED_PASSWORD
```

**Frigate container logs**
logging is set to 'debug'
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    WARNING : Camera montana_driveway has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
detector.coral                 INFO    : Starting detection process: 38
frigate.app                    INFO    : Camera processor started for montana_driveway: 41
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Capture process started for montana_driveway: 43
frigate.edgetpu                INFO    : TPU found
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
[N/A]
```

**Screenshots**

**Computer Hardware**
 - OS: HassOS
 - Install method: Add-on
 - Virtualization: N/A
 - Coral Version: USB
 - Network Setup: WiFi

**Camera Info:**
 [N/A]

**Additional context**

**Comment by blakeblackshear** [comment]
The [next version](https://github.com/blakeblackshear/frigate/pull/825) should address this.

**Comment by rwifall** [comment]
That's great!  Thanks!  And thank you for all the work on Frigate.  It's very impressive.
