### ISSUE TITLE
Motion Review playback speed

### ISSUE THREAD

**Issue by djtremolo** [blakeblackshear/frigate#14774]
**Describe what you are trying to accomplish and why in non technical terms**
When viewing the recorded motion in Review -> Motion tab, the allowed playback speeds are 4x, 8x, 12x and 16x. Are the slower speeds missing because of some technical reason or could they be added?

**Describe the solution you'd like**
There are use cases where something interesting happens and I would like to be able to lower down the speed. At least to 1x, but if possible, also half/quarter speed would be preferred to figure out "what happened first".

**Describe alternatives you've considered**
Not sure if this is a good idea, but perhaps a zipped multicamera export at chosen speed could be triggered from the motion review window?

**Additional context**
![image](https://github.com/user-attachments/assets/9d5a19c1-8de1-4a0f-8a68-ce58612d4a05)

**Comment by hawkeye217** [comment]
Motion review is designed with a different use case in mind and uses low-resolution, low-frame rate previews. So viewing it at anything less than 4x will not display fluent and clear video. 

You should use History view where slower speeds are available and your full resolution, full frame rate footage is displayed and you can easily click between all your cameras.

**Comment by djtremolo** [comment]
Oh, okay. That's fair, I was not aware of the technology behind it. Thanks for clarification!
