### ISSUE TITLE
Unverified filter in Frigate+

### ISSUE THREAD

**Issue by tbclark3** [blakeblackshear/frigate#14787]
**Describe what you are trying to accomplish and why in non technical terms**
I have more than 2000 images in Frigate+ from 11 cameras.  With the recent addition of new objects, all of my images reverted to "unverified."  Although the instructions say that the verification process will follow a single camera to the end of unverified images, it doesn't work.  The verification process *always* stops before the end of the unverified images for any given camera.  The only way to find remaining unverified images is to scroll through hundreds of images looking for the first unverified one.  That sometimes results in a new chain of unverified images, and sometimes just a single image.  In either case, I have to start over from the beginning to look for new unverified images.  

**Describe the solution you'd like**
A filter for unverified images.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
It is virtually impossible to find unverified images in the present system.  It is all but useless.

**Comment by NickM-27** [comment]
this is not the place to request features for Frigate+, the Frigate+ discussions should be used

for this particular request, I believe it is already being worked on

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate/discussions/14762#discussioncomment-11142893
