### ISSUE TITLE
[Feature Request] Ability to turn on/off 24/7 recording

### ISSUE THREAD

**Issue by joeShuff** [blakeblackshear/frigate#1478]
I would like to see the addition of a toggle to enable/disable 24/7 recording for individual cameras, functioning the same as the detect/clips/snapshots toggles do right now.

The reason for this is I recently switched from a Eufy camera (which has a software on/off to stop the rtsp stream) to a reolink camera for local control, however the reolink doesn't have a software option to stop the rtsp stream. The issue is these are indoor cameras that I only want to turn on when we are out of the house. I have a PTZ model so I solved pointing the lens toward the wall and stopping audio stream but frigate still records the wall at the moment. Also my CPU usage is higher in frigate when recording vs when not (obviously) so it would also stop wasting resources.

I saw you mention the possibility of this on #1331 and that put the idea into my head as a possibility and now I have found a use case! 

Thanks for everything you do!

**Comment by webbson** [comment]
This is something I've been looking for as well. The use case I want it for is to trigger full recording when my alarm system is triggered.

**Comment by joeShuff** [comment]
If you take a look at the #1063 it looks like some backend work is being done to support manually triggered events, so that might be better suited for your use case!

**Comment by joeShuff** [comment]
I've just read through the most recent 0.9.0 commits and found [this](https://github.com/blakeblackshear/frigate/pull/825/commits/c527b1ca5d7bed9759588f51f8b61cad5a0235cd) beauty. I recall reading something about clips using recordings so looks like recordings are the togglable thing instead of clips. Interesting

**Comment by joeShuff** [comment]
This has been added in 0.9.0 and is exactly what I was looking for. I'll close this now.
