### ISSUE TITLE
Continuous recordings not getting deleted for clips

### ISSUE THREAD

**Issue by kanemari** [blakeblackshear/frigate#1479]
Hi there,

I have enabled recording of clips, which it appears is deprecated and now uses a subset of recordings / events to accomplish the same task (its not documented which is why I am using 'clips' in the config).

It appears from reading some of the later commentary that recordings are turned on by default, clips get extracted from those recordings, and the original recording file is supposed to be deleted if 'recording' is not turned on separately. It doesnt look like the recording files are getting deleted. My hard disk is filling up with 1 minute recordings that dont have any movement / event associated to them.

Firstly I would like to fix this issue so my disk doesnt fill up with unneeded static recordings. Secondly I would rather remove the deprecated 'clips' section from the config and use 'recordings / event', as that might help setting some of the values that could potentially fix this - so any documentation on that config would be appreciated.

This is really cool btw - especially the debugging screens that allow setting of masks and showing movement detection - makes everything so much easier! Dont want to sound unappreciative, just trying to help

**Comment by blakeblackshear** [comment]
Are you using the unreleased 0.9.0 version? If so, don't expect all the documentation to be up to date or for it to be bug free. There isn't even a beta version released yet. You are running largely untested development changes.

**Comment by kanemari** [comment]
hmm, maybe but not intentionally?

I am using the one that defaults to install in HA as an add-on. 1.14-beta2. if thats using 0.9.0 which is unreleased - then Ill try to downgrade the HA add-on version back to 1.13 (0.8.4)

**Comment by blakeblackshear** [comment]
The beta addon is a very old version. Just run stable. Everything you have mentioned is related to new features, not the stable version. Just use stable and read the docs.

**Comment by kanemari** [comment]
ok cool - will do that

just for reference, this is where I got that beta. didnt realise it was out of date.

Hass.io Add-ons - Jason Hunter
Jason Hunter <hunterjm@gmail.com>
https://github.com/hunterjm/hassio-addons

**Comment by blakeblackshear** [comment]
Then that is a different beta that is the new version.
