### ISSUE TITLE
Manifest not found error

### ISSUE THREAD

**Issue by Travisco29** [blakeblackshear/frigate#1480]
![image](https://user-images.githubusercontent.com/42927137/128622640-eabd12e2-73c3-4bf7-b424-a0a9f17783c6.png)
I Am getting this error whenever i try to install on docker. Happened on an intel mac and a ryzen pc.

**Comment by blakeblackshear** [comment]
That tag doesn't exist

**Comment by Travisco29** [comment]
oh yeah, looked at guide and realized i omitted the tag so it defaulted to the latest.
