### ISSUE TITLE
Minimum motion time for motion detection

### ISSUE THREAD

**Issue by Kedryn** [blakeblackshear/frigate#14818]
Coming from Blue Iris, i'm missing a way to set a minimum movement time lenght for the motion detection.
I'll try to explain with an example.
I live in the countryside, and we have a lot of flying insects, even in winter.
When it's night, and my cameras switch to IR mode, it happens often that some fast flying insect pass in the camera FoV, but near the lens, for like 0,5 seconds.

In BI i had a settings were i used to set 0,5s "at least" of movement before the "motion" flag turning on
that eliminates a lot of unwanted detections.

With Frigate, i didn't find a way to not detect movements of fliying insects :(

**Comment by hawkeye217** [comment]
Frigate motion detection works differently than other NVRs like Blue Iris. Motion detection is only used to determine if an area in the frame should be examined for objects. If you are detecting objects that you don't want to be detected, you should use required zones and filters.

**Comment by Kedryn** [comment]
it's not a matter of sensitivity, because insects gets full ir on them
It's not a matter of areas, because they fly at few centimeters from the lens, so they can be detected oeverywhere on the camera view.
it's not a matter of examining object, because insects can't be recognized by the detectors
I use "motion" because it happens that people are not always detected either, maybe for the angle of cameras not always optimal for detectors. I'm fine with motion, but i think that a setting like that would benefit many users.

**Comment by hawkeye217** [comment]
Again, because of how Frigate uses motion detection to trigger object detection, an "at least" setting would change the way that objects are detected. You could potentially miss true positives, which would then actively work against the rest of the detection pipeline.

The Motion Review screen in Frigate 0.14 and later makes reviewing areas of motion for potential missed objects very easy. Just click the "Motion only" toggle and scrub the timeline over your areas of interest. Smaller areas of motion in the frame are represented as shorter yellow bars, larger areas as longer yellow bars.

**Comment by Kedryn** [comment]
understood

but then, if i switch to detection and not motion, and i turn lights on when there is motion AND a car or a preson, what prevent me to have insects turn on motion where i have the car parked?

is there a way to prevent this?

**Comment by NickM-27** [comment]
I think it would be better to understand what the exact concern is? An insect on a camera will show up as a small yellow blip on the timeline. This takes a fraction of a second to scrub through and understand what happened, so I am not sure what the issue is with this happening when the flip side being missing quick important motion seems like a much larger issue.

**Comment by Kedryn** [comment]
i have an automation in Home assistant that, in night hours, turns on garage/porch lights when motion is detected.
i want to limit the time the lights are on, but insects keep triggering it.
if i switch to object detection triggers, often lights will not turn on
and i'm pretty sure that if i use both motion + objects, it will not change much, because of parked cars.

the easiest way is to skip small <1s motion detection.

i've uderstood @hawkeye217 explanation, but i fail at understanding  why an optional parameter can't be implemented as a per camera motion setting.

**Comment by hawkeye217** [comment]
I do a similar thing, except I trigger the automation both on objects and on motion, but at night time I have another automation that increases my `contour_area` to be slightly higher than the day time. That avoids smaller changes in motion. And with `required_zones`, I can still get a notification for a person that has come too close to the house, for example.

**Comment by NickM-27** [comment]
To be clear I'd you have an automation just set that you need motion to be on for a certain amount of time, no need for frigate to require this itself. You can customize the delay in the motion settings

**Comment by Kedryn** [comment]
> To be clear I'd you have an automation just set that you need motion to be on for a certain amount of time, no need for frigate to require this itself. You can customize the delay in the motion settings

that won't work. in HA i can specify timing in seconds, not fractions, and there is the pipeline lag between frigate-MQTT/integration-HA that makes every motion detection, HA sensor side, way longer than 1 sec.

**Comment by Kedryn** [comment]
> I do a similar thing, except I trigger the automation both on objects and on motion, but at night time I have another automation that increases my `contour_area` to be slightly higher than the day time. That avoids smaller changes in motion. And with `required_zones`, I can still get a notification for a person that has come too close to the house, for example.

I think i'll try that way, but without touching the contour_area, because my problem is not a small change. In facts, it tends to be a big change (the flying insect an inch of the camera is pretty big). Same for required_zones, because if the insect flies horizontally, it will be caught in every zone i define.

**Comment by rmawatson** [comment]
Came looking for the same thing. I don't use any of the upstream detections. I only want motion to trigger recordings and send out an mqtt message and would like some basic filtering for this. @Kedryn is absolutely spot on with this request. Insects cause tons of unnecessary recordings, and this would be easily fixed. by requiring the motion to last a minimum amount of time.

> I am not sure what the issue is with this happening when the flip side being missing quick important motion seems like a much larger issue.

The same could be said for the threshold and contour parameters. Having a minimum motion time that is settable from 1 frame upwards would continue to allow everything to work as it currently does, with the addition of allowing users to decide where they see the need for filtering.

<img width="574" height="531" alt="Image" src="https://github.com/user-attachments/assets/c91f91b3-7902-4eb4-b1bd-4ed07d24fe8a" />
