### ISSUE TITLE
ffmpeg No such filter Volume

### ISSUE THREAD

**Issue by K-4U** [blakeblackshear/frigate#1481]
So i noticed the audio was a little low when reviewing my clips. I wanted to up the volume, but i just get a "No such filter volume" whenever a clip gets made
My config for output_args is:
`clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac -filter:a "volume=1.5"`

Log:
```
ffmpeg.front_door.clips_record ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.front_door.clips_record ERROR   : Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 1, only the last option '-c:a aac' will be used.
ffmpeg.front_door.clips_record ERROR   : [AVFilterGraph @ 0x55b52e37c1c0] No such filter: '"volume'
ffmpeg.front_door.clips_record ERROR   : Error reinitializing filters!
ffmpeg.front_door.clips_record ERROR   : Failed to inject frame into filter network: Invalid argument
ffmpeg.front_door.clips_record ERROR   : Error while processing the decoded data for stream #0:1
watchdog.front_door            INFO    : Terminating the existing ffmpeg process.
```

Is there something wrong with my config or is the build of ffmpeg wrong?

**Comment by blakeblackshear** [comment]
Remove the double quotes around the filter

**Comment by K-4U** [comment]
Oh.. Oh god that is so stupid. Serves me right for doing home automation late in the evening without coffee.
Thank you for your reply. I'm just gonna pretend this never happened.

**Comment by Edesem** [comment]
I had this very same issue and finally removing quotes worked. Why though? @blakeblackshear, in the terminal it works but now in my script it only works without the quotes? Is it because its putting the single quotes ('filter') automatically or what?

**Comment by NickM-27** [comment]
> I had this very same issue and finally removing quotes worked. Why though? @blakeblackshear, in the terminal it works but now in my script it only works without the quotes? Is it because its putting the single quotes ('filter') automatically or what?

Passing via command line which handles the "" is different to the way python handles this internally where it passes what is put in the config to ffmpeg directly

**Comment by blakeblackshear** [comment]
It's based on the way python spawns the subprocess.

**Comment by Edesem** [comment]
The interesting thing is I'm not actually using this repo. I had the same issue relating to quotes and the same solution fixed my issue, however I'm using ffmpeg in a bash script. I'm therefore assuming the bash script does the same thing python does handling quotation marks
