### ISSUE TITLE
Copy Mask Coordinates in UI

### ISSUE THREAD

**Issue by myst3k** [blakeblackshear/frigate#14837]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to copy mask coordinates from the UI like in previous versions.

**Describe the solution you'd like**
A copy coordinates button next to the mask I created in the UI.

**Describe alternatives you've considered**
Open Chrome DevTools and copy and paste from there.

**Additional context**
I am running in K8S using the Frigate Helm chart. I recently upgraded from v12 to v14. Since my config.yaml file is a ConfigMap, it is immutable from the Frigate NVR UI. I would make the masks in the UI, copy them into my helm chart config file, and have it re-deploy with FluxCD. I am no longer able to easily grab the coordinates for the masks from the UI like I was in previous versions.

**Comment by NickM-27** [comment]
This already exists

![Screenshot 2024-11-06 at 9 50 33 AM](https://github.com/user-attachments/assets/59f69943-55c7-48f2-a16e-1671e0493a42)

**Comment by myst3k** [comment]
Ughhhh thank you! Dont know how I missed that.
