### ISSUE TITLE
Shoplifting identification - generally action detection 

### ISSUE THREAD

**Issue by ArtaFakhari** [blakeblackshear/frigate#14831]
Is there any expectations for using Frigate to identify shoplifting or any other action identification? 
Or any workaround suggestions to achieve this goal?

**Comment by NickM-27** [comment]
In 0.15 genai can be prompted to describe a persons actions / behavior

**Comment by NickM-27** [comment]
what do you mean by workaround? You can check out the beta release notes, and the associated beta documentation

**Comment by saket424** [comment]
@NickM-27 
It would be sweet if we can use multiple still images from a video clip (with ffmpeg) instead of a single best scoring thumbnail/snapshot to generate the description using genai so it is more "actionable" and "alertable"

**Comment by NickM-27** [comment]
@saket424 that's already how the feature works
