### ISSUE TITLE
Enable running script with the homeassistant automatisation blueprint (not only notifications)

### ISSUE THREAD

**Issue by StenLeijskens** [blakeblackshear/frigate#14844]
**Describe what you are trying to accomplish and why in non technical terms**
Enable running script with the homeassistant automatisation blueprint (not only notifications)

**Describe the solution you'd like**
Enable running script with the homeassistant automatisation blueprint (not only notifications)

**Describe alternatives you've considered**
Checking the events / reviews.
But that does not always trigger the way I want:
- Only looking at new events, a zone is often not filled in / not yet filled in 
- The next update events do have the zone, but then you get multiple triggers for the same eventid

**Comment by StenLeijskens** [comment]
In the automation using the blueprint you can only select sending a notification to a cell phone.
I would like to trigger a HA script too. (As an action....)


actions:
  - action: script.frigatetriggeredaneventwhereiwanttorunmyscriptfor
    data: {}

**Comment by NickM-27** [comment]
This is the repo for Frigate itself not the blueprint, this is the wrong place to make this request
