### ISSUE TITLE
Event Download Button/Option

### ISSUE THREAD

**Issue by tokenwizard** [blakeblackshear/frigate#14846]
**Describe what you are trying to accomplish and why in non technical terms**
Simple download button on Event Review screen

**Describe the solution you'd like**
Prior to the rewrite, when reviewing events it was easy to download an event by clicking the download button. Since the rewrite when you are viewing an event or reviewing events on the review page, there does not seem to be a simple way to download the event currently being reviewed. When viewing an event, there is an Export button at the top, but it does not just export the clip; you have to specify a time range to export. There should be a simple way to just download the event you are watching, the way it worked before the rewrite. 

**Describe alternatives you've considered**
The only alternative I can find is to note the timestamps of the start and end of the event and then export that as a custom range. This is tedious, at best, when you should be able to just click a Download button on the clip review screen. 

**Additional context**
Adding Download Clip/Event button in on of these places would be ideal.
![image](https://github.com/user-attachments/assets/502ee15b-7f1a-48c5-a608-e45d00bfbaea)

**Comment by NickM-27** [comment]
This has already been implemented for the next version

**Comment by tokenwizard** [comment]
I assume this means an upcoming version as I just pulled the latest `ghcr.io/blakeblackshear/frigate:stable-tensorrt` image and still not seeing it.

**Comment by NickM-27** [comment]
Yes, 0.15 which is currently in beta

**Comment by NickM-27** [comment]
It's also worth mentioning that in the current version you can long tap or right click a review item to export that directly
