### ISSUE TITLE
Request for Compatibility with Blink Outdoor 4 and Blink Video Doorbell

### ISSUE THREAD

**Issue by ruidazeng** [blakeblackshear/frigate#14848]
Are there any plans to support Blink's Outdoor 4 and Video Doorbell cameras in future releases of Frigate? Currently, these devices lack native RTSP support, which complicates their integration. I came across a discussion [https://github.com/blakeblackshear/frigate/discussions/8935](https://github.com/blakeblackshear/frigate/discussions/8935) where users attempted to stream Blink cameras to Frigate by downloading MP4 files via the Blinkpy library and streaming them with a simple RTSP server. However, this approach resulted in significant delays and occasional missed videos 
GITHUB
.

**Comment by NickM-27** [comment]
There are no plans to support part-time streaming cameras, Frigate is designed to work with devices that stream continuously
