### ISSUE TITLE
Question: Coral Device To Camera Ratio or Formula

### ISSUE THREAD

**Issue by somejavadev** [blakeblackshear/frigate#1485]
Hi,  

Apologies if this is not the correct place to ask, I didn't see any other channels I could use. I am looking to purchase a Coral USB Accelerator for running frigate, currently I have 6 Xeon CPU cores dedicated as accelerators and 5 1080P cameras and looking to add up to 9 cameras. Is there perhaps a formula or ratio I can use to calculate how many Coral USB accelerators would be sufficient for such a task. The cameras are CCTV cameras with as much 'noise' movement removed via masks.

**Comment by blakeblackshear** [comment]
It is likely that 1 Coral will handle all the cameras unless many of them are in busy areas with lots of activity. There isn't a formula.

**Comment by somejavadev** [comment]
Thank you.
