### ISSUE TITLE
LPR...again.

### ISSUE THREAD

**Issue by deanfourie1** [blakeblackshear/frigate#14895]
**Describe what you are trying to accomplish and why in non technical terms**
So with the release a newly designed and awesome frigate (love it by the way) i'm going to yet again bring up LPR just to see if there are any plans in the near future to integrate the ability for ANPR.

I mean, giving how well frigate with with its object detection, I wouldn't imagine its toooo hard. But yea i'm just curious to know if there are any plans for upcoming releases that will aim to work toward native ANPR.

**Describe the solution you'd like**
License Plate recognition. Would be super cool to have the ability to enter known plates into frigate, and then any know plate data is also sent via MQTT etc.

And then all other plates are just recorded along with the vehicle detection.

**Describe alternatives you've considered**
well, there are none.  Not using frigate anyway.

**Additional context**
Yea just testing the waters here to see if there are plans or if you are just going to leave it out.

**Comment by NickM-27** [comment]
this has already been implemented for 0.16

**Comment by deanfourie1** [comment]
Legend thank you

**Comment by achanu** [comment]
Maybe let Frigate do the car detection and use LLM Vision to do the rest for the license plate, the color of the car or whatever
https://github.com/valentinfrlch/ha-llmvision/issues/120
