### ISSUE TITLE
Publish images to GHCR

### ISSUE THREAD

**Issue by onedr0p** [blakeblackshear/frigate#1490]
Dockerhub rate limits are a major pain in the butt, it would be cool if you could push the images to the github container registry.

Thanks @blakeblackshear !

**Comment by onedr0p** [comment]
🙏🏼

**Comment by onedr0p** [comment]
@blakeblackshear any thoughts on moving the CI to build the images to github workflows?

**Comment by blakeblackshear** [comment]
I don't object to it. Happy to accept a PR. Otherwise I will get to it when I get to it.
