### ISSUE TITLE
Entities Unavailable in Frigate Integration

### ISSUE THREAD

**Issue by cegit55** [blakeblackshear/frigate#1492]
Hi there,

I have the exact same issue as this guy:
https://www.reddit.com/r/homeassistant/comments/o4fxpx/trouble_with_frigate_integration/

The advice given is:
"Frigate and homeassistant need to be connected to the same mqtt server"

Apologies if this is a daft question but how do I do this?
(I only ask, as I've spent most of the day trying (and failing)).

Many thanks.

**Comment by RedNax67** [comment]
You'll have to install frigate-hass-integration and then, when it won't show up, empty your browser cache (or use a different browser) to add it. I've been wasting quite some time on this...

**Comment by shred86** [comment]
@cegit55 Which part are you having trouble with? If it's setting up an MQTT server, I just looked at a few YouTube videos and blogs. I'm personally using [eclipse-mosquitto](https://hub.docker.com/_/eclipse-mosquitto). Once that's set up, you just need to connect Home Assistant and Frigate to that MQTT server you set up. Home Assistant has an official MQTT integration you can just install and for Frigate, you just need to add the [mqtt settings](https://blakeblackshear.github.io/frigate/configuration/index#mqtt) to Frigate's config file.

**Comment by cegit55** [comment]
@shred86  Many thanks for the reply.

My Mosquito/MQTT and Frigate Add-On are working fine.
I have installed the Frigate Integration and all the entities are showing up (see Pic1) *BUT* I can't access them when I try to add them to an automation (see Pic2).

I was expecting to see the full list of automation entities just like this: https://youtu.be/43E5bxuaVj4?t=2279

Any ideas what's up?
Much obliged!

![Pic1](https://user-images.githubusercontent.com/88627488/129456383-19542a3c-acea-4d34-99aa-79015a70f949.png)

![Pic2](https://user-images.githubusercontent.com/88627488/129456389-5482dcfc-0e91-43d7-9382-c2c684e443d0.png)

**Comment by blakeblackshear** [comment]
There are multiple devices created by the integration. Look for a device named after your camera.

**Comment by cegit55** [comment]
Result! Thanks @blakeblackshear. Much appreciated.

**Comment by bgashler1** [comment]
If you're sure you're on the same MQTT server and it's still not working, what fixed it for me was updating to the latest version of the following: HACS, Frigate. Then remove and reinstall the Frigate Integration.
