### ISSUE TITLE
Add more verbose for debugging 

### ISSUE THREAD

**Issue by Dave-c-Ross** [blakeblackshear/frigate#14934]
**Describe what you are trying to accomplish and why in non technical terms**
It would be great to get more details on what triggered an alert and a detection. Sometimes, I see alerts from motion that happened in a zone that should not trigger alert, so I guess I have a miss configuration. To help find what is my mistake, it would be great to see what motion of what object in what zone had triggered this alert.

**Describe the solution you'd like**
Have a small overlay table for each event, giving metadata from the event, what triggered it.

**Describe alternatives you've considered**
Maybe in logs ? 

**Additional context**
None

**Comment by NickM-27** [comment]
This is already implemented for 0.15 (currently in beta) as the object lifecycle view

**Comment by Dave-c-Ross** [comment]
Alright ! Many thanks, I'll give it a try :)
And many thanks for all your works around Frigate !

**Comment by Dave-c-Ross** [comment]
😳 Just tried it, way better that what I would have imagined, seriously keep the good work, that app is amazing.
