### ISSUE TITLE
no detection in the zone but clips are generated (and alert sent)

### ISSUE THREAD

**Issue by balajeek** [blakeblackshear/frigate#1494]
I have a camera set with zone marking and any detection for object will sent notification to my iphone that was setup in home assistant.

Not sure why there are clips recorded (too many of them) and marked as this zone, that triggers sending the notification:

![image](https://user-images.githubusercontent.com/19213088/129056398-c09097ff-79c3-4b29-9e5c-edb1fb5b745d.png)

![image](https://user-images.githubusercontent.com/19213088/129056522-eeedf59d-85c5-42bf-9360-0d0a8b85699c.png)

Here is the config https://github.com/blakeblackshear/frigate/issues/1487 on my other posted issue.

Is there something in my setup i am doing wrong?

**Comment by lawm** [comment]
The wind is causing the leaves and shadows to move, causing Frigate to detect motion.
Once motion is detected, it recognized in the motion area, there is a minivan.
The vehicle's bounding box's bottom edge is inside the zone, so it created an event.

I would add motion masks, if possible, and lower the zone line a little.

**Comment by balajeek** [comment]
But if you look at the zone bounding box, even if there is motion, there is no vehicle inside the bounding box, why would it flag it as vehicle, the vehicle is outside of the zone though.  Is my understanding not right.

**Comment by lawm** [comment]
Go to your camera's live view in Frigate and turn on motion boxes and bounding box under Show Options.

The vehicle's bounding box's bottom edge is likely inside the zone.

The box is not perfect.  It can be a little bigger than the vehicle.

You can even see in your picture, the front tire is  in the zone.

**Comment by balajeek** [comment]
> Go to your camera's live view in Frigate and turn on motion boxes and bounding box under Show Options.
> 
> The vehicle's bounding box's bottom edge is likely inside the zone.
> 
> The box is not perfect. It can be a little bigger than the vehicle.
> 
> You can even see in your picture, the front tire is in the zone.

okay, i understand that, i will shorten the box and see what happen.

**Comment by balajeek** [comment]
I made it like this, I hope it good:

![image](https://user-images.githubusercontent.com/19213088/129092201-8e78f2a0-3cd7-44cf-ae48-0f03abbe5e30.png)
