### ISSUE TITLE
Do not use time / timezone from browser

### ISSUE THREAD

**Issue by sean797** [blakeblackshear/frigate#14955]
**Describe what you are trying to accomplish and why in non technical terms**
When looking at the new UI review page from in a different timezone to my camara and/or server, the time displayed is incorrect. However when you export a clip, the time displaed is correct (local to camara) 

**Describe the solution you'd like**
I'd like the time displayed to be both consitent, and probably should be sourced from the frigate server - never the browser.

**Describe alternatives you've considered**
Using the browser time everywhere, but atleast in my usecase, i'm more likely to be reviewing events when im away from my camaras.

**Additional context**
2 images; one from the review page, one from exports of the same event while in another timezone
![Screenshot from 2024-11-13 06-51-53](https://github.com/user-attachments/assets/2910e7f9-6c72-4c99-80d5-fba3d9f291de)
![Screenshot from 2024-11-13 06-51-02](https://github.com/user-attachments/assets/415727fb-909a-481a-8e4d-8fdeea746764)

**Comment by hawkeye217** [comment]
This is adjustable via a config option:

```
ui:
  timezone: America/Chicago
```

There are several bugs with it in 0.14 that have since been corrected and are available in the dev branch and the upcoming 0.15 betas.
