### ISSUE TITLE
Authorization Roles

### ISSUE THREAD

**Issue by mnelni** [blakeblackshear/frigate#14975]
Describe what you are trying to accomplish and why in non technical terms
Different levels of access for different users

Describe the solution you'd like

Roles:

read-only
permissions:
live view 
View events
boundary: can be scoped to 1 or more cameras/zone
Actors: Limited user

delegated-manager

permissions:
live view
View events
View/recordings
View/ Snapshot
boundary: can be scoped to 1 or more cameras/zone
Actors: User
Admin (full access)
permissions:
boundary:
Actors: admins

**Comment by hawkeye217** [comment]
Roles/groups already has a pinned feature request and is planned for a future version. This is a duplicate of #6614
