### ISSUE TITLE
Recognise objects including people / faces.

### ISSUE THREAD

**Issue by wills106** [blakeblackshear/frigate#15]
It would be great if frigate could recognise objects and especially recognise people it has already seen as well as report people it does not know.

This can be handy for a number of reasons, if it recognised the post lady it could either tell the Camera System not to record the activity as it is a known person, or you could use it to trigger a notification that your post has been delivered.

Another example is if it recognises a family member visiting you, it could announce their arrival.

Another example is if it detects an unknown person or vehicle on your property it could trigger a manual recording and notify you of suspect activity on your property.

**Comment by blakeblackshear** [comment]
All of these use cases are things I want too. Would be great to know if the trash can is out on trash day. It will require building the ability to train your own models, which will be a separate effort. The output of that training would then feed in here.

**Comment by tubalainen** [comment]
> All of these use cases are things I want too. Would be great to know if the trash can is out on trash day. It will require building the ability to train your own models, which will be a separate effort. The output of that training would then feed in here.

We can maybe start with forwarding of the different detected objects from the model to the MQTT? 
The model supports quite some items.

Not family members / faces .. that would require training. :)
