### ISSUE TITLE
Requesting MQTT SSL/TLS support

### ISSUE THREAD

**Issue by BrianWithAHat** [blakeblackshear/frigate#1508]
There's currently no configuration option to enable SSL/TLS support for encrypted MQTT communications.

This does appear to be supported by the paho-mqtt library.

> tls_set()
> 
> tls_set(ca_certs=None, certfile=None, keyfile=None, cert_reqs=ssl.CERT_REQUIRED,
>     tls_version=ssl.PROTOCOL_TLS, ciphers=None)
> 
> Configure network encryption and authentication options. Enables SSL/TLS support.
> 
> ca_certs
>     a string path to the Certificate Authority certificate files that are to be treated as trusted by this client. If this is the only option given then the client will operate in a similar manner to a web browser. That is to say it will require the broker to have a certificate signed by the Certificate Authorities in ca_certs and will communicate using TLS v1.2, but will not attempt any form of authentication. This provides basic network encryption but may not be sufficient depending on how the broker is configured. By default, on Python 2.7.9+ or 3.4+, the default certification authority of the system is used. On older Python version this parameter is mandatory.
> certfile, keyfile
>     strings pointing to the PEM encoded client certificate and private keys respectively. If these arguments are not None then they will be used as client information for TLS based authentication. Support for this feature is broker dependent. Note that if either of these files in encrypted and needs a password to decrypt it, Python will ask for the password at the command line. It is not currently possible to define a callback to provide the password.
> cert_reqs
>     defines the certificate requirements that the client imposes on the broker. By default this is ssl.CERT_REQUIRED, which means that the broker must provide a certificate. See the ssl pydoc for more information on this parameter.
> tls_version
>     specifies the version of the SSL/TLS protocol to be used. By default (if the python version supports it) the highest TLS version is detected. If unavailable, TLS v1.2 is used. Previous versions (all versions beginning with SSL) are possible but not recommended due to possible security problems.
> ciphers
>     a string specifying which encryption ciphers are allowable for this connection, or None to use the defaults. See the ssl pydoc for more information.
> 
> Must be called before connect*().

I'm happy to perform testing or even a pull request if would be helpful.

**Comment by blakeblackshear** [comment]
The beta released today has new tls options for mqtt

**Comment by BrianWithAHat** [comment]
Perfect! I only looked in master and missed the release branch. I was able to get it working. Thanks.
