### ISSUE TITLE
Clip Images can't close when opening from mobile ios app notifications

### ISSUE THREAD

**Issue by tdebans** [blakeblackshear/frigate#1509]
**Describe the bug**
When opening an image from notification.
https://community.home-assistant.io/t/frigate-mobile-app-notifications/311091
The image opens in HA ios app directly.
Image can not be closed.
Response on HA ios app bugreport:
It is unintended use of the url parameter to open non-frontend pages in HA app.
https://github.com/home-assistant/iOS/issues/1827

there is no URL to reach a specific frigate event frontpage
for example: 
-http://example.com/events/1628840618.166655-hmlx1u
-http://example.com/api/events/1628840618.166655-hmlx1u
only the direct link to the image or the mp4

**Version of frigate**
0.8.4-5043040

**Expected behavior**
create a direct link/url frontpage to a specific event.

**Additional context**

**Comment by jschwalbe** [comment]
No link? Yes there is! 

https://blakeblackshear.github.io/frigate/usage/api/

Instead of using the "example.com" links you mentioned above, you would use:
http://frigate-ip:5000/api/events/1628840618.166655-hmlx1u/snapshot.jpg
and
http://frigate-ip:5000/clips/CAMERANAME-1628840618.166655-hmlx1u.mp4

Easy peasy.

**Comment by tdebans** [comment]
that is what i mention, a direct link to the snapshot or mp4 clip is available
i mean a frontpage
for example: https://HA-SERVER:8123/api/events/1628840618.166655-hmlx1u
as it is mentioned unintended use op open non-frontend pages in HA app, such as direct link to jpg

**Comment by dealanis** [comment]
Hello! did someone got an elegant solution for this?
