### ISSUE TITLE
0.9.0 Beta 1 / Clips and Home Assistant's Media Browser

### ISSUE THREAD

**Issue by quenthal** [blakeblackshear/frigate#1510]
After upgrading to 0.9.0 Beta 1 from 0.9.0-50f0c05-amd64 I noticed that clips are no longer playable from Home Assistant's Media Browser. Clips before the update still work, also they play fine from Frigate's own ui.

**Comment by blakeblackshear** [comment]
The first sentence in the description of the release tells you this is a known issue.
