### ISSUE TITLE
Reporting "No frames have been received" status to HomeAssistant

### ISSUE THREAD

**Issue by AndreasBVB** [blakeblackshear/frigate#15104]
**Describe what you are trying to accomplish and why in non technical terms**
The "No frames have been received" message is currently displayed in the video frame. I want the situation to be known in HA so that users can monitor and take necessary actions.

**Describe the solution you'd like**
I wonder if it is possible to send the status to HA, maybe through MQTT and add a binary sensor in HA integration?

**Describe alternatives you've considered**
Periodical MQTT messages about the status could also help.

**Additional context**

**Comment by hawkeye217** [comment]
This is already available through MQTT and the HA integration. 

https://docs.frigate.video/troubleshooting/faqs/#how-do-i-know-if-my-camera-is-offline

**Comment by AndreasBVB** [comment]
Is the cam status expected to be exactly in-line with the "no-frame" status? I observed quite frequently when the camera frame says "no frame" but the cam status says "recording", so I assumed they were not completely equivalent.

**Comment by hawkeye217** [comment]
Yes, it may be slightly lagged.

**Comment by AndreasBVB** [comment]
Thank you for confirming! Useful feature!

**Comment by NickM-27** [comment]
it depends on the cause, realistically you should create a support discussion so we can look in to the specific case
