### ISSUE TITLE
Bring back the 0.13 camera selection logic

### ISSUE THREAD

**Issue by jiiins** [blakeblackshear/frigate#15145]
**Describe what you are trying to accomplish and why in non technical terms**
I have many cameras. If I want to select all but 1, I need to select each camera individually.

**Describe the solution you'd like**
Like in 0.13, I would like the All Cameras toggle to enable all cameras individually, so that I can turn off the ones I don't want.

**Describe alternatives you've considered**
I made groups which are great, but quite often the above is useful.

**Comment by NickM-27** [comment]
You should create a camera group for cameras that are often filtered out, as camera groups are shown in the filter menu. The 0.13 had separate issues and was confusing for many users.
