### ISSUE TITLE
Guide on How to set up build?

### ISSUE THREAD

**Issue by lukedukeus** [blakeblackshear/frigate#1517]
I want to help develop on this project, but I haven't been able to find out how to build the code. 

I have cloned /frigate-hass-addons , and added that repo in home assistant, so that I can install it.
I have modified /frigate-hass-addons/Dockerfile to point to a docker image that I have yet to create. 

In this repo, I found the Makefile, which runs the build commands, but cannot find out how to create the docker image and upload it. Is this done by github actions?

Also, When I am developing, do I have to commit each change, then run the makefile, then publish my container for each change? or is there a simpler way?

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/contributing.md

**Comment by MarkGodwin** [comment]
Oh gee, I wish I had noticed that the release-0.9.0 branch was way ahead of master. That would have saved me a lot of headaches!
Looks like all the roadblocks I hit have already been resolved.
