### ISSUE TITLE
Frigate+ Website -> Images -> Add Object filter in addition to camera.

### ISSUE THREAD

**Issue by zonyl** [blakeblackshear/frigate#15190]
**Describe what you are trying to accomplish and why in non technical terms**
As a user of Frigate+, I would like to filter images I have already validated by object type, so that I can improve my model by deleting or redefine some items that were difficult to detect.

**Describe the solution you'd like**
Add a filter by object in addition to the camera filter on the Frigate+ Website images screen.

**Describe alternatives you've considered**
Havent found  a good alternative to this other than trying to see the objects in the tiny preview windows for all cameras

**Additional context**

**Comment by NickM-27** [comment]
This is not the right place to request features for Frigate+ specifically, I would suggest leaving a comment on the Frigate+ discussion https://github.com/blakeblackshear/frigate/discussions/14762
