### ISSUE TITLE
[HWAccel] does not work if only /dev/dri/renderD129

### ISSUE THREAD

**Issue by Serverfrog** [blakeblackshear/frigate#15207]
**Describe what you are trying to accomplish and why in non technical terms**
I want to use Frigate in K8s with the intel-device-plugin Operator where an Intel Arc A770 is installed.
this will mount the GPU with renderD129, and no renderD128.
So the Code Currently sees only one device ( https://github.com/blakeblackshear/frigate/blob/33957e53600afd0e1a677d6575917955d156dd4a/frigate/ffmpeg_presets.py#L37 )

**Describe the solution you'd like**
Kinda removing that if case, as i don't see the major benefit to not check the devices and also then refusing to use other devices then renderD128 if only one is present

**Describe alternatives you've considered**
An alternative would be an parameter which overrides the default renderD128 to another path.

**Additional context**
The reason for that change is that the intel-device-plugin Operator just mounts one device that is present, even if my CPU is mounted on the host under renderD128, it will not be used here (i think a old IntelHD Graphics should not be used for Frigate ;) ) it will mount only renderD129 with exactly that name. Due to forcing to use renderD128 when only one devices is present, this kinda wont work with me

**Comment by NickM-27** [comment]
This has already been fixed in 0.15

**Comment by Serverfrog** [comment]
Ahh nice! But the latest stable release i saw was 0.14.1, thats why i was using that, will test it!

**Comment by philuxe** [comment]
I might have similar issue. I'm passing an AMD integrated GPU to the container (K8S).
In my case /dev/dri/renderD128 doesnt not exist I just have :

/dev/dri/by-path/pci-0000:00:02.0-card
and
/dev/dri/card0

lspci from the k8s worker: 

00:00.0 Host bridge [0600]: Intel Corporation 440FX - 82441FX PMC [Natoma] [8086:1237] (rev 02)
00:01.0 ISA bridge [0601]: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II] [8086:7000]
00:01.1 IDE interface [0101]: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II] [8086:7010]
00:01.2 USB controller [0c03]: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] [8086:7020] (rev 01)
00:01.3 Bridge [0680]: Intel Corporation 82371AB/EB/MB PIIX4 ACPI [8086:7113] (rev 03)
00:02.0 VGA compatible controller [0300]: Device [1234:1111] (rev 02)
00:03.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon [1af4:1002]
00:05.0 SCSI storage controller [0100]: Broadcom / LSI 53c895a [1000:0012]
00:07.0 SATA controller [0106]: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] [8086:2922] (rev 02)
00:08.0 Communication controller [0780]: Red Hat, Inc. Virtio console [1af4:1003]
**00:10.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [1002:1638] (rev c8**)
00:12.0 Ethernet controller [0200]: Red Hat, Inc. Virtio network device [1af4:1000]
00:1e.0 PCI bridge [0604]: Red Hat, Inc. QEMU PCI-PCI bridge [1b36:0001]
00:1f.0 PCI bridge [0604]: Red Hat, Inc. QEMU PCI-PCI bridge [1b36:0001]
