### ISSUE TITLE
Feature request - night vs day settings

### ISSUE THREAD

**Issue by Jolly-Roger82** [blakeblackshear/frigate#1520]
I'm using frigate for a couple of weeks and I must say it is amazing.

But there have been some burglaries in my neighborhood, yesterday and last week on Thursday.

I have one of my cameras watching the road in front of my house with a mask. Because the sidewalk and road gets heavily used during the day I didn't want to clip or record every movement.

Would it be possible to switch off the mask during particular time frames like between 00.00 and 05.00 o'clock, just to capture nightly activities in stead of all during busy daytime hours?

Keep up the good work! Frigate is 'friggin' awesome!

**Comment by mtongnz** [comment]
I'd like to add to this request.

My cameras trigger my security lights.  They turn on great but when the lights turn off, the camera takes about 5 seconds to re-adjust exposure.... This triggers frigate with motion detection and it "detects" my car parked in the drive which turns the lights back on.

Would be great if there was a way to fix this without complex timers in HA.
