### ISSUE TITLE
Implement support for Lower Power Cameras such as Solar Cameras

### ISSUE THREAD

**Issue by deanfourie1** [blakeblackshear/frigate#15226]
**Describe what you are trying to accomplish and why in non technical terms**
Support for low power cameras like Solar cameras. I have seen a lot of people asking for this all over the interwebs.

**Describe the solution you'd like**
The ability for frigate to have the options to select if the camera is a "Low Powered Device" allowing for a non-continuous stream to be handled by frigate.

**Describe alternatives you've considered**
There are no alternatives. For low powered camera's in locations where there are power limitations, there are no alternative solutions.

**Additional context**
Nothing really.

**Comment by NickM-27** [comment]
Frigate is designed to work with continuous streaming cameras. There are a number of reasons why non continuous streaming cameras can not work. There are some external projects to turn some battery camera models into continuous streaming but that is outside the scope of frigate.

**Comment by deanfourie1** [comment]
So what's the behavior here?

When the camera stops the RTSP stream, obviously the camera is offline in Frigate. When the camera starts the RTSP stream, does the camera come back online in Frigate?

**Comment by NickM-27** [comment]
If you are referring to the projects, they basically save the last frame the camera sent and continually send that to Frigate. So as far as frigate knows the camera is continuously streaming

**Comment by deanfourie1** [comment]
No im just referring to what the behavior is for feigate with non continuous streams, does the stream come back up once its being output by the camera again?

so, the camera wakes up and strats outputting a TRSP stream, does that stream come back online in frigate?

**Comment by NickM-27** [comment]
Depends on the camera, some cameras will stream continuously and run out of battery. Others will just stop, frigate will keep spinning until the stream starts back up again

**Comment by deanfourie1** [comment]
ok thanks
