### ISSUE TITLE
[Feature Request] - Ability to Turn off Camera completely in frigate.

### ISSUE THREAD

**Issue by joeShuff** [blakeblackshear/frigate#1522]
Currently my setup contains only indoor cams for the time being, but I feel it may be a common usecase as powering cameras indoor is much easier than outside. During the day when someone is home these cameras are "off", panned to face the corner of a wall and recording/detection is turned off in frigate. However, the container CPU usage still remains high because of the restreaming via RTMP. (Uses about 45% when completely idle streaming walls, around 80-90% when recording all the cameras at night/when away)

I think a toggle to completely turn off indivudual cameras would be suitable in these situations, I don't want to waste resources streaming the wall. I imagine if all cameras are off the restreaming wouldn't happen and CPU usage would drop down. 

Functionality wise I think the following.
- Toggling camera off turns off all detect/record/snapshot and stores their state before they were turned off.
- Toggling the camera on returns detect/record/snapshot to their previous state.
- Either disabling the ability to toggle detect/record/snapshot if the camera is off OR turning any of detect/record/snapshot on will also turn the camera on but not restore previous states.

Totally up for discussion if anyone has any other suggestions for solving this issue. I know some cameras can cut their RTSP stream which does stop frigate restreaming (obviously) but not all cameras can do this.

**Comment by blakeblackshear** [comment]
There are many existing requests for this already. The CPU usage is from the stream being decoded and passed to frigate, not RTMP restreaming. RTMP uses almost no CPU because it is a simple passthrough.

**Comment by joeShuff** [comment]
Ah sorry, I tried to see if there was any existing issues but found nothing.
