### ISSUE TITLE
Can't use secrets in frigate.yml

### ISSUE THREAD

**Issue by withanhdammit** [blakeblackshear/frigate#1524]
I installed Frigate as an add-on via HACS in my Home Assistant.
The instructions say the config file must be frigate.yml.
When I try to mask items like:
    !secret mqtt_pass
It errors as:
Error parsing config: could not determine a constructor for the tag '!secret'
  in "<unicode string>", line 3, column 9:
      user: !secret mqtt_user
            ^

I played around with the file name a bit, and if I name it as 'frigate.yaml' it started working, until I restarted Frigate, then it complained there is no 'frigate.yml'.

Is there a way to use the HA !secret tag with Frigate?

**Comment by janstadt** [comment]
Can you check and see if you have included your secrets into the default configuration.yaml? ex: `secrets: !include secrets.yaml`

**Comment by janstadt** [comment]
i've tried `!env_var` in my secrets file like this `FRIGATE_RTSP_PASSWORD: !env_var FRIGATE_RTSP_PASSWORD "password"` and i dont have any luck either. the docs say to use {} to wrap your environment vars that start with FRIGATE_ but that doesnt seem to work at all. I dont want to actual edit my .env file for homeassistant but i also dont want the passowrds chillin in the firgate.yml. It does seem like the extension of .yml is messing with the rest of homeassistant .yaml files or the cascading nature of yaml isnt happening with yml files??

**Comment by blakeblackshear** [comment]
Frigate's yaml file has nothing to do with the home assistant config files. They just happen to be in the same config directory. There is no magic that happens because two files are in the same folder. In fact, frigate has no idea home assistant even exists. It runs completely independent in it's addon container. Also, home assistant does not do anything with the frigate.yml file. None of the special yaml stuff HA supports applies to frigate. 

The env vars referenced in frigate's config would need to be set on the addon container for frigate, not the HA container.

**Comment by janstadt** [comment]
Thanks @blakeblackshear thats helpful info. I had finally found this portion of the docs and i assume that's where we'd throw in the env vars: https://blakeblackshear.github.io/frigate/configuration/advanced#environment_vars

**Comment by janstadt** [comment]
@blakeblackshear is there a preference/benefit of running frigate directly in hassos vs docker? I have a qnap nas which unfortunately requires me to run hassio on a VM. I have that running and installed frigate via the hassos addon and it seems to be doing just fine but i also have a bunch of other docker containers running directly in qnap. Would there be a benefit to having frigate running directly on the qnap docker instance vs running frigate inside hassio on the VM?

**Comment by blakeblackshear** [comment]
> Thanks @blakeblackshear thats helpful info. I had finally found this portion of the docs and i assume that's where we'd throw in the env vars: https://blakeblackshear.github.io/frigate/configuration/advanced#environment_vars

You could, but then secrets would still be in the same config file anyway. Typically those are passed by a docker run command or set in the compose file.

**Comment by blakeblackshear** [comment]
> @blakeblackshear is there a preference/benefit of running frigate directly in hassos vs docker? I have a qnap nas which unfortunately requires me to run hassio on a VM. I have that running and installed frigate via the hassos addon and it seems to be doing just fine but i also have a bunch of other docker containers running directly in qnap. Would there be a benefit to having frigate running directly on the qnap docker instance vs running frigate inside hassio on the VM?

Running in HassOS limits your options for where recordings are stored. I generally recommend running directly, but you don't get the nice sidebar link to the embedded UI. I do plan to address that with a proxy addon soon.
