### ISSUE TITLE
FR: thumbnails larger than 175px (v14/v15-beta)

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#15249]
**Describe what you are trying to accomplish and why in non technical terms**
The excellent thumbnails that crop / feature the object detected - it would be great if these could be larger than 175 x 175 pixels.

The use case for this is the frigate-hass-card (home assistant card) , in its media gallery mode.    According to the developer of this card:
  "This is a back-end limitation: Frigate itself exports thumbnails with that are 175x175, this is why I capped the card at that same number. If we had higher values, it would just stretch/pixelate the thumbnails. So I'd suggest you take this request upstream to Frigate itself. If it can support larger values, I'm happy to increase that cap in the card to take advantage!"
  here is that post:  https://github.com/dermotduffy/frigate-hass-card/issues/1676

**Describe the solution you'd like**
possibly allow the user to define the thumbs size in config,  Or if no configuration / size is specified in config, it will default to the 175px currently.

**Describe alternatives you've considered**
None
(edit-  i forgot, i did try to extract out or embed the frigate-ip/review page at one point, As that page has larger thumbnails that crop to the action for each event, however i was unsuccessful.)

thanks ( LOVE FRIGATE!! if u use it DONATE ! )

to give a bit more context, On some of my Home assistant powered Crestron panels (several 10" and a few 7") I have a display like this, Im hoping to expand it larger but Id like the thumbnails to be larger in size so they can be easily viewed from a distance or with a quick glance.

![image](https://github.com/user-attachments/assets/719f9e24-7893-4ec5-b368-484331ed70e3)

**Comment by NickM-27** [comment]
The object thumbnails are stored in the database right now so we can't increase the size. Perhaps when they're saved externally they could be configurable

**Comment by NickM-27** [comment]
looks like this was implemented in the frigate card
