### ISSUE TITLE
Can't seem to keep Frigate running long enough to install HACS Integration

### ISSUE THREAD

**Issue by alexp121** [blakeblackshear/frigate#1525]
Frigate NVR
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for back: 36
frigate.app                    INFO    : Capture process started for back: 38
detector.coral                 INFO    : Starting detection process: 33
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate.app                    INFO    : Stopping...
frigate.record                 INFO    : Exiting recording maintenance...
frigate.object_processing      INFO    : Exiting object processor...
frigate.events                 INFO    : Exiting event cleanup...
frigate.events                 INFO    : Exiting event processor...
frigate.watchdog               INFO    : Exiting watchdog...
frigate.stats                  INFO    : Exiting watchdog...
peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
root                           INFO    : Waiting for detection process to exit gracefully...
frigate.video                  INFO    : back: exiting subprocess

**Comment by blakeblackshear** [comment]
Looks like you don't have a Coral. You need to configure CPU detectors.

**Comment by alexp121** [comment]
Thanks for the quick reply!
Still no luck 😢 Running on a HP server with Proxmox and HassOS container
Might just purchase the coral

This is my frigate.yml config:
mqtt:
  host: core-mosquitto
cameras:
  back:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.1.111:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 10


And this is the log:
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for back: 36
frigate.app                    INFO    : Capture process started for back: 38
detector.coral                 INFO    : Starting detection process: 33
frigate.edgetpu                INFO    : Attempting to load TPU as usb
Process detector:coral:
frigate.edgetpu                INFO    : No EdgeTPU detected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
ffmpeg.back.detect             ERROR   : [AVHWDeviceContext @ 0x55b0be2814c0] No VA display found for device /dev/dri/renderD128.
ffmpeg.back.detect             ERROR   : Device creation failed: -22.
ffmpeg.back.detect             ERROR   : [h264 @ 0x55b0be280700] No device available for decoder: device type vaapi needed for codec h264.
ffmpeg.back.detect             ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate.app                    INFO    : Stopping...
frigate.events                 INFO    : Exiting event processor...
frigate.record                 INFO    : Exiting recording maintenance...
ffmpeg.back.detect             ERROR   : [AVHWDeviceContext @ 0x55cf09252a00] No VA display found for device /dev/dri/renderD128.
ffmpeg.back.detect             ERROR   : Device creation failed: -22.
ffmpeg.back.detect             ERROR   : [h264 @ 0x55cf090ab700] No device available for decoder: device type vaapi needed for codec h264.
ffmpeg.back.detect             ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
frigate.object_processing      INFO    : Exiting object processor...
frigate.events                 INFO    : Exiting event cleanup...
frigate.watchdog               INFO    : Exiting watchdog...
ffmpeg.back.detect             ERROR   : [AVHWDeviceContext @ 0x55c04c817040] No VA display found for device /dev/dri/renderD128.
ffmpeg.back.detect             ERROR   : Device creation failed: -22.
ffmpeg.back.detect             ERROR   : [h264 @ 0x55c04c7e4640] No device available for decoder: device type vaapi needed for codec h264.
ffmpeg.back.detect             ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
ffmpeg.back.detect             ERROR   : [AVHWDeviceContext @ 0x55bca3092100] No VA display found for device /dev/dri/renderD128.
ffmpeg.back.detect             ERROR   : Device creation failed: -22.
ffmpeg.back.detect             ERROR   : [h264 @ 0x55bca2ef3200] No device available for decoder: device type vaapi needed for codec h264.
ffmpeg.back.detect             ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
ffmpeg.back.detect             ERROR   : [AVHWDeviceContext @ 0x55e8a1d07a00] No VA display found for device /dev/dri/renderD128.
ffmpeg.back.detect             ERROR   : Device creation failed: -22.
ffmpeg.back.detect             ERROR   : [h264 @ 0x55e8a1de9000] No device available for decoder: device type vaapi needed for codec h264.
ffmpeg.back.detect             ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
ffmpeg.back.detect             ERROR   : [AVHWDeviceContext @ 0x5561399dc940] No VA display found for device /dev/dri/renderD128.
ffmpeg.back.detect             ERROR   : Device creation failed: -22.
ffmpeg.back.detect             ERROR   : [h264 @ 0x5561399d9700] No device available for decoder: device type vaapi needed for codec h264.
ffmpeg.back.detect             ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
frigate.video                  INFO    : back: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
frigate.stats                  INFO    : Exiting watchdog...
peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
root                           INFO    : Waiting for detection process to exit gracefully...

**Comment by shred86** [comment]
As it’s been mentioned, you have to add the CPU detectors to your config. This [page of the docs](https://blakeblackshear.github.io/frigate/configuration/detectors) explains it and there’s an example of adding a CPU detector at the very bottom.

**Comment by alexp121** [comment]
Cool, Im an idiot and thought the 
```
hwaccel_args:
- -hwaccel
- vaapi
- -hwaccel_device
- /dev/dri/renderD128
- -hwaccel_output_format
- yuv420p
```

was all I needed. Sorry, case closed!
