### ISSUE TITLE
Pushover support

### ISSUE THREAD

**Issue by JoshuaSeidel** [blakeblackshear/frigate#15315]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to natively get frigate notifications without needing to setup automations in home assistant, native notifications are much faster. The iPhone PWA app currently doesn't support rich notification with previews and snapshots. This would allow iPhone users to get native notifications. 

**Describe the solution you'd like**
Implement Pushover over.

https://support.pushover.net/i44-example-code-and-pushover-libraries

**Comment by NickM-27** [comment]
This can already be done using MQTT as a feed in, and there is a Frigate project that already supports this https://github.com/0x2142/frigate-notify
