### ISSUE TITLE
Semantic search support for Hailo

### ISSUE THREAD

**Issue by hiteshsharma** [blakeblackshear/frigate#15336]
**Describe what you are trying to accomplish and why in non technical terms**
I recently started using Frigate v0.15 with Hailo 8l on a pi 5. I see that when I enable semantic search, it uses CPU instead of Hailo. Can Hailo be supported for semantic search?

**Describe the solution you'd like**
Support semantic search using Hailo 8L 

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment]
Hailo can only run one model at a time. Hailo also requires the model to be converted to a specific file format and I don't believe the embeddings onnx models are supported for this Hailo format
