### ISSUE TITLE
Allow authenticated port 8971 for link with HomeAssistant

### ISSUE THREAD

**Issue by koudonojinchuu** [blakeblackshear/frigate#15355]
[As described in this discussion](https://github.com/blakeblackshear/frigate/discussions/15352), I am trying to use Frigate and HomeAssistant on two different machines, for valid reasons.

Right now, it would seem that this can only be achieved through the unauthenticated port 5000.
Would it be possible to enable the usage of the authenticated port 8971?

(By the way, would this rather be a feature request for the HomeAssistant project instead?)

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/13297
