### ISSUE TITLE
Any way to address the message "No frames have been received, check error logs" via MQTT / Home assistant

### ISSUE THREAD

**Issue by SuperMaximus1984** [blakeblackshear/frigate#15395]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to track "No frames have been received, check error logs" message and dynamically adjust improve contrast or other sensitivity parameters like Threshold.

**Describe the solution you'd like**
When snow falls all my 9 cameras load server so that No frames have been received message appear and system can't detect objects normally. Especially it happens at night time, and I want to be able to trigger this message in Home Assistant and adjust detection parameters that mitigate "No frames.." message.

**Comment by NickM-27** [comment]
You can do this looking at the camera fps and skipped fps

**Comment by SuperMaximus1984** [comment]
@NickM-27 The problem is that in such conditions as I described quite often Frigate never restores normal inferencing, "No frames..." message persists forever in the viewport unless container is restarted. Sometimes quite a few frames may be skipped and No frames may not raise.

**Comment by NickM-27** [comment]
Then I'd suggest creating a support discussion so we can take a look
