### ISSUE TITLE
gstreamer native support ...wsl2 GPU passthrough 

### ISSUE THREAD

**Issue by khalidaboelmagd** [blakeblackshear/frigate#15416]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to gstreamer instead of ffmpeg natively 

**Describe the solution you'd like**
i was able to use wsl2 with Intel GPU passthrough,
however ffmpeg not able to decode HEVC h265 from my 4k camera ,it is working fine with h264..
i tried gstreamer and both of cameras now utilizing GPU..

**Describe alternatives you've considered**
I know that might be mesa or wsl2 issue bur it will be great if we can use gstreamer

**Additional context**

**Comment by NickM-27** [comment]
ffmpeg is used throughout frigate, the effort to support gstreamer would be immense amount of work and would likely more than double the effort to maintain support for hardware and new features. 

A couple years ago this was considered as part of the nvidia-jetson implementation but it brought many problems and complexities and this has only grown as frigate uses ffmpeg for more features. 

I would suggest that you create a support discussion to figure out why ffmpeg is not working for you, it is likely just a config issue
