### ISSUE TITLE
Frigate+ suggested labels should respect object masks

### ISSUE THREAD

**Issue by F1VWdk** [blakeblackshear/frigate#15424]
The suggested tagging is great but it should respect defined object masks.

To illustrate, I have couple of cam overlooking a parking lot where tracking of parked cars is not needed and, per Frigate documentation, object masks were created to prevent detection of those cars. But, when other objects are detected and sent to Frigate+, auto tagging still detects all those parked cars requiring tabbing between all those labels to be deleted before accomplishing verification.

I have few other cams where other object masks were created for people, dogs, cars but still auto tag by the suggestion feature.

Thank you

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the TrackedObjectProcessor class to filter out objects that are within masked areas before sending them for auto-tagging. This will ensure that objects in masked areas (like parked cars) are not included in the auto-tagging suggestions.

You can review changes in this commit: https://github.com/mnmnk43434/blakeblackshear-frigate-15424/commit/4758b628d24043e427edc032675b77ff4f4c71d6.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by NickM-27** [comment]
> per Frigate documentation, object masks were created to prevent detection of those cars. 

No, that is incorrect. Object masks are to block out false positives not to block out true positive cases that you don't care about. 

Also to be clear the frigate code and frigate+ suggestions are entirely unrelated.

**Comment by NickM-27** [comment]
Additionally, this is not the place to request features for Frigate+

**Comment by NickM-27** [comment]
Object masks won't affect auto labeling at all, auto labeling does not run on your frigate instance and has no knowledge of your object masks. 

Furthermore if you removed the suggested cars and trained that model then you'd be incorrectly teaching the model that those are not cars - reducing the models accuracy. 

As far as your frigate instance goes, if things are working as desired I see no reason to change the configuration but in general masking true objects is not recommended.
