### ISSUE TITLE
Zone required for Clips, Person outside the zone triggering Clips

### ISSUE THREAD

**Issue by HairyHook** [blakeblackshear/frigate#1544]
Hello,

First of all, I'd like to congratulate Blake for a fantastic piece of software. It has exceeded my expectations. 

I have setup zones and listed the zone under clips, required_zones. Once a day, for couple different cameras, I receive clip alerts notifying me that a person has been detected, but the person is clearly outside the zone and there are no shadows or anything that could make Frigate think a person is inside the zone:

Example: 
Zone setup
![image](https://user-images.githubusercontent.com/63165721/129805358-bec5492a-20ff-4a8c-8565-fb4bb85c05f5.png)
Person detected and clip recorded
![image](https://user-images.githubusercontent.com/63165721/129805523-3fa9f028-cc66-4d41-9672-1f5c7872c31f.png)

95% of the time the system behaves as expected and people walking don't generate Clips. Trying to figure out if this is a bug or a problem with the config. Let me know if you need me to supply more information.

Thank you

**Comment by blakeblackshear** [comment]
I would guess you are running into something like this: https://github.com/blakeblackshear/frigate/issues/1246

**Comment by HairyHook** [comment]
Thank you, Blake. Is the recommendation to increase the min_score and min_area? Any way to see the bounding box in the clips or just in snapshots?

**Comment by blakeblackshear** [comment]
That's the simplest option. If that doesn't work, you could look at using the filters on zones in combination with required zones.

**Comment by lawm** [comment]
My guess is that in some cases, the bounding box's bottom center (as explained in the issue Blake posted) is entering the zone on the right wall.

Something like this:
![image](https://user-images.githubusercontent.com/3174101/129985725-96d24d52-ee2d-4bf5-aebd-518697ab10d8.png)

You can move the zone line on the top of the wall, to the right.  Even if there's someone at the window, I think it will still 'enter' the zone marked on the grass or lower wall area.


BTW, you can also see the bounding box by going to Frigate, click your camera for a live view, then click SHOW OPTIONS and enable Bounding box.

**Comment by HairyHook** [comment]
Thank you both! Understanding the bounding box's bottom center behavior has been a huge help. That, combined with min_area filters has reduced the false positives.
