### ISSUE TITLE
Disable transitions in explore view

### ISSUE THREAD

**Issue by mike2307** [blakeblackshear/frigate#15488]
**Describe what you are trying to accomplish and why in non technical terms**
The new explore view in 0.15.0 is a nice addition to quickly browse through detected objects. However the transitions when clicking on an object come with a rather big performance hit. Sometimes I need to work in a VM and this doesn't seem to be rendered in hardware. 

**Describe the solution you'd like**
Would be nice to get an option in the UI to disable all non-essential transitions.

**Describe alternatives you've considered**
Maybe some browser add-ons and/or CSS hacks can accomplish something similar but that would be rather cumbersome and needs to be done on every targeted machine.

**Additional context**

**Comment by NickM-27** [comment]
What transitions are you referring to?

**Comment by NickM-27** [comment]
I have done some profiling and I don't see any performance issues, the page is similar to the review page. If you continue to experience this on the latest beta I would suggest creating a bug report with browser profiling information so we can understand what is using CPU in your case

![Screen Shot 2024-12-13 at 08 04 20 AM](https://github.com/user-attachments/assets/b765ae4b-f197-466d-b564-761bfee769a1)

**Comment by mike2307** [comment]
> What transitions are you referring to?

I'm talking about the transition/motion, which occurs when an object is clicked.
It appears like some kind of dialog with a fade-in phase. At the same time the background around it is being blurred.

In my case it's a firefox, running inside a fedora VM, hosted on a Windows 10 host system. With this setup, firefox tries to software render that transition/fading/blurring, which causes quite some stutter and lag. It's not very smooth at all.

Of course one could try out everything possible, to optimize the setup to take full advantage of every possible hardware acceleration. But that's probably a limitation of the GPU driver for the virtual graphics adapter in the VM.

That's why I suggested to offer an option to disable this eye-candy like actions.

In my case it's purely for performance reasons when running in a very limited environment. But maybe other users prefer to have something similar too just for the sake of simplicity and snappiness. :smile:

**Comment by mike2307** [comment]
Would be nice if it could get reopened :+1:

**Comment by mike2307** [comment]
Hmm... Alright.
I'll do a bit of research to figure out if a browser extension could alter these effects in the background.
In case I find a viable solution I'll post it here for any future requests in this direction.
