### ISSUE TITLE
Recordings link disappears if Recordings is toggled off [0.9.0 beta 2]

### ISSUE THREAD

**Issue by lawm** [blakeblackshear/frigate#1551]
**Describe the bug**
Click "Toggle recordings off"
Refresh
"RECORDINGS" link disappears. 

I expected it to still be available, so that I can view old recordings.

**Version of frigate**
Output from `/api/version`
0.9.0-3340952

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/3174101/129982743-3fe1f47c-1e43-4df7-ae77-81c858840d97.png)
2. Refresh
3.
![image](https://user-images.githubusercontent.com/3174101/129982749-026978cb-01f6-4dbc-82c1-d6ced736702a.png)

**Comment by blakeblackshear** [comment]
@hunterjm thoughts on this?

**Comment by ozett** [comment]
i observed this int beta2 with only 1 out of 4 cams. 
i thought it was more my mistake in the frigate.yml, but i did not found any.
your issue proofs my observation.. but i cannot add more userful info than this.

**Comment by hunterjm** [comment]
The frontend is checking the config to see if recordings are enabled for a camera before showing the button to view the recordings page. Mostly to prevent showing a broken link/page for cameras that do not have any recordings. We could remove that logic to always show the recordings button though if you'd like.
