### ISSUE TITLE
Disable coral/detection - plain NVR

### ISSUE THREAD

**Issue by Bonn93** [blakeblackshear/frigate#1552]
Amazing project, however getting my hands on any coral devices seems difficult right now, all seem out of stock, hard to get in Australia, etc etc. 

I'd like to continue my setup and just record plain camera feeds, is there a way I can turn off detection/object detection entirely?

**Comment by blakeblackshear** [comment]
See the detect section in the full example here: https://blakeblackshear.github.io/frigate/configuration/cameras#full-example

Just set enabled to false.

**Comment by Bonn93** [comment]
Too easy! Thanks!
