### ISSUE TITLE
Use relative paths for web assets

### ISSUE THREAD

**Issue by jrivard** [blakeblackshear/frigate#15544]
**Describe what you are trying to accomplish and why in non technical terms**
While attempting to use frigate behind a path-rewriting proxy, I noticed that js, image, and other assets are referenced using absolute url paths.  For example, frigate is at "https://127.0.0.1:8971/", and a reverse proxy (such as apache) with a proxied url of "https://www.example.com/app1".  This works except that the assets in the app use absolute path references to root such as href="/images/apple-touch-icon.png" instead of href="images/apple-touch-icon.png".

**Describe the solution you'd like**
Use relative paths instead of absolute paths (paths that start with "/").

**Describe alternatives you've considered**
Can be worked around using url-rewriters which is complex to configure and not always reliable.

**Additional context**
Thanks for the great app!

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/discussions/3996
