### ISSUE TITLE
Multiple Issues moving from Swann Cameras to Dahua (FFMPEG Process Crashes / Memory Allocation Failures / Non Monotonic DTS Errors / Detection Process Stuck and Restarted)

### ISSUE THREAD

**Issue by exnewbie3** [blakeblackshear/frigate#15562]
**Describe what you are trying to accomplish and why in non technical terms**
I was previously using Frigate with my Swann DVR and recently switched to a Dahua NVR. Since making the switch, my Frigate setup has been plagued with warnings and errors. I've spent a significant amount of time trying to troubleshoot and resolve these issues, but I’m still unable to fix most of them

**Describe the solution you'd like**
Please help me identify and resolve the errors in my code that are causing FFmpeg failures and other issue

**Describe alternatives you've considered**
I have tried moving between frigate version 0.13, 0.14 and currently on the latest beta

**Additional context**
I host Frigate as a Docker container on an Intel 12th Gen NUC i5 machine, which also runs Plex Media Server and several other Docker containers. I've attached the Frigate log file for review
[frigate-logs.txt](https://github.com/user-attachments/files/18172605/frigate-logs.txt)

**Comment by NickM-27** [comment]
You need to create a support discussion
