### ISSUE TITLE
RPI4 failed to create endpoint frigate on network bridge

### ISSUE THREAD

**Issue by dnit71** [blakeblackshear/frigate#1558]
Hello,

I tried to install frigate on a RPI4 with docker. When I run docker-compose or docker run I get this error message:

ERROR: for frigate  Cannot start service frigate: failed to create endpoint frigate on network frigate_default: failed to add the host (vethd720                          1fb) <=> sandbox (veth710b0cb) pair interfaces: operation not supported

Docker version 20.10.8, build 3967b7d
docker-compose version 1.29.2
RPI4 4Go  armv7l  Linux raspberrypi 5.10.17-v7l+

Thank you

**Comment by blakeblackshear** [comment]
If you want help with docker compose, it's a good idea to provide the compose file.

Also, I Googled you error message for you. Here is the first result: https://serverfault.com/questions/738773/docker-failed-to-add-the-pair-interfaces-operation-not-supported

**Comment by dnit71** [comment]
indeed I upgraded kernel without reboot before install docker. Thank you very much. I can't wait to try frigate.
regards,
