### ISSUE TITLE
blank web interface

### ISSUE THREAD

**Issue by dnit71** [blakeblackshear/frigate#1559]
hello,

I run Frigate via docker but when I open a browser with http://X.X.X.X:5000, I just see a blank page.

Below my hardware: 

RPI4 4GO Raspberry OS
docker  20.10.8, build 3967b7d

config.yml:

_cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://syno:ef13e7b2762c2463fd6995d19477f0b9@192.168.2.100:554/Sms=2.unicast
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5_

docker-compose.yml:

_version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-armv7
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/frigate/config.yml:/config/config.yml:ro
      - /home/pi/frigate/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"_

thank you

**Comment by blakeblackshear** [comment]
You didn't provide logs

**Comment by dnit71** [comment]
Could you tell me how to get log with docker ?

**Comment by ozett** [comment]
cmd-line: ```docker logs frigate ```

**Comment by dnit71** [comment]
docker logs frigate :

_* Starting nginx nginx
   ...done.
Error parsing config: 'mqtt'
 * Starting nginx nginx
   ...done.
Error parsing config: 'mqtt'
 * Starting nginx nginx
   ...done._

**Comment by ozett** [comment]
check your frigate.yml ?
(you did not provide it here)

check for some errors in that section?

```
mqtt:
  host: 192.168.1.5
  port: 1883
  user: user
  password:

```

**Comment by dnit71** [comment]
Where can I find frigate.yml ? I have no mqtt server immediately (no mqtt section) , is it mandatory to run frigate ?

**Comment by ozett** [comment]
https://blakeblackshear.github.io/frigate/configuration/index

![image](https://user-images.githubusercontent.com/5937811/130255698-ec59c011-dd92-4476-b3e4-d446f5033817.png)

**Comment by dnit71** [comment]
Could you be more explicit please? I add a section mqtt with host: mqtt.server.com but now I get this normal error : 

frigate.mqtt                   ERROR   : Unable to connect to MQTT server: [Errno -2] Name or service not known

but is it blocking to show the camera's stream in  the web interface ?

**Comment by blakeblackshear** [comment]
That's not a valid mqtt server as the log message indicates. An mqtt server is required.

**Comment by ozett** [comment]
yes, a valid mqtt is required, otherwise booting is blocked. ( i experienced yesterday)
maybe this could be overcome in future versions?

**Comment by dnit71** [comment]
Thank you @blakeblackshear. I installed a mqtt server and now I see the stream of my camera. Maybe you should mention it in the documentation.
