### ISSUE TITLE
Migrate helm chart

### ISSUE THREAD

**Issue by billimek** [blakeblackshear/frigate#156]
We [discussed this](https://github.com/billimek/billimek-charts/pull/249#issuecomment-645361653) in a PR for the frigate helm chart over in the [billimek-charts repo](https://github.com/billimek/billimek-charts).  I'd like to start the process to 'move' the chart over here.

Would you prefer it to be added within this repo, or a separate (dedicated?) repo?  I beleive either should work fine.  It's best (IMO) to have it within a `charts` subdirectory and there are excellent github actions for auto linting/testing (although automated testing the frigate installation is tricky at the moment) and releasing the chart.

**Comment by blakeblackshear** [comment]
If you recommend adding to a `charts` directory in this repo, that is fine. I do have some other charts I will end up creating too, so whatever you recommend based on your experience is fine.

**Comment by billimek** [comment]
The chart linting/testing/releasing automation I suggest using does create github 'releases' for each chart release.  Based on this, and that you may have additional charts, I think a dedicated charts repo (maybe `blakeblackshear/frigate`) would make more sense.

Happy to start the migration process whenever it makes the most sense for you!

**Comment by blakeblackshear** [comment]
Agreed. I will create a dedicated repo for helm charts soon.

**Comment by blakeblackshear** [comment]
I created a repo here: https://github.com/blakeblackshear/blakeshome-charts

Appreciate the assist.

**Comment by brujoand** [comment]
Maybe this could add support for exposing port 1935 also when migrating?

**Comment by blakeblackshear** [comment]
This is a bit messy at the moment. I have updated the helm chart here, but haven't moved things over. https://github.com/blakeblackshear/billimek-charts/tree/master/charts/frigate

**Comment by billimek** [comment]
It's on my list of things to do for formally migrating the frigate chart over here, sorry for the delays!

**Comment by billimek** [comment]
@blakeblackshear I'd like to take a stab at the chart migration this weekend.  The https://github.com/blakeblackshear/blakeshome-charts repo is empty and I can't fork to PR the incomgin chart.

* Do you still want to use that repo to host the chart? (I do strongly suggest leveraging a dedicated repo for chart(s) instead of co-habbing with the frigate repo so there won't be tagging confusion.
* If so, can you push something to the repo so it can be forked?
* Alternatively, if you add me as a contributor to https://github.com/blakeblackshear/blakeshome-charts I can branch directly and PR the incomnig chart and associated actions changes.

**Comment by blakeblackshear** [comment]
I pushed up a commit. Appreciate the help.

**Comment by brujoand** [comment]
@billimek I'll just close my PR on the k8s-at-home repo then and you'll add the port and volume when migrating?

**Comment by billimek** [comment]
@brujoand yes, will do!
