### ISSUE TITLE
MQTT frigate/events -> get snapshot from event in node-red ? [FR?]

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#1560]
As the mqtt-topic of /events has an [endpoint thumbnail, but not sending image-data](https://github.com/blakeblackshear/frigate/issues/820).
 version: ```DEBUG 0.8.4-5043040```

anybody here who has a working flow or a hint how to get the snapshot image from the mqtt-event?
sample by camera-name? or any other way? cannot figure this out...

![image](https://user-images.githubusercontent.com/5937811/130086863-ce90987d-da90-4c77-8fae-1d725ac7e5e4.png)

**Comment by ozett** [comment]
for the moment a general placeholder for cam-name ond object-name helps me showing the last (event?) snapshots.
a little control missing for selections...

![image](https://user-images.githubusercontent.com/5937811/130128676-b9dbd9e6-42b2-4a60-9eff-d5dc88327059.png)

**Comment by muzzak123** [comment]
@ozett I connect direct to the frigate/events topic and then decode and save images from the first zone into various folders using this flow. The Change node does all the heavy lifting and then I use a HTTP request node to get the image, and then save it with a File node It may help you to do what you want.
![image](https://user-images.githubusercontent.com/51472089/130164117-a29b36c6-cf16-4168-a501-47b50d096e2b.png)

```[{"id":"9e41f007.6d7b8","type":"mqtt in","z":"e6fe9dff.9eee8","name":"Frigate","topic":"frigate/events","qos":"2","datatype":"json","broker":"9e3c4f5a.bf88d","nl":false,"rap":false,"x":70,"y":80,"wires":[["fbcf13ed.38b29"]]},{"id":"53a54ff0.06682","type":"change","z":"e6fe9dff.9eee8","name":"Extract Data","rules":[{"t":"set","p":"eventid","pt":"msg","to":"payload.after.id","tot":"jsonata"},{"t":"set","p":"camera","pt":"msg","to":"payload.after.camera","tot":"jsonata"},{"t":"set","p":"object","pt":"msg","to":"payload.after.label","tot":"jsonata"},{"t":"set","p":"zone1","pt":"msg","to":"payload.after.entered_zones[0]","tot":"jsonata"},{"t":"set","p":"filename","pt":"msg","to":"\"/media/frigate/thumbs/\" & msg.zone1 & \"/\" & msg.object & \"/\" & msg.mydt & \"-\" & msg.camera & \"-\" & msg.eventid & \".jpg\"","tot":"jsonata"},{"t":"set","p":"url","pt":"msg","to":"\"http://localhost:5000/api/events/\" & msg.eventid & \"/thumbnail.jpg\"\t","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":470,"y":80,"wires":[["34ec3b24.71d3c4"]]},{"id":"5ef01a6e.da2454","type":"file","z":"e6fe9dff.9eee8","name":"Save Image","filename":"","appendNewline":false,"createDir":true,"overwriteFile":"true","encoding":"none","x":790,"y":80,"wires":[[]]},{"id":"fbcf13ed.38b29","type":"moment","z":"e6fe9dff.9eee8","name":"Nice Date & Time","topic":"","input":"frame_time","inputType":"msg","inTz":"Australia/Perth","adjAmount":"0","adjType":"days","adjDir":"add","format":"YYYY-MM-DD_HHmm","locale":"C","output":"mydt","outputType":"msg","outTz":"Australia/Perth","x":270,"y":80,"wires":[["53a54ff0.06682"]]},{"id":"34ec3b24.71d3c4","type":"http request","z":"e6fe9dff.9eee8","name":"","method":"GET","ret":"bin","paytoqs":"ignore","url":"","tls":"","persist":false,"proxy":"","authType":"basic","x":630,"y":80,"wires":[["5ef01a6e.da2454"]]},{"id":"9e3c4f5a.bf88d","type":"mqtt-broker","name":"SA MQTT","broker":"192.168.0.103","port":"1883","clientid":"NodeRED","usetls":false,"compatmode":false,"protocolVersion":"4","keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","birthMsg":{},"closeTopic":"","closeQos":"0","closePayload":"","closeMsg":{},"willTopic":"","willQos":"0","willPayload":"","willMsg":{},"sessionExpiry":""}]```

**Comment by ozett** [comment]
Super. i will test it.

but this still depends on http getting the photo. 
guess i would be more elegant if i could save photos from mqqt-events - like the mqtt-snapshots.

Feature Request:
It would be great if you could configure whether an event includes a photo.
So simply combine the topic / snapshot and / event.
The event topic has a lot of information, which one could easily rely on as a node-red filter.

=> make it an option for /events to include snapshots... (per camera or general)

![image](https://user-images.githubusercontent.com/5937811/130190232-94b86d28-f0f2-4c27-a8bf-2ffa1ea26275.png)

**Comment by muzzak123** [comment]
Yeah, you might want to have a look at my issue #1401. I think in some instances Frigate does not publish the correct latest image as snapshot. It's actually the image before the latest. That's why I use node-red to capture every image and use the correct image as the latest.
