### ISSUE TITLE
config.yml with user password special character

### ISSUE THREAD

**Issue by qordnjs** [blakeblackshear/frigate#15609]
I access 192.168.10.10:5000 but camera does not display.
I don't know how to type @ character in config.yml file

mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: usb
#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  FrontCam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://**@dmin:p@ssword@**192.168.4.4:554/Streaming/channels/101
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://**@dmin:p@ssword@**192.168.4.4:554/Streaming/channels/101
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 30

**Comment by mimainka** [comment]
Use the URL encoded version of @ instead:
%40

**Comment by hawkeye217** [comment]
This is not a feature request. You should open a support discussion if you are needing support.
