### ISSUE TITLE
Apple Acceleration

### ISSUE THREAD

**Issue by bazylhorsey** [blakeblackshear/frigate#15636]
**Describe what you are trying to accomplish and why in non technical terms**
I want to utilize metal and video toolbox in ffmpeg and ml models. There is some great research going on at Apple for the M-series architecture in creating high power AI with low-watt systems (Apple Intelligence is powered by a cluster of Apple desktops apperently). Texas Tech came up with a way to cluster Mac's and provide Llama 405B for all professors in a low cost and low power way. This could eventually be the high cost recommendation for frigate above the beelink, because for me I think the next step up would be like an i7+Nvidia 4060, but then you have a lot of power costs and room space to take up, keeping a small and eco-friendly form-factor, while being able to handle 100s of cameras would be an awesome benchmark. 

**Describe the solution you'd like**
It should be assumed the firmware is already installed in the OS because of apples packaging. The image should be able to leverage these. Ffmpeg commands that utilize video toolbox can be easily found online.
**Describe alternatives you've considered**
A seperate docker image could be made, but the ARM image should work fine

**Additional context**
Models should continue to work. I believe metal supports ONNX which should give us Jina, and the YOLO models that support ONNX (yolonas for instance)

**Comment by NickM-27** [comment]
MacOS docker does not support mapping devices into containers so there is no possibility for this

**Comment by NickM-27** [comment]
https://chariotsolutions.com/blog/post/apple-silicon-gpus-docker-and-ollama-pick-two/

Provides for context for the problem

**Comment by bazylhorsey** [comment]
Sent a message to Apple for review regarding APIs for gpu in virtual environments.
