### ISSUE TITLE
Sensor for the Detector CPU Usage

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#15668]
**Describe what you are trying to accomplish and why in non technical terms**
I can track the Detector CPU usage in the Frigate metrics page:

![image](https://github.com/user-attachments/assets/e53a9c9a-10d7-45f6-aae2-4fca569d844a)

It would be nice if it were exposed to Home Assistant as a sensor too.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
These are the ones currently exposed:

![image](https://github.com/user-attachments/assets/71e7dbc8-46d6-4ee3-8d71-449c5903d8ba)

**Comment by NickM-27** [comment]
The data is already available in MQTT, this is a feature request for the integration

**Comment by felipecrs** [comment]
WTH. I was pretty sure I was opening the issue in the integration repository. Sorry about that.
