### ISSUE TITLE
Rollback from ghcr.io/blakeblackshear/frigate:stable to 0.13.1-34FB1C2

### ISSUE THREAD

**Issue by bruno-dogancic** [blakeblackshear/frigate#15662]
Dear all and Merry Christmas everyone!

I have made the terrible mistake of pulling the latest docker image for Frigate while updating other things in my Portainer...

How can I go back to the version 0.13.1-34FB1C2? I cannot find where to pull it from...

Kind regards,
Bruno

**Comment by NickM-27** [comment]
This is not a feature request, create a support discussion
