### ISSUE TITLE
Intel/AMD CPU with built in AI (NPU/TPU) support

### ISSUE THREAD

**Issue by ABroodryk** [blakeblackshear/frigate#15686]
Good Afternoon,

Will frigate include support for the Intel/AMD NPU/TPU processors built into the AI cpus?

I would be great to use that instead of requiring a coral TPU or GPU accelerator. 

Thank you for concidering.
A

**Comment by NickM-27** [comment]
Yes, some users have reported it's already working for Intel. Amd will be more difficult and we'll have to see what can be supported
