### ISSUE TITLE
Feature Suggest: Default Camera for Birdseye

### ISSUE THREAD

**Issue by jameswarner62** [blakeblackshear/frigate#1568]
Upcoming Birdseye view is really great for monitoring multiple cameras live 24x7 (and I think is being considered the end fix for multi camera live monitoring). It seems a shame that with no motion/objects etc it only shows streams a logo. It would be great if you could either choose a default camera that is used in the event of no motion, or perhaps allow some config to set which cameras should appear there regardless of motion? I realise that doesn't fit everyone's use, but maybe others would also find that also useful...

**Comment by jasonpstokes** [comment]
FYI you can view the live stream of all your cameras using `mode: continuous`, so there are some other options just not to the extent you have suggested. See: https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/configuration/index.md#birdseye
