### ISSUE TITLE
0.9 Events (clips) do not work unless camera has 24x7 recording

### ISSUE THREAD

**Issue by jameswarner62** [blakeblackshear/frigate#1569]
**Describe the bug**
Potential bug in 0.9, with the new clips > events changes - it seems cameras that are not set to 24x7 record, also cannot be used for clips anymore. It's possible this is by design due to using recordings for events rather than a separate clips copy. 

**Version of frigate**
0.9.0-3340952

**Works:**
`    record:
      enabled: True
      retain_days: 2
      events:
        enabled: True
        max_seconds: 300
        post_capture: 5
        retain:
          default: 14`

**Doesn't work**
`    record:
      enabled: False
      retain_days: 2
      events:
        enabled: True
        max_seconds: 300
        post_capture: 5
        retain:
          default: 14`

**Comment by blakeblackshear** [comment]
This should be clarified in the docs. If you are not recording video from the camera, you won't have any saved video for an event regardless of what your event retention settings are. The terms "24/7 recording" and "clips" are no longer applicable in 0.9.0.

**Comment by jameswarner62** [comment]
Makes sense, I did suspect that was the case given the new approach - thanks for clarifying!

**Comment by jameswarner62** [comment]
Just a thought, if events are being sourced from the recordings - can the events be retained longer the constant recording retain? Or is it necessary now to store all footage all the time? If so, that's quite a significant change in disk space requirements from the very efficient "store only motion" possible beforehand...

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate/discussions/1502#discussioncomment-1168133

**Comment by jameswarner62** [comment]
Thanks, your reply makes sense, and is a great direction  - however for me, this statement is not working as expected:

> You can set it to retain all footage for the number of days you want and/or have a different retention setting for recorded footage that contains detected objects. 

I have 2 day recording retention and 14 day event retention. I therefore would expect 2 days of constant video, and then only segments with motion stored for a further 12 days.  What seems to happen is the entire directory is cleaned up once the 2 day retention passes, and events from 2-14days then just show an error  "The media could not be loaded, either because the server or network failed or because the format is not supported."   The entire folder structure is cleaned each hour beyond 2 days.

**Comment by jameswarner62** [comment]
Actually, I may be wrong here, my testing is only just into the rollover period, and I was changing quite a few settings back then. I've just seen a single motion event kept beyond 2 day retention (maybe retention is set on the file/db at the time, rather than evaluated based on todays setting?)
