### ISSUE TITLE
Camera Order in Camera Groups

### ISSUE THREAD

**Issue by GrahamHollis** [blakeblackshear/frigate#15701]
For each camera, when the UI: Order config is specified, the All group shows the cameras in the requested order. That works perfectly.

When creating a custom camera group, the UI: order per camera is not followed and the cameras shown in the original order. 

Is there a way to have a UI: Order in a camera group, or have the camera group follow the camera UI: Order value?

**Comment by hawkeye217** [comment]
What version of Frigate are you using?
