### ISSUE TITLE
Limit addon disk space usage

### ISSUE THREAD

**Issue by mathgim** [blakeblackshear/frigate#15723]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to limit disk space usage of Frigate addon and integration so that I can avoid situation where disk space limit is reached. Very often, I reach 1Gb only of disk space remaining so I need to delete manually folders in frigate media.

**Describe the solution you'd like**
In the frigate addon config parameter, a parameter for disk space usage in Mb for the full addon or just for the frigate media files.

**Describe alternatives you've considered**
No idea.

**Additional context**
NA

**Comment by NickM-27** [comment]
You can already limit recording retention and snapshot retention and those are the main users of storage. 

There is already a separate feature request for adding storage based retention.
