### ISSUE TITLE
[FR] - Restart Frigate from Front End

### ISSUE THREAD

**Issue by wizbowes** [blakeblackshear/frigate#1576]
It would be great to be able to restart Frigate from the front end.  Whilst very much a nice to have it would make life easier when setting up and messing with config files.  It will also help whilst other bugs are worked on where front end buttons don't work as planned to be able to reset back to the default state.

**Comment by jasonpstokes** [comment]
This is already a part of the v9 release, as seen in the betas:

![image](https://user-images.githubusercontent.com/29766924/130320412-bba98ea6-3d08-476d-8eb0-b7b9379daa38.png)
