### ISSUE TITLE
Documentation: add some info for setup of a Coral TPU ?

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#1577]
my mini PCI-e TPU arrived, i found some missing parts in the docu while installing.

for similar cases, maybe good to [add to docker-compose.yml in that docu-section ](https://blakeblackshear.github.io/frigate/installation)?
```
devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1
```

and maybe mention and Link to how to install software-support (linux./etc.)
```
https://coral.ai/docs/m2/get-started/#2a-on-linux
```
in docu [on section with the detectors](https://blakeblackshear.github.io/frigate/configuration/detectors)?

maybe also how to check like [from google-doku](https://coral.ai/docs/m2/get-started/#2a-on-linux):
```
Once rebooted, verify that the accelerator module is detected:

lspci -nn | grep 089a

lso verify that the PCIe driver is loaded:

ls /dev/apex_0
```

**Comment by paulius2k** [comment]
I also have a question: is it possible to install Coral TPU (USB) on Raspberry Pi 4, which is running the managed Home Assistant Operating System, and how?

**Comment by blakeblackshear** [comment]
@paulius2k with the USB version, you just plug it in and it works. No other steps needed.

**Comment by MrNorm** [comment]
That would be very useful as I came across this issue looking for what to pass into my Docker container.
