### ISSUE TITLE
Is there support for a cycling RTMP feed of multiple cameras?

### ISSUE THREAD

**Issue by UntouchedWagons** [blakeblackshear/frigate#1593]
I'm currently using Blue Iris as my NVR but I'm considering switching to Frigate. Blue Iris has restreaming support where if you give VLC a network stream of `http://blueiris.untouchedwagons.site/mjpg/@Index/video.mjpg` it'll cycle through all the cameras of the @Index group with each camera's view being displayed for about 3 seconds before cycling to the next camera. Does Frigate have something like this?

**Comment by blakeblackshear** [comment]
Birdseye view would be the closest thing. It would be possible to add a new mode to Birdseye that cycles between cameras instead of showing them in a grid. However, there isn't a way to view the Birdseye stream with VLC.

**Comment by ozett** [comment]
maybe as a Feature Request?

FR 1) rtsp stream of Birdseye-view ?

FR 2) [MQTT events with snapshots](https://github.com/blakeblackshear/frigate/issues/1560#issuecomment-902466547) as another way of a birdseye-view steam ?
