### ISSUE TITLE
Frigate loves feet

### ISSUE THREAD

**Issue by boehser-enkel** [blakeblackshear/frigate#1595]
Hey there,

my camera stands on the ground. A person is recognized very fast, but after a few seconds the best image updates and obviosly its the feet?
Any way to fix it?

greetz

**Comment by ozett** [comment]
try; 
https://blakeblackshear.github.io/frigate/configuration/cameras#masks--zones
https://blakeblackshear.github.io/frigate/configuration/false_positives

**Comment by boehser-enkel** [comment]
I can't make a mask because its right at my front door
Also reducing the treshold is not goot. The feet have the best percentage (thats also why they make the "best image")

**Comment by blakeblackshear** [comment]
Make a zone and use the zone best image instead.
