### ISSUE TITLE
Use inbuilt camera sensors / triggers to enable frigate monitoring

### ISSUE THREAD

**Issue by wills106** [blakeblackshear/frigate#16]
On some camera's such as HikVision cameras there are trigger states you can define in the camera such as line crossing.

It might be worth while having an option to trigger frigate on / off depending on for example when an object is detected to cross a line on the camera.
I thought this might be an advantage for users trying to run frigate on lower powered devices, so the system does not have to process every frame.

In HA I use the HikVision sensor to trigger other devices like:

- alias: Tripwire
  trigger:
    platform: state
    entity_id: binary_sensor.driveway_line_crossing
    from: 'off'
    to: 'on'

https://www.home-assistant.io/components/binary_sensor.hikvision/

**Comment by blakeblackshear** [comment]
Can't you accomplish the same thing by defining a region where one side of the region is the "line"?

**Comment by drcrimzon** [comment]
I think this is more leaving object detection off until an event triggered from HA.
A toggle for object detection could be added, and toggled via MQTT.  On motion, turns on object detection for x time, and then back off.  Reducing constant CPU/GPU/Coral load.

I'm not sure the use case for frigate over HA/tensorflow in an example like that.

**Comment by blakeblackshear** [comment]
That use case seems reasonable to me. Maybe you only want to run it when your security system is armed. Should be simple enough to add.

**Comment by jalbstmeijer** [comment]
I'd like something like this too.
In my case I use Foscam camera's.

https://community.home-assistant.io/t/foscam-motion-sound-detection-and-ir-led-status-in-ha-v2-push-method/68190

Is there already something underway to control stopping/starting detection based on mqtt messages?

**Comment by blakeblackshear** [comment]
I haven't started this one.

**Comment by mario-tux** [comment]
If a mqtt activation of the detection in frigate is added, this could be on single camera-based so one could use it to switch on-off the frigate activities on some cameras.

**Comment by frankhommers** [comment]
This would save a lot of CPU and would be awesome.

I am using a fork of https://github.com/mzac/unifi-video-mqtt for unifi protect. 
That way I got motion events/booleans on mqtt. 

It would be great to use these booleans on mqtt to start the work.

**Comment by blakeblackshear** [comment]
When frigate does the motion detection, it know _where_ the motion is and that tells it where to look for objects. The CPU usage to run motion detection is minimal on all 3 setups that I run. I would rather try and optimize frigate's implementation first if needed since it is core to the rest of frigate's functionality.

**Comment by frankhommers** [comment]
Well my CPU can't handle 7 camera's. So I now have to pick one or two to be able to do object_recognition. If it were for motion events, it'll probably work on all 7.

**Comment by blakeblackshear** [comment]
Tell me about your cameras and CPU.

**Comment by frankhommers** [comment]
I have 7 unifi protects cameras (3x G3 Pro, 4x G3 Flex). And my docker host is a Synology DS1817+.
Also there are 2 network switches in between, so that'll cost a lot of power and the whole time.

**Comment by blakeblackshear** [comment]
You should be able to do this with the new switches in RC1
