### ISSUE TITLE
Objects have same score RC1

### ISSUE THREAD

**Issue by Minglarn** [blakeblackshear/frigate#1614]
**Describe the bug**
Just updated to latest RC1, and as time passed by I noticed that objects in the event list have the same score.
Nearly all objects always has a score of 76.95% and even moving cars have the same score...
Scrolling through the event list I see older events (created before RC1) and they all have the same score. 
So this "bug" could have been introduced in earlier versions. To bad I closed the MQTT explorer yesterday so I cant compare older MQTT events for score ratings. 

**Version of frigate**
0.9.0-4efc584

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
No need upon requested.
```

**Frigate container logs**
```
Include relevant log output here
```

**Frigate stats**
```json
{"detection_fps":0.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":11.26,"pid":216},"coral2":{"detection_start":0.0,"inference_speed":10.98,"pid":218}},"frigate_baksida":{"camera_fps":4.1,"capture_pid":281,"detection_fps":0.0,"pid":247,"process_fps":4.1,"skipped_fps":0.0},"frigate_entren":{"camera_fps":4.1,"capture_pid":267,"detection_fps":0.0,"pid":230,"process_fps":4.1,"skipped_fps":0.0},"frigate_inne_garage":{"camera_fps":4.1,"capture_pid":285,"detection_fps":0.0,"pid":262,"process_fps":4.0,"skipped_fps":0.0},"frigate_parkering":{"camera_fps":4.1,"capture_pid":263,"detection_fps":0.0,"pid":227,"process_fps":4.1,"skipped_fps":0.0},"frigate_pathway":{"camera_fps":4.1,"capture_pid":277,"detection_fps":0.0,"pid":239,"process_fps":4.1,"skipped_fps":0.0},"frigate_pryttelverkstad":{"camera_fps":4.0,"capture_pid":268,"detection_fps":0.0,"pid":233,"process_fps":4.0,"skipped_fps":0.0},"frigate_tomten":{"camera_fps":4.0,"capture_pid":273,"detection_fps":0.0,"pid":237,"process_fps":4.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":6399.8,"mount_type":"tmpfs","total":6442.5,"used":42.7},"/media/frigate/clips":{"free":64965.5,"mount_type":"ext3","total":125488.4,"used":54121.1},"/media/frigate/recordings":{"free":64965.5,"mount_type":"ext3","total":125488.4,"used":54121.1},"/tmp/cache":{"free":42085.1,"mount_type":"overlay","total":58275.8,"used":13199.9}},"uptime":1774,"version":"0.9.0-4efc584"}}t
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/58695742/131029815-22ec3dbd-932a-48b0-a254-e8ab7bcb47a9.png)

**Computer Hardware**
 - OS: Ubuntu 20.04.2 LTS
 - Install method: Docker
 - Virtualization: None
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Reolinks / Foscams / HikVision
 - Model: N/A
 - Resolution: N/A
 - FPS: 4

**Additional context**

**Comment by blakeblackshear** [comment]
I have reverted to the previous MobileDet model from 0.8.4. This one doesn't seem quite right.

**Comment by Minglarn** [comment]
Updated to RC-2 ... Now we have different scores again.. 👍
