### ISSUE TITLE
0.9-RC1 - Birdseye view shows up even if disabled

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#1627]
**Describe the bug**
Disabled Birdseyeview still shows up in the GUI and projects a white screen.

**Version of frigate**
0.9-RC1

**Config file**
```yaml
birdseye:
  enabled: False
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26795429/131153864-95d5a8e9-a004-4d2c-b2c5-3224c54cbcee.png)

**Comment by MrAnonymous722** [comment]
I wonder if this relates to my issue #1582
The only difference I can get out of the birdseye config is changing it to continuous. Otherwise it is always there and always reacts to any motion.

**Comment by lukedukeus** [comment]
I'm on 0.9.0, and still having this issue, I have:
`
birdseye:
  enabled: False
`
in the root of my yaml. @tubalainen or @Sinamics , can you post your full config that resolved this issue?

**Comment by tubalainen** [comment]
> I'm on 0.9.0, and still having this issue, I have:
> `birdseye: enabled: False`
> in the root of my yaml. @tubalainen or @Sinamics , can you post your full config that resolved this issue?

It's a bug / to be implemented. It's not resolved.
If I am not mistaken there is already a PR. So hopefully it will be resolved in RC3.

**Comment by Sinamics** [comment]
This will be fixed in RC3.

**Comment by tubalainen** [comment]
Resolved in RC3 - with this PR: https://github.com/blakeblackshear/frigate/commit/b8df419badcde5a137c76bf71be958ada4e5abb3
