### ISSUE TITLE
[feature request] minor changes to support active mobile notifications of events

### ISSUE THREAD

**Issue by mario-tux** [blakeblackshear/frigate#163]
Thank you very much to @blakeblackshear for this great project. I was trying to arrange some kind of notification of events coming from Frigate in HA with proper snapshots and video. The new PR https://github.com/blakeblackshear/frigate/pull/161 looks fit well but few minor changes are necessary. 

First let me explain my idea: when an event starts (a designed object enters the camera view) I would receive an early notification on my mobile phone (I'm using HA Companion app on Android) with a screenshot of the object; if Frigate gets better recognition of the object (higher rate than the previous) I would get an update of the notification with the new screenshot (the notification can be replaced using the same id). Finally, when the event ends (the object goes out the scene), the notification should be updated with the best screenshot (probably already there) and a link to the video generated by Frigate.

The necessary support by Frigate is almost in the upcoming  PR and few minor adjustment would be essential to get the goal:
- in order to update the previous notification with better/more information, a unique id of the event is required; I can see an `id` field in the mqtt message structure; @blakeblackshear can you confirm that this is unique and stable for whole tracking of the object?
- when, during the tracking, Frigate gets a better screenshot of the object (higher rate) a further mqtt event would be necessary ('update' event?); this would permits to send a notification when a better image is available;
- I need a way to get the image related to the start/update/end events: the best would be to save it in the cache or clips folder of Frigate; the notification of HA requires a public URL of the images and videos; I could expose to the web the folder to pass the URL of the image; it could be passed in the json structure of the mqtt message (base64?) but I think this add more workload to  both Frigate and HA; to do this I need the filename of the screenshots and final video in the messages structure;
- if I expose the clips folder to the web, for privacy reasons, it is necessary that the name of the files to be unpredictable: an optional random token included in the name of the videos and images stored would be great.

I think this should be enough to make the 'active notifications' work: with this kind of support by Frigate the corresponding automation in HA should be quite simple and it could be included in the README of Frigate to show how powerful it can be. @blakeblackshear let me know what do you this about this idea.

**Comment by mario-tux** [comment]
Oh, I forgot an important point: it would be nice to be able to configure the length of the preamble and closure of the videos. I think the former is actually fixed to 30 seconds. I understand that this PR was optimized to harvest videos of the false positives but a minor changes would make it a more general and powerful feature of Frigate.

**Comment by blakeblackshear** [comment]
> in order to update the previous notification with better/more information, a unique id of the event is required; I can see an id field in the mqtt message structure; @blakeblackshear can you confirm that this is unique and stable for whole tracking of the object?

It is supposed to be. Sometimes frigate will lose track of an object and one will disappear and a new one will be generated. In that case you would get a second id for the same object.

> when, during the tracking, Frigate gets a better screenshot of the object (higher rate) a further mqtt event would be necessary ('update' event?); this would permits to send a notification when a better image is available;

It used to work this way. I can look at adding it back.

> I need a way to get the image related to the start/update/end events: the best would be to save it in the cache or clips folder of Frigate; the notification of HA requires a public URL of the images and videos; I could expose to the web the folder to pass the URL of the image; it could be passed in the json structure of the mqtt message (base64?) but I think this add more workload to both Frigate and HA; to do this I need the filename of the screenshots and final video in the messages structure

The filename is `{camera_name}-{frame_time}-{object_index}.mp4`

> if I expose the clips folder to the web, for privacy reasons, it is necessary that the name of the files to be unpredictable: an optional random token included in the name of the videos and images stored would be great.

The frame_time has the timestamp down to the microsecond, so it is already fairly obfuscated and difficult to guess. There are a million possible values each second. I will think about an efficient way to do this.

> it would be nice to be able to configure the length of the preamble and closure of the videos. I think the former is actually fixed to 30 seconds

Simple enough

**Comment by mario-tux** [comment]
@blakeblackshear Thanks for the commits related to this PR and for the whole project. I'm testing the 0.6rc1 pre-release: it looks to work well for me. I'm tuning my notification system on the new event-based structure of mqtt messages of frigate.

Few notes/suggestions:
- it looks that when frigate gets a better image (with higher score), it sends a mqtt message on topic `frigate/camera-name/label/snapshot`; in the new event-based structure this is not so useful as I can't logically link this new information to the `id` provided by the start/end mqtt messages; it would be nice to get, on higher score and better snapshot, another new event like `frigate/camera-name/events/update`;
- when a start event is fired, in order to get the image that triggered it, I actually get the snapshot at URL `.../camera-name/latest.jpg`; it is usually fine; I also did some tests on the image provided by mqtt topic `frigate/camera-name/person/snapshot` with very pour and out-of-sync images; it would be great if frigate would save in the `clips` folder a JPG snapshot of the best snapshot;
- I read that frigate considers as "gone" a subject when it disappears for more than, I remember something like, 10 frames; it looks not strictly related to the wall-clock time as one can use different fps rates; it could be also useful to let one to configure this parameter in order to "merge" sequences of movements of the same subject.

**Comment by blakeblackshear** [comment]
Let me think through the best way to accomplish notifications as you described in the original post above. Seems like you are jumping through a bunch of hoops to patch something together.
