### ISSUE TITLE
Posible to batch detect motion in video?

### ISSUE THREAD

**Issue by dig91** [blakeblackshear/frigate#1638]
**Describe the bug**
I have about 50 files recorded from an older NVR.  They are all parsable via ffmpeg.  Is there a way to configure frigate to parse those vidoes and create events from them?

Thanks!

**Comment by blakeblackshear** [comment]
It's definitely possible. I use a static mp4 file for testing. You just have to adjust the ffmpeg parameters so it reads from your files.
