### ISSUE TITLE
Handle offline cameras

### ISSUE THREAD

**Issue by srirams** [blakeblackshear/frigate#164]
I'm using frigate to monitor some remote cameras which are sometimes offline (due to network issues). When I start frigate with an offline camera, it errors out and none of the cameras work.

`
    ffprobe -v panic -show_error -show_streams -of json "rtsp://admin:Q94dwd@camera-road-west.akkarai:554/profile2"    
    {'error': {'code': -5, 'string': 'Input/output error'}}  
    Traceback (most recent call last): 
      File "detect_objects.py", line 361, in <module>
        main()
  File "detect_objects.py", line 204, in main
    frame_shape = get_frame_shape(ffmpeg_input)
  File "/opt/frigate/frigate/video.py", line 39, in get_frame_shape
    video_info = [s for s in info['streams'] if s['codec_type'] == 'video'][0]
KeyError: 'streams'`

**Comment by jamescarlos** [comment]
I'm not sure it will help, but maybe use an RTSP proxy like live555: https://hub.docker.com/r/migoller/live555proxyserverdocker

I connect all my RTSP cameras to this, then other services connect to this proxy server.

**Comment by srirams** [comment]
Thanks! I was actually looking for something like this so I could split the stream for recording as well as frigate. Will have to see how well the proxy handles offline situations, but so far so good.

**Comment by mattheys** [comment]
Live555 is only x86, for people using Arm you can try https://github.com/aler9/rtsp-simple-server 

Again, I'm not sure it will help if the stream is offline or not as it just proxies the raw stream to multiple clients.

**Comment by blakeblackshear** [comment]
Frigate should keep trying to connect until the camera comes back online in 0.8.0.
