### ISSUE TITLE
[Request] Increase recording length above 60 seconds as record flag

### ISSUE THREAD

**Issue by Joshndroid** [blakeblackshear/frigate#1643]
First off, awesome software!

**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

I would like to be able to increase the recording length from 60 seconds to something lets say up to 10 minutes
This would be beneficial for 24/7 recording operations in that you don't end up with a million small clips.

**Describe the solution you'd like**

This could be set as a flag within the record setting such that for most users with object detection, etc they are unaffected. However for users enjoying the 24/7 recording ability we can increase the clip length

**Describe alternatives you've considered**

**Additional context**

**Comment by blakeblackshear** [comment]
You can do this already as described here: https://github.com/blakeblackshear/frigate/issues/1183

Though keep in mind I strongly recommend against changing the defaults. Release 0.9.0 will switch to 10s segments and has a new recordings UI. Increasing the segment size will prevent frigate from properly managing retention for events. The updated integration also let's you view an entire hour of footage in home assistant. There isn't really a need to mess with the way frigate stores video.

**Comment by solarsparq** [comment]
> You can do this already as described here: #1183
> 
> Though keep in mind I strongly recommend against changing the defaults. Release 0.9.0 will switch to 10s segments and has a new recordings UI. Increasing the segment size will prevent frigate from properly managing retention for events. The updated integration also let's you view an entire hour of footage in home assistant. There isn't really a need to mess with the way frigate stores video.

Thank you for clarifying this.  I see why the use of 10-second segments.  While it startles some niche users, it is perfectly fine for the rest of us.  Many people are used to nice, large MP4 files.

Thank you for all your work.
