### ISSUE TITLE
Installing the integration beta: config not found

### ISSUE THREAD

**Issue by herostrat** [blakeblackshear/frigate#1644]
**Describe the bug**
New installation from home assistant in kvm. Installed mqtt broker and friagte beta rc2

**Version of frigate**
cannot run `/api/version`

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
no config found
```

**Frigate container logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Error parsing config: [Errno 2] No such file or directory: '/config/frigate.yml'
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/32066572/131244827-847c97b8-56b6-4b1a-a737-9a8bbbcfefbb.png)

**Computer Hardware**
 - OS: manjaro + kvm
 - Install method: Addon
 - Virtualization: kvm
 - Coral Version: USB
 - Network Setup: wifi

**Camera Info:**
no cam

**Additional context**

**Comment by jasonpstokes** [comment]
Have you followed the instructions in the integration and created a `frigate.yml` config file with your camera settings, etc, in your Home Assistant config folder? (Wen using the HA Supervisor Addon, the config has to be in the same folder as your Home Assistant `configuration.yaml`, `automations.yaml`, etc.)

**Comment by herostrat** [comment]
You are right, I thought one only needs to create the config if not installed via addon manager.
Thanks for the help!

**Comment by jasonpstokes** [comment]
No worries, as you're trying the beta - make sure you [refer to the beta docs ](https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/configuration/cameras.md), as there have been some changes.
