### ISSUE TITLE
Date/time overlay very large

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#1647]
Any idea why the date and time overlay on snapshots are so large? Can they be configured? This wasn't there in the previous versions... it started with 2.0.0.

![Screenshot_20210829-172724_Home Assistant](https://user-images.githubusercontent.com/30929896/131258857-c8950787-edc6-4b52-b1ce-114acbbc7eea.jpg)

**Comment by quenthal** [comment]
Check here : https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/configuration/cameras.md

**Comment by asemev** [comment]
Thanks yes i saw this and read carefully already, but there is no setting to change the font size of the timestamps. There is just true/false to turn it on or off.... Or did i miss it?

**Comment by ozett** [comment]
may use the scale-factor for sizing?
https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/configuration/cameras.md#timestamp-style-configuration

**Comment by asemev** [comment]
Oh wow cool thank you so much! I totally missed it. 

i tried it now but i keep geeting this error:

Error parsing config: 1 validation error for FrigateConfig
cameras -> Package -> timestamp_style
  none is not an allowed value (type=type_error.none.not_allowed)
[cmd] python3 exited 1

i just copy pasted the config there.
Removing the "effect: None" didnt help. it keeps giving the sae error message.

'''yaml

# Optional: in-feed timestamp style configuration
timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  # Optional: Scale factor for font (default: shown below)
  scale: 1.0
  # Optional: Line thickness of font (default: shown below)
  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: None
'''

**Comment by asemev** [comment]
ah wait i saw i had copy paste errors with indents...
now i get different errors. lol

Error parsing config: 3 validation errors for FrigateConfig
cameras -> Package -> timestamp_style -> color -> red
  ensure this value is less than or equal to 0 (type=value_error.number.not_le; limit_value=0)
cameras -> Package -> timestamp_style -> color -> green
  ensure this value is less than or equal to 0 (type=value_error.number.not_le; limit_value=0)
cameras -> Package -> timestamp_style -> color -> blue
  ensure this value is less than or equal to 0 (type=value_error.number.not_le; limit_value=0)
[cmd] python3 exited 1

**Comment by asemev** [comment]
ok now removed all the color entries and it works.. will play around with the scale factor now.

thanks again!!!

**Comment by asemev** [comment]
works perfectly now. Thank you so much kind sir!
