### ISSUE TITLE
Camera input fails with special "#" character in password

### ISSUE THREAD

**Issue by hwinkel** [blakeblackshear/frigate#1649]
**password with # breaks the input**
After hours of debugging i found that stream passwords which contain a "#" will break the input with
Error messages like:
```
frigate.video                  INFO    : mauer_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : mauer_cam: ffmpeg process is not running. exiting capture thread...
```

This leads to a green screen cam view.

**Version of frigate**
0.8.4-5043040`

**Please Note**
I'm pretty sure this is related to FFmpeg or another library and not frigate self. However for all user like to have "#" special character in the stream passwords it might save you some hours. FYI: I have not checked other special characters!

**Comment by hwinkel** [comment]
HI, If you can't or won't fix it upstream, may you can add a hint in the FAQ?

**Comment by ehn** [comment]
Passwords containing a question mark (?) also trigger this.
