### ISSUE TITLE
Please do not start docker "privileged"

### ISSUE THREAD

**Issue by Ka-Mau** [blakeblackshear/frigate#165]
That is not a good idea, because your image can directly access the host hard disk.
Try
docker run --rm --device=/dev/bus/usb:/dev/bus/usb --network host --shm-size=512m -v /etc/frigate:/config:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -e FRIGATE_RTSP_PASSWORD='xxx'  blakeblackshear/frigate:stable

Use --device=/dev/bus/usb:/dev/bus/usb instead of -v /dev/bus/usb:/dev/bus/usb, add --network host and remove privileged.
Important: You can not use -v /dev/bus/usb:/dev/bus/usb and --device=/dev/bus/usb:/dev/bus/usb together.

Thank you.
KM

**Comment by blakeblackshear** [comment]
Totally agree, but in my experience, it is necessary. The problem is that the path for the coral under /dev/bus/usb periodically changes and it is no longer picked up without privileged mode. Maybe newer versions of the coral libraries and/or docker have changed something.

**Comment by blakeblackshear** [comment]
Why would you want network mode set to host?

**Comment by Ka-Mau** [comment]
I don't know docker very well, sorry. There is definitely a better solution for the network.
After what time can the changes to the path be expected? I start frigate as I wrote and would then check the frame rate at http: // ...: 5000 / debug / stats. Or how does the problem show up?
Thank you

**Comment by Parlane** [comment]
I use the m.2. pcie coral device. I can not simply forward a usb /dev device to the docker container, I tried to find out the access path but I was unable to. So in my case privilage is definitely required on the docker container sadly.

**Comment by stoffus** [comment]
I'm using a Coral USB accelerator, and by specifying `/dev/bus/usb:/dev/bus/usb` under the `devices` section I'm no longer forced to run the container in privileged mode (using Docker 19.03.12).
