### ISSUE TITLE
Birdseye Camera Roles

### ISSUE THREAD

**Issue by hankanman** [blakeblackshear/frigate#1651]
**Describe what you are trying to accomplish and why in non technical terms**
I have 5 cameras but one of them I only use for detection and would rather have the 4 "proper" cameras only in the Birdseye view

**Describe the solution you'd like**
Can we have a role for cameras that are included in Birdseye

**Comment by mplinuxgeek** [comment]
+1
I have 2 cameras that are web cams from a mariner and harbor near my home that I do object detection on to capture snapshots of boats, but I'd like to exclude these from the Birdseye view.

**Comment by NickM-27** [comment]
This is included in 0.11 (currently in beta), birdseye can be disabled on a per-camera basis
