### ISSUE TITLE
BirdsEye Camera Order

### ISSUE THREAD

**Issue by therealcarnivor** [blakeblackshear/frigate#1683]
Loving Frigate and the pace of development!!!! lets get that bit out the way :)

I like to be able to make the order of cameras in the Birdseye view static so that I can get familiar with the layout.

I find you get used to where each camera is but i've noticed they tend to change upon restart.

Maybe a config section to define the camera order, or a new stub in each camera to define its position of order.

I don't think it needs to be as complex as Cam_A: top left, etc, just 0/1/2/3/... , so when read, positions left to right, top to bottom are in the sequence defined.

thanks

**Comment by mr6880** [comment]
In fact, a general sort order for the cameras would also be very useful. So like cameras with different names can be grouped together on the left bar while viewing a camera, and also when viewing the cameras dashboard.

At present, they appear to be in alphabetical order, so I've been trying to achieve this by naming my 16 cameras in a way that makes them sort into a logical order, based on their location.

Reckon it's worth a separate feature suggestion?

**Comment by karldonteljames** [comment]
This would be a really useful enhancement, even more so if we could define the number of columns/rows.
Thanks.

**Comment by FizzedInMyPantz** [comment]
I also would love an ability to define camera order in birdseye. Is it a feasible enhancement? My use case is viewing my 4 home camera feeds in continuous mode as a quick view of the house in a home assistant lovelace card, and it would make quick viewing way easier not having to reorient myself to the various cameras' positions.

Thanks for all you do!

**Comment by grug0r** [comment]
Would love this feature also.
