### ISSUE TITLE
[feature request] clips published on an mqtt topic when object is detected at the event end

### ISSUE THREAD

**Issue by rubenfiszel** [blakeblackshear/frigate#169]
Let me preface this by saying that I absolutely love this project. I am able to run a single 3k camera at 1 fps on rpi4b for person detection with ease. I ditched my nest setup in favor of a normal rtsp camera thanks to it. I have integrated it with homeassistant to get a telegram notification as the README suggested. Now there is only one feature request that I would like to suggest and this is somewhat aligned with #161.

The feature request itself:

Inspired by thhe way we publish snapshot images on an mqtt topic
```
### frigate/<camera_name>/<object_name>/snapshot
Publishes a jpeg encoded frame of the detected object type. When the object is no longer detected, the highest confidence image is published or the original image
is published again.
```

I would like to suggest this new mqtt topic and logic:
```
### frigate/<camera_name>/<object_name>/clip
Publishes a clip as a file encoded straight from the camera stream of the frames between an event start and event end with the `object_name` of that label at the time of the event end.
```

This could be used by the homeassistant's telegram notification to send video clips (that can be previewed) directly.

**Comment by bdruth** [comment]
Seconding this, but with a maybe even simpler place to start ... can we at least publish a message when the clip has been created? It's not instantaneous, so for folks with integrations responding to MQTT messages, there's some delay needed before the clip file can be referenced.
