### ISSUE TITLE
Implement metrics, health per camera

### ISSUE THREAD

**Issue by Alfiegerner** [blakeblackshear/frigate#1699]
**Describe what you are trying to accomplish and why in non technical terms**
 
In general something like publishing Prometheus style metrics to get health and measures of app and cameras.

I have a camera that becomes unresponsive very occasionally.  Frigate appears to 'hold' or replay the last frames it recieved. Having metrics available would hopefully allow remediating actions to be automated.

**Describe the solution you'd like**

A set of Prometheus metric for app measures, including per camera stats, e.g. processed video for last minute.

**Describe alternatives you've considered**

ffprobe could be used for camera health, an integrated metric publishing would help understand what's happening at the end consumer, the frigate app 

**Additional context**

**Comment by blakeblackshear** [comment]
Have you looked at the stats api endpoint and mqtt topic?

**Comment by Alfiegerner** [comment]
Thanks I'd missed those. I was thinking something along those lines with a metric that would help us determine camera 'health', e.g. frames processed in last minute.

**Comment by blakeblackshear** [comment]
The fps numbers are a rolling average. Several others use those to detect camera issues.

**Comment by Alfiegerner** [comment]
Oh great! Thanks very much, I'll look at those.
