### ISSUE TITLE
Frigate no longer sees the coral device

### ISSUE THREAD

**Issue by valantur** [blakeblackshear/frigate#171]
I notice something strange with the coral device on my system.
The usb stick sometimes shows up as

```
"Bus 002 Device 010: ID 1a6e:089a Global Unichip Corp." 
and some other times as 
"Bus 002 Device 009: ID 18d1:9302 Google Inc.". 
```

Of course the device # changes every time I reboot the system or plug back in the coral device, but why is it that it changes vendor and product id # ?

I made two UDEV rules to create a stable symlink (and the symlink creation works), but Frigate doesn't seem to detect neither the real device nor the symlink:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="1a6e", ATTRS{idProduct}=="089a", SYMLINK+="coralusbstick"
SUBSYSTEM=="usb", ATTRS{idVendor}=="18d1", ATTRS{idProduct}=="9302", SYMLINK+="coralusbstick"
```

Can anyone point me in the right direction? Can an option to manually select the coral device path be added to Frigate?

Thanks!

**Comment by valantur** [comment]
Moreover, it seems like the act of running Frigate is what changes the device vendor and product id.
I found more info in the interweb:

https://stackoverflow.com/questions/56632485/coral-google-edge-tpu-usb-accelerator-not-recognized-virtualbox-workaround

> However, it is listed as 18d1:9302 Google Inc. only AFTER classify_image.py has been successfully run. No idea why.

>

**Comment by blakeblackshear** [comment]
I was never able to get a UDEV rule to work with the Coral. The changing device # is why I had to map `/dev/bus/usb` as a volume and run with `privileged`. There is no way to manually select the coral device path programmatically as far as I know.

**Comment by valantur** [comment]
> I was never able to get a UDEV rule to work with the Coral. The changing device # is why I had to map `/dev/bus/usb` as a volume and run with `privileged`. There is no way to manually select the coral device path programmatically as far as I know.

Ah now it all makes sense. I was also reading #165 and it's related to this. Anywho, I'm closing the issue since it's a known "quirk". Thanks for getting back to me so quickly.
