### ISSUE TITLE
The REAL question for Blake

### ISSUE THREAD

**Issue by ragenhe** [blakeblackshear/frigate#1716]
Blake,

I see your located in Nashville.  I used to live in Nashville and then Murfreesboro, I now live in Lexington KY.

Are you a UT fan or Vandy fan?  LOL

**Comment by blakeblackshear** [comment]
Ha! I actually went to Texas A&M. I do have a few siblings that went to UT, and I will happily cheer for the _real_ UT over that ridiculous joke of a school based in Austin.

**Comment by ragenhe** [comment]
Yes!! Go VOLS!!!
