### ISSUE TITLE
Mask does not seem to apply and score not correct on overlay

### ISSUE THREAD

**Issue by jhallenb** [blakeblackshear/frigate#1717]
1 below is the actual bug? 2 and 3 are some questions that I would be very happy to get some input on.

1. 
I see some problems with the following found "person"....
First of all it is not a person but my grill, that is picked up as a **person with 70% score**, which I find to be surprisingly bad for a tensorflow network. But also in the **picture overlay it says 55%** score not 70%.

**Picture with overlay**
https://drive.google.com/file/d/1YMr4CHu0aNpBiAYT_qGG_XFLOTi4RsAU/view?usp=sharing

**Score information**
https://drive.google.com/file/d/1blH5JK3ZWcogsPwL-pMIhSgQVW2xw5eH/view?usp=sharing

Even more strange is, the **grill area is masked** out in Frigate, so nothing should really be found there at all...but still the grill was found?

**Image with mask**
https://drive.google.com/file/d/1gp4yInOy-jtNqxp6SI19rTLsFhB10kvp/view?usp=sharing

What is going on here, is it a (known )bug?

2. 
A second question (not bug just if someone has some good input).
In general, I pick up birds and even a paper bag as person with higher score than for real persons.
Any idea what I could do to filter out those and improve the result. If one enable to classify "bird", the birds are found both as person and bird. It does not seem like the category with highest score is only reported, rather all categories above the threshold (even for the same location in the image) are reported.
Could that be changed? 

I have specified 10000 as min area for persons. To see people walk by most far away from the camera I can't increase it much more. Maybe to 15000 but above that I would stop to register real people in the image.

**Some references of wrong classifications**
https://drive.google.com/file/d/1nRrgjj-OHWqSZuK9qzXTtGEyrLVKrlnl/view?usp=sharing

https://drive.google.com/file/d/1MnCcHm-hUw1b7BRdptXnhH-Zy0Dqk48K/view?usp=sharing
https://drive.google.com/file/d/1Vc5HFAZovVhkAswB1VlID7NoESqcvIg5/view?usp=sharing

3. I sometimes get artefacts for some seconds in the image. See picture below.
Not sure if it is the camera or Frigate causing these. Any known ffmpeg setting that  could possibly improve this?
Wrong classification seems to be more common when these artefacts are present (not sure why it is just a subjective registration)

See this image
https://drive.google.com/file/d/1YMr4CHu0aNpBiAYT_qGG_XFLOTi4RsAU/view?usp=sharing

Frigate is really the best alternative. Great work!
I hope to get my setup slightly more stable just, filtering out wrong classifications.  
It is most likely just some lack of settings that I have missed, any help would be very welcome.

**Comment by blakeblackshear** [comment]
1. The event is 6 seconds long. At 5 frames per second, that is 30 images. One of those images had a score of 70%. The image is not necessarily the highest scoring frame. Motion masks do not alter the image sent to object detection, so they do not prevent objects from being detected. They only prevent motion from triggering object detection to be performed. You may need an object mask over the bottom of your grill. Please read the documentation on masks. 
2. I would look at using zones with min_area set to more finely control what size a person can be. Note that zone filters only prevent a zone from being triggered. They do not prevent the object from being detected. You will need to use required_zones on clips and snapshots to prevent unwanted objects from resulting in an event.
3. You did not provide any of the requested information for support in the issue template.
