### ISSUE TITLE
ffmpeg input_opts should not specify frame rate for MJPEG cameras

### ISSUE THREAD

**Issue by tve** [blakeblackshear/frigate#1725]
**Describe the bug**

The documentation for MJPEG cameras in `cameras.md` states one should include the following ffmpeg option in the `input_args`:
```
  - -r
  - "3" # <---- adjust depending on your desired frame rate from the mjpeg image
 ```
I have a bunch of esp32-cams that produce a variable mjpeg frame rate and specifying `-r` makes a mess of the recordings (frigate 0.8 and 0.9). Specifically, the `-r` seems to tell ffmpeg "trust me, the frame rate from the camera is _N_ " and then ffmpeg counts the frames accordingly. The result is that each recording snippet is actually longer or shorter than it claims to be, depending on the actual frame rate delivered by the camera.

For example, I specified `-r 4` but the camera delivered fewer than 4 fps and as a result, while each recording segment contained the correct number of frames for the segment time @4fps, those frames actually stretched over a longer time-period. The tell-tale sign was that the filesystem timestamp and the filename of the segment files were spaced further apart that they should have. Removing the -r option on the input_opts fixes the issue.

If one runs ffmpeg manually with the segment options one can watch the progress and it will show "dup=N" when the input frame rate from the camera is too low for the `-r` option specified in the `output_args > record` and it will show "drop=N' when the input frame rate is higher.

**Version of frigate**
0.9 beta

**Comment by anubisg1** [comment]
If you remove the option, do you see any improvement ?

**Comment by tve** [comment]
Hmmm, maybe I wasn't clear enough: yes, dropping the -r from the input_args solves the issue.

**Comment by blakeblackshear** [comment]
Is this a rtsp mjpeg feed? I added this because ffmpeg was requesting frames from the mjpeg camera as fast as possible and generating a tremendous load on them. Telling ffmpeg to only pull frames at a specific frame rate solved that issue for others.

**Comment by tve** [comment]
I'm not sure I understand your reply. This is mjpeg over http, e.g., using something like `http://esp32-cam6.voneicken.com:81` as `-i` option in ffmpeg. With mjpeg over http the sender transmits one frame after the other with MIME encapsulation. The receiver doesn't send anything about frame rate nor does it request a frame at a time. The only thing that will throttle the frame rate is if the receiver stops reading and thus buffers fill up and back-pressure results. From what I've seen ffmpeg doesn't really do that if you provide a `-r` option, it will drop frames instead and continue reading at full speed.

If the `-r` helps in certain situations, then perhaps that should be explained and not be documented as "standard"?

**Comment by blakeblackshear** [comment]
Seems reasonable. I don't remember the specific situation where this helped someone.
