### ISSUE TITLE
Birdseye tap/click to full screen per camera

### ISSUE THREAD

**Issue by mr6880** [blakeblackshear/frigate#1735]
I've started playing with RC1 & RC2 and the new features are fantastic. With Birdseye, which is an amazing addition to Frigate, I'd like to suggest a tap/click to full screen feature.

At present, when Birdseye is full screen, users are locked into a grid view based on their config. With objects/motion selected, the camera feed may disappear before the user wishes to stop viewing, and with continuous selected, the camera feed of interest to the user may be too small if multiple cameras are available.

It could be useful to be able to tap/click a camera feed to display it full screen, which could switch back to Birdseye view when the screen is tapped/clicked again.

**Comment by mabed-fr** [comment]
I just tested in 0.13 it seems to be OK?

**Comment by NickM-27** [comment]
@mabed-fr what do you mean?
