### ISSUE TITLE
Record/clips retention - auto remove oldest when drive is full

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#1767]
**Describe what you are trying to accomplish and why in non technical terms**
That Frigate doesn't crash if the drive gets full.

**Describe the solution you'd like**
Auto retention, not only based on "days" but on space left of the drive. Just like all other NVR-style software's do.
We need also to cater for, and consider clips accordingly.

**Describe alternatives you've considered**
- Buy a larger disk
- Get a enterprise SAN
- Set one day less recording retention (but still have 100 GB free)

**Comment by ozett** [comment]
👍

**Comment by lawm** [comment]
#994

**Comment by tubalainen** [comment]
AWwwhm! Dang it - duplicate. Thanks @lawm .
