### ISSUE TITLE
Unable to access multiple frigate instances video URL through HA

### ISSUE THREAD

**Issue by weitheng** [blakeblackshear/frigate#1769]
I have 2 frigate instances running on a raspberry pi 4 and on a Jetson Nano, and another raspberry pi is running HA. I have followed the [documentation](https://blakeblackshear.github.io/frigate/usage/home-assistant#api-urls) on how to access the video urls when there are multiple frigate instances running, however, I am getting a `401 Unauthorised` whenever I try to access it. Setting an automation to send the video clip to telegram using this url also results in my IP getting banned, as I have ip ban set up.

LOGS: `2021-09-13 10:33:53 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.1 (192.168.0.1). `

This is the url that I have `https://XXXX.duckdns.org:8123/api/frigate/frigate1/clips/Gate-{{trigger.payload_json["after"]["id"]}}.mp4`. I have tried checking the video url in media browser and it seems that url is correct, but I am missing some authentication token in the url.  Previously before adding another frigate instances into HA, I was able to access the video url using this `https://XXXX.duckdns.org:8123/api/frigate/frigate1/notifications/{{trigger.payload_json["after"]["id"]}}/Gate/clip.mp4`.

I have made sure that the `client_id` for both instances are different, `frigate1` and `frigate2`. I have also made sure that `unauthenticated notification event proxy` is enabled in the integration configuration page. 

Am I doing something wrong here or did the documentation not take into account of the authentication issues when trying to access using the url format stated?

**Comment by blakeblackshear** [comment]
Only the notifications proxy allows unauthenticated requests. https://blakeblackshear.github.io/frigate/usage/home-assistant#notifications

Your urls would look like:
```
https://HA_URL/api/frigate/<instance-id>/notifications/<event-id>/thumbnail.jpg
```

```
https://HA_URL/api/frigate/<instance-id>/notifications/<event-id>/<camera>/clip.mp4
```

**Comment by weitheng** [comment]
Got confused by the documentation on "Multiple Instances Support", but this works! Thanks :)
