### ISSUE TITLE
0.9-RC3 - If "roles" is enabled on the camera - the feature is enabled

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#1770]
**Describe what you are trying to accomplish and why in non technical terms**
```
record:
  enabled: true

```
Was removed as a global with the release of RC3. Now it needs to be enabled with every camera.
Will frigate even work if recording isn't enabled?

Would it be possible to "just enable" it if it is stated as a role in the camera instead of having to declare it twice, per camera?

**Describe the solution you'd like**
Cleaner and consistent config file.

**Describe alternatives you've considered**
Rework what´s global and what's camera specific, in general.
Or, I am all ears, there might be a caveat or a reason for this function that I have overlooked. :)

**Additional context**
Logs
```
2021-09-13T05:55:32.584507000Z [2021-09-13 07:55:32] frigate.app                    WARNING : Camera cam9_uppfart has record assigned to an input, but record is not enabled.
2021-09-13T05:55:32.584663000Z [2021-09-13 07:55:32] frigate.app                    WARNING : Camera cam1_framsidan has record assigned to an input, but record is not enabled.
2021-09-13T05:55:32.584812000Z [2021-09-13 07:55:32] frigate.app                    WARNING : Camera cam2_baksidan has record assigned to an input, but record is not enabled.
2021-09-13T05:55:32.584939000Z [2021-09-13 07:55:32] frigate.app                    WARNING : Camera cam3_framsidan has record assigned to an input, but record is not enabled.
2021-09-13T05:55:32.585032000Z [2021-09-13 07:55:32] frigate.app                    WARNING : Camera cam6_baksidan has record assigned to an input, but record is not enabled.
2021-09-13T05:55:32.585110000Z [2021-09-13 07:55:32] frigate.app                    WARNING : Camera cam10_baksidan has record assigned to an input, but record is not enabled.

```
Config example
```
cameras:
  cam9_uppfart:
    ffmpeg:
      inputs:
        - path: rtsp://ipaddr:8554/cam9_ch1
          roles:
            - detect
            - record
#            - rtmp
    detect:
      enabled: True
    record:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True
  cam3_framsidan:
    ffmpeg:
      inputs:
        - path: rtsp://ipaddr:8554/cam3_ch1
          roles:
            - detect
            - record
#            - rtmp
    detect:
      enabled: True
    record:
      enabled: True
    rtmp:
      enabled: False
    snapshots:
      enabled: True
...
...

```

**Comment by dziobson** [comment]
I can also see that the event option is also not available


Error parsing config: 1 validation error for FrigateConfig
record -> events -> enabled
  extra fields not permitted (type=value_error.extra)


record:
  enabled: True
  retain_days: 5
  events:
    enabled: True
    max_seconds: 300
    pre_capture: 5
    post_capture: 10
    required_zones: []
    retain:
      default: 30

**Comment by dziobson** [comment]
ok i found a problem
 
record:
  enabled: True
  retain_days: 5
  events:
#    enabled: True
    max_seconds: 300
    pre_capture: 5
    post_capture: 10
    required_zones: []
    retain:
      default: 30


https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/configuration/index.md#full-configuration-reference

**Comment by blakeblackshear** [comment]
@tubalainen I have record enabled globally in my config and it's working fine.

**Comment by tubalainen** [comment]
Ok, sorry, I did misread the release note there, my bad. record - events are no longer a global setting.

But for the rest? Could we just enable it by just having the "roles" stated and drop the "enabled: true" per feature?

**Comment by blakeblackshear** [comment]
The enabled setting defines the default value for that function on startup. You may assign record to a stream, but only want to enable it on demand with it disabled by default.

**Comment by tubalainen** [comment]
Well, I surrender. Looks like its just me thinking that the logic is "backwards". There must some smartness behind it that I do not see or understand.

So when I declare a role (detect, record, rtmp) per camera I also need to "enable" that function/role per camera hence its by default disabled. Ok.
