### ISSUE TITLE
Issue with Multi Cameras

### ISSUE THREAD

**Issue by rourke750** [blakeblackshear/frigate#178]
Recently just updated to the latest master, noticed that only 1 camera was doing object detection.  From looking at the debug it appears that every camera image except the first camera are frozen.

Debug stats are:
{"coral":{"detection_start":0.0,"fps":7.6,"inference_speed":22.66,"pid":22},"drive_way":{"camera_fps":5.1,"detection_fps":7.6,"ffmpeg_pid":41,"frame_info":{"detect":1597193326.081779,"process":1597193326.081779,"read":1597193326.274773},"pid":48,"process_fps":5.1,"read_start":1597193326.169762,"skipped_fps":0.0},"front_door":{"camera_fps":18.7,"detection_fps":0.0,"ffmpeg_pid":45,"frame_info":{"detect":1597193326.216895,"process":1597193326.216895,"read":1597193326.275361},"pid":49,"process_fps":18.8,"read_start":1597193326.235714,"skipped_fps":0.0},"garage":{"camera_fps":18.5,"detection_fps":0.0,"ffmpeg_pid":132,"frame_info":{"detect":1597193326.246944,"process":1597193326.246944,"read":1597193326.246944},"pid":47,"process_fps":18.5,"read_start":1597193326.260662,"skipped_fps":0.0},"plasma_store_rc":null}

detection fps for both cameras are reading zero.  I also do not have a cache folder mounted as I am not using the save clips but i do not have it specified as false or true in the config.

Thanks for making the project, it's one of my favorite that I've found!

**Comment by blakeblackshear** [comment]
Are these cameras different than the one that works? The detection_fps will be zero when no motion is detected. Also noticed that your camera fps is 18 which seems odd.

**Comment by jameswarner62** [comment]
Perhaps related to https://github.com/blakeblackshear/frigate/issues/176

**Comment by rourke750** [comment]
the two cameras that arent working are foscam c1-lite and the one that worked is a Foscam G4.  I closed the door where one of my cameras us and it didnt pick it up.

**Comment by rourke750** [comment]
Thanks @jameswarner62 was exactly related to that.  Readding the vsync flag fixed the cameras and they are no longer frozen.
