### ISSUE TITLE
Possibility to tag clips/events as "keep"

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#1787]
**Describe what you are trying to accomplish and why in non technical terms**
The retention is a very core and important thing with all NVR-style software's. I would personally love to see an option where I can tag a event/clip to be kept.

**Describe the solution you'd like**
Tag a event/clip for not being deleted as part of the retention.

**Describe alternatives you've considered**
Download and keep the clips on my Dropbox.

**Additional context**
N/A

**Comment by Minglarn** [comment]
+1 for this! Would be awesome if implemented!!

**Comment by mzman88** [comment]
Would love this as well. Maybe in addition to dropbox/drive/etc. add NextCloud integration?

**Comment by DrSpaldo** [comment]
It would be nice to have a retain button for clips

**Comment by NickM-27** [comment]
This is included in release-0.11.0 👍
