### ISSUE TITLE
Wyze Cam V3 not showing video

### ISSUE THREAD

**Issue by andiewill** [blakeblackshear/frigate#1794]
**Describe the bug**

 I got fed up waiting on wyze to do what they said they would do about implementing the RSTP for v3 and i’m still waiting.

So i decided to order a Wyze V3 and and link it with the Wyze Bridge to display the rtsp url, i went through the motions and voila it works as stated after a few permutations in my config to get it working and displaying the rtsp url …phew… 

After playing around with the configs in all sorts of different ways to get a pic in VLC etc i have it working, also in Blue iris and HA but i cant seem to get this working with Frigate.

I did first try it on a Wyze Cam v2 in Frigate to see if it works and it did with no issues, also in VLC, Blue Iris, Frigate.

Dose anyone no what the correct path is to get the video to show in frigate ? as stated i have tried a whole heap of different permutations, all i get is a green screen and i have tried different resolutions to no avail, just cant get it to show the view of the cam picture.

**Version of frigate**
Output from `/api/version`
Unraid server addon / latest.
blakeblackshear/frigate:stable-amd64

**Config file**
Include your full config file wrapped in triple back ticks.

```##frigate sample config.yml

mqtt:
  host: 192.168.1.11
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
 
detectors:
  coral:
    type: edgetpu
    device: usb
    

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
  input_args:
    - -avoid_negative_ts
    - make_zero
#    - -fflags
#    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - "5000000"
    - -use_wallclock_as_timestamps
    - "1"



 
cameras:
   front_garden_top_right:
    ffmpeg:
      inputs:
        - path: rtsp://andie:xxxxx@192.168.1.xx/live
          roles:
            - clips
            - detect
#            - rtmp
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
    width: 1920
    height: 1080
    fps: 5
    motion:
      mask:
        - 0,881,796,873,1007,1080,1920,1080,1920,0,0,0
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
#        - car
        - cat
        - dog
        - bird
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      crop: True
#      height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
#        - car
        - cat
        - dog
        - bird


#cameras:
   back_garden_kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://Andie:xxxxx@192.168.1.xxx/live
          roles:
            - clips
            - detect
#            - rtmp
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
    width: 1920
    height: 1080
    fps: 5
    motion:
      mask:
        - 1296,493,1920,547,1920,0,0,0,0,485
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
#        - car
        - cat
        - dog
        - bird
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      crop: True
#      height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
#        - car
        - cat
        - dog
        - bird


   front_garden_top_left:
    ffmpeg:
      inputs:
        - path: rtsp://Williams:xxx@192.168.1.xxx/live
          roles:
            - clips
            - detect
#            - rtmp
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
    width: 1920
    height: 1080
    fps: 5
    motion:
      mask:
        - 1483,660,313,670,0,1080,0,62,1920,72,1920,1080,1825,1080
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
#        - car
        - cat
        - dog
        - bird
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      crop: True
#      height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
#        - car
        - cat
        - dog
        - bird


##cameras:

   back_garden_top:
    ffmpeg:
      inputs:
        - path: rtsp://General:xxxxxxx@192.168.1.xx/live
          roles:
            - clips
            - detect
#            - rtmp
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
    width: 1920
    height: 1080
    fps: 5
    motion:
      mask:
        - 1307,366,1464,502,1781,500,1920,642,1666,715,1920,1080,1920,0,0,0,0,883,700,325
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
#        - car
        - cat
        - dog
        - bird
      retain:
        default: 10
        objects:
          person: 15
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
#      crop: True
#      height: 175
      retain:
        default: 10
        objects:
          person: 15
    objects:
      track:
        - person
#        - car
        - cat
        - dog
        - bird

 


   front_yard_cam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.xxx:8554/front-yard-cam
          roles:
            - clips
            - detect
            - rtmp
            - record
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
    width: 1920
    height: 1080
    fps: 5
```

**Frigate container logs**
```
Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
detector.coral INFO : Starting detection process: 42
frigate.app INFO : Camera processor started for front_garden_top_right: 45
frigate.app INFO : Camera processor started for back_garden_kitchen: 46
frigate.app INFO : Camera processor started for front_garden_top_left: 47
frigate.app INFO : Camera processor started for back_garden_top: 48
frigate.app INFO : Camera processor started for front_yard_cam: 49
frigate.edgetpu INFO : Attempting to load TPU as usb
frigate.app INFO : Capture process started for front_garden_top_right: 50
frigate.app INFO : Capture process started for back_garden_kitchen: 52
frigate.app INFO : Capture process started for front_garden_top_left: 56
frigate.app INFO : Capture process started for back_garden_top: 64
frigate.app INFO : Capture process started for front_yard_cam: 69
frigate.edgetpu INFO : TPU found
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x556ec5b52140] moov atom not found
/tmp/cache/back_garden_top-20210917123758.mp4: Invalid data found when processing input
frigate.events INFO : bad file: back_garden_top-20210917123758.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55cc76c0f140] moov atom not found
/tmp/cache/front_garden_top_left-20210917123756.mp4: Invalid data found when processing input
frigate.events INFO : bad file: front_garden_top_left-20210917123756.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55bb9d642140] moov atom not found
/tmp/cache/back_garden_kitchen-20210917123754.mp4: Invalid data found when processing input
frigate.events INFO : bad file: back_garden_kitchen-20210917123754.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x555de79d0140] moov atom not found
/tmp/cache/front_garden_top_right-20210917123754.mp4: Invalid data found when processing input
frigate.events INFO : bad file: front_garden_top_right-20210917123754.mp4
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
```

**Screenshots**

<img width="1311" alt="Screenshot 2021-09-17 at 12 48 48" src="https://user-images.githubusercontent.com/31215592/133778074-c914f9a3-9fdc-43bf-a576-51c424ec7357.png">

 - OS: Unraid
 - Install method: Addon, 
 - Virtualization: Unraid
 - Coral Version: USB
 - Network Setup: WiFi

**Camera Info:**
 - Manufacturer: Wyze Cam V3
 - Model: Wyze
 - Resolution: width: 1920
 - FPS: 5

**Comment by ragenhe** [comment]
Both my V2 and V3 are working flawlessly with the latest version of the bridge.

Here is V3's setup from frigate config.yaml

```
  Mia-cam:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 720
    ffmpeg:
      inputs:
        - path: rtsp://wyze-bridge:8554/mia-cam
          roles:
            - record
            - rtmp
            - detect
    objects:
      track:
        - cat
    detect:
      enabled: True
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: False
    rtmp:
      enabled: True
    snapshots:
      enabled: False
```

**Comment by andiewill** [comment]
Thanks for the reply but no joy with that config, i must be on the right path as stated i can view the stream in other programs but not Frigate, its very strange.

**Comment by ragenhe** [comment]
Try removing your ffmpeg input arguments.  I have none for my cameras.

These lines.
```
  input_args:
    - -avoid_negative_ts
    - make_zero
#    - -fflags
#    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - "5000000"
    - -use_wallclock_as_timestamps
    - "1"
```

**Comment by andiewill** [comment]
No joy i'm afraid.........but that was worth a try as i did not really know what they were all for and i don't think they are needed due to the Wyze V2 still has video / picture.

**Comment by ragenhe** [comment]
Can you post the logs from wyze-cam?  Mine looks like this.

```
2021/09/17 13:22:55 I [0/0] rtsp-simple-server v0.17.3,
2021/09/17 13:22:55 I [0/0] [RTSP] TCP listener opened on :8554,
2021/09/17 13:22:55 I [0/0] [RTMP] listener opened on :1935,
2021/09/17 13:22:55 I [0/0] [HLS] listener opened on :8888,
2021/09/17 13:22:55 I [0/0] [API] listener opened on 127.0.0.1:9997,
,
🚀 STARTING DOCKER-WYZE-BRIDGE v0.6.6,
2021/09/17 13:22:58 [MainThread] 🔍 Could not find local cache for 'user',
2021/09/17 13:22:58 [MainThread] 🔍 Could not find local cache for 'auth',
2021/09/17 13:22:58 [MainThread] ☁️ Fetching 'auth' from the Wyze API...,
2021/09/17 13:22:59 [MainThread] 💾 Saving 'auth' to local cache...,
2021/09/17 13:22:59 [MainThread] ☁️ Fetching 'user' from the Wyze API...,
2021/09/17 13:22:59 [MainThread] 💾 Saving 'user' to local cache...,
2021/09/17 13:22:59 [MainThread] 🔍 Could not find local cache for 'cameras',
2021/09/17 13:22:59 [MainThread] ☁️ Fetching 'cameras' from the Wyze API...,
2021/09/17 13:23:00 [MainThread] 💾 Saving 'cameras' to local cache...,
2021/09/17 13:23:00 [MainThread] 💔 WVOD1 not fully supported yet,
🪄 WHITELIST MODE ON,
,
🎬 STARTING 2 OF 3 CAMERAS,
2021/09/17 13:23:02 [Garage] 🎉 Starting 1080p 120kb/s Stream for WyzeCam V3 in "LAN mode" FW: 4.36.2.5 IP: 10.121.242.24 WiFi: 96%,
2021/09/17 13:23:02 [Garage] WARNING: Lost frame,
2021/09/17 13:23:02 [Mia-cam] 🎉 Starting 1080p 120kb/s Stream for WyzeCam V2 in "LAN mode" FW: 4.9.6.241 IP: 10.121.242.176 WiFi: 95%,
2021/09/17 13:23:06 [Mia-cam] WARNING: Received incomplete frame,
2021/09/17 13:23:08 [Mia-cam] WARNING: Lost frame,
2021/09/17 13:23:08 I [0/0] [RTSP] [conn 127.0.0.1:60642] opened,
2021/09/17 13:23:08 I [0/0] [RTSP] [session 735248175] opened by 127.0.0.1:60642,
2021/09/17 13:23:08 I [0/0] [path mia-cam] created,
2021/09/17 13:23:08 I [1/0] [RTSP] [session 735248175] is publishing to path 'mia-cam', 1 track with TCP,
2021/09/17 13:23:09 I [1/0] [RTSP] [conn 127.0.0.1:60644] opened,
2021/09/17 13:23:09 I [1/0] [RTSP] [session 352606095] opened by 127.0.0.1:60644,
2021/09/17 13:23:09 I [1/0] [path garage] created,
2021/09/17 13:23:09 I [2/0] [RTSP] [session 352606095] is publishing to path 'garage', 1 track with TCP,
2021/09/17 13:23:27 I [2/0] [RTSP] [conn 10.121.243.9:44672] opened,
2021/09/17 13:23:27 I [2/0] [RTSP] [conn 10.121.243.9:44674] opened,
2021/09/17 13:23:27 I [2/0] [RTSP] [session 649373155] opened by 10.121.243.9:44672,
2021/09/17 13:23:27 I [2/0] [RTSP] [session 521074116] opened by 10.121.243.9:44674,
2021/09/17 13:23:27 I [2/1] [RTSP] [session 521074116] is reading from path 'mia-cam', 1 track with TCP,
2021/09/17 13:23:27 I [2/2] [RTSP] [session 649373155] is reading from path 'garage', 1 track with TCP,
2021/09/17 13:31:19 I [2/2] [RTSP] [conn 10.121.243.9:44674] closed,
2021/09/17 13:31:19 I [2/1] [RTSP] [session 521074116] closed,
2021/09/17 13:31:19 I [2/1] [RTSP] [conn 10.121.243.9:44672] closed,
2021/09/17 13:31:19 I [2/0] [RTSP] [session 649373155] closed,
2021/09/17 13:31:25 I [2/0] [RTSP] [conn 10.121.243.9:45744] opened,
2021/09/17 13:31:25 I [2/0] [RTSP] [session 525361336] opened by 10.121.243.9:45744,
2021/09/17 13:31:25 I [2/1] [RTSP] [session 525361336] is reading from path 'mia-cam', 1 track with TCP,
2021/09/17 13:31:25 I [2/1] [RTSP] [conn 10.121.243.9:45748] opened,
2021/09/17 13:31:25 I [2/1] [RTSP] [session 220099027] opened by 10.121.243.9:45748,
2021/09/17 13:31:25 I [2/2] [RTSP] [session 220099027] is reading from path 'garage', 1 track with TCP
```

**Comment by andiewill** [comment]
**Wyze Bridge Logs**

![image](https://user-images.githubusercontent.com/31215592/133820803-73d3d6da-d25d-4246-a28d-e88bf6a83691.png)

**Comment by ragenhe** [comment]
That log looks like it is missing a "starting....." entry for one of your cams.

Maybe open an issue on the wyze-bridge github if you haven't already.

**Comment by andiewill** [comment]
Will do and thanks for you help, just one more thing are you using docker compose for wyze bridge, and if yes could you post your docker compose config please, and just to say i can access the stream in BI, VLC etc with no issues, it's just Frigate that will not show the video.

**Comment by ragenhe** [comment]
I am.  And yes.  See below. One more question. Are you starting the frigate container after the bridge?

```
  wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    container_name: wyze-bridge
    restart: always
    ports:
      - 1936:1935 <-- the host port here has been changed to work in my environment.
      - 8554:8554
      - 8888:8888
    environment:
      - WYZE_EMAIL=<redacted>
      - WYZE_PASSWORD=<redacted>
      - LAN_ONLY=True
      - FILTER_MODELS=V3,V2
    networks:
      - intproxy
```

**Comment by ragenhe** [comment]
Try with these lines removed from the front yard cam.  They can move to global, once, not for each cam.
```
          hwaccel_args:
            - -hwaccel
            - qsv
            - -qsv_device
            - /dev/dri/renderD128
```

**Comment by andiewill** [comment]
Once again no joy, i even removed the ffmpeg global from the settings to no avail, and your compose file is the same format as mine except for the networks line, that throws a error when i tried to use that so i left that line out.

Are you starting the frigate container after the bridge? i have tried it before and after and back again, with the amount of restarts i have had to do with each container, i had to make sure all containers was having a fresh start.

**Comment by ragenhe** [comment]
Yes, _after_ the bridge is when I start frigate.  I'm at a loss.  Sorry.

**Comment by blakeblackshear** [comment]
Try updating the global args for the cameras that arent working to
```yaml
global_args: -hide_banner -loglevel info
```

That should spit out more verbose output from ffmpeg when the process exits.

**Comment by andiewill** [comment]
Not sure if i did it correct but the logs are below from Frigate which still makes no sense to me, i even updated the firmware on one cam and it stopped working with the Wyze Bridge, so i had to revert back to the working version for the Wyze Bridge, i am going to disconnect the docker containers and try the HA addon's to see if that will make a difference.



Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
detector.coral INFO : Starting detection process: 42
frigate.app INFO : Camera processor started for front_garden_top_right: 45
frigate.app INFO : Camera processor started for back_garden_kitchen: 48
frigate.app INFO : Camera processor started for front_garden_top_left: 50
frigate.app INFO : Camera processor started for back_garden_top: 51
frigate.app INFO : Camera processor started for front_yard_cam: 52
frigate.app INFO : Capture process started for front_garden_top_right: 53
frigate.app INFO : Capture process started for back_garden_kitchen: 56
frigate.app INFO : Capture process started for front_garden_top_left: 60
frigate.app INFO : Capture process started for back_garden_top: 65
frigate.app INFO : Capture process started for front_yard_cam: 70
frigate.edgetpu INFO : Attempting to load TPU as usb
frigate.edgetpu INFO : TPU found
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55821cc72140] moov atom not found
/tmp/cache/front_garden_top_right-20210918122643.mp4: Invalid data found when processing input
frigate.events INFO : bad file: front_garden_top_right-20210918122643.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5573b3459140] moov atom not found
/tmp/cache/back_garden_kitchen-20210918122643.mp4: Invalid data found when processing input
frigate.events INFO : bad file: back_garden_kitchen-20210918122643.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559e173dd140] moov atom not found
/tmp/cache/back_garden_top-20210918122643.mp4: Invalid data found when processing input
frigate.events INFO : bad file: back_garden_top-20210918122643.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55a7c91d7140] moov atom not found
/tmp/cache/front_garden_top_left-20210918122638.mp4: Invalid data found when processing input
frigate.events INFO : bad file: front_garden_top_left-20210918122638.mp4
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...
frigate.video INFO : front_yard_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video INFO : front_yard_cam: ffmpeg process is not running. exiting capture thread...

**Comment by blakeblackshear** [comment]
Try removing all roles except detect from your input to see if that works.

**Comment by andiewill** [comment]
I loaded the Frigate add-on into HA and added the frigate.yml in the config and notice the cameras name idents were incorrect by one space, i rectified that and started the add-on and all seemed fine, it found the two cameras for testing and one was the Wyze cam v3 with no errors in the log.

i then loaded the HA integration for frigate and it picked up all the cameras, and i could see it pulling the video and mqtt info, i then transferred the config to Frigate Unraid docker to see if that would off fixed it to no avail ? i'm not sure why that is but i have got a little bit further in my findings. 

Working with the HA frigate integration but not in docker / Unraid.

**Comment by blakeblackshear** [comment]
Sounds like a networking related issue where docker/Unraid are unable to access the address of the camera.

**Comment by andiewill** [comment]
Thats what i was sort of thinking, but for now i'll tinker with HA version and maybe try the docker compose version and some point, but for now i can set up a few detection zones to go on with.

But thanks everyone for your time and help.

**Comment by mitchross** [comment]
@andiewill I have docker wyze bridge, v3 camera, unraid, docker, frigate all working flawlessly. Only part I don't use is HA.

I just use the frigate native UI in docker on unraid. 

Let me know if you need me to send you configs or something.

**Comment by andiewill** [comment]
@mitchross That would be great if you could share your configs, like i stated i have it working in home assistant Frigate HA add on with the V2 and V3s using Wireguard in Portainer docker compose, but when i try it with the Unraid Frigate app i can't pull in the v3, are you running Wireguard in Portainer and Frigate from the community apps ?

**Comment by mitchross** [comment]
> @mitchross That would be great if you could share your configs, like i stated i have it working in home assistant Frigate HA add on with the V2 and V3s using Wireguard in Portainer docker compose, but when i try it with the Unraid Frigate app i can't pull in the v3, are you running Wireguard in Portainer and Frigate from the community apps ?

Frigate config
```
living-room:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.9:8554/living-room

          roles:
            - detect
            - record
    # Optional: Live stream configuration for WebUI
    live:
      # Optional: Set the height of the live stream. (default: 720)
      # This must be less than or equal to the height of the detect stream. Lower resolutions
      # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
      height: 1080

      # Optional: Set the encode quality of the live stream (default: shown below)
      # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
      quality: 1
    snapshots:
      bounding_box: true
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
      retain_days: 15
    objects:
      track:
       - person
       - car
       - dog
       - cat
```
Unraid Wyze Bridge
![image](https://user-images.githubusercontent.com/6330506/134177977-c49e158a-52e1-42b6-979f-744ea3656826.png)

![image](https://user-images.githubusercontent.com/6330506/134178327-f5416ccc-02c4-4a95-9050-b34141dd60bb.png)

**Comment by mitchross** [comment]
> I'm going to try this later on when back home, also is your wireguard in Portainer or stand alone ?

I don't use wiregaurd or portainer. I use ngninx reverse proxy to access frigate over the web. Secured with Authelia.

All my docker containers run in native unraid docker UI.

**Comment by andiewill** [comment]
Sorry i made a mistake there opps, what i meant was about the wyze bridge, so that is run in the docker ui, i must admit im just getting started with unraid so i not sure how you do that, do you have a step how to install the wyze bridge in the native unraid docker UI, the one i have is run in portainer and i think thats causing my issue, i could not the wyze bridge in the apps store which is why i used portainer as a substitute.

**Comment by mitchross** [comment]
> Sorry i made a mistake there opps, what i meant was about the wyze bridge, so that is run in the docker ui, i must admit im just getting started with unraid so i not sure how you do that, do you have a step how to install the wyze bridge in the native unraid docker UI, the one i have is run in portainer and i think thats causing my issue, i could not use the wyze bridge in the apps store which is why i used portainer as a substitute.

Hit Add Container
![image](https://user-images.githubusercontent.com/6330506/134197107-aca2792b-dbbf-4d3a-be93-86b83394c1d8.png)

![image](https://user-images.githubusercontent.com/6330506/134197362-f5ccfab1-d9eb-4c75-b429-31da59e7ad54.png)
![image](https://user-images.githubusercontent.com/6330506/134197460-3b08bb1f-b50a-4827-bfa3-929e893343e3.png)


To add these properties hit

![image](https://user-images.githubusercontent.com/6330506/134197786-cf36751e-2df7-4601-ab41-56a166f3089d.png)

Make sure to select the right type 
![image](https://user-images.githubusercontent.com/6330506/134197834-098e7ac9-c9bd-4a82-8371-eddab88876e7.png)

**Comment by andiewill** [comment]
Think im getting there and decided to get on with it while i can to try it out, and i remember trying this a while back on something else, the only other issue is how do i insert lan, password, email ?

**Comment by mitchross** [comment]
@andiewill  
![image](https://user-images.githubusercontent.com/6330506/134204167-47db2fd2-bb7a-4963-b529-442853754a40.png)

**Comment by andiewill** [comment]
Nice one got the docker running and i will try this all again the see if i can get it to work with this wyze docker later on and keep you updated............thanks once again.
