### ISSUE TITLE
Detection Issue - Animals

### ISSUE THREAD

**Issue by sudheeshb** [blakeblackshear/frigate#1800]
I have installed Frigate v1.14 directly inside home assistant in  dell machine.  I have also coral USB also connected. Four cameras are installed and all working fine.  Detection works fine for 'person'.

How ever I have issues with detecting 'Cat',  It works only some times.   Some time , frigate accurately detect the presence of a cat, and some it failed to detect even though I can see cat is moving in front of the camera.

Camera used is AMCrest , 2688x1520p bullet camera.  Connection done via POE.  Detection done using sub stream.  Is there any config parameter which I can tweak to make the detection better for cats?  Any help is appreciated.

Config file below.
back_yard:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://user:password@192.168.5.13:554/cam/realmonitor?channel=1&subtype=01
          roles:
            - detect
        - path: rtsp://user:password@192.168.5.13:554/cam/realmonitor?channel=1&subtype=00
          roles:
            - clips
            - rtmp
    objects:
      track:
        - cat
      filters:
       cat:
         min_area: 5000
         max_area: 100000
         min_score: 0.5
         threshold: 0.7
    width: 640
    height: 480
    fps: 5
    detect:
      enabled: True
      max_disappeared: 15
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
      # Optional: Objects to save clips for. (default: all tracked objects)
      objects:
        - cat
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15
    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      enabled: true
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: true
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: true
      # Optional: crop the snapshot (default: shown below)
      crop: False
      retain:
        # Required: Default retention days (default: shown below)
        default: 10
        # Optional: Per object retention days
        objects:
          person: 15

**Comment by trythatagain** [comment]
When you say 'sub stream' do you mean the lower resolution stream? If so, when I tried detection I found the 300*300px was to large, ie a cat  for example was bigger than the 300*300 area. I find with my Amcrest's on both Frigate and Shinobi I have to use the Hi-res stream.

**Comment by sudheeshb** [comment]
Thanks for the input.
Yeah.   The  'sub stream from the camera is 640x480 as indicated in the frigate.yml file.  The person detection (  bigger than cat ) always works in the sub stream.    I noticed that we can see same content in sub stream and main stream, only difference is sub stream is of lower resolution/quality.  I also tried by removing min_area and max_area.

I can try this, if you are sure hat this definitely made a difference  I didn't do it till  now as it consumes lots of CPU.

**Comment by trythatagain** [comment]
That's what I found when checking for foxes.
You could grab a frame of the low-res feed and the draw a 300*300 box and compare to a frame with a cat in it. Then do the same with a hi-res frame and you'll be surprised at the difference.

**Comment by sudheeshb** [comment]
Thanks for the suggestion.  Will try that.

**Comment by sudheeshb** [comment]
I just tried that. 300x300 covers a much larger area in a 640x480 feed ( hence chances of catching the cat is higher ) than a high resolution image ( 2304 x 1296 ) as expected.   Hence I am bit confused with your statement.   The chances of cat being bigger than 300x300 pixels is much higher in the high resolution feed.

**Comment by trythatagain** [comment]
Fair enough, all I can say is that when I use the low-res stream, the detections are not as good as when using the hi-res stream. 
I'm sure there was another thread on here that went into more detail. 
But I'm not on my PC so can't check, it's to fiddly by phone. 
I'll try searching tomorrow and post the link in here

**Comment by sudheeshb** [comment]
Thanks.  Appreciate if you can provide the link.  I saw only this link, where it says that cat detection is not reliable even on day time.  https://github.com/blakeblackshear/frigate/issues/1511

**Comment by trythatagain** [comment]
I'm not sure if this was what I thought I'd read, I'm sure I read a better answer either here in Frigate or Shinobi discussions. But someone else agrees with me about switching streams.
I'll keep looking for the answer I'm sure I read, and post it here if I find it.

[#1090](https://github.com/blakeblackshear/frigate/discussions/1090)

**Comment by trythatagain** [comment]
Right I think I've found the discussion I was thinking about. It looks as though it's a compromise. Still a nice thread.

[#1189](https://github.com/blakeblackshear/frigate/discussions/1189)

**Comment by sudheeshb** [comment]
OK.  Thanks.  I am now using 'main stream' for detection.  Let us see how it goes.

**Comment by trythatagain** [comment]
Not sure if this is of any use to you now, but just started to read the new docs for version 9 and there is a page within Camera setup that may help [here]https://docs.frigate.video/guides/camera_setup). It does say 'Larger resolutions do improve performance if the objects are very small in the frame.'
Cheers

**Comment by sudheeshb** [comment]
Thanks for the update/
