### ISSUE TITLE
0.9 RC4 - snapshot resize

### ISSUE THREAD

**Issue by alexdelprete** [blakeblackshear/frigate#1810]
I'm trying to implement face recognition for my doorbell with Double Take. My doorbell has a 1536*2048 resolution, it's working fine with Frigate since 2 years.

Now, I needed to pass a full height snapshot to Double Take because of the face box size that was under minimum requirements with a height of 512. So I configured the camera section of frigate with this:

```
    # Optional: Configuration for the jpg snapshots published via API
    snapshots:
      enabled: True
      clean_copy: False
      timestamp: False
      bounding_box: True
      crop: False
      height: 2048
      retain:
        default: 5 

    # Optional: Configuration for the jpg snapshots published via MQTT
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: False
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: False
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: shown below)
      height: 2048
      # Optional: jpeg encode quality (default: shown below)
      quality: 80
```

The problem is that the MQTT snapshot is correct, with a height of 2048, the snapshot is always an image with a 500 height.

I also tried modifying crop: to true, but it didn't solve the problem. I'll stick with MQTT for now, but I wanted to know if it's a bug or not.

Thanks.

**Comment by alexdelprete** [comment]
Sorry, I don't think it's a Frigate bug, I was checking the height of the snapshot processed by Double Take and noticed it was always 512. Then after opening the issue, I checked under the clips folder, and found out that the images wrote there are indeed 2048 in height. Are those the actual ones passed via API to apps like Double Take?

Another question: the latest.jpg image is also processed by Double Take, is there a way to configure the height for that one too?

Thanks.

**Comment by blakeblackshear** [comment]
https://blakeblackshear.github.io/frigate/usage/api#apicamera_namelatestjpgh300

**Comment by alexdelprete** [comment]
> https://blakeblackshear.github.io/frigate/usage/api#apicamera_namelatestjpgh300

Thank you. I'll check with Double Take dev how the API is called.
