### ISSUE TITLE
beta rc4-0.9.0-A943AC1: more events than on recoding GUI

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#1815]
**Describe the bug**
There are more events listed on the event-view,
than on the new recordings GUI. see screenhshot

**Version of frigate**
DEBUG 0.9.0-A943AC1

**Screenshots**
![image](https://user-images.githubusercontent.com/5937811/134128358-ea05898a-4715-4bec-8271-c21023aaba17.png)

**Additional context**
as it is RC4 that different count/bug (?) could be known by the dev (?).

but for me the events/clips still not clear defined against each other. 
but the clips should get dropped for "video-events " against "always(?) fulltime (?)-recordings" ?

atm i assume that on the right side on the recordings-gui per camera the "events" are the same "events" as fully listed on the left side "event" selection. But there is a countable difference... bug or feature?

**Comment by blakeblackshear** [comment]
This is by design. The recordings view groups overlapping events up differently for the timeline view.
