### ISSUE TITLE
Error parsing config: extra keys not allowed @ data['camera']

### ISSUE THREAD

**Issue by Aezak22** [blakeblackshear/frigate#1825]
> camera:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pswd@10.0.10.10:554/
          roles:
            - detect
    width: 1280
    height: 720
    fps: 5

**Comment by joeShuff** [comment]
It's `cameras` not `camera`. That should do it.

**Comment by ozett** [comment]
https://github.com/blakeblackshear/frigate/blob/v0.9.0-rc4/docs/docs/configuration/cameras.md

**Comment by Aezak22** [comment]
thanks
