### ISSUE TITLE
ffmpeg not working

### ISSUE THREAD

**Issue by CooperSma** [blakeblackshear/frigate#184]
I am trying to see the live feed and all I see is a black screen, I checked the logs and got this error message.
`side: ffmpeg didnt return a frame. something is wrong.
side: ffmpeg process is not running. exiting capture thread...`
How could I fix this?

**Comment by reesericci** [comment]
Same issue @blakeblackshear ^^

**Comment by blakeblackshear** [comment]
Turn on logging for ffmpeg by overriding the global_args on your camera and setting the log level to `info`:
```yaml
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
```

**Comment by CooperSma** [comment]
Ok, 

![image](https://user-images.githubusercontent.com/46323207/90393917-46091b80-e057-11ea-8c21-1964f80e3a43.png)

**Comment by CooperSma** [comment]
Ideas? @blakeblackshear

**Comment by blakeblackshear** [comment]
That doesn't look right. Please post your full config.

**Comment by CooperSma** [comment]
`web_port: 5000

mqtt:
  host: 192.168.128.138
  topic_prefix: frigate
  # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
  user: mqtt # Optional
  #################
  ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  ##   password: '{FRIGATE_MQTT_PASSWORD}'
  #################
  password: ilovemqtt # Optional

#################
# Default ffmpeg args. Optional and can be overwritten per camera.
# Should work with most RTSP cameras that send h264 video
# Built from the properties below with:
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
#################
ffmpeg:
   global_args:
     - hide_banner
     - loglevel
     - info
   hwaccel_args: []
   input_args:
     - -avoid_negative_ts
     - make_zero
     - -fflags
     - nobuffer
     - -flags
     - low_delay
     - -strict
     - experimental
     - -fflags
     - +genpts+discardcorrupt
     - -vsync
     - drop
     - -rtsp_transport
     - tcp
     - -stimeout
     - '5000000'
     - -use_wallclock_as_timestamps
     - '1'
   output_args:
     - -f
     - rawvideo
     - -pix_fmt
     - rgb24

####################
# Global object configuration. Applies to all cameras
# unless overridden at the camera levels.
# Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
# All labels from the model are reported over MQTT. These values are used to filter out false positives.
# min_area (optional): minimum width*height of the bounding box for the detected person
# max_area (optional): maximum width*height of the bounding box for the detected person
# threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
####################
objects:
  track:
    - person
    - car
    - truck
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.8

#zones:
#  #################
#  # Name of the zone
#  ################
#  front_steps:
#    front_door:
#      ####################
#      # For each camera, a list of x,y coordinates to define the polygon of the zone. The top 
#      # left corner is 0,0. Can also be a comma separated string of all x,y coordinates combined.
#      # The same zone can exist across multiple cameras if they have overlapping FOVs.
#      # An object is determined to be in the zone based on whether or not the bottom center
#      # of it's bounding box is within the polygon. The polygon must have at least 3 points.
#      # Coordinates can be generated at https://www.image-map.net/
#      ####################
#      coordinates:
#        - 545,1077
#        - 747,939
#        - 788,805
#      ################
#      # Zone level object filters. These are applied in addition to the global and camera filters
#      # and should be more restrictive than the global and camera filters. The global and camera
#      # filters are applied upstream.
#      ################
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          threshold: 0.8
#  driveway:
#    front_door:
#      coordinates: 545,1077,747,939,788,805
#  yard:

cameras:
  side:
    ffmpeg:
    
      input: rtsp://admin:<mypassword>@<ip>/cam/realmonitor?channel=01&subtype=0
    
      # height: 1080
      # width: 1920

    take_frame: 1

  
    save_clips:
      enabled: False
 
      pre_capture: 30

    snapshots:
      show_timestamp: True
      draw_zones: False

    
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.8

`

**Comment by CooperSma** [comment]
```web_port: 5000

mqtt:
  host: 192.168.128.138
  topic_prefix: frigate
  # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
  user: mqtt # Optional
  #################
  ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  ##   password: '{FRIGATE_MQTT_PASSWORD}'
  #################
  password: ilovemqtt # Optional

#################
# Default ffmpeg args. Optional and can be overwritten per camera.
# Should work with most RTSP cameras that send h264 video
# Built from the properties below with:
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
#################
ffmpeg:
   global_args:
     - hide_banner
     - loglevel
     - info
   hwaccel_args: []
   input_args:
     - -avoid_negative_ts
     - make_zero
     - -fflags
     - nobuffer
     - -flags
     - low_delay
     - -strict
     - experimental
     - -fflags
     - +genpts+discardcorrupt
     - -vsync
     - drop
     - -rtsp_transport
     - tcp
     - -stimeout
     - '5000000'
     - -use_wallclock_as_timestamps
     - '1'
   output_args:
     - -f
     - rawvideo
     - -pix_fmt
     - rgb24

####################
# Global object configuration. Applies to all cameras
# unless overridden at the camera levels.
# Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
# All labels from the model are reported over MQTT. These values are used to filter out false positives.
# min_area (optional): minimum width*height of the bounding box for the detected person
# max_area (optional): maximum width*height of the bounding box for the detected person
# threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
####################
objects:
  track:
    - person
    - car
    - truck
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.8

#zones:
#  #################
#  # Name of the zone
#  ################
#  front_steps:
#    front_door:
#      ####################
#      # For each camera, a list of x,y coordinates to define the polygon of the zone. The top 
#      # left corner is 0,0. Can also be a comma separated string of all x,y coordinates combined.
#      # The same zone can exist across multiple cameras if they have overlapping FOVs.
#      # An object is determined to be in the zone based on whether or not the bottom center
#      # of it's bounding box is within the polygon. The polygon must have at least 3 points.
#      # Coordinates can be generated at https://www.image-map.net/
#      ####################
#      coordinates:
#        - 545,1077
#        - 747,939
#        - 788,805
#      ################
#      # Zone level object filters. These are applied in addition to the global and camera filters
#      # and should be more restrictive than the global and camera filters. The global and camera
#      # filters are applied upstream.
#      ################
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          threshold: 0.8
#  driveway:
#    front_door:
#      coordinates: 545,1077,747,939,788,805
#  yard:

cameras:
  side:
    ffmpeg:
    
      input: rtsp://admin:422711@192.168.128.80/cam/realmonitor?channel=01&subtype=0
    
      # height: 1080
      # width: 1920

    take_frame: 1

  
    save_clips:
      enabled: False
 
      pre_capture: 30

    snapshots:
      show_timestamp: True
      draw_zones: False

    
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.8

 ```

**Comment by CooperSma** [comment]
@blakeblackshear

**Comment by CooperSma** [comment]
'''
web_port: 5000

mqtt:
  host: 192.168.128.138
  topic_prefix: frigate
  # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
  user: mqtt # Optional
  #################
  ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  ##   password: '{FRIGATE_MQTT_PASSWORD}'
  #################
  password: ilovemqtt # Optional

#################
# Default ffmpeg args. Optional and can be overwritten per camera.
# Should work with most RTSP cameras that send h264 video
# Built from the properties below with:
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
#################
ffmpeg:
   global_args:
     - hide_banner
     - loglevel
     - info
   hwaccel_args: []
   input_args:
     - -avoid_negative_ts
     - make_zero
     - -fflags
     - nobuffer
     - -flags
     - low_delay
     - -strict
     - experimental
     - -fflags
     - +genpts+discardcorrupt
     - -vsync
     - drop
     - -rtsp_transport
     - tcp
     - -stimeout
     - '5000000'
     - -use_wallclock_as_timestamps
     - '1'
   output_args:
     - -f
     - rawvideo
     - -pix_fmt
     - rgb24

####################
# Global object configuration. Applies to all cameras
# unless overridden at the camera levels.
# Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
# All labels from the model are reported over MQTT. These values are used to filter out false positives.
# min_area (optional): minimum width*height of the bounding box for the detected person
# max_area (optional): maximum width*height of the bounding box for the detected person
# threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
####################
objects:
  track:
    - person
    - car
    - truck
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.8

#zones:
#  #################
#  # Name of the zone
#  ################
#  front_steps:
#    front_door:
#      ####################
#      # For each camera, a list of x,y coordinates to define the polygon of the zone. The top 
#      # left corner is 0,0. Can also be a comma separated string of all x,y coordinates combined.
#      # The same zone can exist across multiple cameras if they have overlapping FOVs.
#      # An object is determined to be in the zone based on whether or not the bottom center
#      # of it's bounding box is within the polygon. The polygon must have at least 3 points.
#      # Coordinates can be generated at https://www.image-map.net/
#      ####################
#      coordinates:
#        - 545,1077
#        - 747,939
#        - 788,805
#      ################
#      # Zone level object filters. These are applied in addition to the global and camera filters
#      # and should be more restrictive than the global and camera filters. The global and camera
#      # filters are applied upstream.
#      ################
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          threshold: 0.8
#  driveway:
#    front_door:
#      coordinates: 545,1077,747,939,788,805
#  yard:

cameras:
  side:
    ffmpeg:
    
      input: rtsp://admin:password@ip0/cam/realmonitor?channel=01&subtype=0
    
      # height: 1080
      # width: 1920

    take_frame: 1

  
    save_clips:
      enabled: False
 
      pre_capture: 30

    snapshots:
      show_timestamp: True
      draw_zones: False

    
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.8
'''

**Comment by blakeblackshear** [comment]
You are missing dashes in your global args. Note the `-` before `hide_banner` and `loglevel`. These are required.
```
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
```

**Comment by CooperSma** [comment]
Should I get logs?

**Comment by blakeblackshear** [comment]
Your logs should have messages from ffmpeg about why it isn't able to get your video feed once you fix the global_args.

**Comment by CooperSma** [comment]
![image](https://user-images.githubusercontent.com/46323207/90397298-486e7400-e05d-11ea-8ecc-7e429d854d68.png)
Here

**Comment by CooperSma** [comment]
it says something about hide banner

**Comment by CooperSma** [comment]
![image](https://user-images.githubusercontent.com/46323207/90397457-7ce23000-e05d-11ea-9c53-8330fdbc54f1.png)

**Comment by CooperSma** [comment]
![image](https://user-images.githubusercontent.com/46323207/90397484-89ff1f00-e05d-11ea-8875-5ce27830c972.png)

**Comment by blakeblackshear** [comment]
That's because your config is wrong. Replace it with this and try again:
```
web_port: 5000

mqtt:
  host: 192.168.128.138
  topic_prefix: frigate
  # client_id: frigate # Optional -- set to override default client id of 'frigate' if running multiple instances
  user: mqtt # Optional
  #################
  ## Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  ##   password: '{FRIGATE_MQTT_PASSWORD}'
  #################
  password: ilovemqtt # Optional

#################
# Default ffmpeg args. Optional and can be overwritten per camera.
# Should work with most RTSP cameras that send h264 video
# Built from the properties below with:
# "ffmpeg" + global_args + input_args + "-i" + input + output_args
#################
ffmpeg:
   global_args:
     - -hide_banner
     - -loglevel
     - info
   hwaccel_args: []
   input_args:
     - -avoid_negative_ts
     - make_zero
     - -fflags
     - nobuffer
     - -flags
     - low_delay
     - -strict
     - experimental
     - -fflags
     - +genpts+discardcorrupt
     - -vsync
     - drop
     - -rtsp_transport
     - tcp
     - -stimeout
     - '5000000'
     - -use_wallclock_as_timestamps
     - '1'
   output_args:
     - -f
     - rawvideo
     - -pix_fmt
     - rgb24

####################
# Global object configuration. Applies to all cameras
# unless overridden at the camera levels.
# Keys must be valid labels. By default, the model uses coco (https://dl.google.com/coral/canned_models/coco_labels.txt).
# All labels from the model are reported over MQTT. These values are used to filter out false positives.
# min_area (optional): minimum width*height of the bounding box for the detected person
# max_area (optional): maximum width*height of the bounding box for the detected person
# threshold (optional): The minimum decimal percentage (50% hit = 0.5) for the confidence from tensorflow
####################
objects:
  track:
    - person
    - car
    - truck
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.8

#zones:
#  #################
#  # Name of the zone
#  ################
#  front_steps:
#    front_door:
#      ####################
#      # For each camera, a list of x,y coordinates to define the polygon of the zone. The top 
#      # left corner is 0,0. Can also be a comma separated string of all x,y coordinates combined.
#      # The same zone can exist across multiple cameras if they have overlapping FOVs.
#      # An object is determined to be in the zone based on whether or not the bottom center
#      # of it's bounding box is within the polygon. The polygon must have at least 3 points.
#      # Coordinates can be generated at https://www.image-map.net/
#      ####################
#      coordinates:
#        - 545,1077
#        - 747,939
#        - 788,805
#      ################
#      # Zone level object filters. These are applied in addition to the global and camera filters
#      # and should be more restrictive than the global and camera filters. The global and camera
#      # filters are applied upstream.
#      ################
#      filters:
#        person:
#          min_area: 5000
#          max_area: 100000
#          threshold: 0.8
#  driveway:
#    front_door:
#      coordinates: 545,1077,747,939,788,805
#  yard:

cameras:
  side:
    ffmpeg:
    
      input: rtsp://admin:password@ip0/cam/realmonitor?channel=01&subtype=0
    
      # height: 1080
      # width: 1920

    take_frame: 1

  
    save_clips:
      enabled: False
 
      pre_capture: 30

    snapshots:
      show_timestamp: True
      draw_zones: False

    
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.8
```

**Comment by CooperSma** [comment]
It worked! but next error ... 
![image](https://user-images.githubusercontent.com/46323207/90398226-b10a2080-e05e-11ea-80ef-34bf2ac775f8.png)

**Comment by CooperSma** [comment]
@blakeblackshear

**Comment by CooperSma** [comment]
Do you know how id fix this? @blakeblackshear

**Comment by CooperSma** [comment]
I reloaded and it worked, but one more error... 
![image](https://user-images.githubusercontent.com/46323207/90402024-74412800-e064-11ea-9acf-328213a110d2.png)

**Comment by CooperSma** [comment]
I went to url and it didnt say anything

**Comment by CooperSma** [comment]
BTW im attempting to use with Home Assistant

**Comment by CooperSma** [comment]
@blakeblackshear

**Comment by blakeblackshear** [comment]
It doesn't look like you have a Coral device. Try using a lower resolution stream and/or a lower frame rate. Also, you don't need to mention me like you would on Discord. I get notified for every post on issues.

**Comment by CooperSma** [comment]
Thank You!

**Comment by CooperSma** [comment]
I cant navigate to ip actully

**Comment by CooperSma** [comment]
I changed it to 480p is that too much?

**Comment by walthowd** [comment]
Blake, bless you and  your patience.

 @CooperSma If you want to hop on the Home Assistant discord https://discord.gg/c5DvZ4e and PM @Walt_H -- I can help you with this.

**Comment by CooperSma** [comment]
Thanks, I will check with you.
