### ISSUE TITLE
Enable/disable objects to track through mqtt

### ISSUE THREAD

**Issue by marcfager** [blakeblackshear/frigate#1840]
I have a camera that monitors our driveway and front door. Due to practicalities and regulations, the camera is installed in a way where it only sees half our car when it is parked. It also notices shadows when other cars passes by on the street, even though the cars themselves are not visible. This creates motion. The motion causes Frigate to detect the stationary car.

If I mask out the motion in the area where the shadows are detected, the performance of identifying persons is reduced. Thus, this is not a preferred solution. I saw the proposal to use zones to prevent static objects from triggering. However, as the area is so small, it is not feasible to create a separate "parking zone" and zone the car drives through. There simply isn't any "drive through zone" that the camera sees. I can disable notifications for cars easily when they are not wanted, but clips and snapshots are still created, filling up the library with unwanted items.

I would love a function where I can use mqtt and/or the API to enable/disable the tracking for certain objects. In this case, I would disable "car" for this camera when our car's position is close to home. That way I still get material if a different car enters our yard while I don't get not wanted material.

Is this something that could fit into the philosophy of the project?

**Comment by tuomaz** [comment]
I would also like this feature!
