### ISSUE TITLE
Used windows PC with Nvidia card and Frigate (docker)- how I can make it Frigate work and used Nvidia card?

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#1847]
Hi
So I used a PC with Nvidia card and I want to use this PC for Frigate under docker

I already saw this option - 

blakeblackshear/frigate:stable-amd64nvidia

But How I run it after the pull? with docker-compose ? how I can be sure the Frigate used the Nvidia card?

**Comment by ozett** [comment]
start here?
https://github.com/blakeblackshear/frigate/blob/v0.9.0-rc4/docs/docs/configuration/nvdec.md

**Comment by blthlt** [comment]
It would be nice if there was a step by step guide for this..  I've been trying to get this to work on my system for a week.  The document listed above seems to be missing some information.  We have to remember not everyone is a Linux guru.

**Comment by ozett** [comment]
yeah, your right. 
i remember that it was a lot of fiddling for me too. 
i can not fully remember details, but critial was to follow the nivdia-guide for the nvidia-docker.
🤔

**Comment by spattinson** [comment]
There is a shortcut to force home assistant to use amd64nvidia ffmpeg. Install the normal amd64 frigate add-on through home assistant. If you go to /config/addons/local you should find subdirectories one is frigate on mobile now, but have a look. Find the Dockerfile and edit it, replace ${ARCH} with amd64nvidia. Uninstall frigate in home assistant, then recheck Dockerfile has not change again, reinstall frigate and home assistant should pull the correct image. I have just done this upgrading to 0.9.0 beta and it worked great. At some points home assistant overwrites Dockerfile with default one, so dont do auto upgrades, repeat the above when you want to upgrade.

**Comment by spattinson** [comment]
Here are the exact steps I took to get nvidia decoding working on amd64 debian buster:

Install Debian Buster - enable non-free, contrib, backports during install

Install Nvidia driver (maybe not necessary since CUDA installs nvidia driver)
lspci
sudo apt -y install nvidia-detect
nvidia-detect
sudo apt install nvidia-driver
sudo reboot

Install CUDA
sudo apt-get install software-properties-common
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/debian10/x86_64/ /"
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/debian10/x86_64/7fa2af80.pub
sudo add-apt-repository contrib
sudo apt-get update
sudo apt-get -y install cuda
A newer nvidia driver has been installed so...
sudo reboot

Install Docker
sudo apt-get update
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
sudo reboot

Install CUDA Docker support
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
sudo apt-get install -y nvidia-docker2
sudo systemctl restart docker
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi

Install Frigate
git clone ...
cd frigate
make  amd64nvidia_all
sudo docker run -d   --name frigate \
      	--restart=unless-stopped \
      	--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
      	--device /dev/bus/usb:/dev/bus/usb \
      	--device /dev/dri/renderD128 \
	--device /dev/vpu_service \
	--device /dev/dri/card0 \
	-v /home/scott/hassio/media:/media/frigate \
	-v /home/scott/hassio/homeassistant/frigate.yml:/config/config.yml:ro \
       	-e FRIGATE_RTSP_PASSWORD='password' \
        -e NVIDIA_VISIBLE_DEVICES=all \
        -e NVIDIA_DRIVER_CAPABILITIES=compute,utility,video \
       	-p 5000:5000 \
       	-p 1935:1935 \
        --runtime=nvidia \
	--privileged \
       	frigate

Check ffmpeg cpu use
htop

browse to 
Install Hassio
sudo apt install jq
sudo ./install.sh -d /home/scott/hassio
sudo journalctl -f

**Comment by antonbek89** [comment]
@spattinson
Hi
Thanks for the steps guide

I have question about the Nvidia docker, the Nvidia Cuda docker must to install?

I ask it because I'm install Ubuntu 20.04 on the laptop (it's the host) and I can see Nvidia driver already installed automatically
When I'm running ffmpeg I can saw all the stuff belong to Nvidia card

So I'm wonder in my situation the Cuda docker must to have?

**Comment by SeaDude** [comment]
> Here are the exact steps I took to get nvidia decoding working on amd64 debian buster:

Do you have any `hdaccel_args` set in your `config.yml` file to make this work?

**Comment by SeaDude** [comment]
hm... been working for a few hours on this one..

Looking at @spattinson 's detailed workflow...
- `nvidia-detect` says:
```
user8@system8:~$ nvidia-detect
Detected NVIDIA GPUs:
01:00.0 3D controller [0302]: NVIDIA Corporation GK104M [GeForce GTX 880M] [10de:1198] (rev a1)

Checking card:  NVIDIA Corporation GK104M [GeForce GTX 880M] (rev a1)
Your card is only supported up to the 390 legacy drivers series.
Your card is also supported by the Tesla 418 drivers series.
It is recommended to install the
    nvidia-legacy-390xx-driver
package.
```
- Unfortunately, if I install the legacy driver using 
  - `sudo apt install nvidia-legacy-390xx-driver firmware-misc-nonfree`
    - reference: https://wiki.debian.org/NvidiaGraphicsDrivers#bullseye-390
  - then `sudo reboot`, `frigate` won't start
- ERROR states: (just sec, need to reboot!)

**Comment by SeaDude** [comment]
hm... been working for a few hours on this one..

Looking at @spattinson 's detailed workflow...
- `nvidia-detect` says:
```
user8@system8:~$ nvidia-detect
Detected NVIDIA GPUs:
01:00.0 3D controller [0302]: NVIDIA Corporation GK104M [GeForce GTX 880M] [10de:1198] (rev a1)

Checking card:  NVIDIA Corporation GK104M [GeForce GTX 880M] (rev a1)
Your card is only supported up to the 390 legacy drivers series.
Your card is also supported by the Tesla 418 drivers series.
It is recommended to install the
    nvidia-legacy-390xx-driver
package.
```
- Unfortunately, if I install the 390 legacy driver using 
  - `sudo apt install nvidia-legacy-390xx-driver firmware-misc-nonfree`
    - reference: https://wiki.debian.org/NvidiaGraphicsDrivers#bullseye-390
  - then `sudo reboot`, `frigate` won't start
```
user8@system8:~/Documents/frigate$ nvidia-smi
Tue Jul  5 20:37:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.144                Driver Version: 390.144                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 880M    Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   57C    P0    N/A /  N/A |      0MiB /  4037MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```
- Frigate error states:
```
user8@system8:~/Documents/frigate$ docker-compose up -d
[+] Running 0/0
 ⠋ Container frigate  Creating                                             0.0s
Error response from daemon: Unknown runtime specified nvidia
```
- However, if I install the 470 driver:
  - `sudo apt install -t bullseye-backports nvidia-driver firmware-misc-nonfree` the `sudo reboot`

**Comment by LordNex** [comment]
Has the NVDEC been added to the aarch distro yet for use on the Jetson Nano? The docks just still say it may be in the future and references this closed ticket

**Comment by josepescobarinditex** [comment]
I'm interested too compatibility with Jetson Nano... I tryed a lot of workarrounds without success

**Comment by caublet** [comment]
Is it please possible to update tag for nvidia on dockerhub to update to 11.1 please? 

ref: https://hub.docker.com/layers/blakeblackshear/frigate/stable-amd64nvidia/images/sha256-d91dc45bbc8d80f270430668a2a8983f5b22e203c3994545c68964b7b9f8dc8c?context=explore

**Comment by NickM-27** [comment]
> Is it please possible to update tag for nvidia on dockerhub to update to 11.1 please?
> 
> ref: https://hub.docker.com/layers/blakeblackshear/frigate/stable-amd64nvidia/images/sha256-d91dc45bbc8d80f270430668a2a8983f5b22e203c3994545c68964b7b9f8dc8c?context=explore

Please read the docs and the release notes, there is no longer an nvidia specific tag as everything is built into the `stable` tag

**Comment by caublet** [comment]
> > Is it please possible to update tag for nvidia on dockerhub to update to 11.1 please?
> > ref: https://hub.docker.com/layers/blakeblackshear/frigate/stable-amd64nvidia/images/sha256-d91dc45bbc8d80f270430668a2a8983f5b22e203c3994545c68964b7b9f8dc8c?context=explore
> 
> Please read the docs and the release notes, there is no longer an nvidia specific tag as everything is built into the `stable` tag

I've read the 11.0 release notes, where this was introduced and also read doc https://docs.frigate.video/configuration/hardware_acceleration/

if I configure according to doc, nvidia-smi is not into image  and cannot be used. What did I miss?
