### ISSUE TITLE
Support for H265

### ISSUE THREAD

**Issue by sygys** [blakeblackshear/frigate#1848]
I have been trying for over 16 hours now to get my camera imou dome to work in frigate using the H265 stream. But it just wont work. Are there plans to support them out of the box without the 10.000 args input that needs to be done just right to get it working?

I would really love that.

**Comment by blakeblackshear** [comment]
Can you define "work"? Detection works fine with H265. Support for rtmp and recordings with H265 will be supported as soon as Chrome and Firefox support playback in the browser. My understanding is that will never happen, so H265 is not expected to ever work completely with Frigate.

**Comment by svenstaro** [comment]
Related: Shouldn't it be fairly cheap computationally speaking to remux the RTMP stream to HLS to allow for more codecs to be used? With GPU encoding, it would even be feasible to cheaply re-encode multiple streams to an ideal video format inside of HLS.

**Comment by blakeblackshear** [comment]
For h264, yes. In a future version I plan to move away from the rtmp only restreaming and have rtsp, hls, and webrtc (hopefully) too. Only Safari and Edge can playback H265 hls streams. There are a few people using Nvidia GPUs to transcode to h264, but it's not practical for most users and high resolutions require a beefy enough GPU that it would be cheaper to just replace your cameras.

**Comment by svenstaro** [comment]
I just tested live encoding on my small 1050 Ti in my NVR and it was capable of 60 FPS h264 or hevc live encoding so it might be quite reasonable to use pretty much any halfway recent GPU for this task. AV1 is supported by [pretty much all modern browsers](https://caniuse.com/av1) and will probably get hardware encoding support in modern hardware soon so this might be something to be excited about. Anyhow, this is getting a bit off-topic to this issue at this point.

**Comment by blakeblackshear** [comment]
AV1 won't be very relevant until cameras send video in AV1.

**Comment by svenstaro** [comment]
I meant AV1 as a transcoding target as that's kinda what this whole issue is about (flv not supporting better than h264).

**Comment by sygys** [comment]
Blake would you be willing to help me try to get detection to work. I have a substream in 264 that does work but the resolution is so darn low it can't detect very much. Tell me what you need and I'll post it here thanks in advance

**Comment by sygys** [comment]
stupid of me but imou / dahua has software which has a great in dept settings menu which goes allot deeper then the mobile app in which you can simply change the mainstream to H264 instead of 265. Now it works perfect on the high res stream

**Comment by hibby50** [comment]
Would it be possible to implement a feature where, on the events page and the recordings view for a camera, it gives you the option to open the clip/recording in an external app? That way vlc could be launched to playback h.265 clips outside of the browser. Obviously there is a download button, but I'm thinking some way to open it as a stream.
