### ISSUE TITLE
Support objects dwelling for some configurable amount of time before triggering a detection event

### ISSUE THREAD

**Issue by tjhorner** [blakeblackshear/frigate#1850]
**Describe what you are trying to accomplish and why in non technical terms**
I'd like to be able to configure object detection to wait until an object has dwelled on-screen for some amount of time before it triggers a detection event. This is useful for e.g. front door cameras, as many people may walk by on the sidewalk, which will trigger a person detection event. A dwell time minimum would filter out these events and only detect people that are actually at the front door for a certain amount of time.

**Describe the solution you'd like**
Being able to configure this at both the global and per-camera (like the existing `object` config) would be ideal. For example:

```yaml
objects:
  track:
    - person
  filters:
    person:
      dwell: 10 # seconds
```

**Describe alternatives you've considered**
- Since Frigate sends the start time of each event over the wire in MQTT messages, it is possible to write a Home Assistant automation or similar to fire an event only if it is still occurring after some amount of time. However, this is complicated and involves mucking with templates.
- Using the previous example, defining a zone for the front porch area may be feasible depending on the camera's position, but for cameras that are facing through e.g. a peephole, this isn't possible.

**Comment by tve** [comment]
WRT peephole camera, you might be able to use the minimum size parameter to exclude people walking by in the distance

**Comment by NickM-27** [comment]
Closing this as this is supported in 0.13 with required_zone and setting the inertia for that zone. Even if the zone is most of the frame, can still require a minimum amount of time before the zone is activated
