### ISSUE TITLE
Expose Birdseye view as a "camera" in the api

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#1854]
**Describe what you are trying to accomplish and why in non technical terms**
Expose the birdseye view option as a "camera" in the api `/api/birdseye` or perhaps as a RTMP stream.

**Describe the solution you'd like**
To allow the birdseye stream to be consumed "easily" on other devices such as a media player etc.

**Describe alternatives you've considered**
Continue to use rpisurv and similar software's.

**Additional context**
Thanks.

**Comment by blakeblackshear** [comment]
The lovelace card will support it in the future. Making it work like another camera will require encoding to h264 on the fly and will take quite a bit of CPU power.

**Comment by tubalainen** [comment]
Ok.
Great news with the Lovelace card! <3

Its a mjpeg stream today? Would it be possible just to expose it so we as users can consume it outside of the HA ecosystem?
Ok on the encoding part.

**Comment by dermotduffy** [comment]
If you install the pre-release versions of both, you can do this in the Lovelace card **right now** :-)

* Install [integration](https://github.com/blakeblackshear/frigate-hass-integration/releases) >= 2.1.0
* Install [card](https://github.com/dermotduffy/frigate-hass-card/releases) >= 1.1.0
* Configure `frigate_camera_name` as `birdseye` and `frigate_live_provider`as `frigate-jsmpeg`

=> Birdseye view in the Frigate lovelace card!

**Comment by tubalainen** [comment]
> * frigate-jsmpeg

**Comment by dermotduffy** [comment]
Any entity should work, doesn't matter, since you are manually setting the Frigate camera name field. The camera entity field is currently required, but this is the one configuration where it's not used. I may loosen that field to optional in future as a result.

**Comment by ryanm101** [comment]
Ideally something like https://github.com/gihad/streamer  so it could be supported by cast devices

**Comment by andreacoppini** [comment]
has this been dropped?  I just tried to configure this and the birdseye view doesn't appear.
add-on v2.3
card v2.0.0


```
type: custom:frigate-card
frigate_live_provider: frigate-jsmpeg
camera_entity: camera.[one of my cameras]_car
frigate:
  camera_name: birdseye

```

**Comment by dermotduffy** [comment]
Hi @andreacoppini -- it has not been dropped. I suspect you may have missed the [release notes for v2.0.0](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v2.0.0) of the card, which contains a significant configuration change. Give it a read, update your config and if it still doesn't work file a bug over at https://github.com/dermotduffy/frigate-hass-card (as this bug is in the wrong repo for card support).

**Comment by tubalainen** [comment]
Just to clarify. The new Frigate Hass Card is great! Thanks for all the hard work @dermotduffy ! <3

For me, I am looking for a way to consume the "Birdseye" feature in frigate as a rtsp/rtmp stream so that I can consume it outside of the Home Assistant eco system.
