### ISSUE TITLE
Recordings are not shown if the first record of the day is broken.

### ISSUE THREAD

**Issue by Homas** [blakeblackshear/frigate#1862]
**Describe the bug**
By default when you navigate from a camera page to recording frigate shows the first clip's preview. If there is an issue with the first clip (bad file etc, I had them when configured my reolink cameras) frigate shows an error message "The media could not be loaded, either because the server or network failed or because the format is not supported." even if after that there were good files.
The overlay (with error) blocks right navigation and not possible to select different time/event. If you navigate to other camera and select any time with good recordings you can navigate back to the "bad camera" and watch recording w/o issues. Of course next day it is automatically solved but when you install your cameras it is very irritating. 

**Version of frigate**
0.9.0-aa807d2 (0.9 RC5). The same was on RC2.

**Frigate container logs**
no relevant logs

**Computer Hardware**
 - OS: Ubuntu, browser on MacOS
 - Install method: Docker Compose
 - Coral Version: None
 - Network Setup: Wired for cameras, WiFi to access the interface.

**Comment by Homas** [comment]
Actually the issue happens if there is any broken file starting any hour. You can not change time. The only way to navigate out of the bad camera and go back.

The issue happens because the modal window (vjs_video_3_component_602_description) blocks the time navigation panel

**Comment by tve** [comment]
I'm having similar issue repeatedly. Right now I can't play recordings from one camera even though the first recording of the day is playable with vlc. The URL is `http://core2:5000/vod/2021-09/28/00/rodentcam/index.m3u8` and in that directory an `ls` shows
```
> ls 28/00/rodentcam/
00.00.mp4  07.00.mp4  14.01.mp4  21.01.mp4  28.00.mp4  35.00.mp4  42.00.mp4  49.00.mp4  56.00.mp4
01.00.mp4  08.00.mp4  15.00.mp4  22.00.mp4  29.00.mp4  36.00.mp4  43.00.mp4  50.00.mp4  57.00.mp4
02.00.mp4  09.00.mp4  16.00.mp4  23.00.mp4  30.00.mp4  37.00.mp4  44.01.mp4  51.00.mp4  58.00.mp4
03.00.mp4  10.01.mp4  17.00.mp4  24.00.mp4  31.00.mp4  38.00.mp4  45.00.mp4  52.00.mp4  59.00.mp4
04.00.mp4  11.00.mp4  18.00.mp4  25.00.mp4  32.00.mp4  39.00.mp4  46.00.mp4  53.00.mp4
05.01.mp4  12.00.mp4  19.00.mp4  26.00.mp4  33.00.mp4  40.00.mp4  47.00.mp4  54.01.mp4
06.00.mp4  13.00.mp4  20.00.mp4  27.00.mp4  34.00.mp4  41.00.mp4  48.00.mp4  55.00.mp4
```
and the first file (`00.00.mp4`) plays just fine in vlc. Curl returns the following (same as the browser gets):
```
> curl http://core2:5000/vod/2021-09/28/00/rodentcam/index.m3u8
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```
Not sure where to find the nginx log...

**Comment by blakeblackshear** [comment]
Frigate uses the following to determine the duration of the segment. Can you run this on the segment to see if it comes back as 0? 
```
ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 file.mp4
```

**Comment by Homas** [comment]
I don't have these recordings already but I see such issues even in beginning of an hour. Looks like the recordings were not correctly split between the hours.
```
**59.54.mp4 9.579000**
root@beeb7444779d:/media/frigate/recordings/2021-09/30/13/sideyardright511# cd ../../14/sideyardright511/
root@beeb7444779d:/media/frigate/recordings/2021-09/30/14/sideyardright511# for x in *; do echo -n "$x " ;ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 $x; done
**00.04.mp4 9.621000**
```
Last file starts at 13:59:54 and lasts about 10 seconds. There is no file which starts at 14:00:00. The first file starts 14:00:04.
This is reolink 511 camera.

**Comment by peledzius** [comment]
I encountering similar problem that @tve described.

I found out this in Home Assistant Media Browser when I couldn't play some of the recordings, got **503 Service Temporarily Unavailable** error. Checked in Frigate UI - same deal.

I found out that specifically first segment gives error and everyone after is fine:
```
$ curl http://192.168.222.100:5000/vod/2022-03/16/17/living_room/seg-1-v1-a1.ts
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

I can play `00.00.mp4` file fine in VLC. I also ran @blakeblackshear command to check segment duration, but it looks good for me:

```
$ ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 00.00.mp4
10.004000
```

If I play http://192.168.222.100:5000/vod/2022-03/16/17/living_room/index.m3u8 in VLC, it skips that first segment and playback starts from 2nd segment(17:00:10 timestamp)

**Comment by blakeblackshear** [comment]
@peledzius can you post the contents of the m3u8 file?

**Comment by peledzius** [comment]
@blakeblackshear it's from other directory, but has the same issue:

```
$ curl http://192.168.222.100:5000/vod/2022-03/16/21/living_room/index.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1
#EXTINF:10.000,
seg-1-v1-a1.ts
#EXTINF:10.000,
seg-2-v1-a1.ts
#EXTINF:10.000,
seg-3-v1-a1.ts
#EXTINF:10.000,
seg-4-v1-a1.ts
#EXTINF:10.000,
seg-5-v1-a1.ts
#EXTINF:10.000,
seg-6-v1-a1.ts
#EXTINF:10.000,
seg-7-v1-a1.ts
#EXTINF:10.000,
seg-8-v1-a1.ts
#EXTINF:10.000,
seg-9-v1-a1.ts
#EXTINF:10.000,
seg-10-v1-a1.ts
#EXTINF:10.000,
seg-11-v1-a1.ts
#EXTINF:10.000,
seg-12-v1-a1.ts
#EXTINF:10.000,
seg-13-v1-a1.ts
#EXTINF:10.000,
seg-14-v1-a1.ts
#EXTINF:9.891,
seg-15-v1-a1.ts
#EXT-X-ENDLIST
```
