### ISSUE TITLE
Old events shown when navigating from the camera page. New events are shown only if I refresh page.

### ISSUE THREAD

**Issue by Homas** [blakeblackshear/frigate#1863]
**Describe the bug**
I'm getting notifications from HASS about objects and when I try to see the events and navigate from the main cameras page only old events visible. Even if I remove filters, I still see the old events.
I have to hit browser's refresh button to see the new events.
I'm using the recent Chrome on MacOS. Looks like the events feed was cached and was not updated till I refresh the browser page.

**Version of frigate**
0.9.0-aa807d2 - RC5
The same behaviour I saw on RC2

**Computer Hardware**
 - OS: Ubuntu, browser on MacOS
 - Install method: Docker Compose
 - Coral Version: None
 - Network Setup: Wired for cameras, WiFi to access the interface.

**Comment by mr-manuel** [comment]
I confirm having the same problem. Saw this though all Frigate versions. Currently I'm using only Frigate withouth HASS in Docker 0.9.0-a943ac1 - RC4. The latest events only get loaded if I hit F5/refresh the page.

I'm using the latest Firefox and Google Chrome on the latest Windows 10.

**Comment by NickM-27** [comment]
This has been fixed in 0.11.0 👍
