### ISSUE TITLE
frigate inside HASS issue

### ISSUE THREAD

**Issue by heapxor** [blakeblackshear/frigate#1865]
Hi,
no idea whats the issue ... 

frigate.edgetpu                INFO    : No EdgeTPU detected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate.mqtt                   INFO    : MQTT connected
frigate.video                  INFO    : entrance_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : entrance_cam: ffmpeg process is not running. exiting capture thread...
ffmpeg.entrance_cam.detect     ERROR   : [flv @ 0x556dc35830] Video codec hevc not compatible with flv
ffmpeg.entrance_cam.detect     ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
ffmpeg.entrance_cam.detect     ERROR   : 
frigate.video                  INFO    : entrance_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : entrance_cam: ffmpeg process is not running. exiting capture thread

**Comment by blakeblackshear** [comment]
I see two issues here.

- your camera is an h265 camera and you need to disable rtmp
- you don't have a Coral device and you haven't configured a CPU detector in the config

Post your config file if you need further support.

**Comment by heapxor** [comment]
these is bit odd/ broken? 
i added 
detectors: 
  cpu1:
    type: cpu
  cpu2:
    type: cpu

into the config ... but now i got 

frigate.video                  INFO    : entrance_cam: ffmpeg process is not running. exiting capture thread...
ffmpeg.entrance_cam.detect     ERROR   : [flv @ 0x55952e3670] Video codec hevc not compatible with flv
ffmpeg.entrance_cam.detect     ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
ffmpeg.entrance_cam.detect     ERROR   : 
frigate.video                  INFO    : entrance_cam: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : entrance_cam: ffmpeg process is not running. exiting capture thread...

and the screen of camera in frigate is Green.

thanks

**Comment by heapxor** [comment]
okay seems that most important info was missing ... 
https://github.com/blakeblackshear/frigate/issues/1602
You can't use **RTMP with h265. You either have to switch to h264**, disable rtmp, or re-encode to h264 on the fly.

So i switched to h264 and no ffmpeg issue
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.cpu1                  INFO    : Starting detection process: 37
detector.cpu2                  INFO    : Starting detection process: 38
frigate.app                    INFO    : Camera processor started for entrance_cam: 44
detector.cpu3                  INFO    : Starting detection process: 40
frigate.app                    INFO    : Capture process started for entrance_cam: 45


The issue ? is now Displaying at 5.0fps 
5fps? because rpi4 is not capable? not enough power?
The picture is not a green now but i cant see anything there... 


thanks

**Comment by heapxor** [comment]
also camera configuration
>
![image](https://user-images.githubusercontent.com/64676/135083101-ca1b6590-cfe1-48d0-95e2-0ecdfab53a61.png)

even the cam supports>
2688*1520

**Comment by blakeblackshear** [comment]
> seems when i changed cam resolution to 1920*1080 it works now!

Your resolution has to match your config.

> can frigate handle 2688*1520?

Yes, but probably not on a RPi4.

You may want to consider using the release candidate for 0.9.0 and reading through the updated docs: https://docs.frigate.video

**Comment by blakeblackshear** [comment]
If you are using the Addon, you would use the Beta addon instead to get the 0.9.0 release.

The Coral won't help with decoding higher resolutions. It just lowers the CPU usage for object detection. I suggest reading through the docs linked above. Most of the questions you are asking are explained there.

**Comment by heapxor** [comment]
hi, but what addon do u mean - frigate-hass-integration?

okay, i will check doc, thanks
