### ISSUE TITLE
Mask & Zone Creator is not working on 0.9 RC5

### ISSUE THREAD

**Issue by Homas** [blakeblackshear/frigate#1868]
**Describe the bug**
On Chrome/Firefox/Safari it is not possible to create masks or zones using the frigate mask & zone creator.
Clicks on the image aren't recognised, no points can't be set.

In developers tools I see:
Chrome:
`CameraMap.-LxSn76V-_-H.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'reduce') at Object.clickfalse (CameraMap.-LxSn76V-_-H.js:14) at HTMLDivElement.ne (preact.module-ff55218f.bKiDWaS-1sUZ.js:1)`

Firefox:
`Uncaught TypeError: e is undefined m http://192.168.45.114:5000/dist/routes/CameraMap.-LxSn76V-_-H.js:14`

**Version of frigate**
0.9.0-aa807d2

**Additional context**
Looks like a regression bug:
https://github.com/blakeblackshear/frigate/issues/1271

**Comment by Homas** [comment]
The same issue I've observed on RC2 (0.9.0-46FE06E), RC3 (0.9.0-7B063A1), RC4 (0.9.0-A943AC1). All were deployed via docker-compose.

**Comment by Homas** [comment]
My bad. I've missed somehow that I need to press "add" button before clicking around...

**Comment by mweinelt** [comment]
Ugh, just ran into this. Can we reopen this issue and improve the UX?

**Comment by brainfoolong** [comment]
Had the same problem in current docker version. Fixed it  temporarily by opening F12 console in chrome.
In console error, click the filename at the right of the error, 
Rightlick the file and select "override" (or similar named option).
Added this line, works.

![image](https://github.com/blakeblackshear/frigate/assets/1684236/42a8ec2f-293e-4add-8e1e-1ff221c46599)

**Comment by rehevkor5** [comment]
The "copy" button exhibits a similar error which prevents it working.
