### ISSUE TITLE
Frigate Home Assistant Addon - Clip Permissions

### ISSUE THREAD

**Issue by ga2pegw** [blakeblackshear/frigate#1877]
I noticed when trying to play clips within the Home Assistant media browser, that they do not automatically play, and found out that the clips themselves were not set with the right permissions (755). Once I change the folder permission, the clips are able to be viewed, however any new clips that are created go back to having the incorrect permissions. Is there something I need to change in the config or a user permission to change within the container to have future files written with the correct permissions?

**Comment by blakeblackshear** [comment]
What version are you running?

**Comment by ga2pegw** [comment]
I'm running version 1.14...installed directly from the Add-on Store in Home
Assistant

**Comment by blakeblackshear** [comment]
Next version runs the webserver as root, so this shouldn't be a problem there.

**Comment by ga2pegw** [comment]
Great, thanks! After updating, I'll confirm and close the issue if all good.
