### ISSUE TITLE
Ability to hide left menu bar and header on Birdseye page

### ISSUE THREAD

**Issue by patdemko** [blakeblackshear/frigate#1891]
**Describe what you are trying to accomplish and why in non technical terms**
I use a number of fire tablets running [WallPanel](http://thanksmister.com/wallpanel-android/) that I have displaying photos or home assistant dashboards throughout my home.  When frigate detects an object, I'd like to trigger an api call to [WallPanel](http://thanksmister.com/wallpanel-android/) to display the birdseye page and then switch back to photos or a home assistant dashboard after 30 seconds of frigate not detecting an object.  I can trigger the api call now to display the birdseye url, but there's a lot of empty space taken up by the menu and the header which isn't the best viewing experience on a tablet.

**Describe the solution you'd like**
An option on the birdseye configuration to not display the menu or header on the birdseye page or an toggle on the web page itself to hide the menu and header.

**Describe alternatives you've considered**
I know if you click on the image on the birdseye page it will make it go full screen which basically is what i want, but I have not been able to figure out a way to do this automatically with the [WallPanel](http://thanksmister.com/wallpanel-android/) api.  I could also just display the best image of the object that frigate detected, but I really do like the new birdseye page and would prefer to use it if possible.

**Additional context**
I've attached a couple photos showing one of my tablets going from displaying a photo to displaying the birdseye page.  BTW, awesome project!

![frig2](https://user-images.githubusercontent.com/11141892/135477584-929b45f8-015e-4619-9601-eea9aea01f5c.jpg)
![frig1](https://user-images.githubusercontent.com/11141892/135477610-cf4c7337-0195-449f-9c04-4547056d1ae7.jpg)
!

**Comment by therealcarnivor** [comment]
i have the continuous version of birdseye running and clicking the window makes it full screen, with esc to get out of it, not sure if all the birdseye modes have that though

**Comment by patdemko** [comment]
> i have the continuous version of birdseye running and clicking the video window makes it full screen, with esc to get out of it, not sure if all the birdseye modes have that though

Yeah, that does seem to work for the object one too, but like I mentioned I haven't been able to figure out a way to simulate the "click" with the [WallPanel](http://thanksmister.com/wallpanel-android/) api since I'm trying to make this all work automatically without anyone having to touch the tablet.  I normally have a loop running in Node-Red that every 3 minutes picks a random picture from a directory and then sends an API request to [WallPanel ](http://thanksmister.com/wallpanel-android/) to display that picture's URL. When an object is detected, I then pause that loop and want to send the URL to the birdseye page to display it which works but the image isn't maximized like would happen if click on it.  Then after 30 seconds of no object being detected, I'd start up the picture loop again and go back to displaying photos. Hope that explains what I'm trying to do.

**Comment by blakeblackshear** [comment]
I'm sure I can find a way to automatically go fullscreen with a query string parameter or something.

**Comment by Tediore** [comment]
Just wanted to express that this would be awesome to have!

**Comment by k2xl** [comment]
@patdemko I'm doing a similar setup with my fire tablet + fully kiosk + node red listening to mqtt events. Question - what URL are you have it load? I'm unable to find a direct URL to the birdseye page (URL doesn't seem to change when i click on birdseye).

**Comment by patdemko** [comment]
> @patdemko I'm doing a similar setup with my fire tablet + fully kiosk + node red listening to mqtt events. Question - what URL are you have it load? I'm unable to find a direct URL to the birdseye page (URL doesn't seem to change when i click on birdseye).
> 
> _EDIT_ I just figured it out (slaps own head) that Home assistant loads frigate within iframe. Web interface is http://:/birdseye . Port by default is 5000 for web interface.

Sorry for delay in responding, but looks like you figured it out.  I'm actually not using birdseye page since I never figured out a way to make it go full screen.  I'm instead just pointing it do a frigate lovelace card using the WebRTC feed so I need to handle switching which camera feed I show based on which one has an object detected.

**Comment by k2xl** [comment]
So i just got the frigate lovelace card working with birdseye. Did you know you can configure it to do that?

combine that with the fullscreen integrations or just use a custom css on the lovelace dash and it works beautifully. I also have it hooked up with custom functions and TTS to speak messages like ‘A dog was detected in the back yard’

Thing im trying to think through is what is the right timeout / behavior to return to previous url. Got sort of annoying when i had people at my house doing yard work.

**Comment by kevbodavidson** [comment]
I am having this same issue since I am launching frigate in kiosk mode.  It would be nice to have a query for ?no_sidebar or ?full_screen after the /birdseye

**Comment by wsguede** [comment]
bump

**Comment by mikalj2009** [comment]
Bumping this, much wanted feature.

**Comment by wsguede** [comment]
i made a bookmarklet that will delete the drawer;
```
javascript:void%20function(){document.querySelector('[data-testid=%22[drawer](javascript:void%20function(){document.querySelector('[data-testid=%22drawer%22]').parentNode.removeChild(document.querySelector('[data-testid=%22drawer%22]'))}();)%22]').parentNode.removeChild(document.querySelector('[data-testid=%22drawer%22]'))}();
```

this is a very crappy workaround. If you want the drawer back, you need to refresh the page;
something to help until this feature is added hopefully.

**Comment by DrSpaldo** [comment]
Just found this one and I agree it would be a nice option to have for my tablets

**Comment by adamgranted** [comment]
Wanting this as well. I put together a workaround for now if you're using dedicated hardware and a display. I'm using it specifically for the birdseye restream.
https://github.com/adamgranted/rtspstreamer

**Comment by kevbodavidson** [comment]
I ended up going with https://github.com/deepch/RTSPtoWeb

**Comment by nagi603** [comment]
Even just the ability to collapse the left menu bar would be a huge improvement on smaller width screens. I frequently watch a 3x3 on half of a display, and roughly a 5th of the big screen is taken up by the menu.

**Comment by johnwilson1969** [comment]
@Nagy Balázs András - you may want to check out the 0.14 beta version. It
has a completely new UI with a very minimal menu.

**Comment by nagi603** [comment]
Thanks for the heads-up, those seem quite big change. As it involves so many things besides the birdseye page, I think I'll wait for a stable release. But still appreciate the ping, I did not catch the next plans before the mention.

**Comment by NickM-27** [comment]
In the new UI the birdseye view can be full screened via query arg

**Comment by DrSpaldo** [comment]
> In the new UI the birdseye view can be full screened via query arg

@NickM-27, is it possible when you close issues that you can reference or post how you do it?

**Comment by patdemko** [comment]
Thanks @NickM-27, but as @DrSpaldo asked can you tell us how to do this or point us to the documentation?  I've gone through the documentation and haven't been able to find how to do this.

**Comment by NickM-27** [comment]
I should have been clear this was added for 0.15, so it's not currently available. 

The `f` key can be pressed (or scripted) to make the view fullscreen. 

A query arg can't be used for this because the Fullscreen API requires that the request to enter fullscreen mode must be initiated by a user gesture (a click, tap, or keypress). This is a security measure so that malicious websites can't unexpectedly take over a user's entire screen without their consent.

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
