### ISSUE TITLE
Error demuxing stream

### ISSUE THREAD

**Issue by sygys** [blakeblackshear/frigate#1895]
**Describe the bug**
Im having allot of error messages in the home assistant logs like this:

```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:396
Integration: Stream (documentation, issues)
First occurred: 12:10:47 (1 occurrences)
Last logged: 12:10:47

Error demuxing stream: Timestamp overflow detected: last dts = 4295967943, dts = 1000700
```

Also when adding the camera stream into home assistant UI and opening it. The stream is very choppy and a load bar is presented most of the time. Mostly it results in the stream to freeze. When opening the stream with the motion eye addon its rock solid. Im running HA on an intel NUC i7 10th gen at around 14% load with frigate active. with 13 GB of ram free.

**Version of frigate**
1.14

**Frigate container logs**
```
ffmpeg.camera_zijtuin.detect   ERROR   : [h264 @ 0x55c17aea4b40] decode_slice_header error
ffmpeg.camera_zijtuin.detect   ERROR   : [h264 @ 0x55c17aea4b40] no frame!
ffmpeg.camera_zijtuin.detect   ERROR   : [h264 @ 0x55c17aea4b40] non-existing PPS 0 referenced
ffmpeg.camera_zijtuin.detect   ERROR   :     Last message repeated 1 times
ffmpeg.camera_zijtuin.detect   ERROR   : [h264 @ 0x55c17aea4b40] decode_slice_header error
ffmpeg.camera_zijtuin.detect   ERROR   : [h264 @ 0x55c17aea4b40] no frame!
ffmpeg.camera_zijtuin.detect   ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.camera_zijtuin.detect   ERROR   : [swscaler @ 0x55c17af54980] deprecated pixel format used, make sure you did set range correctly
ffmpeg.camera_zijtuin.detect   ERROR   : [flv @ 0x55c17b01d200] Non-monotonous DTS in output stream 0:0; previous: 1006976, current: -9223372036854776; changing to 1006976. This may result in incorrect timestamps in the output file.
ffmpeg.camera_zijtuin.detect   ERROR   : [flv @ 0x55c17b01d200] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
ffmpeg.camera_zijtuin.detect   ERROR   : [flv @ 0x55c17b01d200] Failed to update header with correct duration.
ffmpeg.camera_zijtuin.detect   ERROR   : [flv @ 0x55c17b01d200] Failed to update header with correct filesize.
```

**Comment by blakeblackshear** [comment]
Motioneye provides an mjpeg stream which is completely different than the way frigate provides the stream to HA. Frigate just relays the camera feed back to HA via RTMP without modifying it. Motioneye decodes and then reencodes it as mjpeg which takes much more processing power. Frigate _can_ do mjpeg too, but it uses more CPU and bandwidth.

I am looking at some options that may improve the connection between frigate and HA in the future. Do you also see errors in frigate for your cameras?

**Comment by sygys** [comment]
In frigate itself it just gives me the 5fps stream but this never gets me a loading icon or freezes. this just works.

Do you know what the ```Error demuxing stream: Timestamp overflow detected: last dts = 4295967943, dts = 1000700``` is?

Is there a way to fix this?

**Comment by blakeblackshear** [comment]
Frigate is showing the mjpeg stream. It would be most helpful if you provide the information requested in the issue template. It's requested for a reason.

**Comment by PskNorz** [comment]
i am getting this type of error too.

**Comment by blakeblackshear** [comment]
If you are seeing those errors in the Frigate logs, that is ffmpeg struggling to maintain a consistent connection to your camera. It is losing connection, exiting, restarting, etc. That stop/start pattern for the rtmp role is causing the choppy video issues.

**Comment by PskNorz** [comment]
i am getting something like this

```
Logger: libav.NULL
Source: components/stream/worker.py:223
First occurred: 11:46:11 AM (2 occurrences)
Last logged: 11:46:11 AM

non-existing SPS 1 referenced in buffering period
SEI type 40 size 1856 truncated at 1672
```
```
This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:172
Integration: Frigate (documentation, issues)
First occurred: 10:41:43 AM (2 occurrences)
Last logged: 10:41:54 AM

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Try again]
```
```
Logger: homeassistant.components.stream.worker
Source: components/stream/worker.py:396
Integration: Stream (documentation, issues)
First occurred: 10:57:47 (1 occurrences)
Last logged: 10:51:47

Error demuxing stream: [Errno 1414092869] Immediate exit request: 'rtmp://ccab4aaf-frigate/live/doggie_cam'
```

Also i was watching the camera stream from frigate when the boxes appear if motion detect it and i saw that if it appear a lot of movement the frigate crash and drops those errors.

**Comment by blakeblackshear** [comment]
Same as the comment I posted previously. Lot's of motion means the compression algorithm is working harder on your camera and that may cause the stream to corrupt. It would be most helpful if you open your own issue and provide the information requested in the issue template.

**Comment by PskNorz** [comment]
i will ,just i am new to this, thanks

**Comment by sygys** [comment]
Ik new to these too. I don't know how to get most of the requested data in the template out of home assistant. I thought the error at least told something of what is going wrong

**Comment by blakeblackshear** [comment]
Some things you didn't provide:

- your config file
- make/model of your cameras

**Comment by sygys** [comment]
Model camera is foscam g4p, the config will share in a second
