### ISSUE TITLE
Timestamp into recording and Live view

### ISSUE THREAD

**Issue by michelebossa** [blakeblackshear/frigate#1905]
**Describe the solution you'd like**
I'm using the beta 9.0-rc6 i'd like if possible to view the timestamp into live feed and record section. i'm using two cameras without timestamp written into video feed and for me it is not easy to understand specially during recording view the precision timing of image playing.

And maybe if possible i'd like under recorder view a possibility to jump in a date/hour by pick selector like this:

![image](https://user-images.githubusercontent.com/38975058/135869738-9248976c-01d7-4007-8df5-b243132f4ece.png)

**Describe what you are trying to accomplish and why in non technical terms**
N/A
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by blakeblackshear** [comment]
The timestamp on the live view should just match the time on your computer screen. I'm not sure how this is helpful.

For recordings, the video feed can't be modified to add a timestamp without decoding and re-encoding. The time of the recordings viewer would have to be shown in the UI rather than as a part of the video feed.

**Comment by michelebossa** [comment]
Thanks for the reply.
i use the timestamp in view to understand quikly if the cam it is Frozen. I have a very chep cam and sometimes i need to reboot.

In recording view i undestand it is batter to avoid the rencoding of stream but if we can see the timing on UI section sound good for me. Can you add this?

Thanks

**Comment by b24home** [comment]
Has this been accounted for in the now-future updates? 

On Ring, afaik, there is no way to add a timestamp to the device's output.

**Comment by NickM-27** [comment]
the next version of frigate (which will have a fully new UI) will have a timeline that shows the current time for the recordings playback

**Comment by dcovington2** [comment]
This is good news!

**Comment by b24home** [comment]
Amazing! What date is that planned for?

**Comment by NickM-27** [comment]
there is no date, it will be ready when it is ready
