### ISSUE TITLE
UDP protocol in RTSP

### ISSUE THREAD

**Issue by gusarg81** [blakeblackshear/frigate#1907]
Hi,

I have 2 cameras that uses UDP only as rtsp transport. So, how I do set this option for a particular camera (and not for all cameras)?

Thanks in advance.

**Comment by gusarg81** [comment]
Nevermind, I used:

```
input_args: 
        -rtsp_transport udp
```

But still can't get image from the camera (currently I use Shinobi CCTV and works just fine).

**Comment by blakeblackshear** [comment]
It is difficult to provide support since you didn't use the template for a support request.

**Comment by gusarg81** [comment]
Yeah, sorry about that. Lets begin again:

Describe the problem you are having:

> Image/Videos does not show at all.

Version: 

> Latest version installed via docker-compose (installed yesterday) - amd64.

Frigate config file:

> mqtt:
>   host: home.ddns.gdnet.ar
>   port: 1883
>   topic_prefix: frigate
>   client_id: frigate
>   user: myuser
>   password: passwd
>   stats_interval: 60
> 
> cameras:
>   Doorbell:
>     ffmpeg:
>       inputs:
>         - path: rtsp://myuser:passwd@10.0.1.10:554/onvif1
>           roles:
>             - detect
>             - rtmp
>       input_args: 
>         -rtsp_transport udp
>     width: 1920
>     height: 1080
>     fps: 5

Relevant log output:

> 
> docker logs frigate
>  * Starting nginx nginx
>    ...done.
> Starting migrations
> peewee_migrate                 INFO    : Starting migrations
> There is nothing to migrate
> peewee_migrate                 INFO    : There is nothing to migrate
> frigate.mqtt                   INFO    : MQTT connected
> detector.coral                 INFO    : Starting detection process: 36
> frigate.app                    INFO    : Camera processor started for Doorbell: 39
> frigate.app                    INFO    : Capture process started for Doorbell: 41
> frigate.edgetpu                INFO    : Attempting to load TPU as usb
> Process detector:coral:
> frigate.edgetpu                INFO    : No EdgeTPU detected.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
>     delegate = Delegate(library, options)
>   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
>     raise ValueError(capture.message)
> ValueError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
>     object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
>   File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
>     edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
>   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
>     raise ValueError('Failed to load delegate from {}\n{}'.format(
> ValueError: Failed to load delegate from libedgetpu.so.1.0
> 
> frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
> frigate.app                    INFO    : Stopping...
> frigate.events                 INFO    : Exiting event processor...
> frigate.record                 INFO    : Exiting recording maintenance...
> frigate.object_processing      INFO    : Exiting object processor...
> frigate.events                 INFO    : Exiting event cleanup...
> frigate.watchdog               INFO    : Exiting watchdog...
> frigate.stats                  INFO    : Exiting watchdog...
> peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
> root                           INFO    : Waiting for detection process to exit gracefully...
>  * Starting nginx nginx
>    ...done.
> Starting migrations
> peewee_migrate                 INFO    : Starting migrations
> There is nothing to migrate
> peewee_migrate                 INFO    : There is nothing to migrate
> frigate.mqtt                   INFO    : MQTT connected
> frigate.app                    INFO    : Camera processor started for Doorbell: 39
> detector.coral                 INFO    : Starting detection process: 36
> frigate.edgetpu                INFO    : Attempting to load TPU as usb
> frigate.app                    INFO    : Capture process started for Doorbell: 41
> Process detector:coral:
> frigate.edgetpu                INFO    : No EdgeTPU detected.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
>     delegate = Delegate(library, options)
>   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
>     raise ValueError(capture.message)
> ValueError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
>     object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
>   File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
>     edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
>   File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
>     raise ValueError('Failed to load delegate from {}\n{}'.format(
> ValueError: Failed to load delegate from libedgetpu.so.1.0

FFprobe output from your camera:

> Input #0, rtsp, from 'rtsp://admin:RivenMyst.06260@10.0.1.10:554/onvif1':
>   Metadata:
>     title           : H.264 Video, RtspServer_0.0.0.2
>   Duration: N/A, start: 0.000000, bitrate: N/A
>     Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 5 fps, 5 tbr, 90k tbn, 180k tbc
>     Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

Operating system:

> Ubuntu server 20.04 - Kernel 5.11.0-36-generic

Install method:

> Docker compose

Coral version:

> I don't have Coral hardware

Network connection:

> Ethernet - UTP - 1Gbit LAN (but camera port is 100Mbps)

Camera make and model:

> Its an IP Doobell with RTSP/Onvif support - Konx kw05 (http://www.konxtech.com/Product/detail/l/en/id/6.html)

Any other information that may be helpful:

> Camera is only accessible via UDP transport when using RTSP.
