### ISSUE TITLE
Better handling of vertical videos

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#192]
Front door cameras that are in portrait mode sometimes struggle because the dynamic regions are constrained to the width of the image. This can cause objects to only partially fit within the region. I need to allow the regions to extend beyond the bounds of the image in that situation.

**Comment by mcondren** [comment]
This would be great. I just got a unifi G4 doorbell cam and it only detects people 50% of the time. I was wondering if it was due to the different frame dimensions.
