### ISSUE TITLE
Birdseye view that adjusts to available screen width.

### ISSUE THREAD

**Issue by mannp** [blakeblackshear/frigate#1926]
First congrats on the 0.9.x release :) 👍🏻 

I wondered if it would be possible to create the birdseye view based on the available screen width.

For example on a mobile my 6 cameras are tiny images in a 3x2 arrangement, where full width 1×6 would seem more viewable in that instance.

This is also the case if I reduce the size of my desktop browser, the camera images reduce in size in the same  3×2 structure.

Thanks in advance, for considering the request.

**Comment by blakeblackshear** [comment]
I don't think this will be possible because the Birdseye view resolution and layout are determined on the backend.

**Comment by mannp** [comment]
Oh I see, is the layout in the backend a hard restriction, as it seems very restrictive to have web layout decided in the backend rather than the browser.

**Comment by Rogue136198** [comment]
I too would like to see this improved. I run Birdseye on a portrait monitor and when two cameras detect motion they end up arranged horizontally instead of vertically wasting a bunch of screen space.

**Comment by Mincka** [comment]
I also would like the possibility to specify the number of columns for birdseye (on backend side) so I can use it on mobile with a "one-column" mode. However, it means I need to choose between both setups.

To make it even more flexible, it would be even better to declare "virtual cameras" with their own name, their mode `mode: birdseye`, their number of columns `columns: 1`, their included cameras in an ordered list... This concept of virtual cameras could be expanded for other things later. I know that birdseye requires resources but in my case, I still have plenty of resources.

**Comment by NickM-27** [comment]
The UI has been rewritten for the next version of frigate. As part of that the main camera view shows all cameras in a grid that adjusts to the available size. There is also a button on mobile to switch between list and grid. Cameras that are tracking active objects or see motion are live. I believe this satisfies the request to have a birdseye view that adjusts to the browser window.

**Comment by Mincka** [comment]
Can you share a glimpse of this new interface? To better understand what you are saying. Thank you.

**Comment by NickM-27** [comment]
There's not really a good way to share without sharing cameras or showing how it works. Dev builds are made automatically so anyone can try it. It is basically a grid (or list) of cameras. Each camera is either a snapshot or a live view depending on the camera state.

**Comment by Mincka** [comment]
I tried a few days ago but the dev build was trop buggy for me and I had to rollback. Thanks though.

**Comment by NickM-27** [comment]
I'm curious what kinds of bugs were you seeing (ui or backend)?

**Comment by ccutrer** [comment]
I tried it out last week or the week before, but also rolled back. Basically after a day or so all cameras were no longer connected. I figured it's earlier enough in the cycle, and given the ENV var you have to set, I didn't dig into it much, and figured I'd just try again later.

**Comment by NickM-27** [comment]
Yeah, should be a few more weeks and the UI will have feature parity with the old UI and the env var will be removed
