### ISSUE TITLE
Homeassistant autodiscovery

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#194]
Add support for sensors/cameras in HASS via discovery

**Comment by blysik** [comment]
Is this issue for supporting MQTT Discovery? ie, https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by blakeblackshear** [comment]
Yes

**Comment by corgan2222** [comment]
this would be great!

**Comment by miikkajo** [comment]
i made quick hack for MQTT autodiscovery

https://github.com/miikkajo/frigate_MQTT_autodiscovery

it (re)generates binary_sensor and camera snapshot configurations based on config.yml

if someone has suggestions how to use event start/end messages in homeassistant i sure like to hear them

**Comment by Purii** [comment]
Not sure. Is it added or closed?
That would you awesome!

**Comment by blakeblackshear** [comment]
The integration does this better, so this won't be added.
