### ISSUE TITLE
[Support]:  Record only when detect object

### ISSUE THREAD

**Issue by sudheeshb** [blakeblackshear/frigate#1942]
### Describe the problem you are having

 I upgraded to the latest version of Frigate 0.9.1. I also upgraded the add-on in my HA. Everything works fine, but looks recording is always on.   I used the config below from the docs as I do not want 24x7 recording.

record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 10

I noticed recording always happens, only difference is 5 min of recording is retained.  This is  a deal breaker for me as it reduces the life span of my hard disk and I do not want any recording with out motion/object detection.

Is there any way to avoid this unwanted writing to hard disk?.  I believe the previous version ( where clips are enabled ) writes to hard disk only when object is detected.  Can any one please confirm?

### Version

0.9.1-800F33E

### Frigate config file

```yaml



### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

AMCREST

**Comment by blakeblackshear** [comment]
Probably in one of the first few 0.9.x releases unless I run into something unexpected.

**Comment by sudheeshb** [comment]
Thanks for your all hard work and a great free nvr product!

**Comment by Joeviocoe** [comment]
I have to say, this is a MAJOR issue that is really understated in the change log.
For a traditional NVR setup with proper hardware (disks designed for 24/7 recording), this may be okay.

Frigate is appealing precisely because it can run on a variety of hardware that's not necessarily designed as an NVR.

@blakeblackshear please, please prioritize this fix.

**Comment by Iceman248** [comment]
I just noticed this issue as well trying to get clips going. I'll be turning off recording until it can be object only. Thanks.

**Comment by blakeblackshear** [comment]
If you haven't already seen it, the 0.10.0 betas address this: https://github.com/blakeblackshear/frigate/releases/tag/v0.10.0-beta4

**Comment by Iceman248** [comment]
> If you haven't already seen it, the 0.10.0 betas address this: https://github.com/blakeblackshear/frigate/releases/tag/v0.10.0-beta4

Thanks, but after trying it, it ignores my masks and I get way too many notifications of objects in masked zones as a result. Whether related, my GPU usage skyrockets, as well as CPU the whole time, so back to stable for me.

**Comment by blakeblackshear** [comment]
@Iceman248 Ignores motion masks or object masks? There is no such thing as "masked zones" in frigate, so I am not sure what you mean. If had previously set values for `frame_height` and/or `contour_area` in your motion config, the release notes for the beta specifically say to remove those.

**Comment by Iceman248** [comment]
Sorry, I just worded it in a way that felt natural to me. I just meant ignores motion masks. It did also ignore an object mask as well. I'm not even sure what those other two values do, so definitely didn't have them set.

**Comment by blakeblackshear** [comment]
I don't see any way the changes for 0.10.0 could cause masks to be ignored. No one else has reported that issue yet, so I would appreciate if you could open an issue with more information so I can help track it down.
