### ISSUE TITLE
Stop running detection on stationary objects

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#195]
For things like parked cars, there is no reason to keep running detection on the car if there is no motion within the bounding box of the car. It should just assume the object is still there.

**Comment by asaupp** [comment]
I disabled car tracking in my front yard - as my parked car would generate far more videos than any person / cat / .. really moving through.
I'm speculating here - but quite some of those 'parked car videos' contain a bypassing car on the street. The street is masked in both, object filter car + motion.

**Comment by blakeblackshear** [comment]
Motion masks are not object masks.

**Comment by asaupp** [comment]
>edit: I see you defined both. The object masks operate based on the bottom center of the bounding box. Are you certain that point is within the mask?

The mask works perfect for pedestrians, after some fine tuning its very precise, so I believe the mask is correct, yes. 
On the other hand cats/persons are different from cars, as I don't have a lot of them standing in my frontyard for hours. 

I saw your post in another topic - i might re-enable with bounding boxes to figure which of the two scenarios is right:
 - another car enters the scene and something happens / confuses
 - my car sits there motionless, but somehow frigate looses track long enough to redetect as new object.

**Comment by Trashmee** [comment]
I disabled car tracking in my front yard - as my parked car would generate far more videos than any person / cat / .. really moving through. I'm speculating here - but quite some of those 'parked car videos' contain a bypassing car on the street. The street is masked in both, object filter car + motion.

> edit: I see you defined both. The object masks operate based on the bottom center of the bounding box. Are you 
> certain that point is within the mask?

The mask works perfect for pedestrians, after some fine tuning its very precise, so I believe the mask is correct, yes.
On the other hand cats/persons are different from cars, as I don't have a lot of them standing in my frontyard for hours.

I saw your post in another topic - i might re-enable with bounding boxes to narrow down the scenario:
- another car enters the scene and something happens / confuses detection
- my car sits there motionless & illuminated, but somehow frigate looses track long enough to redetect as new object.

**Comment by NickM-27** [comment]
> It's sort of ridiculous that it keeps detecting my parked car. Why Frigate is concerned with stationary objects to begin with is beyond me.

All objects should remain tracked otherwise frigate will pick that vehicle up again when motion happens around it and treat it as a new event when it's actually not.

There's no consequences to tracking stationary objects as it is efficient and enables finer control of what gets recorded https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean

**Comment by Wheemer** [comment]
What frigate must track to do it's job properly is not something the user should be bombarded with. Dozens of events about stationary things is preposterous. How about the program work intuitively out of the box without users having to fix it's quirks just to get something that's not overly annoying?

**Comment by NickM-27** [comment]
> What frigate must track to do it's job properly is not something the user should be bombarded with. Dozens of events about stationary things is preposterous. How about the program work intuitively out of the box without users having to fix it's quirks just to get something that's not overly annoying?

Not sure what you're referring to exactly. There's no reason a user needs to be "bombarded" with notifications. There's countless notifications blueprints for HA and a guide I wrote https://github.com/blakeblackshear/frigate/discussions/2898 that properly setup notifications that and don't sent notifications for stationary objects. 

If you're going to setup notifications yourself then you should be aware of how the system works and account for it. All of this is in the documentation.

**Comment by Wheemer** [comment]
You seems to have blinders on concerning this issue. I am talking about events within Frigate, not HA. I see loads of useless events for a stationary car. These events and recordings are a waste of energy and resources and should be fixed instead of being called a feature. You might need to step back from the code to get a normal perspective every now and then.

**Comment by NickM-27** [comment]
> You seems to have blinders on concerning this issue. I am talking about events within Frigate, not HA. I see loads of useless events for a stationary car. These events and recordings are a waste of energy and resources and should be fixed instead of being called a feature. You might need to step back from the code to get a normal perspective every now and then.

Ah I see, I misunderstood what you were referring to. In that case you probably don't have frigate configured properly so it's creating multiple events, when the expected behavior is to have one event the whole time the car is there. If you create a support issue we'd be happy to help make suggestions.

**Comment by Wheemer** [comment]
There should not be complication involved or a special setup required for stationary objects to be redetected over and over. Why it has the need to record video of stationary items to begin with seem counter intuitive. If I have to jump through hoops to make Frigate behave normally then that would mean there is an unresolved issue that needs attention. This should never be a user issue. I just set this software up and it has no special configuration. All I know is I have numerous recordings of no movement other than drifting snow, and it keeps identifying my stationary car. It would be nice if there was just a simple option to stop all detection of anything that doesn't move. A security system that detects things that do not move is the exact opposite of what I or anyone desires.
