### ISSUE TITLE
[Support]: Frigate responsible for .deleted hidden folder with retention?

### ISSUE THREAD

**Issue by acateon** [blakeblackshear/frigate#1972]
### Describe the problem you are having

Dont know if this is a system or Frigate issue but my share with Frigate video keeps filling up a hidden .deleted folder with the same structure as the default frigate video directory.

The directory keeps on growing until I run out of disk space. Is this some function of Frigate?

### Version

0.9.1-800F33E

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink

**Comment by blakeblackshear** [comment]
Frigate does not do anything like this.

**Comment by acateon** [comment]
> Frigate does not do anything like this.

Thanks for the quick reply, indeed is some issue between the host running frigate and the storage solution.
