### ISSUE TITLE
Use a different training dataset for detection

### ISSUE THREAD

**Issue by eddyg** [blakeblackshear/frigate#1978]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to better detect people from black and white images so that I can receive more reliable “person” alerts when cameras are in “night mode”.

**Describe the solution you'd like**
Specifically, I’m interested in seeing how the training data from https://gitlab.com/Curid/TF-CCTV performs.

**Describe alternatives you've considered**
I am very new to Frigate and AI-powered object detection from CCTV cameras (just a couple weeks since I started with Frigate), so I haven’t explored alternatives other than “googling around”.

**Additional context**
I was mostly curious about how hard it would be to use the TF-CCTV training data in Frigate (knowing that it will only return “person” objects if it’s swapped out completely), while still retaining the benefits of Coral acceleration.

I use Home Assistant extensively, so Frigate’s integration is a major factor. I am trying to improve motion detection notifications. Before Frigate, things like changes in sun/cloud conditions causing shadows to appear and disappear, wind blowing plants and trees, cameras switching between day/night modes, insects flying in front of the camera, etc. caused “nuisance” notifications with regular motion detection, even with various masks. Frigate improved things a lot, but now I’m _missing_ some things that should’ve been detected.

**Comment by blakeblackshear** [comment]
I'm planning to develop something similar myself. I haven't tried this one, but you may be able to get it work in Frigate as is.

**Comment by ozett** [comment]
first model with erson only seem to be trained:
https://gitlab.com/Curid/TF-CCTV/-/tree/master/#cctv3
