### ISSUE TITLE
[Support]: Detections are not stored

### ISSUE THREAD

**Issue by aasimenator** [blakeblackshear/frigate#1981]
### Describe the problem you are having

I have a single Hikvision DS-2CD1343G0E-I IP-based camera mounted at the main entrance of my apartment.
I am running HomeAssistant version core-2021.10.2 which is latest along with the latest version of Frigate
The issue is that any person that comes into the frame is not being logged or stored. I don't want a continuous recording, I only want motioned-based detections and alerts that too if it's a person.
Below is my config file and all details I could find.

As you can see in the below screenshot, it detected the person
![image](https://user-images.githubusercontent.com/49643079/136705083-6cd37dcf-ede6-479e-95d1-f9dda5639dc7.png)
But when I go into Events I see nothing
![image](https://user-images.githubusercontent.com/49643079/136705324-3b5ace9f-7c7c-4b91-a482-2c74a487eed4.png)

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: 192.168.192.31
  user: aasim
  password: pppppassss
cameras:
  MainDoor_Cam:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://viewer:password@ipaddress:554/Streaming/Channels/101
          roles:
            - detect
    objects:
      track:
      - person
detectors:
  cpu1:
    type: cpu
    cpu2:
      type: cpu  
detect:
  enabled: True
  max_disappeared: 25
```

### Relevant log output

```shell
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "MainDoor_Cam": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 720,
        "max_disappeared": 25,
        "width": 1280
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://viewer:password@ipaddress:554/Streaming/Channels/101",
            "roles": [
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://viewer:password@ipaddress:554/Streaming/Channels/101 -r 5 -s 1280x720 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 99,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "MainDoor_Cam",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": 25,
    "width": 1280
  },
  "detectors": {
    "cpu1": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "ipaddress",
    "password": "password",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "aasim"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### FFprobe output from your camera

```shell
ffprobe 'rtsp://viewer:password@ipaddress:554/Streaming/Channels/101'
ffprobe version 4.1.6-1~deb10u1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 1 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 3 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 3 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 3 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 2 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 1 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 3 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 2 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 1 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 2 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 1 packets
[rtsp @ 0x55cce253c000] max delay reached. need to consume packet
[rtsp @ 0x55cce253c000] RTP: missed 2 packets
Input #0, rtsp, from 'rtsp://viewer:password@ipaddress:554/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.100000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 2560x1440, 20 tbr, 90k tbn, 90k tbc
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD1343G0E-I 

### Any other information that may be helpful

The issue is that any person that comes into the frame is not being logged or stored. I don't want a continuous recording, I only want motioned-based detections and alerts that too if it's a person.

**Comment by blakeblackshear** [comment]
You have to enable snapshots or record in your config. Otherwise there is nothing to save for the detection.

**Comment by aasimenator** [comment]
I made the following change in the config file, the documentation is not that good in terms of giving examples of what needs to be set. 

`record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 30`

Now when I go into events I can see the person being detected 
![image](https://user-images.githubusercontent.com/49643079/136799688-65bf4f02-2373-4d99-bc02-46720503e06a.png)

But what I don't see, is the video of it
![image](https://user-images.githubusercontent.com/49643079/136799793-bf9bedc9-6a7e-47ff-8ad6-cff9808d261b.png)

If I download the clip it gives me a "clip.html" file with the error "Couldn't download - Something went wrong."
![image](https://user-images.githubusercontent.com/49643079/136799952-453c489c-6a90-408d-833f-26f3477529b8.png)

**Comment by aasimenator** [comment]
@blakeblackshear  I changed it back to H.264 in the camera settings but still not able to play new recordings that was created after the change. 
![image](https://user-images.githubusercontent.com/49643079/136901040-f46dadbd-bf58-4a75-b119-cf020cee25b8.png)

I am using Windows 10 PC with Microsoft Edge, but Also tried on my Android 11 OnePlus 8T

**Comment by aasimenator** [comment]
Also is there any place where I can request a new feature? I would like to have multiple selection options available for selecting and deleting those events, instead of deleting each single one individually.

**Comment by aasimenator** [comment]
@tovmax 
I removed all the hardware acceleration part, now my config is like this
![image](https://user-images.githubusercontent.com/49643079/137275506-780b6167-e0e4-4e80-adbc-ca10447fb058.png)

but now I get the following error:

[2021-10-14 13:25:56] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e)
Error parsing config: 1 validation error for FrigateConfig
cameras -> MainDoor_Cam -> ffmpeg -> inputs -> 0 -> roles -> 2
  value is not a valid enumeration member; permitted: 'record', 'rtmp', 'detect' (type=type_error.enum; enum_values=[<CameraRoleEnum.record: 'record'>, <CameraRoleEnum.rtmp: 'rtmp'>, <CameraRoleEnum.detect: 'detect'>])
[cmd] python3 exited 1

**Comment by aasimenator** [comment]
> Seems like "snapshots" cannot be declared in the "roles" block

Yes, but why?

**Comment by blakeblackshear** [comment]
If you set retain_days to 5, can you view recordings? Do you see files being created in the recordings folder? Have you looked at your logs after the changes you made recently?

**Comment by blakeblackshear** [comment]
Can you confirm the missing file mentioned in the logs is actually there?

**Comment by aasimenator** [comment]
Yes the file exists in the folder
![image](https://user-images.githubusercontent.com/49643079/137432941-ebecec7d-42bd-4bb5-85f1-25b0ff8918fa.png)

**Comment by blakeblackshear** [comment]
In your reply, you posted the output from a different URL than what I asked for [here](https://github.com/blakeblackshear/frigate/issues/1981#issuecomment-944281637). I am trying to match the error message you see in the logs with the requested URL.

**Comment by aasimenator** [comment]
> In your reply, you posted the output from a different URL than what I asked for [here](https://github.com/blakeblackshear/frigate/issues/1981#issuecomment-944281637). I am trying to match the error message you see in the logs with the requested URL.
I had cleaned and rebuilt it over the weekend, It didn't help one bit, that error didn't occur again though, not for any directory but I am still unable to play videos but nothing is logged in the Log
![image](https://user-images.githubusercontent.com/49643079/140688581-7fa34277-2e0c-4285-94d5-3556067d9fdd.png)

**Comment by blakeblackshear** [comment]
Are there files in the recordings folder that match the time of the event?

**Comment by aasimenator** [comment]
@blakeblackshear 
Yes, They are there... here is another example..,
![image](https://user-images.githubusercontent.com/49643079/140790397-cf6514db-96fa-41da-b70f-aea947179e28.png)
When I hit play, it fails
![image](https://user-images.githubusercontent.com/49643079/140790428-cec8d640-8a12-45de-adbc-30470834bbad.png)

But when I go into 'Media Browser' and into the correct folder I can see and play those recordings
![image](https://user-images.githubusercontent.com/49643079/140790545-3ce6c615-7ff4-4842-8029-fef02b767eb8.png)

So it's only Frigate that is having a problem playing or processing or converting or whatever it is trying to do to play the video. the events are being recorded and are available for playback from Media Browser not through Frigate.

**Comment by blakeblackshear** [comment]
In the media browser you are viewing the files directly. Can you also try with frigate's media browser provided by the integration?

Do you know how to get a bash prompt inside the frigate container? There is another log file we can check if so.

**Comment by aasimenator** [comment]
@blakeblackshear how do i access the frigate media browser?
is the command below, what you are looking for? 
`docker exec -it <container name> /bin/bash`

**Comment by blakeblackshear** [comment]
If you have the [integration](https://github.com/blakeblackshear/frigate-hass-integration) installed, it should show up automatically.

Let's check the log file at `/usr/local/nginx/logs/error.log` after you try and play a file.

**Comment by aasimenator** [comment]
I have it installed via the "Supervisor"
![image](https://user-images.githubusercontent.com/49643079/140933479-27189c37-2d23-469a-b6c7-bf5184e03dfc.png)
If the below is the media browser you are talking about then it cannot also play video
![image](https://user-images.githubusercontent.com/49643079/140933611-e03ed34c-a268-488c-ae72-c32d8c030ea4.png)

I can see the log files at `/usr/local/nginx/logs/error.log ` but it's empty.
access.log has data

**Comment by blakeblackshear** [comment]
You have the "Addon" installed via the supervisor which runs Frigate and adds it to the side panel, but doesn't integrate into Home Assistant. That is quite different than the "Integration". You are missing out on one of the best parts of Frigate by not integrating it.

The media browser from the integration looks like this:
![image](https://user-images.githubusercontent.com/569905/140936629-afb3c81e-14c5-4285-82c1-f226e2525f26.png)

Can you see what the errors are in the browser console (right click > inspect).

**Comment by aasimenator** [comment]
I don't need to integrate it into HA right now. I am only using Frigate for its event recording, I currently have no use for any sort of automations and triggers right now. 

The following are the errors in the browser console.
![image](https://user-images.githubusercontent.com/49643079/140969927-613aee38-ee7a-40c7-880c-20b9c7a03b22.png)
![image](https://user-images.githubusercontent.com/49643079/140970270-256a7098-712b-4aad-af07-439d54d5753a.png)

**Comment by blakeblackshear** [comment]
Hmm. The console error isn't helpful. There aren't any errors in the Frigate logs or the nginx error.log either. This seems like an issue with the way the VOD nginx module is parsing the segments to create a playlist. Normally that would result in some errors in the nginx error.log file. Do you see the requests with a non-200 status code in the access.log file?

**Comment by aasimenator** [comment]
Today when I looked in the error.log file I saw one error
`2021/11/09 16:54:13 [warn] 203#203: *7566 an upstream response is buffered to a temporary file /usr/local/nginx/proxy_temp/1/00/0000000001 while reading upstr", host: "EXTERNALDNSNAME", referrer: "http://EXTERNALDNSNAME/recording/MainDoor_Cam"
`
As for the access.log
`IP - - [03/Nov/2021:07:47:44 +0000] "GET // HTTP/1.1" 200 670 "http://192.168.192.31:8123/ccab4aaf_frigate" "Mozilla/5.0 (Linux; Android 11; KB2001) >
IP - - [03/Nov/2021:07:47:44 +0000] "GET /api/config HTTP/1.1" 200 4231 "http://192.168.192.31:8123/api/hassio_ingress/P5R7-VC8FIUPTGKqr71e45Zgq-R-6O>
IP- - [03/Nov/2021:07:47:44 +0000] "GET /api/config HTTP/1.1" 200 4231 "http://192.168.192.31:8123/api/hassio_ingress/P5R7-VC8FIUPTGKqr71e45Zgq-R-6O>
IP - - [03/Nov/2021:07:47:44 +0000] "GET /api/MainDoor_Cam/latest.jpg?h=213 HTTP/1.1" 200 9076 "http://192.168.192.31:8123/api/hassio_ingress/P5R7-VC>
IP - - [03/Nov/2021:07:47:45 +0000] "GET /api/MainDoor_Cam/person/best.jpg?crop=1&h=150 HTTP/1.1" 200 1027 "http://192.168.192.31:8123/cameras/MainDo>
IP- - [03/Nov/2021:07:47:48 +0000] "GET /live/MainDoor_Cam HTTP/1.1" 101 59080 "-" "Mozilla/5.0 (Linux; Android 11; KB2001) AppleWebKit/537.36 (KHTM>
IP- - [03/Nov/2021:07:47:48 +0000] "GET /ws HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Linux; Android 11; KB2001) AppleWebKit/537.36 (KHTML, like Gecko) Chro>
IP- - [03/Nov/2021:07:48:19 +0000] "GET / HTTP/1.1" 200 608 "-" "HomeAssistantSupervisor/2021.10.8 aiohttp/3.7.4.post0 Python/3.9" "-"
`

**Comment by blakeblackshear** [comment]
All that looks normal. 😕

**Comment by aasimenator** [comment]
What else can I check? I even tried the "Full Access" addin instead of the normal one. same problem with it.

**Comment by NickM-27** [comment]
@aasimenator Did you find a solution? I am having the same issue

**Comment by aasimenator** [comment]
> @aasimenator Did you find a solution? I am having the same issue

Nope, no solution. Just looking and testing other NVR solutions
