### ISSUE TITLE
Better event list management options

### ISSUE THREAD

**Issue by HAOccassionalUser** [blakeblackshear/frigate#1986]
Hi
 I see that the latest version of Frigate has event management where one can view and delete events you dont want to keep. At the moment you have to go through each event and delete them individually
**Describe the solution you'd like**
Enhance delete functionality where I can select multiple events and delete them them all. Often the same event triggers several images. e.g. Car pulls into the drive and person gets out. Once you have viewed the event, it would be good to delete all of at once, rather than individually
**Describe alternatives you've considered**
None
**Additional context**

**Comment by NickM-27** [comment]
The UI has been rewritten for the next version of frigate. As part of that standard, separate objects are grouped together into a single event (so a person delivering a package would be one event). Multiselect to mark as reviewed and delete is also implemented.
