### ISSUE TITLE
Frigate NVR Proxy Failed to install add-on

### ISSUE THREAD

**Issue by SoulReaver-SS** [blakeblackshear/frigate#1989]
I'm having this popup while trying to install Frigate NVR Proxy
Failed to install add-on
The command '/bin/bash -o pipefail -c apt-get -qq update && apt-get -qq install --no-install-recommends -y nginx && (apt-get autoremove -y; apt-get autoclean -y)' returned a non-zero code: 100
![image](https://user-images.githubusercontent.com/5673736/136762263-31e233c3-b500-4b74-9304-45fee87ab69b.png)

I'm running it on Raspberry Pi OS, Home Assistant Supervised, Frigate running standalone via Docker-Compose as it was recommended and trying to connect it to HA via the NVR Proxy. I've already installed Frigate NVR Custom Component from HACS.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.204
  user: homeassistant
  password: {redacted}

cameras:
  Wyze_v3:
    ffmpeg:
      inputs:
        - path: rtsp://SoulReaver:{redacted}@192.168.1.68/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5
motion:
  mask:
    - 0,484,86,844,292,845,442,549,521,518,608,445,617,373,789,377,854,446,1038,440,1041,384,1195,374,1730,446,1773,278,1920,333,1920,0,0,0

record:
  enabled: True
  retain_days: 0
  events:
    retain:
      default: 90

ffmpeg:
  output_args:
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.4
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.6
```

### Relevant log output

```shell
The command '/bin/bash -o pipefail -c apt-get -qq update && apt-get -qq install --no-install-recommends -y nginx && (apt-get autoremove -y; apt-get autoclean -y)' returned a non-zero code: 100
```

### FFprobe output from your camera

```shell
ffprobe version 4.1.6-1~deb10u1+rpt2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm
  WARNING: library configuration mismatch
  avutil      configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avcodec     configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avformat    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avdevice    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avfilter    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avresample  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swscale     configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swresample  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  postproc    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, rtsp, from 'rtsp://SoulReaver:5AhxjM4jJz@192.168.1.68/live':
  Metadata:
    title           : Session streamed by the WYZE Media Server
    comment         : live
  Duration: N/A, start: 0.000188, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 80 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: pcm_alaw, 16000 Hz, 1 channels, s16, 128 kb/s
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Wyze Cam v3

**Comment by SoulReaver-SS** [comment]
> The supervisor logs should have more detail.

It has:

21-10-11 04:43:07 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for ccab4aaf/armv7-addon-frigate-proxy:1.2
21-10-11 04:43:11 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build ccab4aaf/armv7-addon-frigate-proxy:1.2: The command '/bin/bash -o pipefail -c apt-get -qq update     && apt-get -qq install --no-install-recommends -y nginx     && (apt-get autoremove -y; apt-get autoclean -y)' returned a non-zero code: 100
21-10-11 04:43:11 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/19 : ARG BUILD_ARCH
Step 2/19 : FROM ghcr.io/hassio-addons/debian-base/${BUILD_ARCH}:5.1.0
 ---> fc0e15d45bb7
Step 3/19 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> 23133fc24572
Step 4/19 : RUN apt-get -qq update     && apt-get -qq install --no-install-recommends -y nginx     && (apt-get autoremove -y; apt-get autoclean -y)
 ---> Running in 4ceffa5b4933
W
: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.


E
: 
The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.

W
: 
GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.


E
: 
The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.


W
: 
GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.

E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.

Removing intermediate container 4ceffa5b4933

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate-hass-addons/issues/44

**Comment by Ixian** [comment]
You don't really need to set that port, that's for addons you may want to access outside home assistant. Since the Proxy is already fronting an external Frigate service this option is redundant. The Proxy addon is really meant to be used with Home Assistant's Ingress (which itself is a reverse proxy :) ) so that you can access it from within Home Assistant's UI/User Authentication either locally or remotely.

You should be able to leave the port blank for that setting.

**Comment by Ixian** [comment]
What other addons are you running? Seems like something is conflicting. 

I've been using the Proxy since release without issue (I run HA via Home Assistant OS on an ODroid N2+, and Frigate on a Pi 4) so there's something in your setup causing this we need to ferret out.

**Comment by Ixian** [comment]
Are you using Firefox? There's a known issue with HA Ingress and Firefox where you have to disable enhanced tracking for the page in order for Ingress to work.

**Comment by SoulReaver-SS** [comment]
I thought about checking the logs and it says:

21-10-12 04:04:01 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:04:01 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:04:02 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:04:04 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:06:04 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy

**Comment by blakeblackshear** [comment]
Anything else in the logs to indicate what the problem was?

**Comment by SoulReaver-SS** [comment]
> Anything else in the logs to indicate what the problem was?

It keeps showing those same lines over and over again:
21-10-12 04:10:07 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy
21-10-12 04:10:48 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:10:49 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:10:51 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:12:07 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:12:07 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:12:08 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:12:09 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:14:09 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy
21-10-12 04:16:09 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:16:09 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:16:10 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:16:12 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:18:12 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy
21-10-12 04:20:12 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:20:12 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:20:12 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:20:14 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:22:14 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy
21-10-12 04:24:14 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:24:14 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:24:15 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:24:17 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:26:17 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy
21-10-12 04:28:17 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:28:17 INFO (SyncWorker_2) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:28:18 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:28:20 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:30:20 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy
21-10-12 04:32:20 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:32:20 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:32:21 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:32:22 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:34:22 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy
21-10-12 04:36:22 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate-proxy application!
21-10-12 04:36:22 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_ccab4aaf_frigate-proxy application
21-10-12 04:36:23 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate-proxy application
21-10-12 04:36:25 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ccab4aaf/armv7-addon-frigate-proxy with version 1.2
21-10-12 04:38:25 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missing application response from ccab4aaf_frigate-proxy

**Comment by blakeblackshear** [comment]
Try turning off the watchdog.

**Comment by blakeblackshear** [comment]
And the addon logs don't show anything? Does it stay running?

**Comment by blakeblackshear** [comment]
Is the addon show that it's still running?

**Comment by SoulReaver-SS** [comment]
> Is the addon show that it's still running?

It says it's:
![image](https://user-images.githubusercontent.com/5673736/137201737-44a03ad6-dfeb-4f02-acef-9e58f10088ea.png)
