### ISSUE TITLE
Adjustable motion detection

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#201]

**Comment by hawkeye217** [comment]
Noticed you had this on the roadmap for 0.8.0.  I had mentioned on the HA forums that it would be great to be able to generate clips/recordings for motion detection even where no object was detected.  Should I open a separate issue for that or does this one cover that use case?  Thanks!

**Comment by blakeblackshear** [comment]
Separate issue. Thanks.

**Comment by hawkeye217** [comment]
Great. I'll make one right now. Thanks Blake!
