### ISSUE TITLE
Web UI Password protection

### ISSUE THREAD

**Issue by scorpio862** [blakeblackshear/frigate#2014]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to restrict the access to Frigate web UI. At the moment anybody connected to the local network can just access the Frigate page and view the cameras and disable the detection or recording. I really don't want that as it is not secure.

**Describe the solution you'd like**

Frigate web UI needs a login/password authentication.
Alternatively something like IP filtering would help to allow connection only from specific IP addresses.

**Comment by mitchross** [comment]
Just use Authelia with Ngnix Reverse Proxy Or Traefik Forward Auth.

You can also use Cloudflare access too.

**Comment by scorpio862** [comment]
If I wanted to expose Frigate to the web, I could use Authelia with NginX, but all I want is to restract the access throuth the lan address.

For example I installed Frigate at work for security reasons, so all the security cameras are connected. I don't want all the employees  who have an access to LAN, to be able to see the security cameras feed.

**Comment by abensimon86** [comment]
> If I wanted to expose Frigate to the web, I could use Authelia with NginX, but all I want is to restract the access throuth the lan address.
> 
> For example I installed Frigate at work for security reasons, so all the security cameras are connected. I don't want all the employees who have an access to LAN, to be able to see the security cameras feed.

Hey
I have same problem here
What the solution do you used?
