### ISSUE TITLE
Macrofilter for animals

### ISSUE THREAD

**Issue by mrwiwi** [blakeblackshear/frigate#2016]
**Describe what you are trying to accomplish and why in non technical terms**

I use frigate to track cats that pee on my house at night and attack the rabbit the day... But detection is not flawless because of a lot of parameters, so I have to use dog and cat detect... And I tried bear and it find cats as bear too ! (Which I probably did miss before - because no bear here)

**Describe the solution you'd like**

Simple : make all animals detectable by label "animal" (don't care if it's a cat, dog, horse or bear ;) as a "superlabel"

So I get all animals in events !

**Additional context**
/

Thanks for all the Ork, awesome solution !

**Comment by blakeblackshear** [comment]
This is already possible. https://docs.frigate.video/configuration/advanced#model
