### ISSUE TITLE
View entire image not only object focus crop

### ISSUE THREAD

**Issue by CarpeDiemRo** [blakeblackshear/frigate#2033]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to view and receive the entire image so that I can see better what is happening

**Describe the solution you'd like**
When Frigate detects an object, for example, a person I would like to receive on Telegram. the entire image in a similar way that Deepstack does. In 1980 x 1080 resolution when the object is quite far, it is hard to see what was happening there and the visual context is missing.
 ex.

Deepstack image
![2021-10-17 15 20 13](https://user-images.githubusercontent.com/38489167/137626993-75299baf-afe0-4ee2-9ba0-7a7c923c3ce4.jpg)

vs 

Frigate

![2021-10-17 15 18 28](https://user-images.githubusercontent.com/38489167/137627003-f9a8bfb5-b0b7-40ac-baee-a4b24fbbde93.jpg)

In this case, the viewer is not able to distinguish clearly, at a glance what is happening. More than that, the image is cropped and the magnification is impossible.

**Describe alternatives you've considered**
A full image with boundary boxes or any highlighted feature.

**Additional context**
Maybe the feature is already implemented and I haven't discovered it yet. 
Another improvement would be to have all the people detected on one image, not one cropped image for each object.
For instance, if an image contains 4 people, now, I'm receiving 4 different images, with all the objects detected separately.
I think I could be better to receive only one image with all the object highlighted.

**Comment by CarpeDiemRo** [comment]
...so I will receive 4 full snapshots for each detected object. Right?

**Comment by blakeblackshear** [comment]
yea, but they may not all be the exact same frame. it will select the best frame for each object individually.
