### ISSUE TITLE
Coral EdgeTPU gets crazy on container restart

### ISSUE THREAD

**Issue by mario-tux** [blakeblackshear/frigate#204]
**Describe the bug**
Recently it occasionally happens that when Frigate container restart (configuration change, image upgrade, ...) the Coral EdgeTPU (USB version) is not recognized until a physical unplug/replug of the device.

**Version of frigate**
0.6.0-rc2 (I don't remember such behavior in 0.5.2 and previous)

**Config file**
I'm not using recent option to select the edgetpu device.

**Logs**
Correct startup:
```
 * Serving Flask app "detect_objects" (lazy loading),
 * Environment: production,
   WARNING: This is a development server. Do not use it in a production deployment.,
   Use a production WSGI server instead.,,
 * Debug mode: off,
d
```

Failing one:
```
 * Serving Flask app "detect_objects" (lazy loading),
 * Environment: production,
   WARNING: This is a development server. Do not use it in a production deployment.,
   Use a production WSGI server instead.,
 * Debug mode: off,
Attempting to load TPU as pci:0,
No EdgeTPU detected. Falling back to CPU.,
```

**Computer Hardware**
 - OS: Alpine
 - Virtualization: none
 - Coral Version: USB
 - Network Setup: Wired

Does something change in recent commits that could be the cause? Any way to gracefully release the Coral EdgeTPU on stop/restart of container?

**Comment by blakeblackshear** [comment]
This was actually a known issue in earlier versions. 0.6.0 is the first version that tries to gracefully exit. I would ensure your Coral is getting sufficient power.

**Comment by mario-tux** [comment]
The device is plugged on a USB-3 port of a full size desktop. When the device is recognized it never stops: insufficient power should cause problem on run too, right?

**Comment by mario-tux** [comment]
If you think that there is nothing from the software-side that can give a more safe device restart, you can close this report.

**Comment by blakeblackshear** [comment]
Do the logs show a successful exit of the old container?

**Comment by mario-tux** [comment]
> Do the logs show a successful exit of the old container?

I don't remember a specific error message before the already reported piece of log (they are generate by the new instance). When at home, I can try to reproduce the problem (wild restarts) and try to catch some specific message. Is it possible (and useful) to activate some kind of debug/verbose logging in Frigate activities?

**Comment by blakeblackshear** [comment]
There isn't any more verbose logging at the moment. I would also try seeing if adding a delay before the new container starts prevents it from happening.
