### ISSUE TITLE
[Support]: How to change default media folder for restoring clips, recordings, snapshots

### ISSUE THREAD

**Issue by sneekerzzz** [blakeblackshear/frigate#2062]
### Describe the problem you are having

I would like to know if its possible to change the default MEDIA folder to another mounted folder?

### Version

2.0

### Frigate config file

```yaml
Irrelevant
```

### Relevant log output

```shell
Irrelevant
```

### FFprobe output from your camera

```shell
Irrelevant
```

### Frigate stats

```json
Irrelevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

Not at this moment

**Comment by fwestenberg** [comment]
I have the same question actually. My Home Assistant is running on HassOs, and I use the media folder for other stuff. I have mounted a separate USB drive for Frigate recordings and events. (used the _Samba NAS addon_ to mount it). Is there a possibility to change the storage location from media to <usb1>? 
Thanks for the help, I really like the Frigate addon a lot!

**Comment by NickM-27** [comment]
@fwestenberg Please see the docs: https://docs.frigate.video/installation#home-assistant-operating-system-hassos

> Due to limitations in Home Assistant Operating System, utilizing external storage for recordings or snapshots requires [modifying udev rules manually](https://community.home-assistant.io/t/solved-mount-usb-drive-in-hassio-to-be-used-on-the-media-folder-with-udev-customization/258406/46).
> If possible, it is recommended to run Frigate standalone in Docker and use [Frigate's Proxy Addon](https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate_proxy/README.md).

**Comment by fwestenberg** [comment]
Thanks, after a lot of trial and error I ended up with this solution:

1. Under <hassaddress>:8123/config/hardware -> hamburger menu -> all hardware, find the USB drive's partition label. Look for the tag: "/dev/disk/by-label/`<YOUR LABEL>`".
2. Format an USB stick to FAT32 format, name the stick CONFIG and create a folder _udev_.
3. Create the file below and replace the text `<YOUR LABEL>` with the label from step 1. Name the file something like mount_frigate_usb.rules or something else useful.
4. Insert the USB, navigate to <hassaddress>:8123/hassio/system/info. In the Host box, look at the bottom for Reboot Host & Shutdown Host buttons - to the right is a burger menu, click this and ‘Import for USB’

After a while, the USB drive will be mounted to the media/frigate location and frigate will use this folder for the recordings etc. 

```

# Filter on block devices, exit otherwise
# CAUTION: Change to 'sd[b-z][0-9]' if booting from a USB drive (e.g.: sda)
KERNEL!="sd[b-z][0-9]", GOTO="abort_rule"

# Skip none USB devices (e.g.: internal SATA drive)
ENV{ID_PATH}!="*-usb-*", GOTO="abort_rule"

# Import the partition info into the environment variables
IMPORT{program}="/usr/sbin/blkid -o udev -p %N"

# Exit if partition is not a filesystem
ENV{ID_FS_USAGE}!="filesystem", GOTO="abort_rule"

# Exit if this is the 'CONFIG' USB key
ENV{ID_FS_LABEL}=="CONFIG", GOTO="abort_rule"

# Only applies for this HDD partition
ENV{ID_FS_LABEL}!="<YOURLABEL>", GOTO="abort_rule"

# Get the partition name if present, otherwise create one
ENV{ID_FS_LABEL}!="", ENV{dir_name}="%E{ID_FS_LABEL}"
ENV{ID_FS_LABEL}=="", ENV{dir_name}="usb-%k"

# Determine the mount point
ENV{mount_point}="/mnt/data/supervisor/media/frigate"

# If filesystem is ntfs, use the ntfs3 driver, so we get rw support
# Home Assistant Operating System 8.0 or later required (linux kernel 5.15)
ENV{ID_FS_TYPE}=="ntfs", ENV{fstype}="-t ntfs3"
ENV{ID_FS_TYPE}!="ntfs", ENV{fstype}="-t auto"

# Mount the device on 'add' action (a.k.a. plug the USB drive)
ACTION=="add", RUN{program}+="/usr/bin/mkdir -p %E{mount_point}", RUN{program}+="/usr/bin/systemd-mount %E{fstype} --no-block --automount=no --collect $devnode %E{mount_point}"

# Umount the device on 'remove' action (a.k.a unplug or eject the USB drive)
ACTION=="remove", ENV{dir_name}!="", RUN{program}+="/usr/bin/systemd-umount %E{mount_point}", RUN{program}+="/usr/bin/rmdir %E{mount_point}"

# Exit
LABEL="abort_rule"
```

Sources:
https://community.home-assistant.io/t/solved-mount-usb-drive-in-hassio-to-be-used-on-the-media-folder-with-udev-customization/258406/68

https://github.com/home-assistant/operating-system/blob/dev/Documentation/configuration.md
