### ISSUE TITLE
Make timeout of object detection configurable per camera

### ISSUE THREAD

**Issue by hawkeye217** [blakeblackshear/frigate#207]
Per this post: https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/1779

It'd be great to be able to change how many frames it takes for Frigate to determine when an object has disappeared.  Even with my 3fps cameras (without ``-vsync drop`` and explicitly set at ``-f 3``) Frigate seems to be frame hungry and I see frame rates increase to the point that objects that should technically take ~3 seconds to mark as no longer there seem to disappear in less than a second, thus causing a quick flip of my binary sensor in HA.

**Comment by hawkeye217** [comment]
Yes, I still have the problem even with ``fps`` set in the config.  I have 2 cameras that are super cheap, non-RTSP cameras - the input stream to ffmpeg is actually an mjpeg stream.  There's no issue with my other RTSP camera on Frigate.

**Comment by mario-tux** [comment]
> Yes, I still have the problem even with `fps` set in the config. I have 2 cameras that are super cheap, non-RTSP cameras - the input stream to ffmpeg is actually an mjpeg stream. There's no issue with my other RTSP camera on Frigate.

Where did you add the `-r <fps>` option? in the `input_args` or `output_args`.

**Comment by hawkeye217** [comment]
I just added the ``-r <fps>`` to the ``output_args`` and am testing it now.  If that fixes the issue, great.  It would still be helpful to have the frame count configurable, however.

**Comment by mario-tux** [comment]
it was recently readded: https://github.com/blakeblackshear/frigate/commit/69406343eedc7ca20dce4bd30efc7d32cefe66d2
