### ISSUE TITLE
[Support]: cannot disable protection mode ?

### ISSUE THREAD

**Issue by spacecabbie** [blakeblackshear/frigate#2096]
### Describe the problem you are having

The documents say "disable protection mode" for hw acceleration. (https://docs.frigate.video/configuration/hardware_acceleration)

How even there is toggle switch to do that for the addon.

### Version

0.9.1-800F33E

### Frigate config file

```yaml
Not relevant.
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a

**Comment by ImLovinIt** [comment]
Can you please elaborate where to find/disable  it? Pretty sure the button was visible before the recent HA OS update.

**Comment by blakeblackshear** [comment]
You should see several different Addon versions in the repo now. Do you have the one called `Frigate NVR (Full Access)` installed?
