### ISSUE TITLE
Run FFmpeg in a separate process to leverage hardware acceleration

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#21]
I was looking into support for hardware accelerated decoding and realized that OpenCV doesn’t use the hardware acceleration built into FFmpeg. I did some basic tests, and it makes a substantial difference. On the laptop where I am running frigate, decoding a 25FPS 1080p stream uses about 25% of a single CPU. Switching FFmpeg to use hardware acceleration drops that to <2%. I can read raw frames form a separate FFmpeg process like [this](https://github.com/kkroening/ffmpeg-python/blob/master/examples/tensorflow_stream.py). Once I add support for this, even low powered machines should be able to perform object detection on many cameras.

**Comment by blakeblackshear** [comment]
I am running all containers on CoreOS, and the kernel doesnt support video drivers. I will either need to build a custom CoreOS image like [this](https://blog.thesparktree.com/customize-coreos-kernel-part-2) or use a separate machine.

**Comment by cwhits** [comment]
I too am running CoreOS and am _extremely_ interested in where you get with this!

**Comment by blakeblackshear** [comment]
At the moment, I think it is more likely that I will run this on a separate device. I love CoreOS for the seamless automatic updates, and maintaining a custom OS build would defeat the purpose for me.

**Comment by cwhits** [comment]
what about forking something like this? https://github.com/src-d/coreos-nvidia
