### ISSUE TITLE
Add saved clips auto delete and time based file name?

### ISSUE THREAD

**Issue by invinciberry** [blakeblackshear/frigate#211]
**Describe the bug**
This is a feature suggestion, not an actual bug report.

**Version of frigate**
0.6

**Additional context**
I understand the current save clip feature is intended to collect clips for false positives but it works great with home assistant 0.115's media browser to check recent detections. Currently, I am using DirSync to copy the clips from Frigate into Home Assistant's media folder and it works as it is. But it would be great if there is an option to auto delete clips after a configurable amount of time so I don't end up chocking my home assistant and Frigate server with video clips since I use Frigate to do room presence detection though out my house. Naming the video clips by recording time would also be helpful so it will be easier to go back and check each clip.

**Comment by walthowd** [comment]
Can also just put in a script to clean them up after 30 days:

`find /data/clips -type f -mtime +30 -delete`

**Comment by invinciberry** [comment]
> Can also just put in a script to clean them up after 30 days:
> 
> `find /data/clips -type f -mtime +30 -delete`

You mean using corn or DirSync? Sorry, I am a total noob :D

**Comment by jonnyrider** [comment]
I put it in my home assistant config file as a shell command, then run it every night through an automation:

```
shell_command:
  deleteoldclips: find /media/Cameras -name "*.mp4" -type f -mtime +7 -exec  rm  -f {} \;  
```

**Comment by blysik** [comment]
I agree that saved clips and HA media browser is a match made in heaven.  Filenames based on the time stamps would be very helpful when browsing them.  Thanks again for such an awesome tool.

**Comment by blakeblackshear** [comment]
in v0.8.0, I am hoping to develop a custom component that uses the new media browser api to serve up a rich browser for events and historical footage. I haven't dug into it what is possible yet, but take a look at the spotify integration here: https://youtu.be/4tQvMezHJkQ
