### ISSUE TITLE
Home Assistant Notification - Vehicle Entering vs Leaving

### ISSUE THREAD

**Issue by dalewright** [blakeblackshear/frigate#2117]
Hi Blake,

I would love to know if vehicles are entering or leaving in my iOS notifications.

Similar to the way that you can set Frigate to only record if two zones have been entered, I would love to have the option in the Frigate notification blue print to trigger a "Vehicle Entering" notification if the vehicle was tracked from a zone called "Road" and into "Drive". If you just see the vehicle appear in "Drive" zone then assume the vehicle is about to leave.

For the record, I would pay for Frigate if it was not open source. Really excellent solution with so much flexibility.

Cheers

**Comment by blakeblackshear** [comment]
@ryanm101 It's not a bad idea to maintain sort order, but you shouldn't need to for most use cases. You should be able to compare the `before` and `after` values in those fields in the `update` events rather than only looking at the `end` type.

**Comment by blakeblackshear** [comment]
@dalewright can you post your current automation? you should be able to add some conditions to get what you want like [this](https://docs.frigate.video/guides/ha_notifications#conditions)
