### ISSUE TITLE
Possible to turn off/turn on image processing?

### ISSUE THREAD

**Issue by blysik** [blakeblackshear/frigate#213]
Could I have a camera configured in frigate, but off by default.  Then when I trigger Frigate turn the camera on, it would do it's thing, and then later on receive an off command?

The idea is that my cameras have motion detection, but with a lot of false positives.  I could trigger Frigate to start analyzing the video when motion is detected, and then later on, turn it off again.

Is this supported?  I have a Coral ordered, but I my NUC does a lot of stuff, so I want to minimize cpu time.  Thanks!

**Comment by Buzztiger** [comment]
Hmm, afaik Frigate already does motion detection prior to object recognition. Why not turn off the motion detection on the cam instead and let frigate handle the whole process?

**Comment by blysik** [comment]
I'm trying to conserve cpu on my NUC where the docker container would run.

**Comment by blakeblackshear** [comment]
There is a similar request to turn cameras on and off already. The downside will be that frigate uses motion detection to determine where to look for objects. By the time your camera tells frigate to start and it checks for objects, you will likely miss quite a few events. The overhead is pretty low already if you have hwaccel turned on for decoding with ffmpeg. The way I implemented motion detection is light on resources unless you have very high resolution cameras.

**Comment by blysik** [comment]
Thanks for that response.  I will give it a try with the normal workflow, once my Coral gets here.  I'll go ahead and close this out as answered for now, and open a new request if it's something I truly believe is valuable.
