### ISSUE TITLE
[Support]: Camera Recording Schedule

### ISSUE THREAD

**Issue by tjcampanella** [blakeblackshear/frigate#2132]
I am wondering if frigate supports setting a schedule for your cameras. For instance, I am looking to record from say 7am-7pm inside my office. All other time then that I just want motion/object detected recordings saved as clips. Is there any way to do this? I haven't been able to find anything about this. Thank you for any help and this great project.

**Comment by joeShuff** [comment]
I am running frigate in a docker container alongside homeassistant supervised install (I didn't install frigate via HA). Just to clarify this doesn't automate changing what cameras are in frigate or the retain settings, it simply controls turning on/off the 3 options already in frigate UI (detect, recordings and snapshots). 

Toggling these 3 options is just done using the switches that the frigate integration exposes
![image](https://user-images.githubusercontent.com/15524362/139488272-1f308873-5c59-4c0e-bf37-e5d7615d73a8.png)

This means that I can stop recording my indoor cameras during the day (if someone is home), but turn on recordings over night and recordings/detect/snapshots when no one is in the house.

**Comment by tjcampanella** [comment]
@joeShuff Oh ok I think that would be perfect for what I need. Thank you that is also how I intend to install HA and frigate.
