### ISSUE TITLE
Ability to restream birdseye view

### ISSUE THREAD

**Issue by travipross** [blakeblackshear/frigate#2138]
**Describe what you are trying to accomplish and why in non technical terms**
It would be nice to see the birdseye view as its own output stream. For example, by creating camera entities in Home Assistant, one can then connect with the Google Assistant integration to expose Frigate camera streams, enabling "Hey Google, show me the front yard camera on the TV". Having the birdseye view as a camera stream would be great for passive monitoring on a display.

**Describe the solution you'd like**
Ideally, something like adding an `rtmp` role to the birdseye view in the config to enable re-streaming the birdseye feed.

**Describe alternatives you've considered**
Chromecasting the browser tab with Frigate birdseye view. This isn't as easily integrated with other smart home routines though.

**Additional context**
None

**Comment by 654456** [comment]
@felipecrs you can already replace that with the frigate card using birdseye.  Just use birdseye as the 
frigate_camera_name

**Comment by felipecrs** [comment]
> 
> @felipecrs you can already replace that with the frigate card using birdseye.  Just use birdseye as the 
> frigate_camera_name
> 

Hm... this does not seem to work for me. Perhaps I'm missing something?

![Screenshot_2021-10-29-19-49-48-614_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/29582865/139509471-e5f99a41-231d-4a70-b58f-449d8c97e355.jpg)

![Screenshot_2021-10-29-19-49-56-219_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/29582865/139509477-6d8d1b24-c8d7-420a-a291-941aedd7bc00.jpg)

**Comment by felipecrs** [comment]
This is awesome! Thank you for the tip!

![image](https://user-images.githubusercontent.com/29582865/139509960-dca31deb-a8e0-46e9-b1a1-b4f3cead4e38.png)

**Comment by Baumi1245** [comment]
Hi, I think i have the same problem....

I try to get the Birdseye stream like this: rtmp://192.168.125.100:1935/live/Birdseye
...and i absolutly do not know where or how to configure it....

I am using this version "0.9.4-26ae608" with docker on synology.

Thank you very much.

**Comment by felipecrs** [comment]
@Baumi1245 AFAIK this is not yet possible.

**Comment by NickM-27** [comment]
> +1 for this feature. Any updates on if its planned? I'd love to have this as a live RTMP/RTSP stream

This is `pinned` so it has been accepted as a feature that will be done at some point

**Comment by bagobones** [comment]
> @felipecrs you can already replace that with the frigate card using birdseye. Just use birdseye as the frigate_camera_name

Can you clarify that with a YAML example? I don't see a way to get that to work with the frigate custom card.

**Comment by k1n6b0b** [comment]
Since it’s available like this in home assistant I assume it should be simple to expose over RTMP, yes? Is there any workaround outside of hass?

Also the choice of RTMP vs RTSP, RTMP seems to be more a push streamer protocol. RTSP has way more support from what I can see (and is the only option for my Control4 system)

**Comment by NickM-27** [comment]
> Since it’s available like this in home assistant I assume it should be simple to expose over RTMP, yes? Is there any workaround outside of hass?

Not at all, the current RTMP streams are all just restreams from the camera. Birdseye is jsmpeg so sending it via RTMP would require encoding it to h264, pushing it as RTMP, and other detail / challenges that would crop up while implementing since RTMP is so picky with data.

> Also the choice of RTMP vs RTSP, RTMP seems to be more a push streamer protocol. RTSP has way more support from what I can see (and is the only option for my Control4 system)

The goal in a future version is to drop RTMP and use rtsp-simple-server or go2rtc

**Comment by BradleyShaner** [comment]
> 

This would be so nice. I've been struggling to get an RTMP library working in C# so I can write my own desktop camera software!
