### ISSUE TITLE
zone_colors typo

### ISSUE THREAD

**Issue by edk4971** [blakeblackshear/frigate#215]
Hello,
Pulling blackblackshear/frigate:stable. Restarted and got this error in my docker logs:

On connect called,
ffprobe -v panic -show_error -show_streams -of json "http://192.168.0.11:7999/2/source",
Starting detection process: 37,
Attempting to load TPU as usb,
Attempting to load TPU as pci:0,
PCIe TPU found,
{'streams': [{'index': 0, 'codec_name': 'mjpeg', 'codec_long_name': 'Motion JPEG', 'codec_type': 'video', 'codec_time_base': '0/1', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 3840, 'height': 2160, 'coded_width': 3840, 'coded_height': 2160, 'has_b_frames': 0, 'sample_aspect_ratio': '1:1', 'display_aspect_ratio': '16:9', 'pix_fmt': 'yuvj420p', 'level': -99, 'color_range': 'pc', 'color_space': 'bt470bg', 'chroma_location': 'center', 'refs': 1, 'r_frame_rate': '25/1', 'avg_frame_rate': '0/0', 'time_base': '1/25', 'bits_per_raw_sample': '8', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}}]},
eating ffmpeg process...,
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -use_wallclock_as_timestamps 1 -i http://192.168.0.11:7999/2/source -f rawvideo -pix_fmt rgb24 pipe:,
ffprobe -v panic -show_error -show_streams -of json "http://192.168.0.11:7999/1/source",
{'streams': [{'index': 0, 'codec_name': 'mjpeg', 'codec_long_name': 'Motion JPEG', 'codec_type': 'video', 'codec_time_base': '0/1', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 3840, 'height': 2160, 'coded_width': 3840, 'coded_height': 2160, 'has_b_frames': 0, 'sample_aspect_ratio': '1:1', 'display_aspect_ratio': '16:9', 'pix_fmt': 'yuvj420p', 'level': -99, 'color_range': 'pc', 'color_space': 'bt470bg', 'chroma_location': 'center', 'refs': 1, 'r_frame_rate': '25/1', 'avg_frame_rate': '0/0', 'time_base': '1/25', 'bits_per_raw_sample': '8', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}}]},
eating ffmpeg process...,
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -use_wallclock_as_timestamps 1 -i http://192.168.0.11:7999/1/source -f rawvideo -pix_fmt rgb24 pipe:,
Camera_process started for garage: 63,
Starting process for garage: 63,
Camera_process started for backyard: 64,
Starting process for backyard: 64,
Traceback (most recent call last):,
  File "detect_objects.py", line 460, in <module>,
    main(),
  File "detect_objects.py", line 296, in main,
    object_processor = TrackedObjectProcessor(CONFIG['cameras'], client, MQTT_TOPIC_PREFIX, tracked_objects_queue, event_queue, stop_event),
  File "/opt/frigate/frigate/object_processing.py", line 310, in __init__,
    zone_config['color'] = zone_colors[zone_name],
TypeError: list indices must be integers or slices, not str,

**Comment by blakeblackshear** [comment]
Can you post your config?

**Comment by edk4971** [comment]
web_port: 5000

mqtt:
  host: 192.168.3.15
  topic_prefix: frigate
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -vsync
    - drop
#    - -rtsp_transport
#    - tcp
#    - -stimeout
#    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
  output_args:
#    - -vf
#    - mpdecimate
    - -f
    - rawvideo
    - -pix_fmt
    - rgb24
objects:
  track:
    - person
    - bicycle
    - car
    - truck
    - bird
    - cat
    - dog
  filters:
    person:
      min_area: 7000
      max_area: 675000
      threshold: 0.8
    bicycle:
      min_area: 9000
      threshold: 0.8
    car:
      min_area: 25000
      max_area: 400000
      threshold: 0.8
    truck:
      min_area: 30000
      max_area: 45000
      threshold: 0.8
#zones:
#  FYline:
#    garage:
#      # Coordinates can be generated at https://www.image-map.net/
#      coordinates:
#        - 3839,2031
#        - 3471,1224
#        - 3267,825
#        - 3174,597
#        - 2760,558
#        - 2247,528
#        - 1884,537
#        - 1557,549
#        - 1245,573
#        - 1044,597
#        - 726,696
#        - 396,822
#        - 0,1014
#        - 0,2159
#        - 3839,2159
#  BYline:
#    backyard:
#      coordinates:
#        - 3839,996
#        - 3519,774
#        - 3213,555
#        - 2994,435
#        - 2793,327
#        - 2610,237
#        - 2466,177
#        - 2331,129
#        - 2034,120
#        - 1803,123
#        - 1563,129
#        - 1299,156
#        - 1065,198
#        - 801,252
#        - 558,318
#        - 318,384
#        - 120,447
#        - 0,504
#        - 0,2159
#        - 3839,2159
cameras:
  garage:
    ffmpeg:
#      input: rtsp://username:password@192.168.0.32:554/cam/realmonitor?channel=1&subtype=0
      input: http://192.168.0.11:7999/2/source
    snapshots:
      show_timestamp: False
      draw_zones: False
    zones:
      FYLine:
        - 3839,2031
        - 3471,1224
        - 3267,825
        - 3174,597
        - 2760,558
        - 2247,528
        - 1884,537
        - 1557,549
        - 1245,573
        - 1044,597
        - 726,696
        - 396,822
        - 0,1014
        - 0,2159
        - 3839,2159
  backyard:
    ffmpeg:
#      input: rtsp://username:password@192.168.0.31:554/cam/realmonitor?channel=1&subtype=0
      input: http://192.168.0.11:7999/1/source
    snapshots:
      show_timestamp: False
      draw_zones: False
    zones:
      BYLine:
        - 3839,996
        - 3519,774
        - 3213,555
        - 2994,435
        - 2793,327
        - 2610,237
        - 2466,177
        - 2331,129
        - 2034,120
        - 1803,123
        - 1563,129
        - 1299,156
        - 1065,198
        - 801,252
        - 558,318
        - 318,384
        - 120,447
        - 0,504
        - 0,2159
        - 3839,2159

**Comment by edk4971** [comment]
```
web_port: 5000

mqtt:
  host: 192.168.3.15
  topic_prefix: frigate
ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -vsync
    - drop
#    - -rtsp_transport
#    - tcp
#    - -stimeout
#    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
  output_args:
#    - -vf
#    - mpdecimate
    - -f
    - rawvideo
    - -pix_fmt
    - rgb24
objects:
  track:
    - person
    - bicycle
    - car
    - truck
    - bird
    - cat
    - dog
  filters:
    person:
      min_area: 7000
      max_area: 675000
      threshold: 0.8
    bicycle:
      min_area: 9000
      threshold: 0.8
    car:
      min_area: 25000
      max_area: 400000
      threshold: 0.8
    truck:
      min_area: 30000
      max_area: 45000
      threshold: 0.8
#zones:
#  FYline:
#    garage:
#      # Coordinates can be generated at https://www.image-map.net/
#      coordinates:
#        - 3839,2031
#        - 3471,1224
#        - 3267,825
#        - 3174,597
#        - 2760,558
#        - 2247,528
#        - 1884,537
#        - 1557,549
#        - 1245,573
#        - 1044,597
#        - 726,696
#        - 396,822
#        - 0,1014
#        - 0,2159
#        - 3839,2159
#  BYline:
#    backyard:
#      coordinates:
#        - 3839,996
#        - 3519,774
#        - 3213,555
#        - 2994,435
#        - 2793,327
#        - 2610,237
#        - 2466,177
#        - 2331,129
#        - 2034,120
#        - 1803,123
#        - 1563,129
#        - 1299,156
#        - 1065,198
#        - 801,252
#        - 558,318
#        - 318,384
#        - 120,447
#        - 0,504
#        - 0,2159
#        - 3839,2159
cameras:
  garage:
    ffmpeg:
#      input: rtsp://admin:lib53311@192.168.0.32:554/cam/realmonitor?channel=1&subtype=0
      input: http://192.168.0.11:7999/2/source
    snapshots:
      show_timestamp: False
      draw_zones: False
    zones:
      FYLine:
        - 3839,2031
        - 3471,1224
        - 3267,825
        - 3174,597
        - 2760,558
        - 2247,528
        - 1884,537
        - 1557,549
        - 1245,573
        - 1044,597
        - 726,696
        - 396,822
        - 0,1014
        - 0,2159
        - 3839,2159
  backyard:
    ffmpeg:
#      input: rtsp://admin:lib53311@192.168.0.31:554/cam/realmonitor?channel=1&subtype=0
      input: http://192.168.0.11:7999/1/source
    snapshots:
      show_timestamp: False
      draw_zones: False
    zones:
      BYLine:
        - 3839,996
        - 3519,774
        - 3213,555
        - 2994,435
        - 2793,327
        - 2610,237
        - 2466,177
        - 2331,129
        - 2034,120
        - 1803,123
        - 1563,129
        - 1299,156
        - 1065,198
        - 801,252
        - 558,318
        - 318,384
        - 120,447
        - 0,504
        - 0,2159
        - 3839,2159`
```

**Comment by blakeblackshear** [comment]
Take a look at the example config again. You are missing `coordinates` for the zones.

```
  backyard:
    ffmpeg:
#      input: rtsp://admin:lib53311@192.168.0.31:554/cam/realmonitor?channel=1&subtype=0
      input: http://192.168.0.11:7999/1/source
    snapshots:
      show_timestamp: False
      draw_zones: False
    zones:
      BYLine:
        coordinates:
          - 3839,996
          - 3519,774
          - 3213,555
...
```

**Comment by edk4971** [comment]
doh! thanks. copy pasted the old from when it was a standalone section in the config (in rc1). Thanks!
