### ISSUE TITLE
[Feature Request] Timestamp on live-feeds/recordings

### ISSUE THREAD

**Issue by Lallassu** [blakeblackshear/frigate#2151]
**Describe what you are trying to accomplish and why in non technical terms**
It would be really nice to have timestamps on live-feeds and in 24/7 recordings/clips. Right now it seems that you can enable timestamp in "debug" in the UI, but it's only visible in the debug view in UI. 

**Describe the solution you'd like**
Have support for timestamp, configured in config file such as `timestamp: true` for recording as it is for snapshots right now.

**Comment by blakeblackshear** [comment]
This will require decoding and re-encoding the video stream, which you almost certainly don't want.

**Comment by Lallassu** [comment]
Oh OK :/

**Comment by XxTopKillerzZ** [comment]
@Lallassu Did you manage to solve it?

**Comment by Lallassu** [comment]
> @Lallassu Did you manage to solve it?

Only by activating timestamps on my cameras, so no, not really.

**Comment by XtremeOwnageDotCom** [comment]
@blakeblackshear A few ideas...

Would, it be possible to have the timestamp displayed when scrolling the bar at the bottom?

![image](https://github.com/blakeblackshear/frigate/assets/5262735/58b3d287-ed01-4eaa-9e48-23a56315ac25)


Another idea- on the right-
![image](https://github.com/blakeblackshear/frigate/assets/5262735/766141b4-e9a0-4939-bfb1-0cacdbe36951)

Perhaps when you say, click "21:00", it expands to allow picking a finer timespan, 21:10, 21:20, etc.


This would be a handy feature, as I purposely disabled the timestamps on my cameras, and instead, have leveraged the timestamp Blue Iris encodes into the stream. However, I am giving Frigate a test to see if it can replace all of the functionality I need/use, and ran across this exact issue.

**Comment by XtremeOwnageDotCom** [comment]
To, give an idea of how blue iris handles it-

When you scroll at the bottom, it highlights events, motion, etc.

![image](https://github.com/blakeblackshear/frigate/assets/5262735/6dbb94a6-6d59-4b6d-a3e3-a199bcb03b16)

And, you can scroll around to a specific time pretty easily. 

Scroll wheel also allows you to increase/decrease the timeframe.

![image](https://github.com/blakeblackshear/frigate/assets/5262735/e5a5fe26-7523-48de-b585-873ca964c5db)

**Comment by NickM-27** [comment]
We've talked about the possibility of YouTube like seeking with the popup preview and showing the actual timestamp on the seekbar. To me that makes a lot more sense than the extra work to re encode the recordings.

**Comment by NickM-27** [comment]
Of course you can always configure frigate / ffmpeg to add the timestamp

**Comment by justJackjon** [comment]
Apologies for reviving an old gh issue, but did anybody manage to solve this?

@Lallassu in terms of those config validation issues with the output args, the solution ended up being just to smash the entire string/args in double quotes, and remove the backslash escape characters from the single quotes around `localtime`.

Whilst that got rid of the yaml validation issues, upon attempting to use the example options provided it appears that the arguments themselves weren't valid - notably the `-c copy` option - as @blakeblackshear noted adding the timestamp will require decoding and re-encoding the stream, so the copy option won't work here.

I did try several different permutations/options but kept encountering errors in the logs and ultimately, ffmpeg crashing. Admittedly I haven't played much with ffmpeg so I feel it's probably something simple I'm missing! If anybody has a working solution and could share it that would be awesome!

**Comment by beeepus** [comment]
Can subtitle be an option? like soft embedded this doesn't decode encode the stream.
Frigate needs to feed the timestamp (both date and time) . Very nice to have when exporting.
ffmpeg example:
ffmpeg -i video.mp4 -i subs.srt -c copy -c:s mov_text output.mp4
