### ISSUE TITLE
Raspberry Pi 4 Vulkan video decode acceleration

### ISSUE THREAD

**Issue by mfedderly** [blakeblackshear/frigate#2153]
**Describe what you are trying to accomplish and why in non technical terms**
It appears that Raspberry Pi 4 will [support Vulkan 1.1](https://www.cnx-software.com/2021/10/27/raspberry-pi-4-achieves-vulkan-1-1-conformance-gets-up-to-60-gpu-performance-boost/) soon. It looks like this may be possible to leverage for improved hardware acceleration of video decode over the [existing support](https://docs.frigate.video/configuration/hardware_acceleration).

**Comment by blakeblackshear** [comment]
I don't think it is likely to improve object detection, but it may offer better hwaccel for decoding video.

**Comment by mfedderly** [comment]
Interesting. Do you want me to rework the issue description over to video decoding, or just close this ticket entirely?

**Comment by blakeblackshear** [comment]
You can rework it. I went ahead and pinned it. I'm guessing it will take a while to work its way into ffmpeg, etc.

**Comment by NickM-27** [comment]
ffmpeg 7.0 is included for the next version of Frigate 0.15 and vulkan decoding is supported
