### ISSUE TITLE
Zone improvement: Detect only contiguous objects

### ISSUE THREAD

**Issue by darkalfx** [blakeblackshear/frigate#2159]
**Describe what you are trying to accomplish and why in non technical terms**
I want zone object detection to detect objects that are contiguous to the specified zone, so that I can avoid getting detections for objects that aren't at least in some part within the specified zones.

**Describe the solution you'd like**
Everything the same as it is right now, but not triggering detection events for objects that are **not** contiguous with the zones.

**Describe alternatives you've considered**
Could not think of any.

**Additional context**

_Example problem:_
I have a camera with people detection enabled that sees this:
![image](https://user-images.githubusercontent.com/22474506/139599056-f13b93df-2d4e-4c9c-be68-b9dafd28b672.png)

If anything creates some kind of motion in the zone (animals, cloud shadows, etc), it triggers detection for people walking _on the other side of the street_, these people are nowhere close to the actual zone define, which results in false positives.

**Comment by blakeblackshear** [comment]
This is exactly what required_zones are for. Just specify the zone under snapshots and events in your config.

**Comment by darkalfx** [comment]
I have set the `required_zone` and it 100% prevents people walking on the other side from **initiating** any detection.

However **if something triggers motion in the zone while someone in walking on the other side of the street** then I will get a people detection for the person on the other side of the street, even though they aren't anywhere close to the actual zone.

**Comment by blakeblackshear** [comment]
That could only happen if there is one frame where where the person is in the zone. I'm guessing it's a false positive in the zone that is linked to the tracked object. I would adjust your zone filters to try and avoid it. Similar to this issue: https://github.com/blakeblackshear/frigate/issues/1246

**Comment by darkalfx** [comment]
Ah I see, I will look into adjusting the settings then, thanks a lot, Frigate is truly amazing
