### ISSUE TITLE
Support bash path for web ui

### ISSUE THREAD

**Issue by jeremyroberts0** [blakeblackshear/frigate#2170]
I am running frigate in a kubernetes cluster and am using path based routing (e.g. 192.168.100.100/frigate-api).  API calls work fine but the web UI doesn't load because the HTML served by frigate uses root-relative paths for JS and CSS (e.g. `<script type="module" src="/dist/index.eGbu4C0_aBX_.js"></script>`).  This can be worked around by using `kubectl port-forward` command to forward local ports to the specified pod running frigate, but it'd be great if it there was a way to pass a base path into the frigate container and the paths in HTML are updated accordingly.

**Comment by blakeblackshear** [comment]
You can pass a header like this: https://github.com/blakeblackshear/frigate-hass-addons/blob/main/frigate_proxy/rootfs/etc/nginx/templates/ingress.gtpl#L11
