### ISSUE TITLE
[DOCS] Update Hardware-accelleration pages - nvidia GPU no great benefit - make use of NVIDIA-GPU for tensorflow

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#2179]
**Describe what you are trying to accomplish and why in non technical terms**
i wanted to know if GPU-hardware/CPU accelleration in decrypting of h264/h265 helps 

**Describe the solution you'd like**
[update the docs](https://github.com/blakeblackshear/frigate/blob/master/docs/docs/configuration/hardware_acceleration.md) (for newbies?) to see that they may dont need special effort in fiddling with hwaccel-parameters

**Describe alternatives you've considered**
make use of exitings NVIDA and CUDA for TENSORFLOW to overcam the CORAL?
its powerfull for tensorflow. why stick to 8bit CORALs and not use fancier tensorflow models?

**Additional context**
i have to nearly identical machines running frigate in docker.
both have one coral edge m2 tpu.
both use the same 13 rtps cams.
one has a nvida gpu 1660 and frigate is configured to do ffmpeg-hardware-decoding of h264/h265 rtsp-streams with it.
the other is configured to decrypt with CPU

NVIDIA (snippet)
``` 
input_args:
        - -c:v
        #- hevc_cuvid    # h265
        - h264_cuvid
``` 

CPU  (snippet)
``` 
input_args:
        # vaainfo to check ver, and check platform -> https://trac.ffmpeg.org/wiki/Hardware/QuickSync
        - -hwaccel      # check with intel_gpu_top
        #- qsv          # HW CPU > 10. 
        - vaapi         # HW CPU < 10 , works only with h264?.. not for modern codecs, check capabiltiy with qsv
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
        #- -tag:v hvc1`
```

on both machines the CPU load is nearly identical overall.
NVIDIA GPU seems to me nearly useless for RTPS offloading. 

Why not use it for TENSORFLOW AI? That would be great!
to overcam the CORAL?

![image](https://user-images.githubusercontent.com/5937811/140286873-e6cb3b14-35e9-4fa1-8330-1ba6b59cf021.png)
-
![image](https://user-images.githubusercontent.com/5937811/140287594-c54977a6-d817-4836-997e-17cad03b4c22.png)

**Comment by xSkate** [comment]
"Load Average" is not a percentage. The machine on the left is leaning on the CPU quite a bit more actually - you can see each core has a much higher load on the left vs right from that htop screenshot.

**Comment by ozett** [comment]
interesting reading. thanks.
dont know if i get all of it, but glad that it is still on the net. and that you pointed to it.

if i got it right, than CPU% is to compare, not the load average. 
![image](https://user-images.githubusercontent.com/5937811/140323267-f27d1d9d-b026-4c54-8c60-b505c1464e6c.png)

but overall in my setting i could stay with my 10 year old CPU-only. 
it seems thats not worth the effort and money to offload ~ 30% for 13 cams to the nvidia-GPU.

still worth the effort and money to try lots of other tensorflow-models on the GPU 😄

**Comment by ozett** [comment]
i forgot about [intel-gpu stats](https://germanium.top/munin-monitoring-de-la-frequence-gpu-intel/)  ```-fri5:/etc/munin/plugins# /usr/bin/intel_gpu_top ```
and maybe also forget to compare cpu/gpu-load of [nvidia-jetson with a coral](https://3dvisionlabs.com/2019/09/18/jetson-nano-and-google-coral-edge-tpu-a-comparison/)
