### ISSUE TITLE
Trigger clip recording from a Home Assistant event

### ISSUE THREAD

**Issue by OldGreyCells** [blakeblackshear/frigate#2182]
I'd like to be able to trigger the recording of an event from Home Assistant - e.g. when a PIR is triggered one or more cameras start recording for a period of time.

It could be via MQTT or directly from a HA event.

I have not found a way of doing this in the documentation, so have tagged this as an enhancement request.

**Comment by blakeblackshear** [comment]
Duplicate of #1063
