### ISSUE TITLE
garten: frame 1601290367.271557 is not in memory store. 

### ISSUE THREAD

**Issue by CaCu15** [blakeblackshear/frigate#219]
Hello blakeblackshear,

after using Frigate (version 0.5.2) for 4 month without any problems I upgraded to the new release 0.6.0 today. I really like the new feature to record video clips. 

After this upgrade I've got problems to get the container running again. After starting the camera processes the log shows a lot of  entries `<camera>: frame 1601306780.083717 is not in memory store.` 

Log output:
```
Camera_process started for garten: 91
Starting process for garten: 91
Camera_process started for treppe: 92
Starting process for treppe: 92
garten: frame 1601306779.98212 is not in memory store.
garten: frame 1601306780.038458 is not in memory store.
garten: frame 1601306780.083717 is not in memory store.
```

The analysis of the video stream coming from the camers seems to be stuck at an image from the point in time the container has been started. If I request the frigate video stream from http://<frigate-host>:5000/garten than I get a still image  with a running clock in the upper left corner.

Another issue: Although all cameras are configured to stream 4 FPS frigate shows a frame rate of ~65-70 FPS coming from the cams in the debug output (camera_fps). 

Any ideas what is causing this behaviour? 

My environment:
Running frigate under XEON 1265L, 32GB RAM, Debian Buster, 3 Reolink 410W WebCams configured to supply 4 FPS in FullHD, Google Coral device

**Comment by blakeblackshear** [comment]
Please see the new fps parameter in the example config. Sometimes ffmpeg cannot reliability determine the frame rate of the source.

**Comment by CaCu15** [comment]
Tried that before, but obviously I made a yaml formatting error. Now it works! Thanks for your support!
