### ISSUE TITLE
[Support]: aarch64 on Coral Dev-Board. Frigate 0.9.x nginx memory error

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#2196]
### Describe the problem you are having

starting docker with frigate 0.9.x aarch64 images on coral-Dev-Board leads to error

snippet:
```bash
frigate    | nginx: [alert] mmap(MAP_ANON|MAP_SHARED, 536870912) failed (12: Cannot allocate memory)
frigate    | nginx: [alert] munmap(FFFFFFFFFFFFFFFF, 536870912) failed (22: Invalid argument)
```

i made this new issue, little more testing is already documented in this thread https://github.com/blakeblackshear/frigate/issues/1718#issuecomment-962590163

any hints for configuring the dev-board highly appreciated. also hints confiming a running 0.9.x container on the dev-board. 👍 

### Version

DEBUG 0.9.x

### Coral version
Dev-Board with Mendel -Linux 5.2 

### Any other information that may be helpful

i made this new issue, little more testing is already documented in this thread https://github.com/blakeblackshear/frigate/issues/1718#issuecomment-962590163

**Comment by ozett** [comment]
maybe as a hint here: https://www.codetd.com/en/article/12291736
```
Summary Nginx mmap:
Therefore, if you encounter an error about Nginx mmap (MAP_ANON|MAP_SHARED, 314572800) in the future, you should first check the configuration that may allocate large memory. The first thing to check is these two
lua_shared_dict
proxy_cache_path.
Modifying these two parameters can solve the problem.
```

leads me to inspect the http-configuration of nginx.
i found only this part with memory reservation [in the nginx.conf](https://github.com/blakeblackshear/frigate/blob/26ae6084ea33593b75093c7408817604e39444ee/docker/rootfs/usr/local/nginx/conf/nginx.conf#L60):

```
 # vod caches
        vod_metadata_cache metadata_cache 512m;
        vod_mapping_cache mapping_cache 5m;
```
and maybe 512MB for VOD is too much for the container inside the coral-dev board?



@blakeblackshear 
can you make this configurable on/off? 
think i dont need VOD at the moment..
would like to see frigate 0.9.x running on coral-dev board to compare memory and CPU-usage for ffmpeg in comparison to the nvidia offload...

**Comment by ozett** [comment]
in 0.x10.beta3 further on as a fixed set to 512m.... 
https://github.com/blakeblackshear/frigate/blob/v0.10.0-beta3/docker/rootfs/usr/local/nginx/conf/nginx.conf#L60

no great hopes (if this is the error cause), but i will try the aarch64 image on the coral-dev-board again ...

**Comment by ozett** [comment]
starting to cross-compile aarch64 myself. but as a noob some steps are missing.

step 1-3 done, but now: what do you mean by ["opening repo with vissuco" ](https://deploy-preview-1927--frigate-docs.netlify.app/contributing#4-open-the-repo-with-visual-studio-code) ?
i have the cloned repo compiled and the remote-ssh-maschine on one of my vmware-servers running.. but what next?

please advice, and i will try to contribute as good as i can... 😄 

![image](https://user-images.githubusercontent.com/5937811/142723344-0bfdb4d5-b7ab-439f-ac4b-3e5d19b20a2e.png)

**Comment by ozett** [comment]
fiddling my way through.. i did on ssh-shell of the maschine in the root of the cloned repo:

```
docker-compose build
docker exec -it frigate-dev /bin/bash
```

and try to [follow with step 5](https://deploy-preview-1927--frigate-docs.netlify.app/contributing#5-run-frigate-from-the-command-line)

**Comment by ozett** [comment]
1st cross-compile ```make aarch64_all ``` failed on my ubuntu 20.04/amd64 with:

```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-headers-raspi2
```

**Comment by ozett** [comment]
2nd try to build, now on the dev-board itself (only 4.8 GB /root-fs) and mendel-os 5 (=debian-buster)
```
# delete all docker containers including its volumes use,
docker rm -vf $(docker ps -aq)
# delete all docker images,
docker rmi -f $(docker images -aq)

# check space
df -h

###Filesystem      Size  Used Avail Use% Mounted on
###/dev/root       5.0G  1.9G  2.9G  39% /

# build...
apt update; apt upgrade
apt install build-essential; apt install git; apt install screen
git clone http.//my-repo-fork
cd frigate
# optional for log run: screen
make aarch64_frigate
```

so far one warning:
![image](https://user-images.githubusercontent.com/5937811/142725311-dd4bc9dd-fb4d-4db8-b67c-9a832727d7d1.png)

**Comment by ozett** [comment]
looks like getting nearer:
![image](https://user-images.githubusercontent.com/5937811/142725750-97d91210-8cbe-4d01-84fc-412e25e5ce21.png)

**Comment by ozett** [comment]
changed source-code for nginx.conf and ```docker-compose build --no-cache```
its compiling... i wait....

**Comment by ozett** [comment]
success. (got it running).

FR: 
please reduce ```vod_metadata_cache metadata_cache``` for the aarch64 image 
from 0.9.x and higher

maybe it could have been easier to simply patch the exiting image with a ngix.conf configured into the container
```
docker run -d -v /path/to/changes/nginx.conf:/etc/nginx/conf.d/nginx.conf IMAGE_NAME
```
see https://stackoverflow.com/a/47070215

on the coral-dev-board:
![image](https://user-images.githubusercontent.com/5937811/142731983-9f3038e5-1be2-44ce-8266-9cd599754616.png)

**Comment by blakeblackshear** [comment]
@ozett nice work. Can you post the contents of your modified `nginx.conf`?

**Comment by ozett** [comment]
i only set the cache size to 32m
in your github code ```/docker/rootfs/usr/local/nginx/conf/nginx.conf```
```
 # vod caches
        vod_metadata_cache metadata_cache 32m;
       ...
```
https://github.com/blakeblackshear/frigate/blob/master/docker/rootfs/usr/local/nginx/conf/nginx.conf#L60
the dev-board has limited ram, must be lower than your default...

![image](https://user-images.githubusercontent.com/5937811/142734918-a9e32408-0256-4911-9fc9-52e807582542.png)

**Comment by blakeblackshear** [comment]
That may be a better default anyway. I will need to look into it.

**Comment by blakeblackshear** [comment]
Can you test with higher values to see what the max supported value is?

**Comment by ozett** [comment]
yes, i will try to use your actual arch64 container and link a nginx.conf into it, something like
```/path/to/changes/nginx.conf:/etc/nginx/conf.d/nginx.conf```
i will report my findings..

**Comment by ozett** [comment]
256 mb is working now for vod-cache with  1 cam configured.
maybe its gets problem with more cams?

i can test tommorow different settings./ram/hwaccel...

```
root@elusive-calf:/usr/src# docker exec -it frigate /bin/bash
root@703ddff4fc4f:/opt/frigate# cd /usr/local/nginx/
root@703ddff4fc4f:/usr/local/nginx# ls
client_body_temp  conf  fastcgi_temp  logs  proxy_temp  sbin  scgi_temp  uwsgi_temp
root@703ddff4fc4f:/usr/local/nginx# ls -la
total 48
drwxr-xr-x 1 root root 4096 Nov 20 18:35 .
drwxr-xr-x 1 root root 4096 Jul  1 22:19 ..
drwx------ 2 root root 4096 Nov 20 18:35 client_body_temp
drwxr-xr-x 1 root root 4096 Sep 25 13:25 conf
drwx------ 2 root root 4096 Nov 20 18:35 fastcgi_temp
drwxr-xr-x 1 root root 4096 Nov 20 18:35 logs
drwx------ 2 root root 4096 Nov 20 18:35 proxy_temp
drwxr-xr-x 2 root root 4096 Jul 21 12:41 sbin
drwx------ 2 root root 4096 Nov 20 18:35 scgi_temp
drwx------ 2 root root 4096 Nov 20 18:35 uwsgi_temp
root@703ddff4fc4f:/usr/local/nginx# cd conf/
root@703ddff4fc4f:/usr/local/nginx/conf# ls
fastcgi.conf  fastcgi_params  koi-utf  koi-win  mime.types  nginx.conf  scgi_params  uwsgi_params  win-utf
root@703ddff4fc4f:/usr/local/nginx/conf# ls -la
total 56
drwxr-xr-x 1 root root 4096 Sep 25 13:25 .
drwxr-xr-x 1 root root 4096 Nov 20 18:35 ..
-rw-r--r-- 1 root root 1077 Jul 21 12:41 fastcgi.conf
-rw-r--r-- 1 root root 1007 Jul 21 12:41 fastcgi_params
-rw-r--r-- 1 root root 2837 Jul 21 12:41 koi-utf
-rw-r--r-- 1 root root 2223 Jul 21 12:41 koi-win
-rw-r--r-- 1 root root 5231 Jul 21 12:41 mime.types
-rw-r--r-- 1 root root 6927 Nov 20 19:12 nginx.conf
-rw-r--r-- 1 root root  636 Jul 21 12:41 scgi_params
-rw-r--r-- 1 root root  664 Jul 21 12:41 uwsgi_params
-rw-r--r-- 1 root root 3610 Jul 21 12:41 win-utf
root@703ddff4fc4f:/usr/local/nginx/conf# cat nginx.conf | grep vod_me
        vod_metadata_cache metadata_cache 256m;
root@703ddff4fc4f:/usr/local/nginx/conf#
```

**Comment by ozett** [comment]
max:  
```
# vod caches
        vod_metadata_cache metadata_cache 400m;
```

**Comment by ozett** [comment]
afraid that the dev-board will be of limited use with more than 1 cam... 
![image](https://user-images.githubusercontent.com/5937811/142740910-4273b510-ccd2-484a-9edd-cef2fd9406f5.png)
