### ISSUE TITLE
[Support]: [Errno 2] No such file or directory: '/config/config.yml'

### ISSUE THREAD

**Issue by Jonnehs** [blakeblackshear/frigate#2204]
### Describe the problem you are having

I'm new to docker and don't really know how I access this location its looking for the config in. Can anyone help?

Ubuntu using docker-compose.

Thanks

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
frigate    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate    | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate    | [fix-attrs.d] applying ownership & permissions fixes...
frigate    | [fix-attrs.d] done.
frigate    | [cont-init.d] executing container initialization scripts...
frigate    | [cont-init.d] done.
frigate    | [services.d] starting services
frigate    | [services.d] done.
frigate    | *************************************************************
frigate    | *************************************************************
frigate    | ***    Your config file is not valid!                     ***
frigate    | ***    Please check the docs at                           ***
frigate    | ***    https://docs.frigate.video/configuration/index     ***
frigate    | *************************************************************
frigate    | *************************************************************
frigate    | ***    Config Validation Errors                           ***
frigate    | *************************************************************
frigate    | [Errno 2] No such file or directory: '/config/config.yml'
frigate    | *************************************************************
frigate    | ***    End Config Validation Errors                       ***
frigate    | *************************************************************
frigate    | [cmd] python3 exited 1
frigate    | [cont-finish.d] executing container finish scripts...
frigate    | [cont-finish.d] done.
frigate    | [s6-finish] waiting for services.
frigate    | [s6-finish] sending all processes the TERM signal.
frigate    | [s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink 510a

**Comment by blakeblackshear** [comment]
Post your compose file.

**Comment by Jonnehs** [comment]
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "128mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb 
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/config.yml:/config/config.yml:ro
      - /mnt/CCTV:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" 
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

**Comment by blakeblackshear** [comment]
On your host, what do you get when you run the following?
```shell
cat /config/config.yml
```

**Comment by Jonnehs** [comment]
I get my config output

`mqtt:
  host: 10.25.1.15

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<SNIP>@10.25.101.101:554//h264Preview_01_                                                                                                                                                                                                                                                                                                                                                                                                                                             sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:<SNIP>@10.25.101.101:554//h264Preview_01_                                                                                                                                                                                                                                                                                                                                                                                                                                             main
          roles:
            - record
    detect:
      width: 2560
      height: 1920
  garage_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<SNIP>@10.25.101.103:554//h264Preview_01_                                                                                                                                                                                                                                                                                                                                                                                                                                             sub
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:<SNIP>@10.25.101.103:554//h264Preview_01_                                                                                                                                                                                                                                                                                                                                                                                                                                             main
          roles:
            - record
    detect:
      width: 2560
      height: 1920
`

**Comment by Jonnehs** [comment]
I'm no expert but the config data needs to be inside the docker container somehow, right?

**Comment by blakeblackshear** [comment]
This line in your compose file should already be mapping that file into the container correctly:
```yaml
- /config/config.yml:/config/config.yml:ro
```

The left side is the location outside the container, and the right side is the location inside the container.

**Comment by Jonnehs** [comment]
Ok, cool. Well we've verified it is in that location for compose to pick it up, why is it saying it cant find it? I'm running this as root I think so I'll try just as a normal user - any other reasons this might not be working?

**Comment by Jonnehs** [comment]
I have fixed it, was a stupid permission thing - thanks for your help

**Comment by smartthings650** [comment]
Jonnehs do you mind sharing how you were able to grant permission as I am having the same issue

**Comment by Hukuma1** [comment]
Just had this happen to me as well. If you're a) using Portainer, b) launching it via stack using Docker Compose, and c) having the issue above try editing the container path to something that's incorrect. e.g. change it from `/config/config.yml'` to `/lol/config.yml`. Make sure your local copy of `config.yml` path is correct/accessible. Edit the path back to `/config/config.yml`on the container side.

Not sure if some caching bug or what, but I initially ran Frigate with an empty bind to a missing `config.yml` file, and then created it after the container was made. Then the above issue happened. Even though the path was correct and I was able to access the file, it would still say it was unable to bind. Messing with the container path and then changing it back seems to fix it.
