### ISSUE TITLE
[Feature request] Add line crossing

### ISSUE THREAD

**Issue by foxy82** [blakeblackshear/frigate#2206]
**Describe what you are trying to accomplish and why in non technical terms**

I want to be able to add a line and only alert/count when a person(cat/dog) crosses it so that I can tune my recording/detection

**Describe the solution you'd like**

Are we able to add something like this: https://github.com/yas-sim/object-tracking-line-crossing-area-intrusion

**Describe alternatives you've considered**

**Additional context**

**Comment by madmic1314** [comment]
Wouldn't Zones do what you're looking for? Set the zone to be quite small - [https://docs.frigate.video/configuration/zones](https://docs.frigate.video/configuration/zones)

**Comment by blakeblackshear** [comment]
Duplicate of #93
