### ISSUE TITLE
Mask not working

### ISSUE THREAD

**Issue by floris-b** [blakeblackshear/frigate#222]
My mask does not seem to load, if I add the following to video.py I get an error message and I am sure the file is in the /config/ directory
```
        if mask.size == 0:
            print("Failed to read mask file")
```
```
  File "/opt/frigate/frigate/video.py", line 213, in track_camera,
    if mask.size == 0:,
AttributeError: 'NoneType' object has no attribute 'size',
```

First I thought frigate is using the middle bottom of the green box to compare against
Is it the blue box or the green box? Why do I have two boxes and why is the green so much bigger?

![inrit_car_03102020-142914](https://user-images.githubusercontent.com/31005120/94996949-1df25f00-05a8-11eb-95ee-1a47362c468c.jpg)
![inrit](https://user-images.githubusercontent.com/31005120/94996958-31052f00-05a8-11eb-867b-0f2e8ec32d80.jpg)
[inrit.zip](https://github.com/blakeblackshear/frigate/files/5321996/inrit.zip)

```

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -vsync
    - drop
    - -rtsp_transport
    - tcp
    - -stimeout
    - "5000000"
    - -use_wallclock_as_timestamps
    - "1"
  output_args:
    # - -vf
    # - mpdecimate
    - -f
    - rawvideo
    - -pix_fmt
    - rgb24

cameras:
  inrit:
    ffmpeg:
      input: rtsp://syno:db872884437ef0e1ed0f66f17b3050d4@192.168.1.10:554/Sms=1.unicast
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    take_frame: 5
    fps: 15
    height: 1080
    width: 1920

    mask: inrit.bmp
    snapshots:
      show_timestamp: True
    save_clips:
      enabled: False
      pre_capture: 10


```

**Comment by blakeblackshear** [comment]
Looks like you are running an older version. The green box shows you what part of the image frigate ran through object detection, and the blue box is the bounding box for the detected object. The mask applies to the bounding box of the object.

**Comment by floris-b** [comment]
I am using docker: blakeblackshear/frigate:0.6.0

It looks like imread cannot read bmp files:
```

root@1f06035dc1fd:/opt/frigate# python3.7
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2 as cv
>>> img = cv.imread('/config/inrit.bmp',0)
>>> print(img)
None
>>> img = cv.imread('/config/inrit.jpg',0)
>>> print(img)
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
>>> 
```

**Comment by blakeblackshear** [comment]
Strange. I am definitely using bmp files. You should be able to use any format that imread supports.

**Comment by floris-b** [comment]
made the mask with GIMP, saved the same file in Windows Paint and now it works

Thank you for your nice work on frigate
