### ISSUE TITLE
Nest "Sightline" like recording scrolling

### ISSUE THREAD

**Issue by hcgonzalezpr** [blakeblackshear/frigate#2230]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have Nest "Sightline" like recording scrolling in Frigate.

**Describe the solution you'd like**
I did some research to see if there were any alternative available and come across this blog post from Nest Dev team on how they achieve it themselves, from the blog post it looks like Frigate has the required building blocks to emulate the functionality.

The blog post talks in details on how they just using H.264 with optimize size and framerate to encode a very low quaility/size view of the day at like a 5mb size and what made a good initial frame sampling rate and how they bump the frame count around "event triggers".  

Frigate already records in 10sec segments, maybe grab the first frame of each recording and save it like at 568x320. 
For the sightline scroll leverage the videojs slow video framerate option and position jump. I think @blakeblackshear is in the right direction with the current recordings view and may be leverage the tech details from that blog post would help improve the current implementation.

Nest Blog Post: https://nest.tech/seeking-100gb-of-video-how-we-made-sightline-c498af316ca4

WaybackMachine link just in case original blog post is taken down:  https://web.archive.org/web/20211111183215/https://nest.tech/seeking-100gb-of-video-how-we-made-sightline-c498af316ca4?gi=d9e62dc9af4

**Comment by blakeblackshear** [comment]
This is exactly where I am planning to head in the future. Thanks for pulling this info together.

**Comment by samuelhautcoeur** [comment]
FYI, that's pretty much what Unifi Protect does, too.

I'm feeding Frigate snapshots and motion events to Unifi Protect, along with the HQ video feeds, and the result is an extremely fluid timeline. Not sure if they use JPGs or build a video from them, but it works.

**Comment by hcgonzalezpr** [comment]
I decided to play around a little bit to get some progress on this item. I tried generating a full day video to a size of less than 10mb. Currently just using CRF but probably a size calculated bitrate would be better.

Im not sure if VideoJs is able to play at speed slower that .25 speed, so I created a 6hrs long video at 1 frame per second.

This generates a base "Sightline" video at 320px wide, that can be easily scroll back and forward.

**Bash script to extract first frame for each 10sec segment for a whole day:**
```
#!/bin/bash
recpath="/media/frigate/recordings";
recmonth="2021-11";
recday="12";
cam="patio";
recdest="/media/frigate/test";

for i in {00..23}; do
  for files in $recpath"/"$recmonth"/"$recday"/"$i"/"$cam"/*.mp4"; do
    mkdir -p "$recdest";
    #echo "$destination/$i-%d.jpeg";
    for file in $files; do
      #echo $(basename $file);
      ffmpeg -hide_banner -i $file -frames:v 1 -vf scale=320:-2 -q:v 3 "$recdest/$i.$(basename $file).jpeg";
    done
  done
done
```

**Bash script to create video from extracted images:**
```
#!/bin/bash
recdest="/media/frigate/test";

# -framerate = 1/15  -> Set the input framerate to 1/4 of a minute to generate a 6hrs video instead of 24hrs. We would use VideoJS .25 speed playback to get full 24hrs back.
# -pattern_type glob -i "$recdest/*.jpeg" -> Read .jpeg files in the specificed folder.
# -c:v libx264 -> Set x264 output format
# -pix_fmt yuv420p -> Make sure images output is encoded in yuv420p insjtead of yuvj420p
# -preset veryslow -> Helps keep video size down and quality
# -crf 30 -> Compresion level
# -r  = Output Framerate
ffmpeg -framerate 1/15 -pattern_type glob -i "$recdest/*.jpeg" -c:v libx264 -pix_fmt yuv420p -preset veryslow -crf 30 -r 1 output.mp4
```

**Comment by blakeblackshear** [comment]
Ideally you could build a video by extracting just the key frames from the source videos. It takes almost no CPU to extract key frames.

**Comment by hcgonzalezpr** [comment]
I thought -frames:v 1 grabs just the first frame of that video segment, just in case I did try with `-vf "select=eq(pict_type\,PICT_TYPE_I)`" and dint see any significant speed improvement extracting frames on my system for the first frame. In .jpeg at 320w max, it only uses around 20mb of jpegs.

Grabbing all I frames that's another topic and way slower.

I'm using Frigate default recording segments and just pulling the first frame, in the future it would be awesome if the segment recording process created the "thumbnail" in advance for that 10sec segment alongside it, so its just a matter of creating the timeline composite every 1 or 5minutes instead of having to run the extraction script.

**Comment by blakeblackshear** [comment]
`-skip_frame nokey ` will only process the key frames from the input. You should get a frame at least every few seconds. I get one every second. https://superuser.com/a/1153483

**Comment by hcgonzalezpr** [comment]
Yes depending on the framerate and I key frame is the number of of them. In my case I'm running the cam at 20fps and I frame every 40 frames. So thats a key frame every 2 seconds in my case.

I did some additional extraction tests:

- Grabbing all  key frames. Result: **Way Slower extraction**. 
- First frame of the video segment + `-skip_frame nokey` . Result : **Slightly faster extraction** 
- Also tried extracting just full image without the frame resize.  Resulted : **Slower extraction**


On the creation side: 

- Adding `-profile:v high` on the video creation. Result: **25% slower video creation, no size improvement**. 
- Chainging the CRF from `-crf 30` to `-crf 35` Result: **Significant size improvement little quality change**.

**Comment by hcgonzalezpr** [comment]
For the scrolling portion of the sightline menue, I found this jquery script: `https://github.com/ka215/jquery.timeline`

Seems it has granularity enough for minutes scale based on the reference docs: `https://ka215.github.io/jquery.timeline/class/src/timeline.esdoc.js~Timeline.html`

**Comment by vajonam** [comment]
in zoneminder world used to use this script to create a similar video to the test like timeline.

https://github.com/pliablepixels/zmMagik

![image](https://github.com/pliablepixels/zmMagik/raw/master/sample/1.gif)

Code is a bit old but worth a look to get some more ideas.

**Comment by blakeblackshear** [comment]
Relevant comment: https://github.com/blakeblackshear/frigate/discussions/6107#discussioncomment-5667712

**Comment by Jens-Wymeersch** [comment]
@samuelhautcoeur Just wondering how you are doing this ? I'm currently recording the frigate events on hdd.

**Comment by burner-** [comment]
I recommend to check unifi video timeline tool. It will give crubbing timeline and draw motion scrore graph to it. It is really usefull when you try find events. 
![image](https://github.com/blakeblackshear/frigate/assets/3836115/9d335f94-58b0-4595-9993-3aa18b7df850)
It wont include "dia show" but that graph is much more usefull anyway. I have tested now ~10 different nvr solution and I must say that unifi video had best ui but I dont use it because of closed ecosystem.

**Comment by NickM-27** [comment]
The new UI has been announced and this has been implemented as part of it https://github.com/blakeblackshear/frigate/discussions/11136
