### ISSUE TITLE
[Support]: Frigate does not display the video from the camera.

### ISSUE THREAD

**Issue by mdanilohome** [blakeblackshear/frigate#2232]
### Describe the problem you are having

Frigate does not display the video from the camera.
I followed the step by step where I created the frigate .yml file but the image is not showing. When running frigate, after a few seconds it stops working and the log displays an asc II error. Follow the log for evaluation.
Clicking on the frigate option in the left sidebar displays a black screen.

Best reggards,

Márcio Danilo

### Version

Frigate NVR (Full Access) Current version: 2.3 

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
mqtt:
  # Required: host name
  host: 192.168.68.81
  # Optional: port (default: shown below)
  port: 1883
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: mdanilo
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: Danilo
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
  cameras:
  # Name of your camera
  Escritório:
    ffmpeg:
      inputs:
        - path: rtsp://mdanilo:Danilo@192.168.68.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
            - rtmp
      objects:
        track:
        - person
      detect:
        width: 1920
        height: 1080
        fps: 5
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-11-11 16:58:13] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2021-11-11 16:58:13] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-11-11 16:58:13] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-11-11 16:58:13] peewee_migrate                 INFO    : There is nothing to migrate
[2021-11-11 16:58:13] frigate.mqtt                   INFO    : MQTT connected
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/frigate/frigate/__main__.py", line 17, in <module>
    frigate_app.start()
  File "/opt/frigate/frigate/app.py", line 326, in start
    self.start_detectors()
  File "/opt/frigate/frigate/app.py", line 157, in start_detectors
    shm_in = mp.shared_memory.SharedMemory(
  File "/usr/lib/python3.8/multiprocessing/shared_memory.py", line 119, in __init__
    register(self._name, "shared_memory")
  File "/usr/lib/python3.8/multiprocessing/resource_tracker.py", line 147, in register
    self._send('REGISTER', name, rtype)
  File "/usr/lib/python3.8/multiprocessing/resource_tracker.py", line 155, in _send
    msg = '{0}:{1}:{2}\n'.format(cmd, name, rtype).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 16: ordinal not in range(128)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal
```

### FFprobe output from your camera

```shell
rtsp://192.168.68.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Intelbras, model IM3

**Comment by mattthewclayton** [comment]
Looks like you have got a non-ascii character somewhere in your .yml and Frigate does not seem to like it for some reason (might be a bug). Do you need to have this? From the debug it looks to be one of these: https://charbase.com/00f3-unicode-latin-small-letter-o-with-acute

**Comment by mdanilohome** [comment]
I don't need this code!
Where do I find this ASC II code? Is it in frigate.yml config? I looked in the file and I couldn't identify it!

**Comment by mdanilohome** [comment]
Would it be in the camera's URL?

**Comment by mdanilohome** [comment]
The camera URL was generated by the Onvif device manager.

**Comment by bernabauer** [comment]
> I don't need this code!
> Where do I find this ASC II code? Is it in frigate.yml config? I looked in the file and I couldn't identify it!

I think , Márcio, that your problem is the name of the camera in your yml file. Instead of naming it “Escritório” try naming it just “Escritorio”. The error code, the way I see it, is because of the “ó”.

**Comment by mdanilohome** [comment]
Hi Bernabauer. I changed the name of the device to CAM Sala de Estudos.
Now Frigate works but has a green screen.
It has the following error messages:
[2021-11-14 19:11:31] ffmpeg.Sala de Estudos.detect  ERROR   : [rtsp @ 0x560310629940] method OPTIONS failed: 401 Unauthorized
[2021-11-14 19:11:31] ffmpeg.Sala de Estudos.detect  ERROR   : rtsp://192.168.68.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif: Server returned 401 Unauthorized (authorization failed)

**Comment by bernabauer** [comment]
> Hi Bernabauer. I changed the name of the device to CAM Sala de Estudos.
> 
> Now Frigate works but has a green screen.
> 
> It has the following error messages:
> 
> [2021-11-14 19:11:31] ffmpeg.Sala de Estudos.detect  ERROR   : [rtsp @ 0x560310629940] method OPTIONS failed: 401 Unauthorized
> 
> [2021-11-14 19:11:31] ffmpeg.Sala de Estudos.detect  ERROR   : rtsp://192.168.68.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif: Server returned 401 Unauthorized (authorization failed)

Your problem now seems to be that your camera needs authentication to access its feed. You can either remove the authentication from your camera's configuration or inform frigate the login and password for the feed.

**Comment by mdanilohome** [comment]
Initially I apologize for the nuisance, because I'm a beginner. I noticed that there are other errors before authentication that I think would be the cause of not being able to authenticate. Could you help me figure it out? Thank you.

[2021-11-15 08:34:05] frigate.video                  INFO    : Sala de Estudos: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2021-11-15 08:34:05] frigate.video                  INFO    : Sala de Estudos: ffmpeg process is not running. exiting capture thread...
[2021-11-15 08:34:24] watchdog.Sala de Estudos       ERROR   : FFMPEG process crashed unexpectedly for Sala de Estudos.
[2021-11-15 08:34:24] watchdog.Sala de Estudos       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2021-11-15 08:34:24] watchdog.Sala de Estudos       ERROR   : You may have invalid args defined for this camera.
[2021-11-15 08:34:24] ffmpeg.Sala de Estudos.detect  ERROR   : [rtsp @ 0x56336d2b3940] method OPTIONS failed: 401 Unauthorized
[2021-11-15 08:34:24] ffmpeg.Sala de Estudos.detect  ERROR   : rtsp://192.168.68.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif: Server returned 401 Unauthorized (authorization failed)
[2021-11-15 08:34:25] frigate.video                  INFO    : Sala de Estudos: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures

**Comment by rossoneri8** [comment]
@mdanilohome You are still seeing the failure because frigate does not have the proper authentication credentials to access the camera (user name and password). I would recommend that you first get the URL to work with something like VLC, and then once you find a working URL, copying that into your frigate.yml. Most likely all you need is to find your camera's configured username and password and modify your URL to something like:
rtsp://**username**:**password**@192.168.68.95:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

**Comment by mdanilohome** [comment]
bernabauer  and rossoneri8, thank you so much for the support. I added in the URL the username and code that appears on a camera tag that would be the password, the same information I included in Onvif Device Manager to have the camera lost and and it worked. I noticed that the CPU usage by the Supervisor is at 84% during the execution of the frigate. Is that right?

**Comment by mdanilohome** [comment]
@rossoneri8  and @bernabauer , now,  I'm trying to set up zones and masks but on my frigate does not appear the "hide options" icon to make the selection and configuration of masks and zone.

**Comment by bernabauer** [comment]
> bernabauer and rossoneri8, thank you so much for the support. I added in the URL the username and code that appears on a camera tag that would be the password, the same information I included in Onvif Device Manager to have the camera lost and and it worked. I noticed that the CPU usage by the Supervisor is at 84% during the execution of the frigate. Is that right?

you will get a higher CPU usage with Frigate if you don't use a TPU. How many cameras are you monitoring with Frigate?

**Comment by bernabauer** [comment]
> I'm now trying to implement the integration to configure the automations but I'm not able to connect.
> [Image_.pdf](https://github.com/blakeblackshear/frigate/files/7540994/Image_.pdf)

Have you installed the integration via HACS?

https://github.com/blakeblackshear/frigate-hass-integration

**Comment by mdanilohome** [comment]
Hi @bernabauer ! Thanks again for your attention and help!!! I still only have one camera monitored on Frigate. I will arrange the installation of Edge TPU Coral. I noticed that when the camera is in night vision mode, in the dark, detection fails. Is this normal or is it due to slow processing?
Frigate was installed via HACS on my Home Assistant. It's working. I only now notice this problem of low performance and high consumption of the processor and the difficulty of detection in the dark.

**Comment by mdanilohome** [comment]
Hi @bernabauer and @rossoneri8 , I'm thinking of putting a GPU card instead of Google Coral. What do you think? Would you guys have any indication of an AMD/ATI Radeon card that has already been tested and worked on Frigate that could indicate me?

**Comment by blakeblackshear** [comment]
Frigate doesn't use the GPU for object detection. It cannot be used instead of a Coral.

**Comment by mdanilohome** [comment]
@blakeblackshear thank you. Can I tell if my server hardware is compatible with Coral? My Mother Board is ASRock, Model D1800B-ITX. As a beginner, I would like to know if there is a step-by-step document for installing and configuring Coral.

**Comment by mdanilohome** [comment]
OK, Thanks! Please, another question, i noticed that when the camera is in night vision mode, in the dark, detection fails. Is this normal or is it due to slow processing?
