### ISSUE TITLE
Easily check and update Frigate version

### ISSUE THREAD

**Issue by CyanAutomation** [blakeblackshear/frigate#2236]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to easily check which Frigate version I'm on, and also easily update Frigate to the latest version

**Describe the solution you'd like**
Using the HA integration (Proxy in my case), see that my Frigate version needs to be updated - and activate the update function

**Describe alternatives you've considered**
Manually checking Github? And then trying to remember which version is installed?

**Comment by noelhibbard** [comment]
You can check the version using the API:
http://<server>:<port>/api/version

I run my frigate server using docker-compose to I just run a script like this to update:
```bash
#!/usr/bin/env bash

docker-compose stop
docker-compose pull
docker-compose up --force-recreate --build -d --remove-orphans
```

**Comment by CyanAutomation** [comment]
Thanks, the docker compose script is really helpful - I will try that!

**Comment by blakeblackshear** [comment]
The version is also visible on the debug page in the UI

**Comment by CyanAutomation** [comment]
I'm going to mark this as closed.

**Comment by Cr4z33** [comment]
> You can check the version using the API: `http://%server%:%port%/api/version`
> 
> This will return something like this: `0.9.4-26ae608`
> 
> The part after the hyphen is the commit hash from the gitrepo. You can check to see what the latest commit hash is with this URL: `https://api.github.com/repos/blakeblackshear/frigate/commits/master`
> 
> It will return some JSON. The first 7 characters of the sha is what you are looking for. If it's different from the hash you are currently running then there is probably a new version.
> 
> If you are running Frigate with docker-compose you could pick up the new version with a script like this:
> 
> ```shell
> #!/usr/bin/env bash
> 
> docker-compose pull
> docker-compose up -d --remove-orphans
> ```
> 
> It's safe to run that script even if there isn't a new version. If there isn't a new version it does nothing. You don't need to down the container first either. If the pull gets new base images then the "up" will cause it to restart. If the pull doesn't get anything new then the "up" is ignored and it comes back saying the container is already up to date. So a cron job that runs nightly would keep you up to date.

Sorry for reviving this old thread, but doing this (without stopping the container first) brings me to this error:
```
Pulling frigate ...
Pulling frigate ... pulling from blakeblackshear/frig...
Pulling frigate ... digest: sha256:bb7f7e76a13eccef0b...
Pulling frigate ... status: image is up to date for g...
Pulling frigate ... done
Creating frigate ...
Creating frigate ... error

ERROR: for frigate Cannot create container for service frigate: Conflict. The container name "/frigate" is already in use by container "876f9cdbe9202bdacf99b4f209076c0ebd7f44a450e7db34ed38faf8f3db1c21". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for frigate Cannot create container for service frigate: Conflict. The container name "/frigate" is already in use by container "876f9cdbe9202bdacf99b4f209076c0ebd7f44a450e7db34ed38faf8f3db1c21". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
```
What commands do I have to I have to add to stop the existing container first?

Also are you 100% sure it will not delete it (the container) and keep using the same settings then?

**Comment by Tokn59** [comment]
Hi, from what directory do you have to run the commands

docker-compose pull
docker-compose up -d --remove-orphans

as when I do this I get the following error messages : 

Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by woody4165** [comment]
Hi all

I've followed [this guide](https://docs.frigate.video/frigate/installation#proxmox) to install Frigate, so no docker-compose

How can I upgrade now Frigate from 0.13.1 to 0.13.2 ?

Thanks

**Comment by Mortis03** [comment]
> Hi all
> 
> I've followed [this guide](https://docs.frigate.video/frigate/installation#proxmox), the "officlal" guide found in Frigate docs, to install it, so no docker-compose
> 
> How can I upgrade now Frigate from 0.13.1 to 0.13.2 ?
> 
> Thanks

Was trying to figure out same thing.  After a little searching, I found to use the same script, but remove the hyphen in "docker-compose"

**Comment by noelhibbard** [comment]
> 
> Was trying to figure out same thing. After a little searching, I found to use the same script, but remove the hyphen in "docker-compose"

I assume by "remove hyphen" you mean, replace the hyphen with a space. docker-compose used to be a stand alone program, today it's just a plugin for the standard docker command.

So in the past you would do this to update Frigate:
```bash
docker-compose pull
docker-compose up -d
```

Today you would do:
```bash
docker compose pull
docker compose up -d
```
