### ISSUE TITLE
Noticeable introduction of false negatives in 0.6

### ISSUE THREAD

**Issue by mcondren** [blakeblackshear/frigate#224]
I am going to roll back to the previous version because I have been fighting with false negatives since upgrading, which hasn’t been an issue before. Been running it for over a year. 

With the previous versions I would occasionally get false positives from pets but after upgrading I have started missing detections. I finally did some troubleshooting while watching the test feed in frigate. It doesn’t draw the box 50% of the time. It may be just looking for motion but not detecting anything but extreme motion. If I walk into the frame it always detected me before. Now it won’t detect me at all unless I start to move quickly...and even then it draws the box around me only 50% of the time I am in frame. It also seems to be less confident when it does. I used to get 80-90% certainty while standing in the middle of the frame. Now the same location is 50-60%. 

I was very happy to see the changes to help with F+‘S in the release notes, but for security cans, F-‘s are definitely the more serious. Is there any info I can provide before rolling back to the previous version? I was watching the log and there were no errors related to the camera I was testing with.

**Comment by blakeblackshear** [comment]
If you can get me a video clip, I can run some tests. It needs to be the same fps and resolution that frigate uses. I think you should be able to adjust some settings and get a similar behavior as the previous version.

**Comment by mcondren** [comment]
Ok, thanks. I’ll try to get something this weekend. Out of curiosity, is there any change in this release that only runs detection on objects that are moving or recently moved. Wondering if stepping into the frame is not enough motion to trigger detection. If so, is there a config value to disable a motion requirement?

**Comment by blakeblackshear** [comment]
Frigate looks for objects based on motion and where objects currently being tracked were last seen. It should definitely be enough motion. Without motion detection, frigate wouldn't look anywhere. The same was true for 0.5.x.

**Comment by mcondren** [comment]
Not noticing this with 0.7-rc2. There may have been a change between 0.6 and 0.7 or I was just imagining things to begin with. Closing.
