### ISSUE TITLE
[Feature] License plate image recognition

### ISSUE THREAD

**Issue by Calimerorulez** [blakeblackshear/frigate#2250]
Hi,

First of all, thank you for your amazing work. 

Is it feasible for Frigate to recognize the front side or the back side of a car, e.g. the image containing a license plate? I could then send the snapshot via MQTT to an app like OpenALPR to 'decypher' the plate.

**Comment by ozett** [comment]
you could use "double take" to use "deepstack.ai" as a detector and in "deepstack" use a custom-model for license-plate-> https://docs.deepstack.cc/custom-models-samples/

longer road to go..

**Comment by leemind** [comment]
I used to do something similar with 'motion' - whenever motion was detected, I sent the snapshot off to be recognised (and then open the gate if I knew them) -- Of course *every* frame of motion was detected so it was expensive in terms of CPU.  Since Frigate can already detect a car and send it via MQTT to Home Assistant, I would have thought this is already possible with a bit of plumbing?

**Comment by Calimerorulez** [comment]
I've found a YouTube video, explaining the use of Plate Recognizer, with Frigate.

https://youtu.be/t-XxCrdj_94

I've managed to get it to work, sort of. Only the resolution of my cam is a little to low for long distance recognition :)

**Comment by Sloth-on-meth** [comment]
i would love this. would make it so easy to do presence detection on my vehicles

**Comment by 654456** [comment]
> you could use "double take" to use "deepstack.ai" as a detector and in "deepstack" use a custom-model for license-plate-> https://docs.deepstack.cc/custom-models-samples/
> 
> longer road to go..

As far as I am aware double-take is only exposing the face end point at this time.

**Comment by ozett** [comment]
https://www.opensourceagenda.com/tags/license-plate-recognition
https://github.com/search?q=License+Plate

detections/recognition ...

lots of frameworks available. would still love to see something coming up.
but not all is open source at the end...
