### ISSUE TITLE
[Support]: Simple Telegram picture - Is someone can give the final solution ?

### ISSUE THREAD

**Issue by Pascal66** [blakeblackshear/frigate#2251]
### Describe the problem you are having

Tryied every solutions found in goole or else
Never able to send a PICTURE, never tried a video

Work manualy with th ID
Work each time with telegram_bot.sendmessage ( a simple message)

Never work with `file or url` in telegram_bot.sendpicture
file : /media/frigate/clip/{{camera}}-{{id}}
url : :500x/api/events/{{camera}}-{{id}}

So can I ask if some one made frigate work with telegram ?

My solution is to use nodered

### Version

N

### Frigate config file

```yaml
N
```

### Relevant log output

```shell
No data
```

### FFprobe output from your camera

```shell
N
```

### Frigate stats

```json
N
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

N

**Comment by Minglarn** [comment]
So you want to use NodeRed only?

**Comment by Pascal66** [comment]
@Minglarn, no, only use nodered with mqtt & telegram wich I know this way is working

**Comment by bennyb21** [comment]
Hi! 
I have a working Flow in Nodered for sending Pictures to my Telegram Bot. I can give you some Screenshots here to understand the Flow. You´ll probably need some adjustments for Your Environment:

![image](https://user-images.githubusercontent.com/57013120/142281629-8adc3061-2af2-4230-9746-18de9122b9fc.png)

I use the Trigger-Node, so i get only one Picture per Event. Frigate sends sometimes several Pictures, for example if you are just taking the Garbage out, you would get at least 2 Notifications for that.

![image](https://user-images.githubusercontent.com/57013120/142281917-c0beddc3-bea0-412e-b0d8-6b85cf518c7a.png)

Inside the Function Node is only the needed formatting for the Message:

![image](https://user-images.githubusercontent.com/57013120/142282132-631ff83b-2442-4678-979e-3741ddae3cb7.png)

I think the Point You are Stuck is here:

![image](https://user-images.githubusercontent.com/57013120/142282256-848ef0ea-c845-4f09-9556-a055728fd350.png)

This stores the Picture in your Machine where Node-Red is running. This File is needed for the Telegram Node to send it into the Chat. Choose Always overwrite the existing File, so only the last Snapshot is available on Node-Red and there is no growing Space needed.

Sorry, the Screenshots are in German Language. But I think, you´ll figure it out... ;)

**Comment by Pascal66** [comment]
Thank you ! And It's ok for the german part :)
If I understand well, I have to save the picture, before sending it with the telegram node ?

**Comment by bennyb21** [comment]
Yes. NodeRed gets the Picture via the MQTT-Message but it will be lost, if you don´t save it. The Image-Preview Node is not needed, but I found it handy when setting up Frigate and Zones and while debugging etc. 
I don´t know if there is a solution where you don´t have to save the Image in NodeRed and use the one in Frigate (Snapshot) since the Filename is different every time and you have to specify a File for the Telegram-Node.

**Comment by Pascal66** [comment]
There's two way to have the picture (but none are working) with automations, frigate and mqtt.
```
// file: /media/frigate/clips/{{trigger.payload_json['after']['camera']}}-{{trigger.payload_json['after']['id']}}.jpg
// url: http://192.168.1.40:5000/api/events/{{trigger.payload_json['after']['camera']}}-{{trigger.payload_json['after']['id']}}/thumbnail.jpg
```
I removed the telegram bot from configuration.yaml (because this make a conflict with node red)
And removed the automation part.
Still investigating :) Thank you @bennyb21
