### ISSUE TITLE
[Support]: Possible Contour-area Values?

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#2257]
### Describe the problem you are having

changed contour-area value per single-cam in ver 0.10.beta and got warning
what are possible values for contour-area?
is the warning critical? how do i proof that the configured value is working?

### Version

DEBUG 0.10.0-B912851

### Relevant log output

```shell
frigate    | [2021-11-16 07:17:15] frigate.edgetpu                INFO    : TPU found
frigate    | /opt/frigate/frigate/motion.py:44: RuntimeWarning: invalid value encountered in true_divide
frigate    |   resized_frame = (((resized_frame - minval) / (maxval - minval)) * 255).astype(
frigate    | /opt/frigate/frigate/motion.py:44: RuntimeWarning: invalid value encountered in true_divide
frigate    |   resized_frame = (((resized_frame - minval) / (maxval - minval)) * 255).astype(
frigate    | /opt/frigate/frigate/motion.py:44: RuntimeWarning: invalid value encountered in true_divide
frigate    |   resized_frame = (((resized_frame - minval) / (maxval - minval)) * 255).astype(
frigate    | [2021-11-16 07:17:21] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:60674]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

all hikvision

### Any other information that may be helpful

![image](https://user-images.githubusercontent.com/5937811/141935588-005cb8e5-f5b0-4ad8-a6b3-810431b5bf68.png)

**Comment by ozett** [comment]
looks like its not coming from contour-area parameter. 

instead coming from 0.10.x motion.py and the new improve contrast calculation.
https://github.com/blakeblackshear/frigate/blob/v0.10.0-beta1/frigate/motion.py#L44

maybe corrected in next beta? 
or do i have to do anything about the warning?

**Comment by blakeblackshear** [comment]
Hmm. I guess this could happen if you got a solid color frame somehow. I will add some handling for this edge case in the next beta.
