### ISSUE TITLE
[Support]: Resolution does not work in latest beta

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#2258]
### Describe the problem you are having

when i input height and width, i get errors saying these keys are not allowed. my front camera is 2590x1920, so the aspect ratio is wrong 

### Version

 0.10.0-B912851

### Frigate config file

```yaml
coming soon, editing out passwords
```

### Relevant log output

```shell
2 validation errors for FrigateConfig

cameras -> front -> height

  extra fields not permitted (type=value_error.extra)

cameras -> front -> width

  extra fields not permitted (type=value_error.extra)
```

### FFprobe output from your camera

```shell
coming
```

### Frigate stats

```json
not relevant since i removed the height and width, as frigate will not start without it
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

REOLINK 520/410

**Comment by Sloth-on-meth** [comment]
this also breaks masks etc

**Comment by blakeblackshear** [comment]
We're you previously on 0.8.4? If so, you need to read the release notes for 0.9.x. These were all breaking changes for the last version. https://github.com/blakeblackshear/frigate/releases/tag/v0.9.1

**Comment by ozett** [comment]
i had this, when identation was not correct for yaml... (tab, spaces, etc..)
may check this?

**Comment by Sloth-on-meth** [comment]
> We're you previously on 0.8.4? If so, you need to read the release notes for 0.9.x. These were all breaking changes for the last version. https://github.com/blakeblackshear/frigate/releases/tag/v0.9.1

oops! this was it.
