### ISSUE TITLE
Allow mask to be defined as a list of polygons

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#226]

**Comment by mattheys** [comment]
This is on the roadmap for v8 but I think it was already added to v7.

Before you close it can you confirm if the closed area of the polygon is the equivalent to the white or black area of the bitmap? i.e. am I masking the area I want or the area I want to exclude?

**Comment by blakeblackshear** [comment]
It is the area you want excluded. This issue is separate in that you may want multiple mask polygons. Some masks are not contiguous.
