### ISSUE TITLE
Disable ingestion of Camera.X into Home Assistant

### ISSUE THREAD

**Issue by jaburges** [blakeblackshear/frigate#2267]
**Describe what you are trying to accomplish and why in non technical terms**
I'd like to be able to disable camera.camera_name being pulled into HA.
Reason being is that I have unify cameras, and the Unifi Protect integration pulls in a nice high quality feed that loads instantly.
I end up with 
camera.camera_name
camera.camera_name_2
(where _2 doesn't load)

**Describe the solution you'd like**
It would be great in the config flow of the integration to specify either domains, or devices that should be excluded.

**Describe alternatives you've considered**
I disabled RTMP for all cameras, but (not sure if this is expected behavior or not) but i'm still getting all the cameras in HA.

**Additional context**

**Comment by blakeblackshear** [comment]
Can't you simply disable the device after setting up the integration?

**Comment by jaburges** [comment]
i can, but doesnt it still waste resource bringing it in?

**Comment by blakeblackshear** [comment]
It wont consume any resources if you aren't using it.
