### ISSUE TITLE
[Support]:  Multiple TPU - How to measure?

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#2281]
### Describe the problem you are having

adding a second Coral TPU doesnt seem to speed up anything.
How do i measure the benefit?

### Version

DEBUG 0.10.0-B912851

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

all hikvision

### Any other information that may be helpful

![image](https://user-images.githubusercontent.com/5937811/142574732-f43c74d9-751d-4b18-a2c6-ca274eaf3266.png)
![image](https://user-images.githubusercontent.com/5937811/142574904-2ba78ad2-2208-467b-87d7-4001bb9d16af.png)

i recently added another Coral TPU. but everthing in frigate feels the same.
on the debug-page it seemms working and the thermal stress on the first TPU went  down.
Where do i see another benefit? Faster Processing Times? 
Can i bring up framerates (all at 5 fps)? any hint?

**Comment by ozrouter** [comment]
how do you get the temp into that graph?

**Comment by blakeblackshear** [comment]
You won't see much benefit until you start to see very high detection fps values. With 2 Corals, each camera process has to wait less time for it's turn to run object detection, so you will have quicker detections by a fraction of a second. It's not going to be a noticeable difference except in a few peak times.

**Comment by ozett** [comment]
@blakeblackshear thanks for looking into it. and explanation.
i have 4 CORAL, so now i can build 4 x frigate and try different settings

**Comment by ozrouter** [comment]
@ozett, thanks

**Comment by ozett** [comment]
> You won't see much benefit until you start to see very high detection fps values. With 2 Corals, each camera process has to wait less time for it's turn to run object detection, so you will have quicker detections by a fraction of a second. It's not going to be a noticeable difference except in a few peak times.

could "pipelining" used with multiple Corals? to reduce latency on bigger models?
found hints for this benefits on google for the corals -> https://coral.ai/docs/edgetpu/pipeline/#overview

**Comment by blakeblackshear** [comment]
It will require code changes. Given most users are struggling to get a single Coral, it's unlikely to be a priority for me to add support for pipelining.

**Comment by ozett** [comment]
ok. but good to know you noticed...

i still have hopes that heavier models have more precision and putting them in tf-lite on two corals could be one option.
another wide opener would be the use of tensorflow on cuda-GPUs..   looking forward for the next developments.. 😉 

and you did great to hold the exising code-base mostly running stable . really great, thx!
