### ISSUE TITLE
[Support]: FFMPEG_VERSION confusion

### ISSUE THREAD

**Issue by tve** [blakeblackshear/frigate#2293]
### Describe the problem you are having

It is intentional that in the `Makefile` you tag the amd64_ffmpeg image with 1.2.0 https://github.com/blakeblackshear/frigate/blob/master/Makefile#L15 but then you build the ffmpeg-base image using 1.1.0 https://github.com/blakeblackshear/frigate/blob/master/Makefile#L21 or am I misunderstanding what's going on?

### Version

0.10.0

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by blakeblackshear** [comment]
It's intentional. The more recent ffmpeg custom builds ended up not working out, so it was reverted.
