### ISSUE TITLE
Save images to another device -> local NAS

### ISSUE THREAD

**Issue by alnavasa** [blakeblackshear/frigate#2296]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to save Images to Synology NAS so that I can run this frigate recorder on a machine with Home Assistant and with just 128Gb

**Describe the solution you'd like**
Save the files in via samba share, 

**Describe alternatives you've considered**
Installing frigate on a Synology box is not an option because its almost imposible to detect coral devices. 
Another option could be to move the files every night to the Synology NAS, without loosing the ability to view files and recordings easily from the interface.

**Additional context**
I am running Home assistant on a VM with just 128GB of space,

However, I also have a Synology NAS were I would like to store frigate clips,
I don't plan on installing frigate on that Synology NAS OS.

Would it be possible?

I don't think it is a strange request, considering many users use low power low storage solutions for Home assistant and also have a NAS at home.

I have already moved the backups of home assistant to be automatically performed to a samba share device (Synology NAS) so If HA can do backups to a samba share, I guess it can also store video recordings.

I am also planing on moving the database from HA to that Synology NAS (which its possible to be done since I have already read others have done it)

**Comment by blakeblackshear** [comment]
If you are using docker to run frigate directly, you can already use volume mounts to store snapshots and recordings elsewhere. I assume you are running HassOS where this is more difficult. There is already an existing feature request for this if so.

**Comment by alnavasa** [comment]
Going to run it in Home assistant OS if I can, since, from what I read, it is the most recommended option. 

I found the thread for the feature request for home assistant, but it was "closed".

**Comment by blakeblackshear** [comment]
Running in HassOS is specifically not recommended because of this specific limitation. https://docs.frigate.video/installation#home-assistant-operating-system-hassos

**Comment by alnavasa** [comment]
> Running in HassOS is specifically not recommended because of this specific limitation. https://docs.frigate.video/installation#home-assistant-operating-system-hassos

Ill try portainer with docker components then, and install it then, but I'll need to personally reduce the HA share of the HD, which I think that requires to completely re install HASSOS in proxmox again, No option to reduce HD in proxmox (logically)

**Comment by dclobato** [comment]
I combined NFS share and docker volumes...

```bash
[dclobato@frigate] ~$ cat /etc/fstab
# /etc/fstab: static file system information.
10.0.3.2:/volume1/FrigateMedia /mnt/frigatemedia nfs rw,nosuid,noexec,intr,rsize=32768,wsize=32768,vers=3,hard    0 0

[dclobato@frigate] frigate$ cat docker-compose.yml
version: '3.8'
services:
  frigate:
    image: blakeblackshear/frigate:stable-amd64
    privileged: true
    container_name: Frigate
    shm_size: 512M
    tmpfs:
      - /tmp/cache,size=1G
    environment:
      - FRIGATE_RTSP_PASSWORD=yLRJZCwjq2
      - TZ=America/Sao_Paulo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/frigate/config/config.yml:/config/config.yml:ro
      - /mnt/frigatemedia:/media/frigate
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 5000:5000
      - 1935:1935
    restart: unless-stopped
    pull_policy: always
```

**Comment by r3wt** [comment]
> Running in HassOS is specifically not recommended because of this specific limitation. https://docs.frigate.video/installation#home-assistant-operating-system-hassos

Hi Blake, I am having trouble parsing exactly what the recommended solution is. Are you saying we should run 2 docker images, 1 for frigate, and 1 for home assistant, from a host os of our choice?

**Comment by NickM-27** [comment]
> > Running in HassOS is specifically not recommended because of this specific limitation. https://docs.frigate.video/installation#home-assistant-operating-system-hassos
> 
> Hi Blake, I am having trouble parsing exactly what the recommended solution is. Are you saying we should run 2 docker images, 1 for frigate, and 1 for home assistant, from a host os of our choice?

The main point is that Frigate should be run in a container outside of HA OS.

Past that it depends on your setup, for example if HA OS is running in a VM with Frigate in docker (outside the VM) then this NAS storage would work. Running both HA and Frigate in docker on some linux OS will also work just as well for this purpose.
