### ISSUE TITLE
Make event view more mobile friendly

### ISSUE THREAD

**Issue by Bod1985** [blakeblackshear/frigate#2313]
**Describe what you are trying to accomplish and why in non technical terms**
Move the addition information in the events view so that on mobile the web page fits horizontally and doesn’t side scroll

**Describe the solution you'd like**
Only show start and end time when viewing the event rather than in the list or stack the info so it’s not in a wide table

Screenshot showing full screen option hidden off screen right
![457E9A45-07C0-4E4C-B6C5-398AF0BE55DA](https://user-images.githubusercontent.com/1529155/143004622-2e7140da-ad6b-402f-8664-0242bdc3ab5b.png)

Screenshot after scrolling right
![02B08B9A-EE47-4F03-9A38-B75C5F880875](https://user-images.githubusercontent.com/1529155/143004326-47b44392-e379-47e0-bcc9-864ae4729aac.png)

Device used in above examples is iPhone 13 Pro running iOS 15.1.1 via Safari

**Comment by jasonpstokes** [comment]
No it doesn't work great on mobiles, which may be reworked as per [this comment](https://github.com/blakeblackshear/frigate/pull/1596#issuecomment-933388492) to merge the events and recordings views.
