### ISSUE TITLE
[Support]: How to render an image from the mqtt snapshot data to telegram using nodered?

### ISSUE THREAD

**Issue by Yonny24** [blakeblackshear/frigate#2324]
### Describe the problem you are having

Please can you explain how I get an image rendered from the mqtt snapshot data?
Been going in circles for days sorry.

Using nodered - bringing in the mqtt snapshot data from Frigate.

But now I'm stuck. How do I format this and send it as an image through telegram for example?

Wish I had a json package to use. 

Your documentation has this but where to go from here I'm stuck

`frigate/<camera_name>/<object_name>/snapshot#

Publishes a jpeg encoded frame of the detected object type. When the object is no longer detected, the highest confidence image is published or the original image is published again.`

### Version

0.9.4-26ae608

### Frigate config file

```yaml
N/R
```

### Relevant log output

```shell
N/R
```

### FFprobe output from your camera

```shell
N/R
```

### Frigate stats

```json
N/R
```

### Operating system

Proxmox

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Ezviz

**Comment by blakeblackshear** [comment]
It's the raw bytes of the jpg. I would recommend using the events topic and pulling images from frigate's http api instead.

**Comment by ozett** [comment]
maybe like this (as a starter)? 

![image](https://user-images.githubusercontent.com/5937811/143488973-cfd65be0-46cd-4c0d-b49c-9a09802aa09a.png)


```
[{"id":"eaa134bdcaca6010","type":"mqtt in","z":"34b6f7d0786adeb5","name":"","topic":"/frigate5/events/#","qos":"2","datatype":"auto","broker":"9b50c12.74a3a4","inputs":0,"x":940,"y":980,"wires":[["409e9dd35e5b6391"]]},{"id":"409e9dd35e5b6391","type":"json","z":"34b6f7d0786adeb5","name":"","property":"payload","action":"","pretty":false,"x":1130,"y":980,"wires":[["3fc6824daeee170a"]]},{"id":"f65d0aaef22b9a41","type":"switch","z":"34b6f7d0786adeb5","name":".after.has_clip","property":"json.after.has_clip","propertyType":"msg","rules":[{"t":"true"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":1440,"y":980,"wires":[["5774179af2ddf639"],[]]},{"id":"5774179af2ddf639","type":"http request","z":"34b6f7d0786adeb5","name":"/{{id}}/snapshot.jpg?bbox=1","method":"GET","ret":"bin","paytoqs":"ignore","url":"http://192.168.14.159:5000/api/events/{{json.after.id}}/snapshot.jpg?bbox=1","tls":"","persist":false,"proxy":"","authType":"","senderr":false,"x":1700,"y":980,"wires":[["84f99936e594bd21"]]},{"id":"84f99936e594bd21","type":"file","z":"34b6f7d0786adeb5","d":true,"name":"save","filename":"/tmp/clip-e.mp4","appendNewline":true,"createDir":true,"overwriteFile":"true","encoding":"none","x":1910,"y":980,"wires":[["07c865cf99c2ac02"]]},{"id":"07c865cf99c2ac02","type":"image","z":"34b6f7d0786adeb5","name":"","width":"320","data":"payload","dataType":"msg","thumbnail":false,"active":true,"pass":false,"outputs":0,"x":2060,"y":980,"wires":[]},{"id":"3fc6824daeee170a","type":"change","z":"34b6f7d0786adeb5","name":"save","rules":[{"t":"move","p":"payload","pt":"msg","to":"json","tot":"msg"},{"t":"set","p":"confi","pt":"msg","to":"$formatNumber(json.before.score * 100, \"00\")","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1270,"y":980,"wires":[["f65d0aaef22b9a41"]]},{"id":"9b50c12.74a3a4","type":"mqtt-broker","name":"192.168.14.204-hik","broker":"192.168.14.204","port":"1883","clientid":"","autoConnect":true,"usetls":false,"protocolVersion":4,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]
```

**Comment by Yonny24** [comment]
Perfect thanks - almost there. Just got to find a shared folder I think and send this via telegram which is the idea.
Unless I can send this directly via telegram which is the aim?

![image](https://user-images.githubusercontent.com/64428686/143506940-0a90385b-f810-4649-b353-13d69835e392.png)

**Comment by Yonny24** [comment]
I see there is a passthrough but still coming through telegram as raw bytes

![image](https://user-images.githubusercontent.com/64428686/143507224-1bbe467a-2d03-4e81-b53a-96d66cd962dc.png)

**Comment by ozett** [comment]
little helper may help?

![image](https://user-images.githubusercontent.com/5937811/143536110-cd6d6369-3617-4b2a-8868-2293982cc181.png)


```
[{"id":"b8f8fd77a358bbbd","type":"change","z":"c253c68d.f16528","name":"create msg","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\t\"chatId\": \"-123456789\",\t\"type\": \"photo\",\t\"caption\": \"n1(stra117,img) \" & msg.code & \" -> \" & msg.action,\t\"content\": \"/tmp/strali117.jpg\",\t\"options\": \t    {\t    \"disable_notification\": \"true\"\t    } \t\t}","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1680,"y":90,"wires":[[]]}]
```

**Comment by Yonny24** [comment]
All figured out today finally. yeahh

Very simple - easier than I thought.

mqtt snapshot out as 'buffer' - then use a specific telegrambot node (I was using an almost identical one but would not render the image).

function as

`msg.payload = {
  content: msg.payload, //the image buffer
  caption: `There's someone in the frontyard. `,
  type : 'photo',
  chatId: ""
 
}

msg.payload.options = { parse_mode : "Markdown" };
return msg;`



![image](https://user-images.githubusercontent.com/64428686/143624949-dca92399-a1de-4682-a7c1-ff3a9c82bf45.png)

**Comment by ozett** [comment]
i struggeld with this also and had [help from the telegram-bot author on this issue](https://github.com/windkh/node-red-contrib-telegrambot/issues/211#issuecomment-915536121).
maybe as a reference for some ides around this

**Comment by Yonny24** [comment]
The niggling issue I have now is that whenever save nodered for changes it pushes all the last snapshots to my phone, msg.payload is in message tab, not start or stop which is odd.

How do I stop this happening? Odd behaviour

**Comment by ozett** [comment]
dont know if i understand correctly,
but may you limit your messages to 2 per minute?

![image](https://user-images.githubusercontent.com/5937811/143734730-cc141a76-ba61-4e01-99d2-f51106f108b5.png)


```
[{"id":"4ac98e7d9a14d43a","type":"delay","z":"c9ebd9ff3af5e55d","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"2","nbRateUnits":"1","rateUnits":"minute","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"allowrate":false,"outputs":1,"x":1010,"y":680,"wires":[["43ec873098ef5f91"]]}]
```

**Comment by customstudioyandexru** [comment]
Hello friends! Please tell me how to implement this idea so that messages in telegrams go only with new objects. I have 6 cameras, and they are constantly sending pictures. If you limit messages to 2-5 minutes, then you can miss something important. Thank you for your help!

**Comment by NickM-27** [comment]
> Hello friends! Please tell me how to implement this idea so that messages in telegrams go only with new objects. I have 6 cameras, and they are constantly sending pictures. If you limit messages to 2-5 minutes, then you can miss something important. Thank you for your help!

There are plenty of things to limit off of including zones being entered, probability, if the object is stationary, etc

**Comment by customstudioyandexru** [comment]
I know how to make visible zones. Fixed objects and probability do not know. Can you help?

**Comment by NickM-27** [comment]
> I know how to make visible zones. Fixed objects and probability do not know. Can you help?

I don't think you got my meaning. Using the MQTT payload you can use any of these properties to filter when an image / notification is sent. 

https://docs.frigate.video/integrations/mqtt#frigateevents

And if you're using NodeRED no I can't help.

**Comment by customstudioyandexru** [comment]
> > I know how to make visible zones. Fixed objects and probability do not know. Can you help?
> 
> I don't think you got my meaning. Using the MQTT payload you can use any of these properties to filter when an image / notification is sent.
> 
> https://docs.frigate.video/integrations/mqtt#frigateevents
> 
> And if you're using NodeRED no I can't help.

**Comment by NickM-27** [comment]
I made a guide: https://github.com/blakeblackshear/frigate/discussions/2898
