### ISSUE TITLE
[Support]: How do I disable recording during certain times?

### ISSUE THREAD

**Issue by ksignorini** [blakeblackshear/frigate#2328]
### Describe the problem you are having

I would like to disable detection and recording, say with an indoor camera, during the day. However, at night I want it detecting and recording.

Is this possible?

### Version

0.9.4-26AE608

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Vivotek

**Comment by Bod1985** [comment]
I’m not sure if there’s another way without but I would likely approach this with the HomeAssistant integration as it produces switches for detection, clips and snapshots - then you could use the built in HomeAssistant automations or NodeRed

**Comment by ksignorini** [comment]
Of course! I forgot that the integration has the switches. That should do it. Thanks!

**Comment by ksignorini** [comment]
Hmmm..... not working. Even when I send the actions manually.

I'm using the following:

```alias: Cameras.Disable Living Room Recording During Day
description: ''
trigger:
  - platform: time
    at: '06:00:00'
condition: []
action:
  - service: camera.disable_motion_detection
    target:
      entity_id: camera.livingroom
mode: single
```
Where camera.livingroom is the _Frigate_ camera _entity_.

Is that the right way to do it?

**Comment by Bod1985** [comment]
I personally use node red but my action would likely be calling the service switch.turn_off with the entity being switch.livingroom_detect.

Check your integration entities list to be certain of the switch name. These are what mine look like:

![B782B01A-6D03-475D-97D4-4916C5CF13B0](https://user-images.githubusercontent.com/1529155/143489538-311bfc4c-3eeb-41dd-9d7e-364070ab96fc.jpeg)

**Comment by ksignorini** [comment]
That’s it! Thanks.
