### ISSUE TITLE
Question on polygon mask

### ISSUE THREAD

**Issue by MEntOMANdo** [blakeblackshear/frigate#234]
Sorry for creating an issue, I can't figure out how to just post a question/comment on a release.

In 0.6, you can define polygon masks. Are you testing that the bottom-center point is (a) inside the polygon, or (b) outside the polygon to be considered an object of interest? If inside, then it behaves like a zone polygon? 

Also, I didn't bother to look at the code, but do we need to close the polygon, or does it automatically create the final leg?

I defined one, but it didn't seem to catch or exclude anything...

**Comment by blakeblackshear** [comment]
It works just like a zone. No need to close it. You could create a temporary zone with the same coordinates to see it drawn on the preview as a test.

**Comment by mattheys** [comment]
Thanks I wanted to ask this as well. The Zone idea to test is great.
