### ISSUE TITLE
[Support]: Docker Frigate container locking up randomly

### ISSUE THREAD

**Issue by lazyjai** [blakeblackshear/frigate#2340]
### Describe the problem you are having

Container running frigate locks up completely, seemingly randomly. Attempting to kill the container provides, "Failure
cannot stop container: [...]: tried to kill container, but did not receive an exit event" 

system drive has 90% available, media drive for clips and pictures has 96% available space.

A reboot of the machine leaves docker to timeout as the machine cannot kill the container during shutdown, requiring a hard reboot.

Wondering if anyone is seeing something similar?

### Version

frigate:0.10.0-beta4-amd64 (also occurred on stable-amd64)

### Frigate config file

```yaml
mqtt:
  host: 192.168.X.X
  port: 1883
  topic_prefix: frigate

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: warning

birdseye:
  enabled: False

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
    detect: -f rawvideo -pix_fmt yuv420p
#    rtmp: -c:v libx264 -an -f flv

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain: 
    default: 60

record:
  enabled: True
  retain_days: 0 
  events:
    pre_capture: 10
    post_capture: 10
    max_seconds: 300
    retain:
      default: 60

timestamp_style:
  effect: shadow

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle

rtmp:
  enabled: False

cameras:
  front_door_ai:
    ffmpeg:
      inputs:
        - path: https://stream-us1-foxtrot.dropcam.com:443/nexus_aac/[removed for privacy]
          roles:
            - detect
            - record
    zones:
      front_steps:
        coordinates: 690,947,790,715,1043,707,1037,227,1600,221,1600,1200,781,1200,691,1070
        objects:
          - person
        filters:
          person:
            min_area: 10000
            max_area: 150000
    detect:
      width: 1600
      height: 1200
      fps: 15
  patio_ai:
    ffmpeg:
      inputs:
        - path: https://stream-us1-charlie.dropcam.com:443/nexus_aac/[Removed for privacy]
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 15
```

### Relevant log output

```shell
[2021-11-28 19:15:01] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x5569c39feec0] Failed to open segment 1281 of playlist 0

[2021-11-28 19:15:01] ffmpeg.front_door_ai.detect    ERROR   : [https @ 0x5569c4955100] HTTP error 404 Not Found

[2021-11-28 19:15:01] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x5569c39feec0] Failed to open segment 1282 of playlist 0

[2021-11-28 19:15:01] ffmpeg.front_door_ai.detect    ERROR   : [https @ 0x5569c3a43800] HTTP error 404 Not Found

[2021-11-28 19:15:01] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x5569c39feec0] Failed to open segment 1283 of playlist 0

[2021-11-28 19:15:01] ffmpeg.front_door_ai.detect    ERROR   : [https @ 0x5569c4955100] HTTP error 404 Not Found

[2021-11-28 19:15:01] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x5569c39feec0] Failed to open segment 1284 of playlist 0

[2021-11-28 20:59:49] frigate.record                 WARNING : Discarding a corrupt recording segment: {'cache_path': '/tmp/cache/patio_ai-20211128205807.mp4', 'start_time': datetime.datetime(2021, 11, 28, 20, 58, 7)}

[2021-11-28 20:59:54] frigate.record                 WARNING : Discarding a corrupt recording segment: front_door_ai-20211128203738.mp4

[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

<docker error>
Failure
cannot stop container: d67fb52bc89032d61e528a94d4376dec8dec83b2e2d04004ca9addc3fc519efe: tried to kill container, but did not receive an exit event

<log upon reboot>
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2021-11-29 00:15:16] frigate.app                    INFO    : Starting Frigate (0.10.0-c1155af)

Starting migrations

[2021-11-29 00:15:16] peewee_migrate                 INFO    : Starting migrations

There is nothing to migrate

[2021-11-29 00:15:16] peewee_migrate                 INFO    : There is nothing to migrate

Process detector:coral:

[2021-11-29 00:15:45] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate

    delegate = Delegate(library, options)

  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__

    raise ValueError(capture.message)

ValueError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap

    self.run()

  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector

    object_detector = LocalObjectDetector(

  File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__

    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)

  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate

    raise ValueError('Failed to load delegate from {}\n{}'.format(

ValueError: Failed to load delegate from libedgetpu.so.1.0


[cont-finish.d] executing container finish scripts...

[cont-finish.d] done.

[s6-finish] waiting for services.

[s6-finish] sending all processes the TERM signal.

[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2021-11-29 00:16:17] frigate.app                    INFO    : Starting Frigate (0.10.0-c1155af)

Starting migrations

[2021-11-29 00:16:17] peewee_migrate                 INFO    : Starting migrations

There is nothing to migrate

[2021-11-29 00:16:17] peewee_migrate                 INFO    : There is nothing to migrate

[2021-11-29 00:18:02] frigate.record                 WARNING : Discarding a corrupt recording segment: front_door_ai-20211129001619.mp4

[2021-11-29 00:18:07] watchdog.front_door_ai         ERROR   : FFMPEG process crashed unexpectedly for front_door_ai.

[2021-11-29 00:18:07] watchdog.front_door_ai         ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.

[2021-11-29 00:18:07] watchdog.front_door_ai         ERROR   : You may have invalid args defined for this camera.

[2021-11-29 00:18:07] ffmpeg.front_door_ai.detect    ERROR   : [tls @ 0x55fe3bf78900] error:00000000:lib(0):func(0):reason(0)

[2021-11-29 00:18:07] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x55fe3bf34ec0] keepalive request failed for 'https://stream-us1-foxtrot.dropcam.com:443/nexus_aac/[removed for privacy]' with error: 'Input/output error' when opening url, retrying with new connection

[2021-11-29 00:18:07] ffmpeg.front_door_ai.detect    ERROR   : [tls @ 0x55fe3bf5dec0] error:00000000:lib(0):func(0):reason(0)

[2021-11-29 00:18:07] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x55fe3bf34ec0] Failed to open segment 24 of playlist 0

[2021-11-29 00:18:07] ffmpeg.front_door_ai.detect    ERROR   : [tls @ 0x55fe3c5430c0] error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

[2021-11-29 00:18:07] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x55fe3bf34ec0] keepalive request failed for 'https://stream-us1-foxtrot.dropcam.com:443/nexus_aac/[removed for privacy] with error: 'Input/output error' when parsing playlist

[2021-11-29 00:18:07] ffmpeg.front_door_ai.detect    ERROR   : [hls @ 0x55fe3bf34ec0] Media sequence changed unexpectedly: 22 -> 1
```

### FFprobe output from your camera

```shell
ffprobe from front door cam only:

ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[hls @ 0x5561d7a83b80] Skip ('#EXT-X-VERSION:3')
[hls @ 0x5561d7a83b80] Opening 'https://stream-us1-foxtrot.dropcam.com:443/nexus_aac/[removed for privacy]' for reading
[hls @ 0x5561d7a83b80] Opening 'https://stream-us1-foxtrot.dropcam.com:443/nexus_aac/[removed for privacy]' for reading
Input #0, hls, from 'https://stream-us1-foxtrot.dropcam.com:443/nexus_aac/[removed for privacy]':
  Duration: N/A, start: 13625.707267, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709), 1600x1200 [SAR 1:1 DAR 4:3], 15 tbr, 90k tbn, 30 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Unsupported codec with id 100358 for input stream 0
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Nest indoor/hello

### Any other information that may be helpful

container runs as host networking. 

Env is: 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FLASK_ENV=development
DEBIAN_FRONTEND=noninteractive
LIBVA_DRIVER_NAME=radeonsi

Volumes:
standard volume mappings for config.yml, localtime, media directory as per documentation, tmpfs is 1 GB.

Running on Ryzen 5600g and Gigbyte x570 board.

Ubuntu 21.10 server build. Docker via apt not snap.

**Comment by ozett** [comment]
your log tells some errors to correct in the config-file ?
```
[2021-11-29 00:15:45] frigate.edgetpu                ERROR   : No EdgeTPU was detected. 
[2021-11-29 00:18:07] watchdog.front_door_ai         ERROR   : You may have invalid args defined for this camera.
 ```
and mybe the stream-source is unreliable?

**Comment by blakeblackshear** [comment]
Looks like an issue with connectivity to your Coral. The container exits due to a Coral issue and on restart isn't able to re-establish a connection. I most often see this happen when it doesn't have enough power.

**Comment by lazyjai** [comment]
More notes and documentation of ongoing troubleshooting:


Upgraded to docker.io/blakeblackshear/frigate:0.10.0-beta6-amd64

Coral was/still is plugged directly into a 3.0 port on the IO shield of the motherboard with original A-to-C cable. it should (in theory) be receiving enough power as there are no other items plugged into the 3.0 ports (kvm and Conbee II and zwave are on 2.0 ports)


config file has not changed including arguments:

> ffmpeg:
>   hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
>   input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
>   output_args:
>     record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
>     detect: -f rawvideo -pix_fmt yuv420p

If these args change, i get the green screen of death. they conform with the ffmpeg motion jpeg section as indicated in the documentation.

The feed is odd.. is is very chopping when viewed through frigate. but when viewed as a network stream via VLC player it is smooth. There is the obligatory 10 second delay due to Nest/Google. it does have the 1 GB /tmp/cache volume setup (16GB RAM and / is on a nvme drive). The /media/frigate directory is mapped to a mechanical HDD I use for media storage (maybe this is an issue? see below).

container lock up still produces the following error:

> "Failure Cannot restart container 90977b9dffe9a8ec8b8645a9140c1cd40a3217705d4876ea1cc6bdfc25e04989: tried to kill container, but did not receive an exit event"

a review of the processes indicates it has stopped and the logs indicate this well (see container log below) - this is confirmed as the frontend is no longer available, but a "sudo docker ps | grep frigate" produces:

> 90977b9dffe9   blakeblackshear/frigate:0.10.0-beta6-amd64   "/init python3 -u -m…"   5 days ago     Up 2 days                                                                                                                                                                                                                                                                                                                                    frigate

which indicates docker thinks is still running when it's not.

last number of lines from the log:

> "[2021-12-18 05:36:57] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x564762780d80] skipping 1 segments ahead, expired from playlists
> [2021-12-18 05:36:57] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x564762780d80] skipping 3 segments ahead, expired from playlists
> [2021-12-18 05:36:57] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x564762780d80] skipping 4 segments ahead, expired from playlists
> [2021-12-18 05:37:58] frigate.record                 WARNING : Discarding a corrupt recording segment: {'cache_path': '/tmp/cache/patio_ai-20211218052601.mp4', 'start_time': datetime.datetime(2021, 12, 18, 5, 26, 1)}
> [2021-12-18 05:38:07] watchdog.patio_ai              ERROR   : FFMPEG process crashed unexpectedly for patio_ai.
> [2021-12-18 05:38:07] watchdog.patio_ai              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2021-12-18 05:38:07] watchdog.patio_ai              ERROR   : You may have invalid args defined for this camera.
> [2021-12-18 05:38:07] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x55a150338d80] Media sequence changed unexpectedly: 20 -> 10
> [2021-12-18 05:39:05] watchdog.patio_ai              ERROR   : FFMPEG process crashed unexpectedly for patio_ai.
> [2021-12-18 05:39:05] watchdog.patio_ai              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2021-12-18 05:39:05] watchdog.patio_ai              ERROR   : You may have invalid args defined for this camera.
> [2021-12-18 05:39:05] ffmpeg.patio_ai.detect         ERROR   : [h264 @ 0x5599f70ce040] co located POCs unavailable
> [2021-12-18 05:39:05] ffmpeg.patio_ai.detect         ERROR   :     Last message repeated 1 times
> [2021-12-18 05:39:05] ffmpeg.patio_ai.detect         ERROR   : [https @ 0x5599f8080880] HTTP error 404 Not Found
> [2021-12-18 05:39:05] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x5599f7077d80] keepalive request failed for 'https://stream-us1-charlie.dropcam.com:443/nexus_aac/8a054ed67f4b478b9566bd6c09334487/chunklist_w820305142.m3u8?public=zqFNvUqJ5a' with error: 'Server returned 404 Not Found' when parsing playlist
> [2021-12-18 05:39:05] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x5599f7077d80] skipping 3 segments ahead, expired from playlists
> [2021-12-18 05:40:08] frigate.record                 WARNING : Discarding a corrupt recording segment: {'cache_path': '/tmp/cache/patio_ai-20211218052613.mp4', 'start_time': datetime.datetime(2021, 12, 18, 5, 26, 13)}
> [2021-12-18 05:40:15] watchdog.patio_ai              ERROR   : FFMPEG process crashed unexpectedly for patio_ai.
> [2021-12-18 05:40:15] watchdog.patio_ai              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2021-12-18 05:40:15] watchdog.patio_ai              ERROR   : You may have invalid args defined for this camera.
> [2021-12-18 05:40:15] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x55e68f614d80] DTS discontinuity in stream 1: packet 28 with DTS 147584803222006, packet 29 with DTS 147584803232109
> [2021-12-18 05:40:15] ffmpeg.patio_ai.detect         ERROR   : [https @ 0x55e690948840] HTTP error 404 Not Found
> [2021-12-18 05:40:15] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x55e68f614d80] keepalive request failed for 'https://stream-us1-charlie.dropcam.com:443/nexus_aac/8a054ed67f4b478b9566bd6c09334487/chunklist_w820305142.m3u8?public=zqFNvUqJ5a' with error: 'Server returned 404 Not Found' when parsing playlist
> [2021-12-18 05:41:18] frigate.record                 WARNING : Discarding a corrupt recording segment: patio_ai-20211218054021.mp4
> [2021-12-18 05:41:26] watchdog.patio_ai              ERROR   : FFMPEG process crashed unexpectedly for patio_ai.
> [2021-12-18 05:41:26] watchdog.patio_ai              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2021-12-18 05:41:26] watchdog.patio_ai              ERROR   : You may have invalid args defined for this camera.
> [2021-12-18 05:41:26] ffmpeg.patio_ai.detect         ERROR   : [hls @ 0x559e3e134d80] Media sequence changed unexpectedly: 20 -> 10
> [2021-12-18 06:02:08] frigate.record                 WARNING : Discarding a corrupt recording segment: {'cache_path': '/tmp/cache/patio_ai-20211218055929.mp4', 'start_time': datetime.datetime(2021, 12, 18, 5, 59, 29)}
> [2021-12-18 06:02:13] frigate.record                 WARNING : Discarding a corrupt recording segment: patio_ai-20211218060044.mp4
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting."

indicates that the processes have actually stopped. attempting to remove the container gives the error that the container isn't stopped. sending kill signal to the containers gives:

> Failure Cannot kill container: 90977b9dffe9a8ec8b8645a9140c1cd40a3217705d4876ea1cc6bdfc25e04989: tried to kill container, but did not receive an exit event

I can duplicate a second container with the exact same settings - except I get the green video screen of death. They both run showing both as active - but with the same host network - without giving me the conflicting ports message. however, now i can not stop, kill, or remove either container, they both give me the same errors.

A soft boot issued didn't work, checking it via the kvm in the mech room give me these errors on screen

> [drm:amggpu_cs_loctl [amdgpu]] *ERROR* Failed to initialize parser -125!
> [drm:amdgpu_job_timeout [amdgpu]] *ERROR* ring vcn_dec timeout, signaled seq=8365041, emitted seq=8365043
> [drm:amdgpu_job_timeout [amdgpu]] *ERROR* process information: process ffmepg pid 2815643 thread ffmpeg:cd0 pid 2915662

A hard boot of the system brings up the original container just fine.

I do get pretty choppy performance on the video clips. After installing Zabbix this week, it is giving me a warning that the read/write  times of the mechanical HDD I have setup for media file storage was seeing long r/w queue times (>45ms) - wondering if this is causing issues so I am swapping it out for an nvme drive tomorrow.

Will update if I see this again, might be another while since this is relatively intermittent, and i tend to reboot once in a while as I tinker with other things on this box.

**Comment by D34DC3N73R** [comment]
@lazyjai I'm seeing "Failure cannot stop container: [...]: tried to kill container, but did not receive an exit event" with a different container and I'm leaning towards this being a bug with docker. Are you able to issue a command line reboot when this happens or does it require physically holding the power button? I'm running ubuntu server 20.04.

**Comment by lazyjai** [comment]
I thought that could be a possibility as well. I haven't seen this with any of the other 17 containers so I decided to start here in case it is a specific interaction with something in this container.

In this case it required a physical power cycle. I can't remember what happened the other time, I think it was the same but I can't 100% confirm.

Was running on 20.04 LTS on the old machine, but now migrated to 21.10 server as i needed support for the integrated Vega cores after the upgrade.

Also was running previously on an ASUS router, now running pfSense appliance, also migrated to new L2 managed switches. Migrated to all nvme drives for operation today, still seeing choppy video on live streams as well as in clips.

Will try to play with some of the settings.

**Comment by D34DC3N73R** [comment]
It's happening with some frequency for me with an emby container. I've switched from the official image to a linuxserver image yet it persists. I've tried restarting docker service/socket, even uninstalling and reinstalling docker, but this container hangs, unkillable. A reboot command also hangs, forcing a hard reboot in order to remove it. After booting up the container can be started, stopped, restarted without issue for some time (couple hours).  I opened up an issue; if you decide it may be an issue with docker rather than a specific image/container, please add your experience. https://github.com/moby/moby/issues/43094

**Comment by EricReiche** [comment]
I have something similar happening to me.
Previously I was using a config with 9 cameras on an Intel NUC which worked completely fine. 
Then I wanted to add Coral, but as the USB version is not in stock anywhere, I moved Frigate to my fileserver which has an m.2 slot and a Ryzen 5600G. Upgraded the host to Ubuntu 21.10.
Initially it works fine, but after some hours cameras start to hang or become partially green and later the whole container locks up and can not be killed. I have to physically reboot the server. It looks to me like the ffmpeg processes inside docker become zombies or something, because they are visible in the host's process list but can't be killed even with -9.

**Comment by D34DC3N73R** [comment]
Is everyone with this issue on the 5.13 kernel?
```
$ uname -r
5.13.0-23-generic
```

**Comment by D34DC3N73R** [comment]
I rolled by the kernel to 5.11 and the problem has been resolved for me. I'd be interested to know if the problem exists with 5.13+ kernels, or if it's just 5.13.

**Comment by lazyjai** [comment]
Running 5.13.0-23. I'll see if there's an opoprtunity to test a roll back to 5.11.

I also noticed that i'd occasionally get some firmware errors related to the IGPU. Will report back when I have time to play around.

G

**Comment by EricReiche** [comment]
Very interesting. I upgraded the host to 5.15.0-6-generic (this Kernel is still marked as unstable) and it's running fine for 7 hours + now.

**Comment by mnl1121** [comment]
I have also experienced this Docker container lock up as well. No other container has ever locked up. Needed to force reboot in order regain control.

**Comment by lazyjai** [comment]
Is everyone using AMD with integrated Vega GPU cores, and do you have the "-hwaccel_output_format yuv420p" flag enabled, and do you get ffmpeg errors related to processing the stream before it hard crashes?

**Comment by EricReiche** [comment]
I tried 3 different kernels for a while. The container only really gets stuck on 5.13. On 5.11 and 5.15 I can kill the container.
However, the streams still get stuck on all 3 kernels. Subjectively I would say it happens more frequently the longer the host is running. I set up a crontab to restart the container every hour, but it's obviously not a good solution.

Example command from ps:
```
ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://REDACTED -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/REDACTED-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/REDACTED
```
There are no ffmpeg errors in stdout as far as I can see.

**Comment by EricReiche** [comment]
I got a stuck container on 5.11 now as well. It was running only ~2h.

**Comment by diogofspiedade** [comment]
Having a similar issue with docker running on an LXC container (Debian) in Proxmox. The system stats show that the LXC container is taking all the ram and swap. Using Coral via USB and iGPU on a 4th gen i5 with a Tapo camera. Any pointers would be highly appreciated!

**Comment by brettinternet** [comment]
Frigate is the only container I have this issue with. Is there not a force shutdown after a timeout for the graceful shutdown?

**Comment by hawkeye217** [comment]
Check your [Docker restart policy](https://docs.docker.com/engine/containers/start-containers-automatically/).

**Comment by brettinternet** [comment]
Thanks for the suggestion, but I don't think that's the issue. I use `unless-stopped` on all my containers.

```
  deploy:
    restart_policy:
      condition: unless-stopped
```

I also have NFS volumes mounted on other containers, but Frigate is the only container that struggles.

```
Error response from daemon: cannot remove container "frigate": container is running: stop the container before removing or force remove
```

I have to assume that the hardware device access (/dev/dri, /dev/bus/usb) combined with the large shared memory is causing the container to be completely unresponsive to `docker kill frigate`, `docker rm -f frigate` and daemon restarts.

---

Edit: For anyone arriving here from a search engine and attempting to kill the container - try this https://github.com/moby/moby/issues/43094#issuecomment-1000003389
