### ISSUE TITLE
[Support]: Support for other npu or tpu

### ISSUE THREAD

**Issue by usairforce456** [blakeblackshear/frigate#2342]
Is there any way to use a different npu or tpu with frigate? There are a couple of sbc's like Asus tinker board or Nvidia Jetson with built in tensor compatible processors. As far as I'm aware frigate uses tensor lite underneath. Would be easy just to specify said device instead of a coral tpu? Coral tpu's are super popular right now and I ended up ordering one from China for a decent price, but it would be nice to have a little flexibility. I can find other various boards in stock that support tensor.

**Comment by ozett** [comment]
Orange AI Stick: rare support... https://github.com/blakeblackshear/frigate/discussions/2165#discussioncomment-1718425
Jetson Nano: could mainly a platform on its own for frigate. still issues to solve https://github.com/blakeblackshear/frigate/issues/1175
Coral TPUs: chip-shortage, heavily out of stock at the moment, but somewhere also buyable...https://github.com/blakeblackshear/frigate/discussions/2165#discussioncomment-1718425

**Comment by usairforce456** [comment]
That doesn't really answer my main question. The Main of having something like the tinker board 2 is the built in rockchip with a npu for tensorflow. I have dual coral tpu on the way, but the question is, does frigate support any tensorflow lite compatible hardware or just coral.

**Comment by blakeblackshear** [comment]
I haven't seen any alternatives to the Coral that an be used with tensorflow lite directly. They all seem to require their own sdk which would require updates to support. To date, I don't know of anyone successfully using something other that a Coral.

**Comment by usairforce456** [comment]
So theoretically if something like the rk3399 soc or  rk3399pro that the Asus tinker board edge r has supports tensorflow directly, it should work? I'm willing to do some testing, so would like to know if it's at least possible. I could also attempt to make a compatible docker image. I appreciate all the help.

**Comment by ozett** [comment]
you could think about building an abstraction level. for example a rest-server, behind which coral-stick or coral-dev boards or nvidia-gpus are working. this way you could also use the google-dev-board, which is probably too weak to decode more than two rtsp-streams performant. not everything has to run on the frigate machine. there are some hints to these examples here in the forum..  let us know here how it works out...

**Comment by blakeblackshear** [comment]
> behind which coral-stick or coral-dev boards or nvidia-gpus are working

Don't reinvent [DOODS](https://github.com/snowzach/doods). Anything involving encoding/decoding or network transfer will introduce substantial latency. Frigate passes around raw frame data in shared memory to avoid any kind of copy operations or decoding.


> So theoretically if something like the rk3399 soc or rk3399pro that the Asus tinker board edge r has supports tensorflow directly, it should work?

Tensorflow and tensorflow lite are quite a bit different. Frigate is built on top of tensorflow lite.

**Comment by LordNex** [comment]
Add a +1 here to add support for Jetson Nano

**Comment by raintonr** [comment]
This would be very useful. Recently announced ROCK5 Model B RK3588 board looks like a very promising SBC for Frigate work. It has it's own 6TOPS NPU which at first glance is 50% faster than a single Coral chip. If Frigate could make use of that that would be excellent.

FWIW, that board also has an M.2 slot (actually looks like it has 2) for addition of a non-USB Coral so could be a good choice either way.

**Comment by bagges** [comment]
Will frigate run on Asus Tinker Edge T?

**Comment by NickM-27** [comment]
> Will frigate run on Asus Tinker Edge T?

With a built in coral seems that it should as long as you can get linux running on it, not sure how many streams that hardware would be able to support though.
