### ISSUE TITLE
[FR:] Debug-Page. Add Information about loaded Model and Corals Temperature

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#2346]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to see the running/loaded model, not the config.
beside inference-times would be nice to see the actual temp of the corals
(as a heartbeat for the corals, as a indirect indicator of the model-load on the corals)

**Describe the solution you'd like**
two lines on the debug page with that information

**Describe alternatives you've considered**
maybe i setup a dev-machine and fiddle myself. but i am a n00b ...
would take some long steps for me to get there

**Additional context**
![image](https://user-images.githubusercontent.com/5937811/144017373-b5f0c258-54f4-4d83-86c6-dee81dd7a211.png)
should help debugging [some model tryouts](https://github.com/blakeblackshear/frigate/discussions/2336)

**Comment by blakeblackshear** [comment]
The model being used will always be what you have set in the config. It's not possible for a different model to be in use.

**Comment by ozett** [comment]
is it conceivable to[ run two models on two TPUs ](https://coral.ai/docs/edgetpu/multiple-edgetpu/#pycoral-api)on one frigate-instance to compare performance and accuracy? would probably mess up the whole tracking pipeline, or is there a way? Otherwise this could also be done with two seperate machines... hmmm maybe this has to be considered when frigate is also doing face-det/rec with another model...

**Comment by PrplHaz4** [comment]
this would also be useful for centralized logging - different frigate instances using different TPUs/models...
