### ISSUE TITLE
add mqtt message when a camera goes down

### ISSUE THREAD

**Issue by ljmerza** [blakeblackshear/frigate#2347]
**Describe what you are trying to accomplish and why in non technical terms**
send mqtt message when a camera goes down so i can tie it to automation to know when a camera goes down

**Describe the solution you'd like**
send a mqtt message of the camera name and timestamp when a camera is detected to go down. maybe even a config settings to say send message after camera is down after x seconds/minutes

**Describe alternatives you've considered**
i dont know of any way to know if a camera is down in frigate

**Additional context**

**Comment by blakeblackshear** [comment]
Most users do this by monitoring the FPS sensors in home assistant.

**Comment by ljmerza** [comment]
that doesnt seem to be working. my kitchen camera is frozen right now but the integration is saying FPS is 5

**Comment by blakeblackshear** [comment]
What version are you running? Are you looking at the debug or live view? What do your logs say when this happens?
