### ISSUE TITLE
"DIY" Coral USB

### ISSUE THREAD

**Issue by cegit55** [blakeblackshear/frigate#2348]
### Describe the problem you are having

Given the current shortage of USB Corals, has anyone had any success "making one"? For example by placing an M.2 B+M Coral inside an M.2 to USB3 enclosure?

### Version

0.8.4-5043040

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

n/a

**Comment by KuRue** [comment]
You may want to check out this project. https://github.com/magic-blue-smoke/Dual-Edge-TPU-Adapter

Unfortunately DIYing an M.2 Coral into a USB Coral may be difficult.

> External m.2 USB enclosure: 99.99% this is SATA, not NVMe (PCIe) enclosure.
m.2 M key has four configuration pins to tell host system what interfaces should be used, PCIe and SATA are among them, but SATA enclosure simply has no PCIe.
Is there a chance to use it with external enclosure? Maybe. If some laptops allow PCIe over USB-C (or over Thunderbolt?) then there are chances for adapter ending with PCIe connector
https://github.com/magic-blue-smoke/Dual-Edge-TPU-Adapter/issues/2#issuecomment-878143833

It doesn't seem impossible, but I don't think anyone has successfully pulled it off yet.

**Comment by Makin-Things** [comment]
Not using USB, but I have had success using a M.2 Accelerator with Dual Edge TPU which was the only Coral card I could find. I installed it in one of these:
https://www.ebay.com.au/itm/185123196274
And then installed that in a M2 slot on my motherboard. Only one of the TPU's is available (but 1 is better that 0). I am on the waitlist to get a card from Magic Blue Smoke when he can get more produced.
I am running Frigate in Docker on a Ubuntu machine and the TPU showed up with no effort.

**Comment by zoltanszalontay** [comment]
So you can only use one of the two TPU-s? Bummer. I was going to get me a dual card to run two models concurrently. I know I can co-compile them, but in that case the bigger model should fit the 6MB memory of the TPU.

Thx for the info, anyway!
