### ISSUE TITLE
Jetson Nano 2GB 

### ISSUE THREAD

**Issue by mattheys** [blakeblackshear/frigate#235]
With the launch of the stripped down version of the Jetson Nano 2GB for $59 I'm tempted to use this as my main Frigate board, I would move my Coral EdgeTPU over to this and use the GPU solely for h264/265 decompression. It can apparently handle 8 h264/h265 streams at 1080p30 YUV420. 

I've not looked at the Jetson Nano stuff before so does anyone have any thoughts on if this would be a good idea for a cheap, compact and low power Frigate device? I know Blake is working on the Raspberry Pi (Arm) versions at the moment so hopefully this wouldn't be too far of a stretch to adapt either officially or unofficially?

**Comment by blakeblackshear** [comment]
How many cameras do you actually need to decode video for? The Jetson Nano seems a little lopsided. Not sure the processor has enough power to handle the downstream processing for 8 1080p30 streams.

**Comment by mattheys** [comment]
I only need 3 cameras, maybe a 4th soon. I've been looking to split the load of my RockPi as it runs 25 docker containers and was right at it's limits. Thought the new Jetson Nano would be a nice addition but I will also look at how good the Raspberry Pi optimsations are as that's even cheaper.

**Comment by blakeblackshear** [comment]
I think a 2gb RPi4 should be able to handle 4 cameras. The 64bit OS has great inference speeds. Some of it depends on how much motion you have under normal conditions. Just make sure you don't use resolutions or framerates that are unnecessarily high and configure masks to avoid processing areas that don't matter.

**Comment by mattheys** [comment]
I masked out some trees to make it more efficient a while ago, I will keep an eye on what happens, I fancy playing with the Jetson Nano anyway though :-|.
