### ISSUE TITLE
[Support]: Turn off Camera - Work around

### ISSUE THREAD

**Issue by sudheeshb** [blakeblackshear/frigate#2353]
### Describe the problem you are having

Hello,

I know here are multiple request to add a feature for enabling/disabling camera.  I am trying to achieve same thing with a work around till the proper solution is available.  I need couple of cameras ( out of total 4 ) to be turned off completely during day time.

Initially I used the single config file,  and just turned off the camera ( via automation based POE switch ) during day time.  But ffmpeg  is still running and keeps generating errors.  Not a good solution.

Now I am using two config files  one with two camera  and the other with 4 cameras, and night time I use config file with two cameras.  I also restart the frigate container after the config file swap.  This works fine and no ffmpeg errors as only two camera is present in the config file.  But looks like this approach delete the clips/recording related to the camera's which are turned off. Is that expected?.  Any other work around possible for this?

### Version

0.10.0  Beta 4

### Frigate config file

```yaml
Couple of files used.  One with two camera and the other with 4.  Config files swapped two times a day followed with frigate restart.
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest

**Comment by blakeblackshear** [comment]
I can't think of any workarounds.
