### ISSUE TITLE
MQTT events can get stuck ON

### ISSUE THREAD

**Issue by jasonmadigan** [blakeblackshear/frigate#236]
**Describe the bug**
I've noticed, while testing 0.7.0-rc1, that occasionally MQTT events can get stuck "ON". May be related to the detector crashing and restarting.

**Version of frigate**
What version are you using?
0.7.0-rc1

**Config file**
Include your full config file wrapped in back ticks.
```
config here
```

**Logs**
```
Include relevant log output here
```

**Frigate debug stats**
```
Output from frigate's /debug/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**

**Comment by blakeblackshear** [comment]
When that happens, do the video feeds also become stuck? I will be pushing a rc2 today to fix the issue with detection process restarts.

**Comment by jasonmadigan** [comment]
Yeah, the feeds tended to get stuck too, but then resume (although detected states stay on). I saw something that looked like a fix in rc2, will run that today.

**Comment by blakeblackshear** [comment]
Can you post /debug/stats too? Also, did the camera debug feeds recover this time?

**Comment by blakeblackshear** [comment]
All of those "On connect called" messages mean that the MQTT server is kicking you off. That usually happens if you have more than 1 frigate container running. That may be your real issue.

**Comment by jasonmadigan** [comment]
```
{"detection_fps":18.7,"detectors":{"coral":{"detection_start":0.0,"inference_speed":30.09,"pid":467}},"frontlawn":{"camera_fps":15.0,"detection_fps":0.0,"ffmpeg_pid":220,"frame_info":{"detect":1602596227.768613,"process":0.0,"read":1602596227.768613},"pid":270,"process_fps":15.0,"read_start":0.0,"skipped_fps":0.0},"garage":{"camera_fps":19.8,"detection_fps":0.0,"ffmpeg_pid":132,"frame_info":{"detect":1602596227.779159,"process":0.0,"read":1602596227.779159},"pid":268,"process_fps":19.9,"read_start":0.0,"skipped_fps":0.0},"garageinterior":{"camera_fps":12.0,"detection_fps":0.0,"ffmpeg_pid":264,"frame_info":{"detect":1602596227.718556,"process":0.0,"read":1602596227.718556},"pid":275,"process_fps":12.0,"read_start":0.0,"skipped_fps":0.0},"gate":{"camera_fps":15.0,"detection_fps":0.0,"ffmpeg_pid":69,"frame_info":{"detect":1602596227.763161,"process":0.0,"read":1602596227.763161},"pid":266,"process_fps":15.1,"read_start":0.0,"skipped_fps":0.0},"patio":{"camera_fps":12.0,"detection_fps":0.0,"ffmpeg_pid":201,"frame_info":{"detect":1602596227.790742,"process":0.0,"read":1602596227.790742},"pid":269,"process_fps":12.0,"read_start":0.0,"skipped_fps":0.0},"pumphouse":{"camera_fps":19.9,"detection_fps":18.7,"ffmpeg_pid":88,"frame_info":{"detect":1602596227.739288,"process":0.0,"read":1602596227.739288},"pid":267,"process_fps":19.8,"read_start":0.0,"skipped_fps":0.3}}
```

re those "On connect call" messages, maybe these maybe be related to either me keeping an eye on MQTT explorer? Seems odd alright, and I'm certain only one frigate container is running.

**Comment by blakeblackshear** [comment]
Check the logs for mosquitto

**Comment by jasonmadigan** [comment]
Yeah, just had a look - I see thousands of reconnects from frigate:

```
1602596505: New client connected from 192.168.1.231 as frigate (p2, c1, k60, u'frigate').
1602596506: New connection from 192.168.1.2 on port 1883.
1602596506: Client frigate already connected, closing old connection.
1602596506: New client connected from 192.168.1.2 as frigate (p2, c1, k60, u'frigate').
1602596507: New connection from 192.168.1.231 on port 1883.
1602596507: Client frigate already connected, closing old connection.
1602596507: New client connected from 192.168.1.231 as frigate (p2, c1, k60, u'frigate').
```

**Comment by jasonmadigan** [comment]
Update: I should've actually read the log. I found an old dev container running on another VM (192.168.1.231). Closing - was very likely the cause.
