### ISSUE TITLE
Responsive Live View

### ISSUE THREAD

**Issue by TonyBrobston** [blakeblackshear/frigate#2370]
**Describe what you are trying to accomplish and why in non technical terms**
I imagine this already exists in some capacity, however I'm having a hard time finding a live view that fits my needs. Currently I use Blue Iris' UI3 which fits about 95% of my needs.

In Frigate I enabled RTMP and got it working. I added "generic" cameras to Home Assistant, however this setup lacks the ability to watch all 5 of my cameras at the same time. I'm running Home Assistant and Frigate in a docker-compose, so I don't believe I have access to install the HACS integration.

I saw that `birdseye` has an option of `mode: continuous`, however when using this mode the web page isn't responsive to width changes. It works well on a desktop monitor, but when shrinking to a tablet or mobile sized screen it becomes difficult to use.

Is there another option that I have missed? Ideally Home Assistant would allow a card that can an RTMP stream.

**Describe the solution you'd like**
1. The ability to watch a substream of all my cameras at the same time.
2. When a substream video is clicked, it changes or redirects to the main stream of that camera.
3. As I change the width of the screen, the html elements should wrap.

**Describe alternatives you've considered**
I threw together a quick solution using the Frigate API endpoints. However I'm pretty torn with this solution, but it works for now.

`index.html`:
```
<html>
  <head>
    <style>
      .flex-container {
        display: flex;
        justify-content: center;
        max-width: 1200px;
      }

      .wrap { 
        flex-wrap: wrap;
      }
    </style>
  </head>
  <body>
    <div class="flex-container wrap">
      <a href="http://[your ip here]:5000/api/house_northeast?h=800&fps=15">
        <img src="http://[your ip here]:5000/api/house_northeast?h=300&fps=15">
      </a>
      <a href="http://[your ip here]:5000/api/house_east?h=800&fps=15">
        <img src="http://[your ip here]:5000/api/house_east?h=300&fps=15">
      </a>
      <a href="http://[your ip here]:5000/api/garage_north?h=800&fps=15">
        <img src="http://[your ip here]:5000/api/garage_north?h=300&fps=15">
      </a>
      <a href="http://[your ip here]:5000/api/garage_east?h=800&fps=15">
        <img src="http://[your ip here]:5000/api/garage_east?h=300&fps=15">
      </a>
      <a href="http://[your ip here]:5000/api/house_west?h=800&fps=15">
        <img src="http://[your ip here]:5000/api/house_west?h=300&fps=15">
      </a>
    </div>
  </body>
</html>
```
`Dockerfile`:
```
FROM nginx
COPY ./index.html /usr/share/nginx/html/
```
`docker-compose.yml`:
```
version: '3.8'

services:
  frigate:
    image: blakeblackshear/frigate:stable-amd64
    restart: unless-stopped
    privileged: true
    shm_size: '1g'
    ports:
    - 5000:5000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /frigate:/config
    - /frigate/recordings:/media/frigate/recordings
    - /frigate/clips:/media/frigate/clips
    env_file:
    - frigate.env
  
frigate-live-view:
    build: .
    restart: unless-stopped
    ports:
    - 5001:80
```
Some things for reference:
Home Assistant still image, but mostly responsive; Ideally this wouldn't be a still image but a RTMP substream:
![image](https://user-images.githubusercontent.com/4724577/144527921-f3f3a816-e892-455e-a507-c5a9d0840bef.png)
Blue Iris non-responsive page, but plays the substream, and when clicked it opens the main stream:
![image](https://user-images.githubusercontent.com/4724577/144528024-a7b6ddbf-e4c4-4e8b-83bf-ce504cc0ce8a.png)
Quick Vanilla HTML/CSS responsive solution I threw together; responsive, displays main stream but smaller, when clicked it opens the main stream but bigger:
![image](https://user-images.githubusercontent.com/4724577/144528173-8289a91d-f8ff-4dca-af17-bf779f05f2b6.png)

**Additional context**
I ideally wanted to build a page that could be iframed into Home Assistant, however the webpage card won't allow me to use the parent container's full width 🤷 .

If Home Assistant would add `allow-top-navigation` (which I can understand why they might not want to) to their iframe on the Webpage Card component, it may be possible to build an endpoint into frigate that returns html something like:
```
<html>
  <head>
  </head>
  <body>
      <a src="javascript:window.top.location.href = 'http://[your ip here]:5000/api/house_west?h=800&fps=15'">
        <img src="http://[your ip here]:5000/api/house_west?h=300&fps=15">
      </a>
    </div>
  </body>
</html>
```
Then build one Webpage Card component per camera. Somewhat hacky, but at this point I'll take what I can get 🤷 . I would like a solution in Home Assistant, that way it's as much of a one-stop-shop as possible.

**Comment by blakeblackshear** [comment]
Pulling that many mjpeg streams simultaneously is going to generate a good amount of load on the main thread. You will probably start to see it impact performance of processing, so that's probably not the best solution. Also, mjpeg is bandwidth hungry.

You most definitely can install the integration by downloading the integration and placing it in your custom_components folder. That's how I do it. Then I recommend checking out the custom lovelace card.

I can't think of an obvious way to recreate exactly the interface you have in UI3 in home assistant. However, I would be interested to understand more about the needs that interface meets for you. Frigate was designed to watch your feeds for you so you don't have to constantly stream and watch them. To give you an idea, I have a tab in home assistant that shows Birdseye with objects mode at the top and the most recent object from each camera using the custom card. I can quickly flip to live view for each camera from there if needed, but the Birdseye view is already showing the cameras tracking objects, so it's often not necessary.
