### ISSUE TITLE
[Support]: frigate hacs add-on stopped working on 2021-12 beta HASS

### ISSUE THREAD

**Issue by malosaa** [blakeblackshear/frigate#2384]
### Describe the problem you are having

i can't delete or add this add-on from hacs.
it was already installed on one machine and working
then i updated to  homeassistant v2021-21b0 it stopped working.
Frigate itself works normal, only the hacs addon doesnt work

i also checked it on a other machine, same issue, so the last beta of homeassistant has an issue with frigate-hacs add-on

Error occurred loading configuration flow for integration frigate: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### Version

0.9.4-26AE608

### Frigate config file

```yaml
not relevant, it worked before the beta
```

### Relevant log output

```shell
Error occurred loading configuration flow for integration frigate: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

random

**Comment by blakeblackshear** [comment]
This is an issue with the integration, not the addon. You need to update.

**Comment by malosaa** [comment]
> This is an issue with the integration, not the addon. You need to update.

o shit, i see i posted on the wrong one..
well 2.1.0 is last version so there is no update,

thanks
