### ISSUE TITLE
Optical Character/Dial Reading - For reading meters...

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#2385]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... 
** Read and convert a meter such as digital and/or dial

so that I can:
** Use this to produce a numeric indicating 1) Gas; 2) Power; 3) Water usage

** Perhaps create an object, and/or hook to opencv that will
* Detect a value change
* Publish that value  such as sensor.meter_cubic_feet

* OpenCV/MQTT - would only take a few lines

**Comment by alexelite** [comment]
This is a NVR system with smart motion->object detection. Why would you what it to do energy meter readings? 
You can use a dedicated system for this for about 10 euros. https://github.com/jomjol/AI-on-the-edge-device
It works very well with good dial illumination.

**Comment by doug62** [comment]
Thanks for that link, frigate uses opencv, meter reading is just a few lines of code on top of that - would be 'super easy' cos all the infrastructure is there
