### ISSUE TITLE
Birdseye RTSP Feed

### ISSUE THREAD

**Issue by peterhajas** [blakeblackshear/frigate#2387]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have a dedicated RTSP feed for the Birdseye feature so that I can use a dedicated display to show it fullscreen with VLC or mpv. It'd also be nice to set up a camera feed in Lovelace to watch it from a Home Assistant dashboard.

**Describe the solution you'd like**
If this would be low/no additional load on the frigate server, I could see an advertised rtsp://my_server:5000/birdseye or similar.
If it is an additional load, maybe an option in the configuration section for birdseye like this:

```
birdseye
    enabled: true
    rtsp_enabled: true
    quality: 5
    mode: continuous
```

**Describe alternatives you've considered**
I can show the `/frigate` URL fullscreen in a browser, but then I have the sidebar, hamburger menu, frigate logo, etc.

**Additional context**
Birdseye is a really cool feature. I could see enhancements to the contents of the stream to make it a nice glanceable way to see your home.

**Comment by blakeblackshear** [comment]
There is already a feature request for this. Have you looked at using the [lovelace card](https://docs.frigate.video/integrations/home-assistant#optional-lovelace-card-installation)?

**Comment by peterhajas** [comment]
D'oh - the Lovelace card does exactly this. Closing, thanks Blake!
