### ISSUE TITLE
Animated (gif) Preview in Notifications

### ISSUE THREAD

**Issue by craigmdennis** [blakeblackshear/frigate#2388]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to see motion in my notification previews themselves so that I can get a sense of what is happening without having to open the clips and watch it back. Very useful to see if someone is still at the door or has dropped a parcel and left.

**Describe the solution you'd like**
Nest Hello has a good implementation. 
When an event is triggered (e.g. doorbell) a notification appears (e.g. on my Android phone) showing the type of notification and a preview image; a gif replaying the last ~X seconds of motion as a low frame-rate gif.

This would require constant snapshots every ~X seconds to then stitch together at the point of the event.

**Describe alternatives you've considered**
Nest Hello.

**Additional context**
https://www.reddit.com/r/homeassistant/comments/fi86rb/love_the_push_notifications_with_the_app_put/
https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality
https://stackoverflow.com/questions/3688870/create-animated-gif-from-a-set-of-jpeg-images
https://selfhostedhome.com/unifi-video-motion-detection-gif-notifications/

I don't see another issue mentioning `gif` but please mark this as duplicate if needed. I'm sure there have been other requests for this that I'm not finding.

**Comment by blakeblackshear** [comment]
It's not an exact duplicate. This would likely be done via some post processing hook. Note that if you are using iOS, this is already possible in home assistant notifications.

**Comment by craigmdennis** [comment]
> Note that if you are using iOS, this is already possible in home assistant notifications.

Could you elaborate or provide a link to some documentation please? I may be missing a term when searching.

**Comment by blakeblackshear** [comment]
https://companion.home-assistant.io/docs/notifications/dynamic-content/#camera-stream

**Comment by clockworkant** [comment]
@blakeblackshear I think that the camera stream can only show the current live stream (real time MJPEG stream). Is there a convenient way to get access to the clip that triggered the detection via the mqtt api?

**Comment by blakeblackshear** [comment]
You would use the events topic and fetch the clip from the http endpoint with the event id.

**Comment by clockworkant** [comment]
Superb, works a treat, thank you.

Details for anyone else interested in this:
`id` from the topic `frigate/events` and then use
`<frigate-url>:<frigate-port>/api/events/<id>/clip.mp4`

**Comment by NickM-27** [comment]
I have added a PR to the android companion app to support this: https://github.com/home-assistant/companion.home-assistant/pull/705

**Comment by NickM-27** [comment]
there is now a preview gif api so from the frigate side this is closed

**Comment by Inrego** [comment]
@NickM-27 would be great if you could include a link to information about said api :)
With gif previews available in notifications in the latest HA app update, I suppose others like me could be directed to this topic from Google

**Comment by NickM-27** [comment]
There is nothing to link to yet as there is no beta. It has already been implemented on the frigate side

**Comment by Inrego** [comment]
So it is coming in the next release of Frigate?

**Comment by NickM-27** [comment]
yes, along with a complete ui rewrite

**Comment by JCBsystem** [comment]
Any news about this? i whuld also like to have a sort preview in the notifications 
(i use homey not HA)
Thank you

**Comment by NickM-27** [comment]
this has been implemented for a while now

**Comment by JCBsystem** [comment]
greate :) do you mind pointing me in the right direction in the docs?

**Comment by NickM-27** [comment]
https://docs.frigate.video/integrations/api#previews
