### ISSUE TITLE
Breaking change in Home Assistant 2021.12

### ISSUE THREAD

**Issue by bafplus** [blakeblackshear/frigate#2391]
### Describe the problem you are having

Although HA is giving suggestions for months Frigate is still not updated to stay working with Home Assistant.  From HA 2021.12 this will be a BREAKING CHANGE:

Setup failed for frigate: Unable to import component: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### Version

0

### Frigate config file

```yaml
0
```

### Relevant log output

```shell
0
```

### FFprobe output from your camera

```shell
0
```

### Frigate stats

```json
0
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

unrelevant

**Comment by blakeblackshear** [comment]
This is already being addressed: https://github.com/blakeblackshear/frigate-hass-integration/issues/181
