### ISSUE TITLE
[Support]: rtmp stream to Chromecast via homeassistant

### ISSUE THREAD

**Issue by kpcz** [blakeblackshear/frigate#2400]
### Describe the problem you are having

Cannot stream rtmp cameras from Frigate to Chromecast using hassio. Is it possible at all? 

Gives blank screen on Google Nest hub

`service: media_player.play_media
data:
  media_content_type: video
  media_content_id: rtmp://192.168.1.4/live/patio_cam
target:
  entity_id: media_player.living_room_display`

Also gives blank screen on chromecast

`service: camera.play_stream
data:
  media_player: media_player.living_room_display
  format: hls
target:
  entity_id: camera.patio_cam`

Is it possible to cast these streams on Chromecast devices at all? 
Thank you.

### Version

 0.9.4-26AE608

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Dafang, Dahua

**Comment by felipecrs** [comment]
I have the same problem. I wonder what is needed to configure.

**Comment by blakeblackshear** [comment]
It should work out of the box with the automatic camera entities from the integration if you have rtmp enabled and h264 streams with aac audio.

**Comment by felipecrs** [comment]
I do have all this, and all I get is a Home Assistant logo in my TV.

**Comment by kpcz** [comment]
I have the same - chromecast or google nest hub, shows blank screen with chromecast logo.  Will try to investigate further.

**Comment by felipecrs** [comment]
I said HA logo but in fact I meant Chromecast logo as @kpcz said.
![image](https://user-images.githubusercontent.com/29582865/148575922-c6cf76bd-456e-46c1-b3cb-20b708060979.png)

![image](https://user-images.githubusercontent.com/29582865/148575901-87c0f7f4-291c-443a-be9f-e3e88157762f.png)

**Comment by Pete1979** [comment]
I have this issue as well. Will investigate further.

**Comment by felipecrs** [comment]
The new Home Assistant Cast Action seems to work though. I don't know how different it is from the cast service.

**Comment by Pete1979** [comment]
> 

Its the Home Assistant Cast Action im trying to use. Getting this in the log when trying to cast from a camera.
2022-03-21 09:29:42 ERROR (Thread-9) [homeassistant.components.cast.media_player] Failed to cast media https://homeassistant.local:8123/api/hls/1cb6f6eaxxxxx40d54f4707xxxxxx9cc2905a439c242dfb403a23b48179a5c/master_playlist.m3u8?authSig=eyJ0eXAiOiJKV1QcvseEciOiJIUzI1NiJ9.eyJpc3MiOiJhOGQxN5ZkYWEwNDQ0ZTc3OGJkNDZiOGNmMmZiMzMzZCIsInBhdGgiOiIvYXBpL2hscy8xY2I2ZjZlYWVmZjIyHNeSuDU0ZjQ3MDdjZTk2NDI5OWNjMjkwNWE0MzljMjQyZGZiNDAzYTIzYjQ4MTc5YTVjL21hc3Rlcl9wbGF5bGlzdC5tM3UduglsWF0IjoxNjQ3ODUxMzc5LCJleHAiOjE2NDc5Mzc3Nzl9.9prsDE_2zjOhEx9NwM6XrSBjcdirkyfvofco-DMRiYQ from internal_url (https://homeassistant.local:8123). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
