### ISSUE TITLE
Is it possible to get Frigate to apply motion detection to a recorded clip ?

### ISSUE THREAD

**Issue by muzzak123** [blakeblackshear/frigate#2415]
I'm trying to debug and refine the detection of objects using Frigate.
I have some recorded clips where Frigate doesnt seem to have picked up on the objects in the clip.
I was wondering if there was a way I can use the "debug" feature to see motion triggers and bounding boxes on a recorded clip rather than on a live camera feed ?

**Comment by blakeblackshear** [comment]
See the config example in the developer docs: https://docs.frigate.video/contributing#setup

**Comment by muzzak123** [comment]
Brilliant, thanks Blake
