### ISSUE TITLE
[Support]: Learn to set correct FFmpeg arg

### ISSUE THREAD

**Issue by dedalusjinja** [blakeblackshear/frigate#2423]
### Describe the problem you are having

I have multiple cameras from different brands, cheap Chinese-Reolink-Tp-Link. I would like to understand what arguments to insert to improve my configuration. is there a well-explained list or a volunteer to help me?

### Version

-

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

-

**Comment by ozett** [comment]
sorry, i dont know how to assemble ffmpeg step-by-step.
but maybe a startpoint is the minimal configuration? -> https://docs.frigate.video/guides/getting_started#step-3-add-a-minimal-camera-configuration

**Comment by dedalusjinja** [comment]
I have already created my working configuration.  only the log is filled with errors like:
`ffmpeg.cam.record           ERROR   : [segment @ 0x55fccd911b00] Non-monotonous DTS in output stream 0:0; previous: 251330957, current: 251330957; changing to 251330958. This may result in incorrect timestamps in the output file. 
[ 2021-12-11 13:39:41] ffmpeg.strada.detect           ERROR   : rtsp://xxxxxxx : corrupt decoded frame in stream 0
[2021-12-11 13:39:41] ffmpeg.cam.detect             ERROR: [h264 @ 0x55c2de81d180] corrupted macroblock 11 37 (total_coeff=-1)
[2021-12-11 13:39:41] ffmpeg.cam.detect           ERROR   : [h264 @ 0x55c2de81d180] error while decoding MB 11 37 `

`The camera entity camera.cam_person does not support requesting width and height, please open an issue with the integration author `


Or no error in log but video streaming problems in rtmp or recorder. 
Configurations that I have found from other users do not work because they make my camera green, or other errors in the logs or even worse streams.  So i would like to understand where to start to create a right set of ffmpeg args for each camera

**Comment by ozett** [comment]
try this with your cams and show some results to help you out..
https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player

**Comment by dedalusjinja** [comment]
thanks but i already have the exact streams of each cam, i would like to refine my setup
