### ISSUE TITLE
Home Assistant Integration:  Provide a single detection object with parameterized attributes

### ISSUE THREAD

**Issue by rsteckler** [blakeblackshear/frigate#2433]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to setup a single automation in HA that triggers on "object detected by frigate", where I can then grab the object type and camera source to be passed along to other scripts.

**Describe the solution you'd like**
A single "frigate_object_detected" sensor with attributes for:
- object type
- camera source
- timestamp

**Describe alternatives you've considered**
Right now, I have multiple automations.  For example:
- Person detected at the driveway camera
- Car detected at the driveway camera
- Person detected at the front gate camera
- Car detected at the front gate camera
Those all call a single script (object_detected) and pass in the unique combination of object type and camera location.  The total number of automations is number_of_cameras * number_of_object_types.  I have 16 cameras and detect 6 object types, so this requires 96 automations.  
These could all be replaced with a single "detection sensor" from frigate.

**Additional context**
Thanks for building an awesome product!!!

**Comment by blakeblackshear** [comment]
Have you thought about using the events mqtt topic? That will also give you the unique ID and allow you to fetch images and other info about the object.

**Comment by rsteckler** [comment]
I hadn't considered using the MQTT topics.  Actually, just after I submitted this request, I went and figured out how to create a template in HA using Jinja2 (what a terrible language) to solve this.  Here's that script for those who want it:
```
- sensor:
  - name: motion_detection
    state: >
      {# Check all the entities from the Frigate integration #}
      {%- for entity in integration_entities('frigate') %}
        {# get just the entity name part of the entity id #}
        {%- set parts = entity.split('.') %}
        {# Check if this is one of the 'motion' sensors #}
        {%- if 'motion' in parts[1] %}
          {# Check if this motion sensor is currently detecting an object #}
          {%- if states(entity) == 'on' %}
            {# Split up the name of this entity by its underscores #}
            {%- set subparts = parts[1].split('_') %}
            {# By default, jinja2 doesnt let you create a variable outside the scope of a for loop, then update it inside.  This namespace allows that #}
            {%- set ns = namespace(camera_ref='camera_ref: ') %}
            {# Loop through the parts of the entity name, separated by underscore #}
            {# An example of a entity name is camera_back_patio_person_motion #}
            {%- for subpart in subparts %}
              {# The object name is always the second-to-last part of the name (example: person) #}
              {%- if (loop.revindex == 2) %}
                {{ 'object: ' ~ subpart }}
              {# Skip the last token, which is always 'motion' #}
              {%- elif (loop.revindex == 1) %}
              {# Skip the first token, which is always 'camera' #}
              {%- elif (loop.index == 1) %}
              {# The rest of the tokens are the name of the camera location (example: back_patio) #}
              {# If its the scond token in the name, this is the first part of the name (example: back) #}
              {# Otherwise, its a later part of the name and we should prepend an underscore (example: patio becomes _patio) #}
              {%- elif (loop.index == 2) %}
                {%- set ns.camera_ref = ns.camera_ref ~ subpart %}
              {%- else %}
                {%- set ns.camera_ref = ns.camera_ref ~ '_' ~ subpart %}
              {%- endif %}
            {%- endfor %}
            {# output the resulting camera ref name #}
            {{ ns.camera_ref }}
          {%- endif %}
        {%- endif %}
      {%- endfor %}
```

Note this works for current frigate HA entity ids, which are always:  camera_<camera_name>_<object>_motion
