### ISSUE TITLE
[Support]: Camera image smeared

### ISSUE THREAD

**Issue by Se7enair** [blakeblackshear/frigate#2446]
### Describe the problem you are having

Sometimes it happens, that the image of the camera is generating stripes.
![image](https://user-images.githubusercontent.com/1680106/145869819-8b267c8a-9332-477f-8598-5e7063b36607.png)

Dont know when it started. Config seems to be ok, because this issue is not happening the whole time. It comes and goes.
The stream itself is good. When I connect directly to the camera, everything looks fine.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: [redacted]
  user: [redacted]
  password: [redacted]
cameras:
  hof:
    ffmpeg:
      hwaccel_args:
        - -c:v
        - h264_v4l2m2m
      inputs:
        - path: rtsp://user:passwd@[redacted] 
          roles:
            - rtmp
            - record
            - detect
    detect:
      max_disappeared: 100
      width: 1920
      height: 1072
      fps: 5
    objects:
        track:
          - person
          - car
          - dog
          - bicycle
          - cat
          - bird
    motion:
      mask:
        - 963,0,871,232,608,387,0,468,0,1072,0,0    
        - 1920,1072,1564,1072,1740,0,1920,0
      threshold: 50
      contour_area: 150
    zones:  
      strasse:
        coordinates: 941,239,1724,261,1734,66,983,65  
      einfahrt:
        coordinates: 553,454,0,480,0,1010,573,1001,570,1072,1564,1072,1749,253,945,225
    snapshots:
      enabled: true
      crop: false
      retain:
        default: 30
        objects:
          person: 40
    record:
      enabled: true
      retain_days: 0
      events:
        pre_capture: 12
        retain:
          default: 10
          objects:
            person: 15

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=60: bad cseq 42a8 expected=8fd7
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=61: bad cseq bc01 expected=a9b9
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=60: bad cseq 8fd7 expected=42aa
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=60: bad cseq 42aa expected=8fd9
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=61: bad cseq a9ba expected=bc03
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=60: bad cseq 8fd9 expected=42ac
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=60: bad cseq 42ac expected=8fdb
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=61: bad cseq bc04 expected=a9bc
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=60: bad cseq 8fdb expected=42ae
[2021-12-13 08:25:38] ffmpeg.hof.detect              ERROR   : [rtsp @ 0x55c42dfe60] RTP: PT=60: bad cseq 42ae expected=8fdd
```

### FFprobe output from your camera

```shell
dont know how to do that
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Reolink RLC-410W

**Comment by Se7enair** [comment]
Homeassistant is throwing this log

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

```
Logger: custom_components.frigate
Source: helpers/update_coordinator.py:219
Integration: Frigate (documentation, issues)
First occurred: 20:40:32 (1 occurrences)
Last logged: 20:40:32

Error fetching frigate data:
```

**Comment by Minglarn** [comment]
Im using REOLINK cams as well. The RTSP stream sucks big time... 
RTSP stream suffers from smearing. Use the RTMP or HTTP stream instead.

**Comment by Se7enair** [comment]
Sounds like a solution. Searched for it and there were many reports that RTMP solves this issues.
"Smearing" was the word which describes the problem.

Will report when tested.

**Comment by Minglarn** [comment]
Im using these urls...
```
        - path: rtmp://192.168.1.XXX/bcs/channel0_main.bcs?channel=0&stream=1&user=admin&password=secret
OR
        - path: http://192.168.1.XXX/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=secret
```
For sub streams, replace main with sub... like:
`- path: rtmp://192.168.1.XXX/bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password=secret`

Hope it helps.

**Comment by Se7enair** [comment]
Changed to HTTP. It is working. Will observe it for a few days-

But there seems to be a mistake in the documentation.
https://docs.frigate.video/configuration/camera_specific
This says:
```
cameras:
  reolink:
    ffmpeg:
      hwaccel_args:
      input_args:
        - -avoid_negative_ts
        - make_zero
```
But this results in a error that hwaccel_args cannot be null.
Should I open a issue?

When I delete it, it works fine.

**Comment by Minglarn** [comment]
Witch is true.. hwaccel_args cant be null...
Delete it if it works for you. 
You can set the args globally for all cams. Depending on your CPU it differs. 
This is what I've set for all my cams. This is working fine for a I5-6500T Intel CPU. 
```
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

**Comment by Minglarn** [comment]
Don't know but... 
According to https://deploy-preview-1927--frigate-docs.netlify.app/guides/getting_started you have to specify _args ...

**Comment by Se7enair** [comment]
Problem is solved with the HTTP stream.
