### ISSUE TITLE
Submeny for events EVENTS->OBJECTS and MOTION

### ISSUE THREAD

**Issue by Minglarn** [blakeblackshear/frigate#2448]
**Describe what you are trying to accomplish and why in non technical terms**
As the RECORDING function has been able to distinguish when there are OBJECTS, MOTION and 24/7 I would like to have an sub menu for EVENTS. 
![image](https://user-images.githubusercontent.com/58695742/145967938-3d9ba242-38e0-4646-9615-e5c465c0c191.png)

**Describe the solution you'd like**
Under "EVENTS" menu we could put sub menus for "OBJECTS, MOTION and/or 24/7 recordings."
By this sub menus it would bee so much easier for the user to search for MOTION only/OBJECTS only recordings. 
I thought I saw that there where a new table created in beta5 for "motion" only recordings. 

**Describe alternatives you've considered**
Or we could create a new label for recorded events "MOTION" witch could be show in the EVENT list. But it wont do any good if there is no filter to apply. 

**Additional context**
Sorry for my bad grammatical English... :)

**Comment by BBaoVanC** [comment]
I still want this feature

**Comment by blakeblackshear** [comment]
It won't be implemented in this way, but there will definitely be ways to view motion levels in recordings in the future.
