### ISSUE TITLE
Add ability to make Frigate API read-only

### ISSUE THREAD

**Issue by nbartos** [blakeblackshear/frigate#2459]
**Describe what you are trying to accomplish and why in non technical terms**
I want to have a decent interface to look at recordings on mobile. While the home assistant app technically can do this via the media browser (although doesn't seem to be possible to use h265), it is much more annoying to navigate than Frigate's web interface.

Since Frigate only has a private API with no auth/permissions, allowing access to that API from remote devices can be a problem. While I am using VPN that cuts down a major remote attack vector, but it's still possible to have someone gain access and disable recording or object detection before doing something nefarious. Also, I find it is easy for me to accidentally hit those buttons to disable recording or object detection on my small phone screen.

**Describe the solution you'd like**
Adding some option in frigate's config yaml that will not allow requests to happen via the API that would be bad for a security monitoring product, e.g. disabling recordings/events and deleting recordings/events. Bonus would be the ability to disable each thing separately.

**Describe alternatives you've considered**
I was planning on using a reverse nginx proxy to add ssl so I could use the frigate web interface in a home assistant iframe (which hopefully works in the android mobile app), likely also adding http basic auth (assuming that worked ok in the ha iframe), since the frigate API doesn't have auth. I tried to see if I could reject certain HTTP requests that would only be used in these situations (e.g. POST), but it looks like it's just doing everything over a websockets connection so I don't think I can do that.

**Additional context**
Alternatively if there was any way of improving the home assistant media source player to work as well as the frigate web interface, or if there is some other type of solution that used a different mobile app, that would be acceptable. I'm only using home assistant for frigate object notifications. I had originally tried using zoneminder with zkninja as technically that should work, but getting ML going in a sustainable manor with zoneminder proved to be very difficult, whereas frigate "just works".

**Comment by chander** [comment]
I just have nginx in front of my frigate install and add this to the proxy section:

```
limit_except GET {
            deny all;
        }
```

I use lets encrypt to provide ssl support for my install, and expose frigate to external users via an https url.

More completely:

```
server {
    listen       10.0.1.8:443 ssl;
    server_name  frigate.myhost.mydomain;

    #ssl on;
    ssl_certificate /etc/letsencrypt/live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/privkey.pem;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://localhost:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        limit_except GET {
            deny all;
        }

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```
