### ISSUE TITLE
Resolution and detection

### ISSUE THREAD

**Issue by mcondren** [blakeblackshear/frigate#247]
At one point I saw a comment saying that the detection model was trained on 300x300 images and keeping zones/feed resolution close to that was best. That was before dynamic zones, however. Increasing resolution of my rtsp feed will allow people to be visible as people at greater distances, which is what I am looking for, but I’m wondering if the previous resolution guidance is still an issue/valid with 0.7. 

Thanks.

**Comment by blakeblackshear** [comment]
Not sure where the misunderstanding came from, but the guidance has always been to choose a resolution where the smallest object you want to detect fits in a 300x300 pixel square. Frigate has never passed the entire frame into object detection, even in version 0.0.1.

**Comment by mcondren** [comment]
Good to know. Thank you!

**Comment by HITChris** [comment]
If I'm understanding things correctly -- when motion is registered, Frigate cuts a 300x300 square out over the center of the contour area, and runs detection against it. In that case, so as to more reliably detect objects at distance, I'd probably want to increase resolution from 480p to something like 1080 (e.g., making the object-at-distance occupy a larger portion of the 300x300 square that gets pulled into the detect), right?

**Comment by blakeblackshear** [comment]
Correct
