### ISSUE TITLE
Continuous broken frame errors on all cameras

### ISSUE THREAD

**Issue by mcondren** [blakeblackshear/frigate#248]
**Describe the bug**
Log shows broken frame error and ffmpeg restart for each camera every few seconds

**Version of frigate**
0.7.0-2c2

**Config file**
Include your full config file wrapped in back ticks.
```

ffmpeg:
  global_args:
#     - -hide_banner
    - -loglevel
    - debug
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
take_frame: 3
    

objects:
  track:
    - person
  filters:
    person:
      threshold: 0.8
      min_area: 0

cameras:
  driveway:
    ffmpeg:
      input: rtsp://192.168.1.2:7447/G0nYBtl4wV81uzEZ
    snapshots:
      show_timestamp: False

 backporch:
    ffmpeg:
      input: rtsp://192.168.1.2:7447/IwDvC2YOoejswame
    snapshots:
      show_timestamp: False
      
 sidedoor:
    ffmpeg:
      input: rtsp://192.168.1.2:7447/wpi0Mb7fut0U67a7
    snapshots:
      show_timestamp: False
      
  frontdoor:
    ffmpeg:
      input: rtsp://192.168.1.2:7447/cpgnTEzfdqIt9Ote
    snapshots:
      show_timestamp: False

```

**Logs**
```

  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2),
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib,
  libavutil      56. 51.100 / 56. 51.100,
  libavcodec     58. 91.100 / 58. 91.100,
  libavformat    58. 45.100 / 58. 45.100,
  libavdevice    58. 10.100 / 58. 10.100,
  libavfilter     7. 85.100 /  7. 85.100,
  libavresample   4.  0.  0 /  4.  0.  0,
  libswscale      5.  7.100 /  5.  7.100,
  libswresample   3.  7.100 /  3.  7.100,
  libpostproc    55.  7.100 / 55.  7.100,
Splitting the commandline.,
Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.,
Reading option '-hwaccel' ... matched as option 'hwaccel' (use HW accelerated decoding) with argument 'vaapi'.,
Reading option '-hwaccel_device' ... matched as option 'hwaccel_device' (select a device for HW acceleration) with argument '/dev/dri/renderD128'.,
Reading option '-hwaccel_output_format' ... matched as option 'hwaccel_output_format' (select output format used with HW accelerated decoding) with argument 'yuv420p'.,
Reading option '-avoid_negative_ts' ... matched as AVOption 'avoid_negative_ts' with argument 'make_zero'.,
Reading option '-fflags' ... matched as AVOption 'fflags' with argument 'nobuffer'.,
Reading option '-flags' ... matched as AVOption 'flags' with argument 'low_delay'.,
Reading option '-strict' ...Routing option strict to both codec and muxer layer,
 matched as AVOption 'strict' with argument 'experimental'.,
Reading option '-fflags' ... matched as AVOption 'fflags' with argument '+genpts+discardcorrupt'.,
Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'tcp'.,
Reading option '-stimeout' ... matched as AVOption 'stimeout' with argument '5000000'.,
Reading option '-use_wallclock_as_timestamps' ... matched as AVOption 'use_wallclock_as_timestamps' with argument '1'.,
Reading option '-i' ... matched as input url with argument 'rtsp://192.168.1.2:7447/wpi0Mb7fut0U67a7'.,
Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.,
Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.,
Reading option 'pipe:' ... matched as output url.,
Finished splitting the commandline.,
Parsing a group of options: global .,
Applying option loglevel (set logging level) with argument debug.,
Successfully parsed a group of options.,
Parsing a group of options: input url rtsp://192.168.1.2:7447/wpi0Mb7fut0U67a7.,
Applying option hwaccel (use HW accelerated decoding) with argument vaapi.,
Applying option hwaccel_device (select a device for HW acceleration) with argument /dev/dri/renderD128.,
Applying option hwaccel_output_format (select output format used with HW accelerated decoding) with argument yuv420p.,
Successfully parsed a group of options.,
Opening an input file: rtsp://192.168.1.2:7447/wpi0Mb7fut0U67a7.,
[tcp @ 0x5573614e0480] No default whitelist set,
[tcp @ 0x5573614e0480] Original list of addresses:,
[tcp @ 0x5573614e0480] Address 192.168.1.2 port 7447,
[tcp @ 0x5573614e0480] Interleaved list of addresses:,
[tcp @ 0x5573614e0480] Address 192.168.1.2 port 7447,
[tcp @ 0x5573614e0480] Starting connection attempt to 192.168.1.2 port 7447,
[tcp @ 0x5573614e0480] Successfully connected to 192.168.1.2 port 7447,
[rtsp @ 0x5573614ddac0] SDP:,
v=0
,
o=- 647 0 IN IP4 192.168.1.2
,
s=B4FBE4FF8A44_1
,
u=www.evostream.com
,
e=contact@evostream.com
,
c=IN IP4 192.168.1.2
,
t=0 0
,
a=recvonly
,
a=control:*
,
a=range:npt=now-
,
m=audio 0 RTP/AVP 96
,
a=recvonly
,
a=rtpmap:96 mpeg4-generic/11025/1
,
a=control:trackID=1
,
a=fmtp:96 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1508; SizeLength=13; IndexLength=3; IndexDeltaLength=3;
,
m=video 0 RTP/AVP 97
,
a=recvonly
,
a=control:trackID=2
,
a=rtpmap:97 H264/90000
,
a=fmtp:97 profile-level-id=4d401f; packetization-mode=1; sprop-parameter-sets=Z01AH5pkAgAk//+AXoBfNwEBAUAAAPoAAB1MJ2giEag=,aO48gA==
,
,
[rtsp @ 0x5573614ddac0] audio codec set to: aac,
[rtsp @ 0x5573614ddac0] audio samplerate set to: 11025,
[rtsp @ 0x5573614ddac0] audio channels set to: 1,
[rtsp @ 0x5573614ddac0] video codec set to: h264,
[rtsp @ 0x5573614ddac0] RTP Profile IDC: 4d Profile IOP: 40 Level: 1f,
[rtsp @ 0x5573614ddac0] RTP Packetization Mode: 1,
[rtsp @ 0x5573614ddac0] Extradata set to 0x5573614de2e0 (size: 44),
[rtsp @ 0x5573614ddac0] setting jitter buffer size to 0,
    Last message repeated 1 times,
[rtsp @ 0x5573614ddac0] hello state=0,
[h264 @ 0x5573614e5380] nal_unit_type: 7(SPS), nal_ref_idc: 3,
[h264 @ 0x5573614e5380] nal_unit_type: 8(PPS), nal_ref_idc: 3,
[h264 @ 0x5573614e5380] nal_unit_type: 7(SPS), nal_ref_idc: 3,
[h264 @ 0x5573614e5380] nal_unit_type: 8(PPS), nal_ref_idc: 3,
[rtsp @ 0x5573614ddac0] Could not find codec parameters for stream 1 (Video: h264, 1 reference frame, none): unspecified size,
Consider increasing the value for the 'analyzeduration' and 'probesize' options,
Input #0, rtsp, from 'rtsp://192.168.1.2:7447/wpi0Mb7fut0U67a7':,
  Metadata:,
    title           : B4FBE4FF8A44_1,
  Duration: N/A, bitrate: N/A,
    Stream #0:0, 0, 1/11025: Audio: aac, 11025 Hz, mono, fltp,
    Stream #0:1, 0, 1/90000: Video: h264, 1 reference frame, none, 90k tbr, 90k tbn, 180k tbc,
Successfully opened the file.,
Parsing a group of options: output url pipe:.,
Applying option f (force format) with argument rawvideo.,
Applying option pix_fmt (set pixel format) with argument yuv420p.,
Successfully parsed a group of options.,
Opening an output file: pipe:.,
Output #0, rawvideo, to 'pipe:':,
Output file #0 does not contain any stream,
sidedoor: ffmpeg sent a broken frame. something is wrong.,
sidedoor: ffmpeg process is not running. exiting capture thread...,

```

**Frigate debug stats**
```

{"backporch":{"camera_fps":15.0,"detection_fps":0.0,"ffmpeg_pid":116,"frame_info":{"detect":1602959042.247066,"process":0.0,"read":1602959042.247066},"pid":50,"process_fps":15.0,"read_start":0.0,"skipped_fps":0.0},"detection_fps":29.4,"detectors":{"coral":{"detection_start":0.0,"inference_speed":7.5,"pid":16}},"driveway":{"camera_fps":14.9,"detection_fps":29.4,"ffmpeg_pid":56,"frame_info":{"detect":1602959042.197116,"process":0.0,"read":1602959042.197116},"pid":49,"process_fps":15.1,"read_start":0.0,"skipped_fps":0.0},"frontdoor":{"camera_fps":15.0,"detection_fps":0.0,"ffmpeg_pid":62,"frame_info":{"detect":1602959042.20941,"process":0.0,"read":1602959042.20941},"pid":52,"process_fps":15.0,"read_start":0.0,"skipped_fps":0.0},"sidedoor":{"camera_fps":15.0,"detection_fps":0.0,"ffmpeg_pid":60,"frame_info":{"detect":1602959042.257405,"process":0.0,"read":1602959042.257405},"pid":51,"process_fps":15.1,"read_start":0.0,"skipped_fps":0.0}}

```

**FFprobe from your camera**

Run the following command and paste output below
```
Included in debug logs
```

**Computer Hardware**
 - OS: Debian 
 - bare metal Docker
 - Coral Version: USB

**Camera Info:**
 - Manufacturer: unifi G3 x2, unifi flex x1, unifi G4 doorbell x1
 - Resolution: 720p
 - FPS: 15

**Additional context**
Apologies for debug and stats section. Cannot figure out how to get code blocks to word wrap in markdown.

**Comment by blakeblackshear** [comment]
Does this not happen on previous versions?

**Comment by mcondren** [comment]
It was happening on my doorbell cam occasionally when all cameras were using 640x480. After switching to 1024x768 rtsp streams it happens on all cameras. All cameras have wired 100mb connection directly to docker host. 0.7 for both. 

While the broken frame errors increased significantly after increasing resolution, I have been getting more and more ‘eating ffmpeg process’ errors on each camera stream each time I upgrade. I didn’t want to add that to this issue, though, since it’s a different error.

**Comment by mcondren** [comment]
I saw something in debug about ‘ Could not find codec parameters for stream 1 (Video: h264, 1 reference frame, none): unspecified size,’. Wasn’t sure if it couldn’t figure out the resolution and that was causing the issue.

**Comment by mcondren** [comment]
Here is about 10 seconds of log. 

‘’’
eating ffmpeg process...

ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.2:7447/cpgnTEzfdqIt9Ote -f rawvideo -pix_fmt yuv420p pipe:

driveway: ffmpeg sent a broken frame. something is wrong.

driveway: ffmpeg process is not running. exiting capture thread...

backporch: ffmpeg sent a broken frame. something is wrong.

backporch: ffmpeg process is not running. exiting capture thread...

eating ffmpeg process...

ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.2:7447/G0nYBtl4wV81uzEZ -f rawvideo -pix_fmt yuv420p pipe:

eating ffmpeg process...

ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://192.168.1.2:7447/IwDvC2YOoejswame -f rawvideo -pix_fmt yuv420p pipe:
‘’’

**Comment by blakeblackshear** [comment]
All of those errors are from ffmpeg, not frigate. Looks like ffmpeg is having trouble maintaining a reliable feed from your cameras and the exits. You should be able to copy the ffmpeg command from the logs and run with `> /dev/null` at the end to try and tweak the default input parameters. Not sure what you need to change though.

The "eating ffmpeg process" is really just a cutoff message that should say "creating ffmpeg process". When ffmpeg errors out and sends a broke frame, frigate will create a new process and you will see that message.

**Comment by blakeblackshear** [comment]
Those logs are telling you that ffmpeg is failing to read from your camera and exiting. Frigate is restarting ffmpeg, and the cycle continues.

**Comment by tubalainen** [comment]
@mcondren I had similar issues and I managed to narrow it down to a netgear switch. I changed it (I run UBNT/Unify all over now) and that solved my issue. Home Assistant (in my case) also reported different issues with the stream component in its log.

You could try to change the ffmpeg '-rtsp_transport tcp' to '-rtsp_transport udp' and see if that helps.

**Comment by mcondren** [comment]
Thank you @tubalainen , I’ll give that a try. However, it seems to have calmed down. On frigate startup I get a lot of those errors, but then it stabilizes and I haven’t received one in a few hours.

**Comment by mcondren** [comment]
Hmm, they started up again so I did a few tests. I tried changing rtsp transport to udp. No apparent change. 

I also installed ffmpeg outside the container and ran the same command in debug in one window, and then started up the frigate container logs in another window. When I started up frigate I got multiple broken frame errors and restarting ffmpeg error from the same stream I was running outside of frigate in the other window, however, the stream outside frigate continued to run fine and output clean debug. I finally stopped it and it showed now errors. This is at the exact same time period that frigate was reporting broken frames and hung ffmpeg processes from the same stream. 

Here is the perfectly fine 3 minute run from outside frigate. 


frame= 2697 fps= 15 q=-0.0 Lsize= 2730712kB time=00:02:59.80 bitrate=124416.0kbits/s dup=6 drop=4 speed=1.01x              
video:2730712kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Input file #0 (rtsp://192.168.1.2:7447/cpgnTEzfdqIt9Ote):
  Input stream #0:0 (audio): 8437 packets read (1380856 bytes);                                                            
  Input stream #0:1 (video): 2699 packets read (14777968 bytes); 2696 frames decoded;                                      
  Total: 11136 packets (16158824 bytes) demuxed                                                                            
Output file #0 (pipe:):                                                                                                    
  Output stream #0:0 (video): 2697 frames encoded; 2697 packets muxed (2796249600 bytes);                                  
  Total: 2697 packets (2796249600 bytes) muxed                                                                             
2696 frames successfully decoded, 0 decoding errors                                                                        
[AVIOContext @ 0x55e83d929c00] Statistics: 0 seeks, 86304 writeouts                                                        
Exiting normally, received signal 2.

**Comment by mcondren** [comment]
Huh...figured it out.  Re-added vsync -drop to the input params and it stopped getting broken frames.  No clue why.  Also seems to have stopped eating and recreating ffmpeg processes.  I'll let it run for a few hours to confirm.

**Comment by blakeblackshear** [comment]
Note that adding vsync drop will break the clips feature.

**Comment by blakeblackshear** [comment]
What version of ffmpeg are you running outside of the container?

**Comment by mcondren** [comment]
Thanks. Luckily I don’t use clips. Version outside of container is 4.1.6.

**Comment by mcondren** [comment]
Log is still clean as a whistle with vsync -drop. That definitely did it for whatever reason.

**Comment by blakeblackshear** [comment]
Technically vsync drop just tells ffmpeg to drop bad frames, so you are probably just dropping them upstream of frigate.

**Comment by mcondren** [comment]
I’m not a python coder but another side effect of dropping them early is that it seems like it also avoids hitting the the code in video.py that restarts the capture thread when it thinks there is a bad frame. Which may or may not be a benefit?

**Comment by blakeblackshear** [comment]
It doesn't restart the capture thread. It just skips it and gets the next frame. It only starts again if ffmpeg exits on its own. Not sure why it's exiting in the container, but not outside of it.

**Comment by mcondren** [comment]
Ok, thanks. I’ll close this one out for now. Since my feeds seem to be at fault.
