### ISSUE TITLE
Toggle camera RTMP on the fly

### ISSUE THREAD

**Issue by bemble** [blakeblackshear/frigate#2485]
Hi, first of all, thanks a lot for your work, it helps a lot to automate lot of things for me.

**Describe what you are trying to accomplish and why in non technical terms**
To respect my own privacy at home, I would like to turn RTMP while there is someone at home/in a room.

**Describe the solution you'd like**
The ideal solution would be to turn RTMP streaming on/off on the fly per camera.

**Describe alternatives you've considered**
Streaming a blurred/black screen would be an acceptable alternative.

**Comment by vakilando** [comment]
Just saw this as it became stale...
Yes, I also think this would add a possibility to respect privacy at home!
Coming from Xeoma, where this is possible I am missing this feature.

**Comment by blakeblackshear** [comment]
RTMP is a direct pass through from the camera, so that specifically cant be turned off. You can use the switches in home assistant to turn detect/record/snapshots off when someone is home.

**Comment by pierrecle** [comment]
> RTMP is a direct pass through from the camera, so that specifically cant be turned off. You can use the switches in home assistant to turn detect/record/snapshots off when someone is home.

Thanks for your reply.
Actually the only way to be sure that the stream is not available in HA is to disable the camera. But the only way to disable a device in HA is in the UI (or by using the websocket call done by the UI), but nothing "official" in the api.

Is it possible to turn off RTMP proxy in nginx?
