### ISSUE TITLE
How to export a portion of recorded footage?

### ISSUE THREAD

**Issue by jonwork88** [blakeblackshear/frigate#2486]
Hi Blackblackshear - first off, thanks so much for this great application.  I moved from wifi based cameras with cloud integrations to POE cameras using Frigate - its been a lot of fun getting a real NVR system up and running on my Unraid box.  

**Describe what you are trying to accomplish and why in non technical terms**
Is there a way in the UI where we can identify a portion of a recording (we record 24/7) and export it as a separate file?  We picked up 2 foxes in our backyard last night and I would love to export a clip of it to share with friends / family.  I have had several other instances of picking up things on my cameras and wanting to export those sections as a separate file - but didn't see a way to do it.

**Describe the solution you'd like**
If there was a way to mark a start and end on the timeline and have it clip that and allow me to save that somewhere that would be ideal.

**Describe alternatives you've considered**
I could grab the 1 minute sections from the recording folder and try to force them together into a separate file, but I don't want to mess too much with those, I assume they are almost like "system files" for Frigate?  Certainly more difficult to work with vs being able to do it within the UI.   

Again - thanks for all your great work, its a great application!

Jon

**Comment by blakeblackshear** [comment]
There is no UI for it, but there is an endpoint available: https://github.com/blakeblackshear/frigate/issues/2369#issuecomment-985141654
