### ISSUE TITLE
Add CLIPS_DIR as environment variable

### ISSUE THREAD

**Issue by mories76** [blakeblackshear/frigate#249]
Would you consider adding CLIPS_DIR as en environment variable for the folder where to save clips.

This way one can choose where to store the saved clips for example in /media/frigate so the media browser can access these files easily.

**Comment by mories76** [comment]
Or even better, as an option in the global configuration for saving clips in config.yml

**Comment by mories76** [comment]
Is it ok if I open a PR for adding a clips_dir configuration option ?

**Comment by blakeblackshear** [comment]
I can add it today.

**Comment by mories76** [comment]
That would be nice, I do have a suggestion on my fork.

I am trying to follow your changes, with an HA-Addon. Don't know if you where aware of that.

**Comment by blakeblackshear** [comment]
I'm making an official addon today.

**Comment by mories76** [comment]
That's nice, have you taken a look at mine ? 
[](https://github.com/mories76/ha-addon-frigate)
I've been using this addon with your software for months now.

**Comment by blakeblackshear** [comment]
Just did. Thanks for the head start. I can use some of your config.json for inspiration.

**Comment by mories76** [comment]
If I can be of any assistance please let me know.
It was quite an adventure getting it running. Learning by doing.
 
I am mories#1950 on discord.

**Comment by mories76** [comment]
Solved in 0.7.0
clips_dir is configurable in configuration
