### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by tortho** [blakeblackshear/frigate#2491]
### Describe the problem you are having

Not able to use Coral TPU

### Version

3.2 0.10 beta 6

### Frigate config file

```yaml
#DETECTORS - CORAL
detectors:
  coral_pci:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
[2021-12-20 11:50:34] detector.coral_pci             INFO    : Starting detection process: 527
W driver/beagle/beagle_kernel_top_level_handler.cc:131] Could not set performance expectation : 122 (Inappropriate ioctl for device)
[2021-12-20 11:50:34] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2021-12-20 11:50:34] frigate.edgetpu                INFO    : TPU found
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
E driver/mmio_driver.cc:254] HIB Error. hib_error_status = 0000000000002200, hib_first_error_status = 0000000000000200
[2021-12-20 11:50:54] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2021-12-20 11:50:54] root                           INFO    : Waiting for detection process to exit gracefully...
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Foscam

### Any other information that may be helpful

This is the coral dual edge tpu
https://docs.rs-online.com/15f6/A700000007334657.pdf

This is probably the issue but I cant find any way to do this on HAOS
https://coral.ai/docs/m2/get-started/#troubleshooting-on-linux

This is the computer which supports that the above might be the issue.
https://www.asus.com/Displays-Desktops/Mini-PCs/PN-PB-series/Mini-PC-PN51/techspec/

**Comment by blakeblackshear** [comment]
I don't have any input beyond what you already found.

**Comment by tortho** [comment]
Something we should report elsewhere? File a bug towards haos?
Not sure how it can be tested to see if it works

**Comment by ozett** [comment]
what about appling to mentioned solution? :
" You should be able to solve it if you modify your kernel command line arguments to include gasket.dma_bit_mask=32."

**Comment by tortho** [comment]
Don't think I'm able to do that on Haos...?
Tried to ask on haos discord channel but complete silence

**Comment by ozett** [comment]
i have no expereiences with HAss-os, but if there is shell-access, you should be able to tweak the boot settings.
first step here: https://developers.home-assistant.io/docs/operating-system/debugging/
