### ISSUE TITLE
[Support]: Recording playlist "hour" dividers seems to show GMT hour and not local time hour

### ISSUE THREAD

**Issue by ajkrugerza** [blakeblackshear/frigate#2507]
### Describe the problem you are having

On the "Recording Playlist", recordings are grouped by day and by hour.
The "hour" divider seems to be using GMT and not local time.

See below - actual recording time in "EventCard" is correct, but the "hour" heading divider is showing GMT time (local time - 2).

![image](https://user-images.githubusercontent.com/96490833/147266537-635fc488-c518-4b7c-b892-499d279ed024.png)

### Version

0.9.4-26AE608

### Frigate config file

```yaml
Nothing in config file relating to time
```

### Relevant log output

```shell
Not applicable
```

### FFprobe output from your camera

```shell
Not applicable
```

### Frigate stats

```json
Not applicable
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wireless

### Camera make and model

n/a

### Any other information that may be helpful

The hour header divider seems to be coming from the below:

`<Link href={``/recording/${camera}/${recording.date}/${item.hour}\``} type="text">
                  {item.hour}:00
                </Link>`

The Time in EventCard seems to be coming from below:

`const start = fromUnixTime(event.start_time);`

**Comment by ajkrugerza** [comment]
Just did some more digging, it seems when I click on the recording playlsit, the wrong clips are being played. I think it has something to do with the time zones.

I've tried it in Firefox and Chrome - seems to play the GMT time clip and not the clip you click on.

**Comment by blakeblackshear** [comment]
Can you post your Docker Compose file?

**Comment by ajkrugerza** [comment]
Thanks for the great project - happy to try look into the source code if you can point me in the right direction to investigate.
Sorry about the formatting of the file below - couldn’t get it to include to not collapse the spacing.

Docker compose is below:

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true 
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb" 
    devices:
      - /dev/apex_0:/dev/apex_0 
      - /dev/dri/renderD128 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config:/config:ro
      - /ext_data/media/frigate:/media/frigate
      - type: tmpfs 
        target: /tmp/cache
        tmpfs:
          size: 1024M
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "######”

**Comment by blakeblackshear** [comment]
What is the timezone set to on your host?

**Comment by ajkrugerza** [comment]
Thanks - that was the problem.

Proxmox host timezone was correct, and didn't realise the LXC container wasn't pulling the time from there. 
Ran `dpkg-reconfigure tzdata`, restated Frigate and it's all sorted. 

Was thrown off by some of the times being correct, but I suppose that may have been javascript running on a computer with a different timezone.

Thank you!
