### ISSUE TITLE
[Support]: Timezone ignored in displayed events on Firefox

### ISSUE THREAD

**Issue by oztourer** [blakeblackshear/frigate#2513]
### Describe the problem you are having

This is not an error in Frigate but a heads-up for anyone having the same problem when using Firefox - please remove if inappropriate.

### Long story short:

Do _not_ set Firefox config variable 'privacy.resistFingerprinting' to True!

### Long story long:

I have been tearing my hair out trying to resolve an issue with Frigate where the recorded events list was showing events with UTC time instead of my local timezone (UTC+10), and where the recordings timeline would link to clips for the UTC time of the event (so in my case a clip ten hours before the expected one). I naturally assumed that there was a problem with my Frigate config or with the Frigate application.

I have been examining the Frigate Python code and the javascript of the web frontend and it gradually led me to look into the javascript function `toLocaleTimeString()`. That eventually led to a post pointing out that if you have 'hardened' Firefox privacy by setting the 'about:config' setting 'privacy.resistFingerprinting' to True, then Javascript will _always_ return times as UTC.

Resetting that config variable to its default value of False entirely fixed the problem. 

### Version

0.10.0-db1255a

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

```json
Not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Any

### Any other information that may be helpful

This post will apply to any version of Frigate.

**Comment by ajkrugerza** [comment]
Hi

I'm having a similar problem, but my privacy.ResistFingerprinting is set to false - still showing problems with the GMT time v local time zone.

I've logged a separate issue.
