### ISSUE TITLE
Add an indicator of when there's motion when viewing recordings

### ISSUE THREAD

**Issue by BBaoVanC** [blakeblackshear/frigate#2525]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to record 24/7 on my cameras while being able to quickly skim through parts when there's motion, even if an object wasn't detected. 

**Describe the solution you'd like**
I think there should be some sort of indicator (maybe a color) on the timeline of the video player that marks the times where there's motion. 

**Describe alternatives you've considered**
Motion events could also be listed on the sidebar when in full screen, although I think an indicator on the timeline would be better for just motion without objects.

**Comment by NickM-27** [comment]
Closing, this has been implemented in the new UI https://github.com/blakeblackshear/frigate/pull/10235
