### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by jakeharvey205** [blakeblackshear/frigate#2534]
### Describe the problem you are having

Is there a way I Can have all Frigate  Files (Recordings/Clips/Photos) save to a usb storage device that’s plugged into an Odroid N2+ running Home Assistant? And if so how? 

### Version

0.9.4-26AE608

### Frigate config file

```yaml
N/a
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink

**Comment by blakeblackshear** [comment]
https://docs.frigate.video/installation#home-assistant-operating-system-hassos
