### ISSUE TITLE
API Endpoint to trigger snapshot creation

### ISSUE THREAD

**Issue by rufinus** [blakeblackshear/frigate#2535]
**Describe what you are trying to accomplish and why in non technical terms**
I want an API endpoint to trigger the creation of a snapshot image. So the HA Integration can have a Service with which this endpoint can be triggered in for example an automation.
(Use Cases:
 - Each day at 1pm take a snapshot from the garden cam
 - If my doorbell is triggered take a snapshot from frontdoor camera
 - If motion sensor in garden triggers take a snapshot (yes i know - this use case already works with the motion detection from the camera itself - this would also allow it from other presence detection sensors)
 )

**Describe the solution you'd like**
A [POST] API endpoint to trigger the creation. The main work will be in https://github.com/blakeblackshear/frigate-hass-integration/ as the integration should have a service to call from inside HA.

**Comment by LordNex** [comment]
This can already be done with the built in HA API and service calls. You could also base it upon webhooks and track those events in an automation and trigger it that way.

**Comment by raintonr** [comment]
> This can already be done with the built in HA API and service calls.

What mechanism does that use? Interested as I don't use HA so would like to make direct API call to Frigate.

I'd like to trigger a recording event from camera with it's own motion detection/AI, thus saving Frigate resource usage but consolidating events & recordings in one place.

**Comment by raintonr** [comment]
Duplicate of #1063?
