### ISSUE TITLE
[Support]: Any way to detect the distance of a person?

### ISSUE THREAD

**Issue by tjcampanella** [blakeblackshear/frigate#2538]
### Describe the problem you are having

I am not sure if you can do this with frigate, but I am wonder if there is anyway to detect how far a person is from the camera. 

### Version

latest

### Frigate config file

```yaml
Not applicable.
```

### Relevant log output

```shell
Not applicable.
```

### FFprobe output from your camera

```shell
Not applicable.
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Lorex

**Comment by ozett** [comment]
that would need some calculations about the detected box size and the general image size of the cam,
maybe some measurement for reference size of some known objects.

looks like a good idea, but think its not build into the actual version of frigate

**Comment by NickM-27** [comment]
Yeah definitely something that with some knowledge of your camera could be built into a script relatively easily, but I think that is outside the scope of frigate itself

**Comment by tjcampanella** [comment]
I wonder if anything exists for this already for home assistant. Not sure how I'd integrate this using a custom script. Unless there is a way to do it from scripts in home assistant. I would think you'd need Python to do it.

**Comment by NickM-27** [comment]
@tjcampanella how are you looking to automate this?

**Comment by tjcampanella** [comment]
I can write a Python script for this probably but I'm not sure how that would integrate with frigate so I guess a home assistant automation or script would be ideal

**Comment by NickM-27** [comment]
@tjcampanella Sorry, what I mean is how are you looking to use the `distance` data in home assistant. Like only notify if person is closer than 10 ft from the door?

**Comment by tjcampanella** [comment]
Yeah doing something like that is what I'm after.

**Comment by NickM-27** [comment]
Yeah, I mean all it would take is some analysis on your part of the image to figure out how many pixels high some objects are based on distance (manually). And then once you have the pixel to feet factor, on each event just grab the height of the bounding box and apply those factors. I agree though, seems a bit complicated to do in HASS especially since I think you need to interface with the API to get bounding box info. Certainly could be done in a python script (not sure if HASS has a way to run those)

**Comment by tjcampanella** [comment]
I just found this on hacs. https://github.com/custom-components/pyscript
