### ISSUE TITLE
Latest image not drawing bounding boxes

### ISSUE THREAD

**Issue by yayitazale** [blakeblackshear/frigate#254]
Even with _draw_bounding_boxes: True_ defined for the camera, the image _/<camera_name>/latest.jpg_ is not drawing the bounding boxes for detected object since update to 0.7.0-amd64. I can see the boxes on the debug stream and also on the _/<camera_name>/<object_name>/best.jpg_ but not in the latest.jpg

This was so usefull for me since I configured the rstp camera stream on hass with the _/<camera_name>/latest.jpg_ as still_image_url, so I could see in "real time" on lovelace if there was any detection with the bounding boxes drawn and the lovelace card opened the rstp stream when I did click on the image. As long as I'm tracking 2 types of objects (Person and Cat) the _/<camera_name>/<object_name>/best.jpg_ is not very handly because I have to create 2 camera entitys and pictures for every 1 true camera stream.

Thanks

**Comment by blakeblackshear** [comment]
I will be overhauling the drawing for the next release and will include this endpoint.

**Comment by tubalainen** [comment]
In this release only the MQTT snapshots have bounding boxes if enabled.
Ref: https://github.com/blakeblackshear/frigate/issues/240
