### ISSUE TITLE
Make zone event trigger only when person is entirely in it

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#2545]
### **Describe what you are trying to accomplish and why in non technical terms**
I have a zone called `doorbell` as follows:

![image](https://user-images.githubusercontent.com/29582865/147805675-ccb25314-9a1e-40a3-a0f6-df5cf1d0b9fb.png)

I use this zone to predict when someone is about to ring my bell, and to turn on my camera in my tablet in the kitchen beforehand.

However, very often I receive events when someone was partially on that zone, like:

![image](https://user-images.githubusercontent.com/29582865/147805808-196d5def-cbe8-4a63-a8d4-a5cc1bc9195d.png)

(and I have other countless occurrences of such)

### **Describe the solution you'd like**
A way to specify that I only want the object to be considered in the zone if entirely on it, like:

```diff
# frigate.yml

cameras:
 street:
    zones:
      doorbell:
        coordinates: 458,96,454,211,348,231,348,111
        objects:
-         - person
+        - object: person
+           mode: entire # default would be partial, as today
+        - dog # list elements could still be defined as plain strings to retain compatibility (they would have `mode: partial` by default
```

But this implementation details are just suggestions...

### **Describe alternatives you've considered**
I could move the zone a bit higher, to prevent more false negatives, but there are many drawbacks in doing this:

- what about kids? I could probably miss then
- what if someone appears closer in my camera, it would still trigger the partial presence in the doorbell zone

### **Additional context**
None.

**Comment by blakeblackshear** [comment]
Presence in a zone is based only on the bottom center of the bounding box. No other part of the bounding box matters at all. Your zone should outline where people are standing, not where the bounding box will be. If don't think anyone will be standing on your wall.

**Comment by felipecrs** [comment]
That's really good to know. So, I guess, my zone should be like:

![image](https://user-images.githubusercontent.com/29582865/147831884-649dc7d1-88e8-45af-9c74-106cf8ac9c51.png)

Right?

**Comment by blakeblackshear** [comment]
Yes. If that zone is obstructed by a parked car, or if the person is partially visible, the bounding box will only be on the top half of the person. That probably explains why the person walking behind the car entered the zone.

**Comment by felipecrs** [comment]
Hm, makes sense, thank you. I guess the way to "solve" this would be to somehow make Frigate only trigger an event when someone is standing (on their feet) on a zone. Basically, Frigate would have to detect not only the person but also their feet. Which I suppose is not feasible...

I guess my only solution would be to place a camera in another position which would not suffer of such an "interference".

Anyway, I'm still evaluating the new zone configuration. Perhaps it will help to reduce the false positives.

**Comment by felipecrs** [comment]
By the way, I'm still receiving a lot of false positives, but I suppose the only solution is to use the camera in another position.
