### ISSUE TITLE
Create a "Latest" Tag for automatic updates

### ISSUE THREAD

**Issue by yayitazale** [blakeblackshear/frigate#256]
I'm creating a [template](https://github.com/yayitazale/unraid-templates/blob/main/yayitazale/frigate.XML) to this project for UnRaid users. I'm actually using it over an unraid machine at is pretty stable. It would be possible to create a "latest" tag refering always to the latest stable release to make a easier integration and automate the updates?

Thanks

**Comment by invinciberry** [comment]
I also just realized both the latest and stable tag is missing. Also been running the image on an Unraid box for the past 6 months now with no issue.

**Comment by blakeblackshear** [comment]
I will add a stable tag back, but it will need to be architecture specific now that there are builds for several architectures available.

**Comment by blakeblackshear** [comment]
`stable-amd64` is now available.

**Comment by yayitazale** [comment]
Hi, can you update the stable-amd64 tag to 8.1.0?

I'm using this tag to the Unraid template.

Thanks.
