### ISSUE TITLE
Recordings View slow to load

### ISSUE THREAD

**Issue by nopjmp** [blakeblackshear/frigate#2560]
I'm running Frigate with 4 cameras with 24/7 recording as well as having clips.

90 day recordings
14 day event retention

~655400 database entries for each camera found by using the following SQL

`SELECT count(*), camera FROM recordings GROUP BY camera`

I was able to improve the initial performance from camera recordings HTTP endpoint by adding a SQL index.

3 secs -> 895ms in my case.
```
CREATE INDEX "recordings_camera_start_time_asc" ON "recordings" (
	"camera",
	"start_time"	ASC
)
```

However, this still takes 30 seconds on the `/api/[camera]/recordings` endpoint.

I believe the issue is the usage of the strptime and lesser so the usage of strftime.
https://github.com/blakeblackshear/frigate/blob/bb68a2405b32bb821c69dbe2d9bd256083c99bc1/frigate/http.py#L459-L487

I've not looked into it further as I was just made aware of this today by my partner when they were trying to look the recordings. I'll be looking into it later as I've told them 30 seconds is expected right now.

My initial thoughts are to use arithmetic to calculate the diff instead or to implement some kind of pagination.

**Comment by blakeblackshear** [comment]
That endpoint is known to be slow. There is room for improvement, but I haven't had time to look into it yet.

**Comment by skaa** [comment]
On my database with ~182000 recordings for single camera, the `/api/<camera_name>/recordings` HTTP query takes ~15 seconds. Is it possible to speed up page loading? SQL queries from method `def recordings(camera_name):` takes 2-3 seconds, so I think it's about processing the data in the code. [Here](https://stackoverflow.com/questions/13468126/a-faster-strptime) is the example of time format functions optimization.

**Comment by blakeblackshear** [comment]
It's already on my list of things to improve for the next release.

**Comment by nopjmp** [comment]
Thanks I've worked around this by recording motion only since that is now an option and the performance appears to be better.

**Comment by mitchell-pioneer** [comment]
Has there been any improvement on this?  Would clearing the cache help?   Im running this on a very fast machine and it still takes 15-20 seconds to start playing.
