### ISSUE TITLE
[Feature]: File/FTP video file import/processing

### ISSUE THREAD

**Issue by raintonr** [blakeblackshear/frigate#2584]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to configure import of video files from FTP server and/or just import direct from filesystem if mapped on the same host which is running an FTP server ... so that I can import video files uploaded by 'dumb' camera motion detection, discard false positives and integrate the real detection into existing Frigate interface.

**Describe the solution you'd like**
- Ability to configure folder (via Docker mapping) and/or FTP server import location (or multiple locations). Ideally one location/folder per camera
- Ability to configure import locations with exact same options as existing cameras.
- Any video files that appear in import location are read and processed as if they were a live stream, with the caveat that:
  - Motion is assumed for these imports.
  - Timestamp is as per the file create/modify date rather than RTC of the executing host
- Import/processing should only be performed when load on executing host is low.

**Describe alternatives you've considered**
These files are assumed to have been created by a 'dumb' IP camera when it saw motion and uploaded to an FTP server. Sure, one could just process such cameras directly but the ability to process their output files would greatly reduce load on the Frigate container:
- No need to constantly monitor and decode the stream with FFMPEG.
- Processing when container CPU load is low would likely provide 'near real time' detection but without nasty CPU spikes.

**Additional context**
So many IP cameras can perform 'dumb' motion detection and upload files via FTP seems inefficient to constantly stream and decode their feed if at all possible

**Comment by raintonr** [comment]
Actually... having seen #1063 think that might be a better solution.

For example, HikVision Accusense cameras have both dumb motion detection and AI object detection (limited to cars & people at this time, but still pretty useful). 3rd party integration can easily be created to capture a trigger from the camera of either type of detection. If that integration could then call Frigate to start recording, start analysis or even trigger a specific event (detection of target 'person' for example) that would be great. Hopefully #1063 will provide this.

**Comment by blakeblackshear** [comment]
Note that frigate uses motion detection to determine where to run object detection in the frame. It's not simply a running object detection on the entire frame when motion is detected. For this reason, relying on external motion detection is not sufficient. It's not possible to "assume" there was motion.

**Comment by raintonr** [comment]
> ...relying on external motion detection is not sufficient.

OK.

However, I guess if we could use camera detection to turn Frigate detection on/off (via an API - pretty sure I saw another feature request for that?) it would be a small step to lower Frigate resource usage. Every little helps and all that, and if the camera does it for free why not?

**Comment by raintonr** [comment]
Still relevant. But #1063 would help somewhat.

**Comment by NickStallman** [comment]
This would make Frigate much more useful for "less flexible" aka "smarter" cameras. E.g. my use case is with Eufy cameras which handle their own motion detection, to make the Eufy system somewhat sensitive, flick the motion detected clips to Frigate for both storage and further filtering (e.g. double-shot, home assistant, etc....)

Currently cameras like Eufy can't be used at all with Frigate, and it could be quite an efficient setup since Frigate wouldn't need to handle the 24/7 motion detection. Instead it could just be fed clips and run the normal video pipeline on it (including a 2nd round of motion detection).
