### ISSUE TITLE
[Feature]: Better debug/logging/notification from ffmpeg - specifically around hardware acceleration

### ISSUE THREAD

**Issue by raintonr** [blakeblackshear/frigate#2587]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to view detailed logging/debug output from `ffmpeg` processes so that I can properly determine if hardware acceleration is working or not, and if not, why.

**Describe the solution you'd like**
Option in the configuration file and/or UI to enable more debug and/or better logging output from `ffmpeg` processes. Ideally, a large warning should be present on the UI for cameras that are configured to use hardware acceleration but aren't actually doing that. 

**Describe alternatives you've considered**
Running manually from a system shell command line is an option, but... this is problematic as it does not use the same executables and libraries as the docker container (erm... I think, yes?). I guess one could execute `ffmpeg` commands in the actual container to debug, but the point is neither of these are very beginner or even user friendly.

**Additional context**
Looking through issues here note that numerous problems around hardware acceleration. It seems problematic so ability to see exactly what is going on and the `ffmpeg` process output would be really helpful.

For example, I'm trying to get hardware acceleration working on an Intel N4200 based system. Adding the recommended settings (see https://docs.frigate.video/configuration/hardware_acceleration) did nothing (verified with `intel_gpu_top`). One huge problem is that ffmpeg just silently ignores various hardware acceleration issues and continues in software. Eventually I tried decoding the input stream from a command line and discovered this output:

```
[h264 @ 0x5572d4389900] Format vaapi_vld chosen by get_format().
[h264 @ 0x5572d4389900] Format vaapi_vld requires hwaccel initialisation.
[h264 @ 0x5572d4389900] Codec h264 profile 66 not supported for hardware decode.
[h264 @ 0x5572d4389900] Failed setup for format vaapi_vld: hwaccel initialisation returned error.
[h264 @ 0x5572d4389900] Format vaapi_vld not usable, retrying get_format() without it.
```

This appears to show that the N4200 CPU is not capable of decoding the h264 input stream (FYI this stream came from a HikVision DS-KD8003-IME1 intercom camera).

So this seems to be a compatibility issue, but... took me quite some time to discover this and doubt new users would have the patience.

Hence the request for better logging and/or debug.

**Comment by NickM-27** [comment]
One thing is now that we are using ffmpeg 5.0+, if hwaccel is requested but not used it will crash immediately. Make knowing that something is wrong easier at least.
