### ISSUE TITLE
LXC container support

### ISSUE THREAD

**Issue by OptimusGREEN** [blakeblackshear/frigate#259]
Any chance of proxmox support? I was going to try and build a lxc container by looking at the docker files but it looks so complicated now that its been split up.

Maybe even a script or something?

**Comment by blakeblackshear** [comment]
Take a look at some of the posts on the homeassistant forums here: https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/2189

Several people are running in proxmox with lxc I believe.

**Comment by OptimusGREEN** [comment]
Yeah I asked in there before too but no joy unfortunately.

**Comment by blakeblackshear** [comment]
And you saw the recent discussion? https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/2126?u=blakeblackshear

Looks like both of them are running lxc containers.

**Comment by OptimusGREEN** [comment]
Yeah I've seen those post too. 

I've created a new more detailed issue in hope #264 so will close this here. 

thanks again.
