### ISSUE TITLE
Multi-Arch, single Docker image

### ISSUE THREAD

**Issue by maxirus** [blakeblackshear/frigate#2592]
**Describe what you are trying to accomplish and why in non technical terms**
I want a single Docker image (tag) that will work on arm, arm64, and amd64 architectures.

**Describe the solution you'd like**
Use native Docker build features, like buildx, to build a proper multi-arch image. See blog post [here](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

**Describe alternatives you've considered**
Pull the the architecture tagged version of the Docker image. However, this has the following limitations:
- User must know the specific cpu architecture for the node the container will land on
- User must lookup the proper tag to use
- Will not allow for K8s deployments in a mixed architecture environment
- Harder to manage updates

**Additional context**
Will help resolve [Helm Chart issue](https://github.com/blakeblackshear/blakeshome-charts/issues/24)

**Comment by NickM-27** [comment]
0.11 is fully released and built with multi arch 👍
