### ISSUE TITLE
leave recordings link visible when recording is disabled

### ISSUE THREAD

**Issue by rpatel3001** [blakeblackshear/frigate#2610]
**Describe what you are trying to accomplish and why in non technical terms**
I have an automation that toggles the recording setting but I want to be able to view recordings when it's disabled.

**Describe the solution you'd like**
I'd like the link tot he recordings page to remain visible even when recording is disabled.

**Describe alternatives you've considered**
The page is still accessible by direct URL but there's no link

**Additional context**
N/A

**Comment by NickM-27** [comment]
@blakeblackshear I think this can be closed now that the PR has made it to master.

**Comment by rpatel3001** [comment]
Thanks Nick! Works for me.

**Comment by rpatel3001** [comment]
Ah, just noticed that the cameras with recording disabled do not show up on the side bar when on a recordings page: 
![image](https://user-images.githubusercontent.com/6333479/154855002-36c9d46e-1844-4f0a-9405-330789ef7643.png)

There should be a link to the "Bedroom" camera on the left.

**Comment by NickM-27** [comment]
This is now fully done in 0.11
