### ISSUE TITLE
Installing Coral drivers on Home Assistant OS

### ISSUE THREAD

**Issue by cegit55** [blakeblackshear/frigate#2613]
### Describe the problem you are having

When Home Assistant OS 6 was released they said they enabled the drivers needed to run the Google Coral Mini PCIe Accelerator or M.2 Accelerator on all boards supporting PCIe.

Is this correct? ie has anyone managed to get their Mini PCIe / M.2 Accelerator to work under HA OS 6 or later, *without* having to install the drivers separately?

### Version

OS 7

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Mixed

### Camera make and model

n/a

**Comment by Sku1ly** [comment]
Yeh no issues here pretty much plug and play with my A+E key and M.2 adapter.
OS 7.0 at the moment.

**Comment by cegit55** [comment]
Great to hear @Sku1ly - thanks!

**Comment by apaneiro** [comment]
What about on the newly supported Odroid M1? It does not recognize the device in the M.2 slot
