### ISSUE TITLE
Collapsible left menu / navigation bar

### ISSUE THREAD

**Issue by lolouk44** [blakeblackshear/frigate#2617]
**Describe what you are trying to accomplish and why in non technical terms**
Would it be possible to have a collapsible menu / navigation bar and have its status stored so it survives a restart... 

**Describe the solution you'd like**
Similar to Home Assistant / VSCode Editor, the menu could collapse to only display menu icons instead of fulll text. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by NickM-27** [comment]
The UI has been rewritten for the next version of frigate and as part of that the navigation bar is icons only
