### ISSUE TITLE
Add more possibilities for crop option

### ISSUE THREAD

**Issue by TheSleepySlee** [blakeblackshear/frigate#262]
**Describe the enhancement**
Discussed here: https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/2207
Goal would be to allow more options for cropped snapshots like choose bounding box image only.
Passing a string instead of 1/0. Maybe region/object/none as the initial options.

**Comment by blakeblackshear** [comment]
Decided to update crop to include the object with a 10% buffer around the bounding box.
