### ISSUE TITLE
[Support]: How to disable Objects like cars from being detected during certain times in the day?

### ISSUE THREAD

**Issue by Sarelseekat** [blakeblackshear/frigate#2625]
### Describe the problem you are having

Some of my cams look over a busy intersection and I would like to disable cars from being detected during certain happy hours of the day. Is there a way to disable a specific object from being detected during a set time each day? Maybe there is a completely different way to achieve the same? Basically, I want to save system resources during these times as well as save drive space from tons of footage of other peoples cars ;)

### Version

2.3 Full Access

### Frigate config file

```yaml
Not relavent
```

### Relevant log output

```shell
Not relavent
```

### FFprobe output from your camera

```shell
No Sure how to prove cam.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

**Comment by blakeblackshear** [comment]
There isn't a way to dynamically change zones or other settings based on time of day. You could use an automation to disable recordings entirely during that time.

**Comment by Sarelseekat** [comment]
Thanks Blake - Appreciate the feedback
