### ISSUE TITLE
Hi-res vs Low-res feeds?

### ISSUE THREAD

**Issue by jasonmadigan** [blakeblackshear/frigate#263]
**Describe the bug**
Not a bug, more a question - what kinds of camera feeds are recommended? I know the SSD models tend to be trained on low-res images, so I've been using the 480p feeds from cameras for most automation, but am tuning things to get a balance between a low-rate of false positives and good detection of objects that are quite far away (e.g. one camera I have is quite a ways away from a house, but would like for it to still detect persons).

**Comment by blakeblackshear** [comment]
Sounds like I really need some clarifications in the docs. Here is my response on a similar issue: https://github.com/blakeblackshear/frigate/issues/247#issuecomment-711051458

**Comment by jasonmadigan** [comment]
I think that'd help. Like the poster of that issue, I had different take!
