### ISSUE TITLE
Set default speed for the clip video viewer

### ISSUE THREAD

**Issue by MisterTdog** [blakeblackshear/frigate#2644]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to configure the default speed on the clip viewer so that I don't have to increase it, everytime I watch a clip.

**Describe the solution you'd like**
A settings, in the config file, to set the default speed factor for the clip media player: x0.5/x2/x4/.... 

**Additional context**
Everytime I watch a clip, I click on x8 or x4. It's quite annoying having to increase the speed everytime...

**Comment by Spectre5** [comment]
I'd also love this feature for the same reason - I always want to watch the clip at 8x speed (ideal default) and then manually go slower in the rare case I want that.

**Comment by NickM-27** [comment]
this is implemented in the new UI (0.14)
