### ISSUE TITLE
Record main stream and substream

### ISSUE THREAD

**Issue by ceandraka** [blakeblackshear/frigate#2652]
It would be nice if recording could occur on two streams at once. My system has a low res substream (under 480 lines) that can be used for detection, and is also more than suitable for phone checks. The high res stream (main) is a 4k stream, and is great for archival recording or police reports. However, if I set the 4k stream to record, my Android devices cannot play i in the browser (Samsung Internet, Chrome, Opera, Firefox) nor in the HA App. I can download it and it play sin VLC or MXPlayer. Even if it did play, 4k is overkill on the phone.

My current camera setup will not allow me to reduce the main stream to 1080, which may help solve the non-viewable issue.

However, it would be "best" to have an archival record of "clips" in 4k, but be able to select the secondary stream clips for remote review, saving data bandwidth.

A solution form a user perspective would be to record clips in multiple streams, and then be able to select in the app which stream to view. In notifications I can send the link to the correct (Low res) stream.

I have tried changing camera resolutions, but I am using my old NVR as a switch with POE, and the NVR is preventing me form changing resolutions.  And such a  solution (record 1080i) would still use more bandwidth than necessary for a phone.

Thanks!

**Comment by NickM-27** [comment]
If I had to guess I'd say not being able to play has nothing to do with the resolution and likely due to the compression that is being used,. For example this [note in the docs](https://docs.frigate.video/configuration/record) about H.265: **H265 recordings can be viewed in Edge and Safari only. All other browsers require recordings to be encoded with H264.**

**Comment by ceandraka** [comment]
> If I had to guess I'd say not being able to play has nothing to do with the resolution and likely due to the compression that is being used,. For example this [note in the docs](https://docs.frigate.video/configuration/record) about H.265: **H265 recordings can be viewed in Edge and Safari only. All other browsers require recordings to be encoded with H264.**

Thanks for commenting. I suppose this is possible, even though VLC reports H264 AVC. However, this may be just wrapper information that frigate puts on a stream that is really h265? I will see if I can see anything in the camera settings that may shed light. I thought the cameras were 4k, but they are 4MP, 2688x1520. The stream does play in Chrome on the PC.

Nonetheless, regardless of my display issues, it would make sense to store both streams and allow low res stream viewing on mobile devices, high res for archival or viewing on a PC.

**Comment by ceandraka** [comment]
The camera has the same settings for main and substream, for the most part. The only encoding option is h264. The main stream has an additional option of h264+, but that is off. Main stream is set to max bitrate 5120kbps, while substream is 512kbps. Resolution selected is 640x360 substream, main is 2688x1520. Otherwise the same. Not seeing h265 as an option.

**Comment by ceandraka** [comment]
I did manage to reset one camera. Tried different resolutions. 1080p displays on mobile, anything higher does not. No other camera settings changed between tries.

But, still would like to see two streams record.

**Comment by ceandraka** [comment]
As an alternative to recording both streams, how about an option to pass the playback of a clip through ffmpeg and allow re-encoding with all ffmpeg options? This way the notification could have a link to the raw (4MP) clip, and another link that passes through ffmpeg, and re-encodes on the fly to a lower resolution. This would use a little CPU to encode, but only when a low-res replay is selected.

Maybe there is already a way to do this with creative link?

**Comment by blakeblackshear** [comment]
This may make sense for those that don't have a low res stream to record, but for most people it will be much better to just save a secondary stream. Constantly re-encoding will require more CPU than most would want.

**Comment by ceandraka** [comment]
I did not intend constant re-encoding. Rather, save the stream (high res as is done now), and re-encode on the fly when a clip is requested for review. Typically 30 second clip. Sorry if I was not clear. So just the API call to assemble a clip for review, either through a notification or by clicking on the event in Frigate view.

**Comment by blakeblackshear** [comment]
That isn't possible today, but could be one day.

**Comment by ceandraka** [comment]
OK, thanks for taking a look

**Comment by ghgeiger** [comment]
Following this request as I would like to be able to record both hi & low res streams with frigate. Specifically, I'd like frigate to be able to continue to function as it currently does, but I would also like it to archive unprocessed high res streams on any motion event, so that I could go back and get a better look at my scene. In my case, I wouldn't even care if the recordings were not available via UI, I'd just like to be able to retrieve them from the drive if I need them... Or perhaps just a 'Download' button for the high res recording.

**Comment by spacebares** [comment]
Or what about record streams with tags? Highres / Lowres.
```
- path: rtsp://highreslink
  tag: highres
  roles:
    - record
- path: rtsp://lowreslink
  tag: lowres
  roles:
    - record
```

and the events browser will have a dropdown box or buttons that allows you to show recordings from a tag? Would be great for mobile, and you still have highres if your willing to wait for the load.

![aewfrsh](https://user-images.githubusercontent.com/57186372/201863871-8225bef2-69ab-416e-b2d1-60cd0ae096ea.png)

would be awesome to have

**Comment by NickM-27** [comment]
the next version of frigate (0.14) supports previews which are a low fps low resolution video that is easily scrubbable and likely solves this issue for most use cases

**Comment by tearfulnumpty** [comment]
I'm not sure this covers the same use base. The previews aren't exportable, and don't contain audio. I was hoping to utilize a recording of a substream for a script I was writing, but it looks like I'll have to setup a second camera within Frigate for it, and that doesn't seem like a good solution. I think substreams should be recordable with a second set of record retention parameters, and I don't see how the previews are really covering this use case. Previews are great, but they seem quite distinct to me.

Personally I'd love to see this re-opened.

**Comment by NickM-27** [comment]
> The previews aren't exportable

they are in 0.15

in general they cover the original request which was an easy and efficient way to check what happened on the phone when bandwidth is low. Previews fill this use case by making it easy to see what happened on the camera in bandwidth constrained environments

**Comment by tearfulnumpty** [comment]
Ok, I'll open a new issue, unless you're saying that you're not open to the idea. Previews don't give me audio and they are substantially lower fidelity than the raw substream, so they don't serve as a 1:1 replacement for the script I was writing.
