### ISSUE TITLE
TPU USB accelerator

### ISSUE THREAD

**Issue by gabeale** [blakeblackshear/frigate#2668]
Dear fellows, first of all many compliments for Frigate Project that is very cool.

**I was wondering if it would be possible to use a different Tensorflow accelerator hardware because the indicated ones from Google Coral are not available on the market and they won't be before January 2023 (one year from now)!**

**This is an issue for many users like me because they cannot go further with Frigate (only option is to use CPU that is not recommended).**

Being Tensorflow open source, in principle it should be able to run on hardware of different manufacturers. For instance browsing the Tensorflow website i understood that any TPU and GPU can be used.

What is your point of view?

Thanks in advance for the reply you'll give me.
Ciao! :-)

**Comment by blakeblackshear** [comment]
I haven't seen any other AI accelerators that support tensorflow lite directly. They all require their own Sdk and model conversion.

**Comment by gabeale** [comment]
Thanks Blake for prompt reply. 
Have you an idea where purchase the Coral Accelerator? In EU, all the stores don't have it in stock.

**Comment by suth** [comment]
Not in the EU but I found them available on ebay, albeit at a large markup. Resisted paying that much for awhile but now that I have one I wish I had given in sooner.

**Comment by alfwro13** [comment]
They are available from [Kamami store ](https://kamami.pl/en/coral/575395-coral-usb-accelerator-a-module-with-the-coprocessor-google-edge-tpu.html )for about 100Euro.
I bought mine from Germany few weeks ago for about 70Euros from this company: [Berrybase](https://www.berrybase.de/raspberry-pi/raspberry-pi-computer/usb-geraete/google-coral-usb-accelerator-f-252-r-raspberry-pi)

**Comment by Re4DeR** [comment]
Kamami store doesnt have any. they sent me mail "Coral USB Accelerator is out of stock."

**Comment by vakilando** [comment]
Yes, I ordered there and they sent me a mail that the coral will be in stock again in april.
I did not cancel my order......hopefully

**Comment by ve6rah** [comment]
The complete inability to purchase a coral tpu anywhere is a real barrier to frigate adoption. I've been searching for months to try to find one, I've asked every site to notify me when they get any, and nothing.
I refuse to pay $500 for a product advertised as 1/10th of that.

My cpu detector just isn't going to be able to handle my 4 camera setup. Realistically with stock estimates on most sites showing over a year delay to get one, coupled with Google's propensity for discontinuing products at random, trying yourself to only this one, impossible to get, option really limits the project.

I will shortly be forced to go with a competing project, that may not work quite as well, but doesn't require hardware that is unobtainable.

**Comment by jmorris644** [comment]
We have Frigate working on the Jetson Nano.

https://github.com/blakeblackshear/frigate/discussions/2752

**Comment by blakeblackshear** [comment]
Jetson Nano devices are also unobtainable for reasonable prices. GPUs are expensive right now. Even an overpriced Coral is comparable to either of these options. The only reasonable alternative would be the Intel compute stick, and I haven't had the time to look at integrating it yet.

**Comment by jmorris644** [comment]
My apologies, I had not recently looked. You are tight, they are going for close to 4x.

**Comment by ve6rah** [comment]
Looks like a Jetson nano dev kit is about half the price of a coral, and is a full computer rather than just the TPU, still, I'd rather just a tpu to use with my existing setup.

An Intel compute sick is about 1/4 the price of a coral.

The coral may be best, but at $500 it's certainly not cheap! The advertising that says it's $25 makes the mark-up painful!

**Comment by blakeblackshear** [comment]
If you can find a Jetson Nano 4gb for less than $200 please send me a link. I have been looking for weeks. Everything is out of stock.

It's going to be months before the Intel compute stick could be integrated even if it was a priority.

**Comment by ve6rah** [comment]
$200 is less than half the cost of any coral I can find.

**Comment by blakeblackshear** [comment]
You can't find a jetson for less than $400-500 either. I see several listings for a Coral USB on ebay for less than that. I get that they are hard to come by, but so are most of the alternatives.

**Comment by ve6rah** [comment]
[Google Coral](https://www.aliexpress.com/item/10000303451874.html?_randl_currency=CAD&_randl_shipto=CA&src=google&aff_fcid=86c540d64e0a4fb28a617f9f91559fde-1644180543725-07109-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=86c540d64e0a4fb28a617f9f91559fde-1644180543725-07109-UneMJZVf&terminal_id=bd1f510c75fa4489b3c8755000afc0c4) $455
[Jetson Nano](https://www.renhotecic.com/Jetson-Nano-Developer-Embedded-Development-Board-A57-Artificial-Intelligence-AI-Development-Platform-0041495) $300
[Intel Compute Stick](https://www.newegg.ca/p/17Z-0099-00045?item=17Z-0099-00045&nm_mc=knc-googleadwordsca&cm_mmc=knc-googleadwordsca-_-add-on%20cards-_-intel-_-17Z009900045&source=region) $95

Best prices I can find for each.

**Comment by katsaplias** [comment]
+1 for NCS2

**Comment by stixpunk** [comment]
what about donation campaign for prioritizing intel ncs2 integration? after lot of searching, there is many people interested and ncs2 is only one available hardware on market for long term

**Comment by LaurenceGough** [comment]
There are some sites in the UK now where you can backorder the Coral USB accelerator - a few months away, one of them even advertises a 22 day lead time but I suspect it will be a few months too.

I'm sure other countries will also be getting stock soon.

**Comment by x9prototype** [comment]
I believe this could be a starting point for Tensorflow on NCS2 https://www.intel.com/content/www/us/en/support/articles/000055228/boards-and-kits.html

**Comment by gabeale** [comment]
Thanks x9prototype. I also believe that it is required to develop Tensorflow on different hardware than Coral USB. This is because, in general, is not advisable to be bounded on a single Manufacturer: for instance the availability problem we are facing with Coral is the proof. As somebody has suggested, I propose the crowdfunding for this project.

**Comment by bugsysiegals** [comment]
While the supply chain is disrupted, is it possible to leverage Nvidia GPUs for acceleration?

**Comment by NickM-27** [comment]
> While the supply chain is disrupted, is it possible to leverage Nvidia GPUs for acceleration?

Check out #2548

**Comment by gabeale** [comment]
As far as I'm concerned, Nvidia Jetson nano is nowadays more expensive than Coral!

**Comment by NickM-27** [comment]
> As far as I'm concerned, Nvidia Jetson nano is nowadays more expensive than Coral!

Sure, seems most products in that category are, but that PR also adds general support for Nvidia models and at least one user has it working with an nvidia GPU

**Comment by ve6rah** [comment]
Certainly still a big issue. I even bit the bullet and paid the ridiculous price for a coral, over a month later the seller admitted they didn't actually have any even at that price, and I got my money back. You simply cannot get a coral for any price at this point.

**Comment by victorhooi** [comment]
I was able to order a Intel Neural Compute Stick 2 (NCS2) which arrived in a few days - this appears to be an alternative to the Coral USB stick, and is more available.

I don't believe Frigate supports the NCS2 currently - there's a discussion about it here:

https://github.com/blakeblackshear/frigate/discussions/2918

From some naive Google searching, it seems the NCS2 is supported by the OpenVINO library, which does have some kind of tflite import support:

* https://docs.openvino.ai/latest/omz_tools_accuracy_checker_tf_lite_launcher.html
* https://discuss.tensorflow.org/t/convert-tflite-model-maker-object-detection-model-to-openvino/2057/2

What do people think?

Also, Deepstack already does support the Intel NCS2 already =), which helps there as well, I guess if people want to use the Frigate/Deepstack integration, right?

**Comment by kusold** [comment]
> Also, Deepstack already does support the Intel NCS2 already

I might be wandering into the offtopic zone, but Deepstack's NCS2 support [seems to be limited exclusively to rPis](https://github.com/johnolafenwa/DeepStack/issues/100). There doesn't seem to be a way to run it on amd64.

**Comment by ve6rah** [comment]
No change. There are still no available coral devices to purchase, nor will this project accept any alternatives.

**Comment by NickM-27** [comment]
> nor will this project accept any alternatives.

It's quite a bit of work to support another accelerator, it's not a simple switch to get it all to work and takes multiple months of work. 

[The intel NCS2 was being considered](https://github.com/blakeblackshear/frigate/discussions/2918#discussioncomment-2349734) however it was recently marked as end of life and [no longer supported by intel after 2024](https://github.com/blakeblackshear/frigate/discussions/2918#discussioncomment-2697341) so it really depends how complicated it is to support. 

Also the jetson nano is vey close to being supported: https://github.com/blakeblackshear/frigate/pull/2548

Some users have used the above to support the nvidia gpu AI accelerator as well

**Comment by ve6rah** [comment]
I didn't say it would be easy to support a different accelerator, however tying yourself to only one device, that has been out of stock everywhere for over a year with no end in sight is a near guarantee of an end to this project.
And that's not even mentioning that that single device is from a company notorious for discontinuing products.
If this project is only being maintained for existing users who managed to get one of these devices several years ago, that's one thing, however there is any intention of allowing future users to use this program, and the only way is going to be to find a device to support that actually exists.

**Comment by NickM-27** [comment]
> I didn't say it would be easy to support a different accelerator, however tying yourself to only one device, that has been out of stock everywhere for over a year with no end in sight is a near guarantee of an end to this project.
> 
> And that's not even mentioning that that single device is from a company notorious for discontinuing products.
> 
> If this project is only being maintained for existing users who managed to get one of these devices several years ago, that's one thing, however there is any intention of allowing future users to use this program, and the only way is going to be to find a device to support that actually exists.

Well for one, in that thread I linked it was shared that there is some hope as google recently contracted ASUS to manufacture more corals: https://9to5google.com/2022/05/05/google-coral-asus/

Also, I already pointed out, other options are being considered and looked into. It certainly is not the case that the project is only looking to support coral.

Putting months of effort into another TPU just to have it be discontinued and not able to be purchased is a huge waste of time and would help very few people.

**Comment by mikegleasonjr** [comment]
Nvidia GPUs support would be the most compatible way forward maybe?

**Comment by NickM-27** [comment]
> Nvidia GPUs support would be the most compatible way forward maybe?

Most likely not, there's a large number of users that run on Raspberry Pi or other arm devices which these GPUs are not available for. Also the fact that coral and similar USB TPU devices MSRP is $60 (even if not available right now) while GPUs are more expensive. 

> EDIT: what about API calls to Deepstack? it runs on GPUs already...

I believe latency would be too high to be realtime most likely, also wouldn't make sense to depend on another service when frigate is currently self contained.

**Comment by sordfish** [comment]
https://uk.rs-online.com/web/p/development-tool-accessories/2017821

**Comment by mikegleasonjr** [comment]
☝🏻  Can someone buy me one, it doesn't ship to my country 📦

**Comment by NickM-27** [comment]
In case anyone here isn't in the other thread, many users who ordered from RS components have started getting their orders in and seems there is more stock available, https://github.com/blakeblackshear/frigate/discussions/546#discussioncomment-3208043

**Comment by ve6rah** [comment]
Still no change that I know of. The project is completely dependent on a single unobtainable component.

**Comment by jean-paullizotte** [comment]
Got a Coral TPU a few weeks ago on Amazon.com for a little over 150$ before taxes.

**Comment by spacebares** [comment]
> Still no change that I know of. The project is completely dependent on a single unobtainable component.

There is hundreds of them for $100 on ebay. Mine arrived 3 days after ordering and runs fine.
