### ISSUE TITLE
Zones as primary entity

### ISSUE THREAD

**Issue by poindexter12** [blakeblackshear/frigate#2686]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use MQTT zone events as the primary entity so that I can not have multiple zones active in the payload in order to understand which zone I am dealing with.

**Describe the solution you'd like**
Based on [this](https://docs.frigate.video/integrations/mqtt#frigateevents) info, the MQTT event has one camera and many zones for both current and entered zones. I would really like to be able to have the events based on zones as the entity that triggered the event instead of camera and have the camera as the secondary information. My primary means of interacting with events is creating the same zone within multiple cameras (front yard, back yard, etc.). I don't care much for which camera it was triggered on, just want to know the zone is active.

**Describe alternatives you've considered**
Creating events based off the camera looking for the zone. The problem is I cannot tell which zone the notification is for because it's only for all of them in the array so I have to assume it's all of them (which it could be). While this is certainly possible through filtering, it creates extra complexity in the consumption of events.

**Additional context**
I am also attempting to write a similar version of the HA blueprint for notifications and wanting the zone as the base for notifications. This is how I came across this issue in the first place. So, if I want to silence notifications and such, I really want to do it per zone.

**Comment by blakeblackshear** [comment]
The events topic is not camera centric. It is object centric. There isn't a reliable way to have the same event_id across multiple cameras, so there will always only be a single camera listed for an object.

This is really a technical description of what you are trying to do:
> I want to be able to use MQTT zone events as the primary entity so that I can not have multiple zones active in the payload in order to understand which zone I am dealing with.

Are you saying you want to be notified when a zone is active regardless of the camera? You should be replace the condition that looks for camera name to look for a zone name in the list of entered_zones.

**Comment by poindexter12** [comment]
I am definitely working with that right now and it's all working as expected no issues. In order to make this work, I need to know what zone I am looking for before subscribing. I was looking for the ability to listen for events in a zone without knowing the zone beforehand. Similarly for cameras, I can just listen for events and because they are per camera, I know where it came from.

Thinking about it more abstractly now, what I am doing is creating a stitched together 2d plane made from multiple cameras. Each camera is a fixed location, a unmovable zone if you will, that creates part of my larger visual plane for my front yard. The zones are a dynamic location that I can move and change dimensions on. What I think I was hoping for was a stream of events that was only focus on the item I cared about (camera, zone, or whatever) and that's what I could subscribe to instead of need to filter and find all of this.

Again, as you pointed out, the details of what I can do now works fine. Appreciate all the work you have put into this project. It's amazing.
