### ISSUE TITLE
Video stream becomes one large smear

### ISSUE THREAD

**Issue by cjackson234** [blakeblackshear/frigate#27]
After running the latest for 24 hours, some time overnight the video became a large smear.

See here:
[Screenshot](https://www.screencast.com/t/55jVsEFg)

This happened in the previous version as well. For now i'm going to try telling it to restart every night, but it would be great if it would detect when this happens and reset itself.

Debug info: 
Hikvision RTSP stream
Unraid docker host
CPU utilization stayed below 40% all night.

**Comment by blakeblackshear** [comment]
Can you post some information about how you have the RTSP stream configured? I-frame interval, codec, etc. I haven't seen this with my Dahua cameras. It looks like at some point FFMPEG starts decoding the frames incorrectly.

**Comment by cjackson234** [comment]
[https://www.screencast.com/t/t6tzilurNW38](Screenshot)

It happened again this morning as well.

**Comment by blakeblackshear** [comment]
It looks like a lost Iframe during decoding. Does the stream ever come back? Or does the smearing stay until a restart? What is your RTSP url?

**Comment by cjackson234** [comment]
Not it stays like that until I do a restart. 

My streaming url path looks like this:

> path: /ISAPI/Streaming/channels/101/

**Comment by blakeblackshear** [comment]
Try adding `?tcp` to the end of that path

**Comment by cjackson234** [comment]
Same thing again today, I added that as you suggested. My running theory is it has something to do with it switching from day to night mode and back. Sometime later this weekend i'm going to start taking hourly snapshots and narrow down when its happening.

**Comment by blakeblackshear** [comment]
Does the smear change over time or does it stay frozen? If it freezes, my guess is that FFmpeg fails, but in a way that OpenCV is unaware. I may be able to detect it and reopen the stream in that case.

**Comment by cjackson234** [comment]
From what I can tell, it says completely frozen. It's either pinkish or grey depending on the time of day when it fails.

**Comment by blakeblackshear** [comment]
I added a watchdog for the camera stream which restarts the capture process if there are no new frames for 2 seconds. Can you try running the docker image `blakeblackshear/frigate:0.1.2-pre` that I just pushed up? You should see `last frame is more than 2 seconds old, restarting camera capture...` in the logs when it is triggered.

**Comment by cjackson234** [comment]
Docker is updated. Getting lots of "queue full. moving on" messages. So I'm not sure if i'll catch it before the log gets truncated. 

It would be great if you could send an MQTT message for "critical" alerts. That way I can use a node red flow to manage alerts based on content. 

Thanks for getting this out so quick. I'll keep you up to date

**Comment by blakeblackshear** [comment]
Really? I'm surprised you are getting so many queue full messages. I am running detection on 29 regions across 7 cameras at about 3fps without filling the queue. If you total up num_regions*fps for each camera, you shouldn't fill the queue until you get near 100.

**Comment by cjackson234** [comment]
1 camera - 3 regions at 20fps

**Comment by blakeblackshear** [comment]
I'm surprised your queue is getting full then. Either way, this may solve your issue.

**Comment by jon102034050** [comment]
I don't think I'm seeing this same issue that @cjackson234 is seeing (yet?), but fwiw, I'm seeing a TON of `queue full` messages as I'm tuning my new setup. Could be possibly due to the fact that I don't know entirely what I'm doing, but figured it might be worth mentioning.

**Comment by blakeblackshear** [comment]
You should be able to look at about 100 regions per second. If your USB bus is too slow, you could be limiting the speed of the Coral.

**Comment by jon102034050** [comment]
I don't _think_ that's the issue, I'm running it on a nuc with usb3. I'll open a separate issue as it's probably different.

**Comment by cjackson234** [comment]
So the good news is it does knows its failing. The bad news is its not restarting. 

> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
> last frame is more than 2 seconds old, restarting camera capture...
>

**Comment by blakeblackshear** [comment]
I'm probably just doing something wrong. It's a little tough since I can't reproduce it. I will take another look, add more debugging and push up a new build soon.

**Comment by cjackson234** [comment]
I have the docker set up to restart itself on failure. So if you can get it to exit docker with an error code, it should fix itself. 

I did this because when the server starts, sometimes the coral isn't ready yet. So it just retries until it is.

**Comment by blakeblackshear** [comment]
I added some additional debug logging when it trys to restart the process and adjusted the time it waits before checking again. I am wondering if it might be restarting the process before it has a chance to start back up again and grab a frame. Pull down the updated `blakeblackshear/frigate:0.1.2-pre` image and see if this does it.

**Comment by cjackson234** [comment]
So I've ran it for almost a day and it's been perfect so far. I'll keep you posted. Thank you!

**Comment by cjackson234** [comment]
Well it came back today but now its a moving smear.

Video sample: https://www.screencast.com/t/7caV7Yrib

**Comment by blakeblackshear** [comment]
Do you see messages in the logs about it restarting the capture process?

**Comment by cjackson234** [comment]
As usual, by the time I got to it all I see is

> queue full. moving on

Over and over

**Comment by drcrimzon** [comment]
I would try updating to the latest build, and removing the mask from your configuration file.  If it's the same issue I ran into with masks / queue full it should solve that flooding the log.

While the camera feed is blurred, have you tried restarting the camera?  I have one camera that blips once in a while and sends packets out of order, which results in the same issue you are seeing.

**Comment by cjackson234** [comment]
It happened before the mask was implemented as well. My camera is just fine. I use blue iris and it never has an issue.

**Comment by blakeblackshear** [comment]
It looks like it is getting enough corrupted frames that it isn't triggering the capture process to restart. OpenCV isn't noticing that the frames are corrupted, and just passing them along for detection. Not sure what to do at this point other that create a way to reopen the connection to the camera at some interval. In a future version, I will be switching to a different way of decoding the stream. Maybe that will fix it.

**Comment by steveneighbour** [comment]
i often get smearing on video captured via ffmpeg over rstp using Reolink cameras.  Using RTMP instead of RTSP typically fixes it, or works around it.

I'm running two Hikvision cameras in Frigate over RTSP currently, and have not seen any smearing.  I do get a lot of the queue full messages though as well, when using more than 1 region per camera.

2 cameras, 2 regions per camera at 12 fps

**Comment by tubalainen** [comment]
I can also testify of the log filling up with queue full messages. I use only Hikvision for the frigate setup.
I use an old laptop with Intel core i5 and USB 3 and two Hik cameras.

**Comment by blakeblackshear** [comment]
What resolution is your video feed, and what size are your regions?

**Comment by tubalainen** [comment]
Hi!

I use two cameras and the can be been below.
Camera resolution is 2688x1520 with 15 fps for both cameras

```
cameras:
  uppfart:
    rtsp:
      user: camop
      host: 192.168.1.30
      port: 554
      password: supersecret!
      path: /Streaming/Channels/1
    mask: back-mask.bmp
    regions:
      - size: 1220
        x_offset: 1400
        y_offset: 300
        min_person_area: 9000
        threshold: 0.8
  framsidan:
    rtsp:
      user: camop
      host: 192.168.1.32
      port: 554
      password: supersecret!
      path: /Streaming/Channels/1
    regions:
      - size: 900
        x_offset: 300
        y_offset: 0
        min_person_area: 7000
        threshold: 0.7

```

**Comment by blakeblackshear** [comment]
@cjackson234 is this still happening?
