### ISSUE TITLE
Minimum height in pixel for person detection

### ISSUE THREAD

**Issue by maxi1134** [blakeblackshear/frigate#2703]
**Describe what you are trying to accomplish and why in non technical terms**
I am trying to detect people that are very close to the camera only ( 60% of the frame height) and ignore people in the background downstairs ( 5-10% of the frame height)

The end goal is to trigger a scan when someone gets in front of the door.
I then compare that image to one taken from a different camera to let in the person if both have the same detected name!

**Describe the solution you'd like**
A way to set a minimum height for detected items

**Describe alternatives you've considered**
I tried finding this in the existing tools, but English being my third language, I might not be entering the right search terms!

**Additional context**
Random person: 
![image](https://user-images.githubusercontent.com/1342643/150856252-3086d4be-9966-450a-8cc4-14ce3fb3bea0.png)
![snapshot-1641848119 241037-80jeu0](https://user-images.githubusercontent.com/1342643/150856305-b871982c-ae3a-4f16-a056-b93733555001.jpg)

Person I want to detect:
![image](https://user-images.githubusercontent.com/1342643/150856433-1093b6ff-f5b8-4c6a-a96f-5f8a100bdb8d.png)
![image](https://user-images.githubusercontent.com/1342643/150856446-706a5d4c-a335-4bf2-a72f-ebea830e0d1c.png)

**Comment by alexelite** [comment]
You can set a minimum area for each object detection.
For example in your third photo the person was detected in a 7548  pixel area. Just calculate a desired area based on your resolution.
Check the documentation. https://docs.frigate.video/configuration/index

`filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)`

**Comment by maxi1134** [comment]
That worked!

Thanks a lot!

**Comment by victordariovera** [comment]
There is a way to add this filter config for only one of the cameras and not as a global setting? I couldn't find an example in frigate documentation.

**Comment by NickM-27** [comment]
Yes it's the same config just at the camera indentation level
