### ISSUE TITLE
Possibility to add external log file

### ISSUE THREAD

**Issue by AbDhops** [blakeblackshear/frigate#2704]
**Describe what you are trying to accomplish and why in non technical terms**
I am using docker compose installation. All is good. However, every time I have to see the log, I must see the docker container log. There shall be the possibility to store the log in the log file. If this happens, we can store the log file external to the container, which is easy to share / maintain.

**Describe the solution you'd like**
Log shall not be only send to stderr (Standard screen) but shall be also routed to log file (configurable location)

**Describe alternatives you've considered**
As the logs are not stored there are no alternatives.

**Additional context**
N/A

**Comment by blakeblackshear** [comment]
You can use a docker log driver to change the location of the stored logs: https://docs.docker.com/config/containers/logging/configure/

It is a best practice for docker containers to log to stdout and let docker handle log destinations.

**Comment by AbDhops** [comment]
okay.. I thought like other containers, here also its possible to mount the external log file, without adding special options. 
I will close this.
