### ISSUE TITLE
[Support]: Integrate freestanding Frigate install with HA (for automation, etc.)

### ISSUE THREAD

**Issue by dmkjr** [blakeblackshear/frigate#2705]
### Describe the problem you are having

I have installed Frigate in a standalone docker container.  Is there a method to incorporate with Home Assistant after the fact?  Such as automation and entity controls?

Thanks!

### Version

0.9.4

### Frigate config file

```yaml
Not Needed
```

### Relevant log output

```shell
Not Needed
```

### FFprobe output from your camera

```shell
Not Needed
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

WyzeCam V3

**Comment by blakeblackshear** [comment]
https://docs.frigate.video/integrations/home-assistant

**Comment by dmkjr** [comment]
Ahh,  I thought that may try to install another instance.
