### ISSUE TITLE
Add Docker Tags for beta versions

### ISSUE THREAD

**Issue by elgorro** [blakeblackshear/frigate#2706]
**Describe what you are trying to accomplish and why in non technical terms**
Currently betas have to selected manually and upgrading is only manually possible (defining each version).

**Describe the solution you'd like**
Add beta tags for the platforms addionally, so updating the betas is more simple.

**Describe alternatives you've considered**
I guess this is alternativeless - sure you can upgrade manually.

**Additional context**
Thought for normal users not recommanded: A solid config check depending on the version with logging would be helpful for crashes.

**Examples**
`latest-amd64` == `beta-amd64`,
`beta-0.10-amd64` and `beta-0.9-amd64`, ...

**Comment by blakeblackshear** [comment]
This project still has frequent breaking changes. When I had these tags previously, there was a constant flow of users complaining about their their setup no longer working. It is recommended to intentionally choose specific versions at this time.

**Comment by Firerouge** [comment]
I miss having beta tags, it was nice being able to use watchtower to automatically test new versions.

Please consider bringing back occasional beta tags blakeblackshear, I know it's not the case, but the Updated 2 months ago tag on docker hub makes the project look a bit stagnant.

**Comment by scooper1** [comment]
Agree  I would like to see beta tags.   Using a beta you should expect to see thing break
