### ISSUE TITLE
Recording Window is too large

### ISSUE THREAD

**Issue by tmjpugh** [blakeblackshear/frigate#2709]
**Describe what you are trying to accomplish and why in non technical terms**
when viewing the recording window (https://frigate/recording/camera) I cannot see the controls at bottom of screen unless I scroll down.  If I scroll down I cannot view upper portion of video.  Need ability to view entire image while navigating.

This is possible with events (https://frigate//events?camera)

**Describe the solution you'd like**
Recording view should be similar to Clips

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/pull/9985 this has been fixed as part of the new ui rewrite, closing
