### ISSUE TITLE
Config - Zones and Poly Masks should have same config syntax(?)

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#272]
In the configuration file, the zones are defined by `coordinates: 555,666,773,222` and the masks as `mask: poly,555,666,773,222` they use the same coordinate system and tools to produce them but there´s different config syntax to configure them.
Could this be harmonized in some way to avoid confusion?

**Comment by tubalainen** [comment]
Well, I guess that if the FR https://github.com/blakeblackshear/frigate/issues/273 is addresses this would automatically be addressed :)

**Comment by blakeblackshear** [comment]
Masks support multiple types, so I need some kind of prefix. It is unnecessary for zones since they only accept one type. I will think about it.

**Comment by tubalainen** [comment]
True, maybe we should retire the mask types that are the most difficult to produce and stick with the type that are easily accessible for the majority? Or, offer multiple masks for only polys?

If found it very easy to produce the masks based on polys, for me, at least the image and the base64 way is way more fiddly and less user friendly.

You code, your call. 🌳 I am just a very happy user :)
