### ISSUE TITLE
[Support]: Yolov5 as TFLITE model works?

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#2726]
### Describe the problem you are having

i am wondering if anybody had tried to convert yolov5 to tflite and got it running with frigate.
any experience with this and is it worth a try?

### Version
DEBUG 0.10.0-B912851

here is how this could be done:

https://github.com/ultralytics/yolov5/issues/4586

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

all hikvision

### Any other information that may be helpful

-

**Comment by ozett** [comment]
i did it ... 

```python3 export.py --weights yolov5s.pt --include tflite```


![image](https://user-images.githubusercontent.com/5937811/152032351-003c6510-f398-4528-9e66-72e4181ecea8.png)

**Comment by ozett** [comment]
i missed a step?

![image](https://user-images.githubusercontent.com/5937811/152033219-1ddd880c-b177-440f-b789-dde78aece0a2.png)

**Comment by ozett** [comment]
convertion was fast as hell... 

![image](https://user-images.githubusercontent.com/5937811/152033704-c37e230f-47a4-4e00-b425-91e17f1fcf52.png)

**Comment by ozett** [comment]
same error...

![image](https://user-images.githubusercontent.com/5937811/152034106-46b703ff-fa9a-4bc9-a733-bc321c204eca.png)

**Comment by ozett** [comment]
another try in colab..

![image](https://user-images.githubusercontent.com/5937811/152036690-785662e8-437e-4cec-8f53-432cb9561f1f.png)

**Comment by ozett** [comment]
something is missing...

![image](https://user-images.githubusercontent.com/5937811/152037154-c3fd5c5b-21f6-4b04-9a5f-6aa607029984.png)

**Comment by ozett** [comment]
??
https://github.com/google-coral/edgetpu/issues/419#issuecomment-889878751

**Comment by mr6880** [comment]
Same issue here when I tried it a few days ago

`Process detector:coral_pci:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 180, in run_detector
    detections = object_detector.detect_raw(input_frame)
  File "/opt/frigate/frigate/edgetpu.py", line 110, in detect_raw
    self.interpreter.tensor(self.tensor_output_details[3]["index"])()[0]
IndexError: list index out of range
Process detector:coral_pci3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 180, in run_detector
    detections = object_detector.detect_raw(input_frame)
  File "/opt/frigate/frigate/edgetpu.py", line 110, in detect_raw
    self.interpreter.tensor(self.tensor_output_details[3]["index"])()[0]
IndexError: list index out of range
Process detector:coral_pci2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 180, in run_detector
    detections = object_detector.detect_raw(input_frame)
  File "/opt/frigate/frigate/edgetpu.py", line 110, in detect_raw
    self.interpreter.tensor(self.tensor_output_details[3]["index"])()[0]
IndexError: list index out of range`

**Comment by rogerquake** [comment]
Haven't tried yet, but curious how the results were after importing into Frigate? If it worked good, it would be amazing to get it uploaded so we didn't have to compile it!

**Comment by ozett** [comment]
happens at the point where the model is loaded, i guess
looks like the converted model has different parameters than the usual edgetpu-models from google...

https://github.com/blakeblackshear/frigate/blob/a2d1bd2c6711015f2735b7f508b59cfec397b0f7/frigate/edgetpu.py#L102-L111

**Comment by ozett** [comment]
https://github.com/google-coral/edgetpu/issues/272

**Comment by ozett** [comment]
😱 

> Thanks. My colleague run YOLOv5 v4 320x320 on EdgeTPU for 24 hours yesterday without errors.
https://github.com/google-coral/edgetpu/issues/272#issuecomment-765042662
