### ISSUE TITLE
 FFMPEG process crashed unexpectedly

### ISSUE THREAD

**Issue by wgstarks** [blakeblackshear/frigate#2732]
### Describe the problem you are having

My logs are being flooded with the below error on a new setup.

### Version

0.9.4-26AE608

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.23
  user: mqtt
  password: ********************
  
detectors:
  coral:
    type: edgetpu
    device: usb
  
cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.0.30.20:554/Streaming/channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://user:password@10.0.30.20:554/Streaming/channels/101
          roles:
            - record
      input_args:
        - -c:v
        - h264_cuvid
 #     output_args:
 #       - -filter:v
 #       - fps=fps=5       
    detect:
      width: 352
      height: 240
    motion:
      mask:
        - 775,553,1240,564,1280,0,0,0,0,513
    record:
      enabled: True
    snapshots:
      enabled: True
```

### Relevant log output

```shell
[2022-01-31 19:12:46] watchdog.doorbell INFO : Terminating the existing ffmpeg process...
[2022-01-31 19:12:46] watchdog.doorbell INFO : Waiting for ffmpeg to exit gracefully...
[2022-01-31 19:14:08] frigate.video INFO : doorbell: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
[2022-01-31 19:14:08] frigate.video INFO : doorbell: ffmpeg process is not running. exiting capture thread...
[2022-01-31 19:14:16] watchdog.doorbell ERROR : FFMPEG process crashed unexpectedly for doorbell.

[2022-01-31 19:14:16] watchdog.doorbell ERROR : The following ffmpeg logs include the last 100 lines prior to exit.

[2022-01-31 19:14:16] watchdog.doorbell ERROR : You may have invalid args defined for this camera.

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [rtsp @ 0x562f2ec05700] Missing PPS in sprop-parameter-sets, ignoring

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [flv @ 0x562f2ec6cf80] Non-monotonous DTS in output stream 0:0; previous: 600, current: 100; changing to 600. This may result in incorrect timestamps in the output file.

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [flv @ 0x562f2ec6cf80] Non-monotonous DTS in output stream 0:0; previous: 600, current: 200; changing to 600. This may result in incorrect timestamps in the output file.

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [flv @ 0x562f2ec6cf80] Non-monotonous DTS in output stream 0:0; previous: 600, current: 300; changing to 600. This may result in incorrect timestamps in the output file.

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [flv @ 0x562f2ec6cf80] Non-monotonous DTS in output stream 0:0; previous: 600, current: 400; changing to 600. This may result in incorrect timestamps in the output file.

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [flv @ 0x562f2ec6cf80] Non-monotonous DTS in output stream 0:0; previous: 600, current: 500; changing to 600. This may result in incorrect timestamps in the output file.

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [rtsp @ 0x562f2ec05700] max delay reached. need to consume packet

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [rtsp @ 0x562f2ec05700] RTP: missed 1 packets

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : rtsp://admin:Z4JREiY8W4uu@10.0.30.20:554/Streaming/channels/102: Connection timed out

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : Last message repeated 9 times

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [flv @ 0x562f2ec6cf80] Failed to update header with correct duration.

[2022-01-31 19:14:16] ffmpeg.doorbell.detect ERROR : [flv @ 0x562f2ec6cf80] Failed to update header with correct filesize.
```

### FFprobe output from your camera

```shell
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.9)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
```

### Frigate stats

{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "objects",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "doorbell": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 240,
        "max_disappeared": 25,
        "width": 352
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:Z4JREiY8W4uu@10.0.30.20:554/Streaming/channels/102",
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:Z4JREiY8W4uu@10.0.30.20:554/Streaming/channels/102 -c copy -f flv rtmp://127.0.0.1/live/doorbell -r 5 -s 352x240 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "record",
            "rtmp",
            "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 82,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 180,
        "mask": "",
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "doorbell",
      "objects": {
        "filters": {
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person"
        ]
      },
      "record": {
        "enabled": false,
        "events": {
          "max_seconds": 300,
          "objects": null,
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {}
          }
        },
        "retain_days": 0
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "10.0.1.23",
    "password": "T87N4FFuYcM78fnX3Rz7boJyQ8m6",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mqtt"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

hikvision DB-1

### Any other information that may be helpful

I'm sure this is probably a configuration issue. Not sure what though?

**Comment by blakeblackshear** [comment]
Ffmpeg errors with flv indicate issues with rtmp. This is probably a symptom of the root issue which appears to be poor connectivity to your camera. The main issue is the connection timed out message. Ffmpeg is timing out when trying to connect to your camera.

**Comment by wgstarks** [comment]
The camera is showing a strong signal. It’s a doorbell so not much I can do to improve it. No way to connect ethernet. Is there some other way to work around this?

**Comment by blakeblackshear** [comment]
Is anything else connecting to the camera? What if you remove the second record stream? Can you lower the bitrate of the high resolution stream?

**Comment by wgstarks** [comment]
The hik-connect app is still connecting.

I tried connecting to sub stream but not disabling one of the streams. I’ll give that a shot.

I can’t change the sub stream but I can lower the resolution of the main. I’ll try some various settings and see what happens.

Thanks for the help with this.

**Comment by wgstarks** [comment]
Reducing the bitrate seems to have helped. I am not getting the errors nearly as often (every 10 minutes or so now). Also disabled the cloud connection.

Current configuration-
![Screen Shot 2022-02-01 at 10 02 08 AM](https://user-images.githubusercontent.com/5657833/151994506-49ecc8d0-39de-4d4c-9aee-d9f83eee9e45.png)

`mqtt:
  host: 10.0.1.23
  user: mqtt
  password: T87N4FFuYcM78fnX3Rz7boJyQ8m6
  
detectors:
  coral:
    type: edgetpu
    device: usb
  
cameras:
  doorbell:
    ffmpeg:
      inputs:
#        - path: rtsp://admin:Z4JREiY8W4uu@10.0.30.20:554/Streaming/channels/102
#          roles:
#            - detect
#            - rtmp
        - path: rtsp://admin:Z4JREiY8W4uu@10.0.30.20:554/Streaming/channels/101
          roles:
            - record
            - detect
            - rtmp
      input_args:
        - -c:v
        - h264_cuvid
 #     output_args:
 #       - -filter:v
 #       - fps=fps=5       
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 775,553,1240,564,1280,0,0,0,0,513
    record:
      enabled: True
    snapshots:
      enabled: True`


If you have any recommendations for changes I could use them. Total noob at this.😁
