### ISSUE TITLE
Make wait_time for recording cleanup configurable

### ISSUE THREAD

**Issue by joesteffee** [blakeblackshear/frigate#2734]
When running frigate on unraid, it is constantly deleting files (every 5 seconds) causing array disks to remain spun up all the time, while new recordings will go to the cache disk. I think it would be useful to be able to set the recording cleanup to run one larger job once per day, or even once per week.

**Comment by blakeblackshear** [comment]
This is still a valid request, but 0.10.0 runs cleanup much less frequently. I think it's once per hour. It also doesn't move things from cache unless there is actually an event ongoing. Disk activity is significantly reduced.

**Comment by blakeblackshear** [comment]
This was implemented in 0.10.0
