### ISSUE TITLE
SRT support

### ISSUE THREAD

**Issue by kaffetorsk** [blakeblackshear/frigate#2736]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to use the SRT protocol with Frigate

**Describe the solution you'd like**
Compile ffmpeg with --enable-libsrt

**Describe alternatives you've considered**

**Additional context**
SRT is an up-and-coming video transmission protocol. As far as I can tell, the only change that has to be implemented is compiling ffmpeg with --enable-libsrt for this to be supported
[SRT (wikipedia)](https://en.wikipedia.org/wiki/Secure_Reliable_Transport)

**Comment by G2G2G2G** [comment]
yea srt is a massive improvement with QUIC (http/3) as well (vs old streaming methods)
