### ISSUE TITLE
[Support]:  Filenames are minute:second

### ISSUE THREAD

**Issue by Sloth-on-meth** [blakeblackshear/frigate#2740]
### Describe the problem you are having

currently, my filenames look like

```38.34.mp4```

but i want them to look like ```04-02-2022-00-38-34.mp4```

is that possible?

### Version

0.9.4-26AE608

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolinks

### Any other information that may be helpful

n/a

**Comment by blakeblackshear** [comment]
Why do you want to alter the names of the files? This is an internal file structure for frigate and they are refenced in the database. Future versions will likely store them as Unix timestamps to avoid any daylight savings related issues.

**Comment by Sloth-on-meth** [comment]
It used to always be "Back-date-time" with clips etc
