### ISSUE TITLE
[Support]: Download Clip button visible when it is a snapshot only

### ISSUE THREAD

**Issue by DrSpaldo** [blakeblackshear/frigate#2753]
### Describe the problem you are having

Within the event view listing (showing event details), if you are looking at snapshot only events, the "download clip" button is still visible inside that event. When you click the download clip button it gives a html error.

I would have expected that this button only show when you are viewing events with a clip and the download snapshot button only to be visible.

This may be intentional?

### Version

0.10.0-B1E84CA

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

NA

**Comment by blakeblackshear** [comment]
That button is driven by a flag that indicates the clip does exist. If you get an html file, that means the files are missing unexpectedly.
