### ISSUE TITLE
"Add as Repository" does not appear on the Add-on Store area.

### ISSUE THREAD

**Issue by atlant1c000** [blakeblackshear/frigate#276]
Instructions say: 
        
HassOS users can install via the addon repository. Frigate requires that an MQTT server be running.
Navigate to Supervisor > Add-on Store > Repositories
Add https://github.com/blakeblackshear/frigate-hass-addons

Problem:
    "Add as Repository" does not appear on the Add-on Store area.
    The word "Repository" does not appear at all on that page.
    HassOS version 0.115.4

**Comment by blakeblackshear** [comment]
There is a menu button in the top right when you are in the addon store. https://www.home-assistant.io/hassio/installing_third_party_addons/
