### ISSUE TITLE
Database vacuums

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#2761]
Implement some kind of database vacuum functionality.

**Comment by elgorro** [comment]
Would [PostgreSQL](https://www.postgresql.org/) offer all your requirements?

**Comment by brendanpward** [comment]
I would really like to see this myself.  I have four cameras recording 24/7 and I find that after a few weeks Frigate becomes incredibly slow when I want to watch a clip.  Things speed right back up again after I complete a vacuum of the database.  For now, I have a cron job that takes Frigate offline, completes a vacuum, then starts it back up.  Something built in to Frigate would be far better though.

**Comment by NickM-27** [comment]
> I would really like to see this myself.  I have four cameras recording 24/7 and I find that after a few weeks Frigate becomes incredibly slow when I want to watch a clip.  Things speed right back up again after I complete a vacuum of the database.  For now, I have a cron job that takes Frigate offline, completes a vacuum, then starts it back up.  Something built in to Frigate would be far better though.

Where is your db stored? (What storage medium?) I've never seen the db get slower and events still load in less than 100 milliseconds

**Comment by brendanpward** [comment]
I have it stored across the network over an NFS share on spinning platters, RAID level 0 with two disks.  Disk syncing is disabled and atime is turned off.  My frigate.db is currently 100MB, frigate.db-wal is 4MB and frigate.db-shm is 32KB.  I forgot to mention above that it's not any kind of issue where a simple restart of Frigate helps.  As soon as I vacuum the database Frigate goes back to being blazing fast, videos load instantly, and there's no pause every 10 seconds as though it's buffering (presumably due to loading segments).

Here's a random read/write test from the machine running Frigate to my networked storage:
```
$ fio --name=testRandom --ioengine=sync --rw=randrw --bs=4k --numjobs=1 --size=120m --iodepth=1 --runtime=120 --time_based --end_fsync=1
testRandom: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=sync, iodepth=1
fio-3.28
Starting 1 process
Jobs: 1 (f=1): [m(1)][100.0%][r=6256KiB/s,w=6456KiB/s][r=1564,w=1614 IOPS][eta 00m:00s]
testRandom: (groupid=0, jobs=1): err= 0: pid=2962872: Mon May  1 23:53:14 2023
  read: IOPS=1593, BW=6373KiB/s (6526kB/s)(749MiB/120290msec)
    clat (usec): min=2, max=471570, avg=599.15, stdev=2814.56
     lat (usec): min=3, max=471570, avg=599.48, stdev=2814.57
    clat percentiles (usec):
     |  1.00th=[    4],  5.00th=[    5], 10.00th=[    5], 20.00th=[   12],
     | 30.00th=[  578], 40.00th=[  603], 50.00th=[  619], 60.00th=[  635],
     | 70.00th=[  652], 80.00th=[  676], 90.00th=[  701], 95.00th=[  734],
     | 99.00th=[ 1663], 99.50th=[ 3818], 99.90th=[26084], 99.95th=[35914],
     | 99.99th=[78119]
   bw (  KiB/s): min=    8, max=10848, per=100.00%, avg=6392.09, stdev=2225.86, samples=239
   iops        : min=    2, max= 2712, avg=1598.01, stdev=556.47, samples=239
  write: IOPS=1590, BW=6363KiB/s (6515kB/s)(747MiB/120290msec); 0 zone resets
    clat (usec): min=4, max=471404, avg=14.11, stdev=1077.73
     lat (usec): min=4, max=471407, avg=14.52, stdev=1077.74
    clat percentiles (usec):
     |  1.00th=[    6],  5.00th=[    7], 10.00th=[    7], 20.00th=[    8],
     | 30.00th=[    8], 40.00th=[   10], 50.00th=[   11], 60.00th=[   12],
     | 70.00th=[   13], 80.00th=[   15], 90.00th=[   18], 95.00th=[   21],
     | 99.00th=[   32], 99.50th=[   37], 99.90th=[   56], 99.95th=[   77],
     | 99.99th=[  594]
   bw (  KiB/s): min=   24, max=10992, per=100.00%, avg=6379.53, stdev=2241.47, samples=239
   iops        : min=    6, max= 2748, avg=1594.87, stdev=560.37, samples=239
  lat (usec)   : 4=1.20%, 10=31.01%, 20=25.62%, 50=3.03%, 100=0.07%
  lat (usec)   : 250=0.01%, 500=0.16%, 750=37.03%, 1000=1.20%
  lat (msec)   : 2=0.23%, 4=0.20%, 10=0.14%, 20=0.04%, 50=0.05%
  lat (msec)   : 100=0.01%, 250=0.01%, 500=0.01%
  cpu          : usr=2.11%, sys=6.02%, ctx=161968, majf=5, minf=21
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=191667,191342,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=6373KiB/s (6526kB/s), 6373KiB/s-6373KiB/s (6526kB/s-6526kB/s), io=749MiB (785MB), run=120290-120290msec
  WRITE: bw=6363KiB/s (6515kB/s), 6363KiB/s-6363KiB/s (6515kB/s-6515kB/s), io=747MiB (784MB), run=120290-120290msec
```
Not hugely fast, but I also wouldn't call it slow.

**Comment by NickM-27** [comment]
I think you'd have much better success keeping the db file local. Otherwise every db query has the network latency working against it.

**Comment by DrSpaldo** [comment]
Is there a way (this may be Unraid related) to have the DB in the config area, instead of the media area? Because I can't put 3 TB worth of files onto my SSD...

**Comment by ehn** [comment]
You can set the location of the database in the Docker compose config: https://docs.frigate.video/frigate/installation#storage

**Comment by DrSpaldo** [comment]
> You can set the location of the database in the Docker compose config: https://docs.frigate.video/frigate/installation#storage

Thanks @ehn, I will map another path and try it out :)

**Comment by blakeblackshear** [comment]
Looks like home assistant does this every other Sunday by default: https://www.home-assistant.io/integrations/recorder/#auto_repack

**Comment by DrSpaldo** [comment]
I've updated the DB location to cache/ssd and I think it is faster. Is there any easy way to do the DB vacuum if we are running it on Unraid and not within HA?

**Comment by blakeblackshear** [comment]
Just to clarify, I was noting the way home assistant does vacuuming on it's own sqlite database. The frigate database is not vacuumed by HA or frigate regardless of where it is stored.

**Comment by NickM-27** [comment]
Implemented in https://github.com/blakeblackshear/frigate/pull/6712
