### ISSUE TITLE
Tail docker log in web-gui.

### ISSUE THREAD

**Issue by parhedberg** [blakeblackshear/frigate#2762]
**Describe what you are trying to accomplish and why in non technical terms**
As a user i want to be able to tail docker logs directly in web-gui (under the dots or debugpage?) so that I don't need to log in to my docker container whenever the stream go offline... The very handy "restart frigate" button is awesome for most intermittent problems, but it would be nice to confirm suspicions first.

**Describe the solution you'd like**
Under the three dots, where "restart frigate" is found, have an option like "See docker log" or something..

**Describe alternatives you've considered**
Manually log in to container and tail the logs, (tail -f /var/log/syslog) or doing it from docker (docker logs -tf -n 100 frigate).
Maybe this issue is only for those who run frigate in a docker separate from Home Assistant installation?

**Comment by trythatagain** [comment]
That would be great, I have Dozzle setup for my docker logs, but having access from within Frigate would be really nice.

**Comment by blakeblackshear** [comment]
Logs are included in 0.12
