### ISSUE TITLE
[FR/Question] Use of some shared parameters

### ISSUE THREAD

**Issue by mario-tux** [blakeblackshear/frigate#277]
From the documentation is not clear if one can specify the following parameters in the global configuration letting the cameras to inherit them:
- `best_image_timeout` parameter;
- `crop_to_region` and `snapshot_height` in `mqtt` stanza;
- all the parameters in `save_clips` stanza;
- all the parameters in `snapshots` stanza.

If not, it would be useful to generalize such approach.

**Comment by blakeblackshear** [comment]
Every possible config option is listed in the example config, so those options are generally not available at a global level. I agree that it would be good to have that as an option.

**Comment by mario-tux** [comment]
With reference to the new beta release, could you consider to add in the global section `save_clips` the support for parameters like `enabled` or `pre_capture`. 
Good candidates for a global settings would be also parameters `best_image_timeout` but all one included in the camera-specific `snapshots` section.

**Comment by mario-tux** [comment]
If I didn't miss something, the request should be considered still valid. The above params, in a global position, would be very useful to cut redundant information in the configuration. Thanks.

**Comment by mario-tux** [comment]
The stale bots are very annoying...
