### ISSUE TITLE
Anyone else get config validation error when adding "stationary_threshold" ?

### ISSUE THREAD

**Issue by bm55** [blakeblackshear/frigate#2780]
Anyone else get config validation error when adding "stationary_threshold" ?

`detect:
  #width: 2048
  #height: 1536
  fps: 5
  max_disappeared: 35
  stationary_interval: 0
  #stationary_threshold: 10`

If I comment it out, no error.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/7528001/153298626-8af1e3b4-9547-4fe2-9135-06d567ee42ad.png">

_Originally posted by @bm55 in https://github.com/blakeblackshear/frigate/discussions/2748#discussioncomment-2145117_

**Comment by NickM-27** [comment]
Did you build it yourself? That change to make `stationary_threshold` configurable hasn't been included in a release yet.

Works fine for me with my build as I just tested changing it.

**Comment by bm55** [comment]
https://github.com/blakeblackshear/frigate/discussions/2748#discussioncomment-2145515
