### ISSUE TITLE
Change the order of the cameras in the GUI

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#2782]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to sort the order of the cameras in the gui.

**Describe the solution you'd like**
I would like to be able to sort the cameras in the GUI - today the sorting is based on the camera name.

**Describe alternatives you've considered**
I am hesitant to change my camera naming and numbering.

**Additional context**
![image](https://user-images.githubusercontent.com/26795429/153393171-95e60dbe-10c2-4bd5-94d1-9ab4be4dc3be.png)

**Comment by NickM-27** [comment]
Implemented in #2817

**Comment by thinkloop** [comment]
It seems ordering is implemented but I don't see how to do it, what config is used for ordering?

**Comment by NickM-27** [comment]
> It seems ordering is implemented but I don't see how to do it, what config is used for ordering?

Like this:

```yaml
cameras:
  some_cam:
    ui:
      order: 2
```

Higher numbers come later. This is also visible in the full config reference for the preview docs

**Comment by thinkloop** [comment]
Thank you! Where would I find the preview docs?

**Comment by NickM-27** [comment]
> Thank you! Where would I find the preview docs?

https://deploy-preview-2829--frigate-docs.netlify.app/

**Comment by gabemcg** [comment]
> > It seems ordering is implemented but I don't see how to do it, what config is used for ordering?
> 
> Like this:
> 
> ```yaml
> cameras:
>   some_cam:
>     ui:
>       order: 2
> ```
> 
> Higher numbers come later. This is also visible in the full config reference for the preview docs

this config does not appear to be working for me. Log shows:
 `cameras -> Some_Camera -> ui`
`extra fields not permitted (type=value_error.extra)`

I've triple checked the formatting I don't think I'm doing it wrong but that is what the error seems to indicate?

**Comment by NickM-27** [comment]
@gabemcg are you on 0.11 release candidate? 0.11 hasn't been fully released yet

**Comment by gabemcg** [comment]
> @gabemcg are you on 0.11 release candidate? 0.11 hasn't been fully released yet

ah, nope... frigate:stable-amd64

Thanks!

**Comment by NickM-27** [comment]
Closing as this is now fully released 👍
