### ISSUE TITLE
 Preserve output from 'best.jpg' API after Frigate restart (to get rid of black boxes for all tracked objects)

### ISSUE THREAD

**Issue by leloch** [blakeblackshear/frigate#2799]
It does not look like output of `best.jpg` API endpoint (like `/api/camera_1/car/best.jpg?crop=1&h=150`) is preserved after Frigate restart. Despite there being pleny of events / snapshots in storage, after restart each 'best' image reverts to a black square.

This results with 'Tracked Objects' defaulting to black as well:

![image](https://user-images.githubusercontent.com/13730836/153746183-3d95d0c4-b3a6-4a17-b2ec-416dd616f37a.png)
(it might take hours or more for all these to repopulate - depending on the activity in the video)

It seems like this is because `best_objects` in `CameraState` is just in-memory dictionary:

https://github.com/blakeblackshear/frigate/blob/master/frigate/object_processing.py#L328

Some sort of persistence for this (in db?) could be very useful - the UI looks borken with all these black boxes, which is quite alarming and potentially confusing the users, which might think something is not working as it should (I know I got confused!)

**Comment by blakeblackshear** [comment]
That endpoint is a legacy from a time when Frigate was completely stateless. It will likely be removed in the future and replaced with the thumbnail from the most recent object in the existing database.

**Comment by dermotduffy** [comment]
FWIW: I would like to be able to give the Frigate card the option of showing the latest 'best' match (across any object type, or a specified object type) in the card `image` view. It is possible the described replacement could fit that bill.

**Comment by NickM-27** [comment]
Implemented in #2816

**Comment by NickM-27** [comment]
0.11 is now fully released so closing as this is fixed 👍

**Comment by KillahB33** [comment]
@NickM-27 sorry can you confirm which version this is fixed in?
I am running 0.11.0-3846A13 and have black boxes for everything.

**Comment by NickM-27** [comment]
> @NickM-27 sorry can you confirm which version this is fixed in?
> 
> I am running 0.11.0-3846A13 and have black boxes for everything.

It is fixed in that version and now pulls the images from your events. If you don't have an event with that camera / label then it will be a black box

**Comment by KillahB33** [comment]
> It is fixed in that version and now pulls the images from your events. If you don't have an event with that camera / label then it will be a black box
If I click on that black box I can see events there though, so is there an option I need to have on?

**Comment by NickM-27** [comment]
> If I click on that black box I can see events there though, so is there an option I need to have on?

Snapshots need to be on

> Also this returns a 404. http://192.168.0.30:5000/api/front_right/car/latest.jpg BUT best.jpg returns a black box.

Of course, because that is not a valid url. It is either http://192.168.0.30:5000/api/front_right/car/thumbnail.jpg or http://192.168.0.30:5000/api/front_right/car/snapshot.jpg

**Comment by KillahB33** [comment]
Snapshots need to be on, ok this is the missing piece for me.

BUT I have to ask why, each event have a thumbnail attached to it. How come before this thumbnail was passed to best.jpg but now it's not past to latest.jpg.

Not trying to be annoying, just genuinely curious.

**Comment by NickM-27** [comment]
> BUT I have to ask why, each event have a thumbnail attached to it. How come before this thumbnail was passed to best.jpg but now it's not past to latest.jpg.

You'll find an explanation of why this changed happened above:

> That endpoint is a legacy from a time when Frigate was completely stateless. It will likely be removed in the future and replaced with the thumbnail from the most recent object in the existing database.

That being said, when I implemented this I used the same initial logic for both snapshot.jpg and thumbnail.jpg functions. Naturally, a snapshot is not required for the thumbnail to work, so that would be a bug.

**Comment by KillahB33** [comment]
Ah ok, so once that replacement goes in than I can probably turn snapshots back off.

Appreciate the help and knowledge! Thank you
