### ISSUE TITLE
mjpeg stream does not work

### ISSUE THREAD

**Issue by mitchross** [blakeblackshear/frigate#280]
**Describe the bug**

> A web server is available on port 5000 with the following endpoints.
> 
> /<camera_name>
> An mjpeg stream for debugging. Keep in mind the mjpeg endpoint is for debugging only and will put additional load on the system when in use.

This only produces a single frozen image

**Version of frigate**
latest
**Config file**
Include your full config file wrapped in back ticks.
```
cameras:

  back:
    ffmpeg:
      ################
      # Source passed to ffmpeg after the -i parameter. Supports anything compatible with OpenCV and FFmpeg.
      # Environment variables that begin with 'FRIGATE_' may be referenced in {}
      ################
      input: rtsp://192.168.1.154/ch0_0.h264
      fps: 5
      global_args:
            - -hide_banner
            - -loglevel
            - info
```

**Comment by blakeblackshear** [comment]
What are you seeing in the logs? Also, your `fps` parameter should not be indented under `ffmpeg`. It needs to be up one level.

```
cameras:

  back:
    ffmpeg:
      ################
      # Source passed to ffmpeg after the -i parameter. Supports anything compatible with OpenCV and FFmpeg.
      # Environment variables that begin with 'FRIGATE_' may be referenced in {}
      ################
      input: rtsp://192.168.1.154/ch0_0.h264
      global_args:
            - -hide_banner
            - -loglevel
            - info
    fps: 5
```

**Comment by mitchross** [comment]
Wow moving the FPS inward did it! Thanks!
