### ISSUE TITLE
FR : logo detection

### ISSUE THREAD

**Issue by TRusselo** [blakeblackshear/frigate#2802]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to detect logos so that I can get releavant detection of unknown people

" An unknown person with a Dominos Logo is at the front Door"

ect

deepstack has a custom model for logos here https://docs.deepstack.cc/custom-models-samples/

**Comment by NickM-27** [comment]
You could use something like [double take](https://github.com/jakowenko/double-take) with deep stack which integrates directly with frigate. 

I'm not sure it's within the scope of frigate to have that by default. Although perhaps the custom models in the future frigate+ could be trained to include that, although I'm not sure.

**Comment by TRusselo** [comment]
oh crap... thought this was the doubletake github.... too many tabs open....
