### ISSUE TITLE
Debugging with process_clip.py

### ISSUE THREAD

**Issue by jasonmadigan** [blakeblackshear/frigate#281]
**Describe the bug**
I saw a really useful comment on https://github.com/blakeblackshear/frigate/pull/190 about how to process saved clips for debugging/tuning:

```
docker run --privileged --rm -v ${PWD}/config:/config -v /dev/bus/usb:/dev/bus/usb -v ${PWD}/debug:/debug -v /etc/localtime:/etc/localtime:ro --name=frigate --shm-size=1g blakeblackshear/frigate:reduce_false_positives-deec71f python3.7 process_clip.py --path /debug/false_positives/porch-1599803694.352481-73n4yg.mp4 --debug-path /debug/frames
```

Running with latest stable, I seem to get an error:

```
    capture_frames(ffmpeg_process, self.camera_name, self.frame_shape, self.frame_manager, self.frame_queue, 1, fps, skipped_fps, stop_event, detection_frame, current_frame)
TypeError: capture_frames() takes 10 positional arguments but 11 were given
```

With: 

```
docker run --privileged --rm -v ${PWD}/config:/config -v /dev/bus/usb:/dev/bus/usb -v ${PWD}/debug:/debug -v /etc/localtime:/etc/localtime:ro --name=frigate --shm-size=1g blakeblackshear/frigate:stable-amd64 python3.8 process_clip.py --path /debug/false_negatives/trim.mp4 --debug-path /debug/frames
```

**Comment by blakeblackshear** [comment]
Try running an older version.

**Comment by jasonmadigan** [comment]
Seems to work OK with the older `frigate:reduce_false_positives-deec71f` image. Be nice if it worked with current stuff too. Would also be nice if general config (maybe minus the camera config) could be used as well, rather than the hardcoded debugging config. Would help to be able to test things other than person movement etc.

**Comment by jasonmadigan** [comment]
Closing this, but wanted to note that I've had good success in tuning Frigate with clips by streaming the clip as an RTSP stream on a "test" camera. Details here: https://gist.github.com/jasonmadigan/910d1fb0997c5fa69997340b84367aa8
