### ISSUE TITLE
[FR] clips dir per camera

### ISSUE THREAD

**Issue by robinostlund** [blakeblackshear/frigate#282]
Hi,
It would be nice it would be possible to put each saved clips for each camera in subfolders. Would that be possible to add? 👍 

Thank you for a great tool
Brg Robin

**Comment by blakeblackshear** [comment]
Do you mind describing your use case?

**Comment by robinostlund** [comment]
I have 3 cameras today, 1 is detecting persons alot and to prevent to many files in one folder i would like to separate them in different sub folders, and even better would be to have like /clips/cameraname/date for example /clips/camera1/2020-11-03

Brg
Robin

**Comment by blakeblackshear** [comment]
Got it. Thanks.

**Comment by jmedlin** [comment]
I'll second this, would be useful.
