### ISSUE TITLE
MQTT and/or HA switch to enable/disable motion detection

### ISSUE THREAD

**Issue by hawkeye217** [blakeblackshear/frigate#2835]
**Describe what you are trying to accomplish and why in non technical terms**
0.10.x introduced the ability to record on motion with object detection disabled. This is great. However, it introduced a regression from 0.9.x where motion detection was also disabled whenever detection was disabled.

**Describe the solution you'd like**
I would like to be able to disable motion detection altogether for an indoor camera when it's not needed so that nothing is recorded and I don't see the indoor camera on Birdseye view when Birdseye view is set to ``motion``.

**Describe alternatives you've considered**

**Additional context**
Opening this FR per [this](https://github.com/blakeblackshear/frigate/issues/803#issuecomment-1046109261) discussion thread. Thanks @blakeblackshear!

**Comment by pafnow** [comment]
Would love this too !!

**Comment by NickM-27** [comment]
Closing as this 0.11 is fully released
