### ISSUE TITLE
Hide cameras from web ui

### ISSUE THREAD

**Issue by pjfian** [blakeblackshear/frigate#2837]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to hide certain cameras from the gui so that I can not see the cameras I am using solely for presence detection.

**Describe the solution you'd like**
A option in the config per camera to hide from gui.

**Describe alternatives you've considered**
Running second frigate instance just for presence, but would need additional coral.

**Additional context**
Looking to add up to 9 presence cameras to my setup, but don't need / want them to appear in the web ui.

**Comment by NickM-27** [comment]
Implemented in #2832

**Comment by pjfian** [comment]
@NickM-27 just built and this is perfect, thanks.

**Comment by NickM-27** [comment]
> @NickM-27 just built and this is perfect, thanks.

Glad to hear it 😃

**Comment by NickM-27** [comment]
Closing as 0.11 is fully released

**Comment by BushTrocity** [comment]
Where does the config go? I cant seem it place it anywhere in the config for it apply. I'm running the docker on unraid. Has the docker just not been updated to allow this yet?

**Comment by NickM-27** [comment]
> Where does the config go? I cant seem it place it anywhere in the config for it apply. I'm running the docker on unraid. Has the docker just not been updated to allow this yet?

You need to update it if you haven't, it just goes on the camera level

```yaml
cameras:
  your_camera:
    ui:
      dashboard: false
```

**Comment by BushTrocity** [comment]
Ok and the docker im running is running on 10.1 so that is my main issue. Thanks for getting back so quick.
