### ISSUE TITLE
Make all timestamps match the server time (or give an option for it)

### ISSUE THREAD

**Issue by G2G2G2G** [blakeblackshear/frigate#2838]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to see events in the correct time for the location I am viewing

**Describe the solution you'd like**
If people don't like this, maybe a setting in frigate to switch between server time / your time zone? (though it seems bad to have videos and UI differ, but youc an choose!)

**Describe alternatives you've considered**
I guess I can always go cry in the shower and just deal with it (or a violentmonkey/greasemonkey script)

**Additional context**
## UI time stamps currently differ from video / event / built in video timestamps etc

When managing many locations in different parts of the world, I don't think "oh these people get out of work at 21:30 my time.. and these people get out at 19:30 and these people get out at 01:30" etc
Instead it's simple: they all get out at ~5PM their time.
When reviewing logs, everywhere in home assistant and linux, the logs are set to their server's time. It makes it very easy to follow.

Which brings me to frigate's UI:

It says 5:40 in the UI but it was actually 15:40 as the picture timestamp says.
![1](https://user-images.githubusercontent.com/50514477/154824665-2a8b107c-d42f-4351-977a-6546a651c023.jpg)

Note all 5 of these are under 15:00 so they should all be 15:xx right?
![1](https://user-images.githubusercontent.com/50514477/154825218-17eebe25-a2d0-401c-a4d2-82d4e2364b94.jpg)
However they are all Start: 17:xx instead?

Other people have this issue, for the past year, IDK if anyone has noticed:
https://youtu.be/bu5gce1YIyc
Go to 10:40, you can see he clicks a video that says it "starts: 20:11:10" but the timestamp on his video itself is 19:11:01
It seems his server maybe is off 1 hour because he's certainly at the same house as his server? idk

I am guessing the UI is getting time from your timezone or at least converting it

Thanks!

**Comment by imerr** [comment]
Same issue here

I'm guessing clicking on events is supposed to jump to the relevant video segment as well, which doesn't seem to work due to the mismatched times?
