### ISSUE TITLE
Allow for different date/time formats in timestamp

### ISSUE THREAD

**Issue by muzzak123** [blakeblackshear/frigate#284]
Hi, I'm loving this addon in HA. Keep up the great work.
I live in Australia and was wondering if it was possible to change the  format of the **snapshots: show_timestamp:**  to a dd/mm/yyyy type format, or other types of formats ?

**Comment by fgonza2** [comment]
i was about to file this request when i saw this... yeah, we'd like maybe to customize the file_name format and it's timestamp format via "snapshots:" settings?

**Comment by tubalainen** [comment]
Yes please, in Northern Europe we use yyyy-mm-dd as the commonly used format.

**Comment by dvbit** [comment]
up. one more
