### ISSUE TITLE
A "default camera" timeout.

### ISSUE THREAD

**Issue by maxi1134** [blakeblackshear/frigate#2856]
****Ignore this, I am high and went on the wrong Github.****

Describe what you are trying to accomplish and why in non technical terms
I would like for my live view to return to the preset camera after a certain amount of time.

Describe the solution you'd like
A time out option for the camera view ( Like the timeout for the views )

Describe alternatives you've considered
I tried using the view time out, but it doesn't seem to trigger when I change camera while remaining on "live"

**Comment by NickM-27** [comment]
@maxi1134 If this isn't meant for frigate you can close this issue yourself 👍
