### ISSUE TITLE
[Support]: Recordings view: all links are broken

### ISSUE THREAD

**Issue by midcode** [blakeblackshear/frigate#2859]
Version: 0.10.0-BFECEE9

In the Recording view all the links to video segments do not work because the time is wrong.

![image](https://user-images.githubusercontent.com/6597617/155101113-9b0e0ed5-b21b-466b-83c0-b90245d91064.png)
Here you can see that the timestamps of the videos do not match the timestamps of the "categories"

if you click on the segment at 19:36:40 the url changes to http://\<frigate\>/recording/\<camera\>/2022-02-21/19/306
and (incorrectly) the first segment of the day starts playing. 
If I change the browsers url to http://\<frigate\>/recording/\<camera\>/2022-02-21/**18**/306 the correct segment plays.

**Comment by blakeblackshear** [comment]
Please provide your docker run command and/or compose file.

**Comment by midcode** [comment]
Im running docker inside a proxmox lxc container if that matters.

here is my docker-compose file:

services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config.yml:/config/config.yml:ro
      - /frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "******"

**Comment by midcode** [comment]
Figured it out by looking at the docker-compose file... /etc/localtime was set to UTC in the lxc container... I didn't think to check that its set to Europe/Berlin because normally I setup lxc containers by a script which does that, but i must have created this container in another way.

Maybe add a little sentence to the proxmox section in the documentation to make sure /etc/localtime ist correctly set in the LXC container, because by default its always UTC
