### ISSUE TITLE
Error Attempting Install

### ISSUE THREAD

**Issue by LordNex** [blakeblackshear/frigate#287]
**Describe the bug**
After adding the repository, I attempted to install the component with the install link and got the following error. 

Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout

**Version of frigate**
Not installed yet

**Config file**
Include your full config file wrapped in back ticks.
```
No config
```

**Logs**
```

Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout

```

**Frigate debug stats**
```
Output from frigate's /debug/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
RPi64bit HA - OS: [e.g. Ubuntu, Windows]
Docker - Virtualization: [e.g. Proxmox, Virtualbox]
None - Coral Version: [e.g. USB, PCIe, None]
Both - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
Wyze - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**

**Comment by blakeblackshear** [comment]
Sounds like a docker issue. Still happening?

**Comment by LordNex** [comment]
Yes this resolved itself
