### ISSUE TITLE
[Support]: Incorrect event datetimestamp on first clip this morning

### ISSUE THREAD

**Issue by vertex-github** [blakeblackshear/frigate#2875]
### Describe the problem you are having

Object detection ran this morning just after 7AM, and Frigate detected a person.  However, the first event reported is listed in the Events list as having occurred at 6:25:24AM (incorrect) and then another event shortly thereafter reported at 7:09:46AM (same person). Both events came from the same camera - prior event was 9:04PM the previous evening (reported time was correct).  Ive no idea where the 06:25 timestamp came from. Is there any additional logging I can enable to see if this happens again tomorrow AM?  Camera image has a timestamp embedded in it - the timestamp watermark on the image was 07:02:10.  There are other events reported from different cameras around the same time with the correct timestamps in the Events list.

### Version

0.11.0-3de1948

### Frigate config file

```yaml
Is it possible to move the UIDs and PWDs into a separate config file, which would make pasting the config.yml in here much simpler?
```

### Relevant log output

```shell
Only two log lines logged (these are consecutive in the logs), prior log is from 05:12:52):

[2022-02-26 06:12:52] frigate.record                 WARNING : Unable to find file from recordings database: /media/frigate/recordings/2022-02/25/23/garage_2/58.14.mp4
[2022-02-26 07:11:02] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:57296]
```

### FFprobe output from your camera

```shell
Detect Stream:

Input #0, rtsp, from 'rtsp://UID:PWD@192.168.X.Y:554/h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_sub
  Duration: N/A, start: -0.527938, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x360, 25 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp

Record Stream:

Input #0, rtsp, from 'rtsp://UID:PWD@192.168.X.Y:554/h265Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h265Preview_01_main
  Duration: N/A, start: 0.000250, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink RLC-822

**Comment by blakeblackshear** [comment]
Example at the top of the configuration page in the docs shows how to use an environment variable in camera paths. https://docs.frigate.video/configuration/index

![image](https://user-images.githubusercontent.com/569905/155846176-d3b64540-77d4-4f80-9542-b982b21dc57b.png)
