### ISSUE TITLE
Compatibility with HA's new _Play media_ action

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#2896]
[Home Assistant 2022.3.0](https://www.home-assistant.io/blog/2022/03/02/release-20223/) has introduced [a new "Play media" action](https://www.home-assistant.io/blog/2022/03/02/release-20223/#media-selector-and-the-new-play-media-action), which streamlines the process of streaming a camera entity to a media player.

Quoting from the release notes:

> Have you ever wanted to play your front door camera stream on your television when the doorbell rings? Well, this is now very possible with this update. Check out this video on how to set that up in only 1.5 minutes. 🤯
> 
> https://youtu.be/l2ppksDTq_w

But, for some reason, the Frigate provided cameras cannot be selected as a media source:

https://user-images.githubusercontent.com/29582865/156607893-73737c0f-bce4-4410-8727-f94fee9b1922.mp4

It only lets me select an "object" camera like "front door person", but not "front door".

I wonder if there is anything Frigate can do to support it.

**Comment by NickM-27** [comment]
This probably fits better as an issue in the repo for the integration: https://github.com/blakeblackshear/frigate-hass-integration/issues

**Comment by felipecrs** [comment]
False alarm from my side. In fact, this is working very nicely! What happened in my case was that I was missing `default_config:` in HA (most likely because of the lack of [Media Source](https://www.home-assistant.io/integrations/media_source/)).

Sorry for the confusion.
