### ISSUE TITLE
[Support]: Integration not loading in HA after updating to 2022.3.2

### ISSUE THREAD

**Issue by chench00** [blakeblackshear/frigate#2913]
### Describe the problem you are having

After updating Home Assistant to the latest version (2022.3.2), Frigate ~sensors~ integration no longer loads. 

### Version

0.10.0

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

Home Assistant logs:

        Logger: homeassistant.components.sensor
        Source: custom_components/frigate/__init__.py:364
        Integration: Sensor (documentation, issues)
        First occurred: 6:25:13 PM (2 occurrences)
        Last logged: 6:25:13 PM

        Error adding entities for domain sensor with platform frigate
        Error while setting up frigate platform for sensor
        Traceback (most recent call last):
          File "/home/user/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
            await asyncio.gather(*tasks)
          File "/home/user/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
            await entity.add_to_platform_finish()
          File "/home/user/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
            await self.async_added_to_hass()
          File "/home/user/.homeassistant/custom_components/frigate/__init__.py", line 364, in async_added_to_hass
            self._sub_state = await async_subscribe_topics(
        TypeError: async_subscribe_topics() takes 2 positional arguments but 3 were given

There's actually an error like the above for each such as `sensor`, `switch`, `camera` and`Binary sensor`. The entire integration fails to load.

-----
edit: Is it related to [this](https://www.home-assistant.io/blog/2022/03/02/release-20223/#updates-for-custom-integration-developers) possibly?

**Comment by NickM-27** [comment]
Please check for updates in the hacs store for version `2.2.2`, this has already been fixed before 2022.3 rolled out.

**Comment by junior466** [comment]
@NickM-27 I am running HA core so no store. I simply load the integration through HA.

**Comment by chench00** [comment]
@NickM-27 I am running HA core so no store. I simply load the integration through HA.

**Comment by NickM-27** [comment]
> @NickM-27 I am running HA core so no store. I simply load the integration through HA. 

You're talking about the add on store. Home assistant community store is where all custom integrations come from...

**Comment by chench00** [comment]
I am running a virtual environment.

        System Health
        Version 	core-2022.2.2
        Installation Type 	Home Assistant Core
        Development 	false
        Supervisor 	false
        Docker 	false
        User 	USER
        Virtual Environment 	true
        Python Version 	3.9.10
        Operating System Family 	Linux
        Operating System Version 	4.15.0-169-generic
        CPU Architecture 	x86_64
        Timezone 	America/New_York

**Comment by chench00** [comment]
Sorry, the HA version above is because I had to roll back.

**Comment by NickM-27** [comment]
How did you install the frigate integration? It is not apart of the base home assistant install so you must either have HACS or you downloaded the js file manually. 

HACS is enabled for all home assistant builds including core.

**Comment by chench00** [comment]
I must of had installed it manually. If I search for Frigate under Integrations it doesn't show:

![Screen Shot 2022-03-06 at 8 28 45 PM](https://user-images.githubusercontent.com/63960113/156952729-fd8066e7-b168-407b-9a45-5a5f84c5b17b.png)

**Comment by NickM-27** [comment]
I would highly recommend using HACS now so it is easier to update in the future. Here are the HA instructions to get HACS for core: https://hacs.xyz/docs/setup/download

**Comment by Vitani** [comment]
I can't see version 2.2.2 in the list of releases in [GitHub](https://github.com/blakeblackshear/frigate-hass-integration/releases), nor HACS - 
![image](https://user-images.githubusercontent.com/5907401/161960506-309b3ec1-a232-4964-a0f4-c7744d242ce1.png)

I _can_ see it in the list of [tags](https://github.com/blakeblackshear/frigate-hass-integration/tags) though

**Comment by si458** [comment]
im having the same problem, the is no release of 2.2.2 and you must use the master branch instead

**Comment by NickM-27** [comment]
> im having the same problem, the is no release of 2.2.2 and you must use the master branch instead

There is a release HACS just isn't picking it up for some reason. There is a tag which can be used, master is fine but anyone using master please be aware there are features / things that aren't supported by current frigate version.

**Comment by si458** [comment]
> > im having the same problem, the is no release of 2.2.2 and you must use the master branch instead
> 
> There is a release HACS just isn't picking it up for some reason. There is a tag which can be used, master is fine but anyone using master please be aware there are features / things that aren't supported by current frigate version. 

I believe HACS uses the releases NOT the tags
We had a similar issue with another project

**Comment by NickM-27** [comment]
Yeah since this issue was created we added it as a release https://github.com/blakeblackshear/frigate-hass-integration/releases

**Comment by si458** [comment]
> Yeah since this issue was created we added it as a release https://github.com/blakeblackshear/frigate-hass-integration/releases
> 
> It's just not "latest" for some reason

Only 2.2.1 is listed in releases, the is no 2.2.2?
