### ISSUE TITLE
[FR] Support models with different input-size

### ISSUE THREAD

**Issue by chsw** [blakeblackshear/frigate#293]
I wanted to try the MobileDet SSD model from coral.ai, but his model had an input size of 320x320 instead of the hard coded 300x300 in frigate.
Maybe this  size could be configured in the settings (or even better; if it is possible to get the requested size from the model itself).

(BTW, the model works if I changing the size directly in the code.)

**Comment by RealKanashii** [comment]
Some how-to to use this model inside frigate will be 
really appreciated by IA newbies like me.

**Comment by blakeblackshear** [comment]
I will be adding support for specifying the input size of the model or reading to from the model directly. If this model performs better, I may make it the default as well.

**Comment by rb2k** [comment]
For anyone interested, the hardcoded values are over here in the video area:
https://github.com/blakeblackshear/frigate/blob/64b63142b130a2942b318ea4f65de420ebb12332/frigate/video.py#L94

and also in the detect_objects.py
https://github.com/blakeblackshear/frigate/blob/64b63142b130a2942b318ea4f65de420ebb12332/detect_objects.py#L177
