### ISSUE TITLE
Change the stream source that will be recorded based on mode

### ISSUE THREAD

**Issue by Trixpua** [blakeblackshear/frigate#2932]
Is it possible to change the stream source that will be recorded based on mode?

Lets say in mode "all" it use a substream that record at 640*480 resolution and a framerate of 10 fps, when a motion is detected (mode: motion) it use the main stream to save the record in full resolution and a framerate of 15 fps, so it will save space and increase the lifespan of the hard drive.

I don't figured out how to make this work in the record configuration. If it is not possible I think can be a good feature to implement in the future.

**Comment by blakeblackshear** [comment]
I think this is a duplicate of #2652
