### ISSUE TITLE
Home assistant integration jumping back to older images

### ISSUE THREAD

**Issue by fgonza2** [blakeblackshear/frigate#294]
**Describe the bug**
On the home assistant integration, using MQTT cameras, the content on the images sometimes jumps back to older detections.   For example images from a couple of days ago show up instead of the latest one.    It is strange as i am able to see the right content, but then suddenly jumps to an older image 

**Version of frigate**
0.73

**Comment by mattheys** [comment]
I would suggest using something like MQTT Explorer to see if you have any messages with a retain flag on them. I get this when restarting applications, they connect to MQTT and query the topics they subscribe to for retained messages first, so if I reboot NodeRed for example I will get a push notification from all my cameras for their last detected image which could be a couple of days ago if no one has been out the back.
