### ISSUE TITLE
Question: How does "mask" work with events?

### ISSUE THREAD

**Issue by scottgrobinson** [blakeblackshear/frigate#295]
If I have a mask applied to an image, how much of an "object" needs to be outside of that mask for it to be picked up? Is that configurable?

Specifically - Camera pointing at a house driveway which includes the main road. The main road is masked out, but still want to receive an event if a vehicle is on the main road but has part of the vehicle on the driveway

**Comment by scottgrobinson** [comment]
Even more specifically - Here is a mask, along with an event that was picked up. I expect it's something to do with light changes but not entirely sure.

![Evernt](https://ibb.co/BKBhDDH)

![Mask](https://ibb.co/gwTjj6k)

**Comment by blakeblackshear** [comment]
Masks only apply to the initial motion detection. Once motion is detected, frigate will look for objects near the motion even if they are in masked areas. Zones can be used to limit areas where you want to detect objects. Frigate will find and follow objects outside the zones and into masked areas, but only trigger zone sensors when the object enters a zone.

**Comment by scottgrobinson** [comment]
Thanks @blakeblackshear - Makes sense.

I've set those up, however, the zone data doesn't appear to come through in my events?

```
{'label': 'person', 'score': 0.58203125, 'box': [152, 213, 175, 251], 'area': 874, 'region': [0, 84, 300, 384], 'frame_time': 1605031982.783722, 'centroid': [163, 232], 'id': '1605031982.783722-5axk8b', 'start_time': 1605031982.783722, 'top_score': 0.58203125, 'zones': [], 'score_history': [0.58203125], 'computed_score': 0.0, 'false_positive': True}
```

Config below, and I can confirm that the zone's "appear" to be there!

<img width="508" alt="Screenshot 2020-11-10 at 18 41 36" src="https://user-images.githubusercontent.com/207075/98717225-b5f01f00-2384-11eb-921c-b0c615bab8c2.png">

```
web_port: 5000

detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  host: mqtt
  topic_prefix: frigate
  client_id: frigate

save_clips:
  max_seconds: 300
  clips_dir: /clips
  cache_dir: /cache

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - panic
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -stimeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
  output_args:
    - -f
    - rawvideo
    - -pix_fmt
    - yuv420p

objects:
  track:
    - person
    - car
    - truck
  filters:
    person:
      #min_area: 5000
      #max_area: 100000
      threshold: 0.25
    car:
      #min_area: 5000
      #max_area: 100000
      threshold: 0.25
    truck:
      #min_area: 5000
      #max_area: 100000
      threshold: 0.25

cameras:
  frontgate:
    ffmpeg:
      input: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.2.243/Streaming/Channels/1

    # FIXME
    height: 960
    width: 1280
    fps: 8

    best_image_timeout: 0.5

    #mask: poly,0,-1,2,277,167,254,319,235,472,231,735,236,745,287,1279,377,1279,1

    zones:
      drive:
        coordinates: 3,959,1,277,323,234,498,231,732,236,745,288,1277,374,1279,959,1064,959
      masked:
        coordinates: 0,-1,2,277,167,254,319,235,472,231,735,236,745,287,1279,377,1279,1

    snapshots:
      show_timestamp: False
      draw_zones: True
      draw_bounding_boxes: True
```

**Comment by blakeblackshear** [comment]
The zones in that event message are the zones the object was currently in during the first or last frame where it was tracked. Probably not useful for determining if something is in a zone. The zone specific mqtt topics are designed to report when objects enter zones.

**Comment by scottgrobinson** [comment]
Thanks, @blakeblackshear - Is there something I can "tweak" for the events here so they are more responsive?

See below examples. I seem to get an event start notification first, then I get the zone on/zone off notification.

```
020-11-11 10:43:10,865 - INFO [root] Event start [1605091390.567773-ljxyuh], zones [{'drive': False, 'masked': False}]- Sending pushover: Car 84% @ 10:43:10 (Zones: {'drive': False, 'masked': False})
2020-11-11 10:43:11,147 - DEBUG [root] Zone 'masked' ON
2020-11-11 10:43:12,471 - DEBUG [root] Zone 'masked' OFF
2020-11-11 10:43:37,901 - INFO [root] Event start [1605091417.231856-ow2dhe], zones [{'drive': False, 'masked': False}]- Sending pushover: Car 91% @ 10:43:37 (Zones: {'drive': False, 'masked': False})
2020-11-11 10:43:38,233 - DEBUG [root] Zone 'masked' ON
2020-11-11 10:43:40,326 - DEBUG [root] Zone 'masked' OFF
```

I'm specifically trying to achieve something where I can trigger a message if there is an object detected within a zone. I guess what I could do here is
* Event trigger started
* Pull the image back that triggered the event
* Wait up to X amount of seconds to see if I get a zone on the trigger
* If I do, send the notification

The above seems a bit "clunky" but maybe that's just my way of thinking :D

**Comment by blakeblackshear** [comment]
I see. I use the zone mqtt notification, wait a few seconds and then save a snapshot of best.jpg for my camera. It works most of the time. There are several issues I am working on for the next version that will make this easier, so not sure how far you want to go now. I can make sure your specific scenario is addressed in the next version.

**Comment by scottgrobinson** [comment]
Thank you - That's very much appreciated. Do you have a vague timeframe for that? Not anything I'd be hassling for, just so I can work out if I should put any more effort in right now!

**Comment by blakeblackshear** [comment]
Hoping to get the next version out by mid December.

**Comment by lawrence-jeff** [comment]
@scottgrobinson - Have you had any luck with this. I have a similar setup where I have masked the street and trying to get notifications when a car actually enters my driveway (which I have defined as a zone). Unfortunately I also get alerts when a vehicle exits my garage and enters that same zone on the way out.. I haven't figured the right combination to detect incoming vehicles only... I'm basically trying to do a line detection from only one side (I'm using the latest RC)

**Comment by scottgrobinson** [comment]
@lawrence-jeff Yes and no. It's working semi-nicely, but I hacked the code a bit and added quite a bit on top for my processing. I think I could move to v0.8 and get rid of most of that, but I haven't braved that yet. Unfortunately, we get notifications whether a vehicle is coming or going, but that's acceptable considering the alternative would be to get nothing.

Although... If I had to do this all again based on what you just said above, I think I'd still need to change the code a bit (which is entirley possible FYI! Building a custom docker image based on your own version is pretty easy). I think it would be possible using the coordinates from the detected object (and possible from the event itself), and the coordinates of the line to determine wether something was coming or going...

**Comment by blakeblackshear** [comment]
Here is one way you could do it in 0.8.0.

Split your driveway into two zones. One for the end of your driveway (driveway_entrance) by the street, and another for the rest (remaining_driveway). Then add a condition to only notify if the object has entered driveway_entrance, but not (remaining_driveway).

```yaml
  conditions:
    - "{{ not 'remaining_driveway' in trigger.payload_json['after']['entered_zones'] }}"
    - "{{ 'driveway_entrance' in trigger.payload_json['after']['entered_zones'] }}"
```

You could also add a condition that evaluates the centroid when the zone is first entered to determine where the object entered from and/or determine the direction the object is moving by comparing the centroids in the before and after data.

**Comment by lawrence-jeff** [comment]
@blakeblackshear  Thanks!, I had tried to do the reverse (creating a zone closer to my garage doors) named GarageExit and then one in the middle of the driveway called Driveway. The thought being I could **ignore** transitions from GarageExit zone to Driveway zone and only pay attention when objects go from [] No zone (the street) to driveway.. In that case I was expecting to see Current Zone [] New Zone [Driveway] but I get so many events and most have both GarageExit and Driveway in the entered_zones. I did it in reverse because the camera has an easier time seeing the garage than the street and much of the street is masked

Is EnteredZones a running list of all zones the object has passed through in the event? I was expecting the intermediate events to be singe transition . I.e going from [] to [Driveway] and then another when it went from [Driveway to [GarageExit] and then at the end of the event it would summarize this in the final message with the beginning zone to the final zone so in this case [] (street) to [GarageExit] (the garage door). Also what is the interaction between zones and before and after? In your example you only look at the after, would the before portion not have the object location at the sec before the event was fired and the after have the new zone? Sorry I tried reading the docs but its kind of lite on the details of the MQTT events

**Comment by blakeblackshear** [comment]
> Is EnteredZones a running list of all zones the object has passed through in the event?

Yes. `current_zones` is the alternative.

> Also what is the interaction between zones and before and after?

The `after` message will become the `before` message in the next mqtt publish. It is just giving you both so you can see what changed from the last message more easily.
