### ISSUE TITLE
Choose stream for live video

### ISSUE THREAD

**Issue by srirams** [blakeblackshear/frigate#2963]
**Describe what you are trying to accomplish and why in non technical terms**
I use a lower quality stream for 'detect' and a higher quality stream for 'record'. I would like to select the stream that is used for the live video in the web interface. Currently it seems the that the 'detect' stream is used.

**Describe the solution you'd like**
Add a new option to select the live stream.

**Comment by blakeblackshear** [comment]
This won't happen until HLS is supported. The current live views require decoding the stream.

**Comment by srirams** [comment]
Ok, thanks. Will close this for now.
