### ISSUE TITLE
[Feature Request] Custom storage provider for media files (S3-like or WebDAV)

### ISSUE THREAD

**Issue by dotWee** [blakeblackshear/frigate#2964]
**Describe what you are trying to accomplish and why in non technical terms**

Frigate's media directory uses a lot of storage. It would be useful to use custom storage providers like S3 or WebDAV. 

This would also be useful for cloud-hosting environments.

**Describe the solution you'd like**

Being able to persist events & clips to S3 or WebDAV.

**Describe alternatives you've considered**

When using Docker, mounting the /media directory to an external drive with more space.

**Additional context**

I'm considering implementing this feature myself, but my Python experience is pretty limited. Let me know if this feature is marked as low-priority or not planed for implementing, maybe I'll contribute this feature.

**Comment by natm** [comment]
This would be a great addition, I have been using Frigate for a couple of years now and store recordings + clips offsite. I do this using a custom NodeRED pipeline which is triggered via MQTT, it uploads clips to a local [Minio](https://github.com/minio/minio) container. That local container has bucket replication setup to another Minio instance in a different country.

I would love to see the ability to store in an S3 compatible object store (e.g. AWS or Minio).

**Comment by dotWee** [comment]
Currently digging into the source code, i'll try to implement this for myself. Already forked the repo, but haven't published any code yet. Will update this issue on progress.

**Comment by anuragbhatia** [comment]
Over an year passed on this discussion. Any ideas if option of s3 as storage is being considered now? I would love to have that feature. Would make handing HA storage much more easier.

**Comment by IvanBoykov** [comment]
would love to have this functional too Nice to have some retry logic, at least for latest records to not lost something because temporary network glitchs.

**Comment by gruntmar** [comment]
Using Frigate in cloud environment and would love to have alternative and cheaper storage like S3.

**Comment by scholzi100** [comment]
It looks like dotWee experimented with this last week: [dotWee/feat/remote-storage-driver-via-s3](https://github.com/dotWee/frigate/tree/feat/remote-storage-driver-via-s3)@[ec0bd46](https://github.com/dotWee/frigate/commit/ec0bd4688ef9e99f496ed1e6c70d98d492bbd887)

**Comment by dotWee** [comment]
This is highly experimental. Previously I've used custom docker volume drivers, but I've experienced bottleneck issues and read-write issues while recording.

My fork is an experimental implementation of a customizable storage interface, which currently allows storing the media files on a broadband connected S3 storage.

I try to cover the implementation with unit tests & broad coverage.

Feel free to play with it. Make sure to report if anybody runs into issues.

**Comment by mowol94** [comment]
Hi @dotWee is this a complete implementation yet? I tested your branch, and while S3 initializes without any issues, it doesn't seem to be used. Everything is still being saved to local storage.
FYI: I’m using Ceph RGW as the S3 endpoint.

I would love to test this. I am in the same situation and am currently working with S3 storage drivers, which unfortunately crash quite often.
