### ISSUE TITLE
[Support]: WARNING (SyncWorker_3)

### ISSUE THREAD

**Issue by AnKloss** [blakeblackshear/frigate#2967]
### Describe the problem you are having

22-03-15 07:35:35 WARNING (SyncWorker_3) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access) Beta (0.11.0)
22-03-15 07:35:35 WARNING (SyncWorker_3) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)

hello can you fix it ?

mfg
Andreas

### Version

0.11.0

### Frigate config file

```yaml
sorry i have deleted it out
```

### Relevant log output

```shell
WARNING (SyncWorker_3)
```

### FFprobe output from your camera

```shell
WARNING (SyncWorker_3)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

other

**Comment by NickM-27** [comment]
Have you followed the instructions here to use the correct host when setting it up? https://docs.frigate.video/integrations/home-assistant/#configuration

**Comment by blakeblackshear** [comment]
Is this causing you a problem?

**Comment by AnKloss** [comment]
Frigate is not starting.
Is wait on service and then is send term signal and restart

**Comment by AnKloss** [comment]
22-03-15 09:14:35 ERROR (SyncWorker_0) [supervisor.docker.interface] Container addon_ccab4aaf_frigate is not running
22-03-15 09:14:46 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with ccab4aaf_frigate!
22-03-15 09:14:47 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_ccab4aaf_frigate application

**Comment by AnKloss** [comment]
log 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-03-15 09:17:07] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-03-15 09:17:07] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-03-15 09:17:07] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-03-15 09:17:07] peewee_migrate                 INFO    : There is nothing to migrate
[Errno -2] Name or service not known
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by blakeblackshear** [comment]
That message is not your problem. Looks like it is unable to connect to the mqtt server in your config file.

**Comment by AnKloss** [comment]
okay thanks
