### ISSUE TITLE
[FR] Do an initial scan on startup

### ISSUE THREAD

**Issue by chsw** [blakeblackshear/frigate#297]
Would it be possible to scan the whole image once at startup, to start the tracking process?

I have noticed that on startup on calm days, nothing is detected until some movement is detected. Once there is some movement (or if I turn off/on a light on my driveway) it starts scanning again and starts tracking my stationary car.

**Comment by blakeblackshear** [comment]
How often are you restarting frigate? I could look on startup, but that would only be once every few weeks for me. What are you tracking your stationary car for?

**Comment by chsw** [comment]
You have a valid point. 
I have two somewhat useful scenarios where it would help to start tracking at startup. 
Currently i'm setting this up and trying to figure out if and how this software can do what I want. That means i restart it a couple of times  a day (when ever I get the time to adjust some sitting i config).

What I eventually want to achieve is to be notified if there is a person  or car on my driveway at nights or if I am away from home. The problem  I have is that I have two cars, and at least  one of them will always be visible (and tracked) once there is motion. I haven't figured out how to deal with this yet, but one ideal scenario would be to be able to activate a recording/notifying state, which ignores the objects it can currently detect. I suspect that in this scenario I need to detect the car even if there have been not motion detected since startup, otherwise I get a false alert of the car whenever something else moves.

**Comment by blakeblackshear** [comment]
Makes sense, and it is a common use case. I  will think about ways to handle the challenge when there are existing objects in the zone vs new ones. Can you post an image from your camera so I have an idea what your driveway looks like?

**Comment by chsw** [comment]
I'm "not allowed" posting an image of my driveway publicly by other members of this house, I'm sorry.
