### ISSUE TITLE
Motion or last motion sensor

### ISSUE THREAD

**Issue by SlickUnderTheGun** [blakeblackshear/frigate#2974]
I'd like to request a generic binary motion sensor per camera that changes state when the camera is or isn't sensing motion. Alternatively, a sensor for each camera that lists the datetime of last motion.

I currently achieve this with the Amcrest integration which does have binary motion sensors and a template sensor that displays their last state change. My intent is to stop using the Amcrest integration and rely entirely on Frigate.

**Comment by NickM-27** [comment]
To be clear, are you talking about actual motion or just objects? There is already an implementation (that hasn't been released yet) for a sensor in HA `all` that will be true when any object is detected. 

Nothing exists for a true motion sensor, but that is already agreed upon and I believe there is a separate issue for that already.

**Comment by SlickUnderTheGun** [comment]
Motion in general, whether an object is detected or not. I saw the detection_fps sensor suggested but that seems to apply to all cameras.

**Comment by NickM-27** [comment]
> Motion in general, whether an object is detected or not. I saw the detection_fps sensor suggested but that seems to apply to all cameras.

This is definitely coming but in the interim, you can use detection fps. There is a global as well as per-camera detection fps sensor

**Comment by SlickUnderTheGun** [comment]
Oh duh, I see the individual fps sensors in the entity list for each camera now. Tracking their state changes should definitely work until true motion sensors are available. Thank you
