### ISSUE TITLE
[FR] Log all events

### ISSUE THREAD

**Issue by scottgrobinson** [blakeblackshear/frigate#298]
Please delete/close if not a viable/sensible suggestion, it might be a bit niche.

I have currently set a very low confidence threshold in frigate so that "most" object detections trigger an event, then in my "messaging" application (Just some processing that does a few bits of magic and sends me a pushover notification), I filter out events with a lower percentage but still debug log them.

I specifically do this so that I have some debugging to fall back on if someone says "At 18:12:12 a person went by, but I didn't get a notification. Any reason why?"

It might be useful if frigate had that ability. Ideally, I'd also like to snapshot it with a picture somehow aswell.

**Comment by blakeblackshear** [comment]
I expect to build this into frigate directly. Next version will have an integrated database for events.

**Comment by scottgrobinson** [comment]
Thank you! I'll close this one myself in that case. Look forward to that :)
