### ISSUE TITLE
[Support]: Docker pull fails with "manifest unknown"

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [blakeblackshear/frigate#2982]
### Describe the problem you are having

I can't install via Docker either by `docker pull` or `docker-compose`.  It fails as follows:

```
[root@nvr frigate]# docker pull blakeblackshear/frigate
Using default tag: latest
Error response from daemon: manifest for blakeblackshear/frigate:latest not found: manifest unknown: manifest unknown
```

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
[root@nvr frigate]# docker pull blakeblackshear/frigate
Using default tag: latest
Error response from daemon: manifest for blakeblackshear/frigate:latest not found: manifest unknown: manifest unknown
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

Nothing more to add.  I'm assuming there has been a change to the manifest that has corrupted new installs?

**Comment by blakeblackshear** [comment]
There is no latest tag. Pull a specific version or the stable tag.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Both result in the same issue.  I have also tested this between my frigate testing box, and my production Docker server.  Both exhibit identical behavior.

**Comment by NickM-27** [comment]
> Both result in the same issue.  I have also tested this between my frigate testing box, and my production Docker server.  Both exhibit identical behavior.
> 
> 

Can you give an example of a specific tag you tried and the logs of it failing?

**Comment by blakeblackshear** [comment]
Available tags are listed here: https://hub.docker.com/r/blakeblackshear/frigate/tags

Docs list images available here: https://docs.frigate.video/installation#docker

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Sorry.  I misread the instructions.  Thanks for your help.

**Comment by PrynsTag** [comment]
For those reading this in the future:
> We are no longer pushing images to Dockerhub. All docker builds will be published to github container registry instead. The new image location for stable is ghcr.io/blakeblackshear/frigate:stable

Source: https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0
