### ISSUE TITLE
[Support]: Support for CPU without AVX instruction

### ISSUE THREAD

**Issue by HSB-collab** [blakeblackshear/frigate#2999]
### Describe the problem you are having

I have already written this up in Issue #2298 but because that issue is marked as closed I am starting a new issue.

I apologise in advance if I am doing something stupid. I am new to Docker and have limited programming skills.

I am trying to compile a Frigate Docker container as per the instructions from @pdecat in Issue #2298 for an old Phenom II based machine that I have which is running Ubuntu 20.04.
.
The first time I tried, I successfully compiled the Frigate Docker container but after a while it stopped recording video so I decided to rebuild the container. However, I have tried a dozen times and it fails to rebuild.

I enclose a file with the Docker build terminal output. As far as I can see there appear to be compiler errors but I don't know why.

I would really appreciate any hel
[error.txt](https://github.com/blakeblackshear/frigate/files/8323454/error.txt)
p

### Version

0.10.0

### Frigate config file

```yaml
Not relevant because the problem is building the Docker container
```

### Relevant log output

```shell
Please error.txt above
```

### FFprobe output from your camera

```shell
Not relevant because the problem is building the Docker container
```

### Frigate stats

```json
Not relevant because the problem is building the Docker container
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

Not relevant because the problem is building the Docker container

**Comment by NickM-27** [comment]
So you're building the docker image from @pdecat and it is failing? I would try setting no-cache option on docker build and see if that works correctly.

**Comment by pdecat** [comment]
Also make sure your system is not suffering from other conditions like low available disk space or free memory.

**Comment by HSB-collab** [comment]
Thanks @pdecat and @NickM-27 for your help. I finally got it to build by (a) using --no-cache as suggested by @NickM-27, (b) stripping just about all apps out of the machine (so perhaps it was a system resource issue but I can't see why because I have 8Gbyte of Memory and 32Gbyte of swap space and plenty of free disk space) and (c) uninstalling and reinstalling Docker. I can't understand why I had to do the last but it would not build unless I had a fresh install of Docker.

**Comment by HSB-collab** [comment]
Unfortunately, now that I have been able to build and run the Docker container, I still can't get it to record video when an event is detected. I get a snapshot but no video. This is the config file for my cameras. It has worked successfully on another instance of Home Assistant with the same setup (but not an old cpu):
``
# Name of your camera
  Camera2:
    ffmpeg:
      inputs:
        - path: rtsp://***:***@10.0.0.125/live
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: False
    objects:
      track:
        - person
    record:
      enabled: False
      events:
        max_seconds: 60
        retain:
          default: 10
          mode: active_objects 
    snapshots:
      enabled: True
      crop: False
      height: 500
``
Any suggestions would be greatly appreciated.

**Comment by NickM-27** [comment]
> Unfortunately, now that I have been able to build and run the Docker container, I still can't get it to record video when an event is detected. I get a snapshot but no video. This is the config file for my cameras. It has worked successfully on another instance of Home Assistant with the same setup (but not an old cpu):
> 
> ``
> 
> # Name of your camera
> 
>   Camera2:
> 
>     ffmpeg:
> 
>       inputs:
> 
>         - path: rtsp://***:***@10.0.0.125/live
> 
>           roles:
> 
>             - detect
> 
>             - rtmp
> 
>             - record
> 
>     detect:
> 
>       width: 1920
> 
>       height: 1080
> 
>       fps: 5
> 
>       enabled: False
> 
>     objects:
> 
>       track:
> 
>         - person
> 
>     record:
> 
>       enabled: False
> 
>       events:
> 
>         max_seconds: 60
> 
>         retain:
> 
>           default: 10
> 
>           mode: active_objects 
> 
>     snapshots:
> 
>       enabled: True
> 
>       crop: False
> 
>       height: 500
> 
> ``
> 
> Any suggestions would be greatly appreciated.

Your config shows record: false

**Comment by pdecat** [comment]
Still current.
