### ISSUE TITLE
Exception followed by queue full

### ISSUE THREAD

**Issue by drcrimzon** [blakeblackshear/frigate#30]
running on 2 cameras, 5 regions (2x 640, 3x800) @ 2-10fps.

I would notice the detection would not be running, check the container, and it's churning queue is full.  Finally caught the exception which triggers the queue is full.  See below.

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/object_detection.py", line 55, in run
    self.cameras[frame['camera_name']].add_objects(parsed_objects)
  File "/opt/frigate/frigate/video.py", line 219, in add_objects
    y_location = min(int(obj['ymax']), len(self.mask)-1)
TypeError: object of type 'NoneType' has no len()

queue full. moving on
queue full. moving on
queue full. moving on
queue full. moving on
queue full. moving on

**Comment by jon102034050** [comment]
I had this same stack trace. Does your mask file exist for all of your cameras?

**Comment by drcrimzon** [comment]
My masks are there, is there a specific bitmap format they are supposed to be in?  I just created a WxH sized image in gimp and exported as bmp.  I verified permissions, and triple checked config, it looks correct.

**Comment by drcrimzon** [comment]
Well, I recreated the masks with a gray scale bitmap, which dropped the size from 7MB to 2MB, this solved the crash it appears.

**Comment by drcrimzon** [comment]
Well, it crashed again with the 2MB bitmaps, I created 500k ones using imagemagick:
convert -size 2560x1440 -colors 254 xc:white mask.bmp, which looks like it's working so far.

Not sure if it's still an issue, If I remove the mask from the config, it looks like the code is supposed to create one on the fly, but that generates an error currently.

I'll let this run over night and see if it is really fixed, and then take a look at the auto create tomorrow.

**Comment by jon102034050** [comment]
fwiw, my mask is literally just a white bmp, and its around 4.5MB and I've had no issues. I'll be perfectly honest though and say that I don't know much about how the masks work, and it doesn't seem to be really well documented (yet).

**Comment by blakeblackshear** [comment]
The mask works by looking at the bottom center of the bounding box for the detected person in the image. If that pixel in the mask is a black pixel, it ignores it as a false positive. In my mask, the grass and driveway visible from my backdoor camera are white. The garage doors, sky, and trees (anywhere it would be impossible for a person to stand) are black.

@jon102034050 If you just omit the `mask:` property in your yaml config, it should generate an all white one for you on the fly.

@drcrimzon The only reason that line could fail is if OpenCV was unable to read your mask file. Looking at the docs, this is what it says:
> If the image cannot be read (because of missing file, improper permissions, unsupported or invalid format), the function returns an empty matrix

I have been saving my file out of Photoshop as a BMP with these settings:
![image](https://user-images.githubusercontent.com/569905/57422783-f7739d00-71d6-11e9-81d4-46418c0cfa57.png)

**Comment by drcrimzon** [comment]
Those are the settings, I was using.  The container ran overnight with the new bmp i generated with convert.

I also tried omitting mask, but that resulted in an error trying to execute np.zeros in the generation of the mask.  I'll try it again and post the exact error.

**Comment by drcrimzon** [comment]
@blakeblackshear, I went back and removed the mask from my config.  The error was np not defined.  Checked and video.py is missing numpy.
Added
import numpy as np  and rebuilt, and it resolved the auto mask creation.

**Comment by blakeblackshear** [comment]
Thanks. I will fix that in the next release.
