### ISSUE TITLE
[Bug]: Disabling recording & snapshots for a camera with an in-progress event keeps the event in-progress perpetually.

### ISSUE THREAD

**Issue by NickM-27** [blakeblackshear/frigate#3022]
### Describe the problem you are having

Steps to reproduce:
1. Start event with snapshots &|| record enabled.
2. Disable snapshots & record through frigate UI or MQTT
3. Remove object for event from view
4. Notice that event stays in-progress after object has stopped being detected.
5. After restart, snapshots and recording are not available.

### Version

0.10 & 0.11

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

N/A

**Comment by NickM-27** [comment]
I believe I found a fix so will submit a PR.

**Comment by akarpych** [comment]
> I believe I found a fix so will submit a PR.


could you share the solution? I have the same problem: the sensor is not reset after detection.

**Comment by NickM-27** [comment]
> > I believe I found a fix so will submit a PR.
> 
> 
> could you share the solution? I have the same problem: the sensor is not reset after detection.

I fixed it in a PR, it's already been merged and will be fixed in the next release.

**Comment by akarpych** [comment]
OK. thanks

**Comment by NickM-27** [comment]
@akarpych  I would double check the title if the issue though as I didn't have anything directly related to sensors. I was talking about events continuing when deleting recording and snapshots...
