### ISSUE TITLE
[Support]: NAS storage

### ISSUE THREAD

**Issue by LaurenceGough** [blakeblackshear/frigate#3031]
### Describe the problem you are having

Hello,

I have a Raspberry Pi 4 with HASSOS running on it - everything is working lovely including smart home control but I believe it is impossible currently to mount either a Samba or NFS share from a NAS for 24/7 constant storage? I understand that this is a limitation of HASSOS itself. I am not in the know but if this is changing in the future I am happy to wait - although this might be more of a question for the HA guys!

I wanted to use this install method to avoid the overheads of running a full Linux OS and supervisors on my Pi 4.

Is the Home Assistant Supervised method the lightest way to allow Frigate to record to a Samba or NFS share on a NAS? Do you think the Pi 4 could cope OK? It is doing just fine currently.

Notes: I have preordered a Coral USB TPU accelerator so I would need it to work with that. 

Thank you and sorry but I am a bit confused as to which route to go along.

### Version

0.11.0-CBF26E0

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
There is a related ticket which has good information on this: https://github.com/blakeblackshear/frigate/issues/2296

[There are workarounds](https://docs.frigate.video/installation/#home-assistant-operating-system-hassos) but overall it is not recommended to run frigate inside of HASSOS for this reason. Not sure what type of NAS you have but if it supports docker containers then it might be better to just have the NAS run frigate.

**Comment by LaurenceGough** [comment]
> There is a related ticket which has good information on this: #2296
> 
> [There are workarounds](https://docs.frigate.video/installation/#home-assistant-operating-system-hassos) but overall it is not recommended to run frigate inside of HASSOS for this reason. Not sure what type of NAS you have but if it supports docker containers then it might be better to just have the NAS run frigate.

Hi Nick, thanks for helping again :).

I did have a read through of that but looks like there was indeed no solution for HASSOS on bare metal.

Unfortunately my NAS is as simple as it comes and has no chance of running Docker or anything, new ones are too expensive! 

I was foolish to install it on the Pi itself, now I am going to have to redo my many hours of work, I hope my configs save! 

I suppose an alternative is just to have the cameras themselves save to the NAS directly with the main stream and perhaps just retain object events on Frigate on the SSD on the sub stream it's currently running on. I may have to play with this.

Thank you

**Comment by LaurenceGough** [comment]
I'm closing this "issue" off. My solution was to reinstall home assistant fully and use the Supervised HA install on a Linux OS install. Unfortunately I had to setup all of my smart home devices and automations but there we go... I was then able to use fstab to mount my NAS share automatically (avoiding the Frigate .db file).

Thank you :)
