### ISSUE TITLE
[Support]: How to specify local frigate.db location on Home Assistant Supervised install?

### ISSUE THREAD

**Issue by LaurenceGough** [blakeblackshear/frigate#3037]
### Describe the problem you are having

Hello,

Finally today I made the switch away from HASSOS to Home Assistant Supervised running on Raspberry OS. 

After many hours of work and perhaps a few more hours... I have mounted the frigate media drive to my NAS, unfortunately now this has caused the frigate.db lock message... as expected I believe.

The issue I am having is I cannot for the life of me work out how to configure this to be locally stored on my Pi 4's local SSD - I am not sure how to set it up but that might be because it's 4AM now and I've had enough!!
I know you can set a database location here but I cannot find how to set it locally - I understand that as it runs in a docker container it's a bit tricky?
database:
  path: /path/to/frigate.db

All I need is recordings on the NAS, everything else can go on the local SSD... 

### Version

0.11.0-CBF26E0

### Frigate config file

```yaml
N/A for this
```

### Relevant log output

```shell
unable to open database file
Starting migrations
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
N/A for this
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A for this

**Comment by NickM-27** [comment]
Docker containers should make this simple. By default the database goes to the media folder, so I think you will need to define another shared volume: `/path/on/pi/ssd/database/:/database/` and then set in the frigate config database path `/database/frigate.db`

**Comment by LaurenceGough** [comment]
> Docker containers should make this simple. By default the database goes to the media folder, so I think you will need to define another shared volume: `/path/on/pi/ssd/database/:/database/` and then set in the frigate config database path `/database/frigate.db`

Thanks Nick, just as you posted that I think I found a solution (a bit out of the box thinking haha, time for bed I think....):

//ip/share/recordings     /usr/share/hassio/media/frigate/recordings  cifs  username=cctvuser,password=xxxxxx,iocharset=utf8  0  0
//ip/share/clips     /usr/share/hassio/media/frigate/clips  cifs  username=cctvuser,password=xxxxxx,iocharset=utf8  0  0
//ip/share/cache     /tmp/cache  cifs  username=cctvuser,password=xxxxxxxx,iocharset=utf8  0  0

**Comment by LaurenceGough** [comment]
> Docker containers should make this simple. By default the database goes to the media folder, so I think you will need to define another shared volume: `/path/on/pi/ssd/database/:/database/` and then set in the frigate config database path `/database/frigate.db`

Thanks Nick, just as you posted that I think I found a solution (a bit out of the box thinking haha, time for bed I think....):

//ip/share/recordings     /usr/share/hassio/media/frigate/recordings  cifs  username=user,password=xxxxxx,iocharset=utf8  0  0
//ip/share/clips     /usr/share/hassio/media/frigate/clips  cifs  username=user,password=xxxxxx,iocharset=utf8  0  0
//ip/share/cache     /tmp/cache  cifs  username=user,password=xxxxxxxx,iocharset=utf8  0  0

**Comment by trythatagain** [comment]
Not sure if this is any help to you. I put db on to my hard drive, as I kept loosing db of events etc, when messing about new images.

In my docker-compose I have this line based on Frigate docs.
#Docker container db volume
- /media/main/frigate/db:/db
     
This line is in the frigate.yml file. I only have 3 cameras with a retain of 21 days and the 3 db files amount to less than 110MB.
So far its been working well and I haven't had any trouble.
#Database folder
database:
  path: /db/frigate.db
