### ISSUE TITLE
[Support]: Is there a recommended i-frame setting for Frigate? Also a question about lowering detection FPS further

### ISSUE THREAD

**Issue by LaurenceGough** [blakeblackshear/frigate#3048]
### Describe the problem you are having

Hello,

I did some research but I couldn't appear to find a recommended i-frame. Is there a recommended setting at all for Frigate (object detection and recording streams)?

Another question if I may, I am currently using my Pi 4 CPU which appears to be coping very well with peaks of CPU usage around 70-80%, however I was wondering if I could get an improved inference speed if I used a lower detection FPS than the current 5 FPS? (detection substream)

Sometimes I am seeing spikes in the inference speed which I believe means time until object detection reported? So if the person was to only show briefly in view it could take up to half a second to detect the person (object) during the peaks? Or have I misunderstood it?  Normally it is around 140ms but I am wondering if it's spiking when processing information.

Or are there any other tricks I could try to reduce the peak inference time?

Currently I have two CPU processor config's setup with 4 threads each being that the Pi 4 has a 4 core processor.

I have a Coral USB accelerator on pre-order but it's going to be a while yet.

Many thanks,

Laurence

### Version

0.11.0-CBF26E0

### Frigate config file

```yaml
N/A for this question
```

### Relevant log output

```shell
N/A for this question
```

### FFprobe output from your camera

```shell
N/A for this question
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A for this issue I believe

**Comment by blakeblackshear** [comment]
Since you are using a CPU, its going to have slower inference speeds when there is more CPU usage for other things. It's just competing for resources. Adjusting the iframe rates won't have any effect on inference speeds. You could try reducing the detection fps as long as it's frequent enough for your needs.
