### ISSUE TITLE
[Q] "Accuracy" of zone detection/Point Polygon Test

### ISSUE THREAD

**Issue by scottgrobinson** [blakeblackshear/frigate#306]
I'm trying to work out why I am getting zone triggers for an image like the below. You can see my zone outlined, and I've used cv2 to "mark" the bottom_centre position that is passed to pointPolygonTest. 

I've confirmed this image is "triggered" by the pointPolygonTest by modifying the code slightly to output said image to a file along with the green dot for testing when the pointPolygonTest is >= 0.

I can see it crosses, but I can't work out "why". Why is the box around the tracked object bigger than it needs to be? Is it purposefully putting a square (rather than a rectangle), or does the underlying detection (using coral) actually think that the extra space is part of the "car"?

NB - I can't easily reduce the size of the zone. The zone is there to pick up vehicles that purposefully cross the driveway threshold, sometimes they are just on the very edge. 

![1605535581 122381-iyzeg1_1](https://user-images.githubusercontent.com/207075/99262126-7f4b5600-2815-11eb-971d-c7b19be9b22c.jpg)

**Comment by tubalainen** [comment]
I the example picture above I guess that the shadow causing frame and pixel movement from the passing truck (car) can have gone over into your poly zone. Bring it in a bit into the driveway and hopefully that will help.

**Comment by blakeblackshear** [comment]
That is the bounding box of the detection directly from the Coral. Nothing I do determines the size. You will need to adjust the zone or add a `for` parameter on your automation trigger if you want to avoid false positives.
