### ISSUE TITLE
[Support]: Frigate with Home Assistant docker image

### ISSUE THREAD

**Issue by ipiazza** [blakeblackshear/frigate#3082]
### Frigate integration for Home Assistant docker image

Hello team,
I am very new to Home Assistant and Frigate, but as I have some experience with the Arduino framework and MQTT I was thinking to leverage the aforementioned tools to create a Smart Home Alarm System triggering mechanic sirens upon person detections, switching on&off outside lights at regular interval for the alarming timeout, stuff like those...
Now I followed the Frigate installation guide, I setup everything but then I came into the Home Assistant Integration part and I saw it refers to the Home Assistant Operating System or Supervised mode.
My setup is made of 3 docker containers: frigate, mosquitto-eclipse, homeassistant. I was wondering if there is a way to integrate Frigate into HomeAssistant in such a setup.
Thanks!

### Version

the one of the latest docker image for amd64 arch

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

rtsp stream of the laptop webcam [used for testing purpose only]

**Comment by NickM-27** [comment]
Hi, yes simply setup the HomeAssistant integration and when it asks for the URL just put the URL of the frigate docker container.

**Comment by NickM-27** [comment]
> wow! As simple as that.. :) Thank you very much!

Sure! If that is working then you can close this issue and feel free to open another if something else comes up 👍

**Comment by ipiazza** [comment]
> 
One question before I close it: how can I install the integration in the Home Assistant container?

After that I will close it as I work this project during weekends and nights. But I am not sure I can work on it regularly and extensively in the next days so better to keep things clean.

**Comment by NickM-27** [comment]
> > 
> 
> One question before I close it: how can I install the integration in the Home Assistant container?
> 
> 
> 
> After that I will close it as I work this project during weekends and nights. But I am not sure I can work on it regularly and extensively in the next days so better to keep things clean.  

You need to install HACS and then it can be downloaded through there: https://hacs.xyz/docs/setup/download

**Comment by ipiazza** [comment]
> > > 
> > 
> > 
> > One question before I close it: how can I install the integration in the Home Assistant container?
> > After that I will close it as I work this project during weekends and nights. But I am not sure I can work on it regularly and extensively in the next days so better to keep things clean.
> 
> You need to install HACS and then it can be downloaded through there: https://hacs.xyz/docs/setup/download

SUPER!!!! Thanks so much for the help. I'll close the issue. If I'll succeed you no longer read from me, otherwise I will file a new one.
