### ISSUE TITLE
Would OpenVINO be an option?

### ISSUE THREAD

**Issue by andre-pt** [blakeblackshear/frigate#3084]
**Describe what you are trying to accomplish and why in non technical terms**
Due to the chip shortage, more specifically CoralTPU, it would be great to have a more efficient inference framework for CPU.

**Describe the solution you'd like**
My ML and python knowledge is very limited, but from what i understand on tf / tflite vs openvino benchmarks, openvino is much more efficient:
* https://hackernoon.com/optimizing-neural-networks-for-production-with-intels-openvino-a7ee3a6883d
* https://github.com/yaysummeriscoming/xnnpack_benchmarks

I think it would be worth to make an isolated benchmark on this for frigate's usecase. If it can reduce about 9x the latency, it would probably be good enough for a lot of people who have a limited number of cameras.

**Additional context**
Existing models can be converted: https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html

**Comment by NickM-27** [comment]
One thing to note is that Frigate runs on TensorflowLite `tflite` while the model conversion docs only seem to reference full Tensorflow models `pb`. Might be possible with multiple conversions, but not sure how well that would work.

In general, there have been talks of supporting other TPU devices like Intel NCS2, [Jetson Nano](https://github.com/blakeblackshear/frigate/pull/2548), etc. Not sure how this fits in with that, will be curious  to see what others think.

**Comment by andre-pt** [comment]
thanks for your reply.

Jetson Nano goes for about 400€ in europe, which is pretty steep.
Intel NCS2 seems to play well with OpenVINO too. Enabling OpenVINO would enable better performance on Intel CPUs as well.

Anyway, looking forward for feedback on this :)

**Comment by Maratyszcza** [comment]
@andre-pt Have you tried XNNPACK delegate for TFLite for quantized inference (IIUC, Frigate use quantized models)?

**Comment by andre-pt** [comment]
@Maratyszcza as i mentioned on the first post, my knowledge in the area is somehow limited and I haven't found the time to learn a lot yet :\

I assumed for some maintainer of this project, it would be easier to timebox some effort to try if openVINO would bring a lot of benefits or not. Specially after the effort in https://github.com/blakeblackshear/frigate/pull/2548 to have multiple ML engines for inference.

**Comment by Maratyszcza** [comment]
IIUC, this project already use TFLite. In this case, trying quantized XNNPACK inference requires just a few lines:

```c++
TfLiteXNNPackDelegateOptions delegate_options =
    TfLiteXNNPackDelegateOptionsDefault();
delegate_options.flags |= TFLITE_XNNPACK_DELEGATE_FLAG_QS8;
delegate_options.flags |= TFLITE_XNNPACK_DELEGATE_FLAG_QU8;
TfLiteDelegate* xnnpack_delegate =
    TfLiteXNNPackDelegateCreate(&delegate_options);
assert(interpreter->ModifyGraphWithDelegate(xnnpack_delegate) == kTfLiteOk);
```

On the other side, trying OpenVINO would require additional model conversion and dependency integration.

**Comment by andre-pt** [comment]
I did some more research and I think the ultimate change would be to migrate to https://onnxruntime.ai/
it would support openVINO for intel cpus, CUDA for nvidia and more!
The bad part is it doesn't support coral tpu acceleration
