### ISSUE TITLE
[Support]: Does not work when accessing via VPN

### ISSUE THREAD

**Issue by fgonza2** [blakeblackshear/frigate#3088]
### Describe the problem you are having

Frigate working great from LAN in docker.  For some reason when I connect remotely via VPN using an address on the same subnet, pool, etc I can’t access it, just throws a blank page, any ideas of what could be the problem?   Other containers running on the same IP are accessible in other ports like home assistant

maybensomeone run into thia

### Version

3

### Frigate config file

```yaml
default
```

### Relevant log output

```shell
Default
```

### FFprobe output from your camera

```shell
Default
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Many

**Comment by NickM-27** [comment]
Hi, we will need information to be able to help. 

At the very least will need docker compose file, also logs from frigate, whatever OS Docker Compose is running in, etc. will likely also help.

**Comment by fgonza2** [comment]
well...I found the problem, two issues.   First the MTU in my router/VPN had to be reduced to 1300. Second: safari disable "block pop-ups" which made me feel a little stupid ... :)
