### ISSUE TITLE
Invalid config for [ffmpeg]: [hwaccel_args] is an invalid option for [ffmpeg].

### ISSUE THREAD

**Issue by tuanha2000vn** [blakeblackshear/frigate#309]
Hi, I've follow the documentation to add ffmeg hardware acceleration for Intel NUC run Ubuntu 20

Added this to configuration.yaml
```
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

and I got this message on check config
```
Invalid config for [ffmpeg]: [hwaccel_args] is an invalid option for [ffmpeg]. Check: ffmpeg->ffmpeg->hwaccel_args. (See /config/configuration.yaml, line 68).
```

Did I missed something?

**Comment by blakeblackshear** [comment]
I think that message is from homeassistant. The config for frigate is a separate file entirely. How are you running frigate? Please post your docker run command or compose file and your full config file.

**Comment by tuanha2000vn** [comment]
Thank, my bad, need to read document twice :D
