### ISSUE TITLE
[Q] Does this have some kind of frontend?

### ISSUE THREAD

**Issue by MisterMelDev** [blakeblackshear/frigate#310]
Question in the title. Does Frigate have some kind of fancy web interface, which allows you to sort clips by, for example, object type? If there isn't, I might try to create my own. Is this something you would be interested in?

Thanks!

**Comment by blakeblackshear** [comment]
It is designed to be used with homeassistant as a frontend. You can certainly build your own, but I would wait until the next version is available. I am adding several endpoints for fetching data. You can see a preview of how it will be integrated into homeassistant here: https://youtu.be/fXQZeI1-hms

Note that I never intend to add any kind of authentication directly to frigate's api. It would need to sit behind some kind of reverse proxy that handles authentication.

**Comment by MisterMelDev** [comment]
Thanks for the info!
