### ISSUE TITLE
Detect specific number of the same object

### ISSUE THREAD

**Issue by janstadt** [blakeblackshear/frigate#3101]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to detect a specific number of objects (like 5 people) before triggering a notification so i can make a notification for when a specific number of kids are found at the bus stop. (seems weird, but it would be nice to notify my daughter that a quorum of people are at the bus stop so she can get a move on :-) ).

**Describe the solution you'd like**
Maybe an integer that could be passed to an object type for detecting specific numbers. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by NickM-27** [comment]
This is already supported in home assistant and MQTT, where are you expecting to see it / use it?

**Comment by janstadt** [comment]
I wasnt aware. Do you have an example trigger? I am unsure how to trigger an automation when x number of objects are detected within a specific area.

**Comment by NickM-27** [comment]
Do you have the frigate integration? There's sensors added to every camera and every zone with each sensor. 

Then just setup the automation using that sensor and the count you want

**Comment by janstadt** [comment]
Yes i have the frigate integration. Using the blueprint above.

**Comment by NickM-27** [comment]
It won't be possible with the blueprint unless you edit it manually, otherwise you'll need to use the sensors themselves to make a notification

**Comment by janstadt** [comment]
Well all be damned. I was looking at the binary sensor. Debugged the regular object sensor and you're right @NickM-27. This'll make it much easier! Thanks again.
