### ISSUE TITLE
[Support]: Demo is down:

### ISSUE THREAD

**Issue by jlpoolen** [blakeblackshear/frigate#3102]
### Describe the problem you are having

The DEMO link on the web site takes you to https://demo.frigate.video/ and results in:

     404 page not found

### Version

NA

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Windows

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

NA

### Any other information that may be helpful

Using Firefox on Windows.

Tried some other way to reach you to alert you to this, but finally resorted to logging this issue.

**Comment by blakeblackshear** [comment]
I made some changes and now it should work at http://demo.frigate.video

**Comment by jlpoolen** [comment]
Confirmed.  Thank you.
