### ISSUE TITLE
Copy captured clips away from the computer

### ISSUE THREAD

**Issue by fireport** [blakeblackshear/frigate#3105]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

For security reasons, I would copy captured clips away from the computer. I'm thinking, for example, send copies to a cloud (dropbox,nextcloud, google drive) or sending them by email. The last feature is already supported by blue iris.

Using the Companion app or telegram to send links to clips does not cover the risk of computer being stolen and thus losing all videos.

**Comment by NickM-27** [comment]
There's already a way to do this using the UI or API to download. This could be automated using HA or a generic script with the API.

**Comment by fireport** [comment]
SMTP cannot send video attachments and, for me, it is better to push video out instead of pulling video from outside downloading it. Blue iris is capable to send email with video
