### ISSUE TITLE
Official Nodered Node (Feature Request)

### ISSUE THREAD

**Issue by MrSiO** [blakeblackshear/frigate#3113]
**Describe what you are trying to accomplish and why in non technical terms**
I wish there were an official Nodered Node that we could add to the palette to be able to easily add Frigates events to our nodered flow.

**Describe the solution you'd like**
A downloadable node for frigate that include all the possible event types, detection, snapshots, camera, stationary objects.. etc.

**Describe alternatives you've considered**
Actually, I'm using the MQTT node, and manually filtering all possible values from the JSON. 
We currently need to search the payload for all the options and filter them out.
Eg:  Is object stationnary?  Is message type NEW?    Is object a CAR?   Is it overs 0.70 certainty?  etc... etc.. etc..

**Additional context**
Thx for considering!

**Comment by NickM-27** [comment]
I think someone who is familiar with NODERed would need to work on this, I have done some digging but haven't been able to find any examples for such a thing so it will be difficult to get this going

**Comment by MrSiO** [comment]
I'm progressing in my research.
I pretty much figured out all the MQTT info and how to filter them properly.

Will post what I tested as soon as I can.

**Comment by ozett** [comment]
not much issues with node-red here.
but one some example https://github.com/blakeblackshear/frigate/issues/1560#issuecomment-902359952
