### ISSUE TITLE
[Q/FR] Extend ffmpeg "timeout"

### ISSUE THREAD

**Issue by scottgrobinson** [blakeblackshear/frigate#312]
By default, ffmpeg times out after not receiving frames for 5 seconds.

I'm trying to "fine tune" my setup, so I download clips from my NAS (Synology) then use ffmpeg to convert to .264 (ffmpeg -i XXX.mpg XXX.264) then use live555 to play this back as an RTSP stream so I can tweak the values repeatedly from the camera recording.

frigate/ffmpeg will play this stream (live555) without issue, but only if I change the default timeout to something a little longer, roughly 15 - 20 seconds.

Is it worth adding this as a configurable parameter? I don't mind putting a PR in but wanted to get thoughts first... I guess 5 seconds is probably sufficient for 99% of people...

**Comment by blakeblackshear** [comment]
15-20 seconds seems like a reasonable default and I can make it configurable. My development branch has drifted significantly from the code base in the current version, so I would want to implement this change on top of that. If you want it before that version is available, I would just fork and run a custom build.

**Comment by scottgrobinson** [comment]
Thanks! I've already forked for a few changes like this, just wantd to get a "ticket in" and check.

Thank you.

**Comment by msekoranja** [comment]
Note: I have similar problem with Dahua VTO (doorbell) camera, others Dahuas work fine. It needs 10-15 seconds for the initial frames.

Hint: ffmpeg needs "disable audio" (-an) flag for VTO since mmpeg cannot handle its audio encode format; easy add this in frigate config 👍

**Comment by blakeblackshear** [comment]
I already bumped this up to 20 seconds for the upcoming release.

**Comment by evenex** [comment]
> I already bumped this up to 20 seconds for the upcoming release.

When will this update hit the HassOS Addon?
