### ISSUE TITLE
[Camera Support]: RTSP stream from IP camera can't load

### ISSUE THREAD

**Issue by matt-winfield** [blakeblackshear/frigate#3125]
### Describe the problem you are having

I'm trying to load an IP camera via RTSP stream, ffmpeg seems to be failing to parse the data being sent (see ffprobe response). The stream loads fine in VLC. I've tried forcing UDP and TCP using `-rtsp_transport` flag with ffprobe, as I have seen some discussions about this in other threads, but this has not made a difference.

The RTSP stream must have the correct data, as it can be loaded with VLC. How can I get around this issue?

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: 192.168.X.X
  user: mqtt-user
  password: XXXXXXX

cameras:
  main_camera:
    ffmpeg:
      inputs:
        - path: rtsp://username:XXXXXX@192.168.X.X
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
```

### Relevant log output

```shell
[2022-04-19 21:37:43] watchdog.main_camera           ERROR   : Ffmpeg process crashed unexpectedly for main_camera.
[2022-04-19 21:37:43] watchdog.main_camera           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-04-19 21:37:43] ffmpeg.main_camera.detect      ERROR   : rtsp://username:XXXXXX@192.168.X.X: Invalid data found when processing input
[2022-04-19 21:37:43] frigate.video                  ERROR   : main_camera: Unable to read frames from ffmpeg process.
[2022-04-19 21:37:43] frigate.video                  ERROR   : main_camera: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
ffprobe version 2022-04-18-git-d5687236ab-full_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 26.100 / 59. 26.100
  libavformat    59. 22.100 / 59. 22.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 33.100 /  8. 33.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
rtsp://username:XXXXX@192.168.X.X: Invalid data found when processing input
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Veroyi EC30_T11 (Cheap IP Camera)

**Comment by NickM-27** [comment]
how complex / long is your password? ffmpeg seems to have trouble at times with passwords that are long or contain special characters. I would temporarily try a really simple password just to rule out this possibility.

**Comment by matt-winfield** [comment]
> how complex / long is your password? ffmpeg seems to have trouble at times with passwords that are long or contain special characters. I would temporarily try a really simple password just to rule out this possibility.

I tried it with `123456` (the shortest length my camera will allow), and I still got the same issue. My regular password isn't much longer anyway or contain special characters, so I don't think this is related.

**Comment by NickM-27** [comment]
When viewing in VLC, can you put a screenshot of the `codec information` menu in settings for this camera?

**Comment by matt-winfield** [comment]
> When viewing in VLC, can you put a screenshot of the `codec information` menu in settings for this camera?

![image](https://user-images.githubusercontent.com/15931560/164103932-ab7dc529-8543-4ddf-a184-44f968f26916.png)

**Comment by marcoLPT** [comment]
: rtsp://username:XXXXXX@192.168.X.X is not a Rtsp stream.. look the documentation of the camera..(missing rtsp://username:XXXXXX@192.168.X.X/Stream ..)
