### ISSUE TITLE
Enhancements between home assistant and frigate, more dynamic recording

### ISSUE THREAD

**Issue by gurkburk76** [blakeblackshear/frigate#3129]
Not sure if this is for "Config Support Request" or in this section, i'm sure some gentle sol will move it if it's in wrong section.

**Describe what you are trying to accomplish and why in non technical terms**
I ususally do 24h recording and record clips on events for 11 cameras, i also use home asssitant to tie most of my stuff together,

If frigate and home assistant could extend the way they "talk" to one another i might not have to do 24h recording on all the cameras all the time.
As an example if i'm at home there is no need to record on my inside cameras 24/7 but clips is ok, if i'm not at home do both or whatever you choose.

Home assistant does "know" that i'm not at home if my alarm system is engaged, or phone outside of area etc etc.

**Describe the solution you'd like**
Some sort of way to define this behaviour on a per camera basis in the config that it should only do 24/7 recording and/or just clips if a certain condition is true or false in HA.

Is this at all feasible or i'm i asking too much?

**Comment by NickM-27** [comment]
There's already a home assistant integration for frigate which can control recording, detection, snapshots, etc. for each camera

https://github.com/blakeblackshear/frigate-hass-integration

**Comment by NickM-27** [comment]
I've been thinking about this and a more feasible way to go about it as opposed to toggling 24/7 recording vs events, would be to allow the retention mode (all, motion, active_objects) to be toggled via MQTT. So recordings could be limited to `active_objects` when only clips are wanted and `all` when 24/7 is wanted.

Still not 100% on how clean this would be, but definitely more feasible.
