### ISSUE TITLE
[Config Support]: Birdseye now required?

### ISSUE THREAD

**Issue by chelming** [blakeblackshear/frigate#3130]
### Describe the problem you are having

My config has `birdseye:` in it with no config params because they're all listed as optional with defaults that I was willing to accept. 

I'm not sure _when_ the problem started, but now I get an error if I don't have at least one parameter for birdseye listed. It seems adding `enabled: True` causes it to work (though that's the default for enabled 🤷‍♀️).

### Version

0.10.1-83481AF

### Frigate config file

```yaml
birdseye:
```

### Relevant log output

```shell
1 validation error for FrigateConfig
birdseye
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
birdseye
  none is not an allowed value (type=type_error.none.not_allowed)
```

### Frigate stats

```json
{"backyard":{"camera_fps":5.0,"capture_pid":244,"detection_fps":6.6,"pid":237,"process_fps":5.0,"skipped_fps":0.0},"detection_fps":6.6,"detectors":{"coral":{"detection_start":1650649666.969583,"inference_speed":18.03,"pid":226}},"driveway":{"camera_fps":5.0,"capture_pid":246,"detection_fps":0.0,"pid":239,"process_fps":5.0,"skipped_fps":0.0},"porch":{"camera_fps":5.1,"capture_pid":240,"detection_fps":0.0,"pid":234,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":243.4,"mount_type":"tmpfs","total":268.4,"used":25.0},"/media/frigate/clips":{"free":1438713.7,"mount_type":"xfs","total":2999126.3,"used":1560412.6},"/media/frigate/recordings":{"free":1438713.7,"mount_type":"xfs","total":2999126.3,"used":1560412.6},"/tmp/cache":{"free":911.4,"mount_type":"tmpfs","total":1000.0,"used":88.6}},"temperatures":{},"uptime":225,"version":"0.10.1-83481af"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

**Comment by NickM-27** [comment]
If you define a top level config item like `birdseye` then it will need to have some of its properties set otherwise it isn't parsed correctly. It has been this way since I started using frigate with 0.9.4 so I can't comment on if it was like that before.

Regardless, if you are not customizing any properties then there is no reason to add `birdseye` to the config at all, as it is enabled by default and will work as expected.

**Comment by chelming** [comment]
oh snap. good call. I swear it had to be explicitly defined at one point.

thanks @NickM-27!
