### ISSUE TITLE
[Support]: HTTP API <start-timestamp> example

### ISSUE THREAD

**Issue by acardace** [blakeblackshear/frigate#3133]
### Describe the problem you are having

Hi,

I'm trying to use this API https://docs.frigate.video/integrations/api#get-vodcamerastartstart-timestampendend-timestampindexm3u8 but cannot get it to work as I don't understand the required format of the timestamp, can anyone help?

An example in the docs would be great.

### Version

0.10.1

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua

**Comment by blakeblackshear** [comment]
It's a unix timestamp. https://www.epochconverter.com/

**Comment by hesa2020** [comment]
Have you found solution? I am getting error 404
