### ISSUE TITLE
Event time filter

### ISSUE THREAD

**Issue by DrSpaldo** [blakeblackshear/frigate#3140]
Hello,

I would like to be able to have the date picker also have a time option. For example, I can just view events that are overnight as there are so many during the day.

**Comment by dmkjr** [comment]
I concur.

**Comment by Homas** [comment]
I second that. Much less events are during nights/early morning as well as most criminal activities happens around the same time frame. It will be much easier to track that.

**Comment by NickM-27** [comment]
This has been implemented for 0.13 👍

**Comment by DrSpaldo** [comment]
> This has been implemented for 0.13 👍

Firstly, thanks for adding this option!  

Can I just add feedback that the time selector isn't super functional in 0.13. It doesn't let you select say 10pm - 6am . You need to do two different selections as you can only do after midnight or before midnight.

**Comment by NickM-27** [comment]
@sinamics is that a bug or expected for the current implementation?

(Haven't tested myself)

**Comment by DrSpaldo** [comment]
This is the selector:

![2023-09-13_8-21-43](https://github.com/blakeblackshear/frigate/assets/8526509/5c6eef29-5a13-4b7f-b676-dc454672038a)

When you select the initial start time, it only lets you select an item greater than that time. So you cannot select 2200 to 0600. Only 2200 to 2300 then you would need a second selection of 0000 to 0600

**Comment by Homas** [comment]
It is just a time selector for specific date range (on the screenshot above). It is not the same what was requested. 
E.g. I need to finds events which happened from 1am till 7am over the last 4 weeks (I keep detections for 90 days).

**Comment by NickM-27** [comment]
> This is the selector:
> 
> ![2023-09-13_8-21-43](https://user-images.githubusercontent.com/8526509/267481083-5c6eef29-5a13-4b7f-b676-dc454672038a.png)
> 
> When you select the initial start time, it only lets you select an item greater than that time. So you cannot select 2200 to 0600. Only 2200 to 2300 then you would need a second selection of 0000 to 0600

that's not what I am seeing, it worked just fine to choose overnight

![Screen Shot 2023-09-12 at 17 20 58 PM](https://github.com/blakeblackshear/frigate/assets/14866235/0dbda79f-fa99-4bee-9c33-de0e9e0b88ec)

**Comment by DrSpaldo** [comment]
> > This is the selector:
> > ![2023-09-13_8-21-43](https://user-images.githubusercontent.com/8526509/267481083-5c6eef29-5a13-4b7f-b676-dc454672038a.png)
> > When you select the initial start time, it only lets you select an item greater than that time. So you cannot select 2200 to 0600. Only 2200 to 2300 then you would need a second selection of 0000 to 0600
> 
> that's not what I am seeing, it worked just fine to choose overnight
> 
> ![Screen Shot 2023-09-12 at 17 20 58 PM](https://user-images.githubusercontent.com/14866235/267489497-0dbda79f-fa99-4bee-9c33-de0e9e0b88ec.png)

Yep, it works for one night, overnight. Not show all the events for 10pm - 6am for more than one day

**Comment by NickM-27** [comment]
I don't think it will be too much to adjust it to behave that way, I do agree that that is likely how more people will want to use it.

**Comment by sinamics** [comment]
@NickM-27, this behavior is by design, not a bug. I may have misunderstood the original requirements. 
However, modifying it to support time-from to time-to selection for each day should be doable.

**Comment by DrSpaldo** [comment]
This one still isn't working for me, I am not sure if I need another version (rather than beta 2)?  I am just getting the error "ending must occur on final day!"

**Comment by NickM-27** [comment]
This was merged yesterday, this is not in beta 2

**Comment by DrSpaldo** [comment]
> This was merged yesterday, this is not in beta 2

Sorry, missed that... I will wait :)

**Comment by NickM-27** [comment]
You can always run the dev version

**Comment by DrSpaldo** [comment]
> You can always run the dev version

I know, but I am hopeless at finding the builds. I have tried 

ghcr.io/blakeblackshear/frigate:dev-1aba8c1
ghcr.io/blakeblackshear/frigate:dev-7c43fcd

Both give me errors

**Comment by NickM-27** [comment]
where did you put those in your unraid config? it should work fine in the `respository` field: ghcr.io/blakeblackshear/frigate:dev-d11c1a2

**Comment by NickM-27** [comment]
the latest builds are listed here https://github.com/blakeblackshear/frigate/pkgs/container/frigate

**Comment by DrSpaldo** [comment]
> the latest builds are listed here https://github.com/blakeblackshear/frigate/pkgs/container/frigate which is linked directly in the sidebar

Great, thats a perfect link for me to save!

> where did you put those in your unraid config? it should work fine in the `respository` field: `ghcr.io/blakeblackshear/frigate:dev-d11c1a2`

Good memory, I have switched over to Proxmox with Portainer for now, Unraid kept giving me problems with the server crashing. That build appears to be working, thanks again

**Comment by DrSpaldo** [comment]
PS. Search works well, that will save so much time doing a multiple day (over night) review
