### ISSUE TITLE
[Support]: Can you change the object detection region (green box) (QUESTION)

### ISSUE THREAD

**Issue by LaurenceGough** [blakeblackshear/frigate#3148]
### Describe the problem you are having

Hello,

More of a question.

I was just wondering if it was possible to reduce the size of the object detection region (green box)? I have various masks setup both in motion detection and people object masks but it seems when motion is triggered in a non masked area the green object detection region box takes up almost the whole camera feed size causing my poor little Raspberry Pi 4 to try to detect people (or objects that look slightly like a person) from all of the masked off areas.

I had a look through the config files and all I could see was an option to reduce max size of a person object but this isn't quite what I'm after I believe.

I know a Coral TPU is recommended and I wish I could buy one, been on backorder for months!

Thanks,

Laurence

### Version

0.11.0-CBF26E0

### Frigate config file

```yaml
N/A for this question
```

### Relevant log output

```shell
N/A for this question
```

### FFprobe output from your camera

```shell
N/A for this question
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A for this question

**Comment by LaurenceGough** [comment]
> > It sounds like it will still do object detection but then be marked as a false positive - so I guess it's just working as intended.
> 
> Yes, the object mask is considered much higher in the pipeline after the detection has run.
> 
> > I try to avoid asking these questions as I do fully understand this was made with a TPU accelerator in mind, it's just I am trying to fine tune my setup until I get one. Perhaps others are in the same boat. Hopefully you guys don't mind me asking these silly questions :).
> 
> Definitely understand it is difficult not being able to get ahold of a coral. Any suggestion I can think of would lead to frigate working sub-optimally.
> 
> 1. Detection could be automated more to only run when needed (basically to reduce Pi CPU usage when less important, but still will have high usage when detecting).
> 2. Make sure that the `width` and `height` matches the dimensions of the cameras feed. This will keep ffmpeg from having to resize the stream, potentially reducing some CPU usage.
> 3. Could try reducing the fps which would likely cause some issues with tracking but overall reducing CPU usage / those high latency detection times during heavy load.

Thanks so much again Nick.

I am currently running 5fps on detection on 2x cams - but I wasn't sure if reducing that or increasing that would help. I might need to do some further testing. I wasn't sure if giving Frigate more frames to decide on objects would help or cause it to start to lock up. The issue I face most of all is just red motion boxes and no object detection starting even after quite a few seconds, this can happen for a long time sometimes even with just one person on one camera, I'm not sure why this is happening. I did reduce the minimum score required on one camera for the object to initiate tracking but I don't think this has helped (I'm sure I'm using it wrong!). I did just notice that the debug FPS is fluctuating up and down by a few FPS on that same camera so perhaps I have another issue. I think this issue impacts one camera more than the other so it most likely will be related.

Yeah, I have checked the width and height - all good but thank you for that.

Overclocking the Pi to 2GHz for sure helped big time, it was running slow before due to a config issue from a previous HAOS install.

**Comment by LaurenceGough** [comment]
> Kind of a lot to unpack. The reason the detection fps fluctuates is likely that the pi doesn't have enough performance to keep up with 5 fps while tracking an object. Limiting it to a lower fps will help in this regard but moving objects will not be tracked as well / could be lost.

Oh I forgot to mention, this camera has lower activity and the fluctuating FPS on the debug view is even with no motion detection/object detection happening! :o

**Comment by blakeblackshear** [comment]
The best way to prevent object detection for smaller objects further away would be to increase the `contour_area` and/or reduce the `frame_height` in the motion settings. That will cut off object detection upstream.
