### ISSUE TITLE
[Feature Request] Package detection

### ISSUE THREAD

**Issue by Joseph-DiGiovanni** [blakeblackshear/frigate#3156]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to detect packages so that I can be notified of mail delivery

**Describe the solution you'd like**
Add package object detection, like cardboard box or bubble envelopes

**Describe alternatives you've considered**
There are none that I am aware of

**Additional context**
I understand since there are so many different types of boxes and they're not a specific shape it would be difficult to get reliable detection but the option would be nice. False positives could be common but I would just mask everything but my front doorstep

**Comment by NickM-27** [comment]
This is coming as part of [Frigate +](https://frigate.video/plus/). Package is already a supported label for the initial models.
