### ISSUE TITLE
Summary video clip

### ISSUE THREAD

**Issue by poldim** [blakeblackshear/frigate#3174]
**Describe what you are trying to accomplish and why in non technical terms**
Summary video or gif that gives you an overview of the main motion events on a camera

**Describe the solution you'd like**
This tech comes up on Reddit every now and then showing a video of many motion events on a single camera feed with the time that they occured hovering over the action: https://reddit.com/r/interestingasfuck/comments/ufavbx/security_camera_superimposes_all_the_footage_from/
This user appears to have coded something in python to do it: https://github.com/Askill/Video-Summary

Would be very nice if you could have a daytime and a night time summary or gif auto generated for a camera feed. This way you could have an HA tab to see yesterday's daytime and nighttime summaries.

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/54
