### ISSUE TITLE
[Support]: Events last too long

### ISSUE THREAD

**Issue by nau53** [blakeblackshear/frigate#3186]
### Describe the problem you are having

Hi

Sometimes I'm experiencing strange behaviour of Frigate. It can detect a person however event could last up to 5 hours. For example last one started at 21:09:48 and ended at 02:15:46. It wasn't false event it was a person (me to be precise i've been on yard for about 2-3 minutes only). 

Any workaround on this
![snapshot](https://user-images.githubusercontent.com/64654882/166620282-1a27a7c1-466f-4f2c-bb9b-262c78c67639.jpeg)
?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
south:
    ffmpeg:
      inputs:
        - path: rtsp://xxxx
          roles:
            - detect
    motion:
      mask:
        - 51,0,453,0,502,0,536,0,550,0,640,0,640,266,487,83,79,43
        - 616,71,503,252,512,256,477,142,489,46
    detect:
      width: 640
      height: 360
      fps: 18
    record:
      enabled: false
    rtmp:
      enabled: False
```

### Relevant log output

```shell
[2022-05-04 09:29:29] ws4py INFO : Using epoll
[2022-05-04 09:29:40] ws4py INFO : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:34780]
[2022-05-04 09:29:44] ws4py INFO : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:34780]
[2022-05-04 09:29:44] ws4py INFO : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35654]
[2022-05-04 09:30:09] ws4py INFO : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35654]
[2022-05-04 09:30:09] ws4py INFO : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35770]
[2022-05-04 09:30:11] ws4py INFO : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35770]
[2022-05-04 09:30:11] ws4py INFO : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35792]
[2022-05-04 09:31:39] ws4py INFO : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35792]
```

### FFprobe output from your camera

```shell
x
```

### Operating system

UNRAID

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
Seems to be a case where it kept detecting person after and marked it as stationary. The person is quite small in the snapshot so I can see why that would happen.

could set min_area so it doesn't try to track people that small / far away

max_frames can be set but that will disable stationary tracking for person

**Comment by nau53** [comment]
Thanks for answering. So if I just want to disable stationary tracking for person that would be enough?

      stationary:
        max_frames:
          objects:
            person: 10

**Comment by NickM-27** [comment]
> Thanks for answering. So if I just want to disable stationary tracking for person that would be enough?
> 
> 
> 
>       stationary:
> 
>         max_frames:
> 
>           objects:
> 
>             person: 10

Yes, if that's a good solution for your use case 👍

**Comment by bigbangus** [comment]
I have the same issue. My event can last for hours. It shows up in the frigate GUI and it breaks my Nodered iOS notifications which filter for new or updates for the same event ID every 30seconds or so. See log attached and an example of a long event where people leave the frame and it continues.

This only started happening after frigate 0.9 or so when the whole stationary deal came up.

[config_anon.yml.txt](https://github.com/blakeblackshear/frigate/files/8619956/config_anon.yml.txt)

![image](https://user-images.githubusercontent.com/91270101/166677305-321d1526-e4d6-4273-8285-e3f23c1abf37.png)

Persons @ 11:51AM
![image](https://user-images.githubusercontent.com/91270101/166677973-930b2ce0-1f33-4bcd-a883-b3a158f34274.png)

Persons @ 12:58AM
![image](https://user-images.githubusercontent.com/91270101/166678066-f9ff3169-3049-4698-8986-5e0e80e897b3.png)

And nothing in between all recorded on the same event clip!

**Comment by NickM-27** [comment]
> I have the same issue. My event can last for hours. It shows up in the frigate GUI and it breaks my Nodered iOS notifications which filter for new or updates for the same event ID every 30seconds or so. See log attached and an example of a long event where people leave the frame and it continues.
> 
> 
> 
> This only started happening after frigate 0.9 or so when the whole stationary deal came up.
> 
> 
> 
> [config_anon.yml.txt](https://github.com/blakeblackshear/frigate/files/8619956/config_anon.yml.txt)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/91270101/166677305-321d1526-e4d6-4273-8285-e3f23c1abf37.png)
> 
> 
> 
> Persons @ 11:51AM
> 
> ![image](https://user-images.githubusercontent.com/91270101/166677973-930b2ce0-1f33-4bcd-a883-b3a158f34274.png)
> 
> 
> 
> No persons for 1 HOUR!
> 
> 
> 
> Persons @ 12:58AM
> 
> ![image](https://user-images.githubusercontent.com/91270101/166678066-f9ff3169-3049-4698-8986-5e0e80e897b3.png)
> 
> 

Likely the same case as above but difficult to say for sure without seeing the debug view. While this is happening can always check the debug view to see what frigate sees.

**Comment by NickM-27** [comment]
It also looks like in your case you have a lot of motion masks, without being able to see what they look like, they may be too big causing objects to get sick if they walk through them and are totally obstructed

**Comment by bigbangus** [comment]
so yeah, I've used motion masks to remove areas outside of the zones I care about to avoid triggering motion detection in places I don't really care about.... not sure if this is good practice?

![image](https://user-images.githubusercontent.com/91270101/166680721-90caa029-a9c5-486b-b1e6-9044413f95dc.png)

**Comment by NickM-27** [comment]
> so yeah, I've used motion masks to remove areas outside of the zones I care about to avoid triggering motion detection in places I don't really care about.... not sure if this is good practice?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/91270101/166680721-90caa029-a9c5-486b-b1e6-9044413f95dc.png)
> 
> 

That is strictly advised against in the docs: https://docs.frigate.video/configuration/masks

100% would expect the behavior you described as if someone walks away frigate will not update (it ignores motion) and is forced to assume it is still there. 

Zones should be used to restrict events, motion masks are to avoid non-object related motion (trees, Timestamps, clouds, etc)

**Comment by bigbangus** [comment]
> That is strictly advised against in the docs: https://docs.frigate.video/configuration/masks
> 
> 100% would expect the behavior you described as if someone walks away frigate will not update (it ignores motion in the mask) and is forced to assume it is still there.
> 
> Zones should be used to restrict events, motion masks are to avoid non-object related motion (trees, Timestamps, clouds, etc)

I'm reckless... OK I will test a config with motion masks applied only to trees. I feel like I added all these because I was getting false positives from outside of the zone....

**Comment by NickM-27** [comment]
> I feel like I added all these because I was getting false positives from outside of the zone....

Motion masks shouldn't be used to block out false positives either. There's separate tools for that. 

At this point if you get false positives I'd recommend creating your own issue as this is different than OPs issue which should be sorted out now 👍

**Comment by bigbangus** [comment]
agreed thank you
