### ISSUE TITLE
[Q] GPU docker tag

### ISSUE THREAD

**Issue by mihaiblaga89** [blakeblackshear/frigate#320]
What's the latest option to run frigate with GPU support? I see the [docs](https://github.com/blakeblackshear/frigate/blob/master/docs/nvdec.md) referencing a DockerHub tag that is not available anymore (stable-amd64nvidia)

Thanks

**Comment by blakeblackshear** [comment]
You have to build your own. That build only enables GPU decoding for ffmpeg, not for tensorflow.

**Comment by mihaiblaga89** [comment]
Thanks. Any plans to add the switch from TF to Cuda anytime soon? Saw some PRs and discussions about some branch but couldn't find it, so I don't know if that is still in the works or not

**Comment by blakeblackshear** [comment]
There is a closed PR with some recent comments. TensorRT doesn't support python 3.8, so no plans to incorporate it until that changes.

**Comment by jaburges** [comment]
I'm at a loss on my research, so wondered if you all had an input.
If i'm using a 1080 Nvidia GPU for hardware acceleration it surely makes sense to use that for the object detection.
BUT
The Dual Coral TPU M2 only uses 2W - so i'm wondering - does it make sense to use the coral for object detection and the GPU for hardware acceleration? Are the gains of hardware acceleration for 6 cameras worth it (if i'm using main and sub streams from Amcrest cameras?) 
Reason I ask is I have 2 nvme slots, and 1 PCI-e in my Unraid box, so trying to figure out the right way to go - appreciate any insight you all might have
