### ISSUE TITLE
Bad motion detection

### ISSUE THREAD

**Issue by MichalDoom** [blakeblackshear/frigate#3203]
Hello
i have problem with bad motion detection of person object.
When sun rise going up and shine through window to inside garage,motion detection start false detect person.
Can You help me what tune in config?
I tried play with threshold value but unsucessfull.

## Version of the custom_component
frigate v 2.2.2
NVR beta 0.10.9 ver 3.8

## Configuration

 cam_garaz:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.3.254:554/live3.sdp
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 1280
      height: 800
      fps: 5
    record:
      enabled: false
      retain:
          days: 0
          mode: motion
      events:
        retain:
          default: 2
          mode: active_objects
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.6
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      retain:
        default: 5
    motion:
      threshold: 40

![Screenshot_2022-05-10-07-49-34-069_io homeassistant companion android](https://user-images.githubusercontent.com/95631905/167579524-43c3f776-ffdc-4dca-b145-9818ab709afd.jpg)

Add your logs here.

```

## Describe the bug
A clear and concise description of what the bug is.


## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

```text

Add your logs here.

```

**Comment by blakeblackshear** [comment]
I would try using the min_area filter. I don't think a person could be that small.
