### ISSUE TITLE
Way to see the exact real timestamp when viewing recordings

### ISSUE THREAD

**Issue by BBaoVanC** [blakeblackshear/frigate#3205]
**Describe what you are trying to accomplish and why in non technical terms**

I would like the actual timestamp to be shown when watching 24/7 recordings from my camera.

**Describe the solution you'd like**

Preferably some widget maybe in the top left of the video player that shows the timestamp. Also, if Frigate doesn't already have a way of knowing what real life timestamp each recording is from, then it needs a way to do that.

**Describe alternatives you've considered**

Another way could be to insert gaps into the recording so the progress bar matches up, although I think that would be clunky.

**Additional context**

My main usecase is that when I restart Frigate, or it has been offline for some amount of time, then there is no media recorded during that time. However, that means that any recording from after that point in time has the wrong time when looking at the video progress bar.

For example, if my server is offline for 5 minutes starting 36 minutes into the hour, if I look at the recording at 37 minutes, it's actually showing the recording from 41 minutes.

Additionally, people who have their config set to record only on motion have no way of knowing exactly what real life date and time the motion they're watching happened at.

This feature would also mean that you can reliably give exact dates and times that events happened at, even if they weren't marked as events.

**Comment by NickM-27** [comment]
I can see how this would be confusing, but to be clear frigate already supports adding a timestamp to the video feed / recordings so that would take care of part of this

**Comment by BBaoVanC** [comment]
> I can see how this would be confusing, but to be clear frigate already supports adding a timestamp to the video feed / recordings so that would take care of part of this

I'd like to try this, how do I do this? I didn't see it in the docs.

**Comment by NickM-27** [comment]
It is [here](https://docs.frigate.video/configuration/index) in the full config

![image](https://user-images.githubusercontent.com/14866235/167748446-300cbe8d-e992-479d-8d52-eb2589d74c0c.jpeg)

**Comment by blakeblackshear** [comment]
This doesn't add a timestamp to recordings as that would require reencoding. 

The changes I am currently working on will make it possible to have a progress bar that reflects the actual time when viewing recordings. This is coming in a future release and will not only show the actual time in the progress bar, but will also overlay motion levels and object counts so you can quickly jump to the footage you want to watch.

**Comment by NickM-27** [comment]
> This doesn't add a timestamp to recordings as that would require reencoding. 

Ah I see my bad, just the live view then.
