### ISSUE TITLE
Same score as described in events as in the clip rectangle

### ISSUE THREAD

**Issue by hmakmur** [blakeblackshear/frigate#3210]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to see the same score as described in events as in the clip rectangle shows. Current version: 0.10.1-83481AF

**Describe the solution you'd like**
 same key score as described in events as the clip rectangle shows.

**Describe alternatives you've considered**
Not sure why they are different. Should they be?

**Additional context**
see attached
![Screen Shot 2022-05-12 at 3 18 01 PM](https://user-images.githubusercontent.com/32586402/168153068-372e14e4-78c0-44d6-8bcf-c09ba3b0841e.jpg)

**Comment by hmakmur** [comment]
I am just confused. I expected the event score to be the same as what is written in the clip. I requested this because I was totally surprised at the discrepancy of the numbers. logically, shouldn't computed score' be displayed for both?

**Comment by NickM-27** [comment]
> I am just confused. I expected the event score to be the same as what is written in the clip. I requested this because I was totally surprised at the discrepancy of the numbers. logically, shouldn't computed score' be displayed for both?

No, again as the docs outline how the score is calculated, the snapshot for the event is the score at that exact moment meanwhile the score in the events page is the score as calculated when the event ends.
