### ISSUE TITLE
[FR] Enable num_threads parameter when creating tflite.Interpreter

### ISSUE THREAD

**Issue by msekoranja** [blakeblackshear/frigate#322]
Interpreter constructor supports num_threads parameter. This might not be beneficial for TPU, however on bare Raspberry PI 4 this helps a lot (e.g. using 3 threads, leaving one free, I can bring down inference time from 180ms down to ~60ms).

Looks like a nice FR.

**Comment by RealKanashii** [comment]
I have Frigate in docker inside my server with Ryzen 3700x, it will be a nice feature to improve performance with threads and limit the docker as needed.

**Comment by blakeblackshear** [comment]
What happens if you add additional CPU detectors? This may result in even better performance. https://github.com/blakeblackshear/frigate#detectors
