### ISSUE TITLE
[Support]: 0.11.0-beta2 - Migration took 5-6 Minutes (No Bug, Just to inform others)

### ISSUE THREAD

**Issue by ozett** [blakeblackshear/frigate#3224]
### Describe the problem you are having

i pulled the new beta DEBUG 0.11.0-D2C3CDC and used my old config from 10.x.
All went well, everything good.

just to inform others. it took 5-6 Minutes for migration .

on an old intel-i5 /ubuntu / docker / pci-e coral

looking for the next beta, alway a pleasure to see this growing!

new events-ui looks great!

### Version

DEBUG 0.11.0-D2C3CDC

**Comment by NickM-27** [comment]
As this isn't an issue, it would be better served as a discussion

**Comment by ozett** [comment]
hmmm, ok. sorry...
normally i look up unusual behevior in the issues here.
i seldom  go to the discussion.  i thought i prevent false bug-Assumption.

i dont wanted to fill up the issues, i will do better next time.
anyway: great new UI, my install runs fine now for the first/last 5 minutes, 
had no issue with that new version, GREAT! thanx.

**Comment by NickM-27** [comment]
Another good place might be the discussion for the release itself [here](https://github.com/blakeblackshear/frigate/discussions/3221)

But yeah in general it's good to keep the issues trimmed down 👍
