### ISSUE TITLE
Clips name and time after event

### ISSUE THREAD

**Issue by farnots** [blakeblackshear/frigate#323]
Hi, 

I would like to know if it's possible to rename clips name with other filename format that the epoch time ? Also we can pre-capture clips but is it possible to have post-capture clips after even to ensure we have the whole element ?

Thanks

**Comment by blakeblackshear** [comment]
There is already a request for post capture time. I think I know, but why do you want to rename the clips?

**Comment by farnots** [comment]
> There is already a request for post capture time. I think I know, but why do you want to rename the clips?

Thanks I saw this just after, sorry about that. 

I use the media player in HomeAssistant to show the clips. With clips named `front-1606742747.272411-0lbwng.mp4` it's hard at glance to find the date of the last clips captured by frigate. 

Would love to be able to set a custom format for exemple `%Y-%M-%d` to find them easily and even if possible each one in different folder by date of capture.

I'm trying to send the video with the picture captured by frigate to telegram but it's hard to determine the output file. (Maybe it's possible to add a `latest.mp4` at the root path as a copy of the latest video found in organized sub-directory)

I saw that you're working on better home-assistant integrations but I don't know if you plan to add some clips organisation available

**Comment by blakeblackshear** [comment]
The next version is specifically solving those exact problems. You won't need to worry about how the files are organized in the folder or saving snapshots for notifications. All of that will become easily available out of the box.

**Comment by farnots** [comment]
> The next version is specifically solving those exact problems. You won't need to worry about how the files are organized in the folder or saving snapshots for notifications. All of that will become easily available out of the box.

Awesome thanks a lot ♡ 
Do you have any ETA for this new version ?
