### ISSUE TITLE
[Support]: 0.11.0-2 Dashboard blank screen

### ISSUE THREAD

**Issue by teslamine** [blakeblackshear/frigate#3230]
### Describe the problem you are having

when I try to view the frigate dashboard app, its blank. I confirmed the cameras themselves work through homeassistant. 

![image](https://user-images.githubusercontent.com/51567215/169121369-9ef96caf-54fa-479f-bae9-cac97ff3d40b.png)

### Version

0.11.0-2

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

unifi

**Comment by NickM-27** [comment]
May be an issue [with the HASS addon](https://github.com/blakeblackshear/frigate-hass-addons)

**Comment by NickM-27** [comment]
Do you see any logs in the addon?

**Comment by teslamine** [comment]
Logs do not show any errors. All the devices and entities seem to be working fine. Its showing its actually detecting stuff. Only the dashboard is blank.

**Comment by blakeblackshear** [comment]
Do you see any errors in the browser console?

**Comment by teslamine** [comment]
GET http://homeassistant.local:8123/assets/index.555c98b0.js net::ERR_ABORTED 404 (Not Found)

**Comment by jaytea33** [comment]
Same problem here with same symptoms. Ingress doesn't work within HA but if I re-enable port 5000 it works with a browser. No logs to report and everything is working fine except the dashboard, although with about 10% higher CPU usage than beta1

**Comment by chrisborell** [comment]
> 

Same as you - increased CPU & No Ui

**Comment by kajmaj** [comment]
Same here. No errors in the log, all devices working but no UI within HA.

**Comment by Coolie1101** [comment]
Lost integration sensors as well after upgrading.
![image](https://user-images.githubusercontent.com/28989417/169260928-bef5de97-711a-4823-b2a8-7aa20466d3dc.png)

Reverting seems to solve the dashboard issue, but integration sensors still missing.

**Comment by LaurenceGough** [comment]
Sorry to report but the same issues here. Everything restarted. I was going mad this morning then I remembered I had auto add-on updates turned on and the Frigate add-on has been updated.

Hopefully the fix won't be too bad 🤞

**Comment by blakeblackshear** [comment]
I have fixed this and it will be in the next beta. It impacts all addons including the proxy addon.

**Comment by LaurenceGough** [comment]
> I have fixed this and it will be in the next beta. It impacts all addons including the proxy addon.

Thanks Blake I'm looking forward to trying it out. 👍

**Comment by LaurenceGough** [comment]
Ooof, crashing Home assistant many times now, taking down the rest of the smart home stuff with it (lighting etc :( )... Have to reboot the host Raspberry Pi to get access back. Lesson learnt, keep that auto update box firmly off. 

Now I cannot find any way to get back to previous 0.11 BETA 1 release :(

**Comment by NickM-27** [comment]
> Only error I see in logs is: Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa-beta:5000 ssl:default [Name does not resolve] Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate-fa-beta:5000/api/stats')

That looks like a home assistant integration log, not the addon log

**Comment by LaurenceGough** [comment]
> > Only error I see in logs is: Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa-beta:5000 ssl:default [Name does not resolve] Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate-fa-beta:5000/api/stats')
> 
> That looks like a home assistant integration log, not the addon log

It is indeed, the addon log was completely blank - nothing showing at all :(

**Comment by angrycatmeowmeow** [comment]
Still no UI today after upgrading to beta 3

**Comment by NickM-27** [comment]
Have y'all done ctrl + F5 / CMD + R to ensure there aren't any bad browser caches sitting around?

**Comment by angrycatmeowmeow** [comment]
Yeah I cleared all data/cookies for all HA sites and tried another browser I've never logged into HA on as well

**Comment by thundergreen** [comment]
Same here :(

**Comment by deviant77** [comment]
This is fixed in beta 4.

**Comment by thundergreen** [comment]
Fixed great thanks
