### ISSUE TITLE
[Support]: PLUS_API_KEY environment variable

### ISSUE THREAD

**Issue by giga89** [blakeblackshear/frigate#3234]
### Describe the problem you are having

Hello
how to add it on frigate.yaml configuration?
Thanks

### Version

0.11.beta2

### Frigate config file

```yaml
not pertinent
```

### Relevant log output

```shell
not pertinent
```

### FFprobe output from your camera

```shell
not pertinent
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

not pertinent

**Comment by NickM-27** [comment]
Setting the env variables [per the docs](https://docs.frigate.video/configuration/advanced/#environment_vars) should work

```yaml
environment_vars:
  PLUS_API_KEY: "jfkld;jsklsdjgksdjfksldjf;ljfsdkl;fsjdl;djsa"
```

**Comment by giga89** [comment]
Thank you so much :)

**Comment by blakeblackshear** [comment]
Does this work? It might not.

**Comment by giga89** [comment]
I have to try :)
