### ISSUE TITLE
Ability to toggle birdseye mode via MQTT

### ISSUE THREAD

**Issue by CrossEyeORG** [blakeblackshear/frigate#3244]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to see an option to have two or all `birdseye` modes enabled at the same time. The birdseye modes work great when individually enabled but there are times where I would just want to see all (continuous) cameras, others I want motion only view, and then just objects viewed.

This way, my automation and can display the appropriate birdseye view for my defined criteria. For instance, there are times I would like to just check all the camera streams at one time, like just wanting to see if my kids are in bed and maybe there is no motion or objects that would trigger the respective birdseye view. Then are are times where my automation would trigger and I would like to see all the cameras with motion, this is then opened on all my TVs and Alexa Show devices.

I realize in advance that there is cost to having all the birdseye modes enable at the same time but for some of us this is an none issue.

**Describe the solution you'd like**
Extend the `birdseye` mode(s) to accept a list and or have an option for `all`. Then ultimately expose these enabled modes through separate streams to be accessible externally (Home Assistant) to Frigate.

**Describe alternatives you've considered**
I have tried defining separate Dashboards within Home Assistant with just the selected cameras I wanted to see at a given moment. But this approach does not scale nor is it as dynamic as the birdseye view. I have not verified the stats on this, but I imagine having 15+ individual Frigate camera streams displayed on one Dashboard within Home Assistant is more resource intensive on an Alexa Show than just one birdseye stream.

**Additional context**
Frigate is awesome and once Frigate+ subscriptions are available, I will be signing up!

**Comment by NickM-27** [comment]
I think this makes sense, but the way you're describing it doesn't. Having an all mode doesn't make sense as it can't be both continuous and only-motion at the same time, for example. 

It sounds like what you're really asking for here is the ability to toggle the birdseye modes via mqtt (and by extension the HA integration), perhaps the UI at some point as well. 

Does that make sense? I think that should be doable barring any technical issues in the implementation.

**Comment by CrossEyeORG** [comment]
Hey @NickM-27, a toggle would also be a very nice addition but for my above request, I still like the idea of having all birdseye modes running at the same time.

For example, I personally love the objects birdseye mode more than the other modes but my wife simply likes the continuous mode more. For me, I have an additional monitor on my desk where the cameras are always being displayed and what catches my attention is when the object detector works and displays a stream. My wife on the other hand just wants to see at the cameras at once. So if the only option was a toggle, they every time she would open Home Assistant to view the cameras, it would toggle back to the continuous mode and I would be confused (but not surprised) why I am looking at all the cameras (small price to pay all be it). 

My idea was to have all the birdseye modes running at the same time. Then having a Home Assistant Dashboard with the labeled mode/expected view, and the Frigate extension configured to the respective birdseye mode.

For example,
 - https://www.somehomeassistant.com/cameras/continuous for the Frigate extension to be preconfigured with the continuous birdseye mode
 - https://www.somehomeassistant.com/cameras/motion for the Frigate extension to be preconfigured with the continuous birdseye mode
 - https://www.somehomeassistant.com/cameras/objects for the Frigate extension to be preconfigured with the objects birdseye mode

This way, both my wife and I can both get what we want, and my automation for a person and or vehicle approaching our house house gets displayed on our TVs and Alexa Shows. For the automation to work with Alexa Shows, I have to send a URL to an Alexa Skill that opens Silk to one of the above URL examples.

Having a toggle option be better than current approach and would require less resources on the docker host but also limits us to just one birdseye mode at a given moment.

**Comment by NickM-27** [comment]
> My idea was to have all the birdseye modes running at the same time. Then having a Home Assistant Dashboard with the labeled mode/expected view, and the Frigate extension configured to the respective birdseye mode.

Ah I see, so it's more like per-client birdseye settings. I don't see any reason why it couldn't be done, but that is a lot more complicated to implement and would be a considerable architecture change from the way birdseye is designed currently.

I've already started working on the version I described as it is fairly simple, so at least will be an improvement.

**Comment by CrossEyeORG** [comment]
Agreed the toggle will definitely be an improvement thank you for your help!

**Comment by setterlee** [comment]
I have a doub @NickM-27, if the toggle is implemented, the definition in the config.yml  for birdseye will be still there? if yes, will act like default setting in any restart of service? or the toggle value will be persisted to the database to use it on the start-up of the service?

**Comment by sberryman** [comment]
I didn't come across this so created a duplicate (#8207) and would really like an MQTT topic to control the mode per camera.
```
frigate/<camera_name>/birdseye/set
```

Based on a quick glace of the code and the `comms/dispatcher` the `SET` topic suffix is very structured and only allows `ON|OFF` which won't really work for setting the mode.

Maybe another
```python
        elif topic.endswith("birdseye"):
            try:
                # example /cam_name/birdseye payload=CONTINUOUS|MOTION|OBJECTS
                camera_name = topic.split("/")[-2]
                self._on_birdseye_command(camera_name, payload)
            except IndexError:
                logger.error(f"Received invalid birdseye command: {topic}")
                return
```

and the implementation (wrote this in github so more pseudo code and haven't written python in a while)

```python
    def _on_birdseye_command(self, camera_name: str, payload: str) -> None:
        """Callback for birdseye mode topic."""

        if not payload in ["CONTINOUS", "MOTION", "OBJECTS"]:
            logger.info(f"Invalid birdseye command: {payload}")
            return
        
        camera_config = self.config.cameras[camera].birdseye
        if not camera_config.enabled:
            logger.info(f"Birdseye mode not enabled for {camera_name}")
            return
        
        camera_config.mode = BirdseyeModeEnum(payload.lower())

        self.publish(f"{camera_name}/birdseye/mode", payload, retain=True)
```

I know there would also have to be some updates to `comms/mqtt.py` as well
