### ISSUE TITLE
RTMP and hevc

### ISSUE THREAD

**Issue by chsw** [blakeblackshear/frigate#328]
Hi, I'm trying out the new 0.8 branch, but having issues with one of my two cameras.
I have one that outputs h264 and this works fine.
I also have one that ouputs h265, and this seems to be a problem when using the new rtmp-functionality.

ffmpeg.garageuppfart.detect    ERROR   : [flv @ 0x55f713c5b580] Video codec hevc not compatible with flv
ffmpeg.garageuppfart.detect    ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented

If I setup output_args for this camera as follows it starts and frigate seems to work, but no camera in HA
rtmp: -c copy -f mpegts

Do you know how to configure ffmpeg-arguments to get this camera to work in Home-assistant using frigate?

**Comment by blakeblackshear** [comment]
I would Google around for h265 video and ffmpeg rtmp output args. I'm not sure if you will be able to get this to work without re-encoding. Homeassistant may not support h265 streams anyway.

**Comment by tubalainen** [comment]
Ive got the same issue with my HVEC camera.
The new option `-rtmp `under `roles:` does not work, if commented the detection part doesnt show any errors.

**Comment by chsw** [comment]
I have done some research and chrome (which i'm using) will most likely not play hevc anyway.
To view the live stream over RTMP or play saved clips, I will probably need to figure out the correct parameters to transcode the video in real time using ffmpeg.
Actually, for me its more important to be able to play the saved hevc clips than get the live feed working.

**Comment by tubalainen** [comment]
> I have done some research and chrome (which i'm using) will most likely not play hevc anyway.
> To view the live stream over RTMP or play saved clips, I will probably need to figure out the correct parameters to transcode the video in real time using ffmpeg.
> Actually, for me its more important to be able to play the saved hevc clips than get the live feed working.

Check! Thanks for the research.

I have it all working just fine here with detection only, my "cam9_uppfart" is a HVEC / H.265 stream. The clips part, nooop.
There isnt any support with flv for that codec. :/

**Comment by chsw** [comment]
Got transcoding the live feed to work for rtmp by using the following paramerers

Software transcode:

output_args:
        rtmp: -c:v libx264 -c:a copy -f flv  

Hardware transcode on intel based hardware:

output_args:
        rtmp: -c:v h264_vaapi -c:a copy -vf format=nv12|vaapi,hwupload -f flv

I don't think that it is currently possible to transcode the clips on the fly when trying to watch them in home-assistant, but this would probably be preferred over actually transcoding the video when saving it to disk (something that I have not tried yet).

**Comment by tubalainen** [comment]
@chsw aces! <3

It worked!

**Comment by blakeblackshear** [comment]
Nice. I am going to add this to the docs. I tried to make sure you have as much control over the ffmpeg commands for these exact situations.

**Comment by chsw** [comment]
clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v h264_vaapi -c:a copy -vf format=nv12|vaapi,hwupload -b:v 2M -r 25 -an

This line seems to work for transcoding my hevc-camera feed to h264 before saving. For some reason I had to specify the camera fps (-r 25) and bitrate for the clip (-b:v 2M, although I'm not entirely sure if this is necessary).

**Comment by chsw** [comment]
@blakeblackshear  Would it be possible to enable ffmpeg to process saved clips before serving them to the media browser (transcode, change bitrate etc)?

I would prefer to save the clips using copy, to have the best possible quality for the saved clips (and save space as a bonus, since hevc compresses the files more efficiently then h264).

**Comment by blakeblackshear** [comment]
Nothing in the current feature set will allow that, but you could open a new feature request issue. Is it not an option to configure your camera to use h264? I haven't found the compression improvements to be worth the hassle given the cost of storage.

**Comment by chsw** [comment]
The camera in question is a Imou Looc, and as far as i know, I can only get h265 or very low resolution h264.
It's a quite cheap camera, with only full hd resolution and unfortunately h265 as main output. But it good enough picture quality and quite good at night.
