### ISSUE TITLE
Add bbox area information on the Events page in 11 Beta Version

### ISSUE THREAD

**Issue by bm55** [blakeblackshear/frigate#3281]
The Events page no longer shows the thumbnail with bounding box, area information.  Do I need to update my config to show the thumbnail with the bbox area info? OR should I request that feature -either thumbnail or the size info displayed on the page. This is very helpful to eliminate when false alerts are received with out having to go through the snapshot images stored in frigate/clips .

_Originally posted by @bm55 in https://github.com/blakeblackshear/frigate/discussions/3221#discussioncomment-2859113_

**Comment by NickM-27** [comment]
Thanks, this has been added back in 0.11 RC3 so closing 👍
