### ISSUE TITLE
Name snapshot files starting with a timestamp so they can be easily sorted without relying on the files' metadata

### ISSUE THREAD

**Issue by thinkloop** [blakeblackshear/frigate#3295]
(just the title)

**Comment by NickM-27** [comment]
I think more info is needed on why the metadata is not suitable. There would be a considerable amount of extra logic needed to account for the old and new filenames for snapshots.

**Comment by thinkloop** [comment]
When you copy files between systems, recover files, open them in some management program that for some reason touches them all (i.e. Capture One for photography), use syncing software (i.e. seafile), over time metadata gets lost and is not reliable in the long-term. 

If the engineering effort is high it's really probably not worth it, but would be nice if feasible.

Out of curiosity, what do you mean by "old and new"? Are snapshots replaced/updated at some point?

**Comment by NickM-27** [comment]
> Out of curiosity, what do you mean by "old and new"? Are snapshots replaced/updated at some point?

What I mean is the snapshots are retrieved from the file system by name. So we would need to have logic everywhere that the snapshots are used and search by the old name (so existing snapshots still work) and then if that doesn't exist retrieve with the new name. Then change all the places that they are saved to use the new name.

**Comment by NickM-27** [comment]
We could maybe make snapshot filename format configurable and leave the default as is, those who change it have to accept the fact that the old ones will be broken.

**Comment by thinkloop** [comment]
That would work for my use-case and new deployments.
