### ISSUE TITLE
Create Event (Manually)

### ISSUE THREAD

**Issue by zacheryph** [blakeblackshear/frigate#3307]
**Describe what you are trying to accomplish and why in non technical terms**
Download an _event_.

Something occurred that did not get picked up as an event. By viewing Recordings I can locate this event, the start and end, but cannot download a clip.

I want to be able to manually define an event, so that a clip can be downloaded.

**Describe the solution you'd like**
I'd like to be able to specify a point in time [and camera] and length of time, and define an event type.

**Describe alternatives you've considered**
manually mounting the video storage disk and manually downloading the [multiple] recording videos to produce the _event_ i want as a single clip.

**Comment by NickM-27** [comment]
[There is already an endpoint to download a clip of any start / end time](https://github.com/blakeblackshear/frigate/blob/master/frigate/http.py#L577), it just needs a UI. I am not sure how feasible it is to actually create an event manually as there will be a lot of information that is unavailable (bounding box, zone, etc.).

I think the endpoint I linked just needs a UI as discussed in this issue: https://github.com/blakeblackshear/frigate/issues/2369

Let me know if you disagree.

**Comment by zacheryph** [comment]
@NickM-27 Ahh thank you. I will look into using that for what I need :)
