### ISSUE TITLE
Support (or workaround) for using HD stream when storing an event

### ISSUE THREAD

**Issue by brujoand** [blakeblackshear/frigate#331]
Hey, thanks for making this! It was super simple to setup with my m.2 Google coral!

I'm curretly using the substreams (640x480) of two 4k ip cameras in frigate. When something is detected it would be really nice to save video from the 4k stream instead of the low res substream. Is this something that is meant to be handled by integrating with other services or a feature that could be considered? I could probably cough up a PR for it.

**Comment by blakeblackshear** [comment]
This (and much more) is already in the latest beta release.

**Comment by brujoand** [comment]
Awesome! :D
