### ISSUE TITLE
FEAT: Maintained order for birdseye cameras

### ISSUE THREAD

**Issue by McPaHa** [blakeblackshear/frigate#3327]
I'd like to see config possibility that I can manage "order" for birdseye cameras. F.e. if I have cameras 1-5 then I'd like to see these cameras always at same order independent which camera are visible at birdseye page.

For example if cameras 1,3,4 & 5 are visible then order is that and similarly if 2 & 5 are visible then order is always this...

I am not sure does this all ready like I wanted but if my request is unnecessary then just ignore this.

**Comment by NickM-27** [comment]
Bump

**Comment by NickM-27** [comment]
@wsguede birdseye also just got that ability to do true/false in this release.

**Comment by wsguede** [comment]
oh?
![image](https://user-images.githubusercontent.com/840762/193051611-513777a8-a7d2-4026-b5c4-861d10c8a08c.png)


is it called `birdseye`?

**Comment by NickM-27** [comment]
It is here

<img width="848" alt="Screen Shot 2022-09-29 at 7 59 49 AM" src="https://user-images.githubusercontent.com/14866235/193052241-2f50d6da-33e3-4405-a1a6-a119d2aeff90.png">

**Comment by wsguede** [comment]
sorry; true/false per camera is what i was thinking; similar to the `ui.dashboard` feature.

**Comment by NickM-27** [comment]
> sorry; true/false per camera is what i was thinking; similar to the `ui.dashboard` feature.

That is exactly what "can be overridden at the camera level" means

**Comment by menkej** [comment]
This can be closed now, right?

**Comment by NickM-27** [comment]
> This can be closed now, right?

No, the manual ordering of birdseye cams is not yet supported.

**Comment by crazyfrog-github** [comment]
Hi, Is there any way to manipulate the order the cameras (e.g. name them a certain way or order them in the config.yml? how does the code currently get the cameras to show up in Birdseye? 

Is there any other way to show live cameras in HA and have them in order?

**Comment by vekexasia** [comment]
Subbing to this. Would like to have birdseye ordering as well.
