### ISSUE TITLE
[Support]: No dashboard/web ui after upgrading to "0.11.0-beta3"

### ISSUE THREAD

**Issue by Coolie1101** [blakeblackshear/frigate#3329]
### Describe the problem you are having

After upgrading to "0.11.0-beta3", dashboard/web ui is blank 😥

On the other hand, video clips in notifications now work  🥳 🎉 😍

### Version

No Web UI

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
No logs for frigate.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

Worked in 0.11.0-beta1

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3230

**Comment by Coolie1101** [comment]
> This is a duplicate of #3230

And

**Comment by NickM-27** [comment]
> And

There's no reason to have multiple issues open for the same bug, better to have all reports and comments in one so it's easier to track and there's less clutter in the issues list.

**Comment by Coolie1101** [comment]
👍 
That issue was posted 24 days ago referring to beta2, that's probably why I missed it, do we combine or close this one?

**Comment by NickM-27** [comment]
I think closing this and then leave any specific comments you have on the linked ticket should be good 👍

**Comment by Calimerorulez** [comment]
I thought it would be solved in beta 3?

**Comment by Coolie1101** [comment]
duplicate of https://github.com/blakeblackshear/frigate/issues/3230
