### ISSUE TITLE
Beta3 events overview corrupt in desktop Firefox 101.0.1

### ISSUE THREAD

**Issue by bvweerd** [blakeblackshear/frigate#3334]
### Describe the problem you are having

Events browser has a weird lay-out in Firefox 101.0.1 (64-bit), see picture. Other browsers (i.e. Edge) look ok.

![image](https://user-images.githubusercontent.com/5443524/173244777-76dc6e47-158c-468a-8f3f-50e0122ab03a.png)

### Version

0.11.0-1D45B0B

### Frigate config file

```yaml
NR
```

### Relevant log output

```shell
NR
```

### FFprobe output from your camera

```shell
NR
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink

**Comment by hacsjalano** [comment]
Also seeing the same layout issue - the delete/trashcan icon is huge still for me, as it was in beta2.

**Comment by NickM-27** [comment]
This has been fixed in https://github.com/blakeblackshear/frigate/pull/3226, it seems the beta3 build didn't include the web changes and may need to be rebuilt

**Comment by bvweerd** [comment]
fixed in Beta4 👍
