### ISSUE TITLE
[Support]: 504 Gateway Timeout when downloading large recording

### ISSUE THREAD

**Issue by mew1033** [blakeblackshear/frigate#3337]
### Describe the problem you are having

I'm trying to download a very large recording (19.5 hours) to make a timelapse. I'm using the api endpoint `/api/<camera>/start/<start_time>/end/<end_time>/clip.mp4`. It spins for a long time (I assume it's assembling the file), then gives me a 504 Gateway Timeout.

Any chance that timeout period could get adjusted for the api?

### Version

0.10.1-83481AF

### Install method

Docker Compose

### Network connection

Wired

**Comment by blakeblackshear** [comment]
It unlikely to work because that endpoint writes to the tmp directory and you will run out of space. I would recommend reading the VOD endpoint with ffmpeg and writing the file yourself.
