### ISSUE TITLE
[FR] Enable ffmpeg to transcode saved videos when watching clips using HA media browser

### ISSUE THREAD

**Issue by chsw** [blakeblackshear/frigate#334]
Many IP-cameras use hevc (h265) to stream the video (some cheap ones ONLY output hevc).
Browser support for hevc is however for the most part lacking.

It would be great if it was possible to let frigate save the clips in hevc-format (using copy to retain the original quality/size) and then transcode the clips before sending them to home assistant for viewing. 
This would also make it possible to transcode high bitrate h264-clips before sending them to home-assistant, to minimize data usage if viewing saved clips on mobile data.

**Comment by speedst3r** [comment]
Not just HA media browser, but the Frigate UI as well.

**Comment by paularmstrong** [comment]
Only [Safari currently supports HEVC/h265](https://caniuse.com/hevc). While this might be beneficial for a small few, most people won't be able to view them in their browser, which greatly reduces the utility.

**Comment by speedst3r** [comment]
The feature request is to allow ffmpeg to transcode them to H.264 on demand, so recordings can still be stored in H.265 but played back in a browser.

**Comment by paularmstrong** [comment]
Ah sorry, I read this backwards 🙃 

There is actually a preference to serve as HLS (#422) because it's more bandwidth friendly. I think this might fit well paired with that work getting done first.
