### ISSUE TITLE
[Support]:  change documentation page config/objects to include object numbers

### ISSUE THREAD

**Issue by renarena** [blakeblackshear/frigate#3341]
### Describe the problem you are having

it would be easier to find out the number of an object fe. to change object names by using lablemap if the labels would be a numbered list rather then a dotted one :-)
https://docs.frigate.video/configuration/objects

### Version

x

### Frigate config file

```yaml
x
```

### Relevant log output

```shell
x
```

### FFprobe output from your camera

```shell
x
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

x

**Comment by NickM-27** [comment]
As far as editing the labelmap file itself, it must be a standard list format as it is required to be given to the model, see the official label maps: https://coral.ai/models/object-detection/. 

However, the docs could be updated to show the numbers for reference.

**Comment by renarena** [comment]
> However, the docs could be updated to show the numbers for reference.
That is what i mean - so you do not have to count lines every time you need the number of a model
