### ISSUE TITLE
Modify objet filter min max area

### ISSUE THREAD

**Issue by Pascal66** [blakeblackshear/frigate#3356]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to Modify objet filter min max area so that I can remove false positive

**Describe the solution you'd like**
changing min_area max_area according the captured area
adding an option for that in the box below
![image](https://user-images.githubusercontent.com/3041616/174250631-34c4fe00-8fa0-4dc4-9c15-3c2bb929c99c.png)

**Describe alternatives you've considered**
None

**Additional context**
example picture
![image](https://user-images.githubusercontent.com/3041616/174249837-c0321557-d8c4-4016-9a0b-5a54d46110de.png)

**Comment by NickM-27** [comment]
min_area and max_area are already supported filters. Please see https://docs.frigate.video/configuration/index for how to set this up in be config
