### ISSUE TITLE
[Support]: How can I identify event files only?

### ISSUE THREAD

**Issue by crider17** [blakeblackshear/frigate#3360]
### Describe the problem you are having

I'm recording 24/7 and I see the 10 second length video files where they are saved. Some of these files have event data in them (that is, objects detected via motion) but most do not. I want to copy my event files over to a folder that Plex is monitoring so that I can watch my events via Plex on my TV. So my questions are:
1. How can I identify the video files that contain event data so that I can move them (via a Linux bash script or something), OR
2. Can I have Frigate save the events off into a different folder separate from the than the 24/7 recordings?

Thanks for your help.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
Irrelevant
```

### Relevant log output

```shell
Irrelevant
```

### FFprobe output from your camera

```shell
Irrelevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Irrelevant

**Comment by NickM-27** [comment]
Users are not meant to interact with the files directly. There's a myriad of endpoints / APIs that can be used to get the content you want to store it elsewhere, see https://docs.frigate.video/integrations/api

Specifically, it would be a lot more difficult for plex to store all those 10 second segments vs just getting a single mp4 for the entire event and storing that in plex. 

> Can I have Frigate save the events off into a different folder separate from the than the 24/7 recordings

No, frigate uses the same segments to fill both 24/7 and events to reduce redundant storage and drive wear.

**Comment by crider17** [comment]
Yes. That is exactly what I'm looking for. Move the entire event file over to Plex, rather than the 10 second files. I'm just not finding any files that self contain the entire event. Frigate, when playing events within the software must just know which 10 second files to string together to play the event. I need to try and get that event a single file that I can move. 

Thank you for your response. I will check out the API document and report back.

**Comment by NickM-27** [comment]
> Frigate, when playing events within the software must just know which 10 second files to string together to play the event.

Yes that's exactly what it does, there's APIs to get a single clip based on a start and end time or get one for an event

**Comment by blakeblackshear** [comment]
I recommend using the VOD endpoints rather than the clip.mp4 endpoints

**Comment by crider17** [comment]
Thanks Blake.

I'm googling around the topic but having a hard time finding use cases/examples. Does anyone know where someone has provided examples of API/VOD implementations, or even an example of using the API's to identify events and copy the files off to another location? I see the doc but I'd really like to find some example implementations if possible. I'm assuming this is implemented within the config yaml as a triggered process following a detection or perhaps an HA automation that does the work?

Thanks again.

**Comment by NickM-27** [comment]
> Thanks Blake.
> 
> 
> 
> I'm googling around the topic but having a hard time finding use cases/examples. Does anyone know where someone has provided examples of API/VOD implementations, or even an example of using the API's to identify events and copy the files off to another location? I see the doc but I'd really like to find some example implementations if possible. I'm assuming this is implemented within the config yaml as a triggered process following a detection or perhaps an HA automation that does the work?
> 
> 
> 
> Thanks again. 


config.yaml doesn't have any trigger processes. You'd either want to setup an HA automation or maybe there's some way to do it with plex.

Manually for a past event it would look like:
1. Check `/api/events` to find an event id
2. you'd then have `/api/vod/event/{event-id}/index.m3u8`

That may be able to be played directly in plex or it might need a specific way (I don't use plex so don't know).

Similar could be done with the mp4 endpoint and put that in plex

Automations:
1. HA (or something) watches MQTT for an event end (can filter on types, zones, etc)
2. Take the event id and get index.m3u8 or clip.mp4 and send it to plex
