### ISSUE TITLE
[Support]: Possible minor memory leak...ObjectTracker, positions[id] are added, but never deleted

### ISSUE THREAD

**Issue by bwmcin** [blakeblackshear/frigate#3369]
### Describe the problem you are having

In objects.py, in deregister, the tracked_objects and disappeared are deleted, but positions isn't.  Shouldn't it also be deleted?

### Version

Current Master, appears to be in recent versions

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wired

### Camera make and model

N/A

**Comment by scooper1** [comment]
maybe this is the reason that frigate maybe appears to crash my system every week on beta 4  the container grows by 1GB every 4 to 8 hours

**Comment by NickM-27** [comment]
> maybe this is the reason that frigate maybe appears to crash my system every week on beta 4 the container grows by 1GB every 4 to 8 hours

This is pure text, we are talking bytes not even megabytes so that is highly unlikely. It is most likely ffmpeg crashing issues which you can see the discussion for here: https://github.com/blakeblackshear/frigate/issues/3301

**Comment by NickM-27** [comment]
the previous object tracker is not used anymore
