### ISSUE TITLE
[Support]: Debug "stuck" detection events

### ISSUE THREAD

**Issue by mag1024** [blakeblackshear/frigate#3372]
### Describe the problem you are having

Hi,
I'm using Home Assistant to send notifications on Frigate MQTT events.
The issue is that sometimes these MQTT events seem to get "stuck" on a frame and repeat for many hours, even though the object has long since left the camera view.

`
{
    "before": {
        "id": "1655815890.497768-jqe4g3",
        "camera": "side_door",
        "frame_time": 1655830427.443526,
        "snapshot_time": 1655815992.314924,
        "label": "person",
        "top_score": 0.84375,
        "false_positive": false,
        "start_time": 1655815890.497768,
        "end_time": null,
        "score": 0.76953125,
        "box": [
            396,
            91,
            454,
            203
        ],
        "area": 6496,
        "region": [
            220,
            0,
            588,
            368
        ],
        "stationary": true,
        "motionless_count": 72113,
        "position_changes": 2,
        "current_zones": [],
        "entered_zones": [],
        "has_clip": true,
        "has_snapshot": true
    },
    "after": {
        "id": "1655815890.497768-jqe4g3",
        "camera": "side_door",
        "frame_time": 1655830487.946631,
        "snapshot_time": 1655815992.314924,
        "label": "person",
        "top_score": 0.84375,
        "false_positive": false,
        "start_time": 1655815890.497768,
        "end_time": null,
        "score": 0.76953125,
        "box": [
            396,
            91,
            454,
            203
        ],
        "area": 6496,
        "region": [
            220,
            0,
            588,
            368
        ],
        "stationary": true,
        "motionless_count": 72415,
        "position_changes": 2,
        "current_zones": [],
        "entered_zones": [],
        "has_clip": true,
        "has_snapshot": true
    },
    "type": "update"
}
`

Note that the "snapshot_time" is several hours in the past, and so Frigate thinks the object is still present and stationary.
What can cause this to happen?

### Version

0.10.1 -- but this has happened with prior versions as well

### Frigate config file

```yaml
cameras:
  ffmpeg:
      inputs:
        - path: ...
          roles:
           - record
        - path: ...
          roles:
           - detect
      output_args:
        detect: -vf transpose=1 -f rawvideo -pix_fmt yuv420p
    detect:
      width: 720
      height: 1280
```

### Relevant log output

```shell
Nothing relevant
```

### FFprobe output from your camera

```shell
Nothing relevant
```

### Frigate stats

```json
{"detection_fps":0.0,"detectors":{"cpu":{"detection_start":0.0,"inference_speed":114.84,"pid":225}},"front_door":{"camera_fps":5.1,"capture_pid":232,"detection_fps":0.0,"pid":228,"process_fps":5.1,"skipped_fps":0.0},"mudroom":{"camera_fps":5.1,"capture_pid":233,"detection_fps":0.0,"pid":230,"process_fps":5.1,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":61.5,"mount_type":"tmpfs","total":67.1,"used":5.6},"/media/frigate/clips":{"free":1592313.5,"mount_type":"ext4","total":1964006.5,"used":371571.3},"/media/frigate/recordings":{"free":1592313.5,"mount_type":"ext4","total":1964006.5,"used":371571.3},"/tmp/cache":{"free":339914.4,"mount_type":"btrfs","total":456159.6,"used":116245.1}},"temperatures":{},"uptime":783516,"version":"0.10.1-83481af"},"side_door":{"camera_fps":5.1,"capture_pid":234,"detection_fps":0.0,"pid":231,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Dahua N43AL52

**Comment by NickM-27** [comment]
There's a few things that can cause this:
- a false positive that kept the object for enough frames to become stationary 
- a motion mask that is too large causing the object to get stuck due to no motion updates (motion masks should just cover trees, skyline, Timestamps, etc
- Could be a DB error of some kind but you indicated that's not the case

**Comment by mag1024** [comment]
Thanks, Nick. To be clear, I believe the event starts with a real object -- a person walks into the frame, and the first detection/notification is perfectly legitimate, it's just that the frame seems some how then get frozen/stop updating, and so the detection engine keeps thinking the object is still there and issuing followup events.

**Comment by NickM-27** [comment]
> Thanks, Nick. To be clear, I believe the event starts with a real object -- a person walks into the frame, and the first detection/notification is perfectly legitimate, it's just that the frame seems some how then get frozen/stop updating, and so the detection engine keeps thinking the object is still there and issuing followup events.

Right, I understood what you meant, all 3 points I mentioned fit this case and have seen them before with these symptoms. 

> What is also odd is that it seems to mostly happen on only 2 cameras of different models, and I have multiple other cameras of the same models as the two affected ones installed, and I haven't ever noticed them exhibit this issue.

Do these cameras have motion masks on them? Have you checked the debug view to see where the object is being detected?

**Comment by mag1024** [comment]
There are no masks on the affected cameras.
The event history shows two overlapping multi-hour events:
  | side_door | person | 76.95% |   | 6/21/2022 | 8:53:26 AM | 11:37:28 AM
  | side_door | person | 77.93% |   | 6/21/2022 | 8:52:59 AM | 2:33:52 PM
In both cases the clip shows the person walking out of the frame, then it cuts to several hour later when a cat walks by :)

**Comment by NickM-27** [comment]
> In both cases the clip shows the person walking out of the frame, then it cuts to several hour later when a cat walks by :)

Right, that's expected since your config doesn't keep segments that have no motion. Once the cats motion triggers a check it doesn't see the object anymore. 

I mean while the event is still active I'd look at the debug camera feed with bounding boxes enabled so you can see what's stuck / what frigate sees as an object.

**Comment by joesteffee** [comment]
Just chiming in that im having the exact same problem. MQTT event notifications through home-assistant. Sometimes my front porch camera will detect someone in the frame and ill receive the same notification and still photo of the same event over and over every few minutes until something else happens or i restart frigate.

**Comment by NickM-27** [comment]
> I think @joesteffee's issue _is_ the same as mine -- whether the stuck event results in repeat notifications depends on whether the notification logic does `type` filtering.

I didn't realize you were experiencing repeat notifications. 

> It should be noted as a useful workaround, but even if the repeat notifications are filtered out, it still seems like there might be an underlying issue with Frigate that leads to this behavior in the first place.

Filtering on event type or other data is not a workaround. It is the behavior by design. MQTT is how frigate communicates with the integration and other places.

The stuck objects is not intended behavior needs to be sorted out separately, but the MQTT event updates for it are expected

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/3195 for another example for more context

**Comment by NickM-27** [comment]
> The fact that the poster in #3195 indicated that he's receiving repeat notifications with the "same picture" and that  "[he has] another automation for another camera with exact same notification and that is working fine.", would seem to imply that he too is afflicted with the stuck event problem.

Like was indicated in the comments, the event update will come through MQTT once a minute while the object is being tracked stationary or not, so the picture being the same makes sense. 

> For example, I have independent rate filtering based on the last time the notification automation was triggered, and if not for the stuck events, I may want to drop the type filtering, and receive notifications every N minutes if the detection is still _legitimately_ ongoing

The stuck detection is a problem that needs to be solved. If you look at the payload for the event there's all kinds of data to clue off of including if the object is stationary and how long it's been stationary which can be used to get designed behavior (assuming stuck detection isn't happening). 

As far as the stuck detection goes, I'd recommend setting `detect -> stationary -> interval` to something greater than 0 to address it.

**Comment by mag1024** [comment]
My theory is that the real root cause is the failure to update snapshot. This is what causes the picture in the notifications to be *identical* (not just having little change), and since it's being fed the same frame over and over again, it's no wonder that detection thinks that the object is present and stationary.

Apologies if I'm belaboring this point, and you already understood this, but it seems that everything else (type filtering, stationary interval, etc) is just masking the symptoms. Even if we ameliorate the notification spam, if the frame is not being updated, we could probably be missing legitimate events in the meantime.

**Comment by NickM-27** [comment]
> My theory is that the real root cause is the failure to update snapshot. This is what causes the picture in the notifications to be *identical* (not just having little change), and since it's being fed the same frame over and over again, it's no wonder that detection thinks that the object is present and stationary.
> 
> 
> 
> Apologies if I'm belaboring this point, and you already understood this, but it seems that everything else (type filtering, stationary interval, etc) is just masking the symptoms. Even if we ameliorate the notification spam, if the frame is not being updated, we could probably be missing legitimate events in the meantime.

We have never seen that behavior so I highly doubt that's the case (not trying to be rude, just being honest). We have seen similar incorrect behavior before and it's due to a false positive stationary object.

Stationary interval has nothing to do with notifications directly, it just  config option that makes frigate run object detection every X frames looking for the object that is currently detected as stationary to ensure it's still there. So if the frame was truly stuck then that change wouldn't help, but I wager it will fix this issue.

By default once an object is stationary it is assumed to be there until motion occurs near it. In rare cases an object can be marked as stationary and for one reason or another the motion is missed when it exits and the detection is stuck on a false positive.

Either way, it's all speculation, the only way to say for sure is to try a new value or look at the debug camera view and see what it sees while this is happening.

**Comment by NickM-27** [comment]
Here are a couple examples of stuck detections like I've been explaining how they can happen

https://github.com/blakeblackshear/frigate/issues/3186

https://github.com/blakeblackshear/frigate/issues/2965

Another option to debug would be to change your event retain mode to `all` and then watch back the whole clip / use the clip as a camera in frigate to watch the debug view live.

**Comment by mag1024** [comment]
I caught a "stuck" event today, and was able to confirm your theory.
There was a ~60% probability false positive on a relatively small area of the frame with a lot of detail -- the presence of such "difficult" areas is probably what accounts for some cameras being more prone to this issues than others.
The fact that the false positive is relatively small/low probability, probably also explains why it was never considered worth updating the snapshot for, which is what misled me about the potential cause.
I'm going to attempt to fight this issue with a combination of probability/area thresholds for the person detector...

Is there a way to tune the snapshot updating logic? If it were possible to force an update on every event, it would make debugging such issues easier, as the content of the notifications would now clearly indicate the cause for ongoing notifications.

**Comment by NickM-27** [comment]
> Is there a way to tune the snapshot updating logic?

I don't believe there is currently tunability for when the snapshot is updated. You could have the notification use the full frame (latest) snapshot instead of the one attached to the event. 

> If it were possible to force an update on every event

What do you mean by "event" here? Perhaps you mean every MQTT update message?

**Comment by mag1024** [comment]
What I currently use for notifications is the snapshot published on `frigate/<camera>/person/snapshot`.
When you say "full frame (latest) snapshot" do you mean just snapshotting the live view of the camera in HA? That wouldn't have the bounding bounding boxes, which is the part that's most useful for identifying false positives, right?

Yes, updating `frigate/<camera>/person/snapshot` as often as new MQTT update messages are published is what I was hoping for.

Anyway, I think this issue is mostly resolved. Thanks for your help!
