### ISSUE TITLE
[frigate+] Bird should be an option

### ISSUE THREAD

**Issue by BBaoVanC** [blakeblackshear/frigate#3379]
**Describe what you are trying to accomplish and why in non technical terms**

Sorry if this isn't the right place to ask for this, but I couldn't find any other way to contact you.

I uploaded an image of a bird detection to Frigate+ and was going to annotate it. Unfortunately, bird isn't one of the options to annotate. I had to mark it as a person instead since there wasn't any option to delete the image from Frigate+.

**Describe the solution you'd like**

Option to annotate a bird on Frigate+, and a way to delete uploaded images.

**Comment by NickM-27** [comment]
I don't think this is a good place for this as this is for the main frigate issues. The discussion https://github.com/blakeblackshear/frigate/discussions/1043 would be better

Also, it's already been said that more options will be present in the future but gotta start somewhere for an initial release.

**Comment by user897943** [comment]
I totally agree. I want my NVR to spot all the cute british ladies.

**Comment by blakeblackshear** [comment]
Please don't pollute the models by mislabeling objects. You don't have to add any labels to an image if there aren't any appropriate labels added.

**Comment by BBaoVanC** [comment]
> I don't think this is a good place for this as this is for the main frigate issues. The discussion #1043 would be better
> 
> Also, it's already been said that more options will be present in the future but gotta start somewhere for an initial release.

Oh I didn't notice the discussions section when I made this

> Please don't pollute the models by mislabeling objects. You don't have to add any labels to an image if there aren't any appropriate labels added.

I didn't know whether it would be better to leave it blank (saying that there was nothing there, which isn't true). But still the better way would be to have an option to delete the image since I'd rather not put a false-false-positive (if you know what I mean)

**Comment by NickM-27** [comment]
> I'd rather not put a false-false-positive (if you know what I mean)

@blakeblackshear correct me if I'm wrong but I'm pretty sure these models are not trained on negatives, so not labeling it now wot affect it later. Also they can be considered that bird wasn't in the list when this was submitted

**Comment by blakeblackshear** [comment]
Yes, you aren't specifying that nothing is there. You are specifying that none of the available labels are present.

**Comment by BBaoVanC** [comment]
Sorry for the late response, I edited the image on Frigate+ to unlabel it.
