### ISSUE TITLE
Dynamic realtime video feed of a combined camera view 

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#338]
Would be interesting to have a single video feed where frigate dynamically builds a grid view based on which cameras currently have detected objects. I could assemble this from the raw yuv420p data and expose it to ffmpeg for encoding. This would **probably** end up being very low overhead. I could then broadcast this via rtmp or over websockets as mpeg1 for jsmpeg to consume.

**Comment by scstraus** [comment]
Maybe time for this?
https://www.youtube.com/watch?v=-xgqlaWnKmo

**Comment by blakeblackshear** [comment]
That would be something quite different. More of a daily post processor for clips.

**Comment by scstraus** [comment]
Yeah I see what you're saying.. For me its easy enough to assemble a grid in homeassistant, but maybe there would be some performance benefits to this approach.

**Comment by scstraus** [comment]
Yeah I see what you're saying. Could be useful for the [popups I do on tablets](https://github.com/scstraus/home-assistant-config/blob/6027951c351dbc1df1938c6d099aa1b3218a8039/automations/security_automations.yaml#L584-L800) to not have to decide which camera feed to popup (which creates unreliability by opening and closing the feeds too often).

**Comment by pdecat** [comment]
Still desired :pray: :)
