### ISSUE TITLE
Add timestamps to logs

### ISSUE THREAD

**Issue by Ysbrand** [blakeblackshear/frigate#339]
Example of a current log:
 ```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
detector.coral                 INFO    : Starting detection process: 35
frigate.app                    INFO    : Camera processor started for Voordeur: 38
frigate.app                    INFO    : Capture process started for Voordeur: 40
frigate.edgetpu                INFO    : Attempting to load TPU as usb:0
frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.
ffmpeg.Voordeur.detect         ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
```

With this I have no clue when the event happened, especially if there is some repeating error event it would be niuce to know what the real frequency is (every 5 minutes or every day makes obviously a huge difference).

If possible add some simple day/time information to each of the events.

**Comment by blakeblackshear** [comment]
If you are using docker to view the logs, you can get timestamps with a command line parameter. How are you viewing the logs?

**Comment by Ysbrand** [comment]
Hi,
I'm using the home assistant integration and look at the "log" tab.

**Comment by B0ndo2** [comment]
Sorry for reopening this, I have the same request. Viewing logs from the HA addon show no timestamp and makes it difficult to know if errors are recent or old
