### ISSUE TITLE
[Support]: failed to create shim task OCI runtime create failed unable to start container process unable to apply caps operation not permitted

### ISSUE THREAD

**Issue by epicurean70** [blakeblackshear/frigate#3390]
### Describe the problem you are having

During docker compose installation, this is the error I get:
failed to create shim task OCI runtime create failed unable to start container process unable to apply caps operation not permitted

I am trying to install frigate (no coral yet), on a debian priviledged LXC , with docker and docker compose installed. 
My docker compose file is:
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: '64mb'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config.yml:/config/config.yml:ro
      - /mnt/Recordings:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

### Version

not installed yet

### Frigate config file

```yaml
none yet
```

### Relevant log output

```shell
in the problem description
```

### FFprobe output from your camera

```shell
none yet
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

none yet

### Any other information that may be helpful

Proxmox hypervisor, Debian 11 container, Lenovo M920Q

**Comment by gwisl** [comment]
Try disabling
`privileged: true # this may not be necessary for all setups`
