### ISSUE TITLE
Dewarping for fish eye 360 cameras 

### ISSUE THREAD

**Issue by JonLaliberte** [blakeblackshear/frigate#3397]
Any plans to support dewarping for use with 360 degree / fish eye cameras?

**Comment by NickM-27** [comment]
Seems like this can already be done with ffmpeg output args https://stackoverflow.com/questions/62238714/how-to-de-warp-180-degree-or-360-degree-fisheye-video-with-ffmpeg

**Comment by JonLaliberte** [comment]
Interesting, thanks for sharing. I'm not using Frigate yet, just evaluating options, good to see there may be a way to use these cameras with it.
