### ISSUE TITLE
Documentation: Add note related to Protection mode in Home Assistant Add-on when enabling hwaccel

### ISSUE THREAD

**Issue by Ysbrand** [blakeblackshear/frigate#340]
I'm running the 0.80 beta on a PI4/X64/Hassos 5.3
If one wants to enable hardware acceleration you will need to disable "Protection mode" in order to get elevated system access.

If protection mode is enabled (which is the default) any attempt to enable hardware acceleration will fail with:
```
ffmpeg.Voordeur.detect         ERROR   : [h264_v4l2m2m @ 0x55945d9d80] Could not find a valid device
ffmpeg.Voordeur.detect         ERROR   : [h264_v4l2m2m @ 0x55945d9d80] can't configure decoder
```

Just a note in the documentation should be enough.

**Comment by blakeblackshear** [comment]
You just saved me a bunch of time. Thanks.
