### ISSUE TITLE
Determining direction of travel

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3403]
### Describe the problem you are having

I would like to be able to detect direction of travel.

I have a camera watching the die of a long driveway, with a long narrow detection zone.

I'd like to be able to determine the direction of travel of a vehicle so that I can be notified with 'leaving' or arriving.

I'm thinking that 3 zones will be required, but how do I configure them? The vehicle detection with the single zone is working fine.

Any pointers will be much appreciated.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
If you have a view of the street then you could use `street` as the entrance and wouldn't need a separate `entrance` zone.

**Comment by ripvega** [comment]
Thanks for the quick reply, Nick.

I'm not sure I explained myself properly.

This is the zone in question:
<img width="642" alt="Screenshot 2022-06-30 at 13 47 17" src="https://user-images.githubusercontent.com/42817627/176680815-d82f639a-4f90-4a17-bc27-7c15662a6d7e.png">
Vehicles can enter at either end and exit at either end. Typically, they don't stop.

I need to determine which way they are going so that I can then notify if leaving on arriving at the property.

**Comment by NickM-27** [comment]
I see, that makes sense. The logic still should follow what I said mostly. The order of items in `entered_zones` is chronological so if zone is `left_gate,driveway,right_gate` then they went from left to right. Opposite order for the other way, and then you can naturally infer their current position / direction of travel if `current_zone` contains `driveway` and only one of `left_gate` or `right_gate`

**Comment by ripvega** [comment]
Right! So, you are saying to make all three as required zones and then trigger automations based on the order in which the MQTT messages are received, using `start_time` to determine this?

Will they always be sent in the correct time order?

If so, that's just the answer I was looking for. Thank you.

**Comment by NickM-27** [comment]
> Right! So, you are saying to make all three as required zones and then trigger automations based on the order in which the MQTT messages are received, using `start_time` to determine this?
> 
> 
> 
> Will they always be sent in the correct time order?
> 
> 
> 
> If so, that's just the answer I was looking for. Thank you.

Not quite, you don't need to consider other messages. Each message will have all the information you need, the fields `entered_zones` and `current_zones` are in each MQTT message as described in the docs and those will be enough to understand the current state of the car.

**Comment by ripvega** [comment]
OK. Got that. Thank you.

I'll enlist someone to drive up and down the driveway to test!
