### ISSUE TITLE
[Support]: 0.11-beta4 looks good

### ISSUE THREAD

**Issue by vertex-github** [blakeblackshear/frigate#3404]
### Describe the problem you are having

No problem.  Upgrade from `3de1948` went without a hitch.  Upgraded ~250Mb DB.  UI seems snappier ( birdseye and events view).  I like the more compact events view. 👍 

Only thing I noticed in the docker logs are lines similar to:

[2022-06-30 12:27:55] frigate.output                 WARNING : Unable to copy frame garage_31656606469.629646 to birdseye.
[2022-06-30 12:27:55] frigate.output                 WARNING : Unable to copy frame driveway1656606469.59901 to birdseye.

when viewing the birdseye page, although all cameras seem to be updating frequently in that view.  Reloading the page shows different cameras mentioned in the logs (same warning as above) - i.e. its not the same cameras logged every time I view the birdseye page.

### Version

0.11.0-1d45b0b

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink, Axis and Amcrest

**Comment by NickM-27** [comment]
Really glad to hear the beta is working well for you, the [Discussions](https://github.com/blakeblackshear/frigate/discussions) (either the beta topic or creating your own topic) are a much better place than creating an issue if there is nothing wrong / to solve as this is just adding clutter to the list of issues that do need to be solved 👍
