### ISSUE TITLE
[Support]: How do I actually RUN Frigate?

### ISSUE THREAD

**Issue by SeaDude** [blakeblackshear/frigate#3418]
### Describe the problem you are having

I've installed Debian 11 on a server, installed Docker, cloned this Github repo... **now what?** 

The Frigate installation instructions don't seem to cover this critical point or it assumes the user knows what to do with Docker to get Frigate running.

I'm a Docker newb.

### Version

NA

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

NA

### Any other information that may be helpful

Thank you

**Comment by SeaDude** [comment]
After `docker` and `docker-compose` are installed and configured on the system:
- `git clone` this Frigate repo
- `cd` in
- `docker-compose up`

**Comment by NickM-27** [comment]
You can git clone this repo but it isn't recommended and isn't the official build. 

Following https://docs.frigate.video/installation#common-docker-compose-storage-configurations is how you'll get the official build. https://hub.docker.com/r/blakeblackshear/frigate has the tags if needed
