### ISSUE TITLE
Toggle improve_contract without full frigate restart or modifying yaml

### ISSUE THREAD

**Issue by irakhlin** [blakeblackshear/frigate#3420]
**Describe what you are trying to accomplish and why in non technical terms**
I want to improve night time detection by using improve_contrast without increasing daytime false positives.

**Describe the solution you'd like**
If possible I would love to be able to set a time period, or time range between which "improve_contrast" would be enabled, and otherwise would be disabled per camera, this would be an optional sub property of improve_contract. My understanding would be that this would require a restart of the detection stream but to me the benefit is pretty significant. Potentially this could be done with the sched module?

Alternatively exposing via MQTT to none persistently (without writing to yaml) toggle improve_contrast would also work, as then it could be automated in home assistant in addition with the hass frigate integration which already lets you toggle detection, on/off. This may potentially be significantly easier.  

**Describe alternatives you've considered**
Keeping improve_contrast off has been the only alternative that has been usable thus far. All of my cameras go absolutely crazy with over sensitivity and false detection during day time; it is especially bad on a sunny, rainy or snowy day with double to triple CPU usage. Additionally many static objects that have always been part of the frame will often be detected as objects, for example a flower pot with the right shadow gets detected as a person while with improve_contract it is not.

**Comment by NickM-27** [comment]
This is already done in 0.11 which is currently in beta

**Comment by irakhlin** [comment]
@NickM-27 That is awesome news, I was going to offer to submit a pr otherwise. I am currently running the latest .11 beta, could you point me to the documentation to this functionality if its available? Does it also require the beta version of the integration?

**Comment by NickM-27** [comment]
Yes it does require the beta version of the integration. If you check the docs (at the top of the release notes) it is under the MQTT section.

**Comment by irakhlin** [comment]
> Yes it does require the beta version of the integration. If you check the docs (at the top of the release notes) it is under the MQTT section.

Just found it, linking here for reference. 
https://deploy-preview-2829--frigate-docs.netlify.app/integrations/mqtt#frigatecamera_nameimprove_contrastset

Thank you

**Comment by NickM-27** [comment]
Is this working for you? This issue should be closable in that case 👍

**Comment by irakhlin** [comment]
@NickM-27 
Sorry I did not follow up, I was able to set this  up within 10 minutes of reading the documentations. Very well done, and implemented in a clean and easy to use way. Great job. Please close!

**Comment by NickM-27** [comment]
I don't have the powers to close, you should be able to 👍

And thanks, credit for this feature goes to @hawkeye217
