### ISSUE TITLE
Use ffmpeg-python for args parsing

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#3428]
**Describe what you are trying to accomplish and why in non technical terms**
When I need to override some arg for my cameras, because, let's say, I want to enable audio, I have to be aware that on newer releases of Frigate, I must check whether the default args have changed or not, and if they did, I have to also refactor my whole config file.

**Describe the solution you'd like**
[ffmpeg-python](https://github.com/kkroening/ffmpeg-python) is a very known library that could help with that. If we could specify named arguments in the YAML configuration, could easily override the default args with the args I set. In case I only wanted to enable audio, I could add `-c:a aac` only.

**Describe alternatives you've considered**
N/A, I think.

**Additional context**
I haven't tested though.

**Comment by blakeblackshear** [comment]
This would require writing code to handle every possible ffmpeg argument that exists or not supporting many options. Today you can use anything supported by the command line. This seems like it would create far more problems than it would solve, but I could be wrong.

**Comment by felipecrs** [comment]
Manually it's totally not feasible indeed. I was thinking about programmatically mapping the ffmpeg-python bindings to the YAML parser.

Let me do some investigation...

**Comment by felipecrs** [comment]
Nevermind, this won't help much indeed.

What do you think about an `audio` flag for cameras, like:

```
cameras:
  garden:
    audio: true
```

In which, if turned on, it will cause the _default_ flags to come with `-c:v copy -c:a aac` rather than `-c copy -an`. It would be effectless in case the user overrode the default parameters.

**Comment by felipecrs** [comment]
Ok, I elaborated my idea a little better at https://github.com/blakeblackshear/frigate/issues/3429.
