### ISSUE TITLE
[Support]: Is it possible to write recordings to RAID storage?

### ISSUE THREAD

**Issue by SeaDude** [blakeblackshear/frigate#3435]
### Describe the problem you are having

Would to nice to have redundant storage. 

**Is it possible to write to two (or more) disks using Frigate?** 

As an add-on question: 
- **What type of formatting is storage required to have? NTFS possible or only EXT4?**

Thank you

### Version

NA

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

UVC G3 Flex

**Comment by NickM-27** [comment]
As a docker container any type of storage can be mounted and used for storage.

**Comment by SeaDude** [comment]
Ah, ok. So the combined RAID disk would look like the single disk in the `docker-compose` file, gotcha. 

What about NTFS vs EXT4?

Example:
- I'm running `docker` (Frigate) on a bare metal Debian 11 server
- I want to write Frigate recordings to disk on a Windows 10 server on my network

Would this work? 

I ask because the example in the docs for writing recordings to a network file share, looks like a linux path. vs a Windows path like `D:/frigate` etc.

```
volumes:
      - /path/to/your/config.yml:/config/config.yml:ro
      - /path/to/network/storage:/media/frigate
```

Thank you
