### ISSUE TITLE
AprilTags or other QR 

### ISSUE THREAD

**Issue by edk4971** [blakeblackshear/frigate#3443]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to scan AprilTags or some other form of QR code so that I can trigger HomeAssistant automations.

**Describe the solution you'd like**
Text someone a picture, or store a picture on my phone, to trigger a script or automation in HA.

**Describe alternatives you've considered**
None. As far as I know, this product doesn't really exist.

**Additional context**
https://hackaday.com/2022/07/08/use-apriltags-to-let-guests-open-your-front-gate/

**Comment by NickM-27** [comment]
I believe that is a duplicate of https://github.com/blakeblackshear/frigate/issues/3155

It would be best if you could close this and add your specific comments / ideas to the linked issue so it can all be kept in one place.

**Comment by edk4971** [comment]
Agreed, I searched for QR and didn't find anything. Thanks!
