### ISSUE TITLE
VOD endpoint not working properly?

### ISSUE THREAD

**Issue by vekexasia** [blakeblackshear/frigate#3444]
### Describe the problem you are having

The vod with timestamps endpoint does not work.

https://docs.frigate.video/integrations/api/#get-vodcamerastartstart-timestampendend-timestampindexm3u8

I'm trying to create a script that backs up all the clips of last 24 hours to then save it securely in my NAS (maybe there is a better way) 

VLC just explodes when i open it and I tried also with ffmpeg. Log below.

### Version

0.10.0-DB1255A

### Frigate config file

```yaml
irrelevant
```

### Relevant log output

```shell
irrelevant
```

### FFprobe output from your camera

```shell
irrelevant the camera output BUT this is what ffmpeg returns.

[http @ 00000251e5948300] HTTP error 404 Not Found
[hls @ 00000251e5920700] Failed to open segment 35 of playlist 0
[hls @ 00000251e5920700] Opening 'http://frigate2.iot:5000/vod/retro/start/1657298493/end/1657357537/seg-36-v1.ts' for reading
[http @ 00000251e5948300] HTTP error 404 Not Found
[hls @ 00000251e5920700] Failed to open segment 36 of playlist 0
[hls @ 00000251e5920700] Opening 'http://frigate2.iot:5000/vod/retro/start/1657298493/end/1657357537/seg-37-v1.ts' for reading
[http @ 00000251e5948300] HTTP error 404 Not Found
[hls @ 00000251e5920700] Failed to open segment 37 of playlist 0
[hls @ 00000251e5920700] Opening 'http://frigate2.iot:5000/vod/retro/start/1657298493/end/1657357537/seg-38-v1.ts' for reading
[http @ 00000251e5948300] HTTP error 404 Not Found
[hls @ 00000251e5920700] Failed to open segment 38 of playlist 0
[hls @ 00000251e5920700] Opening 'http://frigate2.iot:5000/vod/retro/start/1657298493/end/1657357537/seg-39-v1.ts' for reading
[http @ 00000251e5948300] HTTP error 404 Not Found
[hls @ 00000251e5920700] Failed to open segment 39 of playlist 0
[hls @ 00000251e5920700] Opening 'http://frigate2.iot:5000/vod/retro/start/1657298493/end/1657357537/seg-40-v1.ts' for reading
[http @ 00000251e5948300] HTTP error 404 Not Found
[hls @ 00000251e5920700] Failed to open segment 40 of playlist 0
[hls @ 00000251e5920700] Opening 'http://frigate2.iot:5000/vod/retro/start/1657298493/end/1657357537/seg-41-v1.ts' for reading
[http @ 00000251e5948300] HTTP error 404 Not Found
[hls @ 00000251e5920700] Failed to open segment 41 of playlist 0
[hls @ 00000251e5920700] Opening 'http://frigate2.iot:5000/vod/retro/start/1657298493/end/1657357537/seg-42-v1.ts' for reading
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

irrelevant

**Comment by NickM-27** [comment]
Okay there's a few things to clear up.

1. The timestamp VOD uses Unix timestamps so make sure those are correct. 
2. If you're trying to get a full 24 hours of footage from it you'll likely need to do it with ffmpeg (not the endpoint but the command itself)

This is because the endpoint writes to cache and that'll likely fill up long before it can get all the way to 24 hours of footage

This endpoint is used in the frontend for viewing event clips / recordings so it is definitely not broken

**Comment by blakeblackshear** [comment]
The VOD endpoint doesn't write to cache. You are thinking of the mp4 endpoint. You may be running into some limitations on the maximum number of segments supported by VOD. Does it work with a smaller time period.

**Comment by vekexasia** [comment]
gotcha. so what would you suggest @blakeblackshear for my "daily backup" thing?

**Comment by blakeblackshear** [comment]
You would need to backup 12 or 6 hour blocks of time instead. Also, you could try setting your record retain mode to motion to reduce the number of segments.
