### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by divemasterjm** [blakeblackshear/frigate#3463]
### Describe the problem you are having

i had frigate running ok with cpu detectors, today i receive tpu usb coral, i plug it, and run lsusb with the result Bus 001 Device 002: ID 1a6e:089a Global Unichip Corp. , change docker to pass usb, config,yml to edgetpu usb and when i restart i have the following message 
Process detector:coral:
[2022-07-13 11:54:51] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 44, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0

im in ubuntu 22.04 LTS (GNU/Linux 5.15.0-39-generic x86_64), docker Docker version 20.10.14, build a224086349 and python3  3.10.4-0ubuntu2

can you please help me?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
s
```

### Relevant log output

```shell
Process detector:coral:
[2022-07-13 11:54:51] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 44, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Frigate stats

```json
{"cocina":{"camera_fps":4.26,"capture_pid":271,"detection_fps":0.0,"pid":242,"process_fps":0.0,"skipped_fps":0.0},"despacho":{"camera_fps":4.55,"capture_pid":253,"detection_fps":0.0,"pid":233,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":226}},"entradajardin":{"camera_fps":4.57,"capture_pid":290,"detection_fps":0.0,"pid":248,"process_fps":0.0,"skipped_fps":0.0},"garaje":{"camera_fps":4.64,"capture_pid":279,"detection_fps":0.0,"pid":245,"process_fps":0.0,"skipped_fps":0.0},"pasillo":{"camera_fps":4.49,"capture_pid":255,"detection_fps":0.0,"pid":237,"process_fps":0.0,"skipped_fps":0.0},"piscina":{"camera_fps":0.0,"capture_pid":287,"detection_fps":0.0,"pid":246,"process_fps":0.0,"skipped_fps":0.0},"salon":{"camera_fps":4.77,"capture_pid":268,"detection_fps":0.0,"pid":240,"process_fps":0.0,"skipped_fps":0.0},"salon2":{"camera_fps":4.6,"capture_pid":274,"detection_fps":0.0,"pid":243,"process_fps":0.0,"skipped_fps":0.0},"service":{"storage":{"/dev/shm":{"free":111.9,"mount_type":"tmpfs","total":134.2,"used":22.3},"/media/frigate/clips":{"free":389927.0,"mount_type":"vfat","total":999751.0,"used":609824.0},"/media/frigate/recordings":{"free":389927.0,"mount_type":"vfat","total":999751.0,"used":609824.0},"/tmp/cache":{"free":997.1,"mount_type":"tmpfs","total":1000.0,"used":2.9}},"temperatures":{},"uptime":6,"version":"0.10.1-83481af"},"terraza":{"camera_fps":4.42,"capture_pid":294,"detection_fps":0.0,"pid":250,"process_fps":0.0,"skipped_fps":0.0},"trasera":{"camera_fps":0.0,"capture_pid":260,"detection_fps":0.0,"pid":238,"process_fps":0.0,"skipped_fps":0.0},"traserapiscina":{"camera_fps":3.74,"capture_pid":300,"detection_fps":0.0,"pid":251,"process_fps":0.0,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

> Please use backticks to format these file contents
> 
> ```yaml your file contents ```
``` yaml motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
snapshots:
  enabled: true
  timestamp: false
  bounding_box: false
  crop: false
#  height: 360
  retain:
    default: 5
    objects:
      person: 5
record:
  enabled: True
#  fps: 15
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 14
      mode: motion
    pre_capture: 5
    post_capture:  10
detect:
  width: 640
  height: 360
  fps: 5
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for running detection on stationary objects (default: shown below)
    # When set to 0, object detection will never be run on stationary objects. If set to 10, 
    # it will be run on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered 
    # stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person,
    # but leave car at the default.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
    
#    - -hwaccel
#    - qsv
#    - -qsv_device
#    - /dev/dri/renderD128

#  hwaccel_args: -c:v h264_qsv

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - qsv
#    - -qsv_device
#    - /dev/dri/renderD128
#    - -c:v h264_qsv
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#ffmpeg:
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
detectors:
#  coral:
#    type: edgetpu
#    device: usb
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu  
  cpu4:
    type: cpu
  cpu5:
    type: cpu
  cpu6:
    type: cpu
  cpu7:
    type: cpu  
  cpu8:
    type: cpu
#database: 
#  path: /mnt/frigate/db/frigate.db
mqtt:
  host: 192.168.8.85
  user: mqttjuanma
  password: mqttjuanma
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
cameras:
  despacho:
    ffmpeg: 
      inputs:
        - path: 'rtsp://root:ismart12@192.168.8.193:554/unicast'
          roles:
            - detect
            - rtmp

            - record
    record:
      retain:
        days: 7
        mode: motion
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True
#      fps: 10

  pasillo:
    ffmpeg:
      inputs:
        - path: 'rtsp://root:ismart12@192.168.8.198:554/unicast'
          roles:
            - detect
            - rtmp

            - record
    record:
      retain:
        days: 7
        mode: motion
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True


  trasera:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.162:554/12'
          roles:
            - detect
            - record
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.162:554/11'
          roles:
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.8
    rtmp:
      enabled: True

  salon:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.31/ch0_0.h264'
          roles:
            - rtmp
      inputs:
        - path: 'rtsp://192.168.8.31/ch0_1.h264'
          roles:
            - detect
            - record
    record:
      retain:
        days: 7
        mode: motion
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True

  cocina:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.189/ch0_0.h264'
          roles:
            - rtmp
      inputs:
        - path: 'rtsp://192.168.8.189/ch0_1.h264'
          roles:
            - detect
            - record    
    record:
      retain:
        days: 7
        mode: motion        
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True


  salon2:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.221/ch0_0.h264'
          roles:
            - rtmp
            - record           
      inputs:      
        - path: 'rtsp://192.168.8.221/ch0_1.h264'
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True

 
  garaje:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.240/user=admin&password=admin&channel=1&stream=1.sdp?'
          roles:
            - detect
      inputs:
        - path: 'rtsp://192.168.8.240/user=admin&password=admin&channel=1&stream=0.sdp?'
          roles:
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 299,404,357,421,354,451,343,500,324,524,294,550,254,531,225,523,227,498,231,470,252,412,234,450,236,431
    zones:
      calle:
        coordinates: 1665,162,1665,0,1920,0,1920,240
      coche:
        coordinates: 1292,927,1148,968,1024,964,633,898,65,676,58,493,531,279,1452,319,1531,694
    objects:
      track:
        - person
        - car 
        - cat 
#        - bicycle
#        - motorcycle
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.74
    rtmp:
      enabled: True


#    zones:
#      Coche:
#        coordinates: 1515,976
#      Entradagaraje:
#        coordinates: 1920,300
  piscina:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.33/user=admin&password=admin&channel=1&stream=0.sdp?'
          roles:
            - rtmp
            - record
      inputs:
        - path: 'rtsp://192.168.8.33/user=admin&password=admin&channel=1&stream=1.sdp?'
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - cat 
    zones:
      agua:
        coordinates: 54,479,1696,862,1620,384,1334,336,1053,300,456,201
    rtmp:
      enabled: True


  entradajardin:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:RGOVKT@192.168.8.239//Streaming/Channels/101'
          roles:
            - rtmp
      inputs:
        - path: 'rtsp://admin:RGOVKT@192.168.8.239//Streaming/Channels/102'
          roles:
            - detect
            - record
    motion:
      mask:
          - '122,86,119,263,0,287,85,295,0,217,115,173,108,157,108,134,69,34,47,21,74,0,88,0,114,0,139,27,103,109,115,108,101,88,62,84,0,186,74,159,80,178,65,179,0,203,35,189,40,164,59,146,46,149,34,139,0,135,0,115,41,109,48,95,74,60,62,70,51,38,34,66,39,83,38,96,0,100,58,0,0,0,0,0,22,88,0,106,0,82,0,83,166,238'
    detect:
      width: 704
      height: 396
      fps: 5
    objects:
      track:
        - person
        - cat 
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.74
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #threshold: 0.7
    rtmp:
      enabled: True


  terraza:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:DRHPOK@192.168.8.138//Streaming/Channels/102'
          roles:
            - record
            - detect
      inputs:
        - path: 'rtsp://admin:DRHPOK@192.168.8.138//Streaming/Channels/101'
          roles:
            - rtmp
    detect:
      width: 704
      height: 396
      fps: 5
    objects:
      track:
        - person
        - cat 
    rtmp:
      enabled: True


  traserapiscina:
    ffmpeg:
#      input_args: -rtsp_transport udp      
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.181:554/12'
          roles:
            - detect
            - record
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.181:554/11'
          roles:
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #    min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.8
    rtmp:
      enabled: True 



docker compose
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/frigate/config/config.yml:/config/config.yml:ro
      - /mnt/grabador/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password". ```

**Comment by NickM-27** [comment]
In order to help we need to see your frigate config and docker compose config

**Comment by NickM-27** [comment]
Please use backticks to format these files

**Comment by divemasterjm** [comment]
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
snapshots:
  enabled: true
  timestamp: false
  bounding_box: false
  crop: false
#  height: 360
  retain:
    default: 5
    objects:
      person: 5
record:
  enabled: True
#  fps: 15
  retain:
    days: 14
    mode: all
  events:
    retain:
      default: 14
      mode: motion
    pre_capture: 5
    post_capture:  10
detect:
  width: 640
  height: 360
  fps: 5
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for running detection on stationary objects (default: shown below)
    # When set to 0, object detection will never be run on stationary objects. If set to 10, 
    # it will be run on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered 
    # stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person,
    # but leave car at the default.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
      # Optional: Object specific values
      objects:
        person: 1000
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
    
#    - -hwaccel
#    - qsv
#    - -qsv_device
#    - /dev/dri/renderD128

#  hwaccel_args: -c:v h264_qsv

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - qsv
#    - -qsv_device
#    - /dev/dri/renderD128
#    - -c:v h264_qsv
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
#ffmpeg:
#  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
detectors:
#  coral:
#    type: edgetpu
#    device: usb
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu  
  cpu4:
    type: cpu
  cpu5:
    type: cpu
  cpu6:
    type: cpu
  cpu7:
    type: cpu  
  cpu8:
    type: cpu
#database: 
#  path: /mnt/frigate/db/frigate.db
mqtt:
  host: 192.168.8.85
  user: mqttjuanma
  password: mqttjuanma
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects
cameras:
  despacho:
    ffmpeg: 
      inputs:
        - path: 'rtsp://root:ismart12@192.168.8.193:554/unicast'
          roles:
            - detect
            - rtmp

            - record
    record:
      retain:
        days: 7
        mode: motion
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True
#      fps: 10

  pasillo:
    ffmpeg:
      inputs:
        - path: 'rtsp://root:ismart12@192.168.8.198:554/unicast'
          roles:
            - detect
            - rtmp

            - record
    record:
      retain:
        days: 7
        mode: motion
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True


  trasera:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.162:554/12'
          roles:
            - detect
            - record
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.162:554/11'
          roles:
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.8
    rtmp:
      enabled: True

  salon:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.31/ch0_0.h264'
          roles:
            - rtmp
      inputs:
        - path: 'rtsp://192.168.8.31/ch0_1.h264'
          roles:
            - detect
            - record
    record:
      retain:
        days: 7
        mode: motion
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True

  cocina:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.189/ch0_0.h264'
          roles:
            - rtmp
      inputs:
        - path: 'rtsp://192.168.8.189/ch0_1.h264'
          roles:
            - detect
            - record    
    record:
      retain:
        days: 7
        mode: motion        
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True


  salon2:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.221/ch0_0.h264'
          roles:
            - rtmp
            - record           
      inputs:      
        - path: 'rtsp://192.168.8.221/ch0_1.h264'
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
    rtmp:
      enabled: True

 
  garaje:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.240/user=admin&password=admin&channel=1&stream=1.sdp?'
          roles:
            - detect
      inputs:
        - path: 'rtsp://192.168.8.240/user=admin&password=admin&channel=1&stream=0.sdp?'
          roles:
            - rtmp
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 299,404,357,421,354,451,343,500,324,524,294,550,254,531,225,523,227,498,231,470,252,412,234,450,236,431
    zones:
      calle:
        coordinates: 1665,162,1665,0,1920,0,1920,240
      coche:
        coordinates: 1292,927,1148,968,1024,964,633,898,65,676,58,493,531,279,1452,319,1531,694
    objects:
      track:
        - person
        - car 
        - cat 
#        - bicycle
#        - motorcycle
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.74
    rtmp:
      enabled: True


#    zones:
#      Coche:
#        coordinates: 1515,976
#      Entradagaraje:
#        coordinates: 1920,300
  piscina:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.8.33/user=admin&password=admin&channel=1&stream=0.sdp?'
          roles:
            - rtmp
            - record
      inputs:
        - path: 'rtsp://192.168.8.33/user=admin&password=admin&channel=1&stream=1.sdp?'
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - cat 
    zones:
      agua:
        coordinates: 54,479,1696,862,1620,384,1334,336,1053,300,456,201
    rtmp:
      enabled: True


  entradajardin:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:RGOVKT@192.168.8.239//Streaming/Channels/101'
          roles:
            - rtmp
      inputs:
        - path: 'rtsp://admin:RGOVKT@192.168.8.239//Streaming/Channels/102'
          roles:
            - detect
            - record
    motion:
      mask:
          - '122,86,119,263,0,287,85,295,0,217,115,173,108,157,108,134,69,34,47,21,74,0,88,0,114,0,139,27,103,109,115,108,101,88,62,84,0,186,74,159,80,178,65,179,0,203,35,189,40,164,59,146,46,149,34,139,0,135,0,115,41,109,48,95,74,60,62,70,51,38,34,66,39,83,38,96,0,100,58,0,0,0,0,0,22,88,0,106,0,82,0,83,166,238'
    detect:
      width: 704
      height: 396
      fps: 5
    objects:
      track:
        - person
        - cat 
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.74
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      #threshold: 0.7
    rtmp:
      enabled: True


  terraza:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:DRHPOK@192.168.8.138//Streaming/Channels/102'
          roles:
            - record
            - detect
      inputs:
        - path: 'rtsp://admin:DRHPOK@192.168.8.138//Streaming/Channels/101'
          roles:
            - rtmp
    detect:
      width: 704
      height: 396
      fps: 5
    objects:
      track:
        - person
        - cat 
    rtmp:
      enabled: True


  traserapiscina:
    ffmpeg:
#      input_args: -rtsp_transport udp      
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.181:554/12'
          roles:
            - detect
            - record
      inputs:
        - path: 'rtsp://admin:admin@192.168.8.181:554/11'
          roles:
            - rtmp
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - cat
      filters:
        person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      #    min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      #max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.8
    rtmp:
      enabled: True


docker compose
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-amd64
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/frigate/config/config.yml:/config/config.yml:ro
      - /mnt/grabador/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

**Comment by divemasterjm** [comment]
> Just copy all of the below and paste, then copy your entire file contents and overwrite the `file contents here` leaving the backticks and the yaml at the top
> 
> ```yaml your file contents ```

done, sorry, if done in the original message

**Comment by NickM-27** [comment]
after those logs above, what does `lsusb` look like?

**Comment by divemasterjm** [comment]
> after those logs above, what does `lsusb` look like?

Bus 001 Device 002: ID 1a6e:089a Global Unichip Corp.

**Comment by NickM-27** [comment]
I would just let it stop - start one to two times. You want to avoid restarting the host for now.

**Comment by divemasterjm** [comment]
> I would just let it stop - start one to two times. You want to avoid restarting the host for now.

this is my complete lsusb

Bus 002 Device 002: ID 0480:a200 Toshiba America Inc External USB 3.0
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0bda:565c Realtek Semiconductor Corp. Integrated_Webcam_HD
Bus 001 Device 005: ID 1a6e:089a Global Unichip Corp. 
Bus 001 Device 004: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by divemasterjm** [comment]
> 

i've tried in the other 2 usb plugs but still same problem

**Comment by NickM-27** [comment]
I wonder how much power the laptop USB ports are able to provide

**Comment by divemasterjm** [comment]
> Um, a nuc would be the best thing to try but I certainly don't want you to go to lots of effort if it isn't easy to try as I could be barking up the wrong tree with what is the issue here.

and what you suggest me? i'm out of tries

**Comment by divemasterjm** [comment]
> Um, a nuc would be the best thing to try but I certainly don't want you to go to lots of effort if it isn't easy to try as I could be barking up the wrong tree with what is the issue here.
this morning after many tries i have the following.:


detector | detection start | inference speed | pid
-- | -- | -- | --
coral | 0 | 10 | 226
cpu1 | 0 | 165.05 | 228
cpu2 | 0 | 145.78 | 231
cpu3 | 0 | 152.79 | 235
cpu4 | 0 | 174.59 | 237
cpu5 | 0 | 157.94 | 239
cpu6 | 0 | 138.55 | 241
cpu7 | 0 | 136.7 | 243
cpu8 | 1657779181.184923 | 145.71 | 245

but in host i cant see in lsusb google just Bus 001 Device 009: ID 1a6e:089a Global Unichip Cor
i run dpkg -l | grep edgetpu and result is
rc  libedgetpu1-max:amd64                 16.0                                    amd64        Support library for Edge TPU
actually i don't know if is working or not, i dont want to remove the cpy detectors and restart just if you want to make some tests before

**Comment by divemasterjm** [comment]
i've tried on nuc and same results

**Comment by NickM-27** [comment]
You may need to try to do some udev rules to force the coral to appear correctly and be recognized. I'll see if I can find a guide.

**Comment by NickM-27** [comment]
Here's the guide, mentions Pi but should work in your laptop case as well https://github.com/tensorflow/tensorflow/issues/32743#issuecomment-570811813

**Comment by NickM-27** [comment]
Another point of consideration is that you're using a USB cable capable of high data speeds and not just charging (not sure if yours came with a cable)

**Comment by divemasterjm** [comment]
> Another point of consideration is that you're using a USB cable capable of high data speeds and not just charging (not sure if yours came with a cable)

came with a cable, try udev rules as stated on guide, reboot but still same problem

**Comment by NickM-27** [comment]
Another thing I thought of, you might want to check your bios setting to see if there are any relating to USB, perhaps some compatibility is disabled

**Comment by divemasterjm** [comment]
> Another thing I thought of, you might want to check your bios setting to see if there are any relating to USB, perhaps some compatibility is disabled

I did this afternoon and I can't see anything, the only change I've made was powersafe on usb but same results

**Comment by divemasterjm** [comment]
> Another thing I thought of, you might want to check your bios setting to see if there are any relating to USB, perhaps some compatibility is disabled

i've tried with a new cable same as in the other comment, still the same

**Comment by NickM-27** [comment]
Might be worth asking for help in the coral GitHub repo, I am out of ideas

**Comment by divemasterjm** [comment]
change unit and now works from first time, thanks for your help
