### ISSUE TITLE
[Config Support]:  Google Coral USB not found by FRIGATE

### ISSUE THREAD

**Issue by roger561** [blakeblackshear/frigate#3470]
### Describe the problem you are having

I am not able to make the FRIGATE detect my GOOGLE CORAL USB, for all the attempts I made it always appears written: No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.

What I noticed in some forums was the detail referring to the HARDWARE ID of the pendrive is different from what FRIGATE looks for when it tries to locate a GOOGLE CORAL USB, the ID that is searched for would be the number: 18d1:9302 , since what is detected in my PC (I use UNRAID SERVER system) is the number : 1a6e:089a Global Unichip Corp.

How can I make FRIGATE be able to locate the GOOGLE CORAL USB flash drive plugged into the machine?

### Version

Current version: 3.1

### Frigate config file

```yaml
mqtt:
    host: 192.168.0.213
    port: 1883
    topic_prefix: frigate
    client_id: frigate
    user: roger561
    password: roger561
    stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb
    
database:
  path: /media/frigate/frigate.db

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:x1x2x3x4x5@192.168.0.65:554/Streaming/Channels/102/
          roles:
            - detect
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-07-14 16:42:34] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-07-14 16:42:34] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-07-14 16:42:34] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-07-14 16:42:34] peewee_migrate                 INFO    : There is nothing to migrate
[2022-07-14 16:42:34] frigate.app                    INFO    : Output process started: 215
[2022-07-14 16:42:34] frigate.app                    INFO    : Camera processor started for back: 218
[2022-07-14 16:42:34] ws4py                          INFO    : Using epoll
[2022-07-14 16:42:34] frigate.app                    INFO    : Capture process started for back: 219
[2022-07-14 16:42:34] ws4py                          INFO    : Using epoll
[2022-07-14 16:42:34] detector.coral1                INFO    : Starting detection process: 214
[2022-07-14 16:42:34] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-07-14 16:42:34] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral1:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 44, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

The camera image even appears even with this error, but the image is locked and I don't realize that Google Coral is working, since it was not located.

**Comment by NickM-27** [comment]
I use this with Unraid as well, is there any reason you are using frigate inside of the addon instead of through the frigate docker container? It will most likely be a lot easier that way since it doesn't need to go through the VM

**Comment by roger561** [comment]
> I use this with Unraid as well, is there any reason you are using frigate inside of the addon instead of through the frigate docker container? It will most likely be a lot easier that way since it doesn't need to go through the VM

I am newbie with UNRAID and HOME ASSISTANT, what I want was to integrate FRIGATE with HOME ASSISTANT to get notifications that frigate provides from cameras, at first I thought it would only be possible if I installed HOME ASSISTANT OS ,
but apparently it has the complete home assistant also with the supervisor function via DOCKER correct? no need to install a VM to be able to enjoy the full version of the home assistant, as the app store only has the CORE version (which is more limited).

**Comment by NickM-27** [comment]
> as the app store only has the CORE version (which is more limited).

This is not true, it is "more limited" for users that would run that on a RPi. But every addon is also in the Unraid app store. and the docker app for example supports all the same features

**Comment by NickM-27** [comment]
Either way, I'd seriously recommend installing frigate from the community store and just run it there

**Comment by roger561** [comment]
I tried to install FRIGATE and HOME ASSISTANT from the UNRAID APPS store and I can't activate FRIGATE it is always red stopped, remember I'm very new to this server system, I've never been used to using linux is my first contact, I didn't understand how to activate this FRIGATE service,
Will I need to do some configuration via command?

**Comment by NickM-27** [comment]
You will need to create the config.yaml file if you haven't already. The Unraid app defaults it to /appdata/frigate/config.yaml checkout https://docs.frigate.video to setup

**Comment by roger561** [comment]
> You will need to create the config.yaml file if you haven't already. The Unraid app defaults it to /appdata/frigate/config.yaml checkout https://docs.frigate.video to setup

inside this config.yaml file I must insert this information below, please check if the syntax is correct:

mqtt:
    host: 192.168.0.213
    port: 1883
    topic_prefix: frigate
    client_id: frigate
    user: roger561
    password: roger561
    stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb
    
database:
  path: /media/frigate/frigate.db

cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:teste123@192.168.0.65:554/Streaming/Channels/102/
          roles:
            - detect

**Comment by roger561** [comment]
could you tell me what is the ID of the google coral flash drive that your UNRAID detects when entering the command in the lsusb terminal?

18d1:9302  or   1a6e:089a Global Unichip Corp  ?

**Comment by NickM-27** [comment]
For me it shows as that when I plug it in then once frigate launches frigate will fail. On second launch it'll change to Google Inc. and will work

**Comment by simeon-walker** [comment]
I have just seen the same issue with a new Coral USB device. I am using podman on Ubuntu and started investigating possible USB passthough/permissions issues.
After reading this thread I re-enabled the config, restarted frigate, then it worked.
I also see the same change in lsusb output.

**Comment by Tokn59** [comment]
Any solutions here ? I have the exact same issue :

Process detector:coral:
[2022-08-05 19:30:04] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-08-05 19:30:04] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0

**Comment by NickM-27** [comment]
@Tokn59 You need to give more details otherwise there's no way to help. What is your OS, how are you running Frigate, can you see the USB device with `lsusb`, what type of coral are you running, etc.

**Comment by Tokn59** [comment]
Sorry about that ..
Running on Proxmov 7.x - Intel NUC
HASSOS latest build 2022.8.1
Supervisor 2022.07.0

USB ID Coral Device : Unkown (1a6e:089a)
Running Frigate Add On version 2.3
Using USB Coral
Config in frigate.xml :

detectors:
  coral:
    type: edgetpu
    device: usb  

Coral USB Accelerator - Edge TPU Coprocessor
lsusb on Proxmox shows : Bus 003 Device 004: ID 18d1:9302 Google Inc.

**Comment by Tokn59** [comment]
> @Tokn59 You need to give more details otherwise there's no way to help. What is your OS, how are you running Frigate, can you see the USB device with `lsusb`, what type of coral are you running, etc.

Sorry about that ..
Running on Proxmov 7.x - Intel NUC
HASSOS latest build 2022.8.1
Supervisor 2022.07.0

USB ID Coral Device : Unkown (1a6e:089a)
Running Frigate Add On version 2.3
Using USB Coral
Config in frigate.xml :

detectors:
coral:
type: edgetpu
device: usb

Coral USB Accelerator - Edge TPU Coprocessor
lsusb on Proxmox shows : Bus 003 Device 004: ID 18d1:9302 Google Inc.

**Comment by NickM-27** [comment]
And you're passing that bus into the HA OS VM right? Seems correct other than the VM can't see the usb device most likely

**Comment by Tokn59** [comment]
> And you're passing that bus into the HA OS VM right? Seems correct other than the VM can't see the usb device most likely

Yes it is configured as follows : 

Use USB Vendor/Device ID
Choose device id: unknown 1a6e:089a)

ALL OTHER usb devices are seen by the VM (Conbee, Aeotec Stick, USB SSD ... )

**Comment by NickM-27** [comment]
I would make your own issue and someone else who has done proxmox can hopefully help you, I don't use it so I don't know how to help past this point

**Comment by Tokn59** [comment]
> I would make your own issue and someone else who has done proxmox can hopefully help you, I don't use it so I don't know how to help past this point

BIG THANKS for trying to help me nevertheless !!!!
