### ISSUE TITLE
bounding_box dont work on snapshot event on  version 0.11.0-B36B635

### ISSUE THREAD

**Issue by exsatgit** [blakeblackshear/frigate#3471]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment]
Please elaborate as there is currently no detail at all. I am running the latest version and the bounding box on snapshots work the same as previous versions

**Comment by NickM-27** [comment]
Also this should be a support issue not a feature request

**Comment by exsatgit** [comment]
well, i have not change the config.yml when i upgrade, and the bounding box on snaphot was working fine. The issue i have now is, when i select the camera in UI, and i select events, there are a star on the snapshot. When i click on the snapshot it start play the video at same time. It dont show a snapshot with bounding box on. It just play the video at same time i select the snapshot

**Comment by exsatgit** [comment]
sorry for mistake and not use support issue

**Comment by NickM-27** [comment]
Yeah more detail would have helped, I see what you're saying now. That's been requested and pinned here: https://github.com/blakeblackshear/frigate/issues/3281
