### ISSUE TITLE
Different retention policies for the same camera based on zone

### ISSUE THREAD

**Issue by ediguidedog** [blakeblackshear/frigate#3487]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have different retention policies for the same camera based on zone. In other words my front camera covers both my front garden and the street and I want to retain any activity in my garden for 21 days. However being a ~~nosey~~ good neighbour I want to keep an eye on the street but only want to retain the recordings for say 3 days.

**Describe the solution you'd like**
Additional configuration options to define the retention period based on zone & object rather than just object types 

        record:
            events:
                required_zones:
                    - the roadway
                    - my path
                objects:
                    - person
                    - car
                retain:
                    zones: 
                        the roadway:
                             objects:
                                 car: 2
                                 person: 3
                        my path:
                              objects:
                                person: 21

Or another way if better as this may well lead to an exponential growth of the config files 

**Describe alternatives you've considered**
I can do this with a second camera utilising the rtmp feed from the first camera but it's messy and increases the processing load

**Additional context**
Hopefully this helps if I haven't explained. I want to retain events in my property for one period and outside retain for a different period
![Untitled-1](https://user-images.githubusercontent.com/73383390/179481859-1a4258fc-dd67-46d8-a208-262116a6c6f6.jpg)

**Comment by NickM-27** [comment]
How do you suggest this works if an object is detected in multiple zones?

I agree that exponentially growing config file is a concern, the request makes sense though

**Comment by ediguidedog** [comment]
> How do you suggest this works if an object is detected in multiple zones?
> 
> I agree that exponentially growing config file is a concern, the request makes sense though

I guess the longest zone retention policy would win. So to use my examples 
If someone was just in the roadway it would be 3 days but if they then stepped foot onto my path it would increase to 21

**Comment by eagleco** [comment]
Found this after searching for the same feature, here's another vote in support of zone specific retention configuration.

**Comment by nwish** [comment]
For what it's worth, I would like to see this implemented as well, with pretty much the same use case as the OP.

**Comment by ctml91** [comment]
Also interested in this for the same reason. Would like to retain events from the street for a shorter duration than events that take place on my property.

**Comment by bubba925** [comment]
I would be interested in this as well for the same reason. Currently only retain about 10 days of events but would probably keep the street retention even less.

**Comment by NickM-27** [comment]
This will be supported in 0.15 as alerts and detections can be given different retention configs
