### ISSUE TITLE
Add Support for Old Nvidia Graphics (Cuda 9.1) Nvidia Drivers nvidia-legacy-390xx-driver

### ISSUE THREAD

**Issue by wes1993** [blakeblackshear/frigate#3496]
**Describe what you are trying to accomplish and why in non technical terms**
Hello, could you add support for old Nvidia Graphic driver that support only Cuda 9.1?

**Comment by wes1993** [comment]
Thanks for your reply.
Can I install the beta from HassOs addon beta version?

**Comment by wes1993** [comment]
Thanks a lot, i have install this version from HassOS:
![image](https://user-images.githubusercontent.com/52070589/180047239-87184e7d-8cbc-41c3-96a1-b4c722d0eb00.png)


Should i set in the runtime nvidia or not?
If i do nvidia-smi
bash: nvidia-smi: command not found

ffmpeg -decoders | grep cuvid:
![image](https://user-images.githubusercontent.com/52070589/180047460-aa4685af-95f2-4300-ae64-e29326cce2ef.png)

Thanks a lot
Stefano

**Comment by NickM-27** [comment]
I'm not sure if that's possible in the addon, but the decoders are visible so should be able to add hwaccel to the config and fire it up

**Comment by wes1993** [comment]
Thanks again for your reply :-D
seems that won't work.. :-(

![image](https://user-images.githubusercontent.com/52070589/180053105-b03b171a-ec4e-4371-a949-ccbab30a4835.png)

Can't load ncuvid, can i test from my linux with some command?
