### ISSUE TITLE
Mask Editor to load existing masks for easier fine tuning

### ISSUE THREAD

**Issue by jonofmac** [blakeblackshear/frigate#3528]
**Describe what you are trying to accomplish and why in non technical terms**
When tweaking my masks, the mask editor always starts with none. So I must try to eye ball my previous mask. It would be much easier if the mask editor would load the existing masks in the config.yml for me to click on and edit.

**Describe the solution you'd like**
When opening the mask editor, parse/load the existing masks in the config.yml

**Describe alternatives you've considered**
If this is not possible, provide a way to paste an existing mask into the viewer for easy tweaking would work as well

**Comment by NickM-27** [comment]
Not sure what you mean, the mask editor already does this, just scroll down from the camera image and you'll see all the masks that currently exist in the config and you can click on one to edit it

**Comment by jonofmac** [comment]
You're absolutely right... I restarted my frigate and now the mask editor is doing this. I must not have restart, or switched to cameras without a mask. My mistake. Sorry for waste of your time

**Comment by NickM-27** [comment]
No problem, glad it's working 👍

**Comment by jonofmac** [comment]
Quick comment, it just did it again for me. It was chrome's cache.

Anyone having this issue, clear your chrome cache. Cleared it and the masks immediately showed up.
