### ISSUE TITLE
[Support]: NVIDIA, Frigate, Home Assistant, Unraid - How to integrate NVIDIA and Frigate

### ISSUE THREAD

**Issue by bocob5** [blakeblackshear/frigate#3530]
### Describe the problem you are having

My setup:
- Unraid Version: 6.10.3
- Home Assistant 2022.7.5 running in VM
  Supervisor 2022.07.0
  Operating System 8.2
  Frontend 20220707.1 - latest 
- Frigate NVR addon
  Current version: 2.3
- NVIDIA GeForce RTX 2060 SUPER

GOALS:
1. Use NVIDIA card for ffmpeg hardware acceleration
2.  Use NVIDIA card for ffmpeg hardware acceleration and object detection

First I would like to get working ffmpeg hardware acceleration only. However, I could not find any instructions, guide how to get this setup working on Unraid. Do I need to use passthrough for NVIDIA PCIe card or there are other option. And how to use then NVIDIA on Frigate that runs on Home Assistant? 
I will appreciate if someone can give me some directions where to start. 

Thanks

### Version

Frigate 2.3 / version  0.9.4

### Frigate config file

```yaml
Current config does not use NVIDA accelerator yet
```

### Relevant log output

```shell
No log output since setup is not running yet
```

### FFprobe output from your camera

```shell
ffprobe rtsp://admin:t0j3g3sl0@192.168.13.107:554//h264Preview_01_sub
ffprobe version 4.4 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://admin:t0j3g3sl0@192.168.13.107:554//h264Preview_01_sub':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_sub
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x352, 12 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink, ESP32 Cam, some XONZ modules

**Comment by NickM-27** [comment]
It is highly recommended to run Frigate in docker natively instead of through the HASS addon. Unraid already has nvidia drivers and nvidia-frigate build in the community apps store ready to be downloaded and setup where the docs give instructions: https://docs.frigate.video/configuration/nvdec

There is also Frigate 0.11 currently in RC which works with nvidia more simply but still requires the drivers to be installed from the community apps store.

**Comment by chrissiesparkle** [comment]
Agreed with @NickM-27 . That is how I run my setup with HA/Frigate/Unraid

**Comment by DrSpaldo** [comment]
Agreed with @NickM-27  . That is how I run my setup with HA/Frigate/Unraid
