### ISSUE TITLE
Add option for time format for web UI

### ISSUE THREAD

**Issue by Aculeasis** [blakeblackshear/frigate#3540]
WebUI shows 12-h format for Events, and it can't be changed.

Could you make it configurable? Something like:
```
web:
   time_format: "%m/%d/%Y %H:%M:%S %p"
```

![image](https://user-images.githubusercontent.com/42580940/181162004-530287f3-a0e3-4e50-afe1-29091d54697b.png)

**Comment by NickM-27** [comment]
This is a duplicate of #2629

**Comment by Aculeasis** [comment]
Thanks, I didn't  check the discussions.

**Comment by NickM-27** [comment]
Oh that's fair, I didn't realize it was a discussion. Either way, I already have a draft PR up https://github.com/blakeblackshear/frigate/pull/3309
