### ISSUE TITLE
Frigate clean up at specific times

### ISSUE THREAD

**Issue by narayanvs** [blakeblackshear/frigate#3541]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to set a time of the day for frigate to clean up the old recordings and clips. it appears like frigate cleans up old data every 10 mins which keeps the mechanical disks rotating all the time. 

**Describe the solution you'd like**
This will help to reduce frequency of disk spin up actitivity. Especially useful on platforms like unraid where we have an option to set when the disks are spun down when there are no activities. this will help to reduce the power consumption . 

**Describe alternatives you've considered**
Not sure if Frigate already support it. i couldn't find any leads from the documentation.

**Additional context**
Unraid has a disk for share and parity. when the files are chaged on the share disks, the currespoding parity has to be written on to parity disks as well. this means at least two disks are spinning all the time and increasing the disk wear and power consumption . being able to set a time will be helpful to overcome this so frigte files are cleaned only at speicified time intervals.

**Comment by NickM-27** [comment]
It is `record -> expire_interval` and is 60 minutes by default

**Comment by narayanvs** [comment]
Cool, thanks for this. i will check this option.
