### ISSUE TITLE
Event clip PNG files - can they be deleted?

### ISSUE THREAD

**Issue by jursed** [blakeblackshear/frigate#3544]
**Describe what you are trying to accomplish and why in non technical terms**
The clips directory contains duplicated screen grabs: one "raw" PNG, and then another (identical) JPEG overlaid with the object detection result.
My question: Is it possible to delete the PNG once the JPEG is created?
Justification: PNGs are huge, mine average 4-5 MB. With frequent events and a long retention period, I'm looking at 50+ GB of disk usage. And once the JPEG is available, the PNG is of no practical value.

**Describe the solution you'd like**
Delete the PNG immediately after the event pipeline has concluded, if possible.

**Describe alternatives you've considered**
I can make a cronjob to delete the PNGs manually, but I'd like to know that this won't break Frigate. (I'm unable to experiment with this at the moment, so I'd appreciate some insight from the devs.)

**Additional context**
Running Frigate 0.10.1-83481AF.

**Comment by NickM-27** [comment]
This isn't really how it works. The PNG is saved per the config, it isn't used or needed for anything. 

You can simply set `snapshots -> clean_copy` to `false` in the config and it will never be saved

I have just realized though this is not included in the full config docs so I will add it

**Comment by jursed** [comment]
Thank you Nick, that is precisely what I need.

**Comment by NickM-27** [comment]
I guess one update, in 0.11 (currently in RC) the snapshot will be needed to submit images to Frigate+ just FYI
