### ISSUE TITLE
[Support]: Native installation support

### ISSUE THREAD

**Issue by tweak19** [blakeblackshear/frigate#3565]
### Describe the problem you are having

Hi there,
I want ask if there is any way to made firgate available for native installations?
It would be possible to extract everything from the container and run it on bare metal but thats not what i supposed to do.

Are there any dependencies why its not available for native installation? I didn't like it to make an fully blown docker setup only for hosting firgate.
Please be so fine and share your opinion.

Thanks!

### Version

any

### Frigate config file

```yaml
not relevant
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

not relevant

**Comment by blakeblackshear** [comment]
It is very simple to install Docker and it's the only supported way to install Frigate. Think of it as needing to install Make to build from source. You could try looking at the Dockerfile and installing on bare metal, but it would be entirely unsupported. When it is time to upgrade, you would likely need to rebuild your bare metal setup from scratch.

**Comment by tweak19** [comment]
Thanks for your information.
Still hope that you will support in anytime bare metal.
Because for me Docker isn't the prefered method for large scaled setup and as may needed for high performance storage and network.
Yes if you need to compile frigate it would be more complex. But it would also be possible to make the packages for DEB/RHEL
