### ISSUE TITLE
Add camera recording FPS rate to debug page

### ISSUE THREAD

**Issue by RexWheeler** [blakeblackshear/frigate#3567]
I have my cameras set to record all of the time and as an aid in managing storage space and camera configuration, it would be useful to be able to see in one place the recording frame rate (fps) for each camera. 

My frame rate configuration is done on the cameras themselves and I use different frame rates for the different streams that are ultimately used for motion/object detection and for recording. To review my current recording frame rate configuration, I either need to look at the individual camera cameras or use ffprobe. 

The Debug page currently shows the image processing rate, so this would be a convenient place to also show the recording rate.

**Comment by NickM-27** [comment]
The recording stream is not decoded, unlike the detect stream which is what is used for these state.

I don't think there would be a way to know how many fps the recording stream is containing, we just stream the data right into a .mp4 file

**Comment by RexWheeler** [comment]
Okay thanks.
