### ISSUE TITLE
[Config Support]: Documentation for frigate.yml is inconsistent

### ISSUE THREAD

**Issue by tensiondriven** [blakeblackshear/frigate#3571]
### Describe the problem you are having

The frigate configuration example at https://docs.frigate.video/configuration/index appears to be missing the following under the config for each camera:

```
    detect:
      width: 1280
      height: 720
```

The width/height for each camera is listed elsewhere in the documentation, such as [here](https://docs.frigate.video/guides/getting_started) and here.

Fix: Update the main config example with either a comment or more information to include all available keys (or a comment that they are inherited).

I found this while researching a problem with my RTMP restreams and was left wondering if I am missing keys for the roles (detect, rtmp, record), which is how I found it.  If the documentation was a little more explicit, I think it would help people like me who are trying to piece things together.

### Version

0.10.1-83481AF

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
To me this would be redundant. Every option at the top level of the config has `# NOTE: Can be overridden at the camera level` which is what indicates that it can be customized for each camera.

Really, if a user had 12 of the same camera then that would not need to be defined for each camera at all.

**Comment by tensiondriven** [comment]
Ahh, got it.  Not sure how I missed that, or failed to make the mental connection.  Thank you
