### ISSUE TITLE
[Config Support]: Failed to connect

### ISSUE THREAD

**Issue by marcgarciamarti** [blakeblackshear/frigate#3579]
### Describe the problem you are having

Hello,

I've just configured the repository via HACS and attempted to install the integration. However, HA can't seem to be able to connect with the integration. The error message that I see says: "Failed to connect"

If I try to telnet from the host into the container on port 5000, talent won't be successful either.

### Version

NaN

### Frigate config file

```yaml
I have not yet managed to get past the installation menu
```

### Relevant log output

```shell
I have not yet managed to get past the installation menu
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

![Captura de pantalla 2022-08-03 a les 10 10 10](https://user-images.githubusercontent.com/12695572/182559468-552653e6-2ebd-489e-857b-cf8595bbaf9f.png)

**Comment by marcgarciamarti** [comment]
I just realised I can install this via add-on store. Will close this issue.

**Comment by NickM-27** [comment]
Yes, frigate must be installed for the integration to have something to connect to 👍
