### ISSUE TITLE
Contribute to the translation of the web interface

### ISSUE THREAD

**Issue by elax46** [blakeblackshear/frigate#3582]
Hello I was reading the [contribution ](https://docs.frigate.video/contributing/#web-interface)section for the web section but I did not find information for the translation of the web interface I wanted to help

**Comment by NickM-27** [comment]
We don't currently have the infrastructure for translations in place, all the strings are hardcoded currently. Happy to accept PRs to adapt to use translations (seems [this](https://blog.shahednasser.com/how-to-internationalize-a-react-app/) is how it is done in react, but not 100% sure myself). 

If you are just looking to do translations and not the web part, may be some time until this is supported

**Comment by elax46** [comment]
If you know which is the best internationalization solution for the project I can help you but I repeat it depends on the solution you want to adopt (for example HA use lokalise)

**Comment by NickM-27** [comment]
@blakeblackshear have you looked into this at all / have an opinion?

**Comment by elax46** [comment]
@NickM-27 I opened a request on your [branch ](https://github.com/NickM-27/frigate/pull/1)
