### ISSUE TITLE
UI for editing config.yml

### ISSUE THREAD

**Issue by werkstrom** [blakeblackshear/frigate#3587]
**Describe what you are trying to accomplish and why in non technical terms*
When setting up (or tuning) Frigate I would very much like to be able to do that, easily from within the UI.
IMHO a UI for editing the config.yml file would be an enormous improvement to accessibility of Frigate.  

**Describe the solution you'd like**
So, adding an ACE or Monaco (or alike) editor for the config.yml file would ease the process of tuning and editing the setup. In Home Assistant this is easier as one can utilize the VS or FileEditor tools within HA to do, but for me, who run HA on a RPi and wanted to run Frigate on a separate server that ability is not available. Also, it is not entirely a solution, more of a work around. 

**Describe alternatives you've considered**
As of now I assume I have to edit the file on the server, which is not intuitive (or at accessible), IMHO

**Additional context**

**Comment by evanheckert** [comment]
I think the include solution linked above is a great step forward, though I'd suggest a hybrid of sorts in the interest of accessibility mentioned in the OP of this issue:

Initial setup is still done with docker and a single config file. Then in the UI, allow the user to edit settings that are saved in persisted storage and function as overrides where it overlaps entries in config.yml.

This proposal is agnostic to whether the overrides are done in a YAML experience in a browser-based editor, or a full GUI workflow. That said, it does allow more flexibility in the transition between the two.

If Frigate wants to move to a UI-driven config in the long term, this could also allow a smooth, take-your-time transition. People who still want to edit their config.yml as they do now can still do so, while the number of config items that are possible in the UI can grow over time.

**Comment by NickM-27** [comment]
Closing this as monaco is included in the webUI in 0.12
