### ISSUE TITLE
Application not stopping on error in setup

### ISSUE THREAD

**Issue by werkstrom** [blakeblackshear/frigate#3588]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to start Frigate, even though the config file is not valid or missing. 

**Describe the solution you'd like**
In combination with ticket #3587 making the Frigate UI open, allowing you to edit the config.yml file (and perhaps even create it if it was missing) would, IMHO lower the initial threshold for setting up Frigate. 

Something in the lines of "Frigate configuration data cannot be used, please edit it here" along with a link to the documentation and any information from the logs that might help.

**Describe alternatives you've considered**
Today I check the log for errors, then rectifying them using an external editor. Working, but not particularly streamlined IMHO.

**Additional context**

**Comment by NickM-27** [comment]
I don't think this makes sense. We really don't ever want frigate starting in a bad state with an unknown configuration.

To me, starting with a basic config the user can have frigate running and then simply allowing the UI config editor to not overwrite (save) the file unless it is considered valid (which can already be known using the Pydantic JSON schema) would make it workable.

**Comment by werkstrom** [comment]
@NickM-27 Thanks for commenting. I agree. The thing is to get some sort of interactive thing up instead of simply shutting down. My suggestion was to start some sort of UI and force the user to set up a config that is valid before "main" Frigate starts. Your suggestion is to generate some sort of base config.yml file if it is not present. I would agree both solutions would achieve the same goal.

Two considerations: 

1. How would the "minimal" config file be generated? i.e. what values should be added so that Frigate starts using these "fake values". Could surely be done, just wondering.
2. What if the config file is edited outside of Frigate (as it is possible). I guess Frigate can't generate a new "generic" config.yml in this case as it would overwrite the old config.yml file...

Again, IMHO these two scenarios would be covered by a solution that stopped short of starting Frigate if the config.yml was not uasable (for any reason) and presented it in a UI for the user to edit.

**Comment by NickM-27** [comment]
I wasn't necessarily suggesting that frigate fill in a default config file, we require MQTT so it wouldn't really be able to fill in an MQTT server correctly.

The way I see it, anyone setting up frigate in docker is setting up the container and mapping the config file to the container so it ought to exist at least in a minimal form and then use the built in editor to expand past that.

If the file doesn't exist and the user mapped `/whatever/dir/config.yaml:/config/config.yaml:rw` to frigate then `config.yaml` becomes a directory anyway which is its own issue, so most users would at least have the easy access after structuring the docker container to setup a basic config.yaml file and make sure the container starts.

I definitely see the UI editor with schema validation being a value add, this change would at the very least require a lot of reorganization / restructuring of how frigates startup logic works today to get it to work like that.

**Comment by werkstrom** [comment]
@NickM-27 I think we are on the same page and I fully agree the UI-editor has infinitely more value. I'm fine with laying this issue to rest as my instance is now up and running.
