### ISSUE TITLE
Request Golf Cart Object Detection

### ISSUE THREAD

**Issue by dmkjr** [blakeblackshear/frigate#3592]
**Describe what you are trying to accomplish and why in non technical terms**
I would like an object detection of a golf cart.  We have a lake house where the mode of transportation is typically by golf cart.  Would like to record those objects.

**Describe the solution you'd like**
Detection object of "Golf Cart"

**Comment by NickM-27** [comment]
`car` would likely work alright even though it is a golf cart. The current model is from the Google Coral test data so we don't have a way to change that. [Frigate+](https://frigate.video/plus/) is coming and eventually will have the ability for users to train their own labels that they want for less popular labels that don't apply to everyone, so Golf Cart label could be added by yourself there once that is available.

**Comment by rhatguy** [comment]
My golf cart gets detected as a car frequently in my yard using the
standard models.  I think until frigate+ comes you'll at least get
recordings (detected as cars) with the existing models.

**Comment by heffneil** [comment]
I don't know if I can re-open this.  I would LOVE to have a golf cart object to filter out cars vs golf carts.

**Comment by ehn** [comment]
I'm not sure when it was added, but `golf cart` is now a candidate label for Frigate+.

**Comment by heffneil** [comment]
Oh thats interesting news! The problem is I think if I add it I need to re-analyze the thousands of images I currently submitted?

**Comment by NickM-27** [comment]
~~You don't need to but the model might perform worse if there are golf carts in the older images that have not been labeled.~~

The UI in Frigate+ has been adjusted so new images appear separately from existing images.

**Comment by blakeblackshear** [comment]
To clarify, it might perform worse in the future when `golf_cart` graduates to a full label. When that happens, there will likely be a backend process to automatically go through users images for `car` and suggest which ones should be updated to `golf_cart`. I don't recommend going back through all images to make corrections for candidate labels.

**Comment by heffneil** [comment]
I think the problem is frigate+ shows images that need approval once you add a tag? Am I misunderstanding this?  I feel like this has been discussed - its just clear as mud to me.

**Comment by ehn** [comment]
Related to the golf cart discussion, PostNord, the postal service in Denmark and Sweden, uses these [delivery vehicles](https://www.clubcar.com/en-us/club-car-urban-supports-sustainable-logistics-cold-climate):

<img width="400" height="225" alt="Image" src="https://github.com/user-attachments/assets/3dace85d-35c4-4a9f-89e7-11d734c18a4d" />

They are built on a golf cart platform. My Frigate instance sometimes detects them as `car`. Should I label them as `golf cart` in Frigate+?
