### ISSUE TITLE
[Support]: HASSOS on PROXMOX / Frigate does not find Coral Edge TPU USB device

### ISSUE THREAD

**Issue by Tokn59** [blakeblackshear/frigate#3593]
### Describe the problem you are having

Frigate reports "frigate.edgetpu ERROR : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors."

### Version

2.3

### Frigate config file

```yaml
#--------------------------------------------------------------------------------------------------------  
detectors:
  coral:
    type: edgetpu
    device: usb  
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
#-----------------------------------------------------------------------------------------------------------------------
```

### Relevant log output

```shell
process detector:coral:
[2022-08-05 19:30:04] frigate.edgetpu INFO : Attempting to load TPU as usb
[2022-08-05 19:30:04] frigate.edgetpu ERROR : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
delegate = Delegate(library, options)
File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in init
raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector
object_detector = LocalObjectDetector(
File "/opt/frigate/frigate/edgetpu.py", line 64, in init
edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Several all working fine without Coral TPU

### Any other information that may be helpful

Configuration :

Running on Proxmox 7.x - Intel NUC
HASSOS latest build 2022.8.1
Supervisor 2022.07.0

USB ID Coral Device : Unkown (1a6e:089a)
Running Frigate Add On version 2.3
Using USB Coral
Config in frigate.xml :

detectors:
coral:
type: edgetpu
device: usb

Coral USB Accelerator - Edge TPU Coprocessor
lsusb on Proxmox shows : Bus 003 Device 004: ID 18d1:9302 Google Inc.

**Comment by NickM-27** [comment]
I would specify in the title that it's proxmox 👍

**Comment by Trakkasure** [comment]
is this a VM, LXC container, or docker within an LXC or VM?
Each has its own way to get the USB device.

**Comment by Tokn59** [comment]
It is a vm … all other connected usb devices are working fine.

**Comment by claustro** [comment]
I solved manually config an usb filter following this tutorial https://dev.to/0xkoji/coral-edgetpu-usb-with-virtualbox-57e1

**Comment by Tokn59** [comment]
Update : I got it to work by changing the way the USB port is configured in Proxmox. Normally (and recommended) you use "Use USB Vendor/Device ID" but that doesn't work. When I configure it as "Use USB Port" - "Choose USB Port" it does work and Frigate finds it. However that is not the preferred method AFAIK and it should work the other way as well.

**Comment by NickM-27** [comment]
> However that is not the preferred method AFAIK and it should work the other way as well.

The coral is an odd device, unlike simpler usb devices like a zigbee coordinator that load and firmware is interfaced with. The coral usb loads an interval driver and as it's plugged in be vendor / device id change which is likely what's causing the issue just passing a specific one through.
