### ISSUE TITLE
Required_Zones clarification[Support]: 

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3597]
### Describe the problem you are having

Please can you clarify the purpose and function of -required_zones in events for me?

If I have:

required_zones:
 - zone_1
 - zone_2
 - zone_3

Does this mean that detection is required in all three zones to trigger an event or in any of the three zones?

If it's the latter, how do, or can I, achieve the former within Frigate config?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
Setting required zones as a list of multiple, any of them will trigger the event. 

Otherwise, you'd just want to set the furthest one as required so the other two will be tracked but no event created until the furthest zone is entered

**Comment by ripvega** [comment]
Thank you.
Will this over come this problem?

I have three zones (maybe only two are needed) on our car parking area.
When a vehicle arrives and parks an event gets triggered.

However, if the light changes where the vehicle is parked an event gets triggered again, as if it's a new vehicle.

**Comment by NickM-27** [comment]
If you provide a picture from the debug screen (with bounding boxes and your current zones) I can give a specific suggestion. 

Otherwise https://docs.frigate.video/guides/stationary_objects seems to be what you're referring to

**Comment by ripvega** [comment]
Thank you. What do you need that's different from the above.

There are three zones above showing as blue to the rear, yellow and then orange to the front.

**Comment by NickM-27** [comment]
If it looks very similar to the link I mentioned then just follow that, but if it is different then I'd need to see a snapshot to really be able to make a recommendation

**Comment by NickM-27** [comment]
Sorry I was on mobile and it didn't load the picture for some reason

**Comment by NickM-27** [comment]
You will need to post your config files so I can understand how you have it setup currently

**Comment by ripvega** [comment]
`  car_park: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:*@10.0.1.42:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://admin:*@10.0.1.42:554/cam/realmonitor?channel=1&subtype=0 # <----- Update for your camera
          roles:
            - record
            # - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          threshold: 0.6
          min_score: 0.76
        car:
          threshold: 0.6
          min_score: 0.7
          mask:
            - 280,160,348,209,403,125,408,99,301,90,279,103         
        dog:
          threshold: 0.5
          min_score: 0.6
    motion:
      mask:
        - 640,0,0,0,0,39,187,21,326,29,280,89,288,172,447,346,493,139
    # zones:
    #   carpark:
    #     coordinates: 640,480,0,480,0,211,57,175,190,79,290,96,284,164
    #   top_of_drive:
    #     coordinates: 254,39,304,49,293,87,209,76
    zones:
      carpark_south:
        coordinates: 640,480,0,480,0,211,57,175,85,151,284,164
      top_of_drive:
        coordinates: 254,39,304,49,293,87,209,76
      carpark_north:
        coordinates: 291,169,273,93,198,70,102,164
    record:
      enabled: True
      retain:
        days: 2
        mode: all
      events:
        required_zones:
          - carpark_north
          - carpark_south
          - top_of_drive
        retain:
          default: 5
          mode: motion
        pre_capture: 3
        post_capture: 15
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: true
      height: 500
      retain:
        default: 5
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500
      quality: 100`

You'll notice that I have 'person' and 'dog' as objects to track also and I'd like to see events for those in any zone.

**Comment by NickM-27** [comment]
Okay, I'm not sure why the light changing would be creating a new event since the car should be easily in the zone (unless one of the cars partially visible is moving between detected and not detected.

> You'll notice that I have 'person' and 'dog' as objects to track also and I'd like to see events for those in any zone.

Then you'll probably want to make both of the zones in the `required_zones` list but then just make the closest one the only zone that tracks `car`

**Comment by ripvega** [comment]
>  just make the closest one the only zone that tracks car

That's new to me I think. Can you point me at a config example of who to do that? I thought events referred to all objects and zones and couldn't be filtered.

**Comment by NickM-27** [comment]
You can check it out at the full config https://docs.frigate.video/configuration/index

Specifically:

```yaml
    # Optional: zones for this camera
    zones:
      # Required: name of the zone
      # NOTE: This must be different than any camera names, but can match with another zone on another
      #       camera.
      front_steps:
        # Required: List of x,y coordinates to define the polygon of the zone.
        # NOTE: Presence in a zone is evaluated only based on the bottom center of the objects bounding box.
        coordinates: 545,1077,747,939,788,805
        # Optional: List of objects that can trigger this zone (default: all tracked objects)
        objects:
          - person
        # Optional: Zone level object filters.
        # NOTE: The global and camera filters are applied upstream.
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
```

**Comment by ripvega** [comment]
Thank you!
