### ISSUE TITLE
[Support]: issue with dashboard

### ISSUE THREAD

**Issue by heapxor** [blakeblackshear/frigate#3602]
### Describe the problem you are having

hi.
i am running haas in VM and frigate is installed as addon ... i can see via overview camera/movement but when i go to Frigate section right area is empty ... there is nothing inside the logs... any idea?

![image](https://user-images.githubusercontent.com/64676/183300577-23b709a7-c7ff-41ef-bd7f-0cb81ead366b.png)

frigate plugin log>
`[2022-08-07 18:15:06] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:58620]
[2022-08-07 18:17:02] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:58620]`

thanks

### Version

-

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
What version of frigate are you running?

**Comment by heapxor** [comment]
@NickM-27 Addon version is 
Frigate NVR
Current version: 3.1 (Changelog)

**Comment by NickM-27** [comment]
Thanks, what do your browser logs say when viewing that page?

**Comment by heapxor** [comment]
@NickM-27 what do u mean by browser logs? or how can i access/enable? thanks!

**Comment by heapxor** [comment]
@NickM-27 i  reopened it again in non private browser and it works ! uhm sorry :( no clue why it doesnt work in private browser.

**Comment by NickM-27** [comment]
Private browser as in what? That is interesting

**Comment by heapxor** [comment]
private browsing window in Firefox sorry

**Comment by NickM-27** [comment]
I see, might need to raise the issue with home assistant frontend, I don't believe there's anything frigate can do
