### ISSUE TITLE
Frigate media browser clips not working with other players

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#361]
@blakeblackshear first I really like the HA Integration and thanks again for all your work.
The clips are working and I can play inside the browser but when I choose chromecast as player and click on the clips icon, it shows following error -
![image](https://user-images.githubusercontent.com/7528001/101839094-9fa9c000-3af6-11eb-9356-e175cbf83afa.png)

_Originally posted by @bm55 in https://github.com/blakeblackshear/frigate/discussions/360_

**Comment by drinfernoo** [comment]
Can confirm, I have the same issue on 0.8.0-beta2.

**Comment by thundergreen** [comment]
I was wondering ans searching how to acces this media browser at all?? someone here who can ojnt me in the right direction please?

**Comment by drinfernoo** [comment]
> I was wondering ans searching how to acces this media browser at all?? someone here who can ojnt me in the right direction please?

Do you mean to access the media browser in general? Besides showing in the default sidebar, you can find it at `http://your_ha_host:port/media-browser`.

**Comment by thundergreen** [comment]
> > I was wondering ans searching how to acces this media browser at all?? someone here who can ojnt me in the right direction please?
> 
> Do you mean to access the media browser in general? Besides showing in the default sidebar, you can find it at `http://your_ha_host:port/media-browser`.

Do i Have to activate this browser somehow? I get 404 not found error. What do ia have to do to get this media browser working?

**Comment by drinfernoo** [comment]
Is this issue resolved in a recent release?

**Comment by blakeblackshear** [comment]
I believe so. I was able to reproduce and fix.
