### ISSUE TITLE
Setting of disk space to use and location to save the files in

### ISSUE THREAD

**Issue by elektrinis** [blakeblackshear/frigate#3625]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to:
1. set the location where the recordings should be saved
2. Set the limit of space it can take.

**Describe the solution you'd like**
1. introduce a setting record -> location (with option to record to other local drive at least)
2. introduce a setting record -> size (0 means all free space, newest file removes oldest (FIFO))

**Describe alternatives you've considered**
I thought about running a script that scans the directory and deletes old files, hut it won't update the database.

**Additional context**
This is really basic, I'm not asking much.

What's the ETA for this feature? Someone said it will be on v0.11. But will it?

**Comment by NickM-27** [comment]
> introduce a setting record -> location (with option to record to other local drive at least)

this is already possible with standard docker volume mounts

> introduce a setting record -> size (0 means all free space, newest file removes oldest (FIFO))

This is a duplicate request of #994

**Comment by elektrinis** [comment]
> > set the location where the recordings should be saved
> > introduce a setting record -> location (with option to record to other local drive at least)
> 
> this is already possible with standard docker volume mounts

how?


> > Set the limit of space it can take.
> > introduce a setting record -> size (0 means all free space, newest file removes oldest (FIFO))
> 
> This is a duplicate request of #994
Well that one is locked and there is no way to ask when it will be done. Somewhere was promised for v0.9, then pushed to v0.10, then 11. There is a release candidate already and I don't see this among changes.

**Comment by NickM-27** [comment]
> how?

A good start is here: https://docs.frigate.video/installation#storage and a more generic guide is in the docker docs https://docs.docker.com/storage/volumes/

> Well that one is locked and there is no way to ask when it will be done. Somewhere was promised for v0.9, then pushed to v0.10, then 11. There is a release candidate already and I don't see this among changes.

Right, it is not in 0.11, hoping to get it into 0.12

**Comment by NickM-27** [comment]
Closing as these are implemented or have an existing issue. Feel free to make a new issue on any questions about implementing the above mentioned functionality 👍
