### ISSUE TITLE
Authentication and RBAC for UI Access

### ISSUE THREAD

**Issue by lostangel556** [blakeblackshear/frigate#3633]
I would like to see the following implemented for access control to/in the UI
- Authentication for access to the UI. Ability to login to the UI with local accounts and/or OAUTH authentication as currently the CCTV system and its configs are open to all users on the network (Exposing the Authentication for the cameras in plain text as Debug is exposed)
- Role Based Access Control. Allow definition of user groups that grant access to view specific sets of cameras. This would allow a single installation to be able to grant access to different users that do not need to see each other's cameras. Current way around this is multiple installations but this becomes difficult to manage at scale and more memory intensive.

So far to secure the deployment I've implemented Basic Authentication on the Ingress Controller as per https://kubernetes.github.io/ingress-nginx/examples/auth/basic/ but implementing authentication in this manner is an all or nothing approach.

**Comment by blakeblackshear** [comment]
For auth, it's more likely that there will be a way to disable the admin like features so using oauth2_proxy or something similar meets the needs of 99% of users.

Can you talk a little more about your use case for multiple users who can't see each other's cameras?

**Comment by lostangel556** [comment]
Sure,
Use case is that on a single location we may have multiple cameras for multiple areas. While we may want a single application to perform object detection and manage the tensorflow models ran on a particular camera we wont want every user to be able to see every camera. 
e.g. we might have operator 1 that works in area A and operator 2 that works in area B as well as an admin that ensures system functionality. Operator 1 would need visibility to view the items of interest in area A but is not authorised for area B.   Similar for operator 2, but with the admin they will need visibility over all to ensure uptime.

**Comment by blakeblackshear** [comment]
Is this a need for a business or a need for a centralized system for apartments or other residential settings?

**Comment by lostangel556** [comment]
It could be for any. The ability to separate cameras out by areas and grant specific users the ability to view that area could be used for commercial or residential use cases.

**Comment by blakeblackshear** [comment]
So this is a hypothetical use case?

**Comment by lostangel556** [comment]
well, I have a real world use case but cant really get into it on a public forum

**Comment by lunarok** [comment]
for authentication, for me, that's not really needed, because it's very easy to protect it with for exemple traefik+authelia (that's my conf, so it's protected on network and outside)
for rbac, it could be a plus, imagine in a family, you want allow kids access without having them access some cam. Or going on holidays, letting access to neighbor or family to check.

**Comment by BobTB** [comment]
-- Or going on holidays, letting access to neighbor or family to check. --

This is a real use case, I don't want neighbor/family to see my bedroom camera for example, but I want to :)

**Comment by lostangel556** [comment]
My real world use case for RBAC would like the following.
I want to perform object detection on multiple cameras across a building however rather than granting global access to the entire fleet of cameras person1 only needs to see a subset. Person2 might need a different subset whereas person3 might need access to them all

**Comment by skupi20** [comment]
Role Based Access Control will be nice, at least simple one for start. Later more complex, proxy could be use for ssl/domain access or vpn. But division role for specific user seeing for example live view of chosen camera, access to config or modify stored media.

Simply version could be for example only admin password for changing configuration or modify stored media from web gui.
Implementation of complex RBAC need more time, but simple admin/rest_users division for start will be useful feature for me or others maybe too.

**Comment by mabnz** [comment]
I have 10 cameras at home, covering different areas of my property. It would be ideal to be able to give my neighbours access to a couple which cover public areas as we've had a few burglaries and providing access to certain areas via RBAC would be ideal.

**Comment by NickM-27** [comment]
see https://github.com/blakeblackshear/frigate/issues/6614
