### ISSUE TITLE
[Support]: not sure if thats a bug - found in dmesg inside HAAS

### ISSUE THREAD

**Issue by heapxor** [blakeblackshear/frigate#3642]
### Describe the problem you are having

hello,
looking into the latest version of HAAS dmesg log ... there are following messages regarding the google coral device... 
is that usb hub issue? or just can be ignored?

[ 1239.838607] usb 2-2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 2036.022206] usb 2-2: reset SuperSpeed USB device number 4 using xhci_hcd
[ 2036.035762] usb 2-2: LPM exit latency is zeroed, disabling LPM.
[ 2788.905505] usb 2-2: reset SuperSpeed USB device number 4 using xhci_hcd
[ 2788.919238] usb 2-2: LPM exit latency is zeroed, disabling LPM.

thanks!

### Version

latest

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
Is your coral not working as expected? This looks like standard log output to me

**Comment by heapxor** [comment]
@NickM-27 hard to say how to find out - if its working as expected. is it possible to find out somehow? thanks

**Comment by NickM-27** [comment]
> @NickM-27 hard to say how to find out - if its working as expected. is it possible to find out somehow? thanks

If you have the coral set in the config and frigate is running then it's working as expected. The coral is a very simple device, if it's not working as expected then it's not working at all
