### ISSUE TITLE
[Support]: Notifications do not work when running Frigate using NVR Proxy

### ISSUE THREAD

**Issue by jambuu** [blakeblackshear/frigate#3645]
### Describe the problem you are having

I am currently running Frigate via docker compose and Home Assistant via VirtualBox VDI. Therefore, I am accessing frigate via the reverse proxy add-on.

My problem is about the home assistant notification. The blueprint did not work and I initially suspected on the mqtt message, so, I decided to observe that event manually and dispatch the notification based on the mqtt frigate events. This works! but without the thumbnail :(

The problem with thumbnail lies in the reverse proxy add-on which does not propagate the internal endpoint externally.

# The documentation

The [documentation](https://docs.frigate.video/guides/ha_notifications) for sending notification states that the thumbnail should be reachable via this address:

```yaml
image: 'https://your.public.hass.address.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
```

which I initially found it odd since this address would collide with [home assistant rest api address](https://developers.home-assistant.io/docs/api/rest/) which requires oauth2-based authentication (i.e. long-term token). When I didn't see the Bearer token being passed, I realized that api address was not what I was looking for.

# Also the documentation

So, now I decided to go back to the [documentation](
https://docs.frigate.video/integrations/api/#get-apieventsidthumbnailjpg) to see how to get the thumbnail from frigate directly and I discovered that the api address is for the machine where frigate is running (which kinda makes sense). Now, when I access this path, voilà, the thumbnail appears. Notice though how both address differ.

```yaml
http://192.168.178.42:5000/api/events/1660507956.719384-tzbdr2/thumbnail.jpg?format=android
```

# How to proceed?

- I could attempt to reverse proxy this machine myself using nginx but this would expose the whole frigate api through the internet without authentication which I am not so excited about.
- The ideal solution (for me) is if the reverse proxy add-on could take care of this for clips, recording, thumbnails, etc. 

Would that be possible?

Thank you and great job with this amazing project!
Sam

### Version

0.10.1-83481af

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

amcrest

**Comment by blakeblackshear** [comment]
The thumbnail in notifications comes from the integration, not the proxy. Have you installed the integration?

**Comment by jambuu** [comment]
I somehow missed that I need to install the integration, I only installed the add-on. Now eberything works flawlessly, including Blueprint
