### ISSUE TITLE
Uncategorized/Other Motion Objects

### ISSUE THREAD

**Issue by VTEX999** [blakeblackshear/frigate#3670]
Thank you for all the hard work you do on this project.

I was wondering if there would be any interest in creating an "uncategorized" or "other" class of motion object.  This way if an object is in motion but unable to be categorized, one could easily view these objects as an event and upload and label them to Frigate+ to help build better models.

A config sample could be:

objects:
  track:
    - person
    - car
    - dog
    - other

Just an idea, but it might be worthwhile to implement depending on the difficulty.

**Comment by NickM-27** [comment]
It doesn't really work like that, the "objects" are essentially specifically trained patterns. The objects are in the labelmap and other than those specific objects the model has no idea what an "object" is, so it can only track / recognize those things and has no idea of anything else.

[You could adjust the labelmap and make everything else called "other"](https://docs.frigate.video/configuration/advanced#model) but then you'd have hundreds of false positives / events and Frigate+ isn't accepting submissions for those objects anyway.

Also, the Frigate+ label list currently only consists of objects or analogous objects that are already in the default model so there wouldn't be anything to label. In the future there will be more, but the default model won't be able to be utilized to recognize them / create an event anyway.

**Comment by VTEX999** [comment]
So for example, last night we had a cat wonder in our backyard.  There was clearly motion, and I'm tracking cats, but no event was created because the threshold wasn't met.  I adjusted the thresholds, but I was just wondering if there might be an easy way to log motion in an event list (with snapshots) so one could go through and see if there are false negatives.  Sort of like a "spam" folder.

**Comment by NickM-27** [comment]
> So for example, last night we had a cat wonder in our backyard. There was clearly motion, and I'm tracking cats, but no event was created because the threshold wasn't met. 

Sounds like the motion wasn't captured, do you have `motion -> improve_contrast` on? that usually helps a lot with night detections.

> but I was just wondering if there might be an easy way to log motion in an event list (with snapshots) so one could go through and see if there are false negatives. Sort of like a "spam" folder.

I see, that's different than I thought you were suggesting. In any case, one of the main ideas of frigate is to not have to watch lots of motion events that are actually just the wind blowing (for example). I can see how it could be helpful for submission, but a properly configured camera in frigate shouldn't miss things like this.

**Comment by VTEX999** [comment]
No worries, it's just an idea to toy around with.  Like "spam" folders, you can have reject thresholds as well that aren't logged depending on the setting.

And I'll definitely try the improve contrast setting.  Thanks again!
