### ISSUE TITLE
What does this error mean?: 

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#3672]
### Describe the problem you are having

I'm repeatedly seeing the error below in the log.

It's not restricted to just the one camera.

Should I be using a particular time setting on the cameras? All of my cameras are the same.

Please can you tell me what it means?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
[2022-08-18 15:13:41] ffmpeg.driveway.record         ERROR   : [segment @ 0x557d22e98ec0] Non-monotonous DTS in output stream 0:0; previous: 477049901, current: 477049901; changing to 477049902. This may result in incorrect timestamps in the output file.
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW5442E-ZE

**Comment by NickM-27** [comment]
Are the cameras WiFi or wired? This usually means there's some lost packets or other bad data coming through to ffmpeg

**Comment by ripvega** [comment]
Thank you, Nick. 

All cameras are wired. I don't seem to be missing any video so I guess it's not a major issue.
