### ISSUE TITLE
Add ability to merge object detection class labels

### ISSUE THREAD

**Issue by rb2k** [blakeblackshear/frigate#3694]
**Describe what you are trying to accomplish and why in non technical terms**
I would love to know if there's an animal in my backyard. I don't need to know details about whether it's a sheep, a cat, a dog, ...
Enabling all of them will lead to dozens of objects in home assistant.

**Describe the solution you'd like**
I would like the ability to say "if a cat or a dog or a sheep is detected, just tag it as 'animal' and use that in events.

**Describe alternatives you've considered**
I could do that client side in some sort of home assistant automation, but it seems easier to scale when it's in frigate

**Additional context**
I like the created fake 'cameras' in homeassistant that show a still image of the last time something was detected, but having 5-6 of them seems superfluous.

**Comment by rb2k** [comment]
Oh neat, so that’ll also work with the existing default one as long as I map the right integers?

Cool! Thanks :)

**Comment by NickM-27** [comment]
> Oh neat, so that’ll also work with the existing default one as long as I map the right integers?

Yes 👍
