### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by rchamp26** [blakeblackshear/frigate#3696]
### Describe the problem you are having

Not an Issue but a request within the documentation. While I'm in the security industry, and While Dahua, Hikvision and Amcrest are inexpensive cameras with a simple API, they are extremely insecure and have been known to have multiple backdoors and are linked to the Chinese state and are on the US NDAA blacklist (https://ipvm.com/reports/ndaa-guide) . While some folks probably don't care, I would at least put a disclaimer to this. 

I can confirm other devices that are not on the USA naughty list that work well are are only slightly more expensive. 

All below are Onvif Certified with at least one 
Axis Communications (I've validated multiple models. Arguably the best IP camera manufacturer globally. pretty much every model guaranteed to work.)
Vivotek (easy API, closest in cost to a Dahua or Hik. Validated Multiple models. Pretty much every model guaranteed to work) 
Hanwha Security (formerly samsung security) I've validated their SNV-6080R

### Version

0.10.1-83481AF

### Frigate config file

```yaml
none
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Axis, Vivotek, Hanwha

**Comment by NickM-27** [comment]
Just to clarify, speaking on behalf of myself and not frigate as a whole:

Here's a good video on the subject which points out some of the flaws in logic of banning those camera manufacturers and the lack of knowledge when creating the US NDAA list: https://www.youtube.com/watch?v=C-zyl0y8Uus

secondly, frigate is concerned in the docs with recommending cameras that have the features to be optimal with frigate (multiple configurable streams (including resolution, fps, and i-frame interval), no RTSP issues like invalid stream data, etc.). 

There are plenty of security measures that should likely be taken like blocking camera WAN access, setting up firewall rules, etc. but this is outside the scope of frigate so it is not mentioned in the docs.

**Comment by NickM-27** [comment]
Also as another anecdote, as the linked video points this out, [Axis had their own data breach this year](https://www.bleepingcomputer.com/news/security/axis-communications-shares-details-on-disruptive-cyberattack/) which illustrates that all cameras can have security issues and the frigate docs are targeted towards what features are required to work best with frigate.
