### ISSUE TITLE
Language substitution

### ISSUE THREAD

**Issue by siri10086** [blakeblackshear/frigate#3715]
Is there any way to change these Title languages into other languages? I will translate and replace them myself
<img width="1414" alt="WX20220826-210520@2x" src="https://user-images.githubusercontent.com/61342291/187006856-3d40fedd-b8ed-4a88-84ed-ed6e251bf60b.png">

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3582

Basically, happy to accept help but it isn't currently setup so we need someone who is familiar with that to get it started.

**Comment by NickM-27** [comment]
I might see if I can work on getting the templating setup this weekend, seems like as frigate gets more popular this will become more and more of a popular request.

**Comment by siri10086** [comment]
Yes, I look forward to new progress
