### ISSUE TITLE
Distinguish moving object vs stationary object

### ISSUE THREAD

**Issue by dinki** [blakeblackshear/frigate#375]
Hi ya.  Giving frigate a try and am having problems getting it up and running.  I'm installing amd64 version in Docker on my Linux server.  Here's the docker run command I'm using:

```
root@omv:/sharedfolders/appdata/frigate# docker run --rm --name frigate --privileged -v /dev/bus/usb:/dev/bus/usb -v /sharedfolders/appdata/frigate/:/config:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -e FRIGATE_RTSP_PASSWORD='redacted' blakeblackshear/frigate:stable-amd64
```

and here's my config.yml file:

```
# Optional: port for http server (default: shown below)
web_port: 5000

# Optional: detectors configuration
# USB Coral devices will be auto detected with CPU fallback
detectors:
  # Required: name of the detector
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    
# Required: mqtt configuration
mqtt:
  # Required: host name
  host: 192.168.0.25
  topic_prefix: frigate


# Optional: Global configuration for saving clips
save_clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300
  # Optional: Location to save event clips. (default: shown below)
  clips_dir: /config/clips
  # Optional: Location to save cache files for creating clips. (default: shown below)
  # NOTE: To reduce wear on SSDs and SD cards, use a tmpfs volume.
  cache_dir: /config/cache

# Optional: Global object filters for all cameras.
# NOTE: can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: max_int)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.85

# Required: configuration section for cameras
cameras:
  # Required: name of the camera
  front:
    # Required: ffmpeg settings for the camera
    ffmpeg:
      # Required: Source passed to ffmpeg after the -i parameter.
      # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}
      input: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.0.26/livestream/11?action=play&media=video_audio_data
      # Optional: camera specific global args (default: inherit)
      global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args:
      # Optional: camera specific input args (default: inherit)
      input_args:
      # Optional: camera specific output args (default: inherit)
      output_args:
    
    # Optional: desired fps for your camera
    # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
    #       Frigate will attempt to autodetect if not specified.
    fps: 5


    # Optional: timeout for highest scoring image before allowing it
    # to be replaced by a newer image. (default: shown below)
    best_image_timeout: 60

    # Optional: camera specific mqtt settings
    mqtt:
      # Optional: crop the camera frame to the detection region of the object (default: False)
      crop_to_region: True
      # Optional: resize the image before publishing over mqtt
      snapshot_height: 300

    # Optional: Configuration for the snapshots in the debug view and mqtt
    snapshots:
      # Optional: print a timestamp on the snapshots (default: shown below)
      show_timestamp: True
      # Optional: draw zones on the debug mjpeg feed (default: shown below)
      draw_zones: False
      # Optional: draw bounding boxes on the mqtt snapshots (default: shown below)
      draw_bounding_boxes: True

    # Optional: Camera level object filters config. If defined, this is used instead of the global config.
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
```

and finally, here's the error:

```
Fontconfig error: Cannot load default config file
On connect called
Traceback (most recent call last):
  File "detect_objects.py", line 441, in <module>
    main()
  File "detect_objects.py", line 202, in main
    ffmpeg_output_args = ["-r", str(config.get('fps'))] + ffmpeg_output_args
TypeError: can only concatenate list (not "NoneType") to list
```

I did try remove portions of the optional items in the yaml config file in hopes of getting things to work but I was not able.  Can anyone tell me what the problem might be?  I see that the error is for 'fps' and I do have it configured for the one camera that I'm trying.  Is it not seeing this value?

Thanks for you help!

**Comment by dinki** [comment]
Not sure why this always seems to happen but I managed to get it running right after posting despite trying what I thought was everything.  The fix for me was to comment all optional lines in this section:

```
      # Optional: camera specific global args (default: inherit)
      global_args:
      # Optional: camera specific hwaccel args (default: inherit)
      hwaccel_args:
      # Optional: camera specific input args (default: inherit)
      input_args:
      # Optional: camera specific output args (default: inherit)
      output_args:
```

Not too sure why those are not commented out in the default config example unless I'm doing something wrong?  Is there any harm not having these available?

**Comment by blakeblackshear** [comment]
No harm. That is exactly the suggested fix. The docs will be clearer in the next version. You may want to give the beta release a try if you want some of the new features.

**Comment by dinki** [comment]
Thanks for this.  One last question so that I'm clear, frigate does differentiate between moving cars and parked cars right?  My cameras in the front of my house have a clear view of the neighbors cars.  I'd like to keep the entire frame (no zones) and capture anything with people (standing or moving) as well as moving cars only.  

And also is there a list of other objects other than car and person?  Is there a distinction between car/truck/bus/etc?  Dogs/cats?

Thanks again.

**Comment by blakeblackshear** [comment]
Frigate will save clips for any object type it is tracking, even if they are stationary. At the moment, it will probably latch onto your neighbors cars and track them as soon as there is any motion in the surrounding areas. You could use a zone so you can at least filter the clips down to areas of interest when viewing. It won't be long before Frigate has object specific masks and the ability to stop running detection on stationary objects as these are fairly common needs.

It uses the models trained on the COCO image dataset. You can see the label map for everything it is trained on [here](https://github.com/blakeblackshear/frigate/blob/release-0.8.0/labelmap.txt).

**Comment by dinki** [comment]
> Frigate will save clips for any object type it is tracking, even if they are stationary. At the moment, it will probably latch onto your neighbors cars and track them as soon as there is any motion in the surrounding areas. You could use a zone so you can at least filter the clips down to areas of interest when viewing. It won't be long before Frigate has object specific masks and the ability to stop running detection on stationary objects as these are fairly common needs.

Truth be told, this is the functionality that lead me here.  I started going down the trail of doing this myself with motionEye and multiple snapshots per motion event.  My thought was that I could do a count for cars in all images and if I ever had more cars than what I started with then the odds were good that a moving car caused the event.  Going further, I discovered that Deep Stacks returns a centroid point per object and that could be used to test if the car was moving.  All this said, I haven't gotten very far with this outside of some initial testing.  I'm guessing that you would use a similar approach with Frigate?  I can say, with certainty, that the ability to distinguish between parked and moving cars is lacking from all AI options I've run across and know of a few people besides myself that would be very interested in a solution.

Thanks again for your insight.

**Comment by blakeblackshear** [comment]
Should be easy enough. I have all the information I need to distinguish a moving object from a stationary object.

**Comment by dinki** [comment]
Excellent.  I'm up for testing when you get it integrated.

**Comment by dinki** [comment]
Hey @blakeblackshear , any chance on seeing this functionality in the near future?  More curious than anything.  Have been running motioneye since this post but would prefer frigate when this is added.

All the best to you.

**Comment by noelhibbard** [comment]
Just wanted to give a +1 on this. I have a zone for my driveway and then wrote an app that monitors the MQTT events and then sends the thumbnail to a Telegram group. I only send the Telegrams if it's in specific zones so I don't get constant alerts on my phone. I typically park my cars all the way up the driveway in a masked area where I exclude car detection. This works well but on occasion I park outside of the mask and on nights like that I get constant notification every time there is motion. I'd love to see someway of filtering static objects. I'm sure this is easier said than done though.

**Comment by dinki** [comment]
@blakeblackshear Hi again.  Just circling back to see if this had made it closer to a reality.  Waiting to make the jump to Frigate but, as mentioned, this is a must have feature for me.  Again, understand the time and effort required and am certainly not trying to come across as pushy or entitled just curious.  All the best to you.

**Comment by blakeblackshear** [comment]
I'm hoping 0.10.0 will meet the needs here. Determining what qualifies as a moving object is challenging. Pixel changes could just be lighting and movement could just be variation in the bounding box from one frame to the next. I have some ideas to try, but there will probably always be some scenarios it doesn't handle. For now, most people use zones and require objects to enter multiple zones for notifications.
