### ISSUE TITLE
[FR] Ability to increase live view fps, use high res stream for live view

### ISSUE THREAD

**Issue by dmidthun** [blakeblackshear/frigate#3753]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to adjust the 'Live' camera fps in the web interface so as to view the feed in a more 'live' experience -- 5fps is sometimes choppy when trying to view a stream in real time.

**Describe the solution you'd like**

config example:

live:
  height: [xxxx]
  quality: x
  **fps: xx**

**Comment by NickM-27** [comment]
The live view comes from the debug stream. The live view supports up to 10 fps if detect is set to use 10 fps.

**Comment by dmidthun** [comment]
I suppose, then I should request that the live view support up to 25fps? The recordings are perfect, and the audio inclusion is right on - which is why I was hoping to get better fps on the live view. Some of my cameras I dont necessarily need to record nor do object detection, but I am ecstatic that I can get my cameras working on a single pane of glass.

**Comment by NickM-27** [comment]
> I suppose, then I should request that the live view support up to 25fps? The recordings are perfect, and the audio inclusion is right on - which is why I was hoping to get better fps on the live view. Some of my cameras I dont necessarily need to record nor do object detection, but I am ecstatic that I can get my cameras working on a single pane of glass.

The difficult thing is that it requires decoding the stream. Decoding a high res / high fps stream would be a LOT of work and especially if actual motion detection is occurring it would be too much for most CPUs to handle.

We may have an option to decode both streams and use the high res stream as a live view but that's not decided and will be a ways out either way.

**Comment by dmidthun** [comment]
So I have a Coral USB coming this weekend, and am under the novice understanding that I would be offloading that work to the TPM... That's why I thought that if it were configurable, it would be okay at a higher framerate. Maybe have a note on the config sample stating that without a coral device that a fps of 5 is recommended so you don't lock up the proc?

**Comment by NickM-27** [comment]
> So I have a Coral USB coming this weekend, and am under the novice understanding that I would be offloading that work to the TPM... That's why I thought that if it were configurable, it would be okay at a higher framerate. Maybe have a note on the config sample stating that without a coral device that a fps of 5 is recommended so you don't lock up the proc?

Not quite, the coral accelerates object detection but motion detection and video decoding are still run on the CPU and will definitely cause a strain even with a coral like I said.

**Comment by dmidthun** [comment]
So the question now is what is the actual framerate of the live view? I can tell you that is is not what the camera is streaming, as the recordings are on par with what has been physically seen. The system I have frigate running on is probably overkill for what is usually used; 8-core Intel Xeon @ 3.5GHz, 16G Ram and SSD running the storage. Any thoughts?

**Comment by NickM-27** [comment]
@dmidthun as I said previously the actual frame rate of the live view is based on your cameras `detect -> fps` which defaults to five. The live view can go up to 10 fps currently.

**Comment by tpjanssen** [comment]
Maybe it is an idea to add an option to use the RTSP stream for this purpose? Lots of camera's have 3 streams, so you can configure the detect, record and live stream the way you want.

**Comment by NickM-27** [comment]
> Maybe it is an idea to add an option to use the RTSP stream for this purpose? Lots of camera's have 3 streams, so you can configure the detect, record and live stream the way you want.

The reason this isn't possible yet isn't due to just a lack of option but the way that part is currently architectured. You can read more about this: https://github.com/blakeblackshear/frigate/issues/3430#issuecomment-1177481187

**Comment by blakeblackshear** [comment]
Once there is a live view mode that uses HLS or WebRTC it can be a direct passthrough from the camera. The current live views will always be limited fps based on the detect stream. Any efforts to workaround that would be better spent just implementing HLS and/or WebRTC.

**Comment by NickM-27** [comment]
Closing this as it’s been implemented in https://github.com/blakeblackshear/frigate/pull/4082
