### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by nameErr0r** [blakeblackshear/frigate#3764]
### Describe the problem you are having

frigate stops here on loading and stays here until I exit with ctrl+C:

frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-09-03 23:06:06] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | Starting migrations
frigate  | [2022-09-03 23:06:06] peewee_migrate                 INFO    : Starting migrations
frigate  | There is nothing to migrate
frigate  | [2022-09-03 23:06:06] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-09-03 23:06:06] frigate.app                    INFO    : Output process started: 242
frigate  | [2022-09-03 23:06:06] detector.cpu                   INFO    : Starting detection process: 241
frigate  | [2022-09-03 23:06:06] ws4py                          INFO    : Using epoll
frigate  | [2022-09-03 23:06:06] frigate.app                    INFO    : Camera processor started for garage: 245
frigate  | [2022-09-03 23:06:06] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | [2022-09-03 23:06:06] frigate.app                    INFO    : Capture process started for garage: 248
frigate  | [2022-09-03 23:06:06] ws4py                          INFO    : Using epoll

### Version

0.10.1-83481af (I think--I can't get to the Web UI)

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.10 
  
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxx@192.168.1.239:554
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False
    detect:
      width: 3840
      height: 2160
```

### Relevant log output

```shell
I'm not sure which logs are relevant here...
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:XXXXXXX@192.168.1.239:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.533333, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 7713:7712 DAR 857:482], 15 fps, 100 tbr, 90k tbn, 30 tbc
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

amcrest 

### Any other information that may be helpful

I can stream the camera live views through the camera's webserver and by using:
mplayer rtsp://admin:xxxxx@192.168.1.239:554

If I try other urls such as the ones suggested by amcrest in my frigate config, I get authorization errors when frigate tries to start, and it loops.  With that URL, the auth errors and loops don't happen, but it freezes.

**Comment by NickM-27** [comment]
These are completely normal logs and frigate is running happily. What is your docker compose file and what URL are you using to try to access frigate frontend?

**Comment by nameErr0r** [comment]
You're right.  I spent so long diagnosing actual errors, I didn't notice when it was working but I mistyped the access URL.  It is actually working normally.  Thanks!
