### ISSUE TITLE
[HW Accel Support]: HW Acceleration on raspberry with Debian OS doesn't work

### ISSUE THREAD

**Issue by maframan** [blakeblackshear/frigate#3772]
### Describe the problem you are having

I've installed frigate with docker compose on debian os release "bookworm/sid" and when I'try to use hw acceleration with this configuration:
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m 
from webui the camera is green.

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  user: xxxxxxxxxxx
  password: xxxxxxxxxx
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: True
  timestamp: False
  bounding_box: False
  retain:
    default: 10
    objects:
      person: 15

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
  ingresso_principale:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxx@192.168.102.51:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False  # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    snapshots:
      required_zones:
        - zone_1
    zones:
      zone_1:
        coordinates: 1390,1080,1540,473,825,377,800,373,54,669,0,1080
        objects:
          - person
  strada_privata:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxx@192.168.102.44:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    snapshots:
      required_zones:
        - zone_4
    zones:
      zone_4:
        coordinates: 1280,720,1234,166,0,409,0,720
        objects:
          - person
  giardino_posteriore_sx:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.102.23:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:   
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    snapshots:
      required_zones:
        - zone_2
    zones:
      zone_2:
        coordinates: 0,720,1280,720,1280,246,1106,239,0,333,1099,251,864,197,609,187,0,287
        objects:
          - person
  garage_esterno:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxxxxx@192.168.102.45:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    snapshots:
      required_zones:
        - rampa
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    zones:
      rampa:
        coordinates: 0,1080,1920,1080,1920,150,1444,310,1369,333,1242,443,1316,621,986,617,634,596,0,47
        objects:
          - person
  giardino_posteriore_dx:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxxxx@192.168.102.2:554/h.264
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    motion:
    snapshots:
      required_zones:
        - zone_3
    zones:
      zone_3:
        coordinates: 763,491,1920,557,1920,1080,0,1080,0,1080,86,666
        objects:
          - person

birdseye:
  enabled: False
  width: 1280
  height: 720
  quality: 8
  mode: objects
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-aarch64
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/frigate/config.yml:/config/config.yml:ro
      - /usr/share/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxxxx"
```

### Relevant log output

```shell
[2022-09-06 00:30:36] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-09-06 00:30:36] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-06 00:30:36] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-06 00:30:36] frigate.app                    INFO    : Output process started: 218
[2022-09-06 00:30:36] detector.coral                 INFO    : Starting detection process: 217
[2022-09-06 00:30:36] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-06 00:30:36] ws4py                          INFO    : Using epoll
[2022-09-06 00:30:36] frigate.app                    INFO    : Camera processor started for ingresso_principale: 225
[2022-09-06 00:30:38] frigate.video                  ERROR   : strada_privata: Unable to read frames from ffmpeg process.
[2022-09-06 00:30:38] frigate.video                  ERROR   : giardino_posteriore_dx: Unable to read frames from ffmpeg process.
[2022-09-06 00:30:38] frigate.video                  ERROR   : giardino_posteriore_dx: ffmpeg process is not running. exiting capture thread...
[2022-09-06 00:30:38] frigate.video                  ERROR   : ingresso_principale: Unable to read frames from ffmpeg process.
[2022-09-06 00:30:38] frigate.video                  ERROR   : ingresso_principale: ffmpeg process is not running. exiting capture thread...
[2022-09-06 00:30:38] frigate.video                  ERROR   : garage_esterno: Unable to read frames from ffmpeg process.
[2022-09-06 00:30:38] frigate.video                  ERROR   : strada_privata: ffmpeg process is not running. exiting capture thread...
[2022-09-06 00:30:38] frigate.video                  ERROR   : giardino_posteriore_sx: Unable to read frames from ffmpeg process.
[2022-09-06 00:30:38] frigate.video                  ERROR   : garage_esterno: ffmpeg process is not running. exiting capture thread...
[2022-09-06 00:30:38] frigate.video                  ERROR   : giardino_posteriore_sx: ffmpeg process is not running. exiting capture thread...
[2022-09-06 00:30:36] frigate.app                    INFO    : Camera processor started for strada_privata: 227
[2022-09-06 00:30:36] frigate.app                    INFO    : Camera processor started for giardino_posteriore_sx: 229
[2022-09-06 00:30:36] frigate.app                    INFO    : Camera processor started for garage_esterno: 230
[2022-09-06 00:30:36] frigate.app                    INFO    : Camera processor started for giardino_posteriore_dx: 233
[2022-09-06 00:30:36] frigate.app                    INFO    : Capture process started for ingresso_principale: 235
[2022-09-06 00:30:36] frigate.app                    INFO    : Capture process started for strada_privata: 236
[2022-09-06 00:30:36] frigate.app                    INFO    : Capture process started for giardino_posteriore_sx: 237
[2022-09-06 00:30:36] frigate.app                    INFO    : Capture process started for garage_esterno: 242
[2022-09-06 00:30:36] frigate.app                    INFO    : Capture process started for giardino_posteriore_dx: 245
[2022-09-06 00:30:36] ws4py                          INFO    : Using epoll
[2022-09-06 00:30:39] frigate.edgetpu                INFO    : TPU found
```

### FFprobe output from your camera

```shell
ffprobe version 5.1-2+b1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.1.0-7)
  configuration: --prefix=/usr --extra-version=2+b1 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --arch=arm64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libplacebo --enable-libx264 --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0xaaaafb891dc0] Missing PPS in sprop-parameter-sets, ignoring
[rtsp @ 0xaaaafb891dc0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, rtsp, from 'rtsp://admin:xxxxxxxx@yyy.yyy.yyy.yyy:554/h.264':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
  Stream #0:1: Audio: aac, 16000 Hz, mono, fltp
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Ezviz

**Comment by NickM-27** [comment]
You need to pass `/dev/video10` as that is the device that represents RPi GPU

**Comment by maframan** [comment]
> You need to pass `/dev/video10` as that is the device that represents RPi GPU

how you do it?

**Comment by NickM-27** [comment]
Add `/dev/video10` to the `devices` section of your docker compose

**Comment by maframan** [comment]
> Add `/dev/video10` to the `devices` section of your docker compose

root@frigate:~# ls -lrt /dev/video10
ls: cannot access '/dev/video10': No such file or directory

**Comment by NickM-27** [comment]
Run `ls /dev` and paste a screenshot of the results here.

**Comment by maframan** [comment]
> Run `ls /dev` and paste a screenshot of the results here.

root@frigate:~# ls /dev
autofs		 cuse	    input	  ppp	  snapshot  tty13  tty23  tty33  tty43	tty53  tty63	vchiq  vcsa3  vfio
block		 disk	    kmsg	  psaux   snd	    tty14  tty24  tty34  tty44	tty54  tty7	vcs    vcsa4  vga_arbiter
bsg		 dri	    kvm		  ptmx	  stderr    tty15  tty25  tty35  tty45	tty55  tty8	vcs1   vcsa5  vhost-net
btrfs-control	 fd	    log		  pts	  stdin     tty16  tty26  tty36  tty46	tty56  tty9	vcs2   vcsa6  vhost-vsock
bus		 full	    loop-control  random  stdout    tty17  tty27  tty37  tty47	tty57  ttyS0	vcs3   vcsu   watchdog
cec0		 fuse	    mapper	  rfkill  tty	    tty18  tty28  tty38  tty48	tty58  ttyS1	vcs4   vcsu1  watchdog0
cec1		 gpiochip0  mem		  sda	  tty0	    tty19  tty29  tty39  tty49	tty59  ttyS2	vcs5   vcsu2  zero
char		 gpiochip1  mqueue	  sda1	  tty1	    tty2   tty3   tty4	 tty5	tty6   ttyS3	vcs6   vcsu3
console		 hugepages  net		  sda2	  tty10     tty20  tty30  tty40  tty50	tty60  uhid	vcsa   vcsu4
core		 hwrng	    null	  sg0	  tty11     tty21  tty31  tty41  tty51	tty61  uinput	vcsa1  vcsu5
cpu_dma_latency  initctl    port	  shm	  tty12     tty22  tty32  tty42  tty52	tty62  urandom	vcsa2  vcsu6

**Comment by NickM-27** [comment]
What device are you running frigate on?

**Comment by maframan** [comment]
> What device are you running frigate on?

raspberry 4 with 4GB RAM

**Comment by NickM-27** [comment]
It seems that your GPU is not enabled, you'll need to enable it (not 100% how to do that, but you can start by running `rasbpiconfig`

**Comment by maframan** [comment]
> It seems that your GPU is not enabled, you'll need to enable it (not 100% how to do that, but you can start by running `rasbpiconfig`

i can't find any guide to do this on debian.
In raspi-config where do i find the configuration to enable?

**Comment by maframan** [comment]
I followed this guide https://www.dedoimedo.com/computers/rpi4-ubuntu-mate-hw-video-acceleration.html and now I've this device
root@frigate:~# ls /dev/
autofs		 cuse	    input	  ppp	  snapshot  tty13  tty23  tty33  tty43	tty53  tty63	vchiq  vcsa3  vfio
block		 disk	    kmsg	  psaux   snd	    tty14  tty24  tty34  tty44	tty54  tty7	vcs    vcsa4  vga_arbiter
bsg		 dri	    kvm		  ptmx	  stderr    tty15  tty25  tty35  tty45	tty55  tty8	vcs1   vcsa5  vhost-net
btrfs-control	 fd	    log		  pts	  stdin     tty16  tty26  tty36  tty46	tty56  tty9	vcs2   vcsa6  vhost-vsock
bus		 full	    loop-control  random  stdout    tty17  tty27  tty37  tty47	tty57  ttyS0	vcs3   vcsu   watchdog
cec0		 fuse	    mapper	  rfkill  tty	    tty18  tty28  tty38  tty48	tty58  ttyS1	vcs4   vcsu1  watchdog0
cec1		 gpiochip0  mem		  sda	  tty0	    tty19  tty29  tty39  tty49	tty59  ttyS2	vcs5   vcsu2  zero
char		 gpiochip1  mqueue	  sda1	  tty1	    tty2   tty3   tty4	 tty5	tty6   ttyS3	vcs6   vcsu3
console		 hugepages  net		  sda2	  tty10     tty20  tty30  tty40  tty50	tty60  uhid	vcsa   vcsu4
core		 hwrng	    null	  sg0	  tty11     tty21  tty31  tty41  tty51	tty61  uinput	vcsa1  vcsu5
cpu_dma_latency  initctl    port	  shm	  tty12     tty22  tty32  tty42  tty52	tty62  urandom	vcsa2  vcsu6

**Comment by NickM-27** [comment]
have you rebooted? It will be presented as `video10` -> `video19`. I run debian on my test rpi 3b+ and it had these available. These are what need to be passed to the container to be used

**Comment by maframan** [comment]
> have you rebooted? It will be presented as `video10` -> `video19`. I run debian on my test rpi 3b+ and it had these available. These are what need to be passed to the container to be used

Yes, I've rebooted

**Comment by maframan** [comment]
i guess i should install raspbian, right?

**Comment by NickM-27** [comment]
Like I said, I run debian and it just worked. Which Pi are you running on? Another OS could be worth a try, but I'm not sure.

**Comment by maframan** [comment]
I've added in my config.yaml follow config:
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

**Comment by NickM-27** [comment]
Are you passing `/dev/video10` through to the container? This will always be the first step to getting RPi hwaccel working

**Comment by maframan** [comment]
> Are you passing `/dev/video10` through to the container? This will always be the first step to getting RPi hwaccel working

Yes

**Comment by maframan** [comment]
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-aarch64
    shm_size: "1024mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
      - /dev/video10
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/frigate/config.yml:/config/config.yml:ro
      - /usr/share/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxx"

**Comment by maframan** [comment]
In document is typed: "If you are using the addon, you may need to turn off Protection mode for hardware acceleration."
How to verify protection mode status?

**Comment by NickM-27** [comment]
> In document is typed: "If you are using the addon, you may need to turn off Protection mode for hardware acceleration."
How to verify protection mode status?

You are running in docker compose so that is not relevant to your install, that is only for users running Frigate in the HA addon.

The next step is setting the right amount of GPU memory, how much do you currently have allocated for the GPU? This is in the rasbpi-config

**Comment by maframan** [comment]
configured to 128

**Comment by maframan** [comment]
Increase to 256 or 512?

**Comment by NickM-27** [comment]
Probably worth trying 512 for now and once working can be brought back down if needed

**Comment by NickM-27** [comment]
Okay seems that is too high

> capture VIDIOC_REQBUFS failed: Cannot allocate memory

**Comment by maframan** [comment]
Try to 512?

**Comment by NickM-27** [comment]
> Try to 512?

yes

**Comment by maframan** [comment]
With 512 doesn't work, work with 256 but only 2 cameras of 5 work
[2022-09-06 15:10:14] watchdog.ingresso_principale   INFO    : FFmpeg didnt exit. Force killing...
[2022-09-06 15:10:14] frigate.video                  ERROR   : giardino_posteriore_sx: Unable to read frames from ffmpeg process.
[2022-09-06 15:10:14] frigate.video                  ERROR   : giardino_posteriore_sx: ffmpeg process is not running. exiting capture thread...
[2022-09-06 15:10:15] frigate.video                  ERROR   : ingresso_principale: Unable to read frames from ffmpeg process.
[2022-09-06 15:10:15] frigate.video                  ERROR   : ingresso_principale: Unable to read frames from ffmpeg process.
[2022-09-06 15:10:15] frigate.video                  ERROR   : ingresso_principale: ffmpeg process is not running. exiting capture thread...
[2022-09-06 15:10:17] frigate.video                  ERROR   : strada_privata: Unable to read frames from ffmpeg process.
[2022-09-06 15:10:17] frigate.video                  ERROR   : strada_privata: ffmpeg process is not running. exiting capture thread...
[2022-09-06 15:10:24] watchdog.strada_privata        ERROR   : Ffmpeg process crashed unexpectedly for strada_privata.
[2022-09-06 15:10:24] watchdog.strada_privata        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-06 15:10:24] ffmpeg.strada_privata.detect   ERROR   : [rtsp @ 0x557cfc05f0] Missing PPS in sprop-parameter-sets, ignoring
[2022-09-06 15:10:24] ffmpeg.strada_privata.detect   ERROR   : [rtsp @ 0x557cfc05f0] RTP H.264 NAL unit type 27 is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[2022-09-06 15:10:24] ffmpeg.strada_privata.detect   ERROR   : [rtsp @ 0x557cfc05f0] CSeq 9 expected, 0 received.
[2022-09-06 15:10:24] ffmpeg.strada_privata.detect   ERROR   :     Last message repeated 2 times
[2022-09-06 15:10:24] ffmpeg.strada_privata.detect   ERROR   : [NULL @ 0x557cfc3ba0] FMO is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[2022-09-06 15:10:24] ffmpeg.strada_privata.detect   ERROR   : [NULL @ 0x557cfc3ba0] missing picture in access unit with size 63641
[2022-09-06 15:10:24] watchdog.giardino_posteriore_sx ERROR   : Ffmpeg process crashed unexpectedly for giardino_posteriore_sx.
[2022-09-06 15:10:24] watchdog.giardino_posteriore_sx ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-06 15:10:24] ffmpeg.giardino_posteriore_sx.detect ERROR   : [rtsp @ 0x558ec685f0] Missing PPS in sprop-parameter-sets, ignoring
[2022-09-06 15:10:25] ffmpeg.giardino_posteriore_sx.detect ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable
[2022-09-06 15:10:25] watchdog.ingresso_principale   ERROR   : Ffmpeg process crashed unexpectedly for ingresso_principale.
[2022-09-06 15:10:25] watchdog.ingresso_principale   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-06 15:10:25] ffmpeg.ingresso_principale.detect ERROR   : [rtsp @ 0x55b0dba5f0] Missing PPS in sprop-parameter-sets, ignoring
[2022-09-06 15:10:25] ffmpeg.ingresso_principale.detect ERROR   : Error while decoding stream #0:0: Resource temporarily unavailable

![image](https://user-images.githubusercontent.com/24868793/188644199-a8dc4d16-20a7-4c11-8c3b-caa660c4c8ff.png)

**Comment by NickM-27** [comment]
`Error while decoding stream #0:0: Resource temporarily unavailable` (this is referring to memory)

Okay, that makes sense then, seems your device is memory limited.

**Comment by maframan** [comment]
How to resolve for that devices?

**Comment by NickM-27** [comment]
I'm not sure how much of your RAM is being used by other services so could try to limit it that way. Unfortunately, if more memory can't be allocated to the GPU then the Pi just isn't able to handle that many video streams with hwaccel.

**Comment by maframan** [comment]
Now, I disable hw accelerator because w/o the feature the streams works for all cameras

**Comment by NickM-27** [comment]
Sure, please also keep in mind that instead of setting 

```yaml
hwaccel_args:
  - -c:v
  - h264_v4l2m2m
```

globally, you can set it just for 2 cameras specifically so at least it will be used for 2 cameras.

**Comment by maframan** [comment]
Ok, thanks
I see that with raspbian the cpu usage is very high (90/95% percentage) while with debian was abot 60/70%

**Comment by maframan** [comment]
I rollback to debian, is lower cpu consuming

**Comment by EmmanuelVella** [comment]
Hello, just to let you know, I installed Debian 11 on my RPI4 too, and I have no `/dev/video[...]` entry, and enabling hardware acceleration in frigate configuration leads to green video too.

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [2022-09-06 14:15:01] frigate.app                    INFO    : Starting Frigate (0.11.0-c461c9e)
> Starting migrations
> [2022-09-06 14:15:01] peewee_migrate                 INFO    : Starting migrations
> There is nothing to migrate
> [2022-09-06 14:15:01] peewee_migrate                 INFO    : There is nothing to migrate
> [2022-09-06 14:15:01] detector.coral                 INFO    : Starting detection process: 216
> [2022-09-06 14:15:01] frigate.app                    INFO    : Output process started: 217
> [2022-09-06 14:15:01] frigate.edgetpu                INFO    : Attempting to load TPU as usb
> [2022-09-06 14:15:01] ws4py                          INFO    : Using epoll
> [2022-09-06 14:15:01] frigate.app                    INFO    : Camera processor started for nord: 224
> [2022-09-06 14:15:01] frigate.app                    INFO    : Camera processor started for est: 226
> [2022-09-06 14:15:01] frigate.app                    INFO    : Camera processor started for sud: 227
> [2022-09-06 14:15:01] frigate.app                    INFO    : Camera processor started for ouest: 229
> [2022-09-06 14:15:01] frigate.app                    INFO    : Capture process started for nord: 231
> [2022-09-06 14:15:01] frigate.app                    INFO    : Capture process started for est: 234
> [2022-09-06 14:15:01] frigate.app                    INFO    : Capture process started for sud: 236
> [2022-09-06 14:15:01] frigate.app                    INFO    : Capture process started for ouest: 239
> [2022-09-06 14:15:02] ws4py                          INFO    : Using epoll
> [2022-09-06 14:15:04] frigate.edgetpu                INFO    : TPU found
> [2022-09-06 14:15:08] frigate.video                  ERROR   : est: Unable to read frames from ffmpeg process.
> [2022-09-06 14:15:08] frigate.video                  ERROR   : est: ffmpeg process is not running. exiting capture thread...
> [2022-09-06 14:15:08] frigate.video                  ERROR   : nord: Unable to read frames from ffmpeg process.
> [2022-09-06 14:15:08] frigate.video                  ERROR   : nord: ffmpeg process is not running. exiting capture thread...
> [2022-09-06 14:15:08] frigate.video                  ERROR   : sud: Unable to read frames from ffmpeg process.
> [2022-09-06 14:15:08] frigate.video                  ERROR   : sud: ffmpeg process is not running. exiting capture thread...
> [2022-09-06 14:15:08] frigate.video                  ERROR   : ouest: Unable to read frames from ffmpeg process.
> [2022-09-06 14:15:08] frigate.video                  ERROR   : ouest: ffmpeg process is not running. exiting capture thread...
> [2022-09-06 14:15:21] watchdog.nord                  ERROR   : Ffmpeg process crashed unexpectedly for nord.
> [2022-09-06 14:15:21] watchdog.nord                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2022-09-06 14:15:21] ffmpeg.nord.detect             ERROR   : [h264_v4l2m2m @ 0xaaab021471a0] Could not find a valid device
> [2022-09-06 14:15:21] ffmpeg.nord.detect             ERROR   : [h264_v4l2m2m @ 0xaaab021471a0] can't configure decoder
> [2022-09-06 14:15:21] ffmpeg.nord.detect             ERROR   : Error while opening decoder for input stream #0:0 : Invalid argument
> [2022-09-06 14:15:21] watchdog.sud                   ERROR   : Ffmpeg process crashed unexpectedly for sud.
> [2022-09-06 14:15:21] watchdog.sud                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2022-09-06 14:15:21] ffmpeg.sud.detect              ERROR   : [h264_v4l2m2m @ 0xaaaadc7893d0] Could not find a valid device
> [2022-09-06 14:15:21] ffmpeg.sud.detect              ERROR   : [h264_v4l2m2m @ 0xaaaadc7893d0] can't configure decoder
> [2022-09-06 14:15:21] ffmpeg.sud.detect              ERROR   : Error while opening decoder for input stream #0:0 : Invalid argument
> [2022-09-06 14:15:21] watchdog.est                   ERROR   : Ffmpeg process crashed unexpectedly for est.
> [2022-09-06 14:15:21] watchdog.est                   ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2022-09-06 14:15:21] ffmpeg.est.detect              ERROR   : [h264_v4l2m2m @ 0xaaab11bd7c20] Could not find a valid device
> [2022-09-06 14:15:21] ffmpeg.est.detect              ERROR   : [h264_v4l2m2m @ 0xaaab11bd7c20] can't configure decoder
> [2022-09-06 14:15:21] ffmpeg.est.detect              ERROR   : Error while opening decoder for input stream #0:0 : Invalid argument
> [2022-09-06 14:15:21] watchdog.ouest                 ERROR   : Ffmpeg process crashed unexpectedly for ouest.
> [2022-09-06 14:15:21] watchdog.ouest                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
> [2022-09-06 14:15:21] ffmpeg.ouest.detect            ERROR   : [h264_v4l2m2m @ 0xaaab0d4339d0] Could not find a valid device
> [2022-09-06 14:15:21] ffmpeg.ouest.detect            ERROR   : [h264_v4l2m2m @ 0xaaab0d4339d0] can't configure decoder
> [2022-09-06 14:15:21] ffmpeg.ouest.detect            ERROR   : Error while opening decoder for input stream #0:0 : Invalid argument

**Comment by NickM-27** [comment]
You can see my setup here:

![Screen Shot 2022-08-28 at 08 52 55 AM](https://user-images.githubusercontent.com/14866235/187080438-f3a0bf83-b4c6-4438-bcd2-b5ed5c70607e.png)

**Comment by EmmanuelVella** [comment]
Hum ok, on my side I installed it with an image from the debian website : 

![image](https://user-images.githubusercontent.com/663607/188721080-904f8f64-83cb-469e-b467-143b67fd0347.png)

**Comment by NickM-27** [comment]
Maybe different packages are included and need to be pulled on your side. I imagine installing ffmpeg on the host might do it but I don't know. Either way it's required to have the gpu driver devices installed and passed to container.
