### ISSUE TITLE
[Support]: 0.11.0 RC2 HASS Card/Frigate UI Clip Duration/Length

### ISSUE THREAD

**Issue by saluther** [blakeblackshear/frigate#3773]
### Describe the problem you are having

The clip length for 0.11.0 RC2 is longer than the duration shown in the Frigate HASS Card. For the same clip played with RC1, the clip HASS Card duration and Frigate length usually match within 1 to 2 seconds. For RC2 the same clip may have a length up to 1 minute longer than the duration shown in the HASS Card. Both the Frigate UI and the Frigate HASS Card have the same issue.

See the screenshots below for RC1 and RC2 as an example. The duration/length of the clip for RC1 is shown as 15 seconds for the HASS Card and 14 seconds for the Frigate UI. For RC2, the length of the clip is shown as 29 seconds for the HASS Card and 28 seconds for the Frigate UI for the same clip. An additional 14 seconds has been added to the beginning of the RC2 clip.  Note the differences in the camera time stamps between RC1 and RC2.

### Version

0.11.0-c461c9e

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP5MB1186EW-28MM

### **RC1**
![0 11 0-RC1 Overview – Home Assistant](https://user-images.githubusercontent.com/97411437/188524349-e8fe0e64-ac75-4e35-8b76-2b599cab9d77.png)

![0 11 0-RC1 Frigate](https://user-images.githubusercontent.com/97411437/188524359-a19108a7-8d0d-4387-847b-27e3a2846ac0.png)

### **RC2**
![0 11 0-RC2 Overview – Home Assistant](https://user-images.githubusercontent.com/97411437/188524391-2be9c5e9-2d53-4ab3-a47f-3dd7c0735cfb.png)

![0 11 0-RC2 Frigate](https://user-images.githubusercontent.com/97411437/188524407-1e8ec1e1-4bce-432b-bc1c-8f47b60b9212.png)

**Comment by NickM-27** [comment]
Are you saying that the clip in the frigate UI the actual length and correct and the UI showing 15 seconds is wrong? 

We had some changes with how the segments are queried so they're more successful in getting the appropriate segments but seems it may be getting an extra segment than expected.

**Comment by saluther** [comment]
The duration shown on the HASS Card is correct. The actual duration/length should be 15 seconds. With RC2 the 28 seconds in the UI is incorrect.  The clip has 14 seconds added to the beginning that shouldn't be included.

**Comment by NickM-27** [comment]
@uvjustin I think this may be related to your recent changes, what do you think?

**Comment by uvjustin** [comment]
Yes, most likely.
The prior behavior was to clip the beginning of the clip to the desired start time. However, this time often doesn't align to a keyframe, and thus the clip would start from the next keyframe. This risks losing data, and the solution is to start from the previous keyframe (but Blake actually preferred not to probe for a keyframe at all, so we just don't clip the first segment now).
Given that this is adding more than 10 seconds to a clip, I'm guessing this user is using a codec with variable keyframe intervals. The previous version of Frigate was probably cutting clips too short, starting from the next keyframe and potentially losing data, but the camera itself is probably inserting a keyframe soon after motion is encountered, so the effect is not noticeable.
Regardless, I think the current behavior is more correct, and without transcoding it's not possible to get the clip cut exactly right. It will either be too long or too short. I suppose it is possible to expose that choice as an option.

**Comment by NickM-27** [comment]
@uvjustin thanks for the detailed explanation, that's more or less what I thought. I agree it's likely better to include extra recording vs cutting it short.

**Comment by uvjustin** [comment]
If we determine that we are ok losing some small amount of time in clips, say 1 or 2 seconds max, we could probably work around this issue.

**Comment by blakeblackshear** [comment]
At the moment this is expected behavior. Did you modify the segment length in your output args?

**Comment by divemasterjm** [comment]
> At the moment this is expected behavior. Did you modify the segment length in your output args?

well, after installing rc2, i have 11 cameras, 5 recording 24/7 with motion detection on, the others only recording on motion. 
i have 2 issues.:
1.- when detecting motion on the cameras recording 24/7 the clip is all day long
2.- i have corrupted (i think) database on some cameras (ramdom) cause i cant access recordings.
i delete db, clips and recordings folders, start and everything is ok, except issue number 1.
the config for cameras.:
    record:
      retain:
        days: 14
        mode: all
      events:
        retain:
          default: 14
          mode: motion

**Comment by NickM-27** [comment]
> > At the moment this is expected behavior. Did you modify the segment length in your output args?
> 
> well, after installing rc2, i have 11 cameras, 5 recording 24/7 with motion detection on, the others only recording on motion. i have 2 issues.: 1.- when detecting motion on the cameras recording 24/7 the clip is all day long 2.- i have corrupted (i think) database on some cameras (ramdom) cause i cant access recordings. i delete db, clips and recordings folders, start and everything is ok, except issue number 1. the config for cameras.: record: retain: days: 14 mode: all events: retain: default: 14 mode: motion

Please make your own issue, the behavior you are describing is completely unrelated to what is being discussed above

**Comment by saluther** [comment]
> At the moment this is expected behavior. Did you modify the segment length in your output args?

That's an interesting question. In looking at the output args, I have the segment time set at 60. This is probably from carrying over the config from previous versions. Until RC2 it hadn't caused any problems. I see that the segment time for the config in the documentation is set at 10. I hadn't noticed that change. I will update the the config and see if that fixes difference between the duration on the HASS Card and the actual length of clip and report back.

**Comment by uvjustin** [comment]
A segment time of 60 will definitely cause this behavior even with standard codecs and short I-frame intervals.
If you set it to 10 you may still get extra time at the beginning at the clip, but it will be a max of ~10 secs assuming frequent I-frames.

**Comment by saluther** [comment]
I can report back that after changing the segment time to 10, the difference between the duration on the HASS Card and the actual clip length is 10 seconds or less.

**Comment by saluther** [comment]
This is a great project and well supported. Thanks to everybody for their help.
