### ISSUE TITLE
[FR] API to turn on/off detection/recording

### ISSUE THREAD

**Issue by cben0ist** [blakeblackshear/frigate#378]
Such feature would allow, for example, to only detect and/or record when Home Assistant alarm is "Armed"...

**Comment by blakeblackshear** [comment]
Duplicate of #242

**Comment by cben0ist** [comment]
Even though I found #242, my use case is more for security purpose (not recoding while someone in on the premise) rather that saving some cpu.
My 2 cents.

**Comment by blakeblackshear** [comment]
I appreciate the additional description of your use case. I expect the solution to meet the needs of both, and will keep it in mind.

**Comment by JonGilmore** [comment]
Just wanted to make a comment here to see if this api would also have the ability to disable the "save_clips" of a camera. The use case would be similar to what was requested here - I'd like to keep detection enabled but disable clip saving on internal cameras for when I'm home.

**Comment by cben0ist** [comment]
Agree, disable/enable save_clips and records but keep detect and rtmp for my use case.
