### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by meteosat007** [blakeblackshear/frigate#379]
**Describe the bug**
I have a PI4 2GB running the new 64bit Rapspian OS and I have tried to load several ways your software using aarch64 as advised.

**Version of frigate**
Tried latest bersion and the stable version but maybe I'm doing something wrong.

The docker approach fails with 

docker run --rm --name frigate --privileged --mount type=tmpfs,target=/tmp/cache,tmpfs-size=100000000 -v /dev/bus/usb:/dev/bus/usb -v /home/pi/frigate/clips:/media/frigate/clips -v /home/pi/frigate/recordings:/media/frigate/recordings -v /home/pi/frigate/config:/config:ro -v /etc/localtime:/etc/localtime:ro -e FRIGATE_RTSP_PASSWORD='meteosat007' -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:0.8.0-beta1-aarch64
 * Starting nginx nginx
   ...done.
frigate.app                    ERROR   : Error parsing config: extra keys not allowed @ data['database']
pi@dockerpi:~/frigate/config $ 

I have added the latest config into a yml in the folder specified above.

All help and guidance welcomed here as it looks stunning.

Alan

**Comment by blakeblackshear** [comment]
The `database` and `model` sections of the config are not in the published beta version. Those snuck into the branch early. Make sure you remove them from your config and try again.

**Comment by meteosat007** [comment]
Hi Blake,

Yes that worked better.

One last thing my RTSP feed is  admin:Mxxxxxxxx@192.168.9.167:554/Streaming/Channels/401/  .

How shall I add into the config as this 

    ffmpeg:
      inputs:
        - path: rtsp://viewer:admin:Meteosat007@192.168.1.167:554/Streaming/Channels/401/


fails with 

frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for back: 38
frigate.app                    INFO    : Capture process started for back: 39
detector.coral                 INFO    : Starting detection process: 35
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.
frigate.video                  INFO    : back: ffmpeg sent a broken frame. something is wrong.
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : back: ffmpeg sent a broken frame. something is wrong.
frigate.video                  INFO    : back: ffmpeg process is not running. exiting capture thread...
frigate.video                  INFO    : back: ffmpeg sent a broken frame. something is wrong.

Also tried this 

    ffmpeg:
      inputs:
        - path: rtsp:/ <rtsp://admin:Mxxxxxxx7@192.168.9.167:554/Streaming/Channels/401/>/admin:Meteosat007@192.168.1.167:554/Streaming/Channels/401/

Hangs at 

 * Starting nginx nginx
   ...done.
frigate.mqtt                   INFO    : MQTT connected
detector.coral                 INFO    : Starting detection process: 35
frigate.app                    INFO    : Camera processor started for back: 38
frigate.app                    INFO    : Capture process started for back: 39
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.

Check the cameras in VLC and they play ok...

So close now and your help gratefully received.

Alan

**Comment by MikEarpp** [comment]
Hello Alan,

Each camera has its URL format.

Everything is indicated in the [readme file](https://github.com/blakeblackshear/frigate/tree/release-0.8.0#configuration).
Reread this page carefully and you will have the answer to your questions.

**If** rtsp://admin:Meteosat007@192.168.9.167:554/Streaming/Channels/401/ is correct **in VLC of your PI4**, just copy the same link in the Frigate configuration file. It should work.

Have you tried this ?:

```
cameras:
  back_or_your_camera_name:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Meteosat007@192.168.9.167:554/Streaming/Channels/401/
        #- path: rtsp://fake.fake/juste_here/for_ex/ample
```

Instead of:

```
    ffmpeg:
      inputs:
        - path: rtsp:/ <rtsp://admin:Mxxxxxxx7@192.168.9.167:554/Streaming/Channels/401/>/admin:Meteosat007@192.168.1.167:554/Streaming/Channels/401/
```

With >**my**< cameras the link looks like this:
        - path: rtsp://10.0.0.202:554/user=user&password=password&channel=0&stream=0.sdp?`<

If you wish, you can comment out a line (i.e. ignored by Frigate in this case) with the first character on the line #

You must respect the tab in this file (as in many others).
Eliminate the tabs, replace them with the space character.
Respect the number of spaces.
[...](https://www.google.com/search?client=firefox-b-d&sxsrf=ALeKk02Ou_U5tQcJf_dPGYCPTSWa09D3Gw%3A1608045572042&ei=BNTYX8iHAoiKlwSU-brQBA&q=how+to+explain+a+python+tabulate&oq=how+to+explain+a+python+tabul)

The characters **<** and **>** are invalid in a URL.

In this same configuration file you can add (if you don't have Google Coral):
```

detectors:
  coral:
    type: cpu
```

You can forget **-e FRIGATE_RTSP_PASSWORD='meteosat007'** in your command line because you should understand.

**Comment by meteosat007** [comment]
Hi Mike,

Yes followed several read me files and they seem to have changed very slightly over revisions. However I can confirm that the one you directed me too works and now the task to get proper images and get detection running….

Thanks

Alan

**Comment by asemev** [comment]
Btw, if you are running the beta 0.8 (https://github.com/blakeblackshear/frigate/tree/release-0.8.0), you dont need to configure anything in the config.yaml. The below steps install everything automatically without config.yaml modifications. Delete everything you added in the config.yaml and then:.

1. Add Supervisor Frigate NVR Beta add-on
2. Add HACS frigate repository
3. Configuration - Integrations - Add Frigate (this adds all camera and sensor entities)

Blake helped me out a lot with setting it up and he taught me all this. I can help you further.  but i am no expert by any means. For example, I cannot get the notifications attach the snapshot images.

But got everything else working with 2 cameras and a nice inferencing speed of 20ms average (with Coral) and overall CPU perormance around 25-30%. Used big area masks and 720p resolutions and lowered camera fps to 15, to achieve this performance which i am very satisfied with.

Hope this helps.
