### ISSUE TITLE
Mean color for a zone

### ISSUE THREAD

**Issue by Pascal66** [blakeblackshear/frigate#3795]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to follow color day by day from swimming pool/garden so that I can follow efficience of filling/rain

**Describe the solution you'd like**
Mean or median color of a zone

**Additional context**
![image](https://user-images.githubusercontent.com/3041616/189079074-76b614ef-25be-451e-a8c4-55ec584a0431.png)

**Comment by blakeblackshear** [comment]
You want to be able to detect when it's raining? What for?

**Comment by Pascal66** [comment]
@blakeblackshear this zone have a real mean of color, mowned, or not, need more water or not.
Trust me, color of a zone work fine, but cant achieve with frigate easily.
This work on my swimming pool to.
Can imagine if a car enter in a zone, then the color must be different too
