### ISSUE TITLE
Stops detection of objects when one person appears in a region

### ISSUE THREAD

**Issue by alex-savin** [blakeblackshear/frigate#38]
Hey Folks,

I have a problem with detecting a "person" object. When it appears in a region frigate stops detecting any objects at all. I was trying to play around with variable "min_person_area", setting it low (70) or high (7000), but nothing helps.
Might be I setup something wrong, could you please help me to figure out a proper way.

Thanks in advance

Frame with the "car" objects 
<img width="1049" alt="frigate_cars" src="https://user-images.githubusercontent.com/10366351/58374387-504b7100-7f0b-11e9-84a5-1a4da5995e62.png">

Frame with the "car" and "person" objects, but there are no more frames
<img width="1028" alt="frigate_person" src="https://user-images.githubusercontent.com/10366351/58374406-9d2f4780-7f0b-11e9-8db9-03a94054044f.png">

**Comment by blakeblackshear** [comment]
Do you see any errors in the logs when a person steps in the frame?

**Comment by alex-savin** [comment]
@blakeblackshear 
```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/object_detection.py", line 55, in run
    self.cameras[frame['camera_name']].add_objects(parsed_objects)
  File "/opt/frigate/frigate/video.py", line 260, in add_objects
    y_location = min(int(obj['ymax']), len(self.mask)-1)
TypeError: object of type 'NoneType' has no len()
```

**Comment by alex-savin** [comment]
@blakeblackshear I found the issue, I was missing mask file `back-mask.bmp` in the config folder

Sorry for disturbing!

PS: Could you please brief explanation for the mask and how to use it?! Thank you in advance

**Comment by blakeblackshear** [comment]
It must be the same dimensions as your video feed, and if the bottom center of the bounding box for the detected person is on a black pixel, it will be ignored.
