### ISSUE TITLE
On-device object training support within Frigate

### ISSUE THREAD

**Issue by Shreyas-R** [blakeblackshear/frigate#3806]
**Describe what you are trying to accomplish and why in non technical terms**
Need on-device object training support within frigate to reduce object detection errors and to train custom objects which are not available in the default model used by Frigate. 

**Describe the solution you'd like**
It would be great if Frigate supports,
1. Basic tensorflow lite model with [on device training](https://www.tensorflow.org/lite/examples/on_device_training/overview) support.
2. UI within frigate to locally train and untrain object models (something similar to [double-take](https://github.com/jakowenko/double-take) used for face recognition).

**Describe alternatives you've considered**
Frigate+ is coming which is cloud based solution. I'm looking for something offline and local solution. The following are the other alternatives but they have their own disadvantages. 

_To reduce object detection errors_: 
1. Apply object detection filters tweaking `min_score`, `threshold` and `mask`. 
2. Train custom tensorflow lite models outside Frigate and use them within Frigate.

_To train custom objects_: 
1. Train custom tensorflow lite models outside Frigate and use them within Frigate.

**Additional context**
Raising this feature request after facing lot of false detections in Frigate which is discussed [here](https://github.com/blakeblackshear/frigate/issues/3792) #3792.

**Comment by blakeblackshear** [comment]
I don't think this will ever be implemented directly in Frigate. I could see it as a companion service alongside Frigate like double take, but my time and energy will be going into Frigate+.
