### ISSUE TITLE
Display time length

### ISSUE THREAD

**Issue by siri10086** [blakeblackshear/frigate#3813]
Can you add the length of this video event here

<img width="1439" alt="222" src="https://user-images.githubusercontent.com/61342291/189507420-b98ca50a-95e9-498e-b420-86d18ff34444.png">

**Comment by banthungprong** [comment]
I added this to "web/src/routes/Events.jsx" in Line458:
 <span className="text-red-300">{(event.end_time - event.start_time).toFixed(0)}s</span>
And changed the next line by adding End Time in the following div.
 
![frigate Events with Length](https://user-images.githubusercontent.com/59219161/195351470-98818b31-125e-44fa-84ab-d40d1f281196.jpg)

(Right now I started playing with the local environment in VS Code and trying to understand the code...).
