### ISSUE TITLE
immediate replicate footage to OneDrive

### ISSUE THREAD

**Issue by marcgarciamarti** [blakeblackshear/frigate#3818]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to replicate my local footage to OneDrive as soon as it is recorded, so that in case my home gets broken into footage is preserved in case my frigate endpoint is destroyed
 
**Describe the solution you'd like**
Footage is stored locally on the hard drive of my local server. Motioneye does feature this ability out of the box.

**Describe alternatives you've considered**
Motioneye does offer this feature out of the box

**Comment by NickM-27** [comment]
This is something that can be done on the host like https://itsfoss.com/use-onedrive-linux-rclone/ or other options as well. 

I don't think this is something that has value being baked directly into frigate.

**Comment by ehn** [comment]
> This is something that can be done on the host like https://itsfoss.com/use-onedrive-linux-rclone/ or other options as well.
> 
> I don't think this is something that has value being baked directly into frigate.

If you wanted to make a backup of Frigate's media store and database, it would make sense to do that on the host. However, there is a use case for only backing up (some) events to the cloud.

For example, you might want events with `person` or `car` to be backed up immediately but not care much about other things. At a remote site with a cellular-network or satellite uplink, you might not even have enough bandwidth, especially in the "up" direction, for a continuous full backup.

It doesn't seem entirely outrageous that Frigate would support this, though a better solution might be something outside Frigate that uses MQTT and the HTTP API to be notified and make backups of certain events.

**Comment by NickM-27** [comment]
> If you wanted to make a backup of Frigate's media store and database, it would make sense to do that on the host. However, there is a use case for only backing up (some) events to the cloud.
> 
> For example, you might want events with `person` or `car` to be backed up immediately but not care much about other things. At a remote site with a cellular-network or satellite uplink, you might not even have enough bandwidth, especially in the "up" direction, for a continuous full backup.

I definitely agree with you, and I don't think doing it on the host makes that less of a possibility.

From my perspective, frigate should give the user the tools to: be alerted of new footage, filter what is important, and upload / backup to wherever they want. 

If we were toadd onedrive then there's a request for Dropbox and the list will get longer and longer, 

> It doesn't seem entirely outrageous that Frigate would support this, though a better solution might be something outside Frigate that uses MQTT and the HTTP API to be notified and make backups of certain events.

In my opinion, this would be ideal. I think it's definitely possible for a user to set this up today via MQTT and our http API. I'm sure there's optimizations / other APIs that could make it easier.

**Comment by ArcaEge** [comment]
> If we were toadd onedrive then there's a request for Dropbox and the list will get longer and longer

Would adding rclone support be possible?  The user could run `rclone config` to configure it, then Frigate could run `rclone sync` (with all the arguments of course) when needed. It is obviously a little janky but it would be better than nothing and could be labelled as an 'advanced' feature or something.

(sorry to reply on an old issue)

**Comment by NickM-27** [comment]
I don't think there's any reason frigate needs to be involved in that, rsync can do that by itself

**Comment by ArcaEge** [comment]
Would it not be better to have it integrated directly into Frigate? It would mean that:
1. rsync only needs to run when there's a new motion event, not poll every minute or so. This could perhaps be fixed by using a filewatcher on the folder but I'm not sure how reliable that'd be.
2. As @ehn said, it would allow for filtering by event types.

I might be able to submit a PR to add this feature, does that seem fine? (Not a promise yet, I'll see if I can find time.)

**Comment by NickM-27** [comment]
You can use MQTT to trigger it to get whatever behavior you want, no need to watch files directly. 

Doing the basic part in frigate would make it easier for the user but as more users want more specificity the complexity increases greatly. 

Certainly something that may come in the future but seems perfectly achievable using existing information
