### ISSUE TITLE
[Config Support]: Failed to connect

### ISSUE THREAD

**Issue by cmeans** [blakeblackshear/frigate#3835]
### Describe the problem you are having

Latest Home Assistant on a VM
Used Haas to install Frigate via UI
Logs confirm frigate is running:
``

However, during Home Assistant -> Settings -> Integrations -> Add Integration -> Frigate, neither of the suggested URLs work.  No obvious info in the logs.

I've manually added a `frigate.yml` to see if that would help...it didn't.  I've manually added `media_source` and `http` `configuration.yaml` entries, didn't help.

How do I determine what the correct URL is, or how can I figure-out what's wrong?

### Version

No web UI yet

### Frigate config file

```yaml
Instructions do not mention creating one as yet.
```

### Relevant log output

```shell
2022-09-13 17:40:48.569 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You should have a web UI, as frigate will work without the integration installed. If you don't have a webUI then odds are your configuration is invalid. What do the frigate addon logs say?

**Comment by cmeans** [comment]
What's the URL for the web UI?  There is no Frigate entry in the tabs list on the left.
Where would I find the Frigate addon logs?

Thanks!

**Comment by NickM-27** [comment]
The webui will show up on the left if you've installed it as an addon. And to view logs go to `Settings -> Add-ons -> frigate`

**Comment by cmeans** [comment]
Settings -> Add-ons -> frigate (there is no frigate)

I followed the instructions and try to add the Integration...and that's where I'm getting the `Failed to connect` message.  

Maybe a screen shot will help:
<img width="1440" alt="Screen Shot 2022-09-13 at 6 43 59 PM" src="https://user-images.githubusercontent.com/5384091/190028623-c460f2c3-1400-488d-bdf1-3659e39152cf.png">

**Comment by cmeans** [comment]
Maybe I'm confusing things between an Addon and an Integration?  Is there more than one way to install Frigate into the Home Assistant instance?

**Comment by NickM-27** [comment]
[Please read the docs](https://docs.frigate.video/installation), specifically 

> Frigate is a Docker container that can be run on any Docker host including as a [HassOS Addon](https://www.home-assistant.io/addons/). Note that a Home Assistant Addon is not the same thing as the [integration](https://docs.frigate.video/integrations/home-assistant). The integration is required to integrate Frigate into Home Assistant.

**Comment by cmeans** [comment]
Thank-you.  I've clearly not been reading for comprehension...was in too much of a rush...and a newbie at HA so I was mixing up the terminology.  I'll start a new thread if I continue to have problems...they'll likely be different than this particular one.

**Comment by asemev** [comment]
Hi, i have the same issue. how did you fix it? thx
