### ISSUE TITLE
FFMPEG Input_Args on Beta

### ISSUE THREAD

**Issue by kowalke** [blakeblackshear/frigate#384]
FFMPEG bow giving input errors after uninstalling beta. Beta was giving input_args error. This is after uninstalling, never could get beta to run.

Fontconfig error: Cannot load default config file
Traceback (most recent call last):
  File "detect_objects.py", line 441, in <module>
Starting detection process: 19
Attempting to load TPU as usb:0
    main()
  File "detect_objects.py", line 196, in main
    ffmpeg_input = get_ffmpeg_input(ffmpeg['input'])
KeyError: 'input'

web_port: 5000
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
save_clips:
  clips_dir: /media/frigate
mqtt:
  host: core-mosquitto.local.hass.io
  user: mqtt_user
  password: mqtt_password
ffmpeg: {}
cameras:
  Camera1:
    input: 'rtsp://user:password@192.168.1.xxx:554/Preview/h264_01_main/'
​
Running on Raspberry Pi 4 64, Debian 10 Home Assistant Supervised addon installed per this guide: 
https://community.home-assistant.io/t/installing-home-assistant-supervised-on-a-raspberry-pi-with-debian-10/247116

**Comment by kowalke** [comment]
Log from beta after reinstalling

 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    ERROR   : Error parsing config: expected a dictionary for dictionary value @ data['ffmpeg']

**Comment by tubalainen** [comment]
@kowalke 

There are many things in play here, i´d recommend you to start from scratch.

- Take a deep breath, all is going to be all right.
- Make a backup of all your configuration
- Remove all previous frigate instances `docker stop frigate ; docker rm frigate`
- Go to: https://github.com/blakeblackshear/frigate/tree/release-0.8.0#installing and make sure that your docker instance got all parameters (I can see that you did not pass the tmpfs volume parameter to the docker container for instance)
- Create a new config.yml file in your configuration folder
- Just paste in and mod the bare minimum of configurations needed as per: https://github.com/blakeblackshear/frigate/tree/release-0.8.0#configuration and adapt accordingly with your system parameters
- Update the docker compose or command line parameters to match the ones here: https://github.com/blakeblackshear/frigate/tree/release-0.8.0#docker
- Start the docker container
- What does the log say?

**Comment by kowalke** [comment]
I am running "supported" HassOS on Debian 10 on Raspberry Pi 4 4 gig. I did a docker ps and don't show a frigate in docker on Debian. Is it a container in HassOS?

CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
81359422fac1        homeassistant/aarch64-hassio-supervisor                 "/init"                  12 hours ago        Up 12 hours                                                                              hassio_supervisor
ea1f4d909d48        homeassistant/raspberrypi4-64-homeassistant:2020.12.0   "/init"                  2 days ago          Up 2 days                                                                                homeassistant
15220aadfcd1        esphome/esphome-hassio-aarch64:1.15.3                   "/init"                  4 days ago          Up 4 days                                                                                addon_15ef4d2f_esphome
45e9300d946c        homeassistant/aarch64-addon-samba:9.3.0                 "/init"                  6 days ago          Up 6 days                                                                                addon_core_samba
84cfda2120af        homeassistant/aarch64-addon-configurator:5.2.0          "/init"                  6 days ago          Up 6 days                                                                                addon_core_configurator
7229ada6097b        homeassistant/aarch64-addon-mosquitto:5.1               "/run.sh"                7 days ago          Up 7 days           0.0.0.0:1883-1884->1883-1884/tcp, 0.0.0.0:8883-8884->8883-8884/tcp   addon_core_mosquitto
8e36505a6510        homeassistant/aarch64-hassio-multicast:3                "/init"                  7 days ago          Up 7 days                                                                                hassio_multicast
c7542c512a7e        homeassistant/aarch64-hassio-cli:2020.11.1              "/init /bin/bash -c …"   7 days ago          Up 7 days                                                                                hassio_cli
cdc0babf852e        homeassistant/aarch64-hassio-audio:17                   "/init"                  7 days ago          Up 7 days                                                                                hassio_audio
c00195856e56        homeassistant/aarch64-hassio-dns:2020.11.0              "/init"                  7 days ago          Up 7 days                                                                                hassio_dns
5ee1cc568d19        homeassistant/aarch64-hassio-observer:2020.10.1         "/init"                  7 days ago          Up 7 days           0.0.0.0:4357->80/tcp                                                 hassio_observer

**Comment by blakeblackshear** [comment]
It should be there if it's running. What about `docker ps - a`?

**Comment by kowalke** [comment]
Thank you for the help. I reinstalled HassOS and updated docker, now its working. Thanks again.

**Comment by kowalke** [comment]
Also, I think I was using "input" in my config instead of "inputs"
