### ISSUE TITLE
Allow Birdseye and Snapshots to be roles so the feed / quality can be selected.

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#3841]
**Describe what you are trying to accomplish and why in non technical terms**
Currently both birds eye and snapshots appear to use the detection feed as they are both low quality AND some of my cameras have a different aspect ratio for the low quality feed so it is very obvious

**Describe the solution you'd like**
I would like to see birdseye and snapshots appear as roles so they can be attached to a specific feed for higher quality...

**Describe alternatives you've considered**
I don't really have an alternative if I increase the quality of my detection feed then it will hurt performance.

**Additional context**

**Comment by NickM-27** [comment]
To be used for snapshots & birdseye they must be decoded so using a different higher res stream will be considerably more CPU. Not to mention the differences between camera streams may make the snapshot be inaccurate. It would also disable the ability to use the snapshot configs like blinding box, timestamp, crop, etc

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/2199 for a similar request and what would be acceptable solution

**Comment by bagobones** [comment]
Thanks I will comment on that existing request.. Interestingly I did do a search before posting, guess I lost key word bingo.

**Comment by NickM-27** [comment]
I just realized that the OP closed that one but it's still open so I'll reopen it
