### ISSUE TITLE
Ability to ignore initial distortion from camera connect / reconnect as motion

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#3846]
**Describe what you are trying to accomplish and why in non technical terms**
When doing setup changes and restarting frigate or if WiFi coverage is poor for a camera a lot of motion events and extra detection can happen during the initial few seconds a feed is starting.

It would be nice if there was a way to filter out these issues on a per camera basis.. IE ignore 1-2 seconds after connect/startup for processing

**Describe the solution you'd like**
I would like a configuration option to defer detection on a camera for a set time after startup or reconnection.

**Describe alternatives you've considered**
Get better cameras / wire cameras but that is not always an option.

**Comment by NickM-27** [comment]
Can you elaborate on what symptoms you're seeing and any evidence for this behavior? It's not clear what exactly the issue is. 

Frigate runs one set of object detection on startup to detect objects that are already present (but they won't be considered true positive until motion occurs near them).

Frigate also uses the first 30 seconds on startup to establish a baseline to compare future motion against.

Both of which are by design.

**Comment by bagobones** [comment]
3 of my cameras tend to produce motion recordings when frigate restarts, OR when the camera reconnects after IT restarts / reconnects to WiFi

Note this isn't unique to Frigate Surveillance station also had this as well.

There are some sudden pixel flashes / corruption till the video feed stabilizes. Since a FULL restart is required to reconfigure Frigate I am just noticing a lot of these with configuration changes.. It clears up after a few seconds but I would prefer to just filter it out on those problem cameras.

Not sure if frigate handles reconnect (a camera goes offline and back) or FFMPEG does but when a camera is rebooted or disconnects/reconnects to wifi this happens as well again on some of my cameras after reboot the camera will take a moment to settle the light balancing or take a few seconds to switch to night mode as well.

All I am asking is to defer motion detection / event detection user configurable time on reboot or camera reconnect to not record these unstable video periods.

**Comment by bagobones** [comment]
Two of these cameras are Reolink cameras, which already have some knowing issues and required tweaks (I have followed the FFMPEG threads on those) so I think I will eventually replace them however the issue does happen with my other WiFI cameras just with less frequency than the 2 Reolink ones.

Also this is more about motion recording than object detection as object detection does ignore this for the most part however sometimes the jitter does cause it to think an object has moved and generates an object event on startup.

**Comment by NickM-27** [comment]
That's why I asked for clarification, it wasn't clear what you want. Now I see what you're saying.

To answer your question, frigate & ffmpeg handle reconnecting when a camera goes offline. Ffmpeg exits and frigate restarts it.

**Comment by bagobones** [comment]
> To answer your question, frigate & ffmpeg handle reconnecting when a camera goes offline. Ffmpeg exits and frigate restarts it.

Then what I am asking would be for a delay in processing motion/detection x seconds after FFMPEG starts to let things settle down.

**Comment by NickM-27** [comment]
Right, I understand
