### ISSUE TITLE
HWAcceleration diagnostic tools

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#3848]
**Describe what you are trying to accomplish and why in non technical terms**
FFMPEG is very fussy and changes between versions, this has been seen in MANY projects that use it. Looking at most of the support threads I propose providing a front end diagnostic that displays the "detected" capabilities of the system in a nice table

Second suggestion would be a tool that would let the end user test each of the recommended or available options against their camera feeds. Basically just two simple drop downs, 1 with a list of accelerations that passed / show as available and a second that lets the user select one of their configured camera feeds. The test then would display or output a clip using those settings.

**Describe the solution you'd like**
For a diagnostic just printing out the output of the various console commands that succeed or fail for Intel / AMD / NVEC etc to show what was detected. At the very least this would save time and be easy to bundle in the docker to cut and past into tickets.

Also as more options are added the user gets new tests to run.

**Additional context**
This is more of a suggestion than a feature request.. 
I have seen a lot of threads on hardware acceleration on this project already, but other projects also frequently have problems with FFMPEG HW support. Providing some front end tools should reduce support tickets or at least make it easier to troubleshoot.

This is are more up front solution / approach than https://github.com/blakeblackshear/frigate/issues/2587 which I think is also important once you have configured and started using acceleration.

**Comment by morpheus8888** [comment]
good idea

**Comment by NickM-27** [comment]
Not a full solution but https://github.com/blakeblackshear/frigate/pull/3931

**Comment by bagobones** [comment]
> Not a full solution but #3931

Will that just show the performance of what you have configured (very useful) or will it list all the possible hardware detected with zero use (more  like what I am asking to show what was found)?

The idea being that the diagnostic would just go and try everything and tell you what didn't error out.

**Comment by NickM-27** [comment]
It shows everything you're trying to use. Like I said not funny encompassing this but progress

**Comment by bagobones** [comment]
Understood thanks.. Still very useful to answer "is it working" for sure.
