### ISSUE TITLE
Ability to debug recordings in the UI

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#3856]
**Describe what you are trying to accomplish and why in non technical terms**
I am currently working through missed detections and false positives, the only way to re-test changes to my settings is to wait for them to happen again or try to re-create them (IE go out walk in front of a camera etc)

**Describe the solution you'd like**
In the debug view have the option to select a previous recording and run it through the debug process to see how detection would behave on the recording after changing the settings.

**Describe alternatives you've considered**
Just doing what I am doing now.. go out walk in front of the camera, move a car, wait for more events. The problem with waiting is that you have to go back and review the recording to see if something was missed.

**Additional context**
I think this would be a VERY powerful diagnostic / setup tool since the project is focused on object detection, it would drastically cut down on tuning time.

**Comment by NickM-27** [comment]
This is already possible manually using: https://docs.frigate.video/contributing#2-create-a-local-config-file-for-testing

At some point it would be nice to have a UI version of this.

**Comment by bagobones** [comment]
Thanks, that is the core of what I was looking for, maybe there should be a reference to that under the troubleshooting section not just the contribution section.. I do my best to read through the docs before posting but didn't see something like this or hit key word bingo to find it when searching.

Also great project, great work.. I have been creating a number of feature tickets  as I think this project is exciting and really an advancement over some other options out there.

**Comment by NickM-27** [comment]
> maybe there should be a reference to that under the troubleshooting section not just the contribution section

Feel free to make a PR to add it to another section, otherwise I will take a look at some point in the future.
