### ISSUE TITLE
[Q] Add Frame count to messages

### ISSUE THREAD

**Issue by scottgrobinson** [blakeblackshear/frigate#386]
I'm trying to compare the same video using both the new and old model.

Is there a way I can "easily" add the current frame count to the MQTT /event/start message? I have a CSV of old and new model results, but it's very hard to match up and compare at present.

I can probably work this out myself, but I'm asking on the basis of "someone might be able to tell me the answer almost immediatly because they are more familiar with the code"

:)

**Comment by blakeblackshear** [comment]
There is a process_clip.py in the code that was designed for this purpose. It can save each frame as a jpg in a directory.
