### ISSUE TITLE
Updated ffmpeg version?

### ISSUE THREAD

**Issue by n4w4k** [blakeblackshear/frigate#3870]
Frigate uses ffmpeg version 4.3, but this version does not support adding metadata to segments (in my case, to rotate the stream).
ffmpeg version 5.0 fixes that problem ( https://stackoverflow.com/a/71078228 ) but I don't know whether I can manually update ffmpeg's version inside frigate's container (and... whether I even should ?)
Or is there any plan for frigate to update this dependency in an upcoming release?

**Comment by NickM-27** [comment]
Frigate 0.11 (currently in RC) runs ffmpeg 5.1

https://github.com/blakeblackshear/frigate/blob/release-0.11.0/docker/Dockerfile#L85

**Comment by NickM-27** [comment]
It also supports running your own build if you want: https://deploy-preview-2829--frigate-docs.netlify.app/configuration/advanced#custom-ffmpeg-build
