### ISSUE TITLE
Ability to add descriptions to events

### ISSUE THREAD

**Issue by NickM-27** [blakeblackshear/frigate#3876]
**Describe what you are trying to accomplish and why in non technical terms**

When events occur, especially with the new event favoriting, you may want to add a short description.  This description will be shown in the UI so it is easy to skim and remember why a clip was favorited and is important. 

**Describe the solution you'd like**

Add a `user_description` field to the DB and show the description as well as button to edit in the UI.

**Describe alternatives you've considered**

Could save descriptions elsewhere

**Comment by bagobones** [comment]
I like this idea as it avoids having to re-watch the clip to figure it out. It is also good for documenting things if it is related to a police or insurance issue.

**Comment by jimtng** [comment]
It also needs to be searchable

**Comment by irakhlin** [comment]
@NickM-27, did not notice this open issue but did a first pass at adding this: https://github.com/irakhlin/frigate/commit/9b1f1ac493aa6d618c8f7a919e897c88a4c55e20  outside of renaming the field from description to user_description, what other additional could be made? Would this be entertained as a pull request?

**Comment by irakhlin** [comment]
> sit

Sounds good, I will maintain the added functions for now on my own branch to help with adding more functionality to amblegpt. Regardless feel free to let me know here when this feature would be entertained for merging in regardless of what code changes need to be made. Thus far I've added it to the event section, and have it expand the message on event selection, along with a dedicated search box to queries across the "description" field.. 

![image](https://github.com/blakeblackshear/frigate/assets/12637936/40875dfc-68a1-4c51-b262-cfcc45403eaf)

**Comment by NickM-27** [comment]
now that we are further along with the UI, I don't think this feature directly makes sense. exports will be the way to mark a review as important (retain it indefinitely) and name it what makes sense. Then it can be searched in the new UI
