### ISSUE TITLE
Display the first frame of the recoding in the recording view

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#3877]
**Describe what you are trying to accomplish and why in non technical terms**
I have a lot of motion recording time without object detection (bugs, squirrels, racoons, cats that did not detect, birds that did not detect). When reviewing a day it would be nice if the timeline was not visually blank.

**Describe the solution you'd like**
Show the first frame of recording, OR a more advanced option would be to store snapshots for the start of every motion event and display those as thumbnails.

**Describe alternatives you've considered**
Nearly every other NVR is based on motion and when reviewing a day shows thumbnails of the start of the video. While nearly always I care about people which works very well I have A LOT of recording time that is not accounted for by objects that are detectable.

**Additional context**

**Comment by NickM-27** [comment]
Probably requires extracting the key frame from the first segment of that hour

**Comment by bagobones** [comment]
> Probably requires extracting the key frame from the first segment of that hour

Has to account for the users pre recording time setting or it will never show anything relevant. 

Alternatively generate a snapshot of type Motion for the start of every recoding in the hour and display them like events and an optional index to the recording view.

**Comment by NickM-27** [comment]
> Has to account for the users pre recording time setting or it will never show anything relevant.

Pre recording only applies for events, not motion

**Comment by bagobones** [comment]
> > Has to account for the users pre recording time setting or it will never show anything relevant.
> 
> 
> 
> Pre recording only applies for events, not motion or 24/7 recording

That would explain a few recordings I have but that does make it simple.

**Comment by NickM-27** [comment]
The frigate ui is currently being rewritten and as part of this is no longer relevant
