### ISSUE TITLE
Native HEVC/H.265 support (to solve 'Playback cannot continue' error)?

### ISSUE THREAD

**Issue by pvi25** [blakeblackshear/frigate#3882]
I would like to be able to view HEVC/H.265 videos in the recordings section and not get a 'Playback cannot continue. No available working or supported playlists' error. I dont mind having to use a browser (like edge) that supports HEVC/H.265 (or maybe chrome with plugin could also work).

There is partly overlap with these issues:
- [https://github.com/blakeblackshear/frigate/issues/3054] (closed, posted something in there but not sure if that will be picked up)
- [https://github.com/blakeblackshear/frigate/issues/3561] (still open, but more about decoding)

But think my request is a bit different.

From what I understand, if frigate would be able to fetch some information from a HEVC/H.265 file, it would be able to display a meaningful/navigable Recordings screen (then it would only depend on the browser used if playback would be possible, but now it doesnt even get to that point).

The main stream of my Reolink 842A camera only supports HEVC/H.265 output, Lowering the resolution (as suggested in one of the above mentioned issues) doesnt change it to H.264 format (probably does work for other/older Reolink cameras). 

Alternatives considered:
- Using the ext RTMP stream (http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password). Best alternative until now, but resolution is only max 896x512 instead of the 3840x2160 4k resolution for the main HEVC/H.265 RTSP stream
- Using the sub RTSP stream for recording, only 640x360 resolution
- Ask Reolink to support H.264 for main stream or a main higher resolution RTMP stream. Will do that, but Reolink doesnt seem to be very responsive to requests.

Easiest would be if frigate could support HEVC/H.265 a bit better (at least show proper recordings screen)

**Comment by NickM-27** [comment]
Not sure what version of Frigate you are running, but h.265 is better supported in supported browsers on 0.11 RC3. if the browser is able to play the h.265 then it will be played by frigate, otherwise the error is shown. There is really not more that we can do to support h.265. 

The long term solution as discussed in other issues will be to provide post-recording processing hooks to transcode the recordings to h.264

**Comment by pvi25** [comment]
Ok, thanks, that probably explains, I installed the stable amd64 version about two weeks ago, from the logs it says 0.10.1-83481af, so not the 0.11 RC3, that would then probably solve my issue. Will try the RC3 version

**Comment by pvi25** [comment]
Indeed RC3 works like a charm regarding this (even in chrome with plugin works fine). Thanks!

**Comment by NickM-27** [comment]
Thanks for confirming 👍

**Comment by skupi20** [comment]
@NickM-27 as in version 12 there is a new function called restream. Something like that you can use for playback clips in webgui for better compatibility. The only difference will be use gpu for encoding and decoding simultaneously, or with jmpeg only gpu decoding.

Most ppl watching in webgui clips only needs to check something. When they need to analyze clips its more simple to download it and do it in another player or editor.
For fast playback will be nice use something like restream, when i can use compatible codec with my browser. Not only we can change codec, but also resolution. Most clips are recorded with highest resolution of camera, but watching them for example on cellphone its nonsense. Not only you cant see those additional details on small screen but also it took more bandwidth (when you are outside your home its important i think). Also for fast checking, it is enough to watch clips in 720p or smaller resolution. Like in restream function we could also choose codecs for that.

For firefox users like me it will be nice function. I dont wanna loose hvec efficiency, but for checking in browser recorded clips its pain to download files or changing to another browser compatible with hvec format.
