### ISSUE TITLE
[Support]: Getting invalid build on homeassistant when upgrading addon

### ISSUE THREAD

**Issue by jdeath** [blakeblackshear/frigate#3888]
### Describe the problem you are having

22-09-22 22:13:21 ERROR (SyncWorker_1) [supervisor.docker.addon] Invalid build environment, can't build this add-on!

Trying to upgrade from 3.1 to 0.11 on x86_64 homeasistant

### Version

.11

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
22-09-22 22:13:21 ERROR (SyncWorker_1) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

amcrest

**Comment by NickM-27** [comment]
Please try uninstalling the addon then reinstalling it instead of upgrading

**Comment by niemyjski** [comment]
uninstalling and installing worked for me, not sure what all I lost.

**Comment by NickM-27** [comment]
> not sure what all I lost.

Nothing, the config and media are not removed when uninstalling the addon

**Comment by jdeath** [comment]
> uninstalling and installing worked for me, not sure what all I lost.

Thanks that worked! I did not lose anything either.

**Comment by rugene76** [comment]
Now I'm really in the ditch.
On HA the upgrade failed so I did a uninstall/install.
After a reboot, the startup fails with errors like this; "Unable to read frames from ffmpeg process."

I was working fine pre upgrade.

What should I do to recover?
thanks
(running latest HA on intel hardware)

**Comment by NickM-27** [comment]
@rugene76 please make a new issue and provide the requested info
