### ISSUE TITLE
Implement Sub Labels to MQTT Events

### ISSUE THREAD

**Issue by Rogue136198** [blakeblackshear/frigate#3889]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to see a sub-label field added to MQTT events

**Describe the solution you'd like**
Currently we have:
`label: person`
I would like:
`label: person`
`sub_label: rogue1198136`

**Describe alternatives you've considered**
Alternatively I could settle for an option to have:
`label: person rogue1198136`

**Additional context**
I want to be able to have a Home Assistant automation that notifies of the specific person seen.

**Comment by NickM-27** [comment]
How are you having sub labels applied? Whichever option that is should be suitable to be used in HA automations as well. 

I understand the need but this is more complicated to implement than it seems.

**Comment by Rogue136198** [comment]
> How are you having sub labels applied?
Double Take is applying them via your previous work.

> I understand the need but this is more complicated to implement than it seems.

I expected it to not be easy. I already started looking into how I can use the DT MQTT event to do this instead and it also does not look easy. I just figure long term having this built into frigate MQTT events would be ideal.

**Comment by NickM-27** [comment]
See my guide for how to do it: https://github.com/blakeblackshear/frigate/discussions/2898

**Comment by NickM-27** [comment]
Okay I think I got it figured out

**Comment by Rogue136198** [comment]
> Okay I think I got it figured out

Just gave your PR a once over. It looks like what I was hoping to get. Assuming I am reading it right, it looks like as soon as Frigate figures out a sub label it will be included in the next MQTT event. Very nice work.

With this I expect I can use some simple logic to modify my notification blueprint to something like the following (not proper syntax):
if sub_label != null {
Title: '{{ sub_label }} seen • {{ camera_name }}' = "Rogue136198 seen • Backyard Camera" }
else {
Title: '{{ label }} seen • {{ camera_name }}' = "Person seen • Backyard Camera" }

**Comment by NickM-27** [comment]
Yes, it's important to point out that it will be included in the next MQTT update. It will not send out an update when the sub label is set. 

And yes I already tried that syntax as part of testing this PR and it works well
