### ISSUE TITLE
control label formatting for detected objects

### ISSUE THREAD

**Issue by steveneighbour** [blakeblackshear/frigate#39]
Noticed this today on a successful object scan, a person is picked up a decent distance from the camera (so they are pretty small) but the label drawn obscures the person.

![small_person](https://user-images.githubusercontent.com/13775628/59006436-4576d180-8865-11e9-8f75-90103209ec85.PNG)

Is it possible/feasible to control the label (eg remove the red background), in an effort to not obscure the detected object?

**Comment by blakeblackshear** [comment]
Looks like you are using 0.2.0-pre, right? What camera are you using? I need to tweak the position of the label a bit.

**Comment by steveneighbour** [comment]
i've been messing with the ffmpeg hardware decoding, so am using the latest git version from ffmpeg-subprocess branch.

These are from Hikvision cameras, at a pretty low res (width 640, height 360), 10fps

I'll have a quick play with util.py to alter the box, see if i can make it look cleaner

**Comment by steveneighbour** [comment]
i've added a car endpoint (just by copy/pasting your people endpoint), as that generates a lot more images than people in my street

Here are a few examples using different fonts/thickness/colours etc (i don't like any of them!)

![car1](https://user-images.githubusercontent.com/13775628/59076088-70b9f900-8917-11e9-9962-9cf5ab86261c.PNG)
![car2](https://user-images.githubusercontent.com/13775628/59076089-70b9f900-8917-11e9-9269-70a2f7a1e8e3.PNG)
![car3](https://user-images.githubusercontent.com/13775628/59081125-e336d300-892f-11e9-9732-b765e911fa4f.PNG)
![car4](https://user-images.githubusercontent.com/13775628/59081126-e3cf6980-892f-11e9-90b7-bae32510b4c7.PNG)
![car5](https://user-images.githubusercontent.com/13775628/59081164-0e212700-8930-11e9-80ac-da5f75253199.PNG)

I think perhaps stick with how you had it but, as you said, alter the positioning a bit so that small objects are not obscured so much?

Here is a car with the title removed entirely, i actually quite like that.  I'm only really caring about cars and people, so including the label doesn't really add value for me.

![car6](https://user-images.githubusercontent.com/13775628/59081269-88ea4200-8930-11e9-92db-6139d63c7e3c.PNG)
 
Might try with a 1080p version as well, see if it looks better
