### ISSUE TITLE
[Support]: Failed to restart add-on

### ISSUE THREAD

**Issue by limitless-code** [blakeblackshear/frigate#3913]
### Describe the problem you are having

After uninstalling older version 10 and Installing version 11.0 restart of Frigate add-on no longer works.

I have to stop the add-on and then start it and then it works

error message provided below.

Thank you.

### Version

11.0

### Frigate config file

```yaml
n/a?
```

### Relevant log output

```shell
Can't create container from addon_ccab4aaf_frigate-fa: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate-fa: Conflict ("Conflict. The container name "/addon_ccab4aaf_frigate-fa" is already in use by container "3aa89dac8e19df7754afef26e61e4ac6ca4db67b9a13166409e721641a16c561". You have to remove (or rename) that container to be able to reuse that name.")
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

n/a

**Comment by NickM-27** [comment]
> Can't create container from addon_ccab4aaf_frigate-fa: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate-fa: Conflict ("Conflict. The container name "/addon_ccab4aaf_frigate-fa" is already in use by container "3aa89dac8e19df7754afef26e61e4ac6ca4db67b9a13166409e721641a16c561". You have to remove (or rename) that container to be able to reuse that name.")


This looks like a supervisor issue not a frigate issue. Try restarting HA OS

**Comment by limitless-code** [comment]
Spot on. "Reboot Host" fixes the problem and now allows a restart of the frigate-fa 11.0 add-on without having to stop and then start it. no more error messages.

Thank you!
