### ISSUE TITLE
[Support]: Docker container keeps restarting

### ISSUE THREAD

**Issue by Kalougear** [blakeblackshear/frigate#3919]
### Describe the problem you are having

Hello guys,i just installed frigate with docker,specifically with portainer,my compose file is this 

```
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/sktech-server/frigate/config.yml:/config/config.yml
    ports:
      - 5000:5000  
      - 1935:1935 # RTMP feeds
    environment:
      - FRIGATE_RTSP_PASSWORD="removed"
     
```

the container starts but it was keep missing the ip and ports,i could see it live on the portainer.The logs of the container are below.

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Fatal Python error: Illegal instruction
> Current thread 0x00007fba4dcc4740 (most recent call first):
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 1108 in create_module
>   File "<frozen importlib._bootstrap>", line 565 in module_from_spec
>   File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1058 in _handle_fromlist
>   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 41 in <module>
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 790 in exec_module
>   File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "/opt/frigate/frigate/edgetpu.py", line 11 in <module>
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 790 in exec_module
>   File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "/opt/frigate/frigate/app.py", line 24 in <module>
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 790 in exec_module
>   File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "/opt/frigate/frigate/__main__.py", line 9 in <module>
>   File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
>   File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
> [cmd] python3 exited 260
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Fatal Python error: Illegal instruction
> Current thread 0x00007f8139bde740 (most recent call first):
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 1108 in create_module
>   File "<frozen importlib._bootstrap>", line 565 in module_from_spec
>   File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1058 in _handle_fromlist
>   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 41 in <module>
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 790 in exec_module
>   File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "/opt/frigate/frigate/edgetpu.py", line 11 in <module>
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 790 in exec_module
>   File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "/opt/frigate/frigate/app.py", line 24 in <module>
>   File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
>   File "<frozen importlib._bootstrap_external>", line 790 in exec_module
>   File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
>   File "/opt/frigate/frigate/__main__.py", line 9 in <module>
>   File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
>   File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
> [cmd] python3 exited 260
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [s6-finish] waiting for services.
> 
> [s6-finish] sending all processes the TERM signal.
> 
> [s6-finish] sending all processes the KILL signal and exiting.
> 
 it keeps looping with the same messaging as you see above...

### Version

-

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.107
  user: stefanos
  password: "removed"

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://fakeusr:fakepass@192.168.1.100:554/stream1
          roles:
            - rtmp
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo

**Comment by NickM-27** [comment]
Looks like your CPU doesn't support AVX and may not be compatible: 

https://github.com/blakeblackshear/frigate/issues/49
https://github.com/blakeblackshear/frigate/issues/1999

**Comment by Kalougear** [comment]
> 

Holy Shit! i didnt even thought this was possible since i upgraded my old laptop with a desktop to have better performances(in general not on frigate) my old cpu is like super old 15 year old,the "new" desktop cpu is AMD Athlon(tm) II X3 460 Processor ancient too

**Comment by NickM-27** [comment]
So what is your current CPU, AMD Athlon II ?

**Comment by Kalougear** [comment]
> So what is your current CPU, AMD Athlon II ?

AMD Athlon(tm) II X3 460

**Comment by NickM-27** [comment]
Yeah looks like it does not support AVX unfortunately: https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX

**Comment by Kalougear** [comment]
But i had a working frigate with this cpu on my laptop --->AMD A4-4300M APU TRINITY is it posible to fix this somehow?

**Comment by NickM-27** [comment]
> But i had a working frigate with this cpu on my laptop --->AMD A4-4300M APU TRINITY is it posible to fix this somehow?

The `AMD Athlon(tm) II X3 460` was released in 2011 and the `AMD A4-4300M APU TRINITY` was released in 2012 and is apart of the "bulldozer" group mentioned in the above link.

I would look through those issues and see if anyone found a solution but as far as frigate official, a CPU with AVX support is required.

**Comment by Kalougear** [comment]
on issue [#1999](https://github.com/blakeblackshear/frigate/issues/1999) there is a "fix" with a custom docker file i guess? how  can i implement this on my compose? where you i put the link of the docker file?

`[btoconnor](https://github.com/btoconnor) commented [on Jan 26](https://github.com/blakeblackshear/frigate/issues/1999#issuecomment-1022465497)

Sure - this is the Dockerfile I'm using: https://gist.github.com/btoconnor/e7bbd0c1f6727c235fa6db0c6377c4b4

I don't work with Docker that often, so if there's something I've messed up, feel free to correct me. This has been working with me for several months now though.

There's a couple of comments in there if you want to try and get grouper running instead of frogfish. I don't know what the practical implications are of using frogfish vs grouper, I just know the last time I tried to get grouper working, it was causing problems on my specific machine.`

**Comment by NickM-27** [comment]
You'd need to get that docker file and then build it. Similar to how we don't here: https://github.com/blakeblackshear/frigate/blob/3846a1380532427f2d6cc34896f508cfd5ec95b2/docker-compose.yml#L13

You'll also need to change the part that says `frigate:stable-amd64` to just be `frigate:stable`
