### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by rce1086** [blakeblackshear/frigate#3926]
### Describe the problem you are having

Cannot resubmit error report form, after cutting down the logs due to being told “comment too big”, initially, not I can’t get the submit button to work at all…

### Version

xyz

### Frigate config file

```yaml
N/a
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Frigate stats

```json
N/a
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/a

### Any other information that may be helpful

I’ve just filled out a long bug report for release, and I can’t submit the form - help!

**Comment by NickM-27** [comment]
If your logs are too long then you can use pastebin to include them.
