### ISSUE TITLE
Enable/Disable Individual Motion Masks by Home Assistant or time of day in Frigate

### ISSUE THREAD

**Issue by villasenor** [blakeblackshear/frigate#3927]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to enable or disable individual motion masks for individual cameras by either MQTT in Home Assistant or time of day in Frigate. I have cameras facing the street that get a lot of activity during the day, so I mask off the street so that I'm not getting alerted to every person who walks by on the sidewalk or every car that drives by. However, after dark I would want to know if someone is loitering in front of my house, etc.

**Describe the solution you'd like**
I want to be able to enable or disable individual motion masks for individual cameras by either MQTT in Home Assistant or time of day in Frigate. 

**Describe alternatives you've considered*
n/a

**Comment by NickM-27** [comment]
Hi, zones should be used to limit events to areas of interest. Our docs specifically explain why masks should not be used to mask out true positive objects: https://docs.frigate.video/configuration/masks

I am going to close this as motion masks should just cover things like trees, bushes, timestamps, etc. which are always going to be making motion day or night. Let me know if you disagree 👍 

There is also an existing feature request to have the ability to enable / disable zones dynamically which would go along with what you're suggesting: https://github.com/blakeblackshear/frigate/issues/3621

**Comment by villasenor** [comment]
Hi @NickM-27! I think you're right about the motion masking - zones would probably be better and #3621 is exactly what I'm looking for. I'll keep an eye on that issue. Thanks so much for your contributions to the Frigate project!

**Comment by NickM-27** [comment]
Awesome, I'll go ahead and close this then. Feel free to create a new request / issue if anything comes up 👍
