### ISSUE TITLE
[Support]: frigate docker not starting 

### ISSUE THREAD

**Issue by yacine-em** [blakeblackshear/frigate#3936]
### Describe the problem you are having

frigate docker not starting when firewall is activated in DSM
I guess a frigate tries to connect to a server when starting.
by deactivating the firewall, frigate start normally 

### Version

0.11

### Frigate config file

```yaml
classical config file
```

### Relevant log output

```shell
exit
```

### FFprobe output from your camera

```shell
non relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

g

**Comment by NickM-27** [comment]
Frigate has to connect to MQTT otherwise it won't work. Without any logs or information there's no way to help
