### ISSUE TITLE
[Support]: Error occurred when attempting to maintain recording cache

### ISSUE THREAD

**Issue by luzik** [blakeblackshear/frigate#3937]
### Describe the problem you are having

$ docker-compose restart frigate
Restarting frigate ... error
ERROR: for frigate  Cannot restart container
tried to kill container, but did not receive an exit event

### Version

11

### Frigate config file

```yaml
unrelated
```

### Relevant log output

```shell
$ docker-compose logs --tail 20 frigate
Attaching to frigate
frigate                   | [2022-09-25 15:57:56] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [2022-09-25 15:58:01] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate                   | [2022-09-25 15:58:01] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [2022-09-25 15:58:06] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate                   | [2022-09-25 15:58:06] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [2022-09-25 15:58:11] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate                   | [2022-09-25 15:58:11] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [2022-09-25 15:58:16] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate                   | [2022-09-25 15:58:16] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [2022-09-25 15:58:21] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate                   | [2022-09-25 15:58:21] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [2022-09-25 15:58:26] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate                   | [2022-09-25 15:58:26] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [2022-09-25 15:58:31] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
frigate                   | [2022-09-25 15:58:31] frigate.record                 ERROR   : could not convert string to float: ''
frigate                   | [cont-finish.d] executing container finish scripts...
frigate                   | [cont-finish.d] done.
frigate                   | [s6-finish] waiting for services.
frigate                   | [s6-finish] sending all processes the TERM signal.
frigate                   | [s6-finish] sending all processes the KILL signal and exiting.
```

### FFprobe output from your camera

```shell
is ok
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

vto

**Comment by NickM-27** [comment]
It seems for some reason ffprobe is returning weird data when it encounters corrupt segments. Does this keep going or stop if you let frigate run?

**Comment by luzik** [comment]
I can't stop container, after docker it do not run

$ docker-compose exec frigate bash 
OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown

**Comment by NickM-27** [comment]
Not sure what that command is, should just be `docker-compose up -d`

**Comment by luzik** [comment]
Few days ago I renamed camera. Maybe it is related with this ?

..more logs

$ docker-compose ps |grep frigate
frigate                  /init python3 -u -m frigate      Up             0.0.0.0:1935->1935/tcp,:::1935->1935/tcp, 0.0.0.0:5000->5000/tcp,:::5000->5000/tcp
$ telnet localhost 5000
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

**Comment by NickM-27** [comment]
No, it is just a bad recording segment usually from restarting a camera while it was writing a segment. If it happens continually for more than a minute then it might be a sign that recordings are not working. I've been able to reproduce it but it only happens when a bad recording segment is discarded and stops quickly after startup.

**Comment by luzik** [comment]
Ok.
Situation is now stable ..container is up, but it does not work, I can't stop it restart it nor exec bash. There is free space available. I do not know that I can do to diagnose it more

**Comment by NickM-27** [comment]
That sounds like a host or docker issue, I don't know why that would be the case. Maybe try restarting the host and see what happens.

**Comment by luzik** [comment]
Yeah, reboot fixed issue. Do not know what it was, but only frigate was affected. Thx
