### ISSUE TITLE
[EdgeTPU Support]: 

### ISSUE THREAD

**Issue by gfro84** [blakeblackshear/frigate#3944]
### Describe the problem you are having

I see with the new frigate integration a disabled mqtt entity for tpu (apex) temperature I'd be interested in using.

I know where to get the value on my host system, but I don't know where to mount it within the frigate docker so it can read it, or if there is a variable in the config file to tell frigate where to look. 

Any clues, I've searched documentation and can't find it. 

### Version

0.10.1-83481AF

### Frigate config file

```yaml
N/A
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

**Comment by NickM-27** [comment]
You don't need to provide it, just enable the sensor in HASS, the data is already inside frigate

**Comment by gfro84** [comment]
Wow, that easy. Thanks very much! 

Missed an obvious thing to try there.

**Comment by gfro84** [comment]
Closed
