### ISSUE TITLE
[Support]: 64bit Image not updated?

### ISSUE THREAD

**Issue by boehser-enkel** [blakeblackshear/frigate#3945]
### Describe the problem you are having

blakeblackshear/frigate:stable-amd64 is still on 10.1
Should i use blakeblackshear/frigate:stable?

### Version

-

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

### Any other information that may be helpful

-

**Comment by blakeblackshear** [comment]
Yes, use the stable tag. All architectures are in a single image now.
