### ISSUE TITLE
[Camera Support]: ANRAN Q3 White

### ISSUE THREAD

**Issue by Dvalin21** [blakeblackshear/frigate#3953]
### Describe the problem you are having

So I purchased this camera and ran nmap (linux) on the IP and got the following "rtsp filter 554"  From what I can tell, nmap has to send request twice as much because of the  "filtered" status of the port (554). Attempted to view with vlc player which failed due to the filtered status of the port.

filtered
Nmap cannot determine whether the port is open because packet filtering prevents its probes from reaching the port. The filtering could be from a dedicated firewall device, router rules, or host-based firewall software. These ports frustrate attackers because they provide so little information. Sometimes they respond with ICMP error messages such as type 3 code 13 (destination unreachable: communication administratively prohibited), but filters that simply drop probes without responding are far more common. This forces Nmap to retry several times just in case the probe was dropped due to network congestion rather than filtering. This slows down the scan dramatically.

Requesting support for this camera if possible.

### Version

NA

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Anran Q3 White

**Comment by NickM-27** [comment]
If ffmpeg supports the camera then it's supported, otherwise it's not.

**Comment by NickM-27** [comment]
This camera is solar / battery powered. It does not support 24/7 recording / RTSP so it won't work with frigate.
