### ISSUE TITLE
Custom Events / Home Assistant notification APIs ?

### ISSUE THREAD

**Issue by bagobones** [blakeblackshear/frigate#3971]
**Describe what you are trying to accomplish and why in non technical terms**
Trigger an event start and end from home assistant based on "anything" but some examples being the door bell button pressed, garage opening / closings, gate opening closing, door opening closing, or even a light turning on.

**Describe the solution you'd like**
Something very easy to use like adding a notification event type in HA where you send in a description and some zone details. The idea being to FORCE capture when someone comes into the front door or rings the doorbell so it is nicely captured in the Frigate timeline. Main idea is that we KNOW someone or something is there so it would be good to trigger an event for that camera at that time.

This could be further used with cameras that support their own events in HA/ or directly in the future, such as cameras that have their own motion, person, line crossing, taper events etc. 

**Describe alternatives you've considered**
At the moment you could review all the events in HA, however if no event was generated due to object detection failure etc you may have to review an hour of recording to see who opened the door.. Doorbells are a bit easier as you can also capture snapshots in HA

**Additional context**
Under some situations I have had people exit the home (opened and closed the front door) without triggering an event from the doorbell came mostly because they where obscuring the camera by standing really close to it or processing just didn't pick them up for some reason.

**Comment by NickM-27** [comment]
I believe this is a duplicate of #1063

**Comment by bagobones** [comment]
It is, Thank-you
