### ISSUE TITLE
[Config Support]: Dynamically add camera

### ISSUE THREAD

**Issue by francoisdutoit** [blakeblackshear/frigate#3973]
### Describe the problem you are having

Hi,
I need to be able to update the config file (Add cameras) without having to restart frigate - as this will cause other cameras to go offline...
Is this possible - and if not - is it possible to run multiple instances of frigate?

 

### Version

0.10.1-83481af

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
What do you mean by add cameras? There's an existing feature request to be able to enable/disable cameras entirely.

**Comment by francoisdutoit** [comment]
Hi @NickM-27 
Say I have 3 cameras in my config and frigate is running - I now want to add an additional camera without having to restart frigate. So my other cameras keep recording without interruption..

**Comment by NickM-27** [comment]
No, it's not possible, I also (personally) am failing to see what the issue is with a 10-20second downtime.

**Comment by francoisdutoit** [comment]
Say I have three sites connected to my server via VPN. If site 1 needs to add cameras it would mean that both site 1,2 and 3 will have downtime.  I know 10-20 seconds is not much - but generally NVR's allows one to add and remove cameras and change config without any downtime.

**Comment by NickM-27** [comment]
I get it, but it's not possible currently and would require a considerable rewrite to make it work that way. 

As for your question about multiple instances, why would it not be possible or what do you mean?

**Comment by francoisdutoit** [comment]
So my other idea to make this work better is to have a docker instance running for each site. This means I can update each site as required without affecting the other sites... So just wanted to check if I would be able to do this - multiple frigate instances on the same server...

**Comment by NickM-27** [comment]
Yes of course, only thing to consider is that multiple instances can not share the same coral.

**Comment by francoisdutoit** [comment]
Ok Thanks - will keep that in mind. 

Thanks again for the quick response to my questions :)
