### ISSUE TITLE
Add configuration option to hide configuration file in debug view

### ISSUE THREAD

**Issue by jokakilla** [blakeblackshear/frigate#3981]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to give others access to the web interface without allowing them to access the password to my cameras which is contained in the configuration file's rtsp url.

**Describe the solution you'd like**
Add a configuration option to disable access to the configuration as json from the Web-UI.

**Describe alternatives you've considered**
-

**Additional context**

**Comment by NickM-27** [comment]
I think this might fall better into just having the ability to configure if the debug section is viewable at all. There has been talk in the past about rolls and how a user may be admin or normal user and admin would have access to more controls / debug info

**Comment by jokakilla** [comment]
That sounds pretty good. If there is already a request feel free to close this one. Maybe it makes sense to have a broader look on this by applying such a role model.

Nevertheless I was just about to setup the build environment as I thought my simple idea might be easy to implement ;)
Honestly I failed on the first step in the contribution guide -> call make
https://docs.frigate.video/contributing#1-build-the-version-information-and-docker-container-locally-by-running-make
Prerequisits are installed but make fails when trying to copy web/dist into web to the docker image because web/dist isn't there.
```
------
 > [stage-2 11/13] COPY web/dist web/:
------
failed to compute cache key: "/web/dist" not found: not found
```
Any tip?

**Comment by NickM-27** [comment]
@jokakilla You need to run `make web` first so web is built

**Comment by Iceman248** [comment]
I couldn't find anything, but is there a way to remove the "config" tab from the UI?
