### ISSUE TITLE
[Support]: StandAlne install

### ISSUE THREAD

**Issue by MyraBaba** [blakeblackshear/frigate#3986]
### Describe the problem you are having

Hi,

I am confused . Do I have to install Home Assistant to use Frigate ? 

Can I Install and use only firgate via docker ? 

### Version

dev

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

.

**Comment by NickM-27** [comment]
Home assistant is not required, all functionality exists without it. Frigate just integrates really well with home assistant

**Comment by MyraBaba** [comment]
docker run -ti   --name frigate   --restart=unless-stopped   --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000   --device /dev/bus/usb:/dev/bus/usb   --device /dev/dri/renderD128   --shm-size=64m   -v /Udata/frigate/storage:/media/frigate   -v /Udata/frigate/config.yml:/config/config.yml:ro   -v /etc/localtime:/etc/localtime:ro   -e FRIGATE_RTSP_PASSWORD='password'   -p 5000:5000   -p 1935:1935   blakeblackshear/frigate:stable
Unable to find image 'blakeblackshear/frigate:stable' locally

is this ok ?

**Comment by NickM-27** [comment]
> Unable to find image 'blakeblackshear/frigate:stable' locally

That means it should start downloading the image from dockerhub which is expected
