### ISSUE TITLE
[Config Support]: Failed to Connect

### ISSUE THREAD

**Issue by Frankenberrypi** [blakeblackshear/frigate#3992]
### Describe the problem you are having

I'm getting a failed to connect error when trying to setup the integration.  I already have the addon working with two cameras.  The default http://ccab4aaf-frigate:5000 does not work.  I have also tried:
http://[local ip address]:5000
https://[my prefix].duckdns.org/ccab4aaf_frigate-fa
https://[my prefix].duckdns.org/ccab4aaf_frigate-fa:5000
https://[my prefix].duckdns.org:5000
http://frigate:5000

I do use duckdns and pass the port to my local computer running home assistant.  Is that likely to be causing this issue?  

### Version

0.11.0

### Frigate config file

```yaml
Configuration seems to be working fine when accessing from the side bar
```

### Relevant log output

```shell
This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:51
Integration: Frigate (documentation, issues)
First occurred: 7:40:01 PM (3 occurrences)
Last logged: 7:44:23 PM

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name does not resolve]
Error fetching information from https://[my prefix].duckdns.org/ccab4aaf_frigate-fa/api/stats: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://[my prefix].duckdns.org/ccab4aaf_frigate-fa/api/stats')
Error fetching information from https://frankenberrypi.duckdns.org/ccab4aaf_frigate-fa:5000/api/stats: 404, message='Not Found', url=URL('https://frankenberrypi.duckdns.org/ccab4aaf_frigate-fa:5000/api/stats')
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

![image](https://user-images.githubusercontent.com/8370483/193378186-b04a0e73-b1bb-49c8-85ba-c85f04cd0b18.png)

**Comment by NickM-27** [comment]
Are you using the full access version of the addon?

**Comment by Frankenberrypi** [comment]
Yes, maybe I misunderstood what the "Version" field was for on the submission form.  
Frigate NVR (Full Access)
Current version: 0.11.0

**Comment by NickM-27** [comment]
Check the docs, you were using the wrong host name for the full access addon https://docs.frigate.video/integrations/home-assistant#configuration

**Comment by Frankenberrypi** [comment]
That was it.  Thanks for the help.
