### ISSUE TITLE
[Support]: Add a Wiki with configuration help

### ISSUE THREAD

**Issue by menkej** [blakeblackshear/frigate#3997]
### Describe the problem you are having

I recently installed Frigate and am quite happy with the possibilities and flexibility.

My Setup:
* Unraid/Docker
* Google Coral
* Annke C800 (2x)
* 3-5 Cameras to come

Still work todo like better event handling/notifications via ioBroker, etc. What is quite annoying is to find proper documentation, like camera model specific options, working in a non home assistant environment, FAQ, etc. It helps to search the discussions, but structure is lacking. I suggest enabling the Wiki feature in GitHub to work on documentation (distilled from discussions) together. I'm more than willing to contribute, as I still have some cameras to go.

### Version

0.11.0-3846A13

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

```json
Not relevant
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Annke C800

**Comment by NickM-27** [comment]
We have official docs which contain all this info and more https://docs.frigate.video

**Comment by menkej** [comment]
> We have official docs which contain all this info and more https://docs.frigate.video

I know about these docs but it is not *all* there. It is a complex system when it comes to integration (apart from HA) and camera model specific settings are lacking completely. Especially the latter could benefit from community input. Today you have to search a lot. That's all I'm saying.

**Comment by NickM-27** [comment]
Camera specific settings are here: https://docs.frigate.video/configuration/camera_specific

If there's something missing then would be happy to accept a PR to update them. In any case this is where such information would go, otherwise it would be difficult to keep both in sync with each other.

**Comment by menkej** [comment]
Fine. I'll submit a PR. Still I think this limits feedback from the users regarding camera specific issues a little, as it is (technically) harder to submit a PR than to edit a Wiki page...

How can I achieve that level 4 headlines are shown in the sidebar, @NickM-27 ?

**Comment by NickM-27** [comment]
They're added here https://github.com/blakeblackshear/frigate/blob/dev/docs/sidebars.js#L1 corresponding to which section it was added to.

**Comment by NickM-27** [comment]
That's done automatically by docasaurus. You just simple add the #### heading and docasaurus will add those after the deploy

**Comment by menkej** [comment]
This is not the case in my fork. Anyways, change is done and PR will be submitted tomorrow.

**Comment by NickM-27** [comment]
it might also be a netlify feature

**Comment by menkej** [comment]
> That's done automatically by docasaurus. You just simple add the #### heading and docasaurus will add those after the deploy

As I expected: this is not the case. Check the deploy preview (very nice feature ;-) ) here: https://deploy-preview-4005--frigate-docs.netlify.app/

![image](https://user-images.githubusercontent.com/12273047/194124133-c3e481fa-f445-45ae-9b88-dd0ff92bf3ae.png)

**Comment by NickM-27** [comment]
> As I expected: this is not the case

Incorrect, it is done automatically (notice how `Model/vendor specific setup` is there which you added in your PR). The only thing is that level four \#### do not get links there

**Comment by NickM-27** [comment]
I would suggest knocking all the headers down a level and that should get it the way you're wanting it to be

**Comment by menkej** [comment]
> > As I expected: this is not the case
> 
> Incorrect, it is done automatically (notice how `Model/vendor specific setup` is there which you added in your PR). The only thing is that level four #### do not get links there

This is exactly what I mean. They don't show up. Well might be better though if this sections grows. But for now I find it rather annoying.

**Comment by menkej** [comment]
> I would suggest knocking all the headers down a level and that should get it the way you're wanting it to be

by down you mean up, making ### out of ####, right?

**Comment by NickM-27** [comment]
> > I would suggest knocking all the headers down a level and that should get it the way you're wanting it to be
> 
> 
> 
> by down you mean up, making ### out of ####, right?

Correct, I meant "down" as in reducing the number of \# but I see how that is ambiguous
