### ISSUE TITLE
[Support]: RAM Usage Increases Linearly Over Time

### ISSUE THREAD

**Issue by FortranFour** [blakeblackshear/frigate#4006]
### Describe the problem you are having

RAM usage increases linearly over time, until it reaches about 90% of capacity and then drops about 5%, continuing the cycle, creating a sawtooth graph of RAM usage, when plotted over time. Restarting add-on resets RAM usage.

Platform is HassOS, running on HP EliteDesk 800 G4 Min PC with 8th Generation Intel i5-8500T, 32gb RAM, with USB Coral Edge TPU.

Operation otherwise appears normal.

### Version

0.11.0 

### Frigate config file

```yaml
mqtt:
  host: YY.YY.YY.39
  port: 1883
  user: XXXXXXXXXX
  password: YYYYYYYYYY

detectors:
  coral:
    type: edgetpu
    device: usb    
  
cameras:
  Front_door:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500    
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.24:8554/Streaming/Channels/202 
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 
      height: 360 
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,38,285,39,285,0,0,0
        - 640,360,640,116,588,229,551,206,515,237,470,360
    objects:
      track:
        - person
        - dog
        - cat
        
  Front:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500    
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.24:8554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 
      height: 360 
    record:
      enabled: True
      events:
        required_zones:
          - zone_2
    zones:
      zone_2:
        coordinates: 0,37,129,36,262,51,583,180,565,226,640,282,640,0,114,0,0,0
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,37,129,36,262,51,583,180,565,226,640,282,640,0,114,0,0,0
    objects:
      track:
        - person
        - dog
        - cat        
        
  Side_porch:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500    
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.24:8554/Streaming/Channels/302 
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 
      height: 360 
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 457,35,501,64,546,108,577,144,640,152,640,112,640,74,640,0,552,0,416,0
    objects:
      track:
        - person
        - dog
        - cat

  Driveway:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500    
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.29:8555/Streaming/Channels/202
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 
      height: 360 
    record:
      enabled: True
      events:
        required_zones:
          - zone_1
    zones:
      zone_0:
        coordinates: 543,360,437,156,389,94,393,72,360,72,345,47,250,50,64,360
      zone_1:
        coordinates: 235,56,352,58,344,23,256,23      
    snapshots:
      enabled: True
      
    motion:
      mask:
        - 269,0,236,26,258,42,66,360,0,360,0,0
        - 640,0,640,203,525,300,382,89,406,23
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - motorcycle
        - bicycle
        
  Bedroom_windows:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.32:8556/Streaming/Channels/102
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 
      height: 360 
    record:
      enabled: True
      events:
        required_zones:
          - zone_3
    zones:
      zone_3:
        coordinates: 640,0,640,360,517,360,257,0
    snapshots:
      enabled: True
    motion:
      mask:
        - 640,0,640,360,517,360,257,0
    objects:
      track:
        - person
        - dog
        - cat
        
  Streetside:
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.24:8554/Streaming/Channels/802
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 
      height: 360 
    record:
      enabled: True
      events:
        required_zones:
          - zone_4
    zones:
      zone_4:
        coordinates: 0,360,529,79,525,53,574,46,576,0,530,0,0,0
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,360,529,79,525,53,574,46,576,0,530,0,0,0
    objects:
      track:
        - person
        - dog
        - cat
        
  Garage_gate:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500   
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.24:8554/Streaming/Channels/402         
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 # 
      height: 360 # 
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,360,80,304,32,221,116,111,223,99,267,0,0,0
        - 456,94,586,253,587,237,512,124,640,156,640,0,361,0
        - 640,360,579,266,534,215,440,236,295,273,229,360
    objects:
      track:
        - person
        - dog
        - cat   
        
  Backyard:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500   
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.24:8554/Streaming/Channels/502        
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 # 
      height: 360 # 
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,261,137,186,179,114,429,105,536,38,576,0,0,0
        - 584,39,606,107,640,105,640,0
    objects:
      track:
        - person
        - dog
        - cat 
        
  Back_door:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500   
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.24:8554/Streaming/Channels/702        
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 # 
      height: 360 # 
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,259,166,263,177,218,185,174,294,148,338,0,0,0
    objects:
      track:
        - person
        - dog
        - cat 
        
  Garage_porch:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500   
    ffmpeg:
      inputs:
        - path: rtsp://XXXXXXXXXX@YY.YY.YY.29:8555/Streaming/Channels/402        
          roles:
            - detect
            - rtmp
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
    rtmp:
      enabled: True
    detect:
      width: 640 # 
      height: 360 # 
    record:
      enabled: True
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,99,74,274,293,183,287,0,0,0
        - 572,0,521,99,388,91,382,0
        - 640,167,541,324,520,313,640,77
    objects:
      track:
        - person
        - dog
        - cat
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-10-02 14:25:35] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
[2022-10-02 14:25:35] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-10-02 14:25:35] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-10-02 14:25:35] peewee_migrate                 INFO    : There is nothing to migrate
[2022-10-02 14:25:35] detector.coral                 INFO    : Starting detection process: 220
[2022-10-02 14:25:35] frigate.app                    INFO    : Output process started: 221
[2022-10-02 14:25:35] ws4py                          INFO    : Using epoll
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Front_door: 226
[2022-10-02 14:25:35] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Front: 228
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Side_porch: 230
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Driveway: 233
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Bedroom_windows: 236
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Streetside: 237
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Garage_gate: 238
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Backyard: 240
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Back_door: 242
[2022-10-02 14:25:35] frigate.app                    INFO    : Camera processor started for Garage_porch: 243
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Front_door: 245
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Front: 247
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Side_porch: 251
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Driveway: 255
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Bedroom_windows: 261
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Streetside: 263
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Garage_gate: 265
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Backyard: 279
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Back_door: 286
[2022-10-02 14:25:35] frigate.app                    INFO    : Capture process started for Garage_porch: 295
[2022-10-02 14:25:36] ws4py                          INFO    : Using epoll
[2022-10-02 14:25:38] frigate.edgetpu                INFO    : TPU found
[2022-10-02 14:25:48] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:37980]
[2022-10-02 14:26:08] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:37980]
[2022-10-02 14:28:38] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45738]
[2022-10-02 14:28:46] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:45738]
[2022-10-02 14:59:27] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35506]
[2022-10-02 14:59:47] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35506]
[2022-10-02 19:09:17] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56226]
[2022-10-02 19:14:53] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56226]
[2022-10-02 19:27:27] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2022-10-02 19:27:27] root                           INFO    : Waiting for detection process to exit gracefully...
[2022-10-02 19:27:57] root                           INFO    : Detection process didnt exit. Force killing...
[2022-10-02 19:27:57] detector.coral                 INFO    : Starting detection process: 22973
[2022-10-02 19:27:57] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-10-02 19:28:00] frigate.edgetpu                INFO    : TPU found
[2022-10-02 19:29:00] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41772]
[2022-10-02 19:29:08] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:41772]
[2022-10-02 22:16:20] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:50370]
[2022-10-02 22:16:51] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:50370]
[2022-10-03 08:48:02] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48244]
[2022-10-03 08:50:10] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48244]
```

### FFprobe output from your camera

```shell
Not relevant. (If deemed relevant, link to instructions on how to run this command would be appreciated.)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

 LTCMHT2722-28

### Any other information that may be helpful

See screenshots in post 6070 of https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/6197

**Comment by NickM-27** [comment]
Next time the RAM usage is this high there will be a few commands that you need to run which will explain what is using so much memory.

`docker exec -it addon_ccab4aaf_frigate df -h`
`htop` on your host or `docker exec -it addon_ccab4aaf_frigate apt-get update && apt-get install htop -y && htop`

**Comment by FortranFour** [comment]
First command yields:
` ➜  ~ docker exec -it addon_ccab4aaf_frigate df -h
Error: No such container: addon_ccab4aaf_frigate `

Second command yields:
`  
    0[||||||||||||||||||||||||||||||||||||||||||||||                                                                                                             28.2%]   3[|||||||||||||||||||||||||||||||||||||||||||||||||||                                                                                                         31.5%]
    1[|||||||||||||||||||||||||||||||||||                                                                                                                        21.5%]   4[|||||||||||||||||||||||||||||||||||||||                                                                                                                     24.0%]
    2[||||||||||||||||||||||||||||                                                                                                                               16.9%]   5[||||||||||||||||||||||||||||||||||||||||||||||||                                                                                                            29.5%]
  Mem[||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                                                                             5.73G/31.1G] Tasks: 14, 1 thr, 0 kthr; 2 running
  Swp[||||||||||||||||||||||||||                                                                                                                           1.20G/7.79G] Load average: 2.13 1.87 1.80 
                                                                                                                                                                        Uptime: 18 days, 05:56:52

  [Main] [I/O]
    PID USER       PRI  NI  VIRT   RES   SHR S CPU%  MEM%▽  TIME+  Command
    374 root        20   0 29680 19108  2308 S   0.0  0.1  0:00.29 ttyd -d1 -i hassio -p 63715 tmux -u new -A -s homeassistant zsh -l
    410 root        20   0 29680 19108  2308 S   0.0  0.1  0:00.00 ttyd -d1 -i hassio -p 63715 tmux -u new -A -s homeassistant zsh -l
    414 root        20   0  4348  4044  1996 S   0.0  0.0  0:01.39 zsh -l
    536 root        20   0  4404  3964  1072 R   0.7  0.0  0:00.05 htop
    376 root        20   0  4588  3464  3012 S   0.0  0.0  0:00.04 sshd: /usr/sbin/sshd -D -e [listener] 0 of 10-100 startups
    413 root        20   0  2792  2112  1304 S   0.0  0.0  0:00.66 tmux -u new -A -s homeassistant zsh -l
    409 root        20   0  2276  1904  1600 S   0.0  0.0  0:00.00 tmux -u new -A -s homeassistant zsh -l
     24 root        20   0   208    68    48 S   0.0  0.0  0:00.00 s6-supervise s6rc-oneshot-runner
     25 root        20   0   208    64    48 S   0.0  0.0  0:00.00 s6-supervise s6rc-fdholder
    373 root        20   0   208    64    48 S   0.0  0.0  0:00.00 s6-supervise sshd
      1 root        20   0   204    60    44 S   0.0  0.0  0:00.01 /package/admin/s6/command/s6-svscan -d4 -- /run/service
     15 root        20   0   208    60    48 S   0.0  0.0  0:00.00 s6-supervise s6-linux-init-shutdownd
    371 root        20   0   208    60    48 S   0.0  0.0  0:00.00 s6-supervise ttyd
     17 root        20   0   196     4     0 S   0.0  0.0  0:00.00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
     33 root        20   0   184     4     0 S   0.0  0.0  0:00.00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --`

**Comment by NickM-27** [comment]
What version of the frigate addon are you running? (full access?)

**Comment by FortranFour** [comment]
Affirmative:
Frigate NVR (Full Access)
Current version: 0.11.0

**Comment by NickM-27** [comment]
Then you need to run `docker exec -it addon_ccab4aaf_frigate-fa df -h`

**Comment by NickM-27** [comment]
also screenshot of htop will be much more helpful

**Comment by FortranFour** [comment]
Many thanks.
![Screenshot 2022-10-03 152520](https://user-images.githubusercontent.com/29408780/193696986-8fc1bfa4-d9ee-4c6a-854c-45f91673c953.png)



![Screenshot 2022-10-03 152735](https://user-images.githubusercontent.com/29408780/193697118-8ba4fe9a-92af-44ae-87bf-8e90ba83cdf3.png)


![Screenshot 2022-10-03 152856](https://user-images.githubusercontent.com/29408780/193697245-88086788-5b09-4e33-bfe3-978c6873a2b1.png)

**Comment by NickM-27** [comment]
It looks like your RAM using isn't that high (nowhere near the 90%) so it might be difficult to see what is using so much. 

Also looks like you'll need to run `ocker exec -it addon_ccab4aaf_frigate apt-get update && apt-get install htop -y && htop` because the frigate processes aren't showing up in the systems htop

**Comment by FortranFour** [comment]
Thanks again. Here you go:

![Screenshot 2022-10-03 154159](https://user-images.githubusercontent.com/29408780/193698886-22495ad7-b8ef-4031-9014-7b939bfe7c7b.png)

Also, the memory usage is reporting out as pretty high and continuously growing. The two vertical cliffs are when I restarted the Frigate add-on and the initial inflection point is when I updated Frigate to the current version (and there's 32gb installed, so it's a relatively good amount):

![Screenshot 2022-10-03 153844](https://user-images.githubusercontent.com/29408780/193698940-541f8e06-c765-46e9-9ec1-faabe6287e8e.png)

**Comment by NickM-27** [comment]
Okay you'll probably need to do them separately:
`dcker exec -it addon_ccab4aaf_frigate-fa apt-get update`
`dcker exec -it addon_ccab4aaf_frigate-fa apt-get install htop -y`
`dcker exec -it addon_ccab4aaf_frigate-fa htop`

**Comment by FortranFour** [comment]
Here they are. Last one is a doozy (in five parts):
![Screenshot 2022-10-03 155604](https://user-images.githubusercontent.com/29408780/193701187-d33867c9-9cae-4414-854a-918b7d573cde.png)
![Screenshot 2022-10-03 155701](https://user-images.githubusercontent.com/29408780/193701201-845d9b7f-eb1f-4c03-9711-e4fa8f28c9d7.png)
![Screenshot 2022-10-03 160035](https://user-images.githubusercontent.com/29408780/193701221-bfbbb778-4c9e-4094-8a0e-c01821eee049.png)
![Screenshot 2022-10-03 160139](https://user-images.githubusercontent.com/29408780/193701247-e38b010b-0a94-4ce9-a368-c807369ee64b.png)
![Screenshot 2022-10-03 160218](https://user-images.githubusercontent.com/29408780/193701264-18f6d955-48c3-41e4-a223-5853c512a105.png)
![Screenshot 2022-10-03 160254](https://user-images.githubusercontent.com/29408780/193701279-861788fd-7b2c-4602-8518-a60c534f9c34.png)
![Screenshot 2022-10-03 160325](https://user-images.githubusercontent.com/29408780/193701295-4a681fd2-20d6-4bbb-84f1-64b9451bec08.png)

**Comment by NickM-27** [comment]
Hmm, they all look quite normal, I don't see anything using loads of RAM. The shm is 8.1 MB and the cache is using 15MB, not really sure what could be going on here especially since this seems to be an isolated case 🤔 

Just for random attempt, maybe try using QSV instead of vaapi and see if that makes any difference https://docs.frigate.video/configuration/hardware_acceleration#intel-based-cpus-10th-generation-via-quicksync-1

**Comment by blakeblackshear** [comment]
There is a way to sort processes by memory usage in htop in the menu at the bottom. That may help identify the process using memory. Is the memory usage graph specific to the frigate addon or is that general ram usage? Also, I'm not sure if it will work, but you could try running `docker top` to see usage by container.

**Comment by FortranFour** [comment]
Changing hardware acceleration settings to the same as >= 10th Gen Intel CPUs (i.e., QSV) seems to have worked for this 8th Gen CPU. While I cannot tell if the hardware acceleration is actually speeding things up, it seems just as snappy as it was before. Thank you, both, Nick and Blake.
![Screenshot 2022-10-03 174133](https://user-images.githubusercontent.com/29408780/193710641-a505fc81-e19d-4e05-a1d3-6c1fac05a6ac.png)

**Comment by NickM-27** [comment]
Might have been a memory leak in the VAAPI intel driver then, not sure

**Comment by NickM-27** [comment]
Either way going to go ahead and close this for now, feel free to create a new issue if something else comes up.

**Comment by domneedham** [comment]
I too had the linear memory problem, definitely seems like a memory leak somewhere. 

Short term testing seems to show the 10>= intel hardware acceleration does sort the problem (also running the 8th gen i5 - believe it is the 8500T too). Will report back after leaving it running.

**Comment by FortranFour** [comment]
Good to know I haven't been alone with this issue. While changing the hardware acceleration mode stabilized memory usage, I have observed zero recordings since doing so. My situation is a little unique in that the cameras are at a remote location not easily accessed, but there are usually events that are triggered multiple times a day (but none since making the change). I suspect that Frigate has become nonfunctional since making the change, with the caveat that I am unable to go out in front of the cameras and jump around and test the system.

**Comment by NickM-27** [comment]
> Good to know I haven't been alone with this issue. While changing the hardware acceleration mode stabilized memory usage, I have observed zero recordings since doing so. My situation is a little unique in that the cameras are at a remote location not easily accessed, but there are usually events that are triggered multiple times a day (but none since making the change). I suspect that Frigate has become nonfunctional since making the change, with the caveat that I am unable to go out in front of the cameras and jump around and test the system.

hwaccel is not used for recording, so that really shouldn't have been affected by this change at all

**Comment by FortranFour** [comment]
I'm pleased to report I was wrong and it's working as it should after changing hwaccel. Thanks again.

**Comment by SgtBatten** [comment]
Ill have to keep this in mind for when I move my unraid server over to my HP prodesk which has an 8500. Thanks

**Comment by domneedham** [comment]
Following up from my transition, the RAM problem is definitely sorted. However, I seem to miss a lot of events that used to be detected before the switch. Not sure if the two are linked, but it is all I have changed (apart from updating to Frigate 0.11.1).
