### ISSUE TITLE
Handling for vod 503 errors caused by clip corruption

### ISSUE THREAD

**Issue by venix1** [blakeblackshear/frigate#4031]
**Describe what you are trying to accomplish and why in non technical terms**
Recovery of recordings for camera with corrupted video files 

**Describe the solution you'd like**
For frigate to handle this condition internally when possible.

**Additional context**
When trying to review recordings, the camera fail with a 503 error, leading to the nginx logs. 

media_set_parse_durations: clip duration 92310000 too large while sending to client, client: 192.x.x.x, server: , request: "GET /vod/2022-10/05/18/dining_room/index.m3u8 HTTP/1.1"

I could not find any relevant prior documentation, other than to use ffprobe to identify the failed file.  There is 5TB of video data split across different directories.  A bit of shell fu could do it, but frigate already knows which file is causing problems, it just isn't checking for it. 

Eventually enough information was pieced together to query the following in docker. `127.0.0.1:5001/vod/2022-10/05/18/dining_room` which returns the json being processed by vod.   The problem is obvious when reading the JSON. 

```
  "durations": [
    92310000,
    10011,
    10072,
    10058,
```

Looking at clips there is a matching entry as well.
```
      "clips": [
        {
          "keyFrameDurations": [
            92310000
          ],
          "path": "/media/frigate/recordings/2022-10/04/17/dining_room/21.30.mp4",
          "type": "source"
        },
```

This corrupted entry was listed under `recordings` in the database, removing that entry allowed vod to playback recordings again.  Rather than having than manual steps it would be good if frigate applied the same sort of sanity checks as vod for duration to avoid sending damaged files resulting in 503 errors.

**Comment by NickM-27** [comment]
Curious on your thoughts, this seems it could also be handled by a sanity check on the segment duration when storing the segment. Seems like that would be simpler as we don't want to add latency when building the VOD or MP4

**Comment by venix1** [comment]
I hadn't considered that, it definitely makes more sense to check while populating the database instead of waiting when it's accessed. 

I was also wondering if using a smaller number than what vod has as it's threshold would be beneficial.  The vod cap is 25 hours, which means any playback until that limit is met could include corrupted video.  Checking my database, anything greater than my segment length is corrupted in some way, although most don't affect playback.

I wonder, would there be a good way to see if the duration exceeds the next timestamp?  Since it's on insert, perhaps if end_time of the previous segment > than the new start_time.
