### ISSUE TITLE
Frigate CPU Load as a MQTT message

### ISSUE THREAD

**Issue by ekt-** [blakeblackshear/frigate#4035]
It would be useful to have an indication of the CPU load caused by frigate. 

It would become possible to have a history of the frigate cpu consumption as a graph in home assistant even if frigate is installed on a dedicated server and not as an addon.
For example it would allow at a glance to see regressions between versions of frigate or to understand if the hardware acceleration of the gpu is actually working.

This stat could maybe go in the already existing 'frigate/stats' topic

**Comment by NickM-27** [comment]
This is implemented in 0.12
