### ISSUE TITLE
Docs: Demo Link is not working

### ISSUE THREAD

**Issue by menkej** [blakeblackshear/frigate#4058]
### Describe the problem you are having

I view the documentation https://docs.frigate.video then I click on Demo in the top right. This brings up https://demo.frigate.video/ with a 404 - page not found

### Version

0.11.0-3846A13

### Frigate config file

```yaml
not relevant
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

not relevant

**Comment by blakeblackshear** [comment]
Thanks. It just needs to be updated to http://demo.frigate.video/

**Comment by menkej** [comment]
I see this fixed in dev branch already, so this can be closed.
