### ISSUE TITLE
[Support]: The Default Docker Pull Command is unknown

### ISSUE THREAD

**Issue by gcortes** [blakeblackshear/frigate#4063]
### Describe the problem you are having

I clicked on the Docker pull command on the Docker page for this app and tried to run it. It defaulted to default and errored out with:

Error response from daemon: manifest for blakeblackshear/frigate:latest not found: manifest unknown: manifest unknown

The command was: docker pull blakeblackshear/frigate

It worked when I changed the command to: docker pull blakeblackshear/frigate:0.11.1

You might consider updating the command on the Docker page if it's possible.

### Version

n/a

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
The recommended is `stable` which comes from [the tags list](https://hub.docker.com/r/blakeblackshear/frigate/tags) and [the frigate docs](https://docs.frigate.video/installation#docker). 

> Error response from daemon: manifest for blakeblackshear/frigate:latest not found: manifest unknown: manifest unknown
>
> The command was: docker pull blakeblackshear/frigate

We don't support the `latest` tag by design, and that is what docker defaults to if the user doesn't specify it.

**Comment by gcortes** [comment]
Thanks for the correct command. Is it possible to change the pull command on the right side of the page to reflect that? I won't make that mistake again, but others might click on the command to copy and run it.

**Comment by NickM-27** [comment]
Can you show a screenshot of that? I don't see it. 

And no I don't think it's possible to change, latest is the standard docker default when no tag is specified.

**Comment by gcortes** [comment]
This the url: https://hub.docker.com/r/blakeblackshear/frigate
I got it by doing a search on docker frigate.

<img width="1441" alt="2022-10-10_13-59-43" src="https://user-images.githubusercontent.com/5271010/194951697-ad0ed0e0-bf5c-4174-ab0a-8bd6d19203d2.png">

**Comment by NickM-27** [comment]
Yeah that can't be changed
