### ISSUE TITLE
[HW Accel Support]: RK3588 NPU

### ISSUE THREAD

**Issue by grinco** [blakeblackshear/frigate#4066]
### Describe the problem you are having

Radxa has released a new beast - Radxa Rock 5B - that is perfect for running HA and frigate. The hardware has a built-in neural processing unit. Docs are here: https://github.com/rockchip-linux/rknpu2 and https://github.com/rockchip-linux/rknn-toolkit2
While it does have an m2 e-key slot and could work with google coral, it would be amazing if you could get the built-in NPU to do the object recognition.

### Version

0

### Frigate config file

```yaml
-
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
This would be covered under https://github.com/blakeblackshear/frigate/pull/3626
