### ISSUE TITLE
[Support / Feature Request]: Mask the output

### ISSUE THREAD

**Issue by TheCherry** [blakeblackshear/frigate#4083]
### Describe the problem you are having

Is it possiple do add a mask (best will be with the same cordination system like frigate does it) to the ffmpeg output?
I want that the detection still take care about areas that are masked out but the output, for snapshots, live view and clips should have the mask.

the German law on data protection of recordings is very strict. And filming the public street or neighboring properties can be punished very highly here. But if I hide the areas before processing, the person recognition will not work well.

### Version

0.11.1-2eada21

**Comment by NickM-27** [comment]
This isn't possible currently, and would be quite difficult to do on clips.

Doing this would require decoding each frame of the clip and then reencoding which is a lot of work. 

I believe live view similarly would be difficult to support this.

Snapshots most likely could.

**Comment by TheCherry** [comment]
But the config:
```
ffmpeg:
  output_args:
    record:
```
Effects not the detection - only the clips and live view or not?
And ffmpeg have a `-filter_complex` argument. Didnt try that yet I don't understand the format atm.

**Comment by NickM-27** [comment]
I meant from the frigate perspective, I was unaware that ffmpeg supported this natively. I'll take a look and see

**Comment by TheCherry** [comment]
https://stackoverflow.com/questions/53518589/how-to-use-filtering-and-stream-copy-together-with-ffmpeg

**Comment by NickM-27** [comment]
Yes because you probably had `-c:v copy` in there which isn't allowed since you're trying to edit it

**Comment by TheCherry** [comment]
I am not so familar with ffmpeg. I just used the sample for enable audio. Ether I don't know much about the procedure from frigate. I want to take a close look at the sourcecode of frigate and maybe even help a bit. But unfortunately I don't have time for that at the moment.

**Comment by NickM-27** [comment]
Right, from the enable audio sample just remove the -c:v copy and add the filter you put above

**Comment by TheCherry** [comment]
but without copy its dont work?
I tried that now on the rtmp stream:

`rtmp: -f flv -vf crop=100:100:12:34`

```
[2022-10-14 15:43:06] ffmpeg.KameraEinfahrtSchuppen.rtmp ERROR   : [flv @ 0x55975a702780] FLV does not support sample rate 16000, choose from (44100, 22050, 11025)
[2022-10-14 15:43:06] ffmpeg.KameraEinfahrtSchuppen.rtmp ERROR   : [flv @ 0x55975a702780] Audio codec mp3 not compatible with flv
[2022-10-14 15:43:06] ffmpeg.KameraEinfahrtSchuppen.rtmp ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
[2022-10-14 15:43:06] ffmpeg.KameraEinfahrtSchuppen.rtmp ERROR   : Error initializing output stream 0:1 -- 
```

**Comment by NickM-27** [comment]
You keep changing what you're doing so you're running in to other issues.

Just try getting it working with recording as I explained above.

**Comment by TheCherry** [comment]
Then I have to setup a another cam first. I have only one outside and that is hard to debug with recordings. I try that later.
