### ISSUE TITLE
Allow us to buy you a drink

### ISSUE THREAD

**Issue by aav7fl** [blakeblackshear/frigate#41]
This is a great project. I really like the work that you've done here with Coral and TensorFlow. 

Please let some of us buy you a drink similar to how frenck [allows us to buy him coffee in his readme files](https://github.com/frenck/home-assistant-config#frencks-home-assistant-configuration). Maybe just add that badge to your project as well?

**Comment by blakeblackshear** [comment]
I went ahead and added a link to my Ko-fi page. Thanks for your support.
