### ISSUE TITLE
[Support]: Addon update in HomeAssistant - You have 3.1 installed. Click update to update to version 0.11.1

### ISSUE THREAD

**Issue by arsenicks** [blakeblackshear/frigate#4120]
### Describe the problem you are having

I can't update my addon in home assistant, I get a weird message regarding the versions.. Have you ever seen this ?

`You have 3.1 installed. Click update to update to version 0.11.1
`
Doesn't sound like an upgrade to me! When I try to update it fails. I'm trying to find the supervisor logs, I'm a bit lost since they've moved everything!

Here's the logs

```
22-10-18 11:14:14 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon ccab4aaf_frigate
22-10-18 11:14:15 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 78444336 completed
22-10-18 11:14:15 INFO (SyncWorker_8) [supervisor.docker.interface] Updating image ccab4aaf/amd64-addon-frigate:3.1 to blakeblackshear/frigate:0.11.1
22-10-18 11:14:15 ERROR (SyncWorker_8) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
```

### Version

DEBUG 0.10.1-83481AF

### Frigate config file

```yaml
N/A Doesn't go this far in the upgrade process.
```

### Relevant log output

```shell
22-10-18 11:14:14 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon ccab4aaf_frigate
22-10-18 11:14:15 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 78444336 completed
22-10-18 11:14:15 INFO (SyncWorker_8) [supervisor.docker.interface] Updating image ccab4aaf/amd64-addon-frigate:3.1 to blakeblackshear/frigate:0.11.1
22-10-18 11:14:15 ERROR (SyncWorker_8) [supervisor.docker.addon] Invalid build environment, can't build this add-on!
```
```


### FFprobe output from your camera

```shell
N/A Doesn't go this far in the upgrade process.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

dafang hack wyze cam v2 and wyzecam pan

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/3888

Also the versioning is correct. Previously the addons had their own version and it has now been updated to be consistent with frigate itself

**Comment by arsenicks** [comment]
> #3888

Oh god thanks, I looked at the open issue but didn't find that one.. I'm closing this one thanks a lot for your reply!!
