### ISSUE TITLE
0.8 beta 2: custom model crashes: IndexError: index 20 is out of bounds for axis 0 with size 20,

### ISSUE THREAD

**Issue by rb2k** [blakeblackshear/frigate#415]
**Describe the bug**
Using a model I previously trained (and that worked in [doods](https://github.com/snowzach/doods)): File "sqwrlmodel2.tflite" from https://github.com/rb2k/sqwrlmodel

Dimensions are 320x320 according to https://github.com/rb2k/sqwrlmodel/blob/main/sqwrlmodel2_metadata.json

Dictionary is:

```
0 person
1 cat
2 bird
3 squirrel
4 dog
```

**Version of frigate**
0.8b2

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
model:
  # Required: height of the trained model
  height: 320
  # Required: width of the trained model
  width: 320
```

**Logs**
```
Process detector:coral:,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap,
    self.run(),
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run,
    self._target(*self._args, **self._kwargs),
  File "/opt/frigate/frigate/edgetpu.py", line 149, in run_detector,
    detections = object_detector.detect_raw(input_frame),
  File "/opt/frigate/frigate/edgetpu.py", line 105, in detect_raw,
    detections[i] = [label_codes[i], score, boxes[i][0], boxes[i][1], boxes[i][2], boxes[i][3]],
IndexError: index 20 is out of bounds for axis 0 with size 20,

```

**Computer Hardware**
 - OS:  OpenSuse
 - Virtualization: Docker
 - Coral Version: USB
 - Network Setup: Wired

**Comment by blakeblackshear** [comment]
Looks like your output shape is different.

**Comment by rb2k** [comment]
Oh, interesting. I tried to find some tooling that can show information about the model.
I created it using Google AutoML Vision.

**Comment by rb2k** [comment]
So I uploaded https://github.com/rb2k/sqwrlmodel/raw/main/sqwrlmodel2.tflite to https://netron.app/ , but I can't really seem to find  the output shape

![image](https://user-images.githubusercontent.com/9519/102723541-80145380-42bd-11eb-9913-c8a702d12d92.png)

Any idea how I could verify the model output shape?

**Comment by rb2k** [comment]
I still have this issue on rc4 btw

**Comment by blakeblackshear** [comment]
Try running that same tool on the model mobiledet model to compare: https://github.com/google-coral/test_data/raw/master/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite

Your model needs to conform to these outputs.

**Comment by rb2k** [comment]
Input image tensor seems to be the same.
Output... kinda?

<img width="469" alt="Screen Shot 2021-01-22 at 4 55 39 PM" src="https://user-images.githubusercontent.com/9519/105563394-c3098280-5cd2-11eb-9c88-fc550f4ed328.png">
