### ISSUE TITLE
[Support]: Source install only ?

### ISSUE THREAD

**Issue by xbeaudouin** [blakeblackshear/frigate#4154]
### Describe the problem you are having

Hello,

My main OS is FreeBSD, I would like to install this on a jail or raw machine to replace another $VENDOR locked solution.
Docs provides only docker installation, which is good and nice for *some* people. 
But since my OS doesn't support recent docker, I would like to install this without taking hours to reverse engineering dockerfiles (that really I hate).
Is there any basic information about install it without docker 
Kind regards

### Version

0.11.1

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

I have added install method docker-compose, but really this doesn't exist... (even HASS can run on FreeBSD).

**Comment by NickM-27** [comment]
We aren't looking to support non docker based installs. 

See https://github.com/blakeblackshear/frigate/issues/3565#issuecomment-1200405222 for a similar question.
