### ISSUE TITLE
[Support]: HASS notification example in Frigate documentation unclear

### ISSUE THREAD

**Issue by jonrasp** [blakeblackshear/frigate#4159]
### Describe the problem you are having

I've got a single camera connected to Frigate, with HASS to provide notifications. I can achieve some of what I want with the hunterjm blueprint - notifications of people in a zone, with thumbnails.

My objective is to get notifications of people walking down a path.

There's an example in the Frigate documentation here:
https://docs.frigate.video/guides/ha_notifications
which provides examples of conditional triggers, and the thumbnail. However it's not clear if this requires modification before it's usable, or if I haven't copied/pasted properly.

Either way, thanks for the amazing software.

### Version

0.10.0

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
> My objective is to get notifications of people walking down a path.

So what are you not able to accomplish with the HA notification blueprint? This is a very generic ask which the blueprint is very capable of.

I also wrote this guide which explains how to build an automation manually if the blueprint doesn't work for you, https://github.com/blakeblackshear/frigate/discussions/2898

**Comment by jonrasp** [comment]
Thanks for offering support.
I’m after a notification when a person walks in one direction, but not the other. Something like: person detected in zone 2 after person detected in zone 1.

This is covered in the conditional trigger example in the frigate help, but it’s not clear how I should be modifying this example for my case.

I’ll have a go with the example that you’ve just shared with me; I can see where I should be changing names to suit my configuration.

**Comment by jonrasp** [comment]
To answer my own question - the examples work, but need a genuine MQTT message to trigger.

A question, if you don't mind:

The purpose of this is to notify me when somebody walks down the path towards my house, not when they walk in the opposite direction. I'm trying to achieve this by having a zone for the street and a zone for my garden path.

My understanding is that when a person crosses the threshold from street to path, the MQTT payload for _before_, _current zone_ will be _street_. And for _after_, _entered zone_, will be _path_. But sometimes the

**Comment by NickM-27** [comment]
> My understanding is that when a person crosses the threshold from street to path, the MQTT payload for before, current zone will be street. And for after, entered zone, will be path. But sometimes the

That doesn't seem quite right. Current zone is the zone the object is currently in. So if the object just passed from the `street -> path` then `before -> current_zones` would be `['street']` and `after -> entered_zones` would be `['path']`

`entered_zones` is a list of ALL the zones the object has ever entered.

**Comment by jonrasp** [comment]
Don't think I've seen that definition documented anywhere.

So for my use case, sounds like I want
```
before -> current zone ['street']
before -> entered zone not ['path']
after -> current_zones ['path']
after -> entered_zones ['path']

```
or would I have to be explicit and have `after -> entered_zones` as `['path','street']`?

**Comment by NickM-27** [comment]
I would just do `after.current_zones == [street]` and `path in before.entered_zones and street not in before.enrered_zones` (pseudo code)
