### ISSUE TITLE
[Config Support]: Frigate Proxy issues HASSOS (with working Frigate)

### ISSUE THREAD

**Issue by tyfoon** [blakeblackshear/frigate#4174]
### Describe the problem you are having

I have Frigate running fine on dedicated hardware (Ubuntu+Docker). Frigate is also accessible from any system within the network on 192.168.1.228:5000.

Next step is to integrate into HASS (HASSOS) by installing the frigate_proxy add on. 

Add on installs fine however can't get it to run (will not start add-on). Port is free

Setting of add_on below. Output of log of add -on added to output.

Any help welcome

<img width="1043" alt="Screen Shot 2022-10-26 at 13 53 20" src="https://user-images.githubusercontent.com/22179507/198019676-28a03b31-a7f5-45c5-9925-16547dc0ab11.png">

### Version

Frigate proxy 1.3, Frigate 0.11.1

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Frigate Proxy
 Proxy addon for Frigate
-----------------------------------------------------------
 Add-on version: 1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.10.5
 Home Assistant Supervisor: 2022.10.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:39:49] INFO: Starting NGinx...
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

**Comment by blakeblackshear** [comment]
My best guess would be that something else is already using port 5000. Maybe try changing the port.

**Comment by tyfoon** [comment]
That was also my first hunch but checked and is not the case.

Evenmore, the integration works just fine (which I should have mentioned) on the same port. It's only the add on that refused to run

**Comment by tyfoon** [comment]
> My best guess would be that something else is already using port 5000. Maybe try changing the port.

That was also my first hunch but checked and is not the case.

Evenmore, the integration within HASSOS works just fine (which I should have mentioned) on the same port. It's only the add on that refused to run

**Comment by blakeblackshear** [comment]
I'm guessing there is probably more info in the nginx error logs that aren't included in the addon log viewer. Do the supervisor logs have any info?

**Comment by tyfoon** [comment]
This was solved after upgrading HASSOS to newest version (I think now 9.3). 9.2 was out very short so maybe there was a bug there.
