### ISSUE TITLE
Frigate proxy

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#4178]
### Describe the problem you are having

When I try and start the proxy I get the following error:

`Port '5000' is already in use by something else on the host.`

My Home Assistant is running on 10.0.1.105 and Frigate is running on 10.0.1.64.

What am I missing?

### Version

0.11.1

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
You have another addon that is using port 5000, you'll need to configure the proxy (or the other addon) to work on a different port

**Comment by ripvega** [comment]
Thank you.

Assuming that 'the host' is where Frigate is running and 'the client' is
Home Assistant where I'm trying to run the proxy, the only thing on the
host is Frigate and that uses port 5000 so I'm confused as to the reason
for the message.

**Comment by NickM-27** [comment]
No, in this case as that is an HA log it is saying that some other HA addon is using port 5000

**Comment by tyfoon** [comment]
Probably AppDeamon in HASS. That runs on 5000
