### ISSUE TITLE
Customize Layout in Birdseye View

### ISSUE THREAD

**Issue by clearwave1** [blakeblackshear/frigate#4183]
**Describe what you are trying to accomplish and why in non technical terms**
I have multiple cameras that all have different resolutions and even different aspect ratios (e.g. doorbell cam). I would like to be able to control the layout of the cameras in birdseye view including order and size of each camera in the view.

**Describe the solution you'd like**
Configuration of this through config.yml would be fine. Something like a CSS grid config might work well for this.

**Describe alternatives you've considered**
I currently run multiple frigate cards in a custom grid layout in HA to achieve this but it is heavy on processing.

**Comment by NickM-27** [comment]
I think this is a duplicate of https://github.com/blakeblackshear/frigate/issues/3327 and https://github.com/blakeblackshear/frigate/issues/1926

**Comment by clearwave1** [comment]
The two items you mention cover some of what I'm suggesting but not all of it. Mine could replace those two and since I'm suggesting it be configured in the config file, it likely could be handled on the back end as it currently is. Of actual resolutions are not possible or practical, then a ratio for height and width per camera could work and then the browser would scale it.

Does this sound possible?

**Comment by NickM-27** [comment]
> Mine could replace those two

The feature requests are just feature requests, as the linked issues were created first it won't make sense for this to replace them. You're welcome to comment on the tickets with your ideas / expansions on what was already requested there. 

> since I'm suggesting it be configured in the config file, it likely could be handled on the back end as it currently is.

The actual implementation of the feature is up to whoever creates the PR and then those who review the PR, not the one requesting the feature.

> Of actual resolutions are not possible or practical, then a ratio for height and width per camera could work and then the browser would scale it.

This is already possible, the birdseye cam is derived from the detect streams and has its own resolution set in the config `birdseye -> width / height`. Each camera has its own resolution set in `detect -> width / height`

**Comment by clearwave1** [comment]
Thanks for clarifying the process. I might try to develop this myself and submit for consideration.

**Comment by NickM-27** [comment]
Sure, always happy to accept contributions
