### ISSUE TITLE
Drop-in edgetpu model replacement

### ISSUE THREAD

**Issue by cliffjao** [blakeblackshear/frigate#4190]
I recently found a drop-in edgetpu model trained on COCO2017 here: https://tfhub.dev/iree/lite-model/ssd_spaghettinet_edgetpu_large_320/uint8/nms/1

On my USB Coral unit, the performance is much slower (~100ms inference speed) but it also seems to be more accurate so far. From https://github.com/tensorflow/models/blob/master/research/object_detection/README.md: "When compared to MobileDet-EdgeTPU, SpaghettiNet models achieve +2.2% mAP (absolute) on COCO17 at the same latency."

Maybe someone can add this to the Documentation as an alternative, or package it in the Docker for easy switching.

**Comment by NickM-27** [comment]
For one, I'll link this: https://github.com/blakeblackshear/frigate/pull/3768#issuecomment-1279222806

> The vast majority of models available to try will all be trained on the same COCO dataset. The primary difference will be in the size of the images it is trained on. I have tried nearly all the various model architectures mobilenet/mobiledet/spagettinet/efficientdet and I don't see much of a difference in precision unless you go with larger image size versions from efficientdet. This has a significant tradeoff in terms of inference speeds.

Users always have the ability to run whatever model that they want. That being said, Frigate has a heavy focus on real time processing and I don't think we'd want to recommend a model which has that high of an inference speed especially for users that have more than a few cameras and only 1 coral.

**Comment by ehn** [comment]
> I recently found a drop-in edgetpu model trained on COCO2017 here: https://tfhub.dev/iree/lite-model/ssd_spaghettinet_edgetpu_large_320/uint8/nms/1

I one wanted to try this drop-in replacement, how would one drop it in?

**Comment by NickM-27** [comment]
@ehn you'd mount it into the frigate container as a volume mount (or include it in an already mounted volume). Then specify it in the frigate config 

```yaml
model:
  path: /path/my_new_model.tflite
```

**Comment by ehn** [comment]
Thanks for the quick reply!
