### ISSUE TITLE
Add deer for object detection

### ISSUE THREAD

**Issue by snarlingllama** [blakeblackshear/frigate#4217]
As the title implies, I would love to get deer added to the list of available object detection.

**Comment by NickM-27** [comment]
Frigate by default uses the COCO dataset which does not include deer, there is nothing we can do to change that. There is also https://github.com/blakeblackshear/frigate/discussions/1043 which talks about Frigate+ custom models and deer has been requested previously. That discussion is the proper place to request labels.
