### ISSUE TITLE
Alert if object in zone for longer then specific duration (Car is stopped for 5+ seconds)

### ISSUE THREAD

**Issue by k1n6b0b** [blakeblackshear/frigate#4226]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to alert only if an object (car) is in a zone for longer then a specific time

i.e. My camera sees the road in front of my house. I dont want alerts on every car passing by, but I do want alerts if a car stops for more then, say, 5 seconds (parked)

**Describe the solution you'd like**
a duration filter by zone and object type to trigger the object detected

**Describe alternatives you've considered**
None

**Additional context**
I searched but didnt find this discussed

**Comment by NickM-27** [comment]
I believe this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2397

**Comment by k1n6b0b** [comment]
Yes I believe it is! Well.. my vote for the loitering feature then :)
