### ISSUE TITLE
[Support]: Probelm uninstalling old version 3.  Can't install version 0.11

### ISSUE THREAD

**Issue by Klagio** [blakeblackshear/frigate#4238]
### Describe the problem you are having

I unistalled an older version 3. 

At reboot I get the below message, and it does not asllow me tro install new version 0.11
```

Invalid config
The following integrations and platforms could not be set up:

frigate ([Show logs](https://ccccc/config/logs?filter=frigate))
Please check your config and [logs](https://ccccc/config/logs).
```

### Version

3l

### Frigate config file

```yaml
c
```

### Relevant log output

```shell
c
```

### FFprobe output from your camera

```shell
c
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

c

**Comment by NickM-27** [comment]
Recommend checking out https://github.com/blakeblackshear/frigate/issues/3888

That log also seems to be related to the frigate integration and not the addon. 

Besides that, you may want to at getting support in the HA forums as this seems to be a supervisor issue and nothing we can do.

**Comment by adekloet** [comment]
do you have max-seconds (don't remember the exact config) in the frigate.yml? remove it, it failed with me when I upgraded from 3.1 to 0.11.1

by the way, the best way in my eyes was to remove frigate, keep the config/database and event files and reinstall it (I am on HASSOS with the addon. I then had to correct the config (removed the max-seconds and a restart started the upgrade process of the database etc.. everything worked again expect RTMP (still no solution to that)

**Comment by Klagio** [comment]
Thanks a couple of reboots fixed the issue. Now all cameras are green (were working all fine before) will have to investigate this

**Comment by NickM-27** [comment]
> Thanks a couple of reboots fixed the issue. Now all cameras are green (were working all fine before) will have to investigate this

Check the release notes, a few things that would catch this case. Provide logs so we can help specifically

**Comment by Klagio** [comment]
> That log also seems to be related to the frigate integration and not the addon.

yes now everything works fine, but still receive that notification each time I restart HA
