### ISSUE TITLE
[Config Support]: v12 - error on config file but not telling me what the error/line is. Does not start.

### ISSUE THREAD

**Issue by user897943** [blakeblackshear/frigate#4241]
### Describe the problem you are having

```
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
11:37:50.554 INF [api] listen addr=:1984
11:37:50.554 INF [rtsp] listen addr=:8554
11:37:50.554 INF [webrtc] listen addr=:8555
11:37:50.554 INF [srtp] listen addr=:8443
[2022-11-03 11:37:52] frigate.app                    INFO    : Starting Frigate (0.12.0-1bc9efd)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
live
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 344, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 78, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 977, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
live
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
exit OK
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
11:38:47.446 INF [api] listen addr=:1984
11:38:47.446 INF [webrtc] listen addr=:8555
11:38:47.446 INF [rtsp] listen addr=:8554
11:38:47.446 INF [srtp] listen addr=:8443
[2022-11-03 11:38:48] frigate.app                    INFO    : Starting Frigate (0.12.0-1bc9efd)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
live
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 344, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 78, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 977, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
live
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
exit OK
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Version

On logs above

### Frigate config file

```yaml
Will provide if it's relevant, please ask.
```

### Relevant log output

```shell
As above
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

Surely the validation should tell me where the error is... not helpful to just tell me that there is an error on the config file, if the parser knows where it is then tell me the exact line so I can go fix it!

**Comment by user897943** [comment]
I removed this from my config:
```
live:
  height: 972
  quality: 8
```
and Frigate now started successfully.

Where's the link to the documentation/changes for v12? The tag is live on DockerHub but no documentation?

**Comment by NickM-27** [comment]
We do not recommend trying random tags on dockerhub. That build is there for our testing and the reason there were no release notes and no docs changes is because it's not released (not even beta)

**Comment by user897943** [comment]
> We do not recommend trying random tags on dockerhub. That build is there for our testing and the reason there were no release notes and no docs changes is because it's not released (not even beta)

Thanks, think for a moment, don't you think it's a bit irresponsible to submit to dockerhub under the public account if it's just for internal testing? Why not post testing builds in private then? It's not like that's not possible... Please let me know.

**Comment by blakeblackshear** [comment]
Just about every open source project in the world publishes development builds publicly. Anyone is welcome to try them out, but development builds should only be used by those willing and able to read through the source code changes. Development builds should also be expected to have known and unknown issues.

**Comment by user897943** [comment]
> "...for our testing..." 

It sounds very different than "Anyone is welcome" does it not?

Wording matters. I don't dispute what you said, Blake. But the response by Nick had a totally different tone, sounded like it was exclusively internal.

**Comment by blakeblackshear** [comment]
We publish development builds for internal testing just like every other project does. Soon enough, automatic builds from the dev branch will be pushed to dockerhub on every commit. This is a common practice and also done by Home Assistant: https://hub.docker.com/r/homeassistant/home-assistant/tags

The official stance would be:
> Development builds are meant for testing or for those who want bleeding edge access to new features. You should expect undocumented breaking changes and known/unknown issues, so be prepared to read through the source code changes if you would like to use them. We aren't quite ready for general users to test them and don't have the bandwidth to provide config support after each commit during development. If you need this kind of help, please wait until a beta release.

The best place to look when using development issues will be the [draft release PR](https://github.com/blakeblackshear/frigate/pull/4055).

Tone is difficult to communicate in written text. As I am sure you have seen on here, @NickM-27 puts forth more effort than anyone else to help others. I tend to give people the benefit of the doubt.

**Comment by NickM-27** [comment]
> But the response by Nick had a totally different tone, sounded like it was exclusively internal.

A lot of "tone" on written text is perceived. I can see how it could be interpreted that way, but to be clear that was not my intended meaning. I was trying to explain why a build that is not meant as a release would be put up on dockerhub.

**Comment by user897943** [comment]
Thanks, I'll consider what you said
