### ISSUE TITLE
Option to disable Frigate+ UI elements

### ISSUE THREAD

**Issue by Mist-Hunter** [blakeblackshear/frigate#4250]
**Describe the solution you'd like**

Please add a config.yml option to disable Frigate+ UI references.

**Additional context**

I hesitated to make this request, as I'm very grateful for this awesome software and don't begrudge anyone trying to make a little money off all their effort, however, what attracted me to this project was the ability to set something up and control it myself. 

There are many commercial offerings out there, but there aren't many self-hosted options like Frigate. When a user has no plans to use Frigate+ the button effectively becomes an advertisement (intentional or not) other users of my system got confused when clicking on it.

**Comment by dugite-code** [comment]
If the devs wish to keep some form of "advertisement" for Frigate+ Perhaps having it as a gentle banner notice in the config section and hiding the UI elements elsewhere when an API key is not configured would be a nice option.
