### ISSUE TITLE
[Config Support]: Special Characters in Camera Password

### ISSUE THREAD

**Issue by NateMeyer** [blakeblackshear/frigate#4257]
### Describe the problem you are having

On the latest dev branch, only a few special characters are supported in the password.

Just adding all specials to the password portion of the regex fails, because the `rstp://` portion of the URL also gets sucked in and converted, encoding the slashes.

Does using `[\S]+@` for the password matching section of the Regex present any (security) issues?  Would also need to do something to explicitly match the start of the url path `://` so it isn't treated as matching the user part of the regex.

### Version

dev (0.12)

### Frigate config file

```yaml
cameras:
  cam1:
    ffmpeg:
        inputs:
          - path: rtsp://frigate:password!@#$%^&*()_-=+[]{}\/,.:;'"<>@192.168.0.123:554/cam/realmonitor?channel=1?&subtype=1
```

### Relevant log output

```shell
[2022-11-04 15:33:28] watchdog.cam1               ERROR   : Ffmpeg process crashed unexpectedly for nursery.
[2022-11-04 15:33:28] watchdog.cam1               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-11-04 15:33:28] ffmpeg.cam1.detect          ERROR   : [tcp @ 0x55a7d8282780] Port missing in uri
[2022-11-04 15:33:28] ffmpeg.cam1.detect          ERROR   : rtsp://frigate:password!@#$%^&*()-_=+[]{}\/,.:;'"<>@192.168.0.123:554/cam/realmonitor?channel=1&subtype=1: Invalid argument
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NateMeyer** [comment]
Also of note, the video.py:251 `self.logpipe.dump()` does not scrub user/password from the log.

**Comment by NickM-27** [comment]
The supported special characters are in this regex: https://github.com/blakeblackshear/frigate/blob/dev/frigate/const.py#L12

Notably `[` and `]` are not supported which is likely why that is having issues.

**Comment by NickM-27** [comment]
> Also of note, the video.py:251 `self.logpipe.dump()` does not scrub user/password from the log (or something around there).

Looks like it needs to be cleaned here as well: https://github.com/blakeblackshear/frigate/blob/dev/frigate/log.py#L59
