### ISSUE TITLE
[Support]: Recordings Overwriten after daylight saving time (back 1 hr)

### ISSUE THREAD

**Issue by tmjpugh** [blakeblackshear/frigate#4270]
### Describe the problem you are having

Recording from 2AM appear to be overwritten by new recording when the times jumps back due to DST.
I'm in Central US time.  At 3AM seemed that Frigate recognize time change (back 1hr) and begin overwrite the 2AM recordings.

### Version

0.11.1-2eada21

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Amcrest/various

**Comment by NickM-27** [comment]
This is the current expected behavior as was implemented in https://github.com/blakeblackshear/frigate/pull/3995 which was to avoid corruption.

Will be further improved in 0.12
