### ISSUE TITLE
Multiple overlapping save_clips being recorded.

### ISSUE THREAD

**Issue by mattheys** [blakeblackshear/frigate#430]
**Describe the bug**
When I enable save_clips I am getting multiple overlapping recordings, I think it has something to do with the ffmpeg segmentaition or multiple people being detected.

In my example the segmentation is set to 10s, here are two videos h28gzj and 85rxin with 2 people in them.

***h28gzj***
has a detection of 13:41:46 - 13:41:49
and a recording time of 13:41:35 - 13:41:54 

***85rxin***
has a detection of 13:41:53 - 13:42:00
and a recording time of 13:41:42 - 13:42:03

As you can see the recording overlaps by 12s.

What I guess I'm saying is there a way to tell if you are already recording a segment for one detection and another one goes off while it's still going can I just have one video of 13:41:35 - 13:42:00 and an array of detection json? Will increasing the segmentation size reduce this from happening? It's just I don't have much ram to create a large tmpfs. If it is just multiple objects being detected can I just get one video with an array of json objects that were detected in it?

**Version of frigate**
blakeblackshear/frigate:0.7.3-aarch64

**Detections**

```json
{
  "label": "person",
  "score": 0.96484375,
  "box": [ 728, 612, 854, 743 ],
  "area": 16506,
  "region": [ 602, 517, 902, 817 ],
  "frame_time": 1608644507.057639,
  "centroid": [ 791, 677 ],
  "id": "1608644506.068749-h28gzj",
  "start_time": 1608644506.068749,
  "top_score": 0.96484375,
  "zones": [],
  "score_history": [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ],
  "computed_score": 0.0,
  "false_positive": false,
  "end_time": 1608644509.237206
}

{
  "label": "person",
  "score": 0.73046875,
  "box": [ 683, 290, 856, 743 ],
  "area": 78369,
  "region": [ 505, 243, 1039, 777 ],
  "frame_time": 1608644518.650108,
  "centroid": [ 769, 516 ],
  "id": "1608644513.442781-85rxin",
  "start_time": 1608644513.442781,
  "top_score": 0.91015625,
  "zones": [],
  "score_history": [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ],
  "computed_score": 0.0,
  "false_positive": false,
  "end_time": 1608644520.91899
}
```

**Comment by blakeblackshear** [comment]
For now, there will be a clip for each object detected. If they overlap, you will get overlapping clips. There is a single cache for the camera, so this does not impact the tmpfs usage. It is not writing the stream twice to tmpfs. In the future, I may change the clips so they can be associated with multiple events.
