### ISSUE TITLE
Generate/Create Link to latest event per camera in HA

### ISSUE THREAD

**Issue by Coolie1101** [blakeblackshear/frigate#4313]
**Describe what you are trying to accomplish and why in non technical terms**
If possible, I would like to be able to link the latest event to a "picture-entity" card, so that the "tap action" takes me to the latest event clip.  

**Describe the solution you'd like**
Need help with linking the "tap action" in a "picture-entity" card to the latest event per camera.

**Describe alternatives you've considered**
None that I am aware of.

![image](https://user-images.githubusercontent.com/28989417/200492939-11a3f2d7-dd1d-4766-90c9-ff2679e638bc.png)

**Comment by Coolie1101** [comment]
Any response or alternatives to this?

**Comment by blakeblackshear** [comment]
The custom lovelace card already supports this. It's similar to how I have it configured.
