### ISSUE TITLE
Take snapshot from high resolution feed

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#4323]
I want to be able to run detection on the substream. However when saving snapshots, I want it to use the image from the high resolution main stream.

This snapshot is what should be displayed in the Web UI.

My main use case is that I want to send this image on via SMS or a push notification to a phone, and the lower resolution image makes it hard to make it who or what it may be.

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/2199
