### ISSUE TITLE
[Config Support]: Mount NFS or SMB for storage

### ISSUE THREAD

**Issue by agrieco** [blakeblackshear/frigate#4342]
### Describe the problem you are having

Is there any configuration which allows for this HASS addon to mount NFS or SMB storage for media recordings?  I'm not seeing anything documented..am I missing it?

### Version

0.11.1

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

M.2

**Comment by NickM-27** [comment]
From the docs:

> Due to limitations in Home Assistant Operating System, utilizing external storage for recordings or snapshots requires modifying udev rules manually.

https://docs.frigate.video/installation/#home-assistant-operating-system-hassos

**Comment by agrieco** [comment]
> From the docs:
> 
> > Due to limitations in Home Assistant Operating System, utilizing external storage for recordings or snapshots requires modifying udev rules manually.
> 
> https://docs.frigate.video/installation/#home-assistant-operating-system-hassos

ugh.  rtfm.  sorry bout that.

**Comment by NickM-27** [comment]
Relevant: https://community.home-assistant.io/t/wth-cant-i-mount-a-remote-share-nas-smb-nfs-etc-in-haos/468067/22

Let me know if you have any questions, otherwise I think we can close this 👍

**Comment by agrieco** [comment]
thx all.
