### ISSUE TITLE
[Feature]: Full screen for Birdseye

### ISSUE THREAD

**Issue by orson1282** [blakeblackshear/frigate#4357]
**Describe what you are trying to accomplish and why in non technical terms**
Birdseye in full screen without top and left navigation menus.

**Describe the solution you'd like**
Press F11 to go to full screen, or maybe a button to show Birdseye in full screen,
When in full screen, the top and left navigation menus disappear, when exiting full screen, they re-appear.
If not possible to auto disappear > re-appear, maybe a small floating button to hide/show them.

**Comment by NickM-27** [comment]
Birdseye already supports fullscreen, just click on the feed to go full screen mode.

**Comment by orson1282** [comment]
Oh wow., 🤦  awesome, thanks! 👍
