### ISSUE TITLE
Suggestion: Adding a MTTQ event for when FFMPEG crashes/connection to camera is lost 

### ISSUE THREAD

**Issue by jean-paullizotte** [blakeblackshear/frigate#4361]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

Hi.

I'm sorry if this seems too trivial and it should be easy for me to do on my own, but I'm just learning python now. I thought that this could be a great feature so that we can automate things like restarting plugs or switches when cameras go down.
I'll try to figure out how to implement it in the code, but is someone is quicker than me, I'd love to know!

Right now I have a "service" container that is running and contacts the frigate container, goes through the cameras, tries an FFprobe and then does a webhook to node red when a camera is unavailable. 

But since frigate already has a great watchdog service, thought it would be smarter to just use that.

**Comment by NickM-27** [comment]
I think this might make more sense as an MQTT topic which just keeps track of the current connection status for each camera as opposed to one topic which updates when a camera loses / gain connection, but definitely would help

**Comment by jean-paullizotte** [comment]
I tend to agree, but since the MQTT topic raise can be considered an event, it could also make sense to implement it there too. Either way, as long as it's possible to pick it up somewhere without parsing the logs, I'm happy.

**Comment by danruck** [comment]
Frigate reports camera FPS.  One of my cameras locks up sometimes and I've been checking if the FPS goes to 0 and giving it a powercycle using a smart plug when it dies.

**Comment by jean-paullizotte** [comment]
I imagine you gave to poll the cameras every second or so to accomplish this? Seems like a lot of wasted CPU cycles since frigate already has a watchdog service. It's a functional workaround, certainly, but what I'm proposing is using what's already in place, just better.
Thank you for the suggestion.

**Comment by NickM-27** [comment]
@jean-paullizotte no, no polling is involved, frigate already updated the camera fps in MQTT automatically.

**Comment by jean-paullizotte** [comment]
Ah yes, at a fixed interval, every 30s or so usually, correct? What would be the cost (CPU wise) of bringing this down to the second? Is it significant?

**Comment by NickM-27** [comment]
In the current version I think it will be negligible since the values are already set and it is just reading them. In the next version (0.12) however, it will be somewhat more as we will be including GPU and CPU usage stats which require a top, nvidia-smi, radeontop, etc. call to get info

**Comment by jean-paullizotte** [comment]
Thanks a lot for the info. I'm still struggling to get be able to see python as it should be, but I'm still thinking an event would be best. I'm just too poor at reverse engineering what has been done so far to do it quickly. I'll submit a branch/pull request if I get it working. I don't want to cause overhead either.

**Comment by NickM-27** [comment]
The reason I didn't suggest the solution above is because some users have said the fps never goes to 0 when the camera crashes, so a full solution is definitely still necessary. And yes always happy to accept contributions. 

Like I said before we'd want it to be something that allows the current state to be readable, so probably an attribute on each camera in MQTT like `/<camera_name>/connection`. We don't  want this to behave like the MQTT `/events` topic for example.

This would allow an event to be created for this being updated per camera, be able to reference each cameras current state, and also allow the frigate home assistant integration to create a `problem` sensor for each camera

**Comment by jean-paullizotte** [comment]
I see, it would also allow for an event that indicates when cameras come back online. Makes sense. I'll see what I can do. :)

**Comment by NickM-27** [comment]
@jean-paullizotte have you been able to work on this? I have realized I will likely need to implement this to implement a feature that is coming in 0.12. I am happy to help view and give pointers on a draft PR 👍

**Comment by jean-paullizotte** [comment]
Hey, @NickM-27 
No, not at all. Like I said, I’m a total newb to Python. So, I’m going through the basics at this point, understanding declarations and whatnot. Sorry.

**Comment by NickM-27** [comment]
> Hey, @NickM-27 
> 
> No, not at all. Like I said, I’m a total newb to Python. So, I’m going through the basics at this point, understanding declarations and whatnot. Sorry.

Not a problem, also turns out I won't need to do this for 0.12 anyway. If you have any questions happy to answer them

**Comment by jean-paullizotte** [comment]
@NickM-27 "Force dropping" the framerate to 0 as soon as the watchdog sees an issue, could be a good workaround. At least with Nodered and MQTT it seems to allow me to get decent notification for cameras that become unreachable, if not immediately.

**Comment by NickM-27** [comment]
this was implemented in https://github.com/blakeblackshear/frigate/issues/4998 and the home assistant integration uses this to mark a camera as unavailable as well
