### ISSUE TITLE
Set `-user_agent` in `ffmpeg` calls

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4369]
**Describe what you are trying to accomplish and why in non technical terms**
When spoofing who is connecting to my cameras, I can easily distinguish some like Home Assistant, or Google Chrome. But Frigate is also connected to them, but since `-user_agent` is not set, it's not easi to distinguish.

![image](https://user-images.githubusercontent.com/29582865/201259480-8b263732-8796-47c4-9cd6-2de3f159ebfb.png)

**Describe the solution you'd like**
This can be set with the `-user_agent` ffmpeg flag. In order of usefulness but also in order of difficulty to implement:

1. `-user_agent 'Frigate'` already much better than now
2. `-user_agent 'Frigate/0.11.1'`
3. `-user_agent 'Frigate/0.11.1 FFmpeg'`
4. `-user_agent 'Frigate/0.11.1 FFmpeg/3.1.2'`

I guess that, with the FFmpeg version in the string we don't need the `Lavf59.27.100` either. But it wouldn't hurt to even add the `Lavf59.27.100`, I guess.

**Describe alternatives you've considered**
I can probably set this by myself using the args, but I think this deserves to come by default.

**Additional context**
- Refs https://github.com/AlexxIT/go2rtc/issues/106

**Comment by AlexxIT** [comment]
I don't want generate ugly exec commands for ffmpeg. So it would be:
- for ffmpeg input: `go2rtc/ffmpeg`
- for ffmpeg output: `ffmpeg/go2rtc`
- for go2rtc client: `go2rtc/version`

**Comment by felipecrs** [comment]
Sure. That's million times better than the current already. Thank you!

**Comment by felipecrs** [comment]
- Ops, I guess you meant to comment on: https://github.com/AlexxIT/go2rtc/issues/106?
