### ISSUE TITLE
Upgrade Python

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4394]
Python 3.10 and 3.11 have brought several performance improvements. I wonder if we can't benefit of them by upgrading Python (we are using Python 3.9).

**Comment by NickM-27** [comment]
A number of dependencies for frigate don't support > 3.9, for example: https://github.com/google-coral/pycoral/issues/58

**Comment by felipecrs** [comment]
Thanks for the heads up.

**Comment by witold-gren** [comment]
https://github.com/feranick/pycoral/releases

**Comment by witold-gren** [comment]
Good discussion about `pycoral` and update this library to version 3.10 or higher
https://github.com/google-coral/pycoral/issues/85

**Comment by systemtester** [comment]
Base image updates appear to resolve this (when complete). #15103

**Comment by levski** [comment]
am new to linux and am figuring out frigate with a tpu. this compatibility got me stumped.

The following packages have unmet dependencies:
 python3-pycoral : Depends: python3-tflite-runtime (= 2.5.0.post1) but it is not going to be installed
                   Depends: python3 (< 3.10) but 3.11.2-1+b1 is to be installed
E: Unable to correct problems, you have held broken packages.

how'd y'all get around it?

**Comment by hawkeye217** [comment]
You should follow the Getting Started guide to install Frigate. You don't need to install those drivers directly. 

https://docs.frigate.video/guides/getting_started

Additionally, if you continue to have issues, you should open a support discussion rather than commenting on old feature request threads.

**Comment by levski** [comment]
> You should follow the Getting Started guide to install Frigate. You don't need to install those drivers directly.
> 
> https://docs.frigate.video/guides/getting_started
> 
> Additionally, if you continue to have issues, you should open a support discussion rather than commenting on old feature request threads.

yeah, after some more googling found a post that said so.
oh, didn't notice it was opened back in 2022.
all i saw what that there was a couple of recent post, figured it was still something people talked about.

**Comment by felipecrs** [comment]
Too bad #15103 is still Python 3.11. Maybe it would be worth switching base image to Python, to take newer ones like 3.13 while still using bullseye base `python:3.13-bullseye`.

**Comment by NickM-27** [comment]
I don't think so, that will cause a lot more problems as many of our deps would have to be further updated and would be a massive amount of effort, I don't think being on the latest will help us, and this is already a major improvement being on 3.11

**Comment by NickM-27** [comment]
I'd highly suggest creating a discussion before putting too much time into it, I already looked in to various python versions and there will be a lot more work & various problems to solve regarding the different hardware platforms if we move forward to a newer version. IMO we don't want to have too many moving parts for 0.16 and this is already a big step forward.

**Comment by felipecrs** [comment]
Alright, understood. Great to see Python 3.11 arriving!
