### ISSUE TITLE
Use ONVIF motion events to trigger recording

### ISSUE THREAD

**Issue by tomuta** [blakeblackshear/frigate#4396]
I bought a cheap TP-Link Tapo C110 WiFi camera and set it up for motion detection and rtsp/onvif streaming. It works great with Frigate, except that it records 24/7. Unlike my Eufy Wifi camera, which basically returns "404 Not Found" while not motion is detected. Because it is a WiFi camera with built-in motion detection I would like to avoid streaming 24/7 as to not saturate my WiFi constantly.

Looking into how this can be done it appears that ONVIF has an event service that should relay motion events, which then could be used to start or stop the RTSP stream.

I am pretty new to Frigate and NVR in general, so maybe I'm just missing something, but I could not find anything about ONVIF support. I think it would be a very useful feature to have.

**Comment by NickM-27** [comment]
I'd recommend reading https://github.com/blakeblackshear/frigate/issues/3485 which explains why this isn't feasible for frigates motion detection

**Comment by NickM-27** [comment]
> Unlike my Eufy Wifi camera, which basically returns "404 Not Found" while not motion is detected. Because it is a WiFi camera with built-in motion detection I would like to avoid streaming 24/7 as to not saturate my WiFi constantly.
>
> Looking into how this can be done it appears that ONVIF has an event service that should relay motion events, which then could be used to start or stop the RTSP stream.

It's also worth noting that there is a decent delay in starting a stream and getting detection going (frigate takes an average of the first 30 seconds to establish a motion baseline). Frigate is meant to work with cameras that stream 24/7.

I'd also suggest you may be overestimating the WiFi load of having a camera streaming 24/7, especially a 1080p camera.

**Comment by tomuta** [comment]
Yes I got this idea that Frigate works best with 24/7 streaming cameras. For cameras with Ethernet this makes perfect sense. And yes, I am ware of the ~5 second delay with my Eufy Wifi camera. It's not ideal but sufficient for my use case.

I read through #3485 and I'm not sure i understand the problem. If I understand things correctly it seems to relate mostly to object/person detection and the draw backs of having this done in the camera itself. Which does make sense, as it wouldn't be configurable through Frigate in most cases.

But in my setup I don't actually want to do object/person detection. I just want to leverage the built-in motion detection in my Wifi cameras, and only record (without any detailed detection) while these cameras detect motion. The Wifi load for 1 camera isn't really a big deal, but I am looking at potentially up to 7. I'm not how that will scale, unfortunately they only support 2.4ghz. I can of course set up a separate AP on a different channel (which I probably will do anyway).

What I really have in mind here is maybe a wrapper process around ffmpeg. Basically some process that you hand an onvif url, and then it listens to motion events and if it gets a "motion detected" event through onvif then it would spawn ffmpeg with the options provided, and when it receives a "no more motion detected" event then it would send a SIGTERM to ffmpeg. So, essentially emulating (sort of) the behavior that my Eufy camera does. I'm not sure if these events are standardized or not, so maybe there'd have to be some custom options. I hope this makes sense?

**Comment by NickM-27** [comment]
> But in my setup I don't actually want to do object/person detection. I just want to leverage the built-in motion detection in my Wifi cameras, and only record (without any detailed detection) while these cameras detect motion.

Thanks, that does help clarify on the use case.

To be clear I only speak for myself, but my personal opinion is that this doesn't really align with the goals of frigate. It's using frigate as a basic recorder (not even using frigates smart recording based on motion / object detection). There are likely much more lightweight solutions which can enable this. 

> What I really have in mind here is maybe a wrapper process around ffmpeg. Basically some process that you hand an onvif url, and then it listens to motion events and if it gets a "motion detected" event through onvif then it would spawn ffmpeg with the options provided, and when it receives a "no more motion detected" event then it would send a SIGTERM to ffmpeg.

There is https://github.com/blakeblackshear/frigate/issues/4325 which would more easily enable the use case you're suggesting, but I personally don't think Frigate will support the battery powered camera use case directly.

**Comment by tomuta** [comment]
Well, I do plan on adding PoE cameras as well, which would be streaming 24/7, and for those I do want object/people detection. The Wifi cameras are for rarely used areas that I also don't really want to go pull cable to. Would be nice to do both. Anyway, Frigate just seemed very appealing and exactly what I was looking for, also considering the nice integration with HASS. And it worked reasonably well with my Eufy camera, but then I bought the Tapo C110 and I just can't get it to work in a similar fashion.

**Comment by hawkeye217** [comment]
> But the smart ones have good object recognition and tracking built in. I don't want frigate to waste resources on these. ONVIF event support would be welcome here.

See the first reply in this thread that points to https://github.com/blakeblackshear/frigate/issues/3485 which explains why this isn't feasible for frigate's object detection pipeline.

The recommendation would be to have some kind of external ONVIF trigger with a script or Home Assistant to create manual events using frigate's HTTP API.

**Comment by hischampion** [comment]
What API call would we use to do this? Can we call create event with no duration and then call end event with an end_time of now?

Also if we call the APIs, do we have to have recording setup 24/7 or trigger recording before creating the event?

**Comment by hawkeye217** [comment]
> What API call would we use to do this? Can we call create event with no duration and then call end event with an end_time of now?

https://docs.frigate.video/integrations/api/create-event-events-camera-name-label-create-post

https://docs.frigate.video/integrations/api/end-event-events-event-id-end-put

> 
> Also if we call the APIs, do we have to have recording setup 24/7 or trigger recording before creating the event?

No, but you'll likely want at least `motion` as your `retain` policy.
