### ISSUE TITLE
RAM usage keeps increasing

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#440]
HI Blake, I have a feeling that my RAM usage keeps increasing over time. Not sure if this is related to frigate though. My Raspberry Pi 4 with 2GB has reached 1.4GB RAM (78%). I added a 3rd camera. Could this be the reason? Have you noticed this on your side?

**Comment by blakeblackshear** [comment]
Can you track down which process is using more ram? I haven't seen this.

**Comment by asemev** [comment]
It looks like its the Home Assistant thats using excessive RAM, not frigate.... Is that even normal?

![image](https://user-images.githubusercontent.com/30929896/103176577-2985b700-4873-11eb-9e7f-971c2cd3b676.png)
