### ISSUE TITLE
Support streaming camera to homekit

### ISSUE THREAD

**Issue by megapearl** [blakeblackshear/frigate#4404]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to stream my camera's to homekit using Homekit Secure Video. 

**Describe the solution you'd like**
Support for Homekit Secure Video.

**Describe alternatives you've considered**
With Homebridge or Scrypted this is possible, but they lack the ability to record to local storage.

**Additional context**
None.

**Comment by NickM-27** [comment]
We are integrating https://github.com/AlexxIT/go2rtc which supports homekit secure video though actual support for HKSV likely won't be in 0.12 officially, it might still be usable.

**Comment by megapearl** [comment]
I meant the other way around, I want to stream my regular (rtsp) non-homekit secure video camera's to homekit via homekit secure video, like homebridge and scrypted do.

**Comment by NickM-27** [comment]
Oh, no I don't believe so, should just use home assistant or homebridge or whichever to do that. Frigate will support RTSP restream in the next release

**Comment by AlexxIT** [comment]
Streaming to HomeKit from go2rtc in plans. I have working prototypes. Probably not this year.

**Comment by jbishop129** [comment]
> Streaming to HomeKit from go2rtc in plans. I have working prototypes. Probably not this year.

Any place we can track progress on this? My Frigate cameras are accessible in HomeKit, but I just get still-frames, not getting the actual video stream. If this is expected I’ll just be patient and wait. If not expected let me know, I’ll share my config.yml

**Comment by NickM-27** [comment]
This is now supported https://github.com/AlexxIT/go2rtc#module-homekit

**Comment by AlexxIT** [comment]
But in Frigate, there can be difficulties. It is important to have a network host. I don't know if forwarding ports will be enought.
