### ISSUE TITLE
[Support]: How to get last image from Frigate (Home assistant ) include token ?

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#4409]
### Describe the problem you are having

Hey
I trying to write some automation on HA and have a problem retrieving the last image from some camera
I am aware of the entity "camera.entrance_person" but do not have any idea what to do with the token

for example : 

: /api/camera_proxy/camera.entrance_person?token=fe5aa21aafc68a6981773f941357524587e8ccb0c68f2c26b8f8564af6d38f5f

How we can solve it ?

### Version

latest version 

### Frigate config file

```yaml
a
```

### Relevant log output

```shell
a
```

### FFprobe output from your camera

```shell
a
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest

**Comment by NickM-27** [comment]
Please describe more of what you're trying to accomplish. Are you needing to use the image internally or while you're not home too? Is it specifically the latest person you want or latest snapshot in general? The integration handles the token so no need to worry about that
