### ISSUE TITLE
where is the config.yml ?

### ISSUE THREAD

**Issue by wwdok** [blakeblackshear/frigate#441]
Hi, where is the config.yml ? I want to use it to learn yaml.

**Comment by Trashmee** [comment]
Sure that this is an actual frigate issue?

The yaml is documented in the readme  - I'd look at beta4 documentation:
https://github.com/blakeblackshear/frigate/tree/beta4

**Comment by wwdok** [comment]
Hahaha, it is more likely a yaml issue, i just happened to remember that this repo used yaml for configuration, so i came here to have a look.
Then i saw [this line of code](https://github.com/blakeblackshear/frigate/blob/64b63142b130a2942b318ea4f65de420ebb12332/detect_objects.py#L29), so i guess `/config/config.yml` is a existing file in this repo, but i didn't see it, so i asked this question. 
You said i need to generate my specific config.yaml ? I first time heard such operation ...

**Comment by wwdok** [comment]
I think i should go to learn the home assistant first, thanks ~
