### ISSUE TITLE
[Support]:  upgraded to 0.11.1, all cameras notify as doorbells in HomeKit

### ISSUE THREAD

**Issue by blysik** [blakeblackshear/frigate#4416]
### Describe the problem you are having

After upgrading to 0.11.1, all my hikvision cameras send doorbell notifications to HomeKit.  This is a new behavior after upgrading.

I found this closed issue [#3933](https://github.com/blakeblackshear/frigate/issues/3933), which is the same issue.  I argue that it shouldn't have been closed.  It's a new behavior.  Is there a support channel for the Frigate Integration where this questions can be asked?  If not, lets sort out this new behavior here.

Very simply, I would like to stop HomeKit/Home.app from sending "doorbell alerts" from vanilla cameras.  How can I accomplish this?  Thanks.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
Like the other issue said, this is not a frigate issue. If you'd like, you can open an issue on the frigate integration https://github.com/blakeblackshear/frigate-hass-integration but this is not the right place.

**Comment by blysik** [comment]
Thanks.  I found that repo and opened an issue: https://github.com/blakeblackshear/frigate-hass-integration/issues/368
