### ISSUE TITLE
[Support]: Events doesn't always seem to update

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#4421]
### Describe the problem you are having

For some reason the global events list doesn't reflect (immediately) the events on the individual camera. Not sure why.
After a few minutes it does.

Using chrome, is this a caching issue perhaps ? 

### Version

latest

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

No, just curious about this behaviour. I have the latest frigate, inference is 10-11 or so, and everything works well (other then the previously described issue).

**Comment by NickM-27** [comment]
Frigate 0.11 added support for this, it's always been up to date for me as the event rolls in. Might want to see if there's anything in the browser log

**Comment by atv2016** [comment]
Yeah, it's on and off, probably a Safari issue. If i do a refresh it's there. I guess it can be closed.
