### ISSUE TITLE
MQTT Reference for all topics Frigate subscribes and publishes

### ISSUE THREAD

**Issue by SergioRAgostinho** [blakeblackshear/frigate#4426]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to have a page in the documentation that has a listing of all MQTT topics frigate publishes and subscribes to.  Currently, I need to crawl through the source code to find calls to the MQTT client to figure out what sort of topics are being published.

**Describe the solution you'd like**
Having a reference page listing of all MQTT topics frigate publishes and subscribes to. 

**Describe alternatives you've considered**
There might be 3rd party tools for grabbing information directly from the broker that I'm just not familiar with. 

**Additional context**
n.a.

**Comment by NickM-27** [comment]
This is already in the docs: https://docs.frigate.video/integrations/mqtt
