### ISSUE TITLE
[Config Support]: Mask live and recorded video

### ISSUE THREAD

**Issue by aervig** [blakeblackshear/frigate#4429]
### Describe the problem you are having

I need to mask both live and recorded video because of local regulations in my country. I'm only allowed to see my own property and need to black out everything else. I have not found any way to do that on live view.

### Version

0.11

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/discussions/2866

This is usually something that the camera itself supports.

Otherwise you can use ffmpeg but this would use considerable CPU resources to do so.
