### ISSUE TITLE
Fire detection FR

### ISSUE THREAD

**Issue by ukrolelo** [blakeblackshear/frigate#4437]
I want to be able to detect fire so that I can be notified

**Comment by spacebares** [comment]
There is no "fire" detection model for frigate, and if there was, you would want 100% reliability. Only a fire alarm can provide this.
A smart fire alarm paired with its app or home-assistant is the most reliable way for being notified of fire.

Unsure about outdoor solutions.

**Comment by ukrolelo** [comment]
> There is no "fire" detection model for frigate, and if there was, you would want 100% reliability. Only a fire alarm can provide this. A smart fire alarm paired with its app or home-assistant is the most reliable way for being notified of fire.
> 
> Unsure about outdoor solutions.

Obviously you are right. But if one don't want 100% reliability :)
