### ISSUE TITLE
Add ability to filter for only favorited events

### ISSUE THREAD

**Issue by Armadillo1** [blakeblackshear/frigate#4450]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to save certain clips so they would be kept for longer than 'retain' setting.
I recently had a few events where a suspicious person was spotted in the footage and I'd like to keep such videos until I remove them manually

**Describe the solution you'd like**
1. 'Save' (or 'Archive') button  in 'Events' tab (next to Download/Send to Frigate+).
2. 'Saved videos' tab next to Cameras/Birdseye/Events/Debug for selected videos.

**Describe alternatives you've considered**
Download the file manually and store, however that's tedious.

**Additional context**
None.

Thanks

**Comment by NickM-27** [comment]
This is already supported in 0.11, just press the star on the thumbnail. 

<img width="1249" alt="Screenshot 2022-11-20 at 11 43 38 AM" src="https://user-images.githubusercontent.com/14866235/202920066-216778fc-0fca-41dd-855f-e164cf947229.png">

**Comment by Armadillo1** [comment]
Ah, great. Thanks for pointing this out. Is there a way to access all the 'Starred' clips ?

Thanks

**Comment by NickM-27** [comment]
There's currently no way to filter them, they'll naturally accumulate at the bottom of the events list

**Comment by Armadillo1** [comment]
Thanks. Would be nice to have an option to 'Filter Starred'.
