### ISSUE TITLE
Track faces to improve recognition

### ISSUE THREAD

**Issue by atv2016** [blakeblackshear/frigate#4469]
**Describe what you are trying to accomplish and why in non technical terms**
Track faces it received from double take (might be better to implement this on double take side) so it does not need to keep matching faces and potentially choose a lower match at some point. Once a face with good match and percentage is received, track it across a camera (or cameras e.g. a recognised face can't exist on more then one camera, and if it does, flag it for potential spoofing) 

This will:
-Improve recognition
-Lower cpu and overhead
-Implement spoofing
-If the tracked face goes to a place with a small recognition box, it won't have to rely on small images but can use the previously recognised face instead.

**Describe the solution you'd like**
Track faces or the object attached to it to lower cpu and improve recognition.
**Describe alternatives you've considered**
Doubletake, to which i will also suggest this.
**Additional context**

**Comment by NickM-27** [comment]
There's not really a good way to track a face without running recognition to know if it is the same face (or a face at all). If using [the upcoming frigate+ models which have face detection](https://frigate.video/plus/) (not recognition) it would at least be able to track the face but there is still not a good way to know if the face between two different frames is the same or a different one.

**Comment by bertybuttface** [comment]
@NickM-27 Something like Nvidia Deepstream uses a tracker to get round that problem if I understand correctly: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvtracker.html

**Comment by atv2016** [comment]
The point is of course that once you recognise the face, you use an object tracker to track and not do face recognition anymore and rely on the object tracker. 10 years ago when I checked there were already very good ones out there. Of course the object tracker might fail at some point that will have to be mitigated but I would say that still would save so much in bandwidth (memory as well as cpu), false positives, speed, spoofing etc that it seems a logical way forward rather then recognising every frame.
________________________________
