### ISSUE TITLE
Leverage Intel's new oneVPL for hardware acceleration 

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4481]
Just opening this issue for future reference and tracking.

It seems that support to ffmpeg has been added already but requires a special flag during build, and the output binary isn't compatible with current hw acceleration flags for Intel.

https://www.phoronix.com/news/FFmpeg-Intel-oneVPL

In the best case scenario this can improve performance, in the worse case it will at least generalize the flags between the different CPU generations. At least that's what I understood.

**Comment by dspears0809** [comment]
Any plans to implement ffmpeg with OneVPL soon?

**Comment by felipecrs** [comment]
Here is another reference: https://www.intel.com/content/www/us/en/developer/articles/technical/onevpl-in-ffmpeg-for-great-streaming-on-intel-gpus.html#gs.2hharv
