### ISSUE TITLE
Tripwire -

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#4483]
**Describe what you are trying to accomplish and why in non technical terms**
if user could define a simple tripwire with the ability to identify to cross direction
it would be much easier to trigger/define "motion" and also reduce the complexity of defining multiple religion/masks.

I.e - in some case the doorbell camera have a wide angel which capture many irrelavnt things,
but from the otherhad , it require to define almost the entire frame size as we do want to idetify face coming closer to the camera.

see picture:
![image](https://user-images.githubusercontent.com/9049952/203437265-8b1320b1-6711-45e4-8ce3-397d184c4455.png)

I'd frigate to let me know where:
who is coming IN front of camera
when car is parking/getting out of parking 

By existing frigate functionality :
1.The problem (i think is clear)- both regions cover each other ,
how can we(easily) define rules in frigate to support both cases ?
2.it is very difficult to reduce repetitive events for the parking car in my case 

building automation can be quite challenging .

**Describe the solution you'd like**
1.User draw lines/tripwires which later can be added to yaml (same as done for masking)
 2.Frigate will allow snapshot/recording if line crossed (probably can add an arrow to define direction aswell).
3.Frigate will include the json event as "tripewire_cross: true " + "crossing_direct: LR/RL"
so user can implement automation more easily

**Describe alternatives you've considered**
adopt IVS concept as Dahua is using for intrusion

**Comment by NickM-27** [comment]
I believe this is a duplicate of #93 feel free to leave comments there to express any additional context. 

Also In the picture you're showing I think a zone would work just fine, do be aware that an objects presence in a zone is based on the bottom center of its bounding box.
