### ISSUE TITLE
Feature: Object recognition from main stream, motion from sub-stream

### ISSUE THREAD

**Issue by elektrinis** [blakeblackshear/frigate#4509]
**Describe what you are trying to accomplish and why in non technical terms**
I want frigate to be able to use main stream for object recognition, as sub-streams are often too low resolution and detecting smaller objects like cats and dogs is not possible, even deers passed by without detection.

**Describe the solution you'd like**
Use substream to detect motion as before.
Then take main stream frame, crop to the same region and send that to process object detection.
Yes i know it's not that easy to take a frame, you need key frame etc, and this is CPU intensive. But this is only when movement is detected and I'd rather have a working system than lower CPU load.

**Describe alternatives you've considered**
Could not think of any. Certainly not going to replace all of cameras.

**Comment by NickM-27** [comment]
This would be decoding both streams which is a lot of work, the decoding of different resolutions can have differing delay introduced. The streams from the cameras themselves are also often somewhat out of sync.

This is of course why the docs recommend cameras with configurable sub streams. Completely understandable that replacing cameras is not doable. 

In this case it will of course use more cpu, but arguably less cpu than decoding both streams and then downsizing parts of the 4K stream for object detection. use the high res stream and set the resolution in `detect -> width / height` to downsize it to 1080p.

**Comment by PrplHaz4** [comment]
> This would be decoding both streams which is a lot of work, the decoding of different resolutions can have differing delay introduced. The streams from the cameras themselves are also often somewhat out of sync.
> 
> This is of course why the docs recommend cameras with configurable sub streams. Completely understandable that replacing cameras is not doable.
> 
> In this case it will of course use more cpu, but arguably less cpu than decoding both streams and then downsizing parts of the 4K stream for object detection. use the high res stream and set the resolution in `detect -> width / height` to downsize it to 1080p.

Would this approach greatly benefit from gpu acceleration?  I have started to see limitations with tiny detect resolutions, but also also don't want to completely lose 4k recording...

**Comment by NickM-27** [comment]
> Would this approach greatly benefit from gpu acceleration? I have started to see limitations with tiny detect resolutions, but also also don't want to completely lose 4k recording...

GPU acceleration would help the CPU usage side but not the other issues I raised. But the thing is the solution I suggested will have no affect on the recording resolution. You can set the detect resolution to downscale the detect stream without affecting the record stream at all

**Comment by elektrinis** [comment]
So I have just tested it.
Recording at 4K
Detecting at 1080p (exactly 1/2 res)

Previously, with 8 cameras, my CPU load was 20%.
Now, with 4 cameras it's 90%
Other 4 cameras crashed.

So this is not viable.

**Comment by NickM-27** [comment]
Are you using hardware acceleration to decode the 4K stream? You don't have hardware acceleration in your config

**Comment by NickM-27** [comment]
Hwaccel args are here: https://docs.frigate.video/configuration/hardware_acceleration

**Comment by elektrinis** [comment]
> What cpu do you have? Hwaccel args are here: https://docs.frigate.video/configuration/hardware_acceleration

My CPU is Intel J4105 and I had the proposed args set, but removed them as it seemed to actually use more CPU than without the args (35% vs. 24%).
I also have added `LIBVA_DRIVER_NAME=i965` as suggested for J4000 series. Without this, and with accel args set, I get 60% CPU load.

I have no re-added the args and tried again with 4K main stream and 1080p down-scaled detection.
It's better, as all cameras kinda work. But I still hit 100% CPU and see occasional artefacts on random cameras, like this:
![Screenshot 2022-11-26 160603](https://user-images.githubusercontent.com/15337792/204092932-2bc4765d-7f1a-467d-97a8-ef011fc6d226.jpg)

**Comment by NickM-27** [comment]
That's good to know that it is working somewhat better with hardware acceleration. Maybe there's a good combination of some cameras running that way and others running on the sub stream.

In any case, I don't speak for the project and I'll be happy to hear other's thoughts, but I (personally) believe that the other issues I mentioned mean this approach is not feasible.

**Comment by blakeblackshear** [comment]
Have you tried running detect on the full 4K stream?

**Comment by elektrinis** [comment]
> Have you tried running detect on the full 4K stream?

OK, this is weird.
I have removed 5 cameras for this test, as my CPU can't handle them. So I tested it with 3 cameras at 4K.

With detection set to 1080p I'm getting an average of 48% CPU load.
With resizing commented-out I get an average of 46%.

So it seems the CPU has less work to do if it's not resizing?
I wonder what exactly is hardware-accelerated.

**Comment by NickM-27** [comment]
> I wonder what exactly is hardware-accelerated.

Only decoding of the stream is accelerated, not the resizing. Resizing is done on the CPU

**Comment by blakeblackshear** [comment]
I know I have seen some examples of args to resize with the GPU in other issues.

**Comment by blakeblackshear** [comment]
> With resizing commented-out I get an average of 46%.

Note that commenting out the detect resolution will revert to the default of 720p. To get a true sense of CPU without any resizing, you need to set the detect resolution to the camera resolution.

**Comment by elektrinis** [comment]
> Note that commenting out the detect resolution will revert to the default of 720p.

Oh, I assumed it will use the stream without resizing it.
For now I decided to use 4K detection only on two cameras, and others can be on substream for now. But it turns out I can't have that, since all streams will be up-scaled or down-scaled to either default or what's set by user.

**Comment by NickM-27** [comment]
> For now I decided to use 4K detection only on two cameras, and others can be on substream for now. But it turns out I can't have that, since all streams will be up-scaled or down-scaled to either default or what's set by user.

You can have that, just set the detect resolution at the camera level instead of the global level

**Comment by elektrinis** [comment]
Tested again with resizing to 1080p vs. no resizing.
resized 37%
original 52%

So yes, there is a difference.

I have searched around for hardware scaling, but stuff I found is above me.
