### ISSUE TITLE
[Support]: Frigate suddenly having lots of errors

### ISSUE THREAD

**Issue by k2xl** [blakeblackshear/frigate#4522]
### Describe the problem you are having

Frigate has been working fine for past year or so then suddenly a couple of a days ago it won't start up.
Here's a screenshot of dev console from direct home-assistant:5000 (port i have frigate running on) ... Looks like a crazy amount of requests to api/config are failing
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/965260/204104794-4ef24c31-ceff-4b5a-b646-d87a610eed47.png">

### Version

3.0.0 (I believe, can't access any pages on web ui)

### Frigate config file

```yaml
Can't obtain
```

### Relevant log output

```shell
Seeing this in the logs:

2022-11-26 13:56:40.006 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')
```
```


### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
502 bad gateway
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Reolink

### Any other information that may be helpful

I do'nt recall how i installed but technically i'm on ubuntu (Debian based)

**Comment by NickM-27** [comment]
We need docker logs to be able to help at all. `docker logs frigate`

**Comment by austindetzel** [comment]
I am having the same issue, here are the docker logs

`[2022-12-03 20:37:19] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
Starting migrations
[2022-12-03 20:37:20] peewee_migrate                 INFO    : Starting migrations
Migrate "011_update_indexes"
[2022-12-03 20:37:21] peewee_migrate                 INFO    : Migrate "011_update_indexes"
sql ('CREATE INDEX "event_start_time_end_time" ON "event" ("start_time" DESC, "end_time" DESC)',)
[2022-12-03 20:37:21] peewee_migrate                 INFO    : sql ('CREATE INDEX "event_start_time_end_time" ON "event" ("start_time" DESC, "end_time" DESC)',)
sql ('DROP INDEX recordings_start_time_end_time',)
[2022-12-03 20:37:21] peewee_migrate                 INFO    : sql ('DROP INDEX recordings_start_time_end_time',)
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

**Comment by NickM-27** [comment]
@austindetzel frigate isn't staying alive. Recommend making your own issue.
