### ISSUE TITLE
[Support]: dev support following new changes.. vscode user and build_web target

### ISSUE THREAD

**Issue by CJP-work-acct** [blakeblackshear/frigate#4530]
### Describe the problem you are having

Is there any detailed CHANGES file for developers following along from current? Lots of stuff is changing, that's great, but it feels like between the commit log and the Contributions page I'm missing out on something.

After the recent big devcontainers cleanup my local vscode build broke... the logs showed that devcontainers was now expecting a user 'vscode' via the remoteUser directive in .devcontainer/devcontainer.json

I added this speculative diff to Dockerfile to add that user in the devcontainer section and it seems to have worked:

```
$ git diff
diff --git a/Dockerfile b/Dockerfile
index 2589585..ce38478 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -122,6 +122,8 @@ ENTRYPOINT ["/init"]
 # Frigate deps with Node.js and NPM for devcontainer
 FROM deps AS devcontainer

+RUN useradd -ms /bin/bash vscode
+
 # Install Node 16
 RUN apt-get update \
     && apt-get install wget -y \

```

After I forced delete on the old frigate-devcontainer image and let VSCode rebuld it seems to have worked. I don't feel great about that though... maybe I just missed some step.

So right now my dev frigate and decontainer is working but I'm having trouble building new "production" images with the steps I used before (make version; make build_web; make local)

Right now make build_web is failing for me early on...

```
ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to create LLB definition: target stage web-dist could not be found
```

I'm not sure if this is just something weird w/ my setup or there was a change. It _looks_ like maybe build_web has been obviated and now local takes care of it via the interim stage web-build?

But it would be great if I had the docs somewhere for that... I'm sure I'm just missing a channel.

### Version

DEBUG 0.12.0-5619BA1

### Frigate config file

```yaml
mqtt:
  host: mqtt

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/yard.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
    detect:
      height: 1080
      width: 1920
      fps: 5
    objects:
      track:
        - person
        - dog
```

### Relevant log output

```shell
$ make build_web
docker buildx build --target web-dist --output web/dist .
[+] Building 1.0s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 32B                                                                     0.0s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 34B                                                                        0.0s
 => resolve image config for docker.io/docker/dockerfile:1.2                                            0.7s
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd92b9591  0.0s
ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to create LLB definition: target stage web-dist could not be found
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

AXIS P3245-LV Network Camera

### Any other information that may be helpful

I'm running "production" frigate on a Ubuntu box w/ hardware coral but this question is about my dev setup on a MacBook using MacOS docker and MacOS VS code.

**Comment by blakeblackshear** [comment]
The contributing docs will need to be updated. You should just be able to checkout the repo and open in devcontainer now. Everything should be taken care of automatically.

`make build_web` isn't working at the moment for me either.

**Comment by CJP-work-acct** [comment]
Well after writing all this down I went back and nuked the frigate-devcontainer and built from clean and the missing user error didn't happen so it must have been a lingering container I had somehow. I can't quite figure it out but I'm wrong about that so I will close this.
