### ISSUE TITLE
Make viewing and downloading recordings and events easier

### ISSUE THREAD

**Issue by bbartlomiej** [blakeblackshear/frigate#4549]
When we have events with object detection it is easy to download the whole clip and see when the event happened. However the downloaded video file has a pretty random name - you can't easily figure out when it happened. Also when you have events with object detection and recordings with motion or all you can't easily view and download the recordings. When you go to a camera and click on Recordings you can pick hours where motion happened (or all hours if you have "all" configured) and you can view it in the browser but you can not download the whole clip with recorded motion neither you have any information at what exact time it happened. It would be nice if Recordings section looked similar to Events section where you both get the info about the date and time and you can easily download the recording.

**Comment by NickM-27** [comment]
I believe this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2369 and https://github.com/blakeblackshear/frigate/issues/2525

**Comment by bbartlomiej** [comment]
It doesn't seem to be a duplicate. My issue here is a web gui feature to allow listing motion recordings similarly to events recordings (with objects detected) on a recording list and then a way to easily download them. Similarly to what we already have for events. #2525 is different, #2369 is also different - it focues on downloading a timespan of recordings. I'd like to see all motion-detected recordings to be listed like object-detected events with time/date label and easy download.

**Comment by bbartlomiej** [comment]
Yeah, I think I have it setup this way you describe it:
`record:
      enabled: True
      retain:
        days: 30
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects`
And it serves its purpose however I'm asking about modifying the recordings gui - to make it easier to know when motion was detected or simply when the recording exactly happened (not snapped to the closest hour) and a nice download button like in events list. Is this doable or not in line how Frigate is designed?

**Comment by NickM-27** [comment]
> however I'm asking about modifying the recordings gui - to make it easier to know when motion was detected

That's exactly what #2525 is requesting

> and a nice download button like in events list

That's what #2639 is asking for. I wouldn't put much emphasis on the "custom recording lengths" part as in general the request is to add the ability to download long term recordings from the recordings page. 

Both of these requests are pinned and going to be implemented at some point.
