### ISSUE TITLE
Split storage capabilities - internal SSD then archive to HDD / NAS

### ISSUE THREAD

**Issue by madmic1314** [blakeblackshear/frigate#4557]
**Describe what you are trying to accomplish and why in non technical terms**
Use a high speed location for recording storage, then at a schedulled time move to another storage location - likely slower / NAS stoarge that's not online 24/7.

**Describe the solution you'd like**
My server has an internal 240Gb SSD, ideally Frigate would record to this and then at a schedulled time move these files to a harddisk / external NAS for longer term storage until the expirey limit in the config.

Perhaps called "Archiving"?

**Describe alternatives you've considered**
None at the moment, as the recordings database needs to be updated.

**Additional context**
N/A.

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3673

**Comment by madmic1314** [comment]
Apologies - didn't spot this. Will close
