### ISSUE TITLE
Help: how to stream from a local raspberry pi camera?

### ISSUE THREAD

**Issue by angadsingh** [blakeblackshear/frigate#457]
I cannot find information about this anywhere. Everywhere docs and other folks only mention rtsp streams. I'm trying to get frigate running on a raspberry pi 4 2B with a locally attached raspberry pi v2.1 camera. The raspivid | vlc route to create an rtsp stream is too cpu intensive and causes delays. Why can't frigate read from a local pi camera directly?

**Comment by blakeblackshear** [comment]
Frigate can read anything that ffmpeg can read. If you can find the ffmpeg command to create an mp4 file from the camera using ffmpeg, I can show you how to set the parameters.

**Comment by angadsingh** [comment]
well the solution out there is to use raspivid piped to ffmpeg, but that way you can send the ffmpeg stream to a an rtmp destination like so:
`raspivid -t 0 -w 1280 -h 720 -fps 25 -g 75 -fl -o - | ffmpeg -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -i pipe:0 -c:v copy -c:a aac -strict experimental -f flv -f flv rtmp://ip:port/app/stream`

frigate's configuration requires specifying the input parameter. its not possible to pipe raspivid to frigate's ffmpeg the way the configuration is setup. thoughts?

**Comment by angadsingh** [comment]
one workaround could be to use [linux named pipes](https://www.linuxjournal.com/content/using-named-pipes-fifos-bash)

**Comment by mattheys** [comment]
Can't you just use this to get the Pi Camera, sorry not tested it. `ffmpeg -f video4linux2 -input_format h264 -video_size 1280x720 -framerate 15 -i /dev/video0 ` I guess you would need to pass in the /dev/video0 into docker as well.
