### ISSUE TITLE
[Support]: Frigate detecting person in masked off area

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#4578]
### Describe the problem you are having

I have an area masked off, and frigate is showing an event and person in that area

![image](https://user-images.githubusercontent.com/7737834/205367263-3f888bf6-14cf-42fe-b23c-33e1744e8183.png)
![image](https://user-images.githubusercontent.com/7737834/205367278-3c20a905-4407-4bb2-80bb-1cfebd182c7a.png)

### Version

0.11.1

### Frigate config file

```yaml
none
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

amcrest

**Comment by NickM-27** [comment]
Like the docs say, motion masks do not stop objects from being detected. You'll need to use an object mask or a size filter

**Comment by rayzorben** [comment]
> For example, you want to mask out your timestamp, the sky, rooftops, etc. Keep in mind that this mask only prevents motion from being detected and does not prevent objects from being detected if object detection was started due to motion in unmasked areas. 

I'm just confused because I don't see how motion could have been detected outside of the masks - documentation implies if the motion starts in the masked area, then object detection would not be done.

**Comment by NickM-27** [comment]
Yes, but motion starts outside the masked area and a region is sent for detection. Especially with the smaller detect resolution like your camera appears to have, the region will be quite large relative to the camera so an object can definitely be detected.
