### ISSUE TITLE
No frame around detected objects in live mjpg feed

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#458]
HI guys, i re-installed my frigate integration. everything works, except there are no live frames around detected persons in the live mjpg feed. Any idea how i can turn this on?

**Comment by blakeblackshear** [comment]
There is a query string parameter to enable each overlay you want in the mjpeg feed. See the Readme for that endpoint.

**Comment by asemev** [comment]
Thank you and happy new year!

**Comment by asemev** [comment]
...?bbox=1 :)

**Comment by asemev** [comment]
Is it possible to overlay multiple endpoints in the same url?

**Comment by asemev** [comment]
& sign.... Found it.
