### ISSUE TITLE
Region and Mask information

### ISSUE THREAD

**Issue by DevelopIdeas** [blakeblackshear/frigate#46]
Maybe a bit of a newb question regarding opencv and tensorflow but what is the purpose of the back-mask.bmp and is there a tool people are using to plan/make the region sizes and coordinates up?

**Comment by blakeblackshear** [comment]
It hasn't made it into the README, but here is an explanation: https://github.com/blakeblackshear/frigate/issues/30#issuecomment-490718844

**Comment by DevelopIdeas** [comment]
@blakeblackshear thanks, that makes perfect sense.
What tool would you recommend for plotting the video regions (x, y and size)?

**Comment by blakeblackshear** [comment]
Any image editor should work fine. I typically just make a rough guess and then use the endpoint in frigate to check the position.

**Comment by scstraus** [comment]
I just take a full-size picture or feed of the camera and a same size bmp of the map in ms paint zoomed to 100% and alt tab between the two until I masked it right
