### ISSUE TITLE
[Camera Support]: Is it possible to access a camera stream available in Apple's Homekit?

### ISSUE THREAD

**Issue by attzonko** [blakeblackshear/frigate#4605]
### Describe the problem you are having

I am trying to get my Aqara Hub G3 Camera stream into Frigate. There doesn't seem to be a direct rtsp URL, but I was able to add the camera to Homkit. Is it possible for Frigate to get the stream from Homekit?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"detection_fps":4.1,"detectors":{"coral":{"detection_start":0.0,"inference_speed":25.19,"pid":231}},"driveway":{"camera_fps":7.1,"capture_pid":242,"detection_fps":3.0,"pid":238,"process_fps":7.1,"skipped_fps":0.0},"garage":{"camera_fps":6.7,"capture_pid":247,"detection_fps":1.1,"pid":240,"process_fps":6.7,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":265.6,"mount_type":"tmpfs","total":268.4,"used":2.9},"/media/frigate/clips":{"free":6225052.6,"mount_type":"xfs","total":7999425.2,"used":1774372.5},"/media/frigate/recordings":{"free":6225052.6,"mount_type":"xfs","total":7999425.2,"used":1774372.5},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":28526,"version":"0.11.1-2eada21"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Aqara Hub G3

**Comment by NickM-27** [comment]
No, frigate does not support homekit as a source for ffmpeg.

**Comment by attzonko** [comment]
Thanks for the quick response @NickM-27 do you know of any other way to get the Aqara Hub G3 camera feed into Frigate? Their RTSP stream seems to require authentication, which is not documented anywhere.

**Comment by NickM-27** [comment]
Yes, you can use https://github.com/AlexxIT/go2rtc to connect to the homekit camera and then have frigate read the stream from go2rtc
