### ISSUE TITLE
Same ID for events in multi-camera zone

### ISSUE THREAD

**Issue by neonpak** [blakeblackshear/frigate#461]
**Describe the bug**
First thanks for this wonderful piece of software.

When having multiple cameras covering the same zone it would be very helpful if events occurring in that zone share the same ID across all cameras.

**Version of frigate**
0.8.0 Beta 3

**Comment by HITChris** [comment]
I'm not sure how this would be possible without 'true' AI? E.g., cam 1 detects a cat in zone X, and cam 2 also detects a cat in zone X... but how is frigate to say that the cats detected by each are truly the same single cat?
