### ISSUE TITLE
View multiple camera's records at the same time

### ISSUE THREAD

**Issue by algoz098** [blakeblackshear/frigate#4617]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to view  see select two or more cameras to see the records so that I can compare what is happening in my network

**Describe the solution you'd like**
Would be the same player for the records, so you can define the hour and the player would show, if there's, all the camera fotage at that time

Somewhat like what birdeye does.

**Comment by NickM-27** [comment]
The ability to review recordings for multiple cameras at once has been implemented as part of the new UI, closing, https://github.com/blakeblackshear/frigate/pull/9985
