### ISSUE TITLE
Filter by time range

### ISSUE THREAD

**Issue by Armadillo1** [blakeblackshear/frigate#4618]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to filter recordings by time as am mostly interested in what happens overnight.

**Describe the solution you'd like**
Filter by time. From time x to time y.

**Describe alternatives you've considered**
Scroll and review videos manually.

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/3140 and there is also a draft implementation at https://github.com/blakeblackshear/frigate/pull/3302
