### ISSUE TITLE
Send debug stats to MQTT once a minute

### ISSUE THREAD

**Issue by natm** [blakeblackshear/frigate#462]
To enable easier monitoring of a frigate instance, please send debug stats to an MQTT once a minute.

Ideally the same JSON as is currently available via HTTP at `/debug/stats`, would be sent to an MQTT topic `frigate/debug/stats`.

Interested services could subscribe to this topic, such as HomeAssistant and NodeRED, allowing for metrics to be pushed into InfluxDB / Grafana.

Thanks!

**Comment by blakeblackshear** [comment]
Why not poll the endpoint at whatever interval you want?

**Comment by natm** [comment]
Couple of reasons:

- Multiple frigate instances (possibly without HTTP exposed)
- Having the metrics sent to MQTT would allow for HomeAssistant sensors to be created, very easy to graph per-camera FPS, detection FPS, inference speed etc.

**Comment by blakeblackshear** [comment]
The integration for version 0.8.0 already sets up your sensors from frigate automatically in homeassistant.

**Comment by natm** [comment]
Home Assistant isn't the only use case, confusing that data available via for example REST isn't also accessible via MQTT.

Having stats sent periodically would allow downstream services to just pull this data off the MQTT bus, something which they are subscribed to already.

**Comment by natm** [comment]
Will close this ticket, saw the PR got merged. Thanks @blakeblackshear
