### ISSUE TITLE
[Feature Request] Audio detection

### ISSUE THREAD

**Issue by Dvalin21** [blakeblackshear/frigate#4622]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to add audio detection function for my cameras.

**Describe the solution you'd like**
I have a Fascam indoor camera. Through the app that comes with it I get audio detection. This could be a good function in the event the camera is not or can't be pointed in a specific direction, the audio detection could still alert you of something going on in the room.

**Additional context**

**Comment by NickM-27** [comment]
So we have https://github.com/blakeblackshear/frigate/issues/1869 which is how audio detection will be used. If you want to have your camera's audio detection be put in as an event then that is covered by https://github.com/blakeblackshear/frigate/issues/1063
