### ISSUE TITLE
ffmpeg - KeyError: 'input'

### ISSUE THREAD

**Issue by vincent-d-izo** [blakeblackshear/frigate#463]
hello,
fresh installation of home assistant os on a nuc, with a coral.

i got this issue 

Fontconfig error: Cannot load default config file
On connect called
ffprobe -v panic -show_error -show_streams -of json "rtsp://admin:admin@192.168.1.01:554/h264/ch2/sub/av_stream"
Starting detection process: 27
Attempting to load TPU as usb:0
{'streams': [{'index': 0, 'codec_name': 'h264', 'codec_long_name': 'unknown', 'profile': '66', 'codec_type': 'video', 'codec_time_base': '1/60', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 704, 'height': 480, 'coded_width': 704, 'coded_height': 480, 'closed_captions': 0, 'has_b_frames': 0, 'pix_fmt': 'yuvj420p', 'level': 30, 'color_range': 'pc', 'color_space': 'bt709', 'color_transfer': 'bt709', 'color_primaries': 'bt709', 'chroma_location': 'left', 'field_order': 'progressive', 'refs': 1, 'is_avc': 'false', 'nal_length_size': '0', 'r_frame_rate': '30/1', 'avg_frame_rate': '30/1', 'time_base': '1/90000', 'start_pts': 17970, 'start_time': '0.199667', 'bits_per_raw_sample': '8', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}}, {'index': 1, 'codec_name': 'pcm_mulaw', 'codec_long_name': 'unknown', 'codec_type': 'audio', 'codec_time_base': '1/8000', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'sample_fmt': 's16', 'sample_rate': '8000', 'channels': 1, 'bits_per_sample': 8, 'r_frame_rate': '0/0', 'avg_frame_rate': '0/0', 'time_base': '1/8000', 'start_pts': 0, 'start_time': '0.000000', 'bit_rate': '64000', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0}}]}
Traceback (most recent call last):
  File "detect_objects.py", line 441, in <module>
    main()
  File "detect_objects.py", line 196, in main
    ffmpeg_input = get_ffmpeg_input(ffmpeg['input'])
KeyError: 'input'

my config file :

web_port: 5000
detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
save_clips:
  clips_dir: /media/frigate
mqtt:
  host: 192.168.1.02
  port: 1883
  topic_prefix: frigate
ffmpeg:
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
cameras:
  back:
    ffmpeg:
      input: 'rtsp://admin:admin@192.168.1.01:554/h264/ch2/sub/av_stream'
  objects:
    track:
      - person
      - car
    filters:
      person:
        min_area: 5000
        max_area: 100000
        min_score: 0.5
        threshold: 0.85

any idea what's going on ?

thanks a lot.

**Comment by hawkeye217** [comment]
Check your indentation in the yaml and compare it with the [example config](https://github.com/blakeblackshear/frigate#configuration).

**Comment by vincent-d-izo** [comment]
that was that, the example is so big that i ended to miss an indent.
thanks a lot.
