### ISSUE TITLE
Add timestamp in cameras

### ISSUE THREAD

**Issue by algoz098** [blakeblackshear/frigate#4631]
I want to be able to add timestamp on cameras for those which do not have it

**Describe the solution you'd like**
A global configuration, as a per camera configuration to add the time stamp with DD/MM/YYYY HH:MM:ss or something like that.

Would be nice if we can customize the text somehow, but this would not be a must have, only the timestamp.

**Describe alternatives you've considered**
Just a timestamp per camera.

**Comment by NickM-27** [comment]
this can already be done via ffmpeg, but that requires reencoding the stream which would use considerable CPU / GPU resources: https://superuser.com/questions/1491264/ffmpeg-filter-to-add-timestamp-on-video or https://superuser.com/questions/1020102/adding-a-timestamp-on-frames-captured-using-ffmpeg for examples

See https://github.com/blakeblackshear/frigate/issues/3205#issuecomment-1123087885
