### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by mlause** [blakeblackshear/frigate#4691]
### Describe the problem you are having

I thought upgrading from .10 to .11.1 would be easy. No such luck. I was using the Unraid docker container frigate-nvidia. I used the same settings as follows: 

extra parameter - --runtime=nvidia (adding --gpus=all did nothing)
NVIDIA_VISIBLE_DEVICES
GPU-3e8fa27f-ab98-2bdc-20e8-b9098b3b60aa
NVIDIA_DRIVER_CAPABILITIES
compute,utility,video (also tried all without luck)

The container won't start. I got it keeping the standard configuration with the default Intel/Amd configuration. However I had green screens because my config.yml is setup for Nvidia hardware acceleration. You can see the screenshots below.
<img width="2293" alt="unraid" src="https://user-images.githubusercontent.com/103668347/207261191-c7477cb8-f5cb-4056-b735-a59feb027ab2.png">
<img width="1518" alt="unraid (1)" src="https://user-images.githubusercontent.com/103668347/207261222-4abb5521-b582-48fc-bc02-7c5cb2c95e45.png">
<img width="1328" alt="unraid (2)" src="https://user-images.githubusercontent.com/103668347/207261247-84e46f30-1856-4e13-9c80-84fb49eb8ab8.png">

### Version

.11.1

### Frigate config file

```yaml
not necessary here
```

### Relevant log output

```shell
docker won't start
```

### FFprobe output from your camera

```shell
docker won't start
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

No issues on version .10

**Comment by mlause** [comment]
I figured it out. I changed the driver capabilities to all, and it started to work. Go figure.

**Comment by NickM-27** [comment]
Thanks for updating with the solution 👍
