### ISSUE TITLE
[Camera Support]: Google Coral 5MP Camera Module

### ISSUE THREAD

**Issue by Redsandro** [blakeblackshear/frigate#4711]
### Describe the problem you are having

The official [Google Coral Cam 5MP](https://coral.ai/docs/camera/datasheet/) module attached via MIPI to the [Asus Tinker Edge T](https://tinker-board.asus.com/product/tinker-edge-t.html) is (1) **very high on system resources** compared to other cameras. Specs are nearly identical to the Google [Coral Dev Board](https://coral.ai/products/dev-board#tech-specs) since Asus is Coral's [OEM partner](https://developers.googleblog.com/2022/05/coral-googles-platform-for-edge-ai.html).

Any RTSP camera spawns a `ffmpeg` thread using about 10% of CPU resources as observed through `top`. Google Coral Cam module spawns a `ffmpeg` thread using 250% of CPU resources.

Also, importantly, (2) **the camera is unstable**. Sometimes the camera randomly crashes. Or when you do a config change and a `docker-compose restart`, the camera _often_ crashes. I guess the `ffmpeg` thread cannot end gracefully leaving the camera in a broken (soft-bricked) state. When the camera crashes, it is softbricked until you power cycle the Coral Dev Board.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
cameras:
  coral:
    ffmpeg:
      inputs:
        - path: /dev/video1
          roles:
            - detect
          input_args: -f v4l2 -input_format yuyv422 -video_size 640x480 -framerate 30 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
      output_args:
        detect:
          - -f
          - rawvideo
          - -pix_fmt
          - yuv420p
    detect:
      width: 640
      height: 480
      fps: 1
    rtmp:
      enabled: False

# https://docs.frigate.video/configuration/detectors
detectors:
  coral:
    type: edgetpu
    device: ""
```

### Relevant log output

```shell
watchdog.coral      INFO : No frames received from coral in 20 seconds. Exiting ffmpeg...
watchdog.coral      INFO : Waiting for ffmpeg to exit gracefully...
frigate.video       ERROR: coral: Unable to read frames from ffmpeg process.
frigate.video       ERROR: coral: ffmpeg process is not running. exiting capture thread...
watchdog.coral      ERROR: Ffmpeg process crashed unexpectedly for coral.
watchdog.coral      ERROR: The following ffmpeg logs include the last 100 lines prior to exit.
ffmpeg.coral.detect ERROR: Finishing stream 0:0 without any data written to it.
ffmpeg.coral.detect ERROR: Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
```

### FFprobe output from your camera

```shell
$ ffprobe /dev/video1
[video4linux2,v4l2] Cannot find a proper format for codec 'none' (id 0), pixel format 'none' (id -1)
Assertion *codec_id != AV_CODEC_ID_NONE failed at src/libavdevice/v4l2.c:811

$ ffmpeg -f v4l2 -list_formats all -i /dev/video1
[video4linux2,v4l2] Raw : yuyv422 : YUYV 4:2:2 : 640x480 720x480 1280x720 1920x1080 2592x1944 0x0
/dev/video1: Immediate exit requested

$ v4l2-ctl -d /dev/video1 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 720x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 1920x1080
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 2592x1944
			Interval: Discrete 0.067s (15.000 fps)
		Size: Discrete 0x0

$ v4l2-ctl -d /dev/video1 --all
Driver Info:
	Driver name      : mx6s-csi
	Card type        : i.MX6S_CSI
	Bus info         : platform:30b80000.csi2_bridge
	Driver version   : 4.14.98
	Capabilities     : 0x84200001
		Video Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Priority: 0
Video input : 0 (Camera: ok)
Format Video Capture:
	Width/Height      : 640/480
	Pixel Format      : ''
	Field             : None
	Bytes per Line    : 0
	Size Image        : 614400
	Colorspace        : Default
	Transfer Function : Default (maps to Rec. 709)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 0, Height 0
	Default     : Left 0, Top 0, Width 0, Height 0
	Pixel Aspect: 1/1
Crop: Left 0, Top 0, Width 0, Height 0
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
```

### Frigate stats

```json
{
    "coral": {
        "camera_fps": 1.0,
        "capture_pid": 246,
        "detection_fps": 0.0,
        "pid": 239,
        "process_fps": 1.0,
        "skipped_fps": 0.0
    },
    "detection_fps": 0.0,
    "detectors": {
        "coral": {
            "detection_start": 0.0,
            "inference_speed": 16.08,
            "pid": 216
        }
    },
    "service": {
        "latest_version": "0.11.1",
        "storage": {
            "/dev/shm": {
                "free": 64.2,
                "mount_type": "tmpfs",
                "total": 67.1,
                "used": 2.9
            },
            "/media/frigate/clips": {
                "free": 238546.4,
                "mount_type": "ext4",
                "total": 251391.1,
                "used": 0.1
            },
            "/media/frigate/recordings": {
                "free": 238546.4,
                "mount_type": "ext4",
                "total": 251391.1,
                "used": 0.1
            },
            "/tmp/cache": {
                "free": 1398.9,
                "mount_type": "overlay",
                "total": 5355.7,
                "used": 3676.7
            }
        },
        "temperatures": {
            "apex_0": 60.05
        },
        "uptime": 24,
        "version": "0.11.1-2eada21"
    }
}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Dev Board

### Network connection

Wireless

### Camera make and model

Google Coral Cam 5MP

### Any other information that may be helpful

If I remove the `-pix_fmt yuv420p` from the `output_args`, `ffmpeg` CPU load is still about 10x that of other cameras at 100%, but is considerably lower than the 250%. However, the video is now garbled and messed up, because frigate expects yuv420 in stead of 422 the camera provides. I may underestimate what's going on here, but I wouldn't think throwing away some chroma data every other horizontal line would be so CPU intensive.

OS is Mendel, a Debian derivative.

### Summary / TL;DR:

1. The camera is (1) very high on system resources compared to other cameras.
2. The camera is (2) unstable, getting soft-bricked when restarting docker.

**Comment by NickM-27** [comment]
This is 100% expected, especially since you haven't disabled rtmp so ffmpeg is converting the raw stream into h264 which is VERY cpu intensive.

**Comment by Redsandro** [comment]
> This is 100% expected, especially since you haven't disabled rtmp

That 100% does not include soft bricking the camera, correct?

I assumed it was disabled by _not_ mentioning rtmp in `roles`. Could you explain how I disable rtmp?

**Comment by NickM-27** [comment]
> That 100% does not include soft bricking the camera, correct?

Devices do weird things when they get overloaded and they sometimes can't even stop correctly. I'd say it's not outside the range of normal. It's also not 100% clear if that's the issue, we've had users use usb webcams without issue so it could very well be an issue with the camera itself

> I assumed rtmp was disabled by not mentioning rtmp in roles. I have also explicitly added rtmp: enabled: False to this camera, still 255% CPU utilization. Could you explain how I disable rtmp for this camera properly?

You only have one stream so all enabled services are added automatically to the roles

```
rtmp:
enabled: false
```

to disable. If it's still using lots of cpu then your device just doesn't have a cpu with enough power. encoding the camera data to h264 especially since you're also asking it to downsize a 5MP stream to 640x480 which is also very cpu intensive

**Comment by Redsandro** [comment]
> since you're also asking it to downsize a 5MP stream to 640x480 which is also very cpu intensive

You might be on to something. The camera sensor is supposed to be able to output RAW 640x480 directly to the GPU. These are the supported sensor modes:

```bash
$ ffmpeg -f v4l2 -list_formats all -i /dev/video1
[video4linux2,v4l2] Raw : yuyv422 : YUYV 4:2:2 : 640x480 720x480 1280x720 1920x1080 2592x1944 0x0
```

If ffmpeg is downsizing from 5MP, then it's not correctly requesting the raw 480 stream from the sensor.

**Comment by NickM-27** [comment]
another thing, at least right now you're not recording with that camera which means you can set the framerate to 5 instead of 30

**Comment by Redsandro** [comment]
__Addendum:__

FFMpeg [docs](https://ffmpeg.org/ffmpeg.html):

> -s[:stream_specifier] size (input/output,per-stream) Set frame size.
> 
> As an input option, this is a shortcut for the `-video_size` **private option**, recognized by some demuxers for which the frame size (...) is **configurable** – e.g. raw video

Reference:

```
-f v4l2 -input_format yuyv422 -video_size 640x480 -framerate 30
```

Summarized, docs in hand, I believe:

- I'm not doing any h264 encoding
- I'm not running rtmp
- I'm not resizing
- 250% CPU

> you're not recording with that camera which means you can set the framerate to 5 instead of 30

The `framerate` (as literal ffmpeg command for v4l2) can't be 5. I'm desperately trying to get the correct native raw stream (640x480x30fps) from the camera, so I need to request 30 fps:

```bash
$ v4l2-ctl -d /dev/video1 --list-formats-ext | grep -A1 640
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
```

I guess if the stream behaved as expected (low CPU) I could start removing options, although I don't think throwing away 5 frames every 6 frames will cause 250% CPU load.

FFMpeg [docs](https://ffmpeg.org/ffmpeg.html):

> [`-r fps`] is not the same as the `-framerate` option used for some input formats like (...) `v4l2`

**Comment by NickM-27** [comment]
Got it, so it should be requesting the smaller resolution. 

Posting new logs maybe helpful now that it's running. 

Either way, frigate calls ffmpeg directly so if there's high CPU usage I don't see it being a frigate issue if the CPU usage is coming from the ffmpeg process (which it definitely seems to since other cameras work as expected)

**Comment by Redsandro** [comment]
> frigate calls ffmpeg directly so if there's high CPU usage I don't see it being a frigate issue

Well, yes and no. Let's say you're right. Isn't ffmpeg the adapter to all cameras? I thought camera-specific stream related ffmpeg command line problems is what the "Camera Support" issue template was for. :grin: 

On the other hand, let's say you're wrong. The majority of the CPU usage seems to come from the 422 -> 420 conversion. Frigate not being able to handle the raw 422 provided by the camera may be worth a thought.

> Posting new logs maybe helpful now that it's running.

No relevant logs here:

```bash
detector.coral  INFO: Starting detection process: 215
frigate.app     INFO: Output process started: 217
ws4py           INFO: Using epoll
frigate.edgetpu INFO: Attempting to load TPU as 
frigate.app     INFO: Camera processor started for coral: 221
frigate.app     INFO: Capture process started for coral: 224
frigate.edgetpu INFO: TPU found
ws4py           INFO: Using epoll
```

Here's the new config from debug screen:

```json
{
  "cameras": {
    "coral": {
      "best_image_timeout": 60,
      "birdseye": {
        "enabled": true,
        "mode": "objects"
      },
      "detect": {
        "enabled": true,
        "fps": 1,
        "height": 480,
        "max_disappeared": 5,
        "stationary": {
          "interval": 0, "max_frames": {
            "default": null,
            "objects": {}
          }, "threshold": 10
        },
        "width": 640
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner", "-loglevel", "warning"
        ],
        "hwaccel_args": [],
        "input_args": [
          "-avoid_negative_ts", "make_zero", "-fflags", "+genpts+discardcorrupt", "-rtsp_transport", "tcp", "-timeout", "5000000", "-use_wallclock_as_timestamps", "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": "-f v4l2 -input_format yuyv422 -video_size 640x480 -framerate 30 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1", 
            "path": "/dev/video1", 
            "roles": [
              "record",
              "rtmp",
              "detect"
            ]
          }
        ],
        "output_args": {
          "detect": ["-f", "rawvideo", "-pix_fmt", "yuv420p"], 
          "record": ["-f", "segment", "-segment_time", "10", "-segment_format", "mp4", "-reset_timestamps", "1", "-strftime", "1", "-c", "copy", "-an"], 
          "rtmp": ["-c", "copy", "-f", "flv"]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -f v4l2 -input_format yuyv422 -video_size 640x480 -framerate 30 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -i /dev/video1 -r 1 -s 640x480 -f rawvideo -pix_fmt yuv420p pipe:", 
          "roles": [
            "record", "rtmp", "detect"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 30,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 50,
        "improve_contrast": false,
        "mask": "",
        "mqtt_off_delay": 30,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "coral",
        "expire_interval": 60,
        "retain": {
          "days": 0, "mode": "all"
        },
        "retain_days": null
      },
      "rtmp": {
        "enabled": false
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": false,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10, "mode": "motion", "objects": {}
        },
        "timestamp": false
      },
      "timestamp_style": {
        "color": {
          "blue": 255, "green": 255, "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "ui": {
        "dashboard": true,
        "order": 0
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "stationary": {
      "interval": 0,
      "max_frames": {
        "default": null,
        "objects": {}
      },
      "threshold": null
    },
    "width": 1280
  },
  "detectors": {
    "coral": {
      "device": "",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner", "-loglevel", "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts", "make_zero", "-fflags", "+genpts+discardcorrupt", "-rtsp_transport", "tcp", "-timeout", "5000000", "-use_wallclock_as_timestamps", "1"
    ],
    "output_args": {
      "detect": [
        "-f", "rawvideo", "-pix_fmt", "yuv420p"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "plus": {
    "enabled": false
  },
  "record": {
    "enabled": false
  },
  "rtmp": {
    "enabled": false
  },
  "snapshots": {
    "enabled": false
  }
}
```

**Comment by NickM-27** [comment]
> I thought camera-specific stream related ffmpeg command line problems is what the "Camera Support" issue template was for. 😁

Definitely, I just said that to establish that the better behavior will need to come from ffmpeg. I don't have nearly as much experience with hardware cameras but seems it should be doing what it can. 

> Frigate not being able to handle the raw 422 provided by the camera may be worth a thought.

Lots of thought has been put into it, we fully recognize it would make hwaccel simpler but it would make other things more complicated and be a complicated thing to support. 

And to be honest, for most devices (even an RPi) that conversion isn't that intensive when run on CPU which says to me this CPU doesn't have much grunt. 

I'd be curious what the output of it says running ffprobe on it (never done ffprobe on a usb cam so not sure what options there are)

**Comment by Redsandro** [comment]
> Lots of thought has been put into it [but] it would make other things more complicated

Yes I understand. In order to keep things manageable, you can't plan for everything. It's a question of how can I use the hardware I already have with frigate, versus what hardware do I need to work with frigate.

> I'd be curious what the output of it says running ffprobe on it (never done ffprobe on a usb cam so not sure what options there are)

Well you can see the output to all commands in the first post for this issue. :smile: 
**For the record, this is NOT an USB camera.** This is the official MIPI-connected Google Coral Camera connected to an official Coral development board. 

> And to be honest, for most devices (even an RPi) that conversion isn't that intensive when run on CPU which says to me this CPU doesn't have much grunt.

Yes exactly. I'm super disappointed that these Coral dev boards are so super weak, because they are not super cheap. I still find it hard to believe.

**Comment by NickM-27** [comment]
> For the record, this is NOT an USB camera. This is the official MIPI-connected Google Coral Camera connected to an official Coral development board.

I know, but they work very similarly from the ffmpeg and linux perspective. also I've helped a few users get USB cameras working but never one of these so have to go off relevant experience.
