### ISSUE TITLE
[Support]: board support question.

### ISSUE THREAD

**Issue by aaronouthier** [blakeblackshear/frigate#4717]
### Describe the problem you are having

I am wondering if there are any known issues with Frigate on the Asus Tinker Edge T with built-in coral EdgeTPU? I am considering purchasing one for use with Frigate.

### Version

N/A

### Frigate config file

```yaml
Not currently using Frigate.
```

### Relevant log output

```shell
None.
```

### FFprobe output from your camera

```shell
Same as above.
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Amcrest

**Comment by NickM-27** [comment]
I'd recommend reading the discussion over at https://github.com/blakeblackshear/frigate/issues/4711

they are not very powerful and it seems they don't support hwaccel either so I wouldn't recommend it for an actual frigate instance

**Comment by aaronouthier** [comment]
Dang!
