### ISSUE TITLE
Mask Zones also for 24/7 recording

### ISSUE THREAD

**Issue by tweak19** [blakeblackshear/frigate#4722]
Hi,
I am not sure, but i think this is currently not implemented.
In European Countrys we habe the Problem that you only record with cameras your own place.

I have the Problem that i could not adjust the camera that there is no public space in the Video.

Whith Blue Iris i easly could mask this zones, it would be pretty nice if this will be available in frigate. Then i could swap my nvr from BI to Frigate.

Thabks for feedback.

**Comment by NickM-27** [comment]
I'd recommend looking at https://github.com/blakeblackshear/frigate/discussions/2866

This is a very CPU intensive task so you'd really want to do this on your camera directly. Otherwise, you can use ffmpeg to do this already (no changes needed on our side)

**Comment by tweak19** [comment]
Really sad news ;( So i need to continue with BI.
The Problem is that my current camera setup only allows 5 Mask Zones in rectangle style. Whith that i was not able to create a good isolation.
And to change the cameras is no option because this is a enterprise setup for huge amount of money...

Thanks for Feedback

**Comment by NickM-27** [comment]
Like I said you can use ffmpeg to do it https://video.stackexchange.com/questions/33661/ffmpeg-apply-opaque-white-with-mask
