### ISSUE TITLE
[Support]: Frigate Container Not Starting 

### ISSUE THREAD

**Issue by crazyfrog-github** [blakeblackshear/frigate#4730]
### Describe the problem you are having

Hi,

Out of nowhere Frigate stopped rendering live view so I restarted Frigate but the container will not start at all in Proxmox:

explicitly configured lxc.apparmor.profile overrides the following settings: features:nesting
run_buffer: 321 Script exited with status 1
lxc_init: 847 Failed to run lxc.hook.pre-start for container "101"
__lxc_start: 2008 Failed to initialize container "101"
TASK ERROR: startup for container '101' failed

### Version

Current Version

### Frigate config file

```yaml
N/A everything works have not made any updates to config
```

### Relevant log output

```shell
explicitly configured lxc.apparmor.profile overrides the following settings: features:nesting
run_buffer: 321 Script exited with status 1
lxc_init: 847 Failed to run lxc.hook.pre-start for container "101"
__lxc_start: 2008 Failed to initialize container "101"
TASK ERROR: startup for container '101' failed
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

HikVision & Dahua

**Comment by NickM-27** [comment]
This looks like a proxmox issue not a frigate issue

**Comment by crazyfrog-github** [comment]
Hi,

Thanks I just checked the LXC docker container for Frigate ran out of storage space. Hopefully if this error happens for others reading this that are using Proxmox and Frigate inside docker inside LXC check to the storage.

This issue is resolved and can be closed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NickM-27** [comment]
Hopefully won't be an issue after 0.12

**Comment by crazyfrog-github** [comment]
Really looking forward to version 0.12 going to be some good features it seems.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
