### ISSUE TITLE
Audio in Live View

### ISSUE THREAD

**Issue by raddacle** [blakeblackshear/frigate#4762]
I've found how to enable audio in recordings, though I know its not available in live view. As I use Frigate as my nvr, it would be very helpful to that here too. I believe I read that go2rtc is going to be integrated in the next version of Frigate, will audio in live view be slated for that as well?

**Comment by NickM-27** [comment]
This has already been added in 0.12, live audio will be supported in the MSE and webrtc live view modes. Audio will not be supported for the existing jsmpeg live view mode.
