### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by evasilisin1984** [blakeblackshear/frigate#4779]
### Describe the problem you are having

Issues getting image from cameras into frigate.   I have a H265 3840x2160 fps 15 main stream, so I set it to use the sub stream which is H264 704x480 fps 20 MPEG.   But I’m getting the following error even with setting size 

### Version

0.11-1

### Frigate config file

```yaml
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
# frigate.yml
mqtt:
  # Required: host name
  host: 192.168.50.3
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: homeassistant
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: PASSWORD
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60
cameras:
  camera_5: # <------ Name the camera
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -c:v mjpeg
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        # rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: rtsp://admin:Ms745001!@192.168.50.243:554/cam/realmonitor?channel=2&subtype=1 # <----- Update for your camera
          roles:
            - detect
            - rtmp
    detect:
      width: 704 
      height: 480 
      fps: 20
    rtmp:
      enabled: false
```

### Relevant log output

```shell
ffmpeg.camera_5.detect         ERROR   : [udp @ 0x11bb040] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[2022-12-22 09:18:03] ffmpeg.camera_5.detect         ERROR   : [udp @ 0x11cb2e0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[2022-12-22 09:18:03] ffmpeg.camera_5.detect         ERROR   : [udp @ 0x11dc050] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[2022-12-22 09:18:03] ffmpeg.camera_5.detect         ERROR   : [udp @ 0x11ec390] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[2022-12-22 09:18:03] ffmpeg.camera_5.detect         ERROR   : [rtsp @ 0x11b3ee0] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown)): unspecified size
[2022-12-22 09:18:03] ffmpeg.camera_5.detect         ERROR   : Consider increasing the value for the 'analyzeduration' and 'probesize' options
[2022-12-22 09:18:03] ffmpeg.camera_5.detect         ERROR   : Output file #0 does not contain any stream
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Any other information that may be helpful

Currently just using CPU until the coral comes.   trying to get it configured first.

**Comment by NickM-27** [comment]
If your stream is h264 then you should be using the default args, there is no reason to use the libx264 encoder. That is only for mjpeg streams which come from webcams or raspberry pi cams

**Comment by evasilisin1984** [comment]
Even with default args, I get nothing but a green screen and even MORE errors lol.   This setup seems to give me the least amount of errors.  But still green.

**Comment by NickM-27** [comment]
Those logs would be helpful, but your stream is h264 and not mjpeg so the args in your config above will not work

**Comment by evasilisin1984** [comment]
Without any args, this is error log `2022-12-22 09:30:21] watchdog.camera_5              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-12-22 09:30:21] ffmpeg.camera_5.detect         ERROR   : [rtsp @ 0x82af00] Unable to open RTSP for listening
[2022-12-22 09:30:21] ffmpeg.camera_5.detect         ERROR   : rtsp://admin:Ms745001!@192.168.50.243:554/cam/realmonitor?channel=2&subtype=1: Cannot assign requested address `

**Comment by NickM-27** [comment]
are you running this on a 32 bit pi?

**Comment by evasilisin1984** [comment]
It is running on a pi.  Not sure what it’s running.  Been a year or two since I really set up the pic lol

**Comment by NickM-27** [comment]
We highly suggest running 64 bit OS instead of 32 as it will be faster and works better.

If that is not an option, you can set your input_args to:

```yaml
input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
```

and it should work

**Comment by NickM-27** [comment]
It's because 32 bit pi uses ffmpeg 4 because the custom build of ffmpeg we use for all 64bit archs is not supported. From ffmpeg 4 -> 5 they changed the arg from `stimeout` to `timeout` so we have `timeout` as the default but if you have a 32bit pi then you have to change it back to `stimeout`

**Comment by evasilisin1984** [comment]
By the way, there is no way to use the H265 mainstream, correct?   Too much to process?

**Comment by NickM-27** [comment]
Not on a pi I don't think

**Comment by evasilisin1984** [comment]
Appreciate the help!  Should have asked a day ago instead of trying myself so much 😂

**Comment by evasilisin1984** [comment]
One more question.   Why does it fail to load clips.   But does snapshots no problem ?

**Comment by NickM-27** [comment]
have you enabled recordings? your config doesn't show them being enabled, and they must be enabled in the config for them to work

**Comment by evasilisin1984** [comment]
Thanks !On Dec 22, 2022, at 1:44 PM, Nicolas Mowen ***@***.***> wrote:﻿
have you enabled recordings? your config doesn't show them being enabled, and they must be enabled in the config for them to work

**Comment by evasilisin1984** [comment]
So the recordings….  They always get stuck “in progress” - what could be the reason it’s doing that?  They’re recording like hours if I don’t delete it.   Should I have something in the config that I maybe don’t ?

**Comment by NickM-27** [comment]
An event is in progress for as long as the object is visible and this is the correct behavior. If you want to tune your recordings to only happen when an object is active then read https://docs.frigate.video/configuration/record#what-do-the-different-retain-modes-mean

If it's staying in progress despite no object of that type being visible then there's false positive and you'll want to view the debug live view to see where it is and use one of the filters to eliminate it

**Comment by evasilisin1984** [comment]
I do have it set to active_objects.   And it stays “in progress” long after the event that triggered it is out of frame.   Like hours

**Comment by NickM-27** [comment]
in progress has nothing to do with whether or not frigate is saving those recordings. And again, it will stay in progress as long as the object is there. The car in my driveway stays in progress for multiple days until I leave and yet the event only has ~20 minutes of recorded footage due to the retention mode

**Comment by NickM-27** [comment]
If that's the case and the object is not in sight then like I said you have a false positive. Check https://docs.frigate.video/guides/false_positives

**Comment by evasilisin1984** [comment]
I mean, it shouldn’t even have activated though.  That car hasn’t moved.  So not sure why it even began to recognize it.  
![Uploading 413D784F-089C-4F63-ADFD-A6BF3058595D.png…]()

**Comment by NickM-27** [comment]
Looks like that image didn't show up. 

But your comment makes it seem like you're misunderstanding. Frigate will track and create events for objects that are stationary. An event being in progress does not mean it is being actively recorded, but it is being actively tracked. This is working exactly as it is supposed to.

**Comment by evasilisin1984** [comment]
So how would I exclude stationary objects ?  There’s no point in tracking a parked car lol.

**Comment by evasilisin1984** [comment]
![AD749A28-4F8E-48E8-A4DC-FD082BF74299](https://user-images.githubusercontent.com/56237607/209246175-56e22843-4db0-4303-9d63-c614c4db461d.jpeg)

**Comment by NickM-27** [comment]
> There’s no point in tracking a parked car lol.

Sure there is, that way you can tell the difference between your car and the car that drove by. If you ignore the car in your driveway then a car driving by will cause it to be re detected. 

It can technically be done with ` detect -> stationary -> max_frames -> car` but as the docs show it's not intended to work that way and the results may not be what you expect. 

Tracking the stationary car takes no extra cpu, doesn't record any except for when the car is moving, I see no reason to not let frigate just work the way it's meant to

**Comment by evasilisin1984** [comment]
So the car is stationary, but it’s recording a car anyways.  I don’t understand why.  Just trying to sort that out.

**Comment by NickM-27** [comment]
What makes you think it's recording the car? Also please include your most recent config so I have up to date information.

**Comment by evasilisin1984** [comment]
It says “car” in the top of the in progress recording.   Sending config in next post

**Comment by evasilisin1984** [comment]
`driveway: # <------ Name the camera
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
     # output_args:
      #  record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
        # rtmp: -c:v libx264 -an -f flv
      inputs:
        - path: rtsp://admin:Ms745001!@192.168.50.243:554/cam/realmonitor?channel=1&subtype=1 # <----- Update for your camera
          roles:
            - detect
            - clips
            - recordings
    detect:
      width: 704 
      height: 480 
      fps: 20
    objects:
      track:
      - person
      - cat 
      - dog
      - car
    motion:
      mask:
       - 0,120,159,44,340,0,1,1,0,900,1080,900,1080,1920,0,1920
       - 467,0,623,32,704,87,704,0
    zones:
      zone_on_driveway:
        coordinates: 314,480,540,480,680,302,428,39,190,79
        objects:
         - person
         - car
         - dog
         - cat
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects `

**Comment by evasilisin1984** [comment]
Man, I just seen tracking car outside of the zone.   I wonder if that’s it.  Even tho I masked the area I didn’t want it to look.

**Comment by NickM-27** [comment]
> It says “car” in the top of the in progress recording. Sending config in next post

As I said previously that does not mean in progress recording. It just means the object is visible and being tracked. 

You've also set your config to record 24/7 for 2 days keeping all segments with motion (in case you didn't know)

> Man, I just seen tracking car outside of the zone. I wonder if that’s it. Even tho I masked the area I didn’t want it to look.

As it says in the docs, motion masks are not meant to and will not stop objects from being detected. Frigate is meant to track all objects and only create events / notify when those objects enter a zone.

**Comment by NickM-27** [comment]
if a car crashes into your car you'd want to have recording from the second it was visible to know where it came from not just the part where it entered your driveway

**Comment by evasilisin1984** [comment]
Yes, I think my issue was 24/7 recording of motion.   I turned that off (well, it’s on to active objects)     Shall see if that works better

**Comment by evasilisin1984** [comment]
`    zones:
      zone_on_driveway:
        coordinates: 314,480,540,480,680,302,428,39,190,79
        objects:
         - person
         - car
         - dog
         - cat
    record:
      enabled: True
      retain:
        days: 2
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects`

So this config is not recording unless an object is active, correct?   or does that record mode active_objects not what I think ?

**Comment by NickM-27** [comment]
Correct, it'll only save segments where an object was detected and moving.

**Comment by evasilisin1984** [comment]
Still having some issues with active_objects.   Even after the object is gone, the camera is in progress for hours.  Also, my sensor in HA is showing “person” as active even after the person is gone.   Same with dog and other objects.  

Could you point me in the right direction

**Comment by NickM-27** [comment]
That would be a false positive. Simply view the debug camera live view with bounding boxes enabled and put a screenshot here I can give more specific advice. Just need to see a filter to filter out the false positive.

**Comment by evasilisin1984** [comment]
![download](https://user-images.githubusercontent.com/56237607/209712031-f313ff2f-c22b-462a-934d-67e6bd90f8e5.png)
Here is an example of a "person" being stuck active and in progress

I also have the same issue with the front door camrera...

**Comment by NickM-27** [comment]
Can you paste your full config? Blue box means the object is no longer seen by frigate, so that event will end after `max_disappeared` frames (5 seconds by default)

**Comment by evasilisin1984** [comment]
![image](https://user-images.githubusercontent.com/56237607/209714291-5379abc3-b2ed-451b-b1c6-7d832c5fa06c.png)
`  driveway:
    rtmp:
      enabled: False
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://admin:Ms745001!@192.168.50.243:554/cam/realmonitor?channel=1&subtype=1 
          roles:
            - detect
        - path: rtsp://admin:Ms745001!@192.168.50.243:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704 
      height: 480 
      fps: 20
    objects:
      track:
      - person
      - bottle
      - car
      - wine glass
      - cat
      - dog
      - motorcycle
      - bicycle
      - pizza 
      - cellphone phone
    zones:
      zone_enter_driveway:
        coordinates: 624,413,344,51,183,81,314,480,547,480
        objects:
         - person
         - dog
         - cat
         - car
         - pizza 
         - cell phone
         - bicycle
         - motorcycle
      zone_on_driveway:
        coordinates: 440,163,530,280,619,403,704,301,704,182,603,58,456,33,343,51
        objects:
         - person
        filters:
          car:
            mask:
              - 543,0,612,73,704,176,704,264,607,378,366,93,351,0,413,0
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 4
    record:
      enabled: True
      retain:
        days: 1
        mode: active_objects
      events:
        retain:
          default: 7
          mode: active_objects
        pre_capture: 5
        post_capture: 10`

Like here is an example.... the car is filtered out, and should not be recording.  But is.  So I am not sure what I am doing wrong here

**Comment by NickM-27** [comment]
object masks filter objects based on the bottom center of their bounding box, a very small mask is needed to filter out the object.

I don't see any motion masks, so as far as the false positives go you may want to put

```yaml
detect:
  stationary:
    interval: 10
```

**Comment by evasilisin1984** [comment]
I  believe this might have been what I needed....  testing now
