### ISSUE TITLE
[Support]: Navigate to subpages within HA by url

### ISSUE THREAD

**Issue by raddacle** [blakeblackshear/frigate#4794]
### Describe the problem you are having

I'm trying to have event notifications open the home assistant app on my phone, and navigate to the event list for a particular camera. Its possible to do if I connect directly to frigate via ip:port as the url updates continually while navigating to ".../events?camera=Doorbell_Camera". However, from HA the url never updates past or to anything other than ".../dashboard". I've tried appending ".../events?camera=Doorbell_Camera" to the HA url, but instead it pulls up a white blank page. Is there another method deep linking to a certain frigate page using the HA base url, so that it would automatically forward to the app from mobile?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Not relevant

**Comment by NickM-27** [comment]
This seems like an issue for https://github.com/blakeblackshear/frigate-hass-addons as it is unrelated to frigate itself. In fact it is likely a duplicate of this https://github.com/blakeblackshear/frigate-hass-addons/issues/53

**Comment by raddacle** [comment]
Good point, my bad. Closed.
