### ISSUE TITLE
Allow score threshold to be set via MQTT

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#48]
This will allow dynamic thresholds for night/day or anything else. It also may be worth having the ability to create predefined thresholds for low, medium, high.

**Comment by blender0** [comment]
I would also like to see the resulting score % in a MQTT topic, like: frigate/cam1/person/score to go along with the frigate/cam1/person/snapshot.

**Comment by blakeblackshear** [comment]
I don't think this is necessary with the new `frigate/events` topic. You can use normal homeassistant conditions on notifications for custom thresholds.
