### ISSUE TITLE
clips won't play on HA add on media browser 

### ISSUE THREAD

**Issue by comanagedit** [blakeblackshear/frigate#480]
**Describe the bug**
was able to successfully record clips but when trying to play the clips from HA media browser the clips won't play on both browser and HA android/iOS app unless I download the clip and use vlc to play. 

**Version of frigate**
0.8.0 Beta 3

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Logs**
* Starting nginx nginx

   ...done.

frigate.app                    WARNING : Camera backyard has rtmp enabled, but rtmp is not assigned to an input.

frigate.app                    WARNING : Camera frontdoor has rtmp enabled, but rtmp is not assigned to an input.

frigate.app                    WARNING : Camera driveway has rtmp enabled, but rtmp is not assigned to an input.

frigate.app                    WARNING : Camera frontyard has rtmp enabled, but rtmp is not assigned to an input.

frigate.app                    WARNING : Camera side has rtmp enabled, but rtmp is not assigned to an input.

frigate.app                    WARNING : Camera garage has rtmp enabled, but rtmp is not assigned to an input.

frigate.mqtt                   INFO    : MQTT connected

detector.coral                 INFO    : Starting detection process: 33

frigate.edgetpu                INFO    : Attempting to load TPU as usb

frigate.app                    INFO    : Camera processor started for backyard: 37

frigate.app                    INFO    : Camera processor started for frontdoor: 38

frigate.app                    INFO    : Camera processor started for driveway: 42

frigate.app                    INFO    : Camera processor started for frontyard: 43

frigate.app                    INFO    : Camera processor started for side: 44

frigate.app                    INFO    : Camera processor started for garage: 48

frigate.app                    INFO    : Capture process started for backyard: 49

frigate.app                    INFO    : Capture process started for frontdoor: 50

frigate.app                    INFO    : Capture process started for driveway: 53

frigate.app                    INFO    : Capture process started for frontyard: 57

frigate.app                    INFO    : Capture process started for side: 63

frigate.app                    INFO    : Capture process started for garage: 67

frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.

      
      
    

**Frigate debug stats**
```
Output from frigate's /debug/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: Operating System
Ubuntu 20.10
Docker version
20.10.2

**Additional context**
do I need to enable anything else for the clips to be playable on HA media browser?

**Comment by Halytskyi** [comment]
The same issue for me, Home Assistant version: 2020.12.2

**Comment by comanagedit** [comment]
looks like a url issue for you, I am able to pull the clips on my end and play it using vlc but it won't play clips directly from HA browser.

**Comment by Halytskyi** [comment]
If I try in browser without "authSig", i.e: "https://my-HA-url/api/frigate/clips/outdoor_front-1609907530.307049-qf9u85.mp4" I getting "401: Unauthorized" (which seems expected).
When I try directly from Frigate http, i.e: "http://my-Frigate-url/clips/outdoor_front-1609907530.307049-qf9u85.mp4" I getting "403 Forbidden".
But I see file "outdoor_front-1609907530.307049-qf9u85.mp4" on disk and can play it by player directly.

**Comment by comanagedit** [comment]
will close this, my issue was I was using H265 and once I changed it to H264 I was able to do a playback within HA.
