### ISSUE TITLE
Zoom during playback on android and ios 

### ISSUE THREAD

**Issue by jonofmac** [blakeblackshear/frigate#4807]
**Describe what you are trying to accomplish and why in non technical terms**
When viewing a clip (raw recording of camera) from the events menu on a mobile device, something is set of configured that prevents me from being able to zoom. I click in an event, to full screen and try to pinch to zoom but on Android the gesture is ignored and in iOS you can zoom but only to the center of the video. 

**Describe the solution you'd like**
The native video players of both platforms support the ability to do this already.

**Describe alternatives you've considered**
I've got home assistant sending me a link to the file of the clip so I can open it directly in chrome of safari and pinch to zoom like normal but this only works for events as they come in. 

**Additional context**

**Comment by NickM-27** [comment]
If I recall correctly this was looked at before and I'm not sure there's anything that can be done as it's likely just a limitation of the browser video player.
