### ISSUE TITLE
RTSP Url from http request

### ISSUE THREAD

**Issue by alexmorbo** [blakeblackshear/frigate#4810]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to get rtsp url for ffmpeg process from http request so that I can add some cameras from [trassir](https://trassir.com/) via trassir sdk.

**Describe the solution you'd like**
Trassir have an API, that generates rtsp links.
For this you need to call `auth` method, then call `get_video` method, takes token and generate rtsp link with token. 
This token expires in 15 minutes, if no one fetching this stream.

So, I write a wrapper in php, that works with trassir and exposes api, that generate rtsp links.

**Additional context**
So, is there a way, to take rtsp link from http request (http 200, content = rtsp://.....) and forward it to ffmpeg?
Like:
```
curl -v http://192.168.168.67:8899/server/1/channel/DAiYlaGz/video/rtsp
*   Trying 192.168.168.67:8899...
* Connected to 192.168.168.67 (192.168.168.67) port 8899 (#0)
> GET /server/1/channel/DAiYlaGz/video/rtsp HTTP/1.1
> Host: 192.168.168.67:8899
> User-Agent: curl/7.85.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: ReactPHP/1
< Date: Thu, 29 Dec 2022 12:53:13 GMT
< Content-Length: 33
<
* Connection #0 to host 192.168.168.67 left intact
rtsp://66.66.66.66:555/D67UWL50
```

rtsp://66.66.66.66:555/D67UWL50 - rtsp stream

**Comment by NickM-27** [comment]
This could probably be done in the next version with go2rtc included. I'd recommend checking that out as it should be able to do it via the echo module

**Comment by alexmorbo** [comment]
> This could probably be done in the next version with go2rtc included. I'd recommend checking that out as it should be able to do it via the echo module

Thanks for fast reply!

I checked go2rtc and it works!
```
echo:curl http://192.168.168.67:8899/server/1/channel/DAiYlaGz/video/rtsp
```

That syntax works fine.
Sow for now just wait for new version with go2rtc?

**Comment by NickM-27** [comment]
Yes, you'll just need to as this stream to the frigate-go2rtc.yaml and reference that in the frigate config. rtsp://localhost:8554/camera_name

**Comment by NickM-27** [comment]
actually, you could also do it inside the frigate config itself as it is now, so I am going to close this since it is possible in 0.12 as it is now
