### ISSUE TITLE
Not a bug but a question.

### ISSUE THREAD

**Issue by meteosat007** [blakeblackshear/frigate#483]
Firstly great product now I get the construct and have learnt the rules which are much better documented in the last update.

My question is what object types are avilable with the default deployment?
Now clearly I can see cat, dog, car, person, truck but what else is available, do we have a list as despite many google searches and trawls through the issues I cannot find the answer?

Also if I dont specify specific objects and leave it blank will it detect any movement without a category, but still raise an mqtt into HASS and save clips etc?

Not a show stopper but good to know as I would like to ditch my Hikvisio DVR and use frigate into HASS as so much easier to use etc...

Alan

**Comment by meteosat007** [comment]
Doh. Just ventured deep into the beta 4 code and can see the ability to change the COCO labels.
So in theory I could select any of these as filters or provide no filters and it would allocate 15 bird if the detected object met the criteria of a bird?

Great news if tis is the case as I will give it a try tomorrow test the accuracy before ditching the old DVR.

0  person
1  bicycle
2  car
3  motorcycle
4  airplane
5  bus
6  train
7  truck
8  boat
9  traffic light
10  fire hydrant
12  stop sign
13  parking meter
14  bench
15  bird
16  cat
17  dog
18  horse
19  sheep
20  cow
21  elephant
22  bear
23  zebra
24  giraffe
26  backpack
27  umbrella
30  handbag
31  tie
32  suitcase
33  frisbee
34  skis
35  snowboard
36  sports ball
37  kite
38  baseball bat
39  baseball glove
40  skateboard
41  surfboard
42  tennis racket
43  bottle
45  wine glass
46  cup
47  fork
48  knife
49  spoon
50  bowl
51  banana
52  apple
53  sandwich
54  orange
55  broccoli
56  carrot
57  hot dog
58  pizza
59  donut
60  cake
61  chair
62  couch
63  potted plant
64  bed
66  dining table
69  toilet
71  tv
72  laptop
73  mouse
74  remote
75  keyboard
76  cell phone
77  microwave
78  oven
79  toaster
80  sink
81  refrigerator
83  book
84  clock
85  vase
86  scissors
87  teddy bear
88  hair drier
89  toothbrush

**Comment by blakeblackshear** [comment]
Those labels are set in the model, but you can rename them. By default, I have renamed truck to car because the model frequently has a hard time differentiating. By renaming truck to car, frigate sees them as the same. You could also rename, cat, dog, sheep, horse, and cow as animal to track them as a single object type.

**Comment by meteosat007** [comment]
That makes perfect sense. 
So if I have no filters car, person set in the config then it will automatically add which ever best match is chosen to the text on the clip. So if I held up an ice cream the clip would read ice cream 87%?

Of course by applying filters we get out what we are looking for but a few of my cameras could pickup animals. So add all wanted types as filters or no filters and accept more rogue labels?

Alan

**Comment by blakeblackshear** [comment]
The numbers are fixed in the model. It is trained on those 90 objects. You can rename them, but you can't add anything new or remove any of them.

**Comment by meteosat007** [comment]
I think I’m not been clear. Get the model is fixed 100% but we can rename some to group as mentioned that a car or truck could be labelled as an automobile for instance. 

In the camera settings we have object filters which could be car truck person etc, which I think limits the number of types sent to HASS and MQTT.
So if I have no object filter entries as above in my camera config then I would get an MQTT and HASS entry for each different model label detection which I think is what would happen. 

Will try it tomorrow and feedback findings.

Alan

**Comment by meteosat007** [comment]
Hi,

So if I dont add object name into the track section then nothing is tracked. So for each of the objects that I would like tracked I have to enter them into the config. This is all ok as just wasnt sure if no entries defaulted to all being tracked and I have proved that is not the case which actually make perfect sense.

Please close.

Alan

**Comment by Eeeeeediot** [comment]
how do you amend the labels file on HassOS addon?
