### ISSUE TITLE
create an event based on Motion in the recording.

### ISSUE THREAD

**Issue by psykodali** [blakeblackshear/frigate#4833]
i would like to be able to see all the motion detected as events in the recording tab even if i'am setting the detection to off

thanks !

**Comment by jmtatsch** [comment]
This would also be very interesting for me as I have a lot of unclassified objects in my garden (foxes, squirrels, rabbits, mice, etc) that are therefore not tracked but still interesting to me.
Maybe those should not be shown by default but it would be really nice to have a label 'unknown' that can be selected to make them visible.

**Comment by NickM-27** [comment]
This has been implemented as part of the new ui, there is a dedicated motion tab in the events page

**Comment by Gollam** [comment]
@NickM-27 should I see that motion tab in 0.13.2? Cannot seem to find it.

**Comment by jmtatsch** [comment]
No its only on the development branch so far.
