### ISSUE TITLE
Minor typo in docs for config schema path

### ISSUE THREAD

**Issue by T3chArmy** [blakeblackshear/frigate#4844]
Not sure if this is the correct place to report this, however I noticed this minor typo in the docs

https://github.com/blakeblackshear/frigate/blob/ff56262c6e6d4c63bb0f938952e3ae8a729d4419/docs/docs/configuration/index.md?plain=1#L30

I believe this line is missing `.json` as part of the web path for the config schema. 

I believe this should read `# yaml-language-server: $schema=http://frigate_host:5000/api/config/schema.json` otherwise the user is served with a 404 not found error.

**Comment by NickM-27** [comment]
For 0.11 it is correct https://github.com/blakeblackshear/frigate/blob/be2408b36617f719b81dc3935a8e598f0791a521/frigate/http.py#L591

**Comment by NickM-27** [comment]
In the dev image though it has changed to .json so I made a pr to update that for the dev docs https://github.com/blakeblackshear/frigate/pull/4855
