### ISSUE TITLE
Question about snapshots

### ISSUE THREAD

**Issue by InToSSH** [blakeblackshear/frigate#486]
Hi, first of all thank you for this awesome project.

I am currently using the 0.8.0-beta3 version, because on the stable when I turned on clip saving, I was getting ffmpeg broken frames error (with HW accel, without it, the RTSP stream was still green).

I also use the HA integration, which works great and I am glad to see that the Media Browser works even when the clip and HA media folders are not the same, this is amazing!

My question is: the snapshot size is set to 175px for the media browser, which is fine for the thumbnail, but is it possible to have another snapshot which is full image and not cropped (or with different settings, less cropped image, etc)? I woud like to use this one for the Android notification from HA - so it would be great if they were sent via MQTT aswell. 
I tried your `event/<id>/snapshot.jpg?format=android` endpoint but this just uses the same snapshot and adds black background to fit the ratio.

Also nice feature would be if those snapshots could be auto saved to the /clips (or perhaps /snapshots) directory right from Frigate - but I guess this is partially substituted by the HA Media browser with thumbnails.

Thank you very much!

**Comment by blakeblackshear** [comment]
This is already in the works. Thumbnails (saved in the database for media browser) and Snapshots (jpg saved to clips directory) will be completely independent.

**Comment by InToSSH** [comment]
That's awesome, thank you! So far the beta with HA integration has been working well.
