### ISSUE TITLE
[Support]: 0.12.0 beta1 Zone selection not works

### ISSUE THREAD

**Issue by Chris18284** [blakeblackshear/frigate#4881]
### Describe the problem you are having

Zone selection not works:
https://user-images.githubusercontent.com/117124485/210446440-d4e3e908-3d8c-45cc-95c5-78b9600fc7c7.mp4

### Version

0.12.0-53D39A1

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

**Comment by Chris18284** [comment]
Problem was my reverse proxy, sorry.

**Comment by NickM-27** [comment]
Going to need more info and a video including the URL bar, I'm unable to reproduce this and all 4 filters are working as expected

**Comment by Chris18284** [comment]
URL bar shows "http://192.168.1.3:5000/events?"
If I manually type "http://192.168.1.3:5000/events?&zones=our_zone" it works well.

**Comment by NickM-27** [comment]
yeah the problem is you only have one zone, it doesn't handle that currently, I see now

**Comment by NickM-27** [comment]
If you click the blue camera it will work as expected
