### ISSUE TITLE
[HW Accel Support]: tensorrt_models.sh raw file not avalible

### ISSUE THREAD

**Issue by Zacgoose** [blakeblackshear/frigate#4892]
### Describe the problem you are having

Hi,

So the doco has the following link to download the tensorrt_models.sh file,
https://raw.githubusercontent.com/blakeblackshear/frigate/nvidia-detector/docker/tensorrt_models.sh

However this file does not exist there, I have found that NateMeyer who help with this implementation does have the file available at,
https://raw.githubusercontent.com/NateMeyer/frigate/nvidia-detector/docker/tensorrt_models.sh

If this can be update so people don't get confused or if blakeblackshear can set this file to pubic to align with the documentation that would also work.

### Version

0.12.0-53D39A1

### Frigate config file

```yaml
NA
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

NA

**Comment by klunkeh** [comment]
You can find the file in the repo here:
[https://raw.githubusercontent.com/blakeblackshear/frigate/v0.12.0-beta1/docker/tensorrt_models.sh](https://raw.githubusercontent.com/blakeblackshear/frigate/v0.12.0-beta1/docker/tensorrt_models.sh)

**Comment by NickM-27** [comment]
The link in the docs has been set for when this release goes public

**Comment by Zacgoose** [comment]
They are not needed anymore, they will be gererated the first time you start the docker with the required configuration
