### ISSUE TITLE
[Support]: Probably small errors in docs

### ISSUE THREAD

**Issue by mr-manuel** [blakeblackshear/frigate#4893]
### Describe the problem you are having

Hello,

I think I found some small issues in the docs.

Since the 0.12.0 there is a config editor I guess the `:ro` should be removed?
https://github.com/blakeblackshear/frigate/blob/ebef38e4088b09f7839b324e228229b9af71b845/docs/docs/frigate/installation.md?plain=1#L41
https://github.com/blakeblackshear/frigate/blob/ebef38e4088b09f7839b324e228229b9af71b845/docs/docs/frigate/installation.md?plain=1#L58

The name of the config file should be the same as in the samples above?
https://github.com/blakeblackshear/frigate/blob/ebef38e4088b09f7839b324e228229b9af71b845/docs/docs/frigate/installation.md?plain=1#L68

If I'm not mistaken I could open a PR if you want.

### Version

0.12.0 Beta 1

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
A PR has already been opened for the former and the latter doesn't matter since if frigate is running then it will find the file since the config editor uses the same logic as the startup. 

Either way suggest making a PR if you think something needs to change.
