### ISSUE TITLE
Image/recording path in notifications

### ISSUE THREAD

**Issue by Gollam** [blakeblackshear/frigate#4894]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to process the MQTT notifications, without involving Home Assistant, HACS, or the Frigate add-on.

**Describe the solution you'd like**
If the frigate/events JSON payload would contain the filename/path of the actual thumbnail and/or video clip, then I'd be able to process it.

**Describe alternatives you've considered**
I have looked at the example JSON data, it contains the notification "id" field with some proprietary value, which I believe the Frigate add-on would understand and be able to translate to the actual picture/video.

**Comment by NickM-27** [comment]
This is already possible.

Snapshots are available at https://docs.frigate.video/integrations/api#get-apieventsidsnapshotjpg and clips are available at https://docs.frigate.video/integrations/api#get-apieventsidclipmp4

Also there is no "video path" as all clips / recordings are generated dynamically from 10 second segments. The recording segments are considered internal metadata and all access needs to go through the API

**Comment by Gollam** [comment]
Thanks! I'll check.
