### ISSUE TITLE
support for old hardware with no AVX

### ISSUE THREAD

**Issue by thepiam** [blakeblackshear/frigate#49]
I'm running frigate on a laptop with an old Intel CPU with no AVX support: 
Intel(R) Core(TM) i3 CPU M 370 @ 2.40GHz
I have google coral USB accelerator plugged into this laptop.

When running frigate I received the following error:
frigate    | 2019-07-08 14:35:13.075587: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

Would really appreciate if someone could suggest how to modify existing codes in frigate in order to run on such old hardware. Thank you so much in advance.

**Comment by blakeblackshear** [comment]
That message is more of a warning. It should still function fine. The next version uses different libraries, and that message should not appear.

**Comment by thepiam** [comment]
Ah thank you so much! I thought it was broken. Will try again.

**Comment by pdecat** [comment]
I wanted to recycle an old computer with an Intel Core E4400 and the frigate addon container `ccab4aaf/amd64-addon-frigate-beta:1.2` fails with the following error:

```
Fatal Python error: Illegal instruction
Current thread 0x00007f5aea255740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1101 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 36 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/opt/frigate/frigate/edgetpu.py", line 14 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/opt/frigate/frigate/app.py", line 15 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 783 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/opt/frigate/frigate/__main__.py", line 7 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
```

Apparently, this is caused by missing CPU instructions: https://github.com/tensorflow/tensorflow/issues/17411#issuecomment-608027554 even if using an EdgeTPU https://github.com/google-coral/edgetpu/issues/163 (but maybe not AVX instruction)
And working it around would require rebuilding tensorflow `tflite-runtime` and/or `libedgetpu.so`.

**Comment by pdecat** [comment]
Changing frigate configuration from:

```
detectors:
  coral:
    type: edgetpu
    device: pci
```
to
```
detectors:
  cpu:
    type: cpu
```

does not help.

**Comment by pdecat** [comment]
Rebuilding the `tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl` package on the target machine with an old Core2 Duo E4400 and using a docker image built from `blakeblackshear/frigate:0.8.0-beta3-amd64` with just this new package installed works.

I've created an addon variant named `frigate_beta_oldcpu` in my fork to demonstrate this: https://github.com/pdecat/frigate-hass-addons/commit/3179b179ac6494d9993f649a6eb3bea90f54a094

The Dockerfile for `pdecat/frigate:0.8.0-beta3-amd64-oldcpu`: 

```
FROM blakeblackshear/frigate:0.8.0-beta3-amd64
COPY tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl .
RUN pip3 install --upgrade tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl
```

The wheel package was built following the instructions from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

@blakeblackshear Is this something you would like to support in your official repository? If so, I could look into putting all this in a PR in a cleaner way. The wheel package may even be built at deployment time on the target Home Assistant instance by the supervisor in a docker container to make sure the exact instruction set supported by the target is used for optimizations at build time.

**Comment by moskovskiy82** [comment]
@pdecat is there a way to try out your fork of the add-on?

**Comment by pdecat** [comment]
@moskovskiy82 you should be able to add https://github.com/pdecat/frigate-hass-addons/ as a Supervisor repository and then see the third variant `Frigate NVR Beta (old x86_64 CPU without AVX)`:

![image](https://user-images.githubusercontent.com/318490/106578796-35365e80-6540-11eb-834a-9a51fb0b61b0.png)

Note: this version is built on top of `frigate:0.8.0-beta3` as I've put aside my migration for the time being but should be enough to validate if it is working for you. I'm still planning to clean this up someday...

**Comment by moskovskiy82** [comment]
Thanks. Missed that one. Installed instead 1.3 (Update to 0.7.3) which appeared from your repo. And managed to run it. will give a shot for the newer version

**Comment by pdecat** [comment]
1.3 is the same as the official version from this repository.
It is working on old CPUs as it was using an older version of tflite compiled without modern CPU optimizations.

**Comment by moskovskiy82** [comment]
@pdecat got it up and running without any issues. The only thing - no webUI. Instead when clicking on open web ui in add ons i get just a line of text.

{"detection_fps":0.5,"detectors":{"cpu":{"detection_start":1612266480.825662,"inference_speed":2105.29,"pid":32}},"cam1":{"camera_fps":10.1,"capture_pid":36,"detection_fps":0.5,"pid":34,"process_fps":0.3,"skipped_fps":0.0}}

**Comment by pdecat** [comment]
Yeah, Web UI was added later (beta 4 IIRC).

**Comment by moskovskiy82** [comment]
> Yeah, Web UI was added later (beta 4 IIRC).

Any chance on the update of the fork?

**Comment by pdecat** [comment]
Looking into implementing my proposition :

> The wheel package may even be built at deployment time on the target Home Assistant instance by the supervisor in a docker container to make sure the exact instruction set supported by the target is used for optimizations at build time.

First installation will take time.

**Comment by moskovskiy82** [comment]
> PS: with this fork, the address to use in the HA integration is `http://be8d440d-frigate-beta:5000` instead of `http://ccab4aaf-frigate:5000` / `http://ccab4aaf-frigate-beta:5000`

Well tried http://be8d440d_frigate-beta-oldcpu:5000 and http://be8d440d_frigate-beta:5000 without any luck
Unable to connect to Frigate. error

**Comment by blakeblackshear** [comment]
It was

**Comment by pdecat** [comment]
Oh, indeed. Let me rebuild the addon on top of frigate 0.8.1.

And you're right, it's http://be8d440d-frigate-beta-oldcpu:5000/

**Comment by pdecat** [comment]
I've pushed https://github.com/pdecat/frigate-hass-addons/commit/e70333e20813429008a529b2770887d3307e6ec6:
> Dynamically build tensorflow tflite wheel on target platform and use official blakeblackshear/frigate:0.8.1 as base image

@moskovskiy82 you should be able to reload repositories and update the addon.

![image](https://user-images.githubusercontent.com/318490/106610113-a6890800-6566-11eb-9875-eb78bbf93613.png)

**Comment by pdecat** [comment]
I had to fix the Dockerfile so I published a new version: https://github.com/pdecat/frigate-hass-addons/commit/b562d4b73dcd1edef70b0cacb0336407139b8498

**Comment by pdecat** [comment]
I've tentatively submitted https://github.com/blakeblackshear/frigate-hass-addons/pull/12 as draft to get feedback.

**Comment by moskovskiy82** [comment]
> I had to fix the Dockerfile so I published a new version because 
> ```

The new one built just fine. Although get the following error now

peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
RuntimeErrordetector.cpu                   INFO    : Starting detection process: 33
: module compiled against API version 0xe but this version of numpy is 0xd
frigate.app                    INFO    : Camera processor started for uchastok: 35
Process detector:cpu:
ImportError: numpy.core.multiarray failed to import
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 72, in __init__
    self.interpreter = tflite.Interpreter(
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 280, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
SystemError: <built-in method CreateWrapperFromFile of PyCapsule object at 0x7f5d7f40b6f0> returned a result with an error set
frigate.app                    INFO    : Capture process started for uchastok: 37
frigate.mqtt                   INFO    : MQTT connected
frigate.watchdog               INFO    : Detection appears to have stopped. Restarting frigate
frigate.app                    INFO    : Stopping...
frigate.object_processing      INFO    : Exiting object processor...
frigate.events                 INFO    : Exiting event cleanup...
frigate.events                 INFO    : Exiting event processor...
frigate.record                 INFO    : Exiting recording maintenance...
frigate.watchdog               INFO    : Exiting watchdog...
frigate.stats                  INFO    : Exiting watchdog...
root                           INFO    : Waiting for detection process to exit gracefully...

**Comment by pdecat** [comment]
Oh, I think I know why. Let me pin the same version as in the frigate Dockerfile.

**Comment by pdecat** [comment]
Pushed https://github.com/pdecat/frigate-hass-addons/commit/8ed9d6b21c42a50a2336bafc48ea99d85f2e0ccb

**Comment by moskovskiy82** [comment]
> Pushed [pdecat/frigate-hass-addons@8ed9d6b](https://github.com/pdecat/frigate-hass-addons/commit/8ed9d6b21c42a50a2336bafc48ea99d85f2e0ccb)

Everything is working. I guess. Camera shows a green screen but that's i guess a config error i will solve. Thank you!!!

**Comment by parhedberg** [comment]
@moskovskiy82 , did you ever solve that green picture?

**Comment by moskovskiy82** [comment]
@parhedberg Yep. Just follow the documentation for frigate. You need to match the width/height/fps to you cam stream otherwise it will not work

**Comment by albertcaba** [comment]
Hello, how can I use this? I tried adding https://github.com/pdecat/frigate-hass-addons to the addon store in Hassio, I could add it, but when I try to install the old cpu variant, the installation never ends. Also the link Frigate NVR Beta for old x86_64 CPUs is dead. Do I need to create my own docker container? Or am I doing something wrong? Thank you in advance!

**Comment by inode-** [comment]
Any way to get the old CPU support with the docker version?

**Comment by toddrob99** [comment]
@inode-  based on everything I read about this issue, I ended up using the below Dockerfile (github won't let me attach it) and building a custom docker image. I want to give credit, but to be honest I don't remember where I copied it from or what modifications I had to make. I have not updated it with the latest stable version of Frigate since April, but if you want to use the image I built it's on Docker Hub as `toddrob/frigate:oldcpu`. I'll probably update it soon, now that I realize it's been a while.

```
ARG BUILD_ARCH=amd64

FROM ubuntu:20.04 as base
ENV DEBIAN_FRONTEND=noninteractive
# tflite dependencies, see https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package
# libedgetpu dependencies, see https://github.com/google-coral/libedgetpu/blob/master/docker/Dockerfile
RUN apt-get -qq update \
    && apt-get -qq install -y \
    python3 \
    python3-dev \
    python3-numpy \
    python3-pip \
    python3-pybind11 \
    build-essential cmake git pkg-config \
    curl unzip \
    swig libjpeg-dev zlib1g-dev \
    libusb-1.0-0-dev xxd

FROM base as build_libedgetpu
RUN git clone https://github.com/google-coral/libedgetpu.git
RUN cd libedgetpu && git checkout release-grouper
RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list \
    && curl -s https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | apt-key add - \
    && apt-get -qq update \
    && apt-get -qq install bazel=3.2.0
RUN cd /libedgetpu && bazel fetch --experimental_repo_remote_exec @coral_crosstool//...
RUN sed -i 's/"-msse4.2"//g' $HOME/.cache/bazel/*/*/external/coral_crosstool/cc_toolchain_config.bzl.tpl
RUN printf "build --copt=-march=native\nbuild --host_copt=-march=native\n" > ~/.bazelrc
RUN cd /libedgetpu && make libedgetpu
RUN apt-get -qq install debhelper
RUN cd /libedgetpu && dpkg-buildpackage -rfakeroot -us -uc -tc -b

FROM base as build_tflite
RUN git clone https://github.com/tensorflow/tensorflow.git
RUN cd tensorflow && git checkout v2.5.1
RUN bash tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
RUN env BUILD_NUM_JOBS=$(($(grep -c "^processor" /proc/cpuinfo) / 2)) bash tensorflow/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh

FROM blakeblackshear/frigate:stable-${BUILD_ARCH}
COPY --from=build_libedgetpu /libedgetpu1-max_16.0_amd64.deb /
RUN dpkg -i /libedgetpu1-max_16.0_amd64.deb
COPY --from=build_tflite /tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-2.5.1-cp38-cp38-linux_x86_64.whl /wheels/
RUN pip3 install --force-reinstall --no-deps /wheels/tflite_runtime-2.5.1-cp38-cp38-linux_x86_64.whl
```

**Comment by pdecat** [comment]
This comes from https://github.com/blakeblackshear/frigate-hass-addons/pull/12
