### ISSUE TITLE
[Support]: Clicking on "events" on a specific camera no longer shows you events for just that camera [0.12.0-beta1]

### ISSUE THREAD

**Issue by thinkloop** [blakeblackshear/frigate#4922]
### Describe the problem you are having

Previously when you clicked "events" on a specific camera it would show events just for that camera. After 0.12.0-beta1 all cameras are selected with each having to be deselected manually.

### Version

0.12.0-beta1

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
This has already been fixed https://github.com/blakeblackshear/frigate/pull/4875
