### ISSUE TITLE
Many ffmpeg errors continuously

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#493]
Hi Blake,

I didnt want to bother you during the holidays but i have been having tons of errors in the logs for quite some time, but despite those errors things have been working. However today i configured a 3rd camera (same Ezviz cam i use for the garage) and i think either my raspberry pi is struggling or frigate is struggling to handle them. 

![Screenshot_20210109-115847_Chrome](https://user-images.githubusercontent.com/30929896/104089814-2c6ca880-5272-11eb-8008-bebaf8e3a520.jpg)

I see the following errors in the logs:

AttributeError: 'CameraState' object has no attribute 'motion_boxes'
watchdog.Garage                INFO    : No frames received from Garage in 20 seconds. Exiting ffmpeg...
watchdog.Garage                INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Garage                INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Garage: ffmpeg process is not running. exiting capture thread...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaaae97eac10] moov atom not found
/tmp/cache/Garage-20210108194308.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Garage-20210108194308.mp4
werkzeug                       ERROR   : Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/opt/frigate/frigate/http.py", line 260, in imagestream
    frame = detected_frames_processor.get_current_frame(camera_name, draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 477, in get_current_frame
    return self.camera_states[camera].get_current_frame(draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 264, in get_current_frame
    motion_boxes = self.motion_boxes.copy()
AttributeError: 'CameraState' object has no attribute 'motion_boxes'
werkzeug                       ERROR   : Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/opt/frigate/frigate/http.py", line 260, in imagestream
    frame = detected_frames_processor.get_current_frame(camera_name, draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 477, in get_current_frame
    return self.camera_states[camera].get_current_frame(draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 264, in get_current_frame
    motion_boxes = self.motion_boxes.copy()
AttributeError: 'CameraState' object has no attribute 'motion_boxes'
werkzeug                       ERROR   : Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/opt/frigate/frigate/http.py", line 260, in imagestream
    frame = detected_frames_processor.get_current_frame(camera_name, draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 477, in get_current_frame
    return self.camera_states[camera].get_current_frame(draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 264, in get_current_frame
    motion_boxes = self.motion_boxes.copy()
AttributeError: 'CameraState' object has no attribute 'motion_boxes'
watchdog.Garage                INFO    : No frames received from Garage in 20 seconds. Exiting ffmpeg...
watchdog.Garage                INFO    : Waiting for ffmpeg to exit gracefully...
watchdog.Garage                INFO    : FFmpeg didnt exit. Force killing...
frigate.video                  INFO    : Garage: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Garage: ffmpeg process is not running. exiting capture thread...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xaaab11c44c10] moov atom not found
/tmp/cache/Garage-20210108194408.mp4: Invalid data found when processing input
frigate.events                 INFO    : bad file: Garage-20210108194408.mp4
watchdog.Garage                INFO    : No frames received from Garage in 20 seconds. Exiting ffmpeg...
watchdog.Garage                INFO    : Waiting for ffmpeg to exit gracefully...
werkzeug                       ERROR   : Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/opt/frigate/frigate/http.py", line 260, in imagestream
    frame = detected_frames_processor.get_current_frame(camera_name, draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 477, in get_current_frame
    return self.camera_states[camera].get_current_frame(draw_options)
  File "/opt/frigate/frigate/object_processing.py", line 264, in get_current_frame
    motion_boxes = self.motion_boxes.copy()
AttributeError: 'CameraState' object has no attribute 'motion_boxes'

My config is as follows:

detectors:
  coral:
    type: edgetpu
    device: usb
mqtt:
  host: core-mosquitto.local.hass.io
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxx
  password: xxx
ffmpeg:
  hwaccel_args: '-c:v h264_v4l2m2m'
cameras:
  Garage:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:xxxx@192.168.178.209:554/h.264'
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 5
    mask: >-
      poly,0,1072,2,1,1919,7,1917,1070,1495,1072,1678,653,547,227,528,89,357,109,370,292,116,340,316,1072
    best_image_timeout: 60
    zones:
      Front:
        coordinates: >-
          0,1072,2,1,1919,7,1917,1070,1495,1072,1678,653,547,227,528,89,357,109,370,292,116,340,316,1072
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    save_clips:
      enabled: true
      pre_capture: 5
      post_capture: 8
      objects:
        - person
        - cat
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: false
      retain_days: 30
    rtmp:
      enabled: false
    snapshots:
      show_timestamp: true
      draw_zones: true
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
  Garden:
    ffmpeg:
      inputs:
        - path: 'rtsp://192.168.178.234/profile2/media.smp'
          roles:
            - detect
            - clips
    width: 1280
    height: 720
    fps: 5
    mask: 'poly,0,718,2,2,1275,4,1275,320,1066,182,199,478,232,713'
    best_image_timeout: 60
    zones:
      Terrasse:
        coordinates: '0,718,2,2,1275,4,1275,320,1066,182,199,478,232,713'
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    save_clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: false
      retain_days: 30
    rtmp:
      enabled: false
    snapshots:
      show_timestamp: true
      draw_zones: true
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
  Street:
    ffmpeg:
      inputs:
        - path: 'rtsp://admin:xxxx@192.168.178.19:554/h.264'
          roles:
            - detect
            - clips
    width: 1920
    height: 1080
    fps: 5
    mask: >-
      poly,1,1071,4,1,1919,3,1917,274,1919,1073,1313,1073,1612,752,1403,608,1570,223,1395,121,1344,421,1213,362,270,1064
    best_image_timeout: 60
    zones:
      Terrasse:
        coordinates: >-
          1,1071,4,1,1919,3,1917,274,1919,1073,1313,1073,1612,752,1403,608,1570,223,1395,121,1344,421,1213,362,270,1064
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.7
    save_clips:
      enabled: true
      pre_capture: 5
      post_capture: 5
      objects:
        - person
        - cat
      retain:
        default: 10
        objects:
          person: 15
    record:
      enabled: false
      retain_days: 30
    rtmp:
      enabled: false
    snapshots:
      show_timestamp: true
      draw_zones: true
      draw_bounding_boxes: true
      crop_to_region: true
      height: 175
    objects:
      track:
        - person
        - cat
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7
logger:
  default: info
  logs:
    frigate.mqtt: error
save_clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 15
objects:
  track:
    - person
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7

**Comment by cybertza** [comment]
Seems you have quite a lot of errors, The easiest would be for you to start with a more "basic" config, also seems you are out of temp space, depending on the build its either the /tmp/SHM or the tempfs thats out of space.
frigate.events INFO : bad file: Garage-20210108194408.mp4, i have also had some luck with making the stream constant bit rate and forcing the resolution on the cam, but the first thing would be to look at that /tmp/SHM free space with a df -h /tmp/shm

**Comment by cybertza** [comment]
its also advices to be more vigilant when posting configs with passwords online :p

**Comment by asemev** [comment]
Thanks a lot. I will look into it. Ooops indeed. I thought I removed my passwords but the cams also have it. Totally forgot about it. Time to change them all :)

**Comment by asemev** [comment]
I think temp space is not the issue right?

![Screenshot_20210111-150821_JuiceSSH](https://user-images.githubusercontent.com/30929896/104192313-f3be0200-541e-11eb-9c19-17a83afc186d.jpg)

**Comment by cybertza** [comment]
Check 
#439 
Perhaps that can help?

**Comment by mattheys** [comment]
I have intermittent issues but I know mine are down to signal quality and the cameras dropping off the wifi briefly.

**Comment by asemev** [comment]
Thank you both. That must be it. I do have weak wifi outside...

**Comment by asemev** [comment]
I switched the street cam to use LAN cable (and disabled wifi) and now I'm getting ffmpeg errors only on the street cam. And the cam works well with a stable rtsp stream. How can that be? 

![Screenshot_20210112-010107_Chrome](https://user-images.githubusercontent.com/30929896/104252257-e67e3300-5471-11eb-885a-c2db176f32e8.jpg)

**Comment by cybertza** [comment]
I got those errors for two reasons, the camera was the wrong res, so look at the :5000/street video and see what it looks like, or if it cant write read from the cache area.

**Comment by asemev** [comment]
Thank you cybertza. The mjpg feed at :5000 is always working well. Never had issues with that. Now I disabled one of the cameras so I'm down to 2 cams. And now it's working well again. I still do see many ffmep errors but at least I get notifications and recordings. I guess my system cannot handle 3 cameras.

**Comment by cybertza** [comment]
Are you doing the 5fps stream for analysis and direct write for saving, that should, coz you can even analize on 1 fps and have decent results, so have to take advantage of the dual stream design

**Comment by asemev** [comment]
Ok thank you cybertza. Much appreciated.
