### ISSUE TITLE
Allow to record both continuously and on motion with different retentions

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4943]
### New feature

Allow to record both continuously and on motion at the same time with different retentions.

### Use case

For example, I would want to enable 24/7 recording for all my cameras and retain these recordings for 2 days. At the same time, I'd like to retain the _motion_ recordings for 7 days.

**Comment by NickM-27** [comment]
There are only settings for 24/7 and events. There's no way to keep 24/7-all for x days and then 24/7-motion for y days

**Comment by felipecrs** [comment]
That's what I suspected. I think this should be labeled as a feature request/suggestion then. And I think this feature would be really nice to have.

What do you think?

**Comment by NickM-27** [comment]
Seems like a reasonable request. Feel free to edit this template to the other one or just create a new issue. I can update the tags

**Comment by felipecrs** [comment]
Done.

**Comment by NickM-27** [comment]
Just realized this is a duplicate of https://github.com/blakeblackshear/frigate/issues/2590
