### ISSUE TITLE
[Support]: Zone 'None' empty

### ISSUE THREAD

**Issue by Chris18284** [blakeblackshear/frigate#4972]
### Describe the problem you are having

If I select to display zone 'None' only then I get an empty list.

![img](https://user-images.githubusercontent.com/117124485/211290724-8c282cea-edd5-41c7-a9e8-66bb37a3a6e6.png)

### Version

0.12.0-0DBF909

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

**Comment by NickM-27** [comment]
Can you show a screenshot without the zone filter?

**Comment by Chris18284** [comment]
![img](https://user-images.githubusercontent.com/117124485/211342764-fd43c6e4-f149-4097-b570-e1beabbb7135.png)

**Comment by tpjanssen** [comment]
I'm having an issue that's more of less the same. I have a couple of cameras, and one of them has no zones defined. If I set the filter to "None" I would have expected the events of that camera to show up. However, this is not the case, instead an empty list is shown. To show the recordings of this camera I have to enable all zones in the list ("None" included).
