### ISSUE TITLE
[Support]: Recommended USB Hub back powers Host USB Port, preventing Raspberry Pi boot

### ISSUE THREAD

**Issue by jrstarke** [blakeblackshear/frigate#4988]
### Describe the problem you are having

I bought (the recommended USB Hub)[https://github.com/blakeblackshear/frigate/blob/dev/docs/docs/frigate/installation.md?plain=1#L93] for use with the Coral USB. I've noticed a number of times that my raspberry pi wouldn't boot properly, but eventually tracked it down to the USB hub, With the powered USB hub plugged in, it would consistently not boot, but with it not plugged in, it would boot consistently.

I found today in the reviews that there are [a number of other people with the same issue reported in the low reviews](https://www.amazon.ca/Sabrent-Individual-Switches-included-HB-UMP3/product-reviews/B00TPMEOYM/ref=cm_cr_arp_d_viewopt_sr?ie=UTF8&reviewerType=all_reviews&pageNumber=1&filterByKeyword=raspberry&filterByStar=critical), so we should probably put a disclaimer. However, given it's in the Raspberry Pi section, I'm not sure how to address this.

Here's a link to images showing the back powering to the RPi 
https://imgur.com/a/qhRe4Ay

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by jrstarke** [comment]
I also found the HB-UMP3 on [this list of Raspberry Pi USB hubs](https://www.addictedtotech.net/best-powered-usb-hub-for-raspberry-pi-4-in-2021/), specifically calling it out as having a Back Power issue

**Comment by LaurenceGough** [comment]
Depending on what you are running off the Pi you may find it has enough power already (especially the Pi 4).

With a low power SSD I am running that, the USB coral and a zigbee antenna with no issues at all. This is actually running off a Pixel C tablet charger which is a good quality one.

Some SSDs consume a lot more power than others

**Comment by jrstarke** [comment]
I tried [this UGREEN hub](https://www.amazon.ca/dp/B00LLUEJFU) with my raspberry pi, and confirmed that there was no back power applied to the USB port. The Raspberry pi had now issue booting with it.
