### ISSUE TITLE
API to stop object/motion detection

### ISSUE THREAD

**Issue by segator** [blakeblackshear/frigate#499]
used frigate as alarm system when at home we don't need object motioon detected enabled, an API to disable recording/object detection will be nice.

**Comment by rourke750** [comment]
Do you use homeassistant with this?

**Comment by cybertza** [comment]
Dont even know what ver you running, check out the beta 3 readme.

**Comment by segator** [comment]
Yes I running beta3, i already checked readme, there aren't anything to disable by API the object detector.

**Comment by cybertza** [comment]
Would it not be best to just disable your notification? otherwise you may not have recording if something happens?

**Comment by segator** [comment]
I just only want to record when my alarm is enabled, also this also will reduce computer power.

**Comment by cybertza** [comment]
Cool, Have you look at calling a terminal script to stop that docker?

https://community.home-assistant.io/t/unable-to-restart-addon-via-homeassistant-addon-restart-in-automation/165158

Something like that but just with a stop?

**Comment by segator** [comment]
oh  didn't tought on use hassio api to start/stop, good workarround thanks!

**Comment by segator** [comment]
awesome thanks I will try it :)
