### ISSUE TITLE
Handle unavailability of cameras

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#4998]
**Describe what you are trying to accomplish and why in non technical terms**

If some of my cameras becomes unavailable for whatever reasons, poor Wi-Fi, network issues, random crashes, or anything, Frigate does not help much to identify that unless I start to interpret the logs.

**Describe the solution you'd like**

It would be nice if Frigate could handle the unavailability of cameras instead of just treating it as an error. Some things Frigate could do:

1. Display camera unavailable in its UI
2. The Home Assistant integration to turn the entities into unavailable state
   1. This one is cool because I could then use HA's history to figure out how often my cameras becomes unavailable.

**Describe alternatives you've considered**
There is none, I believe.

**Additional context**
The way I see this being implemented is: Frigate injects the stream URL into go2rtc, and go2rtc handle the errors and return some error indicator somehow, like an HTTP status (I don't understand much about RTSP). Frigate then simply handles it.

This would require that restream is always enabled for the camera, and that the restream RTSP is reused for the other roles as mentioned in the documentation. But I think it's an ok compromise.

**Comment by NickM-27** [comment]
> Display camera unavailable in its UI

Frigate already does this

![Screen Shot 2023-01-10 at 07 09 56 AM](https://user-images.githubusercontent.com/14866235/211573368-683cd8cf-8905-4521-bf32-00eda92c10ef.png)

**Comment by NickM-27** [comment]
> The way I see this being implemented is: Frigate injects the stream URL into go2rtc, and go2rtc handle the errors and return some error indicator somehow, like an HTTP status (I don't understand much about RTSP). Frigate then simply handles it.
> 
> This would require that restream is always enabled for the camera, and that the restream RTSP is reused for the other roles as mentioned in the documentation. But I think it's an ok compromise.

I think more info is needed, I don't see why go2rtc would be a part of this feature at all, frigate already knows whether or not the camera is currently sending it a stream or not

**Comment by NickM-27** [comment]
I also think more info is needed on if this request is different than https://github.com/blakeblackshear/frigate/issues/4361

**Comment by felipecrs** [comment]
No, it's probably the same. The only thing not covered then is setting the camera state to unavailable in Home Assistant. Should I open an issue in the integration repository then?

**Comment by NickM-27** [comment]
yes, I think there is enough information available in the existing APIs for the integration to be able to do that
