### ISSUE TITLE
All sensors/cameras become unavailable after restart

### ISSUE THREAD

**Issue by Kurisutian** [blakeblackshear/frigate#500]
**Describe the bug**
When restarting either the addon or the integration or HassOS after an upgrade all my detection sensors and cameras became unavailable. I know that happened before but they eventually came back after I restarted the addon and the integration. But this time they remain unavailable no matter what. It worked fine with the same config until I restarted after the latest HassOS update. 

**Version of frigate**
Frigate NVR Beta version 1.2

**Config file**
Include your full config file wrapped in triple back ticks.
```detectors:
  coral:
    type: edgetpu
    device: 'usb:0'
mqtt:
  host: *mqtt server hostname*
ffmpeg: {}
cameras:
  garden:
    ffmpeg:
      inputs:
        - path: *path to my camera*
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
objects:
  track:
    - person
    - dog
    - cat
    - bird
    - car
    - motorcycle
    - bus
    - truck
    - bicycle

```

**Comment by cybertza** [comment]
Do you have a log file?

**Comment by Kurisutian** [comment]
@cybertza Where do I get the log from?

**Comment by cybertza** [comment]
> @cybertza Where do I get the log from?

Third icon on the top right of the integration page, the the right of the settings

**Comment by Kurisutian** [comment]
> > @cybertza Where do I get the log from?
> 
> Third icon on the top right of the integration page, the the right of the settings

Oh you mean within the addon settings page. I thought there will be more logs somewhere else like in HA itself or some debug URL or anything. 
Well the logs are not very conclusive other than there actually is a Google Coral Drive on USB but it claims not to (using an Intel NUC btw. I read only about RPi having that issue, but it seems to be the same case, right?):

` * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Camera processor started for garten: 33
detector.coral                 INFO    : Starting detection process: 31
frigate.app                    INFO    : Capture process started for garten: 35
frigate.edgetpu                INFO    : Attempting to load TPU as usb:0
frigate.mqtt                   INFO    : MQTT connected
frigate.edgetpu                INFO    : No EdgeTPU detected. Falling back to CPU.`

**Comment by cybertza** [comment]
Are you running in privileged mode?

**Comment by Kurisutian** [comment]
> Are you running in privileged mode?

Not that I know of... I just used the Home Assistant Beta addon and the integration with it. I'm not aware that there is (or was) an option somewhere to choose. Just installed as I did with other addons.

**Comment by cybertza** [comment]
ok, check that this option is correct:
![image](https://user-images.githubusercontent.com/20600538/104202814-11499680-5434-11eb-8d75-1bf803b538a9.png)

**Comment by cybertza** [comment]
In any event, The system being unavailable is most likely due to mqtt not being available when the docker starts up.

It may be in the coders benefit to do a try and repeat statement at that point.

**Comment by Kurisutian** [comment]
OK, that one was enabled but also when it was running previously. I disabled it now according to your recommendation. But why was it working before?

MQTT is running on the same HA device so I can rule that out since nothing would work anymore if that ain't running. ;)

**Comment by Kurisutian** [comment]
I checked the logs from MQTT and it's definitely working:
```
1610378652: New connection from 172.30.32.1 on port 1883.
1610378652: New client connected from 172.30.32.1 as frigate (p2, c1, k60).
1610378694: Saving in-memory database to /data/mosquitto.db.
1610378957: Socket error on client frigate, disconnecting.
1610378962: New connection from 172.30.32.1 on port 1883.
1610378962: New client connected from 172.30.32.1 as frigate (p2, c1, k60).
1610379856: Socket error on client frigate, disconnecting.
1610379860: New connection from 172.30.32.1 on port 1883.
1610379860: New client connected from 172.30.32.1 as frigate (p2, c1, k60).
```

Unchecking the protection mode didn't change anything, same error like above and all sensors/cameras remain unavailable.

**Comment by cybertza** [comment]
https://github.com/blakeblackshear/frigate/blob/444fa45a2c2bd45aa8efa971a72b0a4203d323d5/frigate/app.py#L122 is where it would be addressed if it was an mqtt issue:

From your log above I 
frigate.mqtt                   INFO    : MQTT connected

So i would then assume that according to that it should be working.

But your mqtt log does report:
1610378957: Socket error on client frigate, disconnecting.

I migrated over to the MQTT Server & Webclient that has the HiveMq logo, and havent had issues, not sure why i struggle with the native one, but i have had similar errors with DC's.

This is the MQTT i use at the moment:
https://github.com/hassio-addons/addon-mqtt/blob/master/README.md

Just don't run both at the same time :p

Dont Forget to thumbs up the solution, and close it if it resolved for you.

**Comment by Kurisutian** [comment]
You've pointed me to the right direction. I had to specifically enter the username and password for the MQTT connection. Although I did use the default ones from the Frigate config example which I did locally add to the MQTT config as well to allow connecting, it would not use it unless when I put them explicitly into the config. It now seems to work (also with the mosquitto mqtt server), thanks!
