### ISSUE TITLE
[Support]: Main page loses WS connection, toggle buttons silently fail

### ISSUE THREAD

**Issue by leccelecce** [blakeblackshear/frigate#5000]
### Describe the problem you are having

Client OS: Windows 11
Client Browser: Chrome (latest)
Server: Frigate running via docker-compose on Debian
Network: wired 10Gbps

From time to time, the UI homepage seems to lost the WebSocket connection to the server. This isn't detected, and because the homepage is largely static isn't immediately obvious. However, when you then go to click any toggle buttons (e.g. toggle detect off), they silently fail to do anything, and the below error is logged in Chrome devtools.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/24962424/211585701-96db8c3c-9b98-41d3-843f-ad62f248fc91.png">

I'm not quite sure what causes this, but it would be useful if the front-end had some kind of heartbeat over the websocket connection and could either restart the connection, or highlight the need for a browser refresh.

### Version

0.12-beta2

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Windows

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
fixed by https://github.com/blakeblackshear/frigate/pull/8178
