### ISSUE TITLE
[Support]: Unable to use Frigate integration

### ISSUE THREAD

**Issue by nmcrae85** [blakeblackshear/frigate#5001]
### Describe the problem you are having

Can install the frigate on HA from HACS I get this error

![image](https://user-images.githubusercontent.com/32064932/211601549-8f63f0c8-80b6-4b61-b928-9fd0bcbc8c0a.png)

### Version

latest

### Frigate config file

```yaml
nothing yet
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink

**Comment by NickM-27** [comment]
Please read the docs, the integration does not run frigate it only connects to frigate. You must install frigate in the addon or in a native docker container.
