### ISSUE TITLE
[Config Support]: Invalid Config Errors

### ISSUE THREAD

**Issue by nmcrae85** [blakeblackshear/frigate#5009]
### Describe the problem you are having

Im getting the following error inside the addon term.

### Version

latest

### Frigate config file

```yaml
mqtt: 
  host: 192.168.150.26
  port: 1883  
  
cameras:
  Reolink:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.150.10:554/h264Preview_01_main
        - roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5  
  detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-10 22:34:53] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 521, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 1056, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/fields.py", line 859, in validate
    v, errors = self._validate_mapping_like(v, values, loc, cls)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/fields.py", line 994, in _validate_mapping_like
    value_result, value_errors = self._validate_singleton(v_, values, v_loc, cls)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/fields.py", line 1067, in _validate_singleton
    value, error = field.validate(v, values, loc=loc, cls=cls)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/fields.py", line 857, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/fields.py", line 1074, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/fields.py", line 1121, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/class_validators.py", line 313, in <lambda>
    return lambda cls, v, values, field, config: validator(v)
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 704, in validate
    return cls(**value)
  File "/opt/frigate/frigate/config.py", line 584, in __init__
    if len(config["ffmpeg"]["inputs"]) == 1:
KeyError: 'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Please read the docs on how to setup the yaml config

```yaml
mqtt: 
  host: 192.168.150.26
  port: 1883  
  
cameras:
  Reolink:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.150.10:554/h264Preview_01_main
        - roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5  
  detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

is incorrect and does not match https://docs.frigate.video/guides/getting_started#step-3-add-a-minimal-camera-configuration

```yaml
mqtt:
  host: <ip of your mqtt server>

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp # <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

**Comment by nmcrae85** [comment]
ok ive managed to get it running and started now (via a container).

Why am i seeing this error? Running the latest beta fyi

frigate  | 2023-01-11 21:08:02.020728099  *************************************************************
frigate  | 2023-01-11 21:08:02.020736533  *************************************************************
frigate  | 2023-01-11 21:08:02.020744081  ***    Your config file is not valid!                     ***
frigate  | 2023-01-11 21:08:02.020876878  ***    Please check the docs at                           ***
frigate  | 2023-01-11 21:08:02.020881938  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2023-01-11 21:08:02.020883959  *************************************************************
frigate  | 2023-01-11 21:08:02.020885990  *************************************************************
frigate  | 2023-01-11 21:08:02.020888840  ***    Config Validation Errors                           ***
frigate  | 2023-01-11 21:08:02.020911841  *************************************************************
frigate  | 2023-01-11 21:08:02.020927565  1 validation error for FrigateConfig
frigate  | 2023-01-11 21:08:02.020929762  live
frigate  | 2023-01-11 21:08:02.020931689    extra fields not permitted (type=value_error.extra)
frigate  | 2023-01-11 21:08:02.022228945  Traceback (most recent call last):
frigate  | 2023-01-11 21:08:02.022237130    File "/opt/frigate/frigate/app.py", line 335, in start
frigate  | 2023-01-11 21:08:02.022238973      self.init_config()
frigate  | 2023-01-11 21:08:02.022241041    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate  | 2023-01-11 21:08:02.022242977      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2023-01-11 21:08:02.022245115    File "/opt/frigate/frigate/config.py", line 1020, in parse_file
frigate  | 2023-01-11 21:08:02.022246921      return cls.parse_obj(config)
frigate  | 2023-01-11 21:08:02.022249020    File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
frigate  | 2023-01-11 21:08:02.022256514    File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
frigate  | 2023-01-11 21:08:02.022259132  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
frigate  | 2023-01-11 21:08:02.022261046  live
frigate  | 2023-01-11 21:08:02.022262949    extra fields not permitted (type=value_error.extra)
frigate  | 2023-01-11 21:08:02.022310342  
frigate  | 2023-01-11 21:08:02.022313014  *************************************************************
frigate  | 2023-01-11 21:08:02.022315064  ***    End Config Validation Errors                       ***
frigate  | 2023-01-11 21:08:02.022358585  *************************************************************

**Comment by nmcrae85** [comment]
this is the config

mqtt:

  host: 192.168.150.26
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: **removed**
  password: **removed**
  stats_interval: 300

record:
  expire_interval: 10


timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:1!Tessian@192.168.150.10:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:1!Tessian@192.168.150.10:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - drivewayclose_in
        - driveway_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      drivewayclose_in:
        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
        objects:
          - car
          - person
          - dog
          - cat
          - bicycle
      driveway_whole_area:
        coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
        objects:
          - person
          - cat
          - dog
          - bicycle
    motion:
      mask:
        - 2,465,328,468,330,432,5,431
        - 72,43,154,0,0,0,0,129
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - drivewayclose_in
          - driveway_whole_area
        pre_capture: 5
        post_capture: 15
        
detectors:
  cpu1:
    type: cpu
    num_threads: 3

rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects

live:
  height: 640
  quality: 1

**Comment by NickM-27** [comment]
are you running the beta? It seems like you are

**Comment by nmcrae85** [comment]
yes.

**Comment by NickM-27** [comment]
Then you should read the release notes as this is covered there

**Comment by nmcrae85** [comment]
from here - https://github.com/blakeblackshear/frigate/releases?

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0-beta2

Specifically:

> - live configuration has been moved to restream -> jsmpeg

**Comment by nmcrae85** [comment]
im sorry @NickM-27 - do i need to adjust something in the config? im new to this and trying to learn on the fly

**Comment by NickM-27** [comment]
You need to move 

```yaml
live:
  height: 640
  quality: 1
```

to

```yaml
restream:
  jsmpeg:
    height: 640
    quality: 1
```

**Comment by nmcrae85** [comment]
i still see the errors, is there something else amiss? 

frigate  | 2023-01-11 21:36:11.587897553  [2023-01-11 21:36:11] frigate.app                    INFO    : Starting Frigate (0.12.0-581c259)
frigate  | 2023-01-11 21:36:11.635315181  *************************************************************
frigate  | 2023-01-11 21:36:11.635323869  *************************************************************
frigate  | 2023-01-11 21:36:11.635331707  ***    Your config file is not valid!                     ***
frigate  | 2023-01-11 21:36:11.635335381  ***    Please check the docs at                           ***
frigate  | 2023-01-11 21:36:11.635337833  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2023-01-11 21:36:11.635989540  *************************************************************
frigate  | 2023-01-11 21:36:11.635997791  *************************************************************
frigate  | 2023-01-11 21:36:11.636000032  ***    Config Validation Errors                           ***
frigate  | 2023-01-11 21:36:11.636002190  *************************************************************
frigate  | 2023-01-11 21:36:11.636004404  Camera driveway has restream enabled, but restream is not assigned to an input.
frigate  | 2023-01-11 21:36:11.636628766  Traceback (most recent call last):
frigate  | 2023-01-11 21:36:11.636636839    File "/opt/frigate/frigate/app.py", line 335, in start
frigate  | 2023-01-11 21:36:11.636638847      self.init_config()
frigate  | 2023-01-11 21:36:11.636640981    File "/opt/frigate/frigate/app.py", line 81, in init_config
frigate  | 2023-01-11 21:36:11.636642915      self.config = user_config.runtime_config
frigate  | 2023-01-11 21:36:11.636645122    File "/opt/frigate/frigate/config.py", line 951, in runtime_config
frigate  | 2023-01-11 21:36:11.636646973      verify_config_roles(camera_config)
frigate  | 2023-01-11 21:36:11.636650899    File "/opt/frigate/frigate/config.py", line 742, in verify_config_roles
frigate  | 2023-01-11 21:36:11.636656794      raise ValueError(
frigate  | 2023-01-11 21:36:11.636659155  ValueError: Camera driveway has restream enabled, but restream is not assigned to an input.
frigate  | 2023-01-11 21:36:11.636660874  
frigate  | 2023-01-11 21:36:11.636662892  *************************************************************
frigate  | 2023-01-11 21:36:11.637841704  ***    End Config Validation Errors                       ***
frigate  | 2023-01-11 21:36:11.637850261  *************************************************************

**Comment by NickM-27** [comment]
You need to add the `restream` role to one of your cameras streams for each camera

**Comment by nmcrae85** [comment]
from this 

`cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.150.10:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:1pass@192.168.150.10:554/h264Preview_01_main
          roles:
            - record`

to this 

[cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.150.10:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:pass@192.168.150.10:554/h264Preview_01_main
          roles:
            - record
            - restream](url)

**Comment by NickM-27** [comment]
Correct

**Comment by nmcrae85** [comment]
frigate  | 2023-01-11 21:46:29.275832320  *************************************************************
frigate  | 2023-01-11 21:46:29.275840411  *************************************************************
frigate  | 2023-01-11 21:46:29.275847994  ***    Your config file is not valid!                     ***
frigate  | 2023-01-11 21:46:29.275851456  ***    Please check the docs at                           ***
frigate  | 2023-01-11 21:46:29.275853923  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2023-01-11 21:46:29.275910637  *************************************************************
frigate  | 2023-01-11 21:46:29.275913592  *************************************************************
frigate  | 2023-01-11 21:46:29.275915673  ***    Config Validation Errors                           ***
frigate  | 2023-01-11 21:46:29.275917839  *************************************************************
frigate  | 2023-01-11 21:46:29.275919662  while scanning for the next token
frigate  | 2023-01-11 21:46:29.275921699  found character '\t' that cannot start any token
frigate  | 2023-01-11 21:46:29.275923603    in "<unicode string>", line 34, column 1:
frigate  | 2023-01-11 21:46:29.275926835      			- restream
frigate  | 2023-01-11 21:46:29.275928435      ^
frigate  | 2023-01-11 21:46:29.279353129  Traceback (most recent call last):
frigate  | 2023-01-11 21:46:29.279361764    File "/opt/frigate/frigate/app.py", line 335, in start
frigate  | 2023-01-11 21:46:29.279363828      self.init_config()
frigate  | 2023-01-11 21:46:29.279366023    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate  | 2023-01-11 21:46:29.279368104      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2023-01-11 21:46:29.279370338    File "/opt/frigate/frigate/config.py", line 1016, in parse_file
frigate  | 2023-01-11 21:46:29.279372403      config = load_config_with_no_duplicates(raw_config)
frigate  | 2023-01-11 21:46:29.279374582    File "/opt/frigate/frigate/util.py", line 77, in load_config_with_no_duplicates
frigate  | 2023-01-11 21:46:29.279376643      return yaml.load(raw_config, PreserveDuplicatesLoader)
frigate  | 2023-01-11 21:46:29.279380400    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
frigate  | 2023-01-11 21:46:29.279411119      return loader.get_single_data()
frigate  | 2023-01-11 21:46:29.279414205    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
frigate  | 2023-01-11 21:46:29.279416268      node = self.get_single_node()
frigate  | 2023-01-11 21:46:29.279418615    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
frigate  | 2023-01-11 21:46:29.279431914      document = self.compose_document()
frigate  | 2023-01-11 21:46:29.279435029    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
frigate  | 2023-01-11 21:46:29.279437270      node = self.compose_node(None, None)
frigate  | 2023-01-11 21:46:29.279439699    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  | 2023-01-11 21:46:29.279441780      node = self.compose_mapping_node(anchor)
frigate  | 2023-01-11 21:46:29.279444278    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  | 2023-01-11 21:46:29.279446341      item_value = self.compose_node(node, item_key)
frigate  | 2023-01-11 21:46:29.279459668    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  | 2023-01-11 21:46:29.279462200      node = self.compose_mapping_node(anchor)
frigate  | 2023-01-11 21:46:29.279464694    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  | 2023-01-11 21:46:29.279466865      item_value = self.compose_node(node, item_key)
frigate  | 2023-01-11 21:46:29.279469596    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  | 2023-01-11 21:46:29.279471538      node = self.compose_mapping_node(anchor)
frigate  | 2023-01-11 21:46:29.279473941    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  | 2023-01-11 21:46:29.279490586      item_value = self.compose_node(node, item_key)
frigate  | 2023-01-11 21:46:29.279493557    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  | 2023-01-11 21:46:29.279495437      node = self.compose_mapping_node(anchor)
frigate  | 2023-01-11 21:46:29.279497793    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  | 2023-01-11 21:46:29.279499951      item_value = self.compose_node(node, item_key)
frigate  | 2023-01-11 21:46:29.279502212    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 82, in compose_node
frigate  | 2023-01-11 21:46:29.279504142      node = self.compose_sequence_node(anchor)
frigate  | 2023-01-11 21:46:29.279506566    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
frigate  | 2023-01-11 21:46:29.279508681      node.value.append(self.compose_node(node, index))
frigate  | 2023-01-11 21:46:29.279510999    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  | 2023-01-11 21:46:29.279512916      node = self.compose_mapping_node(anchor)
frigate  | 2023-01-11 21:46:29.279515308    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  | 2023-01-11 21:46:29.279517247      item_value = self.compose_node(node, item_key)
frigate  | 2023-01-11 21:46:29.279534613    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 82, in compose_node
frigate  | 2023-01-11 21:46:29.279537169      node = self.compose_sequence_node(anchor)
frigate  | 2023-01-11 21:46:29.279539565    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
frigate  | 2023-01-11 21:46:29.279541501      while not self.check_event(SequenceEndEvent):
frigate  | 2023-01-11 21:46:29.279543721    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
frigate  | 2023-01-11 21:46:29.279545804      self.current_event = self.state()
frigate  | 2023-01-11 21:46:29.279548296    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
frigate  | 2023-01-11 21:46:29.279550146      if self.check_token(BlockEntryToken):
frigate  | 2023-01-11 21:46:29.279552413    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
frigate  | 2023-01-11 21:46:29.279554157      self.fetch_more_tokens()
frigate  | 2023-01-11 21:46:29.279556539    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 258, in fetch_more_tokens
frigate  | 2023-01-11 21:46:29.279579944      raise ScannerError("while scanning for the next token", None,
frigate  | 2023-01-11 21:46:29.279582670  yaml.scanner.ScannerError: while scanning for the next token
frigate  | 2023-01-11 21:46:29.279584633  found character '\t' that cannot start any token
frigate  | 2023-01-11 21:46:29.279586568    in "<unicode string>", line 34, column 1:
frigate  | 2023-01-11 21:46:29.279588196      			- restream
frigate  | 2023-01-11 21:46:29.279589681      ^
frigate  | 2023-01-11 21:46:29.279591183  
frigate  | 2023-01-11 21:46:29.279593190  *************************************************************
frigate  | 2023-01-11 21:46:29.279595212  ***    End Config Validation Errors                       ***
frigate  | 2023-01-11 21:46:29.279597263  *************************************************************

**Comment by nmcrae85** [comment]
- restream
is that incorrect format?

**Comment by NickM-27** [comment]
You're using tabs, you need to use spaces

**Comment by nmcrae85** [comment]
thanks @NickM-27 - gent and a scholar, schooling a noob like me.

**Comment by nmcrae85** [comment]
@NickM-27 - when i add the second camera. why do i get the live error again?

frigate  | 2023-01-11 22:18:41.419564779  *************************************************************
frigate  | 2023-01-11 22:18:41.419566819  *************************************************************
frigate  | 2023-01-11 22:18:41.419568924  ***    Config Validation Errors                           ***
frigate  | 2023-01-11 22:18:41.419570951  *************************************************************
frigate  | 2023-01-11 22:18:41.420405322  1 validation error for FrigateConfig
frigate  | 2023-01-11 22:18:41.420408410  live
frigate  | 2023-01-11 22:18:41.420410599    extra fields not permitted (type=value_error.extra)
frigate  | 2023-01-11 22:18:41.421827559  Traceback (most recent call last):
frigate  | 2023-01-11 22:18:41.421830893    File "/opt/frigate/frigate/app.py", line 335, in start
frigate  | 2023-01-11 22:18:41.421832757      self.init_config()
frigate  | 2023-01-11 22:18:41.421834894    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate  | 2023-01-11 22:18:41.421836881      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2023-01-11 22:18:41.421839002    File "/opt/frigate/frigate/config.py", line 1020, in parse_file
frigate  | 2023-01-11 22:18:41.421840902      return cls.parse_obj(config)
frigate  | 2023-01-11 22:18:41.421843651    File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
frigate  | 2023-01-11 22:18:41.421847847    File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
frigate  | 2023-01-11 22:18:41.421850283  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
frigate  | 2023-01-11 22:18:41.421852250  live
frigate  | 2023-01-11 22:18:41.421854257    extra fields not permitted (type=value_error.extra)
frigate  | 2023-01-11 22:18:41.421884951  
frigate  | 2023-01-11 22:18:41.421902727  *************************************************************
frigate  | 2023-01-11 22:18:41.421905460  ***    End Config Validation Errors                       ***
frigate  | 2023-01-11 22:18:41.421907547  *************************************************************

**Comment by NickM-27** [comment]
share your new config

**Comment by nmcrae85** [comment]
mqtt:

  host: 192.168.150.26
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: Tessian
  stats_interval: 300

record:
  expire_interval: 10


timestamp_style:
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:1!Tessian@192.168.150.10:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:1!Tessian@192.168.150.10:554/h264Preview_01_main
          roles:
            - record
            - restream
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - drivewayclose_in
        - driveway_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      drivewayclose_in:
        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
        objects:
          - car
          - person
          - dog
          - cat
          - bicycle
      driveway_whole_area:
        coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
        objects:
          - person
          - cat
          - dog
          - bicycle
    motion:
      mask:
        - 2,465,328,468,330,432,5,431
        - 72,43,154,0,0,0,0,129
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - drivewayclose_in
          - driveway_whole_area
        pre_capture: 5
        post_capture: 15

  garden:
    ffmpeg:
      inputs:
        - path: rtsp://admin:1!Tessian@192.168.150.11:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:1!Tessian@192.168.150.11:554/h264Preview_01_main
          roles:
            - record
            - restream
    detect:
      width: 640
      height: 360
      fps: 15
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
      filters:
        car:
          min_area: 15000
        person:
          min_area: 500
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      required_zones:
        - gardenclose_in
        - garden_whole_area
      crop: True
      height: 500
      retain:
        default: 3
    zones:
      gardenclose_in:
        coordinates: 0,480,429,480,443,335,460,173,263,133,88,120,36,212,0,279
        objects:
          - car
          - person
          - dog
          - cat
          - bicycle
      garden_whole_area:
        coordinates: 383,52,497,105,569,316,575,480,261,480,0,480,0,225,148,57
        objects:
          - person
          - cat
          - dog
          - bicycle
    motion:
      mask:
        - 2,465,328,468,330,432,5,431
        - 72,43,154,0,0,0,0,129
    record:
      enabled: True
      retain:
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        required_zones:
          - gardenyclose_in
          - garden_whole_area
        pre_capture: 5
        post_capture: 15

detectors:
  cpu1:
    type: cpu
    num_threads: 3

rtmp:
  enabled: false

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 1
  mode: objects

live:
  height: 640
  quality: 1

**Comment by NickM-27** [comment]
You have at the bottom

```yaml
live:
  height: 640
  quality: 1
```

which is exactly the same as before...

**Comment by nmcrae85** [comment]
restream:
  height: 640
  quality: 1

?

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/issues/5009#issuecomment-1379453461

**Comment by nmcrae85** [comment]
thanks for your help. Do you have a sponsor page? I think I owe you a coffee or 3 :)

**Comment by NickM-27** [comment]
Can this be closed now?

And there's really no need to but if you feel so inclined I do appreciate it https://github.com/sponsors/NickM-27

**Comment by nmcrae85** [comment]
Thanks. Will do
