### ISSUE TITLE
[Config Support]: Help setting up RPi

### ISSUE THREAD

**Issue by eros23** [blakeblackshear/frigate#5026]
### Describe the problem you are having

I tried to do a first install with minimal configuration on my raspberry 4 (4Gb) to test frigate.
I noticed that, during the installation, it has problems with the config folder. If I enter as a local path, /config/, it manages to read the file. While if I enter /config/config.yaml, it gives an error with python.

### Version

I can't see it

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.83
  port: 1883
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
root@raspberrypi:~# docker logs --tail 100 frigate
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-11 19:39:31] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
Starting migrations
[2023-01-11 19:39:31] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-01-11 19:39:31] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 111] Connection refused
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-11 19:39:41] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
Starting migrations
[2023-01-11 19:39:41] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-01-11 19:39:41] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 111] Connection refused
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-11 19:39:51] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
Starting migrations
[2023-01-11 19:39:51] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-01-11 19:39:51] peewee_migrate                 INFO    : There is nothing to migrate
[Errno 111] Connection refused
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
root@raspberrypi:~#
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

This is the code I run from the command line:
`docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  --shm-size=64m \
  -v /media/frigate:/media/frigate \
  -v /config:/config:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='password' \
  -p 5000:5000 \
  -p 1935:1935 \
  blakeblackshear/frigate:stable`
  
  This is output of docker ps -all
  `root@raspberrypi:~# docker ps --all
CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS         PORTS                                                                                  NAMES
221eefe8091e   blakeblackshear/frigate:stable   "/init python3 -u -m…"   About a minute ago   Up 8 seconds   0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   frigate`

This is the output after a few seconds...
`root@raspberrypi:~# docker ps --all
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS                          PORTS     NAMES
221eefe8091e   blakeblackshear/frigate:stable   "/init python3 -u -m…"   7 minutes ago   Restarting (1) 35 seconds ago             frigate`

**Comment by NickM-27** [comment]
The error is `[Errno 111] Connection refused` because it is unable to connect to MQTT, most likely because there is a user/pass setup

**Comment by eros23** [comment]
I actually don't have a mqtt server. Do I need to remove it from the configuration?

But isn't there a minimum configuration to start the web interface?
I wanted to get a little familiar with frigate.

This is what I see the first seconds. Then everything stops.

![Schermata del 2023-01-11 19-56-58](https://user-images.githubusercontent.com/812155/211895226-d5e034f3-1824-46db-be00-550a9362ff3b.png)

**Comment by NickM-27** [comment]
For 0.11 (current stable version) MQTT is required for everything including the web interface, you have also set an IP address for MQTT so naturally it expects it to be there. In frigate 0.12 (currently in beta) MQTT is optional

**Comment by eros23** [comment]
Ok, I was able to start it after installing a mqtt server. If I can give you some advice, write two simple commands in the guide to be clear. Thank you so much for the work you do
![Schermata del 2023-01-11 20-24-33](https://user-images.githubusercontent.com/812155/211899133-c249b061-d634-411d-8e76-007ddefd87fc.png)

**Comment by eros23** [comment]
Now I have this problem with ffmpeg.

LOG:
`[2023-01-11 20:26:54] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2023-01-11 20:26:54] ffmpeg.back.detect             ERROR   : [rtsp @ 0x677f00] Unable to open RTSP for listening
[2023-01-11 20:26:54] ffmpeg.back.detect             ERROR   : rtsp://192.168.0.82:554/user=admin&password=&channel=1&stream=0.sdp?: Cannot assign requested address
[2023-01-11 20:26:55] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
[2023-01-11 20:26:55] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...
`

**Comment by NickM-27** [comment]
This is covered at the very top of the installation docs that MQTT is required

![Screenshot_20230111_123124_Chrome Beta.jpg](https://user-images.githubusercontent.com/14866235/211900526-d800bf4b-9b4d-4a40-8a1d-6b3b3b5b35e8.jpg)

**Comment by NickM-27** [comment]
Are you running on a 32bit pi?

**Comment by eros23** [comment]
yes

**Comment by NickM-27** [comment]
You'll need to set the args manually as there's an issue with 32 bit arm. 

```
ffmpeg:
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
```

**Comment by eros23** [comment]
With the raspberry 4 - 32bit, it gave me this error, also setting the configuration you gave me.

`[2023-01-12 21:36:40] watchdog.back                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2023-01-12 21:36:40] ffmpeg.back.detect             ERROR   : [rtsp @ 0x679f00] Unable to open RTSP for listening
[2023-01-12 21:36:40] ffmpeg.back.detect             ERROR   : rtsp://192.168.0.82:554/user=admin&password=&channel=1&stream=0.sdp?: Cannot assign requested address
[2023-01-12 21:36:41] frigate.video                  ERROR   : back: Unable to read frames from ffmpeg process.
[2023-01-12 21:36:41] frigate.video                  ERROR   : back: ffmpeg process is not running. exiting capture thread...
`

I replaced ffmpeg with ffmpeg-armhf static:
https://johnvansickle.com/ffmpeg/

and now everything works fine.
![Schermata del 2023-01-12 21-44-33](https://user-images.githubusercontent.com/812155/212177090-7bc4c4c9-06ac-4ceb-ad03-fc96a214e1b1.png)

**Comment by NickM-27** [comment]
Okay thanks, we've already changed everything related to this for the upcoming version so it should be fixed when that comes out. For now seems this can be closed, feel free to create a new issue if something else come up.
