### ISSUE TITLE
[Support]: Cannot load HA integration when using frigate proxy

### ISSUE THREAD

**Issue by nickrout** [blakeblackshear/frigate#5030]
### Describe the problem you are having

I have frigate set up and running on a box (nuccy.lan) that is separate from the box running HA (hass.lan). Frigate's UI is accessible both by accessing it from a web browser pointed at  nuccy.lan:5000 and via HA using the frigate proxy addon.

I am now trying to set up the HA integration. I go to Settings|Devices and Services/Add Integration/Frigate, which then asks me for the url for frigate, and I enter http://ccab4aaf-frigate-proxy:5000. However it returns "! Failed to connect"

![image](https://user-images.githubusercontent.com/5105631/211969956-e3e7dfd5-1d33-43de-90fd-9529b345140b.png)

From the log below you can see I also tried http://ccab4aaf-frigate:5000 and http://ccab4aaf-frigate-proxy.local.hass.io:5000
 

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
I am not sure this is relevant given that Frigate is running. It is the integration that won't work.
```

### Relevant log output

```shell
From HA
This error originated from a custom integration.

Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:51
Integration: Frigate (documentation, issues)
First occurred: 4:06:22 PM (8 occurrences)
Last logged: 4:35:11 PM

Error fetching information from http://ccab4aaf-frigate-proxy:5000/api/stats: 403, message='Forbidden', url=URL('http://ccab4aaf-frigate-proxy:5000/api/stats')
Error fetching information from http://hass.lan:8123/ccab4aaf_frigate-proxy/api/stats: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('http://hass.lan:8123/ccab4aaf_frigate-proxy/api/stats')
Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name does not resolve]
Error fetching information from http://ccab4aaf-frigate-proxy.local.hass.io:5000/api/stats: 403, message='Forbidden', url=URL('http://ccab4aaf-frigate-proxy.local.hass.io:5000/api/stats')
```

### FFprobe output from your camera

```shell
Frigate is working.
```

### Frigate stats

```json
{"detection_fps":14.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":12.16,"pid":216}},"drive":{"camera_fps":5.1,"capture_pid":230,"detection_fps":5.1,"pid":221,"process_fps":5.1,"skipped_fps":0.0},"foyer":{"camera_fps":5.1,"capture_pid":235,"detection_fps":1.1,"pid":228,"process_fps":5.1,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":61.5,"mount_type":"tmpfs","total":67.1,"used":5.6},"/media/frigate/clips":{"free":67275.8,"mount_type":"ext4","total":117018.1,"used":43750.8},"/media/frigate/recordings":{"free":67275.8,"mount_type":"ext4","total":117018.1,"used":43750.8},"/tmp/cache":{"free":1000.0,"mount_type":"tmpfs","total":1000.0,"used":0.0}},"temperatures":{},"uptime":260984,"version":"0.11.1-2eada21"},"view":{"camera_fps":5.1,"capture_pid":231,"detection_fps":8.0,"pid":226,"process_fps":5.1,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hik vision

**Comment by nickrout** [comment]
Forgot to say, the Integration Version is 3.0.0, and I have had frigate integration working via the addon on the same host as HA.

**Comment by NickM-27** [comment]
I don't think that is supported, it is not [listed in the docs](https://docs.frigate.video/integrations/home-assistant#configuration). You should just use the IP of the device running frigate with port 5000

**Comment by nickrout** [comment]
Thanks for the extremely quick reply. I thought I had tried that (unsuccessfully) too, but I just did again, and lo and behold it worked.
