### ISSUE TITLE
[Support]: Docker image in docs still references Docker Hub

### ISSUE THREAD

**Issue by geerlingguy** [blakeblackshear/frigate#5046]
### Describe the problem you are having

I was setting this up today, and I noticed in the docs (https://docs.frigate.video/frigate/installation), the suggested `docker-compose.yml` configuration still points to `image: blakeblackshear/frigate:stable`, which is coming from https://hub.docker.com/r/blakeblackshear/frigate

I went to Docker Hub to check out the image, and I found at the top of that repository:

> NOTICE: This repository is no longer being updated
> 
> Latest images can be found on ghcr instead: https://github.com/blakeblackshear/frigate/pkgs/container/frigate

So I went over to ghcr, but I don't see an easy way to just get a `stable` release... the top of that page shows the following:

```
docker pull ghcr.io/blakeblackshear/frigate:0.12.0-beta3-tensorrt
```

In fact, looking through all four pages of tagged releases, there are none tagged 'stable' on ghcr: https://github.com/blakeblackshear/frigate/pkgs/container/frigate/versions?filters%5Bversion_type%5D=tagged&page=4

Did I just happen to come in during a transition period where the docs are not yet up to date? This was confusing to me as I want to use `stable` and not pin to a dev release in my setup.

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
Yes, for the latest version (0.12) which is in beta we have decided to move to GHCR only. At this point to get a stable build you should use dockerhub, once 0.12 is released you'll need to switch to ghcr images. 

We can probably get the image from dockerhub over to GHCR so there is a stable tag but will have to see.

**Comment by NickM-27** [comment]
actually looks like the dockerhub page says this is starting with version 0.12 so I think that makes sense.
