### ISSUE TITLE
Patch internal NVIDIA drivers to increase maximum simultaneous transcodes

### ISSUE THREAD

**Issue by ErroneousBosch** [blakeblackshear/frigate#5055]
**Describe what you are trying to accomplish and why in non technical terms**
NVIDIA softlocks the NVENC engine on Linux to limit the number of simultaneous transcodes. Luckily there is a patch that removes this limit:

https://github.com/keylase/nvidia-patch

**Describe the solution you'd like**
Apply the patch as part of container startup

**Describe alternatives you've considered**
I have my host system patched, but it seems the container may also need it, as one stream is hitting my CPU

**Additional context**
none

**Comment by NickM-27** [comment]
Looks like the patch requires to match the version of the driver the user has installed on the host, seems like that would be pretty complicated to do

**Comment by dennispg** [comment]
I don't think that is true, you just run the `patch.sh` script from there and it will handle for the installed driver version for you. However, I'm not so sure that building this into the frigate container is a great idea. I think what would be better, and more general, is to implement a mod system like how linuxserver.io containers do. See here: [https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers)

Then users can manage modding however they like.

**Comment by NickM-27** [comment]
> I don't think that is true, you just run the `patch.sh` script from there and it will handle for the installed driver version for you. 

Thanks, only looked briefly and didn't see that.

> However, I'm not so sure that building this into the frigate container is a great idea. I think what would be better, and more general, is to implement a mod system like how linuxserver.io containers do. See here: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
> 
> Then users can manage modding however they like.

Yeah, I think that would make more sense

**Comment by dennispg** [comment]
> I have my host system patched, but it seems the container may also need it, as one stream is hitting my CPU

@ErroneousBosch Looking at it again, it should just work if your host system is already patched and you are using the `nvidia-container-runtime`. I do not think that patching it again inside the container will change much for you.. I suspect you have something else going on.

**Comment by ErroneousBosch** [comment]
Alright, figured I would ask. No worries.

**Comment by ErroneousBosch** [comment]
I figured out where the CPU spike is coming from: I have to scale for the detect stream on one of my cameras. I can see you are already adding in HW accelerated scaling on 0.12, so once that drops as stable, upgrading to that should solve my issue.

Thanks for all of your fantastic work and responsiveness!
