### ISSUE TITLE
0.12.0-0DBF909 - Change "Storage" sizes shown under storage menu to GB

### ISSUE THREAD

**Issue by tubalainen** [blakeblackshear/frigate#5069]
**Describe what you are trying to accomplish and why in non technical terms**
Be able to correlate the figures show to real values without having to do math. 

**Describe the solution you'd like**
Show all MB numbers in GB instead.

**Describe alternatives you've considered**
Live with MB - this is not a dealbreaker. :)

**Additional context**
![image](https://user-images.githubusercontent.com/26795429/212345187-0d91d294-d497-4027-90d3-389ff3d858b1.png)

**Comment by leccelecce** [comment]
An alternative option would be to comma-separate the values I.e. 1,715,234 which improves readability
