### ISSUE TITLE
How do you edit coco labels.txt in HassOS addon?

### ISSUE THREAD

**Issue by Eeeeeediot** [blakeblackshear/frigate#507]
Hey,

I downloaded it as per docs but it doesnt say how to import it into the addon.

Thanks

**Comment by blakeblackshear** [comment]
This isn't possible with the addon unfortunately. I can look into it for future versions.

**Comment by Eeeeeediot** [comment]
> This isn't possible with the addon unfortunately. I can look into it for future versions.

Yes please, my cat is everything but a cat at this point!

**Comment by Eeeeeediot** [comment]
don't know what 'stale' means but please don't forget about this!

**Comment by jmadden91** [comment]
Just bumping this. Looks like release 0.9.0 will fix it.
