### ISSUE TITLE
[Config Support]: Unable to edit config from WebUI due to permissions error

### ISSUE THREAD

**Issue by SpartacusIam** [blakeblackshear/frigate#5073]
### Describe the problem you are having

When I try to edit the config in the WebUI I receive the following error:

`Could not write config file, be sure that frigate has write permission on the config file.`

### Version

0.12.0-CF2466C

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

The user running my docker containers has full read/write access to the config file in the OS.  So not sure what permissions issue could be causing this.

**Comment by NickM-27** [comment]
Show your docker compose file

**Comment by SpartacusIam** [comment]
> Show your docker compose file

`  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta3
    restart: unless-stopped
    privileged: true
    env_file:
      - ./.frigate.env
    ports:
      - 5000:5000
      - 1935:1935
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ${APPDATA}/frigate/config.yml:/config/config.yml:ro
      - /mnt/data/nvme01/nvr:/media/frigate
      - /mnt/data/hdd01/nvr/recordings:/media/frigate/recordings
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    shm_size: "496mb" # update for your cameras based on calculation above
    depends_on:
      - hass
      - mqtt`

And inside .frigate.env is the following:

```
FRIGATE_RTSP_PASSWORD=""
FRIGATE_MQTT_PASSWORD=""
```

**Comment by NickM-27** [comment]
As is covered in the release notes you need to remove the `:ro` directive which tells docker to mount that file as read only

`${APPDATA}/frigate/config.yml:/config/config.yml:ro`

**Comment by SpartacusIam** [comment]
> As is covered in the release notes you need to remove the `:ro` directive which tells docker to mount that file as read only
> 
> `${APPDATA}/frigate/config.yml:/config/config.yml:ro`

wow I can't believe I missed the :ro on that mount.  I sincerely apologize.

**Comment by NickM-27** [comment]
No problem, feel free to create a new issue if something else comes up 👍
