### ISSUE TITLE
Request: Enable support for MSE on iPadOS Safari (Frigate 0.12)

### ISSUE THREAD

**Issue by roger-** [blakeblackshear/frigate#5077]
According to [this page](https://caniuse.com/mediasource), MSE should be supported on iPadOS 13+, but currently Frigate gives a message about MSE not being supported on iOS devices.

**Comment by NickM-27** [comment]
Oof, not sure what a good way to detect if it's iPhone or iPad is, will have to do some looking

**Comment by roger-** [comment]
Looks like it's tricky. Maybe just remove the check entirely?

**Comment by NickM-27** [comment]
> Looks like it's tricky. Maybe just remove the check entirely?

Then iOS users will be making issues asking why MSE doesn't work

**Comment by roger-** [comment]
Should have been clearer: I mean not check for iPadOS (which doesn't seem to be possible) but check for MSE support directly. I see some examples [here](https://web.dev/media-mse-basics/).

**Comment by roger-** [comment]
Works, thanks!
