### ISSUE TITLE
Expose AMD HW Acceleration env variable in the config for supervised installs 

### ISSUE THREAD

**Issue by lawrence-jeff** [blakeblackshear/frigate#509]
Running the .80 beta 3 on an AMD CPU with embedded graphics. I see in the config AMD hardware acceleration is supported but can't seem to add the environment variable the docs call out to the container on a supervised install (Debian 10 Supervised install using the official support)

Can this be added into the configuration so you don't have to manually edit things? Or can a pointer be provided to clarify where the container details are stored in a supervised install?

Would greatly appreciate any help

**Comment by blakeblackshear** [comment]
This should be resolved in RC1

**Comment by lawrence-jeff** [comment]
Thank you - working great
