### ISSUE TITLE
[Support]: 0.12.0 beta 3 storage stats question

### ISSUE THREAD

**Issue by RexWheeler** [blakeblackshear/frigate#5102]
### Describe the problem you are having

On the new storage stats screen (very cool BTW, thanks!), there are usage percentage numbers per camera. I am trying to figure out how they are calculated and I am thinking that they may not be correct in my environment.

In my environment I have the video storage mounted on a NFS share and mapped to my container. The NFS share has a quota of 3TB, which appears to align with the "Total MB" stat. the "Used MB" stat is reasonably close to what "du" reports on the file system. Based on these stats about 82% of my disk storage is in use. 

The percentages of the camera stats only add up to 20%. I would either expect them to add up to either 100% (to show how the used space is allocated) or to 82% (to match the overall space used out of what is available). 

Are the percentages reported wrong in my environment, or do they mean something else that I don't understand?

As a side note, I would find per camera stats on how much space was being consumed by both recordings and snapshots useful in order to help me tune my retention settings. Having columns on each camera card for Percentage of total available space used, MB used by video, MB used by snapshots, Bandwidth would be nice (two more stats than we currently have).

![Screenshot 2023-01-15 133741](https://user-images.githubusercontent.com/6587943/212568620-1347378f-b555-4a37-9bdf-73f90439b44b.jpg)

### Version

0.12.0-cf2466c

### Frigate config file

```yaml
record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
snapshots:
  enabled: True
  timestamp: False
  bounding_box: true
  retain:
    default: 90
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Various

**Comment by NickM-27** [comment]
The storage stats are based on the amount of storage the camera segments add up to relative to the total available storage on that drive. However, these stats only started being kept for 0.12 so any recordings segments from 0.11 do not count towards this %

**Comment by RexWheeler** [comment]
@NickM-27 Thanks, that answer make sense :-)

In my case I am recording 24/7 for a week, keeping events for a month, and snapshots for 3 months. This means that the stats will take a month to become mostly accurate (or three months to be really accurate, if I care about the size of the small snapshot images). - Not a complaint, rather an observation that folks upgrading should be aware of.

Any thoughts on adding storage size numbers to the stats (instead of just percentages)? Should I put in a separate feature request for that? If there isn't interest in adding size numbers, what about adding one or more digits of precision to the percentage value? I ask because 1% of 3TB is 30GB, which would be the closest size granularity I can calculate by just multiplying the percentage used by my storage size.

**Comment by NickM-27** [comment]
I would make a separate request for that, probably makes sense to put an exact number there too
