### ISSUE TITLE
[FR] Add "/events/<id>/best.jpg" endpoint

### ISSUE THREAD

**Issue by InToSSH** [blakeblackshear/frigate#511]
Hi,
I would like to ask for a favor, if it's possible to add this endpoint: `/events/<id>/best.jpg`

Currently the `/events/<id>/snapshot.jpg` show the latest image (while event in progress, as well as after it ended)

This means that when I am sending a notification it doesn't necesarily have the best image possible. It would be nice if this new endpoint could show best image while the event is in progress (replacing this image only if the next reported score of the same event is higher) and of course even after it ended.

I noticed this while looking at the notifications, the image I received has score of 59%, but I set my threshold (in Node-Red automation) to 70%, looking at the logs I can see that the score indeed went above 70% for two event updates, then went down to 59%, but before the notification was processed, it was too late and grabbed the 59% image from the `snapshot.jpg` endpoint.

Thank you

**Comment by blakeblackshear** [comment]
It does provide the best image, but the definition of best has changed from previous versions. It looks at more than the score to determine if a better image is available. It looks at whether or not the object is larger, how long it has been, and whether or not it is partially outside the frame in addition to the score.

**Comment by InToSSH** [comment]
Thank you for the explanation,  that makes sense and is much better. You are right that the previous 76% score had only 364 area, and the 59% has 435 area.

And one more question, the `top_score` is same as the Computed score as you explained in the Reducing False Positives section in README? I see it seems averaged somehow.

I am trying to figure out how to best calculate the score (to be good enough) for notifications automation I made in Node-Red, which works with Telegram, allowing to get a snapshot with "Get Video" button to request a video for each snapshot. (Posted [#476](https://github.com/blakeblackshear/frigate/issues/476#issuecomment-758734230))

Now as you explained how the score works maybe I don't even need to check the events mqtt stream, calculate the best score and then send snapshot. I could just listen to the snapshot camera update from your integration, which should already have the best one even during the event (I don't want to wait for the end of event. When there is no better score/snapshot for 5 seconds it will send notification even before end).

Thank you, I appreciate your work, it works flawlessly.

**Comment by blakeblackshear** [comment]
`top_score` is the top computed score over the life of the tracked object.
