### ISSUE TITLE
Add specific per camera storage usage to storage screen

### ISSUE THREAD

**Issue by RexWheeler** [blakeblackshear/frigate#5120]
I want to be able to better understand and manage the storage space used by each camera. 

While the new storage screen is a great start, it doesn't give detailed enough data on how much storage a camera is using. It currently displays a whole number percentage value based on the total storage available. In order to know how much space a camera is using, I need to multiply the percentage value by the total storage available (which is also displayed on the screen). The issue is that the percentages are rounded to whole numbers. In my case I have 3TB of storage allocated so each percentage is equivalent to 30GB, meaning that I can only know within 30GB how much space a camera is using. I would like the data to be more granular (and I would prefer not to have to math in my head when looking at the screen.)

Instead I would like to see the actual storage used for each camera. Ideally this would also be broken down by the storage used for video and for snapshots. Bonus points for including the number of events currently known for the camera (making calculation of storage used per event easy to calculate and providing an idea as to how "busy" the camera is.)

So currently on a per camera basis we have two stats:

Usage: xx%
Stream Bandwidth: xxxx.xx MB/hr

I would like to see

Usage: xx%
Video Storage: x,xxx MB
Snapshot Storage: x,xxx MB
Events: x,xxx
Stream Bandwidth: x,xxx MB/hr

**Comment by NickM-27** [comment]
Snapshot storage won't really be doable, that information is not saved in the DB and would require reading the file system for each file which would spin up drives.
