### ISSUE TITLE
[Question] Type of Model and Inference Speeds on Coral

### ISSUE THREAD

**Issue by arsenal-2004** [blakeblackshear/frigate#513]
Hello, thank you for the great work.
I wanted to ask you what kind of model you are using, since I have had issues getting YOLOv4 compiled for the Edge TPU.
Also, what kind of inference speeds do you get for the detection phase?

**Comment by blakeblackshear** [comment]
I'm using the mobiledet model. Speed is ~10ms.

**Comment by arsenal-2004** [comment]
Oh, that's great. Thank you
