### ISSUE TITLE
View object bounding boxes in snapshot also for events in progress

### ISSUE THREAD

**Issue by jmtatsch** [blakeblackshear/frigate#5136]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to deal with false positives and see where they occur.
Right now I have to wait several hours until the event ends naturally to be able to see where the object was located that triggered the (false positive event)

**Describe the solution you'd like**
I would like to see the initial bounding box that triggered the event in the snapshot view just like it would be viewed after the event has ended.

**Comment by miczlo** [comment]
Would be lovely if it was possible to rerun an event with debug detection to see live the bounding boxes, labels etc.

**Comment by blakeblackshear** [comment]
You can rerun frigate on video as described here: https://github.com/blakeblackshear/frigate/issues/4841#issuecomment-1368997143
