### ISSUE TITLE
[Config Support]: go2rtc exec:ffmpeg streams {output} parsing

### ISSUE THREAD

**Issue by dspalu32** [blakeblackshear/frigate#5160]
### Describe the problem you are having

Beginning with 0.12.0 Beta 5, the {output} substitution in go2rtc [exec:ffmpeg streams](https://github.com/AlexxIT/go2rtc#source-exec) is seemingly being parsed by [docker/rootfs/usr/local/go2rtc/create_config.py](https://github.com/blakeblackshear/frigate/commit/19afb035ffac957c1e469f43efc40babea8ff5ba#diff-5c13c143f743dc6c80e9d9e5b5930f4f180b9306ab4ac3e357cbc2899847598f) rather than being passed through to go2rtc.

This worked OK on 0.12.0 Beta 4.

I've tried escaping the {output} as \{output\} and \u007boutput\u007d

### Version

0.12.0 Beta 5 (0.12.0-12d51d3)

### Frigate config file

```yaml
go2rtc:
    drive: exec:ffmpeg <options> -i rtsp://cam-drive.lan -vcodec copy -acodec copy -f rtsp {output}
```

### Relevant log output

```shell
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/go2rtc/create_config.py", line 59, in <module>
frigate  |     go2rtc_config["streams"][name] = go2rtc_config["streams"][name].format(**FRIGATE_ENV_VARS)
frigate  | KeyError: 'output'
frigate  | Service go2rtc exited with code 1 (by signal 0)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by giedriuskilcauskas** [comment]
Aren't you missing `streams:` part between `go2rtc:` and `drive:`

**Comment by dspalu32** [comment]
@giedriuskilcauskas, yes well spotted. Thanks. Sorry, I just cut too much out when pasting the small section from my config. I wanted to show the line as being within gortc and streams, but forgot to paste the latter.

The issue seems specifically within the Frigate create_config.py parser. It doesn't allow curly braces to pass through to go2rtc, as needed for the exec:ffmpeg output token. I use this to apply some odd input and output directives to an XM camera: e.g. rewriting DAR for 16:9 on a substream. @NickM-27

**Comment by NickM-27** [comment]
Can you try using two? `{{output}}`

**Comment by dspalu32** [comment]
Yes, using two works, thanks: {{output}}

I've just learnt something new.
