### ISSUE TITLE
[Support]: documentation website on iOS not usable

### ISSUE THREAD

**Issue by MansM** [blakeblackshear/frigate#5177]
### Describe the problem you are having

On the desktop you would have on the left all menu items which you can use to navigate through documentation. On iOS in the browser you are limited to only go to the next item.

### Version

N/a

### Frigate config file

```yaml
N/a
```

### Relevant log output

```shell
N/a
```

### FFprobe output from your camera

```shell
N/a
```

### Frigate stats

```json
N/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/a

**Comment by NickM-27** [comment]
You just use the navigation on the bottom right

![image](https://user-images.githubusercontent.com/14866235/213871066-4d7ca9eb-f693-4f98-bcf0-a060e6e11b54.jpeg)

![image](https://user-images.githubusercontent.com/14866235/213871071-142d1df7-72cf-4f16-bebf-19afca339462.png)

**Comment by MansM** [comment]
Ah, guess my right thumb was blocking that from view as I use it for scrolling

**Comment by NickM-27** [comment]
In any case, the next version of frigate (currently in beta) has updated docs dependencies which moves the top left button to the expected functionality.
