### ISSUE TITLE
MQTT question

### ISSUE THREAD

**Issue by mjalindahl** [blakeblackshear/frigate#5188]
### Describe the problem you are having

With the Before/After and False Positive entries on an Event, which is the best one to use for an actionable function on MQTT?

I’m currently using False Positive=false and After, but is Before better for faster alerts? Is a person guaranteed to be a person even with Before, and I just use the Confidence level?

Thanks!

### Version

12.04

### Frigate config file

```yaml
Not needed
```

### Relevant log output

```shell
Not needed
```

### FFprobe output from your camera

```shell
Not needed
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

All sorts

**Comment by NickM-27** [comment]
It just depends on what you're trying to check. Before is just the message that was previously after. If you want to be notified when something happens use after, if you want to be notified when something happens but only when an object never entered a zone previously then use both (for example)

**Comment by mjalindahl** [comment]
Ok, thanks.  I'll stick with After.
