### ISSUE TITLE
Hikvision hardware motion detection

### ISSUE THREAD

**Issue by Gollam** [blakeblackshear/frigate#5243]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use the camera CPU to do the motion detection, so that I can offload this task from the raspberry 4.

**Describe the solution you'd like**
I don't have the knowledge to determine if it is possible or not, this is just an idea that I had. The Hikvision cameras provide a sort of API called ISAPI, and it can provide a state if motion is detected or not. Here is a python lib which Home Assistant uses, to read and process this data: https://github.com/mezz64/pyHik
If the information whether there is motion can be used in Frigate, then maybe the CPU in Raspberry 4 didn't have to do so much work.

**Comment by NickM-27** [comment]
This has been requested before but it's not really feasible. Frigate doesn't just detect IF there's motion but also where exactly the motion happened which is used to run object detection only in those areas. It also uses the motion data with things like masks and motion in previous frames.

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/issues/3485

**Comment by Gollam** [comment]
Thanks for the information, if I can think about a working solution regarding this, I'll let you know.
