### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by Sammy1Am** [blakeblackshear/frigate#5275]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to connect to Frigate using the IPv6 address assigned to its docker container; I'm working on moving all my dockers to IPv6-only (largely as an experiment toward moving to a primarily IPv6-stack on my home LAN), but I'm generally finding that IPv6 has a lot of advantages and I'm trying to use it more.

**Describe the solution you'd like**
IPv6 connections would be possible either out-of-the-box or with some configuration.

**Describe alternatives you've considered**
I have this working currently by bind-mounting my own local `nginx.conf` over Frigate's `/usr/local/nginx/conf/nginx.conf`, and replacing the line `listen 5000;` with `listen [::]:5000;`.  However this means any upstream updates to nginx.conf won't show up in my docker.

**Additional context**
- I see this was mentioned previously in issue #300 , but they didn't mention nginx (and that was a long time ago, so I'm not sure it's the same setup now).
- I tried **adding** a line with `listen [::]:5000;` below the existing `listen` directive, but this made go2rtc upset because of a mismatched origin.  I was able to fix this by adding this the go2rtc configuration section, but this seems less-than ideal:
``` yaml
api:
  origin: "*"
```
- Even if we were able to resolve the origin mismatch issue, I suspect nginx might get grumpy if the system it was on didn't have IPv6 support.  So while I personally think requiring system to at least support IPv6 as localhost isn't too steep, I can understand why some people might disagree, and this would need to be made configurable.

It's also possible I've missed something somewhere else that would enable IPv6 in a more user-configurable way, so I'm happy to be pointed in the right direction there too.

**Comment by NickM-27** [comment]
Looks similar to: https://github.com/blakeblackshear/frigate/pull/3497

I'd make a similar request to go2rtc as I imagine it will need to have its own support added or at least docs put up about it

**Comment by Sammy1Am** [comment]
It does indeed look similar to that one, though based on my (light) testing, just replacing line means IPv4 doesn't work anymore.  ~~You'd need to have both `listen 5000` and `listen [::]:5000` for nginx to respond on both.~~

Actually, it looks like the ideal solution may be replacing the line with `listen [::]:5000 ipv6only=off;` which allows nginx to respond to both IPv4 and IPv6, and doesn't seem to make go2rtc as cranky about origins (or at least doesn't here on my dual stack network, I don't really have the ability at the moment to test this on an IPv4-only network/docker).

As far as go2rtc, I actually think it's working okay already.  I was able to use this on my camera and it seems fine:
```yaml
inputs:
        - path: rtsp://[::1]:8554/frontdoor?video=h264
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://[::1]:8554/frontdoor
          input_args: preset-rtsp-restream
          roles:
            - record
```

And MSE and WebRTC are both still working okay in my browser (with `ipv6only=off` or `ipv6only=on` for nginx).  Though since nearly everything is wrapped by nginx's port 5000, it's maybe less important that IPv4 stuff is happening within the container (i.e. when 127.0.0.1 connections are made to various things).

**Comment by imp1sh** [comment]
How to enable IPv6 for the container? I can't find a solution.

**Comment by Sammy1Am** [comment]
The solution that worked for me was to use my own `nginx.conf` file and replace `listen 5000;` with `listen [::]:5000 ipv6only=off;`.  This enables IPv6 for nginx, which is wrapping Frigate.

Your Docker stack will also need IPv6 enabled, but that's not a question for here.

**Comment by imp1sh** [comment]
Having to manage my own nginx is only a workaround, no solution. It should be configurable either via environment variables or just have better default values like below.

I believe this is best practice in Nginx if you'd like to run dual stack. If I'm not fully mistaken this should also be done for rtmp. 
```
listen 5000;
listen [::]:5000;
[...]
listen 1935;
listen[::]:1935;
```

**Comment by luckylinux** [comment]
I am running CADDY Proxy Server as an Entry Point and SSL/TLS Certificate with Letsencrypt. By default, I run IPv6 ONLY.

I first tried to manually bind-mounting `listen.conf` to `/usr/local/nginx/conf/listen-conf:ro,z` but NGINX would Complain that it was read-only and keep restarting ...

So, based on the [(Incomplete) Guide in the Official Documentation](https://docs.frigate.video/configuration/advanced/#enabling-ipv6), I bind-mounted a modified Version of `listen.gotmpl` instead (as read-only):

```
volumes
  - ~/containers/config/frigate-server/nginx/templates/listen.gotmpl:/usr/local/nginx/templates/listen.gotmpl:ro,z
```

Note that I also needed to use `[::1]` instead of `[::]` otherwise it would NOT work for me.

Not sure why `[::1]` works when I can also see in the Logs some Errors:
```
dial tcp [::1]:5000: connect: connection refused
```

Anyways, here is the complete File for `listen.gotmpl` that (kinda ?) seems to work for now:

```
# intended for internal traffic, not protected by auth
listen 5000;


{{ if not .enabled }}
# intended for external traffic, protected by auth
listen [::1]:8971 ipv6only=off;
{{ else }}
# intended for external traffic, protected by auth
listen [::1]:8971 ipv6only=off ssl;

# intended for internal traffic, not protected by auth
listen [::1]:5000 ipv6only=off;

ssl_certificate /etc/letsencrypt/live/frigate/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/frigate/privkey.pem;

# generated 2024-06-01, Mozilla Guideline v5.7, nginx 1.25.3, OpenSSL 1.1.1w, modern configuration, no OCSP
# https://ssl-config.mozilla.org/#server=nginx&version=1.25.3&config=modern&openssl=1.1.1w&ocsp=false&guideline=5.7
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
ssl_session_tickets off;

# modern configuration
ssl_protocols TLSv1.3;
ssl_prefer_server_ciphers off;

# HSTS (ngx_http_headers_module is required) (63072000 seconds)
add_header Strict-Transport-Security "max-age=63072000" always;

# ACME challenge location
location /.well-known/acme-challenge/ {
    default_type "text/plain";
    root /etc/letsencrypt/www;
}
{{ end }}
```
