### ISSUE TITLE
[FR] Snapshot/thumbnail crop padding

### ISSUE THREAD

**Issue by InToSSH** [blakeblackshear/frigate#529]
Hello,
I went through your PR for beta4 and saw you implemented the snapshots and thumbnails separately, which is awesome. Thank you for that.

If I may have one more request, it would be great when `crop: True` on snapshots and thumbnails if we could add a padding in px to the crop region to make it a bit less cropped (to have higher field of view).

It has happened to me, that when the object is really close (high area), it crops too much and then the label above bounding box (with object type, score and area) is not visible on the snapshot (or in general I would like to see more of the image around the object).
Not sure how much work this would be, but it is definitely a low priority request.. just something nice to have.

Thank you again for your amazing work.

**Comment by blakeblackshear** [comment]
Padding is set to 10% of the size of the object.

**Comment by InToSSH** [comment]
So that means the bigger (closer) the object is, the bigger the padding should be?
Now if the object is far the crop has bigger padding (but I think this is due to the resolution of the snapshot as it doesn't upscale, when the object is smaller in resolution than snapshot size it appears smaller)

But I get a lot of snapshots like this:
![photo_2021-01-14_18-16-22](https://user-images.githubusercontent.com/6452373/104830701-79a7d600-5881-11eb-932a-be081b26d8f8.jpg)

It would be nice if additional crop padding (or bounding box margin) could be configurable - either fixed px or additional percentage, to see more around the object.
This would mean that small objects (that now appear small on the snapshot) would be unaffected (as the additional padding - well in this case it would be a margin around the bounding box would not push the crop further), but big objects which would fill the whole cropped image as shown on the snapshot here and it's bounding box + additional margin would "push" the crop a bit further away from the actual object. I hope it makes sense.

**Comment by mario-tux** [comment]
My request is loosely related to this report: if @blakeblackshear prefer I can open another one.
I'm using the thumbnails for notification on Android smartphones: the option to get the 2:1 aspect ratio is very useful but the black background of the square thumbnail is quiete ugly. It would be possible to get a 2:1 version cropping for the subject sides?

**Comment by blakeblackshear** [comment]
Android will crop it that way for you if you don't pass the parameter.

**Comment by mario-tux** [comment]
> Android will crop it that way for you if you don't pass the parameter.

Yes, I know but in this way the transmitted thumbnail will be a square and my Android phones (all of them?) showing the image in the notification  area will cut/hide the upper-lower parts to show it with 2:1 aspect. I guessed that the specific android option was added to fix this problem. I'm asking to fix it in a "nicer way". :-) I understand that this is not trivial to fix as the thumbnails are stored in the database already cropped.

**Comment by blakeblackshear** [comment]
Yea. That's the issue.

**Comment by mario-tux** [comment]
If a specific option is enabled, Frigate could store a double snapshot (1:1 and 2:1 a.r.) in the database: it would provide the second one if the specific android-option on snapshot requests is provided. This should not worry or create overhead to anyone not interested in this specific kind of snapshots.
