### ISSUE TITLE
implement healthcheck

### ISSUE THREAD

**Issue by billimek** [blakeblackshear/frigate#53]
As a scheduler of a frigate docker container,
I want a healthcheck endpoint,
So that I will know when frigate is ready to start working and serving traffic

---

It would be great if we could have some form of healthcheck/liveness probe, or even something served at the root `/` URL so we will know when it is properly running and ready for use.  As far as I know, the only way for an external entity to see if it's working is to hit the preview URL specific to a camera defined in the configuration.  This doesn't easily allow for a generic check.

**Comment by Draxter** [comment]
I think this needs to be revisited. While being able to monitor the frontend app using a curl healthcheck is useful, I think it's more useful for Frigate to monitor whether ffmpeg process is running, considering it has a tendency of sometimes failing for invalid data while the frontend continues to work fine.

Something along those lines?
```
if ps aux | grep ffmpeg | grep -v grep > /dev/null
then
  exit 0
else
  exit 1
fi
```
