### ISSUE TITLE
[Config Support]: CPU usage MQTT 

### ISSUE THREAD

**Issue by piccer** [blakeblackshear/frigate#5313]
### Describe the problem you are having

Is there any option to stop frigate publishing CPU and MEM usage via MQTT? I don‘t want to stress the broker with these informations.

### Version

0.12-beta5

### Frigate config file

```yaml
Doesn’t matter
```

### Relevant log output

```shell
Doesn‘t matter
```

### Frigate stats

```json
Doesn‘t matter
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

**Comment by NickM-27** [comment]
What do you mean by stress the broker? This information doesn't cause MQTT to update any more often and it's simply a few extra bytes, basically nothing.

**Comment by piccer** [comment]
the reason is: I use the internal mqtt2-server of fhem. It creates readings and fills up the logfile... Of cause I could delete these readings, but I think it would be better not to publish informations, that I dont need. Is this possible?

**Comment by piccer** [comment]
OK, I removed all stats now from readinglist, so I haven't any unwanted events anymore.
