### ISSUE TITLE
[Request] Transcoder for playback

### ISSUE THREAD

**Issue by revenz** [blakeblackshear/frigate#5335]
I want to be able to configure ffmpeg to be used as a transcoder for recording playback

This would allow me to record video sin h265/hevc to save space and my cameras natively support this (many newer cameras support hevc).   And this would then allow me to view the recordings without downloading these.

The only alternatives now are to download the recordings to view them, or to record in h264 instead

If you could point me to the file where playback occurs I could have a stab at implementing this and making a PR for it

**Comment by NickM-27** [comment]
This is already supported using hwaccel args and output args

**Comment by NickM-27** [comment]
Why is h265 playback not working? All recent updates for chrome, edge, etc support h265

**Comment by revenz** [comment]
Doesnt work in firefox.  Also tried chrome/edge on fedora and I couldnt get it to work

**Comment by NickM-27** [comment]
> Doesnt work in firefox.  Also tried chrome/edge on fedora and I couldnt get it to work

That's likely a camera issue or you're not running the latest version of frigate most likely.

**Comment by revenz** [comment]
Running 0.11.1-2eada21
Also hwaccel would require a hardware decoder, my home assistant VM, doesnt have access to one.   would need cpu to transcode on the fly for playback.  How would i achieve this?  happy to downscale in the transcode to improve transcoding speed

**Comment by revenz** [comment]
from this page (where I got the info about h265 playback in a browser not working)
https://docs.frigate.video/configuration/camera_specific/#jpeg-stream-cameras

Under annkee c800 (not the camera im using, a different h265 camera)
``` Unfortunately direct playback of in the browser is not working (yet), but the downloaded clip can be played locally. ```

**Comment by NickM-27** [comment]
> Running 0.11.1-2eada21
> 
> Also hwaccel would require a hardware decoder, my home assistant VM, doesnt have access to one.   would need cpu to transcode on the fly for playback.  How would i achieve this?  happy to downscale in the transcode to improve transcoding speed

Yeah, this would be really complicated to implement given that frigate does playback via HLS so you'd either need to transcode each segment on the fly (playback would take a long time to start)

I'd recommend trying to diagnose why h265 playback isn't working. Maybe the camera has settings to change the h265 mode to be more compatible.

**Comment by NickM-27** [comment]
> from this page (where I got the info about h265 playback in a browser not working)
> 
> https://docs.frigate.video/configuration/camera_specific/#jpeg-stream-cameras
> 
> 
> 
> Under annkee c800 (not the camera im using, a different h265 camera)
> 
> ``` Unfortunately direct playback of in the browser is not working (yet), but the downloaded clip can be played locally. ```
> 
> 

That's outdated from before browser support for h265 was added

**Comment by revenz** [comment]
k, so it works on windows using chrome.

Doesnt work on fedora running firefox or chrome, so environmental issue, so something I should be able to fix somehow.

Will close this request then.

**Comment by revenz** [comment]
actually, I could solve this on the desktop, but using the home assistant app on android also has this issue.   Having the ability to view h265 streams is fairly important.  Anyway to achieve this?

**Comment by NickM-27** [comment]
> actually, I could solve this on the desktop, but using the home assistant app on android also has this issue. Having the ability to view h265 streams is fairly important. Anyway to achieve this?

That will depend on the browser used for webview on the mobile device, I think H265 support on Android chrome is less supportive. My android device is unable to playback h265 in the chrome browser while my Iphone plays it back as expected.

**Comment by revenz** [comment]
aware of that, jsut live in the now, so unless home assistant app changes or android webview changes.  it cant support it.

however, adding transcoding to frigate has more advantages
- support any client
- can adjust bitrate/resolution per client, so if viewing on mobile over the slower network can reduce to say 480p to view the event remotely

**Comment by NickM-27** [comment]
Right, my main point previously was to suggest seeing why h265 wasn't working on desktop. This request is a duplicate of https://github.com/blakeblackshear/frigate/issues/2243

**Comment by revenz** [comment]
no its not.  thats asking to reencode and save the reencode.

this request is transcoding on the fly for playback.  but to keep the original saved file the same.

**Comment by NickM-27** [comment]
> no its not. thats asking to reencode and save the reencode.
> 
> this request is transcoding on the fly for playback. but to keep the original saved file the same.

my bad, misremembered what that request was.

**Comment by clinta** [comment]
Shame to see this closed. Is there any chance that the integration of go2rtc into frigate might make this possible?

HEVC browser support on linux is very hit or miss, depending on your GPU. And I'm also interested in the ability to playback in the homeassistant android app, while keeping my recordings without any transcoding.

**Comment by NickM-27** [comment]
Go2rtc would have nothing to do with this really, ffmpeg is what would be doing the transcoding. 

Android hevc has also gotten better, I have no problems playing back my cameras and they are all set to h.265

This would be very complicated to implement and if none of the devices support hevc anyway then better to just set the camera to h264 or if that's not an option transcode in the beginning. 

There's also another feature request which has been pinned to only transcode recordings that are kept which would make things a bit more efficient.

**Comment by clinta** [comment]
Of course, ffmpeg does the actual transcoding, I thought the magic of go2rtc was negotiating supported codecs with the browser and automatically launching ffmpeg to transcode a stream on demand. I thought maybe with go2rtc integrated and able to handle that complication, that implementation of this feature might be simpler.

If go2rtc can do that negotiation it really should create the best of both worlds. You get to keep the original video as delivered from the camera, devices that can play back h265 will play back without any transcoding. And the server will only transcode when necessary to allow viewing from a device that doesn't support it.

**Comment by Janhouse** [comment]
My particular issue is that I store 1440p recordings but frigate is running far away from the city where the mobile network has some issues with upstream bandwidth so playing back that 1440p is practically impossible. Having a way to transcode on the fly during playback or encoding in multiple resolutions and qualities for storage would be a nice addition.

**Comment by aso824** [comment]
I'd like to add +1 for this feature and kindly ask @NickM-27 to reopen.

In my imagination, I see this feature as additional role like `preview`, so we could set up Frigate like:

```
go2rtc:
  streams:
    camera:
    - rtsp://some_h265_4k_stream
    - "ffmpeg:back#video=h264" # and some downscaling

cameras:
  camera:
    ffmpeg:
      inputs:
      - rtsp://some_h265_4k_stream
        roles:
        - record

      # And our new stream:
      - rtsp://127.0.0.1:8554/camera
        input_args: preset-rtsp-restream
        roles:
        - preview
```

Simple, but elegant for MVP; will solve both H265(+) on Linux problem - which is not solved yet on NVIDIA+Chrome set up, and will be usable also over very slow connections.

It would be ideal if:
- the streams would start only if any preview active, not running all time - no idea if it's already works like this
- we could provide more than one configuration...
- ...which could be selected in preview
- and it could work also for recordings and recorded events

I'm aware that this feature request is pretty big and may target very small audience, so it will land on the bottom of the backlog. But, it would be nice to see this ticket open, so maybe someday it will be done. Also, I could try to tinker with that, but I don't know this codebase at all - but probably I'll try anyway because this lack of support of h265 is real pain when I need to find something on recordings, which are splitted to 1min fragments.

**Comment by NickM-27** [comment]
I don't think this is needed. We already have a preview feature implemented and coming with the next version of frigate that is a low fps and low res easily scrubbable video.

**Comment by muava12** [comment]
> We already have a preview feature implemented

did you mean this config?
```
live:
      stream_name: back_lowres
```

**Comment by NickM-27** [comment]
No, I'm referring to features that are in the upcoming version of frigate

**Comment by UserGalileo** [comment]
> No, I'm referring to features that are in the upcoming version of frigate

With those features and new APIs, do you think it would be feasible for the hass card to playback past events with a lower resolution? I have more or less a similar problem, I record at 1440p but my tablet (Samsung Galaxy Tab A8) cannot play a 1440p video unfortunately (and probably never will?), so there's no way to see the recordings from there. Thanks!
