### ISSUE TITLE
0.8.0 RC1 - Notification thumbnail size

### ISSUE THREAD

**Issue by neonpak** [blakeblackshear/frigate#534]
It looks like it is not possible anymore to set the height of the notification thumbnails. The old height parameter is now applied to the snapshots.

**Comment by blakeblackshear** [comment]
This is intentional. The thumbnails are stored in the database and returned as base64 from the api for the media browser. Making these larger will cause performance issues long term.

**Comment by neonpak** [comment]
Ok, makes sense.
