### ISSUE TITLE
[Support]: Minor issue with System view showing wrong GPU

### ISSUE THREAD

**Issue by jvrobert** [blakeblackshear/frigate#5348]
### Describe the problem you are having

This is a very low priority issue, I think, but I have 2 GPUs - one I use for compreface and one for video decode (because..overkill, that's literally the hostname). Anyway, I have the frigate docker locked to GPU 1 (a T600) and can confirm it's locked to GPU 1 in nvidia-smi output:
![image](https://user-images.githubusercontent.com/2155516/216239852-ed5f44a1-c121-4e4c-9a1f-8bf072d8dc9d.png)

However, the system view shows the other GPU, the 3050:
![image](https://user-images.githubusercontent.com/2155516/216239968-b21bba31-933f-4e53-b4c7-11b5de07c334.png)

### Version

0.12.0-66881EB

### Frigate config file

```yaml
NA/nothing of interest...
```

### Relevant log output

```shell
NA/Nothing of interest.
```

### FFprobe output from your camera

```shell
NA/Nothing of interest
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

various

**Comment by NickM-27** [comment]
Can you run `printenv` and paste the results here? I am not sure if there is a good way to know which GPU was specified for the container.

However, it would also be helpful to see your docker compose because you may just want to set env var `NVIDIA_VISIBLE_DEVICES=1` so that way frigate can't see the other GPU.

**Comment by jvrobert** [comment]
Hey Nick - I was using CUDA_VISIBLE_DEVICES, I also added NVIDIA_VISIBLE_DEVICES as you mentioned and didn't seem to help.
Here's env in container:
NVIDIA_VISIBLE_DEVICES=1
HOSTNAME=cfc5db0d84ad
PWD=/opt/frigate
NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
HOME=/root
S6_LOGGING_SCRIPT=T 1 n0 s10000000 T
CUDA_VISIBLE_DEVICES=1
TERM=xterm
GIDLIST=117
SHLVL=1
PLUS_API_KEY=bb35e169-49ca-4a56-984e-139d5747ab61:b30dee00511160443ffa299043e3225781a7f9f9
PATH=/usr/lib/btbn-ffmpeg/bin:/usr/local/go2rtc/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env


Here's compose snippet (only relevant parts):
frigate:
    privileged: true
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta7
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
....
environment:
      CUDA_VISIBLE_DEVICES: 1
      NVIDIA_VISIBLE_DEVICES: 1
      PLUS_API_KEY: "xxxx"
      GIDLIST: 117

**Comment by NickM-27** [comment]
That's odd, I have no idea how frigate would even be seeing the other GPU in that case

**Comment by jvrobert** [comment]
I put up a quick workaround, https://github.com/blakeblackshear/frigate/pull/5356 - not sure how to link that PR to this issue (or vice-versa).

**Comment by NickM-27** [comment]
Fixed in PR
