### ISSUE TITLE
[Support]:  Home Assistant Warning after upgrade to 2023.2

### ISSUE THREAD

**Issue by ShortPutt** [blakeblackshear/frigate#5354]
### Describe the problem you are having

upgraded to HA 2023.2 and following appeared in log

`2023-02-02 11:57:30.424 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for frigate using this method at custom_components/frigate/__init__.py, line 289: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

### Version

0.10.1-83481af

### Frigate config file

```yaml
shouldn't need this but will send if it helps
```

### Relevant log output

```shell
see above
```

### FFprobe output from your camera

```shell
shouldn't need this but will send if it helps
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Anpviz Model: IPC-D250W-SE

**Comment by NickM-27** [comment]
This has already been fixed https://github.com/blakeblackshear/frigate-hass-integration/issues/421
