### ISSUE TITLE
Restarts are slower in 0.12 betas

### ISSUE THREAD

**Issue by leccelecce** [blakeblackshear/frigate#5368]
### Describe the problem you are having

Rather than continue this in the 0.12 beta discussion threads such as https://github.com/blakeblackshear/frigate/discussions/5329#discussioncomment-4845268 (which get closed with each new beta) I thought an issue was an easier way to track this. I am happy to debug and send a PR for review once understanding the problem a bit more.

The understanding is that pre-0.12, Frigate always was forcefully killed by s6 and so a process being slow to end wasn't visible.

I think a key point here is that slow restarts can have multiple different causes and there may be one or two tweaks required.

Per Blake's request want to focus on graceful cleanup rather than forcibly killing things.

Observations:

1. go2rtc I understand is managed separately via s6 and so isn't a culprit here
2. If I have detect disabled on all cameras, shutdown is reliably < 5 seconds.
3. If I leave detect running, it does seem to take 5-10 seconds for any processes to start closing i.e. all ffmpeg, coral, camera processes are still there. After ~10 seconds most of these disappear, and I'm mainly left with frigate.process:cameraX hanging around. Sometimes frigate.output and ffmpeg processes are also present. This is where the bulk of the delay is as the camera processes can gradually die off over the course of ~30 seconds
4. The last remaining process is usually a frigate.process:cameraX one (see sample ps -ef output below)

![image](https://user-images.githubusercontent.com/24962424/216630790-ca990ce2-c4b3-4328-85b4-b6d1fb5602a0.png)

I will probably add some extra debug logging in a build locally and try and find where the process is sticking. I'm currently suspicious of https://github.com/blakeblackshear/frigate/blob/66881eb89f29dc78c4c4dc1bbea4991b7bf42ef7/frigate/output.py#L99 but will report back with findings.

### Version

0.12.0 betas

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
Does it restart quickly if you turn off detect via the UI and then restart? Or only if detect is disabled in the config?

**Comment by leccelecce** [comment]
The former

**Comment by NickM-27** [comment]
if that's the case, why not just have the shutdown logic turn off detect before it begins shutting down?

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/pull/5371 speeds restarts up for me

**Comment by leccelecce** [comment]
That's awesome, just as I think I've found the underlying cause :-) the stuck `frigate.process:cameraX` processes look like this:

![image](https://user-images.githubusercontent.com/24962424/216668246-b048ec03-9156-4ec4-83ad-6618e1613d1f.png)

Which in my recent dev build is this line:

![image](https://user-images.githubusercontent.com/24962424/216667224-5406bf73-0126-4a85-b68d-160c1af4794f.png)

I'm not going to profess to fully understanding the detection engine front to back but it looks like potentially the camera processor keeps trying to stick events on to the detector processing queue, but as the detector has been stopped they never get processed, so it continually sits there waiting for the 10 second timeout to expire until either it just gets killed outright.

So disabling detection prior to restarts probably solves this because the detect loop just gets exited, but an ideal way would probably be for the camera process to listen for the stop signal and stop trying to put items on to the queue?

**Comment by NickM-27** [comment]
> So disabling detection prior to restarts probably solves this because the detect loop just gets exited, but an ideal way would probably be for the camera process to listen for the stop signal and stop trying to put items on to the queue?

yes, if you find a solution like this I think it would be preferred

**Comment by blakeblackshear** [comment]
This is helpful. I'm pretty far down this path locally, too. There are lots of places to address similar things that I am already fixing.

**Comment by leccelecce** [comment]
This is the conclusion I'm getting to - I'm chasing wait()'s all over the place it seems. I think there are a few timeouts set to 10s across the codebase which have probably always held up restarts but were invisible pre-0.12 and the S6 fix.

In the code I referenced above, if I add a check for the stop event, it seems to improve things from up to 30s down to ~13s. My guess (being new to debugging multi-process Python apps) is that putting the check in stops new items being added to the queue, but if there is _already_ an item on the queue e.g. added just prior to restart being called, that still has to incur the 10s wait before timeout in `result = self.event.wait(timeout=10.0)`

Given this code is right at the heart of Frigate's processing I'm loathe to touch it!

**Comment by leccelecce** [comment]
Another one

![image](https://user-images.githubusercontent.com/24962424/216683143-6670fdfc-3eea-4b24-83a6-7fb7b930255e.png)

**Comment by leccelecce** [comment]
This seems to have made a big difference in line with my local attempts - thanks! Two observations, both of which can be seen in the logs below

1. There are now quite a lot of errors thrown during restarts from frigate.video threads complaining they can't read from ffmpeg. While it's fairly benign it's a bit disconcerting to see the errors, particularly for anyone who monitors their log output
2. I still sometimes get a 10s wait on 1-2 camera processes - looks like still a 10s wait in object_detection

![image](https://user-images.githubusercontent.com/24962424/216767265-8a6ad892-6d36-4438-81ce-b103a50c4bfb.png)

![image](https://user-images.githubusercontent.com/24962424/216767480-46f69fba-9ca2-4aac-9877-a70622db8928.png)

![image](https://user-images.githubusercontent.com/24962424/216767520-73446b2c-192d-4bb7-b9b8-61431e47f5e9.png)

**Comment by blakeblackshear** [comment]
It's probably a race condition somewhere because I set that event immediately when frigate starts to shutdown. It should immediately release the wait, so it shouldn't matter that it's 10s. I will take another look to see if I can figure it out.

**Comment by leccelecce** [comment]
Restarts now taking <3 seconds with no log errors - excellent thank you!
