### ISSUE TITLE
Configure size and quality for Birdseye (camera + frame)

### ISSUE THREAD

**Issue by 2Belette** [blakeblackshear/frigate#5372]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to change the size + the quality for both cameras and Birdseye "frame".
It seems fixed size for both camera and the birdseye (or did I miss something?). I am trying 
```
birdseye:
  enabled: True
  width: xx
  height: xx
  mode: continuous
```
not sure this impact the individual camera quality ? I am unable to see any way to change/increase the size of the "frame" only a small piece of my screen is taken by Birdeseye.

**Describe the solution you'd like**
I would like to have a parameters for size & quality for Birdseye (camera + frame) like the one in live:
```
  height: xx
  quality: 1

```

**Comment by NickM-27** [comment]
Birdseye already has full resolution customization. When you open the birdseye screen it is set to a fixed size and you click it to go fullscreen.

**Comment by 2Belette** [comment]
Thanks, yes, but in my case I have 6 cameras but I have a large black frame in the bottom like I would have 7,8 or 9 cameras (which is not the case).

When I double click to go to fullscreen got the same big black frame at the bottom so big black frames on the left/right.

Any way to "force" to 6 cameras to remove the frame ?

**Comment by NickM-27** [comment]
> Any way to "force" to 6 cameras to remove the frame ?

No, that is how birdseye currently works

**Comment by 2Belette** [comment]
Ok, but is is expected to have this large frame at the bottom?

**Comment by NickM-27** [comment]
> Ok, but is is expected to have this large frame at the bottom?

yes it is expected, birdseye currently works to have cameras in a square. Whether it is a 2x2 square, 3x3 square, etc.

**Comment by 2Belette** [comment]
Got it! perhaps a enhancement to support 2x3 for example
