### ISSUE TITLE
Ability to trigger manual object detection in the frame; respecting masks and zones. 

### ISSUE THREAD

**Issue by roger-** [blakeblackshear/frigate#5376]
I know similar requests have been made for the ability to support external motion detection (e.g. #3485), but how about the simpler ability to just trigger a recording based on mqtt? 

One step further would be the ability to also trigger the object detector over the entire (current) frame.

**Comment by NickM-27** [comment]
this is a duplicate of https://github.com/blakeblackshear/frigate/issues/1063
