### ISSUE TITLE
Request for Addition of H.265 Support Following Chrome Implementation

### ISSUE THREAD

**Issue by JohnLeNerd** [blakeblackshear/frigate#5393]
I would like to express my interest in having H.265 support added to your platform. I understand that this format is now supported by Chrome, and I believe it would be an asset to have this feature available.

I am using several Reolink RLC-810A cameras, and currently, my only option is to downscale to 1440P in order to stream the footage in H.264. Having the ability to utilize the full resolution of the camera would be highly beneficial.

I apologize if this request has already been made in light of H.265 being added to Chrome. If so, please accept my apologies for the repetition.

Thank you for your time and consideration.

Best regards,
John

**Comment by blakeblackshear** [comment]
H265 is already supported in every way possible by Frigate. Support is improving some in the upcoming 0.12 release with the addition of RTSP restreaming instead of RTMP. The limitations are browser related, so requests for support of H265 should be sent to Google, Apple, Firefox, etc.

**Comment by banthungprong** [comment]
I`m using a chromium beta and with that I can play all H265+ streams from my HikVision-Cameras.
https://github.com/RobRich999/Chromium_Clang/releases

**Comment by leccelecce** [comment]
I have Hikvision xxx6G2 cameras working with H265 streams via MSE in Chrome on Windows and Android in 0.12 beta via go2rtc. 

Useful link on the go2rtc docs around codec support: https://github.com/AlexxIT/go2rtc#codecs-madness

**Comment by JohnLeNerd** [comment]
Forgive me, I would like to express my thoughts more elegantly. I had previously mentioned that Google Chrome now supports the H.265 codec, however, I am encountering a challenge in using it with my Reolink camera. Unfortunately, this has resulted in a green screen display. I was hoping to ask if RTSP implementation could potentially resolve this issue. I am humbly open to the possibility that I may have overlooked something and would greatly appreciate any assistance or suggestions in finding a solution.

**Comment by NickM-27** [comment]
> Forgive me, I would like to express my thoughts more elegantly. I had previously mentioned that Google Chrome now supports the H.265 codec, however, I am encountering a challenge in using it with my Reolink camera. Unfortunately, this has resulted in a green screen display. I was hoping to ask if RTSP implementation could potentially resolve this issue. I am humbly open to the possibility that I may have overlooked something and would greatly appreciate any assistance or suggestions in finding a solution.

This issue has nothing to do with chrome supporting h265 or not. You should create a camera support request, answering all the prompts.
