### ISSUE TITLE
HA ingress won't work with static built web ui

### ISSUE THREAD

**Issue by paularmstrong** [blakeblackshear/frigate#541]
Looks like due to Home Assistant changing the pathname / baseUrl of accessing the HTTP web ui, the paths are broken.

eg: HA ingress uses a path like `/api/hassio_ingress/phGvaecS8O1W86zsjRe23F93S-9gU0bQNxv5xjP7ZXs/` and proxies that into the Web UI. Unfortunately, the statically built HTML expects the paths of the JS to be `/js/...`, but that means it's attempting to load from the Home Assistant's root `/js` folder and not the frigate docker container's host:port/path.

Some other solution will be needed, like running another web server that can understand if it's being run with ingress and changing the URLs to the built JS/CSS.

Alternatively, an nginx path could be added for `/homeassistant`, which could then serve a modified HTML file, though this may be just as much work to maintain, but harder to test and verify.

**Comment by paularmstrong** [comment]
Another idea, the Python server could serve the HTML file, but add `<base href="<INGRESS_PATH>" />`. This may be easier than running another HTTP service.

**Comment by blakeblackshear** [comment]
There are established patterns for this in other addons. There are some features to enable dynamic nginx configs during startup that add the required prefix. I think the way ingress works is terrible, and it is all a byproduct of homeassistant rolling their own authentication system that does not conform to standard practices used by the rest of the internet. I really wish they would just implement actual cookie based authentication and a proper proxy instead of using a system account to generate a serverside token dynamically and forcing that to be in the path. They won't even consider it.

**Comment by paularmstrong** [comment]
Another alternative (sorry for spam)... We could actually inject into the webpack config that I added for hashing JS scripts and write the JS straight into the HTML, thus avoiding both caching and all the path issues.

**Comment by blakeblackshear** [comment]
The API calls will still be broken though.

**Comment by paularmstrong** [comment]
🤦🏻

**Comment by paularmstrong** [comment]
> There are established patterns for this in other addons. There are some features to enable dynamic nginx configs during startup that add the required prefix.

Can you point me at one of these examples? I've looked at a bunch but haven't seen anything that looks to be using nginx

**Comment by blakeblackshear** [comment]
I can't find it now. I need to dig in and figure out how it works again.

**Comment by blakeblackshear** [comment]
It is a fairly deep and messy rabbit hole: https://github.com/esphome/esphome/tree/dev/docker/rootfs

What would be the best way to pass a base url to the app for API calls? env.js?

**Comment by paularmstrong** [comment]
Wow that's cumbersome.

> What would be the best way to pass a base url to the app for API calls? env.js?

The environment variable will only be good on the API calls – and must be included during build time. That also won't fix the paths for scripts/css/images/etc. a `<base href="..." />` injected into the HTML at the time of serving the page would handle all cases. That would mean we'd still have to go back to Python (or other) serving the HTML and adding the correct info (https://github.com/blakeblackshear/frigate/issues/541#issuecomment-762535625) I can get to work on that piece today, possibly.

**Comment by blakeblackshear** [comment]
If you can get the `base` tag added and used in the index.html, I can modify the docker build to replace that with the unique addon url at runtime. If not, I was just going to use sed to find and replace src/href in the index.html file. If we can get a way to fix the API calls, I think I can handle the html updates.

**Comment by paularmstrong** [comment]
Sounds good. Adding the `base` tag is simple – Just need to have the JS respect it at startup.

**Comment by pdecat** [comment]
I was hacking on supporting HA ingress on my own too and found there does not seem to be an easy way to make all references to snowpack generated resources relative.

```
diff --git a/web/public/index.html b/web/public/index.html
index fd93173..cc6ace9 100644
--- a/web/public/index.html
+++ b/web/public/index.html
@@ -3,19 +3,19 @@
   <head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1" />
-    <link rel="icon" href="/favicon.ico" />
+    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
     <title>Frigate</title>
-    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
-    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
-    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
-    <link rel="manifest" href="/site.webmanifest" />
-    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#3b82f7" />
+    <link rel="apple-touch-icon" sizes="180x180" href="%PUBLIC_URL%/apple-touch-icon.png" />
+    <link rel="icon" type="image/png" sizes="32x32" href="%PUBLIC_URL%/favicon-32x32.png" />
+    <link rel="icon" type="image/png" sizes="16x16" href="%PUBLIC_URL%/favicon-16x16.png" />
+    <link rel="manifest" href="%PUBLIC_URL%/site.webmanifest" />
+    <link rel="mask-icon" href="%PUBLIC_URL%/safari-pinned-tab.svg" color="#3b82f7" />
     <meta name="msapplication-TileColor" content="#3b82f7" />
     <meta name="theme-color" content="#ff0000" />
   </head>
   <body>
     <div id="root"></div>
     <noscript>You need to enable JavaScript to run this app.</noscript>
-    <script type="module" src="/dist/index.js"></script>
+    <script type="module" src="%PUBLIC_URL%/dist/index.js"></script>
   </body>
 </html>
diff --git a/web/snowpack.config.js b/web/snowpack.config.js
index 613c91f..60240a2 100644
--- a/web/snowpack.config.js
+++ b/web/snowpack.config.js
@@ -26,5 +26,6 @@ module.exports = {
   },
   buildOptions: {
     sourcemap: true,
+    baseUrl: "./",
   },
 };
```

Another solution I was about to evaluate would be to rely on the `X-Ingress-Path` header that HA passes: https://developers.home-assistant.io/docs/add-ons/presentation/#ingress

That header can be used in nginx filters, e.g.:
- https://github.com/ncarr/addon-repository/blob/b33761a21f5f5d2f53cf46ca045d0ff32dbab25b/cups/rootfs/etc/nginx/nginx.conf#L14-L16
- https://github.com/matt-FFFFFF/hassio-addon-teslamate/blob/d544873055382c8509af49fc6270c68319a69f5d/services/nginx/teslamate.conf#L32-L40

**Comment by paularmstrong** [comment]
Those nginx `sub_filter` directives are really cool. I think that would work a whole lot better than my current solution with the `<base href...`, as it's getting pretty cumbersome and requires a bunch of post build optimization against the HTML file that's built.

@blakeblackshear Would you like to go down the direction @pdecat suggests with using the ingress-path header and sub_filters?

**Comment by blakeblackshear** [comment]
Yes! I assumed there was something like that available, but couldn't find an example. I have done things like that in the past. Now we just need a way to pass a base url for the api.

**Comment by pdecat** [comment]
From my testing of HA Ingress, everything (HTML, CSS, JS and API) has to be relative to the same `X-Ingress-Path` (something like http://hassio.local/api/hassio_ingress/somerandomtoken/).

**Comment by paularmstrong** [comment]
Let me know if there's anything I can support with on this. For now, I'll leave it in your court

**Comment by blakeblackshear** [comment]
@paularmstrong I got the sub_filters to work with nginx, but I still need a way to set a prefix for the API calls. I can still use the `sub_filter`, but I need to know what to replace. I can inject a script tag and set a global variable. Let me know if you have a better idea.

**Comment by blakeblackshear** [comment]
here is what I came up with:
```
            sub_filter 'href="/' 'href="$http_x_ingress_path/';
            sub_filter 'url(/' 'url($http_x_ingress_path/';
            sub_filter '"/js/' '"$http_x_ingress_path/js/';
            sub_filter '<body>' '<body><script>window.baseUrl="$http_x_ingress_path";</script>';
```

When coming from ingress, the `<body>` will be replaced with `<body><script>window.baseUrl="/hassio/frigate/token";</script>`. 

When not coming from ingress the `<body>` will be replaced with `<body><script>window.baseUrl="";</script>`.

**Comment by blakeblackshear** [comment]
I think i got it actually. 

```js
export const ApiHost = createContext(import.meta.env.SNOWPACK_PUBLIC_API_HOST || window.baseUrl || '');
```

**Comment by paularmstrong** [comment]
That should work!

**Comment by pdecat** [comment]
Nice!

The only thing not working yet seems to be the video streaming: 

![image](https://user-images.githubusercontent.com/318490/105148131-517ada00-5b02-11eb-9791-2c083299e487.png)

**Comment by blakeblackshear** [comment]
Looks like ingress modifies the content type headers and breaks mjpeg.

**Comment by pdecat** [comment]
There must be some way to do it properly. Before switching to frigate, I used the motioneye add-on which has fully working HA ingress support: https://github.com/hassio-addons/addon-motioneye/commit/ff24879f52ae450712758ce61238977a3e7e266a

**Comment by blakeblackshear** [comment]
Are you sure it was actually using MJPEG?

> motionEye doesn't normally rely on MJPEG streaming to present the live video to the user; it rather uses separate HTTP requests to repeatedly fetch the most recent JPEG for each camera frame

https://github.com/ccrisan/motioneye/wiki/Running-Behind-Nginx#mjpeg-and-nginx

I guess we could fetch latest at some interval ourselves too.

**Comment by blakeblackshear** [comment]
I think we should just update the UI to pull the latest.jpg at an interval. From what I can tell, it's going to take an update from homeassistant to get it to handle multipart content types properly. This is what happens when you try to build your own proxy.

**Comment by pdecat** [comment]
> Are you sure it was actually using MJPEG?

You're right, it isn't. I quickly reinstalled it to check and it does JPEG refreshing.

**Comment by paularmstrong** [comment]
> I think we should just update the UI to pull the latest.jpg at an interval. From what I can tell, it's going to take an update from homeassistant to get it to handle multipart content types properly. This is what happens when you try to build your own proxy.

We can certainly do that, but at the moment we'll need to remove all of the toggles for timestamp, zones, bounding boxes, etc. Or are you considering adding them to the `latest.jpg` endpoint as well?

**Comment by blakeblackshear** [comment]
If they aren't there, we can add them.

**Comment by paularmstrong** [comment]
Ah, looks like they are, I was looking at old docs, I think. I'll work on getting a PR up

**Comment by paularmstrong** [comment]
Created https://github.com/blakeblackshear/frigate/pull/565 to address

**Comment by SamMousa** [comment]
Was randomly reading this issue after having read the recent HA changelog. So if relevant for anyone: https://github.com/home-assistant/core/pull/83425

It seems HA no longer changes the content-type header since 2022.12.6
