### ISSUE TITLE
Can I using Frigate online?

### ISSUE THREAD

**Issue by wangyiwu** [blakeblackshear/frigate#5415]
I want to host Frigate on a server and using IP camera to connect to it, to view online. How Can I do that?

**Comment by NickM-27** [comment]
You are going to need to be more specific. Are you asking if frigate works with cameras that have a public IP address, or are you asking if you can expose frigate on the internet to view remotely?

**Comment by wangyiwu** [comment]
> You are going to need to be more specific. Are you asking if frigate works with cameras that have a public IP address, or are you asking if you can expose frigate on the internet to view remotely?

Thanks much for reply. Sorry I didn't describe it clearly. What I want to ask is if I can deploy Frigate on a server, and connect my IP cameras located at home. then i can access through my server on internet without configuring proxy or dns.

**Comment by NickM-27** [comment]
> > You are going to need to be more specific. Are you asking if frigate works with cameras that have a public IP address, or are you asking if you can expose frigate on the internet to view remotely?
> 
> Thanks much for reply. Sorry I didn't describe it clearly. What I want to ask is if I can deploy Frigate on a server, and connect my IP cameras located at home. then i can access through my server on internet without configuring proxy or dns.

you will need to setup some kind of reverse proxy, TCP tunnel, or DDNS service. There are lots of free services out there. I personally use Cloudflare TCP tunnels which work great

**Comment by NickM-27** [comment]
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/

**Comment by wangyiwu** [comment]
So do you know What is the tool can help me streaming from camera to cloud server

**Comment by wangyiwu** [comment]
> https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/

Thanks.
