### ISSUE TITLE
How to integrate camera with different resolution in the day and night mode

### ISSUE THREAD

**Issue by ekos2001** [blakeblackshear/frigate#542]
**Describe the bug**
I have a Lorex camera which has different resolutions in the day and night mode.
In the day mode it is 2560x1440, in the night mode - 1920x1080.
Is there any way to use it with frigate?

**Version of frigate**
0.8.0-rc1-amd64

**FFprobe from your camera**
Day mode
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55cb2d81eb80] max delay reached. need to consume packet
[rtsp @ 0x55cb2d81eb80] RTP: missed 1 packets
Input #0, rtsp, from 'rtsp://root:xxx@192.168.0.150:554/cam/ch0_0.h264':
  Metadata:
    title           : Session streamed by "ISD RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 10 fps, 9.58 tbr, 90k tbn, 20 tbc
    Stream #0:1: Audio: aac, 44100 Hz, mono, fltp
```
Night mode
```
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x5605b7056b80] max delay reached. need to consume packet
[rtsp @ 0x5605b7056b80] RTP: missed 1 packets
Input #0, rtsp, from 'rtsp://root:xxx@192.168.0.150:554/cam/ch0_0.h264':
  Metadata:
    title           : Session streamed by "ISD RTSP Server"
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: aac, 44100 Hz, mono, fltp
```

**Comment by cybertza** [comment]
Hi, I would assume that as a worst case scenario you could force the day res lower, this bearing in mind, that if you really wanted to get complex about it, you would have to delve into the fact that Frig only a fairly low res stream to detect, and then you can use the higher res stream to record, now with the new features of the ability to disable things via mqtt, you could go all out and duplicate the camera, and then have an automation that shifts between the 2 camera's detections.

as an alternative solution i have seen someone using something relating to an RTSP proxy, and that may normalize the stream for you?

Alternatively there may be multiple stream endpoints on the camera to investigate, forcing one stream to night, one stream to day, and one stream to detection? (depending on if its a hardware based night mode)

**Comment by blakeblackshear** [comment]
Is there any way to setup a substream that is the same at night and day? rtmp/clips/record roles won't care if the resolution changes on the main stream. Worst case scenario, you can use ffmpeg output_args to resize to 1080p for the detect role only similar to [this](https://github.com/blakeblackshear/frigate/issues/416#issuecomment-749023219).

**Comment by ekos2001** [comment]
Unfortunatelly there is no documentation for this camera model (Lorex FXC33V) and their app no longer works, everything what I was able to find only single RTSP url. 
I will try output_args, thank you. But both this solution and RTSP proxy will create extra server load.
I was thinking if you can make an option to use ffprobe for a selected camera and/or set a resolution as a list of values and iterate over it checking which resolution is current.

**Comment by blakeblackshear** [comment]
It's not going to create much extra load. You are going to offset much of the additional load by processing a lower resolution in frigate as well. Ffmpeg already has the video decoded, so the resize should be a minimal impact. Frigate processes the decoded video stream. Using another rtsp proxy in the middle would add significant additional load because it would have to decode, reencode at the smaller resolution, and then decode again.
