### ISSUE TITLE
Birdseye - Ability to manually define birdseye layout

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5424]
I want to be able to for example put camera 1 side by side to camera 2 - now its just random.

In addition I want to able to split Birdseye screen with my own resolution - for example, half screen camera 1, and the other half camera 2,3,4,5

**Comment by DrSpaldo** [comment]
@NickM-27 I am not sure if it is better to create another issue or add some suggestions for Birdseye to this one? 

- Have the ability to limit how many cameras are displayed in the Birdseye view, including limiting it to 1 camera. Example use case is you have a camera that is displayed via the Birdseye RTSP stream on a monitor / window that shows the single camera with the last motion, and continues to display one single camera after the motion has finished.

**Comment by NickM-27** [comment]
You already created an issue for that https://github.com/blakeblackshear/frigate/issues/7189

**Comment by DrSpaldo** [comment]
> You already created an issue for that #7189

Hahah, I swore that I did, so before I posted the one above, I searched my name and the word Birdseye and couldn't find it!  Ignore me then...

**Comment by Majestic7979** [comment]
Nick, is there any estimated timescale for this?

**Comment by tyzbit** [comment]
This issue technically has two feature requests:

- [X] The ability to define the ordering of cameras in Birdseye
- [ ] The ability to define the geometry/sizing of cameras in Birdseye

Number 1 is now satisfied with [released functionality in 0.13.0](https://docs.frigate.video/configuration/birdseye#sorting-cameras-in-the-birdseye-view).

So I believe the remainder of this feature request would then deal with adding a feature to change the geometry/sizing of cameras in Birdseye (such as in #6556).
