### ISSUE TITLE
[Config Support]: Possible make password to web page?

### ISSUE THREAD

**Issue by abensimon86** [blakeblackshear/frigate#5426]
### Describe the problem you are having

I want connect Frigate remotely without HA

Its possible make any authentication ? password? SSO?

### Version

0.12

### Frigate config file

```yaml
none
```

### Relevant log output

```shell
none
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
We recommend using a reverse proxy or TCP tunnel with authentication to do this. You can view https://github.com/blakeblackshear/frigate/issues/2014 for more context.
