### ISSUE TITLE
[Support]:  Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by convicte** [blakeblackshear/frigate#5429]
### Describe the problem you are having

FYI, the HA addon will presumably stop working correctly starting from HA 2023.03, as per the log below.

### Version

0.11.1

### Frigate config file

```yaml
In this particular case it's irrelevant, since the issue is related to the main integration code, it seems.
```

### Relevant log output

```shell
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 21:33:35 (4 occurrences)
Last logged: 21:34:05

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for frigate using this method at custom_components/frigate/__init__.py, line 289: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

### FFprobe output from your camera

```shell
Irrelevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink - but again irrelevan

**Comment by NickM-27** [comment]
this has already been fixed https://github.com/blakeblackshear/frigate-hass-integration/issues/421

**Comment by convicte** [comment]
Thank you and apologies for not spotting similar tickets—I was only looking in these still open.
