### ISSUE TITLE
[Support]: *CONFUSED* go2rtc, web2rtc, restreaming...Can someone explain?

### ISSUE THREAD

**Issue by moonbrushed** [blakeblackshear/frigate#5439]
### Describe the problem you are having

I'm CONFUSED. I'm using the latest beta and have been getting really confused by the new lingo to do with go2rtc, restreaming and all of the various new terms (MSE, webrtc, etc).

So my understanding is *really* limited - but can someone correct me or clarify the following....

So at its most basic level, I can access my camera streams (both main and sub) either as the camera transmits them directly - or use ffmpeg to transcode them into different sizes/formats? I use main stream for recording and sub for detecting.

With the go2rtc part....as I understand it I can pass my camera streams to go2rtc via the config file and then this new bundled plugin will transcode the stream into various other formats? Not entirely sure why this is needed other than something to do with limiting the number of connections to a camera.

I don't understand the Web2rtc stuff

I don't understand the difference between rtsp and rtmp...

Can someone just give me a basic 101 on the above?

Thanks!

### Version

0.12.0-66881EB

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest (various)

**Comment by blakeblackshear** [comment]
Have you read the guide? https://deploy-preview-4055--frigate-docs.netlify.app/guides/configuring_go2rtc

**Comment by NickM-27** [comment]
> With the go2rtc part....as I understand it I can pass my camera streams to go2rtc via the config file and then this new bundled plugin will transcode the stream into various other formats? Not entirely sure why this is needed other than something to do with limiting the number of connections to a camera.

It doesn't transcode the streams. It takes the same rtsp stream and makes it available using different transport technologies. This enables frigate to offer a better live view of the camera that is full resolution, full fps, supports audio, and is low latency. 

The fact that the stream can be restreamed to reduce connections to the camera is just a side effect ability that helps as well.
