### ISSUE TITLE
0.8.0-rc1 webui: debug stats not readable using chrome night mode

### ISSUE THREAD

**Issue by TheSleepySlee** [blakeblackshear/frigate#544]
The new UI is great. Kudos @paularmstrong  :)
However, when using chrome night mode, the background is grey, and the text is black, which make it difficult to read. Minor issue.
I am also facing responsiveness issues, when enabling zones for example.

Last comment: I have 5 cams, and need to scroll down. Is there option to specify cam size on the main UI?
Even better would be to have possibility to configure layout => Specify how many cams per line/column for example.

thanks

**Comment by paularmstrong** [comment]
> However, when using chrome night mode, the background is grey, and the text is black, which make it difficult to read. Minor issue.

Working on it today 😄

**Comment by TheSleepySlee** [comment]
@paularmstrong I'm having issues in the events tab too.

**Comment by TheSleepySlee** [comment]
Fixed
