### ISSUE TITLE
Better support for wide and tall aspect ratio cameras

### ISSUE THREAD

**Issue by NickM-27** [blakeblackshear/frigate#5449]
**Describe what you are trying to accomplish and why in non technical terms**
All cameras in the webUI and birdseye are treated the same regardless of aspect ratios. With dual lense cameras becoming more popular and portrait cameras being a relevant usecase, it would be nice if frigate used space for these cameras better

**Describe the solution you'd like**
Auto layout cameras view and birdseye where larger aspect ratio cameras are given more space

**Comment by DrSpaldo** [comment]
Agreed. I have 2 cameras that are sideways for a path, so they look terrible when viewing in the main Frigate page

**Comment by spikeygg** [comment]
I just got one of these double-camera setups and added it to my array. It would be REALLY nice to be able to describe in YAML cameras that are double wide should take up two units in the UI dashboard. There is quite a bit of dead-space below the double-camera image:
![image](https://github.com/blakeblackshear/frigate/assets/1015891/efaccee2-15cc-4282-9cce-aeb0449af28d)

**Comment by gravelfreeman** [comment]
+1 for this feature.

I made a duplicating [issue ](https://github.com/blakeblackshear/frigate/issues/9035)and even though I had searched through the issues before I couldn't find this issue.

**Comment by NickM-27** [comment]
the new UI takes panoramic and portrait cameras in to account
