### ISSUE TITLE
[Bug]:  `ui.live_mode` does not appear to be effective

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#5454]
### Describe the problem you are having

https://user-images.githubusercontent.com/29582865/218284044-b8394758-e054-4438-87fe-d9e2d57359b4.mp4

I want Frigate to always prefer webrtc over jsmpeg or mse, but this setting does not appear to be effective.

### Version

0.12 beta 8

### Frigate config file

```yaml
ui:
  live_mode: webrtc
```
```


### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
this setting only sets a default, the browser cached value will always take precedent

**Comment by felipecrs** [comment]
Hm... I see. So, I guess I should clean my cache. Thank you!

**Comment by NickM-27** [comment]
to be clear the value is "cached" using cookies

**Comment by felipecrs** [comment]
Then I should clean my cookies. Thanks again! :P

**Comment by blakeblackshear** [comment]
I actually think it's local storage

**Comment by NickM-27** [comment]
> I actually think it's local storage

Gotcha, I thought local storage was a type of cookie based on this

![Screen Shot 2023-02-11 at 15 49 18 PM](https://user-images.githubusercontent.com/14866235/218284326-649a2597-9b95-489e-84fc-68b06df4a6b2.png)

**Comment by NickM-27** [comment]
Also @felipecrs I do see a bug with this logic though unfortunately, will put up a fix

**Comment by felipecrs** [comment]
Interesting! 🤔
