### ISSUE TITLE
[HW Accel Support]: What the reason Coral interface between 10-40ms ?

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5461]
### Describe the problem you are having

I watch the graph and see its going between 10-40ms
What the reason its doesn't stay constant? 0-10ms ?
Its depended the PC hardware ? USB 2/3 ?

### Version

0.12 beta7

### Frigate config file

```yaml
none
```

### docker-compose file or Docker CLI command

```yaml
none
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Amcrest

### Any other information that may be helpful

none

**Comment by NickM-27** [comment]
It depends on the USB bus. Many hardware configurations have the USB bus shares for all ports and sometimes even other hardware like the Ethernet port. So when another devices starts sending data, the coral has less bandwidth to use.

**Comment by antonbek89** [comment]
> It depends on the USB bus. Many hardware configurations have the USB bus shares for all ports and sometimes even other hardware like the Ethernet port. So when another devices starts sending data, the coral has less bandwidth to use.

Thanks for your answer Nick
So my calculation FPS should be - 1000 / Coral interface average ( 25ms) = 40FPS 
its mean 8 camera with 5 FPS detect configuration = 1 Coral USB ?

**Comment by NickM-27** [comment]
> > It depends on the USB bus. Many hardware configurations have the USB bus shares for all ports and sometimes even other hardware like the Ethernet port. So when another devices starts sending data, the coral has less bandwidth to use.
> 
> Thanks for your answer Nick So my calculation FPS should be - 1000 / Coral interface average ( 25ms) = 40FPS its mean 8 camera with 5 FPS detect configuration = 1 Coral USB ?

No, that's not really how the math works. Just because a camera is set to 5fps detect doesn't mean it is always detecting, detection is only run when there is motion detected (which is done by the CPU). Also, when there's activity on a camera frigate may run multiple detections on the same frame in different regions and the detections per second can be higher. You will know if your coral is saturated because you will see the skipped fps being greater than 0

**Comment by antonbek89** [comment]
> 



> > > It depends on the USB bus. Many hardware configurations have the USB bus shares for all ports and sometimes even other hardware like the Ethernet port. So when another devices starts sending data, the coral has less bandwidth to use.
> > 
> > 
> > Thanks for your answer Nick So my calculation FPS should be - 1000 / Coral interface average ( 25ms) = 40FPS its mean 8 camera with 5 FPS detect configuration = 1 Coral USB ?
> 
> No, that's not really how the math works. Just because a camera is set to 5fps detect doesn't mean it is always detecting, detection is only run when there is motion detected (which is done by the CPU). Also, when there's activity on a camera frigate may run multiple detections on the same frame in different regions and the detections per second can be higher. You will know if your coral is saturated because you will see the skipped fps being greater than 0

Thanks Nick
