### ISSUE TITLE
[Config Support]: Comprehensive config.yml docs/example

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#5469]
### Describe the problem you are having

I'm having problems finding a single/consolidated schema/example for configs, I'm accustomed to example yml such as those found in Kubernetes configs where every option is demonstrated and documented.  Here, I find numerous snippets but no context, so Indentation levels/scopes are vague.

Does such a thing exist?

Thanks

### Version

core - 2022.8.3

### Frigate config file

```yaml
None
```

### Relevant log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
This already exists in the docs https://docs.frigate.video/configuration/index

**Comment by doug62** [comment]
Thanks/Sorry - was a bit thrown off by thinking this was within the ha/config file.
