### ISSUE TITLE
Add a message to log with the config file isn't found

### ISSUE THREAD

**Issue by simulot** [blakeblackshear/frigate#547]
**Describe the bug**
I have named by configuration file config.yaml by mistake. Obvioulsy this prevents frigate to start. But the log shows nothing.
It took me an embarrassingly long moment  to get it fixed...

**Version of frigate**
0.8.0 Release Candidate 1

**Config file**
Not relevant

**Logs**
```
Attaching to frigate
frigate             |  * Starting nginx nginx
frigate             |    ...done.
frigate exited with code 1

```

**Frigate debug stats**
N/A

**FFprobe from your camera**

N/A

**Additional context**
It uses to work with stable version. This shows me the problem.

```
Attaching to frigate
frigate             | Fontconfig error: Cannot load default config file
frigate             | Traceback (most recent call last):
frigate             |   File "detect_objects.py", line 32, in <module>
frigate             |     with open(CONFIG_FILE) as f:
frigate             | FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
frigate exited with code 1

```

I think it would be nice to log this fatal error. 
And if you can accept config.yml or config.yaml, that would be very nice! 

Thanks a lot for your work!

**Comment by blakeblackshear** [comment]
found this and fixed it for the next rc
