### ISSUE TITLE
[Support]:  General object "motion", trigger on any motion, emit MQTT on any motion.

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#5470]
### Describe the problem you are having

Is it possible to treat any motion as an event/object?  and then have that also emit an mqtt event w image?

### Version

0.10.0-beta5-amd64 

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

NA

### Any other information that may be helpful

This feature will ensure that if objects are not detected that an event/recording/mqtt event would be triggered.

**Comment by NickM-27** [comment]
A generic motion sensor is supported in frigate 0.11. There is no way to have motion appear as an event in the timeline. There's an existing request to add a motion event timeline to the recordings page.

**Comment by doug62** [comment]
The fact that motion is a sensor and not an object - does that mean there is no way to emit an MQTT topic when a motion occurs?  My goal is to subscribe via MQTT via motion detected events, similar to the way objects are.

**Comment by NickM-27** [comment]
> The fact that motion is a sensor and not an object - does that mean there is no way to emit an MQTT topic when a motion occurs?  My goal is to subscribe via MQTT via motion detected events, similar to the way objects are.  

All sensors are communicated via MQTT https://docs.frigate.video/integrations/mqtt#frigatecamera_namemotion

**Comment by doug62** [comment]
Thanks for being so responsive, That pages shows settings on/off states, I'm hoping to see a topic like:
frigate/Lobby/motion/snapshot = {JPG IMAGE}

**Comment by NickM-27** [comment]
That doesn't exist but I don't see why it's needed. Just watch the motion topic and pull the latest.jpg snapshot from the frigate api

**Comment by doug62** [comment]
Thanks - That was my plan B, however I'm not seeing a motion topic :(

**Comment by NickM-27** [comment]
> Thanks - That was my plan B, however I'm not seeing a motion topic :(

You're on an outdated version of frigate
