### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by EduardoLaranjo** [blakeblackshear/frigate#5477]
### Describe the problem you are having

> OpenVINO now supports YOLOX models, [see the OpenVINO docs for more info](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/detectors#openvino-detector)

What advantages does YOLO have?
Is it better accuracy? Is It better performance? Is It better inference speed? 

Much appreciated, Eduardo

### Version

0.12.0 Beta 8

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You can read https://github.com/blakeblackshear/frigate/issues/5184 for more info on that. The models are trained on the same datasets so they're similar but different types which leads to different inference speeds, different accuracies, etc. 

From what I can tell no model that is currently supported for OpenVINO is particularly better than another
