### ISSUE TITLE
[Support]: USB stack crashing

### ISSUE THREAD

**Issue by RichardPar** [blakeblackshear/frigate#5481]
### Describe the problem you are having

Bringing up a new platfom (Khadas VIM4) - The USB stack crashes and recordings stop.

I am currently recording to a USB-3 Hard drive and using Coral on USB2. Without recording, it seems OK - with recording - things go wonky

### Version

0.11.1-2eada21

### Frigate config file

```yaml
[Omitted - too many secrets]
```

### Relevant log output

```shell
F driver/usb/usb_driver.cc:870] ProcessIo [1-1] async transfer out failed. Abort. Resource exhausted: USB error -11 [AsyncBulkOutTransfer]
Fatal Python error: Aborted
Thread 0x0000007f4bfff1e0 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
Thread 0x0000007f697fa1e0 (most recent call first):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke
  File "/opt/frigate/frigate/edgetpu.py", line 83 in detect_raw
  File "/opt/frigate/frigate/edgetpu.py", line 159 in run_detector
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/edgetpu.py", line 220 in start_or_restart
  File "/opt/frigate/frigate/watchdog.py", line 34 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
[2023-02-13 19:30:42] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Not relevant

**Comment by NickM-27** [comment]
seems like your USB bus may be being oversaturated or it can't provide enough power for both devices. Would recommend a powered USB hub

**Comment by RichardPar** [comment]
> seems like your USB bus may be being oversaturated or it can't provide enough power for both devices. Would recommend a powered USB hub

Thanks - I have tried a powered hub (using a DELL docking station) - this happens even when I use a USB stick 
VIM4 is powered by 5V/4A psu and the DELL docking station is plenty power 🗡️ 

IOSTAT on the hard disk shows the iowats on the kernel staying at 0 until disk writes, then it goes to 5 for a second and then back to 0.  The CORAL and the disk are on different USB BUS 

```
khadas@homeassistant:~$ lsusb
**Bus 002 Device 005: ID 0480:a307 Toshiba America Inc EXTERNAL_USB**
Bus 002 Device 004: ID 05e3:0620 Genesys Logic, Inc. USB3.1 Hub
Bus 002 Device 003: ID 17e9:6006 DisplayLink Dell Universal Dock D6000
Bus 002 Device 002: ID 05e3:0620 Genesys Logic, Inc. USB3.1 Hub
**Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub**
Bus 001 Device 008: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 001 Device 006: ID 0424:2514 Microchip Technology, Inc. (formerly SMSC) USB 2.0 Hub
**Bus 001 Device 004: ID 18d1:9302 Google Inc.**
Bus 001 Device 009: ID 06c4:c411 Bizlink International Corp. D6000 Controller
Bus 001 Device 007: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 005: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 002: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
How can I tell what the USB bus untilisation is?

Thanks,
Richard

**Comment by RichardPar** [comment]
I added a command to reset the CORAL device when the problem occurs - (USB RESET) 

Restarting FFMPEG and CORAL seem to recover the situation;  so something with CORAL is causing issues. (I am using it on USB-2)

**Comment by NickM-27** [comment]
It commonly happens when the coral isn't getting enough power or it's communication is cut mid stream.

**Comment by RichardPar** [comment]
> It commonly happens when the coral isn't getting enough power or it's communication is cut mid stream.

Thanks... I'll put a scope on the power rails and see if there are any power issues.

**Comment by RichardPar** [comment]
> It's important to understand that if the laptop is getting power it doesn't mean that laptop can provide power via the USB port as that could have its own limitations. Like you said you're using the usb port of the dock itself which I'd think would work.
> 
> It could also be a usb2 issue as usb3 is recommended

Unfortunately I am locked to USB-2 as the hardware is custom (I had some Coral boards made; it was easier than waiting for the delivery dates of 'coralus unobtanium' to get to the market) - 

its running on a Khadas VIM4 hardware platform :D

**Comment by RichardPar** [comment]
I hope I have spotted the issue.. I got an oscilloscope trace of the power dropping on the Coral device during peak activity.    Made some changes and now running tests again... 

THanks all!
Richard

**Comment by RichardPar** [comment]
Double checked - its not power. 
My current hypothesis is that the RECORDING task on usb disk is being cached by the kernel. (as the files are not being opened with O_DIRECT); after 30 seconds (dirty cache expiry), the kernel flushes to disk... in this case its a large amount of data and saturates the USB bus.

I have changed the linux kernel to flush the cache in 5 seconds.. it makes it a bit more agressive, but the write sizes are much smaller and quicker. 

The correct fix (if its this) is to use O_DIRECT file access and not to use the linux caching system.

**Comment by RichardPar** [comment]
Update - its not the  USB saturation..

It was running fine - I restarted Frigate from the HomeAssistant GUI and it gave the below error 

The same thing happens on external Coral USB dongle and my custom hardware. USB2 and USB3 ports.  Hardware is not de-registering (no kernel USB errors) 

```
[2023-02-18 10:02:53] ws4py                          INFO    : Using epoll
[2023-02-18 10:02:56] frigate.edgetpu                INFO    : TPU found
F driver/usb/usb_driver.cc:870] ProcessIo [1-2] async transfer out failed. Abort. Resource exhausted: USB error -11 [AsyncBulkOutTransfer]
Fatal Python error: Aborted
Thread 0x0000007f63dc91e0 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
Thread 0x0000007f87b1d010 (most recent call first):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke
  File "/opt/frigate/frigate/edgetpu.py", line 83 in detect_raw
  File "/opt/frigate/frigate/edgetpu.py", line 159 in run_detector
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/edgetpu.py", line 220 in start_or_restart
  File "/opt/frigate/frigate/edgetpu.py", line 189 in __init__
  File "/opt/frigate/frigate/app.py", line 217 in start_detectors
  File "/opt/frigate/frigate/app.py", line 360 in start
  File "/opt/frigate/frigate/__main__.py", line 16 in <module>
  File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
```

**Comment by RichardPar** [comment]
Update: 
Frigate wont startup, I get the above error 100% of the time - but when I run the Coral test apps, it works. The Coral inference app has been running for hours without any issues. 

(NOTE) - There has been no reboot between Frigate crashing and the Coral test app running
```
khadas@Khadas:~/coral/pycoral$ python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg -c 10
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
108.6ms
13.5ms
13.6ms
13.5ms
13.5ms
13.6ms
13.5ms
13.5ms
13.6ms
13.5ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.75781
```

**Comment by blakeblackshear** [comment]
Can you run the Coral test apps inside the frigate container? I would guess that it's either a permissions difference when running in the container or a driver difference.

**Comment by RichardPar** [comment]
> Can you run the Coral test apps inside the frigate container? I would guess that it's either a permissions difference when running in the container or a driver difference.

From inside the container - it works -Frigate is running using CPU detectors (so it doesnt hijack the Coral device) 

```
root@ccab4aaf-frigate:/opt/frigate/pycoral# python3 examples/classify_image.py --model test_data/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels test_data/inat_bird_labels.txt --input test_data/parrot.jpg
/opt/frigate/pycoral/examples/classify_image.py:79: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  image = Image.open(args.input).convert('RGB').resize(size, Image.ANTIALIAS)
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
107.4ms
12.0ms
12.0ms
12.0ms
12.1ms
-------RESULTS--------
Ara macao (Scarlet Macaw): 0.75781
root@ccab4aaf-frigate:/opt/frigate/pycoral#

> 
```

**Comment by blakeblackshear** [comment]
I don't know why that would happen. To my knowledge, frigate is using the same underlying libraries.

**Comment by RichardPar** [comment]
> I don't know why that would happen. To my knowledge, frigate is using the same underlying libraries.

What is the best way to debug?  within the docker container is a bit of a headache - I dont mind poking about and changing things too add more debug messages.

**Comment by blakeblackshear** [comment]
There aren't really any debug outputs from tensorflow lite. Running inside the container is the only way to ensure the environment matches frigate's environment. Otherwise you are introducing other changes.

You could try creating a custom python script that runs the minimal python code from frigate for detection. You just have to narrow down the differences.

**Comment by RichardPar** [comment]
From the drivers.. they are identical - MD5 sums are the same..

Could it be possible that the video frame is complete garbage and messing up Coral?

**Comment by blakeblackshear** [comment]
I don't see how that would be possible. The Coral accepts a very specific input for the loaded model. I have also never seen that error message reported before, and many users have terrible video streams.

**Comment by RichardPar** [comment]
really dumb question - never done Docker stuff past 'run' and 'exec'; but do you have a recomemnded link to how to develop within a container?

**Comment by RichardPar** [comment]
Update -
The error occurs when there is LOTS of Disk-IO happening ..  I can reproduce at will using DD and the Coral Example apps. 

Not using recording functionality and the AI works fine. When Frigate records 24x7 on multiple cameras, the linux buffering fills and the kernel takes over to commit the data and takes priority away from all other processes

**Comment by aegershman** [comment]
I still need to troubleshoot more, but as a data point I'm seeing the same error error (`F driver/usb/usb_driver.cc:870] ProcessIo [1-2] async transfer out failed. Abort. Resource exhausted: USB error -11 [AsyncBulkOutTransfer]`) happen when I have 4 RTL-SDR dongles (software defined radios) plugged into my computer (on a powered usb hub) and active in a docker container. If I shut down the docker container the SDRs are using (trunk-recorder), frigate will launch with the TPU just fine.

And interestingly, when I shut down the SDRs container, I can launch frigate to get the TPUs running, then I can re-launch the SDRs container and everyone gets along just fine. It's a little weird.

I'll create a separate issue after I troubleshoot more, just wanted to share this comment in case someone comes across this in the future
