### ISSUE TITLE
[Feature Request] Fall Detection

### ISSUE THREAD

**Issue by akamel001** [blakeblackshear/frigate#5495]
**Describe what you are trying to accomplish and why in non technical terms**
I have cameras setup through out the house. It would be amazing if Frigate is able to detect if a person has fallen and trigger a sensor that can automate a workflow to alert users. This would be immensely helpful for elderly folks that live on their own. 

**Describe the solution you'd like**
I would love to see Frigate enable us to do fall detection on one of the substreams or on a designated zone. If detected, a binary sensor is triggered to "detected" and eventually clears once the person has gotten up and walked away. The sensor would then integrate with home assistant for automation of notifications. 

**Describe alternatives you've considered**
There are a bunch of paid alternative solutions but non work well and all are mostly cloud based with a massive delay.

**Comment by soundslikeluke** [comment]
This would be amazing

**Comment by woojtekk** [comment]
Maybe it's worth revisiting the idea of fall detection. Recently, I came across this repository where some amazing work has been done. so maybe it will be possible to integrate with frigate
https://github.com/parichehrvn/fall_detection

**Comment by soundslikeluke** [comment]
I think you are right that repository looks real amazing. I might even try set it up just to test it. If it could be integrated though that would be even better. Not sure what the appetite would be to do this but I don't think this probably is going away.

**Comment by T-C-D** [comment]
After setting up Frigate NVR at my parents place, where my Dad (77) is constantly in the yard gardening, I also thought this would make a great feature. He appreciates having the cameras everywhere, but he's much too stubborn to wear a fall detector device.
