### ISSUE TITLE
[Feature Request] Change start and stop time of a recording

### ISSUE THREAD

**Issue by tpjanssen** [blakeblackshear/frigate#5496]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to to change the start and stop time of an event so that I can add some extra time that might be missed by the detection logic. Also useful when an event is a long lasting stuck detection. Of course extending the duration (either pre or post) is only possible if 24/7 recording is enabled, and that these recordings are still retained.

**Describe the solution you'd like**
Best is to do this in the GUI, but it might also be useful to add API endpoints for this.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by NickM-27** [comment]
it's not clear what you're asking for. If you don't have recordings then what does it mean to change the start and stop times?

**Comment by tpjanssen** [comment]
Starting point is an existing recording. What I want to change its start and/or stop time.

**Comment by NickM-27** [comment]
Interesting, the only direction you could go is to make it shorter. As far as stuck detections go I think the effort is better spent improving frigate so stuck detections don't happen. If that were the case I am unsure where this feature would fit in.

**Comment by tpjanssen** [comment]
Some time ago I had some suspicious activity on my driveway. This activity started on the driveway of my neighbour, out of sight of the camera. You can hear people talk on the 24/7 recording. After they left his driveway they moved to my driveway, perfectly detected by Frigate. After some time they left and the activity continued on the other side of the road, where I normally don't want Frigate to detect anything. So in my case I want to advance the starting point of the recording, and I also want to add some extra post time to it.

This explains my use case a bit more I hope.

**Comment by tpjanssen** [comment]
No more input on this one?

**Comment by NickM-27** [comment]
I see what you're saying, just not 100% sure how it fits into frigate and the planned recordings overhaul.

**Comment by blakeblackshear** [comment]
It's not really changing the start and stop time of a recording. It would be of the event.
