### ISSUE TITLE
[Feature Request]: Improve navigation with a lot of cameras

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5512]
**Describe what you are trying to accomplish and why in non technical terms**
I have a _lot_ of cameras (30+). When I go to a specific camera, the left nav then lists _all_ the cameras just below the Cameras heading. This is great, because it's actually faster for me to click Cameras, then a specific camera, then find it in that list rather than scrolling through the full Cameras home page to find a particular camera. The problem is it pushes the Birdseye and Events sections below the fold, so I either have to scroll a long ways below that, _or_ I use multiple clicks to go to the home page again, _then_ to Birdseye.

**Describe the solution you'd like**
Keep Birdseye and Events list above the camera list when on a specific Camera's page.

**Comment by ccutrer** [comment]
Not stale

**Comment by ccutrer** [comment]
Not stale

**Comment by NickM-27** [comment]
I believe this is closed by the new UI in general along with the inclusion of support for camera groups https://github.com/blakeblackshear/frigate/issues/5510

**Comment by ccutrer** [comment]
I thought I'd take a look at the latest dev branch. WOW!!!! The UI is revolutionarily better! Strong work!!
