### ISSUE TITLE
[Bug]: Can't "fullscreen" Birdseye on Mobile

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5513]
**Describe what you are trying to accomplish and why in non technical terms**
When I tap the actual images of Birdseye on desktop, it goes full screen. It does not do this on mobile.

**Describe the solution you'd like**
Tap the image, it goes full screen (in either portrait or landscape orientation).

**Describe alternatives you've considered**
Turning my phone to landscape, and zooming in on the video feed. But it's hard to get to line up perfectly to not waste padding on top or bottom _and_ not crop anything on top or bottom. More importantly, as I'm doing this, if I have to scroll up at all, or reach the bottom accidentally, the top navbar "pops over" a good chunk of the image, and I can't get rid of it without scrolling up and back down and trying again.

Even if full screen is not truly supported on mobile for some reason, just perfectly scrolling and zooming so that the top of the video feed is at the top of the window, and the bottom is at the bottom, with no navbar, would be sufficient.

**Comment by NickM-27** [comment]
This is supported in 0.12 with the new restreamed birdseye view

**Comment by ccutrer** [comment]
Hmmm... I enabled that (as documented at https://deploy-preview-4055--frigate-docs.netlify.app/configuration/restream#birdseye-restream):

```yaml
birdseye:
  mode: objects
  width: 1280
  height: 720
  restream: true
```

 and MSE streaming is working, but WebRTC is not (even though it works fine with individual cameras). Is there something else I need to do? And since MSE isn't supported on iOS...

**Comment by NickM-27** [comment]
That is all that is needed for birdseye restream. Please describe in more detail what not working means and I'd suggest checking the go2rtc logs

**Comment by ccutrer** [comment]
Heh, WebRTC started working while I was looking for Go2RTC logs. Apparently it takes >10s each time I load it to start the WebRTC stream. I apologize, I simply wasn't patient enough. All my other WebRTC streams start in < 0.1s.
