### ISSUE TITLE
Invalid certificate on plus.frigate.video

### ISSUE THREAD

**Issue by ehn** [blakeblackshear/frigate#5537]
### Describe the problem you are having

It looks like the TLS certificate on plus.frigate.video has expired.

<img width="540" alt="Screenshot 2023-02-18 at 10 56 57" src="https://user-images.githubusercontent.com/179446/219854194-80fcb905-3d16-4b51-83e0-e2fce514ebe3.png">

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

N/A

**Comment by blakeblackshear** [comment]
How embarrassing. It's fixed. It was just the frontend. The api should have been fine.
