### ISSUE TITLE
manifest unknown: manifest unknown Not able to update.

### ISSUE THREAD

**Issue by sheminasalam** [blakeblackshear/frigate#554]
**Describe the bug**
Unable to update to beta 1.4

**Version of frigate**
Now running Beta 1.3 in HA supervised in Raspbian OS rpi 4
**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Logs**
```
21-01-20 06:08:56 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for ccab4aaf/armv7-addon-frigate-beta:1.4
21-01-20 06:09:01 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build ccab4aaf/armv7-addon-frigate-beta:1.4: manifest for blakeblackshear/frigate:0.8.0-rc2-armv7 not found: manifest unknown: manifest unknown
21-01-20 06:09:01 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/8 : ARG BUILD_ARCH
Step 2/8 : FROM blakeblackshear/frigate:0.8.0-rc2-${BUILD_ARCH}
```
**Additional context**
I was having the same issue with another addon. And it that it was found that the latest update of HA supervisor has some issues with any alphabets given in the version parameter. You can get the details in this link. 
https://github.com/ThePicklenat0r/hassio-ngrok/issues/23

**Comment by neonpak** [comment]
@blakeblackshear Looks like the armv7 image didn't make it to the docker hub.

**Comment by blakeblackshear** [comment]
This one takes so much longer to build that I forgot to push it. It is up now.
