### ISSUE TITLE
[Support]: How to keep continuous recording, but backup only events to external storage

### ISSUE THREAD

**Issue by fliespl** [blakeblackshear/frigate#5541]
### Describe the problem you are having

Are there some guidelines how to backup only segments with motion detected?

Since those are stored same way as 24/7 recording I assume I should somehow take "important" filenames from frigate.db file. Are there any guidelines as to on which columns should I filter ?

### Version

0.11.1

### Frigate config file

```yaml
Not applicable
```

### Relevant log output

```shell
Not applicable
```

### FFprobe output from your camera

```shell
Not applicable
```

### Frigate stats

```json
Not applicable
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Not applicable

**Comment by NickM-27** [comment]
If you wanted to do that you'd want to use the api to pull clips of what you want. The internal recordings structure is not meant to be interacted with directly.

**Comment by fliespl** [comment]
@NickM-27 thanks much! I am not sure how I missed availability of api to do that... Probably tired or something :)
