### ISSUE TITLE
Only detect moving:  objects... 

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#5543]
### Describe the problem you are having

I'm sure this must be a feature, how do I only detects moving objects (without affecting zones - My driveway frequently has stationary cars in all areas for example - zones only filtering won't work)

### Version

Current beta

### Frigate config file

```yaml
x
```

### Relevant log output

```shell
x
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Other

### Any other information that may be helpful

Mucho thanks

**Comment by NickM-27** [comment]
Frigate is designed to track objects the entire time they are in the frame. If your car stops being tracked in the driveway then when a car drive by or some other motion happens you get another event for the car. Meanwhile, if you let frigate work the way it is designed, you'll have one event for the car in the driveway the entire time it is there. There are of course recording retention and other options to ensure these stationary objects are not recorded.

**Comment by doug62** [comment]
I'm confused by " you'll have one event for the car in the driveway the entire time it is there" - that seems to not be an event but rather a state, my goal is to "receive an MQTT message when a) there is any motion; b) a tracked object moves - and to receive an event when it transitions from motion/no-motion,  object moving/not moving.  I really only care about motion of anything - cos motion is the only time something bad may occur?

**Comment by NickM-27** [comment]
if you're referring to notifications then you should use the stationary flag in the MQTT messages to ignore those messages

**Comment by NickM-27** [comment]
By event I'm talking about frigate events

**Comment by NickM-27** [comment]
I wrote a guide for this that could be leveraged to get the behavior you want https://github.com/blakeblackshear/frigate/discussions/2898

**Comment by doug62** [comment]
Thanks - I'm not seeing a 'stationary flag' in the mqtt topics, but then you pointed out frigate event? - is that emitted in logs that I could parse? (I use Kubernetes->Elastic so could parse, wondering what log level/types of log messages to filter for?)  Looks like objects message include the detected object count so guessing that's the way I will have to proceed but thanks for getting back to me.

**Comment by NickM-27** [comment]
It's definitely there assuming you're running 0.11 https://docs.frigate.video/integrations/mqtt#frigateevents
