### ISSUE TITLE
Frame Grab (API and UI)

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5564]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to grab a specific, frame (full resolution of recording stream, or down-converted to detection stream resolution) while watching a recording so that I can either send it to Frigate+ to improve the model, or for various other reasons that I feel this is the best frame.

**Describe the solution you'd like**
Firstly, an API similar to https://docs.frigate.video/integrations/api#get-vodcamerastartstart-timestampendend-timestampindexm3u8 that has a single arbitrary timestamp (sub-second resolution, or frame number after a specific second starts would probably be necessary) and returns a JPG.

Second, in the UI while watching a recording or clip, while paused, a "snapshot" button would trigger an automatic download of the current frame (frame-step forward and back buttons would make it much easier to select the correct frame), or a Frigate+ button would send _this_ frame to Frigate+ for annotation.

**Describe alternatives you've considered**
Screenshotting the paused frame is likely to have reduced quality due to either difficulties in cropping the screenshot to the exact area, the video window in your viewing app not exactly matching the recording resolution, etc.

Downloading the recording/clip and then extracting it yourself via ffmpeg, etc. is a lot of extra steps.

**Comment by NickM-27** [comment]
the api for this has been added in https://github.com/blakeblackshear/frigate/pull/6194

**Comment by NickM-27** [comment]
This has been implemented in 0.14 UI
