### ISSUE TITLE
Crosslink Recordings and Live camera views

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5565]
**Describe what you are trying to accomplish and why in non technical terms**
Getting to the recordings page for a camera (`/recording/<camera>`) is unnecessarily cumbersome. The only way to get to it is from the homepage, scrolling to the snapshot of the camera, and clicking Recordings.

**Describe the solution you'd like**
While at `/cameras/<camera>`, have a link to Recordings (`/recording/<camera>`, probably down by the Tracked Objects area that links to events). But only if there are any recorded segments for that camera.

While at `/recording/<camera>`, have a link back to the live view (`/cameras/<camera>`).

**Describe alternatives you've considered**
Clicking the home page, scrolling down to the proper camera, and clicking Recordings.

**Additional context**
Perhaps the Events page could also have a link to the Recordings page for each camera/event, that would drop you directly into the recordings UI with the event time pre-selected at `/recording/<camera>/<timestamp>`, making it easier to jump around and look for additional context that perhaps the object detection missed.

**Comment by ccutrer** [comment]
Not stale

**Comment by NickM-27** [comment]
This has been implemented in the new ui for 0.14
