### ISSUE TITLE
[Config Support]: MQTT not working to hostname (HASS add-on)

### ISSUE THREAD

**Issue by jherby2k** [blakeblackshear/frigate#5566]
### Describe the problem you are having

If i configure MQTT using a hostname, it doesn't appear to resolve. Works perfectly fine with an IP address, but i'd like to use a hostname with a matching cert for SSL. Is there no DNS resolver in the add-on? 

### Version

all

### Frigate config file

```yaml
mqtt:
    host: <hostname.myhouse.net>
    port: 1883
    user: frigate
    password:
```

### Relevant log output

```shell
2023/02/21 15:19:44 [error] 129#129: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "ccab4aaf-frigate-fa-beta:5000"
```

### Frigate stats

```json
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

is it choking on IPv6? Using a hard-coded DNS provider?

I have both IPv4 and IPv6 configured. Also conceivable that Adguard is choking on the request, although i don't see the DNS query coming through at all.

**Comment by austindetzel** [comment]
Are you able to ping the hostname from HASS? I know there's a lot of networks that have issues with hostnames.

**Comment by jherby2k** [comment]
i'm not really sure how to test this from within the container as there are no networking tools in there. Tried adding a static entry to /etc/hosts but unfortunately i can't persist the changes on a restart. So no idea how to make a hostname work.

**Comment by NickM-27** [comment]
Probably need to look and see if / how other addons support this. Wouldn't be a problem in a native docker container

**Comment by jherby2k** [comment]
Sorry i'm not an expert at all in docker, but have a look at https://github.com/hassio-addons/addon-adguard-home. its a DNS server so it kinda by definition needs to be able to do DNS lookups.

**Comment by NickM-27** [comment]
Looks like it is running with host networking mode so that is likely all that would be needed. Unfortunately HA does not make network mode customizable with addons, host mode in general would likely cause a lot of issues for users generally since frigate uses many ports internally

**Comment by jherby2k** [comment]
Fair. Ill do some more research on if this is doable some other way - maybe
use the home assistant API to do a lookup? Using unencrypted MQTT is not
the end of the world. Might be good to mention that it needs to be an IP in
the docs though.
