### ISSUE TITLE
Recordings: File segmenting - fewer files please.

### ISSUE THREAD

**Issue by doug62** [blakeblackshear/frigate#5568]
### Describe the problem you are having

It seems that recordings are stored like: recordings\<date>\<hour>\<cam name>\<mm>:<ss> and in 10 second segments/files.

Is it possible to create: 1) 1 file/cam/(day/hour) or some such pattern?

Thanks

### Version

Current dev

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

**Comment by blakeblackshear** [comment]
You can modify the ffmpeg output args, but that will require a much larger cache and video for events won't be available until the full hour is complete.

Think of these files as a part of frigate's internal database structure, so messing with them directly isn't recommended. 

Why do you want to modify them?

**Comment by doug62** [comment]
I'm finding that object detection isn't 100% reliable, I wish to retain either full or motion triggered videos, would be nice to have a file named <yy><mm><dd><hh>.mpeg with all video, and/or segments with motion, plus current object triggered video, and then run this through retention mechanism.

Side note - Last year a child was last seen possibly passing near our house, If I would have had this feature I could have provided info/assistant (kid still missing - sad)

**Comment by NickM-27** [comment]
What you're describing is already supported. You can simultaneously have object triggered recordings (events recordings) and 24/7 recordings

**Comment by doug62** [comment]
I am using current dev/alpha and viewing configs at - https://deploy-preview-4055--frigate-docs.netlify.app/configuration/

I am currently getting hundreds of 10 second recordings, I wish to have : 1) All video/camera in files 1 hour long named yymmddhh.mpeg or something like that; 2) and for Motion either an mpeg or have motion trigger just like object detection does.
Can you point me towards the docs where I can do something like that?

**Comment by NickM-27** [comment]
You can't do exactly that. And it's not clear if you understand the consequences of having such large segments of what that would actually accomplish that the existing system wouldn't. 

You could use the ffmpeg output_args for record to change the segment time to 3600 but again there's going to be a number of issues with changing that.

**Comment by blakeblackshear** [comment]
If you want to archive footage for long term storage and don't want to use Frigate to view recordings, then I would recommend using the VOD endpoint with ffmpeg to download and create an hour of footage with whatever name you want. I don't recommend trying to modify Frigate to work the way you are describing. There is no way to extract only the segments containing motion in the current versions of Frigate.

**Comment by veqryn** [comment]
At least on the latest beta image, segment_time is limited to 60 seconds max, otherwise frigate throws an error.  I tried setting it to 3 minutes, and got that error.

@blakeblackshear @NickM-27 I have a question or two for you: 
1. are longer videos more efficiently compressed by H.264/H.265?
I would assume so, but I'd wonder if there was a reasonable point of diminishing returns, and what that point would be?  In other words, how much less space would a single 1 minute or 10 minute video file take up, versus the same video file broken into many video files each of which was a 10 second segment?

2. How would changing the segment_time from 10s to 60s change the CPU/GPU/RAM/tmpfs-cache/shm-size requirements?  Would I just need 6x the tmpfs cache and 6x the shm?  Would there be any increased cpu / gpu / or ram requirements beyond that?

**Comment by NickM-27** [comment]
Another thing to point out is it will make loading times longer when watching back the clips because it has to send the whole 60 second segment to watch. 

If you are interested, I'd suggest reading about HLS or DASH and how that is used, because even for movies on popular streaming setups they are delivered in small segments like that.

**Comment by blakeblackshear** [comment]
One other downside is that mp4 files will generally become corrupted if the ffmpeg process exits unexpectedly before the file is written because there is metadata at the end. If you have hour long segments, you would lose the entire hour if the ffmpeg process is interrupted.

**Comment by veqryn** [comment]
> > 1. are longer videos more efficiently compressed by H.264/H.265?
> > 
> > I would assume so, but I'd wonder if there was a reasonable point of diminishing returns, and what that point would be?  In other words, how much less space would a single 1 minute or 10 minute video file take up, versus the same video file broken into many video files each of which was a 10 second segment?
> 
> No there is not. H264 and h265 do compression between key frames. A key frame is a full frame with all pixels and between there they only include the diff data (motion). There is no compression benefit outside of that. This is why if you look at the 10 second segments they are very consistent in size.

I did a probably unscientific test, with my camera in a room with no motion or lighting changes.  10s segments over 20-30 minutes averaged out to about 35.1 KiB/second for total file size, while 60s segments over a similar time frame came out to about 22.5 KiB/second.

Is there a lot of metadata in the file that might account for a large difference like that?

**Comment by veqryn** [comment]
> One other downside is that mp4 files will generally become corrupted if the ffmpeg process exits unexpectedly before the file is written because there is metadata at the end. If you have hour long segments, you would lose the entire hour if the ffmpeg process is interrupted.

Fwiw I was personally considering 1-3 minute long recordings. But I was also curious about the efficiency of such short files. Good to know about it possibly being interrupted tho.

**Comment by doug62** [comment]
From a feature/user perspective, the ability to easily view a 24x7 recording for a given time point from a browser is critical (IMO) - the technical aspects don't concern the user...  I heard that ffmpeg can join movies so I plan to write a .sh rollup job for that at some point....

**Comment by NickM-27** [comment]
> > > 1. are longer videos more efficiently compressed by H.264/H.265?
> > > 
> > > I would assume so, but I'd wonder if there was a reasonable point of diminishing returns, and what that point would be?  In other words, how much less space would a single 1 minute or 10 minute video file take up, versus the same video file broken into many video files each of which was a 10 second segment?
> > 
> > 
> > No there is not. H264 and h265 do compression between key frames. A key frame is a full frame with all pixels and between there they only include the diff data (motion). There is no compression benefit outside of that. This is why if you look at the 10 second segments they are very consistent in size.
> 
> I did a probably unscientific test, with my camera in a room with no motion or lighting changes. 10s segments over 20-30 minutes averaged out to about 35.1 KiB/second for total file size, while 60s segments over a similar time frame came out to about 22.5 KiB/second.
> 
> Is there a lot of metadata in the file that might account for a large difference like that?

There are things like the moov atom and other metadata which are put at the beginning of the mp4 file in frigate's case. If we counted that as 15 KiB/second then that amounts to 54 MiB/hour which is very insignificant considering the data rates of the actual video footage especially as you go up in resolution.

**Comment by NickM-27** [comment]
> From a feature/user perspective, the ability to easily view a 24x7 recording for a given time point from a browser is critical (IMO) - the technical aspects don't concern the user... 

This is already supported though so I don't understand your point? also, the technical aspects do concern the user when the user is trying to change those technical aspects. 

> I heard that ffmpeg can join movies so I plan to write a .sh rollup job for that at some point....

yes, so just use ffmpeg to create a concatenated video file from the api like has been suggested https://docs.frigate.video/integrations/api#get-vodyear-monthdayhourcameramasterm3u8

**Comment by doug62** [comment]
Thanks, for the link to API document, Q: If I have thousands of 10 second clips of 24x7 records (not triggered by motion/object but fulltime), is the API able to combine those 10 second clips into a single mpeg?  I'm still thinking I will need to write a .sh for this.

**Comment by NickM-27** [comment]
> Thanks, for the link to API document, Q: If I have thousands of 10 second clips of 24x7 records (not triggered by motion/object but fulltime), is the API able to combine those 10 second clips into a single mpeg?  I'm still thinking I will need to write a .sh for this.

The API is able to do this but you are very likely to run into memory issues as it has to be combined in memory. The easier way is to use ffmpeg to combine on your client that is requesting the clip. It is very easy `ffmpeg -i http://frigate//////master.m3u8 output.mp4` (left out api path for brevity)
