### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by MyraBaba** [blakeblackshear/frigate#5569]
### Describe the problem you are having

@blakeblackshear 

Hi Can we use frigate as our SaaS system and can support thousands of camera ? 

Can we cooperate to improve the system ? 

### Version

dev

### Frigate config file

```yaml
dev
```

### Relevant log output

```shell
dev
```

### FFprobe output from your camera

```shell
dev
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wired

### Camera make and model

dev

**Comment by blakeblackshear** [comment]
The project is MIT licensed, so you can use it for that purpose if you wish. You are welcome to contribute to the project with pull requests and we will consider including changes at our discretion.
