### ISSUE TITLE
Error adding integration

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#557]
updated to 1.4 version today. re-did all the confiog. working well so far. 

But I still cannot add the integration.

![image](https://user-images.githubusercontent.com/30929896/105150771-76bd1780-5b05-11eb-9952-13b309d65d30.png)

Also i'm a bit confused with the instructions (as i'm a total noob) below.

I am not using HassOS but running Home Assistant on Ubuntu (and HA running in docker).
I installed the Supervisor, then installed the HACS repository. But cannot install the Integration. gives error as above.

![image](https://user-images.githubusercontent.com/30929896/105151058-cbf92900-5b05-11eb-9b0f-433b06e618b1.png)

**Comment by fanningert** [comment]
When you running HassOS Addon with the beta (Release) version. Then you need to use following URL.

http://ccab4aaf_frigate-beta:5000

**Comment by asemev** [comment]
Ah ok thank you fanningert.

**Comment by asemev** [comment]
weird. this also didnt work.
![image](https://user-images.githubusercontent.com/30929896/105152292-437b8800-5b07-11eb-85f1-4f95efb281da.png)

**Comment by asemev** [comment]
i cleared browser cache, re-installed HACS reporsitory, restarted HA and now it works. Thanks again.
