### ISSUE TITLE
"Last Received Frame" data point.

### ISSUE THREAD

**Issue by joeShuff** [blakeblackshear/frigate#5575]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to track when the last frame was received from a camera so that I can quickly be notified that a camera isn't reporting to frigate to remedy asap.

**Describe the solution you'd like**
Ideally a timestamp attribute reported to MQTT broker/HA integration of the time the last frame was received from the ffmpeg stream so that can be hooked into automations.

**Describe alternatives you've considered**
Considered pinging the device to monitor but might cause more issues than it solves.

**Additional context**
Sometimes some cameras just stop sending frame for a while and I have to reboot the camera and/or frigate and it'd be good to be notified of a symptom of this through frigate. Sometimes it is network connectivity issues but a symptom would be the frames not received by frigate.

**Comment by NickM-27** [comment]
This is already supported with the camera_fps value being 0. In 0.12 we force the camera_fps to be set to 0 when the process stops receiving frames

**Comment by joeShuff** [comment]
Interesting, good to know!

Now I know for certain my doorbell is struggling...

![image](https://user-images.githubusercontent.com/15524362/220945725-afe4fb98-a9a4-4f78-bd44-c1f48fba61d2.png)
