### ISSUE TITLE
Events Sub_Labels Bug or Improvement

### ISSUE THREAD

**Issue by LckySndays** [blakeblackshear/frigate#5599]
1. If I have so many Sub_Labels that may stretch out of my screen, I need to adjust browser zoom to lower value than 100% so that the drop-down menu appear correctly, otherwise it seems to do nothing when I click it.

2. When for example I want to filter out specific sub-labels (ex: James), anything start with James (ex:JamesBond) will also appear on the list. which I think is not ideal.

3. Sometimes the Sub_Labels contain multiple value, but at the same time some other multiple value is not even on that list which kinda confusing ( see attached image below ). 

4. I think its better to breakdown the Sub_Labels value into single value only, For example when I filter "James" value, the list may contain "James" only, "James" with others or vice versa. 

![Frigate_Sub_Labels_](https://user-images.githubusercontent.com/13220698/221567054-0a457d69-a677-4d9c-ac39-397b3f5e813e.png)

**Comment by LckySndays** [comment]
Ideally when I select ```James``` it should only show me ```James``` and ```James, Nick```
and the Sub_Labels Drop-down should list 3 entities ```James```, ```Nick```, and ```JamesBond```

**Comment by NickM-27** [comment]
> and the Sub_Labels Drop-down should list 3 entities `James`, `Nick`, and `JamesBond`

This is already the case. I am trying to reproduce an issue where it does not do this but I am unsuccessful so far
