### ISSUE TITLE
RTMP support suggestion

### ISSUE THREAD

**Issue by mr-onion-2** [blakeblackshear/frigate#56]
I have had to switch to RTMP for some of my cameras.

My Reolink cameras use the syntax _rtmp://{host}:{port}{path}&user={}&password={}_. For now I've simply added the rtmp values to my config file and made a copy of the _get_rtsp_url_ method (_get_rtmp_url_), which is used if the rtsp host is blank. I'm sure there is a more elegant way though.

Also, I've since noticed that the ffmpeg documentation suggests the URL syntax for RTMP can be _rtmp://[username:password@]server[:port][/path]_. 

I'm happy to put a PR in for this if you think it would benefit others, but I'm unsure of the best approach with regards to the different syntaxes which are possible. I'm wondering whether it would be better to just have an optional override ffmpeg_url in order to support any syntax.

Background
Artefacts in my feed were triggering occasional false alerts. Switching to the RTMP stream (thanks @steveneighbour #27) has fixed this. Also I've only had one 'last frame is more than than 2 seconds old, restarting...' in the last 24 hours, compared to once every 2-3 hours before :)

**Comment by steveneighbour** [comment]
i implemented this workaround as well, reolink cameras are much better behaved with ffmpeg when using rtmp.  using the latest build i'm rock solid, only a few blips per day now.

I altered video.py to be the below, assuming that your path starts with /bcs (i don't know much python though, so this is almost certainly a bad way to do it)

```python
def get_rtsp_url(rtsp_config):
    if (rtsp_config['password'].startswith('$')):
        rtsp_config['password'] = os.getenv(rtsp_config['password'][1:])
    if (rtsp_config['path'].startswith('/bcs')):
        return 'rtmp://{}:{}{}?user={}&password={}'.format(rtsp_config['host'], rtsp_config['port'], rtsp_config['path'], rtsp_config['user'], rtsp_config['password'])
    else: 
        return 'rtsp://{}:{}@{}:{}{}'.format(rtsp_config['user'], rtsp_config['password'], rtsp_config['host'], rtsp_config['port'], rtsp_config['path'])
