### ISSUE TITLE
Invalid Person detection

### ISSUE THREAD

**Issue by segator** [blakeblackshear/frigate#560]
Running beta3, with CPU based object detection.
I know there are bikes better than some people but, 78% acurracy maybe is too high 
![image](https://user-images.githubusercontent.com/2348131/105171986-3c607400-5b1f-11eb-8b85-ca81a5d244e0.png)

**Comment by blakeblackshear** [comment]
This isn't a bug. The model is published by Google and is what it is for now. Try using filters.
