### ISSUE TITLE
[Camera Support]: Reolink RLC-511

### ISSUE THREAD

**Issue by georgbachmann** [blakeblackshear/frigate#5605]
### Describe the problem you are having

I would like to have an NVR that is recording 24/7 and I'd like to be able to playback that footage. I think that my config is setup correctly. I can see a live stream, and sometimes also recordings, but most of them are not really playing back.
Even when I go to the mapped media folder -> recordings and drill down, some files there are able to play back, but most of them also will not back on my computer either.

My camera is a Reolink RLC-511 and I am totally new to this, so please tell me which more information you need. I can, if that's ok, upload a sample video that is stuck?!?

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.15
  user: frigate
  password: <my-password>
  topic_prefix: frigate

cameras:
  Einfahrt:
    ffmpeg:
      inputs:
        - path: rtsp://synology:<my-password>@192.168.1.165:554//h264Preview_01_sub
          roles:
            - detect
            - rtmp
        - path: rtsp://synology:<my-password>@192.168.1.165:554//h264Preview_01_main
          roles:
            - record

    record:
      enabled: True

    detect:
      fps: 4

    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: False
      retain:
        default: 14

    motion:
      mask:
        - 1280,0,1280,720,810,720,497,375,497,303,422,213,292,198,0,207,0,0

    objects:
      track:
        - person

record:
  enabled: True
  retain:
    days: 2
    mode: all

birdseye:
  enabled: True
  quality: 8
  mode: continuous

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
Not sure if if's relevant, but this is the docker log since my last restart:


[2023-02-27 19:43:39] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2023-02-27 19:43:39] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-02-27 19:43:39] peewee_migrate                 INFO    : There is nothing to migrate
[2023-02-27 19:43:39] detector.cpu1                  INFO    : Starting detection process: 217
[2023-02-27 19:43:39] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2023-02-27 19:43:39] detector.cpu2                  INFO    : Starting detection process: 219
[2023-02-27 19:43:39] frigate.app                    INFO    : Output process started: 220
[2023-02-27 19:43:39] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2023-02-27 19:43:39] ws4py                          INFO    : Using epoll
[2023-02-27 19:43:39] frigate.app                    INFO    : Camera processor started for Einfahrt: 225
[2023-02-27 19:43:39] frigate.app                    INFO    : Capture process started for Einfahrt: 227
[2023-02-27 19:43:39] ws4py                          INFO    : Using epoll
[2023-02-27 19:43:44] frigate.record                 WARNING : Discarding a corrupt recording segment: Einfahrt-20230227194341.mp4
[2023-02-27 19:44:14] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:33886]
[2023-02-27 19:44:17] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51228]
[2023-02-27 19:45:03] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51228]
[2023-02-27 19:45:49] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:33886]
[2023-02-27 19:46:54] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51694]
[2023-02-27 19:46:59] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51694]
[2023-02-27 19:47:02] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51732]
[2023-02-27 19:47:04] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51732]
[2023-02-27 19:47:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51744]
[2023-02-27 19:47:11] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51744]
```

### FFprobe output from your camera

```shell
ffprobe rtsp://synology:<my-password>@192.168.1.165:554//h264Preview_01_main                                                                                                            
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1.2_5 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://synology:<my-password>@192.168.1.165:554//h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2304x1296, 36 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
{"Einfahrt":{"camera_fps":4.1,"capture_pid":227,"detection_fps":0.0,"pid":225,"process_fps":4.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":84.42,"pid":217},"cpu2":{"detection_start":0.0,"inference_speed":82.31,"pid":219}},"service":{"storage":{"/dev/shm":{"free":65.1,"mount_type":"tmpfs","total":67.1,"used":2.0},"/media/frigate/clips":{"free":1949440.1,"mount_type":"btrfs","total":3835992.3,"used":1886552.2},"/media/frigate/recordings":{"free":1949440.1,"mount_type":"btrfs","total":3835992.3,"used":1886552.2},"/tmp/cache":{"free":1949440.1,"mount_type":"btrfs","total":3835992.3,"used":1886552.2}},"temperatures":{},"uptime":753,"version":"0.10.1-83481af"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink RLC-511

**Comment by NickM-27** [comment]
First off you are running an outdated version of frigate, I would suggest updating. 

Secondly, you will need to provide some actual logs for the error when frigate fails to play back otherwise there's no way to know what is wrong

**Comment by georgbachmann** [comment]
Ok... I thought I just updated to the latest using Portainer... will check that! Thanks for pointing that out!

So I am not really sure what the problem is... here is a screenshot of my file-explorer. Those files that seem not to play, don't have a preview
<img width="991" alt="Bildschirm­foto 2023-02-27 um 21 41 37" src="https://user-images.githubusercontent.com/893113/221681429-d1a1e524-bdc7-4005-88eb-5dcbb55f755e.png">

In frigate that looks like so:
<img width="1462" alt="Bildschirm­foto 2023-02-27 um 21 46 10" src="https://user-images.githubusercontent.com/893113/221681865-249688db-bbd0-484a-ac46-63c219217feb.png">
Also... in the player the time is continuing but the image itself is stuck.
So I guess the camera will then just report shit data?

And here are two sample files.

Working File:
https://www.dropbox.com/s/szf7ornf7xgh725/03.42.mp4?dl=0

Invalid File:
https://www.dropbox.com/s/dz68zabb88t5hj2/03.51.mp4?dl=0

An other think... I used to use Synology Surveillance Station before and it kinda worked there, but it was just very slow. That's why I'd like to switch...

Again... I know very very little about video files... so forgive me if my problem is obvious... but I don't see it :)

**Comment by NickM-27** [comment]
Reolink cameras are known to have awful RTSP realization. You should either follow the docs for reolink cameras https://docs.frigate.video/configuration/camera_specific#reolink-cameras or you should contact reolink support to get a firmware which has fixed the RTSp issues.

**Comment by georgbachmann** [comment]
Unfortunately it seems as if I am already on the latest firmware for my camera which is from March 2021 :(
I'll try out the settings you linked and will also now add my second camera (an Annke camera) and see if there is a difference in the recordings.
Again... thanks for your super fast help!
I'll close the issue for now and will re-open if I need more help if that's ok :)

**Comment by NickM-27** [comment]
> Unfortunately it seems as if I am already on the latest firmware for my camera which is from March 2021 :(

You misunderstand. Reolink has firmware which is not yet released and fixes these issues. You just need to ask. I have done this for multiple cameras. 

> I'll try out the settings you linked and will also now add my second camera (an Annke camera) and see if there is a difference in the recordings.
> 
> Again... thanks for your super fast help!

> I'll close the issue for now and will re-open if I need more help if that's ok :) 

Let's just leave it open until there's a resolution.

**Comment by BlueArcherX** [comment]
Probably the related fix is due to the iframe bugs they had. They released a beta version of the firmware with this fix and posted about it on the Reolink subreddit, but that was a LONG time ago, and they seem to have moved on to new cameras rather than continuing to support the old ones.

I hate that I chose Reolink cameras to be honest.

https://www.reddit.com/r/reolinkcam/comments/qkdgyr/beta_firmware_test_for_iframe_iframe_for_nonai/

**Comment by georgbachmann** [comment]
Ok... So I just sent an email to their support asking if they have any newer firmware, as my camera has lots of artifacts and streaming issues using the current version. Excited to see if they can help :)

**Comment by georgbachmann** [comment]
@BlueArcherX thx for that article!
And yes... I have also both my cameras setup for Scrypted (to bridge them to HomeKit) and my Annke in general opens up super quickly, while my reolink is suuuuuper slow...

**Comment by filipeaparicio91** [comment]
@georgbachmann, I've been using Frigate exclusively with Reolink cameras and the RTSP feeds are always problematic.
Use HTTP feeds instead, as they work flawlessly:
- Main feed
```
- path: http://YOUR.CAMERA.IP.ADDRESS/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=USERNAME&password=PASSWORD
```

- Sub feed
```
- path: http://YOUR.CAMERA.IP.ADDRESS/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=USERNAME&password=PASSWORD
```

Please keep in mind that if your stream uses h265, it will not work for the `rtmp` role, but it works for `record` (h265 playback needs to be supported by your device though).

Please include the following `ffmpeg input_args` as well:
```
input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
```

This should do the trick. If you need any more help, let me know!

**Comment by NickM-27** [comment]
The http-flv standard does not support h265 so if your reolink camera is h265 and you want to use http you need to lower the resolution so it will use h264
