### ISSUE TITLE
Unable to connect to MQTT server: timed out

### ISSUE THREAD

**Issue by dimmanramone** [blakeblackshear/frigate#5629]
### Describe the problem you are having

Hi,

I just started setting up frigate and I'm stuck with the following error

`[2023-03-02 17:04:52] frigate.mqtt ERROR : Unable to connect to MQTT server: timed out`

which is causing an endless loop of restarts.

I'm using exactly the same host ip and crendentials with 3 instances of room-assistant and home assistant and I don't have any problems connecting in the mqtt broker.

Everything is running i docker containers in a QNAP NAS (home assistant, mqtt and frigate). Home assistant and mqtt are in the same docker subnet. but not frigate (if any case this is the problem, that it shouldn't I guess).

### Version

Latest

### Frigate config file

```yaml
mqtt:
  host: ip
  user: user
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person

cameras:
  canera1:

  camera2:
```

### Relevant log output

```shell
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-03-02 18:13:36] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
Starting migrations
[2023-03-02 18:13:36] peewee_migrate                 INFO    : Starting migrations
[2023-03-02 18:13:36] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
[2023-03-02 18:13:36] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
There is nothing to migrate
[2023-03-02 18:13:36] peewee_migrate                 INFO    : There is nothing to migrate
[2023-03-02 18:13:41] frigate.mqtt                   ERROR   : Unable to connect to MQTT server: timed out
timed out
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts..
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
If you get a shell in the container can you ping the MQTT server?

Have you tried looking at the logs on the MQTT broker?

**Comment by NickM-27** [comment]
You just need to start the container with a different command than the default so it doesn't stop. and if there are no logs directly pointing to frigate in mqtt then that could very well mean frigate is unable to communicate with mqtt, pointing to a network / fiirewall issue

**Comment by dimmanramone** [comment]
@NickM-27 I just changed the container configuration to 

`network_mode: host`

and everything started to work. So it seems to have something to do with the network configuration of the container

**Comment by NickM-27** [comment]
If an outgoing connection isn't working except in host mode then it's something in the docker network / communication not letting frigate connect unless it is using the hosts network interface. There's not enough information given about the setup to have suggestions to make.

**Comment by dimmanramone** [comment]
I'll do my best to describe the setup.

Docker Compose App  #1 (Subnet 10.10.0.x)
- Home Assistant (Connecting to broker with 192.168.1.100)
- Mqtt Broker

Docker Compose App #2 (Subnet 10.10.1.x)
- Frigate

Both of them are running in a QNAP NAS with IP 192.168.1.100 and all the container are accessible with 192.168.1.100:port

3 RPis running Room Assistant docker containers.
Pi 1: 192.168.1.101  (Connecting to broker with 192.168.1.100)
Pi 2: 192.168.1.102  (Connecting to broker with 192.168.1.100)
Pi 3: 192.168.1.103  (Connecting to broker with 192.168.1.100)

**Comment by NickM-27** [comment]
And what ip are you using in the frigate config?

**Comment by dimmanramone** [comment]
I did try with both 192.168.1.100 and 10.10.1.2 when I was getting the timed out error.

Now with `network_mode: host` I use 192.168.1.100 and works fine
