### ISSUE TITLE
Should `sub_labels` be included in `api/events/summary` ?

### ISSUE THREAD

**Issue by dermotduffy** [blakeblackshear/frigate#5639]
I'm trying to implement `sub_label` support in the card (https://github.com/dermotduffy/frigate-hass-card/issues/900). To do this, I need to fetch the available sub_labels. 

I had assumed they would show up in the event summary information, but they don't. So there are two paths:

* Add `sub_labels` to `api/events/summary` information (this has the advantage that the integration media browser could do drilldowns by sub_label).

* Proxy the `api/sub_labels` call from card -> integration -> Frigate.

Personally, I think the first option is the better one, but there may be a good reason why it's not included in the event summary info?

**Comment by NickM-27** [comment]
There's no explicit reason it isn't included in the summary, but how do you figure it would work? Just create a list of all names that are included in that particular day?

**Comment by dermotduffy** [comment]
> There's no explicit reason it isn't included in the summary, but how do you figure it would work? Just create a list of all names that are included in that particular day?

Exactly. I already need to fetch the event summary on my end (and it's already proxied), so calculating the complete list of sublabels would simply be `uniq`ing the full set of sublabels returned by the summary.

**Comment by NickM-27** [comment]
Sounds good to me then, seems consistent with things. Is that something you can put a PR up for? Otherwise I may have some time tomorrow morning.

**Comment by dermotduffy** [comment]
> Sounds good to me then, seems consistent with things. Is that something you can put a PR up for?

Absolutely.
