### ISSUE TITLE
Docker Container Support for User / Group Env. Variables

### ISSUE THREAD

**Issue by xstream25** [blakeblackshear/frigate#564]
**Describe the bug**
Now that frigate requires write access for the database file, I've been struggling with getting container permissions to work properly. Would it be possible to add environment variables to support the container to run as a custom user/group - i.e. something like -e PUID=1000 -e PGID=1001

**Version of frigate**
8.0RC

**Comment by blakeblackshear** [comment]
Possibly. This will likely create other permissions issues when trying to access a Coral device or the video card for hardware acceleration.
