### ISSUE TITLE
Disable detection for a specific object

### ISSUE THREAD

**Issue by albinmedoc** [blakeblackshear/frigate#5646]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to disable detection for a specific object separately.

**Describe the solution you'd like**
I would like to have a switch entity for every object detection so I can disable only one of them. 

**Describe alternatives you've considered**
Setup multiple cameras in frigate with the same stream, but a single (different) object detection for each. This would require more computing power.

**Comment by NickM-27** [comment]
Can you describe more about the usecase for this? In what situations would a user want to disable detection for one object type?

**Comment by albinmedoc** [comment]
I have a camera in my garden. It's setup to detect and record persons and cats. 

* When a cat is detected my HomePod says to my kids that there is a cat in the garden (they love cats).
* And the person detection I want to be able to record any thieves when I'm not home. 

**What I want** is to have the cat detection enabled when I'm home and the person detection enabled when I'm not home. 

**Currently** it records us when we are it the garden (we are there a lot) and fills up my hardrive.

**Comment by albinmedoc** [comment]
Maybe this is not the best use case. But I think this should be easy integrated. Isn't the detection for the objects handled separately?

**Comment by NickM-27** [comment]
I don't think it would be easy, there's a lot of unseen legwork getting the switch state into the process which handles detection. Then adding one for each label would be something to work through as well. 

I see your point though about the request. For now I'd suggest disabling recording while home may suffice.

**Comment by ericgullickson** [comment]
I'd second this request. I have a situation where every week we have cleaners come to the house. I have a camera that watches the driveway. When the cleaners are here they park on the driveway and the entire time they are here I get notified of a car. My choice is either disable all detection, which I have been doing, or just deal with the alerts. It would be amazing to just disable car detection when they are here. 

Similarly whenever we have guests over. I don't need to be notified that their car is in my driveway. That situation as well I tend to just disable all detection.
