### ISSUE TITLE
Docker images not available for latest 0.12.*-beta versions

### ISSUE THREAD

**Issue by nabheet** [blakeblackshear/frigate#5649]
**Describe what you are trying to accomplish and why in non technical terms**
Looks like docker hub does not have the latest beta version images. Could it be possible to get them uploaded to docker hub? I am trying to build an image and its been an hour with not end in sight. 

**Describe the solution you'd like**
Docker Hub should have latest beta version images.

**Describe alternatives you've considered**
I tried to build it myself and it is taking a long long time.

**Additional context**
N/A

**Comment by kirsch33** [comment]
it got buried i think but see the following comments from the v0.12 beta 3 release:

> We have decided to stop publishing builds to Dockerhub and new builds will be available exclusively on GHCR going forward. Please update to use the new image locations by adding ghcr.io/ in front of your image names. (blakeblackshear/frigate:0.12.0-beta3 needs to be changed to ghcr.io/blakeblackshear/frigate:0.12.0-beta3)

**Comment by jurasjo** [comment]
https://github.com/blakeblackshear/frigate/pkgs/container/frigate/versions?filters%5Bversion_type%5D=tagged

**Comment by nabheet** [comment]
NOICE! thank you! I will give these a shot.
