### ISSUE TITLE
FR: Timestamps in LOG file

### ISSUE THREAD

**Issue by cybertza** [blakeblackshear/frigate#566]
**Describe the bug**
Show Timestamps at the start of the log sentence.

**Version of frigate**
blakeblackshear/frigate:0.8.0-rc1-amd64nvidia

Rest of the information is not relevant for this.

**Comment by blakeblackshear** [comment]
Are you using the addon?

**Comment by cybertza** [comment]
Guess the questions was important. 

I’m running inside an unraid docker.

**Comment by blakeblackshear** [comment]
Docker already keeps the timestamps of log messages. `docker logs -t frigate` will get the logs with timestamps.

**Comment by cybertza** [comment]
Ok, Thanks, I'll address it in the unraid forum for the view,

![image](https://user-images.githubusercontent.com/20600538/105233792-fdf4a480-5b72-11eb-9daf-3af264ba0907.png)

**Comment by cybertza** [comment]
For unraid, run:
```
docker logs -tf frigate
```
will show time next to the log file
