### ISSUE TITLE
[Support]: Issue with Folder Names being UTC time and not local

### ISSUE THREAD

**Issue by tkffaul** [blakeblackshear/frigate#5691]
### Describe the problem you are having

Frigate is saving files in the recordings by UTC time. I've checked and inside the docker container the time is correct. All recordings show the right time in frigate... but the folders are all wrong. Am i missing something? I tired a few settings but my 11 folders were all correct.

### Version

0.12.0-beta9

### Frigate config file

```yaml
This is huge and not necessary for this.
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink

**Comment by blakeblackshear** [comment]
This is by design and there isn't a way to change it.

**Comment by tkffaul** [comment]
Thanks Blake, just wanted to make sure i wasn't screwing up somewhere.
