### ISSUE TITLE
Consider implementing object detection without full decoding of h264

### ISSUE THREAD

**Issue by filip-zyzniewski** [blakeblackshear/frigate#5704]
**Describe what you are trying to accomplish and why in non technical terms**

It would be nice to try the approach similar to the one described in https://arxiv.org/abs/1811.11057.
This could lower hardware and power requirements considerably.

**Describe the solution you'd like**

Instead of the current approach where the video is decoded into separate frames and inferences are ran on these frames,
we could try running inferences on partially decoded streams.
Motion information in the h264 stream could be used to aid motion detection (both whether it has occurred and where it has taken place in the frame(s)).

**Comment by filip-zyzniewski** [comment]
Should I just bump it with a comment to avoid the stale label?

**Comment by filip-zyzniewski** [comment]
Bump.

**Comment by NickM-27** [comment]
Just wanted to note in your post 

> Motion information in the h264 stream could be used to avoid running object detection on a full frame

Frigate does not do this. It only runs object detection on areas where motion occurs.

**Comment by filip-zyzniewski** [comment]
> Frigate does not do this. It only runs object detection on areas where motion occurs.

Thanks, my statement was misleading.

How does it determine where the motion occurs? My assumption was that it compares whole frames to find motion - even though h264 already contains information about changes frame-to-frame.

**Comment by NickM-27** [comment]
> How does it determine where the motion occurs? My assumption was that it compares whole frames to find motion - even though h264 already contains information about changes frame-to-frame.

Frigate runs motion detection on the full frame but it employs many tactics to only find **useful** motion. This effort has even been expanded further for the next release (0.13) in https://github.com/blakeblackshear/frigate/pull/6741 where motion like camera changing IR modes, lightning, PTZ moves, etc. won't be seen as motion. The same PR also reduced CPU usage of motion detection further. Other improvements are also planned like ignoring rain / snow as well.

That type of granularity can't come without knowing what the full frame looks like so Frigate knows what the background is to understand what the source of motion really is.

**Comment by filip-zyzniewski** [comment]
> That type of granularity can't come without knowing what the full frame looks like so Frigate knows what the background is to understand what the source of motion really is.

Do you think that h264 motion information is not helpful for this?
Like not running motion detection if there is no motion (or tiny amount) reported in h264, or feeding the h264 motion information into the algorithms implementing the tactics you are describing. 

I am not suggesting discarding the full frame, but just avoiding some (or even most) operations done on the decoded stream.

**Comment by blakeblackshear** [comment]
I have thought about this too, but it would be a very large undertaking. All of the work would have to be done upstream of the decoder on the raw stream and then only pass video data to the process to decode conditionally. Also, not all cameras are h264, so this would have to support h265 and every variation of codec (h265+, mjpeg) we see. We would either end up needing to handle every possible variation or only support this for a limited set of codecs and maintain two implementations of motion and object detection. 

It would be cool, but this feels like something that would require complete control over the camera hardware. If you have that level of control, you would just implement motion/object detection before encoding to h264 anyway.

This feature is in the "maybe someday, but probably not" bucket.

**Comment by filip-zyzniewski** [comment]
> This feature is in the "maybe someday, but probably not" bucket.

That sounds reasonable, thank you for your explanation!
