### ISSUE TITLE
[HW Accel Support]: UNRAID using the wrong GPU

### ISSUE THREAD

**Issue by sohail579** [blakeblackshear/frigate#5712]
### Describe the problem you are having

The wrong GPU is being used for hardware transcoding

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
N/A
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

hikvision

### Any other information that may be helpful

I have changed the config of my docker I have added the below to my extra parameters

--runtime=nvidia

 and then the following two parameters as variables

NVIDIA_DRIVER_CAPABILITIES: all
NVIDIA_VISIBLE_DEVICES: [My device ID from the NVIDA Driver]: GPU-aa990942-1de0-de99-3ab0-6e5a105dbcea

 I have added the correct ID for the GPU but for some reason its using the other GPU what have i done wrong?  also when i have noticed is that when I reboot my server sometimes it will use the correct GPU its seems to be pot luck as to which GPU its using

**Comment by yayitazale** [comment]
This way of defining GPUS is supported by nvidia runtime:

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html

Not sure if this is something realted with the nvidia support in unraid or realted to the implementation on frigate docker.
