### ISSUE TITLE
Config error when using experimental_ui

### ISSUE THREAD

**Issue by ehn** [blakeblackshear/frigate#5717]
### Describe the problem you are having

Trying to set `experimental_ui: True` as [documented](https://deploy-preview-4055--frigate-docs.netlify.app/configuration/) when editing the config file in the web UI leads to a config error:

```
Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 761, in config_save
    new_yaml = FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1075, in parse_raw
    return cls.parse_obj(config)
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
ui -> experimental_ui
  extra fields not permitted (type=value_error.extra)
```

In the embedded VS Code frame, `experimental_ui` gets a yellow wriggly underline and this note: `Property experimental_ui is not allowed. yaml-schema: UIConfig(0)`.

Not sure if the bug is in the documentation (and this setting simply doesn't exist in this version of Frigate) or in the YAML schema.

### Version

0.12.0-E8D8CC4

### Frigate config file

```yaml
ui:
  # Optional: Use an experimental recordings / camera view UI (default: False)
  experimental_ui: True
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

N/A

**Comment by blakeblackshear** [comment]
It's a typo in the docs. It should be `use_experimental`. To be honest, none of the maintainers use that UI and its likely to be removed rather than maintained in the future.

**Comment by kirsch33** [comment]
@blakeblackshear i thought that the timeline feature that the experimental UI added was something you've been wanting to implement? its pretty similar to this request, no?  https://github.com/blakeblackshear/frigate/issues/2230

**Comment by blakeblackshear** [comment]
I personally don't find the current implementation useful. I do still want to implement more of a timeline view, but in a different way.
