### ISSUE TITLE
webrtc simulcast

### ISSUE THREAD

**Issue by joukio** [blakeblackshear/frigate#5734]
IMHO it would be a really big improvement to be able to use webrtc simulcast in Frigate for both live viewing and watching recordings.
Even though I have a pretty decent phone and uplink, the streams are still sometimes buffering/lagging/stuttering. Mainly I guess because the streams are 2k and 4k h264, but still.

**Comment by joukio** [comment]
ok I will. I can imagine this would be true for the live viewing part, but would it also be true for viewing recordings?

**Comment by blakeblackshear** [comment]
Viewing recordings doesnt use webrtc.
