### ISSUE TITLE
[Support]: docker: failed to register layer: ApplyLayer exit status 1

### ISSUE THREAD

**Issue by 2Belette** [blakeblackshear/frigate#5736]
### Describe the problem you are having

docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/lib/locale/C.UTF-8/LC_MESSAGES: invalid argument.

### Version

0.12.0-beta9

### Frigate config file

```yaml
not even able to reach this point
```

### Relevant log output

```shell
not even able to reach this point
```

### FFprobe output from your camera

```shell
not even able to reach this point
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

UNV

### Any other information that may be helpful

Trying to docker run and got this issue.
Alpine Linux 3.17, tried to install musl-locales but same issue.
Same issue on Debian
Thanks

**Comment by fsedarkalex** [comment]
For anyone encountering - and finding this...

I had the same issue. The cause was extremely high IOWait caused by a driver issue.

In my case, I am running frigate in docker on an LXC container (on Proxmox).
The solution: use overlay2 as storgae driver in docker.
