### ISSUE TITLE
[Support]: direct URL for camera?

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#5740]
### Describe the problem you are having

When motion is detected on a camera, such as driveway_person_occupancy, I am using node red to get the camera image as such

```json
{
    "message": "",
    "data":{
        "image": $entities(camera).attributes.entity_picture,
        "url": "/ccab4aaf_frigate-fa-beta/dashboard",
        "clickAction": "/ccab4aaf_frigate-fa-beta/dashboard"
    }
}
```

This works, but as you can see, the url/clickAction points to the dashboard. I would like it to take the person directly to the camera, but I cannot find a url that will allow that. When clicking on a specific camera in hassos/frigate it keeps the dashboard url the same. 

### Version

12

### Frigate config file

```yaml
?
```

### Relevant log output

```shell
?
```

### FFprobe output from your camera

```shell
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

amcrest

**Comment by NickM-27** [comment]
This seems like a request for the addon as it has nothing to do with frigate directly. You can also link to a dashboard with the frigate card having a specific camera selected (as of the latest dev versions)
