### ISSUE TITLE
Is it possible run detectors remotely?

### ISSUE THREAD

**Issue by lovelylain** [blakeblackshear/frigate#5766]
**Describe what you are trying to accomplish and why in non technical terms**
I have an arm box, I installed frigate on it and it works, but the cpu load is very high.
Is it possible run detectors on another machine to reduce local cpu load?

**Describe the solution you'd like**
Remote machine detect events and push to mqtt, local machine get events from mqtt and trigger record.
I have tried but local frigate  didn't handle the events.

**Comment by blakeblackshear** [comment]
No. Latency is too high to send detections to a remote machine.
