### ISSUE TITLE
[0.8.0-rc3] 404 error on event page of Admin webui under HassIO

### ISSUE THREAD

**Issue by fanningert** [blakeblackshear/frigate#577]
**Describe the bug**
When I click on a single event (not image, camera link or label link) over the event page of the admin web ui, I get a 404 error message. When I click on the image, I get the details of the event

**Version of frigate**
Frigate 0.8.0-rc3

**Screenshots**
![Bildschirmfoto von 2021-01-21 17-25-06](https://user-images.githubusercontent.com/365219/105380304-04842a00-5c0e-11eb-8ff3-67293df82e59.png)
![Bildschirmfoto von 2021-01-21 17-27-50](https://user-images.githubusercontent.com/365219/105380398-1fef3500-5c0e-11eb-94d4-6d7397ae838b.png)

**Computer Hardware**
 - OS: HassIO
 - Virtualization: Proxmox
 - Coral Version: USB
 - Network Setup: Wired

**Comment by paularmstrong** [comment]
I think this is a weird route-capturing thing with HA ingress. Should be able to look into it soon.

**Comment by blakeblackshear** [comment]
Should be resolved in RC6
