### ISSUE TITLE
[Bug]: Error writing trailer log line is missing substitutions

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5794]
### Describe the problem you are having

I sometimes see this in my log:

`2023-03-21 16:45:42.528181936  [2023-03-21 16:45:42] ffmpeg.sewing.record           ERROR   : Error writing trailer of /tmp/cache/sewing-%Y%m%d%H%M%S.mp4: No space left on device`

Ignoring that /tmp/cache is out of space (I'm currently figuring out how to increase that), the log line should be the final file name with timestamp substituted in, not the template.

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
2023-03-21 16:45:42.528181936  [2023-03-21 16:45:42] ffmpeg.sewing.record           ERROR   : Error writing trailer of /tmp/cache/sewing-%Y%m%d%H%M%S.mp4: No space left on device
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
This is an error directly from ffmpeg, it is working as expected

**Comment by ccutrer** [comment]
oh, ok.
