### ISSUE TITLE
Ability to detect and decode from previously saved video files?

### ISSUE THREAD

**Issue by pdarcos** [blakeblackshear/frigate#5797]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to continue using my unifi protect setup and have frigate parse the recorded video files instead of doing its magic from the camera stream. I can't find any info on this so maybe it is already possible?
The reason for this is I'm happy with my UDM and unifi protect setup for recording, but I don't like their detection software.
I was hoping instead to be able to just point frigate to the share holding the unif recorded video and run its detection software on the video files already stored by unifi.

**Describe the solution you'd like**
The ability to use frigate to analyze previously recorded video instead of real time streams from the cameras.

**Comment by NickM-27** [comment]
This is already possible https://deploy-preview-4055--frigate-docs.netlify.app/development/contributing#2-modify-your-local-config-file-for-testing

it wouldn't be automated though and you would need to handle that part yourself. it would also need to be real time and not fast-forwarded detection.

I am not sure what you are describing is really within the scope of frigate

**Comment by pdarcos** [comment]
Thanks for the fast reply @NickM-27 

I'm going to take a look at that link and play around to see if it's good enough for my use case.

Not sure if it is within the scope but I imagine lots of others have video from other platforms that they'd like to use frigate on.

Cheers
