### ISSUE TITLE
Camera cover/blind detection

### ISSUE THREAD

**Issue by evolucja** [blakeblackshear/frigate#5804]
Hi, I had a case that someone simply covered the camera with some clothing so it became blind.

Is there any chance to implement a detection algorithm for such cases to prevent moving or masking the camera?

Simple movement/people detection is not enough as the camera is in a place with constant movement, people walking through etc.

Thanks

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1793 feel free to leave additional comments there and support with a 👍
