### ISSUE TITLE
Tag recordings to exclude from deletion

### ISSUE THREAD

**Issue by clinta** [blakeblackshear/frigate#5805]
**Describe what you are trying to accomplish and why in non technical terms**
When reviewing recordings if I find a recording of interest, I'd like to make sure that recording is not deleted without having to download and copy it to another location.

**Describe the solution you'd like**
When browsing recordings and events, I'd like to tag a video to exclude it from being deleted when it falls out of retention, or storage space gets low.

**Describe alternatives you've considered**
Manually downloading and categorizing recordings of interest into another system. But now this recording is no longer visible in frigate.

**Comment by clinta** [comment]
> This is already supported for events

Does starring an event do this? Is this documented anywhere? I tried to search documentation to find out if this was already possible.

**Comment by NickM-27** [comment]
Yes that's what starring an event means (internally it is referred to as favorite). The api is documented but generally the UI itself is not covered in the documentation.

**Comment by clinta** [comment]
Thanks. I thought favorite was just to filter events, I didn't realize it made sure it wouldn't be deleted. This covers my needs.
