### ISSUE TITLE
[Support]: Running Coral TPU process on a different server from the GPU/Stream decode

### ISSUE THREAD

**Issue by velaar** [blakeblackshear/frigate#5808]
### Describe the problem you are having

As formulated in the subject line. I have Coral TPUs in an M.2 format available on Server A with no additional expansion slots.  I have an Nvidia GPU in a Server B that can be used for stream decoding and movement detection. Is this setup possible? 

As the overhead of transferring 320x320 picture 2 times over 20 Gbps network should be insignificant at best. 

### Version

Not applicable

### Frigate config file

```yaml
Not applicable
```

### Relevant log output

```shell
Not applicable
```

### FFprobe output from your camera

```shell
Not applicable
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Not applicable

**Comment by blakeblackshear** [comment]
It's not possible, and it will be more significant than you think. If copying the data and sending over the network adds 10ms, then you might as well just use openvino or tensorrt on the same machine.
