### ISSUE TITLE
[Support]: Unable to "make build_web" on v0.11.1

### ISSUE THREAD

**Issue by tranzmatt** [blakeblackshear/frigate#5827]
### Describe the problem you are having

After cloning frigate and checking out v0.11.1, I attempt to run "make build_web", but get the following error

`theuser@linuxbox:~/Code/Frigate/frigate$ make build_web
docker run --volume /home/theuser/Code/Frigate/frigate/web:/web -w /web --volume /etc/passwd:/etc/passwd:ro --volume /etc/group:/etc/group:ro -u 1000:1000 node:16 /bin/bash -c "npm install && npm run build"
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/theuser
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/theuser'
npm ERR!  [Error: EACCES: permission denied, mkdir '/home/theuser'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/theuser'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! Log files were not written due to an error writing to the directory: /home/theuser/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
make: *** [Makefile:12: build_web] Error 243`

### Version

0.11.1

### Frigate config file

```yaml
None, did not get that far.
```

### Relevant log output

```shell
None, did not get that far
```

### FFprobe output from your camera

```shell
None, did not get that far
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
Closing as this is fixed in dev. Feel free to [create a discussion](https://github.com/blakeblackshear/frigate/discussions) if you run into other issues building the dev container
