### ISSUE TITLE
[Support]: Bugfix: Scrollbar issue breaks Cameras view at certain resolutions

### ISSUE THREAD

**Issue by mscott5861** [blakeblackshear/frigate#5852]
### Describe the problem you are having

This is identical to Issue #1657, which seems to have been marked closed (https://github.com/blakeblackshear/frigate/issues/1657) without resolution.

Once I expanded to 4 cameras (all Amcrest, all 1920x1080), this started happening to my camera view. The cameras themselves are working great, but just like in the above Issue, the Camera view flickers rapidly on page load, endlessly, and no thumbnails for the cameras ever manage to render.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest, various

**Comment by NickM-27** [comment]
> This is identical to Issue https://github.com/blakeblackshear/frigate/issues/1657, which seems to have been marked closed (https://github.com/blakeblackshear/frigate/issues/1657) without resolution.

No? As it says in the issue, this has been fixed in 0.12

**Comment by mscott5861** [comment]
Sorry, missed that somehow.

**Comment by NickM-27** [comment]
No problem, feel free to create a new issue if something else comes up
