### ISSUE TITLE
[Config Support]: Remote storage

### ISSUE THREAD

**Issue by ztardik** [blakeblackshear/frigate#5855]
### Describe the problem you are having

I have a Frigate server (A) in one location (EU), now I need to add two additional cameras located on another continent (server B, Asia). 
The main server is connected to the internet over metered connection, so connecting the streams directly is not an option (too much data). I want to transfer only the event recordings from a local detector running on B. Due to instability in connection I cannot just mount a folder from A to B, I need somehow tell A to accept recordings from B.

I have a VPN tunnel between A and B.

Thanks

### Version

0.11.1-2eada21

### Frigate config file

```yaml
standard rtsp, nothing fancy
```

### Relevant log output

```shell
none
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by banthungprong** [comment]
There is no solution with these "conditions":
- metered connection
- frigate offers no "local detector" separated from the rest of the engine.
- instability of connection

My way for this scenario (until my next holiday in Thailand).
- frigate on Mini-PC in Germany
- cameras in Thailand
- not using VPN anymore, using a DDNS for the configuration in frigate. Resulted in better quality.
- reduced resolution/bitrate (but still using Full HD in 5 cameras and even one 4K)

This works without any problems for many months now. When the connection is down, it is down. Nothing to solve here.

Only real solution: carry the frigate-HW to Asia, connect your cameras directly to the frigate server (assuming a flat rate there).

**Comment by ztardik** [comment]
> There is no solution with these "conditions":
> 
> * metered connection
> * frigate offers no "local detector" separated from the rest of the engine.

Maybe I didn't expressed myself correctly. There are two frigate installs (one in EU - A, another in Asia - B). I want to transmit events and recordings to the A from B (VPN or direct connection, doesn't matter).

The B is a small mini PC with limited resources, while A is a real server with tens of TB storage. Also, in case something happens and the footage is left on the B, it's easily stolen before I can react.

When I was talking about instability, I meant that sharing a folder over internet is not stable option. It doesn't matter what technology you use (samba, NFS...) and what type of connection you use, it will cause problems.

I can always set up rsync or similar, but that doesn't bring the data into the existing frigate.
