### ISSUE TITLE
[Support]: Unable to save Config File through GUI 

### ISSUE THREAD

**Issue by Buckeyes1995** [blakeblackshear/frigate#5887]
### Describe the problem you are having

My config.yml and the entire directory structure is set to 777, yet I always get:

`Could not write config file, be sure that Frigate has write permission on the config file.`

Is there something else I need to do to be able to edit and save in the GUI?

### Version

0.12.0-e454daf

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

HITSINO 8MP

**Comment by NickM-27** [comment]
As the release notes say, you need to remove the `:ro` which puts the config in read only mode.

**Comment by Buckeyes1995** [comment]
Yeah.. sorry, reading comprehension. Thanks.
