### ISSUE TITLE
[Support]: Cannot use custom go2rtc in 0.12.0-rc2

### ISSUE THREAD

**Issue by luisiam** [blakeblackshear/frigate#5896]
### Describe the problem you are having

I am trying to import custom go2rtc binary into /config directory but frigate still loads the embedded one. The binary can be seen under /confg.

![image](https://user-images.githubusercontent.com/16310467/229372337-ec92f36a-fb94-416b-bc29-eb7d5a14fc8d.png)

### Version

0.12.0-BC16AD1

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
2023-04-02 11:32:28.727658590  [INFO] Preparing go2rtc config...
2023-04-02 11:32:29.500392131  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-04-02 11:32:29.548895267  [INFO] Starting go2rtc...
2023-04-02 11:32:29.666857293  11:32:29.664 INF go2rtc version 1.2.0 linux/amd64
2023-04-02 11:32:29.666862062  11:32:29.664 INF [api] listen addr=:1984
2023-04-02 11:32:29.666875255  11:32:29.665 INF [rtsp] listen addr=:8554
2023-04-02 11:32:29.666877624  11:32:29.665 INF [srtp] listen addr=:8443
2023-04-02 11:32:29.667131421  11:32:29.665 INF [webrtc] listen addr=:8555
2023-04-02 11:32:38.727662328  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
What is your docker compose file?

Most likely you are not passing the go2rtc binary into the container.

**Comment by luisiam** [comment]
The CLI snapshot is coming from inside the docker. So the binary can be seen within the docker itself.
```
  frigate:
    container_name: frigate
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - FRIGATE_RTSP_USERNAME=xxx
      - FRIGATE_RTSP_PASSWORD=xxx
      - FRIGATE_MQTT_USERNAME=xxx
      - FRIGATE_MQTT_PASSWORD=xxx
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta9
    network_mode: bridge
    ports:

      - 192.168.10.3:5000:5000
      - 192.168.10.3:8554:8554
      - 192.168.10.3:8555:8555
      - 192.168.10.3:8555:8555/udp
    privileged: true
    restart: always
    shm_size: "128mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/fg-config:/config
      - /share/Recording/fg-media:/media/frigate
```

**Comment by NickM-27** [comment]
Does it have the correct execute permissions set on it?

This is working fine for me so I expect it is some kind of file system issue or something.

**Comment by luisiam** [comment]
Oh you are right. Haven't set the execute permission on the binary. It works after running `chmod +x go2rtc`. I am not an expert in Linux file system. Thank you for your help.
