### ISSUE TITLE
Process keyframes only

### ISSUE THREAD

**Issue by ivelin** [blakeblackshear/frigate#59]
@blakeblackshear  I ran some experiments extracting only keyframes instead of extracting a frame every 2 seconds. It seems like its about 50% faster. 

Another potential advantage to using keyframes other than processing time is that they are a full  image capture and don't include compression artifacts that could fool the AI. 

Here is my script and test results in case you'd like to consider it:

```
INPUT_FILE=front-door-camera-3.mp4
OUTPUT_DIR=keyframes

# extract keyframes only
time ffmpeg -i $INPUT_FILE -vf "select=eq(pict_type\,I)" -vsync vfr $OUTPUT_DIR/kframe%04d.jpg -hide_banner

# extract a frame every 2 seconds
time ffmpeg -i $INPUT_FILE -vf fps=1/2 $OUTPUT_DIR/half_fps%04d.jpg -hide_banner
```

```bash
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'front-door-camera-3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : RTSP/RTP stream from anjvision ipcamera
    encoder         : Lavf58.20.100
  Duration: 00:00:59.93, start: 0.000000, bitrate: 5041 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc), 2592x1944, 5000 kb/s, 15.02 fps, 15 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 39 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'keyframes/kframe%04d.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : RTSP/RTP stream from anjvision ipcamera
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 2592x1944, q=2-31, 200 kb/s, 15 fps, 15 tbn, 15 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.35.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
[h264 @ 0xa404a0] error while decoding MB 104 42, bytestream -5A speed=0.133x    
[h264 @ 0xa404a0] concealing 12905 DC, 12905 AC, 12905 MV errors in P frame
frame=   30 fps=1.0 q=24.8 Lsize=N/A time=00:00:58.06 bitrate=N/A speed=2.02x     
video:12512kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

real	0m29.299s
user	1m16.481s
sys	0m1.419s
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'front-door-camera-3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : RTSP/RTP stream from anjvision ipcamera
    encoder         : Lavf58.20.100
  Duration: 00:00:59.93, start: 0.000000, bitrate: 5041 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc), 2592x1944, 5000 kb/s, 15.02 fps, 15 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 39 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'keyframes/half_fps%04d.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : RTSP/RTP stream from anjvision ipcamera
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 2592x1944, q=2-31, 200 kb/s, 0.50 fps, 0.50 tbn, 0.50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.35.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
[h264 @ 0x14c4480] error while decoding MB 104 42, bytestream -5
[h264 @ 0x14c4480] concealing 12905 DC, 12905 AC, 12905 MV errors in P frame
frame=   30 fps=0.8 q=24.8 Lsize=N/A time=00:01:00.00 bitrate=N/A speed=1.64x    
video:12942kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

real	0m37.326s
user	1m36.217s
sys	0m1.850s

```

Reference links:
- https://www.bugcodemaster.com/article/extract-images-frame-frame-video-file-using-ffmpeg

**Comment by ivelin** [comment]
I was able to confirm these positive results and found a further improvement with another version of the input parameters:

```
   - -skip_frame - nokey
```

ref: https://superuser.com/questions/669716/how-to-extract-all-key-frames-from-a-video-clip/1153483#1153483?newreg=0ab377d373314304a62780ee818aae63

Running frigate with this change on my system:
- RPI4 4GB RAM Raspbian Buster 10 
- Latest Homeassistant from docker image
- Latest frigate from source
- One hikvision camera rtsp streaming 720p
- One region with size 700

Results in under 10% CPU utilization at 1x ffmpeg processing rate:

```
ffmpeg log:
frame=  144 fps=0.3 q=-0.0 size=  388800kB time=00:07:09.80 bitrate=7410.5kbits/s speed=   1x 
```

```
top:
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND   
 8504 root      20   0  195392  40708  21904 S   8.9   1.0   0:35.71 ffmpeg                                                   
 8748 root      20   0       0      0      0 I   3.6   0.0   0:07.69 kworker/u8:4-events_unbound                              
 8398 root      20   0  351588 104972  41724 S   1.7   2.6   1:18.72 python3  
```

I can look at submitting a pull request if this is of interest.

**Comment by billimek** [comment]
I'm not having luck with just passing the `-skip_frame nokey` flag to ffmpeg,

```
ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -skip_frame nokey -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://<redacted>@pool:554/cam/realmonitor?channel=1&subtype=1 -f rawvideo -pix_fmt rgb24 pipe:
Creating a new capture thread...
Starting a new capture thread...
ffmpeg didnt return a frame. something is wrong. exiting capture thread...
ffmpeg didnt return a frame. something is wrong. exiting capture thread...
ffmpeg didnt return a frame. something is wrong. exiting capture thread...
```

... and it restarts over and over

**Comment by blakeblackshear** [comment]
This may work for some cameras and not others. Not all cameras have an adjustable I-frame rate. For my Dahua cameras, this effectively drops my frame rate to 1 per second because my camera can't be configured to have an I-frame rate lower than the FPS. Also, it's not really fair to compare the CPU usage here unless you lower your FPS to match the I-frame rate. My guess is that the reduced CPU usage is mostly due to a much lower effective FPS. I am working on adding hardware acceleration for the RPi in the next release. That should make a difference.

**Comment by steveneighbour** [comment]
using skipframe works fine for me on hikivision cameras but crashes repeatedly on reolink cameras using rtmp

**Comment by ivelin** [comment]
> This may work for some cameras and not others. Not all cameras have an adjustable I-frame rate. For my Dahua cameras, this effectively drops my frame rate to 1 per second because my camera can't be configured to have an I-frame rate lower than the FPS. Also, it's not really fair to compare the CPU usage here unless you lower your FPS to match the I-frame rate. My guess is that the reduced CPU usage is mostly due to a much lower effective FPS. I am working on adding hardware acceleration for the RPi in the next release. That should make a difference.

Yes, you are correct that its not a fair comparison. Key frames (I-frames) are built into h264 (and most popular video compression codecs) but their time spacing is dependent on the codec implementation. Usually occur every 2-5 seconds depending on how much change there is in the picture and other factors.

I spent some time trying to turn on ffmpeg with hardware acceleration on my RPI4, but so far no luck. 

When I run with CPU only, even at 0.5fps (a snapshot every 2 seconds), my CPU was still at around 40%. Skipping non-key frames brought it down to 8% and it still provides near-real time detection.

It may very well be the case that when hardware acceleration is available, that's the preferred way to go. For CPU only environments, this keyframe trick might be worth considering.

**Comment by ivelin** [comment]
> I'm not having luck with just passing the `-skip_frame nokey` flag to ffmpeg,
> 
> ```
> ffmpeg -hide_banner -loglevel panic -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -skip_frame nokey -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://<redacted>@pool:554/cam/realmonitor?channel=1&subtype=1 -f rawvideo -pix_fmt rgb24 pipe:
> Creating a new capture thread...
> Starting a new capture thread...
> ffmpeg didnt return a frame. something is wrong. exiting capture thread...
> ffmpeg didnt return a frame. something is wrong. exiting capture thread...
> ffmpeg didnt return a frame. something is wrong. exiting capture thread...
> ```
> 
> ... and it restarts over and over

@billimek  Thank you for sharing your observations. Looks like you are running with hardware acceleration, which I still can't get to work on my RPI4. 

What's  the hardware/OS that you run frigate on? Also which cameras are you testing with?

@steveneighbour reports problems with reolink streams. I am only able to test on my [whitelabel](https://www.amazon.com/gp/product/B07PNF7DQT/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1) hikvision compatible camera at the moment.

**Comment by billimek** [comment]
@ivelin in my case, it's an Odroid-H2 (x64-based device with intel iGPU acceleration).  The OS is ubuntu, but frigate itself is running as a kubernetes pod on that node with the TPU plugged-in.

The cameras are a mix of dahua and reolink so that may explain the issues w/iframe for my setup.

I am also eagerly hoping we can get HW acceleration with a RPI4 w/this solution - that would be awesome!

**Comment by ivelin** [comment]
@billimek that's good to know. See below:

> @ivelin in my case, it's an Odroid-H2 (x64-based device with intel iGPU acceleration). The OS is ubuntu, but frigate itself is running as a kubernetes pod on that node with the TPU plugged-in.
> 

I don't have an Odroid to test with at the moment. If you have the cycles, feel free to help debug the issue on Ordoid.

> The cameras are a mix of dahua and reolink so that may explain the issues w/iframe for my setup.

In the upcoming release #55 there will be ability to configure ffmpeg parameters per camera #61 . You can see what settings work well for which cameras. Based on that we can create preset templates for others to use in the future.

**Comment by scstraus** [comment]
> 
> 
> > This may work for some cameras and not others. Not all cameras have an adjustable I-frame rate. For my Dahua cameras, this effectively drops my frame rate to 1 per second because my camera can't be configured to have an I-frame rate lower than the FPS. Also, it's not really fair to compare the CPU usage here unless you lower your FPS to match the I-frame rate. My guess is that the reduced CPU usage is mostly due to a much lower effective FPS. I am working on adding hardware acceleration for the RPi in the next release. That should make a difference.
> 
> Yes, you are correct that its not a fair comparison. Key frames (I-frames) are built into h264 (and most popular video compression codecs) but their time spacing is dependent on the codec implementation. Usually occur every 2-5 seconds depending on how much change there is in the picture and other factors.
> 
> I spent some time trying to turn on ffmpeg with hardware acceleration on my RPI4, but so far no luck.
> 
> When I run with CPU only, even at 0.5fps (a snapshot every 2 seconds), my CPU was still at around 40%. Skipping non-key frames brought it down to 8% and it still provides near-real time detection.
> 
> It may very well be the case that when hardware acceleration is available, that's the preferred way to go. For CPU only environments, this keyframe trick might be worth considering.

As I wasn't able to get HW acceleration going on my synology and have hikvision cameras with adjustable keyframes, this could be useful to me if it gets the results you suggest. I'd be happy to try it if it makes it into the codebase.

**Comment by blakeblackshear** [comment]
There isn't anything to add to the code base for this one. You just have to modify your ffmpeg parameters in your config.

**Comment by scstraus** [comment]
Okay is the proper syntax just to pass 

-skip_frame nokey
