### ISSUE TITLE
Hikvision DS-2CD2183G2-IU RTSP Authentication[Camera Support]: 

### ISSUE THREAD

**Issue by grembling22** [blakeblackshear/frigate#5907]
### Describe the problem you are having

I recently purchased a new hikvision camera. Initially I was unable to add this camera to frigate.

After much troubleshooting  found that if I was using a password file for the cameras I could not authenticate to the camera. 
Example:
path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.72:554/Streaming/channels/103

If i removed {FRIGATE_RTSP_PASSWORD} and used the admin:password format rtsp://admin:password@192.168.1.72:554/Streaming/channels/103 I was able to connect to the camera without issue. This issue only occurred on a newer hikvision camera. 

### Version

11.1

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2183G2-IU

**Comment by bung69** [comment]
Suspect OP initaly used camera Admin account "hardcoded" in the config, and then swaped to a viewer only account using env variables.  when using a viewer only account i had to change RTSP Authentication to digest/basic  ( under system - security - authentication)   Web Auth seems to be fine left on digest whatever that is.
