### ISSUE TITLE
[Detector Support]: PCIe based corals for RPi

### ISSUE THREAD

**Issue by Steidy12** [blakeblackshear/frigate#5908]
### Describe the problem you are having

I have received a half size PCIe mini coral that I have put on a USB board https://www.amazon.com/dp/B00SR1YRA8?psc=1&ref=ppx_yo2ov_dt_b_product_details. I do not know if this will work through this adapter or not, but i am wondering if this should be ran as a PCIe or USB and if anyone has tried to do this before. I currently have a USB Coral on a pi4 and tried to put this on as a second, and yes I do have a powered hub that does work.

### Version

0.11.1-2ESDA21

### Frigate config file

```yaml
.
```

### docker-compose file or Docker CLI command

```yaml
.
```

### Relevant log output

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

PCIe

**Comment by NickM-27** [comment]
This won't work, the adapter has a SATA controller that maps PCIe calls to SATA.

**Comment by Steidy12** [comment]
Is there any way to make a PCIe work on the Pi4?

**Comment by NickM-27** [comment]
Not that i know of

**Comment by LaurenceGough** [comment]
> > Is there any way to make a PCIe work on the Pi4?
> 
> The CM4 has a PCIe bus connection so a CM4 + carrier board that provides a slot would do. Although hard to come by at the present moment so you're probably better off getting a cheap/second hand desktop.

There are known issues with the CM4 boards and PCIe Corals. Just make sure to research if it works before buying one. https://github.com/google-coral/edgetpu/issues/280#issuecomment-789093199 as an example.

I was going to go down this route but I read of so many issues, you're better off just buying a low powered Intel device, they aren't much more money and don't use that much more power, only a few more watts for machines at least twice as powerful.
