### ISSUE TITLE
[Support]: Thinking about any way to censor parts of the video from the recording

### ISSUE THREAD

**Issue by GiorgioUghini** [blakeblackshear/frigate#5909]
### Describe the problem you are having

I am using Frigate and I think this software absolutely rocks.
However, in my country it is required to censor from any video registration all public areas, meaning that you cannot record roads, walkways, etc...
My cameras point towards my house but still there's a tiny part of the image that should be removed from the recordings that I store on my HDD.
I saw that via ffmpeg it is possible to blur fixed portions of images/videos quite easily, but I am wondering how can I include this behavior inside frigate. Is there a way currently available to achieve this result?
Thank you,
Greetings

### Version

latest

### Frigate config file

```yaml
Not needed
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision

**Comment by NickM-27** [comment]
Yes, frigate gives full control to the user. Most likely you will just need to put the additional args in the 

```yaml
ffmpeg:
  output_args:
    record:
```

section

**Comment by LaurenceGough** [comment]
It might be worth checking your cameras as well, many cameras support this directly as it's a very common request. Apologies if you have already checked this.
