### ISSUE TITLE
/api endpoint not available in docker container

### ISSUE THREAD

**Issue by joshs85** [blakeblackshear/frigate#591]
**Describe the bug**
When the docker container is manually created using blakeblackshear/frigate:stable-amd64, the /api endpoint is not present preventing anyone from using the HACS plugin.

**Version of frigate**
docker blakeblackshear/frigate:stable-amd64

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Logs**
```
Include relevant log output here
```

**Frigate debug stats**
```
Output from frigate's /debug/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**

**Comment by InToSSH** [comment]
The HACS plugin is for v0.8.0+ which is currently in RC4 version.. You have to use `blakeblackshear/frigate:0.8.0-rc4-amd64` image.

**Comment by joshs85** [comment]
Aah, ok.  When I switch to that, I get an error complaining that my config has extra keys not allowed.. Is there documentation for the config somewhere?

**Comment by InToSSH** [comment]
Yes, here is the docs for new version: [https://blakeblackshear.github.io/frigate](https://blakeblackshear.github.io/frigate)
Quite a lot of stuff needs to be changed in your config for the new version.
If anything goes wrong while following the docs, save a backup for your config and start with bare minimum.
