### ISSUE TITLE
Beta docker image links to appropriate documentation

### ISSUE THREAD

**Issue by dasb00ter** [blakeblackshear/frigate#5934]
**Describe what you are trying to accomplish and why in non technical terms**
The beta docker image seems to link to old frigate support documentation. I am a new user and I am using the beta b/c it successfully incorporates my google coral, other versions dont work. While learning to use I clicked on the link in the menu which took me to the old documentation. This led to some confusion for quite abit time for me as a new user.

**Describe the solution you'd like**
clicking on the menu in beta frigate steers you to https://deploy-preview-4055--frigate-docs.netlify.app/ instead

**Additional context**
Thank you for this software and trying to incorporate other important things like go2rtc and webrtc into. I expect that with rapidly evolving software its very difficult to keep up on the documentation. Sorry if I have misunderstood so
mething leading me here but if I have not I hope its an easy correction to make.

![Screenshot (51)](https://user-images.githubusercontent.com/36972116/230725517-07d7be41-0689-4cce-bdad-cd72e4ef43b1.png)

**Comment by NickM-27** [comment]
The link will point to the stable docs. Once 0.12 is released it will point to the correct place because the stable docs will be updated.
