### ISSUE TITLE
[Support]: Failed to get WebRTC port from supervisor

### ISSUE THREAD

**Issue by Mikescotland** [blakeblackshear/frigate#5941]
### Describe the problem you are having

WebRTC working in 0.12 RC, however doesn't work with 0.12.
Getting
Failed to get WebRTC port from supervisor.
I noticed version 0.12 (as add on in HA) does not have section with all ports in configuration like RC had. 

### Version

0.12

### Frigate config file

```yaml
N/a
```

### Relevant log output

```shell
Failed to get WebRTC port from supervisor
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tplink tapo tc60

**Comment by NickM-27** [comment]
> I noticed version 0.12 (as add on in HA) does not have section with all ports in configuration like RC had.

what are you referring to? the configs should be identical at this point

**Comment by NickM-27** [comment]
and without providing full logs, there is no way to debug why this is happening

**Comment by Mikescotland** [comment]
New properly formatted issued
