### ISSUE TITLE
[Support]: webrtc stopped working (reliably) in 0.12.0

### ISSUE THREAD

**Issue by Mikescotland** [blakeblackshear/frigate#5942]
### Describe the problem you are having

WebRTC stopped working in 0.12, while in 0.12RC was working properly. In add on configuration tab in HA Addon screen version 0.12RC had more ports to configure, production version has only two ports to configure (lack of WebRTC port) 

### Version

0.12 

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.4
  user: xxxx
  password: xxxx
  
  
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  
ffmpeg:
  hwaccel_args: preset-vaapi  
  
go2rtc:
  streams:
    doorbell: 
      - rtsp://xxx:xxx@192.168.1.8:554/stream1 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
      - ffmpeg:doorbell#audio=opus
    #doorbell_sub:
    #  - rtsp://xxx:xxx@192.168.1.8:554/stream2 # <- stream which supports video & aac audio. This is only supported for rtsp streams, http must use ffmpeg
    #  - ffmpeg:doorbell_sub
 

    
cameras:
  doorbell:
    ffmpeg:
     
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell # <--- the name here must match the name of the camera in restream
         
          roles:
            - record
            - detect
       # - path: rtsp://127.0.0.1:8554/doorbell_sub # <--- the name here must match the name of the camera_sub in restream
       #   input_args: preset-rtsp-restream
       #   roles:
        
       #     - detect
          
          

         
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    objects:
      track:
        - person
        - dog
   
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 7
    motion:
      mask:
        - 0,720,892,720,777,482,1026,466,1029,350,1068,0,722,0,0,0,0,240
record:
  enabled: True
  retain:
    days: 3
    mode: all
```

### Relevant log output

```shell
Logs version 0.12

2023-04-08 18:19:43.175034378  [INFO] Preparing go2rtc config...
2023-04-08 18:19:43.308084207  [INFO] Got IP address from supervisor: 192.168.1.4
2023-04-08 18:19:43.429461877  [WARN] Failed to get WebRTC port from supervisor
2023-04-08 18:19:44.072050026  [INFO] Starting go2rtc...
2023-04-08 18:19:44.341680192  19:19:44.341 INF go2rtc version 1.2.0 linux/amd64
2023-04-08 18:19:44.342254572  19:19:44.342 INF [api] listen addr=:1984
2023-04-08 18:19:44.343048558  19:19:44.342 INF [rtsp] listen addr=:8554
2023-04-08 18:19:44.343625989  19:19:44.343 INF [srtp] listen addr=:8443
2023-04-08 18:19:44.344194083  19:19:44.344 INF [webrtc] listen addr=:8555

Logs version 0.12RC
2023-04-08 18:21:54.010395623  [INFO] Preparing go2rtc config...
2023-04-08 18:21:54.138295022  [INFO] Got IP address from supervisor: 192.168.1.4
2023-04-08 18:21:54.260426949  [INFO] Got WebRTC port from supervisor: 8555
2023-04-08 18:21:54.868368251  [INFO] Starting go2rtc...
2023-04-08 18:21:55.143978424  19:21:55.143 INF go2rtc version 1.2.0 linux/amd64
2023-04-08 18:21:55.144810671  19:21:55.144 INF [api] listen addr=:1984
2023-04-08 18:21:55.145592182  19:21:55.145 INF [rtsp] listen addr=:8554
2023-04-08 18:21:55.146611136  19:21:55.146 INF [srtp] listen addr=:8443
2023-04-08 18:21:55.147519980  19:21:55.147 INF [webrtc] listen addr=:8555
2023-04-08 18:22:04.036997897  [INFO] Starting go2rtc healthcheck service...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo c100

### Any other information that may be helpful

WebRTC starts in cards and in the frigate live view immediately I'm version 0.12RC
I'm version 0.12.0 starts sometimes after 10 seconds but mostly spinning waiting circle.
Configuration Addon tab lacks also ports (see screenshot) 
![Screenshot_20230408_191231_io homeassistant companion android](https://user-images.githubusercontent.com/52081323/230737088-2a821fdf-ecfc-4d68-b909-dce6bb7942b8.jpg)
![Screenshot_20230408_191241_io homeassistant companion android](https://user-images.githubusercontent.com/52081323/230737089-f39ee473-c3d6-41bd-8991-b0a069c66607.jpg)

**Comment by NickM-27** [comment]
It seems your addon isn't updated or you need to refresh your browser cache. The addon config definitely exposes the same ports.

**Comment by Mikescotland** [comment]
Reinstalled Addon and ports appeared. Cleared cache in browser etc, webrtc still remains. Card rarely shows Rtc, showing MSE, frigate live view spinning in webrtc mode. All other modes ok.

**Comment by NickM-27** [comment]
we'll need to see new logs for that then. Nothing changed from RC2 to this release, the code is identical

**Comment by cybertza** [comment]
```
go2rtc:
  api:
    origin: '*'
  log:
    format: text
  rtsp:
    default_query: mp4
  webrtc:
    candidates:
    - stun:8555
  streams:
    YourCam: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@X.X.X.X:554/Streaming/Channels/101/
```

Seems to work for me, Basically just did the config inside [go2rtc] Copied it, and pasted, and added a tab to all the lines.

**Comment by NickM-27** [comment]
to be clear, those are all defaults set by frigate on startup so that is not needed to be set manually

**Comment by cybertza** [comment]
Yet Magically, if I change things there it finds its way into the running config located on the SHM.

**Comment by Mikescotland** [comment]
After deinstalling and reinstalling everything, a few reboots later all works. BTW if I don't specify port 5000 in frigate config tab, the port isn't open, while theoretically should.
Go2rtc dashboard link in the system tab in frigate has url with 1984 port and goes to 404 page, while changing it to 5000 port shows go2rtc dashboard.

**Comment by NickM-27** [comment]
Frigate does not try to open 1984 as we assume it is a closed port. Glad everything is working
