### ISSUE TITLE
enabling go2rtc uses much higher/errratic CPU usage

### ISSUE THREAD

**Issue by RichardPar** [blakeblackshear/frigate#5948]
### Describe the problem you are having

Since moving to 0.12, I enabled the go2rtc and deprecated the RTS2P by snowzach. Atatched is the CPU usage and temperatures of the processor. 

### Version

0.12

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### Frigate stats

```json
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

I migrated to go2rts at 8h20 .. the temperature profiles now go wild; the fan is set to switch on at 65 degrees celcius (low speed) and the ARM chip has a max temp of 75. (fan will be 100%) 

![image](https://user-images.githubusercontent.com/1158641/230763267-79e88338-3439-4dbd-bb22-d7284ab3396a.png)

**Comment by NickM-27** [comment]
We can't help without seeing your config, logs, etc

**Comment by RichardPar** [comment]
> We can't help without seeing your config, logs, etc

I cant see how its relevant...

I have Frigate 0.12 running using RTS2P .. I disabled the RTSP proxy plugin and changed to rts2go within Frigate and swapped the streams over to look at the local proxy..

Thats the result... its a comparison - I am at a bit of a loss what the logs will tell you.

**Comment by NickM-27** [comment]
You created an issue under the category config support and then didn't provide a config or logs. These will of course give information about what is configured, what's going on in the system, if there's any errors, etc

We've had a long beta phase with thousands of users and have not had anyone experience issues like this since the early beta.

Are you actually asking for support?

**Comment by RichardPar** [comment]
> We've had a long beta phase with thousands of users and have not had anyone experience issues like this since the early beta.
> 
> Are you actually asking for support?

Apologies, 
Maybe miscatagoriesed, its more of a bad observation and the lack of a category for 'Issues' Please move to a section you find more appropriate. 

![image](https://user-images.githubusercontent.com/1158641/230773378-19b08288-77c2-40bb-b9ee-28c5848f9011.png)

**Comment by RichardPar** [comment]
> The top screenshot shows 15% CPU usage for go2rtc
> 
> What device are you running this on and what type of cameras are being used?

they are 4x Herospeed cheap-n-no_so_cheerful CCTV cameras (outdoor) 

The board its running on is a Khadas VIM4 SBC
https://www.khadas.com/vim4

![image](https://user-images.githubusercontent.com/1158641/230780671-e7d63f53-c3ef-4f26-9c72-67d78e6f3b65.png)
