### ISSUE TITLE
[Support]: No Published 4.0.x Release for HASS Integration

### ISSUE THREAD

**Issue by james-bjss** [blakeblackshear/frigate#5953]
### Describe the problem you are having

Hi, The latest release notes advise upgrading the Frigate HASS Integration to `4.0.0-rc1` however there is currently no published release on the GH repository and HACS doesn't seem to be able to install from a Tag.

Not sure if I am going mad and there is an alternate way to update?
I had already bumped the frigate install to 12.x and it (seems) to be working OK but perhaps I am missing something.

The relevant bullet from the Release notes:
`If using the [Frigate-HomeAssistant Integration](https://github.com/blakeblackshear/frigate-hass-integration) it will need to be updated to [4.0.0](https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v4.0.0-rc1) to avoid breaking changes with Frigate 0.12`

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

HikVision

**Comment by NickM-27** [comment]
it is published, you just need to enable beta versions to run the RC. It will be updated to stable soon https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v4.0.0-rc1

**Comment by james-bjss** [comment]
> it is published, you just need to enable beta versions to run the RC. It will be updated to stable soon https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v4.0.0-rc1

Thanks, as soon as I hit submit I double checked then saw it under pre-releases! Thanks, will do that now.
