### ISSUE TITLE
[Support]: Possible to open nginx to external connections?

### ISSUE THREAD

**Issue by kylepyke** [blakeblackshear/frigate#5961]
### Describe the problem you are having

I have Frigate with go2rtc running in docker on one computer, and home assistant running on another. I setup the Webrtc Camera integration in HA to point to the go2rtc server on the Frigate computer, but loading the connection via the webrtc_card fails with the error "Invalid Response Status" (see attached).
<img width="504" alt="1" src="https://user-images.githubusercontent.com/107963487/230831714-46786f4e-3ab2-4a13-a41e-abbbdea4e91d.png">

### Version

latest stable

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
2023-04-10 00:02:33.641857844  2023/04/10 00:02:33 [error] 134#134: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.100, server: , request: "GET //api/Basement_frgt/latest.jpg?h=394 HTTP/1.1", upstream: "http://127.0.0.1:5001Basement_frgt/latest.jpg?h=394", host: "192.168.1.167:5000", referrer: "http://192.168.1.167:5000/"
2023-04-10 00:02:33.641924122  192.168.1.100 - - [10/Apr/2023:00:02:33 -0500] "GET //api/Basement_frgt/latest.jpg?h=394 HTTP/1.1" 502 157 "http://192.168.1.167:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0" "-"
```

### FFprobe output from your camera

```shell
.
```

### Frigate stats

```json
.
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

.

**Comment by NickM-27** [comment]
Port 5000 is frigate's api. You should be using port 1984 for the webrtc integration, making sure it is also mapped in the docker config

**Comment by NickM-27** [comment]
No problem, feel free to create a new issue if something else comes up.

**Comment by kylepyke** [comment]
This works, in theory, but I think my HA instance has an issue. Maybe this is a larger problem than than this thread, but I can't get any webRTC streams to load at all in Home Assistant. I've tried:

- camera -> RTSPtowebRTC (intergration) -> RTSPtowebRTC (addon) -> HA
- camera -> RTSPtowebRTC (intergration) -> go2rtc (addon) -> HA
- camera -> WebRTC Camera (intergration) -> go2rtc (addon) -> HA
- RTSP stream -> go2rtc (local addon)-> HA
- RTSP stream -> go2rtc (via frigate)-> HA

Everytime, I get a black screen with "loading2". The webRTC stream opens fine in VLC, and MSE works from the same source, but webRTC simply will not load.

<img width="501" alt="Screen Shot 2023-04-10 at 12 31 54 PM" src="https://user-images.githubusercontent.com/107963487/230958077-6be8ca92-07ab-44d0-8bab-c4e13ef9c2bf.png">

Any advice on what could be hanging up in HA? Or at least how to debug/cleanup that process in the backend?

**Comment by NickM-27** [comment]
VLC supports rtsp not WebRTC so that is not a valid comparison.

Does webrtc work for you in frigate's webUI?

**Comment by kylepyke** [comment]
Yes, it works great in the Frigate UI. Ideally, I'd like to get that same stream in the Frigate lovelace card.

**Comment by kylepyke** [comment]
Ah, cool! I'll give this a shot. Thanks! Looks like v5 is in pre-release. Any idea when the official stable release will be available?

**Comment by NickM-27** [comment]
Nope

**Comment by kylepyke** [comment]
Sorry to keep asking questions... Looks like there isn't much info in the docs, for how to configure the Frigate card YAML to use native go2rtc. Do you have any resources you could point me to?
