### ISSUE TITLE
[Config Support]: timestamp_style scale not supported?

### ISSUE THREAD

**Issue by amosyuen** [blakeblackshear/frigate#5963]
### Describe the problem you are having

Looks like scale was previously supported at one time according to https://github.com/blakeblackshear/frigate/issues/1647. Looks like it is no longer an option according to https://deploy-preview-4055--frigate-docs.netlify.app/configuration. Any plans to add it back? The font size is a little on the large side.

### Version

0.12.0-BC16AD1

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
The scale is automatically calculated based on the resolution, there was never a full release with a manual scale option. You can request the feature if you would like https://github.com/blakeblackshear/frigate/commit/f63a7cb6c0e16abc4bd7d6ffc655dc6f7d528656
