### ISSUE TITLE
False positive: detected leaves as person

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#599]
First time I got this :

![Screenshot_20210124-190001_Chrome](https://user-images.githubusercontent.com/30929896/105639092-93937b00-5e76-11eb-8df7-ba0c323cb427.jpg)
![Screenshot_20210124-185941_Chrome](https://user-images.githubusercontent.com/30929896/105639097-97270200-5e76-11eb-84b9-75381b6492d4.jpg)

**Comment by asemev** [comment]
https://user-images.githubusercontent.com/30929896/105639188-161c3a80-5e77-11eb-8b3f-0caabfaf447c.mp4

**Comment by blakeblackshear** [comment]
This is what the filters are for. These are going to happen occasionally. The only way to prevent these is to develop a better model, which is getting very close to the top of my to do list.

**Comment by InToSSH** [comment]
I had the same problem, it was detecting a pipe in my garden as a person when it was raining, the rain was triggering the motion. I would suggest going to the web UI, turning on Motion box and watching whats triggering the motion, then fine tuning the motion to be less sensitive or using motion mask in place where the motion can't happen. Then of course you have the filters, thresholds, etc. But I agree better model would be really nice, although even this one is not bad at all.

**Comment by asemev** [comment]
Thank you both. Not a problem for me at all. Frigate is a thousand times better than any other motion detection solution out there, including Google Nest (not a scientific statement) . So I'm super satisfied. Just shared this to help.
