### ISSUE TITLE
[Support]:  Web Event Camera Selection

### ISSUE THREAD

**Issue by kdill00** [blakeblackshear/frigate#5997]
### Describe the problem you are having

Ever since 12 beta-8 or 9, the new fancy camera drop down selection under events does not work if frigate has more than 16 cameras for the instance.  16 and below and it works. I tried various combinations and redid my config serveral times so I do not believe it is my config as everything else still works correctly. The only thing I could think to grab was inspect/debug menu from chrome.  There are 3 messages presented:

[172.16.1.45-1681218152992.log](https://github.com/blakeblackshear/frigate/files/11200664/172.16.1.45-1681218152992.log)
[172.16.1.45-1681218193431.log](https://github.com/blakeblackshear/frigate/files/11200665/172.16.1.45-1681218193431.log)
[172.16.1.45-1681218116824.log](https://github.com/blakeblackshear/frigate/files/11200666/172.16.1.45-1681218116824.log)

it may be easier to just quickly add 17 cameras and try it out.  and just a picture so its clear what I am talking about:

![frig](https://user-images.githubusercontent.com/76188629/231171355-551dac04-95d6-467b-9f3c-2a1a3905171e.PNG)

Let me know if there is anything else I need to procure.  

### Version

0.12.0-da3e197

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wired

### Camera make and model

spiffy one

**Comment by NickM-27** [comment]
are you using the browser in full screen? what if you change the height?

I assume it is https://github.com/blakeblackshear/frigate/commit/a5e561c81ddec5fac2ded287b2e534b0c5cb9468 but that is what fixed this issue

**Comment by kdill00** [comment]
Wait sorry, this fix is applied.  Still asleep.  So yeah this issue persists unless i remove half my cameras and go under 16.

**Comment by NickM-27** [comment]
Hmm, it seems to be working as expected for me

![Screen Shot 2023-04-11 at 07 19 33 AM](https://user-images.githubusercontent.com/14866235/231175562-aa3f120f-f9ad-4c4f-a3fc-2c2815c5cc41.png)

**Comment by kdill00** [comment]
strange.  I cleared cache and cookies to no avail, i will post my config in just a moment.

**Comment by sinamics** [comment]
sure, can try to figure it out. @kdill00 can you send me you config and a snippet of the issue if you can?

**Comment by blakeblackshear** [comment]
@kdill00 can you also test this image build? https://github.com/blakeblackshear/frigate/pkgs/container/frigate/85471497?tag=master-dee471e

**Comment by ccutrer** [comment]
I can confirm that [master-dee471e](https://github.com/blakeblackshear/frigate/pkgs/container/frigate/85471497?tag=master-dee471e) fixed the issue for me. Thanks!

**Comment by Morphy99** [comment]
> are you using the browser in full screen? what if you change the height?
> 
> I assume it is [a5e561c](https://github.com/blakeblackshear/frigate/commit/a5e561c81ddec5fac2ded287b2e534b0c5cb9468) but that is what fixed this issue for others

Although I would think this fix necessary for edge use cases of low resolution screens and a lot of cameras, for me it misses the underlying issue with the event filters. I think most people would run into it when trying to filter by zone, as even with a modest 4 cameras you quickly encounter it when using zones. I would expect from a UE point of view, when filtering by camera, to also filter out the zones not from that camera?

Another issue was not being able to bulk select and deselect items which is a pretty standard feature with potentially large drop-down menus.
