### ISSUE TITLE
Look into usb accelerators

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#6]
Such as

- https://coral.withgoogle.com/tutorials/accelerator/
- Intel Neural Compute

**Comment by blakeblackshear** [comment]
I purchased a Coral USB TPU today. Excited to try it out.

**Comment by blakeblackshear** [comment]
I was able to successfully run the demo classifier from the getting started guide as well as run the classifier inside a docker container. A couple of things I have learned so far:
- It shows up as a raw USB device in `/dev/bus/usb`
- The udev rules in the installer just set permissions for the `plugdev` group
- In order to have it run in a docker container, you have to pass the device at `/dev/bus/usb/001/009`, but the last number changes over time even when plugged in.
- You can't pass an aliased device to the container such as `/dev/coral` or it fails to load the TPU context
- Multiple processes cannot access the processor at the same time

This is going to require quite a bit of modification to frigate, but according to the specs, it can handle 100+ fps with MobileNet. Based on that, one TPU may be able to handle 20+ regions at 5fps.

**Comment by blakeblackshear** [comment]
Added in 0.1.0

**Comment by scstraus** [comment]
So is it time for me to buy a coral and try this? It can handle 4 camera streams now?

**Comment by blakeblackshear** [comment]
I am running the version with Coral support as my primary. To test multiple cameras, I added the same camera multiple times to my config file. I only tried 6 cameras, but it should be able to handle more. Most of the CPU usage is for decoding the video stream now. I also just ordered a second Coral.

**Comment by scstraus** [comment]
Heading over to the Coral order page then! Looking forward to having my CPU back ;-).
