### ISSUE TITLE
Pass height to latest.jpg dynamically to reduce data usage and reduce load time

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#600]
With several 1080p cameras, the UI can be slow to load due to always loading full resolution images. It is particularly slow over a mobile network. So slow in fact, that they live view never updates because it takes more than 0.5 seconds to load the full image. It would be great to have frigate reduce the image size by passing the `h` parameter to latest.jpg based on the width of the actual img tag.

**Comment by paularmstrong** [comment]
May be best to use [Responsive Images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) here to avoid layout calc and reflow issues, requiring a lot more JS code – and let the browser deal with picking the right image on its own.

**Comment by blakeblackshear** [comment]
Cool. Doesn't look like that supports query strings, but I can parse it out of the filename.

**Comment by paularmstrong** [comment]
It should support them, afaik. The srcset parsing is the same as parsing any img URL.

**Comment by blakeblackshear** [comment]
The responsive images is certainly an improvement. It is an elegant way to address this. Is the image size selected based on total browser width or just the width of the image tag? It still seems to request the 1080 images for me when loading the Cameras view regardless of my browser window. Also, I don't really want to load the full width image even if I have a large enough screen. It is particularly bad for portrait mode cameras because I have to scroll (a lot) to view the entire image. It might help to have a default max width.
![image](https://user-images.githubusercontent.com/569905/105849878-9a211000-5fa6-11eb-9d45-e3ca3b2d1717.png)

**Comment by paularmstrong** [comment]
>  Is the image size selected based on total browser width or just the width of the image tag?

I think there's a bug. It's not super easy to get this right, mostly because Frigate's API keys on height and browsers really only understand `width` as the first-class layout mechanism. I'll tweak things up a bit.

> It might help to have a default max width.

This becomes a balancing act. It seemed like there was a bit of feedback from people that they were upset that the images were too small.

**Comment by blakeblackshear** [comment]
They will be more upset when the feed doesn't load at all and/or they aren't on unlimited mobile data plans. I think it's best that we have a sane default and allow opening the full resolution separately. People have also asked to not hardcode the width to 277 in the camera entities, but it's just a bad idea to have the full resolution image there.

**Comment by paularmstrong** [comment]
I think I can make it work, but we need to be pretty clear about expectations:

1. There will be a flash of missing content and the page is going to reflow
2. Camera images will have a max-height of the configuration height (sane default?)
3. The layout may be a little funky on the live view and mask editor if your camera's max-width is smaller than your viewport would normally allow

**Comment by paularmstrong** [comment]
For the auto-updating image, I think we may need some extra logic to prevent loading an updated view if the previous has not loaded. This will take some extra thought.

**Comment by blakeblackshear** [comment]
This still needs a bit of refinement at some point. On initial load, the images load twice because the width must change during layout rendering.
![image](https://user-images.githubusercontent.com/569905/106084187-76171900-60e3-11eb-9a3e-41056e20db80.png)

**Comment by paularmstrong** [comment]
I'm unable to reproduce this, but that is definitely one of the dangers of this approach over inferring the size via the viewport or some other factor that does not change.

**Comment by blakeblackshear** [comment]
Can we calculate based on the viewport and use a smaller image such as 1/3 of the viewport for the main page when there are 2 images side by side and still have it behave well on mobile when you get a single column? The main goal is just to avoid loading large images just to resize them in the image tag. No rush. It works ok as is and I don't use the UI much myself.

**Comment by paularmstrong** [comment]
The layout is responsive, so it can be unknown how the image will be displayed.
