### ISSUE TITLE
[Support]: detector status from Web UI system endpoint

### ISSUE THREAD

**Issue by my-umd** [blakeblackshear/frigate#6013]
### Describe the problem you are having

I am curious about OpenVINO performance on my system.  Couldn't find any document to explain the system endpoint from Web UI.  While it looks straightforward and self-explanatory, there are several points that I would like clarifications.  I am attaching a screenshot for better exchange:
![IMG_20230412_055401](https://user-images.githubusercontent.com/27736698/231424943-f0fa6926-31f8-413a-8351-6fe5b377e0bb.jpg)
Here are my questions:
1. Is the boxed inferencing stats from the latest detection?  Or an average of past detections?
2. What P-ID (291 in the screenshot) does it refers to?  I checked the P-ID from all my camera status under the same system endpoint, none of them has this detect pid.
3. There is also CPU% displayed.  The number can go up to 40-50 for CPU% sometimes.  Does this mean the inferencing is done through the CPU?  I have a J3455 CPU.  From the [document](https://docs.frigate.video/frigate/hardware) , the speed (27.34 ms in the screenshot) does not suggest that it is done from CPU.
4. If the inferencing is done through GPU, what would have caused CPU% to go up to 40-50?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
# only pasted relevant part
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wireless

### Camera make and model

Wyze

**Comment by blakeblackshear** [comment]
Object detections run in their own dedicated process separate from the camera detect process. The PID is the process I'd for that process.

The detect process has to take the binary frame data, transform it into the input format required by the model, execute the model, and read the output. The CPU usage is related to those operations.

**Comment by my-umd** [comment]
I see.  Thanks @blakeblackshear for your explanation.
