### ISSUE TITLE
Thumbnail.jpg not showing in the app notification

### ISSUE THREAD

**Issue by asemev** [blakeblackshear/frigate#602]
Sorry to disturb again. I had this working in the past but cannot make it work anymore.

I tried to debug it:

- I can see the thumbnail.jpg when i do http://192.168.178.125:5000/api/events/1611589703.134563-1jjpyc/thumbnail.jpg
- But cannot see it when i do https://asemev.duckdns.org/api/events/1611589703.134563-1jjpyc/thumbnail.jpg (i get error 404: Not found). 

I have duckdns add-on running and the IP address is correctly mapped, and also of course i have the ports open in my router, and also NGINX addon to handle the ports. So nothing changed in these settings and the thumbnails were showing in the app notifications.

Any clue as to what i should check next? Thanks a lot.

**Comment by blakeblackshear** [comment]
The public url should be https://asemev.duckdns.org/api/frigate/notifications/1611589703.134563-1jjpyc/thumbnail.jpg

**Comment by asemev** [comment]
Ah ok, it works. I can see the thumbnail. But then i wonder why the notification didnt attach the image?

**Comment by asemev** [comment]
alias: Notify Person Detection
description: ''
trigger:
  - platform: mqtt
    topic: frigate/events
condition: []
action:
  - service: notify.notify
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: >-
          https://
          asemev.duckdns.org/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
        tag: '{{trigger.payload_json["after"]["id"]}}'
mode: single

**Comment by sycophantic** [comment]
That API endpoint is accessible without authentication.

**Comment by blakeblackshear** [comment]
That is intentional. It is the only way notifications can work and why it includes the unique event id.

**Comment by asemev** [comment]
Hi Blake, so do you have any idea why the images are not attached to the notifications? its very strange.

**Comment by blakeblackshear** [comment]
Where are you sending that notification? What type of device?

**Comment by asemev** [comment]
Same device as before when it used to work. Its a Samsung Galaxy Fold 2 5G and running the native Home Assistant app version 2021.1.2-full. I'm using the notify.notify service call (as before).

**Comment by blakeblackshear** [comment]
I would check the homeassistant logs. I don't see anything wrong with it.

**Comment by asemev** [comment]
I seem to be getting this error in the logs. I wonder if it's related? 

2021-01-26 13:43:50 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 4d98729e2d85d0327e509722835db498b1a3491ad5759d40972bf2841a05178e from 172.30.33.2

**Comment by blakeblackshear** [comment]
It doesn't look related.

**Comment by asemev** [comment]
And I see this:
![Screenshot_20210126-135135_Home Assistant](https://user-images.githubusercontent.com/30929896/105848108-d53f3580-5fde-11eb-8a27-7fdddbc33b8f.jpg)

**Comment by blakeblackshear** [comment]
Does it always fail to attach the image to the notification?

**Comment by asemev** [comment]
might be also related. i'm getting duckdns errors...

![image](https://user-images.githubusercontent.com/30929896/105856445-8c40ae80-5fe9-11eb-8694-0e5bb323f7bf.png)

**Comment by asemev** [comment]
Hi Blake, hope you are doing well. I was wondering if you would be able to help me troubleshoot this issue with my setup, if and when you have some free time. Since Feb, Frigate has been working perfectly, except for the snapshot thumbnail in the notification messages. Its a pity really as i really love your Frigate and once the thumbnails were showing and it was awesome. Anywho, if one day you have time and interest, i would appreciate tremendously. Thanks and stay safe.

**Comment by SgtBatten** [comment]
@asemev did you have any luck?

I am also unable to get this working. my Notifications (used the template from github) just say "A person was detected" and no other content or space for an image.

My thumbnail.jpg is not available on the LAN IP or remote domain. My clips in media browser in HA also don't have thumbnails so i'm not sure if it's related. 
```
http://192.168.1.25:5000/api/frigate/notifications/1632265959.30984-7mzpvz/thumbnail.jpg
```
I can get other data using the api endpoints so that appears to be working.

**Comment by asemev** [comment]
Hi @SgtBatten, ms issue is quite different from yours and i figured out the problem on my side. its caused by my Vodafone broadband router as it does not support reverse DNS. so i'm using WIFI at home with my mobile phone, the thumbnails dont appear in the notifications. But when i switch off WIFI and use cellular, then the pictures come to my phone. I can also always see the thumbnails and clips in the media browser in HA... so its different from your issue...

**Comment by SgtBatten** [comment]
Hey @asemev 

Thanks for replying. I actually resolved mine also about an hour ago. Turns out it was an issue with my install of frigate. I missed a step.

**Comment by asemev** [comment]
Cool, happy for you! Enjoy Frigate :)
