### ISSUE TITLE
Release package without go2rtc bundling

### ISSUE THREAD

**Issue by my-umd** [blakeblackshear/frigate#6027]
**Describe what you are trying to accomplish and why in non technical terms**
I have hard time to get go2rtc working stably (issue #5976).  I checked the functionality of the unstable installation, I do not think I will need any of the go2rtc offering.  I need OpenVINO though.  I also need integration with Home Assistant.  I am running Frigate on an NAS with relatively weak CPU with 16G RAM.  With go2rtc, I see a steadily higher CPU usage, which I am reluctant to let it keep running.  Because I have Pfsense, Home Assistant, MQTT and all my remote file system running on the same unit.  I do not want to risk go2rtc to bring my entire NAS down.  Unbundling go2rtc will likely make it more light weighted, suitable for a low powered system.

**Describe the solution you'd like**
I would like a docker release without go2rtc bundling, but with OpenVINO.  As well as Home Assistant integration.

**Describe alternatives you've considered**
I am currently using a configure file without any go2rtc setting.

**Additional context**
Providing a separate package seems a workable approach to provide support for different needs for this project.  Because I see Nvidia GPU is supported in a separate release with tensorrt suffix.  Not sure how hard it will be to unbundle go2rtc though.

**Comment by NickM-27** [comment]
what reason is there for this? go2rtc provides required features for the integration and even if you don't use go2rtc there is nothing about it that is required or would disrupt the standard usage of frigate. The binary is also ~ 5MB so it is not a concern of wasted space

**Comment by NickM-27** [comment]
if the concern is about *some* CPU usage even if go2rtc is not used for anything since it is running idle, then surely that would be covered by "as a user, I don't want go2rtc to be running if it is not configured"

**Comment by my-umd** [comment]
Thanks @NickM-27.  I think, with current packaging, I will have to use go2rtc no matter what.  Because I need Home Assistant integration, which, if I understand correctly, will be supported through go2rtc.

BTW, I didn't know go2rtc binary is only 5M.  That's definitely not a concern then.

**Comment by NickM-27** [comment]
yes, go2rtc will be required to get your camera entity to have the stream in HA once RTMP is removed.

of course, using go2rtc as the source for cameras in frigate (reducing connections to the camera) is not required in any way.

**Comment by my-umd** [comment]
@NickM-27 Thanks for confirming.
I am essentially using a config file from v0.11 plus the OpenVINO config (i.e., running without using any go2rtc feature).  I haven't upgraded Home Assistant integration.  I see no Frigate live stream in HA.  And Frigate recordings in HA media is shown empty.  Clips and snapshot are not affected.  Events are not affected, because Frigate based automations are still working fine in HA.  I am not sure if upgrading Frigate HA integration will break more things or make things better.  It's a bit off from ideal, but I can probably live with the current status.

**Comment by NickM-27** [comment]
That would be a support issue to figure that out, but most likely your go2rtc streams and cameras section are not matching.
