### ISSUE TITLE
Add camera event to detector summary on Web UI System section

### ISSUE THREAD

**Issue by my-umd** [blakeblackshear/frigate#6029]
**Describe what you are trying to accomplish and why in non technical terms**
Remember seeing a request to add memory percentage to Web UI detector status (cannot fine the issue now).  Wondering if it's worthwhile to add camera and object there.  It is just for my personal curiosity.  Maybe fun to have it there.

**Describe the solution you'd like**
Add camera event to detector summary on Web UI System section, along with CPU and Memory percentages.

**Comment by NickM-27** [comment]
Can you elaborate? What do you mean by camera and event? This info isn't available in the same processes, it would be a lot of work from what I can tell and would also rapidly switch between the many different objects

**Comment by my-umd** [comment]
Thanks @NickM-27.  I thought the shown inferencing speed, CPU% and Memory% are from the latest inference event.  And looks it is not auto refreshing on the page.  So rapid switching among many objects may not be a concern.  Do you mean the process ID is not the actual process that does the inferencing for individual camera?  If so, then I see it is not easy to communicate among processes.  I do see there is a detect pid associated with each camera on the same page.  Does this pid do the real inferencing?

**Comment by NickM-27** [comment]
The pid for detector is a separate process that only handles running detections for all cameras. The cpu % and inference speed is also a rolling average. Also, the page updates automatically every 60 seconds.

**Comment by my-umd** [comment]
> The pid for detector is a separate process that only handles running detections for all cameras. The cpu % and inference speed is also a rolling average. Also, the page updates automatically every 60 seconds.

I see.  Thanks for the info..  I'll close this then, seems to much involved.

**Comment by my-umd** [comment]
BTW, there seems a bug on auto refreshing.  If I stay on the page, I see it refreshes every minute.  But if I keep the browser tab open but go to other tab then return, the page seems not refreshing anymore.  Not sure if it is by design.
![IMG_20230414_063239](https://user-images.githubusercontent.com/27736698/232021933-6bab717e-e5f5-43bc-952b-1695fda447a4.jpg)
