### ISSUE TITLE
Reduce detection kill timeout (or make configurable)

### ISSUE THREAD

**Issue by chromakode** [blakeblackshear/frigate#6036]
In cases where the detection process hangs, there's currently a 30s wait before killing it:

https://github.com/blakeblackshear/frigate/blob/6986949d84098b87c231ce221aff4939356e87fb/frigate/object_detection.py#L155

I'd prefer for my Frigate instance to be more aggressive about getting the detection running again. Would it hurt to lower this timeout for all users? Alternatively, it could be a useful configuration knob to expose.

**Comment by blakeblackshear** [comment]
I don't know if there would be any harm to a lower value. This shouldn't be happening often.
