### ISSUE TITLE
More than retain_days days of recording

### ISSUE THREAD

**Issue by cben0ist** [blakeblackshear/frigate#605]
**Describe the bug**
There is more than 15 days of recording in the media/recordings file even though each cams has a "retain_days: 10" setup

**Version of frigate**
rc5

**Config file**
https://pastebin.com/uJpkGiBF

Could this be due to a missed migration from beta to rc or another rc? Should I just manually delete everything older than 10 days for now and see?
Thanks

**Comment by blakeblackshear** [comment]
Can you post the output of `/api/config` too?

**Comment by cben0ist** [comment]
here it is: https://pastebin.com/X3aBkeKC

**Comment by blakeblackshear** [comment]
Do you have anything in the logs related to this? Does a restart of the container cause the older records to be deleted?

**Comment by cben0ist** [comment]
no and no :(

**Comment by blakeblackshear** [comment]
Hmm. This is the code that deletes them: https://github.com/blakeblackshear/frigate/blob/release-0.8.0/frigate/record.py#L95-L104

Any reason that the files would get their date modified updated?

**Comment by cben0ist** [comment]
I have finally found my issue. As I moved from Beta to RC I have also renamed some cameras to their final name (prior was test like name). The deletion code do not delete previous name cam recordings.
Obvious now I found the reason...
Thanks for the help!
