### ISSUE TITLE
[Support]: Frigate not validating runtime config before savingf

### ISSUE THREAD

**Issue by guinnberg** [blakeblackshear/frigate#6055]
### Describe the problem you are having

Using the new config edit section, if for some reason Frigate crashed, you're still allowed to do changes in the config, but when you click on save it won't save and won't show any errors.

After refreshing the page I can see an error saying the addon isn't running.

### Version

0.12

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA

**Comment by NickM-27** [comment]
I'm not able to reproduce this, in my testing it immediately shows an error

![Screen Shot 2023-04-13 at 16 25 37 PM](https://user-images.githubusercontent.com/14866235/231896429-216b2426-52a8-49ce-9f88-a0254a513a8e.png)

**Comment by guinnberg** [comment]
I tried again and I still don't see the error, let me list my steps:

1. Enable RTMP in a camera, but don't add it to any role (this will throw a config error at startup)
2. Click on Save & Restart
3. Wait until you get the error in the addon's logs 
4. Go back to the config editor and change something.
5. Click on Save only, no errors, no saving

**Comment by NickM-27** [comment]
If there is an error in the config the config editor will show it and frigate won't restart or save to the file.

**Comment by guinnberg** [comment]
It does in this case, to test it out again I just followed the above steps
and saved and restarted.

**Comment by NickM-27** [comment]
So that's the actual bug then, it is validating yaml structure but not the runtime config

**Comment by guinnberg** [comment]
If I can give my opinion here, I think it should also show an error if the HTTP call done from the front end fails. It can happen that someone stops the server or it crashes, and since everything works in the browser, the user might not get the appropriate feedback, but I guess that's not a major issue anyway.

**Comment by NickM-27** [comment]
it already does show an http error when the call fails, as I showed above. It transparently shows all errors that come back. Because frigate is in the process of a restart loop the call is received but not handled.
