### ISSUE TITLE
[FR] Timelapse from the recorded footage

### ISSUE THREAD

**Issue by sakalauskas** [blakeblackshear/frigate#609]
It would be really nice to have a feature on the web page to generate and store a speeded-up timelapse from the selected camera at the set timeframes and speed.

Now, I just copy the relevant files, concatenate them and generate time-lapse with this command:
```
for f in `ls -tUr  recordings/2021-01/25/**/camera_name/*.mp4`; do echo "file '$f'" >> tempfilelist.txt; done
ffmpeg -f concat -i tempfilelist.txt -c copy concatenated.mp4
ffmpeg -i concatenated.mp4 -filter:v "setpts=0.1*PTS" output.mp4
```
The way folders are structured/files are named, it can be a bit inconvenient to generate timelapse e.g. from 11.30 to 12.45.

Let me know if you'd be willing to merge this if I made a PR.

**Comment by blakeblackshear** [comment]
This is still something I am considering.

**Comment by umairyounus** [comment]
Maybe an option to record in timelapse.

**Comment by heebo1974** [comment]
I am using motioneye to take snapshots and after that I will combine those to one timelapse video with this command.
`cd "$(\ls -1dt ./*/ | head -n 1)" && cat *.jpg | ffmpeg -framerate 30 -f image2pipe -vcodec mjpeg -i - -s hd720 -c:v h264 -crf 26 -preset faster -vf "tblend=average,format=yuv420p" -f mp4 /data/output/Timelapse/"timelapse_`date +%Y-%m-%d-%H-%M-%S`.mp4"`
![image](https://user-images.githubusercontent.com/108828550/178251865-9bb06fd8-6d77-400f-8f67-f39da52af9bb.png)

It would be awesome if frigate could do that and I could use that extra motioneye raspberry for other things.

**Comment by heebo1974** [comment]
I assume that it would be quite easy to run ffmpeg to create a 1 minute video collected from 24h of recorded material?
Well maybe it is too heavy compared to combining couple hundreds of still pictures.

**Comment by gshlomi** [comment]
Hi,
Any chance this will be implemented?

**Comment by NickM-27** [comment]
> Hi,
> 
> Any chance this will be implemented?

It's a pinned issue so it's on the roadmap

**Comment by rb2k** [comment]
One thing that would be a nice variant/option of this that I've seen on synology devices:

Do a timelapse at 10x/20/50x speed until there's an event and then just splice the event video at regular speed in there.
That way you can keep one 'full day' video that has details of all events with very little memory footprint.

**Comment by evolucja** [comment]
If it is not soon to be implemented by Frigate, do you guys know any existing solution which I could feed from Frigate recordings and generate such time-lapses?
It's really a pain currently to review all-day recordings from multiple cameras.

There are many interesting approaches worth discussing mentioned already in the other topic like:
https://towardsdatascience.com/build-a-motion-heatmap-videousing-opencv-with-python-fd806e8a2340
https://github.com/Askill/Video-Summary

For me, it would be nice even to have an option in the player to play like 16x or 32x when there is no motion and 1x with motion detected. Then I'd be able to fast forward the whole day.

**Comment by NickM-27** [comment]
This is implemented for 0.13

**Comment by ndbroadbent** [comment]
That's awesome! I had a look at the release notes for 0.13 Beta 1 and the documentation but struggled to find something about timelapses. I'm interested in this feature just for fun, to take some timelapses of our garden. Will it be possible to take a photo once a day over a period of months and years?

**Comment by NickM-27** [comment]
Timelapses are supported via the recordings export. It does not done via snapshots but via the recorded footage.

**Comment by jtut1731** [comment]
Awesome feature! Could we get parameters added to the API (and even the UI) to indicate desired length of output video and frames per second instead of getting these from the config? Maybe leave the config as the default values.

**Comment by NickM-27** [comment]
@iursevla the feature already has the ability to tune the parameters in the config for each camera

**Comment by iursevla** [comment]
Yeah, @NickM-27 seems like it. Thanks

I'll try to make it better by allowing the user to provide more parameters on the UI (like maximum time, maximum size in MB etc). I need this for a personal project that will be deployed remotely in a place with a low monthly bandwidth (only a few GB a month)

**Comment by NickM-27** [comment]
@iursevla I wouldn't recommend that. We are currently rewriting the UI and also we specifically chose not to make these UI configurable due to new features coming in 0.14

**Comment by iursevla** [comment]
Okay, @NickM-27 I'll implement it for myself. Whenever the new UI comes I'll take a look and provide my findings in a discussion thread before attempting to make a PR.
