### ISSUE TITLE
[Support]: Unable to save image with large, overlapping labels in Frigate+

### ISSUE THREAD

**Issue by ehn** [blakeblackshear/frigate#6118]
### Describe the problem you are having

When labeling some images in Frigate+ with large, overlapping labels that go all the way to several edges, I'm unable to save the labels. Pressing the _Save_ button fails silently. Looking in the browser dev console, I can see the HTTP response status code `400` and the response `{"errors":[{"param":"annotations","type":"too_big"}]}`.

The requests are:

* `{"annotations":[{"label":"person","x":0.499609375,"y":0,"w":0.500390625,"h":1.0005208333333333,"difficult":false},{"label":"face","x":0.615234375,"y":0,"w":0.12656250000000002,"h":0.16197916666666667,"difficult":false},{"label":"car","x":0.100390625,"y":0.2765625,"w":0.899609375,"h":0.7234375,"difficult":false}]}`
* `{"annotations":[{"label":"person","x":0.499609375,"y":0,"w":0.500390625,"h":1.0005208333333333,"difficult":false},{"label":"face","x":0.615234375,"y":0,"w":0.12656250000000002,"h":0.16197916666666667,"difficult":false},{"label":"car","x":0.100390625,"y":0.2765625,"w":0.899609375,"h":0.7234375,"difficult":false}]}`
* `{"annotations":[{"label":"person","x":0.499609375,"y":0,"w":0.500390625,"h":1.0005208333333333,"difficult":false},{"label":"face","x":0.615234375,"y":0,"w":0.12656250000000002,"h":0.16197916666666667,"difficult":false},{"label":"car","x":0.100390625,"y":0.2765625,"w":0.899609375,"h":0.7234375,"difficult":false}]}`

Happy to share screenshots in a private channel. The images contain photos of individuals I don't want to expose publicly without first getting their consent.

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

N/A

**Comment by blakeblackshear** [comment]
I will have to look at this again. It shouldn't be possible to have a height of > 1.0 (100%). `1.0005208333333333`

You may just want to adjust the height of the bounding box slightly so it doesn't go over.

**Comment by ehn** [comment]
I adjusted the upper edge of some of the boxes ~1 px downwards and was able to save.

The objects all go "above" the image. The way I created the bounding boxes was by dragging outside of the image so that they snap to the edge. There seems to be a bug there, then, that makes them too large.
