### ISSUE TITLE
[0.8.0-rc6] Object mask cannot be drawn

### ISSUE THREAD

**Issue by InToSSH** [blakeblackshear/frigate#612]
**Describe the bug**
All the masks can be created just fine, except for Object masks.
When I create a new Object mask it adds a new yaml entry below the the image>
```
object_0:
      mask:
```
which is fine, but then clicking on the image it doesn't draw the mask, nor can I see the corner points, but the coordinates are written down to the yaml preview.

Then after I click on a different mask (for example motion mask) and then switch back to the object mask only a single point (last one added / first in the yaml list) shows up on the image and no area visible. Then if I start clicking more, it adds more points and even the area, but starting from the last point, ignoring the rest before.
Which means to successfully draw an object mask I need to create a new one, make the first point, switch to different mask, switch back to the object mask (which makes the first point show up), then I can continue drawing the rest.

Even the mask coordinate text below doesn't turn to blue color when activated as it does for other mask types, it stays white.

**Version of frigate**
0.8.0-RC6

**Screenshots**
![2021-01-26_15-11-52](https://user-images.githubusercontent.com/6452373/105855869-dc6b4100-5fe8-11eb-8327-4194d3b66b47.png)
![2021-01-26_15-11-25](https://user-images.githubusercontent.com/6452373/105855914-e725d600-5fe8-11eb-8fdf-82765cc86969.png)

**Comment by paularmstrong** [comment]
What browser and version are you using?

**Comment by paularmstrong** [comment]
Oh this is _only_ for object masks. I see it now. 🤦🏻

**Comment by InToSSH** [comment]
Yes, looks like something with the coordinate array/object initialization when new mask is created.
By the way, thank you for fixing the scaling on masks with the resize observer. It works beautifully :)

**Comment by paularmstrong** [comment]
Opened #613 and #614 for fixing + making the object mask editing a little easier
