### ISSUE TITLE
[Support]: After 0.12 upgrade recordings can no longer be viewed in HomeAssistant in media browser

### ISSUE THREAD

**Issue by mvintila** [blakeblackshear/frigate#6131]
### Describe the problem you are having

After upgrading frigate from 0.10 to 0.12 i noticed that new recordings stopped appearing in Media browser in Home Assistant. Uppon further investigation i think this is caused by the location of the recordings that changed on disk from `frigate/yyyy-mm/dd/hh/camera-name` to `frigate/yyyy-mm-dd/hh/camera-name`. This change does not seem to be reflected in the Home Assistant integration.

### Version

0.12

### Frigate config file

```yaml
irrelevant, nothing changed
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
Frigate 0.12 and v4 of the integration were released together, you need v4 of the integration for recordings to work.
