### ISSUE TITLE
[Config Support]: go2rtc extra fields not permitted (type=value_error.extra)

### ISSUE THREAD

**Issue by mjoy99** [blakeblackshear/frigate#6141]
### Describe the problem you are having

I get a config not valid error when trying to add the go2rtc to restream an esp32 cam.  I am running frigate in a docker container using docker compose.  

### Version

ghcr.io/blakeblackshear/frigate:stable

### Frigate config file

```yaml
go2rtc:
  streams:
    mjpeg_cam: ffmpeg:http://192.168.1.x#video=h264#hardware

cameras:
  mjpeg_cam:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam
          roles:
            - detect
            - record
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-04-17 22:23:40] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-04-17 22:23:45] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-04-17 22:23:50] frigate.app                    
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
you need to show the actual log output (and all of it) otherwise there is no way to help

**Comment by AussiSG** [comment]
Hmm seem to be having the same problem at this moment when trying to make go2rtc work.

`  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-04-18 19:07:32] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-04-18 19:08:37] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
go2rtc
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by NickM-27** [comment]
@AussiSG you are running an old version of frigate

**Comment by AussiSG** [comment]
Serious.... I've updated the docker container yesterday :)

**Comment by AussiSG** [comment]
> @AussiSG you are running an old version of frigate

Sorry seems that I was using wrong build in dockercompose yaml. My bad !

**Comment by mjoy99** [comment]
> you need to show the actual log output (and all of it) otherwise there is no way to help

actual logs added.

I did a docker pull just not for latest stable and get the same error message

**Comment by NickM-27** [comment]
@mjoy99 you are also running an old version of frigate. If you look at dockerhub and the 0.12 release notes they are clear that dockerhub is no longer being used by frigate and it is exclusively hosted on GHCR

**Comment by mjoy99** [comment]
> @mjoy99 you are also running an old version of frigate. If you look at dockerhub and the 0.12 release notes they are clear that dockerhub is no longer being used by frigate and it is exclusively hosted on GHCR

@NickM-27  OK.  I am slightly more educated in docker repositories now.  Once I actually got logged in to the ghcr.io, removed the old image and pulled the latest it all came up correctly.  Thanks for the help.

**Comment by luciandf** [comment]
> > @mjoy99 you are also running an old version of frigate. If you look at dockerhub and the 0.12 release notes they are clear that dockerhub is no longer being used by frigate and it is exclusively hosted on GHCR
> 
> @NickM-27 OK. I am slightly more educated in docker repositories now. Once I actually got logged in to the ghcr.io, removed the old image and pulled the latest it all came up correctly. Thanks for the help.

do you mind educating me as well? i am using portainer and have little to no experience on how to change to this new repository

**Comment by mjoy99** [comment]
> > > @mjoy99 you are also running an old version of frigate. If you look at dockerhub and the 0.12 release notes they are clear that dockerhub is no longer being used by frigate and it is exclusively hosted on GHCR
> > 
> > 
> > @NickM-27 OK. I am slightly more educated in docker repositories now. Once I actually got logged in to the ghcr.io, removed the old image and pulled the latest it all came up correctly. Thanks for the help.
> 
> do you mind educating me as well? i am using portainer and have little to no experience on how to change to this new repository

You can follow instructions for the personal access token and GHCR login here. https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

You will need to do some from command line with docker and some on git hub account. 

You may also be able to pull the image directly from Portainer by having the ghcr.io in path

**Comment by blakeblackshear** [comment]
There is no need to login to ghcr.

All you have to do is change the image from
```
blakeblackshear/frigate:stable
```
to
```
ghcr.io/blakeblackshear/frigate:stable
```

**Comment by luciandf** [comment]
> There is no need to login to ghcr.
> 
> All you have to do is change the image from
> 
> ```
> blakeblackshear/frigate:stable
> ```
> 
> to
> 
> ```
> ghcr.io/blakeblackshear/frigate:stable
> ```

good stuff! it worked! cheers! wow the new version looks really cool!
