### ISSUE TITLE
[FR] Mark Clips/Snapshots to Retain Indefinitely

### ISSUE THREAD

**Issue by drinfernoo** [blakeblackshear/frigate#615]
I'd love the ability to mark individual clips/snapshots to *not* delete automatically, but rather to be retained indefinitely, disregarding the relevant retention configuration.

I imagine this would work best from Frigate's web UI, but whatever works 😉

**Comment by hawkeye217** [comment]
Yes, would love this as well.  Zoneminder has an "archive" feature to retain clips indefinitely, and it'd be nice to have the ability to do the same with Frigate.

**Comment by apaperclip** [comment]
moving over from #732 
Sometimes frigate will record a clip that I would like to save and not have it purged, It would be nice if there was a UI and maybe even an API and/or MQTT topic to save the clip of a specific event.

Just a bunch of thoughts for consideration

A save/retain flag so the regular purge doesn't remove them
The flag could be toggled
The file could be copied to a different location outside the clips folder
The file could have a download link (right now right-click on the video and triple dot option works)
Related event data, or the event itself could also be saved
Event list would indicate that it and/or the clip is marked save/retain
This flag could be filtered on in the event list
Thanks!

**Comment by tungmeister** [comment]
@blakeblackshear any chance of seeing this soon?

**Comment by NickM-27** [comment]
This would be awesome!

**Comment by NickM-27** [comment]
I made a PR for this: #2643

**Comment by NickM-27** [comment]
This has been added in 0.11 👍
