### ISSUE TITLE
Add Re-Usable Static Docker Tag For Rolling Update - latest Or master-tensorrt

### ISSUE THREAD

**Issue by Sn3akyP3t3** [blakeblackshear/frigate#6153]
**Describe what you are trying to accomplish and why in non technical terms**
When running weekly docker updates there should be no need to verify and modify the existing targeted docker tag.  It should just update as-is when the docker repository has been tagged with both the code-gen build docker tag as well as the static one.

**Describe the solution you'd like**
Both would potentially be the same at one point until the static tag is superceded.
docker pull ghcr.io/blakeblackshear/frigate:master-433bf69-tensorrt
docker pull ghcr.io/blakeblackshear/frigate:master-tensorrt
or
docker pull ghcr.io/blakeblackshear/frigate:latest

**Comment by NickM-27** [comment]
There's already a stable and stable-tensorrt tag

**Comment by NickM-27** [comment]
We don't provide latest on purpose due to breaking changes and problems with auto update.
