### ISSUE TITLE
Basic HTTP Authentication for UI

### ISSUE THREAD

**Issue by luisiam** [blakeblackshear/frigate#6161]
**Describe what you are trying to accomplish and why in non technical terms**
I want to have some sort of protection to the UI so that no everyone can see my cameras when I expose it to the internet.

**Describe the solution you'd like**
Basic username/password protection will do. Any more secured implementation is always welcome.

**Describe alternatives you've considered**
I am running workers in cloudflare to password protect my Friage instance.

**Additional context**
N/A

**Comment by NickM-27** [comment]
This is a duplicate of https://github.com/blakeblackshear/frigate/issues/1726
