### ISSUE TITLE
Save segment from all cameras on event detection

### ISSUE THREAD

**Issue by nickpoorman** [blakeblackshear/frigate#6167]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to save the segment from all cameras when a given event is triggered so that I can have a holistic view of the event. Ideally, something like recording the birdseye view of all cameras on an event.

**Describe the solution you'd like**
Just like an object or motion event can trigger saving a recording for that specific camera, I would like if it could trigger the saving of recordings for all cameras for the event.

Now:
Camera 1 motion detected -> Camera 1 recording saved

Want:
Camera 1 motion detected -> Camera 1, Camera 2, Camera 3 recordings saved.

**Describe alternatives you've considered**
Stitching all the camera streams into a single stream through ffmpeg and then passing that "birdseye" view in as a single camera.

**Additional context**
Maybe just a config property?

**Comment by my-umd** [comment]
If integrated with Home Assistant, maybe can use Home Assistant automation to implement this?

**Comment by NickM-27** [comment]
Once #1063 is implemented it could be done that way

**Comment by ams2990** [comment]
@NickM-27, it looks like that FR was implemented. Is this now in fact possible? If so, any pointers to how it could be done?

**Comment by NickM-27** [comment]
You can make an automation to create a manual event for all other cameras
