### ISSUE TITLE
Mechanism to remove snapshot for most recent object detection

### ISSUE THREAD

**Issue by RexWheeler** [blakeblackshear/frigate#6188]
Frigate maintains the most recent snapshot for each object detected for each camera. It is not clear where this snapshot is stored and there doesn't appear to be a way to delete it. These images are shown in the tracked objects section on the camera view:

![Screenshot 2023-04-20 165915](https://user-images.githubusercontent.com/6587943/233510492-a9facdb3-2320-45eb-b250-438c09d13c66.jpg)

I would like to be able to delete (or at least prevent the future display of) images that I may deem inappropriate or sensitive. I realize that under the covers the snapshots or related video may still be retained due to my retention policies - that is okay, as I am concerned with what is obviously displayed in the Frigate and Home Assistant user interfaces by default.

In the above image a deer was recognized as a dog and the only way to remove the deer image from this screen appears to be to wait until something else is recognized as a dog and replaces the image. In this case having a deer image isn't particularly problematic, but if the image was sensitive, there doesn't appear to be a way to remove it.

When running the Frigate extension on Home Assistant, these same images can be displayed on various HA dashboards as well - point being that the scope of people that might see a sensitive image goes beyond just those using the Frigate portal.

I would like to see a delete button or option in the tracked objects section on the camera page that would clear the image. This could either be per object type or for all objects for a given camera. After the image was is cleared, it would appear as if no objects had been detected. (Similar to how the cat object appears in the screenshot above - in my case a cat has never been detected on this camera.)

**Comment by NickM-27** [comment]
These images come from the most recent event. They are cached and will reset a few minutes after the linked event is deleted

**Comment by RexWheeler** [comment]
@NickM-27 Thanks. In my deer picture I had starred the event because it was interesting. I am seeing that in Frigate if I delete events, those images do go away. They don't however go away in Home Assistant, which must be caching them independently. Do you know off the top of your head how to clear those, or should I post the question over in the Frigate HA add in repository?

**Comment by NickM-27** [comment]
those are stored as binary data in mqtt, you need to use mqtt explorer or similar to clear those
