### ISSUE TITLE
[BLOCKER] v0.8.0 - web_port automatically added

### ISSUE THREAD

**Issue by Kurisutian** [blakeblackshear/frigate#620]
I just upgraded to the final version v0.8.0 on HA and noticed that I cannot start it due to the following error:

`Error parsing config: extra keys not allowed @ data['web_port']`

I checked the config and removed the webport entry, restarted the addon and faced the same error. Checking the config showed that the web_port: 5000 entry was automatically added (at least I didn't add it). 

So currently Frigate is not starting up because of this. I took the config from the Beta version which worked and just copied it over, so it's a valid config as far as I can tell. 

Thanks for looking into it.

**Comment by blakeblackshear** [comment]
Just pushed a fix to the addon for this.
