### ISSUE TITLE
[FR] Show motion recordings in recordings tab

### ISSUE THREAD

**Issue by SchoolGuy** [blakeblackshear/frigate#6206]
**Describe what you are trying to accomplish and why in non technical terms**

My parents don't have access to my storage directly. Only through the Frigate WebUI. We have one camera (for a birdhouse) that is purely motion-based and working quite nicely for a few days now. Sadly my parents need to call me every time they want to get new recordings from me. This is quite a time-intensive task for me and duplicates the recordings either onto their phones or into our Nextcloud

**Describe the solution you'd like**

I would like to see the recordings of motion-based cameras in the WebUI natively where all other recordings can be found.

**Describe alternatives you've considered**

I have thought about linking the share directly onto their desktop but that means that I need to give them access directly to the server... This is both not very stable (due to them not being tech-savvy I fear they might break the setup constantly) and security wise I would open up another whole from my dedicated rack network. Both reasons I would like to avoid doing.

**Additional context**

I have looked for another feature request for half an hour but wasn't able to find one. Please forgive me if I didn't look well enough.

**Comment by my-umd** [comment]
If I understand correctly, motion recordings should be there already.  I have a couple cameras set to record on motion.  And I view these clips from web ui.

**Comment by SchoolGuy** [comment]
@my-umd Ahhh now I see where my confusion is coming from. I can't view them due to a bug it appears:

![grafik](https://user-images.githubusercontent.com/15035141/233836389-115be580-d9e0-4065-b4d7-64223b90be1e.png)

I will open a new issue for that bug. Thanks for your help.
