### ISSUE TITLE
Release: 0.080 Error parsing config: extra keys not allowed @ data['web_port']

### ISSUE THREAD

**Issue by Ysbrand** [blakeblackshear/frigate#621]
I'm running the HA Add-on

I'm not sure what happens but everytime I remove the web_port entry from the config, it automagically adds it again to the top of my configuration:

`web_port: 5000`

I've also done the following:

```
Container | Host | Description
-- | -- | --
5000/tcp |  disabled  | Web interface (Not required for Hass.io Ingress)
```

But it still adds the port 5000 to the top of my config.
In other words, when I press "save" the config is as expected. The moment I start frigate, it adds the web_port parameter.

**Comment by talsalmona** [comment]
Same as #620 and #619

**Comment by Ysbrand** [comment]
Hmm, you guys did submit while I was editing....
