### ISSUE TITLE
[BUG]: Go2rtc Config Generator Bug

### ISSUE THREAD

**Issue by alexyao2015** [blakeblackshear/frigate#6237]
### Describe the problem you are having

When using the go2rtc `exec` mode, theres a bug in the config generation. Since go2rtc expects `{output}` in the string passed in as detailed in the docs [here](https://github.com/AlexxIT/go2rtc#source-exec), it is passed into the yaml but it is being incorrectly formatted. 

In the example config, I have `{output}` here and the config generator is attempting to format the string, but `{output}` is not something that should be formatted but rather passed through to go2rtc.

```
exec:ffmpeg -hide_banner -i rtsp://127.0.0.1/path -c copy -rtsp_transport tcp -f rtsp {output}
```
https://github.com/blakeblackshear/frigate/blob/0d16bd0144791b3e37192c4d798730a3ce553183/docker/rootfs/usr/local/go2rtc/create_config.py#L90

### Version

0.12.0

### Frigate config file

```yaml
go2rtc:
  streams:
    back_entry_detect:
    - exec:ffmpeg -hide_banner -i rtsp://127.0.0.1/path -c copy -rtsp_transport tcp -f rtsp {output}
```

### Relevant log output

```shell
frigate    | 2023-04-24 23:27:29.759169004  [INFO] Preparing go2rtc config...
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/local/go2rtc/create_config.py", line 90, in <module>
frigate    |     go2rtc_config["streams"][name][i] = stream.format(**FRIGATE_ENV_VARS)
frigate    | KeyError: 'output'
frigate    | 2023-04-24 23:27:30.241099721  [INFO] The go2rtc service exited with code 1 (by signal 0)
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
This isn't a bug, single `{}` is used for template insertion. You just need to follow the docs which cover this case https://docs.frigate.video/configuration/restream#advanced-restream-configurations

**Comment by alexyao2015** [comment]
I see thanks. Somehow I missed this piece of documentation. It would be great to link to this page from the go2rtc guide which I was following/combine the go2rtc guide with this page.

**Comment by alexyao2015** [comment]
Might also want to suppress the error message and present a more meaningful error message when this occurs.

**Comment by NickM-27** [comment]
Fair point, I'll see if we can improve that error message.
