### ISSUE TITLE
Web: Live image not displayed

### ISSUE THREAD

**Issue by simonbirt** [blakeblackshear/frigate#625]
Affected Version: release 0.8.0-amd64, docker

First off, thanks for all the work you've put into this release. It's looking fantastic. 

I've just come across one issue. I've a setup with a single camera. When I view the web UI in Safari(14.0.2) or Firefox(84.0.2), the live view of the camera does not display. It *does* work in Chrome (88.0.4324.96).

When the image is not displayed, clicking through to the camera detail page shows "Displaying at 0fps" in place of the live feed.

The only error shown in the dev console is 

```
[Error] TypeError: undefined is not an object (evaluating 'e.path[0]')
	(anonymous function) (0bf3b12563e54490a9e9358e3f6fb6e21491b526.94290d3195bf2b069663.js:1:2185)
        CameraImage.js:1:706
```

**Comment by sycophantic** [comment]
I'm experiencing this as well. The previous RC worked fine.

**Comment by hawkeye217** [comment]
Same issue on Mac Firefox and Safari.  Works great on Chrome, though.  Has to do with this PR https://github.com/blakeblackshear/frigate/pull/618

**Comment by mattheys** [comment]
Same Mac Safari, Windows Firefox and Android Firefox. Not displaying the preview on the cameras page or on the specific camera page either. Works ok on Chrome for Android.

**Comment by paularmstrong** [comment]
Fixed in https://github.com/blakeblackshear/frigate/pull/628
