### ISSUE TITLE
Serve Web UI as a Progressive Web App

### ISSUE THREAD

**Issue by mdezzi** [blakeblackshear/frigate#6253]
**Describe what you are trying to accomplish and why in non technical terms**
It would be great to serve the web ui as a PWA so that i can "install" frigate on my mobile device or in windows to create a desktop icon, or frigate app in my app drawer. 

**Describe the solution you'd like**
I am not familiar with the in-depth technical changes that are required, but as i understand it, most web UI's can be converted to a PWA by adding a manifest file. Examples of web ui's that are available as PWA's that i am familiar with are: Overseerr, Mealie, jsonformatter.com, regex101. Reddit, SoundCloud, Twitter, Youtube Music are also served as PWA's. 

**Describe alternatives you've considered**
I have tried creating shortcuts to my webUI on both android and windows. On android, it does not allow you to "install" the app and appear in the app drawer. On windows, it just opens the link in whatever default web browser, and doesnt allow you to open in its own app window. 

**Additional context**

**Comment by mdezzi** [comment]
@NickM-27 I am confused. You installed frigate via google play/apple app store? Or you were able to install as a PWA? When i open a PWA supported web ui in chrome on android it gives me the option to install the app. I dont see that when i open my frigate web ui. (I am on v0.12.0)

**Comment by NickM-27** [comment]
I just used the add to homescreen option in chrome. It shows up in my app drawer and on my homescreen and I can launch it as if it was an app that was installed.

**Comment by mdezzi** [comment]
That might be device/launcher specific, because when i do that it only puts it on my home screen (not app drawer), and opens in chrome. I am on a Pixel 6A and tried with Pixel Launcher as well as Nova Launcher.

**Comment by NickM-27** [comment]
weird, it opens as its own app and no address bar or anything for me

**Comment by mdezzi** [comment]
I was able to find this guide for packaging an existing web app as a PWA: https://docs.pwabuilder.com/#/studio/existing-app

**Comment by dnestico** [comment]
Finally updated to frigate 14 and downloaded PWA option doesn't work on my pixel phone in Chrome, it just adds the typical chrome website shortcut which is not the same as a PWA... pls help

![Screenshot_20241119-172421.png](https://github.com/user-attachments/assets/368cba82-16f8-4fe0-aa91-3fff3bb9fc5d)

![Screenshot_20241119-172413.png](https://github.com/user-attachments/assets/83bcd163-5329-417e-81f4-de55572535b1)

**Comment by NickM-27** [comment]
installing as a PWA requires a secure connection, like it says in the docs https://docs.frigate.video/configuration/pwa

**Comment by dnestico** [comment]
Port 8971 doesn't work for me, oh well guess this just won't work for me 
![Screenshot_20241119-174135.png](https://github.com/user-attachments/assets/10af5353-3f8f-4393-873e-a0b0bcacb820)

**Comment by NickM-27** [comment]
have you enabled the port in docker?

**Comment by dnestico** [comment]
Good point lol, haven't done this in a while but I assume this should be what I have to do, right?

<img width="984" alt="Screenshot 2024-11-19 at 5 48 34 PM" src="https://github.com/user-attachments/assets/7da4f8a7-bc59-46c4-8eb1-89d07acaa517">
<img width="822" alt="Screenshot 2024-11-19 at 5 48 40 PM" src="https://github.com/user-attachments/assets/3ad96454-73a7-4e08-ab3b-7ed9f8b20b2e">

**Comment by dnestico** [comment]
Still shows as insecure so guess not.... Damn lol, on unraid btw, don't have much docker experience ![Screenshot_20241119-175805.png](https://github.com/user-attachments/assets/509e27ea-f023-407a-8c80-3bcbdb00539f)

**Comment by NickM-27** [comment]
you'd need to use something like tailscale or nginx proxy manager to expose it with SSL
