### ISSUE TITLE
[FR] frontend ui development planning

### ISSUE THREAD

**Issue by ljmerza** [blakeblackshear/frigate#627]
Now that the frontend is being built out I think it's a good idea to step back and make some design choices before development on it continues. The main problem i see here is there's no centralized color scheme so say we want to add a dark theme it would be very hard to do so without a bunch of rewriting. I work with React a lot so i think it's a great choice for the ui. i think it would be helpful to pick out a ui library that supports colors schemes. maybe we can get a separate project roadmap going for the ui to plan out long term features and design the ui with those in mind?

**Comment by sakalauskas** [comment]
I think Tailwind (And React-style framework) is a great choice here (I work with them a lot as well).

Actually, the dark mode can be quite easily added:
https://tailwindcss.com/docs/dark-mode

**Comment by paularmstrong** [comment]
> so say we want to add a dark theme

There is a dark theme. Tailwind chooses it based on the user system preference.
<img width="1348" alt="Screen Shot 2021-01-27 at 7 32 34 PM" src="https://user-images.githubusercontent.com/33297/106086139-6c3ae900-60d6-11eb-8114-f226a9ffb177.png">
<img width="1392" alt="Screen Shot 2021-01-27 at 7 32 25 PM" src="https://user-images.githubusercontent.com/33297/106086147-6e9d4300-60d6-11eb-884e-4d8cec3b0732.png">

The "color scheme" is using Tailwind's default theme of grays with blue for links.

**Comment by ljmerza** [comment]
The color scheme was more of an example. The color scheme was more of an example. Overall I'd like to see frontend roadmaps to plan out development.
