### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by janiske** [blakeblackshear/frigate#6279]
### Describe the problem you are having

Looking for experienced Frigate pro user to set up Frigate for my office. 

Can pay for both setup and maintenance. 

### Version

?

### Frigate config file

```yaml
None jet
```

### Relevant log output

```shell
None jet
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Pls contact me at janis@ronin.lv

**Comment by NickM-27** [comment]
This isn't the right place for this. We're happy to help you set it up if you have specific questions and provide your config here.
