### ISSUE TITLE
Overlapping Clip recordings (when multiple simultaneous events occur)

### ISSUE THREAD

**Issue by DeadEnded** [blakeblackshear/frigate#630]
During object detection, multiple objects can be tracked simultaneously.
Each of these objects generates a unique event ID.
Each of these unique event ID's also generates its own clip independent of each other.

So, if you have 3 people walking past a camera you get three nearly identical clips (slight offsets due to when it began tracking each person).
Or if the tracking loses a person and re-acquires them as a new event ID... you get multiple overlapping clips.
These can compound until you have a plethora of overlapping clips being recorded and saved of the same time frame.

Just for example - I had 3 people in a room for 11 minutes.  Frigate registered at one point 16 people (this is probably more to do with the configuration on my part - it lost and re-acquired them multiple times) and generated 111 clips.

Making it so that if a clip is already being generated another is not started, but instead, the clip continues until all objects are "gone" would be a great enhancement.  This will be difficult though due to event ID to clip matching (many to one).

One idea (just to brainstorm as I expect this issue is more complex than I am explaining):

1. Add a new property - `clip_ID` and assign it to each clip just as `event_ID` is for each object tracking event.
2. When an event starts check if a clip is already being recorded.
3. If it is, copy the `clip_ID` to the `event_data` - if not, start a new `clip_ID` and copy it to the `event_data`.

This would allow each event to be associated with the clip that contains it, and each clip could contain multiple events.   I'm not sure if the database design would need to be updated or not (haven't looked at it that closely).  With the clips and events having different ID's I expect a lot of updating would have to be done... but if the `clip_ID` is in the `event_data` maybe it won't be horrible?

Okay, I'll stop theorizing now... I'm happy to help with this if I can!

Cheers!
DeadEnd

**Comment by cicavey** [comment]
Thanks for taking time and articulating this!

I spent more time then I care to admit (beta3 on) trying to find a postprocessing solution with ffmpeg to coalesce overlapping clips. Like you, I really just one _one_ event that encompasses the start of (any) object detect to the end of object detect - an object keepalive function if you will. If only I had more free time to dig into the baseline.

**Comment by hawkeye217** [comment]
+1 for this feature. I like the idea of separate clips per event ID from a technical perspective, but for everyday practical purposes, a single clip makes the most sense to average/non-power users.

**Comment by blakeblackshear** [comment]
The more I think about this, the harder it gets to solve. The issue is that I cannot predict when the events are going to end. For example, let's say 2 people are walking in opposite directions in front of your house. One of them keeps walking by, but the other person decides to stop and talk on the phone for 10 minutes while still in view of the camera.

Clips are created from the cached segments at /tmp/cache. When an event begins, it will start to extend the cache up to `max_seconds` from your config and ultimately assemble the clip from the segments available when the event ends. In the previous scenario, the person who walked by at the beginning would not be included in the clip at all since those segments would have expired from cache.

Also, using something like a clip id would be a breaking change for notifications and a few other things, so I think this may need to wait until 0.9.0. 

For now, I think the best I could do is proactively cleanup events/clips after they have been created if the time ranges obviously overlap.

**Comment by DeadEnded** [comment]
Yes, adding a clipID would be a breaking change, and require updates to... well a lot of stuff (API, HA components, everywhere a clip is referenced by eventID - which I at this point can't even guess the coverage of).

I suggested it because in my novice brain that was the best (easiest/least complicated?) solution - by no means is it ideal.  I have no expectation that my 1 week of tinkering has any footing compared to your literal full knowledge of all the inner workings of how Frigate works.

The issue with cleanup after is then you have multiple event-ID's for a single clip, so referencing the clip is difficult (unless you are creating symlinks or something... and that becomes messy too).  No easy solution...

DeadEnd

**Comment by hawkeye217** [comment]
> The more I think about this, the harder it gets to solve. The issue is that I cannot predict when the events are going to end. For example, let's say 2 people are walking in opposite directions in front of your house. One of them keeps walking by, but the other person decides to stop and talk on the phone for 10 minutes while still in view of the camera.

If the person who stopped walking and talked on the phone for 10 minutes was not in motion and Frigate stopped tracking them, I wouldn't mind a 2nd clip that only began when they started moving again.  Or even a new clip that began after ```max_seconds``` would work.  

> For now, I think the best I could do is proactively cleanup events/clips after they have been created if the time ranges obviously overlap.

This would definitely be helpful in the meantime!  Thanks Blake, this project is awesome.

**Comment by blakeblackshear** [comment]
> If the person who stopped walking and talked on the phone for 10 minutes was not in motion

I'm assuming here that they don't quite stop moving enough, but the next version will already work this way if they stop moving.

> Or even a new clip that began after `max_seconds` would work.

This could be interesting.

**Comment by blakeblackshear** [comment]
I implemented some duplicate removal logic in the event cleanup process that runs every 5 minutes. It groups events that started within 10 seconds of each other and removes everything but the longest one. Not perfect, but I think it covers a majority of the duplicates.

**Comment by thinkloop** [comment]
I get duplicates like this for most events:

![image](https://github.com/blakeblackshear/frigate/assets/118814/ce7c279a-f7d4-4297-ab50-6007dafa34ab)

**Comment by lutfijw** [comment]
Reopening this case again as I notice when Frigate is still recording an event, it mark the event as progressing. If the event logic can be changed to before opening new event, check if there is ongoing event happen on the camera, if yes, combine the event into one (keep marking the initial recording as in progress, until the second event stopped)

Event will start from the time when the first event started and ended when there is no more event/object detected.

From the example you gave and with the above logic in place, the clip will span from the first person walking until the second person moved from the camera point of view.

**Comment by hawkeye217** [comment]
The situation is significantly more complex than that, unfortunately.

Changes have already been made in the upcoming version of Frigate (0.14) that better address this behavior.
