### ISSUE TITLE
WebP support for clip photos

### ISSUE THREAD

**Issue by Volkor3-16** [blakeblackshear/frigate#6303]
**Describe what you are trying to accomplish and why in non technical terms**
I'd like the camera clips to use webp instead if png, so I don't have tens of thousands of images taking up hundreds of gb in my archive.

**Describe the solution you'd like**
An option to set webp over png for the clips (or potentially any other supported file format)

**Describe alternatives you've considered**
Manually encoding the images myself, but I don't know if that'll break things with the application, so I haven't tried.

**Additional context**
webp is much more efficient than png, and is supported on all browsers except Internet Explorer (https://caniuse.com/webp)
Having this option would allow for decent filesize savings, for no quality loss.

**Comment by NickM-27** [comment]
Given the way that the existing snapshots are implemented, there is no easy way to switch them to webp while maintaining support for existing snapshots.

However, frigate is currently undergoing a UI rewrite and the current snapshots are not used in the UI. All new image types are using the webp codec.
