### ISSUE TITLE
Make motion masks resolution agnostic

### ISSUE THREAD

**Issue by sshaikh** [blakeblackshear/frigate#6309]
**Describe what you are trying to accomplish and why in non technical terms**
I want to avoid recalculating masks when fiddling with detect resolutions

**Describe the solution you'd like**
For masks to be defined abstractly from detect resolutions.

**Describe alternatives you've considered**
Currently I recalculate my masks by the factor I used to change the detect resolution.

**Additional context**
Either make the mask points percentages or include a reference resolution alongside their definitions.

**Comment by ctml91** [comment]
I haven't been adjusting my detect resolutions and still find the alignment randomly changes after editing in UI, saving, and restarting.

<img width="902" alt="image" src="https://github.com/blakeblackshear/frigate/assets/74685281/47f223aa-3dc5-457b-8a9e-3d3d03874ee1">

This is supposed to be my "lawn" zone, most points need to be shifted down by 50-100 pixels. The weird thing is it doesn't seem to be all points, the ones on the right look like they are in the correct position.

Have also experienced when editing using the UI and saving, after restarting one point is completely reset to some edge coordinate (like 0,0 or the max width/height I cant recall which).
