### ISSUE TITLE
Show error message instead of last frame for offline cameras

### ISSUE THREAD

**Issue by michelle-avery** [blakeblackshear/frigate#6315]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to clear object presence when a camera is not accessible, so that things don't show up as perpetually present if the camera has been turned off.

**Describe the solution you'd like**
I'd like the images from the camera to show an error message, or a blank screen, if the camera has not been available for a certain amount of time. 

**Describe alternatives you've considered**
I think I may be able to manually clear object detection states, but even if that's the case, it can be confusing to see an image from days ago when I check on my cameras.

**Additional context**
We have a lot of exterior always-on cameras which I imagine is a frequent use case. We do, however, also have one internal camera, but we normally leave it off and only turn it on periodically for specific pet-related reasons. We're using IP4M-1041's which have a "privacy mode" that can be enabled which physically covers the lens and stops the stream. While it's in privacy mode, the RTSP call seems to return a 404. Frigate, however, continues to show the last frame in the interface. Given one of our uses is to detect our dog at the back door, then turn off the camera, this has the effect of always leaving dog presence on, since the dog is in the frame when the camera is turned off. There are ways I can work around this specifically, but they're a little convoluted and brittle, and all of them still result in the Frigate interface still showing that frame, which can be confusing.

**Comment by NickM-27** [comment]
Where are you seeing this image? Frigate already shows an error message for cameras that are offline in 0.12

![Screenshot_20230428_172320_Chrome Beta.jpg](https://user-images.githubusercontent.com/14866235/235269059-514e37be-f4ec-4df5-8ce9-bf3fe908e9a6.jpg)

**Comment by michelle-avery** [comment]
Ah, is that new in .12? I forgot I reverted my install to .11 after some issues trying to upgrade. If it's not new, then there's probably something else odd going on with my setup.

**Comment by NickM-27** [comment]
It is new for 0.12 so that makes sense.

**Comment by michelle-avery** [comment]
Ah, that's my fault for not checking the new version. Thank you!

**Comment by NickM-27** [comment]
We'd be happy to provide support for the issues upgrading as well 👍
