### ISSUE TITLE
[Support]: Birdseye maximum rescale view is limited to 1280x720

### ISSUE THREAD

**Issue by Homas** [blakeblackshear/frigate#6340]
### Describe the problem you are having

Frigate 0.12.0 limits maximum screen rescale size on the birdseye view to 1280x720. On the large monitors it is an issue.
It is due to the `max-w-7xl` class applied to the outer div.
In html:
```
<div class="max-w-7xl">
<div class="jsmpeg" style="position: relative;">
```
Likely this code in `/web/src/routes/Birdseye.jsx`
```
      <Fragment>
        <div className="max-w-7xl xl:w-1/2">
          <JSMpegPlayer camera="birdseye" />
        </div>
      </Fragment>
```

### Version

0.12.0

### Frigate config file

```yaml
not relevant
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

not relevant

**Comment by NickM-27** [comment]
This is on purpose, you can click the jsmpeg view to open fullscreen or you can use the fullscreen button of the MSE / WebRTC players. In 0.13 the extra space will be taken up by camera controls.

**Comment by hawkeye217** [comment]
I too have a large monitor and ran into this issue - apparently it is by design according to [this discussion](https://github.com/blakeblackshear/frigate/discussions/5652#discussioncomment-5220249) I had back in March.

I just removed the class (as well as a `max-w-5xl` on the cameras view) and everything works fine.

**Comment by Homas** [comment]
> This is on purpose, you can click the jsmpeg view to open fullscreen or you can use the fullscreen button of the MSE / WebRTC players. In 0.13 the extra space will be taken up by camera controls.
> 
> ![Screen Shot 2023-02-08 at 07 06 21 AM](https://user-images.githubusercontent.com/14866235/217552681-080b4ad6-157a-4d46-8d92-87b0b1978d3e.png)
Thanks for the explanation. My monitor is 3440x1440, so I have plenty of space for everything. It would be good to have it configurable.



> I just removed the class (as well as a `max-w-5xl` on the cameras view) and everything works fine.
Yep. In my case I had to remove `max-w-7xl`

**Comment by Homas** [comment]
> I'm happy to create a PR if it's still an issue once 0.13's controls are added.

Thanks

> Might also make sense to keep the video full width if a camera doesn't have ptz controls, but I'm sure that will be something considered.

It's about the birdeye's view. It is intended to be used with multiple cameras, unless there will be an ability to select which camera to manage I don't believe that such controls are needed here (they make sense per camera).
E.g. I've 12 cameras and only one has PTZ controls, 4 cameras even connected via neolink.

**Comment by NickM-27** [comment]
> Might also make sense to keep the video full width if a camera doesn't have ptz controls, but I'm sure that will be something considered.

have to say I disagree, to me the view taking up the full width when opening is jarring and also makes the fullscreen function redundant. I see no reason this is an issue given that the fullscreen function exists. 

> It's about the birdeye's view. It is intended to be used with multiple cameras, unless there will be an ability to select which camera to manage I don't believe that such controls are needed here (they make sense per camera).
E.g. I've 12 cameras and only one has PTZ controls, 4 cameras even connected via neolink.

Just like in my screenshot above, all ptz enabled cameras are manageable. This becomes really powerful if camera a sees someone and you want to use PTZ to move camera b to get a better look all within one single view in birdseye.

**Comment by Homas** [comment]
> Just like in my screenshot above, all ptz enabled cameras are manageable separently. This becomes really powerful if camera a sees someone and you want to use PTZ to move camera b to get a better look all within one single view in birdseye

Yep. I've missed that. Thanks. 
With my 12 cameras :) I would prefer to drill-down to a camera (when I click on an image) if I need to take a close view on something (PTZ per camera is good).

**Comment by NickM-27** [comment]
> > Just like in my screenshot above, all ptz enabled cameras are manageable separently. This becomes really powerful if camera a sees someone and you want to use PTZ to move camera b to get a better look all within one single view in birdseye
> 
> Yep. I've missed that. Thanks. With my 12 cameras :) I would prefer to drill-down to a camera (when I click on an image) if I need to take a close view on something (PTZ per camera is good).

that will require a lot of extra work to drill down to a specific camera from clicking on the video player. and again, I see a lot of value in being able to move one camera while seeing what is going on on another camera at the same time

**Comment by Homas** [comment]
> that will require a lot of extra work to drill down to a specific camera from clicking on the video player. and again, I see a lot of value in being able to move one camera while seeing what is going on on another camera at the same time

Yep. The other option is to have a modal window with the camera and controls.

**Comment by hawkeye217** [comment]
> have to say I disagree, to me the view taking up the full width when opening is jarring and also makes the fullscreen function redundant. I see no reason this is an issue given that the fullscreen function exists.

Personal preference, I guess. And I suppose this is only because @Homas and I have large monitors. Full screen is easy, but without the limiting max width class, I can make my Frigate browser window whatever size I want and the video image conforms to the width of the window without taking up my *entire* screen. 

Appreciate all your work on Frigate, @NickM-27 !

**Comment by NickM-27** [comment]
I do agree if you have a large window the max-width could be scaled to be more responsive in that case. But I still think the width should be maxed to an extend.

**Comment by hawkeye217** [comment]
Right. [This](https://user-images.githubusercontent.com/32435876/235517044-55de6544-89f1-4d94-91c9-ac6b0b1ce5a1.jpg) just doesn't feel right to me - I suppose it's just because of the amount of real estate and my browser zoom level...

I'm being really picky though, and it's easy enough for me to work around it.

**Comment by NickM-27** [comment]
The problem for me is when you increase the width you also increase the height. Without the max-width I had to scroll down and the entire birdseye view wasn't viewable at once. To me that's a terrible default experience.

**Comment by hawkeye217** [comment]
> To me that's a terrible default experience.

Definitely agree with that.
