### ISSUE TITLE
[Support]: Raspberry Pi Disk Image, frigate as MotionEye alternative?

### ISSUE THREAD

**Issue by flatsiedatsie** [blakeblackshear/frigate#6342]
### Describe the problem you are having

I found this project because it's being mentioned as a possible replacement for MotionEye, a popular project to turn a Raspberry Pi into an open source security camera. Motion Eye is no longer being developed.

However, I'm a little confused: can Frigate also import a video stream from a connected USB camera or ribbon-connected camera? Or can it only handle external rtsp cameras?

If it can read from attached cameras, then I'm wondering if there is a Raspberry Pi disk image for this project. If not, perhaps it's an idea to generate it? It would allow this project to fill the gap that MotionEye has left.

### Version

none

### Frigate config file

```yaml
none
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Raspberry Pi camera module v2

**Comment by NickM-27** [comment]
> However, I'm a little confused: can Frigate also import a video stream from a connected USB camera or ribbon-connected camera? Or can it only handle external rtsp cameras?

frigate uses ffmpeg for video streams which can read from a variety of sources including USB cameras and probably ribbon-connected cameras although I am not 100% sure on that part. 

> If it can read from attached cameras, then I'm wondering if there is a Raspberry Pi disk image for this project. If not, perhaps it's an idea to generate it? It would allow this project to fill the gap that MotionEye has left.

I am not sure what you are referring to disk image, but frigate is installed via docker.

**Comment by flatsiedatsie** [comment]
Cool!

By disk image I mean an image that users can 'burn' to an SD card (e.g. with Balena Etcher), and have a ready-to-go system. Many users, like me, are not well versed in Docker.

An example would be the asset list on [Motion Eye's releases page](https://github.com/motioneye-project/motioneyeos/releases). These are a bunch of zip files with .img files in them.

Making such an img file for Frigate, e.g. through a Github workflow, could make Frigate available to a wider audience.

**Comment by NickM-27** [comment]
To be clear, I don't speak for the project, but my gut is I don't think there's any interest in doing that. 

We've already said in the past that Frigate doesn't even offer a way to run frigate bare metal because there are too many dependency change and other issues between versions which would make an install like that pretty complicated. And if a user doesn't know docker odds are they would get stuck and have issues at some point with a preconfigured image anyway.

**Comment by flatsiedatsie** [comment]
I'm not asking for it to run bare metal. Just a Raspberry Pi disk image that is generated after all the installation steps in the documentation. So that would include the docker wrapper.

> And if a user doesn't know docker odds are they would get stuck and have issues at some point with a preconfigured image anyway.

I don't know enough about docker, so I'll have to take your word for that. But it's surprising to me that a pre-made docker system would lead to such issues. Can't a docker image be run automatically at boot? What kind of issues do you foresee?

**Comment by NickM-27** [comment]
> I don't know enough about docker, so I'll have to take your word for that. But it's surprising to me that a pre-made docker system would lead to such issues. 

all you have to do is look at the latest release notes to see all the changes that needed to be made to the docker config file between 0.11 and 0.12. If a user doesn't know docker then they'd be stuck on whatever release they downloaded. Also, there are plenty of UI based docker managers that can be used anyway and come with preconfigured frigate images.

> Can't a docker image be run automatically at boot? What kind of issues do you foresee?

yes a docker image can be run at boot.
