### ISSUE TITLE
[Support]: Home Assistant Integration Provides Incorrect URL for Full Access Add-On

### ISSUE THREAD

**Issue by joaldes** [blakeblackshear/frigate#6356]
### Describe the problem you are having

This is more of a bug report than needing support but I wasn't sure the best place to put it; sorry in advance if that's wrong.

When using the full access add-on, and then trying to install the Integration, it provides an incorrect URL to use. 

It provides:
`http://ccab4aaf-frigate:5000/`

But needs:
`http://ccab4aaf-frigate-fa:5000/`

I found this solution here: https://community.home-assistant.io/t/trying-to-install-frigate-but-get-failed-to-connect/450183/13?u=alecd

### Version

 0.12.0

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest

**Comment by jonandel** [comment]
I had made a similar comment about a year ago - solun was to update the docs on stallation for Frigate ... there it describes the URL required for FA, beta etc....
