### ISSUE TITLE
[Support]: Proxmox Portainer - failed to pull images of the stack: ghcr.io/blakeblackshear/frigate:stable

### ISSUE THREAD

**Issue by crazyfrog-github** [blakeblackshear/frigate#6377]
### Describe the problem you are having

Hi,

I have been using 0.11 (11) for a while in Proxmox LXC Portainer and want to upgrade to 0.12 (12) so I pointed the stack to: 

image: ghcr.io/blakeblackshear/frigate:stable

When I update the stack and try to redeploy I get:

**failed to pull images of the stack: frigate Pulling frigate Error Error response from daemon: Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)**

I have no problem connecting to ghcr.io/blakeblackshear/frigate:stable via a browser so not sure why I am getting this?

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by Coder84619** [comment]
I'm using a traditional Ubuntu VM on Proxmox with Portainer without any issues. Sounds like you issues is with Portainer, network, or something.

**Comment by Se7enair** [comment]
Can you ping 8.8.8.8 from the lxc container?

**Comment by crazyfrog-github** [comment]
> Can you ping 8.8.8.8 from the lxc container?

No I could not pint 8.8.8.8 from the container then I checked the default gateway and it was wrong, changed it and now I have version 12, looks great. Do you know if the go2rtc is setup automatically or I have to do something and my cameras say jsmpeg is that okay, from fresh upgrade is there anything I need to change to get the new features to work, I am using coral USB TPU.

**Comment by NickM-27** [comment]
> Do you know if the go2rtc is setup automatically or I have to do something and my cameras say jsmpeg is that okay, from fresh upgrade is there anything I need to change to get the new features to work, I am using coral USB TPU.

https://docs.frigate.video/guides/configuring_go2rtc

feel free to create a new issue if something else comes up
