### ISSUE TITLE
[Support]: Can somebody explain latest and snapshot pictures?

### ISSUE THREAD

**Issue by Se7enair** [blakeblackshear/frigate#6378]
### Describe the problem you are having

I dont unterstand it. Maybe to dumb to find the answer. Searched this repo and also google. Never tried chatGPT.

Doubletake is recieving latest and snapshot pictures from frigate. But what exactly is the difference between these?
When is latest created? Is it the last picture frigate used to recognize a object? and what is snapshot?

Are both pictures coming from the detect stream? If yes, is there a way to send this pictures from the record-stream? Because for face detection higher resolution should be better.

If this is already explained somewhere, please point me to it.

### Version

12

### Frigate config file

```yaml
irrelevant
```

### Relevant log output

```shell
irrelevant
```

### FFprobe output from your camera

```shell
irrelevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

irrelevant

**Comment by NickM-27** [comment]
> Doubletake is recieving latest and snapshot pictures from frigate. But what exactly is the difference between these?
When is latest created? Is it the last picture frigate used to recognize a object? and what is snapshot?

snapshot is the snapshot that frigate has saved for that particular object, it can change over the course of the event but does not change super often. latest has nothing to do with objects, it is literally just the latest frame that frigate has from the camera.

> Are both pictures coming from the detect stream? If yes, is there a way to send this pictures from the record-stream? Because for face detection higher resolution should be better.

both are from the detect stream. getting a snapshot from a stream requires decoding the stream which is considerable amount of work to do especially twice for every camera. There is a pinned feature request with more info on why it is not ideal https://github.com/blakeblackshear/frigate/issues/2199

**Comment by Se7enair** [comment]
Thank you for this fast response.
So latest would be better for face detection, because this is updated several times over the event. And doubletake scans every picture and stops as soon as a known face is detected? 

A separate high resolution stream for face detection would be nice. Will test to use the high resolution stream for detection according to #2199

**Comment by NickM-27** [comment]
> So latest would be better for face detection, because this is updated several times over the event. And doubletake scans every picture and stops as soon as a known face is detected?

Well, you can use both and Double-Take will pull from the separately. It's up to you and how you want it to work. 

> A separate high resolution stream for face detection would be nice. Will test to use the high resolution stream for detection according to #2199

Like I said it's complicated to implement and would potentially be more resource demand than just using the high res stream anyway (which is what I do, scaling high res stream down to 1280x960)
