### ISSUE TITLE
[Support]: exec ffmpeg hstack

### ISSUE THREAD

**Issue by mperone** [blakeblackshear/frigate#6400]
### Describe the problem you are having

I am trying to put together a mosaic stream so that my lower powered devices (wall mounted tablet dashboards) only need to make one video connection for a summary view rather than N individual connections (in my case 5) and I'd like it to be short and wide rather than the more square continuous birdseye view. So I'm setting up that stream using exec:ffmpeg and hstack. My question is if there's some kind of limit on this process that I'm unaware of?

The problem is that I see both of these just fine:

```
go2rtc:
  streams:
    ...
    mosaic:
      - exec:ffmpeg 
        -i rtsp://127.0.0.1:8554/doorbell_sub_stream
        -i rtsp://127.0.0.1:8554/front_sub_stream
        -i rtsp://127.0.0.1:8554/garage_sub_stream
        -filter_complex "[0:v]scale=-1:360[0v];[0v][1:v][2:v]hstack=inputs=3"
        -c:v libx264 -f rtsp {{output}}
```

and

```
go2rtc:
  streams:
    ...
    mosaic:
      - exec:ffmpeg 
        -i rtsp://127.0.0.1:8554/front_sub_stream
        -i rtsp://127.0.0.1:8554/garage_sub_stream
        -i rtsp://127.0.0.1:8554/side_sub_stream
        -filter_complex hstack=inputs=3
        -c:v libx264 -f rtsp {{output}}
```

but this one fails and the error messages I can find don't say anything other than basically 'exit status 1':

```
go2rtc:
  streams:
    ...
    mosaic:
      - exec:ffmpeg 
        -i rtsp://127.0.0.1:8554/doorbell_sub_stream
        -i rtsp://127.0.0.1:8554/front_sub_stream
        -i rtsp://127.0.0.1:8554/garage_sub_stream
        -i rtsp://127.0.0.1:8554/side_sub_stream
        -filter_complex "[0:v]scale=-1:360[0v];[0v][1:v][2:v][3:v]hstack=inputs=4"
        -c:v libx264 -f rtsp {{output}}
```

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
>  wide rather than the more square continuous birdseye view

to be clear, you can set birdseye to have whatever aspect ratio / resolution that you want it to

> but this one fails and the error messages I can find don't say anything other than basically 'exit status 1':

you should enable trace logs for exec to see the reason

```
go2rtc:

  streams:
    ...

  log:
    exec: trace
```

**Comment by mperone** [comment]
Thank you for responding so quickly!

Re: b

> to be clear, you can set birdseye to have whatever aspect ratio / resolution that you want it to

Yes, thanks - I should clarify that what I'm trying to do is have all my videos on one row. When I use birsdeye it's doing a grid with 2 rows, 3 cameras on top and 2 on bottom. Adjusting the resolution seems to keep this grid and just resize the cameras to fit in their spots in the fixed grid locations.

I will enable the trace log and take a look, thanks.

**Comment by mperone** [comment]
Oof, this is a lot of output and it doesn't on the face of it seem to indicate what exactly is wrong. I'm sure there's clues in here, I'll just have to try various configurations and figure out what's changing. Thanks.

**Comment by NickM-27** [comment]
Ffmpeg will tell you the reason for erroring. That being said, this isn't really a frigate issue as much as it's ffmpeg support so I'd suggest making this a discussion instead 👍

**Comment by mperone** [comment]
Thanks Nick.

I'll work on it (and in the background have my fingers crossed that an option to specify the birdseye grid layout... i.e. columns: N... becomes available in the case I don't figure it out!)
