### ISSUE TITLE
Option for Secure Delete of clips/recordings/etc. instead of just deletion

### ISSUE THREAD

**Issue by kdorff** [blakeblackshear/frigate#6411]
**Describe what you are trying to accomplish and why in non technical terms**
I'd like to have an per-`camera:` (`record:`?) option for `secure deletion` of video files (snapshots, events, clips, etc. anything that gets deleted instead of just `unlink`. There is a system-level unix command `srm` that exists or perhaps a function like below (taken from [StackOverflow](https://stackoverflow.com/questions/17455300/python-securely-remove-file))
```
def secure_delete(path, passes=3):
  with open(path, "ba+", buffering=0) as delfile:
      length = delfile.tell()
      delfile.close()
  with open(path, "br+", buffering=0) as delfile:
      for i in range(passes):
          delfile.seek(0,0)
          delfile.write(os.urandom(length))
      delfile.seek(0)
      for x in range(length):
          delfile.write(b'\x00')
      os.remove(path)
```

**Describe the solution you'd like**
When selected for a `camera:`, video or image files are deleted, the aren't just deleted they are securely deleted.

**Describe alternatives you've considered**
Per-`camera:` option for a shell command that will be executed before a file is deleted where I can supply a system command like `srm`. But I'd need something like `srm` in the docker container to leverage that.

**Additional context**
None.

**Comment by aleofreddi** [comment]
This one would be a useful one.
