### ISSUE TITLE
Add Share Link Direct to Event

### ISSUE THREAD

**Issue by norman350** [blakeblackshear/frigate#6416]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to share a link of an event on my local lan. 

**Describe the solution you'd like**
It might be a good enhancement to provide a capability on the events page which is part of the download icon that could link directly to the specific event.  Share event via link.

**Describe alternatives you've considered**
Downloading the event video and sending via email is a bit cumbersome.  It would be nice to keep all the video on the NVR and not move it around to other platforms.  A link directly to the event might be good option.

**Additional context**
Thanks!

**Comment by ctml91** [comment]
+1 would love to have sharing capability via link, preferably one using the public facing URL (maybe somehow with homeassistant?)

**Comment by SpangleLabs** [comment]
+1 indeed, even if it was LAN only in my case.

I've got alerts set up via HA, but I would like to have a link from the notification where I can view the event, view the clip, favourite the event, etc.

I even tried looking at whether there's anchors one can use and just link to the events listing scrolled to a given event, but there doesn't seem to be

**Comment by edalquist** [comment]
I have the same HA alert use case, where I want to be able to direct-link from the notification to the event in the review UI by passing the eventId on the URL

**Comment by NickM-27** [comment]
> I have the same HA alert use case, where I want to be able to direct-link from the notification to the event in the review UI by passing the eventId on the URL

that can already be done to be clear, if you use the /reviews topic for notifications then just link to `frigate_url/reviews?id=<review_id>` and it will open right to the item

**Comment by edalquist** [comment]
> > I have the same HA alert use case, where I want to be able to direct-link from the notification to the event in the review UI by passing the eventId on the URL
> 
> that can already be done to be clear, if you use the /reviews topic for notifications then just link to `frigate_url/reviews?id=<review_id>` and it will open right to the item

This works on a desktop browser but the rich web app installed on Android doesn't seem to honor the parameter. Should I open a separate bug for that issue?

**Comment by edalquist** [comment]
Ack, sorry for the noise here, I had a missing character in `clickAction` vs `url` in my notification template. Thank you for the support.

**Comment by NickM-27** [comment]
The share button for reviews has been implemented for 0.15
