### ISSUE TITLE
Some kind of indication that you have previously viewed a clip?

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#6419]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/6418

<div type='discussions-op-text'>

<sup>Originally posted by **LaurenceGough** May  7, 2023</sup>
Hey all,

What are your thoughts about some kind of indication in the events list that you have previously viewed a clip?

On many occasions I would have found this really useful personally when sorting through events and checking things.

Your thoughts?</div>

**Comment by LaurenceGough** [comment]
Thanks for creating this Blake, I wasn't quite sure where to raise it. Cheers

**Comment by NickM-27** [comment]
This has been implemented as part of the new ui rewrite. Events are marked as reviewed and have an indicator to show that as well.
