### ISSUE TITLE
[Support]: RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

### ISSUE THREAD

**Issue by Lucus123** [blakeblackshear/frigate#6454]
### Describe the problem you are having

as title says, frigate is unable to start due to this error occurring on starting the addon

2023-05-09 15:53:46.582290480  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-05-09 15:53:46.584422922  Traceback (most recent call last):
2023-05-09 15:53:46.584456307    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-05-09 15:53:46.586141459      return _run_code(code, main_globals, None,
2023-05-09 15:53:46.586693749    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-05-09 15:53:46.588009943      exec(code, run_globals)
2023-05-09 15:53:46.588525983    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-05-09 15:53:46.589749365      from frigate.app import FrigateApp
2023-05-09 15:53:46.590267281    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-05-09 15:53:46.591780245      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-05-09 15:53:46.592427587    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-05-09 15:53:46.593895343      from frigate.config import FrigateConfig
2023-05-09 15:53:46.594414040    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-05-09 15:53:46.595611432      import matplotlib.pyplot as plt
2023-05-09 15:53:46.596160129    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-05-09 15:53:46.602455476      from . import _api, _version, cbook, _docstring, rcsetup
2023-05-09 15:53:46.602892037    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-05-09 15:53:46.609196291      from matplotlib.colors import Colormap, is_color_like
2023-05-09 15:53:46.609752227    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-05-09 15:53:46.615089503      from matplotlib import _api, _cm, cbook, scale
2023-05-09 15:53:46.615780127    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-05-09 15:53:46.619416575      from matplotlib.ticker import (
2023-05-09 15:53:46.619789178    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-05-09 15:53:46.622859169      from matplotlib import transforms as mtransforms
2023-05-09 15:53:46.623581407    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-05-09 15:53:46.626610409      from matplotlib._path import (
2023-05-09 15:53:46.626690878  ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 27, in <module>
    config: dict[str, any] = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],

this causes Frigate to exit.

### Version

0.12.0

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
2023-05-09 15:53:46.582290480  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-05-09 15:53:46.584422922  Traceback (most recent call last):
2023-05-09 15:53:46.584456307    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-05-09 15:53:46.586141459      return _run_code(code, main_globals, None,
2023-05-09 15:53:46.586693749    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-05-09 15:53:46.588009943      exec(code, run_globals)
2023-05-09 15:53:46.588525983    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-05-09 15:53:46.589749365      from frigate.app import FrigateApp
2023-05-09 15:53:46.590267281    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-05-09 15:53:46.591780245      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-05-09 15:53:46.592427587    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-05-09 15:53:46.593895343      from frigate.config import FrigateConfig
2023-05-09 15:53:46.594414040    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-05-09 15:53:46.595611432      import matplotlib.pyplot as plt
2023-05-09 15:53:46.596160129    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-05-09 15:53:46.602455476      from . import _api, _version, cbook, _docstring, rcsetup
2023-05-09 15:53:46.602892037    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-05-09 15:53:46.609196291      from matplotlib.colors import Colormap, is_color_like
2023-05-09 15:53:46.609752227    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-05-09 15:53:46.615089503      from matplotlib import _api, _cm, cbook, scale
2023-05-09 15:53:46.615780127    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-05-09 15:53:46.619416575      from matplotlib.ticker import (
2023-05-09 15:53:46.619789178    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-05-09 15:53:46.622859169      from matplotlib import transforms as mtransforms
2023-05-09 15:53:46.623581407    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-05-09 15:53:46.626610409      from matplotlib._path import (
2023-05-09 15:53:46.626690878  ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 27, in <module>
    config: dict[str, any] = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

reolink

**Comment by NickM-27** [comment]
Are you running HA OS in 32bit? This happens for some users, recommendation is to upgrade to 64bit OS

**Comment by n-shay** [comment]
Having same issue here, exact same log.

Happening when I switched the repo to the one hosted on ghcr.io.
Fortunately, I still have the previous repo image cached locally so I was able to switch back and run it.

Not sure which version I have running and I can't find any indication anywhere.
One thing I know for sure, the current docker stable version (0.12.0) is not working on my RPi2. 

@NickM-27 Is 32-bit not longer supported?

**Comment by blakeblackshear** [comment]
There is a build for it and some users are able to run the 32bit build. We haven't been able to track down this error, and we are removing 32bit support officially in 0.13.0.

**Comment by track0x1** [comment]
I am seeing this exact same error but clearly running x64:
```
pi@mypi:~ $ uname -a
Linux mypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

```
pi@mypi:~ $ uname -m
aarch64
```

**Comment by NickM-27** [comment]
You need to update the docker engine, this is different from the docker server version.

**Comment by Phzing** [comment]
Anything else you could say on this? 

I've updated docker ("sudo apt update", "sudo apt upgrade docker-ce", and "sudo apt upgrade docker") and then restarted docker ("sudo systemctl restart docker") but am still getting the same issue. 

I also tried updating the numpy library ("pip install --upgrade numpy"), then stopping frigate and removing it ("docker stop frigate" and "docker rm frigate") and then using docker-compose up -d, but still nothing.

**Comment by NickM-27** [comment]
> @NickM-27 Anything else you could say on this?
> 
> I've updated docker ("sudo apt update", "sudo apt upgrade docker-ce", and "sudo apt upgrade docker") and then restarted docker ("sudo systemctl restart docker") but am still getting the same issue.

Take a look at https://github.com/blakeblackshear/frigate/issues/6708#issuecomment-1579648955 which has more details

> I also tried updating the numpy library ("pip install --upgrade numpy"), then stopping frigate and removing it ("docker stop frigate" and "docker rm frigate") and then using docker-compose up -d, but still nothing.

of course, because changing the dependency on your host will not affect numpy inside frigate in any way

**Comment by Phzing** [comment]
Thanks for the link @NickM-27. Before I go further, I should mention that I'm pretty new to all of this. I've just upgraded, following the guide attached in the comment you linked until I completed the section titled "Upgrade Docker Engine", then restarted the containers but the error still persists and the loading screen is not fixed.

**Comment by NickM-27** [comment]
are you sure you are running a 64 bit OS? That is another issue

**Comment by Phzing** [comment]
I am running docker on Raspberry Pi OS which is 32 bit, so I guess this is the problem. Is there any way I can solve this?

**Comment by NickM-27** [comment]
Upgrade to a 64 bit OS

**Comment by track0x1** [comment]
> You need to update the docker engine, this is different from the docker server version. Other users have confirmed this to be the fix.

I am running the latest version of Docker server
```
pi@mypi:~ $ docker version
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:07 2023
 OS/Arch:           linux/arm
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:07 2023
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

**Comment by cmrenus** [comment]
I also have the same error. Running 64 bit OS on a pi and 64 docker. So not sure that is the problem. Any suggestions? 
`pi@raspberrypi:~/home $ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 10
  Paused: 0
  Stopped: 5
 Images: 51
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.103-v8+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.28GiB
 Name: raspberrypi
 ID: OPZP:2AFE:LPMM:FGUV:2F2G:MLQT:UKCX:3ZEA:45JX:YCW4:XT2H:DC2Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**Comment by NickM-27** [comment]
> I also have the same error. Running 64 bit OS on a pi and 64 docker. So not sure that is the problem. Any suggestions? 

It is one of the problems, 64 bit users have found that https://github.com/blakeblackshear/frigate/issues/6708#issuecomment-1579648955 fixed the issue for them

**Comment by cmrenus** [comment]
So I thought I was up to date but guess not. even after updating, still see the same error. Let me try to do a fresh install I guess and see how that goes.

**Comment by cmrenus** [comment]
I am still confused though, how the following error could be related to docker version since this is containerized. 
` RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf`

**Comment by cmrenus** [comment]
So to update, I have got some things working. Docker seems to detect my OS as arm/v8. That shuold be 64 bit, but for whatever reason, is not working approproately. If I try to use the specific x64 image here:
https://github.com/blakeblackshear/frigate/pkgs/container/frigate/100534713?tag=0.12.1

And then specify the platform:
`export DOCKER_DEFAULT_PLATFORM=linux/amd64`

Then it works

**Comment by josh-m-sharpe** [comment]
Hi 👋  - I'm seeing the same thing.  I had a spare raspberry pi4b lying around and just yesterdday downloaded the latest rasp OS Lite (headless) version and installed - then a lot of apt-get update/upgrading.  I think I'm pretty close to up to date as you can be:

```
$ uname -m
aarch64
$ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
$ docker --version
Docker version 24.0.2, build cb74dfc
```

Here's my docker-compose (I know it's incomplete - was just trying to get frigate up and running to see its UI first)
```
version: "3.3"
services:
  frigate:
    # container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    # shm_size: "64mb" # update for your cameras based on calculation above
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    #   - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    #   - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
    #   - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml
      - /mnt/frigate:/media/frigate
    #   - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
    #     target: /tmp/cache
    #     tmpfs:
    #       size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

Here's `docker compose up`

```
frigate-frigate-1  | s6-rc: info: service s6rc-fdholder: starting
frigate-frigate-1  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate-frigate-1  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate-frigate-1  | s6-rc: info: service fix-attrs: starting
frigate-frigate-1  | s6-rc: info: service s6rc-fdholder successfully started
frigate-frigate-1  | s6-rc: info: service fix-attrs successfully started
frigate-frigate-1  | s6-rc: info: service legacy-cont-init: starting
frigate-frigate-1  | s6-rc: info: service legacy-cont-init successfully started

frigate-frigate-1  | s6-rc: info: service log-prepare: starting
frigate-frigate-1  | s6-rc: info: service log-prepare successfully started
frigate-frigate-1  | s6-rc: info: service nginx-log: starting
frigate-frigate-1  | s6-rc: info: service go2rtc-log: starting
frigate-frigate-1  | s6-rc: info: service frigate-log: starting

frigate-frigate-1  | s6-rc: info: service nginx-log successfully started
frigate-frigate-1  | s6-rc: info: service frigate-log successfully started
frigate-frigate-1  | s6-rc: info: service go2rtc-log successfully started
frigate-frigate-1  | s6-rc: info: service go2rtc: starting
frigate-frigate-1  | s6-rc: info: service go2rtc successfully started
frigate-frigate-1  | s6-rc: info: service go2rtc-healthcheck: starting
frigate-frigate-1  | s6-rc: info: service frigate: starting

frigate-frigate-1  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate-frigate-1  | s6-rc: info: service frigate successfully started
frigate-frigate-1  | s6-rc: info: service nginx: starting
frigate-frigate-1  | 2023-06-19 22:10:00.587256608  [INFO] Preparing go2rtc config...
frigate-frigate-1  | 2023-06-19 22:10:00.597154990  [INFO] Starting Frigate...
frigate-frigate-1  | 2023-06-19 22:10:00.602670972  [INFO] Starting NGINX...

frigate-frigate-1  | s6-rc: info: service nginx successfully started
frigate-frigate-1  | s6-rc: info: service legacy-services: starting

frigate-frigate-1  | s6-rc: info: service legacy-services successfully started

frigate-frigate-1  | 2023-06-19 22:10:01.375960360  [INFO] Starting go2rtc...
frigate-frigate-1  | 2023-06-19 22:10:01.564078879  22:10:01.563 INF go2rtc version 1.2.0 linux/arm
frigate-frigate-1  | 2023-06-19 22:10:01.565790362  22:10:01.565 INF [api] listen addr=:1984
frigate-frigate-1  | 2023-06-19 22:10:01.567665695  22:10:01.567 INF [rtsp] listen addr=:8554
frigate-frigate-1  | 2023-06-19 22:10:01.569484658  22:10:01.569 INF [srtp] listen addr=:8443
frigate-frigate-1  | 2023-06-19 22:10:01.571356158  22:10:01.571 INF [webrtc] listen addr=:8555
frigate-frigate-1  | 2023-06-19 22:10:01.600072092  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
frigate-frigate-1  | 2023-06-19 22:10:01.601449819  Traceback (most recent call last):
frigate-frigate-1  | 2023-06-19 22:10:01.601471522    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
frigate-frigate-1  | 2023-06-19 22:10:01.601576132      return _run_code(code, main_globals, None,
frigate-frigate-1  | 2023-06-19 22:10:01.601623669    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
frigate-frigate-1  | 2023-06-19 22:10:01.603105876      exec(code, run_globals)
frigate-frigate-1  | 2023-06-19 22:10:01.603127802    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.603138302      from frigate.app import FrigateApp
frigate-frigate-1  | 2023-06-19 22:10:01.603216005    File "/opt/frigate/frigate/app.py", line 17, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.603295671      from frigate.comms.dispatcher import Communicator, Dispatcher
frigate-frigate-1  | 2023-06-19 22:10:01.603341781    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.604787619      from frigate.config import FrigateConfig
frigate-frigate-1  | 2023-06-19 22:10:01.606821154    File "/opt/frigate/frigate/config.py", line 9, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.606839357      import matplotlib.pyplot as plt
frigate-frigate-1  | 2023-06-19 22:10:01.606888801    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.606986189      from . import _api, _version, cbook, _docstring, rcsetup
frigate-frigate-1  | 2023-06-19 22:10:01.606998152    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.607008411      from matplotlib.colors import Colormap, is_color_like
frigate-frigate-1  | 2023-06-19 22:10:01.609130390    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.609166149      from matplotlib import _api, _cm, cbook, scale
frigate-frigate-1  | 2023-06-19 22:10:01.609307203    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.609321851      from matplotlib.ticker import (
frigate-frigate-1  | 2023-06-19 22:10:01.609332240    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.609342147      from matplotlib import transforms as mtransforms
frigate-frigate-1  | 2023-06-19 22:10:01.609352332    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
frigate-frigate-1  | 2023-06-19 22:10:01.609497979      from matplotlib._path import (
frigate-frigate-1  | 2023-06-19 22:10:01.609511590  ImportError: numpy.core.multiarray failed to import
frigate-frigate-1  | 2023-06-19 22:10:01.754713614  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate-frigate-1  | s6-rc: info: service legacy-services: stopping
frigate-frigate-1  | s6-rc: info: service legacy-services successfully stopped
frigate-frigate-1  | s6-rc: info: service nginx: stopping
frigate-frigate-1  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate-frigate-1  | 2023-06-19 22:10:01.792846639  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate-frigate-1  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate-frigate-1  | 2023-06-19 22:10:01.854770480  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate-frigate-1  | s6-rc: info: service nginx successfully stopped
frigate-frigate-1  | s6-rc: info: service nginx-log: stopping
frigate-frigate-1  | s6-rc: info: service frigate: stopping
frigate-frigate-1  | s6-rc: info: service frigate successfully stopped
frigate-frigate-1  | s6-rc: info: service go2rtc: stopping
frigate-frigate-1  | s6-rc: info: service frigate-log: stopping
frigate-frigate-1  | 2023-06-19 22:10:01.867997996  exit OK
frigate-frigate-1  | s6-rc: info: service nginx-log successfully stopped
frigate-frigate-1  | s6-rc: info: service frigate-log successfully stopped
frigate-frigate-1  | 2023-06-19 22:10:01.883904188  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate-frigate-1  | s6-rc: info: service go2rtc successfully stopped
frigate-frigate-1  | s6-rc: info: service go2rtc-log: stopping
frigate-frigate-1  | s6-rc: info: service go2rtc-log successfully stopped
frigate-frigate-1  | s6-rc: info: service log-prepare: stopping
frigate-frigate-1  | s6-rc: info: service s6rc-fdholder: stopping
frigate-frigate-1  | s6-rc: info: service log-prepare successfully stopped
frigate-frigate-1  | s6-rc: info: service legacy-cont-init: stopping
frigate-frigate-1  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate-frigate-1  | s6-rc: info: service legacy-cont-init successfully stopped
frigate-frigate-1  | s6-rc: info: service fix-attrs: stopping
frigate-frigate-1  | s6-rc: info: service fix-attrs successfully stopped
frigate-frigate-1  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate-frigate-1  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by josh-m-sharpe** [comment]
Okay so this is weird, on my OSX laptop (where i dont plan on running frigate, but is definitely 64bit (arm, m1)):
```
docker image inspect ghcr.io/blakeblackshear/frigate:stable | grep Archite
        "Architecture": "arm64",
```

But on my pi:
```
docker image inspect ghcr.io/blakeblackshear/frigate:stable | grep Archi
        "Architecture": "arm",
```

**Comment by josh-m-sharpe** [comment]
Ah, noticed I downloaded 32-bit rasp software and put it on my 64-bit PI.  Grabbed the right arch and all is well.

**Comment by snoopfab** [comment]
> , noticed I downloaded 32-bi

Hi josh

Could you explain your fix ? I have the same issue but cannot understand what you did. What do you mean by "32-bit" rasp software ?

**Comment by n-shay** [comment]
> Could you explain your fix ? I have the same issue but cannot understand what you did. What do you mean by "32-bit" rasp software ?

The OS itself can be 32 or 64-bit (see [download](https://www.raspberrypi.com/software/operating-systems/) page).
If you have 32-bit OS, it can only run 32 bit software.

**Comment by track0x1** [comment]
I realized that despite my OS saying `aarch64` from my uname -m output, for whatever reason my OS was still only 32 bit. I wiped the drive and installed 64 bit Raspberry Pi OS and now I'm in business!

**Comment by mlepa84** [comment]
Do you think it would be possible to revert numpy to 1.12 for armv7 machines, as it seams to be causing "numpy version error compiled with API 0x10 installed 0xf" errors?
I've found this solution of a similar problem here:
https://github.com/tensorflow/tensorflow/issues/57106#issuecomment-1213350183

If this works and if possible could we have a fork of the project with this version, so the older Raspberry Pi 4 with armv7 would work fine?

**Comment by kurtleee** [comment]
> Do you think it would be possible to revert numpy to 1.12 for armv7 machines, as it seams to be causing "numpy version error compiled with API 0x10 installed 0xf" errors? I've found this solution of a similar problem here: [tensorflow/tensorflow#57106 (comment)](https://github.com/tensorflow/tensorflow/issues/57106#issuecomment-1213350183)
> 
> If this works and if possible could we have a fork of the project with this version, so the older Raspberry Pi 4 with armv7 would work fine?

I have already tried downgrading NumPy to version 1.12, but the issue persists when running the Frigate container using Portainer. The error in the logs matches the description in the current issue: RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf.

**Comment by mlepa84** [comment]
I managed to get frigate working by forking the v0.11.0 version.

**Comment by kurtleee** [comment]
Thanks, I will give it a try using this version and attempt again.

> I managed to get frigate working by forking the v0.11.0 version.
