### ISSUE TITLE
[Support]: Please push an updated image to https://hub.docker.com/r/blakeblackshear/frigate

### ISSUE THREAD

**Issue by henrik-muehe** [blakeblackshear/frigate#6459]
### Describe the problem you are having

I'd love to install Frigate using docker compose, however the images are somewhat outdated. Thanks a lot for your work!

### Version

0.12.0

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink

**Comment by NickM-27** [comment]
Docker compose supports ghcr without issues. You can simply set your image as ghcr.io/blakeblackshear/frigate:stable
