### ISSUE TITLE
web: allow dark mode via user preference

### ISSUE THREAD

**Issue by paularmstrong** [blakeblackshear/frigate#646]
Would like to make dark mode both auto-chosen via the media query AND by user preference. Will require a backing store with IndexedDB if manually set.

**Comment by blakeblackshear** [comment]
Use local storage for now. People aren't switching devices all that often, and they can click the toggle if needed. If they want a persistent default, it can be added to the config.

**Comment by paularmstrong** [comment]
I picked IndexedDB because it is a form of localstorage, but has a more robust API that will allow for more possibilities in the future.

**Comment by blakeblackshear** [comment]
Just realized that. Thanks.
