### ISSUE TITLE
Add API endpoints & UI for toggling detect/clip/snapshots on & off

### ISSUE THREAD

**Issue by paularmstrong** [blakeblackshear/frigate#647]

**Comment by blakeblackshear** [comment]
want me to add endpoints for this?

**Comment by paularmstrong** [comment]
I have only looked at it briefly and I think I know what needs to be done, just haven't prioritized it yet. I was thinking a POST-able endpoint that accepts JSON would be nice. If you are looking for something to do, feel free, otherwise I will look into it after I'm certain the UI updates are correct in all browsers

**Comment by blakeblackshear** [comment]
Don't forget that we will need to publish an mqtt state message so the switches in HA stay in sync,

**Comment by paularmstrong** [comment]
Yep! Something that's tripping me up is it seems that sometimes my Frigate instance loses connection to MQTT and stops updating, so I'm getting a little tripped up ensuring everything is in sync
