### ISSUE TITLE
[MQTT] Hide credentials (username+password) in the debug-section of WebUI

### ISSUE THREAD

**Issue by SHU-red** [blakeblackshear/frigate#6470]
**Describe what you are trying to accomplish and why in non technical terms**
- I recently added user and password to my MQTT broker
- Now Frigate needs to use a username and password to send messages to the broker
- I configured the username and password in the config.yml
- afaik i have to put in the credentials without obfuscation
- looking through my config in the debug-section shows my mqtt-brokers password

**Describe the solution you'd like**
- Obfuscation of password in web-UI
- The config.yml file on the server/host has anyways to be secured to prevent access
- But showing the credentials on the webui shows the password

**Describe alternatives you've considered**
- Password via environment variables --> Also shows the credentials in the debug-view?
- Password for frigate webui --> I dont want that due to slower access to the live-videos
- Encrypting password with some hash? (I have no knowledge in this)

**Comment by NickM-27** [comment]
This is already supported, you can use env variables for MQTT password and user https://docs.frigate.video/configuration/

**Comment by NickM-27** [comment]
Actually not sure on the debug section though, will have to check that.
