### ISSUE TITLE
☂️ web: style guide and more reusable components

### ISSUE THREAD

**Issue by paularmstrong** [blakeblackshear/frigate#651]
Current UI is arbitrary and basic just pulled from a couple things that tailwindcss offers quickly. A more coherent style and reusable components would help bring everything together better.

If anyone wants to play with the branch, it's available at https://github.com/paularmstrong/frigate/tree/styleguide

## TODO:

- [x] AppBar
- [x] NavigationBar
- [x] TextField
- [x] Select
- [x] Switch
- [x] Logo
- [x] Card
- [x] Button
- [x] Menu
- [x] Dialog
- [x] Camera view

**Comment by ljmerza** [comment]
would be good to get a list of components we think we need. 

for forms:
- form container
- dropdown 
- toggle
- input 
- chips

- image/video container
- general container
- sidebar
- sidebar link
- table, table header/column/row/cell

We'll have to think about what the config area will look like.

**Comment by paularmstrong** [comment]
> I also wonder if the dev resources are there for storybook or something similar. I personally dont have much experience in storybook though

Storybook is pretty heavy-handed for Frigate's needs. I think adding a dev-only path with every component displayed would be enough to get started.

Most things that aren't built yet can be put off until they're needed (most form bits, chips, dropdowns). For starters, I'd like to see about getting color, text, & logo items together and solidified.

> We'll have to think about what the config area will look like. 

This is going to need a lot of exploration. Even a first pass that just "gets it done" would help to better understand what's actually needed and we could go from there. I don't think we have an issue filed yet for editing the configuration.

**Comment by ljmerza** [comment]
I think all these components are needed now which is why I mention them. The form components are needed for the event filtering. If we create on an as needed basis, this will force the event filtering PR to also create the needed form inputs which would make it quite a large PR. We shouldn't have large PRs like that. I think a good compromise is basic inputs we know we need then slowly flesh them out during usage in other features.

**Comment by paularmstrong** [comment]
I think mostly following the [Material Design](https://material.io/components?platform=web) guidelines is the easiest way to go here, that way when there's a question, we can fall back to an open guide as a moderator.

Very early WIP (obviously select boxes aren't done)

<img width="488" alt="Screen Shot 2021-02-01 at 2 37 52 PM" src="https://user-images.githubusercontent.com/33297/106526818-192cb180-649b-11eb-93b5-9a0c893502af.png">

**Comment by paularmstrong** [comment]
I've updated the initial issue at the top to track the things getting done. There's quite a bit to create components that are both usable and accessible (think: keyboard navigation) and implement them across this small app. The branch I'm working from is at https://github.com/paularmstrong/frigate/tree/styleguide. But be warned, as I'll likely re-write the commit and force-push a lot.

**Comment by paularmstrong** [comment]
some progress…

https://user-images.githubusercontent.com/33297/106824982-d274be00-6638-11eb-9ff3-00341a68efd5.mov
