### ISSUE TITLE
Restream (birdseye) to mjpeg

### ISSUE THREAD

**Issue by mikalj2009** [blakeblackshear/frigate#6514]
Restream cameras or birdseye to mjpeg format

I have magicmirrors around and the software cant stream rtsp.
https://magicmirror.builders/

As of now, i use blue iris to host the mjpeg stream, but this requires two connections to the cameras in play - when using frigate.

Purpose is to have birdseye visible when there is motion or object on the mirror, and otherwise invisible.

**Comment by NickM-27** [comment]
This is already supported using the built in go2rtc

**Comment by NickM-27** [comment]
You can see https://github.com/AlexxIT/go2rtc#module-mjpeg for more info
