### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by gregmare** [blakeblackshear/frigate#6527]
### Describe the problem you are having

![image](https://github.com/blakeblackshear/frigate/assets/96090531/3768001b-1c12-42c2-b363-02e464ab0d43)

Apologies. New to Frigate so this might be a very simple solution.

### Version

Home Assistant 2023.5.3 Supervisor 2023.04.1 Operating System 10.1 Frontend 20230503.3 - latest

### Frigate config file

```yaml
mqtt:
  host: 10.10.10.229
cameras:
  Pool Area:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSWORD_Swa@10.10.10.53:554/ch01/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720
```

### Relevant log output

```shell
Home Assistant Core
2023-05-18 15:47:01.914 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-18 15:47:01.914 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-18 15:47:07.188 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.10.20.173 (10.10.20.173). Requested URL: '/api/websocket'. (Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.4.2 Chrome/102.0.5005.177 Safari/537.36)
```

### FFprobe output from your camera

```shell
Not sure
```

### Frigate stats

```json
Not sure
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

SWANN

### Any other information that may be helpful

https://au.swann.com/swdvk-856806rl/?setCurrencyId=1&gclid=CjwKCAjw9pGjBhB-EiwAa5jl3Ijy3IfuLyE76n_YObYvQ8u5Aj31O0LGjNeDPvimcwkiezIGUaq-ahoCy2IQAvD_BwE

**Comment by gregmare** [comment]
Thanks @NickM-27 

I added this to the config.yml with my custom details. Should this work?

go2rtc:
  streams:
    back:
      - rtsp://user:password@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2

**Comment by NickM-27** [comment]
I believe so

**Comment by gregmare** [comment]
Hello,

Excuse the ignorance, but still seeing this:

Could not determine suitable engine for camera. [Check troubleshooting](https://github.com/dermotduffy/frigate-hass-card#troubleshooting).
{
  "hide": false,
  "dependencies": {
    "all_cameras": false,
    "cameras": []
  },
  "triggers": {
    "motion": false,
    "occupancy": true,
    "entities": []
  },
  "engine": "auto",
  "frigate": {
    "client_id": "frigate"
  },
  "motioneye": {
    "images": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    },
    "movies": {
      "directory_pattern": "%Y-%m-%d",
      "file_pattern": "%H-%M-%S"
    }
  },
  "live_provider": "auto",
  "image": {
    "refresh_seconds": 1
  }
}




![image](https://github.com/blakeblackshear/frigate/assets/96090531/861ac7d5-820d-4979-916e-97694ae92cb0)

**Comment by NickM-27** [comment]
Please update with your full config

**Comment by gregmare** [comment]
I have kept it very simple while troubleshooting

mqtt:
  host: 10.10.10.229
go2rtc:
  streams:
    back:
      - rtsp://admin:gr3gm@r3@@_Swa@10.10.10.53:554/ch01/0
cameras:
 Pool Area:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSWORD_Swa@10.10.10.53:554/ch01/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720

**Comment by gregmare** [comment]
[config.txt](https://github.com/blakeblackshear/frigate/files/11544507/config.txt)

**Comment by gregmare** [comment]
Hello @NickM-27  Thanks again. As I said. Very new to this. Something like this?

Also, would I need a go2rtc entry for every camera?

mqtt:
  host: 10.10.10.229
go2rtc:
  streams:
    Pool Area:
      - rtsp://admin:PASSWORD_Swa@10.10.10.53:554/ch01/0
cameras:
 Pool Area:
    ffmpeg:
      inputs:
        - path: rtsp://admin:PASSWORD_Swa@10.10.10.53:554/ch01/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720

**Comment by NickM-27** [comment]
That should do it I think

**Comment by gregmare** [comment]
Still no luck:

mqtt:
  host: 10.10.10.229
go2rtc:
  streams:
    Pool Area:
      - rtsp://admin:password_Swa@10.10.10.53:554/ch01/0
cameras:
  Pool Area:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password_Swa@10.10.10.53:554/ch01/0
          roles:
            - detect
    detect:
      width: 1280
      height: 720

![image](https://github.com/blakeblackshear/frigate/assets/96090531/383171da-e473-45c4-bc84-c1be029cc7b3)

Beginning to think its time to throw in the towel :)

**Comment by gregmare** [comment]
Thanks, but think that is the sign for me. Appreciate the help. As far as I know all are up to date

**Comment by NickM-27** [comment]
I would suggest checking, many users have thought it was up to date only to find it was very much out of date. If you are no longer interested in support then please close the issue 👍
