### ISSUE TITLE
[Support]: Object in zone... even though it wasn't

### ISSUE THREAD

**Issue by sshaikh** [blakeblackshear/frigate#6541]
### Describe the problem you are having

I've receiving MQTT events that claim an object had been in a defines zone, even though visually it isn't/wasn't 

### Version

0.12.0-da3e197

### Frigate config file

```yaml
front-door:
    ffmpeg:
      inputs:
        - path: rtsp://cctv:{FRIGATE_RTSP_PASSWORD}@front-door-camera:554/unicast
          #rtsp://127.0.0.1:8554/front-door
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 306,128,288,382,906,385,921,438,1028,396,1038,573,1920,626,1920,0,335,0,298,65,0,67,0,125
    zones:
      driveway-zone:
          coordinates: 1920,1080,1920,639,774,552,0,631,0,1080
    record:
      events:
        required_zones:
          - driveway-zone
    snapshots:
      required_zones:
        - driveway-zone
```

### Relevant log output

```shell
MQTT entries:

12:40:45.538 QoS:AtMostOnce  frigate/events                                     Payload(1123): {"before":{"id":"1684496447.852872-6yippf","camera":"front-door","frame_time":1684496447.852872,"snapshot_time":0,"label":"person","sub_label":null,"top_score":0,"false_positive":true,"start_time":1684496447.852872,"end_time":null,"score":0.55859375,"box":[1494,755,1505,770],"area":165,"ratio":0.7333333333333333,"region":[1372,532,1920,1080],"stationary":false,"motionless_count":0,"position_changes":0,"current_zones":[],"entered_zones":[],"has_clip":false,"has_snapshot":false},"after":{"id":"1684496447.852872-6yippf","camera":"front-door","frame_time":1684496456.450131,"snapshot_time":1684496456.450131,"label":"person","sub_label":null,"top_score":0.701171875,"false_positive":false,"start_time":1684496447.852872,"end_time":null,"score":0.82421875,"box":[1253,324,1336,573],"area":20667,"ratio":0.3333333333333333,"region":[1189,295,1509,615],"stationary":false,"motionless_count":0,"position_changes":1,"current_zones":[],"entered_zones":["driveway-zone"],"has_clip":true,"has_snapshot":true},"type":"new"}

12:40:50.528 QoS:AtMostOnce  frigate/events                                     Payload(1137): {"before":{"id":"1684496447.852872-6yippf","camera":"front-door","frame_time":1684496456.450131,"snapshot_time":1684496456.450131,"label":"person","sub_label":null,"top_score":0.701171875,"false_positive":false,"start_time":1684496447.852872,"end_time":null,"score":0.82421875,"box":[1253,324,1336,573],"area":20667,"ratio":0.3333333333333333,"region":[1189,295,1509,615],"stationary":false,"motionless_count":0,"position_changes":1,"current_zones":[],"entered_zones":["driveway-zone"],"has_clip":true,"has_snapshot":true},"after":{"id":"1684496447.852872-6yippf","camera":"front-door","frame_time":1684496460.655673,"snapshot_time":1684496456.671296,"label":"person","sub_label":null,"top_score":0.81640625,"false_positive":false,"start_time":1684496447.852872,"end_time":null,"score":0.5,"box":[675,357,693,373],"area":288,"ratio":1.125,"region":[600,268,1096,764],"stationary":false,"motionless_count":2,"position_changes":1,"current_zones":[],"entered_zones":["driveway-zone"],"has_clip":true,"has_snapshot":true},"type":"update"}

12:40:55.143 QoS:AtMostOnce  frigate/events                                     Payload(1121): {"before":{"id":"1684496447.852872-6yippf","camera":"front-door","frame_time":1684496460.655673,"snapshot_time":1684496456.671296,"label":"person","sub_label":null,"top_score":0.81640625,"false_positive":false,"start_time":1684496447.852872,"end_time":null,"score":0.5,"box":[675,357,693,373],"area":288,"ratio":1.125,"region":[600,268,1096,764],"stationary":false,"motionless_count":2,"position_changes":1,"current_zones":[],"entered_zones":["driveway-zone"],"has_clip":true,"has_snapshot":true},"after":{"id":"1684496447.852872-6yippf","camera":"front-door","frame_time":1684496460.655673,"snapshot_time":1684496456.671296,"label":"person","sub_label":null,"top_score":0.81640625,"false_positive":false,"start_time":1684496447.852872,"end_time":1684496465.860796,"score":0.5,"box":[675,357,693,373],"area":288,"ratio":1.125,"region":[600,268,1096,764],"stationary":false,"motionless_count":2,"position_changes":1,"current_zones":[],"entered_zones":["driveway-zone"],"has_clip":true,"has_snapshot":true},"type":"end"}
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.5-0+deb11u1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mp3float @ 0x55d4dbfb6ec0] Header missing
Input #0, rtsp, from 'rtsp://cctv:nLqUSou10M4buIi2@front-door-camera.atal.cc:554/unicast':
  Metadata:
    title           : LIVE555 Streaming Media v2020.05.15
    comment         : LIVE555 Streaming Media v2020.05.15
  Duration: N/A, start: -0.179744, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: mp3, 44100 Hz, mono, fltp, 64 kb/s
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"2.2"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"0.0","mem":"0.0"},"111":{"cpu":"9.3","mem":"5.1"},"119":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"14833":{"cpu":"4.3","mem":"1.5"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"188636":{"cpu":"2.3","mem":"1.3"},"189995":{"cpu":"2.7","mem":"1.4"},"192099":{"cpu":"0.0","mem":"0.0"},"192156":{"cpu":"0.0","mem":"0.1"},"192159":{"cpu":"0.0","mem":"0.1"},"192170":{"cpu":"0.3","mem":"0.1"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"285":{"cpu":"0.0","mem":"0.8"},"29":{"cpu":"0.0","mem":"0.0"},"291":{"cpu":"0.7","mem":"0.1"},"292":{"cpu":"0.0","mem":"1.1"},"293":{"cpu":"2.0","mem":"1.0"},"297":{"cpu":"0.0","mem":"0.0"},"298":{"cpu":"0.7","mem":"1.1"},"299":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"1.0","mem":"1.1"},"301":{"cpu":"0.0","mem":"0.0"},"302":{"cpu":"0.3","mem":"1.0"},"303":{"cpu":"0.0","mem":"0.0"},"304":{"cpu":"1.3","mem":"1.1"},"305":{"cpu":"1.0","mem":"2.0"},"306":{"cpu":"0.0","mem":"0.0"},"307":{"cpu":"0.7","mem":"0.9"},"308":{"cpu":"0.0","mem":"0.0"},"309":{"cpu":"1.0","mem":"0.9"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"1.3","mem":"1.0"},"311":{"cpu":"0.0","mem":"0.0"},"314":{"cpu":"1.0","mem":"1.0"},"315":{"cpu":"0.0","mem":"0.0"},"316":{"cpu":"1.7","mem":"0.4"},"317":{"cpu":"1.0","mem":"1.0"},"32":{"cpu":"0.0","mem":"0.0"},"321":{"cpu":"1.0","mem":"1.0"},"327":{"cpu":"3.7","mem":"1.1"},"335":{"cpu":"0.7","mem":"1.0"},"337":{"cpu":"1.3","mem":"0.3"},"339":{"cpu":"1.7","mem":"0.5"},"344":{"cpu":"0.7","mem":"0.2"},"350":{"cpu":"0.7","mem":"1.0"},"358":{"cpu":"1.0","mem":"0.2"},"360":{"cpu":"1.3","mem":"0.2"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"477":{"cpu":"1.3","mem":"0.3"},"479":{"cpu":"0.7","mem":"0.2"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"95":{"cpu":"9.3","mem":"0.6"},"MiB":{"cpu":"2468.5","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"decking":{"camera_fps":6.0,"capture_pid":314,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":477,"pid":300,"process_fps":6.0,"skipped_fps":0.0},"detection_fps":1.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":9.21,"pid":292}},"driveway":{"camera_fps":6.0,"capture_pid":310,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":316,"pid":298,"process_fps":6.0,"skipped_fps":0.0},"extension-roof":{"camera_fps":6.0,"capture_pid":317,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":339,"pid":302,"process_fps":6.1,"skipped_fps":0.0},"front-door":{"camera_fps":5.0,"capture_pid":327,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":14833,"pid":305,"process_fps":5.0,"skipped_fps":0.0},"garden":{"camera_fps":6.0,"capture_pid":321,"detection_enabled":1,"detection_fps":1.6,"ffmpeg_pid":337,"pid":304,"process_fps":6.0,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"2.51 %","mem":"- %"}},"living-room":{"camera_fps":7.0,"capture_pid":350,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":188636,"pid":309,"process_fps":7.0,"skipped_fps":0.0},"lower-hallway":{"camera_fps":7.1,"capture_pid":335,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":189995,"pid":307,"process_fps":7.1,"skipped_fps":0.0},"service":{"last_updated":1684508029,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":145.9,"mount_type":"tmpfs","total":157.3,"used":11.4},"/media/frigate/clips":{"free":148128.3,"mount_type":"ext4","total":1678394.6,"used":1444933.0},"/media/frigate/recordings":{"free":148128.3,"mount_type":"ext4","total":1678394.6,"used":1444933.0},"/tmp/cache":{"free":980.8,"mount_type":"tmpfs","total":1000.0,"used":19.2}},"temperatures":{"apex_0":54.05},"uptime":86503,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Fang Cam

### Any other information that may be helpful

I filter MQTT events on `entered_zones` to pick up relevant events.

Sometimes I get an event which on reviewing the snapshot and video clearly show the object not entering the zone. I've attached the relevant events above.

What I find peculiar is that there is never an event where "current_zone" is set, which makes me wonder why Frigate ever thought this was an entered zone.

I will note that there was a glitch on the camera feed in the non-masked motion part of the feed, which presumably set off the detection in the first place (the zone and motion mask compliment each other). But that happened a good 3 seconds before the object came into view.

**Comment by NickM-27** [comment]
There's some things wrong here:
1. It is discouraged to use motion masks to filter out uninteresting areas where objects are expected as this will cause problems. That is the whole point of zones.
2. Without a visual example it is difficult to suggest what is wrong, but this logic has not changed so most likely there was a single frame where the object was in the zone. We plan to improve this in 0.13

**Comment by sshaikh** [comment]
Hmm. I'm happy to try unmasking, but it was mainly to save on detection cycles, inspired by the docs "For example, you want to mask out your timestamp, the sky, rooftops, etc.". I'll have to see if the increased motion detections affects performance.

I'm happy to provide the relevant samples directly if you feel it would help. Like I said though, there was a feed glitch in the zone which would have triggered motion in the first place - would that count?

What's interesting to me (in that it shows my lack of understanding) is how in the first MQTT event (which was of `type: new`), the before had:

```
"current_zones":[],"entered_zones":[]
```

and the after had:

```
"current_zones":[],"entered_zones":["driveway-zone"]
```

And I would have expected an event with `current_zone` to be populated in between those.
```

**Comment by sshaikh** [comment]
According to the video, the person that was labelled did not enter the zone, although the glitch did happen in that window.

I suspect my confusion lies in when updated events are generated - I would have expected one when zones are crossed if it was significant enough to mark the object as having entered it.

I've reduced my masks to just the timestamp and will see how it goes.

**Comment by NickM-27** [comment]
> I suspect my confusion lies in when updated events are generated - I would have expected one when zones are crossed if it was significant enough to mark the object as having entered it.

Updates are not sent until the object is confirmed to be a true positive. Once that happens, a message is sent as soon as an object's zone presence is updated

**Comment by sshaikh** [comment]
Since reducing the motion mask on this particular camera, I'm seeing a lot more picked up "non relevant" alerts - it seems that the shadow of the object places the object as in the zone even though the respective bounding box of the object isn't. This kind of explains the original issue if frigate somehow thinks the feed glitch was part of the object too.

This leaves me wondering about the claim in the docs about the definition of an object being in a zone as depending on its bounding box. This doesn't seem to be the case for me, as any motion occurring at the same time seems to trigger a zone being entered.

I'll work around this by reducing my zone to account for cast shadows.

**Comment by NickM-27** [comment]
The presence of an object in a zone is based on the bottom center pixel of the bounding box. The motion area has nothing to do with that. The best way to debug this is to simply watch the debug view with bounding boxes and zones turned on. The zone will appear thicker when the object is considered in the zone.

**Comment by NickM-27** [comment]
In Frigate 0.13 there will be a debug view for recordings which will show key moments like when an object entered a zone with overlays like the current debug live view

**Comment by sshaikh** [comment]
Great thanks - I'll restore the zone and reassess when that's available. Thanks for the attention!

**Comment by sshaikh** [comment]
Unfortunately reducing the zone has made little difference to zone capture - on review detected object are definitely not entering the now minimal zone, but are being marked as such.

Also I'm getting around 50% more detections after reducing the motion mask, so I'll be putting that back as right now the alerts are way too numerous to be effective.

Hopefully being able to see bounding boxes on recorded events will help me understand what I'm doing wrong here.

**Comment by NickM-27** [comment]
If you show an image of the zone, motion mask, objects detected, etc it'll be a lot easier to make suggestions.

**Comment by sshaikh** [comment]
Is there any way to share this material privately?

**Comment by NickM-27** [comment]
You can email me at nickmowen213@gmail.com if you'd like

**Comment by sshaikh** [comment]
For completion, @NickM-27 advised that the event sample had a lot of false positives that appear in the zone. I am looking at some of the mitigations in the docs to minimise these.

Is there a way to tune these parameters against existing clips, or will that need the same improvement as described above (ie debug views on clips)?

**Comment by NickM-27** [comment]
You can use https://docs.frigate.video/development/contributing#2-modify-your-local-config-file-for-testing to run debug on existing clips to get an **APPROXIMATION** of what frigate originally saw. It won't be exactly what happened, however

**Comment by sshaikh** [comment]
I've managed to set up the problematic clip as a camera. Very useful. I can see a flower in the zone that is sometimes detected as a person which explains the event now.

I have noticed that the detected objects aren't necessarily consistent across loops though. For example after many loops the same flower stops being detected as a person (while the actual person is still). Is that expected? Some kind of longer context being used? If so is there a way to reset that without restarting?

**Comment by NickM-27** [comment]
Like I said it is an approximation. The regions sent to detection are not deterministic and will vary from clip run to clip run.

**Comment by sshaikh** [comment]
I'm trying to determine an appropriate min area to use in an object filter. Is the second number on bounding boxes their areas? If not, what's the best way to ascertain a figure, given that the mqtt area might not correspond to a snapshot?

**Comment by NickM-27** [comment]
yes, the second number is the area of that box in pixels
