### ISSUE TITLE
Add FLAC(PCMA/PCMU/PCM) support for MSE live view

### ISSUE THREAD

**Issue by lovelylain** [blakeblackshear/frigate#6546]
**Describe what you are trying to accomplish and why in non technical terms**
Currently frigate's MSE live view only support AAC audio, but many cameras give PCMA and lack AAC support. According to [go2rtc's docs](https://github.com/AlexxIT/go2rtc#built-in-transcoding),

Go2rtc support automatic repack PCMA/PCMU/PCM codecs to FLAC for MSE/MP4/HLS so they will work almost anywhere.
Go2rtc can pack PCMA, PCMU and PCM codecs into an MP4 container so that they work in all browsers and all built-in players on modern devices. Including Apple QuickTime:
```
PCMA/PCMU => PCM => FLAC => MSE/MP4/HLS
```
So it's possible to add FLAC(PCMA/PCMU/PCM) support for MSE live view.

**Describe the solution you'd like**
Currently frigate just send `{type: "mse"}`, [frigate](https://github.com/blakeblackshear/frigate/blob/dev/web/src/components/MsePlayer.jsx#L24)
Use `MediaSource.isTypeSupported` to test codecs support then send `{type: "mse", value: "<supported codecs>"}` like [go2rtc](https://github.com/AlexxIT/go2rtc/blob/master/www/video-rtc.js#L175) do.

**Comment by NickM-27** [comment]
This requires go2rtc 1.5 while frigate currently uses go2rtc 1.2 by default. I already have a PR to do this https://github.com/blakeblackshear/frigate/pull/5814
