### ISSUE TITLE
[Support] Enable external event to determine it's start time and thumbnail?

### ISSUE THREAD

**Issue by pingchesu** [blakeblackshear/frigate#6549]
**Describe what you are trying to accomplish and why in non technical terms**
Really thanks for this awesome project! Based on this integration guide [external event](https://github.com/blakeblackshear/frigate/blob/dev/docs/docs/integrations/api.md#post-apieventscamera_namelabelcreate), the api enable user to create event from external system. However, the start time and thumbnail of the event will be determined when calling the api [start_time](https://github.com/blakeblackshear/frigate/blob/dev/frigate/events/external.py#L40) [thumbnail](https://github.com/blakeblackshear/frigate/blob/dev/frigate/http.py#L866). This may somehow cause inaccurate start time and image because some event will be processed in external system.

**Describe the solution you'd like**
Maybe we could consider let user determine it's start time and thumbnail? The request body may be:
```python
{
  "thumbnail": "base64 string of external event ",
  "start_time": "the start time of external event",
  "subLabel": "some_string", // add sub label to event
  "duration": 30, // predetermined length of event (default: 30 seconds) or can be to null for indeterminate length event
  "include_recording": true, // whether the event should save recordings along with the snapshot that is taken
  "draw": {
    // optional annotations that will be drawn on the snapshot
    "boxes": [
      {
        "box": [0.5, 0.5, 0.25, 0.25], // box consists of x, y, width, height which are on a scale between 0 - 1
        "color": [255, 0, 0], // color of the box, default is red
        "score": 100 // optional score associated with the box
      }
    ]
  }
}
```

**Comment by NickM-27** [comment]
I don't think that really works. We don't have access to old frames for specific times and similarly if the start time was in the future we would essentially have to sit and wait until that time and then hope a frame is available.

I think this is much better handled by the service calling the API to just wait until it is relevant to start the event
