### ISSUE TITLE
[Support]: MQTT update messages and top scores

### ISSUE THREAD

**Issue by sshaikh** [blakeblackshear/frigate#6551]
### Describe the problem you are having

I'm trying to set up a series of automations in HA that trigger off events received on MQTT and send appropriate media to Telegram as follows. For brevity I've omitted the filtering contextual criteria (eg entered_zones, camera, label) I use to identify relevant events. As HA prefers not to store variables, I'm trying to lean on the MQTT payloads as much as possible:

- on `type: new`: Send the snapshot (retrieved from frigate via API) to Telegram
- on `type: update`: If `[after][score] == [after][top_score]`, send the (better) snapshot (retrieved from frigate via API) to Telegram
- on `type: end`: Send the clip (retrieved from frigate via API) to Telegram

This largely does what I want it to do, and a common pattern is to see the first detection when the object is detected, then get a new picture each time the score of the object improves, and finally receive a video of the event.

However there are times when I get a successive stream of identical pictures, due to receiving many `update` messages for which score == top_score, but with the snapshot not being updated. I'm trying to understand why I would receive such a stream of messages (assuming it's not just a matter of luck of getting so many identical top scores).

1. Is there a way to "statelessly" determine if an update message has resulted in a better snapshot having been made available? 
2. Why are update events being generated while no new snapshots are being made? Even if top scores happen to be tied for later detections, should we not expect the newer snapshot?

I suspect a lot of this could be worked around using a stateful script or program to deal with relevant updates, but given the integration with HA I would hope Frigate would lend itself to HA's paradigm.

### Version

0.12.0-da3e197

### Relevant log output

[ssagr2-mqtt.txt](https://github.com/blakeblackshear/frigate/files/11523126/ssagr2-mqtt.txt)

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"2.8"},"1":{"cpu":"0.0","mem":"0.0"},"108":{"cpu":"5.7","mem":"6.0"},"112":{"cpu":"0.0","mem":"0.0"},"119":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"17502":{"cpu":"4.0","mem":"1.1"},"18698":{"cpu":"0.0","mem":"0.0"},"18772":{"cpu":"0.0","mem":"0.1"},"18774":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"283":{"cpu":"0.0","mem":"1.2"},"289":{"cpu":"1.3","mem":"0.2"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"3.7","mem":"1.8"},"291":{"cpu":"3.7","mem":"1.6"},"295":{"cpu":"1.3","mem":"1.7"},"296":{"cpu":"0.0","mem":"0.2"},"297":{"cpu":"0.7","mem":"1.7"},"298":{"cpu":"1.3","mem":"1.7"},"299":{"cpu":"0.0","mem":"0.2"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"1.0","mem":"1.7"},"302":{"cpu":"13.0","mem":"2.6"},"303":{"cpu":"0.0","mem":"0.2"},"305":{"cpu":"1.3","mem":"1.6"},"31":{"cpu":"0.0","mem":"0.0"},"317":{"cpu":"1.0","mem":"1.6"},"318":{"cpu":"0.0","mem":"0.2"},"319":{"cpu":"2.0","mem":"1.6"},"32":{"cpu":"0.0","mem":"0.0"},"320":{"cpu":"1.3","mem":"1.6"},"324":{"cpu":"0.0","mem":"0.2"},"326":{"cpu":"2.0","mem":"1.6"},"330":{"cpu":"1.7","mem":"1.5"},"333":{"cpu":"6.0","mem":"1.7"},"334":{"cpu":"0.0","mem":"0.2"},"338":{"cpu":"2.0","mem":"1.5"},"346":{"cpu":"2.0","mem":"0.6"},"347":{"cpu":"0.0","mem":"0.2"},"351":{"cpu":"1.7","mem":"1.6"},"365":{"cpu":"0.0","mem":"0.2"},"368":{"cpu":"0.0","mem":"0.2"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"444":{"cpu":"2.7","mem":"0.7"},"445":{"cpu":"2.3","mem":"0.8"},"448":{"cpu":"1.7","mem":"0.4"},"449":{"cpu":"2.0","mem":"0.4"},"450":{"cpu":"2.3","mem":"0.8"},"4744":{"cpu":"4.3","mem":"0.7"},"509":{"cpu":"1.0","mem":"0.4"},"510":{"cpu":"1.7","mem":"0.4"},"511":{"cpu":"5.0","mem":"1.3"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"23.3","mem":"0.6"},"MiB":{"cpu":"2299.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"decking":{"camera_fps":6.1,"capture_pid":320,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":445,"pid":297,"process_fps":6.1,"skipped_fps":0.0},"detect-test":{"camera_fps":0.0,"capture_pid":null,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":0,"pid":null,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":8.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":8.32,"pid":290}},"driveway":{"camera_fps":6.1,"capture_pid":319,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":444,"pid":295,"process_fps":6.1,"skipped_fps":0.0},"extension-roof":{"camera_fps":6.1,"capture_pid":326,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":450,"pid":298,"process_fps":6.1,"skipped_fps":0.0},"front-door":{"camera_fps":5.1,"capture_pid":333,"detection_enabled":1,"detection_fps":8.2,"ffmpeg_pid":511,"pid":302,"process_fps":5.1,"skipped_fps":0.0},"garden":{"camera_fps":6.1,"capture_pid":330,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":346,"pid":301,"process_fps":6.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"2.86 %","mem":"- %"}},"living-room":{"camera_fps":7.0,"capture_pid":351,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":17502,"pid":317,"process_fps":7.0,"skipped_fps":0.0},"lower-hallway":{"camera_fps":7.1,"capture_pid":338,"detection_enabled":0,"detection_fps":0.0,"ffmpeg_pid":4744,"pid":305,"process_fps":7.1,"skipped_fps":0.0},"service":{"last_updated":1684613176,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":148.2,"mount_type":"tmpfs","total":157.3,"used":9.1},"/media/frigate/clips":{"free":148561.5,"mount_type":"ext4","total":1678394.6,"used":1444499.8},"/media/frigate/recordings":{"free":148561.5,"mount_type":"ext4","total":1678394.6,"used":1444499.8},"/tmp/cache":{"free":984.0,"mount_type":"tmpfs","total":1000.0,"used":16.0}},"temperatures":{"apex_0":54.05},"uptime":8208,"version":"0.12.0-da3e197"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Fang Cam

**Comment by NickM-27** [comment]
There are a few things to understand here:
1. Frigate sends updates on the MQTT events topic on key moments like an object entering / exiting a zone, 60 seconds has passed since the last message, etc. Frigate will also send a message every minute an object has been stationary
2. Frigate does not always update the snapshot, this only happens based on the score and `best_image_timeout` settings. 

all of that being said, I would suggest ignoring `stationary == true` as a condition and that should fix the issue you are seeing.

**Comment by sshaikh** [comment]
All five of the update MQTT messages that had the triggering `score == top_score` critera also had `stationary:false` (and indeed in the clip the person was moving). All five retrieved snapshots were the same.

**Comment by NickM-27** [comment]
if we could see the actual messages that may be helpful, but in any case instead of checking score == top_score I would check before.top_score < after.top_score

**Comment by sshaikh** [comment]
The mqtt dump was attached in the opening message (albeit unclearly under logs).

Comparing before and after sounds like a good way forward though!

**Comment by blakeblackshear** [comment]
The `snapshot_time` should be different if the snapshot has been updated.

**Comment by sshaikh** [comment]
Unfortunately we don't have the snapshot time for the last top score, but I guess comparing it to `before` should do the trick here also.

In the `new` message what is `before` defined as?

**Comment by blakeblackshear** [comment]
Just checked the mqtt logs you posted. It is `0`.

**Comment by sshaikh** [comment]
Apologies I meant for the whole before section. What is "before" the new event?

**Comment by blakeblackshear** [comment]
Data about the object before it was determined to be a true_positive.

**Comment by sshaikh** [comment]
I'm still analysing MQTT messages, but here's something I saw:

```
 8:38:17.703 QoS:AtMostOnce  frigate/events                                     Payload(1108): {"before":{"id":"1684827492.271004-npprwp","camera":
"front-door","frame_time":1684827492.271004,"snapshot_time":0,"label":"person","sub_label":null,"top_score":0,"false_positive":true,"start_time":16
84827492.271004,"end_time":null,"score":0.53515625,"box":[613,339,625,355],"area":192,"ratio":0.75,"region":[261,0,753,492],"stationary":false,"mot
ionless_count":0,"position_changes":0,"current_zones":[],"entered_zones":[],"has_clip":false,"has_snapshot":false},"after":{"id":"1684827492.271004
-npprwp","camera":"front-door","frame_time":1684827499.074806,"snapshot_time":1684827499.074806,"label":"person","sub_label":null,"top_score":0.705
078125,"false_positive":false,"start_time":1684827492.271004,"end_time":null,"score":0.84375,"box":[291,81,592,974],"area":268793,"ratio":0.3370660
694288914,"region":[0,0,1440,1440],"stationary":false,"motionless_count":9,"position_changes":1,"current_zones":["driveway-zone"],"entered_zones":[
"driveway-zone"],"has_clip":true,"has_snapshot":true},"type":"new"}

 8:38:22.892 QoS:AtMostOnce  frigate/events                                     Payload(1174): {"before":{"id":"1684827492.271004-npprwp","camera":"front-door","frame_time":1684827499.074806,"snapshot_time":1684827499.074806,"label":"person","sub_label":null,"top_score":0.705078125,"false_positive":false,"start_time":1684827492.271004,"end_time":null,"score":0.84375,"box":[291,81,592,974],"area":268793,"ratio":0.3370660694288914,"region":[0,0,1440,1440],"stationary":false,"motionless_count":9,"position_changes":1,"current_zones":["driveway-zone"],"entered_zones":["driveway-zone"],"has_clip":true,"has_snapshot":true},"after":{"id":"1684827492.271004-npprwp","camera":"front-door","frame_time":1684827504.275751,"snapshot_time":1684827500.274939,"label":"person","sub_label":null,"top_score":0.84375,"false_positive":false,"start_time":1684827492.271004,"end_time":null,"score":0.84375,"box":[483,176,701,896],"area":156960,"ratio":0.30277777777777776,"region":[33,0,1221,1188],"stationary":false,"motionless_count":5,"position_changes":1,"current_zones":["driveway-zone"],"entered_zones":["driveway-zone"],"has_clip":true,"has_snapshot":true},"type":"update"}
```

My latest notification logic now tests for both the following:

```
{{ trigger.payload_json["after"]["score"] >= trigger.payload_json["after"]["top_score"]}}
{{ trigger.payload_json["after"]["snapshot_time"] > trigger.payload_json["before"]["snapshot_time"]}}
```

and so both messages above correctly triggered the sending of the latest snapshot. However, although the second snapshot was useful, it had a person score of 79% in the bounding box.

1. Should it be the case that `score` equals the figure given by the bounding box in a taken snapshot, or is that in the MQTT message some kind of further calculated metric?
2. Is it guaranteed that the latest snapshot saved for an event is the latest one that has achieved, or equals the previous, top score (however that is calculated)?

**Comment by blakeblackshear** [comment]
In the current stable version, the scores won't necessarily match the snapshot. In the next release, the score will match the score shown in the snapshot. You could however still have a race condition where the snapshot is updated again before you pull it.

**Comment by sshaikh** [comment]
I figured, which is why I asked the second question - if the snapshot will always have a higher score anyway then I'm not too concerned.

Matching scores aside, is there a reason why the second snapshot might have a lower score (in the bounding box)? Or are we saying it's the bounding box that has the misleading score?

**Comment by sshaikh** [comment]
I regret my phrasing.

Mqtt aside, are we saying that replacement snapshots may be chosen even if the detection score is lower? Ie there's a different measure of "better"?

**Comment by NickM-27** [comment]
> Mqtt aside, are we saying that replacement snapshots may be chosen even if the detection score is lower? Ie there's a different measure of "better"?

There are multiple factors.

https://github.com/blakeblackshear/frigate/blob/39bf6c44bcae060b01937b58d1f856725dac7a59/frigate/object_processing.py#L540-L556

This second factor can be configured via the `best_image_timeout` config.

In Frigate 0.13 we are hoping to better refine the "best" image logic to use things like zones, the image with the most clear face / license_plate (requires Frigate+), etc.
