### ISSUE TITLE
Green video feed when using RTMP feeds from cameras

### ISSUE THREAD

**Issue by webbson** [blakeblackshear/frigate#656]
I have a couple of Reolink RLC-410-5MP and are getting a lot of smear/broken feeds and basically all saved clips are smeared as well.

This seems to be a problem with Reolink cameras and people with Zoneminder and BlueIris have had success with using RTMP mode instead.

https://forums.zoneminder.com/viewtopic.php?f=10&t=25874&start=15

However when I try to use these urls I only get a green feed in Frigate

**Comment by blakeblackshear** [comment]
https://blakeblackshear.github.io/frigate/troubleshooting/

Also, here are the recommended settings for the reolink cameras: https://blakeblackshear.github.io/frigate/configuration/cameras#reolink-410520-possibly-others

**Comment by walthowd** [comment]
See also here:

https://github.com/blakeblackshear/frigate/discussions/369#discussioncomment-216966

Make sure your encoding setting on the camera matches your Frigate config.
