### ISSUE TITLE
Frigate+

### ISSUE THREAD

**Issue by greghesp** [blakeblackshear/frigate#6571]
Short and sweet, just wondering if any timelines on when Frigate+ will be available

**Comment by NickM-27** [comment]
Creating an issue / feature request isn't really an appropriate place to ask, a discussion or even asking on [the frigate+ discussion](https://github.com/blakeblackshear/frigate/discussions/1043) would be a better place. 

Blake can likely give a more concrete answer but I believe it has been said that frigate+ will be generally available alongside 0.13 release
