### ISSUE TITLE
0.80 HA-Addon: Failed to create tmpfs - HA protection mode needs to be enabled

### ISSUE THREAD

**Issue by Ysbrand** [blakeblackshear/frigate#658]
It happens occasionally during the start of frigate

```
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Creating tmpfs of size 256m
mount: /tmp/cache: cannot mount tmpfs read-only.
frigate.app                    ERROR   : Failed to create tmpfs, error code: 8192
```

/tmp/cache exists, but as part of the root filesystem

```
root@ccab4aaf-frigate:/opt/frigate# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         220G   53G  156G  26% /
tmpfs            64M     0   64M   0% /dev
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
shm              64M  1.2M   63M   2% /dev/shm
/dev/root       103M  103M     0 100% /usr/sbin/docker-init
/dev/sda8       220G   53G  156G  26% /data
tmpfs           1.9G     0  1.9G   0% /proc/asound
tmpfs           1.9G     0  1.9G   0% /sys/firmware
```

```
root@ccab4aaf-frigate:/# ls -ald /tmp/cache
drwxr-xr-x 2 root root 4096 Jan 29 10:57 /tmp/cache
```

Tried to submit the command manually (as a test), but that fails as well:

```
root@ccab4aaf-frigate:/opt/frigate# mount -t tmpfs -o size=32m tmpfs /tmp/cache2
mount: /tmp/cache2: cannot mount tmpfs read-only.
root@ccab4aaf-frigate:/opt/frigate# echo $?
32
```

EDIT:
Found it, protection mode needs to be enabled when running as a HA-addon
In other words, the protection mode is not only needed for the hardware acceleration but for the creation of tmpfs as well.
I guess a minor update to the documentation makes sense.

**Comment by heikkis** [comment]
@Ysbrand Hmm. which one is it. Im getting the error with newest Hassio and Frigate with protection mode disabled. The documentation linked says it should be disabled and you are saying multiple times that it need to be enabled (=privileged mode disabled)? Could you clarify this?

```
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Creating tmpfs of size 16384m
mount: /tmp/cache: cannot mount tmpfs read-only.
frigate.app                    ERROR   : Failed to create tmpfs, error code: 8192
Starting migrations
```

**Comment by Ysbrand** [comment]
Protection mode should be disabled:
Warning: Protection mode is disabled!

But it looks like the issue is back after some recent updates (I actually think its one of the HA updates that breaks it not sure).

**Comment by Ysbrand** [comment]
@blakeblackshear 
I think this error is related:
`WARNING (MainThread) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR`

**Comment by Eeeeeediot** [comment]
I am also recieving this error and now clips isn't workibg

**Comment by lawrence-jeff** [comment]
Just got this error today after upgrading from 1.10 to 1.11
Protection mode is disabled (in fact nothing changed other than the upgrade).

**Comment by michaelstein60** [comment]
Protection mode is disabled. I’m running a new install and getting the same issue described above. 

RPi 4b 4G RAM. Debian 10. HA Supervised. Frigate as add-on via HACS

**Comment by lawrence-jeff** [comment]
> Protection mode is disabled. I’m running a new install and getting the same issue described above.
> 
> RPi 4b 4G RAM. Debian 10. HA Supervised. Frigate as add-on via Custom repository

Upgrading to the latest version and removing any tempfs stuff in your config fixed it for me. Ha made it by default use a tempfs ram drive so using the config option confuses things
