### ISSUE TITLE
[Config Support]: Change Presence Time Until Clear

### ISSUE THREAD

**Issue by monsieurlatte** [blakeblackshear/frigate#6597]
### Describe the problem you are having

I can't seem to find how to change how long presence sensor is set in HA.  

I have frigate installed in HAOS and works great but I'm trying to use it to detect cats and keep them out of my garden and recently one learned that they can trigger it, wait until the sprinklers come on (15 seconds) and then go in and do their business before frigate detects them again.  

### Version

.12.

### Frigate config file

```yaml
Not needed assuming since just a question.
```

### Relevant log output

```shell
Not needed assuming since just a question.
```

### Frigate stats

```json
Not needed assuming since just a question.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Not needed assuming since just a question.

**Comment by NickM-27** [comment]
The sensor updates immediately based on what frigate sees. If you want to add debounce logic that should be done in the HA automation

**Comment by monsieurlatte** [comment]
Gotcha, thanks so much for this awesome product!
