### ISSUE TITLE
Serve up previous best_person images too.

### ISSUE THREAD

**Issue by scstraus** [blakeblackshear/frigate#66]
As discussed here: https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/559?u=scstraus

I’ve been thinking it would be nice to save the last 5 or 10 images. Couple times I’ve been in a meeting or didn’t see my phone and I’ll have a few notifications. Do you think this is something that could be added ? Or even worth the time? I was thinking of creating a small script that just moved the file and added a date time but I haven’t messed with it just yet.

I want that too! I’d like to have something like the [swiper card](https://community.home-assistant.io/t/lovelace-swiper-card/72447) in my UI with the last 5-10 images I can browse through to see what was seen. If we could have multiple cameras for “best_person” “best_person_-1”, “best_person_-2”, etc, that would make it possible to do… An option for how many previous images to serve would be good too.

**Comment by miikkajo** [comment]
how about doing this on hass side?
you could create automation for saving snapshot images to disk
i'm currently pushing images to telegram on detection so i have history there

but i'm liking this swiper card idea, it should not be too hard to do  :)

**Comment by scstraus** [comment]
I haven't upgraded to the new MQTT image push yet, and don't know how this would be done, to keep only a certain amount of images and expose to the UI but if you know how to do this, please share :-). I can imagine how to do it with multiple cameras, but I bet there are many ways to skin this cat.

**Comment by miikkajo** [comment]
for the fun of it i created simple automation :)

cams:
  - platform: mjpeg
    name: cam1
    mjpeg_url: http://192.168.0.2:5000/cam1
  - platform: local_file
    name: cam1_history1
    file_path: /tmp/image1.jpg    
  - platform: local_file
    name: cam1_history2
    file_path: /tmp/image2.jpg    
  - platform: local_file
    name: cam1_history3
    file_path: /tmp/image3.jpg    
  - platform: local_file
    name: cam1_history4
    file_path: /tmp/image4.jpg    
  - platform: local_file
    name: cam1_history5
    file_path: /tmp/image5.jpg

automation:

  alias: create_history 
  trigger:
  - entity_id: binary_sensor.cam1_person
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: camera.cam1_history2
      filename: /tmp/image1.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history3
      filename: /tmp/image2.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history4 
      filename: /tmp/image3.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history5
      filename: /tmp/image4.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1         
      filename: /tmp/image5.jpg
    service: camera.snapshot


This is just quick hack, mut dont see why it would not work
cameras are pointin to local images, and automation is rotating then when person is detected

I believe you can just run swiper from those camera entities?
i havent got any time to test it yet.

**Comment by miikkajo** [comment]
i created repo for this example
for simplicity it's package file
https://github.com/miikkajo/frigate-history

**Comment by scstraus** [comment]
Nicely done! Time for me to upgrade!

**Comment by miikkajo** [comment]
just moved images out of /tmp/ to /config/www , /tmp/ is stupid place to keep them, as you lose them :)
i'm actually not using mqtt images for this, but surely one can do it

**Comment by scstraus** [comment]
Does anyone know how this would work with MQTT? I'm thinking to try jumping to the new version as it looks like my sensors are triggering at very low thresholds for some reason, I'm hoping MQTT solves this, but would also like to know how to do this "look back" with MQTT images.. I don't have any idea how MQTT handles images..

**Comment by miikkajo** [comment]
i'll update example to use MQTT images

**Comment by miikkajo** [comment]
Added, tested, fixed... should be working now ;)

**Comment by scstraus** [comment]
Wow you're on top of things!! Thanks!

**Comment by miikkajo** [comment]
ok, i took another take on this.
moved fifo logic from automation to bash script, added check for duplicates and size of history
no need to scripts and automation is simpler now

config is now for 2 cameras and history_size is 10 frames.

what is bugging me is using local_image camera entities,
i tried to use directly lovelace picture entity, but as /local is cached 
i did not manage to get updated images...

**Comment by miikkajo** [comment]
i was thinking of custom_component but this last version is working so fine that  
i'm going to just use it for now :)
10 frames of history is great, seems to be enough for quick view of past detections.

**Comment by scstraus** [comment]
Hi @miikkajo, I finally got up on the MQTT version and was thinking to try this. In the repo, you reference the file frigate_history_mqtt.yaml, but I can't find it in the repo. Is frigate_history.yaml working with the MQTT version?

**Comment by scstraus** [comment]
Finally got it working.. Strange though, it seems to randomly reverse the order of the cards so that sometimes it starts with the tenth from the last instead of last.. Did you ever have that issue?

**Comment by miikkajo** [comment]
sorry, i'm been pretty busy latelty... 
i actually moved to using addon myself, 
i try to document it as soon as i got time for it.

here is project for it 
https://github.com/miikkajo/ha-addon_frigate-history

you can add my addon repository to hassio,  https://github.com/miikkajo/hassio_addons

of course if you are not using hassio, it does not help much...
as for order of cards, i remember i have seen something like that,
not sure what is causing it...

**Comment by niemyjski** [comment]
@miikkajo your fork is now out of date, I got write access to the parent and merged in a ton of changes.

**Comment by JonGilmore** [comment]
@miikkajo is your addon still working for the 0.8.0 release?

**Comment by miikkajo** [comment]
well, it should, it only listens for mqtt snapshot message and dumps snapshot images to disk.
personally i'm using clips and events from 0.8.x release, and i'm pretty pleased with it
