### ISSUE TITLE
[Support]: nethogs CPU usage

### ISSUE THREAD

**Issue by roger-** [blakeblackshear/frigate#6613]
### Describe the problem you are having

I'm seeing nethogs use 20-40% CPU every few seconds (according to htop).

Would be nice to have an option to disable it for people who don't care too much about monitoring bandwidth.

### Version

0.13.0-53d63e0

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by skrashevich** [comment]
please, execute this commands in frigate docker container:
```
apt update
apt install -y net-tools
ifconfig -a
```
and show it's output
