### ISSUE TITLE
"Unable to create clip" when post_capture > 5 x 5 seconds wait from v0.8.0-rc4

### ISSUE THREAD

**Issue by card78** [blakeblackshear/frigate#662]
Thank you for the fantastic work.

I have clips enabled with post_capture of 30. Seems like the change  [d32fed2](https://github.com/blakeblackshear/frigate/commit/d32fed2c018b46246feedbb5894df1f09952383c) causes create_clip to error out after waiting for 5 times of 5 seconds each regardless of the post_capture setting.

**Comment by blakeblackshear** [comment]
Yea. That would be a bug. For now, the post capture cannot be larger than 25 seconds I guess. I would probably limit to 20.

**Comment by card78** [comment]
Will do. Cheers.
