### ISSUE TITLE
[Support]: External events "end" API-endpoint triggers DB exception

### ISSUE THREAD

**Issue by FilipVaverka** [blakeblackshear/frigate#6622]
### Describe the problem you are having

Using HTTP manual event API to create event of indefinite length ("duration": None) and attempting to "end" said event using (```/api/events/<EVENT-ID>/end```) leads to "Failed to update manual event" exception (the event is not finalized).

Closer examination of https://github.com/blakeblackshear/frigate/blob/1e17dbaa91d1987bbfb8bf28e7fade90b7e6b68e/frigate/events/maintainer.py#L199 suggests that partially filled event in https://github.com/blakeblackshear/frigate/blob/1e17dbaa91d1987bbfb8bf28e7fade90b7e6b68e/frigate/events/maintainer.py#L214 part of the event type branch leads to Database exception as resulting "on_conflict" update does not fulfill DB constraints (event is incomplete).

This can be apparently fixed by using standard "Event.update" instead to set the "end_time" of the event in DB.

### Version

0.13.0-1e17dba

### Frigate config file

```yaml
N/R
```

### Relevant log output

```shell
2023-05-26 10:06:16.821342582  [2023-05-26 10:06:16] frigate.events.maintainer      WARNING : Failed to update manual event: 1685088366.767846-026rav
```

### FFprobe output from your camera

```shell
N/R
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/R

**Comment by FilipVaverka** [comment]
Just noticed that manual events also don't implement pre/post_capture time offsets.

**Comment by NickM-27** [comment]
You are going to need to provide your http calls to show what happened. If you use the api correctly, the event already has all the fields filled in from when the event was created and this succeeds without issue. 

> Just noticed that manual events also don't implement pre/post_capture time offsets.

Why would they be? As a user you can specify exactly when the start and stop happen already. Also, if a user doesn't have 24/7 recordings enabled then there's a low likelihood that the pre capture would have any segments to save anyway.

**Comment by FilipVaverka** [comment]
Here is simple code to assemble the API call:
```
import time
import json
import requests

base_url = "http://127.0.0.1:5000/api/events"

create_event_resp = requests.post(base_url + "/test_camera/test_label/create", json={
    "duration": None})
event = json.loads(create_event_resp.text)
print(create_event_resp.text)

time.sleep(10)

end_event_resp = requests.put((base_url + "/{}/end").format(event[0]['event_id']), json={})
print(end_event_resp.text)
````
with output:
```
[{"event_id":"1685096963.305556-aii4uf","message":"Successfully created event.","success":true},200]

[{"message":"Event successfully ended.","success":true},200]
```

Event is successfully created, but "end" call outputs error log provided in the original issue (and event stays "In Progress" indefinitely). The ```Event.insert(event).on_conflict(..., update=event)``` fails for "end" call (apparently because only `id` and `end_time` fields are provided).

As for the pre/post_time, the API doesn't seem to allow for explicit specification of start time so there is no way to record before the event actually occurs. The end time could be indeed handled by the client.

**Comment by NickM-27** [comment]
Interesting, I'll retest and see but the issue isn't due to fields being provided because the insert will conflict and call update anyway. 

And the start time is set by when you call the api. If a user doesn't have 24/7 recordings enabled for that camera then setting the start time to before the call would mean those recordings likely aren't included anyway. It's a difficult behavior to define so I decided to not include that in my PR, maybe we'll be able to figure out better behavior as the feature matures.

**Comment by FilipVaverka** [comment]
I see, how is this "start time" problem resolved for other detection types (such as in `handle_object_detection`)?
I assume that even with 24/7 recording enabled there will be problem with retention as recording segments before/after the event would get deleted.
My use case is to generate event on lets say push of a button (think "Emergency STOP"), where I need to store some time before that happens and after. With 24/7 I would still want this time-span around the event to stay stored much longer.

**Comment by NickM-27** [comment]
> I see, how is this "start time" problem resolved for other detection types (such as in handle_object_detection)?

Depending on the value of pre_capture it could still be an issue, however the event is inserted into the DB as soon as the event starts with the pre / post capture so there is more chance that the previous recording segment is still in the cache.

**Comment by FilipVaverka** [comment]
So its mostly problem in cases without 24/7 recording.
With 24/7 recording, is it enough to have event with appropriate start_time/end_time pair in DB to ensure that segments are retained according to specified event retention settings?

**Comment by NickM-27** [comment]
yes that is correct
