### ISSUE TITLE
[HW Accel Support]: Rotating Stream With Hwaccel

### ISSUE THREAD

**Issue by rea-ducks** [blakeblackshear/frigate#6634]
### Describe the problem you are having

Frigate is running smoothly when hardware acceleration is off. As soon as I enable it (`hwaccel_args: preset-vaapi`), ffmpeg crashes. Somehow it collides with my output_args `-f rawvideo -vf `transpose=cclock`, because if I strip it down to `-f rawvideo` hwaccel works – but my video has the wrong orientation.
I don't understand what the error message wants to tell me.

How can I get hwaccel together with rotation?

### Version

0.12.0

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
go2rtc:
  streams:
    eyethree_restream:
      - rtsp://192.168.8.62:554/channel=1&stream=1&protocol=unicast&onvif=0.sdp
    eyethree_record:
      - rtsp://192.168.8.62:554/channel=1&stream=0&protocol=unicast&onvif=0.sdp
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: preset-vaapi
cameras:
  eyethree:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/eyethree_restream
          roles:
            - detect
          input_args: preset-rtsp-restream
        - path: rtsp://127.0.0.1:8554/eyethree_record
          roles:
            - record
          input_args: preset-rtsp-restream
      output_args:
        detect: -f rawvideo -vf transpose=cclock
#        detect: -f rawvideo
    detect:
      enabled: True
      width: 448
      height: 800
      stationary:
        max_frames:
          objects:
            person: 100
database:
  path: /db/frigate.db
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate9
    privileged: true
    restart: unless-stopped
    image: "ghcr.io/blakeblackshear/frigate:0.12.0"
    cap_add:
      - CAP_PERFMON
    shm_size: '128mb'
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config/config.yml:/config/config.yml
      - /mnt/smb/cctv:/media/frigate
      - /root/frigate/db:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
```

### Relevant log output

```shell
[2023-05-28 01:09:31] watchdog.eyethree              ERROR   : Ffmpeg process crashed unexpectedly for eyethree.
[2023-05-28 01:09:31] watchdog.eyethree              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2023-05-28 01:09:31] ffmpeg.eyethree.detect         ERROR   : Multiple -filter, -af or -vf options specified for stream 0, only the last option '-filter:v transpose=cclock' will be used.
[2023-05-28 01:09:31] ffmpeg.eyethree.detect         ERROR   : Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
[2023-05-28 01:09:31] ffmpeg.eyethree.detect         ERROR   : Error reinitializing filters!
[2023-05-28 01:09:31] ffmpeg.eyethree.detect         ERROR   : Failed to inject frame into filter network: Function not implemented
[2023-05-28 01:09:31] ffmpeg.eyethree.detect         ERROR   : Error while processing the decoded data for stream #0:0
[2023-05-28 01:09:31] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
[2023-05-28 01:09:31] frigate.record                 ERROR   : list index out of range
[2023-05-28 01:09:35] frigate.video                  ERROR   : eyethree: Unable to read frames from ffmpeg process.
[2023-05-28 01:09:35] frigate.video                  ERROR   : eyethree: ffmpeg process is not running. exiting capture thread...
[2023-05-28 01:09:36] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
[2023-05-28 01:09:36] frigate.record                 ERROR   : list index out of range
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"5/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":448,"width":800}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"12/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1296,"width":2304}]}}]
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Some China thingi from Aliexpress

### Any other information that may be helpful

Hardware is an Intel NUC with Skylake CPU.

VAINFO:
`{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEI"}`

**Comment by NickM-27** [comment]
You're not going to be able to use the ffmpeg preset with your own video filters, you'll need to just use raw ffmpeg args for hwaccel

**Comment by rea-ducks** [comment]
Oh, indeed, with
` hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p`
it works indeed.
Somehow it seems to not like the `-hwaccel_output_format vaapi` in the profile. Though I must say that I don't grasp what all that means.

Nevertheless thank you very much for pointing me in the right direction.

**Comment by NickM-27** [comment]
Yeah, different args would need to be used for that but since frigate sets -vf you can't set it as well
