### ISSUE TITLE
Events / web page enhancements

### ISSUE THREAD

**Issue by srirams** [blakeblackshear/frigate#665]
Fantastic work on the new version!

An enhancement to the web interface that I think would be useful is a denser thumbnail view of the saved clips with the best image as the thumbnail, and on mouse hover, the video clip will play (ideally starting from the pre_capture time). Kinda like how youtube does it...

I believe this will make reviewing the clips faster and more efficient...

In addition a way to delete clips once reviewed would be nice.

**Comment by bratanon** [comment]
+1 for delete clips and also snapshots.

**Comment by UltraSub** [comment]
+1 for being able to delete from web interface. Not asking for library management, just a delete option would be very welcome.

**Comment by mannp** [comment]
This would be great, especially for new comers, as I have a good few clips I'd like to delete after testing but am not sure how ...
