### ISSUE TITLE
Coral Dev Board

### ISSUE THREAD

**Issue by alexsahka** [blakeblackshear/frigate#666]
Is it possible to run Frigate on the Coral Dev Board? Not the Pi + USB stick?

https://coral.ai/products/dev-board/

**Comment by cybertza** [comment]
Don't be lazy search old topics. :/
https://github.com/blakeblackshear/frigate/issues/428
#428

**Comment by alexsahka** [comment]
There is not a single word about Coral Dev Board and all of these topics about Pi 3, Pi 4 or computer + Coral USB stick, not the Coral Dev Board.

I still have a question is it possible to run Frigate on the Coral Dev Board? 
![image](https://user-images.githubusercontent.com/7469537/106364195-1470cd80-62e2-11eb-9bf4-dcabbb8a2f1a.png)

**Comment by jakowenko** [comment]
I have a dev board mini and a coral usb accelerator. I had to run frigate as a docker container on my mini directly. Just got an accelerator today, going to see what the difference makes. Guessing my NUC + accelerator will perform better with the ffmpeg requirements.

**Comment by alexsahka** [comment]
Thank you,
So I have to install docker on the Coral Dev board and run it directly.
How about this docker env:

detectors:
  coral:
    type: edgetpu
    device: 'usb:0'

What is needs to be changed here instead of:   device: 'usb:0'  ?

**Comment by jakowenko** [comment]
At least that was the only way I could figure out how to do it. I see the docs include a way for pci, but I wasn't able to figure out how to run the dev board with the usb device type. The ffmpeg wasn't great though on it. I believe I just had this for the config and didn't specify USB, when I checked the logs when it started, it said it would the TPU. Let me know if you run into issues and I can ssh into my dev board and confirm what I used.

`detectors:
  coral:
    type: edgetpu`

**Comment by alexsahka** [comment]
David,
Do you have problems with installing and running Docker on the Coral dev board mini?
I installed multiple dockers in the last 2-3 years on different hosts without any problems but seems like Coral board has problems with Mendel Linux. 
Any tips on how to install docker on the Coral board?

This not working for some reasons:
https://github.com/f0cal/google-coral/issues/32
![image](https://user-images.githubusercontent.com/7469537/106372315-4a827180-6323-11eb-86be-3fcde86e78d9.png)

**Comment by jakowenko** [comment]
@alexsahka Docker on the dev mini won't work out of the box. I followed [these steps](https://stackoverflow.com/a/65710753/645627) by rebuilding the kernel.

I then had to add the file `/etc/docker/daemon.json` with the content below. After this a reboot and I was up and running with Docker.

```
{
  "storage-driver": "overlay2"
}
```

**Comment by alexsahka** [comment]
Thank you!
Have you used an internal 8 GB eMMC or SD card?
For some reason, I'm getting not enough space while rebuilding the kernel.

**Comment by jakowenko** [comment]
I was just using the internal storage. Were you able to build the `linux-image-4.19.125-mtk_4-2_arm64.deb` image? I was able to flash it by just using the `mdt install` command with the path to the .deb image I built.

**Comment by alexsahka** [comment]
I'm getting not enough space, I think I need to start fresh today after work.
Do you have link to linux-image-4.19.125-mtk_4-2_arm64.deb?
I was using different .deb file I wasn't able to find the exact image file.
Are any good images here? https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19/

**Comment by alexsahka** [comment]
So how is the coral USB accelerator different from the Dev board? Any better performance with the USB accelerator?

**Comment by jakowenko** [comment]
I had to follow these steps to build the new image - https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md. I don't believe you can just download an existing one. You need to build it with the new kernel options to support docker.

**Comment by alexsahka** [comment]
Thank you, I need to start fresh later today.

**Comment by WGrobler** [comment]
Hi @jakowenko & @alexsahka, do you have a working rebuilded image available for download anywhere? I am struggling to rebuild the image, would be nice to use your compiled image if available

**Comment by antonbek89** [comment]
@alexsahka Hi
So what your experience so far?
I'm considering to buy the dev board but not sure if I should.
What the difference between USB and the Dev Board?

**Comment by alexsahka** [comment]
Sold the Dev Board, and bought used Lenovo ThinkCentre M73 Tiny Mini Desktop Computer i3-4130T 4G Ram SSD + Coral Mini PCIe + docker, paid $105 for everything. Happy now, works great!
![image](https://user-images.githubusercontent.com/7469537/151654370-45ceabb9-1663-4c9b-b7f8-9e571a3b8af6.png)

**Comment by techbits00** [comment]
> Sold the Dev Board, and bought used Lenovo ThinkCentre M73 Tiny Mini Desktop Computer i3-4130T 4G Ram SSD + Coral Mini PCIe + docker, paid $105 for everything. Happy now, works great! ![image](https://user-images.githubusercontent.com/7469537/151654370-45ceabb9-1663-4c9b-b7f8-9e571a3b8af6.png)

Any tips on where to buy Coral PCIe? It seems be to out of stock pretty much everywhere with the closest delivery times in Nov 22

**Comment by alexsahka** [comment]
> > Sold the Dev Board, and bought used Lenovo ThinkCentre M73 Tiny Mini Desktop Computer i3-4130T 4G Ram SSD + Coral Mini PCIe + docker, paid $105 for everything. Happy now, works great! ![image](https://user-images.githubusercontent.com/7469537/151654370-45ceabb9-1663-4c9b-b7f8-9e571a3b8af6.png)
> 
> Any tips on where to buy Coral PCIe? It seems be to out of stock pretty much everywhere with the closest delivery times in Nov 22

Sorry I don't know, bought my Coral PCIe back in Jan 2021
