### ISSUE TITLE
[Detector Support]: Frigate's stable-tensorrt image doesn't support higher version of Tensorrt / rtx 4000 series

### ISSUE THREAD

**Issue by doctorttt** [blakeblackshear/frigate#6666]
### Describe the problem you are having

I have a 4060ti and couldn't get tensorrt with yolo models to work in frigate's stable-tensorrt image. I scratched my head the whole evening and narrowed down the issue. The Stable-tensorrt image requires 22.07-py3 to compile the trt models; however, 22.07-py3 doesn't support my 4060ti (which makes me to believe that rtx 4000 series won't work). The error message is as follows:

```
WARNING: Detected NVIDIA NVIDIA Graphics Device GPU, which is not yet supported in this version of the container
ERROR: No supported GPU(s) detected to run this container
```

- I then tried to use 22.08-py3 and ended up with the same error message.
- tried 22.09-py3. I was able to compile the trt models with this version using my 4060ti but frigate couldn't start with error message saying that ```magic tag does not match```
- Obviously, the other higher versions won't work on my 4060ti

Can the frigate team consider supporting a high version of tensorrt + rtx 4000 series? 

### Version

0.12.0-DA3E197 Stable-tensorrt

### Frigate config file

```yaml
N/A
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
22.07-py3 and 22.08-py3
WARNING: Detected NVIDIA NVIDIA Graphics Device GPU, which is not yet supported in this version of the container
ERROR: No supported GPU(s) detected to run this container


22.09-py3
frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
2023-05-31 21:21:44.021000447  [2023-05-31 21:21:44] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

**Comment by NateMeyer** [comment]
Yea, we need to match the library versions between generation and what's included in Frigate (i.e. `magic tag` must match).  The newer TensorRT libraries start dropping support for Kepler and Maxwell era GPUs, so we'll have to figure out which library version that makes sense going forward.  I'm surprised that the newer GPUs aren't able to run with the older library.

**Comment by doctorttt** [comment]
@NateMeyer Thanks for the comment. I'm happy to provide more information or be a beta tester if needed. I really would like to use my rtx4060ti for detection using Yolo's. Happy to make donation to support the Frigate project :) 

- 22.07-py3 is the current Tensorrt library in the docker image and that was released in July 2022. 
- The next version is 22.08-py3 released in August 2022 and I couldn't compile any models. 
- After that, it's 22.09-py3 released in October 2022 and I was able to compile the models. Perhaps this version may continue to work with the older Kepler and Maxwell architectures? I'm not sure. 

There are many other versions between late 2022 and May 2023. The latest is 23.05-py3 and that didn't work on my 4060ti.

**Comment by NateMeyer** [comment]
@doctorttt, I built and pushed a test image with the latest 8.6.1 tensorrt library.  I didn't see a NGC image that matches the _exact_ library versions, but I found I could add a couple things to allow the conversion from the frigate image.  My branch also has a modified script to do the model conversions.  This also means that we can look at integrating the model conversion into the regular startup process if we want.

image: `ghcr.io/natemeyer/frigate:0.13-7155cc4-tensorrt`

To download/convert yolo model:
```bash
docker run --gpus=all --rm -it -v `pwd`/trt-models:/trt-models --entrypoint /bin/bash ghcr.io/natemeyer/frigate:0.13-7155cc4-tensorrt /tensorrt_models.sh
```

Give this a try and let me know if you run into any issues.  Thanks

**Comment by doctorttt** [comment]
@NateMeyer It's working! I was able to generate three yolo tiny models as per your '''/tensorrt_models.sh''' using my 4060ti and launch frigate successfully. I'm on the latest Nvidia driver - v535.54.03. 

Here is the relevant section of my config.yml file.  I also pasted a couple screenshot below as I thought it might be helpful? I have a total of five cameras and four of them have detection on via tensorrt with yolo7-tiny-416.  Inference Speed is just 1.67ms!  Thank you for your time, and I'm happy to do more testing for you. 

I wonder how my card will perform if using larger model, such as yolov7x or yolov8x. 

```
detectors:
  tensorrt:
    type: tensorrt
    device: 0 

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

ffmpeg:
  global_args: -hide_banner
  hwaccel_args: preset-nvidia-h264 #preset-vaapi
  input_args: preset-rtsp-restream
  output_args: 
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    detect: -f rawvideo -pix_fmt yuv420p -an
```

![image](https://github.com/blakeblackshear/frigate/assets/132242705/390fcb3b-e1cc-4fad-839a-3eb8a1e4270c)

![image](https://github.com/blakeblackshear/frigate/assets/132242705/fae897ce-2dec-4e28-97f4-4460d208ce7f)

**Comment by doctorttt** [comment]
Hi Nate. Thank you for the work. I tested #7006 and it works well. No issue throughout the installation process. 

Are the other yolo7 models available for testing: ```yolov7x-320, yolov7x-640, yolov7-640, yolov7-320```. Also, are yolo8 models available as well? Thanks

**Comment by NateMeyer** [comment]
The TensorRT library in 0.12 is version 8.4.1 which supports up to compute 8.7.  The new RTX 4000 cards (Ada Lovelace) are compute 8.9.  I'm looking at updating to 8.5.3 which should be a sweet-spot for compatibility.
