### ISSUE TITLE
Report to MQTT when one of the cameras is not recording

### ISSUE THREAD

**Issue by Heisenberg2980** [blakeblackshear/frigate#6670]
**Describe what you are trying to accomplish and why in non technical terms**
I am having an issue in the last weeks where Frigate is failing with multiple different errors in the log and it is not able to recover the recording for some of the cameras and I need to restart Frigate to fix it. I am still try to figure out why this happens, but I would like Frigate to report to MQTT when this happens so I can create an automation (i.e. notification or even restart the Frigate container automatically) as at the moment the only way to know this has happened is by looking at the logs.

**Describe the solution you'd like**
I would like Frigate to report to MQTT the status of the recording, so when there is an error that causes a camera to stop recording Home Assistant is aware of that.

**Describe alternatives you've considered**
The only alternative I have considered is restarting Frigate every hour or so, but it is not a good solution as Frigate could be running fine for hours without needing a restart.

**Additional context**

**Comment by NickM-27** [comment]
This is already supported with the camera_fps value in MQTT

**Comment by Heisenberg2980** [comment]
Thanks for suck a quick response. That will help in same cases, but camera_fps value seems to be reporting the normal value (5fps) when the log says "WARNING : Discarding a corrupt recording segment" indefinitely and no video is recorded

**Comment by NickM-27** [comment]
RIght, there is currently no error reporting in mqtt, but that is different than "camera not recording". That is your camera recording but sending bad data so the recordings are not usable

**Comment by Heisenberg2980** [comment]
Got it, I will mark this issue as solved because the camera_fps should be enough to know if there is something wrong with Frigate in most cases.

Regarding the cameras sending bad data, the cameras are pretty good (Dahua IPC-HDW5442TM-AS-LED as recommended in the documentation) and this was not happening in v0.11, so I think the issue must be in the setup (maybe related to the movement to go2rtc?), where could I start to find the source of the problem?

**Comment by Heisenberg2980** [comment]
> First thing might be trying to update the internal go2rtc

I don´t want to claim victory too early, but after updating go2rtc to v1.5.0, Frigate has been running without any issue for over 12h (before it usually failed every 4-6h), so it looks promissing
