### ISSUE TITLE
enable/diable all zones/cameras button

### ISSUE THREAD

**Issue by sshort1955** [blakeblackshear/frigate#6688]
When I look at the event view page of the web GUI, then filter for a camera or zone, I have to uncheck all other cameras/zones manually to see only the views I am looking for.

It would be nice to be able to uncheck all views with a single button (as we can now check all boxes), then only check the one view (camera/zone). This would save many clicks each time I need to filter the event views

An alternative would be to have a filter text box (RegEx?) for those of us that name cameras and zones logically for sorting/scripting reasons.

Not critical, but maybe a carpal tunnel avoidance effort???

Thanks!! This product (x64 Docker-Compose, dedicated box) is awesome, I'm heading over to make a donation now!!!

**Comment by NickM-27** [comment]
This is already supported in 0.12, just press the camera icon to the right of the name

**Comment by sshort1955** [comment]
Yikes, how true!!
I just thought it was an identifier icon. Unclear, but as you say, supported!!

Thanks for the rapid response!

**Comment by NickM-27** [comment]
If you have an idea for an icon that would better communicate it's usage that would be helpful, I'm sure others didn't know that either

**Comment by sshort1955** [comment]
Looking for donation link on main page, but don’t see it. Can you guide me?

From: Nicolas Mowen ***@***.***>
Date: Friday, June 2, 2023 at 06:52:17
To: blakeblackshear/frigate ***@***.***>
Cc: Montana Flyer ***@***.***>, Author ***@***.***>
Subject: Re: [blakeblackshear/frigate] enable/diable all zones/cameras button (Issue #6688)

This is already supported in 0.12, just press the camera icon to the right of the name

**Comment by sshort1955** [comment]
After a bit of thought, it seems to me that I could have been under the assumption that no "hide all" capability was there simply because of the inclusion of the "show all" button. Maybe a better approach would be to remove the camera icons altogether and keep the check boxes for individual cameras, then add a "hide all" button?  Events/zones/labels should be in the show all state to begin with as they currently are.

A more standard approach would simply be a checkbox header that checks/unchecks all items. You could then remove the camera icons and the "show all" buttons altogether.

**Comment by sshort1955** [comment]
I as well think it is a great feature, but not an obvious or standard feature as far as human interface conventions go. This was the root cause of this feature request. The first thing I looked for with .12 was the checkbox header to check/uncheck all, as GUI conventions have created for list interfaces. You yourself said "I'm sure others didn't know that either". 

In the end this is no longer an inconvenience issue for me since I now know what the camera icons are for, so whatever your team decides works for me.  But please think of others in the same situation before making final decision.

Once again, FANTASTIC application.
