### ISSUE TITLE
Changing recording to other than default media folder on Home Assistant addon

### ISSUE THREAD

**Issue by samuelolteanu** [blakeblackshear/frigate#6693]
With the upcoming release of Home Assistant 2023.6, we can now add a samba folder to ha media. It's not however (easily) possible to change the default recording path of frigate addon to the samba media folder, something like this:

![Captură de ecran 2023-06-04 033322](https://github.com/blakeblackshear/frigate/assets/85267083/c663719a-998f-43eb-a056-1995066dfbc6)

**Comment by NickM-27** [comment]
The media folders are added by name, I think it could make sense as a user to just add a share with the name `frigate` so it is used automatically

**Comment by dm7500** [comment]
> The media folders are added by name, I think it could make sense as a user to just add a share with the name `frigate` so it is used automatically

Just tried this using the below method in 2023.6:

1. Uninstall Frigate add-on
2. Delete all content found in `frigate` directory
3. Re-create new `frigate` storage connection
4. Reinstall Frigate add-on

Received errors about being unable to create `recordings` and `clips` sub-directories in `frigate` share. Even when I created them on my NAS manually, it gives me the below error in the Frigate log when starting up.

```
2023-06-08 04:46:56.210755053  [2023-06-08 00:46:56] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-06-08 04:46:56.251065496  [2023-06-08 00:46:56] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-06-08 04:46:56.254638897  [2023-06-08 00:46:56] peewee_migrate                 INFO    : Starting migrations
2023-06-08 04:46:56.255799739  unable to open database file
2023-06-08 04:46:57.467651600  [INFO] Service Frigate exited with code 1 (by signal 0)
```

Seems there either needs to be some guidance on how to set this up with the new Storage system in HASSOS, or an option as suggested here, to change the default recording path Frigate will use.

**Comment by NickM-27** [comment]
It sounds like it doesn't have write access is the problem, otherwise we'd expect it to just ignore the NAS and keep writing to local storage

**Comment by dm7500** [comment]
That was my thought too. I was able to get it to work with the new NAS storage, but only by changing the `frigate.db` location to be on the local HA drive, using the below config

```
database:
  path: /config/frigate.db
```

**Comment by NickM-27** [comment]
That is going to be required in the next version of frigate anyway due to performance issues using the db on remote storage

**Comment by muzzak123** [comment]
@dm7500 I was able to get his to work by using your tips above, thx. 
However rather than lose all my current frigate clips and recordings I did this.
1. Stopped Frigate addon
2. Created a temporary Network Storage link to my NAS share like so
![NAS Configt](https://github.com/blakeblackshear/frigate/assets/51472089/1b789b10-a083-4cb2-ac38-e7ea226f03e0)
3. Moved the existing files in HA from /media/frigate to /media/frigate_temp (aka my NAS share)
4. Moved the database location as you suggested and added entry to config
5. As there doesnt seem to currently be a way to rename Network Storage in HA, I then deleted the Network Storage link to frigate_temp, and recreated it exactly the same but this time named it frigate. Hence the HA folder /media/frigate now points to the NAS folder.
6. Start Frigate

So far it seems to be working well.

**Comment by muzzak123** [comment]
Just an update. Seems my method above isn't permanent and doesnt survive a reboot. I'm investigating why.

**Comment by muzzak123** [comment]
And now it seems my method is official :-) 
https://docs.frigate.video/guides/ha_network_storage/#setting-up-remote-storage-for-frigate
I run my HA in a VM on the same box as my NAS. Seems I can reboot the HA VM no problem, so if you run HA on something separate to your NAS this method will work fine. 
The issue I'm having is that after a full NAS reboot, it seems like HA is trying to mount the storage before it is available on the NAS

**Comment by erwindouna** [comment]
> And now it seems my method is official :-) https://docs.frigate.video/guides/ha_network_storage/#setting-up-remote-storage-for-frigate I run my HA in a VM on the same box as my NAS. Seems I can reboot the HA VM no problem, so if you run HA on something separate to your NAS this method will work fine. The issue I'm having is that after a full NAS reboot, it seems like HA is trying to mount the storage before it is available on the NAS

Would you be able to paste some screenshots and further instructions of your workable solution? I am running exactly the same situation HA in a VM on my NAS (I am also using Samba). It seems I am able to create a Network Storage and I have the db config entry included exactly as mentioned as in the documentation.
My odd situation is that Frigate still seems to be storing the recordings locally in the VM (bad for back-ups) and nothing is being sent to the shared folder. Maybe if you're willing to explain what and how you configured your shared folder on the NAS and what steps next to get it up and running?

**Comment by muzzak123** [comment]
@erwindouna Did you make sure you stopped the Frigate addon before you start ?  The behaviour you are describing is typical when Frigate still has hold of the /media/frigate folder.
Another thing you can do to test the NAS side of things, is to copy a file from Windows to your NAS SMB folder you have chosen for Frigate to store it's data. You should be able to see this file through the HA GUI by selecting Media - My Media - frigate

**Comment by erwindouna** [comment]
> @erwindouna Did you make sure you stopped the Frigate addon before you start ? The behaviour you are describing is typical when Frigate still has hold of the /media/frigate folder. Another thing you can do to test the NAS side of things, is to copy a file from Windows to your NAS SMB folder you have chosen for Frigate to store it's data. You should be able to see this file through the HA GUI by selecting Media - My Media - frigate

I tried your approach on testing to upload a file from Windows to the NAS SMB folder and try to see it in Media - Frigate. I didn't see the uploaded file showing up in HA. Best guess is that I configured something wrong on the NAS. When trying to update the configuration in HA, I am getting the error the mount is not empty. I'll have to look into this later (yet I have found a potential source for a solution: https://github.com/home-assistant/supervisor/issues/4358#issuecomment-1624160038).

**Comment by muzzak123** [comment]
Yeah - It may also be a permissions issue. Check to ensure the userid that runs the VM on the NAS has write access to the SMB folder

**Comment by xekil** [comment]
> Just an update. Seems my method above isn't permanent and doesnt survive a reboot. I'm investigating why.

Good morning,

I have exactly the same problem, I use Haos on a VM and the media folder on my NAS Synology (NFS), if I restart Home Assitant (following an update for example) then frigate no longer saves on the NAS Synology :(

Have you found a permanent solution?
THANKS

**Comment by muzzak123** [comment]
@xekil So far the only way I can get it to survive a full NAS reboot is to turn off the Start on Boot in the Frigate integration, and then when everything is up I start Frigate manually

**Comment by xekil** [comment]
Thanks for the reply, I suspected that.  It's no big deal, I'm going to switch to an LXC configuration.

**Comment by thewan056** [comment]
> @xekil So far the only way I can get it to survive a full NAS reboot is to turn off the Start on Boot in the Frigate integration, and then when everything is up I start Frigate manually

you can automate this by exposing the NAS snmp and getting HA to read specifically the value of the status of the volume that your frigate folder is located on. When the status of that volume becomes available, depends what your NAS SNMP reports, you can then start/restart Frigate or restart HA itself. My experience described below:

Note that my HA/Frigate setup is separate from my NAS. I use an automation to restart HA, leaving the Start on Boot enabled for Frigate, when the volume on my NAS that my Frigate is using reports itself to HA as "healthy" using SNMP. In my case restarting HA to mount the network share properly is more reliable than just starting/restarting frigate as sometimes HA doesn't remount the network share at all if HA starts before the network share is ready. With this setup I'm happy with my NAS rebooting anytime, including weekly reboots as my HA and Frigate will just fix itself.

Now if only Frigate can have a fall back storage so that it continues working in the event the NAS share disappears.

**Comment by NickM-27** [comment]
Closing this as from frigate's perspective using network shares for the addon is supported. Reconnection / other logic to the NAS is something that HA will need to clean up

**Comment by navarrolux** [comment]
> That was my thought too. I was able to get it to work with the new NAS storage, but only by changing the `frigate.db` location to be on the local HA drive, using the below config
> 
> ```
> database:
>   path: /config/frigate.db
> ```

So where does the frigate.db fine need to be? The instructions state to move it to the /config folder. but it was already there.
I have not been able to have frigate safe the recordings to my NAS.
any help would be greatly appreciated.

**Comment by NickM-27** [comment]
> So where does the frigate.db fine need to be? The instructions state to move it to the /config folder. but it was already there.

The only reason it would already be there is if you already had that in your config, in 0.12 the default location is /media/frigate/frigate.db

In 0.13 the default location will be `/config/frigate.db`

**Comment by navarrolux** [comment]
> > So where does the frigate.db fine need to be? The instructions state to move it to the /config folder. but it was already there.
> 
> The only reason it would already be there is if you already had that in your config, in 0.12 the default location is `/media/frigate/frigate.db`
> 
> In 0.13 the default location will be `/config/frigate.db`

Thank you. That helps explain that.
I tested it and, yes, the frigate.db was moved thanks to the config file.
Having said this, I am still not able to have frigate save to the NAS. any ideas as to where I can look next?
Thanks again

**Comment by NickM-27** [comment]
it can be due to any number of reasons, more info is needed

**Comment by navarrolux** [comment]
@NickM-27, thank you.
I finally figured it out. 
My issue was that I had named the network storage in HA "frigate" but chose a different name for the folder on my NAS.
Once I named both the network storage in HA and the folder in my NAS as "frigate" it started working.

**Comment by samuelolteanu** [comment]
I've tested Frigate recording on samba for some time now and It's mostly fine. The remote folder **needs** to be always on or the addon will start to record locally and not switch back. Right now i've setup a ha ping binary sensor that stops or starts the addon depending on the network state of the samba server. Not sure yet if it fixed anything.

**Comment by navarrolux** [comment]
After monitoring for an evening I'm noticing that frigate is writing the videos to both locations (local storage and NAS).
Is this the normal behavior?

**Comment by NickM-27** [comment]
> After monitoring for an evening I'm noticing that frigate is writing the videos to both locations (local storage and NAS).
Is this the normal behavior?

No, and this is not something that frigate has any control over. Frigate writes to one location inside the container `/media/frigate/`

if recordings are being written to both that is an HA / Supervisor issue (because that is what starts / stops / controls the frigate docker container)

**Comment by xAcrosonicx** [comment]
> After monitoring for an evening I'm noticing that frigate is writing the videos to both locations (local storage and NAS). Is this the normal behavior?

@navarrolux - did you ever solve this? Mine is currently writing both to my NAS and /media/frigate for both recording and clips

**Comment by NickM-27** [comment]
@xAcrosonicx that is not possible to be writing to both locations, most likely you are misunderstanding the UI (they don't make it clear). The /media is just a mount of the NAS share, if you delete a file on the NAS it will be deleted in /media as well

**Comment by xAcrosonicx** [comment]
@NickM-27 - thank you for clarifying! I was using terminal to find the large directories/files and noticed it showed my /media/frigate as the largest - hence my confusion!
