### ISSUE TITLE
[Support]: HA integration fails to set up.

### ISSUE THREAD

**Issue by ripvega** [blakeblackshear/frigate#6696]
### Describe the problem you are having

Frigate is working fine but the HA integration fails to set up.

Please can you point me in the right direction of a fix?

I'm also see this in the Frigate log for several cameras:

> ERROR   : [swscaler @ 0x561f31de6f80] [swscaler @ 0x561f31dfa080] deprecated pixel format used, make sure you did set range correctly

What does this mean?

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
Error setting up entry 10.0.1.64:5000 for frigate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/frigate/__init__.py", line 235, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua IPC-HFW5442E-ZE

**Comment by NickM-27** [comment]
You are using an old version of the integration and need to update.

**Comment by ripvega** [comment]
Thank you.
