### ISSUE TITLE
[Support]: Cannot connect to Frigate over HTTPS with HA Proxy Add-on

### ISSUE THREAD

**Issue by typytypytypy** [blakeblackshear/frigate#6748]
### Describe the problem you are having

I have a similar setup to what is described in this discussion: https://github.com/blakeblackshear/frigate/discussions/5838

I have frigate setup at https://frigate.mydomain.com, and I am trying to use the HA Proxy Add-On to connect to it, but it wants to use an http connection. 

I have tried: 
https://frigate.mydomain.com:443
frigate.mydomain.com:443
frigate.mydomain.com:80 with redirect to 443

None work

How can I connect to my Frigate domain over HTTPS using the HA Proxy Add-on? 

### Version

0.10.1-83481AF

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
na
```

### FFprobe output from your camera

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

na

**Comment by NickM-27** [comment]
Not related but wanted to point out that you seem to be running a quite old version of Frigate, just FYI

and I believe https is not supported for the frigate proxy addon. Regardless, https://github.com/blakeblackshear/frigate-hass-addons would be the place to request this feature not here 👍

**Comment by typytypytypy** [comment]
Thank you! I'll update Frigate and move this request to the other repo!
