### ISSUE TITLE
tmp/cache overflow and restart don't reset HA person and motion values

### ISSUE THREAD

**Issue by S-Przybylski** [blakeblackshear/frigate#679]
Update: Exchanged MQTT with Home Assistant - second point

Hi @blakeblackshear 
dear @paularmstrong 
First thanks for your wonderful work!
I use Frigate for some weeks now and have two problems:

1. If I turn on my six 8 MP cameras using the highest resolution with clips, then my /tmp/cache is sometimes overflowed. I counted my camera files: I got more then 40+ files per camera (all 10 seconds). My tmpfs is set to 2.5 GByte (I cannot assign more space on my RASPI 4GB). Is there a parameter in place which i have missed? If not, could the logic be adapted to check the remaining space too? I changed clips max_seconds from 300 to 200 - but this don't help at the end
2. If I restart Frigate while detecting something (sometimes some artefacts), then the counter for person and also the motion detection in Home Assistant are not cleared. If later a new detection was made, then these fields are corrected...

**Comment by blakeblackshear** [comment]
1. Thats in the works
2. This can be fixed

**Comment by blakeblackshear** [comment]
Still planning to fix 2

**Comment by S-Przybylski** [comment]
Dear @blakeblackshear 
shoud we reopen it?

**Comment by blakeblackshear** [comment]
Looking more closely at this, I don't think 2 should be fixed. Frigate already sends the values with retain=False. This could perhaps be fixed in the Home Assistant integration.
