### ISSUE TITLE
Disable Decoding of Detect Stream

### ISSUE THREAD

**Issue by lanerussell** [blakeblackshear/frigate#6793]
**Describe what you are trying to accomplish and why in non technical terms**
Ideally, users should be able to completely disable any decoding in Frigate to save CPU cycles on record-only NVRs. In my case, I'm using Frigate to simply constantly record several cameras with no other features. If possible it'd be nice if Frigate could show the streams directly from the cameras in birdseye without doing any decoding itself (relying on client browser to do this) with detect fully disabled.

Looking at this pinned [issue](https://github.com/blakeblackshear/frigate/issues/3860) and another similar [issue](https://github.com/blakeblackshear/frigate/issues/1322), it seems that all cameras must have the detect role, even if detect is disabled? Per @blakeblackshear:

> Many features of frigate require an input to be decoded. You can turn off detection in the config, but one input must be assigned the detect role.

It seems wasteful for Frigate to be decoding anything if not using features such as detect, especially during the 98% of the time no one is looking at the web UI (in my case).

**Describe the solution you'd like**
Setting:
```
detect:
    enabled: False
```
should ideally disable any ffmpeg processing of streams by Frigate to prevent unnecessary CPU usage, perhaps in conjunction with gortc to enable clients to view streams in the browser. Perhaps there could be separate role, something like `live_view` for viewing the cameras in the UI when detect is disabled? It sounds like the detect stream is used for more than just detection, perhaps breaking things out could be helpful here.

**Describe alternatives you've considered**
For now, I've been using the low-quality streams available on my cameras to minimize CPU usage. My detect config (width, height, and fps) matches the streams. This is a workable solution for me, but it would be nice to have an option for users with more cameras.

**Additional context**
<details>
<summary>Click here to see config</summary>
mqtt:
    enabled: False

birdseye:
    enabled: True
    width: 1920
    height: 1080
    quality: 1
    mode: continuous

record:
    enabled: True
    retain:
        days: 90
        mode: all

detect:
    enabled: False
    width: 640
    height: 360
    fps: 10

cameras:
    cam01:
        ffmpeg:
            inputs:
                - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@10.1.50.25:554/s0
                  roles:
                      - record
                - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@10.1.50.25:554/s1
                  roles:
                      - detect
            output_args:
                record: preset-record-generic-audio-copy
    cam02:
        ffmpeg:
            inputs:
                - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@10.1.50.26:554/s0
                  roles:
                      - record
                - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@10.1.50.26:554/s1
                  roles:
                      - detect
            output_args:
                record: preset-record-generic-audio-copy
    cam03:
        ffmpeg:
            inputs:
                - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@10.1.50.27:554/s0
                  roles:
                      - record
                - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@10.1.50.27:554/s1
                  roles:
                      - detect
            output_args:
                record: preset-record-generic-audio-copy
</details>

**Comment by blakeblackshear** [comment]
This is a duplicate of #1911

**Comment by pseud0sphere** [comment]
I know this is old, but I wanted to comment that I don't think this is a duplicate of https://github.com/blakeblackshear/frigate/issues/1911. Although similar, there is a distinction between completely disabling a camera (turning off decode, but also client re-streams and manual recording either from GUI or API call) and disabling decode, but still having the camera enabled for streaming to clients on the web interface and for manual triggering of recording.

I have my cameras setup to notify over SMTP using the onboard detection to a small SMTP server that I wrote that then triggers Frigate to record using the API. It would be nice to be able to disable decoding completely on these streams to save CPU usage. For now, the best I can do, even in 0.16.0-rc1 with `detect: enabled: false` is to set the detect FPS to 1. It seems that even with detect and motion disabled globally, the stream continues to be decoded.

**Comment by NickM-27** [comment]
Decoding is required for a number of things in the UI like camera still preview, quick start live streaming, and scrubbing for recording

It's also required for birdseye

and, unless you're using `all` recording mode then decoding would still be required to do motion detection so Frigate would only when to save motion segments

**Comment by pseud0sphere** [comment]
First, I appreciate the work doing being done and how responsive you are, so I don't mean this as a criticism in any way. If it's not going to happen because it would require too much effort or if it's just not a priority, I get it.

Even without `all` recording, recording could be triggered externally (e.g. from HTTP or MQTT API using the camera's onboard detection as I do), so it'd be useful if possible to implement and separate from the new (fully) disable/enable of cameras in 0.16. That's all I wanted to point out.

It makes sense that birdseye, still preview, etc. are using decode for still frames. I don't use birdseye and personally wouldn't mind sacrificing some of the UI elements (I guess they could be turned on/off depending on whether a client is connected to the UI) for consistent lower CPU load. That said, having decode integrated into all of those makes it understandable if it is a change that would be a huge pain that is impractical to implement.

I also get that maybe the answer is "then Frigate isn't the solution for you." I've tried some others, and nothing out there is perfect, and that's ok.
