### ISSUE TITLE
Clip/Snapshot Naming

### ISSUE THREAD

**Issue by alexispattein** [blakeblackshear/frigate#6799]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to name the snapshot and clips files differently that the one actually done.

**Describe the solution you'd like**
Having variable/options pre-determined for naming exemple camera"-"timestart etc.. could be implemented so anybody could rename the file to its will at the moment the <camera>-<id> system seems totally random and messy except for Frigate eventing system.
So to sort it out and clean the one you d like to keep it can take a bit of time.

**Describe alternatives you've considered**
There is only little explanation on the filenaming system and therefore did not really look further.

**Additional context**
As the snapshot are all in one folder I d like to maintain them and sort them out in folder the snap id does not really give any info and seems to not be in an ascendant form.

I don't know if it sounds like a stupid request or I am the only one to like this kind of thing implemented from the get go, anyway just thought I would try to ask see if it makes sense or bring something more to the table.
Cheers,

**Comment by NickM-27** [comment]
Can you explain more on why you are accessing these files directly? They should be being accessed via the API not the folder structure directly. The information in the file names are there to bring distinct and easily identifiable in the code. Making this customizable would either require this information still be in the name or require considerable refactoring.

**Comment by alexispattein** [comment]
It s mainly for storage. At the moment I have a 360d retention. But from time to time I just get the file and put it on an external storage. For the clips everything is pretty much done nicely with folders per date. Snapshots on the other hand are in one folder which I don't mind the but the filename is based on an id that nobody can understand instead of using a timestamp which is also unique like cameraname+timestamp.
Thanks for the answer so far, if it s too much might not worth it to work on that.
