### ISSUE TITLE
Birdseye autolayout is less optimized than previous grid layout

### ISSUE THREAD

**Issue by skrashevich** [blakeblackshear/frigate#6812]
### Describe the problem you are having

![image](https://github.com/blakeblackshear/frigate/assets/15078499/0a8e0f32-b24e-4579-aebb-e6d8443b7e52)

I circled the boundaries of the cameras with red frames for clarity

cameras dimensions, from left top: 1280x960, 1920x1080, 1920x1080, 2288x1288 (no mistake here), 1920x1080, 1920x1080

### Version

dev-3efa77f

### Frigate config file

```yaml
see #6802
```

### Relevant log output

```shell
no relevant
```

### FFprobe output from your camera

```shell
no relevant
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
Can you elaborate what you mean by broken? This looks to be working as expected unless I'm misunderstanding something

**Comment by skrashevich** [comment]
In previous builds it looks as this: 
<img width="1094" alt="image" src="https://github.com/blakeblackshear/frigate/assets/15078499/3301f22f-b9ac-4d15-8db4-a669a02e05aa">
Which variant is better? :)

**Comment by skrashevich** [comment]
> It can definitely be improved but it is not a bug, it is working as currently expected. It is difficult to make all layouts work for different cameras, especially wide angle and portrait cameras. In any case, I have an idea for a rewrite of the birdseye logic

A significant functionality degradation named a bug 🙂

I haven't found a case in which the new implementation would work better than the old one. Although this isn't a representative, but  it gives an understanding that something went wrong.

Perhaps it is worth making a configuration option to switch between the old and new implementations?

**Comment by NickM-27** [comment]
> I haven't found a case in which the new implementation would work better than the old one. Although this isn't a representative, but it gives an understanding that something went wrong.

Your use case is of course only one. You are using continuous mode which shows all camera. When using the birdseye camera in object mode and only some cameras are shown at a time it is much different. Like in my PR where the previous implementation did not get close to showing the camera in full screen

![Screen Shot 2023-06-07 at 10 45 34 AM](https://github.com/blakeblackshear/frigate/assets/14866235/f809907b-d654-44ca-a27b-967be903d084)

> Perhaps it is worth making a configuration option to switch between the old and new implementations?

I think my new idea for it will make that unnecessary
