### ISSUE TITLE
Make nginx respect logger: default settings

### ISSUE THREAD

**Issue by TheQue42** [blakeblackshear/frigate#6828]
**Describe what you are trying to accomplish and why in non technical terms**
Running 0.12.1-367d724, and I have configured logging as:
```
logger:
  default: warning
  logs:
    frigate.mqtt: warning
```
But the nginx is still continuously logging with:
```
2023-06-17 09:20:04.173117802  1.2.3.4 - - [17/Jun/2023:09:20:04 +0200] "GET /api/stats HTTP/1.1" 200 3594 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
```
**Describe the solution you'd like**
To be able to set NGINX logs to warning, to reduce log output. 

**Describe alternatives you've considered**
Tried adding `frigate.nginx: warning`, but it seems to be ignored.

**Additional context**

**Comment by NickM-27** [comment]
Those logger fields are only applied to python, I'm not sure nginx supports dynamic logging like that.

**Comment by insound** [comment]
IDK, but i guess there is no any help or debug from this logs, and mb should be better add access_log  off; in nginx.conf iside docker contaier.

**Comment by LeoI5** [comment]
Same problem. Messages are dropping once a second or more

**Comment by NickM-27** [comment]
> IDK, but i guess there is no any help or debug from this logs, and mb should be better add access_log  off; in nginx.conf inside docker contaier.

There are plenty of times where these kids have already been helpful for us debugging issues.

**Comment by TheQue42** [comment]
Any reason why?

**Comment by TheQue42** [comment]
Trying to follow the linked tickets, but it seems this whole issue has become stale? :-(

**Comment by pissten** [comment]
any updates on this?

**Comment by TheQue42** [comment]
Personally, although I havent had time to look into detail of this, I think it has already been fixed. Before, I always started a shell in a freshly created frigate container, and manually modified nginx's log-config. But I *think* that I dont have to do this any more, since .14 or something...

**Comment by definitio** [comment]
It's not fixed.

**Comment by TheQue42** [comment]
Well, checking my container now, and even recreating it, the specific complaint I had when I wrote this ticket, seems to be gone, or at least very reduced.

**Comment by definitio** [comment]
My logs still flooded with something like this:
```
frigate    | 2024-09-15 22:32:44.981358506  10.10.3.1 - - [15/Sep/2024:22:32:44 +0300] "GET /api/config HTTP/1.1" 200 14763 "http://frigate.home/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "10.10.1.50"
frigate    | 2024-09-15 22:32:44.981808680  10.10.3.1 - - [15/Sep/2024:22:32:44 +0300] "GET /api/profile HTTP/1.1" 200 18 "http://frigate.home/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "10.10.1.50"
frigate    | 2024-09-15 22:32:44.983276007  10.10.3.1 - - [15/Sep/2024:22:32:44 +0300] "GET /api/review?limit=10&severity=alert HTTP/1.1" 200 3921 "http://frigate.home/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0" "10.10.1.50"
frigate    | 2024-09-15 22:32:52.006244633  127.0.0.1 - - [15/Sep/2024:22:32:52 +0300] "GET / HTTP/1.1" 200 6837 "-" "curl/7.74.0" "-"
frigate    | 2024-09-15 22:32:52.756482739  10.10.3.1 - - [15/Sep/2024:22:32:52 +0300] "GET / HTTP/1.0" 200 6824 "-" "-" "-"
frigate    | 2024-09-15 22:32:55.006196807  127.0.0.1 - - [15/Sep/2024:22:32:55 +0300] "" 400 0 "-" "-" "-"
```
NGINX still ignores logging configuration.
