### ISSUE TITLE
[Bug] skipped_fps is always 0

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#6863]
AFAICT, the skipped_fps is always zero. https://github.com/blakeblackshear/frigate/blob/7c1568fcb941ad17256ab73438cb997b23fb7f33/frigate/video.py#L175 is where I would expect it to get updated (next to the fps, which ends up corresponding to the camera_fps), but that line doesn't actually assign to anything, and I can't find anywhere that the skipped_fps field of camera stats structures is passed anywhere.

Additionally, showing skipped_fps in the UI on the Detect line is slightly misleading if it is intended to be the location I linked above - that would mean that _all_ processing is getting behind, not just object detection.

**Comment by NickM-27** [comment]
I don't think this is valid and the linked issue should not be related. There is a stark difference between what you are seeing there (high levels of motion detection) vs a detector which is slow. 

If you run on an rpi on the CPU there is absolutely skipped fps being set as expected, and it also does not affect the live view from being up to date.

**Comment by NickM-27** [comment]
Looking through the code more, the skipped fps does not seem to be set on the system page, not sure if it was a change recently but I had done testing with skipped fps on my Pi in the past. The value would just need to be passed in to capture_camera and that would link it up I believe.

> Additionally, showing skipped_fps in the UI on the Detect line is slightly misleading if it is intended to be the location I linked above - that would mean that all processing is getting behind, not just object detection.

It might be slightly off in that the detection fps is technically object detections per second and the skipped fps would be total skipped frames, but I don't think it is misleading in the naming because it just says detection after all.

**Comment by ccutrer** [comment]
The issue mentioned (#6861) being only tangentially related is exactly why I opened a new issue. In my case it's perfectly likely that I'm not _actually_ dropping any frames, they just keep getting queued up forever or something.

What I'm saying is I've never seen skipped_fps being non-zero, and can't find an instance of that searching through the issue tracker of other peoples stats that have been posted (granted, GitHub's searching for such a specific thing is poor at best; I just had to search for "skipped_fps" and look at issues that look like they could be load related). I'm positing that assuming frame-skipping is working, it's not actually being reported properly in the stats. I'm not a python expert, but I am an experienced developer of many other languages, so can usually follow along in code even in languages I don't know.

I even tried setting my instance to use a single, single-threaded CPU detector, with the Corals disabled. There's no way it could possibly keep up. As expected, the detector process is using 95% CPU, detect FPS has dropped to 0 or close to it on most cameras (at a total of 9.3fps across all cameras). And yet skipped fps is still 0 for everything.

**Comment by NickM-27** [comment]
Yeah, not 100% sure what happened as it has been quite a while since I did that testing but I can see now it is not linked to the stats, should be easy to fix though.

**Comment by NickM-27** [comment]
By the way, it looks like it was removed in the linter https://github.com/blakeblackshear/frigate/commit/ab50d0b00623297f6d2e32b9add16925b670d85e removed it

**Comment by ccutrer** [comment]
Heh, I was just looking at that :). I'm guessing the linter removed the `skipped_fps = skipped_eps.eps()` because skipped_fps was a local, and never used. So I'm not sure it _was_ hooked up before that commit. Perhaps an earlier commit accidentally broke something?

**Comment by NickM-27** [comment]
Yeah most likely, there were some other things broken by that lint PR which were pretty nuanced as well.
