### ISSUE TITLE
Add a dynamic toggle for camera Birdseye inclusion via API

### ISSUE THREAD

**Issue by ksheyman** [blakeblackshear/frigate#6878]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to temporarily disable Birdseye inclusion without having to disable detection, so frigate will still detect and record in the background without displaying the camera in Birdseye.

**Describe the solution you'd like**
Add a separate toggle button for Birdseye inclusion, both in the UI and API.

**Describe alternatives you've considered**
I could possibly add the camera twice, and have birdseye disabled in one of the configs. So I could toggle between the two based on when I want Birdseye to work. However this feels like a janky workaround.

**Additional context**
Currently, I disable detection on certain cameras while I'm going to be in front of them for a long time, such as the camera in my workshop. I do this because I have a couple security monitors throughout the house constantly displaying the Birdseye view and I don't want it to be taken up by a live feed of me tinkering with things. However, because detection is disabled, I can not utilize person detection in Home Assistant for automation purposes, and events aren't recorded. I'd like to be able to have Frigate still detect person(s) on my workshop camera, but simply exempt it from Birdseye. This would allow me to automate, for example, turning off the lights when I've left my workshop, while not broadcasting myself to the rest of the house. If I am not actively in my workshop, I do want the camera included in Birdseye for security purposes (otherwise I could just disable Birdseye entirely for that camera).

Thanks for your time! I love Frigate!!

**Comment by NickM-27** [comment]
This is supported in 0.13

**Comment by ksheyman** [comment]
How does one make use of the feature? I am on 0.13.0-614a36a and I don't see anything in the UI or the API documentation (or any mention of it in the 0.13 changelogs). Thanks a lot, really looking forward to this!

**Comment by NickM-27** [comment]
it is in the docs https://deploy-preview-6262--frigate-docs.netlify.app/integrations/mqtt#frigatecamera_namebirdseyeset

**Comment by ksheyman** [comment]
> it is in the docs https://deploy-preview-6262--frigate-docs.netlify.app/integrations/mqtt#frigatecamera_namebirdseyeset

Awesome!! Thanks, I hadn't thought to check the MQTT section!!!
