### ISSUE TITLE
show ffmpeg commands and their options in logs

### ISSUE THREAD

**Issue by josh-m-sharpe** [blakeblackshear/frigate#6880]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to see the *actual* ffmpeg commands frigate is executing so that when errors happen (like the one below) I'm better equipped to debug it:

```
frigate-frigate-1  | 2023-06-22 04:36:37.992269269  [2023-06-22 04:36:37] frigate.video                  ERROR   : name_of_your_camera: Unable to read frames from ffmpeg process.
frigate-frigate-1  | 2023-06-22 04:36:37.993018261  [2023-06-22 04:36:37] frigate.video                  ERROR   : name_of_your_camera: Unable to read frames from ffmpeg process.
frigate-frigate-1  | 2023-06-22 04:36:37.994931388  [2023-06-22 04:36:37] frigate.video                  ERROR   : name_of_your_camera: ffmpeg process is not running. exiting capture thread...
```

**Describe the solution you'd like**
If I had the actual command with all its options I could fiddle with ffmpeg directly.

**Describe alternatives you've considered**
googling a lot to guess at what this error might be

**Additional context**
N/A

**Comment by NickM-27** [comment]
In 0.13 the commands are viewable in the system page

**Comment by nmschulte** [comment]
Where can these commands be viewed in current releases, like 0.15?

**Comment by hawkeye217** [comment]
One place you can see them is in the `ffmpeg_cmds` prop for each camera in the config API object: `http://frigate_ip:5000/api/config`
