### ISSUE TITLE
Look for a better model or a secondary model to reduce false positives

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#69]

**Comment by ne0ark** [comment]
Any luck with this? Right now I am running deepquest + blueiris side by side and model they have used is hands down better than corals.

**Comment by blakeblackshear** [comment]
This issue wasn't about accuracy of the model, but removing the need to convert the video format from yuv420p to rgb24. Do you mean deepstack? What model is it using?

**Comment by ne0ark** [comment]
https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff slightly better trained model and has less false positive in night time.

**Comment by blakeblackshear** [comment]
Did you follow a guide for running deepquest and blueiris?

**Comment by ne0ark** [comment]
https://ipcamtalk.com/threads/tool-tutorial-free-ai-person-detection-for-blue-iris.37330/ . It seems like 4k is giving more false positive with coral's model, it detect flower pot as person.

**Comment by scstraus** [comment]
Hi Blake,
Have you heard about this yet?
https://www.hackster.io/news/google-releases-new-efficientnet-edgetpu-models-for-coral-hardware-39c3f3f734bf
https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet/edgetpu

On paper they look very good.  Back when I was using CPU based models, I was using faster_rcnn_inception_v2_coco and it was far better than the mobilenet models. The new ones linked above compare favorably. They might be the holy grail unless I'm misunderstanding something.

**Comment by blakeblackshear** [comment]
Yea. They are image classification models, not object detection models. That means they won't give me a bounding box, so I can't use them for tracking. They might be good for a second look to filter out false positives from the first model.

**Comment by ne0ark** [comment]
deepquest.ai detects a person 40-60 feet away from my sub stream at 90+ accuracy. For the Current model, anything that is more than 20 feet away has issues being detected. Also, there are tons for false-positive when my camera switches the mode from day to night and visa versa. I wonder it is be cause my lorex camera is set on "Super Codec" mode where it reduces frame rate.

**Comment by kidhasmoxy** [comment]
Deepstack uses YOLOv3 for object detection, which can have great performance. Highly recommend thinking about using YOLOV4 in a way that allows end users to specify the image size so that folks that run this on more powerful rigs can take advantage of the higher accuracy, especially for small objects. 

Some examples of YOLOv4 implemented in other frameworks. You'll likely find one that works well in here: https://github.com/AlexeyAB/darknet#yolo-v4-in-other-frameworks

**Comment by ne0ark** [comment]
Anyone have run yolov4 through coral compiler?

**Comment by ne0ark** [comment]
It seems like there are some issues with yolov4 but v3 should work: https://github.com/guichristmann/edge-tpu-tiny-yolo

**Comment by scstraus** [comment]
As I have already had great experiences with R-CNN, I wonder if this would be usable for this?

https://cloud.google.com/tpu/docs/tutorials/mask-rcnn

**Comment by zewelor** [comment]
There is some ongoing work to port efficentdet for coral https://github.com/google/automl/issues/11 . Its object detection based on, previously mentioned, efficentnet

**Comment by ne0ark** [comment]
With version .8 anyone got a better model for edge tpu?

**Comment by blakeblackshear** [comment]
It uses the new MobileDet model which I did find to be better. https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/2740?u=blakeblackshear
