### ISSUE TITLE
Select All or Deselect All

### ISSUE THREAD

**Issue by blthlt** [blakeblackshear/frigate#6900]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to hit a button to select all or to deselect all when looking through events... so that I can avoid having to click every camera that I do not want to see individually.

**Describe the solution you'd like**
See image.

**Describe alternatives you've considered**
Cant think of any easier.

**Additional context**
![image](https://github.com/blakeblackshear/frigate/assets/479263/fd974e37-8cc5-45e6-8843-0b25a47419c2)

**Comment by NickM-27** [comment]
This is already supported, simply click the blue camera icon to only select that item

**Comment by blthlt** [comment]
Oh, crap.  Okay thats easy enough.  Thanks.
