### ISSUE TITLE
[Errno 2] No such file or directory: '/config/config.yml'

### ISSUE THREAD

**Issue by kalyan427** [blakeblackshear/frigate#691]
Whenever I try to setup from docker-compose or docker hub.it always shows this error.
![Screen Shot 2021-02-01 at 2 17 32 PM](https://user-images.githubusercontent.com/9591600/106528107-15019380-649d-11eb-91c2-80c70c0b23d9.png)

**Comment by mitchelloharawild** [comment]
You will need to create a `config.yml` file within the configuration directory.
At minimum, this file should contain a camera and mqtt host server.

Documentation on creating and configuring this file can be found here: https://blakeblackshear.github.io/frigate/configuration/index

---

Perhaps a possible improvement to the project would be to include a template config.yml for docker installation? This would have made it faster/easier to install and run.

**Comment by kalyan427** [comment]
Yeah, that's a good idea. I was a little confused regarding that. thanks for your prompt response.

**Comment by kalyan427** [comment]
Hi, Still I cannot able to set up. can you explain to me with clear steps it will be helpful?

**Comment by jaburges** [comment]
@kalyan427  can you share your docker compose or docker command
You need to put config.yml in the mapped volume (accessible on the host and container). This folder is persistent meaning it survives the destruction of the container. 

Your mapped volume will be something like:
```-v /path/to/frigate/config:/config``` 

You will need to put the config.yml file
```/path/to/frigate/config/config.yml```

Then check the documentation for what to put in there :)

**Comment by kalyan427** [comment]
Sure I will try and I will update.once successful.thanks for info.

**Comment by shawwellpete** [comment]
Hi, I'm having a similar issue with finding the correct location for config.yml 
Looking at the volumes in portainer suggests the correct path is /var/lib/docker/volumes/frigate_config/_data

![2021-09-20_18-28-19](https://user-images.githubusercontent.com/74064242/134047070-83ec56a9-1a1b-438d-9089-6ec78c0ada8a.jpg)

Which is where I put the config file
![2021-09-20_18-29-45](https://user-images.githubusercontent.com/74064242/134047297-4e817d2c-944f-4b59-b13f-aee81650c0da.jpg)

On the logs I'm getting 

[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Error parsing config: [Errno 21] Is a directory: '/config/config.yml'

Any ideas would be very gratefully received. I have Frigate working on Home Assistant under surpervisor but would love to have it on portainer so I could save to a remote HDD

**Comment by LordNex** [comment]
having issues with this too. While ssh'd i created a folder named frigate and built a docker compose with the config file pointing there. But for some reason, I still get the error 21. Here is my docker-compose

`      version: "3.9"
services:
  frigate:
    ...
    volumes:
      - /frigate/config.yml:/config/config.yml:ro
      - /frigate/:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ...`

**Comment by gophernz** [comment]
I ran into the same issue while installing following a Digimoot tutorial. Instructions said to add this line: ./config/frigate.yml:/config/config.yml:ro, but that resulted in the error. Changed it to read:
./frigate.yml:/config/config.yml:ro and everything was peachy.
I know as much about linux as I do about the digestive system of a himalayan mountain goat so take the advice with a grain of salt. Or, perhaps a chunk of himalayan rock salt as the case may be.

**Comment by LordNex** [comment]
> ./frigate.yml:/config/config.yml:ro

Did a rebuild on a Jetson Nano using digimot walkthrough tans had same issue. Your fix worked but now I'm getting 

```

1 validation error for FrigateConfig
frigate  | __root__
frigate  |   FrigateConfig expected dict not NoneType (type=type_error
```

**Comment by GregWoods** [comment]
> You will need to create a `config.yml` file within the configuration directory. At minimum, this file should contain a camera and mqtt host server.
> 
> Documentation on creating and configuring this file can be found here: https://blakeblackshear.github.io/frigate/configuration/index

Thanks
But 2 things add to the confusion here...
1) No mention at all is made of config.yml in the installation instructions
2) Running docker compose shows the outout of "create_config.py". I would have assumed it would create a config file if none were found. 
Maybe a documentation improvement is needed here.

**Comment by NickM-27** [comment]
@GregWoods 

1. It is covered in the [Getting Started Guide](https://docs.frigate.video/guides/getting_started). Completely open to suggestions or PRs for improving the docs, but I can say with helping users getting started they often seem to not read the getting started docs
2. You seem to be referring to https://github.com/blakeblackshear/frigate/blob/159fb51518f2073518fee72d8b5daf895c168a74/docker/main/rootfs/usr/local/go2rtc/create_config.py which has nothing to do with frigate, it is creating the config for go2rtc

**Comment by LordNex** [comment]
I originally used digimoots how too as well. Went to try and find it the other day and couldn’t find it.

Good tutorial, could be updated though last time I saw it.

Benjamin T Powers

On Jan 27, 2022, at 6:24 PM, gophernz ***@***.***> wrote:

﻿

I ran into the same issue while installing following a Digimoot tutorial. Instructions said to add this line: ./config/frigate.yml:/config/config.yml:ro, but that resulted in the error. Changed it to read:
./frigate.yml:/config/config.yml:ro and everything was peachy.
I know as much about linux as I do about the digestive system of a himalayan mountain goat so take the advice with a grain of salt. Or, perhaps a chunk of himalayan rock salt as the case may be.

**Comment by kronkinatorix** [comment]
@ NickM-27  appreciate your good intentions here but I think it may be helpful for you to take a quick refresher on the getting started guide.
This: https://docs.frigate.video/guides/getting_started/ doesn't mention mapping the config.yml file. Or the config.yml file at all, in fact. Am I to not worry about this little rascal?  Or have I once again in my myopic pursuit of a solution missed it?

This: https://docs.frigate.video/configuration/ while all around a thoroughly detailed document (kudos to whoever did this. It's such a breath of fresh air) it is also, unfortunately, not helpful for our quandary. 

The doc says: 

"the config file should be mapped to /config/config.yml inside the container." 

While I agree that it's important to know what needs to be done, it's equally important to know how to do it. 

Now, if Docker were a human being I'd gladly take the life sentence that would come with me acting out the horrific things I'd do to it but alas, it's not, so I can only scream into the void, becoming ever more aware of the fragility of mortality as my death draws nearer day by day, minute by minute, with a whale that is made all the more sinister by my own inability to not only fix the challenge I'm facing, but also to go back in time with an exact replica of the docker mascot made out of a tungsten carbide alloy and stop this horrific smiling monster from ever being created with extreme prejudice.

**Comment by NickM-27** [comment]
I said the installation instructions (not the getting started guide) which absolutely do mention the config.yml https://docs.frigate.video/frigate/installation#docker

Also, the docs have been revamped in 0.13 https://deploy-preview-6262--frigate-docs.netlify.app/guides/getting_started

**Comment by kronkinatorix** [comment]
Indeed. 10-odd tabs, 10 browser windows for some reason, frigate this, cuda that, why, is any surprise I missed this? Or my dog? Or my wife? Word to the wise: if your wife ever tells you that if you go on on more alcohol-fuelled anter-docker tirade she's leaving you, she means it. 

And it's absolutely worth it.
