### ISSUE TITLE
[BUG]: 1 month and 1 minute are both shown as "1m ago"

### ISSUE THREAD

**Issue by ronisaacson** [blakeblackshear/frigate#6935]
### Describe the problem you are having

In web/src/components/TimeAgo.tsx, timeUnits has `mo` for month. But further down, it uses `timeUnits[i].unit[0]` which only shows the first character, even though `timeUnits[i].unit` is already an abbreviation. This leads to the "m" suffix being ambiguously used for both months and minutes.

### Version

0.12.1-367D724

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by ronisaacson** [comment]
Examples. This was 6 minutes ago:

![image](https://github.com/blakeblackshear/frigate/assets/13400038/03066271-3170-4cbd-866b-ee0f93aea9a6)

This was just over a month ago (not quite a cat but close enough):

![image](https://github.com/blakeblackshear/frigate/assets/13400038/f97ead7a-4357-4083-a0ba-e1259311ecc8)

**Comment by NickM-27** [comment]
Fixed for the next version of frigate
