### ISSUE TITLE
[Config Support]: Birdseye beneath each other?!

### ISSUE THREAD

**Issue by illivanillie** [blakeblackshear/frigate#6950]
### Describe the problem you are having

Is it possible to arrange streams in birdseye beneath each other? I have few Rlnk Duo cams which are 4608x1728, thus much space is lost in the view because the streams are next to each other. Kind of unfortunate that details are lost there :/

thanks! :)

### Version

0.12

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

**Comment by NickM-27** [comment]
This has already been reworked for 0.13
