### ISSUE TITLE
Preview?

### ISSUE THREAD

**Issue by clemi2408** [blakeblackshear/frigate#696]
Hey Frigate team,
First of all awsome work you did!

I have a question:
Is this ui ment to have a live preview? As i see 0fps![image](https://user-images.githubusercontent.com/35063751/106600698-0d082900-655b-11eb-8bf4-468c1b543af9.png)

Regards
Clem

**Comment by paularmstrong** [comment]
What version of Frigate are you running?
Is this Mobile Safari?
Does it work in another browser or desktop computer?

**Comment by clemi2408** [comment]
Image	blakeblackshear/frigate:0.8.0-aarch64@sha256:26cd230c19131c2c371ee74ae83c97d8508f358cb396b9fe84288696add20b2b

And it happens not just in safari.

Btw. Person detection works just fine, i have events in the ui!

**Comment by paularmstrong** [comment]
0.8.0 had a bug with the preview. Please update to 0.8.1

**Comment by paularmstrong** [comment]
https://github.com/blakeblackshear/frigate/pull/628

**Comment by paularmstrong** [comment]
Please comment/reopen if this is still a problem after updating!
