### ISSUE TITLE
[Config Support]: motion detection values explained please

### ISSUE THREAD

**Issue by illivanillie** [blakeblackshear/frigate#6966]
### Describe the problem you are having

Hi there! 
im currently trying to fine tune my motion detection, especially at night. Where can I read more about the alpha values and their ranges and how could I determine my best frame height? I guess it depends on the cameras resolution? How is the threshold value processed?
Plus: What does the number next to the percentage value above a bounding box mean?

kind regards and thank you guys a lot! Truly amazing what we are getting here!

### Version

.

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

**Comment by NickM-27** [comment]
The general guidance is to adjust threshold and contour_area without messing with the others unless necessary. All of the values are covered [here](https://docs.frigate.video/configuration/) but you could also read my in-PR motion tuning guide https://github.com/blakeblackshear/frigate/pull/6877

> What does the number next to the percentage value above a bounding box mean?

This is the area of the bounding box
