### ISSUE TITLE
[Config Support]: Missing boundary box on clip

### ISSUE THREAD

**Issue by 2Belette** [blakeblackshear/frigate#6967]
### Describe the problem you are having

Hi, I have the boundary box on Screenshots as I added to my configuration, but I think I am missing the way to add them on clips.

It is like to me what is show inside the filter part from the configuration example but it is not clear to me.

Thanks

### Version

0.12.1

### Frigate config file

```yaml
That's what I am trying to understand
```

### Relevant log output

```shell
Not applicable
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by blakeblackshear** [comment]
There isn't a way to add them on the clips. That would require reencoding the video segments.

The next release will show you where the bounding box was during key moments by drawing it as an overlay on top of the video in the frontend, but it still won't be in the actual video.

**Comment by 2Belette** [comment]
Thanks for that, I was looking like crazy ! maybe because I saw some other users having theses boundary boxes on some of there video.

What you described for the next release is already a very good news and well enough !
