### ISSUE TITLE
[Support]: re-encode H264 to H265 using TDarr

### ISSUE THREAD

**Issue by hollanbm** [blakeblackshear/frigate#6969]
### Describe the problem you are having

I’ve got frigate/tdarr running on the same host using an RTX A4000 for hw encode/decode

my unifi cameras are setup with RTSP, and output H.264

I know frigate wont natively convert the recordings.

but I was wondering if I setup tdarr, to come in and convert files older than say 1 hour. (I would leave the video container alone, just change the codec.)

Would this cause any issues with frigate? Since I’d be changing the codec outside of the frigate application.

I’m hoping to leverage the space savings of H265, to store more footage

would this cause any issues?

### Version

0.1.12

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Unifi Protext g3/g4/g5

**Comment by NickM-27** [comment]
The easiest way would be to just use go2rtc to re-encode the stream to h.265

**Comment by hollanbm** [comment]
> The easiest way would be to just use go2rtc to re-encode the stream to h.265

Oh! I wasn’t aware that was a possibility.

I was searching the repo issues, and kept finding posts of people wanting to go the opposite direction.

I’ll go head back onto the docs and see if I can’t get the config straightened out. Anything you think I should know in advance?

**Comment by NickM-27** [comment]
it should be pretty simple to setup, but the only problem is go2rtc currently has a bug that means the automatic h265 transcoding won't work so you'll need to define a new h265 preset to get it to work. I can help with that if need be

**Comment by hollanbm** [comment]
> it should be pretty simple to setup, but the only problem is go2rtc currently has a bug that means the automatic h265 transcoding won't work so you'll need to define a new h265 preset to get it to work. I can help with that if need be

Good to know, I’ll give it a go first, and see what I come up with.

thank you!

**Comment by johntdyer** [comment]
> it should be pretty simple to setup, but the only problem is go2rtc currently has a bug that means the automatic h265 transcoding won't work so you'll need to define a new h265 preset to get it to work. I can help with that if need be

I would love a working example if you have one

**Comment by tomerh2001** [comment]
Let's say I have `/media` where all my media (movies, TV, and frigate recordings) live, and I tell tdarr to "have at it" in the `/media` folder. Would it cause issues to Frigate?

**Comment by NickM-27** [comment]
As long as the file names stay the same
