### ISSUE TITLE
[FR] Configurable recorder video length

### ISSUE THREAD

**Issue by viperk1** [blakeblackshear/frigate#697]
Currently this is fixed at 1 min length for each video file. Would be great to make this configurable, within any reasonable limits for performance. 3 or 5 mins is what I'd be setting.

**Comment by blakeblackshear** [comment]
You can customize by overriding the `segment_time` in the ffmpeg output params for the record role. https://blakeblackshear.github.io/frigate/configuration/index#ffmpeg

Note that if ffmpeg's connection to the camera is interrupted, you will lose the entire 5 minute file.

**Comment by viperk1** [comment]
That did it! Thanks for the info!
