### ISSUE TITLE
[Support]: Detection after first movement?

### ISSUE THREAD

**Issue by illivanillie** [blakeblackshear/frigate#6982]
### Describe the problem you are having

I switch off detection during the night to reduce false positives and switch on via HA under certain conditions.
Question: If I switch on detection, will it jump on an already existing motion in that moment or is detection in that area only active if it catches the change from no movement to movement?
thanks!

### Version

0.12.0

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

.

**Comment by NickM-27** [comment]
If you have the object detect disabled and then you enabled it at some point later it will detection objects as soon as motion occurs.

**Comment by illivanillie** [comment]
And if there‘s motion and detection is enabled after the first movement? Let‘s say a running person, so there would be frames with movement?

**Comment by NickM-27** [comment]
> And if there‘s motion and detection is enabled after the first movement? Let‘s say a running person, so there would be only frames with movement?

I'm not sure I really understand your question. motion is motion. Once object detect is enabled, motion will cause frigate to look for objects. What was happening before object detect was enabled is entirely irrelevant

**Comment by illivanillie** [comment]
Ok. I’m still trying to figure some things out, but at the moment my setup works like this:
Motion delay is set to zero, if movement occurs for 1s+, spotlights will turn on and only then will object detection be enabled. So in my case, there’s the possibility that there is movement in every frame and detection could not be able to „jump“ on that exact movement because there’s no **initial** moment of movement for detection. Or let’s say that’s my question. Can you follow me?
During the night or better in black/white my (personal) detection was giving me waaaay too many false positives.

**Comment by NickM-27** [comment]
> So in my case, there’s the possibility that there is movement in every frame and detection could not be able to „jump“ on that exact movement because there’s no initial moment of movement for detection

that's not how it works. like I said motion is motion which is just pixels changing. There is no construct of time with motion. if detection is enabled and then there are pixels changing, detection will be run and an object will be detected if there is one. 

the spotlight turning on will be motion across the entire camera frame basically which will cause the object to be detected if there is one.

**Comment by illivanillie** [comment]
Yes thanks. I thought maybe not with time but with a change of state.

> 
> the spotlight turning on will be motion across the entire camera frame basically which will cause the object to be detected if there is one.

this does not matter, because the trigger is a movement before the spotlights are turned on and detection is only enabled after the spotlights turned on

**Comment by NickM-27** [comment]
> this does not matter, because the trigger is a movement before the spotlights are turned on and detection is only enabled after the spotlights turned on

it still affects it though, cameras usually take multiple seconds to fully adjust to drastic changes in lighting and those changes will continue to be detected as motion
