### ISSUE TITLE
Detecting objects other than "person"?

### ISSUE THREAD

**Issue by hawkeye217** [blakeblackshear/frigate#70]
I know it's possible to feed in another model via the `docker-compose` file, but I'm wondering if it would be possible to generalize the code a bit to allow perhaps a config entry or something for detection of other objects/faces with other models and still give a `best_<object>.jpg` image.  I'd love to be able to use your code with the faces model, which doesn't have a labels file either.

**Comment by miikkajo** [comment]
i'd really would like to detect cars on my yard.
Its easy to detect them, but i dont want constant alarms on my own car parked on my yard...

Maybe some sort of detection history should be implemented, 
only alert when bouncing box moved more than 5% in last x seconds ?

maybe configurable age of detection and simple json storage for objects,
older than x sec would be discarded.

https://github.com/pliablepixels/zmeventnotification/ does it somewhat similar:
```
 if g.config['match_past_detections'] == 'yes' and args['monitorid']:
            # point detections to post processed data set
            g.logger.info ('Removing matches to past detections')
            bbox_t, label_t, conf_t = img.processPastDetection(bbox, label, conf, args['monitorid'])   
            # save current objects for future comparisons
            g.logger.debug ('Saving detections for monitor {} for future match'.format(args['monitorid']))
            mon_file = g.config['image_path'] + '/monitor-'+args['monitorid'] +'-data.pkl'
            f = open(mon_file, "wb")
            pickle.dump(bbox,f)
            pickle.dump(label,f)
            pickle.dump(conf,f)  
            bbox = bbox_t
            label = label_t
            conf = conf_t
```
second question is, is this something that frigate should do ?
or should this happen outside frigate docker...

**Comment by scstraus** [comment]
I'd love to see if we could detect specific types of cars using a model trained with the coco imageset which can distinguish between different types of cars.. I'd like to detect delivery vans for example.

**Comment by pizzato** [comment]
Yes I think this should be in Frigate for different object detections. People will use systems like this for different reasons. So setting up whatever type of object you want to detect would be quite useful. I could use this to detect how often some animals get into my house and what were they.

If I find time, I can work towards decoupling the labels from the people detection part, that can set the scene for a multiple screenshots of "best" objects.

**Comment by miikkajo** [comment]
detecting objects is easy, "static" objects (as my own car in driveway) is problem.
there must be a way to detect and alarm when car is detected, 
but if it does not move, no more alarms should trigger.

i have object_filter in use to limit detections to cars and persons per region
so i can create region that does not contain any "static" cars but it's not ideal

**Comment by scstraus** [comment]
>I could use this to detect how often some animals get into my house and what were they.

Hmm, maybe you should spend some time fixing the holes in your walls first!?! ;-)
