### ISSUE TITLE
[Feature] Option to hide PTZ from Birdseye view

### ISSUE THREAD

**Issue by JeffWDH** [blakeblackshear/frigate#7016]
**Describe what you are trying to accomplish and why in non technical terms**
It would be useful to have an option to disable showing the PTZ controls on the Birdseye view.

**Describe the solution you'd like**
A configuration entry such as this:
```
birdseye:
  enabled: true
  ptz: false
```

**Describe alternatives you've considered**
The only option available currently is to disable PTZ globally. 

**Additional context**
In my use case I have no need to control PTZ from the Birdseye view. The controls take up space and if given the option I would disable them.

**Comment by NickM-27** [comment]
We are not wanting to have a bunch of options that control the UI so I don't think that approach makes sense, but could definitely have a button in the UI which collapses the ptz controls and remembers state

**Comment by JeffWDH** [comment]
Sure, I don't have a preference how it's handled as long as there is a way to hide the PTZ controls. :)

**Comment by DoTheEvo** [comment]
Damn, I wanted this too.
birdseye is suppose to be default place to look at, once you enable ptz ALL of my cameras feed shrinks by half.
So I either get ptz control or normal size view.

**Comment by mccasian** [comment]
I need this too
