### ISSUE TITLE
[Detector Support]: "ERROR : No EdgeTPU was detected" on USB 3, slow inference on USB 2 RasPi4

### ISSUE THREAD

**Issue by dfurrer** [blakeblackshear/frigate#7034]
### Describe the problem you are having

I have what I think should be a pretty standard home assistant setup running on a Raspberry Pi 4. Following the advice in the docs and forum here I got an EdgeTPU. At first I had no luck getting it to work. Checking the logs I see "No EdgeTPU was detected.". However I then noticed it works when I plug it into a USB 2 port rather than the USB 3 I tried first. BUT it seems to be very slow. The System page reports and Inference Speed in the range of 100 - 200 ms!

### Version

0.12.1-367D724

### Frigate config file

```yaml
...
# 6 cameras
....
detectors:
  coral:
    type: edgetpu
```

### docker-compose file or Docker CLI command

```yaml
?
```

### Relevant log output

```shell
2023-07-04 20:11:25.908738791  [2023-07-04 22:11:25] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
The pi is likely unable to supply enough power for the coral on usb 3, which is why the docs suggest a powered USB hub

**Comment by easy-and-simple** [comment]
with such config file it is not wondering that you have problems

**Comment by dfurrer** [comment]
Thanks Nick! I missed that part but can see it now.
