### ISSUE TITLE
Anyone has discover how many camera will work on PI4 ?

### ISSUE THREAD

**Issue by dgillier** [blakeblackshear/frigate#704]
I'm quite excited by using Frigate, but I can't find benchmark or at least max capabilities.
I'm particularly interested by how many 1080p RTSP cameras a PI4/4GB with Coral USB dongle can handle ?

Anyone with such info ?

Thanks in advance,
Denis

**Comment by NearlCrews** [comment]
IMO there are way too many factors for an easy answer here. It depends on FPS, detection settings, CPU, NVIDIA cards, etc. Coral has [published specs](https://coral.ai/docs/edgetpu/benchmarks/) though. I'm currently running 5 1080p cameras but doing the processing on substreams at 6 FPS with the NVIDIA docker container. My CPU usage is virtually non-existent, i.e. each instance shows about 1-2% CPU usage on an Intel i7-4790K.

**Comment by dgillier** [comment]
Thanks for your answer !
But a i7 is pretty more powerful than the PI4 A72...
I'm really looking for PI4+coral performance.

**Comment by blakeblackshear** [comment]
If it is dedicated to Frigate, it can handle at least 4 1080p cameras at 5fps assuming you don't have them all pointed at a crowded street of people.

Here is an example of another user using a pi4: https://github.com/blakeblackshear/frigate/discussions/395#discussioncomment-225189

**Comment by dgillier** [comment]
@blakeblackshear Thanks !

Is there any doc of the image processing workflow used to have better understand what is consuming CPU ?
