### ISSUE TITLE
[Support]: Recording playback buffering

### ISSUE THREAD

**Issue by Beeez** [blakeblackshear/frigate#7043]
### Describe the problem you are having

When playing back any recordings, after 10 or so seconds of playing it will stop and start buffering, however once it resumes it has skipped through time as if it continued playing during the buffering. 

When checking chrome://media-internals I am seeing these repeating BUFFERING_HAVE_ENOUGH and DEMUXER_UNDERFLOW BUFFERING_HAVE_NOTHING events that correspond which each moment of buffering. 

Chrome dev console networking will show each segment loading during this.

Is part of my issue for the constant buffering because of my recording resolution? If so, why does the playback time still continue during buffering?

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.4.31
  port: 1883
  user: mqttuser
  password: ''
  topic_prefix: frigate

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: continuous


ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - +genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
    - -rw_timeout
    - "5000000"
  output_args: 
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac

go2rtc:
  streams:
    front_door:
      - ffmpeg:http://192.168.4.45/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
    garage_inside:
      - ffmpeg:http://192.168.4.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
    front_driveway:
      - ffmpeg:http://192.168.4.32/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
    back_yard:
      - ffmpeg:http://192.168.4.71/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=

cameras:
  front_door:
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 10000
          min_score: 0.65
          mask:
          - 583,378,462,489,458,606,660,720,336,720,313,596,345,489,394,425,446,368
          - 472,67,552,93,378,177,313,135
        car:
          min_area: 10000
    ffmpeg:
      inputs:
        - path: http://192.168.4.45/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.4.45/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    motion:
      mask:
        - 925,32,908,0,799,0,763,81,841,113,913,82
        - 348,183,0,313,0,80,0,0,264,0,886,0
        - 583,378,462,489,458,606,660,720,336,720,313,596,345,489,394,425,446,368
    zones:
      driveway:
        coordinates: 269,211,424,200,251,345,65,308
        objects:
          - person
          - car
      driveway_parked:
        coordinates: 291,352,970,395,997,202,855,110,784,96,605,93,497,145,428,194,412,207,265,304,239,333
        objects:
          - person
      porch:
        coordinates: 831,207,984,38,1174,54,1059,720,987,720,652,720,499,649,448,523,602,361
        objects:
          - person
      frontgrass:
        coordinates: 186,328,438,363,357,484,337,720,0,720,0,383,86,323
        objects:
          - person
  garage_inside:
    objects:
      track:
        - person
        - car
    ffmpeg:
      inputs:
        - path: http://192.168.4.50/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.4.50/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    detect:
      width: 1280
      height: 720
      fps: 5
    zones:
      garage_spot:
        coordinates: 570,131,924,418,940,503,826,720,367,720,22,245
        objects:
          - car
          - person
      parked:
        coordinates: 1055,720,1029,536,692,720
        objects:
          - car
  front_driveway:
    objects:
      filters:
        car:
          mask:
          - 1280,0,1280,238,998,159,390,49,0,130,0,0
        person:
          mask:
          - 1280,0,1280,238,998,159,390,49,0,130,0,0
          min_score: 0.71
          max_area: 100000
          min_area: 1100
      track:
        - person
        - car
    ffmpeg:
      inputs:
        - path: http://192.168.4.32/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.4.32/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    zones:
      front_driveway_center:
        coordinates: 0,464,431,278,986,162,1280,249,1280,476,944,720,0,720
        objects:
          - car
          - person
    detect:
      width: 1280
      height: 720
      fps: 5
  back_yard:
    objects:
      track:
        - person
        - dog
        - cat
      filters:
        person:
          mask:
            - 1280,720,1044,720,1114,468,1280,468
            - 1280,0,1280,149,798,85,376,164,0,251,0,0,1041,0
    ffmpeg:
      inputs:
        - path: http://192.168.4.71/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
            - rtmp
        - path: http://192.168.4.71/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
    zones:
      backgrass:
        coordinates: 1074,247,915,399,1280,481,1280,185,1280,98,1198,91,1056,32,857,31,854,77,769,79,695,66,462,148
        objects:
          - person
          - dog
          - cat
      porch_grass:
        coordinates: 255,148,322,47,434,44,479,141,1083,204,1030,405,1280,720,0,720,0,202
        objects:
          - person
          - dog
          - cat
    detect:
      width: 1280
      height: 720
      fps: 5

snapshots:
  enabled: true
  bounding_box: true
  required_zones:
    - driveway
    - porch
    - backgrass
    - frontgrasss
    - front_driveway_center
    - porch_grass
  retain:
    default: 3

detectors:
  cpu1:
    type: cpu

record:
  enabled: True
  retain:
    days: 15
    mode: all
  events:
    required_zones:
      - driveway
      - porch
      - garage_spot
      - backgrass
      - frontgrass
      - porch_grass
      - front_driveway_center
    retain:
      default: 20
      mode: active_objects
    pre_capture: 5
    post_capture: 20

timestamp_style:
  position: "tr"
```

### Relevant log output

```shell
00:00:02.837 | kVideoDecoderName | "D3D11VideoDecoder"
-- | -- | --
00:00:02.837 | kIsPlatformVideoDecoder | true
00:00:02.837 | info | "Selected D3D11VideoDecoder for video decoding, config: codec: h264, profile: h264 high, level: not available, alpha_mode: is_opaque, coded size: [2560,1440], visible rect: [0,0,2560,1440], natural size: [2560,1440], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
00:00:02.837 | pipeline_state | "kPlaying"
00:00:02.866 | dimensions | "2560x1440"
00:00:02.866 | kResolution | "2560x1440"
00:00:02.867 | seek_target | 2957.053989
00:00:02.867 | pipeline_state | "kSeeking"
00:00:02.867 | video_buffering_state | {"state":"BUFFERING_HAVE_NOTHING"}
00:00:05.940 | pipeline_state | "kPlaying"
00:00:06.029 | pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
00:00:12.678 | video_buffering_state | {"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:00:12.751 | warning | " Large timestamp gap detected; may cause AV sync to drift. time:2964114000us expected:2964038000us delta:76000us"
00:00:15.679 | pipeline_buffering_state | {"for_suspended_start":false,"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:00:23.249 | seek_target | 2974.217333
00:00:23.249 | pipeline_state | "kSeeking"
00:00:23.249 | pipeline_state | "kPlaying"
00:00:23.253 | pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
00:00:32.883 | video_buffering_state | {"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:00:32.962 | warning | " Large timestamp gap detected; may cause AV sync to drift. time:2984244000us expected:2984168000us delta:76000us"
00:00:35.885 | pipeline_buffering_state | {"for_suspended_start":false,"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:00:43.437 | seek_target | 2994.337333
00:00:43.437 | pipeline_state | "kSeeking"
00:00:43.437 | pipeline_state | "kPlaying"
00:00:43.442 | pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
00:00:53.070 | video_buffering_state | {"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:00:56.071 | pipeline_buffering_state | {"for_suspended_start":false,"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:01:03.625 | seek_target | 3014.457333
00:01:03.625 | pipeline_state | "kSeeking"
00:01:03.625 | pipeline_state | "kPlaying"
00:01:03.630 | pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
00:01:13.258 | video_buffering_state | {"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:01:16.258 | pipeline_buffering_state | {"for_suspended_start":false,"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:01:23.825 | seek_target | 3034.584333
00:01:23.825 | pipeline_state | "kSeeking"
00:01:23.825 | pipeline_state | "kPlaying"
00:01:23.828 | pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
00:01:33.446 | video_buffering_state | {"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
00:01:33.535 | warning | " Large timestamp gap detected; may cause AV sync to drift. time:3044611000us expected:3044535000us delta:76000us"
00:01:36.448 | pipeline_buffering_state | {"for_suspended_start":false,"reason":"DEMUXER_UNDERFLOW","state":"BUFFERING_HAVE_NOTHING"}
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"29/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"30/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":512,"width":896},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

Happens regardless of mobile or desktop.

**Comment by NickM-27** [comment]
What kind of storage are your recordings stored on?

Also I'd highly suggest updating your config to use ffmpeg presets

**Comment by Beeez** [comment]
> What kind of storage are your recordings stored on?
> 
> Also I'd highly suggest updating your config to use ffmpeg presets

It is a Toshiba Surveillance drive, DT01. Checking iostat it doesn't seem to be struggling to keep up with reads or writes. 

I will have to look into what presets I will need to use.

**Comment by NickM-27** [comment]
So that's definitely the problem, by default in 0.12 the database is stored in the /media drive. You can follow the docs which explain how to move the db to be stored in the /config directory which should fix this issue

**Comment by Beeez** [comment]
I do currently have the DB stored in the /media volume

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/opt/frigate/config.yml:/config/config.yml
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

```

frigate@frigate:/var/opt/frigate$ ls /mnt/frigate
clips  frigate.db  frigate.db-shm  frigate.db-wal  recordings

**Comment by NickM-27** [comment]
You'll want to update the config mount to mount the whole config directory and store it in /config 

https://docs.frigate.video/configuration/advanced/#database

**Comment by Beeez** [comment]
What is the reasoning behind moving the DB to a different directory, if that is the default for 0.12?

**Comment by NickM-27** [comment]
> What is the reasoning behind moving the DB to a different directory, if that is the default for 0.12?

Because having a database on HDD is not good as the latency in the head moving adds lots of delay despite the reads / writes themselves being fast enough. 

In frigate 0.13 using the /config for database instead of /media/frigate will be enforced.

**Comment by Beeez** [comment]
So I finally found the time to make this change, but still seems to have issues buffering during playback of recordings and events. 

![image](https://github.com/blakeblackshear/frigate/assets/46723579/c3becde0-aaa8-4e5d-91e8-c4dc8ea4fe50)

![image](https://github.com/blakeblackshear/frigate/assets/46723579/79c08010-2394-43dc-9793-988ac292cc77)


```  
volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/opt/frigate/config:/config
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

**Comment by NickM-27** [comment]
Okay, then this definitely seems to be an issue with your ffmpeg args in your config. You should be using ffmpeg presets for input_args (`preset-http-reolink`) hwaccel (`preset-vaapi`) and recording (`preset-record-generic-audio-aac`)

**Comment by Beeez** [comment]
Yep those are all already set

![image](https://github.com/blakeblackshear/frigate/assets/46723579/8594c8a9-6953-4a7c-a076-aeb2f2326e44)

**Comment by NickM-27** [comment]
Then I'd suggest trying to run `VACUUM` on the db

**Comment by Beeez** [comment]
Ran the following:
sqlite3 frigate.db "VACUUM;"

DB size is reduced as expected:
![image](https://github.com/blakeblackshear/frigate/assets/46723579/601020e0-9994-4f00-9df2-1de514d9b391)

Here is a video of what exactly is happening:

When a clip or recording is played, it will start, the video will stop and video continues to play, then buffers, then after buffering it resumes to a later point in the video. *Downloading the clip plays the entire clip fine

You can see this pretty much in the "Relevant log output" in my initial post. 


https://github.com/blakeblackshear/frigate/assets/46723579/89103c51-3bfa-41d2-861a-a25087e264cb

**Comment by NickM-27** [comment]
With those bases covered, this is most likely a camera issue where it is sending bad timestamps. I used to see this sometimes when I used reolink cameras.

**Comment by Beeez** [comment]
Interesting. So the timestamps that are sent by the camera can still affect the playback of those events at a later time?

**Comment by NickM-27** [comment]
> Interesting. So the timestamps that are sent by the camera can still affect the playback of those events at a later time?

to be clear by timestamps I do not mean the camera showing the time in the video feed, I am referring to PTS and DTS

**Comment by Beeez** [comment]
Yep I understood :D. Basically what my question was is that even after the event clip is created, the player is using those to sync itself? 

Would the fix possibly be a matter of syncing the server and camera time?

**Comment by NickM-27** [comment]
The streams timestamps affect how it is played back. If the timestamps are out of order or inconsistent this will cause playback issues.

**Comment by Beeez** [comment]
Thanks. I'll play around with that a bit and see if that possibly helps

**Comment by NickM-27** [comment]
Not sure which cameras they are but I found reolink could provide firmware that fixed the issue. Depending on the camera you could also try rtsp and see if it worked better but in my experience the default rtsp always had issues and required a beta firmware from support to fix rtsp

**Comment by shehzman** [comment]
Have the exact same issue with one of the Amcrest [cameras](https://www.amazon.com/gp/product/B083G9KT4C/ref=as_li_tl?ie=UTF8&tag=frigate0d-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B083G9KT4C&linkId=d76f971a9cdf9f6beb02da9864568d43&th=1) that is recommended in the Frigate docs. I've worked with @NickM-27 on Discord to try and debug the issue. The best way I could reliably get that buffer to go away was to set my camera recording stream to h265 or just use Safari since this issue only seems to happen on Chromium browsers. However, both solutions introduces a new issue where there is a split second pause almost every 10 seconds (where one clip ends and a new one starts since Frigate stores 10 second clips). I've tried lowering the frame interval in my camera to fix this, but that doesn't seem to help. Here is my current config:

`cameras:
  front:
    objects:
      track:
        - person
        - cat
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/front_main
          input_args: preset-rtsp-restream
          hwaccel_args: preset-intel-qsv-h264
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub
          hwaccel_args: preset-intel-qsv-h264
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      width: 704
      height: 480
    live:
      stream_name: front_sub

    record:
      expire_interval: 60
      retain:
        days: 0
        mode: all
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - cat
        required_zones: []
        retain:
          default: 7
          mode: motion`

NOTE: I already tried preset-vaapi to no avail.

**Comment by Beeez** [comment]
> Have the exact same issue with one of the Amcrest [cameras](f6beb02da9864568d43&th=1) that is recommended in the Frigate docs. I've worked with @NickM-27 on Discord to try and debug the issue. The best way I could reliably get that buffer to go away was to set my camera recording stream to h265 or just use Safari since this issue only seems to happen on Chromium browsers. However, both solutions introduces a new issue where there is a split second pause almost every 10 seconds (where one clip ends and a new one starts since Frigate stores 10 second clips). I've tried lowering the frame interval in my camera to fix this, but that doesn't seem to help. I also updated go2rtc to 1.7.1 and that didn't help. Here is my current config:

Wish I could say I had resolved this but I have been unable to and still have this problem. I usually just download the clip now and view it outside of the UI.
