### ISSUE TITLE
[Support]: Touchscreen monitor - Cannot exit birdseye

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#7046]
### Describe the problem you are having

Hey
So I have touchscreen monitor
When I use birdseye in full screen I not have the ability to exit I trying to tap on the screen every corner and more

I missed something?

### Version

Latest

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Not relevant

**Comment by NickM-27** [comment]
You exit just like Android says, swipe from the bottom or top to reveal the navigation buttons and then press back. 

I don't think there's much frigate can do since at that point it is system behavior.

**Comment by antonbek89** [comment]
> You exit just like Android says, swipe from the bottom or top to reveal the navigation buttons and then press back.
> 
> I don't think there's much frigate can do since at that point it is system behavior.

I forgot to mention this Ubuntu 20.04 desktop and I watch on Birdseye via web

It's look like any method like you mentioned doesn't work
