### ISSUE TITLE
Keyboard shortcuts for video navigation

### ISSUE THREAD

**Issue by justinwoodland** [blakeblackshear/frigate#7057]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use keyboard shortcuts to control video playback. 

**Describe the solution you'd like**
Similar to YouTube video navigation keys:
1. Left/Right arrow keys scrub backward/forward 5 seconds.
2. Up/Down arrow keys increase/decrease volume
3. Space bar plays/pauses
4. f key toggles full screen

Those 4 would probably be sufficient, but there are more referenced here: https://support.google.com/youtube/answer/7631406?hl=en

**Comment by NickM-27** [comment]
This has been implemented in the new UI (currently under development
