### ISSUE TITLE
Ignores Mask after short time

### ISSUE THREAD

**Issue by MassakerGU** [blakeblackshear/frigate#706]
Frigate ignores the Mask after a short time. The first few minutes after reboot it works normal. But then he trys to detect in the Mask Zone. Somebody had the issue. Would be nice if you could help me. I also recreated the Mask. 
![mask](https://user-images.githubusercontent.com/59168469/106806116-d7049b00-6667-11eb-8181-7a0b5fd1c45f.png)
![bounding](https://user-images.githubusercontent.com/59168469/106806119-d835c800-6667-11eb-9f17-465b30f6b183.png)

**Comment by blakeblackshear** [comment]
Please see the documentation on masks: https://blakeblackshear.github.io/frigate/configuration/cameras#masks

Motion masks do not prevent objects from being detected. They just prevent motion from triggering detection to run. You will need an object mask.
