### ISSUE TITLE
Audio on by default in live stream

### ISSUE THREAD

**Issue by kryllem** [blakeblackshear/frigate#7068]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to set audio on as default in go2rtc/mse live view, so I don't need to enable it every time I open or change camera.

**Describe the solution you'd like**
Add a setting to cofig file to enable audio in live stream as default.

**Comment by spacebares** [comment]
Its a "feature" for browsers to not automatically play video that has audio in it unless the audio is muted.
You can tell firefox & chrome (maybe others) to autoplay video with audio in it by clicking on the lock icon thingy...

https://github.com/blakeblackshear/frigate/assets/57186372/fdc97067-7e31-4008-89cb-565ac7b320f0

This fixes MSE autoplay & auto unmute. However it would appear webrtc remains muted... hmm

**Comment by NickM-27** [comment]
webrtc does not support this

**Comment by kryllem** [comment]
Thanks for pointing me in right direction, found those settings (autoplay, auto sound on etc) in Frigate Card.
