### ISSUE TITLE
Feature: Hikvision - Stream Encryption support

### ISSUE THREAD

**Issue by MindrustUK** [blakeblackshear/frigate#7070]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to add Hikvision Stream Encrypted cameras from Hikvision NVRs as a source so I can combine disparate CCTV sources into one location using Frigate.

**Describe the solution you'd like**
I would like Hikvision Stream Encryption to be added to the project so Hikvision NVR cameras can be supported without having to compromise on the NVR's security (Disabling Stream Encryption).

**Describe alternatives you've considered**
This may not fully fit within the Frigate project as a whole, but Frigate will be the termination point so seemed to be the best place for it to fit. This maybe something that could also fit into the go2rtc component.

**Additional context**
Disabling stream encryption will allow cameras to work but there is a shift to discourage this behaviour on Hikvision devices. Hikvision appear to document the encryption process in their SDK: https://www.hikvision.com/ca-en/support/download/sdk/ this appears to be some form of an ISAPI call to get the certificates and then combined with RTSPS.

**Comment by franciscocardoso** [comment]
Are more people interested in this feature? It would be truly great to be able to use these cameras directly in Frigate without having to disable encryption. Considering that it is even one of the recommended brands to use with this software, having this support would be highly valuable.

**Comment by acmeGR** [comment]
Yes please!!! ¨)

**Comment by kiemlicz** [comment]
Isn't the Hikvision NVR encrypting only when uploading to Hik-Connect Cloud Services?  

It should still be possible to consume local RTSP streams - which are not encrypted by the means of `Hikvision Stream Encryption`

Can someone confirm it?

**Comment by MindrustUK** [comment]
@kiemlicz the behavior is configurable, stream encryption is not forced.

However if you are connecting to Hik-Connect and transmitting RTSP streams across the public internet it makes sense to encrypt them. Unfortunately there's no way to split brain the configuration, that's to say you can't have encrypted public and un-encrypted private traffic. Not using the Hik-Connect service also limits the behavior of other features in the HikVision eco system.

After having more time to understand the problem space and based on my initial comment; this should move to the go2rtc project and away from Frigate, much as the end goal is to have Frigate interact with these devices, it makes more sense to have this functionality in go2rtc as it's principal job is ingesting all manner of streams and outputting something else.
