### ISSUE TITLE
[Bug]: "ONVIF Is not setup" is flooding the logs

### ISSUE THREAD

**Issue by Daniel-dev22** [blakeblackshear/frigate#7094]
### Describe the problem you are having

It looks like after pulling dev-f37f034 this change #6913 is causing a flood of errors in my logs. 

Onvif is not anywhere in my config file.

```
2023-07-08 12:56:08.382808250  [2023-07-08 12:56:08] frigate.ptz.onvif              ERROR   : Onvif is not setup for outdoor_1
```

### Version

0.13.0-F37F034

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
2023-07-08 12:56:08.382808250  [2023-07-08 12:56:08] frigate.ptz.onvif              ERROR   : Onvif is not setup for outdoor_1
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

Likely introduced in #6913

**Comment by NickM-27** [comment]
CC @hawkeye217

**Comment by Mareckil** [comment]
Same here: 2024-09-23 13:26:36
frigate.ptz.onvif
Onvif is not setup for ....

**Comment by hawkeye217** [comment]
If you recently installed/updated to the beta version of the Frigate card in Home Assistant, this is why you are now seeing this error. This fix from 2023 is unrelated.

**Comment by felipecrs** [comment]
@dermotduffy, I'm looking at the Frigate Card source code and I'm having difficulty to pinpoint which exact API is being called and thus throwing this error.

Do you know which one it is?

**Comment by felipecrs** [comment]
@hawkeye217, got it. It was just not released to stable yet. Thank you.
