### ISSUE TITLE
Add rewind capabilities

### ISSUE THREAD

**Issue by stephengolub** [blakeblackshear/frigate#710]
I'm absolutely loving this project. I've used several others and this is by far the most robust and well integrated into Home Assistant.

One thing that I feel would be a good add is the ability to rewind from live if you have the recordings feature enabled on a camera.

From a technical standpoint, you could create a streaming playlist in the UI and allow people to control the playback. I'm not 100% sure how you'd handle the transitions, but I believe there are already projects out there that do that type of thing (make multiple videos behave as one).

**Comment by Pingbo** [comment]
Would Like to See this Feature aswell.
Switched from Synology to frigate and really Missing the option to rewind the video
