### ISSUE TITLE
Proxmox Docker LXC [Config Support]: 

### ISSUE THREAD

**Issue by tommykmusic** [blakeblackshear/frigate#7107]
### Describe the problem you are having

Before setting up the camera I was getting a `Your config file is not valid!` issue, now that I have the camera setup with the config the logs show something different. Portainer sees the frigate container and upon starting the container it will start but the ports will disappear after a few minutes. However upon restart after setting up the config file with the camera settings the logs show the `Your config file is not valid!` error again.

### Version

latest

### Frigate config file

```yaml
Docker Config
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "32gb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/docker/portainer/frigate/config/config.yml:/config/config.yml
      - /mnt:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

Frigate Config
  GNU nano 5.4                                                                                                  config.yml                                                                                                            
mqtt:
  enabled: False

cameras:
  Test Cam: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxx.xxx.xx.xxx:554/rtsp # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 2592 # <---- update for your camera's resolution
      height: 1944 # <---- update for your camera's resolution
```

### Relevant log output

```shell
2023-07-10 16:21:17.404741529  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-07-10 16:21:17.615504441  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-10 16:21:18.621290071  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-07-10 16:21:18.853212488  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-10 16:21:19.859093737  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-07-10 16:21:20.084357885  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-10 16:21:20.516529321  curl: (7) Failed to connect to 127.0.0.1 port 1984: Connection refused
2023-07-10 16:21:20.517208013  [ERROR] The go2rtc service is not responding to ping, restarting...
2023-07-10 16:21:21.089408493  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:

IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-07-10 16:23:04.822194112  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-10 16:23:05.729716685  192.168.50.24 - - [10/Jul/2023:16:23:05 +0000] "GET / HTTP/1.1" 200 6641 "http://192.168.50.15:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
2023-07-10 16:23:05.827172711  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-07-10 16:23:06.055947714  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-10 16:23:06.187368773  2023/07/10 16:23:06 [error] 134#134: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.24, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "192.168.50.15:5000", referrer: "http://192.168.50.15:5000/"
2023-07-10 16:23:06.187412305  192.168.50.24 - - [10/Jul/2023:16:23:06 +0000] "GET /api/config HTTP/1.1" 502 559 "http://192.168.50.15:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
2023-07-10 16:23:07.061308865  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-07-10 16:23:07.266449124  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-10 16:23:08.272427403  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

### Any other information that may be helpful

I setup a privileged LXC container with turnkey linux running docker, portainer, and frigate with the 36tb zpool mounted to the lxc container under /mnt. I made the directory /var/docker/portainer/ which is where I plan to keep all my docker containers and is where the frigate container is located, /var/docker/portainer/frigate/docker-compose.yml. I also have the frigate config file under /var/docker/portainer/frigate/config/config.yml. Portainer sees the frigate container and upon starting the container it will start but the ports will disappear after a few minutes. Also the webui starts however it gets stuck with the loading circle and I can't get passed the loading screen. I also have the coral pcie version plugged in but have not yet setup the drivers for it yet.

**Comment by NickM-27** [comment]
> Is a directory: '/config/config.yml'

the config is not setup correctly and the config file does not exist at the location it is being told it exists at

**Comment by tommykmusic** [comment]
So then how exactly should that line look like? I have the config file
created and stored at /car/docker/portainer/frigate/config/ under that
config folder is where the config.yml is stored.

**Comment by NickM-27** [comment]
the file does not exist there, if I had to guess it is because the lxc config is incorrect

**Comment by tommykmusic** [comment]
That doesn't make sense as I created the file in that location? I
originally had the LXC Container as unprivileged and did a backup/restore
to change it to privileged do you think that may have affected anything?
Should I just delete the container and restart from scratch?

**Comment by NickM-27** [comment]
docker does not make mistakes in that way, if the file is not there it creates a directory because it is trying to be helpful. This is the cause of the error that is shown.

**Comment by NickM-27** [comment]
> Would that mean that docker created the location /var/docker/portainer/frigate/config in a different location?

No, it would mean that the file config.yml did not exist in `/var/docker/portainer/frigate/config/` so docker created a directory called `config.yml` at that location

**Comment by tommykmusic** [comment]
From the root when I navigate to that directory and I type `ls` only one
config.yml shows up which is the one I created use the command `nano
config.yml` if docker did create another one how would I check that?

**Comment by NickM-27** [comment]
>  if docker did create another one how would I check that?

it did, there is no question given the errors that are showing. Whatever file you are editing is not in the correct place for it to be mounted in the frigate container. This type of complication is one of the many reasons it is not recommended running complicated setups like portainer in proxmox lxc. I don't use proxmox so I can't really help past this point; you'll need to find help from someone who uses proxmox and potentially has a similar setup.

**Comment by tommykmusic** [comment]
I resolved this issue however frigate is not seeing my zfs pool that I mounted in the lxc container when I `cd /mnt/` and `ls` it shows that there are indeed folders for clips and recordings as well as all the .db files. However in the webui under storage for the location of the recordings and snapshots it shows Used 0.1 MB Total 226.50 GB. My total should be the 34TB from the mounted zpool. What am I doing wrong?

**Comment by NickM-27** [comment]
could be a filesystem issue or something weird with the way that the mount was created

**Comment by Bettman66** [comment]
I don't have ZFS, but an external USB hard drive that I integrated into Proxmox as data storage under /media/usbhdd for all LXC containers. For Frigate I created a frigate folder on the USB hard drive and mapped it to the Frigate LXC with this config.
```
arch: amd64
cores: 4
features: keyctl=1,nesting=1
hostname: frigate
memory: 8192
mp0: /media/usbhdd/frigate,mp=/media/frigate
net0: name=eth0,bridge=vmbr1,hwaddr=96:0D:2D:D7:66:99,ip=dhcp,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-105-disk-0,size=8G
startup: up=180
swap: 512
unprivileged: 1
lxc.cgroup2.devices.allow: c 120:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.mount.entry: /dev/apex_0 dev/apex_0 none bind,optional,create=file
lxc.mount.entry: /dev/apex_1 dev/apex_1 none bind,optional,create=file
```
The directory can now be seen in Frigate LXC under /media/frigate. I then provided this with this Docker Config in the Frigate Docker container as a video directory.

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    cap_add:
      - CAP_PERFMON
    devices:
      - /dev/apex_0:/dev/apex_0
      - /dev/apex_1:/dev/apex_1
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/frigate/config.yml:/config/config.yml
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
```
I think you can mount your drive the same way.
I have provided the USB hard drive in a Samba LXC as a network hard drive and can access it from any PC in the home network.

**Comment by tommykmusic** [comment]
I got my file browser container to see the zfs pool. Inside my zfs pool which I labeled `"mnt"` that has the path `/mnt/` it holds these files. we have a folder for `clips` and a folder for `recordings` as well as `frigate.db`, `frigate.db-shm` and `frigate.db-wal` 

in my docker-compose.yml file I have the media mapped to
`  - /mnt:/media/frigate` 

Should I make a folder labeled `frigate` and move the recordings folder, clips folder and .db files into the frigate folder or should I make a media folder and then put the frigate folder in the media folder with everything inside?

/mnt/media/frigate/recordings folder, clips folder and .db files

or

/mnt/frigate/recordings folder, clips folder and .db files

**Comment by NickM-27** [comment]
it is discouraged to keep the db on a network share as it can lead to issues, recommend moving that to /config or another directory. As for the main question, that is up to you and what makes more sense to you

**Comment by tommykmusic** [comment]
I tried changing the volume to

`- /mnt/media/frigate:/mnt/media/frigate` 

and it still did not work however it recreated the clips and recordings folder on the root of `/mnt/`

**Comment by NickM-27** [comment]
You should never change the right side, that is inside the frigate container

**Comment by tommykmusic** [comment]
I set it back to `- /mnt/media/frigate:/media/frigate`

and it's still not showing up

**Comment by NickM-27** [comment]
what location is nas mounted at?

**Comment by tommykmusic** [comment]
the zpool which technically is the NAS is mounted with the path `/mnt/`

**Comment by NickM-27** [comment]
okay, so then it will likely be /mnt/

**Comment by tommykmusic** [comment]
So it should be this?

`- /mnt/:/media/frigate`

Cause when I set it to that it doesn't show in the webui under storage. 

Right now it shows the storage of the drive frigate is installed on but not the zpool that I'm trying to map it to. 

Under storage in the webui is says 250gb but the zpool is 34TB if the zpool is mapped correctly then would in the webui under storage wouldn't it show as 34TB?

**Comment by NickM-27** [comment]
The left side needs to be whatever the path is to that storage on the host or inside proxmox, I have no way of knowing what that is. Wherever you put a file and it shows in the root o the zpool that is the location that you want

**Comment by tommykmusic** [comment]
Okay so that would be `/mnt/` however when I set it to that it doesn't show
in the webui under storage as bigger storage space

**Comment by NickM-27** [comment]
That's going to be an issue with the filesystem most likely then, we've seen other cases where when mounted incorrectly it shows the wrong size.

**Comment by tommykmusic** [comment]
How could it be mounted incorrectly?

**Comment by Bettman66** [comment]
If the ZFS pool can be seen in Frigate LXC under /mnt, /mnt:/media/frigate should be correct in the config.
I can only imagine that the write permissions are not correct. You can check this by creating a file without root in Frigate LXC on /mnt.

**Comment by tommykmusic** [comment]
I changed it to 

`/mnt:/media/frigate`

How would I create a file without root on `/mnt`?

I installed the file browser container in a stack in portainer and it sees /many fine
