### ISSUE TITLE
Record able to capture long then 60 seconds?

### ISSUE THREAD

**Issue by Diondk** [blakeblackshear/frigate#711]
Hi,

would it be possible to create longer video files for continues recording?
As i want to have video files with a length of atleast 5 minutes. 

Is there a setting available for this? 
As I am not able to find it on the documentation.

Kind Regards,
Dion

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/frigate/issues/697#issuecomment-772070025

**Comment by Diondk** [comment]
Thanks that worked!
