### ISSUE TITLE
Upgrade go2rtc for WebRTC stream sources

### ISSUE THREAD

**Issue by bdunn44** [blakeblackshear/frigate#7117]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to add a WebRTC stream source so I can reduce latency from my Raspberry Pi camera (uv4l-webrtc).

**Describe the solution you'd like**
I'd like Frigate to leverage go2rtc version 1.3.1 or higher. This is the version where WebRTC stream source support was added. 

https://github.com/AlexxIT/go2rtc/tree/v1.3.1#source-webrtc

**Describe alternatives you've considered**
I considered trying to hack the Docker container and upgrade it myself, but don't have time to dig into this.

**Additional context**
I would be eternally grateful :)

**Comment by NickM-27** [comment]
This is already supported https://docs.frigate.video/configuration/advanced#custom-go2rtc-version
