### ISSUE TITLE
[Support]:  Go2RTC how to update to recent version the version that comes with frigate is 1.2.0 latest 1.6.0

### ISSUE THREAD

**Issue by pbvdven** [blakeblackshear/frigate#7144]
### Describe the problem you are having

I would like to update go2rtc with the latest version with should have hls support for apple devices. instead of mse/webrtc.

Can i update go2rtc version in the frigate container some how? thanks! 

### Version

0.12.1-367D724

### Frigate config file

```yaml
not relevant
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
not relevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

not relevant

**Comment by blakeblackshear** [comment]
https://docs.frigate.video/configuration/advanced#custom-go2rtc-version
