### ISSUE TITLE
[Question]: nginx log location

### ISSUE THREAD

**Issue by skrashevich** [blakeblackshear/frigate#7146]
### Describe the problem you are having

Is there any serious reason to save the nginx (and other like go2rtc) logs in `/dev/shm` instead of, for example, `/tmp`?

### Version

0.13-dev latest

### Frigate config file

```yaml
logger:
  default: warning
go2rtc:
  #log: isn't set
```
```


### Relevant log output

```shell
``
```

### FFprobe output from your camera

```shell
``
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

``

**Comment by NickM-27** [comment]
The original PR is here: https://github.com/blakeblackshear/frigate/pull/4587

I believe it had to do with permission issues with S6 and /tmp.

**Comment by NickM-27** [comment]
@felipecrs do you remember the specific reason?

**Comment by felipecrs** [comment]
Yes, it's to avoid writing data to the sdcard in Raspberry Pis. This writes to RAM.
