### ISSUE TITLE
[Detector Support]: identify electric scooter 

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#7148]
### Describe the problem you are having

Need support to identify electric scooter in video stream .
specifically making sure no one stealing it from my house.

Can't find such on:
https://docs.frigate.video/configuration/objects/

is there an option open request to add it ?
it become so popular so i think many people will be interested ..
Thanks !
![image](https://github.com/blakeblackshear/frigate/assets/9049952/7003351a-29ee-4903-ab50-4a56c9b10796)

### Version

0.12.1

### Frigate config file

```yaml
NA
```

### docker-compose file or Docker CLI command

```yaml
NA
```

### Relevant log output

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

NA

**Comment by NickM-27** [comment]
The current model for frigate is based on the coco dataset, frigate does not control that and can't add anything. It could potentially be added to frigate+ (as in it would be possible) but support issues are not the place to discuss that.
