### ISSUE TITLE
Birdseye - Limiting how many cameras are displayed and display the camera of the last event/motion

### ISSUE THREAD

**Issue by DrSpaldo** [blakeblackshear/frigate#7189]
I would like to be able to limit how many cameras are displayed in the Birdseye view and have the option for Birdseye continue to display the camera of the last recognised motion or object detection. 

This would allow someone, for example, to have a constant Birdseye view on your second monitor (using say VLC or MPV) that displays the camera of the last recognised motion or event. Ie. Front driveway has a motion, that is the only camera that is being displayed on your second monitor until there is another motion (or event if you prefer), then that new camera is displayed until the next motion or event occurs, then it switches to that. This could have 1 camera, 2 cameras, etc.

I believe this would work well with the upcoming changes to the Birdseye auto layout in [PR 6734](https://github.com/blakeblackshear/frigate/pull/6734)

**Comment by DrSpaldo** [comment]
Additional request would also be that you can define the mode. Ie. only switch on 'person' as I assume 'object' just means everything?

**Comment by DrSpaldo** [comment]
Extra request is that the Birdseye usage is put in the System page as an other processes

**Comment by NickM-27** [comment]
Implemented in https://github.com/blakeblackshear/frigate/pull/9778

**Comment by DrSpaldo** [comment]
Thanks @NickM-27

**Comment by DrSpaldo** [comment]
@NickM-27. I am not sure if it is best in this issue, the PR thread or a new issue. But, is there a way to specify what type of birdseye mode (event) triggers? Ie. Say I only want person to change the birdseye camera, as vehicle happens to often on many cameras.

**Comment by DrSpaldo** [comment]
> No, there is an existing request for that

Ah ok. I found one that might be it, https://github.com/blakeblackshear/frigate/issues/2131 ?

**Comment by DrSpaldo** [comment]
@NickM-27 would the best option for [scaling](https://deploy-preview-9778--frigate-docs.netlify.app/configuration/birdseye#birdseye-scaling) be 1.0 if I have only 1 camera being displayed?

**Comment by NickM-27** [comment]
If you only have one camera that field won't do anything

**Comment by DrSpaldo** [comment]
@NickM-27 since I have changed Birdseye to display 1 camera only, it can change quite often depending on the motion. Sometimes it may flick between cameras 15 times in 10 seconds. So it gets a little crazy. Is there an option to make it keep the same camera view for x seconds without changing? or is this another request

**Comment by NickM-27** [comment]
Hmm, it's supposed to limit it so the camera can only change once per 10 seconds.

**Comment by DrSpaldo** [comment]
> Hmm, it's supposed to limit it so the camera can only change once per 10 seconds.

Ah ok, it’s definitely not

**Comment by DrSpaldo** [comment]
Hey @NickM-27 my Birdseye feed is still going a little crazy and changing cameras quite often. Is there a way I can send you a link or a file without posting it here to show you? Then maybe you can let me know if I should create a new issue/bug?

**Comment by NickM-27** [comment]
go ahead and make a support issue describing it, you can send a video to me at nickmowen213@gmail.com

**Comment by DrSpaldo** [comment]
> go ahead and make a support issue describing it, you can send a video to me at [nickmowen213@gmail.com](mailto:nickmowen213@gmail.com)

Done https://github.com/blakeblackshear/frigate/discussions/10836 & emailed the video clip
