### ISSUE TITLE
/<camera_name>/<label>/best.jpg returning completely black image

### ISSUE THREAD

**Issue by paularmstrong** [blakeblackshear/frigate#719]
I have plenty of events in my database matching the camera and label, but I'm getting back blacked-out images.

I'll do some more debugging soon, but wanted to record this issue so I don't forget.

**Comment by blakeblackshear** [comment]
This is expected after a restart. That is stored in memory, so if no objects have been detected since the last update, it will be black.

**Comment by paularmstrong** [comment]
Ah. I was relying on them in the web UI in the camera view as shortcuts to the events page with filters applied. Perhaps we should use something else.

**Comment by InToSSH** [comment]
I saw them too in my web UI and was wondering if it's just problem with my setup.
Perhaps the /thumbnail.jpg could be used? That should be saved to DB and should be the best image after the event ended.
