### ISSUE TITLE
Add "Bear" as an object class in Frigate+ training

### ISSUE THREAD

**Issue by jpettitt** [blakeblackshear/frigate#7215]
**Describe what you are trying to accomplish and why in non technical terms**
I'd like any new models to be able to detect bears.

**Describe the solution you'd like**
Add "Bear" as an object definition in the Frigate+ labeling system.

**Describe alternatives you've considered**
Continue to use the default model 

**Additional context**

![image](https://github.com/blakeblackshear/frigate/assets/524856/023a9e3c-2fca-46dc-8d62-7fdd5cc41faf)

**Comment by NickM-27** [comment]
This is not the correct place to request frigate+ labels

See https://github.com/blakeblackshear/frigate/discussions/1043
