### ISSUE TITLE
[Support]: Method to find the right selection/object's area

### ISSUE THREAD

**Issue by ostracizado** [blakeblackshear/frigate#7216]
### Describe the problem you are having

Is there any method to find (at least, approximately) the right area - so we can define, for instance, "min_area" or "max_area" - of any object inside a snapshot? 
At least without a rare chance or opportunity presenting themselves... that allows you to track live.

Is the value of ppp/dpi we get from the snapshot a good reference?

Take this exemple:

![Untitled-4](https://github.com/blakeblackshear/frigate/assets/78053830/79e95ab5-c012-42a4-9195-29be43673fb0)

The information from the snapshot says it has 96 ppp.

Using the selection measurement of [(4,0x96) x (9,2x96)]; the area is around: ~340.000 / and clearly wrong.
Larger samples, with a dog, for exemple, go around 59.000.
_______________________________________________

Using other method:

![Untitled-6](https://github.com/blakeblackshear/frigate/assets/78053830/5303a82c-829a-4547-8b43-12d105161dfe)

The values (even if I'm not sure if it's right) of 103x290=29.870 seem more at point.

### Version

0.12.1

### Frigate config file

```yaml
---
```

### Relevant log output

```shell
---
```

### FFprobe output from your camera

```shell
---
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo C310

**Comment by ostracizado** [comment]
Yeah, no doubt. But still.... It would have to be all up to chance.

I was thinking that if @blakeblackshear was trying some models he would not wait years so a bird, a rabbit, and so on, would pass in front of the camera. Maybe he could use older footage to define the right area's limits of any object that appeared; and work from that info.
_________________________________________

I do feel I've lost some chances to fine tune some parts of detection because I don't have a snapshot of a determined object. Say cat, for instance. I have hundreds of snapshots of a dog as... well, a dog; and as a cat (while trying to detect cats). And only one snapshot of a cat on a specific zone and perspective from X camera.
 
But if I could somewhat define a specific area, beyond using trial and error, and other objects as reference, I would not lose those chances of detection.

**Comment by NickM-27** [comment]
I'm not sure I understand what you're saying. The area is just area in pixels. It does not matter if it's a dog or a cat or a person the number is just pixels. 

Also, if you aren't having false positives there's no reason to set Min or max area. And if you did have a false positive then the objects snapshot shows you the area and you can work with that.

**Comment by ostracizado** [comment]
Yes, I understand that. 
And I think it was my inicial post that induced in error, as I don't have a snapshot from frigate. Sorry, _mea culpa_.

Using the first exemple of the cat, I have a snapshot from the camera itself as there was no detection from frigate - as it should; since I didn't set the detection of 'cat', and even if I had I would find it tricky to set an ideal area for such object.

It's because I understand that a image is flat and made of pixels that I was wondering what would be the best method to define a area for a specific object without a snapshot with the bounding box.

Say a camera view that has a large perspective, from where it stands up to 20m in front of it. I always found it tricky to set an ideal area for some objects (those that weren't first detected and give me some idea of the area, say in zone_0, zone_1, and so on); so I was wondering what method/calculation could be used, in a flat image of what the camera _sees_ , to try and find areas, somewhat near what a specific object should have, in different zones. That's why I was talking about ppp/dpi and WxH.

**Comment by NickM-27** [comment]
> Using the first exemple of the cat, I have a snapshot from the camera itself as there was no detection from frigate - as it should; since I didn't set the detection of 'cat', and even if I had I would find it tricky to set an ideal area for such object.
>
> It's because I understand that a image is flat and made of pixels that I was wondering what would be the best method to define a area for a specific object without a snapshot with the bounding box.

Right, but there is no reason to set an area at all unless you are getting false positives.

**Comment by moandcompany** [comment]
> The snapshot with bounding boxes shows the area next to the score of the object. That is the easiest to use.

I created something to help analyze this for Frigate events, but something I observed in event data was that sometimes an event's detection area value differs substantially from the bounding box captioned area for related screenshots. In these cases, the event detection area reported by Frigate was substantially lower (orders of magnitude) smaller.
