### ISSUE TITLE
docker compose config mapping

### ISSUE THREAD

**Issue by neutralvibes** [blakeblackshear/frigate#7220]
**Describe what you are trying to accomplish and why in non technical terms**
## Starting frigate via `docker compose`
Starting frigate via `docker compose` using the method in the installation guide [here](https://docs.frigate.video/frigate/installation#docker). The container will fail to run.

From the docs yaml excerpt:-

```yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/config.yml:/config/config.yml # Problem line
```

## Volume to file mapping
The issue is the direct mapping of a volume to a local file, in this case `config.yml`.  If the file does *not* already exist when starting the service, docker will create a  `folder` of that name. This can cause confusion to those not aware of this docker `feature` as a folder with that name is valid, while a listing might fool you into not realising what you are looking at for a time, but of course frigate is expecting a file so correctly rejects it. Docker then repeatedly tries to restart the service to no avail.

**Describe the solution you'd like**

I propose the following:- 

```yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/config:/config # Just map the local `config` folder docker can create locally if it needs to.
```

If a config.yml file does **not** exist in the config location frigate can create an empty one, or better still one with all the annotations, as shown in the docs.

It also mentions in the docs the ability to upgrade the version of `go2rtc` used. Without changing the mapping directly from the yaml file to the config folder as previously described, this of course will never work in docker land without yet another mapping. The method proposed may allow for updates to any other future utilities and or related configs.

**Describe alternatives you've considered**

A cheap alternative is to update the docker based docs to highlight the issue. The issue upgrading of `go2rtc` will remain.

> The config.yml file **must** exist before starting the service. You can begin with an empty one. If a file does not exist at the time of starting the service. Docker will create a folder of that name, which you will have to remove, before creating the file.

**Additional context**

**Comment by NickM-27** [comment]
This change has already been made for 0.13 due to unrelated changes for the default location of the database file as /config/frigate.db 👍
