### ISSUE TITLE
[Camera Support]: setting fps

### ISSUE THREAD

**Issue by Bomberski** [blakeblackshear/frigate#7223]
### Describe the problem you are having

I set my detect at 10 fps like the picture but it also sets my Capture/record the same

Can I set it the same way as detect?

![Screenshot_20230719_122648_Samsung Internet](https://github.com/blakeblackshear/frigate/assets/51887282/ae95300b-7f8c-4b74-bdee-7e0e6b37a682)

![Screenshot_20230719_123013_Samsung Internet](https://github.com/blakeblackshear/frigate/assets/51887282/0abc55b3-6f1c-48ac-9c0e-bdc502f8f232)

I may have misunderstood the docs 

### Version

Current 12.1

### Frigate config file

```yaml
Pictures
```

### Relevant log output

```shell
Na
```

### FFprobe output from your camera

```shell
Na
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Reolink

**Comment by NickM-27** [comment]
This is incorrect, `capture` is not related to record at all, it will not set the fps of the recordings as frigate directly copies the recordings from the camera

**Comment by Bomberski** [comment]
Thank you.
