### ISSUE TITLE
[Support]: Is Github hiding posts by new users?

### ISSUE THREAD

**Issue by tv21** [blakeblackshear/frigate#7224]
### Describe the problem you are having

This is partly a test to confirm my suspicion - I have had a Github account for quite a while and I will bet this issue appears.  A family member (who does not live with me) said that he created a Github account so that he could report an issue he is having with Frigate.but even though he can see the issue he posted, when I go to the link (https://github.com/blakeblackshear/frigate/issues/7214) all I get is a 404 page.  He also said that he tried to respond to another user that was having an issue, that he knew the fix for, and apparently no one can read that but him and then only when he is logged in.  So I am asking so I can report back to him, does Github block posts from new accounts, or hold them in some kind of queue until they are manually approved or something?

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
I get a 404 when trying to view #7214 as well which is very weird. I believe there was one other user who had something like this and it was because their account was flagged by GitHub and they had to talk to GitHub support to get it waived

**Comment by tv21** [comment]
He tried to contact GitHub and apparently now you have to enable 2FA to even talk to them.  If you have ever given any though to moving this project to a GitHub alternative, or alternately opening a separate discussion forum for Frigate independent of GitHub, I now think either of those might be good ideas (really for anyone with a project on GitHub).
