### ISSUE TITLE
[Feature Request] Model Evaluation Tool

### ISSUE THREAD

**Issue by madsciencetist** [blakeblackshear/frigate#7226]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to compare detectors/models in order to choose the best for my setup. I frequently read user comments to the effect of "I tried switching from mobilenet to yolo, and I think the performance is different, but I can't tell if it's better or worse". While each publicly-available model typically has published precision-recall curves or F1 or AP scores on the COCO dataset, comparing literature results can be insufficient for the user for a number of reasons:
- The COCO dataset in not representative. A public security-camera dataset would be better. A self-labeled dataset from the user's own cameras would be best.
- I would like to be able to evaluate the effect of motion detection parameters on detection performance. Not only can the motion detector prevent images from reaching the detector, but by sending the detector only the region of motion, it changes the relative size of the objects, which can affect model performance.

**Describe the solution you'd like**
The end result should be a user-runnable script that inputs a set of models & motion detector parameters and outputs a precision-recall curve for each. That would show the user which model to choose and the effect of the confidence threshold parameter.

Ideally, an existing public labeled dataset exists composed of home security camera video. This would be sufficient for most users and would help developers tune for the general case. I have not been able to find such a dataset (but maybe frigate+ has it?), so I instead propose a way to label one's own data with minimal effort. Instead of labeling (or even reviewing) all images manually, we can just label the images in which the different detectors disagree. Excluding all data in which the detectors agree will shift the PR curves but will maintain their relative ordering. It could be implemented as follows:
- Create dataset:
    - Use user's recordings directory as the input video. Depending on their recording configuration, this will include a mix of interesting and uninteresting video, where the former is more efficient for evaluation but may be biased by excluding objects that frigate's configured motion/object detector did not detect.
    - Detect with all detectors on all frames, where a "detector" is a given combination of motion + object detector.
        - For each detection, output {frame, bounding_box, class, confidence, detector} to DB
    - For each object class:
        - Created sorted list of all detections by confidence, descending
        - For each detection:
            - For each alt_detector != detection.detector:
                - Is there an alt_detector detection in the same frame & class, with bounding_box IOU > 0.5?
                    - If yes, confidence_difference = detection.confidence - alt_detection.confidence
                    - If no, confidence_difference = detection.confidence - 0
                - Append detection w/ confidence_difference to list of detection_differences
- Label dataset:
    - Sort detection_differences by confidence_difference, descending
        - For each detection difference:
            - Show user the object detection and ask if it's correct -> create truth label
            - With each successive user label, the confidence_difference shrinks, approaching a point of diminishing returns. Allow user to stop labeling at any point, but ideally allow them to resume later.
- Plot:
    - For each detector:
        - For confidence threshold = [0, 1]
            - Compute precision & recall of truth labels over all images/classes
        - Plot PR curves

**Describe alternatives you've considered**
I am mainly hoping that someone can point out a python library or standalone tool that already does the above, or something similar. I have to assume that comparing object detectors is a common ML task, but I don't work with them enough to know. For example, Prodigy provides a UI to review and correct existing bounding box annotations, but I want to avoid any implementation that requires the user to manually review all images.

**Additional context**
What existing Frigate code can/should be leveraged? What standard practices and formats should be used? Is dataset balancing required? Is it sufficient to focus on the model differences instead of their absolute performance, or are the resultant PR curves too misleading?

**Comment by NickM-27** [comment]
Just wanted to note frigate already has a [motion benchmarking tool](benchmark_motion) and [clip processing tool](benchmark_motion) though it won't be super user friendly to run for novices, mainly for developer debugging.

I believe some of these things have been said will be a part of Frigate+, like the ability to compare different Frigate+ models on a specific users cameras. In general though, some parts of this sound (IMO) like a completely separate project / endeavor and not something that fits directly within the AI NVR umbrella.

**Comment by ColColonCleaner** [comment]
@NickM-27 what is the expected timeline for frigate+. I'm on the default coral model provided by frigate and the detection is not great. I'm excited for the paid models but not sure when that's going to happen.
I went down the route of researching other models that would run on the coral but all routes i chose ended in failure so I'm back to the default model.

**Comment by NickM-27** [comment]
I believe general availability will be coming alongside 0.13 release

**Comment by ColColonCleaner** [comment]
@NickM-27 Great to hear! Any anticipated time for that release?

**Comment by NickM-27** [comment]
When everything is checked off the list https://github.com/blakeblackshear/frigate/pull/6262 and then the beta release cycle finishes
