### ISSUE TITLE
[Support]: Please Update the Go2RTC to latest version 1.6.1

### ISSUE THREAD

**Issue by wes1993** [blakeblackshear/frigate#7231]
### Describe the problem you are having

Hello,
when is programmed the update on the go2rtc to latest version, 1.6.1? WIth the latest version we have support for DVR163/Eseecloud cameras.

Another question, it's possible to use only Go2RTC for connecting to the cameras and processing the video? because FFMPEG have some bug but in Go2RTC the problem is not present infact the CPU usage in 1% instead of Frigate with FFMPEG and detect disabled (80/90%).

Best regards
Stefano

### Version

Frigate (0.12.1-367d724)

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

DVR163

**Comment by NickM-27** [comment]
> @NickM-27 thanks a lot for you reply :-D I have seen, when i try to start Frigate, that Go2RTC is on version 1.2.0:
> 
> ![image](https://user-images.githubusercontent.com/52070589/254892299-e93b296e-a561-4147-87ff-fff8c5485b50.png)

The version with updating go2rtc hasn't been released yet, it has always been possible to use whatever version you want https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

> So we can't tell Frigate to use Go2RTC for accessing the video stream instead of directly to the Cam?

Of course you can, this is covered in the docs, but it won't reduce CPU usage in the way that you were suggesting.

**Comment by wes1993** [comment]
OK thanks a lot @NickM-27
