### ISSUE TITLE
[Support]: How can I extend the length of all events?

### ISSUE THREAD

**Issue by amdhunter** [blakeblackshear/frigate#7249]
### Describe the problem you are having

I am looking to understand the pre and post capture settings in Frigate.  I understand that pre/post is for events, but what about general motion?  I would like to capture more upon motion (just in case the model doesn't properly detect), not just events.  Is there a way to do this?

### Version

0.12.1-367D724

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

### Network connection

Wired

### Camera make and model

All

**Comment by NickM-27** [comment]
That's what 24/7 recording is for. Just set the 24/7 recording retention mode to motion

**Comment by amdhunter** [comment]
> That's what 24/7 recording is for. Just set the 24/7 recording retention mode to motion

I have that set up, I just would like a longer motion recording if possible.  Similar to how pre and post works for events.   I would rather not move to true 24/7 recording if I can help it.

**Comment by NickM-27** [comment]
It's not clear that you mean by longer motion recording. The 24/7 with recording mode keeps every single 10 seconds segment that contains motion. The only recordings that won't be kept are ones where nothing happened

**Comment by amdhunter** [comment]
> It's not clear what you mean by longer motion recording. The 24/7 with motion recording mode keeps every single 10 seconds segment that contains motion. The only recordings that won't be kept are ones where nothing happened

I see what you mean, and I wasn't aware that's how it worked.  That makes sense and will be fine for my use case.  My problem is, some of my cameras, in certain lighting conditions don't pick up events very well.  I am trying to make sure I at least have the data, even if I need to manually look through motion generated recordings to find what I am looking for.

**Comment by NickM-27** [comment]
Right, that is one of many reasons it's a good idea to keep 24/7 motion recordings along with events.
