### ISSUE TITLE
Export Recordings API does not accept float values (ex: when using start / end time from event)

### ISSUE THREAD

**Issue by PovilasID** [blakeblackshear/frigate#7280]
**Describe what you are trying to accomplish and why in non technical terms**
I want to use export API to export event clips and they start and end floats (sub point values probably revering to seconds) and API accepts only integers

**Describe the solution you'd like**
/frigate/http.py edited to accept floats 
Starting line 1606 
```python
@bp.route("/export/<camera_name>/start/<start_time>/end/<end_time>", methods=["POST"])
def export_recording(camera_name: str, start_time: float, end_time: float):
    playback_factor = request.get_json(silent=True).get("playback", "realtime")
    exporter = RecordingExporter(
        current_app.frigate_config,
        camera_name,
        float(start_time),
        float(end_time),
        PlaybackFactorEnum[playback_factor]
        if playback_factor in PlaybackFactorEnum.__members__.values()
        else PlaybackFactorEnum.realtime,
    )
    exporter.start()
    return "Starting export of recording", 200
```
Not sure if it that easy though...

**Describe alternatives you've considered**
Truncating clip timestamps to ints.

**Additional context**
I would have tested it myself but while building a core dev container I got some error that it was unable to build Tensor models and it's late

**Comment by NickM-27** [comment]
The values are timestamps, so as an int it already has seconds-level granularity

**Comment by NickM-27** [comment]
I see the main issue is you are using the values from an event and it doesn't work because it doesn't support floats (which are for milliseconds)
