### ISSUE TITLE
Frigate Plus - Delete images and annotation limitations

### ISSUE THREAD

**Issue by veinoffeeling** [blakeblackshear/frigate#7304]
### Describe the problem you are having

I see no way to delete images from here. I would like to delete ones that I uploaded and assigned to the wrong camera during testing. Also, the options for labels is very limited and I would like to be able to choose more options (bird, squirrel, etc)

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

not relevant

**Comment by NickM-27** [comment]
This is not the right place to talk about Frigate+, that would be #1043

**Comment by veinoffeeling** [comment]
> This is not the right place to talk about Frigate+, that would be #1043
My apologies, thanks for pointing me in the right direction!
