### ISSUE TITLE
scheduled export with specific configuration for timelapse/realtime video

### ISSUE THREAD

**Issue by tomhub** [blakeblackshear/frigate#7312]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to make schedule to export timelapse for each camera, ex. at 6:00 start export of timelapse for the last 24 hours for each camera separately

**Describe the solution you'd like**
scheduled exports of timelapses for the last 24 hours.

**Describe alternatives you've considered**
API to access and create timelapse exports

**Additional context**

**Comment by NickM-27** [comment]
You can already use the API for this with a simple cron job / script
