### ISSUE TITLE
[Feature Request] Save-a-clip

### ISSUE THREAD

**Issue by apaperclip** [blakeblackshear/frigate#732]
Sometimes frigate will record a clip that I would like to save and not have it purged, It would be nice if there was a UI and maybe even an API and/or MQTT topic to save the clip of a specific event.

Just a bunch of thoughts for consideration

- A save/retain flag so the regular purge doesn't remove them
- The flag could be toggled
- The file could be copied to a different location outside the clips folder
- The file could have a download link (right now right-click on the video and triple dot option works)
- Related event data, or the event itself could also be saved
- Event list would indicate that it and/or the clip is marked save/retain
- This flag could be filtered on in the event list

Thanks!

**Comment by drinfernoo** [comment]
Possible duplicate of: https://github.com/blakeblackshear/frigate/issues/615?

**Comment by apaperclip** [comment]
ha! pretty much - i even searched albeit not very well..  thanks.   I'll colse this and move my content to a reply to yours.
