### ISSUE TITLE
Error parsing config: 'mqtt'

### ISSUE THREAD

**Issue by eyal-h** [blakeblackshear/frigate#735]
I have installed frigate and it worked perfect.
today after update to 1.60 i am getting this error
I have reset everything to default and still getting this error
* Starting nginx nginx
   ...done.
Error parsing config: 'mqtt'

**Comment by pdecat** [comment]
See #703

**Comment by blakeblackshear** [comment]
See solution here: https://github.com/blakeblackshear/frigate/issues/703#issuecomment-775614444
