### ISSUE TITLE
[Support]: Configuring the Home Assistant Integration with an HTTPS URL Using a Self-signed Cert

### ISSUE THREAD

**Issue by rosstroha** [blakeblackshear/frigate#7353]
### Describe the problem you are having

When trying to setup the Home Assistant integration, I am unable to use an HTTPS url with a self-signed certificate.

I don't want to expose my Frigate instance to the internet so I'm providing a self-signed cert to the proxy.

Is there a way to configure the integration so that it doesn't try to verify the certificate?

### Version

0.12.1-367D724

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
Error fetching information from https://frigate.troha/api/stats: Cannot connect to host frigate.troha:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate-hass-integration would be the correct repo for this issue
