### ISSUE TITLE
 Unable to connect to MQTT server: [Errno -2] Name or service not known (Release-0.8.1)

### ISSUE THREAD

**Issue by thanif** [blakeblackshear/frigate#736]
![error](https://user-images.githubusercontent.com/32266960/107218744-db4b0280-6a31-11eb-91d4-28e1c7fed577.png)

![config yml](https://user-images.githubusercontent.com/32266960/107218919-2238f800-6a32-11eb-8efb-6043e23d5ef5.png)
![docker-compose yaml](https://user-images.githubusercontent.com/32266960/107218925-249b5200-6a32-11eb-8664-57120ee836ab.png)

**Comment by blakeblackshear** [comment]
You have to specify your mqtt server. `mqtt.server.com` is just a placeholder.

**Comment by thanif** [comment]
@blakeblackshear , Can you guide me on how to setup mqtt server?

**Comment by InToSSH** [comment]
> @blakeblackshear , Can you guide me on how to setup mqtt server?

If you use Home Assistant, you can install the official addon.
If not, you can either use docker image or install it directly on your ubuntu machine.

Here is a guide for Docker: [https://blog.feabhas.com/2020/02/running-the-eclipse-mosquitto-mqtt-broker-in-a-docker-container/](https://blog.feabhas.com/2020/02/running-the-eclipse-mosquitto-mqtt-broker-in-a-docker-container/)

Here is guide for Ubuntu: [https://www.vultr.com/docs/how-to-install-mosquitto-mqtt-broker-server-on-ubuntu-16-04](https://www.vultr.com/docs/how-to-install-mosquitto-mqtt-broker-server-on-ubuntu-16-04)

There is a plenty of guides online, so it's as easy as using Google :)

**Comment by jlaitinen81** [comment]
Should the mqtt server be on the same system as Frigate? I pointed the mqtt server in the config.yml to a Mosquitto MQTT broker on my HA instance, which is on another machine than the Frigate.

Frigate runs on a Debian Docker, HA on a NUC with HA OS and Frigate integration via HACS.

These 2 systems do not talk to oneanother currently and I am trying to find a solution...

**Comment by InToSSH** [comment]
@jlaitinen81 no, they don't have to be on the machine, as long as their are either on the same network (subnet) or different subnets which are routed together. It is just a connection to a port, same as HTTP, so as long as one machine can "see" the other on the network, it should work.

I am also using the Mosquitto addon on HA, which is running on Debian VM and docker.. and Frigate is directly on my Synology DSM Docker.
I would suggest downloading something like MQTT Explorer for Windows and trying to connect to your Mosquitto server with this app to see if you have ports exposed in your addon. 
Do you have already anything else connected to your broker which is working and is not on the same machine?
