### ISSUE TITLE
[Support]: Snapshots on demand

### ISSUE THREAD

**Issue by alfwro13** [blakeblackshear/frigate#7360]
### Describe the problem you are having

Is it possible to manually take a snapshot and save it as png file?
In my media/frigate/clips folder I can see that snapshots are saved as both jpg and png files so I know saving as png is possible.
Thanks

### Version

0.12.1-367D724

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

anpviz ipc-d250w

**Comment by NickM-27** [comment]
There is no API for this currently, and it wouldn't make sense to put it in the clips folder because frigate doesn't know it exists there so it would never get cleaned up. 

There could be an API to get / download it though like for snapshot.jpg, latest.jpg

**Comment by alfwro13** [comment]
Thanks for confirming that.
Ideally it would be nice if there was a frigate HA service to take a snapshot where you can specify file format (i.e. png or jpg) and file location/name.

**Comment by NickM-27** [comment]
> Thanks for confirming that. Ideally it would be nice if there was a frigate HA service to take a snapshot where you can specify file format (i.e. png or jpg) and file location/name.

You can already do that in HA

**Comment by alfwro13** [comment]
yes, but only as jpg file
