### ISSUE TITLE
[FR] Web UI - MQTT websocket real-time updates

### ISSUE THREAD

**Issue by InToSSH** [blakeblackshear/frigate#737]
Hi,
this will be mostly for @paularmstrong and just an idea for the future.
I was thinking since we now have nice Web UI and a lot of people don't use it with HA or other system it would be great to have some kind of real-time dashboard with current events, possibly even notifications (just in-page with sound perhaps, not HTML5 as it would require external access and HTTPS) and it could grab the events using JS MQTT websocket client, without any additional work on the backend. This would make this project completely standalone for people who don't use or need any other system to connect this with.

**Comment by paularmstrong** [comment]
I'm going to move this to a discussion. I agree that it's probably what we should do, but there are a bunch of considerations to deliberate first.
