### ISSUE TITLE
[Support]: run on port 80 instead of 5000

### ISSUE THREAD

**Issue by nomonkeynodeal** [blakeblackshear/frigate#7386]
### Describe the problem you are having

I would like to run the container on port 80. Usual tricks are not working. Is there a way to do this? I don't understand why people are ok with memorizing hundreds of random port numbers for their containers.

### Version

latest stable

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
You can't, ports below 1024 are reserved for the root user only. In this case it would interfere with unraids own http frontend. There is no need to memorize the port, you can easily setup nginx to have domains or just use unraids webui button to open the webui which already knows the port

**Comment by nomonkeynodeal** [comment]
> You can't, ports below 1024 are reserved for the root user only. In this case it would interfere with unraids own http frontend. There is no need to memorize the port, you can easily setup nginx to have domains or just use unraids webui button to open the webui which already knows the port

What? I run all of my dockers on port 80 on their own domain.

**Comment by NickM-27** [comment]
> What? I run all of my dockers on port 80 on their own domains.

we are talking about different things, I am referring to the docker port mapping 80:5000, that would not work and would conflict with unraid.

Running via a proxy is separate, you can easily map port 5000 to whatever you want via docker and then use nginx to have a custom domain for it.
