### ISSUE TITLE
[Feature Request] alternative streaming option for Dahua cameras

### ISSUE THREAD

**Issue by lewisxy** [blakeblackshear/frigate#7388]
**Describe what you are trying to accomplish and why in non technical terms**
Add support to stream from Dahua camera using proprietary protocol. The proprietary protocol sometimes have lower latency than RTSP (especially for wireless cameras).

**Describe the solution you'd like**
I already implemented the streaming tool in C++ that is compatible with `ffmpeg`. See https://github.com/lewisxy/dhstream

However, I only have access to very limited models of Dahua cameras, and I am not very familiar with the `frigate` code base. Further testings are welcome and appreciated.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lewisxy** [comment]
Any update on this topic?

**Comment by NickM-27** [comment]
Personally I'd like to see more data to present the benefits of this. While it is good that it works with ffmpeg, it would be another dependency and something else that needs to be maintained. It would also add additional complexity to the config. If there is no clear and worthwhile benefit to supporting it then I don't see a reason for it.

It is also not clear what is meant by wireless cameras. If this means truly wireless battery powered cameras then I don't think that is a concern since Frigate is not meant to work with those kinds of cameras.

**Comment by lewisxy** [comment]
> Personally I'd like to see more data to present the benefits of this. While it is good that it works with ffmpeg, it would be another dependency and something else that needs to be maintained. It would also add additional complexity to the config. If there is no clear and worthwhile benefit to supporting it then I don't see a reason for it.

I can do a bit more testing when I got time, but I as I mentioned above, I only have access to a very limited collection of Dahua cameras, so I don't think the test result provided by myself alone would do justice. That being said, a fair reference would be to compare to Dahua's own app such as [SmartPSS][smartpss] (on computer) or [DMSS][dmss] (on mobile), which utilizes the same underlying networking library as my implementation.

> It is also not clear what is meant by wireless cameras. If this means truly wireless battery powered cameras then I don't think that is a concern since Frigate is not meant to work with those kinds of cameras.

By wireless, I mean those IP cameras using WiFi (as opposed to using Ethernet cable) as a transmission medium. Like traditional IP cameras, using WiFi does not mean relying on access to the Internet. Dahua did have a few models using WiFi, in particular from their rebranded partners such as Amcrest and IMOU. I mentioned this due to the different network condition of using WiFi vs Ethernet cable. WiFi network tend to have higher packet loss than wired network. Dahua's proprietary protocol might be able to better deal with these kind of losses than RTSP.

[smartpss]: https://us.dahuasecurity.com/product/smartpss/
[dmss]: https://software.dahuasecurity.com/en/dmss
