### ISSUE TITLE
frigate as binary sensor switches constantly between online and offline 

### ISSUE THREAD

**Issue by jalbstmeijer** [blakeblackshear/frigate#74]
setting this for each binary_sensor, fixes this for me. Found here https://community.home-assistant.io/t/tasmota-mqtt-switches-repeatedly-marked-as-unavailable/46935

```
    payload_available: ‘online’
    payload_not_available: ‘offline’
```
Does this mean HA and frigate defaults have a mismatch?

```
frigate/detect_objects.py:        client.publish(MQTT_TOPIC_PREFIX+'/available', 'online', retain=True)
frigate/detect_objects.py:    client.will_set(MQTT_TOPIC_PREFIX+'/available', payload='offline', qos=1, retain=True)
```

**Comment by blakeblackshear** [comment]
I have seen this happen for other users if they have multiple instances of frigate running at the same time.

**Comment by blakeblackshear** [comment]
I don't think so. Frigate registers using a single client ID with the mqtt server. You can't run multiple instances without separate client IDs. https://github.com/blakeblackshear/frigate/blob/master/detect_objects.py#L39

Do you have multiple Google Coral devices?

**Comment by jalbstmeijer** [comment]
Yes, got 2 raspberry's with Google Coral in two different locations, processing the local camera streams.

**Comment by blakeblackshear** [comment]
That works. Ideally it would be set in the config file with a default.
