### ISSUE TITLE
Historical Debug

### ISSUE THREAD

**Issue by therealeldaria** [blakeblackshear/frigate#7405]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to historically see what triggered an event so that I can find out why it started recording when there was nothing in the recording. 

**Describe the solution you'd like**
The same way it is possible to Live Debug and see bounding boxes, etc. It would be nice to do the same on a recording.
For example I frequently get a detection at night, but I have not been able to figure out what is triggering it.

**Describe alternatives you've considered**
None, except perhaps adding a virtual camera to the config that plays the clip and then view that through the live debug. Not sure how I would do that.

**Additional context**
N/A

**Comment by NickM-27** [comment]
This is already implemented for 0.13
