### ISSUE TITLE
Unique object identifiers for detected objects in events and notifications

### ISSUE THREAD

**Issue by irakhlin** [blakeblackshear/frigate#7406]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have frigate set a unique object identifier on detected objects that would allow distinction of whether or not a new unique object has entered a specific zone(s), instead of whether or not just an object of that specific type has entered those zones. This would allow generating a notification when a unique object has entered a specific zone or list of zones.

**Describe the solution you'd like**

Looking at the attached camera as an example:
red: road
green: top_of_driveway
orange: bottom_of_driveway
red: road

The idea here was to be able to trigger a notification when a 'car' object has been detected in the road, top_of_driveway and bottom_of_driveway zone, ie ignoring cars driving by but only trigger when someone pulls into the driveway. Unfortunately this is not how I am seeing frigate react on notifications, instead a car driving by will trigger as an event where a "car" object has been detected in all 3 zones as there are obviously parked cars in the other two zones.

I am assuming (I am still looking at the code so please let me know if this assumption is incorrect), when a new object is detected ie car, some sort of id is already generated, if so could this id be sent along with the object type and "entered" zone list for the notification?

**Describe alternatives you've considered**
The original idea with the camera example I provided was that the orange zone (bottom_of_driveway) was the "triggering" zone for a notification and cars would not be in that zone other than when they are entering the driveway, as you can see from the photo this is not always possible and not always practical. 

**Additional context**

![snapshot](https://github.com/blakeblackshear/frigate/assets/12637936/ed02749d-aaed-45d1-86f7-2104403c2bf4)

**Comment by NickM-27** [comment]
This is already supported with the /events mqtt topic https://docs.frigate.video/integrations/mqtt#frigateevents

**Comment by irakhlin** [comment]
> This is already supported with the /events mqtt topic https://docs.frigate.video/integrations/mqtt#frigateevents

@NickM-27 this is what I am currently using, but I was under the impression that the id value is the value of the event, is this not the case? Is the id actually the value of the specific object?

**Comment by NickM-27** [comment]
"event" and tracked object are the same thing. The I'd is for that particular tracked object (which is also an event)
