### ISSUE TITLE
Frigate AddOn only visible in Menu when user is administrator

### ISSUE THREAD

**Issue by buhito81** [blakeblackshear/frigate#7419]
**Describe what you are trying to accomplish and why in non technical terms**
I want to the Frigate AddOn only visible in Menu when user is administrator.

**Describe the solution you'd like**
https://developers.home-assistant.io/docs/add-ons/configuration#optional-configuration-options 

<html>
<body>

panel_admin | bool | true | Make the menu entry only available to users in the admin group.
-- | -- | -- | --

</body>
</html>

**Comment by NickM-27** [comment]
This is the wrong repo for this request https://github.com/blakeblackshear/frigate-hass-addons
