### ISSUE TITLE
Change cameras structure in /config API

### ISSUE THREAD

**Issue by httpedo13** [blakeblackshear/frigate#7420]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to decode automatically, with swift, the cameras entity without knowing the name of the cameras.

**Describe the solution you'd like**
Convert the structure of the `cameras` in json file in an array of cameras: 

Now:
```
cameras: {
  firstcamera: {
    name: "firstcamera"
  },
  secondcamera: {
    name: "secondcamera"
  }
}
```

What I propose:
```
cameras: [
  {
    name: "firstcamera"
  },
  {
    name: "secondcamera"
  }
]
```

**Comment by NickM-27** [comment]
The API response is generated directly from the yaml configuration, so changing this would require changing the config for all users as well as refactoring the codebase.
