### ISSUE TITLE
HTTP Api for detect, recordings and snapshots

### ISSUE THREAD

**Issue by httpedo13** [blakeblackshear/frigate#7429]
Hi, it is possible to create the api for enable disable detect, recordings and snapshots like the MQTT version?
`frigate/<camera_name>/detect/set`
`frigate/<camera_name>/recordings/set`
`frigate/<camera_name>/snapshots/set`
`frigate/<camera_name>/detect/state`
`frigate/<camera_name>/recordings/state`
`frigate/<camera_name>/snapshots/state`

Furthermore, why the http API doesn't have a security system like jwt token?
Thanks!

**Comment by NickM-27** [comment]
This can be done via websocket as well as mqtt. http isn't really a good place for it because it does not contain the current state as well as the state that has been set.

**Comment by httpedo13** [comment]
Okay, thanks! So, why the http API doesn't have a security system like jwt token?

**Comment by NickM-27** [comment]
> So, why the http API doesn't have a security system like jwt token?

See https://github.com/blakeblackshear/frigate/issues/1726#issuecomment-1472147836
