### ISSUE TITLE
[Config Support]: Format to combine vehicle labels

### ISSUE THREAD

**Issue by amdhunter** [blakeblackshear/frigate#7431]
### Describe the problem you are having

I want to combine the default labelmap "car" and "bus".  Sometimes UPS and Fedex get recognized as one or the other.  I can't seem to figure out the remapping of the labelmapping to add it to my config.  The config in the docs shows this:

  labelmap:
    2: vehicle

How do I go about this?  I can't find the labelmap.txt file to find the number I would use to remap, so I am coming here for some advice.

I am using OpenVINO for detection, if that matters here.

### Version

0.12.1-367D724

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

**Comment by NickM-27** [comment]
The openvino labelmap is https://github.com/openvinotoolkit/open_model_zoo/raw/master/data/dataset_classes/coco_91cl_bkgr.txt

**Comment by amdhunter** [comment]
Thanks, so would that mean I would format it like this to rename bus (line 7) to car?

  labelmap:
    7: car 
    
 Could I then do this to rename all vehicle types to vehicle?
 
   labelmap:
    4: vehicle
    5: vehicle
    7: vehicle
    9: vehicle

**Comment by NickM-27** [comment]
I believe so but not 100% sure, it may be 0 indexed

**Comment by amdhunter** [comment]
I'll try it and see.  If it is, I can shift the numbers no problem.  Will this break current object detections that are in the database now?

**Comment by NickM-27** [comment]
It will mean that the old labels won't show up in the filters in the webUI but it won't break anything in the DB

**Comment by amdhunter** [comment]
Got it.  Thank you!

**Comment by amdhunter** [comment]
After making the change I see no change in the UI, is there a way to confirm that it did or didn't work?  I assume also I would need to change the tracked objects on cameras from car and bus to vehicle, if I can get this working?

**Comment by NickM-27** [comment]
besides changing the labelmap feature you also need to change the `objects -> track` config to match the new labels

**Comment by amdhunter** [comment]
I thought so.  Would this fail, if the labelmap was not correct (since I'm not sure if it's 0 indexed or not), or would it fail silently?

**Comment by NickM-27** [comment]
no it won't fail, but the UI (like the labels that are shown) will change. Need to make sure to refresh after restarting frigate though

**Comment by amdhunter** [comment]
Gotcha, thanks for the help.
