### ISSUE TITLE
[Support]: Frigate does NOT completely uninstall

### ISSUE THREAD

**Issue by reotto613** [blakeblackshear/frigate#7449]
### Describe the problem you are having

I uninstalled Frigate, and I am now seeing the following in my HAOS Supervisor Logs:

23-08-11 13:27:39 WARNING (SyncWorker_4) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate (Full Access) Beta (0.12.0)

### Version

0.12.0

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
This is not the right repo for this issue, should be reported to https://github.com/blakeblackshear/frigate-hass-addons
