### ISSUE TITLE
Birdseye: option on how to lay-out cameras.

### ISSUE THREAD

**Issue by futuredj** [blakeblackshear/frigate#7466]
**Describe what you are trying to accomplish and why in non technical terms**
In my case, I am streaming birdseye to a monitor mounted vertically so the resolution is 1080x1920. If I had the option to have the second camera appear below the first rather than to the right of it, it would solve my problem. Currently, when movement is detected, the second camera appears to the right of the first making both cameras really small and leaving a big empty space below.

**Describe the solution you'd like**
I think it would be nice to have a bit more customizability to birdseyes layout in general. Pick positions of certain cameras? Preferred order to show them in? Have a camera bigger than the others? Play audio when certain objects are detected? The possibilities could be endless with this software...

**Describe alternatives you've considered**
I have already set one of my cameras to always show in birdseye and I have used go2rtc in frigate config to restream birdseye with the audio of one of the cameras.

**Comment by NickM-27** [comment]
Birdseye has been rewritten for 0.13 to include an auto layout functionality as opposed to the current grid layout. It also always ordering of the cameras in birdseye. 

A manual layout is covered by https://github.com/blakeblackshear/frigate/issues/5424
