### ISSUE TITLE
PTZ  Auto Tracking without RelativePanTilt FOV

### ISSUE THREAD

**Issue by kennethgomez01** [blakeblackshear/frigate#7504]
For most, just playing around with the dev branch and looking to see if my current PTZ camera are.capable to work with auto tracking, as surprise it says it does not have RelativePanTilt FOV. Is it possible to allow cameras without this, as my camera is clone Hikvision which support auto tracking Pan/Tilt/Zoom for Human, but luck of Frigate PTZ Auto Tracking requirements for RelativePanTilt FOV.

**Comment by NickM-27** [comment]
Personally I am not sure this makes sense at least in the near term. Without relative move we have to basically know the speed & just move the camera for a certain amount of time. Of course different cameras will vary depending on their speed and that will throw the tracking off.

**Comment by NickM-27** [comment]
Curious what @hawkeye217 thinks as well

**Comment by kennethgomez01** [comment]
Sorry what I mean is my camera support Relative movement is just that, the fov term requirements that my camera does not support.

**Comment by NickM-27** [comment]
I'm not aware of relative move that doesn't use that https://www.onvif.org/specs/srv/ptz/ONVIF-PTZ-Service-Spec-v1712.pdf

**Comment by hawkeye217** [comment]
I agree with @NickM-27, it doesn't make much sense to try to support particular cameras that don't work with the ONVIF RelativeMove FOV standard in the near term.

My guess is that your Hikvision clone camera's firmware just doesn't fully support the ONVIF standard.

Figuring out how fast the motor moves on one particular camera or another might be an imprecise guessing game. It's something I experimented with and considered when writing the initial code. But the manufacturers of each camera have done the heavy lifting of implementing field of view movement with their lens/motor combination and exposing that via the ONVIF standard. I have a feeling it would vary too much from camera to camera for Frigate to support it and have it work reliably, but maybe it's worth a try at some point later.

I have played around with ONVIF absolute movement (which more cameras probably support) and that might be something that Frigate could support in the future. It would probably require the user to define the limits of their field of view and then Frigate could do some math. It would still not be as precise as the camera firmware's relative move function, though.

**Comment by kennethgomez01** [comment]
Make sense. Thank you!

**Comment by NickM-27** [comment]
I think I'll close this as not planned for now. Can revisit once we have more info on how the auto tracking works for more users in its existing use case of relative move.

**Comment by nikosch86** [comment]
I had the same requirement and ended up forking and patching frigate to support my Sunba 405-D20X
It works well for this model and is partially configurable, you could try if that helps your cause or can serve as a starting point:
https://github.com/nikosch86/frigate/releases/tag/v0.16.2-camera-name-in-views-and-broader-autotracking-support
