### ISSUE TITLE
[Config Support]: mqtt file not found

### ISSUE THREAD

**Issue by jshep321** [blakeblackshear/frigate#7518]
### Describe the problem you are having

I am trying to integrate with a mosquitto mqtt broker that has a shared ca.crt file.  I use this broker successfully with bash and python paho, so I know the broker is functional.  Also, frigate works fine with a non-cert protected broker.   

My problem is with the path, I believe. When I put the below config in place, I see an error.  With my non-secure config on a different host, no problem.

What is the right path here?

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
#  host: 10.0.0.122
#  user: ----
#  password: ----
#  tls_ca_certs: /home/pi/certs/ca.crt
#  tls_insecure: true
```

### Relevant log output

```shell
Aug 18 13:50:59 frigate1 frigate_start.sh[10534]: frigate  | [Errno 2] No such file or directory
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
There are a few issues here:
1. You are running a very old version of frigate
2. Frigate is a docker container, it has no idea what /home/pi is. You need to add the cert into the container and make config use the path from inside the container.
