### ISSUE TITLE
Setting to turn off automatic deletion of event recordings, even when disk is full

### ISSUE THREAD

**Issue by twistedlincoln** [blakeblackshear/frigate#7523]
Currently, Frigate deletes the oldest 2 hours of recordings once it detects that there is less than an hour of storage remaining on disk.  This is an excellent feature, however it appears to delete the oldest 2 hours regardless of if those two hours contain segments that are used in event clips.  This results in not being able to play back the video from those events, as the source recording files are now gone.

While I recognize this behavior might be desirable in some situations, in my case it would be greatly preferable if there were a setting to preserve recording segments used in event clips no matter what -- I'd rather it stop recording entirely in most cases than delete event video, though it seems that would only be necessary in extreme circumstances.

The workflow I'm envisioning with setting enabled would be something like:

1.  If less than an hour of storage is remaining, delete the oldest two hours of video that do not contain event segments.
2.  If events continue to be generated, this will shrink the remaining disk space available for new recordings as a larger and larger percentage of disk space will be used for event segments.  Then once less than an hour of space is available for new recordings, stop all recording and log an error message.

**Comment by NickM-27** [comment]
I'm not sure this makes sense, the feature is only in place as a last resort safeguard. Really, you should have a reasonable retention configuration for your storage amount so that events are kept as long as configured.

**Comment by twistedlincoln** [comment]
> I'm not sure this makes sense, the feature is only in place as a last resort safeguard. Really, you should have a reasonable retention configuration for your storage amount so that events are kept as long as configured.

That's been my workaround, however the retention settings only appear to be allowed in whole day increments. So if you have a bit less than a full day's worth of storage, you have to round-down to the nearest day.  In my case, it's the difference between being able to store 24 hours and about 42 hours of 24/7 recording.  That's quite a bit less.

A related concern with the current behavior: when the auto-delete removes segments that correspond to event clips, it doesn't delete or otherwise mark the event as unavailable.  So it's very unclear when looking at the event list what events still have playable clips and which do not.  This provides a false sense of security that one still has access to recordings when they are in fact gone.  Not ideal, though admittingly probably a different issue.

**Comment by NickM-27** [comment]
> That's been my workaround, however the retention settings only appear to be allowed in whole day increments. So if you have a bit less than a full day's worth of storage, you have to round-down to the nearest day. In my case, it's the difference between being able to store 24 hours and about 42 hours of 24/7 recording. That's quite a bit less.

Perhaps it might make sense to allow floats and not just int for that field so partial days can be retained as well. 

Either way, the storage based retention was not designed to be relied on for standard retention, which is evidenced by the fact that it will even delete favorited events if it must to keep running. This is because it is a last resort, ensuring that the storage is not entirely filled up (which can cause issues even outside of frigate itself) and ensure frigate does not crash. 

> A related concern with the current behavior: when the auto-delete removes segments that correspond to event clips, it doesn't delete or otherwise mark the event as unavailable. So it's very unclear when looking at the event list what events still have playable clips and which do not. This provides a false sense of security that one still has access to recordings when they are in fact gone. Not ideal, though admittingly probably a different issue.

That's because a snapshot is still available, meaning the event is still available.

**Comment by twistedlincoln** [comment]
> Perhaps it might make sense to allow floats and not just int for that field so partial days can be retained as well.

Yes, that would be fantastic.

> That's because a snapshot is still available, meaning the event is still available.

I guess that makes sense.  Perhaps a UI change to make the color of the event's title change to red or something similar when the corresponding video is deleted or missing?

**Comment by NickM-27** [comment]
actually, the recording config already supports partial days

https://github.com/blakeblackshear/frigate/blob/28ea2afa51fa546dfbb089d727fe6c02ac592e38/frigate/config.py#L174

With that being the case, I'm going to close this. Feel free to create a separate feature request for a way to designate if an event has recordings, snapshots without needing to open the event
