### ISSUE TITLE
RTMP stream output takes a long time to start

### ISSUE THREAD

**Issue by jameswarnerEF** [blakeblackshear/frigate#753]
Firstly, incredible work on the new release! It has the potential to completely replace the NVR now...

Using the RTMP output in latest frigate for live multi-cam monitoring in HA, but stream takes a long time to start - some cameras around 5 seconds but one is 10. I've tried using VLC with buffer set to 100ms (delay also appears) and also  "-tune zerolatency" on the rtmp output ffmpeg args. I'm not sure if the start delay is caused by buffer, keyframe wait or a delay in frigate starting the stream. Anyone else seeing this?

**Comment by blakeblackshear** [comment]
It is most likely your key frame wait. I recommend turning on preload for the cameras.

**Comment by jameswarnerEF** [comment]
Sorry, I forgot to mention - tried HA preload, but doesn't appear to make any difference - will continue to test and let you know

**Comment by jameswarnerEF** [comment]
You were right, dropping keyframe interval down helps a lot - thanks!
