### ISSUE TITLE
Update go2rtc

### ISSUE THREAD

**Issue by rb2k** [blakeblackshear/frigate#7540]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use a current version of go2rtc so I can replay streams to software that expects a more compliant RTSP stream (such as Blue Iris before the latest update).

The current version in frigate has an SDP section of the RTSP stream that is [missing "a:control" entries](https://github.com/AlexxIT/go2rtc/issues/560)

**Describe the solution you'd like**
Update go2rtc. My current frigate version shows "Version: 1.2.0" on the go2rtc dashboard. The current go2rtc release on github is [v1.6.2](https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.2)

**Describe alternatives you've considered**
Complain to Blue Iris. They did indeed fix it.

**Additional context**
See https://github.com/AlexxIT/go2rtc/issues/560

**Comment by NickM-27** [comment]
Go2rtc has already been updated for the next version of frigate. 

Also, frigate has always supported the ability to run a custom version of go2rtc https://docs.frigate.video/configuration/advanced#custom-go2rtc-version
