### ISSUE TITLE
Frigate Proxy - HTTPS support

### ISSUE THREAD

**Issue by Quedale** [blakeblackshear/frigate#7559]
First, I would like to send my thanks for this amazing project!

**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to configure the Frigate Proxy add-on to use HTTPS instead of HTTP.
The Frigate Integration works flawlessly with HTTPS, but I couldn't find how to make it work on the Frigate Proxy add-on.

**Describe the solution you'd like**
I didn't dig deep enough , but most likely a simple "SSL" checkbox in the Frigate Proxy configuration page to configure the embed nginx reverse proxy to connect with HTTPS.
Note that I'm not looking to configure HTTPS on Frigate itself, only having the Frigate Proxy connecting using HTTPS.
This assumes a proper HTTPS implementation on the Frigate instance using a reverse proxy.

**Describe alternatives you've considered**
The alternative is simply to not use the add-on altogether. The Frigate Integration works fine over HTTPS.
Although, I lack convenient access to Frigate logs, configs and debugging features.

**Additional context**
1. I have two separate instance for homeassistant and Frigate.
2. Each instance are sitting on a relatively unsafe network (shared), so I have SSL enabled everywhere.
3. I configured Frigate with SSL and ACL, so that it can only be access through HA. (leveraging HA frontend authentication)

Although the Frigate instance can only be accessed through HA, the Frigate Proxy attempts to connect using the HTTP protocol.
This allows guest users on the network to potentially sniff the data between the two peers.

I would like for a similar configuration to be possible:
![image](https://github.com/blakeblackshear/frigate/assets/13303174/f8d968f4-c182-459f-855b-68ea978f8c6c)

But instead it results in:
```
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
```

I don't mind actually contributing such capabilities, if this is something that would accepted.
I'm actually hoping that I missed something super simple.

Thank you for your time and this project is really amazing!

**Comment by NickM-27** [comment]
This is the wrong repo for this request, also see https://github.com/blakeblackshear/frigate-hass-addons/pull/126

**Comment by Quedale** [comment]
Sorry for that, thank you for the reference. I will track this conversation instead!
