### ISSUE TITLE
Hassio Frigate requires now priviledged mode true options for USB edgetpu and uses still more than 60% cpu RPI4?

### ISSUE THREAD

**Issue by heikkis** [blakeblackshear/frigate#758]
I upgraded Frigate and Hassio platform to newest versions with bad result. Im using /config/frigate.yml for configuration. Frigate did not find edgetpu usb device.

I tried to reboot etc. without any luck. Finally I turned protection mode off and at least the log file shows edgetpu found. However, still CPU usage for 8GB RPI4 is more than 60% which is quite much?

Any ideas what might cause the problem? 

After update the error:
```
* Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
detector.coral                 INFO    : Starting detection process: 36
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Camera processor started for takapiha: 39
frigate.app                    INFO    : Camera processor started for etupiha: 41
frigate.app                    INFO    : Capture process started for takapiha: 42
frigate.app                    INFO    : Capture process started for etupiha: 44
frigate.mqtt                   INFO    : MQTT connected
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

After protectionmode off a.k.a. priviledged mode true:
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.app                    INFO    : Camera processor started for takapiha: 39
detector.coral                 INFO    : Starting detection process: 36
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Camera processor started for etupiha: 40
frigate.app                    INFO    : Capture process started for takapiha: 42
frigate.app                    INFO    : Capture process started for etupiha: 43
frigate.mqtt                   INFO    : MQTT connected
frigate.edgetpu                INFO    : TPU found
```

**Comment by heikkis** [comment]
I mean that I think before I did run successfully in protection mode and without nasty red ballon in Frigate setting page.

**Comment by heikkis** [comment]
I'm still newbie with Frigate, so there can be still misunderstanding about the setup etc.

**Comment by summitbri** [comment]
I'm having a similar runaway CPU problem since latest updates of HA supervisor/core/HASSio and Frigate.  My RPI4 CPU was previously under 30% with TPU, now it still shows TPU found but cpu goes up to 90's and then seems to lock up HA.  Not sure what the problem is, but HA is stable again once I uninstalled Frigate.  I've always been running with protection mode OFF.

**Comment by blakeblackshear** [comment]
Nothing changed within frigate itself. Homeassistant made a change to the supervisor that broke frigate, wiped out users config files, and many other addons without any advance notice. They then decided not to fix the breaking change. It's fine. These things happen. The addon will adapt as necessary. 

It may be required to run with protection mode off from here on out. I just don't know. I'm not sure why any of the changes they made would have increased the CPU usage within frigate. If you are running the exact same config, any change in CPU usage is not due to changes in frigate.

**Comment by summitbri** [comment]
Long shot, but I don't recall seeing this message before.  Could it be related?  

21-02-09 23:29:41 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Frigate NVR

**Comment by blakeblackshear** [comment]
Do you have an outstanding update? I thought I addressed that.

**Comment by summitbri** [comment]
Current version: 1.7
________________________________

**Comment by heikkis** [comment]
Okay it works now only in priviledged mode.
