### ISSUE TITLE
[HW Accel Support]: old 4GB Jetson nano - official support

### ISSUE THREAD

**Issue by Blu-Eagle** [blakeblackshear/frigate#7615]
### Describe the problem you are having

I made frigate work with jetson nano (see: https://github.com/blakeblackshear/frigate/discussions/7614) but with an unofficial build.

Any chance that could be added to the official build?

thx

### Version

? it is unofficial...

### Frigate config file

```yaml
see above linnk
```

### docker-compose file or Docker CLI command

```yaml
see above link
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wireless

### Camera make and model

any

### Any other information that may be helpful

.

**Comment by NickM-27** [comment]
Jetson is already supported in the upcoming 0.13
