### ISSUE TITLE
Clips are being saved.  but not visible on the web-ui

### ISSUE THREAD

**Issue by JudeLabs** [blakeblackshear/frigate#765]
Im having a problem with viewing clips on the frigate webUI.  

1) In the web UI  I am getting the message "No video with supported format and MIME type found.
![Screen Shot 2021-02-09 at 6 37 06 PM](https://user-images.githubusercontent.com/11382098/107452750-02273880-6b07-11eb-8631-fcffa2ad9697.png)
2) This is the command I use to start up the docker image:
`docker run --rm --name frigate --privileged --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 -v /dev/bus/usb:/dev/bus/usb -v /home/pi/frigate/clips:/media/frigate/clips -v /home/pi/frigate/recordings:/media/frigate/recordings -v /home/pi/frigate:/config -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:stable-armv7`
3) This is my directory structure:
![Screen Shot 2021-02-09 at 6 54 27 PM](https://user-images.githubusercontent.com/11382098/107453478-4961f900-6b08-11eb-8036-2b3c4c6aeba6.png)

4) The mp4 files are being saved in the clips folder:

![Screen Shot 2021-02-09 at 6 54 05 PM](https://user-images.githubusercontent.com/11382098/107453470-42d38180-6b08-11eb-80ce-7d74ace3cd81.png)

5) my config file:

> mqtt:
  host: 192.168.1.##
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: password
  stats_interval: 60

cameras:

  alley:
    ffmpeg:
      inputs:
        - path: rtsp://admin:#####@192.168.1.###:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect

    width: 1920
    height: 1080
    fps: 5

    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.7

          mask: 0,0,1000,0,1000,200,0,200
    clips:
      enabled: False

      retain:
        default: 10
        objects:
          person: 15
          car: 15

Everything else works fine.  It appears that it may be a permissions problem.  But I have CHMOD 777 on the clips directory and changed it to root.  Still not able to get the clips to view in the web UI.  I have also tunrned on debug logging and I am not seeing an error associated with this.

**Comment by blakeblackshear** [comment]
This is almost always because nginx doesnt have execute on the parent folder. You probably see a 403 error in the browser logs.

Try this docker run command instead:
```
docker run --rm --name frigate --privileged --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 -v /dev/bus/usb:/dev/bus/usb -v /home/pi/frigate:/media/frigate -v /home/pi/frigate:/config -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:stable-armv7
```

**Comment by JudeLabs** [comment]
It looks like you just gave the base path to the clips and recordings directories right?   This is still not working for me.   But the clips are being saved in the "Clips" driectory.

**Comment by blakeblackshear** [comment]
This is usually caused one of two things:

- The permissions on the parent folder don't have execute and nginx returns a 403 error you can see in the browser logs
- Your cameras do not send h264 encoded video and the mp4 files are not playable in the browser

**Comment by paularmstrong** [comment]
These two items keep coming up. We could add them to the troubleshooting docs

**Comment by blakeblackshear** [comment]
Please open if this issue is not resolved.
