### ISSUE TITLE
[Config Support]: document record -> enabled_in_config

### ISSUE THREAD

**Issue by jumika** [blakeblackshear/frigate#7656]
### Describe the problem you are having

On the web ui config editor there is code completion for a `enabled_in_config` key in `record`.
This is not documented. If this option have no use i suggest to disable this auto completion in the editor. If this option have some use please document it.

### Version

0.12.1-367D724

### Frigate config file

```yaml
record:
  enabled: true
  enabled_in_config: false
```

### Relevant log output

```shell
no logs
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
This field is for internal use only, should not be set by the user. Unfortunately, I do not think the control over autocomplete is granular enough to disable specific fields
