### ISSUE TITLE
Events dissapear from the web-ui

### ISSUE THREAD

**Issue by JudeLabs** [blakeblackshear/frigate#766]
I am running Frigate in a docker container and I use the native web-ui.  I am noticing the the thumbnails are disappearing or not appearing at all.  I am looking at the MQTT transfer to my other display and it looks like the images are being processed and transferred over MQTT,  however the WEB UI drops images,  apparently randomly from the events menu.  Also,  some images show up in the camera specific thumbnails on the camera page,  but those thumbnails are not seen in the events page, sometimes.  Has anyone run into this before?

**Comment by blakeblackshear** [comment]
Can you check the console logs in your browser and the frigate logs when you see images for events disappear? I'm not even  sure what you mean by disappear.

**Comment by paularmstrong** [comment]
There's a lot to unpack here…

* MQTT and the Web UI do not (currently) have any interaction. Images in MQTT are (mostly) unrelated to the events that you're seeing in the Web UI. 
* Events in the Web UI come from the sqlite database, provided by the API endpoint [/api/events](https://blakeblackshear.github.io/frigate/usage/api#apievents)
* Images for events are provided from two places
** snapshots: if you have snapshots enabled, they are written to disk and served from [/api/events/:id/snapshot.jpg](https://blakeblackshear.github.io/frigate/usage/api#apieventsidsnapshotjpg)
** thumbnails: These come directly from the sqlite DB, served through [/api/events/:id/thumbnail.jpg](https://blakeblackshear.github.io/frigate/usage/api#apieventsidthumbnailjpg)

>  I am noticing the the thumbnails are disappearing or not appearing at all

What does this mean? On what page? How can I reproduce this?

> however the WEB UI drops images, apparently randomly from the events menu

What does it mean to "drop" an image?

> Also, some images show up in the camera specific thumbnails on the camera page, but those thumbnails are not seen in the events page, sometimes

These are different images all-together. They are the "best" object match for that camera and object, provided by [/api/<camera>/<object>/best.jpg](https://blakeblackshear.github.io/frigate/usage/api#apicamera_nameobject_namebestjpgh300crop1). If you restart Frigate, these images are dropped out of memory and will load up as a black image until a new matching object is detected by that camera.

General questions that will really help track this down:
* What version of Frigate are you running? (you can find this at the top of the Debug page)
* What browser, version, and operating system are you using?

**Comment by blakeblackshear** [comment]
I may have found the issue. I am cleaning up events that do not have clips or snapshots associated with them automatically as a part of the retention settings. I can fix this in the next version. For now, I recommend at least enabling snapshots.

**Comment by JudeLabs** [comment]
Ok thanks for looking at this.  Sorry about the vague issue.  I set up all of my cameras with a Clips setting and it looks like it is saving the images now,  correctly.

**Comment by blakeblackshear** [comment]
I decided to not save events at all unless snapshots or clips are enabled. It's simpler to clarify the docs that one of the two must be enabled than to add another layer of complicated retention settings for database only events.

**Comment by JudeLabs** [comment]
Sounds good.  Thanks for the help.

**Comment by JudeLabs** [comment]
Sounds good.  Thanks for the help!
