### ISSUE TITLE
Pcie Coral Edge TPU temperature stats under "System" tab

### ISSUE THREAD

**Issue by Flick3rF3r** [blakeblackshear/frigate#7662]
Hi. Maybe I'm missing something but is there a way to monitor coral TPU temperature from web UI? From what I found on the Internet the pcie version does have a temperature sensor and it would be really nice to be able to see if its not overheating during operation especially when its installed in a NUC-form factor PC where airflow is minimal. CPU/GPU temps could be useful too.

**Comment by NickM-27** [comment]
This information is already presented to MQTT & the stats api, it could be confusing in the webUI though given that the USB coral does not support this.

> CPU/GPU temps could be useful too.

this information is not provided via the GPU stats tools

**Comment by Flick3rF3r** [comment]
Thanks for a quick reply. So the way I see it is that now stats regarding edge tpu temps are only available through MQTT but that doesn't prevent you from providing them in web UI too if you wanted to, especially when stats regarding usage like inference speed are alrady present. For the USB coral edge tpu there could be a "no sensor available" box for where temps with pcie version would be.
Again, I'm fully aware that feature requests I'm presenting here are of minor importance to say the least.

**Comment by NickM-27** [comment]
right, I was mainly just trying to provide context for why it hasn't been done

**Comment by Cheerpipe** [comment]
This could be extended to add nvidis-smi temperature stat.

**Comment by khisanthax** [comment]
Hello, I looked inside mqtt under frigate > stats and saw tpu stats but not temperature.  Is it somewhere else?

**Comment by paulius2k** [comment]
> Hello, I looked inside mqtt under frigate > stats and saw tpu stats but not temperature. Is it somewhere else?

I can not find it there either.

**Comment by NickM-27** [comment]
Only pcie corals support temperature stats

**Comment by khisanthax** [comment]
I have a pice coral, where would the temp stats be found?  Are they in the
gui?

**Comment by NickM-27** [comment]
In the new UI they are, not in the current version of Frigate. They are in the Frigate integration in home assistant

**Comment by khisanthax** [comment]
Thank you for clarifying!
