### ISSUE TITLE
go2rtc dashboard as an iframe in the Frigate UI

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#7668]
**Describe what you are trying to accomplish and why in non technical terms**
I am testing whether some cameras I have are working with 2-way audio or not, but to test that, I need the go2rtc dashboard to be served with HTTPs.

When running go2rtc as its own add-on, this is trivial thanks to hassio's ingress. But when running it inside Frigate, it's a lot more complicated.

**Describe the solution you'd like**

I believe it would be possible to embed the go2rtc dashboard in the Frigate UI itself, by using some iframe trickery I suppose. I am not experienced with this, but I'm assuming it's possible and it should not be too difficult.

**Describe alternatives you've considered**
1. Run go2rtc-addon temporarily as its own add-on: I have to shutdown Frigate, copy the config and so on.
2. Expose 1984 in Frigate add-on config, and configure NGINX Proxy Manager to proxy it to some address like go2rtc-home.mydomain.com. This requires NGINX Proxy Manager which I suppose many people don't even know about, but that's the solution I'm using for now.

**Additional context**
None.

**Comment by NickM-27** [comment]
I think the same work that would go into this would be more worthwhile just supporting two way talk in the frigate webui

**Comment by felipecrs** [comment]
That's true.

**Comment by skrashevich** [comment]
go2rtc can serve https itself from version 1.6.0 
https://github.com/AlexxIT/go2rtc/pull/352

**Comment by felipecrs** [comment]
Yeah, but it doesn't make anything easier. To make it work I would need to setup a local DNS server or expose 1984 to open internet, which I very much don't want.

**Comment by skrashevich** [comment]
you can get wildcard cert for your domain and make a sub-domain (A-record) to local IP

**Comment by felipecrs** [comment]
That's clever, I could do that indeed.

Still, I would have to generate a certificate and configure the domain.

Too much work for such a simple goal.

(PS: I'm not looking for alternative solutions, as stated in the issue description I already have one solution working).
