### ISSUE TITLE
Events disappear after few minutes

### ISSUE THREAD

**Issue by lukaszolek** [blakeblackshear/frigate#768]
I have frigate configured to detect events successfully:
<img width="753" alt="Zrzut ekranu 2021-02-10 o 08 55 24" src="https://user-images.githubusercontent.com/48291/107489928-7efaf680-6b89-11eb-9aae-a3d5dee1fe27.png">

After few minutes (1-2 min) all events disappear:
<img width="735" alt="Zrzut ekranu 2021-02-10 o 09 04 04" src="https://user-images.githubusercontent.com/48291/107489976-8de1a900-6b89-11eb-89a6-f0df46ebf328.png">

However, the last tracked objects are still visible in the camera view:
<img width="727" alt="Zrzut ekranu 2021-02-10 o 09 03 59" src="https://user-images.githubusercontent.com/48291/107490033-a225a600-6b89-11eb-9582-524d91d332fc.png">

Calling:
http://homeassistant.local:5000/api/events
Also results in:
[]

There are no error messages in the logs:
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Creating tmpfs of size 256m
frigate.app                    WARNING : Camera garage has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera garage has rtmp enabled, but rtmp is not assigned to an input.
frigate.app                    WARNING : Camera garden_front has clips assigned to an input, but clips is not enabled.
frigate.app                    WARNING : Camera garden_front has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for garage: 39
detector.coral                 INFO    : Starting detection process: 36
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Camera processor started for garden_front: 40
frigate.app                    INFO    : Capture process started for garage: 42
frigate.app                    INFO    : Capture process started for garden_front: 43
frigate.edgetpu                INFO    : TPU found
```

**Comment by lukaszolek** [comment]
I've enabled clips for the camera, and now I can see events older than 30 mins...

**Comment by blakeblackshear** [comment]
How are you running frigate? Please provide the info requested in the issue template.

**Comment by lukaszolek** [comment]
@blakeblackshear I'm sorry for my ignorance, but where can I find the issue template?

BTW, great job with frigate - I'm thrilled with it right now. Thanks!

**Comment by lukaszolek** [comment]
Events didn't persist, when clips were turned off, now when I turned it on, all events do persist.

**Comment by blakeblackshear** [comment]
> where can I find the issue template?

Looks like I broke the template a while back and didn't realize it. Sorry about that. Here it is: https://github.com/blakeblackshear/frigate/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by blakeblackshear** [comment]
I found the issue. I am cleaning up events that do not have clips or snapshots associated with them automatically as a part of the retention settings. I can fix this in the next version. For now, I recommend at least enabling snapshots.

**Comment by lukaszolek** [comment]
@blakeblackshear, thanks a lot!
