### ISSUE TITLE
Camera light automation feature

### ISSUE THREAD

**Issue by Flick3rF3r** [blakeblackshear/frigate#7702]
### Describe the problem you are having

I've been wondering if there is a way to setup a person detection based automation that turns on LED light on the camera itself.
I'm using imou cruiser 4mp (https://www.imoulife.com/pl/product/detail/cruiser) and it has LED lights that are otherwise unused and I think they could play a role as deterrent to remind people that the're being recorded lets say if they walk into a specified zone. Can this be done using Onvif protocol and Frigate itself?

### Version

0.12.1

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wireless

### Camera make and model

Imou Cruiser 4MP

**Comment by NickM-27** [comment]
There is no standard in ONVIF for controlling LED lights, that would need to be done in an automation platform like HomeAssistant or NodeRED
