### ISSUE TITLE
Config editor: Success/Error messages do not fade

### ISSUE THREAD

**Issue by mr-manuel** [blakeblackshear/frigate#7707]
**Describe what you are trying to accomplish and why in non technical terms**
If I save the config and it gets saved correctly and/or if there is an error, then the message stays there forever. To make the message disappear you have to switch or refresh the page.

**Describe the solution you'd like**
The message should disappear after some time or at least disappear when hitting the save button again. Else you never know, if this is a previous message or a current one.

**Describe alternatives you've considered**
Refresh or change page.

**Additional context**
![grafik](https://github.com/blakeblackshear/frigate/assets/12592765/19c89f92-de6a-4550-bf20-e7626f22ce79)

**Comment by NickM-27** [comment]
This has been fixed
