### ISSUE TITLE
How to setup Frigate datetime zone?

### ISSUE THREAD

**Issue by lukaszolek** [blakeblackshear/frigate#771]
All my frigate clips have names with wrong timezone (Home Assistant is set up to Europe/Warsaw).

Events show correct time: 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/48291/107506714-cb046600-6b9e-11eb-98c8-77ed1930ac38.png">

But media browser shows:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/48291/107506757-dce60900-6b9e-11eb-8d3e-24b436d16af7.png">

It would be also great if clip names would be formatted using my local datetime format (eg. 10.02.2021 14:05).

**Comment by blakeblackshear** [comment]
Are you running with the addon?

**Comment by lukaszolek** [comment]
Yes, frigate is installed as a Supervisor addon

**Comment by paularmstrong** [comment]
The Web UI is able to know about your local datetime formatting because it's done in JavaScript. The formatting in the media browser in HA comes from another source, the Frigate custom component/integration, which is in Python and has no knowledge of your local date/time formatting. If HA exposes a formatter to custom components, maybe that could be used, but barring that, we have to use a single datetime formatting for everyone.

**Comment by ee02217** [comment]
Hi!
I have this running as a docker and I have the similar issue.

Event date with Europe format:
![image](https://user-images.githubusercontent.com/60232595/111297408-7e9cc200-8645-11eb-9179-32a99ce26ee8.png)

The detecton camera provided by the frigate integration presents american date format:
![image](https://user-images.githubusercontent.com/60232595/111297527-9d02bd80-8645-11eb-8aeb-aefebf4215b2.png)

**Comment by SebbeM** [comment]
I have the same problem. It would be nice to be able to change this with an environment variable but I would argue that it should default to ISO-8601 and not American format.

**Comment by Alfiegerner** [comment]
I was thinking the timezones of the environment of the docker container could be passed via api to HomeAssistant integration. Though not sure if this would help those using the HA Addon as have no experience of that.

**Comment by mloebl** [comment]
Just adding my input to this too, running as a container in k8s here, and the timestamps and exposing the timezone as an env variable would be great if possible.

**Comment by maphilli14** [comment]
Any solutions to this?  It's kind of annoying to do the math for a single timezone that my HOME network spans!

**Comment by yanfali** [comment]
I'm in US timezone, but it's still off. My docker timezone is PST, but it seems to be in CST. I'm running docker image e64648364690. The timezones in both frigate:5000 and the integration in HA are off by an hour. I also think it would be awesome if the docker container defaulted to Zulu/GMT+0, that way you could compare logs against containers.

**Comment by NickM-27** [comment]
> I'm in US timezone, but it's still off. My docker timezone is PST, but it seems to be in CST. I'm running docker image e64648364690. The timezones in both frigate:5000 and the integration in HA are off by an hour. I also think it would be awesome if the docker container defaulted to Zulu/GMT+0, that way you could compare logs against containers
> 
> ![Screenshot 2022-06-03 16 27 05](https://user-images.githubusercontent.com/2275667/171966524-233ddd0e-755b-4a3c-942b-0a4fa2313f06.png)
> 
> Camera timestamp is PST, but frigate obviously thinks it's in the wrong timezone. The machine itself is set correctly to PST. I suppose I could fix this by volume mounting a timezone file into /etc. Oh looks like I already did that...
> 
> Never mind, my cameras are wildly off. Mea culpa

Are you passing `/etc/localtime` to the container?

**Comment by yanfali** [comment]
I am, though because it's a softlink on the local host I switched it to the actual file. The issue was the camera wasn't syncing with NTP anymore so the timestamp in the picture was out of sync. Firmware problems.

**Comment by gadgetbazza** [comment]
> Are you passing `/etc/localtime` to the container?

Sorry for the noob question, but how do I do this?  The recording filenames are 1 hour out (UTC?) from the actual time here (BST)?

Thanks

**Comment by NickM-27** [comment]
@gadgetbazza what installation method are you using? (docker CLI, docker compose, addon?)

**Comment by gadgetbazza** [comment]
A basic form of Docker Compose... Im running QNAP Container Station!

**Comment by NickM-27** [comment]
@gadgetbazza This is what it would look like in docker compose:

```yaml
lines (36 sloc)  935 Bytes

version: "3"
services:
  frigate:
    ...
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ...
```

**Comment by gadgetbazza** [comment]
Thanks, easy when you know how.  That's sorted it for me... Thanks very much for the swift assist!

**Comment by NickM-27** [comment]
> my events times are correct but the recordings where the video files go are still wrong. events for 12-1pm are in the 18 folder

like has been said previously, Frigate stores recordings in UTC folder structure. User is not supposed to be interacting with the files directly, that is why there is an API / WebUI

**Comment by ljmerza** [comment]
the webui only allows me to see events? no motion or general recordings so how does that even work out??

**Comment by ljmerza** [comment]
how is that supposed to work? i can onlysee events not recordings or general movement? pretty limited

**Comment by NickM-27** [comment]
> the webui only allows me to see events? no motion or general recordings so how does that even work out??

You use the 24/7 recordings viewer

![Screen Shot 2023-08-21 at 11 19 45 AM](https://github.com/blakeblackshear/frigate/assets/14866235/08bf53a0-cb7b-427d-848b-cb8082ac889d)

**Comment by ljmerza** [comment]
it says `Dates and times are based on the timezone America/Port-au-Prince` which makes no sense as i have the timezone set to EST

**Comment by NickM-27** [comment]
> it says Dates and times are based on the timezone America/Port-au-Prince which makes no sense as i have the timezone set to EST

most likely you haven't configured that correctly then, but that is an entirely separate issue

**Comment by Max101** [comment]
I have installed Frigate as a docker container too, and I am passing in `/etc/localtime` which shows up the correct time, however the snapshots time is still UTC and not the time I am passing in with `/etc/localtime` so is there a way to fix this so that the snapshot time matches the current time zone?

**Comment by pos-ei-don** [comment]
Same here

**Comment by mr2k24** [comment]
@NickM-27 When I click the "Recordings" button on the camera I only see a summary of events (Frigate 0.12.1). Is there a delay for when 24/7 recordings are available?

**Comment by NickM-27** [comment]
@mr2k24  it's not a summary, click any hour and you can view it

**Comment by mr2k24** [comment]
@NickM-27 Thanks for the fast reply! You're right, I didn't notice each hour was segmented as an "events". 

I just set up Frigate so I am still figuring things. Thanks again!

**Comment by jaymunro** [comment]
> I have installed Frigate as a docker container too, and I am passing in `/etc/localtime` which shows up the correct time, however the snapshots time is still UTC and not the time I am passing in with `/etc/localtime` so is there a way to fix this so that the snapshot time matches the current time zone?

This is the issue I have too. I receive a snapshot with a (US formatted) timestamp and it is not clear what date it is along with the time. I remember then I have to mentally adjust the time and then remember the date is in the US format (month first). However this is not fair on other people that look at it and just lose trust in the whole system.

**Comment by hawkeye217** [comment]
This is a very old issue. You can adjust the way the date and time is displayed using the `timestamp_style` option in your config. See the configuration reference in the official documentation: https://docs.frigate.video/configuration/reference

**Comment by jaymunro** [comment]
Ok, I found we can set the timestamp format with below added to the configuration, but the UTC matter still remains with the time (and sometimes date due to time difference from UTC)
```
timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"
```

**Comment by jaymunro** [comment]
> This is a very old issue. You can adjust the way the date and time is displayed using the `timestamp_style` option in your config. See the configuration reference in the official documentation: https://docs.frigate.video/configuration/reference

Found and added my comment to https://github.com/blakeblackshear/frigate/issues/5755#issuecomment-2869361272

**Comment by hawkeye217** [comment]
Please see the [installation instructions](https://docs.frigate.video/frigate/installation/#docker) in the docs. You should be mapping `/etc/localtime` via your Docker configuration.

**Comment by ehn** [comment]
> Please see the [installation instructions](https://docs.frigate.video/frigate/installation/#docker) in the docs. You should be mapping `/etc/localtime` via your Docker configuration.

Thank you for this comment! I've been hoping for a fix to the issue with the timestamp timezone for a long time and didn't realize that the solution is to set the timezone on the server.

I'm not sure I agree with the solution as I prefer to keep all my servers in UTC and don't necessarily think that should affect how date and time are presented in various web apps running on the servers, but it's great that there _is_ a solution.

**Comment by hawkeye217** [comment]
You could technically bind mount any file as `/etc/timezone` inside of the container - it doesn't need to be your server's `/etc/timezone`.

**Comment by ehn** [comment]
Yeah, that's what I'll do. Still means I need to remember to pay attention to that if trying to correlate timestamps of events on the host and inside the container for some reason, which is what I want to avoid by keeping everything in UTC, but it's not the end of the world. Easier than remembering that all the visual timestamps are in UTC.

**Comment by jaymunro** [comment]
I believe I am. Docker compose contains:
```
your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
```
```% ls -l /etc/localtime
lrwxr-xr-x  1 root  wheel  42 11 Mar 08:36 /etc/localtime -> /var/db/timezone/zoneinfo/Pacific/Auckland
```

**Comment by jaymunro** [comment]
I should mention that the UI is showing the right time. It is the timestamp added to the snapshots that is showing UTC.
e.g. top left time stamp

<img width="450" alt="Image" src="https://github.com/user-attachments/assets/0e3fb46d-9d16-4b37-8a18-d53515ff1254" />

**Comment by jaymunro** [comment]
Upgraded through 0.15.0 stable and now on 0.16.0 and the snapshot time stamps are showing local time.
I guess I missed an upgrade alert.
