### ISSUE TITLE
[Feature Request] Have favorited clips moved to separate folder

### ISSUE THREAD

**Issue by conorlap** [blakeblackshear/frigate#7710]
**Describe what you are trying to accomplish and why in non technical terms**
I'd like to be able to backup (via rsync or similar) my favorited clips ONLY. Currently these clips aren't in their own specific folder so there's no real way to do this that I can see.

**Describe the solution you'd like**
It would be useful if favorited clips were moved to a separate folder once they've been favorited. 
Then I could then setup an rsync job to backup those specific clips to an off-site server on a daily basis.

**Example**:
frigate directory:
  /clips
  /exports
  /recordings
  /favorited

**Comment by NickM-27** [comment]
I think it may be difficult to manage moving the files, especially in cases where unfavoriting needs to move the files back to the original location. 

If the primary goal is to save the footage, I wonder if it might be more straightforward and fill the same need to automatically export the clips of favorited events

**Comment by conorlap** [comment]
> I think it may be difficult to manage moving the files, especially in cases where unfavoriting needs to move the files back to the original location.

I suspected this might be tricky!


> If the primary goal is to save the footage, I wonder if it might be more straightforward and fill the same need to automatically export the clips of favorited events

Yeah that could work! Would this 'duplicate' the clips then? So the original would stay in place and a copy be exported to a separate folder?

**Comment by NickM-27** [comment]
Just the same as the current exports feature works, the exports are stored in the /exports folder as a combined clip and are not cleaned up or touched by frigate at all.

It could also be prepended by `favorite_` so only those files could be saved by rsync

**Comment by blthlt** [comment]
> Just the same as the current exports feature works, the exports are stored in the /exports folder as a combined clip and are not cleaned up or touched by frigate at all.
> 
> It could also be prepended by `favorite_` so only those files could be saved by rsync

Can we add an option in the export area to delete exports?  Just a red X beside it in the exports div?
![image](https://github.com/blakeblackshear/frigate/assets/479263/76fa6a0c-ec79-42b9-b161-495a73fa4d75)

**Comment by conorlap** [comment]
Not stale

**Comment by NickM-27** [comment]
Frigate ui is being rewritten and as part of that "favorited" events are being phased out and fully replaced by exports. This includes naming exports in the ui and being able to search for them.
