### ISSUE TITLE
[Config Support]: go2rtc error

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [blakeblackshear/frigate#7717]
### Describe the problem you are having

I have a very simple small configuration that uses go2rtc. But go2rtc is giving me an error with the URL format:

`2023-09-07 00:52:48.678096075  00:52:48.677 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="parse \"192.2.255.58:8554/\": first path segment in URL cannot contain colon" url=rtsp://192.2.255.58:8554
`

If i copy and paste this URL in VNC, i can see the video. I open this issue in frigate because i am not shure if that will happen in latest versions of go2rtc.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False

go2rtc:
  streams:
    rtsp_cam: 
      - rtsp://192.2.255.58:8554

cameras:
  rtsp_cam:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/rtsp_cam
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
```

### Relevant log output

```shell
2023-09-07 00:52:45.372847897  [INFO] Preparing go2rtc config...
2023-09-07 00:52:46.024167592  [INFO] Starting go2rtc...
2023-09-07 00:52:46.299608979  00:52:46.299 INF go2rtc version 1.2.0 linux/amd64
2023-09-07 00:52:46.300543883  00:52:46.300 INF [api] listen addr=:1984
2023-09-07 00:52:46.301194879  00:52:46.300 INF [rtsp] listen addr=:8554
2023-09-07 00:52:46.301204378  00:52:46.301 INF [srtp] listen addr=:8443
2023-09-07 00:52:46.302014404  00:52:46.301 INF [webrtc] listen addr=:8555
2023-09-07 00:52:48.678096075  00:52:48.677 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="parse \"192.2.255.58:8554/\": first path segment in URL cannot contain colon"
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You can use any version of go2rtc that you want https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

That would likely fix the issue

**Comment by FelipeSanchezCalzada** [comment]
In the latest version of go2rtc (1.7.0) the problem still occurs:
`2023-09-07 18:12:33.099343821  18:12:33.099 WRN [rtsp] error="streams: parse \"192.2.255.58:8554/\": first path segment in URL cannot contain colon" stream=rtsp_cam
`


I don't know if this is a frigate or g2rtc error, I don't see any reference to the error in either project.

**Comment by NickM-27** [comment]
This is an error in go2rtc logs so it is a go2rtc error. I'd suggest trying 

```yaml
go2rtc:
  streams:
    rtsp_cam: rtsp://192.2.255.58:8554/
```

**Comment by leifnel** [comment]
I still have this issue

**Comment by Clear2437** [comment]
Same here
