### ISSUE TITLE
USB Hard Drive or Network Location for Clip & Recording Storage

### ISSUE THREAD

**Issue by konradwalsh** [blakeblackshear/frigate#772]
Ubuntu Desktop 20.04 installed 
 HASS Supervised installed on that

Frigate Latest Version
USB Coral

I have a 2tb Drive that I want to use for storing information and be able to access this INSIDE HA.

When I view Supervisor > System > Hardware I can see my drive:

` 
name: sdb1

    sysfs: >-
      /sys/devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/host2/target2:0:0/2:0:0:0/block/sdb/sdb1
    dev_path: /dev/sdb1

    subsystem: block

    by_id: '/dev/disk/by-id/usb-Intenso_External_USB_3.0_20150610066730-0:0-part1'
    attributes:

      DEVLINKS: >-
        /dev/disk/by-id/usb-Intenso_External_USB_3.0_20150610066730-0:0-part1
        /dev/disk/by-label/INTENSO /dev/disk/by-partuuid/0cd37cf0-01
        /dev/disk/by-path/pci-0000:00:14.0-usb-0:4:1.0-scsi-0:0:0:0-part1
        /dev/disk/by-uuid/C2FE4A79FE4A65AF

      DEVNAME: /dev/sdb1

      DEVPATH: >-
        /devices/pci0000:00/0000:00:14.0/usb3/3-4/3-4:1.0/host2/target2:0:0/2:0:0:0/block/sdb/sdb1`

What is required in config to store clips /recordings on this drive?

Failing that, what is required for a network location store?

The documents reference the ability but dont say how. -

>  If you are storing your clips on a network share (SMB, NFS, etc), you may get a database is locked error message on startup. You can customize the location of the database in the config if necessary.

**Comment by blakeblackshear** [comment]
Try mounting that drive at `/media/frigate` on the host.

**Comment by konradwalsh** [comment]
OK.. I managed that
How do I get the clips to obey that location..
Their are other things on the drive.. 

So I create a sub folder - frigate_store
```
database:
  path: /media/frigate/frigate_store/frigate.db
```
This worked but the recordings and clip still remain at the root

**Comment by blakeblackshear** [comment]
Are the clips at `/media/frigate/clips` on the host?

**Comment by konradwalsh** [comment]
when I applied your suggestion  - 

> Try mounting that drive at /media/frigate on the host.

They are now at the ROOT of the External Hard Drive

Whilst the DB is where I stated in the config file 
```
database:
  path: /media/frigate/frigate_store/frigate.db
```

**Comment by konradwalsh** [comment]
when I applied your suggestion  - 

> Try mounting that drive at /media/frigate on the host.

They are now at the ROOT of the External Hard Drive

Whilst the DB is where I stated in the config file 
```
database:
  path: /media/frigate/frigate_store/frigate.db
```

**Comment by blakeblackshear** [comment]
If you can mount your drive at `/media` on the host, the clips and recordings folders will get nested under a folder named frigate.

**Comment by konradwalsh** [comment]
YES!
That did the trick
Thanks for your patience in walking me through that..

I have just spent 24 hours on this one!
