### ISSUE TITLE
[Config Support]: Problem with remote access with ssl

### ISSUE THREAD

**Issue by httpedo13** [blakeblackshear/frigate#7725]
### Describe the problem you are having

Hi, I installed frigate via the home assistant add-on and I configured the port 5000. 
Until now I have never encountered problems calling the API via the IP address of hassos on the local network. But I can't connect remotely via npm + cloudflare with ssl. 
I have 4 other services that all work. I'm not using cloudflare tunnel.
This is the npm configuration for Frigate service.
<img width="487" alt="Screenshot 2023-09-07 alle 20 10 37" src="https://github.com/blakeblackshear/frigate/assets/40502451/7f25cd70-a451-427b-a9f0-3f6c72acf11b">
<img width="487" alt="Screenshot 2023-09-07 alle 20 11 35" src="https://github.com/blakeblackshear/frigate/assets/40502451/629d6fbc-dbf7-4bdd-9e1e-bda74a4c343b">

And cloudflare
<img width="1242" alt="Screenshot 2023-09-07 alle 20 14 16" src="https://github.com/blakeblackshear/frigate/assets/40502451/0eb0ea9b-791b-4452-bcd6-2ec90be05ed9">

Thank you!

### Version

12.0 beta

### Frigate config file

```yaml
not relevant?
```

### Relevant log output

```shell
nothing in the nginx tab
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
This doesn't really seem like an issue for the frigate repo, it is not directly related to frigate and more to do with nginx / cloudflare config.

There is nothing special that needs to be done on the frigate side, I used to have a setup like this before I moved to cloudflare tunnels. The issue is going to be in the addon port, nginx, or cloudflare parts

**Comment by httpedo13** [comment]
Could you help me? The port in the add-on is set. I don't understand what's because the web interface works properly. @NickM-27

**Comment by NickM-27** [comment]
I don't have my old setup to compare.

You're going to need to check each step in the connection path to see where the issues are. What browser error is there when trying to connect, what about the npm logs, etc. etc.
