### ISSUE TITLE
Reference Coral USB on External Device

### ISSUE THREAD

**Issue by ggennrich** [blakeblackshear/frigate#7737]
### Describe the problem you are having

I have a Home Assistant Yellow and they only have USB 2.0. To get more out of the Coral, I want to put it into my USB 3.0 on my Synology NAS and reference that USB device. It would be on the same network. Frigate is currently installed as an addon through HA so it is on the Yellow as well.

I'm wondering if it is possible to reference an external Coral USB device in the frigate config. Or if what I'm asking even makes sense. USB 2.0 has max throughput of 400Mb/s. I have gigabit Ethernet so theoretically I could get a bit more than double the speed by using the USB 3.0 port over the network (still not max USB 3.0 speed but better than straight 2.0)

### Version

0.12.1

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest

**Comment by NickM-27** [comment]
This is not officially supported. It has been discussed at https://github.com/blakeblackshear/frigate/issues/3449 but as explained there, there are technical issues that mean it won't perform as well as a wired connected

**Comment by ggennrich** [comment]
> This is not officially supported. It has been discussed at #3449 but as explained there, there are technical issues that mean it won't perform as well as a wired connected

Thanks for the quick reply and reference.
