### ISSUE TITLE
[Support]: Home Assistant 2023.9 only accepts "_" as a valid separator in add-on slug names

### ISSUE THREAD

**Issue by ClassicGOD** [blakeblackshear/frigate#7738]
### Describe the problem you are having

Trying to start frigate-fa add-on from an automation now results in the following error:

```
Stopped because an error was encountered at 9 September 2023 at 09:18:55 (runtime: 0.01 seconds)

invalid slug ccab4aaf_frigate-fa (try ccab4aaf_frigate_fa) for dictionary value @ data['addon']
```
Request, if possible, to change add-on slug name to ccab4aaf_frigate_fa

### Version

0.12.1

### Frigate config file

```yaml
not relevant to the issue
```

### Relevant log output

```shell
not relevant to the issue
```

### FFprobe output from your camera

```shell
not relevant to the issue
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

not relevant to the issue

**Comment by NickM-27** [comment]
This is the wrong repo for this request. 

Also looks like an issue already exists https://github.com/blakeblackshear/frigate-hass-addons/issues/133
