### ISSUE TITLE
In Progress filter within events page

### ISSUE THREAD

**Issue by DrSpaldo** [blakeblackshear/frigate#7746]
I would like to have the option of filtering out in progress events. I have noticed that some in progress events are going way way longer than they should, in particular the new speech options. However, with so many events, I find myself scrolling through the events for a long time. It would be great to see at a glance what is 'in progress'

Thanks

**Comment by towerhand** [comment]
I think the "in progress" events should always be at the top of the list of events until they are not in progress anymore.

**Comment by NickM-27** [comment]
Yeah, maybe having a collapsible "ongoing events" or something

**Comment by DrSpaldo** [comment]
Looks good, thanks @NickM-27
