### ISSUE TITLE
[Feature Request] v.13 Timelapse adjustments

### ISSUE THREAD

**Issue by towerhand** [blakeblackshear/frigate#7748]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to select fps while creating a timelapse.  Also, it would be great to make time lapses with a fixed output time.

**Describe the solution you'd like**
There is currently an option to select the camera, start, and end time when creating a timelapse, which can make extremely long timelapses. I suggest adding two options: one where the user can select the fps of the timelapse. Another option that may be a little more complicated where the user can choose a final output length (1 min, 2 min, or 5 min) so Frigate can adjust the fps as needed when sending it to FFmpeg and create a timelapse of 1 min, 2 min, 5 min long. 

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment]
The current timelapse is designed to be able to fit 24 hours into 1 hour. I think it will be easier for frigate to have different types of timelapses because the fps and PTS calculations can be difficult to factor in and at the end of the day I think there are a few different categories of timelapses that users are looking for

**Comment by towerhand** [comment]
On another note, I am not sure if you are already planning on it, but it would be great if the "Exports" followed the same design as the "Events".

**Comment by NickM-27** [comment]
There will likely be changes in future versions as the recordings view is reworked

**Comment by towerhand** [comment]
Excellent, I see you are implementing some adjustments already. 

Could you add some examples in the docs? The link you provided is confusing, so it may be easier to figure out how to change the settings if you also provide other examples to compare, such as 1 day to 30 min and 1 day to 10 min.

Thanks for all your hard work.

https://github.com/blakeblackshear/frigate/pull/7840

**Comment by NickM-27** [comment]
you are basically just providing a multiplication factor. So for example if you wanted to go from 24 hours to 30 minutes that would be going from `86400` seconds to `1800` seconds which would be `1800 / 86400 = 0.02` so it would just be `PTS*0.02`

the fps is just how smooth the video will be, higher fps causes more resource usage to encode

**Comment by towerhand** [comment]
Thanks.
