### ISSUE TITLE
Allow filtering on time+date in Events page.

### ISSUE THREAD

**Issue by vertex-github** [blakeblackshear/frigate#7749]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to filter Events by time+date, not just date as is currently available.  With lots of cameras, and lots of events, being able to reduce the number of events I have to look through by time would be really helpful.

**Comment by NickM-27** [comment]
This is already supported in the upcoming 0.13

**Comment by vertex-github** [comment]
Is this available in a published docker container?

**Comment by NickM-27** [comment]
As a dev image in the packages on the sidebar. Be sure to read the preview release notes as there are breaking changes (or wait for the beta)
