### ISSUE TITLE
[HW Accel Support]: RPi4 running HAOS

### ISSUE THREAD

**Issue by memattyg** [blakeblackshear/frigate#7750]
### Describe the problem you are having

Hi, trying to add the hardware acceleration to my config, confused about how to add this part:

Ensure you increase the allocated RAM for your GPU to at least 128 (raspi-config > Performance Options > GPU Memory)

### Version

0.12.1-367D724

### Frigate config file

```yaml
not relevant
```

### docker-compose file or Docker CLI command

```yaml
not relevant
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

reolink wifi doorbell and wyze cam v2/v3

### Any other information that may be helpful

Just unsure where to go to increase RAM for GPU as part of adding hardware acceleration

**Comment by nblu** [comment]
I've been looking into the same issue in this post https://github.com/blakeblackshear/frigate/issues/7756#issuecomment-1713937149. The easiest method is to get root access (https://developers.home-assistant.io/docs/operating-system/debugging/) and update /mnt/boot/boot/config.txt with the gpu_mem. I hope that helps.

**Comment by memattyg** [comment]
yes and no.  i was worried it was complicated and this seems like a new level for me, so not too easy to get done on my end.
