### ISSUE TITLE
[Config Support]: How to change directory for events/snapshots/recordings

### ISSUE THREAD

**Issue by rayzorben** [blakeblackshear/frigate#7759]
### Describe the problem you are having

I am using HASSOS and I have a share mounted at `/media/security` that I want to use instead of `/media/frigate`. I see that the locate of the sqlite db can be changed, but I don't see an option for the recordings folder.

### Version

12

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
This isn't supported, the share needs to be mounted at `/media/frigate` (by creating a share called frigate as type media) as the docs explain https://docs.frigate.video/guides/ha_network_storage
