### ISSUE TITLE
Smarter, on-demand decoding of record stream

### ISSUE THREAD

**Issue by marcel263** [blakeblackshear/frigate#7785]
**Describe what you are trying to accomplish and why in non technical terms**
In case of only recording on events:
Frigate seems to be decoding the record stream all the time, into docker's `/tmp/cache`. This makes sense as usually the same stream is used for recording and decoding.

But when your record stream is separate, that stream too is being decoded all time, kept in a buffer. Even with hardware acceleration, this adds to system and power load, especially on simple devices such as Pi.

**Describe the solution you'd like**
Just keep the raw, unprocessed camera stream in a buffer. Only start decoding when there is an actual event.

**Comment by NickM-27** [comment]
> But when your record stream is separate, that stream too is being decoded all time, kept in a buffer. Even with hardware acceleration, this adds to system and power load, especially on simple devices such as Pi.

this is incorrect, frigate does not decode the recording stream at all, the recording stream is simply copied as is into to an mp4 container and then moved to storage if the retention config specifies, which is a very lightweight operation.

**Comment by marcel263** [comment]
If there is transcoding with go2rtc this is running all the time. Maybe it is actually a feature request for go2rtc? Hope you understand it.

**Comment by NickM-27** [comment]
Right, but for recording specifically that is not known. And if frigate only connected to the camera stream when a recording needed to be save, the latency penalty would mean there is a chance that an important moment of what caused the recording will be partially or fully missed. 

Also, an RPi is not a good choice of device if transcoding needs to be done anyway
