### ISSUE TITLE
Reolink: Add description around simplifcation of password complexity with go2RTC

### ISSUE THREAD

**Issue by BradleyFord** [blakeblackshear/frigate#7796]
**Describe what you are trying to accomplish and why in non technical terms**
I was struggling to get my Reolink cameras working via go2RTC, but it kept failing I have just realised that my password was too complex; of which I assume it is due to some special characters.

The password I had used for the cameras was: (Note that it is now changed)
O&QFMq%4Iq&Z%tXx

**Describe the solution you'd like**
It might be good to outline the special characters that cannot be used

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by NickM-27** [comment]
I think we need more specific information about what characters don't work and where. As far as I know, the only characters not supported from frigate's side are `{}`. 

go2rtc will have it's own set of unsupported characters

**Comment by dirrgang** [comment]
Oh for crying out loud. I've been trying to figure out the problem myself for hours now.

I had the same problem. In my case the password was too long. 32 characters. Now works with 16 characters.

**Comment by NickM-27** [comment]
also worth noting that given reolinks history of software issues, it could be issues with the camera and not apply to all reolink cameras since newer devices are on newer firmware

**Comment by thetic** [comment]
This is still an issue.

https://drewdevault.com/2021/10/26/stalebot.html

**Comment by NickM-27** [comment]
More information is needed from users to understand what reolink cameras are affected. I've tried and been unable to reproduce this issue with my reolink doorbell

**Comment by thetic** [comment]
I ran into this on my AD410 with a password containing a `#` and `!` character. I can't find anything describing the specific limitations, but it might be worth a call-out that some more complex passwords have been observed not to work.

**Comment by NickM-27** [comment]
We need actual information for what does and doesn't work. "Complex passwords" is very ambiguous, if all the docs say is that complex passwords cause issues that can cause more confusion. 

Also as I said in frigate itself the only characters known to not be supported are `{}`

If anything this issue should be closed and a new one created on the go2rtc repo

**Comment by NickM-27** [comment]
I will double check these characters and see how they work on my reolink doorbell.

**Comment by NickM-27** [comment]
in my testing `#` has issues with go2rtc, `!` works fine.

both work fine with frigate itself. I think an issue should be added to go2rtc to have a list defined so frigate docs can link to it, this is also not specific to reolink cameras as far as I can tell
