### ISSUE TITLE
Frigate addon 1.10 configuration lost

### ISSUE THREAD

**Issue by vinz486** [blakeblackshear/frigate#780]
**Describe the bug**
After the update to v 1.10 no configuration is found

**Version of frigate**
Output from `/version`
1.10

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
empty
```

**Frigate container logs**
```
* Starting nginx nginx
   ...done.
Error parsing config: [Errno 2] No such file or directory: '/config/frigate.yml'
```

**Frigate stats**
```json
N/A
```

**FFprobe from your camera**

Run the following command and paste output below
```
N/A
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2494005/107585447-8c9e9380-6bfe-11eb-8382-79b5d37fa8e7.png)

**Computer Hardware**
 - OS: Home Assistant OS 5.11
 - Install method: Addon
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Android
 - Model: IP Camera
 - Resolution: 640x480
 - FPS: 20

**Additional context**

**Comment by blakeblackshear** [comment]
Homeassistant made changes to the supervisor that broke the addon and deleted configs. The config file now needs to be added to the home assistant config directory at the root and named `frigate.yml`. You can try recovering your previous config from hassos snapshots.

**Comment by vinz486** [comment]
Ok, solved.

One note: all yaml files have .yaml extension, only Frigate uses .yml (this made me to think that workaround was not working).

Thanks,
Bye.

**Comment by blakeblackshear** [comment]
Both extensions are actually common, but it will probably be best to transition to yaml in the future.
