### ISSUE TITLE
[Detector Support]: Generate Model very slow

### ISSUE THREAD

**Issue by wes1993** [blakeblackshear/frigate#7810]
### Describe the problem you are having

Hello, 
i'm trying to generate the yolo model but the download is very slow... there is some alternative to download the yolo model?

![image](https://github.com/blakeblackshear/frigate/assets/52070589/5da075a9-7dd1-4fd9-b9d0-2986a06505a8)

This is my connection speed:

![image](https://github.com/blakeblackshear/frigate/assets/52070589/dd54e771-cbf9-4884-b8c9-2931ff2cc85a)

### Version

Not relevant

### Frigate config file

```yaml
Not relevant
```

### docker-compose file or Docker CLI command

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

**Comment by NickM-27** [comment]
>  there is some alternative to download the yolo model?

no, the model has to be downloaded and generated to that specific GPU and driver version.

The server may just be slow right now

**Comment by wes1993** [comment]
OK, thanks a lot @NickM-27 for the reply :-D
i will wait the end of the download, i have started the command 5 hours ago :-D
