### ISSUE TITLE
[Config Support]: Masks don't seem to be working

### ISSUE THREAD

**Issue by rv10guy** [blakeblackshear/frigate#7811]
### Describe the problem you are having

I have a busy alleyway behind my house and don't want cars in the alley. I care about cars in the driveway. I would like to detect other things in the alley like people etc. My thought was to setup masks for the individual object types so as to eliminate the alley from the video. But this approach does not seem to be working because I still get everything.

When I look at debug the mask seems correct when I select it.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: True
  user: ***
  password: ***
  host: ***
  port: 1883
  
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
  Driveway: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_main # <----- The stream you want to use for detection
          roles:
            - detect
            - record    
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 4608 # <---- update for your camera's resolution
      height: 1728 # <---- update for your camera's resolution
    snapshots:
      enabled: True
    record:
      enabled: True
    objects:
      filters:
        car:
          mask:
            - 577,0,3852,0,4608,824,4297,1269,3551,782,3358,676,1599,679,1500,426,35,827,0,593
        motorcycle:
          mask:
            - 577,0,3852,0,4608,824,4297,1269,3551,782,3358,676,1599,679,1500,426,35,827,0,593
        bus:
          mask:
            - 577,0,3852,0,4608,824,4297,1269,3551,782,3358,676,1599,679,1500,426,35,827,0,593
        boat:
          mask:
            - 577,0,3852,0,4608,824,4297,1269,3551,782,3358,676,1599,679,1500,426,35,827,0,593
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - boat
        - bird
        - cat
        - dog
```

### Relevant log output

```shell
I see a few errors in the log like the ones below but they don't seem related and it seems that they don't occur very often.

2023-09-11 18:35:12.769187905  [2023-09-11 18:35:12] watchdog.Driveway              INFO    : No frames received from Driveway in 20 seconds. Exiting ffmpeg...
2023-09-11 18:35:12.769190304  [2023-09-11 18:35:12] watchdog.Driveway              INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-11 18:35:12.903840337  [2023-09-11 18:35:12] frigate.video                  ERROR   : Driveway: Unable to read frames from ffmpeg process.
2023-09-11 18:35:12.904011520  [2023-09-11 18:35:12] frigate.video                  ERROR   : Driveway: ffmpeg process is not running. exiting capture thread...
2023-09-11 18:35:22.905471355  [2023-09-11 18:35:22] watchdog.Driveway              ERROR   : Ffmpeg process crashed unexpectedly for Driveway.
2023-09-11 18:35:22.907931172  [2023-09-11 18:35:22] watchdog.Driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-09-11 18:35:22.907965035  [2023-09-11 18:35:22] ffmpeg.Driveway.detect         ERROR   : [segment @ 0x5600bd994180] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-09-11 18:35:42.911894442  [2023-09-11 18:35:42] watchdog.Driveway              INFO    : No frames received from Driveway in 20 seconds. Exiting ffmpeg...
2023-09-11 18:35:42.911896738  [2023-09-11 18:35:42] watchdog.Driveway              INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-11 18:35:42.918074580  [2023-09-11 18:35:42] frigate.video                  ERROR   : Driveway: Unable to read frames from ffmpeg process.
2023-09-11 18:35:42.918103892  [2023-09-11 18:35:42] frigate.video                  ERROR   : Driveway: ffmpeg process is not running. exiting capture thread...
2023-09-11 18:35:47.725394943  [2023-09-11 18:35:47] frigate.record                 WARNING : Failed to probe corrupt segment /tmp/cache/Driveway-20230911183542.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x556ce02886c0] moov atom not found\n/tmp/cache/Driveway-20230911183542.mp4: Invalid data found when processing input\n'
2023-09-11 18:35:47.725397568  [2023-09-11 18:35:47] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/Driveway-20230911183542.mp4
2023-09-11 18:35:52.919612146  [2023-09-11 18:35:52] watchdog.Driveway              ERROR   : Ffmpeg process crashed unexpectedly for Driveway.
2023-09-11 18:35:52.919614746  [2023-09-11 18:35:52] watchdog.Driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-09-11 18:35:52.919636893  [2023-09-11 18:35:52] ffmpeg.Driveway.detect         ERROR   : Could not write header for output file #0 (incorrect codec parameters ?): Immediate exit requested
2023-09-11 18:35:52.919754532  [2023-09-11 18:35:52] ffmpeg.Driveway.detect         ERROR   : Error initializing output stream 0:0 -- 
2023-09-11 18:35:52.919756033  [2023-09-11 18:35:52] ffmpeg.Driveway.detect         ERROR   :
```

### Frigate stats

```json
{"Driveway":{"camera_fps":5.1,"capture_pid":1020,"detection_enabled":1,"detection_fps":5.0,"ffmpeg_pid":1025,"pid":1015,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"1003":{"cpu":"0.0","mem":"0.1"},"1009":{"cpu":"0.0","mem":"0.0"},"1010":{"cpu":"1.3","mem":"0.2"},"1012":{"cpu":"0.3","mem":"0.2"},"1015":{"cpu":"8.6","mem":"0.3"},"1019":{"cpu":"0.0","mem":"0.2"},"1020":{"cpu":"4.0","mem":"0.2"},"1024":{"cpu":"0.0","mem":"0.0"},"1025":{"cpu":"5.3","mem":"0.2"},"117":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"140":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"154":{"cpu":"0.0","mem":"0.0"},"15860":{"cpu":"0.0","mem":"0.0"},"15878":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"181":{"cpu":"0.0","mem":"0.0"},"206":{"cpu":"0.0","mem":"0.0"},"219":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"241":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"272":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"30":{"cpu":"0.0","mem":"0.0"},"308":{"cpu":"0.0","mem":"0.0"},"31":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"365":{"cpu":"0.0","mem":"0.0"},"404":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"430":{"cpu":"0.0","mem":"0.0"},"492":{"cpu":"0.0","mem":"0.0"},"543":{"cpu":"0.0","mem":"0.0"},"569":{"cpu":"0.0","mem":"0.0"},"593":{"cpu":"0.0","mem":"0.0"},"609":{"cpu":"0.0","mem":"0.0"},"631":{"cpu":"0.0","mem":"0.0"},"660":{"cpu":"0.0","mem":"0.0"},"695":{"cpu":"0.0","mem":"0.0"},"746":{"cpu":"0.0","mem":"0.0"},"783":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"0.0","mem":"0.0"},"97":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"0.7","mem":"0.9"},"MiB":{"cpu":"34002.6","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":5.0,"detectors":{"coral":{"detection_start":1694723749.872228,"inference_speed":7.39,"pid":1010}},"gpu_usages":{"intel-vaapi":{"gpu":"0.75 %","mem":"- %"}},"service":{"last_updated":1694723753,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":255.4,"mount_type":"tmpfs","total":268.4,"used":13.0},"/media/frigate/clips":{"free":21442240.6,"mount_type":"fuse.shfs","total":24068372.0,"used":2626131.5},"/media/frigate/recordings":{"free":21442240.6,"mount_type":"fuse.shfs","total":24068372.0,"used":2626131.5},"/tmp/cache":{"free":88.7,"mount_type":"tmpfs","total":100.0,"used":11.3}},"temperatures":{},"uptime":52543,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
Just one note, that is a crazy high resolution to be running detect at, there are very few cases where detect needs to be run anywhere near that high

in any case, this is not what object masks are designed for, you should be using required zones

**Comment by rv10guy** [comment]
> Just one note, that is a crazy high resolution to be running detect at, there are very few cases where detect needs to be run anywhere near that high
> 
> in any case, this is not what object masks are designed for, you should be using required zones

Thanks I will play with zones. My intent was to knock the resolution down ultimately. I was just playing with the first camera. This one does happen to be a dual camera reolink so that resolution is strange. and it is covering a sizable area.

**Comment by NickM-27** [comment]
right, I have a dual lens camera as well (from hikvision), I haven't found a need for a detect resolution higher than 2560x720

**Comment by rv10guy** [comment]
great thanks for the advise. I will work on the config with zones. I think I got it from reading the docs.

**Comment by rv10guy** [comment]
Quick question, how do zones and track interact? So for instance if I want to track people for the entire camera do I need to put them in each zone, or if they are listed once under track is that sufficient? I am trying to figure out if I would need to list person for each zone.

**Comment by NickM-27** [comment]
by default zones inherit the list from track. if you define the list for a zone then every object you want to be considered for that zone must be listed

**Comment by rv10guy** [comment]
Okay moving to zones seemed to help, but I am still having some come through that are definitely in a zone but the event is coming up without a zone.
<img width="428" alt="Screenshot 2023-09-14 at 6 36 01 PM" src="https://github.com/blakeblackshear/frigate/assets/15802973/5c9af525-6c4a-44d5-a013-e03286a0dc48">

**Comment by NickM-27** [comment]
You haven't made the zones required, so they are not restricting anything

**Comment by rv10guy** [comment]
Okay, I can change that, but I have broken the entire frame into zones so there should never be anything detected that isn't in a zone.
<img width="1164" alt="Screenshot 2023-09-15 at 8 26 01 AM" src="https://github.com/blakeblackshear/frigate/assets/15802973/ed27f890-632e-415d-8b46-daf3262a2846">
<img width="1154" alt="Screenshot 2023-09-15 at 8 26 10 AM" src="https://github.com/blakeblackshear/frigate/assets/15802973/8effbf87-b3d2-4a79-9058-c4a3e33c4009">
<img width="1154" alt="Screenshot 2023-09-15 at 8 26 21 AM" src="https://github.com/blakeblackshear/frigate/assets/15802973/22f6c8ec-0d93-421f-a6c0-174ffb88e23b">

**Comment by NickM-27** [comment]
please show the current config

**Comment by rv10guy** [comment]
mqtt:
  enabled: True
  user: ***
  password: ***
  host: ****
  port: 1883
  
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

cameras:
  Driveway: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_main # <----- The stream you want to use for detection
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      main_driveway:
        coordinates: 792,353,1550,330,1747,379,2158,624,2304,421,2304,864,0,864,0,746,253,584,756,211
      backyard:
        coordinates: 738,221,152,377,0,482,0,659,63,707
      alley:
        coordinates: 146,387,752,211,794,347,1664,353,1763,385,2152,634,2304,417,2304,0,0,0,0,452
        objects:
          - person
          - cat
          - dog
          - bicycle
    detect:
      enabled: True # <---- disable detection until you have a working camera feed
      width: 2304 # <---- update for your camera's resolution
      height: 864 # <---- update for your camera's resolution
    snapshots:
      required_zones:
        - main_driveway
        - backyard
        - alley
      enabled: True
    record:
      events:
        required_zones:
          - main_driveway
          - backyard
          - alley
      enabled: True

objects:
  track:
    - car
    - motorcycle
    - bus
    - person
    - cat
    - dog
    - bicycle

**Comment by NickM-27** [comment]
> Okay, I can change that, but I have broken the entire frame into zones so there should never be anything detected that isn't in a zone.

right, but all the events you are showing are car events in the alley zone which doesn't detect cars, hence why the cars are not considered in the zone.

**Comment by rv10guy** [comment]
Got it. I really appreciate the help. It seems to be working pretty good. I think I need to clean up the zone, maybe reduce them a bit. I am getting a few false positives like this one, where the bounding box, bleeds over into another zone even if the object does not. 
<img width="425" alt="Screenshot 2023-09-15 at 9 02 24 AM" src="https://github.com/blakeblackshear/frigate/assets/15802973/03741f64-a1e9-4734-a6df-6d982d8db4d0">

**Comment by NickM-27** [comment]
yes, important to remember that presence in zones is based on the bottom center pixel of the objects bounding box

**Comment by rv10guy** [comment]
Thanks for all your help. Now to work on all the other cameras!
