### ISSUE TITLE
[TensorRT Support]: No way to select which GPU a model is built for when multiple GPUs are present

### ISSUE THREAD

**Issue by vajonam** [blakeblackshear/frigate#7822]
### Describe the problem you are having

When running the beta without any environment variables it downloads and builds the yolov7-320 models correct and they are available. But when specifying the environment variable the following error is observed on startup.

```
YOLO_MODELS="yolov7-320,"
```

```
frigate           | 
frigate           | Creating yolov7-320.cfg and yolov7-320.weights
frigate           | 
frigate           | Done.
frigate           | ERROR: file ("yolov7-320".cfg) not found!
```

I have also tried other models, but only works when nothing is specified. 

### Version

0.13.0-9185753

### Frigate config file

```yaml
detectors:
  p106:
    type: tensorrt
    device: 1 #P106
  # 1050ti:
  #   type: tensorrt
  #   device: 0 #1050ti

model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

### Relevant log output

```shell
frigate           | Generating the following TRT Models: "yolov7-320"
frigate           | Downloading yolo weights
frigate           | s6-rc: info: service log-prepare successfully started
frigate           | s6-rc: info: service nginx-log: starting
frigate           | s6-rc: info: service go2rtc-log: starting
frigate           | s6-rc: info: service frigate-log: starting
frigate           | s6-rc: info: service nginx-log successfully started
frigate           | s6-rc: info: service go2rtc-log successfully started
frigate           | s6-rc: info: service go2rtc: starting
frigate           | s6-rc: info: service frigate-log successfully started
frigate           | s6-rc: info: service go2rtc successfully started
frigate           | s6-rc: info: service go2rtc-healthcheck: starting
frigate           | s6-rc: info: service go2rtc-healthcheck successfully started
frigate           | 2023-09-15 09:49:17.433253908  [INFO] Preparing go2rtc config...
frigate           | 2023-09-15 09:49:17.795016652  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
frigate           | 2023-09-15 09:49:17.829778645  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
frigate           | 2023-09-15 09:49:17.829786778  [INFO] Starting go2rtc...
frigate           | 2023-09-15 09:49:18.012088103  09:49:18.011 INF go2rtc version 1.6.2 linux/amd64
frigate           | 2023-09-15 09:49:18.016991801  09:49:18.016 INF [api] listen addr=0.0.0.0:1984
frigate           | 2023-09-15 09:49:18.018201211  09:49:18.018 INF [rtsp] listen addr=0.0.0.0:8554
frigate           | 2023-09-15 09:49:18.018852900  09:49:18.018 INF [webrtc] listen addr=0.0.0.0:8555/tcp
frigate           | 2023-09-15 09:49:18.020635189  09:49:18.020 INF [srtp] listen addr=0.0.0.0:8443
frigate           | 
frigate           | Creating yolov7-320.cfg and yolov7-320.weights
frigate           | 
frigate           | Done.
frigate           | ERROR: file ("yolov7-320".cfg) not found!
```

### FFprobe output from your camera

```shell
Not relavant?
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest

### Any other information that may be helpful

No think, its something simple like some paths messed up when looking for the cfg file when specifying an ENV.

**Comment by NickM-27** [comment]
Do not use quotes when setting the value of the env variable

**Comment by vajonam** [comment]
hmm.. okay, let me try that.

**Comment by vajonam** [comment]
Yup, duh! Thanks. its now building the models.

**Comment by NickM-27** [comment]
I've put up a PR to adjust the docs

**Comment by vajonam** [comment]
okay I thought I just made it up.. cool thanks! There are some deprecation warnings while building the model, safe to ignore?

**Comment by vajonam** [comment]
@NickM-27  I have multiple GPU's and I want to run the detection against GPU: 1, model is built on GPU 0, previously when I was manually building the models I could specify it, are we missing this now with the auto model builder?

**Comment by vajonam** [comment]
```
2023-09-15 10:09:47.215299837  [2023-09-15 10:09:47] frigate.detectors.plugins.tensorrt WARNING : Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
```

**Comment by NickM-27** [comment]
that would be a question for @NateMeyer

**Comment by vajonam** [comment]
The reason is the one of them is a mining GPU, which is good for cuda tasks, and other GPU is used for encode/decode. Which also helps my other apps do video encode / decode, so would rather be able to move the obj. dec. to the mining GPU as i was doing before.

**Comment by NickM-27** [comment]
how exactly did you specify a GPU for the building of the model before?

**Comment by vajonam** [comment]
```docker run --gpus=all --rm -it -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:22.07-py3 /tensorrt_models.sh```

I could limit the GPU visible to container while building.

**Comment by NickM-27** [comment]
Oh I see, yeah so it will be something that Nate will likely need to look into, I am not familiar with the script itself and if it supports selecting a GPU ID for the building phase

**Comment by NateMeyer** [comment]
Hey, that's a great point, I hadn't considered that issue before.  For now, running once with just the detection GPU to build the models should be a workaround.  I'll look at how to specify which GPU to use to the model build scripts and try to get that setup as an env var.

Taking that thought further, what if someone wanted to run detection on multiple GPUs.  Maybe the generated models need some sort of GPU specifier in the file name and be able to run the conversion process on each GPU specified.

**Comment by vajonam** [comment]
well I think I got mine working, but restricting deleting the models, restricting frigate container to only the GPU I want, (encode/decode will fail), but models are built and then I restart with both GPUs and then switch to the right GPU for the model in config.

**Comment by NateMeyer** [comment]
@vajonam Can you try just adding an env var to your docker-compose.yml and having it rebuild the model?  The value is the index of the GPU as seen by the container, and I think it should match the device value of the detector configuration.

```yml
environment:
  - CUDA_VISIBLE_DEVICES=1
```

I think this should limit tensorrt to just the GPU index you want to use.  This var should also be able to specify multiple GPUs if there are a set of identical GPUs for detection and an oddball to use for video, in a theoretical scenario.

If this works, it would just be a documentation update to support this.

**Comment by vajonam** [comment]
#Yes. This works. But since my GPU 1 doesn't support encode/decode all the streams fail to load up. But I am use this setting to build the right models and then switchback. This what I have done to get around this issue.

**Comment by NateMeyer** [comment]
Ah, ok.  I didn't know if this would affect the encode/decode access or just cuda.  I'll add an intermediate variable to apply only to the conversion script.

**Comment by vajonam** [comment]
I think it’s specific to my environment as I have a card that only supports
cuda and no encode / decode. This solution works for me. Just documention
update will work for me

**Comment by NateMeyer** [comment]
If I'm understanding correctly, the script change is needed to make it so you wouldn't need to boot twice, first generating the models, then removing the env var to run normally?  We would want any user to be able to have it come up and run the first time with a correct config.

**Comment by vajonam** [comment]
Yes. That is the correct that’s how it behaves now. 2 boots one with var
CUDA_VISIBLE_DEVICES and one without.

If you need it come up the first time against the right GPU a python script
change with needed on the script that generates the models

The GPU Id that should be used is in the detectors section, but not sure
you have access to it at that time as frigate hasn’t stated yet.

You can either parse it out of the detectors or add a variable like MODEL
_GEN_GPUID, that is used only for GPU and is used by and updated python
script.

**Comment by NateMeyer** [comment]
Shouldn't need to even change the python script, just bash.  I plan to set/unset the `CUDA_VISIBLE_DEVICES` just for the conversion process.

**Comment by vajonam** [comment]
Works well tested with latest dev snapshot! thanks!
