### ISSUE TITLE
HA Proxy: variable sidebar title

### ISSUE THREAD

**Issue by GerdRuetten** [blakeblackshear/frigate#7825]
I like Frigate, but it would be helpful for the UI 
if the sidebar title (and the icon) was freely customizable (as a configuration parameter).

Currently it's fixed "Frigate"

![image](https://github.com/blakeblackshear/frigate/assets/97361636/f0ec44a4-35a8-4bb6-b7dc-711d2fb35a8e)

TIA

Best regards

Gerd

**Comment by NickM-27** [comment]
this is the wrong repo for this request, see https://github.com/blakeblackshear/frigate-hass-addons
