### ISSUE TITLE
[Support]: Time for camera detection/recording

### ISSUE THREAD

**Issue by rv10guy** [blakeblackshear/frigate#7837]
### Describe the problem you are having

Is there a way to disable certain cameras based on time of day? I have some indoor camera which should only be monitored at night.

### Version

0.12.1-367D724

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink

**Comment by NickM-27** [comment]
yes, you can use the webUI, MQTT, or HomeAssistant integration to disable detection, snapshots, recording, etc.
