### ISSUE TITLE
Implement websocket relay for the frontend to receive mqtt messages

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#787]

**Comment by Tuckie** [comment]
Would this allow running a frigate instance integrated with home assistant without an mqtt broker (something I very much want)?

**Comment by blakeblackshear** [comment]
No. Why would you want that? Mqtt is very simple and easy to run.

**Comment by Tuckie** [comment]
I don't know why, but just adding an mqtt server to my HA instance causes weird lag and delays throughout my automations. (Running via AppDaemon) I've never been able to track it down further than having MQTT connected = unstable HA

I'm running on a Xeon D-1541 with SSDs, so it has never made any real sense.

For a more generalized use case:

It would be less moving parts, less to configure, less to break. Just talk websocket directly to Home Assistant.

**Comment by paularmstrong** [comment]
This task is done in #806. @Tuckie a [discussion](https://github.com/blakeblackshear/frigate/discussions/new) may get more traction getting help or alternative ideas with your specific issue.
