### ISSUE TITLE
Upgrade OpenVINO to 2023.1.0

### ISSUE THREAD

**Issue by felipecrs** [blakeblackshear/frigate#7870]
This is just a reminder that OpenVINO has a new version, and I suppose Frigate should eventually upgrade:

- https://www.phoronix.com/news/OpenVINO-2023.1-Released
- https://github.com/openvinotoolkit/openvino/releases/tag/2023.1.0

**Comment by NickM-27** [comment]
The problem with this is that the NCS2 is no longer supported with this version, so we would be losing support for some devices currently being used

**Comment by felipecrs** [comment]
Damn. Nothing is simple in this world. 😅

**Comment by svenstaro** [comment]
There's now [2023.3.0](https://github.com/openvinotoolkit/openvino/releases/tag/2023.3.0) and I think at some point frigate should just upgrade to enable newer opsets. Keeping compatibility with the NCS2 at all costs doesn't seem worthwhile to me.

**Comment by jsapede** [comment]
upgrade is needed as all new models includes opset 11

**Comment by klingon888** [comment]
> upgrade is needed as all new models includes opset 11

Just saw this post and totally agree that upgrade is more important than keeping compatibility. Since yolov8 is no longer supported, I compiled a new yolox-tiny today and it failed miserably since it has opset11.  I assume this error is caused by the old Openvino?

"Cannot create Interpolate layer /backbone/upsample/Resize id:303 from unsupported opset: opset11"

**Comment by jsapede** [comment]
Could it be done using same steategy as immich where hardware accélération is splitted in docker-compose settings using différent docker images as source for the ai engine ?
Would it make it possible to so have old openVINO for compatibility and newer ones for yolov8/v9 ?

**Comment by jsapede** [comment]
> > upgrade is needed as all new models includes opset 11
> 
> Just saw this post and totally agree that upgrade is more important than keeping compatibility. Since yolov8 is no longer supported, I compiled a new yolox-tiny today and it failed miserably since it has opset11.  I assume this error is caused by the old Openvino?
> 
> "Cannot create Interpolate layer /backbone/upsample/Resize id:303 from unsupported opset: opset11"

Theres Somewhere in this github discussion on yolo with a link to a Google collab for yolov8 pretrained for frigate. It stills work with old opset settings

But it's impossible to use the openVINO notebooks for tuning v8 nor v9 : opset error

**Comment by klingon888** [comment]
> Theres Somewhere in this github discussion on yolo with a link to a Google collab for yolov8 pretrained for frigate. It stills work with old opset settings
> 
> But it's impossible to use the openVINO notebooks for tuning v8 nor v9 : opset error

I've been using this collab too in 0.13 versions. BUT unfortunately there is an ongoing AGPL issue with using yolov models, so no longer supported in 0.14 versions of Frigate. See [here](https://github.com/blakeblackshear/frigate/pull/10717). Only yolo tiny is officially supported now. If you enter yolov8 in the 0.14 config, it now errors out.

**Comment by jsapede** [comment]
This sucks but in fact for the use we have theres no real différence in models résults, almost all Can acurately distinguish a human from a car or a dog. 
The only Real point is the openVINO hardware accélération

**Comment by esand** [comment]
> Could it be done using same steategy as immich where hardware accélération is splitted in docker-compose settings using différent docker images as source for the ai engine ? Would it make it possible to so have old openVINO for compatibility and newer ones for yolov8/v9 ?

+1 I'm sure there's a number of us who'd like openvino updated. For people using older hardware, having a different compose config tied to a custom release tag should hopefully be something viable.

Also, just for info - the Intel NCS2 is ending warranty June 30th 2024. Technical support has already ended.

**Comment by felipecrs** [comment]
0.14.0 Beta 2 says "Upgrade to latest openvino version" btw.
