### ISSUE TITLE
Increasing post_capture too much causes clips to not be created because it takes too long

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#788]

**Comment by N5QM** [comment]
Is there any information that I can gather to help with this issue?

I am running into it as well as I was trying to reduce the number of clips created in favor of longer clips.

**Comment by blakeblackshear** [comment]
> Is there any information that I can gather to help with this issue?
> 
> I am running into it as well as I was trying to reduce the number of clips created in favor of longer clips.

Increasing post_capture shouldn't have any effect on the number of clips. There is a clip per tracked object. This will just make each clip longer without reducing the number of clips.

**Comment by cpnbnanamn** [comment]
> 
> 
> > Is there any information that I can gather to help with this issue?
> > I am running into it as well as I was trying to reduce the number of clips created in favor of longer clips.
> 
> Increasing post_capture shouldn't have any effect on the number of clips. There is a clip per tracked object. This will just make each clip longer without reducing the number of clips.

Which is exactly what I wanted to do.  Problem is, it appears that if the port-capture is lengthened beyond the default 5 secs, you end up with a log full of those errors.  Interestingly, the clips still appear to be created in /tmp/cache directories.

**Comment by gurkburk76** [comment]
I'm having issues with longer clips so i'll add to what i know/noticed.
Testing with a single camera and 5 detecting objects at width: 2560 height: 1440 with a pre_capture and post_capture at 5 sec is no problem. If i raise those to 30 sec each it's a bit of a hit and miss if there is any clip recorded.

I've observed this indide the container:
shm                    64M  5.9M   59M  10% /dev/shm
tmpfs                 2.8G   64M  2.8G   3% /tmp/cache

The shm seems a bit small, if it matters at all, the cache is more than enough to hold that time/seconds of clip.
My system has 16gig memory and my docker startup looks like this:
docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=3000000000 \
  -v /root/frigate/media:/media/frigate \
  -v /root/frigate/testcfg.yml:/config/config.yml:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -p 5000:5000 \
  -p 1935:1935 \
  blakeblackshear/frigate:stable-amd64

**Comment by mjoshd** [comment]
I'm not sure if this info is too late to help anyone but I've finally had a measure of success with changing the `pre_capture:` value and _not_ gettting the 'There were no cache files for this event' issue.

What I found, and I may be going at this from the wrong angle, is that changing `max_disappeared:` to a large number, I used 150, caused all detection clips to be extended by ~30s longer than normal.

Once I noticed this, I then tried increasing the `pre_capture:` time to 10 and no longer get the 'There were no cache files...' issue. 

Previously, changing either `pre_capture:` or `post_capture:` to _anything_ larger than the default of 5 caused the 'There were no cache files...' message in the logs and no clip was saved. 

Now it is working well and creating clips with a larger `pre_capture:` value and also longer clips with the larger `max_disappeared:` value.

For what it's worth, I've also slightly altered the docker command in my environment by increasing the `tmpfs-size` and specifying a `shm-size` with:
```
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=4000000000 \
  --shm-size=3.7gb \
```

These configuration changes were made with lots of trial, error, and observation. If I'm misunderstanding how the values are supposed to function then please ignore my ignorance but I'm hoping that I'm on the right track and this info will help others as well.

**Comment by blakeblackshear** [comment]
The shm-size does not have anything to do with the clips cache, so there isn't a need to make it so large. 

Max disappeared defines how long to wait before assuming that an object is gone. Setting it that high will cause multiple persons to be detected as one even if they walk into the frame 30 seconds later (assuming 5fps). That will increase the length of the event related to that object, but not necessarily the length of the clip of the event. If you have people walking by regularly, it will just create one long event because it assumes it is all the same person, and you won't have any video saved other than the last person. 

What likely allows it to work now is the very large tmpfs volume where the clip cache is stored. If you weren't using a tmpfs volume there, it should also solve your issue. The cache is cleared when it is over 90% full, and that can cause the no cached clips available for the event warning. 

The next version will not have this issue for the majority of users because clips and recordings are being merged. Clips will be assembled from the 24/7 recordings rather than a separate cache.

**Comment by mjoshd** [comment]
Thanks for the explanation!

I restored the original 'max_disappeared' value and rebuilt the container without the '--mount' and '--shm-size' lines as you recommended. Now the 'pre_capture' and 'post_capture' seem to work as expected, as long as the values aren't set too high.

Thank you for your recommendations and for your work on this project.. it really is amazing!

Looking forward to checking out the next version you mentioned.

Have a great day 😃

**Comment by Rothammel** [comment]
#932
