### ISSUE TITLE
Object tally in gallery as per calendar view

### ISSUE THREAD

**Issue by dopeytree** [blakeblackshear/frigate#7885]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

See a quick glance at the total number of objects detected in each category. This would update depending on the calendar view so like last All, last day, yesterday, 7days, 30days.

5 🐈 1 🐕 30 🚗 15🧍

**Describe the solution you'd like**

a simple way to add 5 objects to display a tally of in the config

**Describe alternatives you've considered**

People who are not a fan of emojis could use custom icons or simple words like 5 cats - 1 dogs - 30 cars - 15 people

**Additional context**

Some people may think it's irelivent the no of objects but it's kind of a cool metric even if those 5 cats are the same cat.

Calendar view options

<img width="166" alt="Screenshot 2023-09-19 at 20 40 24" src="https://github.com/blakeblackshear/frigate/assets/103341262/4be06c50-4cdd-4164-a136-6e358cb335fb">

**Comment by NickM-27** [comment]
this would require a lot of large queries on the database, I could see this being a separate "analytics" screen or something but would be difficult as a default view on the events page

**Comment by dopeytree** [comment]
Ah maybe a simple approach of just the last 24 hours. I think this data is available as sensors in home assistant?

So it could be something like 

Last 24hrs: 5 🐈 1 🐕 30 🚗 15🧍

**Comment by NickM-27** [comment]
> Ah maybe a simple approach of just the last 24 hours. I think this data is available as sensors in home assistant?

No historical data is available in home assistant sensors (that comes directly from frigate)
