### ISSUE TITLE
☀️🌛 - Filters: Day / Night / All Recordings

### ISSUE THREAD

**Issue by dopeytree** [blakeblackshear/frigate#7886]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

☀️🌛 - Filters: Day / Night / Off (All) - shows day or night or all recordings

**Describe the solution you'd like**

simple button added to gallery viewing.

**Describe alternatives you've considered**

additional drop down label box could be added that says Day / Night / All 
However this would take up more space than a single cycling icon switch.

**Additional context**

<img width="1492" alt="Screenshot 2023-09-19 at 20 35 07" src="https://github.com/blakeblackshear/frigate/assets/103341262/19a3d711-1004-4cd9-bb35-742ff6778bd2">

**Comment by NickM-27** [comment]
there is an existing request for time filters https://github.com/blakeblackshear/frigate/issues/3140

**Comment by dopeytree** [comment]
thanks
