### ISSUE TITLE
Sort clips by Longest to Shortest.

### ISSUE THREAD

**Issue by dopeytree** [blakeblackshear/frigate#7887]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to ... so that I can ... 

⬆ -⬇ - Cycling icons to sort clips by length from shortest to longest. Ascending / Descending

Sometimes it is useful to see long clips to see any errors in one's config. At the moment this has to be done by scrolling down and infinity list. Looking for long recording lengths.

**Describe the solution you'd like**

button added to gallery 

**Describe alternatives you've considered**

[ 0 - 1m ] - drop down selector - shows clips according to length
1m - 5m
5m - 30m
30m - 1h
1h+
Any

**Additional context**

<img width="1492" alt="Screenshot 2023-09-19 at 20 35 07" src="https://github.com/blakeblackshear/frigate/assets/103341262/94c23f4b-8e31-40bc-b706-4daf6a7e03ee">

Icon added

![time](https://github.com/blakeblackshear/frigate/assets/103341262/3792eb81-0078-440a-bcc7-d3d708a99e4d)

**Comment by tpjanssen** [comment]
+1

**Comment by NickM-27** [comment]
this isn't relevant anymore in the new UI
