### ISSUE TITLE
HA Media Brower not showing up

### ISSUE THREAD

**Issue by jaburges** [blakeblackshear/frigate#789]
**Describe the bug**
I should have a media browser in the side-bar, and cant find any docs indicating I have to do something special.

As per another thread i've added
```yaml
config:
  homeassistant:
    media_dirs:
      - cctv: /cctv
```
Docker container volume mapped to /cctv. Validated the folder exists, docker exec'd in to HA and the clips are there.

**Version of frigate**
blakeblackshear/frigate:stable-amd64nvidia

**Frigate stats**
```json
{"back":{"camera_fps":5.1,"capture_pid":93,"detection_fps":0.0,"pid":76,"process_fps":5.1,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":6.39,"pid":57}},"doorbell_1":{"camera_fps":1.3,"capture_pid":80,"detection_fps":0.0,"pid":60,"process_fps":1.3,"skipped_fps":0.0},"driveway":{"camera_fps":5.1,"capture_pid":87,"detection_fps":0.0,"pid":75,"process_fps":5.1,"skipped_fps":0.0},"front":{"camera_fps":5.0,"capture_pid":83,"detection_fps":0.0,"pid":63,"process_fps":5.0,"skipped_fps":0.0},"kitchen":{"camera_fps":5.1,"capture_pid":107,"detection_fps":0.0,"pid":78,"process_fps":5.1,"skipped_fps":0.0},"living_room":{"camera_fps":5.0,"capture_pid":112,"detection_fps":0.0,"pid":79,"process_fps":5.0,"skipped_fps":0.0},"service":{"uptime":1763,"version":"0.8.1-d376f6b"},"side":{"camera_fps":5.1,"capture_pid":100,"detection_fps":0.0,"pid":77,"process_fps":5.1,"skipped_fps":0.0}}
```

**Computer Hardware**
 - OS: Unraid OS
 - Install method: Docker (community addon)
 - Virtualization: Docker
 - Coral Version: M2 (PCIe)
 - Network Setup: wired

**Comment by Diondk** [comment]
Hi,

in your HA configuration please add:

default_config:

That should enable the media browser.

Kind Regards,
Dion

**Comment by jaburges** [comment]
excellent, thanks - one can also add:

```media_sources:``` to their config if they don't want to enable ALL the default_config options.
