### ISSUE TITLE
[Support]: where is the 10.1 DOC ? I can`t found it!

### ISSUE THREAD

**Issue by yuhuanfan** [blakeblackshear/frigate#7897]
### Describe the problem you are having

[Support]: where is the 10.1 DOC ? I can`t found it!

### Version

10.1

### Frigate config file

```yaml
none
```

### Relevant log output

```shell
none
```

### FFprobe output from your camera

```shell
[Support]: where is the 10.1 DOC ? I can`t found it!
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

ezviz C2c

**Comment by NickM-27** [comment]
There isn't specific versions of the docs. It is recommended to run the latest stable version. 

https://github.com/blakeblackshear/frigate/tree/v0.10.1/docs

The git repo can be used if need be.
