### ISSUE TITLE
How to record only audio events?

### ISSUE THREAD

**Issue by javydekoning** [blakeblackshear/frigate#7920]
### Describe the problem you are having

In 0.13 beta 1 I’ve setup a “crying” audio detector for the baby room. This is working great, but it also records due to object detection.

How should I configure my record config? I reviewed the docs but can’t find a relevant example.

https://deploy-preview-6262--frigate-docs.netlify.app/configuration/record

### Version

0.13

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
the audio is only a trigger, you still need the recording config to be setup to record *something*

`audio` itself is considered motion, so you can setup to only record motion and it will only record when audio is detected (assuming object detection and 24/7 recording is disabled)
