### ISSUE TITLE
[Support]: Is it possible for Frigate to restart my camera?

### ISSUE THREAD

**Issue by primski** [blakeblackshear/frigate#7923]
### Describe the problem you are having

The camera is shit and it's losing connection over wifi after which the frigate and the home assistant integration stops streaming, until the camera is rebooted via their Icsee app which is terrible, really

is it possible to have home assistant detect this and reboot the camera? 

Not sure how to find out if this stupid camera supports this or not ? 

THANKS!

PS: is there another community for stupid questions like this? 

### Version

1

### Frigate config file

```yaml
1
```

### Relevant log output

```shell
1
```

### FFprobe output from your camera

```shell
1
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

1

### Any other information that may be helpful

1

**Comment by primski** [comment]
the Generic Camera integration supposedly has "FPS Entity" ... https://www.home-assistant.io/integrations/generic/

Frigate doesn't ?

**Comment by NickM-27** [comment]
The frigate integration offers a camera_fps sensor and in the frigate beta the camera entity is marked as unavailable when the camera is offline. 

There is no way for frigate itself to restart the camera, but you could use a smart switch in HA.
