### ISSUE TITLE
[Support]: Exports and Daylight Savings

### ISSUE THREAD

**Issue by psilantropy** [blakeblackshear/frigate#7935]
### Describe the problem you are having

Hi all,

Just a bug report on daylight savings and exporting.

![image](https://github.com/blakeblackshear/frigate/assets/79955883/2f6ef0d1-52b4-421e-b2f4-bed94b2f3e25)

Not sure if you would like any additional details as the issue is straightforward. 

View recordings: 24/09/2023 12:50PM - 1:30PM.
Result: All good

Export records: 24-09-2023 12:50PM - 1:30PM 
Result: Exports received for 11:50AM - 12:30PM. 1 hour earlier.

Export records: 24-09-2023 1:50PM - 2:30PM
Result: Export received 24/09/2023 12:50PM - 1:30PM - What I wanted.

### Version

0.13.0-9185753

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
is this just an issue that occurs when a recording is started before daylight savings time and ended after? Really, the browser should be taking care of that

**Comment by psilantropy** [comment]
Sorry just did a lot of testing and found it's an issue at Dahua end. NTP failure.
Thanks for the response.
