### ISSUE TITLE
GDPR compatible logs?

### ISSUE THREAD

**Issue by Adephx** [blakeblackshear/frigate#7939]
I've been looking through the documentation and I can't seem to find any info related to download logs? I'm trying to migrate about 80 cameras out of the Ubiquiti UniFi ecosystem, because the logs are atrocious and don't comply with the EU GDPR standards, but after the initial migration of about 20 cameras, I realized that Frigate might have even less features when it comes to logs? I know I'm supposed to rely on reverse proxy Authelia for user access, but how do I monitor when a user downloads a snapshot or a video directly through web interface? From what I see, as I'm relying on Authelia, it should be impossible to see which user downloaded what, as two services aren't directly connected, but from poking around, I can't even seem to find any download logs at all? Where and how can I monitor if a snapshot or a video was downloaded? In order to comply with GDPR I need to know at what time, including the date a snapshot or a video file was downloaded, at which point I can make a script to link that download to an access log from a specific user (just using one, so it should be simple).

**Comment by NickM-27** [comment]
The nginx logs contain the information about when the api is being accessed. Currently downloading isn't supported via the api but I don't think that would be too difficult.

**Comment by Adephx** [comment]
So I would have to solve this issue through nginx api and not Frigate if I understand you correctly? As far as Frigate logs go, it only offers logs related to the service itself, such as errors, bad streams, etc.?

**Comment by NickM-27** [comment]
No that is incorrect. You can already view the nginx logs in the frigate webUI, and technically can access them from inside the container. We would just need to build an api to concatenate those logs and download

**Comment by Adephx** [comment]
I did not know that Frigate natively integrates nginx, I assumed that you have to rely on Authelia for that.

**Comment by NickM-27** [comment]
Auth is not supported and an external service is recommended.
