### ISSUE TITLE
[Support]: MQTT Messages

### ISSUE THREAD

**Issue by rv10guy** [blakeblackshear/frigate#7945]
### Describe the problem you are having

I am looking at the MQTT messages sent by Frigate. Specifically the event messages. Can you explain what the difference is between the before and after sections of the JSON data?

### Version

0.12.1-367D724

### Frigate config file

```yaml
not needed
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA

**Comment by NickM-27** [comment]
The mqtt `/events` topic is sent at different key moments, for example when an object is first considered a true positive, when an object enters a zone, when an object exits a zone, when an object becomes stationary, when the object leaves.

Each of these messages has `before` and `after` which correlate to the objects state `before` this key moment happened and `after` this key moment happened. 

For example when an object first enters the `driveway` zone you could get a message that looked like

```json
{
  "before": {
    "entered_zones": [],
    "current_zones": [],
  },
  "after": {
    "entered_zones": ["driveway"],
    "current_zones": ["driveway"],
  }
}
```

**Comment by rv10guy** [comment]
@NickM-27 One further question. It appears that MQTT events are being sent for detections that are not logged within Frigate. For example, I am getting MQTT events for a car in a zone that I am not looking for a car in. Frigate is not logging that event on the web interface, but I am seeing it on MQTT. Is this correct?

**Comment by NickM-27** [comment]
yes that is correct, /events is a raw topic that includes all events, if you don't want to use that event for example because the object didn't enter a zone then you can use the data in the payload to filter out that event

**Comment by rv10guy** [comment]
@NickM-27  I am looking at messages as they come across in MQTT explorer and it seems that the entered zone and current zone is always blank. The way I have my zones laid out, everythink should be in a zone. Any idea why this may be happening? Here is an example: 
`{"before": {"id": "1695758642.683853-cs8h2m", "camera": "Driveway", "frame_time": 1695758646.669448, "snapshot_time": 1695758643.188439, "label": "car", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1695758642.683853, "end_time": null, "score": 0.609375, "box": [1265, 200, 1309, 230], "area": 1320, "ratio": 1.4666666666666666, "region": [1089, 52, 1409, 372], "stationary": false, "motionless_count": 1, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": false, "has_snapshot": false}, "after": {"id": "1695758642.683853-cs8h2m", "camera": "Driveway", "frame_time": 1695758646.669448, "snapshot_time": 1695758643.188439, "label": "car", "sub_label": null, "top_score": 0.84375, "false_positive": false, "start_time": 1695758642.683853, "end_time": 1695758651.888374, "score": 0.609375, "box": [1265, 200, 1309, 230], "area": 1320, "ratio": 1.4666666666666666, "region": [1089, 52, 1409, 372], "stationary": false, "motionless_count": 1, "position_changes": 1, "current_zones": [], "entered_zones": [], "has_clip": false, "has_snapshot": false}, "type": "end"}`

**Comment by NickM-27** [comment]
without a config and without image examples it is difficult to say

**Comment by rv10guy** [comment]
@NickM-27  I wrote a Python script to pull and parse the incoming events, and this is what I am seeing. If the zone is set up to monitor for an object, then when that object is detected in that zone it appears in the entered zones, but if that object is not listed in the objects for that zone it comes through as an event without any Entered Zones.

Here is an example:

For the Driveway Camera in the config below if a car is detected outside of the driveway, I get an MQTT event that shows a car and it's Entered Zones is blank. However, if the car enters the main_driveway zone, then the event shows that it entered the "main_driveway" zone. 

I am not sure if this is the intended behavior but it seems weird that the event is being sent regardless of if it meets the criteria in the config file but is not including all of the data so that it can be filtered on the backend. This is espically problematic when you have a mix of cameras with and without zones. You cannot simply ignore evens with no entered_zone because that is exactly how they come through on a camera with no zones defined.

Here is my config:

`mqtt:
  enabled: True
  user: "hassio"
  password: "hassio"
  host: 192.168.142.2
  port: 1883
  
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  Front:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.206:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      porch:
        coordinates: 212,105,0,287,0,480,640,480,640,0,387,0,381,104
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      required_zones:
        - porch
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - porch
      enabled: True
    birdseye:
      mode: objects

  Garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.205:554/h264Preview_01_sub
          roles:
            - detect
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
      enabled: True
    birdseye:
      mode: objects

  Back:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.207:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      patio:
        coordinates: 141,114,0,257,0,480,640,480,640,0,404,0,394,46
        objects:
          - person
    detect:
      enabled: True 
      width: 640 
      height: 480 
    snapshots:
      required_zones:
        - patio
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - patio
      enabled: True
    birdseye:
      mode: objects

  Driveway:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_main 
          roles:
            - record
        - path: rtsp://frigate:fr1gat3@192.168.110.208:554/h264Preview_01_sub
          roles:
            - detect
    zones:
      main_driveway:
        coordinates: 35,463,0,440,0,576,1536,576,1536,284,1397,435,1196,285,1064,248,524,278,483,188,273,388
      backyard:
        coordinates: 35,463,273,388,483,188,125,270,0,326,0,443
        objects:
          - person
      alley:
        coordinates: 1280,0,1536,284,1397,435,1196,285,1064,248,524,278,483,188,123,270,0,326,0,207,190,0
        objects:
          - person
          - cat
          - dog
          - bicycle
    motion:
      mask:
        - 1016,73,1015,123,852,88,861,46
    detect:
      enabled: True 
      width: 1536 
      height: 576 
    snapshots:
      required_zones:
        - main_driveway
        - backyard
        - alley
      enabled: True
    record:
      events:
        retain:
          default: 14
          mode: active_objects
        required_zones:
          - main_driveway
          - backyard
          - alley
      enabled: True
    birdseye:
      mode: objects

objects:
  track:
    - car
    - motorcycle
    - bus
    - person
    - cat
    - dog
    - bicycle
    - package

birdseye:
  enabled: True
  mode: continuous`

**Comment by NickM-27** [comment]
> I am not sure if this is the intended behavior but it seems weird that the event is being sent regardless of if it meets the criteria in the config file but is not including all of the data so that it can be filtered on the backend. This is espically problematic when you have a mix of cameras with and without zones. You cannot simply ignore evens with no entered_zone because that is exactly how they come through on a camera with no zones defined.

this is working as expected, the config file is configuring when recordings for events are done. an event is synonymous with a tracked object, it does not necessarily have a snapshot / recording saved

there are many cases this is useful, for example I don't want to record the UPS truck that doesn't enter my driveway, but I still want a notification when it sees it go by

> You cannot simply ignore evens with no entered_zone because that is exactly how they come through on a camera with no zones defined.

right, your automation should account for the specific camera and what zones are relevant for that camera to notify you

**Comment by rv10guy** [comment]
@NickM-27 I guess I don't understand the correlation. I get that you might not want a recording or a snapshot, that makes sense. What doesn't seem to make sense to me is why entered zones is just left blank? If the system is sending a notification of a detected object, why is it is leaving the detail out? In your example there was a UPS truck somewhere and presumably frigate knows that but it is not putting that info into mqtt. But if you were making a recording it would put that information in. 

To me the trouble with this approach is that it requires correlation between the config file and the application or automation looking at the mqtt feed because the mqtt event changes based on the settings in the config file. So for example if you decide you want to start capturing the UPS truck in frigate, then the mqtt event will change (now showing the zone) and you will need to reconfigure whatever is consuming the mqtt events to account for this.

**Comment by NickM-27** [comment]
> What doesn't seem to make sense to me is why entered zones is just left blank? If the system is sending a notification of a detected object, why is it is leaving the detail out? In your example there was a UPS truck somewhere and presumably frigate knows that but it is not putting that info into mqtt. But if you were making a recording it would put that information in.

By defining objects for that zone, you as the user are specifically saying that no other object types can be considered as part of that zone. 

you are saying in your config that a car can not be part of the alley or backyard zones, so it would not make sense for frigate to say in the /events topic that the car entered the zone which you have said the car can not enter

**Comment by rv10guy** [comment]
> By defining objects for that zone, you as the user are specifically saying that no other object types can be considered as part of that zone.
> 
> you are saying in your config that a car can not be part of the alley or backyard zones, so it would not make sense for frigate to say in the /events topic that the car entered the zone which you have said the car can not enter

For me this seems to be a flaw in the logic. If the config file says a car can't enter the alley, then why send an event on it?  And then that event is sent with zones incomplete because a car can't be in an alley. Seems to me that it should be one or the other, it should not send the event if it doesn't meet the criteria or it should send all events with all the relevant data.

For me the confusion comes down to the fact that the config file defines how the cameras work, how frigate works and what is recorded. Then mqtt seems to have an inconsistent implementation. It will get all of the events regardless of the recording/snapshot configuration, but the data sent in the message can be limited based on the recording/snapshot configuration. 

Please don't take this as argumentative or complaining. I am trying to understand the logic and the way the app is intended to work. I am working on an iPhone application that gets notifications and provides mobile access to snapshots and clips. The app will require a backend that runs on the same network as the frigate server and collects the data and sends the notifications to the iPhone app.  I am using a combination of mqtt and http api calls to collect the data and send the notifications from the backend. This is why I am concerned if the user makes a change to their frigate config file, how this impacts the inputs to my application.

**Comment by NickM-27** [comment]
> For me the confusion comes down to the fact that the config file defines how the cameras work, how frigate works and what is recorded. Then mqtt seems to have an inconsistent implementation. It will get all of the events regardless of the recording/snapshot configuration, but the data sent in the message can be limited based on the recording/snapshot configuration.

When you define 

```yaml
cameras:
  a_camera:
    ...
    zones:
      objects:
        - person
```

That has nothing to do with snapshots or recordings. That is simply a camera config of the zone and what objects can be considered entering the zone. 

You can use zones to limit snapshots and recordings to those zones, but that is the only part related to snapshots and recordings. 

I don't understand a usecase where you would not want recordings of a car entering alley zone but you would want notifications specifically when it enters the alley zone. 

But if that is the desired behavior, you'd just need to create a separate zone that is not used for recordings but includes car.

**Comment by rv10guy** [comment]
> I don't understand a usecase where you would not want recordings of a car entering alley zone but you would want notifications specifically when it enters the alley zone despite configuring the alley zone to not include car.

I don't have one. This was the original question. I was seeing all these events that weren't "events" in Frigate. That's when you explained I was getting all the events. My main problem right now is filtering out event notifications I don't want. My original plan was to let the Frigate configuration define it, so if it is recording/snapshot then it is getting notified on. But because the mqtt events come through for events that aren't recorded I have to filter them. That means I need to recreate filtering in the app but don't have all the data. 

> 
> But if that is the desired behavior, you'd just need to create a separate zone that is not used for recordings but includes car.

This is a solution I need to look into further. This potentially could be a workaround but it would be simpler if it only sent mqtt events for Frigate "events" or I had all the data in the event to do the triage myself. I was really hoping to only have the Frigate "events", then I can make the notification engine configuration really simple.

**Comment by NickM-27** [comment]
Like I said, events refers to tracked objects. The /events topic is a raw topic that includes all tracked objects. 

The events page in the webUI is a subset of the events that match the retention config. 

All that being said, I don't see how this makes notifications complicated to configure. The SgtBatten home assistant blueprint supports this topic without issue by simply offering the user to choose what zones they want notifications for. 

If a user wants notifications for an object that enters a zone they have explicitly set to not include said object, that is a user configuration problem.

**Comment by NickM-27** [comment]
It's possible in the future a simpler /notifications topic or something will be created which is less verbose than /events

**Comment by rv10guy** [comment]
> All that being said, I don't see how this makes notifications complicated to configure. The SgtBatten home assistant blueprint supports this topic without issue by simply offering the user to choose what zones they want notifications for.
> 
> If a user wants notifications for an object that enters a zone they have explicitly set to not include said object, that is a user configuration problem.

So this got me thinking and I did some checking. SgtBatten's blueprint relies on a set of sensors that are exposed by the HACS HA/Integration. So his blueprint really never deals with the mqtt feed directly. So if we follow the example above and you were to put Camera: Driveway Zone: Alley Object: car, you would never see the car in the alley because there is no binary sensor for car in the zone alley. I know there are some specific API calls for home assistant. I need to figure out how that is being populated. 

Here is a screenshot for alley in Home Assistant:

<img width="601" alt="Screenshot 2023-09-26 at 10 11 33 PM" src="https://github.com/blakeblackshear/frigate/assets/15802973/2235703e-d357-4067-9f7b-c283302a9249">
 
> It's possible in the future a simpler /notifications topic or something will be created which is less verbose than /events

I am not sure less data is better, it would be better if entered zones and current zone where always populated.

**Comment by NickM-27** [comment]
> So this got me thinking and I did some checking. SgtBatten's blueprint relies on a set of sensors that are exposed by the HACS HA/Integration. So his blueprint really never deals with the mqtt feed directly.

That is incorrect, the blueprint uses the events topic for its notifications 

https://github.com/SgtBatten/HA_blueprints/blob/8d6e7f42f9ea9a681b14c002ca19d491ee3e179e/Frigate%20Camera%20Notifications/Stable#L553-L557

**Comment by NickM-27** [comment]
> I am not sure less data is better, it would be better if entered zones and current zone where always populated.

I stand by what I said, it would make no sense for the alley zone to be included in entered_zones for a car when the config specifically says that specific zone can not contain the car object

**Comment by NickM-27** [comment]
If this were to be implemented it would be a major breaking change and require automations with zones to be much more complicated. 

Right now I can have a simple condition in my automation that checks if a zone was entered, because I know the entered zones is respecting my zones config that defines what objects I care about in each zone. 

For example I only care about cars in my street zone. With this suggested change I would be getting notifications for people in my street zone which is not what I want. I would have to add logic in the automation to not only check entered zones but to check the object type and make sure it matches with that zone. Making things much more complicated.
