### ISSUE TITLE
documentation updated needed for events with active_object

### ISSUE THREAD

**Issue by vajonam** [blakeblackshear/frigate#7967]
yeah, things are working as expected, the docs just need to be tweaked a bit

_Originally posted by @NickM-27 in https://github.com/blakeblackshear/frigate/discussions/7953#discussioncomment-7114258_

**Comment by vajonam** [comment]
https://github.com/blakeblackshear/frigate/discussions/7953#discussioncomment-7114180

**Comment by vajonam** [comment]
https://github.com/blakeblackshear/frigate/discussions/7953#discussioncomment-7112722

**Comment by NickM-27** [comment]
Probably `required_active_objects` but yes that could be done, not sure how difficult it would be to do given the information that is available, but either way I think that would be a post 0.13 implementation

**Comment by NickM-27** [comment]
this is no longer relevant in 0.15 now that recording retention is based on alerts and detections which are inherently defined as periods of activity
