### ISSUE TITLE
Two feature requests

### ISSUE THREAD

**Issue by PianSom** [blakeblackshear/frigate#797]
Two suggestions that might improve (at least my) user experience:
1 - allow a flag for avoiding the posing of jpg snapshots to MQTT (these cause much disruption to cli tools such as `mosquito_sub`
2 - allow an MQTT post giving the date stamp of the last event (so that HA interface can easily see if there has been a recent event)

But these are small things. Loving the tool. Thanks.

**Comment by blakeblackshear** [comment]
1 is already possible. See the mqtt section under camera config. You can accomplish 2 with a homeassistant automation/input and the events mqtt topic.

**Comment by PianSom** [comment]
1 - thank you. I was not reading the comments and making wrong assumptions. (`MQTT: Enabled: False` does NOT mean MQTT is not enabled :) ) I should have read the "NOTE"
2 - I am being dim here. What "events" topic do you mean? I am only seeing topics of frigate / available : <camera> : stats. And under <camera> are clips : snapshots : detect : person.

**Comment by blakeblackshear** [comment]
https://blakeblackshear.github.io/frigate/usage/mqtt#frigateevents

**Comment by PianSom** [comment]
Thanks. 

I was obviously being more than usually stupid that day.
