### ISSUE TITLE
Feature Suggestion - Frigate web interface, view multiple cameras live

### ISSUE THREAD

**Issue by jameswarner62** [blakeblackshear/frigate#799]
Hope it's OK to post non bug reports like this for consideration!

Now that frigate can manage clip aging, and offers live monitoring in the web interface - it's enough to completely replace an actual NVR in many cases I think. The only thing missing is the live monitoring of multiple cameras. I know you can stream out to RTMP and build an interface that way or using home assistant cards, but it would be a great improvement if you could enable optional live monitoring on the "Cameras" page of the web interface rather than just a still. Would need some control over the size of each camera to enable them all to be on screen at once...  Being able to toggle detection boxes like in the single view would be a bonus
Just a thought!

**Comment by paularmstrong** [comment]
This will require #422 as the current solution for live video in the web UI is not performant enough
