### ISSUE TITLE
The default ffmpeg args link is dead on documentation page

### ISSUE THREAD

**Issue by Eagleman7** [blakeblackshear/frigate#800]
**Describe the bug**
The default ffmpeg args link is dead at https://blakeblackshear.github.io/frigate/troubleshooting/#how-can-i-get-sound-or-audio-in-my-clips-and-recordings

This link is dead:
https://blakeblackshear.github.io/frigate/troubleshooting/configuration/index#ffmpeg

**Comment by jaburges** [comment]
@Eagleman7 you can edit the docs and make a PR ;)
