### ISSUE TITLE
[Support]: unable to generete M3u for VOD 

### ISSUE THREAD

**Issue by vajonam** [blakeblackshear/frigate#8005]
### Describe the problem you are having

When exporting for a specific day, which had 2 cars parked in the driveway

```
2023-09-30 06:17:52.926286729  2023/09/30 06:17:52 [error] 177#177: *1267 media_set_parse_durations: invalid number of elements in the durations array 1196 while sending to client, client: 172.19.0.3, server: , request: "GET /vod/front/start/1695960000/end/1696046400/index.m3u8 HTTP/1.1", host: "frigate.domain.com"
2023-09-30 06:17:52.926293800  172.19.0.3 - - [30/Sep/2023:06:17:52 -0400] "GET /vod/front/start/1695960000/end/1696046400/index.m3u8 HTTP/1.1" 503 197 "-" 
```

### Version

0.13-0858859

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest

**Comment by NickM-27** [comment]
What time period was the export requested for

**Comment by vajonam** [comment]
24hr period, from the day before.

https://frigate.domain.com/vod/front/start/1695960000/end/1696046200/index.m3u8

**Comment by vajonam** [comment]
This script has been running with no issues so many months now. No changes
similar to the export script that’s now in frigate.

**Comment by NickM-27** [comment]
I'm confused, are you using a script or the built in export feature?

**Comment by vajonam** [comment]
Not the built in the issue is with VOD API returning a 503. For a given
date range.

**Comment by NickM-27** [comment]
Ah, then this is working as expected. This is nothing new, for many versions the VOD module has been limited to 1000 segments that can be returned in a single reques. Your 24 hour period had 1196 segments so it can't be processed. This is why the export feature concatenates many requests when there are more than 1000 segments for the given time period

https://github.com/blakeblackshear/frigate/blob/22b95077976bdabf0d67cb70c3a263f82459c6ae/frigate/record/export.py#L70-L93
