### ISSUE TITLE
[Support]: TCP errors when cameras are not allowed to access internet in router

### ISSUE THREAD

**Issue by avvalex** [blakeblackshear/frigate#8011]
### Describe the problem you are having

I have some IMOU cameras and since i don't need to send my streams to their cloud i simply thought that i could have disallowed them to access internet in my router.
But when i block internet access i start to have a ton of

2023-10-01 10:08:36.989700090  10:08:36.988 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.xxx.xxx.xxx:xxx->192.168.xxx.xxx:554: i/o timeout" url=rtsp://xxxxxx:xxxxxx@192.168.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0

Is there a chance to prevent these errors while having cams isolated from internet?

### Version

0.12.1-367d724

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

IMOU Cue 2

**Comment by avvalex** [comment]
Wait.... it seems that Cue 2 cams reboots every few minutes when they are not allower to access internet....
Seems it's time to buy new cameras :-)

**Comment by NickM-27** [comment]
This is a camera issue, nothing frigate can do to affect the cameras behavior.
