### ISSUE TITLE
[Support]: Backend storage via Object FUSE

### ISSUE THREAD

**Issue by jvallery** [blakeblackshear/frigate#8017]
Describe what you are trying to accomplish and why in non technical terms
I'd like to leverage the scalability of cloud storage while still retaining local processing.

****Describe the solution you'd like****
I'd like to leverage a FUSE adapter like Goofys or Blobfuse2 to abstract public cloud storage from Azure or AWS to store my recordings and clips. I've attempted to configure storage in this manner with a local ramdisk as a buffer and the results have been poor. Has anyone seriously explored doing this? 

The experience causes lots of clips to be skipped. I suspect this is because the IO pattern coming from the frigate engine is serial in nature. It would be great if the IO could be parallelized to better allow for object as a backing store.

**Comment by NickM-27** [comment]
Did you try this with 0.13 beta? Because the recordings management has been enhanced in many ways. 

I run frigate in Unraid which writes to a volume that is a paring of an SSD and HDD using fuse.fs and it works really well
