### ISSUE TITLE
[PTZ] TRACKING, option to call the preset on stratup

### ISSUE THREAD

**Issue by CurseStaff** [blakeblackshear/frigate#8034]
it would be interesting to be able to obtain an option to be able to call the autotracking preset at startup,

in fact if freegate is restarted and it was tracking an object, the position of the camera will be in an unknown position,

unknown position which could make the view irrelevant, and not trigger new tracking if it is a very unfrequented place

**Comment by hawkeye217** [comment]
The autotracker makes no assumptions about the present state of the PTZ on startup. This might make sense if Frigate supported different zones or objects for different PTZ presets, for example. But at this point, a call to a specific preset at startup is probably best performed with an automation platform like Home Assistant.
