### ISSUE TITLE
Ability to export footage that wasn't an event (i.e. event that happens but isn't tagged)

### ISSUE THREAD

**Issue by jonofmac** [blakeblackshear/frigate#8058]
It would be nice to have the ability to be able to export a time range where an event/tag did not happen (either by lack of detection on Frigate's part, or deliberately avoiding detection in a region of no interest (such as my neighbor's yard).

I had an incident with one of my neighbors today. Apparently someone came by and stole their lawn furnature (right across the street from my house). "No problem" I say, since I have a camera aimed at my front yard (and also the street). 

I don't log events of cars or people in the street, because then I'd get bombarded with events as our street is busy. I only tag events where someone enters my property. However, I do keep a rolling 30 day footage of all my cameras for events just like this. So I was able to find where the footage was. However, I'm just viewing the footage in the regular time viewer. THere is no way to export this footage that I can find in the UI. Seems that you can only save/export events that are tagged as an event.

I found where frigate seems to store the raw footage, but it is saving it in 5 second clips in folders with UTC time stamps I'm guessing (because they don't match my local time stamps), so building the sequence of clips is a bit involved.

**Comment by NickM-27** [comment]
This is already implemented in 0.13

**Comment by jonofmac** [comment]
Ah. Guess it's time to install 13 beta then. Normally stick to stable releases. Thanks.
