### ISSUE TITLE
[Support]: What is a face

### ISSUE THREAD

**Issue by ehn** [blakeblackshear/frigate#8060]
### Describe the problem you are having

When labeling objects in Frigate+, what should we consider a face? For example, when running my Frigate+ model, it detects the back of a head as a face:

![snapshot](https://github.com/blakeblackshear/frigate/assets/179446/a6f3de73-76b7-484a-9b9b-93f509811f1f)

Should I consider this correct or a false positive?

### Version

0.13.0-0858859

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest ASH41-B

**Comment by NickM-27** [comment]
Currently attributes can't be labeled as a false positive, but I would submit `this is a person` and not label the back of the head as `face`

**Comment by ehn** [comment]
Thanks!
