### ISSUE TITLE
Trying to figure out what the new Audio Detector is hearing compared to what I am hearing.

### ISSUE THREAD

**Issue by thewan056** [blakeblackshear/frigate#8078]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to figure out what frigate thinks it is hearing with the audio detector. I am trying some obvious sounds that I know what that sound is, but frigate is not detecting them no matter how sensitive I set it or the threshold of that specific sound type. It maybe possible that what it thinks it hears is different from what i think i heard.

**Describe the solution you'd like**
Maybe an option to enable all types of audio events in the config or maybe in the camera debug UI that temporarily enables it and a section in the debug camera UI that shows what it thinks it hears. Maybe the top 3 or the top 5 with the highest percentage. Then we can narrow it down and use them in the config. Right now I am putting everything I think is related to that sound which I feel is too excessive.

**Describe alternatives you've considered**
Filling out the config with 500+ types of sounds and seeing what sticks. I know, but I am a little desperate after trying out so many sound types and seeing my list slowly and slowly expand.

**Additional context**

**Comment by thewan056** [comment]
I was hoping for it to be part of the same debug ui for the current object detection instead of requiring users to wade through logs but i guess this is ok too.

**Comment by NickM-27** [comment]
that would require a lot more data to be sent constantly via mqtt / webscoket which is inefficient and doesn't match other existing MQTT paradigms
