### ISSUE TITLE
Issues in virtual machine

### ISSUE THREAD

**Issue by rourke750** [blakeblackshear/frigate#81]
Hi I am running on a virtual machine and the vm being run is debian 9. I am getting this error after passing the device to the vm:
On connect called
Traceback (most recent call last):
  File "detect_objects.py", line 99, in <module>
    main()
  File "detect_objects.py", line 57, in main
    prepped_frame_queue
  File "/opt/frigate/frigate/object_detection.py", line 32, in __init__
    self.engine = DetectionEngine(PATH_TO_CKPT)
  File "/usr/local/lib/python3.6/dist-packages/edgetpu/detection/engine.py", line 72, in __init__
    super().__init__(model_path)
  File "/usr/local/lib/python3.6/dist-packages/edgetpu/basic/basic_engine.py", line 40, in __init__
    self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
RuntimeError: Error in device opening (/sys/bus/usb/devices/2-1)!

Any idea?

**Comment by blakeblackshear** [comment]
It's really hard to say without knowing the specifics of your setup. I would see if you can get the examples from the coral getting started guide to work.

**Comment by rourke750** [comment]
Is the recommended setup with a raspberypi?  I do have one laying around and it wouldn't be too much trouble to use instead.

**Comment by blakeblackshear** [comment]
A raspberry pi works OK for low frame rates and 1 or 2 cameras. I don't publish a raspberry pi container, so you will have to build it yourself.

**Comment by tubalainen** [comment]
> Hi I am running on a virtual machine and the vm being run is debian 9. I am getting this error after passing the device to the vm:
> On connect called
> Traceback (most recent call last):
> File "detect_objects.py", line 99, in
> main()
> File "detect_objects.py", line 57, in main
> prepped_frame_queue
> File "/opt/frigate/frigate/object_detection.py", line 32, in **init**
> self.engine = DetectionEngine(PATH_TO_CKPT)
> File "/usr/local/lib/python3.6/dist-packages/edgetpu/detection/engine.py", line 72, in **init**
> super().**init**(model_path)
> File "/usr/local/lib/python3.6/dist-packages/edgetpu/basic/basic_engine.py", line 40, in **init**
> self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
> RuntimeError: Error in device opening (/sys/bus/usb/devices/2-1)!
> 
> Any idea?

I have tried that as well, it doesnt work.

The Coral USB dongle is not a "normal USB dongle" but rather a TPU. It is not possible to forward USB based TPUs (or USB based GPUs) to a virtual machine. There is not much info on the topic out there, but I managed to find some info that pointed to my conclusion.

I scrapped my VM plan and bought a second hand laptop with USB 3 port instead. I run Debian straight on the machine for frigate and some other dockers as well.

I run three cameras with 1080p resolution and a frame rate of 15 fps. The core i5 machine is running at 60% CPU load. It provides some heating to my man cave out in the garage... ;)

**Comment by scstraus** [comment]
I also failed to run this on a VM, it's good to know that it wasn't just my incompetence.

**Comment by dvbit** [comment]
:-( experiencing the same. Dongle is seen in guest machine but with Global Unichip Vendor ID an Product ID . Not google's one.
Worked flawlessly on bare metal.
I have not found any solution.

**Comment by scstraus** [comment]
Some people have gotten it to work on proxmox (see forums), but generally VM's and Coral are a bad combination. I would suggest moving to a docker based architecture if you can. VM's are used for way too many things that can be handled better by docker with lower resource usage anyway. So unless you must run a linux kernel on a windows box or vice versa, I'd suggest just to install linux and run everything in docker. There's docker versions of almost everything these days.
