### ISSUE TITLE
Cleanup cache prior generating new clip

### ISSUE THREAD

**Issue by fliespl** [blakeblackshear/frigate#8101]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to download all events using api, but it's not working as expected when iterating them since cache get full (even though it deletes files every 5 minutes). I don't want to build tmps of 10GB size :)

**Describe the solution you'd like**
If "expected" filesize from clip generation is bigger than free space - do more "aggresive" deletion from temp cache.

**Describe alternatives you've considered**
Currently just retrying api calls until status is 200 (events/{ITEM_ID}/clip.mp4)

**Additional context**
Happy to provide if asked more specifically :)

**Comment by NickM-27** [comment]
the problem is we don't know when the file is done being downloaded. Just because the file is generated doesn't mean the client is finished downloading it yet. If you really want to export every event then I'd suggest using the new export api in 0.13 and not the clip api

**Comment by fliespl** [comment]
@NickM-27 that's understandable, that's why I would suggest deleting least recently used/created files. Also - most of the webservers will keep file in my memory/lock during download which is in progress. So it might work.

Either way - I will checkout export api, when 0.13 becomes stable! :)

**Comment by NickM-27** [comment]
> Also - most of the webservers will keep file in my memory/lock during download which is in progress. So it might work.

it won't, we specifically stop this from happening because otherwise the RAM is used forever by the file descriptor from nginx and it causes OOM exceptions. 

> Edit: export api would probably fall into the same circumstanes after skimming through code.

no it wouldn't, export API does not use RAM
