### ISSUE TITLE
[feature request] Obtain stream, snapshot for any arbitrary time

### ISSUE THREAD

**Issue by MEntOMANdo** [blakeblackshear/frigate#816]
Feature request: Amend these two endpoints

```
/clips/<camera>-<id>.mp4
/clips/<camera>-<id>.jpg
```

to allow a parameter of `start_time=1613784237` [with or without milliseconds]

This will return a stream starting that moment in time, without the user needing to know anything about which event might be involved. This would only be available if a recording exists, of course. So in the case of 24x7 NVR, or for a timestamp that corresponds to an event that was recorded.

The other endpoint would return a single snapshot of the frame immediately after the timestamp.

Use cases: 
- hear a sound, quickly grab a 5-sec replay of the yard
- receive notice on phone of an alert, but it occurred 5 min ago. Go grab a 15-sec review of what happened before that alert.
- to enable additional AI analysis, another program could start grabbing some frames upon receiving an mqtt msg --plus have the ability to get a few seconds before the alert from another camera, for example

Someday we can add additional parameters:
`speed=100` to allow speedup/slowdown of the stream, etc.
`end_time=1613784247`  to deliver a pre-packaged clip
`stream=<x>` specify main or substream, if we are recording multiple streams

**Comment by MEntOMANdo** [comment]
Not stale

**Comment by blakeblackshear** [comment]
These files are served directly from the file system. No code executes when serving them. I might consider adding an endpoint that will serve up the right 24/7 recording given a timestamp. Everything else will require lots of extra CPU to reencode.

**Comment by MEntOMANdo** [comment]
Yeah, the critical part was to get to the right file and a starting point from which to play, not the video playback. I didn't mean to imply we needed any transcoding. Whatever was recorded is what would be streamed. 

Alternatively, a simple API call would be to provide a source (camera name) plus 2 timestamps, start and end. Frigate would respond with a list of [clip filenames, start and stop] that covers the duration requested.

file5181.xyz  00022000 0042732
file5182.xyz 00000000 0000036

That's an example of a time period that spans 2 physical files. Once we know the files, a program could use ffmpeg to do anything we want with it.
