### ISSUE TITLE
Audio detection toggle turning on after a restart

### ISSUE THREAD

**Issue by towerhand** [blakeblackshear/frigate#8164]
**Describe what you are trying to accomplish and why in non technical terms**
I have an indoor camera that only detects and records when we are not home. So, I have an HA automation that turns on the toggles when we leave and turns them off when we return. If the toggle is off and I restart Frigate, the toggle is turned on instead of staying off.

**Describe the solution you'd like**
Frigate to respect the last known status instead of turning it on by default.

**Describe alternatives you've considered**
N/A

**Additional context**
This change would bring the behavior of the audio detection toggle to match the behavior of the detect, record, and snapshot toggles.

**Comment by NickM-27** [comment]
> This change would bring the behavior of the audio detection toggle to match the behavior of the detect, record, and snapshot toggles.

That is incorrect, as of 0.12 none of the toggles remember what was set before restart and this is the current expected behavior due to issues that occurred when the previous toggle was respected.

**Comment by towerhand** [comment]
Ok, what I see on my end is that the only toggle that comes back on after a restart is the audio detection toggle. The other three toggles stay off if they are off before I restart Frigate.

**Comment by NickM-27** [comment]
Then there is a retained field in MQTT that shouldn't be

**Comment by towerhand** [comment]
> 

> Then there is a retained field in MQTT that shouldn't be

Oh I see. Any suggestions to have frigate restore the toggles to what they were before a restart?

**Comment by NickM-27** [comment]
I don't know about to what they were before restart but I have an automation in HA that for example disables audio when frigate restarts.

**Comment by towerhand** [comment]
Ok, thanks. Are you using the sensor.frigate_status to running for the trigger? Or is there a better way?

**Comment by NickM-27** [comment]
I just use the status of the switch, when it goes from unavailable to any other status

**Comment by towerhand** [comment]
Thank you. I'm closing this.
