### ISSUE TITLE
[Advice request] 2-way audio Wired Doorbell Camera with local NVR that integrates with Home Assistant

### ISSUE THREAD

**Issue by Majestic7979** [blakeblackshear/frigate#8183]
What is the best video doorbell quality-wise that competes with the original Wired Nest Hello, but offers wired power, 24/7 recording, obviously a doorbell button (that ideally also has a relay, but not necessary), and 2-way audio?

I need something that basically emulates the Nest Hello (original, wired) but without going through the cloud or paying Google for a subscription. I don't use their facial recognition features, but I like their playback interface a lot... I hope that Frigate copies their UI for recording history and playback where you get a continuous timeline with little dots that grow in size according to the duration of the event.

I need something that will present a trigger to Home Assistant when the button is pushed so that I can create an automation to make a ring sound on the speakers around the house, push a notification to my phone, and allow me to conduct 2-way audio conversations. Ideally, I could also push pre-recorded messages to the doorbell's built-in speaker, like "we're not home" or "we are not interested", or "leave the package with the neighbor".

So, anything that has:
- good video quality, at a minimum it looks like the original Nest Hello
- 2-way audio
- can play back audio
- can integrate with Home Assistant
- generates event on Home Assistant when the button is pushed
- can have a clean RTSP feed for ingestion into Frigate
- does not require cloud, app or subscription to function (for example the UniFi doorbell requires a UniFi NVR)

**Comment by NickM-27** [comment]
This is generally best as a discussion instead of an issue. 

Personally, I really like my reolink doorbell, it passes all of your requirements

**Comment by Majestic7979** [comment]
> This is generally best as a discussion instead of an issue.
> 
> Personally, I really like my reolink doorbell, it passes all of your requirements

Totally missed the discussions at the top. I never used that before. Thanks for bringing to my attention. Can you link me the exact doorbell you're talking about please? I don't wanna buy something that ends up being the incorrect model.

**Comment by NickM-27** [comment]
REOLINK Video Doorbell PoE Camera – 180 Degree Diagonal, 5MP IP Security Camera Outdoor with Chime, 2-Way Talk, Plug & Play, Secured Local Storage, No Monthly Fee https://a.co/d/gXnWXW6

**Comment by Majestic7979** [comment]
Thanks Nick. Ordered the WiFi version that has a LAN port, no PoE but I'd rather have a WiFi backup just in case... will see how it goes. Is there any plan to introduce a playback UI like the Nest website has it? Their Playback/Events UI is freaking amazing, a breeze to browse through events:

<img width="1987" alt="image" src="https://github.com/blakeblackshear/frigate/assets/128995501/ee34c972-0cfb-49b2-ab69-e77555a075db">

Then you can zoom in and becomes even more granular, putting the mouse over any "event blob" on the timeline creates a nice thumbnail to show you what was happening in that particular event:

<img width="2138" alt="image" src="https://github.com/blakeblackshear/frigate/assets/128995501/25ec959e-d6ce-41f0-a8ab-1256dfe28f2e">

Currently that right sidebar on the Recordings screen is a nightmare to use, sorry it's not a criticism of anyone, it's only a comment about a UI that could become a whole lot more useful by just imitating what's been done already by a competitor.

I wanted to say, let's take Photoprism and Immich... they're both photo galleries with AI classification. While Photoprism tries to reinvent the wheel and is frustrating to use, Immich just literally tries to copy what Google Photos does, and it does it really well.

I wish that Frigate would become more like the home.nest.com website for browsing through events/recorded media. Nothing can beat the ease of use of their events timeline interface... Is there anything planned to make Frigate better in that respect? Because when you live in a urban UK townhouse with hundreds of people walking past your door every day, AI detection becomes complete useless. It's quite different than a US suburb where you have 10 ft of lawn before your door and can draw zones across to be ignored... but most of us in Europe living in urban areas have doors literally backing onto the sidewalk directly and zones don't work for that. So browsing timelines is usually the best way to find something. And being able to quickly browse like on the Nest website (not the app) is a huge time saver. They just make "blobs" variable in size within the timeline to represent event and duration.... but the timeline is basically infinitely scrolling.

The way we have to click event by event and change hour by hour and day by day manually in Frigate is a massive chore....

**Comment by NickM-27** [comment]
Frigate has been moving towards a better recording interface for many versions. The database at this point already includes information for each recording segment including if it had motion, object event, audio event, etc. along with improvements to the recordings APIs

The main thing left is just the UI itself. 

Blake also described this in more detail: https://github.com/blakeblackshear/frigate/discussions/6107#discussioncomment-5667712

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/issues/2230 is also relevant

**Comment by derekcentrico** [comment]
I'm considering running Ethernet to the doorbell spot if I can do so without much damage to walls. 

Curiously, any thoughts on rigging up this doorbell camera or any other camera to use the manual chime already in the house?
