### ISSUE TITLE
[Support]: recent dev build has broken intel QSV usage on System page - stuck at 1.0%

### ISSUE THREAD

**Issue by leccelecce** [blakeblackshear/frigate#8186]
### Describe the problem you are having

I downloaded a dev build about an hour ago, and noted on that System page that my intel GPU now always shows `1.0%` usage. Reverting back to 0.13.0-beta2 takes it back to ~30%.

dev-dcafcc1 still seems to be working (from ~5 days ago)
dev-9b687d7 does not (from ~2 days ago)

Haven't got time right now to narrow it down further; a few code changes in that area though

### Version

0.13.0 dev builds

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
...

    "gpu_usages": {
        "intel-qsv": {
            "gpu": "1.0%",
            "mem": "-%"
        }
    },

///
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by xconverge** [comment]
seeing the same thing with VAAPI, so it isnt qsv specific 🤷

**Comment by NickM-27** [comment]
I don't think this has anything to do with code changes, most likely the latest testing repo driver has a bug

**Comment by xconverge** [comment]
> I don't think this has anything to do with code changes, most likely the latest testing repo driver has a bug

That makes sense, I looked at the diff and didn't see anything obvious

Here are the hashes of the images where I noticed it went from working I think

working:               image: ghcr.io/blakeblackshear/frigate:dev-e1a6398
not-working:        image: ghcr.io/blakeblackshear/frigate:dev-4469507

**Comment by NickM-27** [comment]
The easiest thing would be to compare vainfo of working and non working image

**Comment by xconverge** [comment]
interesting!

<img width="696" alt="Screenshot 2023-10-15 at 9 38 00 PM" src="https://github.com/blakeblackshear/frigate/assets/4219348/933b6d30-e88b-4c35-ba73-727ef3b6698c">
<img width="709" alt="Screenshot 2023-10-15 at 9 36 35 PM" src="https://github.com/blakeblackshear/frigate/assets/4219348/f2c4205d-771f-4c47-8d99-fd1f3b4b6af0">

**Comment by xconverge** [comment]
dcafcc13206c472cbacce5535003b6cc6f190e0a works

9b687d77cedd5fd7956384da2e2e942ca12f46fa doesn't

Not sure why the build was failing between them so cant bisect further or understand how the build might be related?

**Comment by xconverge** [comment]
ah ok the intel_gpu_top output changed in the latest package and removed the /0 from the devices so the regex is no good anymore I think. I will open a PR

[old.json](https://github.com/blakeblackshear/frigate/files/12912538/old.json)
[new.json](https://github.com/blakeblackshear/frigate/files/12912536/new.json)

**Comment by NickM-27** [comment]
@xconverge I would not work on that, I still think we should pin the build to the older deps, otherwise this means that any new build can start having a breaking dependency

**Comment by xconverge** [comment]
@NickM-27 do we have a way of adding a test for this as a reminder so that we can catch it if/when it does inevitably changes/we need or want to update?

Might be hard without static test hw, I see we mock the response in a test, but perhaps we should put a log message when we hardcode the 1% so that savvy users will see it in the log?

**Comment by NickM-27** [comment]
not sure what you mean put a log message, with the PR I put up the deps are not pinned at the versions used in debian 12 and those won't dramatically change, in the future if the testing repo needs to be used again then that testing can be done as part of the beta testing

**Comment by NickM-27** [comment]
oh, yeah I think that is supposed to be a -1 which means error
