### ISSUE TITLE
[Support]: ¿Change nginx log level?

### ISSUE THREAD

**Issue by Cheerpipe** [blakeblackshear/frigate#8209]
### Describe the problem you are having

Not really a problem. ¿Is possible change nginx log level to something less verbose?

### Version

0.13

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Frigate stats

```json
Not relevant
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Not relevant

**Comment by NickM-27** [comment]
it is generally recommended to use the frigate webUI to view logs as they are separate depending on type (frigate, go2rtc, nginx). The default also helps to debug cases where users are seeing intermittent issues, and helps to see what devices are accessing frigate. 

technically you can change it by copying the nginx config and mounting your own with access logs off

**Comment by Cheerpipe** [comment]
Thanks for your suggestion. Copy, edit and mount /usr/local/nginx/conf/nginx.conf did the trick.
