### ISSUE TITLE
0.8.2 worse snapshot jpeg quality, possible to configure better?

### ISSUE THREAD

**Issue by bezpodstawny** [blakeblackshear/frigate#821]
In version 8.2, the size of the snapshot jpg files has been reduced. For some users this is important and for others it is less important. I have no problem with the size of the files, I have enough space, but the quality of the file is very important to me.
You've done a lot of work with this software, a lot. It would be pointless to spoil such an important matter.
I use your software to pass the image on to recognize the car's license plate. The quality of the file is of great importance to me. I notice a slight change in the quality of the file for the worse
Listen, I am replacing IP cameras from 4MP to 5MP or 8MP to have the best possible photo quality and here meanwhile such changes change worse.

**Please make it possible to decide in the configuration file what quality someone wants.** Not everyone needs a tiny file, there are those who need the best quality, for OCR in LPR, every pixel matters.

**If it is possible to configure the JPG files to be large and accurate again, please indicate it to me.**

**Comment by blakeblackshear** [comment]
I didn't see any meaningful difference in quality. Please post an example of before and after where quality is visibly worse.

**Comment by bezpodstawny** [comment]
[https://imgur.com/BBQW4C2](url)
[https://imgur.com/zt2Zqvs](url)

Original image:
[https://imgur.com/JzKl930](url)
[https://imgur.com/cS2YSq9](url)

**Comment by blakeblackshear** [comment]
What endpoint are you using for running OCR?

**Comment by bezpodstawny** [comment]
I am downloading image via http API using ID EVENTS after MQTT receives information from topic "Events" about the car.

Maybe I'm wrong but a few months ago saving pictures from mqtt directly was perfect. Virtually the same quality as rtsp from the camera. Then, after the possibility of downloading the image via http api appeared, I assumed it was the same. And suddenly in version 8.2 it got noticeably worse. It was easy to see because the effectiveness of OCR dropped significantly. I started looking and with my own eyes I noticed more Jpeg compression which looks like the pictures above.

**Comment by blakeblackshear** [comment]
You are using the snapshot.jpg endpoint?

**Comment by paularmstrong** [comment]
We did reduce the quality of JPEG _thumbnails_ that are produced. Are you using thumbnails or snapshots here? Those did not receive a change in JPEG quality

**Comment by blakeblackshear** [comment]
I went back and added it in other locations too.

**Comment by bezpodstawny** [comment]
Sample URL to get snapshoot:
http://192.168.32.61:5000/clips/{{{idcamera}}}-{{{idevent}}}.jpg

**Comment by htilly** [comment]
Hey guys.. This is quite an interesting topic!
Would there be any chance of actually implementing the "license plate" recognition in Frigate itself?
Would love to have two things: 
1: Statistics and history of "license plates" entering my driveway.
2: Have a MQTT event triggered with the actual license plate as a value in order to do external events (home automation).

This together with face recognition are the only things Im missing from Frigate right now.. And again, thanks for an awesome project!
