### ISSUE TITLE
Bounding Boxes on Camera feed?

### ISSUE THREAD

**Issue by scstraus** [blakeblackshear/frigate#822]
Just a quick FR to see if it's possible to get a camera feed that includes the bounding boxes? I use rather small cards on my home tablets and seeing the bounding boxes would help us to see if there's something we should pay attention to there.

**Comment by paularmstrong** [comment]
You can use the MJPEG feed for this: https://blakeblackshear.github.io/frigate/usage/api#apicamera_name

http://<your-ip>:5000/api/<camera_name>?bbox=1

**Comment by scstraus** [comment]
Great! Will try it.

**Comment by scstraus** [comment]
Wait, one more question I just thought of.. Is it okay to use the MJPG camera feed in Home Assistant as a camera? I recall with the old ones you didn't recomend it.

**Comment by HITChris** [comment]
The downside is that its very CPU intensive, which becomes exaggerated the more cameras you have.

**Comment by scstraus** [comment]
That was my fear.  I don't have the CPU to spare. Would it be possible to add to the RTMP feed without the overhead?

**Comment by paularmstrong** [comment]
No. Adding bounding boxes or anything requires a lot of processing and re-encoding the stream.

**Comment by scstraus** [comment]
Ok. What about for clips only?

**Comment by blakeblackshear** [comment]
Same thing. None of that can be modified without significant CPU usage to re-encode. The only place you can draw is in snapshots because the image is already decoded for processing and saving a single jpg isn't much overhead.

**Comment by scstraus** [comment]
Yeah not surprising.. Even with added CPU, though, I think it would be a very useful feature at least for clips, since I don't generate that many of them and I'm having a very hard time understanding how some objects are ending up in zones that look very far away, even after looking at the video. I think if I had a bounding box and zone in the clip I could see the strange ways it must be behaving to trigger certain zones and adjust accordingly. Probably not something I would leave on, but would be really helpful for debugging my setup. Would you mind me opening an FR for bounding boxes and zones on clips?

**Comment by blakeblackshear** [comment]
You can create one, but it would require a substantial re-architecture, and I don't think it is likely to be implemented anytime soon if ever. You would be better off taking sections from your 24/7 recordings and re-running them through frigate so you can watch.

**Comment by scstraus** [comment]
Okay. I would assume I can do the same with clips, yes (I don't use 24/7 recording)? How do I run them back through?

**Comment by blakeblackshear** [comment]
I'm working on some developer docs where I will show how to run frigate against a local file in an infinite loop. That's how I test during development so I don't have to run outside after every code change.

**Comment by blakeblackshear** [comment]
Feel free to try this out if you want: https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/contributing.md#core

**Comment by scstraus** [comment]
Cool, so as I don't need to modify the code, it seems that I can just use my existing instance and point it to a config file that has something like the below, yes?

```
mqtt:
  host: mqtt

cameras:
  test:
    ffmpeg:
      inputs:
        - path: /media/frigate/car-stopping.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
            - rtmp
            - clips
    height: 1080
    width: 1920
    fps: 5
    ```

**Comment by blakeblackshear** [comment]
Yes. You can add an additional camera that will run detection on the same file over and over. Just make sure you disable snapshots and clips for the camera to avoid events in the database.

**Comment by HITChris** [comment]
> Feel free to try this out if you want: https://github.com/blakeblackshear/frigate/blob/release-0.9.0/docs/docs/contributing.md#core

I'm having rookie troubles with step #4. I cloned the repo on a headless linux box, and am using Remote-SSH: Connect to Host from VSC on W10.... but upon connecting & opening folder /frigate_dev, I'm not being prompted to load it in a container. Am I supposed to instead be using VSC on a non-linux headless (and thus opening a 'local' folder)?

**Comment by blakeblackshear** [comment]
I haven't tried that specific setup, but I think there is a way to connect to a remote container on another machine. I would look into the docs for remote containers for vscode.

**Comment by blakeblackshear** [comment]
Also, make sure you have the release-0.9.0 branch checked out.

**Comment by HITChris** [comment]
Just to be clear, your personal setup is VSC + docker on a single linux server? Thanks man.

**Comment by blakeblackshear** [comment]
I develop on a Dell xps with Linux installed.

**Comment by HITChris** [comment]
Switching to W10/WSL made this much simpler, thanks.

**Comment by Sloth-on-meth** [comment]
definitely would love this feature, running on a specced out machine that can 100% handle it
