### ISSUE TITLE
Config Validator Option

### ISSUE THREAD

**Issue by rtrox** [blakeblackshear/frigate#8221]
**Describe what you are trying to accomplish and why in non technical terms**
I'm looking to build some automation to validate my frigate config prior to landing in my IaaC setup. Currently, config validation is a pretty tough prospect, as I need to run the entire frigate app to do so.

**Describe the solution you'd like**
I would love a simple `--validate` option which just runs `init_config` or `FrigateConfig.parse_file()` so that we can use the exit code as an indicator of validity.

**Describe alternatives you've considered**
The alternative here would be for me to build a separate small python utility which imports `FrigateConfig` and runs validation with frigate's validator. I'd be happy to do this, but I think this is likely something other folks, at least those self-hosting in k8s, would find useful, so I'd love to see it upstream.

**Additional context**
I'm actually happy to submit a PR for this, but I'd love 1) A nod that the frigate team thinks this is a good idea that they would consider, and 2) some direction on which flagging library you prefer, as it looks like frigate currently takes no flags or subcommands (argparse, click, etc).

**Comment by NickM-27** [comment]
This is already supported, as well as an endpoint to change specific values in the config and validate / save

https://github.com/blakeblackshear/frigate/blob/cd35481e92f206119874c5e0acabaf9dca12de8d/frigate/http.py#L1082

all that is needed is to be added to the docs

**Comment by rtrox** [comment]
Hey @NickM-27 - I may be being dense, but this looks an option to validate/save a new config against a running instance via HTTP, right?

To use this from CI/CD, a user would need to either:
A) Make their Frigate Instance accessible from their CI/CD pipeline. For use in GitHub Actions, as an example, this is a non-starter for me, and I would assume most folks self-hosting this at their homes.
B) Spin up a running Frigate instance inside the pipeline, and make an HTTP request to it, which is somewhat cumbersome to manage as part of a GitHub action.

Would it be possible to consider allowing the binary to be used as a validator as I propose in #8222?

**Comment by NickM-27** [comment]
I don't think the use case was made clear before, now I understand you are essentially trying to take a commit to the config file and then have that trigger a pipeline which validates the config and if it is valid then apply that config to the running instance?

**Comment by rtrox** [comment]
yep! Exactly :-) I like much of the k8s-at-home community use Frigate in Kubernetes, and deploy my frigate config as a configmap. I'd like to set up a GitHub action to validate any changes to my frigate config prior to deploying the new configmap and bouncing the service, as any typos result in a crash loop
