### ISSUE TITLE
Allow specifying the birdseye feed

### ISSUE THREAD

**Issue by jpettitt** [blakeblackshear/frigate#8226]
**Describe what you are trying to accomplish and why in non technical terms**
I wat to be able to use the lower res feeds for creating the birdseye mosaic cine I have all cams all the time sending it 2k feeds is a waste of resource.

**Describe the solution you'd like**
specify which feed to use for birdseye in the same way as for other features

**Describe alternatives you've considered**
running a second frigate withe no object detection that only has low res feed and only generates birdseye

**Additional context**
I'm getting occasional image issue in birdssys withe 7 2k cameras live.

**Comment by NickM-27** [comment]
birdseye requires the stream to be decoded, so it will always use the detect stream

**Comment by jpettitt** [comment]
ah ok.
