### ISSUE TITLE
[Support]: running npm dev

### ISSUE THREAD

**Issue by tpjanssen** [blakeblackshear/frigate#8231]
### Describe the problem you are having

I try to run the npm dev. I had no trouble in doing npm install, no errors reported while running npm dev:

![image](https://github.com/blakeblackshear/frigate/assets/25168870/58fd1505-5980-4db3-b751-34c7efa7b006)

I changed the `baseUrl.js` file to this:

```
export const baseUrl = "http://192.168.10.140:5000/" || `${window.location.protocol}//${window.location.host}${window.baseUrl || '/'}`;
```

If I open the web page, all I see is this:

![image](https://github.com/blakeblackshear/frigate/assets/25168870/a01dd240-0e68-4b5f-8ba9-3955e6350048)

Is there a way to connect to a running instance inside my network?

### Version

0.13.0 beta2

### Frigate config file

```yaml
Not relevant
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by tpjanssen** [comment]
The issue is CORS related...

**Comment by blakeblackshear** [comment]
Don't change the base url. Change the address in the vite config file.

**Comment by tpjanssen** [comment]
Is there a reason why /vod and /exports are not in the vite config file?

**Comment by NickM-27** [comment]
Not sure what you mean, there's no need for it to be because they are directly from nginx not frigate

**Comment by blakeblackshear** [comment]
He is referring to the vite proxy during development. I just didnt think to add them at the time. Probably a good idea to do so.

**Comment by tpjanssen** [comment]
Added in this [#8490](https://github.com/blakeblackshear/frigate/pull/8490) PR.
