### ISSUE TITLE
[frigate+] — UX Improvements to Optimize for Speed

### ISSUE THREAD

**Issue by johnmarksilly** [blakeblackshear/frigate#8235]
**Describe what you are trying to accomplish and why in non technical terms**
I want to speed up the task of annotating images. This could be in the form of more keyboard shortcuts, mouse shortcuts, and a faster UX in general. 

**Describe the solution you'd like**
A toolbar to activate annotation functions. 

**Toolbar**
- A selection tool that you can pin to a specific label. This would allow you to keep making annotations of the same time without the dialog interrupting the flow

**Mouse Shortcuts**
- Hold the right mouse button to display a context menu to select a new label type. This would allow you to continue to use the selection/annotation tool without needing to move to the keyboard or open a dialog. 

**Describe alternatives you've considered**
N/A

**Additional context**
Some great uses of keyboard and mouse shortcuts can be found in tools like Blender or other CAD software due to them optimizing work flow.

**Comment by blakeblackshear** [comment]
I have this in my frigate+ backlog now
