### ISSUE TITLE
Info: Custom TensorRT Issue with frigate-0.13-beta

### ISSUE THREAD

**Issue by 503Dev** [blakeblackshear/frigate#8242]
**Describe what you are trying to accomplish and why in non technical terms**
With Frigate 0.12 it was possible to generate custom models using the method outlined in the docs via running the Nvidia TensorRT docker image, I attempted to do this on 0.13.  I am not suggesting necessarily a new feature but this is something I think others will run into and could be useful as a note.  

**Describe the solution you'd like**
I would like to be able to generate custom models like before.  I do not actually plan to use them anymore as I want to go the Frigate+ route, but these observations can help someone else hopefully? 

**Additional context**
The previous Frigate documentation calls for using the following command to process custom tensorrt models:
```docker run --gpus=all --rm -it -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:22.07-py3 /tensorrt_models.sh```

This makes use of the _Nvidia TensorRT container 22.07_, models processed with this container will not work with Frigate 0.13-beta and will throw an error due to the unexpected TensorRT engine mismatch.

The most up to date container provided by Nvidia at this time is 23.01 (23.01-py3) which is bundled with TensorRT 8.5.2.2 ([Supporting Docs](https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel-23-01.html#rel-23-01))

The current version of frigate-0.13.0-beta1 and beta2 utilize the TensorRT version of [8.5.3](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/index.html#rel-8-5-3) and thus there is no viable way to generate custom tensorrt engines/models that will work at this time using the traditional / previous methods nor the recommended Nvidia method (aka their Docker container).

**Comment by NickM-27** [comment]
I'm not sure I understand the issue, the models are still generated the same as before but with newer library versions and using the python tools directly instead of being run externally in docker by the user. I'm not sure I see why that would hinder custom models from being created and usable.

**Comment by 503Dev** [comment]
@NickM-27 In the event of a custom model, assuming I have the weights like before, I would use the docker image.

Is there a new workflow for 0.13? I know 0.13 handles the standard models inside the container (which is awesome) and those can be specified using the flag in the _docker-compose_ file.  However, in the event that I have custom weights which I previously placed in the trt-models folder (then used the docker image to build the tensorrt engine), how would this be done now in 0.13? I am asking for others as I am moving to Frigate+ for obvious reasons including supporting the awesome work.

**Comment by Cheerpipe** [comment]
Try with:

`docker run --gpus=all --rm -it -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:23.03-py3 /tensorrt_models.sh`

This image has the correct TensorRT version.

**Comment by NateMeyer** [comment]
TensorRT 8.5.3 is available in 23.03. You could try that one, but some of the other libraries may not match. 

See the full table of versions here:
https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

**Comment by 503Dev** [comment]
Thank you both.  I get additional errors with 23.03 due to other components not matching.  It's not a big deal for me, I just wanted to raise the subject for others as this is likely to come up and custom models are already a sore spot for some due to their initial complexity.

**Comment by NickM-27** [comment]
I'm going to close this, I don't think there are any changes to be done on the frigate side to support this assuming the correct versions are shown. If anyone gets it going feel free to put up a PR to update the docs

**Comment by klutzzykitty** [comment]
@503Dev Hey! 
Stumbled upon this conversation while searching solutions for #8246 (Not using custom yolo modles currently) But thought it would be interesting to try later once I get a fix to current issue. 

Can you please share how you got the custom yolo running? 
I saw your other discussion #8240 with model labelmaps. How would you pass the model label map in config? 
should the existing labelmap.txt be removed and replaced with the new model's labelmap?
