### ISSUE TITLE
[HW Accel Support]: nVidia GT730

### ISSUE THREAD

**Issue by geezer500** [blakeblackshear/frigate#8252]
### Describe the problem you are having

GPUs under "System" claims that Hardware Acceleration has not been setup - Although it has been setup and appears to be working.
![frigate](https://github.com/blakeblackshear/frigate/assets/38993054/83864d53-95fc-4e9f-9340-c047db80594b)
![frigate2](https://github.com/blakeblackshear/frigate/assets/38993054/95bb5c00-dfdb-4db3-ab54-303de24f8538)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.96
  port: 1883
  user: xxx
  password: xxx
birdseye:
  width: 1920
  height: 1080
  mode: continuous
detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb
cameras:
  Driveway:
    ffmpeg:
      inputs:     
        - path: rtsp://xxx:xxx@192.168.1.230:554/stream1 
          roles:
            - record
        - path: rtsp://xxx:xxx@192.168.1.230:554/stream2
          roles:
            - detect
    detect:
      width: 640
      height: 360 
    record: # <----- Enable recording
      enabled: True
```

### docker-compose file or Docker CLI command

```yaml
docker create --name frigate \
  --restart=unless-stopped \
  -e PGID=1000 \
  -e PUID=1000 \
  -e TZ=Indian/Mauritius \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  --device /dev/dri/card0 \
  --gpus=all \
  --shm-size=64m \
  -v /mnt/Video:/media/frigate \
  -v /home/xxx/docker/frigate/config.yml/:/config/config.yml \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='xxx' \
  -p 5000:5000 \
  -p 1935:1935 \
ghcr.io/blakeblackshear/frigate:stable
```

### Relevant log output

```shell
2023-10-20 23:03:39.696166131  [INFO] Starting Frigate...
2023-10-20 23:03:41.323281841  [2023-10-21 02:03:41] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-20 23:03:41.363348101  [2023-10-21 02:03:41] peewee_migrate                 INFO    : Starting migrations
2023-10-20 23:03:41.370113838  [2023-10-21 02:03:41] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-20 23:03:41.397790905  [2023-10-21 02:03:41] detector.coral                 INFO    : Starting detection process: 289
2023-10-20 23:03:44.086997794  [2023-10-21 02:03:41] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-20 23:03:44.087162266  [2023-10-21 02:03:41] frigate.app                    INFO    : Output process started: 291
2023-10-20 23:03:44.087387060  [2023-10-21 02:03:41] frigate.app                    INFO    : Camera processor started for Driveway: 297
2023-10-20 23:03:44.087667676  [2023-10-21 02:03:41] frigate.app                    INFO    : Camera processor started for Utility: 299
2023-10-20 23:03:44.087962278  [2023-10-21 02:03:41] frigate.app                    INFO    : Camera processor started for Kitchen: 301
2023-10-20 23:03:44.088244544  [2023-10-21 02:03:41] frigate.app                    INFO    : Capture process started for Driveway: 302
2023-10-20 23:03:44.088760971  [2023-10-21 02:03:41] frigate.app                    INFO    : Capture process started for Utility: 303
2023-10-20 23:03:44.089044310  [2023-10-21 02:03:41] frigate.app                    INFO    : Capture process started for Kitchen: 308
2023-10-20 23:03:44.093477865  [2023-10-21 02:03:44] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### FFprobe output from your camera

```shell
Ffprobe Output

Stream 0: Return Code: 0
Video:
Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1440
FPS: 14/1
Audio:
Codec: PCM A-law / G.711 A-law

Stream 1: Return Code: 0
Video:
Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x360
FPS: 14/1
Audio:
Codec: PCM A-law / G.711 A-law
```

### Operating system

Debian

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Tapo TC65

### Any other information that may be helpful

I've setup a headless Debian 12 (Bookworm), and only installed docker and frigate.

I'm using an an Hp Gen10 Microserver AMD Opteron  X3418,an nVidia GT730 GPU, and a CORAL USB.
For the GT730 I  installed the latest drivers (for my card): "nvidia-tesla-470-driver" as recommended by "nvidia-detect".

I think the nVidia driver disabled the nouveau driver that was originally running.

Vainfo doesn't appear to work for either the nVidia card or the (AMD) vaapi (these both worked on an older ubuntu Plex installation) on the host OS.

I could not get either the onboard cpu gpu or the nvidia gpu to work by putting in "hwaccel_args: " with  "preset-nvidia-h264" or "preset-vaapi" into the frigate config.

After bashing into the container "nvidia-smi" the output was;
![frigate3](https://github.com/blakeblackshear/frigate/assets/38993054/b2b8cac8-724a-4dca-83a9-07a03b47646e)

and the output to "ffmpeg -decoders | grep cuvid" was;
![frigate4](https://github.com/blakeblackshear/frigate/assets/38993054/daf06eb7-c23f-48de-a4f2-e6532bcf7444)

I put "cuda"  as "hwaccel_args: ", and I got a picture with no errors in the logs.

Everything appears to working OK (this is my 1st install so I don't know what to expect) .
It's recording fine.
I just don't know if hardware acceleration is working or not?
Should I get vainfo working to make sure that hardware is working? Or is actually working, just that vainfo doesn't display it?

Thanks

**Comment by NickM-27** [comment]
You have not added the ffmpeg preset for hwaccel args, so hardware acceleration has not been setup

**Comment by NickM-27** [comment]
This is covered in the docs here https://docs.frigate.video/configuration/hardware_acceleration#setup-decoder

**Comment by geezer500** [comment]
Thank you NickM-27,

I had read that section, but I think I was putting a dash in front of the "preset-nvidia-h264". My error...

It now shows "NVIDIA GeForce GT 730" under GPUs although vainfo still gives the same error and "nvidia-smi" shows no running  ffmpeg processes.

**Comment by NickM-27** [comment]
Vainfo is not used for nvidia so this is expected. Where are you checking nvidia-smi

**Comment by geezer500** [comment]
Hi NickM-27,

Thanks again for your prompt replies :-)

I tried "vainfo" in both the host and the container as well as the button under "system" in the frigate GUI.
I didn't know that it didn't work for nvidia, another USER error.... sorry :-(

I thought it might have picked up the AMD HA on the CPU, although I believe the the nouveau drivers were disabled by the nvidia installation, so this may have affected it as well.

I had actually put  "hwaccel_args: cuda" instead of "hwaccel_args: preset-nvidia-h264" and that worked (although GPU didn't display under "System").
Is that another type of hardware acceleration?

Thx 

![frigate5](https://github.com/blakeblackshear/frigate/assets/38993054/d17ebab3-414b-4239-8ea5-661c139a0634)

P.s I think everything seems to be working fine now (it records and gives no errors in the logs), so you may close this.

Thanks

**Comment by NickM-27** [comment]
cuda is accepted but it does not actually engage the gpu in the way that frigate uses it
