### ISSUE TITLE
[Config Support]: Event viewer no longer works on phone, except for AD410 frontdoor camera.

### ISSUE THREAD

**Issue by Oakley707** [blakeblackshear/frigate#8253]
### Describe the problem you are having

I've noticed that after the last update, I'm no longer able to view events while on my mobile device for all but one camera, the AD410 frontdoor camera.  All other camera streams say network error / playback issue while on the phone.  This happens while viewing thru Frigate UI directly or even thru HA integration.  If I view the same event on my laptop, 0 issues.  All playback works.  I've checked high and low as to why this would be the case, but no idea.  I've tried Edge and Chrome on my phone with no luck.  Video codecs are all the same H.264 and the only difference is the resolution being 2k in lieu of 4k for my other cameras.

### Version

0.12.1-367D724

### Frigate config file

```yaml
#frigate sample config.yml
mqtt:
  host: 192.168.1.149
  port: 1883
#environment_vars:
#  LIBVA_DRIVER_NAME: i965
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
#  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
#  client_id: frigate
  # Optional: user
#  user: mqtt user here
  # Optional: 
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
#  password: mqtt pass here
  # Optional: interval in seconds for publishing stats (default: shown below)
#  stats_interval: 60

#record:
#  enabled: true
#  retain_days: 0
#  events:
#    retain:
#      default: 10

# Optional: birdseye configuration
#birdseye:
  # Optional: Enable birdseye view (default: shown below)
#  enabled: True
  # Optional: Width of the output resolution (default: shown below)
#  width: 3840
  # Optional: Height of the output resolution (default: shown below)
#  height: 2160
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
#  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: pci

#logger:
#  default: info
#  logs:
#    frigate.event: logger

#objects:
#  track:
#    - person
#    - car
#    - cat
#    - dog

snapshots:
  enabled: True
  timestamp: True
  crop: False
  height: 175
  retain:
    default: 10

ffmpeg:
  hwaccel_args: preset-vaapi
  
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 1080
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 1

# Optional: in-feed timestamp style configuration
# NOTE: Can be overridden at the camera level
#timestamp_style:
  # Optional: Position of the timestamp (default: shown below)
  #           "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
#  position: "tl"
  # Optional: Format specifier conform to the Python package "datetime" (default: shown below)
  #           Additional Examples:
  #             german: "%d.%m.%Y %H:%M:%S"
#  format: "%m/%d/%Y %H:%M:%S"
  # Optional: Color of font
#  color:
    # All Required when color is specified (default: shown below)
#    red: 255
#    green: 255
#    blue: 255
  # Optional: Line thickness of font (default: shown below)
#  thickness: 2
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
#  effect: None

cameras:

  sidebackyard:
    ffmpeg:
      inputs:
        - path: rtsp://X:X@192.168.1.108:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://X:X@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 720
      height: 1280
      fps: 10
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    objects:
      track:
        - person
        - cat
        - dog

  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://X:X@192.168.1.140:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://X:X@192.168.1.140:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 720
      height: 1280
      fps: 10
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    objects:
      track:
        - person
        - cat
        - dog

  frontdrive:
    ffmpeg:
      inputs:
        - path: rtsp://X:X@192.168.1.142:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://X:X@192.168.1.142:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    objects:
      track:
        - person
        - car
        - cat
        - dog

  frontdoor:
    ffmpeg:
      inputs:
 #       - path: rtsp://X:X@192.168.1.173:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
 #         roles:
 #           - detect
        - path: rtsp://X:X@192.168.1.173:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 2560
      fps: 10
    record:
      enabled: True
      retain:
        days: 4
        mode: all
    objects:
      track:
        - person
        - cat
        - dog      

  frontgarage:
    ffmpeg:
      inputs:
        - path: rtsp://X:X@192.168.1.138:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://X:X@192.168.1.138:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
    record:
      enabled: True
      retain:
        days: 4
        mode: all
    objects:
      track:
        - person
        - car
        - cat
        - dog

  sideyard:
    ffmpeg:
      inputs:
        - path: rtsp://X:X@192.168.1.139:554/cam/realmonitor?channel=1&subtype=2&unicast=true&proto=Onvif
          roles:
            - detect
        - path: rtsp://X:X@192.168.1.139:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 720
      height: 1280
      fps: 10
    record:
      enabled: True
      retain:
        days: 3
        mode: all
    objects:
      track:
        - person
        - cat
        - dog
```

### Relevant log output

```shell
10/20/2023
8:14:38 PM
2023-10-20 20:14:38.965523563  192.168.1.137 - - [20/Oct/2023:20:14:38 -0400] "GET /vod/event/1697840149.045136-zz7x7k/master.m3u8 HTTP/1.1" 200 165 "http://192.168.1.149:5000/events" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36" "-"
10/20/2023
8:14:38 PM
2023-10-20 20:14:38.977589389  192.168.1.137 - - [20/Oct/2023:20:14:38 -0400] "GET /vod/event/1697840149.045136-zz7x7k/index-v1.m3u8 HTTP/1.1" 200 171 "http://192.168.1.149:5000/events" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36" "-"
10/20/2023
8:14:39 PM
2023-10-20 20:14:39.148109113  192.168.1.137 - - [20/Oct/2023:20:14:39 -0400] "GET /vod/event/1697840149.045136-zz7x7k/seg-1-v1.ts HTTP/1.1" 200 19931384 "http://192.168.1.149:5000/events" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36" "-"
10/20/2023
8:14:39 PM
2023-10-20 20:14:39.684789701  192.168.1.137 - - [20/Oct/2023:20:14:39 -0400] "GET /vod/event/1697840149.045136-zz7x7k/master.m3u8 HTTP/1.1" 200 165 "http://192.168.1.149:5000/events" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36" "-"
10/20/2023
8:14:39 PM
2023-10-20 20:14:39.710332869  192.168.1.137 - - [20/Oct/2023:20:14:39 -0400] "GET /vod/event/1697840149.045136-zz7x7k/index-v1.m3u8 HTTP/1.1" 200 171 "http://192.168.1.149:5000/events" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36" "-"
10/20/2023
8:14:39 PM
2023-10-20 20:14:39.784953222  192.168.1.137 - - [20/Oct/2023:20:14:39 -0400] "GET /vod/event/1697840149.045136-zz7x7k/seg-1-v1.ts HTTP/1.1" 200 19931384 "http://192.168.1.149:5000/events" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36" "-"
10/20/2023
8:14:45 PM
2023-10-20 20:14:45.202591374  192.168.1.149 - - [20/Oct/2023:20:14:45 -0400] "GET /api/stats HTTP/1.1" 200 4420 "-" "HomeAssistant/2023.10.3 aiohttp/3.8.5 Python/3.11" "-"
10/20/2023
8:14:47 PM
2023-10-20 20:14:47.069701337  192.168.1.7 - - [20/Oct/2023:20:14:47 -0400] "GET /api/config HTTP/1.1" 200 22744 "http://192.168.1.149:5000/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46" "-"
10/20/2023
8:14:47 PM
2023-10-20 20:14:47.070537215  192.168.1.7 - - [20/Oct/2023:20:14:47 -0400] "GET /api/config/raw HTTP/1.1" 200 1765 "http://192.168.1.149:5000/config" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46" "-"
10/20/2023
8:14:50 PM
2023-10-20 20:14:50.335643585  192.168.1.7 - - [20/Oct/2023:20:14:50 -0400] "GET /api/logs/frigate HTTP/1.1" 200 530 "http://192.168.1.149:5000/logs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46" "-"
10/20/2023
8:14:50 PM
2023-10-20 20:14:50.338302569  192.168.1.7 - - [20/Oct/2023:20:14:50 -0400] "GET /api/logs/go2rtc HTTP/1.1" 200 256 "http://192.168.1.149:5000/logs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46" "-"
10/20/2023
8:14:50 PM
2023-10-20 20:14:50.339052521  192.168.1.7 - - [20/Oct/2023:20:14:50 -0400] "GET /api/logs/nginx HTTP/1.1" 200 6438 "http://192.168.1.149:5000/logs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.46" "-"
10/20/2023
8:14:54 PM
2023-10-20 20:14:54.202760231  192.168.1.149 - - [20/Oct/2023:20:14:54 -0400] "GET /api/stats HTTP/1.1" 200 4424 "-" "HomeAssistant/2023.10.3 aiohttp/3.8.5 Python/3.11" "-"
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2

**Comment by digiblur** [comment]
Same issue even on the Reolink POE doorbell that isn't 4K and that one is fed through go2rtc too per the Frigate docs.

**Comment by NickM-27** [comment]
If you are using chrome then you can open `chrome://media-internals`

0.12.1 has been out for many months and no one else has reported this issue so it's most likely something isolated or some chrome issue. 

@digiblur reolink doorbell is working as expected for me so same  advice as above

**Comment by Oakley707** [comment]
{
  "6:0": {
    "id": "6:0",
    "properties": {
      "render_id": 6,
      "player_id": 0,
      "created": "2023-10-21 00:14:37.206 UTC",
      "origin_url": "http://192.168.1.149:5000/",
      "kFrameUrl": "http://192.168.1.149:5000/events",
      "kFrameTitle": "Frigate",
      "url": "blob:http://192.168.1.149:5000/f113e1ad-f163-4f40-aff4-f5188bfad78d",
      "kTextTracks": [],
      "info": "Using a coded size alignment of 128x2",
      "kRendererName": "RendererImpl",
      "pipeline_state": "kStopped",
      "kVideoTracks": [
        {
          "alpha mode": "is_opaque",
          "codec": "h264",
          "coded size": "2560x1920",
          "color space": {
            "matrix": "BT709",
            "primaries": "BT709",
            "range": "LIMITED",
            "transfer": "BT709"
          },
          "encryption scheme": "Unencrypted",
          "has extra data": false,
          "hdr metadata": "unset",
          "natural size": "2560x1920",
          "orientation": "0°",
          "profile": "h264 baseline",
          "visible rect": "0,0 2560x1920"
        }
      ],
      "debug": "Video rendering in low delay mode.",
      "event": "kWebMediaPlayerDestroyed",
      "kIsVideoDecryptingDemuxerStream": false,
      "kVideoDecoderName": "MediaCodecVideoDecoder",
      "kIsPlatformVideoDecoder": true,
      "duration": 17.523966,
      "dimensions": "2560x1920",
      "kResolution": "2560x1920",
      "pipeline_buffering_state": {
        "for_suspended_start": false,
        "state": "BUFFERING_HAVE_ENOUGH"
      }
    },
    "allEvents": [
      {
        "time": 0,
        "key": "created",
        "value": "2023-10-21 00:14:37.206 UTC"
      },
      {
        "time": 0.9679999351501465,
        "key": "origin_url",
        "value": "http://192.168.1.149:5000/"
      },
      {
        "time": 0.9749999046325684,
        "key": "kFrameUrl",
        "value": "http://192.168.1.149:5000/events"
      },
      {
        "time": 0.9769999980926514,
        "key": "kFrameTitle",
        "value": "Frigate"
      },
      {
        "time": 1.2379999160766602,
        "key": "url",
        "value": "blob:http://192.168.1.149:5000/f113e1ad-f163-4f40-aff4-f5188bfad78d"
      },
      {
        "time": 1.24399995803833,
        "key": "kTextTracks",
        "value": []
      },
      {
        "time": 1.2659999132156372,
        "key": "info",
        "value": "ChunkDemuxer"
      },
      {
        "time": 1.2730000019073486,
        "key": "kRendererName",
        "value": "RendererImpl"
      },
      {
        "time": 4.976999998092651,
        "key": "pipeline_state",
        "value": "kStarting"
      },
      {
        "time": 978.6289999485016,
        "key": "kVideoTracks",
        "value": [
          {
            "alpha mode": "is_opaque",
            "codec": "h264",
            "coded size": "2560x1920",
            "color space": {
              "matrix": "BT709",
              "primaries": "BT709",
              "range": "LIMITED",
              "transfer": "BT709"
            },
            "encryption scheme": "Unencrypted",
            "has extra data": false,
            "hdr metadata": "unset",
            "natural size": "2560x1920",
            "orientation": "0°",
            "profile": "h264 baseline",
            "visible rect": "0,0 2560x1920"
          }
        ]
      },
      {
        "time": 979.2139999866486,
        "key": "debug",
        "value": "Video rendering in low delay mode."
      },
      {
        "time": 983.5230000019073,
        "key": "info",
        "value": "Effective playback rate changed from 0 to 1"
      },
      {
        "time": 983.8969999551773,
        "key": "event",
        "value": "kPlay"
      },
      {
        "time": 986.9199999570847,
        "key": "kIsVideoDecryptingDemuxerStream",
        "value": false
      },
      {
        "time": 986.9239999055862,
        "key": "kVideoDecoderName",
        "value": "MediaCodecVideoDecoder"
      },
      {
        "time": 986.9259999990463,
        "key": "kIsPlatformVideoDecoder",
        "value": true
      },
      {
        "time": 986.9599999189377,
        "key": "info",
        "value": "Selected MediaCodecVideoDecoder for video decoding, config: codec: h264, profile: h264 baseline, level: not available, alpha_mode: is_opaque, coded size: [2560,1920], visible rect: [0,0,2560,1920], natural size: [2560,1920], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
      },
      {
        "time": 987.0729999542236,
        "key": "pipeline_state",
        "value": "kPlaying"
      },
      {
        "time": 77.26599991321564,
        "key": "duration",
        "value": 17.467
      },
      {
        "time": 1197.3099999427795,
        "key": "info",
        "value": "Created MediaCodec c2.android.avc.decoder, is_software_codec=1"
      },
      {
        "time": 1197.5759999752045,
        "key": "info",
        "value": "Using a coded size alignment of 128x2"
      },
      {
        "time": 1409.0569999217987,
        "key": "dimensions",
        "value": "2560x1920"
      },
      {
        "time": 1409.0820000171661,
        "key": "kResolution",
        "value": "2560x1920"
      },
      {
        "time": 1013.8249999284744,
        "key": "duration",
        "value": 17.523966
      },
      {
        "time": 1409.2229999303818,
        "key": "pipeline_buffering_state",
        "value": {
          "for_suspended_start": false,
          "state": "BUFFERING_HAVE_ENOUGH"
        }
      },
      {
        "time": 4151.207999944687,
        "key": "event",
        "value": "kWebMediaPlayerDestroyed"
      },
      {
        "time": 4151.191999912262,
        "key": "pipeline_state",
        "value": "kStopping"
      },
      {
        "time": 4152.509999990463,
        "key": "pipeline_state",
        "value": "kStopped"
      }
    ],
    "lastRendered": 0,
    "firstTimestamp_": 553421155.085
  },
  "6:1": {
    "id": "6:1",
    "properties": {
      "render_id": 6,
      "player_id": 1,
      "created": "2023-10-21 00:14:41.462 UTC",
      "origin_url": "http://192.168.1.149:5000/",
      "kFrameUrl": "http://192.168.1.149:5000/events",
      "kFrameTitle": "Frigate",
      "url": "blob:http://192.168.1.149:5000/26d07c7e-2e61-4202-9e16-ae509bf9ef07",
      "kTextTracks": [],
      "info": "Effective playback rate changed from 0 to 1",
      "kRendererName": "RendererImpl",
      "pipeline_state": "kStopped",
      "kVideoTracks": [
        {
          "alpha mode": "is_opaque",
          "codec": "h264",
          "coded size": "3840x2160",
          "color space": {
            "matrix": "BT709",
            "primaries": "BT709",
            "range": "LIMITED",
            "transfer": "BT709"
          },
          "encryption scheme": "Unencrypted",
          "has extra data": false,
          "hdr metadata": "unset",
          "natural size": "3840x2160",
          "orientation": "0°",
          "profile": "h264 main",
          "visible rect": "0,0 3840x2160"
        }
      ],
      "debug": "Video rendering in low delay mode.",
      "error": {
        "code": 15,
        "data": {},
        "group": "PipelineStatus",
        "message": "",
        "stack": [
          {
            "file": "media/renderers/video_renderer_impl.cc",
            "line": 304
          }
        ]
      },
      "event": "kWebMediaPlayerDestroyed",
      "duration": 36.304
    },
    "allEvents": [
      {
        "time": 0,
        "key": "created",
        "value": "2023-10-21 00:14:41.462 UTC"
      },
      {
        "time": 0.15199995040893555,
        "key": "origin_url",
        "value": "http://192.168.1.149:5000/"
      },
      {
        "time": 0.15400004386901855,
        "key": "kFrameUrl",
        "value": "http://192.168.1.149:5000/events"
      },
      {
        "time": 0.156000018119812,
        "key": "kFrameTitle",
        "value": "Frigate"
      },
      {
        "time": 0.2489999532699585,
        "key": "url",
        "value": "blob:http://192.168.1.149:5000/26d07c7e-2e61-4202-9e16-ae509bf9ef07"
      },
      {
        "time": 0.2560000419616699,
        "key": "kTextTracks",
        "value": []
      },
      {
        "time": 0.281000018119812,
        "key": "info",
        "value": "ChunkDemuxer"
      },
      {
        "time": 0.2879999876022339,
        "key": "kRendererName",
        "value": "RendererImpl"
      },
      {
        "time": 0.309999942779541,
        "key": "pipeline_state",
        "value": "kStarting"
      },
      {
        "time": 699.3129999637604,
        "key": "kVideoTracks",
        "value": [
          {
            "alpha mode": "is_opaque",
            "codec": "h264",
            "coded size": "3840x2160",
            "color space": {
              "matrix": "BT709",
              "primaries": "BT709",
              "range": "LIMITED",
              "transfer": "BT709"
            },
            "encryption scheme": "Unencrypted",
            "has extra data": false,
            "hdr metadata": "unset",
            "natural size": "3840x2160",
            "orientation": "0°",
            "profile": "h264 main",
            "visible rect": "0,0 3840x2160"
          }
        ]
      },
      {
        "time": 699.87399995327,
        "key": "debug",
        "value": "Video rendering in low delay mode."
      },
      {
        "time": 700.0199999809265,
        "key": "info",
        "value": "Cannot select MediaCodecVideoDecoder for video decoding"
      },
      {
        "time": 700.1030000448227,
        "key": "info",
        "value": "Cannot select VpxVideoDecoder for video decoding"
      },
      {
        "time": 700.2309999465942,
        "key": "info",
        "value": "Cannot select Dav1dVideoDecoder for video decoding"
      },
      {
        "time": 700.2799999713898,
        "key": "error",
        "value": "video decoder initialization failed"
      },
      {
        "time": 702.9279999732971,
        "key": "info",
        "value": "Effective playback rate changed from 0 to 1"
      },
      {
        "time": 702.9730000495911,
        "key": "event",
        "value": "kPlay"
      },
      {
        "time": 703.0649999380112,
        "key": "error",
        "value": {
          "code": 15,
          "data": {},
          "group": "PipelineStatus",
          "message": "",
          "stack": [
            {
              "file": "media/renderers/video_renderer_impl.cc",
              "line": 304
            }
          ]
        }
      },
      {
        "time": 705.7179999351501,
        "key": "pipeline_state",
        "value": "kStopping"
      },
      {
        "time": 705.738000035286,
        "key": "pipeline_state",
        "value": "kStopped"
      },
      {
        "time": 706.5429999828339,
        "key": "event",
        "value": "kPause"
      },
      {
        "time": 755.6280000209808,
        "key": "event",
        "value": "kWebMediaPlayerDestroyed"
      },
      {
        "time": 63.230000019073486,
        "key": "duration",
        "value": 36.304
      }
    ],
    "lastRendered": 0,
    "firstTimestamp_": 553425411.194
  },
  "6:2": {
    "id": "6:2",
    "properties": {
      "render_id": 6,
      "player_id": 2,
      "created": "2023-10-21 00:14:42.225 UTC",
      "origin_url": "http://192.168.1.149:5000/",
      "kFrameUrl": "http://192.168.1.149:5000/events",
      "kFrameTitle": "Frigate",
      "url": "blob:http://192.168.1.149:5000/2b685477-f25e-431b-815f-7d1440c1fb33",
      "kTextTracks": [],
      "info": "Effective playback rate changed from 0 to 1",
      "kRendererName": "RendererImpl",
      "pipeline_state": "kStopped",
      "kVideoTracks": [
        {
          "alpha mode": "is_opaque",
          "codec": "h264",
          "coded size": "3840x2160",
          "color space": {
            "matrix": "BT709",
            "primaries": "BT709",
            "range": "LIMITED",
            "transfer": "BT709"
          },
          "encryption scheme": "Unencrypted",
          "has extra data": false,
          "hdr metadata": "unset",
          "natural size": "3840x2160",
          "orientation": "0°",
          "profile": "h264 main",
          "visible rect": "0,0 3840x2160"
        }
      ],
      "debug": "Video rendering in low delay mode.",
      "error": {
        "code": 15,
        "data": {},
        "group": "PipelineStatus",
        "message": "",
        "stack": [
          {
            "file": "media/renderers/video_renderer_impl.cc",
            "line": 304
          }
        ]
      },
      "event": "kPause",
      "duration": 36.304
    },
    "allEvents": [
      {
        "time": 0,
        "key": "created",
        "value": "2023-10-21 00:14:42.225 UTC"
      },
      {
        "time": 0.125,
        "key": "origin_url",
        "value": "http://192.168.1.149:5000/"
      },
      {
        "time": 0.12899994850158691,
        "key": "kFrameUrl",
        "value": "http://192.168.1.149:5000/events"
      },
      {
        "time": 0.13099992275238037,
        "key": "kFrameTitle",
        "value": "Frigate"
      },
      {
        "time": 0.23199999332427979,
        "key": "url",
        "value": "blob:http://192.168.1.149:5000/2b685477-f25e-431b-815f-7d1440c1fb33"
      },
      {
        "time": 0.23500001430511475,
        "key": "kTextTracks",
        "value": []
      },
      {
        "time": 0.25599992275238037,
        "key": "info",
        "value": "ChunkDemuxer"
      },
      {
        "time": 0.2630000114440918,
        "key": "kRendererName",
        "value": "RendererImpl"
      },
      {
        "time": 0.3569999933242798,
        "key": "pipeline_state",
        "value": "kStarting"
      },
      {
        "time": 588.7039999961853,
        "key": "kVideoTracks",
        "value": [
          {
            "alpha mode": "is_opaque",
            "codec": "h264",
            "coded size": "3840x2160",
            "color space": {
              "matrix": "BT709",
              "primaries": "BT709",
              "range": "LIMITED",
              "transfer": "BT709"
            },
            "encryption scheme": "Unencrypted",
            "has extra data": false,
            "hdr metadata": "unset",
            "natural size": "3840x2160",
            "orientation": "0°",
            "profile": "h264 main",
            "visible rect": "0,0 3840x2160"
          }
        ]
      },
      {
        "time": 589.1610000133514,
        "key": "debug",
        "value": "Video rendering in low delay mode."
      },
      {
        "time": 589.2940000295639,
        "key": "info",
        "value": "Cannot select MediaCodecVideoDecoder for video decoding"
      },
      {
        "time": 589.3669999837875,
        "key": "info",
        "value": "Cannot select VpxVideoDecoder for video decoding"
      },
      {
        "time": 589.4290000200272,
        "key": "info",
        "value": "Cannot select Dav1dVideoDecoder for video decoding"
      },
      {
        "time": 589.4639999866486,
        "key": "error",
        "value": "video decoder initialization failed"
      },
      {
        "time": 590.3569999933243,
        "key": "info",
        "value": "Effective playback rate changed from 0 to 1"
      },
      {
        "time": 590.4909999370575,
        "key": "event",
        "value": "kPlay"
      },
      {
        "time": 590.6499999761581,
        "key": "error",
        "value": {
          "code": 15,
          "data": {},
          "group": "PipelineStatus",
          "message": "",
          "stack": [
            {
              "file": "media/renderers/video_renderer_impl.cc",
              "line": 304
            }
          ]
        }
      },
      {
        "time": 593.2519999742508,
        "key": "pipeline_state",
        "value": "kStopping"
      },
      {
        "time": 593.2949999570847,
        "key": "pipeline_state",
        "value": "kStopped"
      },
      {
        "time": 594.4589999914169,
        "key": "event",
        "value": "kPause"
      },
      {
        "time": 32.210999965667725,
        "key": "duration",
        "value": 36.304
      }
    ],
    "lastRendered": 0,
    "firstTimestamp_": 553426174.299
  }
}

I've tried on the Edge mobile browser as well, fwiw. Does the above make any sense to you?

**Comment by digiblur** [comment]
Here's so more info for the fun...  it works on this phone

![image](https://github.com/blakeblackshear/frigate/assets/3240875/12e24058-7d53-46f3-a30d-3f3bbf5ef4fe)

but not on this phone, only the AD410 doorbell video works on that, no 4K, no Reolink POE doorbell.

![image](https://github.com/blakeblackshear/frigate/assets/3240875/72f99d98-4968-45f8-bbb9-7d1e0dea5b8a)

**Comment by Oakley707** [comment]
Both of my phones are new, Pixel 8 and Pixel 8 pro... I wonder if that is the issue?

**Comment by digiblur** [comment]
I just tried it on the Pixel 7 Pro, same latest stock update of Android 14, it works fine.  Oddly enough I wonder if h265 works, and there's just some codec issue on the Pixel 8 build that happens to impact Frigate.

**Comment by NickM-27** [comment]
the profile for OPs camera is `"profile": "h264 baseline",` which would be a weird one for it to not support, but entirely possible

**Comment by Oakley707** [comment]
Any thoughts or workarounds?  Do any of the other mobile browsers use something different that would help identify for sure?

**Comment by NickM-27** [comment]
From what I can tell this definitely seems like a pixel 8 specific issue, given that other mobile and desktop devices work; and it hasn't been a problem reported by others. You could try downloading chrome beta and see if perhaps this issue is fixed there.

**Comment by Oakley707** [comment]
Appreciate the prompt responses.  I'd agree 100% that this doesn't appear to be Frigate related at all.  Just happened to noticed it because of Frigate.

**Comment by digiblur** [comment]
Use Chrome Beta. I just tried it and it works.

Now if I can figure out why the Reolink POE doorbell keeps dropping out of after the new update of Frigate. Off to go searching some threads here..

**Comment by Oakley707** [comment]
Just did the same.  Works great in Chrome beta...

**Comment by NicGray78** [comment]
+1 For Beta, couldn't playback events in Chrome Mac (Version 118.0.5993.96 (Official Build) (x86_64)) but could on Chrome Android. Works fine now Chrome Mac Beta (Version 118.0.5993.96 (Official Build) (x86_64)) even though the Widevine Content Decryption Module version seems the same on both...
