### ISSUE TITLE
add link to camera ui

### ISSUE THREAD

**Issue by ljmerza** [blakeblackshear/frigate#8325]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to in the cameras ui click a link that opens a new window to the camera's http webui so i can easily access it from frigate

**Describe the solution you'd like**
simple icon next to the toggle icons for each camera that open a new window. for example if camera is on 192.168.1.32 the the link opens up to http://192.168.1.32. or maybe even a new setting so users can customize

**Describe alternatives you've considered**
i have to pull up the frigate config to copy the ip and paste it in a new window wheneevr i want to access the webui of a camera

**Additional context**

**Comment by NickM-27** [comment]
this was implemented in #8405
