### ISSUE TITLE
Feature Request: Direction of Travel for Object Detection

### ISSUE THREAD

**Issue by FigJam23** [blakeblackshear/frigate#8326]
**Description:**
I would like to request the implementation of a "Direction of Travel" feature in Frigate's object detection. This feature would allow users to specify the direction in which an object, such as a car or a person, is moving in relation to a specific area, such as a driveway or an entrance. 

**Use Case:**
As a user, I often need to differentiate between objects entering and exiting a particular area, like my driveway or my front door. The current zone-based approach is versatile, but it would be beneficial to have a more precise method to detect and trigger events based on the direction of travel.

**Suggested Implementation:**
- Introduce an option to define "Direction of Travel" in the configuration, possibly using line crossing markings on the video feed.
- Users can then set the desired direction (e.g., "in" for entry, "out" for exit) for specific areas.
- Frigate's object detection algorithm should then consider this directional information when triggering events.

**Benefits:**
- Enhanced accuracy in distinguishing between objects entering and exiting a specified area.
- Better customization for users who want to monitor specific directional events.
- Improved utility for scenarios like driveway monitoring, where direction matters.

**Additional Notes:**
This feature would complement the existing zone-based configuration and further expand Frigate's capabilities for users who require more specific object detection and event triggering.

Thank you for considering this feature request.

**Comment by NickM-27** [comment]
I think this is covered by https://github.com/blakeblackshear/frigate/issues/93

I'd suggest leaving additional comments and a 👍 there
