### ISSUE TITLE
[Support]: ffmpeg, detector, watchdog crash issue, related totime?

### ISSUE THREAD

**Issue by marcel263** [blakeblackshear/frigate#8371]
### Describe the problem you are having

Today october 29th in Europe the time was put back into normal time from Daylight Savings at 3:00.

Immediately (2:01) camera threads started crashing, in an uncommon way. They never recovered and a restart of the Docker container was needed. The camera streams seemed fine.

For config see #8167 as it's the same.

Logs might not be available given the urgency. 

Please report if this is reproducible.

 

### Version

0.12.1-367D724

### Frigate config file

```yaml
See report
```

### Relevant log output

```shell
See report
```

### FFprobe output from your camera

```shell
See report
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Generic onvif

**Comment by NickM-27** [comment]
If anything this sounds like a camera issue not a frigate issue but without logs there's nothing to go off of

**Comment by NickM-27** [comment]
looks like there is an issue when checking if recordings, https://github.com/blakeblackshear/frigate/issues/8376 has more information so closing this as duplicate
