### ISSUE TITLE
Enable 2FA to access Frigate+ site

### ISSUE THREAD

**Issue by robertoprubio** [blakeblackshear/frigate#8378]
I've uploaded a lot of photos to the Frigate+ site and I think it's time to level up the site's security.
Please enable the ability to add 2FA to access the site.

**Comment by NickM-27** [comment]
I would recommend sending an email to blake@frigate.video or posting on https://github.com/blakeblackshear/frigate/discussions/7932

in general this repo is for the frigate project itself not frigate+ website
