### ISSUE TITLE
FEATURE REQUEST - Individual Object Type Toggle Switches

### ISSUE THREAD

**Issue by konradwalsh** [blakeblackshear/frigate#838]
I would love to be able to automate when looking for specific objects

For example, when I put the cat out, I would love to be only notified when it returns but not when other activity is detected

 I would love to enable Object Detection per Object. 

I currently do it with a custom input boolean in HA and notify on cat detection.. but would be nice to have it alongside all the other toggle switches in the HA integration

**Comment by hagak** [comment]
If you tie Frigate into a HA system like Home Assistant couldnt you just use rules with it or even NodeRed to perform this type of function?  Just leave object detection on the whole time and have a rule that only acts on notification when other conditions apply.

**Comment by konradwalsh** [comment]
Thanks.. but I just said that.. thats exactly what I do..

But the Frigate integration in HA has provided so many extra entities that make everything so easy.. this one might make sense to add

**Comment by hagak** [comment]
Sorry not sure i see the advantage of putting it in Frigate.  I like my tools to do what they do best and not try to be a jack of all trades littered with features.  Those usually tend to kill the projects by making them a massive maintenance nightmare.

**Comment by konradwalsh** [comment]
Do you even use the HA Integration?
It has many other _not absolutely necessary_ entities called out. This is a natural next step.

**Comment by hagak** [comment]
Ugh you are asking for a FEATURE in FRIGATE not HA, yes it would be part of the HA integration but before you get to that you have to ADD the FEATURE to FRIGATE.  I am saying lets not add fluff for fluffs sake.  What you have is a perfectly good way to handle your condition without it being a hack so why clutter up another project.

**Comment by konradwalsh** [comment]
Seriously.. you've made you point.. I disagree with you.. so move on.. its not a feature you want.. great for you..

but you are wrong too... The feature is already in Frigate.. Object Detection by Type! I am just merely suggesting that exposed like the other entities options are exposed.

**Comment by hagak** [comment]
I am not wrong, the feature to disable Object Detection by Type during runtime does not currently exist so that would have to be added to Frigate.

**Comment by konradwalsh** [comment]
> I am not wrong, the feature to disable Object Detection by Type during runtime does not currently exist so that would have to be added to Frigate.

Great for you
