### ISSUE TITLE
Feature Request - detect stationary Objects (on demand)

### ISSUE THREAD

**Issue by madface303** [blakeblackshear/frigate#841]
I am using Frigate for presence detection in some rooms for about half a year. This was working nearly perfect, but since 0.8.2 stationary objects (in my case a person) are not longer detect (if they don't move) when max_timeout is over.
Is there a way to choose whether it is enabled or disabled (detection of stationary objects)? I know that for many use cases off is the better decision, but for presence detection it would be great if a person (eg. sitting in front of the monitor and reading something, thereforce there would be no movement) would be detected even it is not moving.

Now using Frigate 0.8.3, with 0.8.0 it was nearly perfect.

Thanks Mike

**Comment by JakeysQ** [comment]
I would like a similar requirement too. Even if it is just a scheduled check. 
i.e every 5 minutes, is there a dog in picture.

**Comment by AnatomicFlack** [comment]
One more request for this feature.  Even if it's zoned/masked or however it need be implemented. Without this, we are back to the same issues cause with all standard motion detection be it by camera, PIR or Microwave sensors.  You resolved a HUGE issue with stationary object detection, perhaps without not really knowing you did.  

Frigate solved my problem in my office to control the lights.  Moving to V8, in general, has been amazing, but I was bummed when on 8.4 my lights kept turning off.  I tweaked many of the available settings and created zones to try to help, but the compromise needed to keep the lights on, for too long, was with last detected variable. I'm going to move back to 8.1 for now to try to fix this one very specific use case I'm having.

**Comment by mannp** [comment]
This would be great 👍🏻

**Comment by tungmeister** [comment]
I'd love this as well. Really wanting to use Frigate for presence detection within rooms. As others have said if the person is lost when they're stationary it's no better than classic motion detection methods which is a shame!

**Comment by agners** [comment]
Similar issue here, I'd like to detect the presence of an object in the frame. Detection works great, but it requires movement. Ideally, Frigate should have a mode where a static object mode.

Maybe this could be implemented by differentiating between the two states: Motion, Static. Whenever the camera switches from Motion -> Static, a last "full frame" detection is run, and every object which is present is then assumed to stay present. As soon as a motion is detected the algorithm switches from Static -> Motion, where the object detection is run on motion only and timeout of tracked objects comes active again etc.

**Comment by DrBlokmeister** [comment]
I'd also like this feature.

**Comment by tungmeister** [comment]
@blakeblackshear any chance of seeing this? It really would make frigate so much more useful to me if I could use it for presence detection.

**Comment by blakeblackshear** [comment]
Yes, but not in 0.9.0. Possibly the following release.

**Comment by nashant** [comment]
+1 for this. Would love to be able to use just this to make my lights not turn off when I'm sat on the sofa watching TV

**Comment by jdgh-19** [comment]
Just another +1 for this. I installed Frigate today to have a look. Requiring movement every 5 seconds kills one intended use case for this to replace PIR motion sensors.

**Comment by R5fan** [comment]
+1 from me too!
As a workaround, until this is implemented  , you can do as i did, also run deepstack on the same or a different box. Its slow though, Im just using the cpu version, processing a scaled down 0.5 MP image on my windows desktop (6 core ryzen 2) takes 500-800ms (although weirdly the image size doesnt seem to make too much difference). On my proxmox box in a windows VM that is shared with blueiris (dual core i3), it takes 7-10 seconds after increasing the thread priority. Ouch. Im sure there are ways to improve that, and you may have a GPU to accelerate things, but for some use cases, including mine,  even that performance isnt really a problem to occasionally count objects on demand.  Setting it up is pretty straightforward with the custom integration through HACS.

**Comment by RunoFawkes** [comment]
+1 for this. I've been using DOODS to suplement this need, but Frigate was loads better. hope we can get this feature back soon.

**Comment by shubness** [comment]
This feature is essential - my main use case for Frigate +1
