### ISSUE TITLE
[Config Support]: PLUS_API_KEY in docker stack environment variable, but not working...

### ISSUE THREAD

**Issue by StefanoGiu** [blakeblackshear/frigate#8442]
### Describe the problem you are having

I set the PLUS_API_KEY in the environment variable of the docker stack, but the send to frigate + button is not showing on the events page. No error in the log....

### Version

0.12.1-367D724

### Frigate config file

```yaml
It's not in the frigate config file.
```

### Relevant log output

```shell
No error in the log
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You'll need to provide an example with the key redacted, there's nothing to work with here.

**Comment by NickM-27** [comment]
I saw this was solved on discord, closing

**Comment by cliffburdick** [comment]
For those who weren't on discord to see the answer, you need snapshots enabled in the config
