### ISSUE TITLE
[Support]: Updating to 0.13.0-beta3; database migration with non-standard location

### ISSUE THREAD

**Issue by wilcomir** [blakeblackshear/frigate#8444]
### Describe the problem you are having

Hello,
I have just updated to 0.13.0-beta3 from 0.12.1 - and it all went through very quickly.

I am running frigate with docker, and I did have the `config.yml` directly mounted, therefore I created the folder & mounted the whole folder, as suggested in the release docs.
After the first startup, I expected to find the db to be migrated in the `config` folder, but this is not the case; I only see an empty `model_cache` folder, and a `.vacuum` file with an odd number inside.

I suspect this is because in my `config` file I have the following entry:

```
database:
  path: /db/frigate.db
```

Now I wonder, should I do anything else here? If I recall correctly, I was using a custom location because I wanted my DB to be on the local disk. Regardless, I am perfectly happy to have the db inside the `config` folder, sitting next to the configuration file; I do not know if there is a path to do so.

Thanks!

### Version

0.13.0-beta3

### Frigate config file

```yaml
not applicable
```

### Relevant log output

```shell
not applicable
```

### FFprobe output from your camera

```shell
not applicable
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

not applicable

**Comment by blakeblackshear** [comment]
No need to move it if you have a custom location defined and you are happy with it.

**Comment by wilcomir** [comment]
Thanks for the quick reply.

I am happy to fall back to the default behavior - would you suggest to do so, and in case what would be the correct procedure?

I am equally happy to keep the custom location as it is - but I want to make sure this will be as forward compatibile as possible.

Cheers
V

**Comment by NickM-27** [comment]
custom location is not going away so I would leave your config as is
