### ISSUE TITLE
MJPEG stream blocks webserver response

### ISSUE THREAD

**Issue by denniedegroot** [blakeblackshear/frigate#846]
**Describe the bug**
When watching/opening a MJPEG stream the webserver does not respond anymore until the MJPEG stream is closed.

So when I open the following URL in Chrome: http://192.168.1.10:5000/api/front?h=600&fps=15
The MJPEG stream works but the webserver (http://192.168.1.10:5000) does not load until the MJPEG stream is closed.

In the previous version it was possible to have multiple mjpeg streams, it seems to be limited to 1 now.

**Version of frigate**
0.8.4

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
-
```

**Frigate container logs**
```
No errors/warnings
```

**Frigate stats**
```json
-
```

**FFprobe from your camera**

Run the following command and paste output below
```
-
```

**Screenshots**
-

**Computer Hardware**
 - OS: Debian 10
 - Install method: Docker Compose
 - Coral Version: USB
 - Network Setup: Wired

**Camera Info:**
-

**Additional context**

**Comment by blakeblackshear** [comment]
See release notes for 0.8.4 https://github.com/blakeblackshear/frigate/releases/tag/v0.8.4
