### ISSUE TITLE
[Support]: Beta 0.13.4 HA add-on will not start

### ISSUE THREAD

**Issue by collinstork** [blakeblackshear/frigate#8498]
### Describe the problem you are having

The Addon will not start after upgrading to beta4.  Restoring to beta3 works fine.

### Version

0.13.0-beta4

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
Can't create container from addon_ccab4aaf_frigate-beta: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate-beta: Bad Request ("invalid CapAdd: unknown capability: "CAP_PERFMON"")
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
Looks like the HA addon / supervisor is outdated

**Comment by felipecrs** [comment]
@collinstork can you just confirm the OS version and Supervisor version?

**Comment by collinstork** [comment]
Ubuntu 22.04.3 
Docker was 20.10.17 -- the min required for HA
upgraded docker to 24.0.7 now everything works

**Comment by felipecrs** [comment]
@collinstork would you mind checking if Intel GPU stats are shown in the Frigate System UI?

![image](https://github.com/blakeblackshear/frigate/assets/29582865/d981c905-e532-45aa-b1d5-d38063fa8278)

**Comment by collinstork** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/4053268/b92b8483-828f-47e3-93cc-b7fa1491c9e0)

they do not.

**Comment by felipecrs** [comment]
Ok, let's keep track of this in https://github.com/blakeblackshear/frigate/issues/8494.
