### ISSUE TITLE
[Support]: Can Frigate work without HomeAssistant?

### ISSUE THREAD

**Issue by mwolfaardt** [blakeblackshear/frigate#8526]
### Describe the problem you are having

I know it's a strange request, but I would like to use the solution to fire events to a 3rd party platform based on what's detected on the camera stream.  For example based on your video demo, is someone walks into a zone, trigger a request and display a message on a screen. 

### Version

0

### Frigate config file

```yaml
n/A
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Other

**Comment by NickM-27** [comment]
Frigate offers all data via MQTT and websocket as well as an http api, none of which require home assistant. You just need some platform that can read from one of those and perform actions in the way that you are expecting. There are users that use NodeRED and other platforms as well
