### ISSUE TITLE
PiP support

### ISSUE THREAD

**Issue by CurlyFlow** [blakeblackshear/frigate#8534]
Hi,
google chrome has that nice feature that you can take "any" video and use it as picture in picture. So you can play game and watch any video or what ever you want.

I also think that would be VERY usefull for frigate and i also think its just a minimal thing to change to make it work. The extention just need to "find" that video on the webpage, which it currently cant. Probably just label it as "video"?

thats their github: https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension

Im using at as i write this.
<img width="1255" alt="image" src="https://github.com/blakeblackshear/frigate/assets/43281991/58956c8c-5266-4735-a7bd-26bd86e96dc9">

Would be cool if i could take the camera views like this also.

**Comment by NickM-27** [comment]
Frigate already supports PiP with the MSE and WebRTC live views

![Screen Shot 2023-11-07 at 20 32 01 PM](https://github.com/blakeblackshear/frigate/assets/14866235/b73280b6-bb88-4671-9791-ded3587a521d)

**Comment by NickM-27** [comment]
Like I said for live view PiP is supported with [MSE and WebRTC ](https://docs.frigate.video/configuration/live) the events and recordings player also supports PiP
