### ISSUE TITLE
mqqt base64 encoded image payload

### ISSUE THREAD

**Issue by grisia** [blakeblackshear/frigate#855]
It would be nice if the image payload was encoded as Base64.

I'm trying to integrate Frigate into Io-Broker, because the mqtt adapter only interprets the messages as a string, the binary data are invalid.

Maybe it could be made configurable?

```
diff /opt/frigate/frigate/object_processing.py /opt/frigate/frigate_cust/
485c485,487
<                     self.client.publish(f"{self.topic_prefix}/{camera}/{obj.obj_data['label']}/snapshot", jpg_bytes, retain=True)
---
>                     encoded = base64.b64encode(jpg_bytes).decode()
>                     image_data = 'data:image/jpeg;base64,{}'.format(encoded)
>                     self.client.publish(f"{self.topic_prefix}/{camera}/{obj.obj_data['label']}/snapshot", image_data, retain=True)
```

Corresponding issue for mqtt ioBroker adapter:
[https://github.com/ioBroker/ioBroker.mqtt/issues/115](https://github.com/ioBroker/ioBroker.mqtt/issues/115)

Lovelace ioBroker:
[https://github.com/ioBroker/ioBroker.lovelace/issues/162](https://github.com/ioBroker/ioBroker.lovelace/issues/162)

**Comment by natm** [comment]
I'd love to see this feature added too
