### ISSUE TITLE
FR: Make rate limit configurable

### ISSUE THREAD

**Issue by neonpak** [blakeblackshear/frigate#859]
**Describe the bug**
For some applications a 5 second rate limit between events published to the frigate/events MQTT endpoint is too high or probably too low. It would be nice if this time frame would be configurable.

**Version of frigate**
v0.8.0 - https://github.com/blakeblackshear/frigate/commit/d315dbea227f370fc2148ebbc9f3a868697ab513

**Comment by blakeblackshear** [comment]
I would rather keep the original issue with more information.
