### ISSUE TITLE
Mask & Zone Creator not working on Safari (CameraMap related)

### ISSUE THREAD

**Issue by dotWee** [blakeblackshear/frigate#860]
**Describe the bug**
On macOS Safari (Version 14.0.3) it is not possible to create masks or zones using the frigate mask & zone creator.  
Clicks on the image aren't recognised, no points can't be set.  
Works just fine on Chromium & Firefox.

**Version of frigate**
`0.8.4-5043040`

**Computer Hardware**
 - OS: `macOS 10.15.7`
 - Install method: `docker-compose`

**Additional context**
The following error gets thrown in the javascript console **on every click** on the image to set a point:

```
[Error] TypeError: undefined is not an object (evaluating 'e.reduce')
	(anonymous function) (CameraMap.KpZNo76OKHnm.js:14:4084)
	ne (preact.module-ff55218f.bKiDWaS-1sUZ.js:1:4564)
```

**Comment by paularmstrong** [comment]
Seems like this is an issue with the version of OS X / Safari that you have. It works correctly on Safari 14 (OS X 11.x)

**Comment by dotWee** [comment]
Can confirm the latest Safari update including the current Technology Preview fixes it.
