### ISSUE TITLE
[Support]: Frigate+ doesnt seem to work

### ISSUE THREAD

**Issue by Dinth** [blakeblackshear/frigate#8602]
### Describe the problem you are having

Hey. Im struggling to set up Frigate+ on my instance.
I have created an account on https://plus.frigate.video/, generated API and added it as env variable in Portainer: 
![image](https://github.com/blakeblackshear/frigate/assets/313674/17fe30a0-40fc-45e6-98bf-afc7cdff6812)
and redeployed the container.
I have set up the cameras on https://plus.frigate.video/:
![image](https://github.com/blakeblackshear/frigate/assets/313674/1120e760-9516-4244-b7e3-e878e0138779)

Unfortunately, i still cannot see a button to upload anything to Frigate+
![image](https://github.com/blakeblackshear/frigate/assets/313674/ecf0a8e6-eff1-463d-9de1-21070d6ecd3e)

Am i doing something wrong? 

### Version

0.12.1-367d724

### Frigate config file

```yaml
not relevant?
```

### Relevant log output

```shell
2023-11-13 17:53:33.063682169  [INFO] Starting Frigate...
2023-11-13 17:53:35.101838300  [2023-11-13 17:53:35] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-13 17:53:35.201335232  [2023-11-13 17:53:35] frigate.app                    INFO    : Creating directory: /tmp/cache
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
not relevant
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

not relevant

**Comment by NickM-27** [comment]
You don't have snapshots enabled, like the docs say snapshots are required to be enabled to submit to frigate+

**Comment by derhappy** [comment]
besides enabling snapshots, you also need to enable the clean attribute. It won't work without.
