### ISSUE TITLE
[Detector Support]:  Convert custom Frigate+ model to OpenVINO

### ISSUE THREAD

**Issue by Sch0field9** [blakeblackshear/frigate#8621]
### Describe the problem you are having

Since the CPU detector really can't keep up with my camera streams, I tried to convert the frigate+ model to an openVINO IR model.

I don't really know much about detection models, but as far as I could figure out, is that the MobileDet architecture uses some TensorFlow lite operations, which are not yet supported by the openvino convert_model API.

I'm currently stuck at "No translator found for TFLite_Detection_PostProcess node"

Before I waste more time on that, can someone tell me if that is even possible? or is there a roadmap available when openvino will be supported by frigate+?

my last try looked like this:
```python
ov.convert_model('custom_model_downloaded_from_model_cache.tflite', 
                 input=("normalized_input_image_tensor",[1, 320, 320, 3], ov.Type.i32), 
                 output=("TFLite_Detection_PostProcess","TFLite_Detection_PostProcess:1","TFLite_Detection_PostProcess:2","TFLite_Detection_PostProcess:3"))
``` 

### Version

0.13.0-Beta5

### Frigate config file

```yaml
none
```

### docker-compose file or Docker CLI command

```yaml
none
```

### Relevant log output

```shell
openvino._pyopenvino.OpConversionFailure: Check 'translate_map.count(decoder->get_op_type())' failed at src/frontends/tensorflow_lite/src/frontend.cpp:238:
FrontEnd API failed with OpConversionFailure:
No translator found for TFLite_Detection_PostProcess node.
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Frigate+ docs say that openvino will be supported, I don't believe any support is going to be given for converting the coral model to openvino. 

@blakeblackshear can confirm

**Comment by Sch0field9** [comment]
yes, I'm aware that its planned to support openvino in the future. I just dont know how long it will take and if im able to wait that long.  I just thought I could bridge this time with a manual conversion.

**Comment by blakeblackshear** [comment]
I don't know if it's possible to convert the tflite model like this. Are you trying the CPU or edgetpu version of your model?

**Comment by Sch0field9** [comment]
I only tried the CPU model so far... could give the tpu model a shot today

**Comment by Sch0field9** [comment]
seems to have the same outcome, but with a different operation name:
```
FrontEnd API failed with OpConversionFailure:
No translator found for edgetpu-custom-op node.
```
