### ISSUE TITLE
Catch time zone tzlocal error

### ISSUE THREAD

**Issue by pos-ei-don** [blakeblackshear/frigate#8636]
### Describe the problem you are having

Im always seeing this message, unfortunately i did exactly what this message is tellimg me.
I'm currently using beta5, but also tested with stable.

The docker-host (debian 12) also uses this timezone.  
```
timedatectl | grep "Time zone"
Time zone: Europe/Vienna (CET, +0100)
```

I configured it in the docker-compose. I also tried a different City, with the same result. 
I also tried to remove this. What am i missing?
```
    environment:
      - TZ="Europe/Vienna"
#      - TZ="Europe/Berlin" 

```

### Version

beta5

### Frigate config file

```yaml
empty default config!
```

### Relevant log output

```shell
zoneinfo._common.ZoneInfoNotFoundError: 'tzlocal() does not support non-zoneinfo timezones like "Europe/Vienna". \nPlease use a timezone in the form of Continent/City'
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

-

### Any other information that may be helpful

-

**Comment by NickM-27** [comment]
so let's see the full set of logs please

**Comment by NickM-27** [comment]
More info was provided in https://github.com/blakeblackshear/frigate/issues/8677
