### ISSUE TITLE
Homeassistant wakeword from Frigate Streams

### ISSUE THREAD

**Issue by starsoccer** [blakeblackshear/frigate#8644]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to have wake words from HA trigger an event on frigate and then be able to use a camera stream to process voice. Ideally If I have a camera sitting I should be able to use my HA wakeword to trigger something to happen

**Describe the solution you'd like**
Ideally it should be possible to use the frigate streams and have HA process those audio streams for wake words and speech and trigger events.

**Describe alternatives you've considered**
An alternative would be have a separate HA addon that does this similar to [streamassist](https://github.com/AlexxIT/StreamAssist)

**Comment by NickM-27** [comment]
this is already possible with stream assist + go2rtc (which is built in to frigate), I would suggest just using that

**Comment by starsoccer** [comment]
@NickM-27 Any context you can provide on how this is possible already? Streamassist doesnt currently support wakewords really and is just a on/off switch to do voice commands

**Comment by NickM-27** [comment]
streamassist already plugs in to the HA assist pipeline, so HA should be able to use the audio inputs for handling that

**Comment by starsoccer** [comment]
It used to, but it doesnt currently work. It worked in the past but has broken over the last few months with changes to assist and has never supported wakeword

**Comment by NickM-27** [comment]
gotcha, that would be a request for that project to continue working. Using a camera as a smart speaker is very much outside the NVR usecase

**Comment by starsoccer** [comment]
Okay fair enough, with audio detections coming, it seemed like doing wakeword detection too wouldnt be that far fetched

**Comment by NickM-27** [comment]
the use cases are completely different, audio detection is made to provide alerts like people talking or a fire alarm heard by your cameras. Using a camera as a smart speaker is an entirely separate use case
