### ISSUE TITLE
ffmpeg issues on 64-bit Pi 4

### ISSUE THREAD

**Issue by mcondren** [blakeblackshear/frigate#865]
**Describe the bug**
Hardware acceleration is not working on my Pi4 using the raspi Debian Arm64 image. (not raspbian).

**Version of frigate**
Latest aarch64 docker image

**Config file**
Include your full config file wrapped in triple back ticks.
```
 detectors:
 42   coral:
 41     type: edgetpu
 40     device: usb
 39
 38 mqtt:
 37   host: mosquitto.ansible.house
 36   topic_prefix: frigate
 35
 34 ffmpeg:
 33   hwaccel_args:
 32     - -c:v
 31     - h264_v4l2m2m
 30
 29 objects:
 28   track:
 27     - person
 26   filters:
 25     person:
 24       threshold: 0.7
 23       min_area: 0
 22
 21 cameras:
 20   driveway:
 19     ffmpeg:
 18       inputs:
 17       - path: rtsp://192.168.1.247:7447/kxsyIbFo1g6kEX6Z
 16         roles:
 15           - detect
 14           - clips
 13           - rtmp
 12     fps: 5
 11     width: 1920
 10     height: 1080
  9     clips:
  8       enabled: true
  7
  6   backporch:
  5     ffmpeg:
  4       inputs:
  3         - path: rtsp://192.168.1.247:7447/jlrMUN3PUvQRiLhz
  2           roles:
  1             - detect
  0             - clips
  1             - rtmp
  2     fps: 5
  3     width: 1920
 32     height: 1080
 31     clips:
 30       enabled: true
 29
 28   sidedoor:
 27     ffmpeg:
 26       inputs:
 25         - path: rtsp://192.168.1.247:7447/TxFfDQWA6nQyleT2
 24           roles:
 23             - detect
 22             - clips
 21             - rtmp
 20     fps: 5
 19     width: 1920
 18     height: 1080
 17     clips:
 16       enabled: true
 15
 14   frontdoor:
 13     ffmpeg:
 12       inputs:
 11         - path: rtsp://192.168.1.247:7447/BFkoDhlFATcRc8DM
 10           roles:
  9             - detect
  8             - clips
  7             - rtmp
  6     fps: 5
  5     width: 1600
  4     height: 1200
  3     clips:
  2       enabled: true
  1
  0 clips:
  1   retain:
  2     default: 30

```

**Frigate container logs**

```
ffmpeg.sidedoor.detect         ERROR   : [h264_v4l2m2m @ 0xaaaaecca5090] Could not find a valid device
ffmpeg.sidedoor.detect         ERROR   : [h264_v4l2m2m @ 0xaaaaecca5090] can't configure decoder
```

**Frigate stats**
```
Wont run long enough without acceleration to get this.
```

**Computer Hardware**
 - OS: raspi.debain.org pi4 arm64-bit image
 - Install method: Docker
 - Coral Version: USB
 - Network Setup: wired 1GB

**Camera Info:**
 - Manufacturer: Unifi
 - Model: G3's x4
 - Resolution: 1080p
 - FPS: 5

**Additional context**
I recompiled ffmpeg with libx264 support but still no go.

**Comment by msekoranja** [comment]
I am running 64-bit HAOS in Pi4 w/ Edge TPU and the same HW acc. config as you without any problems.

**Comment by mcondren** [comment]
raw ffmpeg from command line trying to use the decoder with a test file.

```
 ffmpeg -c:v h264_v4l2m2m -i FPS_test_1080p23.976_L4.1.mkv test.mkv
ffmpeg version N-101345-g3072438 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/root/bin --enable-gpl --enable-gnutls --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libsvtav1 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 66.100 / 56. 66.100
  libavcodec     58.126.100 / 58.126.100
  libavformat    58. 68.100 / 58. 68.100
  libavdevice    58. 12.100 / 58. 12.100
  libavfilter     7.107.100 /  7.107.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, matroska,webm, from 'FPS_test_1080p23.976_L4.1.mkv':
  Metadata:
    encoder         : libebml v1.3.0 + libmatroska v1.4.1
    creation_time   : 2014-09-19T01:06:47.000000Z
  Duration: 00:10:05.06, start: 0.000000, bitrate: 214 kb/s
  Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 212945
      BPS-eng         : 212945
      DURATION        : 00:10:05.063000000
      DURATION-eng    : 00:10:05.063000000
      NUMBER_OF_FRAMES: 14507
      NUMBER_OF_FRAMES-eng: 14507
      NUMBER_OF_BYTES : 16105645
      NUMBER_OF_BYTES-eng: 16105645
      _STATISTICS_WRITING_APP: mkvmerge v7.2.0 ('On Every Street') 32bit built on Sep 13 2014 15:42:11
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.2.0 ('On Every Street') 32bit built on Sep 13 2014 15:42:11
      _STATISTICS_WRITING_DATE_UTC: 2014-09-19 01:06:47
      _STATISTICS_WRITING_DATE_UTC-eng: 2014-09-19 01:06:47
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: mp3, 48000 Hz, stereo, fltp, 38 kb/s (default)
    Metadata:
      BPS             : 34181
      BPS-eng         : 34181
      DURATION        : 00:00:01.056000000
      DURATION-eng    : 00:00:01.056000000
      NUMBER_OF_FRAMES: 44
      NUMBER_OF_FRAMES-eng: 44
      NUMBER_OF_BYTES : 4512
      NUMBER_OF_BYTES-eng: 4512
      _STATISTICS_WRITING_APP: mkvmerge v7.2.0 ('On Every Street') 32bit built on Sep 13 2014 15:42:11
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.2.0 ('On Every Street') 32bit built on Sep 13 2014 15:42:11
      _STATISTICS_WRITING_DATE_UTC: 2014-09-19 01:06:47
      _STATISTICS_WRITING_DATE_UTC-eng: 2014-09-19 01:06:47
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[h264_v4l2m2m @ 0xaaaadeb366f0] Could not find a valid device
[h264_v4l2m2m @ 0xaaaadeb366f0] can't configure decoder
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_v4l2m2m) -> h264 (libx264))
  Stream #0:1 -> #0:1 (mp3 (mp3float) -> vorbis (libvorbis))
Error while opening decoder for input stream #0:0 : Invalid argument
```

**Comment by mchangsp** [comment]
What error message do you get when running Frigate?

**Comment by mchangsp** [comment]
If you try only 1 camera and no hardware acceleration, does Frigate work or do you get an error message?
And if 1 camera works, try to add 1 camera. What happens with two cameras?

**Comment by mcondren** [comment]
Thanks for the help but I ended up getting frustrated and moving back to my x86 server. This looks like it was an issue with ffmpeg on the pi, and not with Frigate.

**Comment by HSB-collab** [comment]
Can we reopen this issue? I have the same issue running HassOS on a Pi4 wth edge TPU but still can't get hardware acceleration working and my CPU is maxing out (I have 5 cameras and want to add 2 more). @msekoranja are you able to show your frigate.yml file so that I can check where I have gone wrong?

**Comment by msekoranja** [comment]
Nothing special in my configuration:
```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args:
    - '-c:v'
    - h264_v4l2m2m
cameras:
...
```

**Comment by HSB-collab** [comment]
Thanks for the reply. Are the single quotes around -c:v significant? That seems to be the only difference between your configuration and mine

**Comment by mcondren** [comment]
I decided to try this again this week with the latest raspberry Pi OS  64-bit.  Same config, same error.  

ffmpeg.driveway.detect         ERROR   : [h264_v4l2m2m @ 0x558e458930] Could not find a valid device
ffmpeg.driveway.detect         ERROR   : [h264_v4l2m2m @ 0x558e458930] can't configure decoder
ffmpeg.driveway.detect         ERROR   : Error while opening decoder for input stream #0:1 : Invalid argument

Frustrating since I don't see any difference in my config compared to @msekoranja.  @HSB-collab did you ever figure this out?

**Comment by mcondren** [comment]
Describe the bug
Hardware acceleration is not working on my Pi4 using the raspberry Pi OS Arm64 image (latest) 

Version of frigate
Latest aarch64 docker image.  0.8.4

Config file
Include your full config file wrapped in triple back ticks.

 detectors:
 42   coral:
 41     type: edgetpu
 40     device: usb
 39
 38 mqtt:
 37   host: mosquitto.ansible.house
 36   topic_prefix: frigate
 35
 34 ffmpeg:
 33   hwaccel_args:
 32     - -c:v
 31     - h264_v4l2m2m
 30
 29 objects:
 28   track:
 27     - person
 26   filters:
 25     person:
 24       threshold: 0.7
 23       min_area: 0
 22
 21 cameras:
 20   driveway:
 19     ffmpeg:
 18       inputs:
 17       - path: rtsp://192.168.1.247:7447/kxsyIbFo1g6kEX6Z
 16         roles:
 15           - detect
 14           - clips
 13           - rtmp
 12     fps: 5
 11     width: 1920
 10     height: 1080
  9     clips:
  8       enabled: true
  7
  6   backporch:
  5     ffmpeg:
  4       inputs:
  3         - path: rtsp://192.168.1.247:7447/jlrMUN3PUvQRiLhz
  2           roles:
  1             - detect
  0             - clips
  1             - rtmp
  2     fps: 5
  3     width: 1920
 32     height: 1080
 31     clips:
 30       enabled: true
 29
 28   sidedoor:
 27     ffmpeg:
 26       inputs:
 25         - path: rtsp://192.168.1.247:7447/TxFfDQWA6nQyleT2
 24           roles:
 23             - detect
 22             - clips
 21             - rtmp
 20     fps: 5
 19     width: 1920
 18     height: 1080
 17     clips:
 16       enabled: true
 15
 14   frontdoor:
 13     ffmpeg:
 12       inputs:
 11         - path: rtsp://192.168.1.247:7447/BFkoDhlFATcRc8DM
 10           roles:
  9             - detect
  8             - clips
  7             - rtmp
  6     fps: 5
  5     width: 1600
  4     height: 1200
  3     clips:
  2       enabled: true
  1
  0 clips:
  1   retain:
  2     default: 30

Frigate container logs

ffmpeg.driveway.detect ERROR : [h264_v4l2m2m @ 0x558e458930] Could not find a valid device
ffmpeg.driveway.detect ERROR : [h264_v4l2m2m @ 0x558e458930] can't configure decoder
ffmpeg.driveway.detect ERROR : Error while opening decoder for input stream #0:1 : Invalid argument

Frigate stats

Wont run long enough without acceleration to get this.

Computer Hardware

OS: raspberry Pi OS arm64-bit image
Install method: Docker
Coral Version: USB
Network Setup: wired 1GB
Camera Info:

Manufacturer: Unifi
Model: G3's x4
Resolution: 1080p
FPS: 5

**Comment by blakeblackshear** [comment]
Try running hwaccel with just 2 cameras. The GPU only has so much memory. It stops working when too many cameras are using it.

**Comment by mcondren** [comment]
I set video memory on my pi 8GB to 512MB.  
I then commented out every camera except for one.  (driveway).
I then tried again.  Same errors.

```
peewee_migrate                 INFO    : Starting migrations

There is nothing to migrate

peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for driveway: 36
detector.coral                 INFO    : Starting detection process: 34
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Capture process started for driveway: 38
frigate.video                  INFO    : driveway: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : driveway: ffmpeg process is not running. exiting capture thread...
frigate.edgetpu                INFO    : TPU found
ffmpeg.driveway.detect         ERROR   : [h264_v4l2m2m @ 0x55cd0cbf80] Could not find a valid device
ffmpeg.driveway.detect         ERROR   : [h264_v4l2m2m @ 0x55cd0cbf80] can't configure decoder
ffmpeg.driveway.detect         ERROR   : Error while opening decoder for input stream #0:1 : Invalid argument
```

**Comment by mcondren** [comment]
```
❯ ffmpeg -decoders | grep v4l2

ffmpeg version 4.1.6-1~deb10u1+rpt2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --disable-mmal --enable-neon --enable-vout-drm --enable-v4l2-request --enable-libudev --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
 V..... h263_v4l2m2m         V4L2 mem2mem H.263 decoder wrapper (codec h263)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 decoder wrapper (codec h264)
 V..... hevc_v4l2m2m         V4L2 mem2mem HEVC decoder wrapper (codec hevc)
 V..... mpeg1_v4l2m2m        V4L2 mem2mem MPEG1 decoder wrapper (codec mpeg1video)
 V..... mpeg2_v4l2m2m        V4L2 mem2mem MPEG2 decoder wrapper (codec mpeg2video)
 V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 decoder wrapper (codec mpeg4)
 V..... vc1_v4l2m2m          V4L2 mem2mem VC1 decoder wrapper (codec vc1)
 V..... vp8_v4l2m2m          V4L2 mem2mem VP8 decoder wrapper (codec vp8)
 V..... vp9_v4l2m2m          V4L2 mem2mem VP9 decoder wrapper (codec vp9)
```

**Comment by blakeblackshear** [comment]
Frigate has its own ffmpeg inside the container. The version you have outside the container is not relevant.

Can you post your docker run command or your compose file?

**Comment by mcondren** [comment]
```
 version: "3.6"
   services:
     Frigate:
       container_name: Frigate
       domainname: ansible.house
       hostname: frigate
       image: blakeblackshear/frigate:stable-aarch64
       networks:
         macvlan:
           ipv4_address: 192.168.1.43
      healthcheck:
        test: ["CMD", "wget" , "-q", "-O-", "http://localhost:5000"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 3m
      privileged: true
      restart: unless-stopped
      #devices:
      #  - /dev/bus/usb:/dev/bus/usb
      volumes:
        - frigate:/config
        - /etc/localtime:/etc/localtime:ro
        - /mnt/media/frigate/clips:/media/frigate/clips
```

**Comment by mcondren** [comment]
I uncommented the device because I changed it to privileged.  It finds the TPU fine.

**Comment by blakeblackshear** [comment]
I wonder if the debian arm64 image is missing the required gpu drivers for the Pi. Have you tried raspbian 64 as the host OS?

**Comment by mcondren** [comment]
This time I am using raspbian 64-bit. Image using rpi-imager. My last try earlier this year when I started the thread was Debian.

**Comment by theopoon** [comment]
I am having exact same issue as this topic, 

RPi4b, 2GB, 1 Camera
vcgencmd get_mem gpu
gpu=256M

uname -a
Linux rpi4b-64-0826 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
Would result in error in log

... ffmpeg process is not running. exiting capture thread.
... ffmpeg sent a broken frame. memoryview assignment

Thanks

**Comment by ultimategrandson** [comment]
I'm having this exact issue too, any solutions?

**Comment by HSB-collab** [comment]
> I'm having this exact issue too, any solutions?

I am afraid not - I never got hardware acceleration running on the Pi. As I only have 2 cameras, it is not too big of a deal.

**Comment by krim404** [comment]
its working on 0.11.0-3de1948, sadly on RC1 it is broken, again

**Comment by krim404** [comment]
no error at all in debug except "no ffmpeg process", - no video feed or green video feed

**Comment by NickM-27** [comment]
> no error at all in debug except "no ffmpeg process", - no video feed or green video feed

If you wait a bit longer when it reconnects to the camera ffmpeg error be shown.

**Comment by krim404** [comment]
i left it running for a few hours now. Only thing i get is:

```
INFO    : No frames received from front in 20 seconds. Exiting ffmpeg...
INFO    : Waiting for ffmpeg to exit gracefully...
INFO    : FFmpeg didnt exit. Force killing...
ERROR   : front: Unable to read frames from ffmpeg process.
ERROR   : front: ffmpeg process is not running. exiting capture thread...
ERROR   : Ffmpeg process crashed unexpectedly for front.

no information from ffmpeg itself. Using -rc1. Everything is working when using -3de1948

**Comment by NickM-27** [comment]
> no information from ffmpeg itself. Using -rc1. Everything is working when using -3de1948

-3de1948 is a 6 month old build, before any actual 0.11 changes were made, so that doesn't really mean much. Are you running in docker compose, hass os, or something else? Also to confirm what Pi and what OS are you running? (32 or 64 bit?)

I have it working just fine on my Pi 3b+ running debian 64 bit.

**Comment by krim404** [comment]
running on Pi cm4 (8gb memory) with debian 64bit.

**Comment by NickM-27** [comment]
> running on Pi cm4 (8gb memory) with raspberry os based on debian bullseye 64bit with docker-compose.

Thanks, what does your compose file look like?

**Comment by krim404** [comment]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:0.11.0-rc1 #3de1948
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/frigate/config.yml:/config/config.yml:ro
      - /usb/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds

**Comment by NickM-27** [comment]
@krim404 You aren't passing in your GPU so there is no way for hwaccel to work. (the previous ffmpeg would not error out on this it would just silently not use hwaccel, but the new build in 0.11 crashes when hwaccel is not installed correctly).

You need to pass the device `/dev/video10` so ffmpeg has access to the GPU for hwaccel

**Comment by krim404** [comment]
just re-added it (i removed it a few minutes ago) - didnt change anything, same behaviour

**Comment by NickM-27** [comment]
Hmm, would expect more logs than that as that seems to indicate hwaccel is working as the driver is being loaded successfully.

**Comment by krim404** [comment]
currently 1024mb

**Comment by krim404** [comment]
however the moment i comment out from config.yml everything works, but without any acceleration:
```
#ffmpeg:
#  hwaccel_args:
#    - -c:v
#    - h264_v4l2m2m
```

**Comment by NickM-27** [comment]
How much RAM does your cm4 have? I might suggest lowering the GPU memory to 256 or something as perhaps the high amount is unable to be allocated which is causing an issue.

**Comment by krim404** [comment]
8gb ram. same error with any value lower.

**Comment by krim404** [comment]
btw it is not a container problem, as i can do hardware encoding from within the container using ffmpeg:

```
root@ad854b786ada:/media/frigate# ffmpeg -c:v h264_v4l2m2m -i video.mp4 -c:v h264_v4l2m2m -frames 300 -b:v 1M -an foo.mp4
ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --toolchain=hardened --enable-cross-compile --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu-
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.25.101
  Duration: 00:00:30.02, start: 0.000000, bitrate: 6053 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 5860 kb/s, 24 fps, 24 tbr, 12288 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[h264_v4l2m2m @ 0x559976f360] Using device /dev/video10
[h264_v4l2m2m @ 0x559976f360] driver 'bcm2835-codec' on card 'bcm2835-codec-decode' in mplane mode
[h264_v4l2m2m @ 0x559976f360] requesting formats: output=H264 capture=YU12
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_v4l2m2m) -> h264 (h264_v4l2m2m))
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0x55997409d0] Using device /dev/video11
[h264_v4l2m2m @ 0x55997409d0] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
[h264_v4l2m2m @ 0x55997409d0] requesting formats: output=YU12 capture=H264
[h264_v4l2m2m @ 0x55997409d0] Failed to set gop size: Invalid argument
Output #0, mp4, to 'foo.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, q=2-31, 1000 kb/s, 24 fps, 12288 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.18.100 h264_v4l2m2m
[mp4 @ 0x5599723a20] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
frame=  300 fps= 39 q=-0.0 Lsize=    1254kB time=00:00:12.45 bitrate= 824.9kbits/s speed=1.61x    
video:1252kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.164211%

**Comment by NickM-27** [comment]
Sounds like a camera issue then, the camera is h264 correct?

**Comment by krim404** [comment]
pretty sure it has nothing to do with the camera, as i can download the stream with ffmpeg in a local file by issuing the command 'ffmpeg -loglevel info -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -use_wallclock_as_timestamps 1 -i "rtsp://root:password@192.168.0.50:554/axis-media/media.amp?videocodec=h264&resolution=1280x720"  -c:v h264 -frames 300 -b:v 1M -an foo.mp4'

**Comment by krim404** [comment]
the GPU can decode it. i copied the whole command string from the ffmpeg pid. there are only two issues:

1st. with "-timeout 5000000" i get an error "Unable to open RTSP for listening"
2nd. the connection string uses an & symbol - so i have to set the rtsp:// string in "

then i can simply capture the frame and output it anywhere i want.

**Comment by krim404** [comment]
little follow up:
`cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)`
this error repeats. this seems like a bug of the "newer" ffmpeg, a few people reported, that older ffmpeg versions do not have this issue on their setup.

**Comment by NickM-27** [comment]
We saw another user that on the newest rpi kernel is having issues with hwaccel when it was working previously, could be similar here. In any case another example of hwaccel working fine for a user but something in the setup unrelated to frigate directly causing it to not work. 

#3705

**Comment by krim404** [comment]
i tried the same command with hardware acceleration with the FFMPEG version from `3de1948` and et voila... hardware acceleration is working.

```
[h264_v4l2m2m @ 0x5594ec3290] Using device /dev/video10
[h264_v4l2m2m @ 0x5594ec3290] driver 'bcm2835-codec' on card 'bcm2835-codec-decode' in mplane mode
[h264_v4l2m2m @ 0x5594ec3290] requesting formats: output=H264 capture=YU12
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_v4l2m2m) -> rawvideo (native))
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0x5594ec3290] Post G selection ret=0, err=22 1280x720
[h264_v4l2m2m @ 0x5594ec3290] Dq event 5
Output #0, rawvideo, to 'foo.mp4':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
    encoder         : Lavf58.45.100
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 55296 kb/s, 5 fps, 5 tbn, 5 tbc
    Metadata:
      encoder         : Lavc58.91.100 rawvideo
frame=   31 fps=8.6 q=-0.0 Lsize=   41850kB time=00:00:06.20 bitrate=55296.0kbits/s dup=0 drop=4 speed=1.72x    
video:41850kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Exiting normally, received signal 2.
```
`ffmpeg version 4.3.3-0+rpt2+deb11u1 Copyright (c) 2000-2021 the FFmpeg developers`

so the solution is to revert to an older ffmpeg version for now...

**Comment by krim404** [comment]
If i recall correctly the ffmpeg version got modified in the particular container. Are there any information what has been changed / which patches were included?

**Comment by NickM-27** [comment]
> If i recall correctly the ffmpeg version got modified in the particular container. Are there any information what has been changed / which patches were included?

RC1 uses https://github.com/jellyfin/jellyfin-ffmpeg (5.0.1-8) I am not sure if they have documented all things that have been modified / changed. 

However, an incompatibility with jellyfin-ffmpeg and rtsp-simple-server was discovered in the RC process, so RC2 will use https://github.com/BtbN/FFmpeg-Builds instead.

**Comment by krim404** [comment]
i meant in 3de1948 - if i recall correctly the ffmpeg version in there has been modified as a test.

**Comment by NickM-27** [comment]
> i meant in the docker image [3de1948](https://github.com/blakeblackshear/frigate/commit/3de1948d51112b4d7bfa5ed9fd8c3fb42b321d95) - if i recall correctly the ffmpeg version in there has been modified as a test.

It used the standard apt ffmpeg, the fix for hwaccel on 64bit was using a new ffmpeg version [with this fix](https://github.com/FFmpeg/FFmpeg/commit/3fc72c9fc16df3b7edc329ed9eeaaa1e65976c33) and the fix for 32bit hwaccel was just to include extra dependency / metadata.

You can see https://github.com/blakeblackshear/frigate/issues/2030#issuecomment-972503838 which shows another user that found RPi kernel / OS used affects this as well.

**Comment by krim404** [comment]
it indeed has something to do with the used OS - when i extract the ffmpeg binary from image [3de1948](https://github.com/blakeblackshear/frigate/commit/3de1948d51112b4d7bfa5ed9fd8c3fb42b321d95) and inject it into rc1  it is not working as well. working like a charm inside the container though, so at least it has nothing to do with the kernel.

**Comment by krim404** [comment]
one other thing i found was, that the binary in 3de1948 has this patch included, which is missing on the other binaries:
https://github.com/Miouyouyou/FFmpeg-V4L2-Request
