### ISSUE TITLE
[Config Support]: Restream streams wrong camera

### ISSUE THREAD

**Issue by shivjm** [blakeblackshear/frigate#8650]
### Describe the problem you are having

I set up a fresh config with two versions of the same camera: a direct stream and a restream. The direct stream works fine. The restream shows a stream from an entirely different camera in the same subnet, despite having the same URL. It’s always the same other camera; there’s no variation. (Frigate also says recordings must be turned on in the UI for both cameras.) The mse viewer shows the same (incorrect) view when I open the individual camera’s page.

### Version

0.12.1-367d724

### Frigate config file

```yaml
cameras:
  front-gate:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/101
          roles:
            - record
  front-gate_restream:
    ffmpeg:
      inputs:
        - input_args: preset-rtsp-restream
          path: rtsp://127.0.0.1:8554/cam1
          roles:
            - record
        - input_args: preset-rtsp-restream
          path: rtsp://127.0.0.1:8554/cam1_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: cam1
go2rtc:
  streams:
    cam1:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/101
      - ffmpeg:cam1#audio-opus
    cam1_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/102
      - ffmpeg:cam1_sub#audio-opus
mqtt:
  enabled: false
record:
  retain:
    days: 15
    mode: all
```

### Relevant log output

```shell
2023-11-17 22:22:01.095420864  [INFO] Starting Frigate...
2023-11-17 22:22:02.191539583  [2023-11-18 03:52:02] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-17 22:22:02.206885431  [2023-11-18 03:52:02] peewee_migrate                 INFO    : Starting migrations
2023-11-17 22:22:02.210427785  [2023-11-18 03:52:02] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-17 22:22:02.223058873  [2023-11-18 03:52:02] detector.cpu                   INFO    : Starting detection process: 3442
2023-11-17 22:22:02.224397013  [2023-11-18 03:52:02] frigate.app                    INFO    : Output process started: 3444
2023-11-17 22:22:02.225496546  [2023-11-18 03:52:02] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-11-17 22:22:02.227687320  [2023-11-18 03:52:02] frigate.app                    INFO    : Camera processor started for front-gate: 3447
2023-11-17 22:22:02.231836670  [2023-11-18 03:52:02] frigate.app                    INFO    : Camera processor started for front-gate_restream: 3449
2023-11-17 22:22:02.235273244  [2023-11-18 03:52:02] frigate.app                    INFO    : Capture process started for front-gate: 3450
2023-11-17 22:22:02.239921621  [2023-11-18 03:52:02] frigate.app                    INFO    : Capture process started for front-gate_restream: 3453
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Any other information that may be helpful

Running on TrueNAS SCALE (i.e. via Kubernetes/k3s). The camera is set up to produce H.264 video with audio in both the main stream and the sub stream.

**Comment by hawkeye217** [comment]
Can you enable go2rtc trace logs and send them?

```
go2rtc:
  log:
    exec: trace
  streams: ...
```

**Comment by shivjm** [comment]
Thanks for responding so quickly, and sorry for not doing the same: I’ve had quite an eventful day or so with Frigate and these cameras. I left Frigate alone last night but restarted the system a couple of times before checking again in the day; now the stream was correct. I added all my other cameras. Only that one (re)stream worked and the rest were blank (<samp>No frames have been received, check error logs</samp>). I made a few attempts at fixing it before reinstalling Frigate (still at the TrueNAS level) and eventually realized I needed to mount the host interface again.

Right now, I have all my cameras configured in two variants: normal and restreamed. The normal ones are all working. The restreamed versions are all blank like earlier. Here’s are the relevant `cameras:` entries for the one I initially reported:
```yaml
  front-gate:
    detect:
      height: 720
      width: 1280
    ffmpeg:
      inputs:
      - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/102
        roles:
        - detect
        - rtmp
      - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/101
        roles:
        - record
  front-gate_restream:
    ffmpeg:
      inputs:
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/cam9
        roles:
        - record
      - input_args: preset-rtsp-restream
        path: rtsp://127.0.0.1:8554/cam9_sub
        roles:
        - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: cam9
```
And `streams:` entries:
```yaml
    cam9:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/101
    - ffmpeg:cam9#audio-opus
    cam9_sub:
    - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.200.19:554/Streaming/Channels/102
    - ffmpeg:cam9_sub#audio-opus
```
Should I open a new issue for this?

**Comment by NickM-27** [comment]
I'd suggest updating go2rtc https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by Aankhen** [comment]
That did fix it! (It knocked out the non-restream versions but I don’t care about that.) And, as a bonus, it also made WebRTC work. Thank you very much for the help!

For anyone faced with the same problem: I updated go2rtc by downloading it within a TrueNAS dataset and mounting it as a `hostPath` volume at `/config/go2rtc`. It’s a single binary so it’s quite trivial to do.

**Comment by NickM-27** [comment]
awesome, feel free to create a new issue if something else comes up

**Comment by NickM-27** [comment]
are you the OP under a different account or a seperate user?

**Comment by shivjm** [comment]
Sorry, that was indeed me, I responded from the wrong tab. 😳
