### ISSUE TITLE
Frigate 0.12 iOS MSE fix

### ISSUE THREAD

**Issue by haroldboom** [blakeblackshear/frigate#8651]
Hi,
As of iOS 17 MSE is supported, is it possible to bypass the message “MSE is not supported on iOS devices. You'll need to use jsmpeg or webRTC. See the docs for more info.” And display the stream? This is on Frigate 0.12

**Comment by hawkeye217** [comment]
MSE is supported on iOS 17.1+ in the next version of frigate, 0.13, which is currently in beta.
