### ISSUE TITLE
Feature: Accept external triggers to record from MQTT or API.

### ISSUE THREAD

**Issue by BloodBlight** [blakeblackshear/frigate#8671]
Going to skip the template as this is fairly simple.

I have several sensors (motion, door and so forth) and would like to send an event message either by MQTT or the HTTP API to trigger a recording event.

Would be awesome if these "external" triggers could get their own rule set in the config as well.  For example, if I send any event, grab the last 60 second for all cameras.

It SEEMS like this wouldn't be a big change, but..

Also, awesome work!  Loving this so far!

**Comment by NickM-27** [comment]
This is already supported in 0.13, it is called manual events

**Comment by BloodBlight** [comment]
Oh, sweet!  Hmmm, now do I go beta.  :)

Thank you!
