### ISSUE TITLE
Is it possible to make frigate.db location configurable?

### ISSUE THREAD

**Issue by ivlis** [blakeblackshear/frigate#8682]
**Describe what you are trying to accomplish and why in non technical terms**
Allow to specify the location of the database frigate uses.

**Describe the solution you'd like**
Add a yaml key into the config with the location of the database instead of hardcoding it. Or read it from an environment variable.
```yaml
db:
    path: '/frigate-db/frigate.db'
```

**Describe alternatives you've considered**
N/A

**Additional context**
In versions before 13 the database file was located at /frigate.db. That allowed me to mount this file from an arbitrary location. Now the location is moved to /config/frigate.db. While convenient, it's a bad practice to allow the application to change the its own configuration. Personally, I store the frigate config in a git repo and then ship it to a machine running Frigate via ansible. The config directory is mounted readonly in the frigate container.

While I could mount a file on top of the config directory (as I do now for root), it would be much more convenient for me to configure a separate directory (as /media). 

In addition from the release notes:
The migration is handled for you, but you must make sure that the docker CLI or docker-compose binds the entire /config directory and not just the /config/config.yml file.

Can this be disabled? What happens if I just move the db myself?

**Comment by NickM-27** [comment]
Frigate has supported configuring the DB path for many versions

https://docs.frigate.video/configuration/advanced#database

**Comment by ivlis** [comment]
Hmm, but what means the breaking change is not breaking change if I configure the db location, correct?

**Comment by NickM-27** [comment]
the change is only for the default location, if you manually configure a db location then frigate will use that instead
