### ISSUE TITLE
[Support]: Frigate+ plus 

### ISSUE THREAD

**Issue by kiloptero** [blakeblackshear/frigate#8684]
### Describe the problem you are having

hi all! just want to know if the 50/year plus suscription able to download new object detect like box etc? Any experience with that the 12 model trainning credits are for that? thanks a lot!

### Version

n/a

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink

**Comment by NickM-27** [comment]
It's not clear to me what you're asking, but I'd suggest reading the FAQ https://deploy-preview-6262--frigate-docs.netlify.app/plus/#frequently-asked-questions

**Comment by kiloptero** [comment]
yes , i read that. the question if this frigate + include new objects ?

**Comment by NickM-27** [comment]
the currently supported objects are listed on that same page https://deploy-preview-6262--frigate-docs.netlify.app/plus/#available-label-types
