### ISSUE TITLE
[Config Support]:  entities no longer detected after last HA update

### ISSUE THREAD

**Issue by goodsale** [blakeblackshear/frigate#8688]
### Describe the problem you are having

After the latest update of Home Assistant (2023.11.2)  the entities are no longer detected even if the frigate server is online and working.

that is the question:

![image](https://github.com/blakeblackshear/frigate/assets/6981274/4f98e4a9-31eb-439c-93fa-123e1a539784)

### Version

0.12.1

### Frigate config file

```yaml
same (never change)
```

### Relevant log output

```shell
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
This is an integration issue and should be posted in that repo
