### ISSUE TITLE
Stop using OpenCV

### ISSUE THREAD

**Issue by blakeblackshear** [blakeblackshear/frigate#87]
OpenCV is still used for determining the camera resolution. We need to switch to ffprobe in order to avoid the limitations built into OpenCV:
```
ffprobe -v panic -show_error -show_streams -of json "<rtsp_url>"
```

**Comment by ebendl** [comment]
Primary problem that trigged this issue is that OpenCV forces a TCP connection, so some cameras that only uses RDP as the transport can't be used. 

ffmpeg has no limitations like this. 

More info: https://answers.opencv.org/question/120699/can-opencv-310-be-set-to-capture-an-rtsp-stream-over-udp/
