### ISSUE TITLE
[Support]: Frigate to Flash Coral TPUs firmware (usb) ? (or why not?)

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#8709]
### Describe the problem you are having

From my research and testing, it seems that using a Google Coral USB based TPU, you *first* have to flash firmware to the device.  (then if power is cut to the USB device, at any point, it reverts to needing to be firmware flashed again).

**Thus my question is why does frigate itself not flash the firmware to Google to the coral TPU? If it detects "global unichip" (via lsusb), then do the flash commands automatically (ie the steps we manually do from coral.ai).** 

please correct me if im wrong and this feature already exists in frigate - *or if not* what is the reason it hasn't been implemented? 
(ie is it perhaps a licensing/IP issue re: google's FW,  or maybe its just beyond the scope of Frigates intended functionality?)

It just seems that Google made a horrible decision in not having some kind of non-volatile flash firmware, and at the same time a coral is essentially required or strongly recommended when using Frigate.  (Thus the need to re-flash if power cut to the coral USB, makes frigate a very "hands on" service to run).  (im aware of the m-pcie coral, which is what i have now ordered and will test)
thanks

### Version

0.12

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

axis p3265-lve

**Comment by NickM-27** [comment]
The Google coral USB loads its own internal driver. Frigate does flash the max speed runtime when it connects to the coral.
