### ISSUE TITLE
sizes for min_area and max_area ?

### ISSUE THREAD

**Issue by burton666** [blakeblackshear/frigate#872]
I could not find this in the documentation. But is there any way to validate the min_area and max_area values ? I don't know how big 4000 or 100000 is. Is trial and error the way to go or can I somehow get the area size for a detected object ?

**Comment by paularmstrong** [comment]
It's the area of width * height of pixels on your detect stream.

So if your camera detect role is 1280x720, the total area of the camera is 921600. If a person standing in front of the camera is only half the height of the camera view and 1/8th the width, that's 160 wide * 240 height = 38400

**Comment by HITChris** [comment]
To help with trial and error, you can add a test 'camera' that loops through an existing clip & then observe that it in real-time via the debug stream

` CameraTest:   
    ffmpeg:
      inputs:
        - path: /media/frigate/clips/mycliphere.mp4
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - detect
    width: 1920
    height: 1080
    fps: 5
    detect:
      enabled: true
    clips:
      enabled: false
    record:
      enabled: false
    rtmp:
      enabled: false
    snapshots:
      enabled: false
    mqtt:
      enabled: false
    objects:
      track:
        - person
`

**Comment by burton666** [comment]
Ok, after setting up some test labels like car, bird and person and waiting for some detections I get some values in the best picture of every detection. Like "Car 78% 62321", "bird 69% 736". is the last value the size of the detection box ?

**Comment by HITChris** [comment]
score*100 (%) and then area, yeah.
