### ISSUE TITLE
Intel Gassian and Neural Accelerator Support 

### ISSUE THREAD

**Issue by dougransom** [blakeblackshear/frigate#8730]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to offload detection tasks to the Intel Gaussian and Neural Accelerator so that I can use my hardware more efficiently.

**Describe the solution you'd like**

Necessity files installed with the amd64/intel installs.  https://github.com/intel/gna

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment]
GNA isn't used for object detection, it is mainly used for things like noise cancellation. It's also being discontinued

https://docs.openvino.ai/2023.1/openvino_docs_OV_UG_supported_plugins_GNA.html
