### ISSUE TITLE
[Support]: Error?

### ISSUE THREAD

**Issue by deanfourie1** [blakeblackshear/frigate#8741]
### Describe the problem you are having

So, very new to Frigate, and still learning. But when trying to pull a stream from my camera, I get the following error and UI shows frame loss.

I have confirmed the RTSP URL in VLC.

### Version

0.12.1-367d724

### Frigate config file
```


### FFprobe output from your camera

```shell
bash: ffprobe: command not found
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

HiLook

**Comment by NickM-27** [comment]
Please do not copy the reference config, it specifically says this. 

It is best to set everything up using the getting started guide https://docs.frigate.video/guides/getting_started

**Comment by deanfourie1** [comment]
> Please do not copy the reference config, it specifically says this.
> 
> It is best to set everything up using the getting started guide https://docs.frigate.video/guides/getting_started

Thank you! I have it working now,

However. I have 9 cams.

Frame rate is so slow for playback and recording, basicly to the point where it is useless.

Any way to increase frame rate?

Thanks

**Comment by NickM-27** [comment]
the recordings frame rate is copied from your camera so you would need to increase the frame rate on the camera settings

**Comment by deanfourie1** [comment]
Max FPS is set on cameras

**Comment by NickM-27** [comment]
What do you mean?

**Comment by NickM-27** [comment]
What do you mean?

**Comment by deanfourie1** [comment]
It's not recording frame rate it's live view it's like 5fps

**Comment by NickM-27** [comment]
the live view and the recordings are completely separate. Recordings are not changed from what comes from the camera. As far as live view goes I would highly suggest reading the docs https://docs.frigate.video/configuration/live

**Comment by deanfourie1** [comment]
Thanks, I'm getting the hang of it. Working quite well.

A few issues / questions I hope you can address, I tried to change the port to 80 in the container config and also tried 8080, but this didnt seem to work? Any idea or reason why this is?

```
ports:
      - "80:80"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

Also, is there any way to record on any motion, rather then events only?

Thanks

**Comment by deanfourie1** [comment]
The reason is I want to serve on port 80, not 5000

**Comment by NickM-27** [comment]
then you would map `80:5000` however important to keep in mind that ports below 1024 are restricted for root user only

**Comment by deanfourie1** [comment]
can you explain the 80:5000 logic, is this some kind of NAT mapping, or is this a docker thing?

80:host 5000:container?

Yes, thanks I am aware of the ports below 1024

**Comment by NickM-27** [comment]
yes, I'd suggest reading the docker docs https://docs.docker.com/network/#published-ports

**Comment by NickM-27** [comment]
closing this as the original issue is solved
