### ISSUE TITLE
[Config Support]: What is the relationship between "preset-record-generic-audio-aac" and go2rtc's "#audio=aac"

### ISSUE THREAD

**Issue by thinkloop** [blakeblackshear/frigate#8747]
### Describe the problem you are having

For audio one can define the AAC preset in output_args like so:

```
ffmpeg:
  output_args:
    record: preset-record-generic-audio-aac
```

As well as AAC in the go2rtc config like so:

```
go2rtc:
    porch_left:
      - rtsp://domain:554/cam/?#video=copy#audio=aac
```

What is the relationship between the two? Are both required?

### Version

n/a

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
They both do audio transcoding, #audio=aac transcodes the audio so go2rtc and Frigate can use it while the preset transcodes the audio for Frigate specifically
