### ISSUE TITLE
[Feature Request] Object Detection on "record" stream but motion detection on "detect" stream.

### ISSUE THREAD

**Issue by pstratem** [blakeblackshear/frigate#8756]
I was wondering if object detection would work better if done using the higher resolution "record" stream, but only when motion is detected on the lower resolution "detect" stream.

The cameras I have are 4k@20, but the sub-stream is maximum 704x480.

The 300x300 object detection box is most of the sub-stream's frame and that seems to be causing lets say "interesting" detection results.

**Comment by NickM-27** [comment]
also to note, you can always run detect on the main stream but use the `detect -> width / height` along with hwaccel to scale the stream down. For example you could use the 4k stream but frigate would scale it down to 1280x720 for detection

**Comment by pstratem** [comment]
I was thinking instead of decoding both streams in parallel going back to decode the recorded stream when motion is detected.

But now that I think about the pipeline that would be very different to how it's working now, so I'm guessing quite a bit of work.

I do think it would improve object detection results even on cameras that supported more reasonable sub stream resolutions.

**Comment by NickM-27** [comment]
> I do think it would improve object detection results even on cameras that supported more reasonable sub stream resolutions.

I would suggest reading https://docs.frigate.video/frigate/camera_setup#choosing-a-detect-resolution as that is not really the case after a certain point of using an appropriate sub stream resolution
