### ISSUE TITLE
[Support]: Birdseye view randomly chooses a bad layout

### ISSUE THREAD

**Issue by YBonline** [blakeblackshear/frigate#8767]
### Describe the problem you are having

Birdseye view does seem better MOST of the time, but for reasons I can't seem to figure out, it sometimes puts all the cameras on a single line, occasionally with one camera on the second. Here's an example:

![Screenshot 2023-11-27 163740](https://github.com/blakeblackshear/frigate/assets/11162258/aeda6e47-bea3-4112-89c9-eba37f1f6f78)

The detect resolution of the shown cameras is as follows, in order:
480x360 480x360 640x480 1920x1080 640x480

Here's another example:
![Screenshot 2023-11-27 164602](https://github.com/blakeblackshear/frigate/assets/11162258/21c5d743-b99b-49e2-82ed-e3c104ad4527)

480x360 480x360 2560x1920

### Version

0.13.0-5C4501E

### Frigate config file

```yaml
.
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

NA

**Comment by NickM-27** [comment]
at a minimum need to see global birdseye configuration

**Comment by NickM-27** [comment]
> Here's another example:
> ![Screenshot 2023-11-27 164602](https://github.com/blakeblackshear/frigate/assets/11162258/21c5d743-b99b-49e2-82ed-e3c104ad4527)
>
> 480x360 480x360 2560x1920

this is an optimal config. With 3 4x3 cameras there is no way there could be two cameras on one row and a single camera on the next row and fit within a 16x9 canvas without breaking the consistency rules that birdseye has in place

**Comment by YBonline** [comment]
Hmm, I guess under the assumption that it should always use full width that is true. I didn't manage to get a screenshot of it (or any way to know the full set of cameras on the view), but I had a few moments with I believe 8 cameras on one line before it corrected itself and went to a good view. I'll keep watching and see if I can get a screenshot of that, but for my first example, that one I assume is not optimal?

I am frequently left feeling like I should try to re-sort my cameras to optimize my birdseye view layout, but I haven't figured out my best approach yet

**Comment by NickM-27** [comment]
The first view is not optimal but I don't think it is an issue in the calculation itself. It may be an issue with the layout cache where that same number of cameras required more rows due to 32:9 cameras being included.

In general it is best to sort the cameras from widest to tallest, so 32x9, 16x9, 4x3

**Comment by NickM-27** [comment]
It clears on every restart. It's just a cache that keeps track of the relationship between # of cameras and the layout density

**Comment by YBonline** [comment]
I didn't get a chance to resort yet, but I had 6 in one row for a few moments and managed to capture it
![Screenshot 2023-11-28 110024](https://github.com/blakeblackshear/frigate/assets/11162258/6157e852-87cf-4b19-b5f2-ebbbceb2d0a5)

Resolutions are 1920x1080 1536x576 640x480 704x480 1920x1080 640x480

**Comment by YBonline** [comment]
So I did sort them as recommended right after my last comment and since then I haven't had any weirdness. Should I close this issue or is this still something you want to look into? Or perhaps add that advise to the documentation?

**Comment by NickM-27** [comment]
Thanks for updating. I think we can close this for now, if it becomes a common report then we can update the docs with the recommendation
