### ISSUE TITLE
Support for multicast DNS

### ISSUE THREAD

**Issue by vangorra** [blakeblackshear/frigate#8772]
**Describe what you are trying to accomplish and why in non technical terms**
Configure MQTT and cameras based on multicast dns. For example, being able to provide homeassistant.local for MQTT host instead of a static IP.

**Describe the solution you'd like**
A HostResolver class that does the following:
- If host ends with .local use `dnspython` to resolve an IP. Return the IP.
- Else return the provided host.

**Describe alternatives you've considered**
Local OS configuration changes are non-standard and messy.

**Additional context**
This is really a convenience feature.

**Comment by NickM-27** [comment]
This isn't going to be simple, generally this requires host networking which the addon and default config don't use. Frigate uses many ports donhost networking would have a higher chance of port conflicts

**Comment by vangorra** [comment]
Good point. Making the container support multicast is doable but only if it's configured to work with the host systems config. It's not really worth the effort and easier to implement dns internally.
