### ISSUE TITLE
Indicator for Birdseye that Stream is Live/Working (and not frozen) (example: 2x or more custom.png)

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#8789]
**Describe what you are trying to accomplish and why in non technical terms**
(TLDR: jump down to the first image down in this post)

Some kind of animated (or flashing) indicator - rendered into the Birdseye video feed (RTSP accessed, via birdseye->restream:true  , that shows it is live and working (and not frozen or stalled).  (even ability to add in a live timestamp, with seconds,  (perhaps under the logo / custom.png - would accomplish this)
- or another solution to this issue:  The ability to switch/flip between two different custom PNG images (ie every 3sec switch from custom1.png to custom2.png)

**Describe the solution you'd like**
Example-  Axis Network cameras offer a flashing/animated heart icon, so that its easy to visually see the stream is running / updating - see animated gif below of an example of this - (more modern generation Axis cameras, such as p3245-lve and on)

+ some Paid NVR solutions will have a different image (or warning message) that shows when the stream to a camera is lost or frozen (ie Milestone NVR does this, in its Smart Client , Client app)

**Additional context**
A well tuned Frigate setup using the Birdseye feature (set to mode: objects) - will frequently show just the black-screen with frigate logo (or other custom.png logo), which is correct/desired behavior - Assuming it's not a high-motion/high-activity location.  thus it will be difficult to Visually see if the stream has frozen or if there's an issue on the client side or the frigate side for in regards to the birdseye RTSP stream.   Any kind of visual indication that the stream is running would fix this (mainly via RTSP which will accessed 24/7 or be displayed 24/7)

Birdseye - and its ability to show activity from any of N number of cameras in real-time- Is a critical and unique feature that Frigate offers (i'm not aware of any DVR / NVR that offers similar functionality!  (Or at least at the same accuracy/quality as frigate's Birdseye) - it really is a great / differentiating feature for frigate!)

what this FR is about:
![image](https://github.com/blakeblackshear/frigate/assets/60830628/bf137581-eb6b-405a-a86a-b9cc3851770b)

axis network cameras animated "Streaming Indicator"
![animated heart](https://github.com/blakeblackshear/frigate/assets/60830628/86fc369c-2d89-4e7b-b25b-869dbe0821d3)

![image](https://github.com/blakeblackshear/frigate/assets/60830628/ec67c52d-a0c7-4004-81e7-04b00919afe8)

**Comment by bob454522** [comment]
I was able to manually force this to work via editing the ffmpeg cmd birdseye (in go2rtc) is using and adding (in go2rtc):

``` -ignore_loop 0 -i /config/loop2.gif -filter_complex "[0][1]overlay=0:H-100"  ```

  **I dont suggest doing this, as im not sure of the consequences / side-effects ,  i can say that in monitoring the bandwidth used by birdseye (in vlc via rtsp on a separate machine), there is very little increase in bw utilization (ie is still around 0.5mbit to 4mbit constantly on a 1080p birdseye w quality set to 16 in frigate settings)**

so my entire birdseye ffmpeg cmd looks like this (i uploaded the loop2.gif into the frigate docker container):

```
streams:
  birdseye: exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1920x1080
    -r 10 -i /tmp/cache/birdseye -ignore_loop 0 -i /config/loop2.gif -filter_complex "[0][1]overlay=0:H-100" -c:v libx264 -g 50 -profile:v high -level:v 4.1 -preset:v
    superfast -tune:v zerolatency -rtsp_transport tcp -f rtsp {output}
```

edited via at http: // frig-ip:5000/live/webrtc/editor.html

![animated heart2](https://github.com/blakeblackshear/frigate/assets/60830628/4d2df8c9-49f9-45fc-b315-1a9031291f8f)

(not the best animated gif to use, but was testing)

here is a good source of Transparent animated gif  (keyword transparent,  often called "stickers" too):
https://icons8.com/preloaders/

(many are better than that large one i have my example above)  -  i still think this would be a great option to have built into frigate / birdseye
(but im not a good coder else i would add a PR + add the structures to expose this option to the gui or config )  thanks!  
(LOVING FRIGATE!)

**Comment by NickM-27** [comment]
To be clear, that works fine when using software to do the encoding, won't work when using hwaccel (which is recommended by frigate docs)

**Comment by bob454522** [comment]
> To be clear, that works fine when using software to do the encoding, won't work when using hwaccel (which is recommended by frigate docs)

thanks,  that is good to know as later today im adding in a Quadro p1000 to help with the h264 streams - so that will save me troubleshooting.

**Comment by bob454522** [comment]
maybe an alternative could be to allow custom.png  to accept animated gifs ?  (or just allow it to accept .png or .gif  files which should cover animated gifs).

fwiw- i tried using an animated png (.apng file) with my method above directly editing ffmpeg,  but ffmpeg would not start (so prehaps ffmpeg does not support animated png files)

**Comment by bob454522** [comment]
> To be clear, that works fine when using software to do the encoding, won't work when using hwaccel (which is recommended by frigate docs)

@NickM-27  - were you referring to this not working on **non-nvidia** HW accel?  I ask as i have a 2nd test frigate with a quadro p1000 -> Docker frigate (which i plan to move over to my main real frigate hardware), and the overlay is working there also (on birdseye accessed via rtsp), via similar command:
```
streams:
  birdseye: exec:ffmpeg -hide_banner -f rawvideo -pix_fmt yuv420p -video_size 1280x720
    -r 10 -i /tmp/cache/birdseye -ignore_loop 0 -i /config/loop10.gif -filter_complex "[0][1]overlay=0:H-100" -c:v h264_nvenc -g 50 -profile:v high -level:v auto -preset:v p2 -tune:v ll -rtsp_transport tcp -f rtsp {output}
```
i doubt its relevant, but in terms of HW accel - im also running a coral tpu on this same test machine.

tks

![image](https://github.com/blakeblackshear/frigate/assets/60830628/1f6abe4c-1afc-4638-b60d-654da5785158)

**Comment by NickM-27** [comment]
you are not using the GPU for encoding the birdseye stream, which means you don't have hwaccel_args set globally

**Comment by bob454522** [comment]
> you are not using the GPU for encoding the birdseye stream, which means you don't have hwaccel_args set globally

im sure your right somewhere along the chain here, but the p1000 is encoding something (in addt to the various decodes);  it the pid matches the birdseye stream:

(i dont have a ton of experience w nvenc- so could be wrong-  just giving out the data)

![image](https://github.com/blakeblackshear/frigate/assets/60830628/bd8c0c7a-1351-4ac8-bb4e-337f8a1bc8f1)

**Comment by NickM-27** [comment]
ah nevermind, I forgot the birdseye nvidia args don't include a video filter, but some others do

https://github.com/blakeblackshear/frigate/blob/f00ced5a3332f1342d89b924a1e7ebb444528d0b/frigate/ffmpeg_presets.py#L87-L99

**Comment by NickM-27** [comment]
that should be fine then 👍
