### ISSUE TITLE
Stop multiple detections of static objects

### ISSUE THREAD

**Issue by burton666** [blakeblackshear/frigate#879]
Is ther some way to disable the "new" detections of static objects ? I tried setting up object detection for cars and bicycles in my driveway for testing but noticed that it would detect parked cars/bicicles multiple times if the lighting changes

**Comment by blakeblackshear** [comment]
Not currently. I may add better static object tracking in the future.

**Comment by cabmeeting1** [comment]
any update on this topic. I've tried many features and settings but still having issues static Bin and car on the street getting. detected. I've tried threshold, masking, zones, object filtering on zones.   to and from zones but still getting the parked car detected.

**Comment by Tuurkevg** [comment]
> any update on this topic. I've tried many features and settings but still having issues static Bin and car on the street getting. detected. I've tried threshold, masking, zones, object filtering on zones. to and from zones but still getting the parked car detected.


Same problem here.

**Comment by NickM-27** [comment]
@Tuurkevg please create a new issue so we can help directly
