### ISSUE TITLE
Timestamp conflicting with camera timestamp

### ISSUE THREAD

**Issue by mories76** [blakeblackshear/frigate#88]
Could you please make the new option of printing the timestamp configurable ?
My camera takes care of this, guess what, also in the upper left corner.

**Comment by kpine** [comment]
Is it possible to have the `show_timestamp` setting applied to the camera stream as well? Having only the FPS looks much better.

![image](https://user-images.githubusercontent.com/791794/72677820-499eda80-3a55-11ea-8a94-bbaef60cf690.png)

**Comment by kpine** [comment]
Or, how about the ability to just disable the stream overlay completely (both timestamp and fps)? I realized I don't need FPS either, since it's available in the `debug/stats` endpoint now. Personally, I just use the stream to check object detection and so the overlay is mostly in the way.

**Comment by blakeblackshear** [comment]
What are you using the mjpeg stream for? It is intended to be a debug tool and streaming from that endpoint increases load and steals CPU time from processing detected objects.

**Comment by kpine** [comment]
I _thought_ I was using it as a debug tool:
- Verify the region size settings (I need to visually see them)
- Observe object tracking so I know it's working as I expect
- Debug false positives

Are those not good reasons? Granted I don't use it too often, but when I do I don't need the time stamp and FPS for those purposes, and they just obscure the view. The FPS can be obtained from the debug stats and I'm not sure what I'd need the time for. All that is to say that for my use case the original behavior is preferred...

**Comment by blakeblackshear** [comment]
Those are the right reasons. Just wanted to be sure you weren't trying to use that endpoint to record to an NVR continuously.
