### ISSUE TITLE
Change default selected items in drop down lists

### ISSUE THREAD

**Issue by kavirondo** [blakeblackshear/frigate#8832]
Firstly, thank you for the great product and all the hard work. Much appreciated.

**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to quickly select a single Camera, Label or Zone in drop down lists in Events View, present behaviour selects all items first, and I have to manually deselct all the items I dont want, which for the 25 cameras we have is tedious.

The default behaviour is to select all items and to also have a show all button.

**Describe the solution you'd like**
It would be interesting to have the default behaviour to NOT select all items so that I can either select a few Cameras, Labels or Zones or press the SHOW ALL button to select everything

**Describe alternatives you've considered**
It could also be interesting to keep the behaviour as it is but add a SHOW NONE button so that I can quickly deselect all items in the drop down list.

Thank you for your consideration of this request.

**Comment by NickM-27** [comment]
> and I have to manually deselct all the items I dont want, which for the 25 cameras we have is tedious.

No you don't, just use the camera icon to select the single item you want.

**Comment by kavirondo** [comment]
Thank you very much for the feedback.

Is there a way to quickly select two or three? Seems to me if I could deselect all then pick a few (more than 1) would be handy.

**Comment by blakeblackshear** [comment]
Choose the first one by using the camera icon. Then select the check boxes for the next couple of cameras you want to add. This ends up taking one less click than if you had an unselect all button.
