### ISSUE TITLE
[Support]: API in Safari (macos, ios) not showing thumbnails in Home Assistant

### ISSUE THREAD

**Issue by rici44** [blakeblackshear/frigate#8837]
### Describe the problem you are having

API in Safari (macos, ios) not showing thumbnails in Home Assistant. In Google Chrome and Safari thumbnails are working correctly. The same situation is when using LAN and also external url. Home Assistant and Frigate are installed in docker under Ubuntu linux.

### Version

0.12.1-367D724

### Frigate config file

```yaml
Frigate is working correctly, but thumbnails are not showing in Safari browser.
```

### Relevant log output

```shell
Frigate is working correctly, but thumbnails are not showing in Safari browser.
```

### FFprobe output from your camera

```shell
Frigate is working correctly, but thumbnails are not showing in Safari browser.
```

### Frigate stats

```json
Frigate is working correctly, but thumbnails are not showing in Safari browser.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

On any camera

**Comment by NickM-27** [comment]
Where are you looking for thumbnails in home assistant?

**Comment by rici44** [comment]
Settimg > Devices > Frigate > Cam1  (see attached screenshot)

**Comment by NickM-27** [comment]
what about Cam1 Dog in chrome?

**Comment by rici44** [comment]
in chrome with thumbnail
in safari without

**Comment by NickM-27** [comment]
not seeing any examples in your last messages

**Comment by rici44** [comment]
In Safari
<img width="1222" alt="Screenshot 2023-12-02 at 22 53 23" src="https://github.com/blakeblackshear/frigate/assets/118632904/5849e4c0-6720-4fbf-b1e0-eb35b0750e5f">

in chrome 
<img width="1152" alt="Screenshot 2023-12-02 at 22 53 34" src="https://github.com/blakeblackshear/frigate/assets/118632904/177a7a2a-af25-4d15-8b3c-d4b17aee0b01">

**Comment by NickM-27** [comment]
Okay thanks for confirming, I would suggest creating an issue on home assistant frontend as frigate does not control what is displayed there

https://github.com/home-assistant/frontend

**Comment by rici44** [comment]
Thanks @NickM-27 I will.

**Comment by rici44** [comment]
@NickM-27  I tested other thumbnails in HA using Safari browser and same Street Cam Car detection with these results:

**HA > Media > Camera > Street Car (no thumbnail)**
<img width="566" alt="Screenshot 2023-12-03 at 09 30 55" src="https://github.com/blakeblackshear/frigate/assets/118632904/983c5360-426c-43b5-9140-e28cb59e8a01">

**HA > Media > Frigate > Snapshots > Today > Street Car (with thumbnail)**
<img width="564" alt="Screenshot 2023-12-03 at 09 31 44" src="https://github.com/blakeblackshear/frigate/assets/118632904/6431836d-cee0-4401-b0fd-377d01926c30">

**HA > Cam Page (view on lovelace)  > Street Car Cam (no thumbnail)**
<img width="568" alt="Screenshot 2023-12-03 at 09 38 30" src="https://github.com/blakeblackshear/frigate/assets/118632904/729fe77c-5bab-4ef7-8fbf-f0995fe2995d">


Could the problem not showing thumbnails be connected to Safari and API of Frigate if other thumbnails from media folders are showing correctly?

**Comment by blakeblackshear** [comment]
Could be something like this: https://stackoverflow.com/questions/57874197/base64-image-not-showing-up-breaking-in-safari
