### ISSUE TITLE
[Support]: Beta bug in time-lapse

### ISSUE THREAD

**Issue by donnievawter** [blakeblackshear/frigate#8884]
### Describe the problem you are having

When you choose at time for the time-lapse it uses a different time.
![badtime](https://github.com/blakeblackshear/frigate/assets/89166921/f54bd9ec-ee6e-46cf-8864-0b53a4a7e84c)

### Version

13-beta 6

### Frigate config file

```yaml
irrelevant
```

### Relevant log output

```shell
irrelevant
```

### FFprobe output from your camera

```shell
irrelevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

irrelevant

**Comment by NickM-27** [comment]
most likely you have just not refreshed to see the new item

**Comment by donnievawter** [comment]
That is not the issue. 
Anytime I create an export. The name of the file does not correspond to the times chosen.
I believe what is happening is the file is named using UTC times instead of local.

**Comment by NickM-27** [comment]
it uses whatever the timezone of the browser is and then converts to a unix timestamp. The file names for the export will be based on the timezone of the frigate server but the footage itself will be the correctly chosen time

**Comment by donnievawter** [comment]
Well both my browser and frigate server are in Mountain time zone and I have set the servers time zone to that but file name is still based on UTC. It is not a big deal and I can work with it and yes the actual footage is correct. I just think you are going to get support tickets unless it is documented somewhere. Not bitching, just trying to help better the user experience.

**Comment by NickM-27** [comment]
I am in the America/Denver timezone and exports match as expected so it seems something else must be going on and affecting things

**Comment by civita** [comment]
I had the similar request as Frigate is located in different timezone from my browser. From/To is based on browser timezone but export name is based on config timezone. Should ui -> timezone in config also apply to From/To in export tab?

**Comment by ehn** [comment]
Shouldn't all times displayed by Frigate always use the timezone of the Frigate location? When does it ever make sense to base things on where the user's browser happens to be at the moment? Surely, if I'm checking what happened at a site, I'm interested in what the time is/was there, not where I am.

(Side note: this doesn't mean that things should be based on the timezone of the server running Frigate. Servers are often set to UTC for good reasons.)
