### ISSUE TITLE
Unable to send video clip from Frigate in Telegram notification

### ISSUE THREAD

**Issue by HSB-collab** [blakeblackshear/frigate#889]
**Describe the bug**
When I receive an alert from a Frigate camera I would like to send the resultant video clip to my devices via the Telegram Bot. I able to send the thumbnail picture via the Telegram Bot, but I have spent hours trying to make it work with video. Both the Home Assistant Telegram and Frigate documentation refer to this use case, but neither shows how it is done. I could not get it done and would appreciate knowing if it is a configuration error on my part or a bug.

**Version of frigate**
1.13

**Config file**
Here is my automation’s yaml file which I got from the Frigate documentation (https://blakeblackshear.github.io/frigate/usage/home-assistant):
```
  alias: Frigate alerts
  description: Person/car detection in cameras from Frigate
  trigger:
  - platform: mqtt
    topic: frigate/events
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: notify.camera_alert_telegram
    data:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected on {{trigger.payload_json["after"]["camera"]}} '
      data:
        video:
        - url: https://******.duckdns.org:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/{{trigger.payload_json["after"]["camera"]}}/clip.mp4
          caption: Video caption for {{trigger.payload_json["after"]["label"]}} detected on {{ trigger.payload_json["after"]["camera"] }}
  mode: single
```

***Home Assistant Log with Error:
```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:584
Integration: Telegram bot (documentation, issues)
First occurred: 6:41:08 PM (2 occurrences)
Last logged: 6:46:11 PM

Error sending video: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out')). Args: (), kwargs: {'chat_id': 1698782360, 'video': <_io.BytesIO object at 0x7f92100a90>, 'caption': 'Video caption for car detected on Camera2', 'disable_notification': False, 'reply_markup': None, 'timeout': None, 'parse_mode': 'Markdown'}
Error sending video: urllib3 HTTPError ('Connection aborted.', timeout('The write operation timed out')). Args: (), kwargs: {'chat_id': 1698782360, 'video': <_io.BytesIO object at 0x7f91b4a630>, 'caption': 'Video caption for car detected on Camera2', 'disable_notification': False, 'reply_markup': None, 'timeout': None, 'parse_mode': 'Markdown'}
```
**Frigate container logs**
```
frigate.mqtt                   INFO    : Turning off clips for Camera1 via mqtt
frigate.mqtt                   INFO    : Turning off detection for Camera2 via mqtt
frigate.mqtt                   INFO    : Turning off clips for Camera2 via mqtt
frigate.mqtt                   INFO    : Turning off detection for Camera3 via mqtt
frigate.mqtt                   INFO    : Turning off clips for Camera3 via mqtt
frigate.mqtt                   INFO    : Turning off detection for Camera4 via mqtt
frigate.mqtt                   INFO    : Turning off clips for Camera4 via mqtt
```

**FFprobe from your camera**

Run the following command and paste output below
I was unable to run ffprobe on HassOS

**Computer Hardware**
 - OS: HassOS
 - Install method: Raspberry Pi Home Assistant installation procedure as per documentation
 - Virtualization: None
 - Coral Version: None]
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Sercomm
 - Model: iCamera2
 - Resolution: 720p
 - FPS: 2

**Additional context**

**Comment by blakeblackshear** [comment]
I would add a condition to only send on the 'end' event type. The clip won't be there until after the event is over, and multiple messages will be sent to that topic for each event. Also, your logs indicate that you have turned off clips via mqtt. Do you see the clip in the media browser or in the WebUI?

**Comment by HSB-collab** [comment]
Thanks for the response.

Yes, I am able to see the clips in the Media Browser and WebUI. I think those Frigate logs I sent you may have been out of date or incomplete. Clips have been turned on.

I have added the 'end' event condition as you suggest.

However, the Telegram Bot is still giving errors and is not sending any message, let alone the video clip as an attachment. Here are the error messages I am getting:
```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:268
Integration: Telegram bot (documentation, issues)
First occurred: 9:43:50 AM (5 occurrences)
Last logged: 9:43:50 AM
•	Status code 404 (retry #1) loading https://*******.duckdns.org:8123/api/frigate/notifications/1615243420.918555-p74r3k/Camera2/clip.mp4
--------------------------------------------------------------------------------------------
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:282
Integration: Telegram bot (documentation, issues)
First occurred: 9:43:50 AM (1 occurrences)
Last logged: 9:43:50 AM
Can't load data in https://*******.duckdns.org:8123/api/frigate/notifications/1615243420.918555-p74r3k/Camera2/clip.mp4 after 5 retries

--------------------------------------------------------------------------------------------
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:795
Integration: Telegram bot (documentation, issues)
First occurred: 9:43:50 AM (1 occurrences)
Last logged: 9:43:50 AM
Can't send file with kwargs: {'message': 'A car was detected on Camera2', 'url': 'https://*******.duckdns.org:8123/api/frigate/notifications/1615243420.918555-p74r3k/Camera2/clip.mp4', 'caption': 'Video caption for car detected on Camera2'}

--------------------------------------------------------------------------------------------

```
It looks like the Telegram Bot cannot access the video but I can't figure out why. If I send the thumbnail.jpg, the Telegram Bot works fine.
I would appreciate any help you can give.

**Comment by blakeblackshear** [comment]
Are you using the latest version of the integration? Earlier versions did not make the clip available. Also, you can try that url yourself in a browser to make sure it works.
