### ISSUE TITLE
Birdseye Restream without the logo

### ISSUE THREAD

**Issue by Natrinicle** [blakeblackshear/frigate#8900]
**Describe what you are trying to accomplish and why in non technical terms**
I added the birdseye stream to my Kodi instances in the form of strm files and used those for the video screensaver addon. Bit worried about the bird burning in if there are no active video feeds for a while. Would like the ability to make the background pure black.

**Describe the solution you'd like**
Would like the ability to disable the white bird and make the background pure black on the birdseye restream when no camera stream is forefront.

**Comment by NickM-27** [comment]
This is already possible with the custom icon https://docs.frigate.video/configuration/birdseye#custom-birdseye-icon

**Comment by Natrinicle** [comment]
Thanks for the tip! Unintuitive filename and path and a bit hidden in the documentation but it does indeed work!
