### ISSUE TITLE
Remote system for detection

### ISSUE THREAD

**Issue by ACiDGRiM** [blakeblackshear/frigate#8911]
**Describe what you are trying to accomplish and why in non technical terms**
I have a local desktop that runs frigate and homeassistant which is moderately powered with an intel gpu for detection. However I run a private cloud with GPU that I do all of my high performance work on, which is offsite.

I would like to be able to continue recording video on the local system, and forward interesting frames from the detect stream to a remote system, for analysis.

**Describe the solution you'd like**
In the detect configuration, I would like to be able to configure a few options
1) remote system endpoint to send frames for detection
2) limit fps sent to remote system
3) motion threshold before sending frames

**Describe alternatives you've considered**
I've considered running frigate on the remote system and connecting to the lower resolution stream of my cameras, however this would require significant bandwidth. My thought is that sending only frames with significant motion to the remote system, will reduce overall bandwidth.
I understand that the upload speed will be a limiting factor, however the ability to use more robust detection on interesting frames is attractive.

**Additional context**
This could be useful in more common situations where someone has both a medium powered appliance for home automation and a system with gpu capabilities in the same network. 
A frigate-frigate architecture could be an option, or a generic  url could request "what is this" to an arbitrary api, allowing more flexibility in how "things" are detected.

**Comment by ACiDGRiM** [comment]
Thanks, this looks promising, I didn't notice the github docs had more info than frigate.video

**Comment by NickM-27** [comment]
To be clear that's not really the case, 0.13 is still in beta and docs.frigate.video is for the stable version.
