### ISSUE TITLE
[Support]: Documentation website out of date

### ISSUE THREAD

**Issue by FinnakaLite** [blakeblackshear/frigate#8934]
### Describe the problem you are having

I committed and merged an addition to the documentation website yesterday, not expecting my changes to be there so fast, of course, but while editing, I noticed the version live on `docs.frigate.video` seems to be a version from many months ago. I noticed this at least on the "Installation" page; it doesn't match up with the version in the docs folder, and even edits from months ago don't show.

Just thought I should point it out!

### Version

N/A

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
docs.frigate.video is the page for stable docs. Your commit along with many others are committed to the dev branch which holds the docs for the upcoming 0.13 which is currently in beta
