### ISSUE TITLE
Add Parameters to Timelapse export API for result duration and frames-per-second

### ISSUE THREAD

**Issue by jtut1731** [blakeblackshear/frigate#8964]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to request a timelapse export with a specific duration and frames per second instead of every export using the same parameters set in config's record\export\timelapse_args value.

**Describe the solution you'd like**
Add two optional parameters to the `POST /api/export/<camera>/start/<start-timestamp>/end/<end-timestamp>` API: length and fps. The length can be used to calculate the setpts value.

**Describe alternatives you've considered**
None

**Comment by NickM-27** [comment]
this was done on purpose as config only, at this point we're not looking to add ui configuration to timelapse output. 

Given the improvements coming to the UI to quickly review footage without exporting timelapses. Recommendation is to use the config option

**Comment by jtut1731** [comment]
Thanks for your reply Nick. But to be clear, this was a request to modify the API, not the UI. Both the API and UI could continue to use the default values set in the config. I was just requesting that two (optional) parameters be added to override those values on the API request. No UI work required for this improvement.

**Comment by morpheus8888** [comment]
Hi @blakeblackshear, thank you again for your amazing work on Frigate.

I’d like to kindly bring this issue back to attention. Being able to pass timelapse_args, speed_factor, or fps dynamically through the API when exporting recordings would be incredibly useful, especially for integrations with external tools or bots.

Right now, these parameters can only be set globally via the YAML config, which limits flexibility for use cases where different exports require different settings (e.g. varying time compression or resolution depending on user input).

Is there any chance support for this could be reconsidered or added in a future release?

Thanks again for your time and dedication to the project!
