### ISSUE TITLE
Object-specific record mode

### ISSUE THREAD

**Issue by MrGeeDub** [blakeblackshear/frigate#8974]
### Describe the problem you are having

Hi,

Is there a way to set object-specific record mode for events? For example, have person set to "all," and cars set to "active_object?"

I'd like the camera to record an event for the entire amount of time that the person is detected in the frame, even if they are stationary for a long time. But I don't want the same for cars. Once it determines a car is stationary, I'd like the recording to stop.

Thank you!

### Version

0.12.1 - 367D724

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
`active_objects` applies to all objects on the camera, not just the one that created the event. So it wouldn't make sense to have an object specific mode right now. Perhaps in the future if there is a way to only record when a particular object is active this would make more sense.
