### ISSUE TITLE
[Support]: API Export returns 404 

### ISSUE THREAD

**Issue by donnievawter** [blakeblackshear/frigate#8984]
### Describe the problem you are having

https://frigate.vawter.com/api/westfrigate/start/2023-12-16:11.20.00/end/2023-12-16:11.34.00 returns 404 error.
Is it because my timestamp format is wrong or some other reason?

### Version

Beta 13.6

### Frigate config file

```yaml
irrelevant. everything working fine except export
```

### Relevant log output

```shell
irrelevant
```

### FFprobe output from your camera

```shell
irrelevant
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink

### Any other information that may be helpful

I can create events successfully using API and get latest image etc so in general everything is working except exporting.

**Comment by NickM-27** [comment]
you are using the incorrect format, the api expects unix timestamps

**Comment by donnievawter** [comment]
msg.theurl = "https://frigate.vawter.com/api/westfrigate/start/1702752753/end/1702753955%E2%80%9D;
msg.payload = {
   "playback": "realtime"
};
The same results if I leave the payload out.
That still gives a 404 
And the time stamps correspond to good times as far as I can tell

￼
￼

I can successfully export from the GUI entering the MDT times corresponding to the timestamps both with Timelapse and realtime

**Comment by NickM-27** [comment]
The end of that url looks wrong. In any case you can check the url that was used in the nginx logs and use that as a starting point.

**Comment by donnievawter** [comment]
That is from docker logs



2023-12-16 20:15:41.197343094  192.168.10.131 - donvawter [16/Dec/2023:20:15:41 +0000] "POST /api/westfrigate/start/1702752753/end/1702753955 HTTP/1.1" 404 207 "-" "got (https://github.com/sindresorhus/got)" “172.27.224.1"

It helps if you put “export” before the camera name <sigh>
You can close the ticket
Thanks

**Comment by NickM-27** [comment]
Feel free to create a new issue if something else comes up
