### ISSUE TITLE
[Config Support]: ha_network_storage

### ISSUE THREAD

**Issue by wrohdewald** [blakeblackshear/frigate#9031]
### Describe the problem you are having

[https://docs.frigate.video/guides/ha_network_storage] is only valid if frigate is installed in the HA OS system. But it does not say so. My bare bone system is Debian with a qemu guest and docker for frigate. The prerequisites do not exclude this situation but /config would not work because /config would be outside of the qemu guest with HA OS.

So - could you either narrow the prerequisites or - much better - add a section for other configurations like mine? I think that additional requirement would be **Frigate runs within the HA OS as an Addon**.

### Version

https://docs.frigate.video/guides/ha_network_storage

### Frigate config file

```yaml
https://docs.frigate.video/guides/ha_network_storage
```

### Relevant log output

```shell
https://docs.frigate.video/guides/ha_network_storage
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
> [https://docs.frigate.video/guides/ha_network_storage] is only valid if frigate is installed in the HA OS system

The entire guide is called HA network storage and the prerequisites include only when running frigate in an HA addon , if you are not running frigate as an addon then it does not apply.

you can just reference the docker docs for how to set up network storage https://docs.docker.com/storage/volumes/#start-a-container-which-creates-a-volume-using-a-volume-driver
