### ISSUE TITLE
Frigate as a Supervisor addon with NVDEC support?

### ISSUE THREAD

**Issue by SashMare** [blakeblackshear/frigate#904]
Is it possible to somehow run Frigate Supervisor (HASSIO) with NVDEC support?

**Comment by blakeblackshear** [comment]
I will have to create it as a separate addon.

**Comment by arcidodo** [comment]
+1 :-)

**Comment by vityabool** [comment]
+1

**Comment by arcidodo** [comment]
https://github.com/arcidodo/frigate-hass-addons

forgotten to mention here..  but i made one for version  blakeblackshear/frigate:0.8.4-amd64nvidia

but don't forget to install the nvidia docker version..

**Comment by Paul-Vdp** [comment]
@arcidodo I did as you suggested, but after adding your repo the Frigate-Nvidia addon does not show up, only the two 'normal' ones ... ?

**Comment by arcidodo** [comment]
@Paul-Vdp weird.. here is it working.. 

<img width="781" alt="Schermafbeelding 2021-08-09 om 20 07 09" src="https://user-images.githubusercontent.com/678514/128752972-c60a3ecd-7273-44ba-8275-d957b69de84a.png">

**Comment by Paul-Vdp** [comment]
VERY weird indeed. This is what I've got :
![frigate](https://user-images.githubusercontent.com/17593073/128753568-97e49704-62d2-471d-9889-4ae61cbaa3ae.PNG)
Can't imagine where it can go so wrong ...

**Comment by arcidodo** [comment]
i removed the normal and beta version.. is it working now?

**Comment by Paul-Vdp** [comment]
YES it is ! Thanks a lot for the addon and your lightning fast support ...

**Comment by Paul-Vdp** [comment]
Good job, finally got my GPU working, halving my CPU load. Thanks again !

**Comment by bjammin** [comment]
Thanks to @arcidodo for this, bit I am worried I will get behind latest frigate releases.
@blakeblackshear any plans for an official nvidia version?

**Comment by NickM-27** [comment]
I'm not aware of any addons that actually support nvidia GPUs because the HA addon system does not apply the nvidia container runtime, use `--gpus=all` or anything else
