### ISSUE TITLE
[Support]: /ws endpoint (0.13.0-C35C7DA) throws error

### ISSUE THREAD

**Issue by ufoczek** [blakeblackshear/frigate#9049]
### Describe the problem you are having

Due to the required HTTP_UPGRADE header, access to the /ws endpoint results in the following error.

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
Does not apply.
```

### Relevant log output

```shell
frigate           | 2023-12-22 09:22:10.787854518  Traceback (most recent call last):
frigate           | 2023-12-22 09:22:10.787861986    File "/usr/lib/python3.9/wsgiref/handlers.py", line 137, in run
frigate           | 2023-12-22 09:22:10.787863851      self.result = application(self.environ, self.start_response)
frigate           | 2023-12-22 09:22:10.787865809    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgiutils.py", line 101, in __call__
frigate           | 2023-12-22 09:22:10.787867389      raise HandshakeError('Header %s is not defined' % key)
frigate           | 2023-12-22 09:22:10.787873922  ws4py.exc.HandshakeError: Header HTTP_UPGRADE is not defined
```

### FFprobe output from your camera

```shell
Does not apply.
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

does not apply

### Any other information that may be helpful

HTTP_UPGRADE header is set by nginx setup as reverse proxy. Requesting directly frigate beta 0.13.0-C35C7DA throws error.

**Comment by NickM-27** [comment]
This is going to be an issue on the nginx / proxy side, HTTP upgrade header is required to connect to a websocket and many users have used this throughout the beta

**Comment by ufoczek** [comment]
For those looking for a solution, nginx.conf example:
`server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
            proxy_pass http://frigate:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /ws {
            proxy_pass http://frigate:5000/ws;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }

        location /live {
            proxy_pass http://frigate:5000/live;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
}
`
