### ISSUE TITLE
Home Assistant Beta .13 is not updating from version 6 to 7

### ISSUE THREAD

**Issue by derekngibbs** [blakeblackshear/frigate#9071]
### Describe the problem you are having

Should the Beta version .13v6 auto-update in HA as an Add-on?

### Version

.13v6

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by chatz86** [comment]
I'm having the same problem on HASSOS installed on a Nuc with a Coral USB TPU

**Comment by derekngibbs** [comment]
Worked after core update and rebooting HA. The upgrade to beta 7 was successful
