### ISSUE TITLE
Bump go2rtc to later version

### ISSUE THREAD

**Issue by stickymongoose** [blakeblackshear/frigate#9080]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to connect to TPLink Kasa cameras

**Describe the solution you'd like**
Update the go2rtc version to 1.8 or later

**Describe alternatives you've considered**

**Additional context**

**Comment by NickM-27** [comment]
https://docs.frigate.video/configuration/advanced#custom-go2rtc-version
