### ISSUE TITLE
[PTZ camera USB neo id]: 

### ISSUE THREAD

**Issue by ItamarSimioni** [blakeblackshear/frigate#9084]
### Describe the problem you are having

Após Atualização da versão do OBS para 29 o Ptz controls quando clica na opção aplicar para capturar a porta serial da camera o obs fecha.

https://github.com/blakeblackshear/frigate/assets/153424553/0e85b054-64f1-4c9f-90ec-21f4f5bd9cf6

### Version

123

### Frigate config file

```yaml
asdas
```

### Relevant log output

```shell
sd
```

### FFprobe output from your camera

```shell
sdr
```

### Frigate stats

```json
sdr
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

neoid

### Any other information that may be helpful

ij

**Comment by NickM-27** [comment]
Seems like this was posted on the wrong repo
