### ISSUE TITLE
Add rabbits to frigate+

### ISSUE THREAD

**Issue by borgqueenx** [blakeblackshear/frigate#9086]
**Describe what you are trying to accomplish and why in non technical terms**
I would love for rabbits to be supported in frigate+ so i can see what they are up to in our garden and what damage they are doing.

**Describe the solution you'd like**
Adding more objects like rabbits to frigate+

**Describe alternatives you've considered**
There are none.

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/discussions/7932 is the best place to request labels.
