### ISSUE TITLE
[Support]: Manual Event Trigger / Recording error

### ISSUE THREAD

**Issue by MrSiO** [blakeblackshear/frigate#9089]
### Describe the problem you are having

With Beta version, we can now manually trigger events and recording:  
[](https://deploy-preview-6262--frigate-docs.netlify.app/integrations/api/#post-apieventscamera_namelabelcreate)

Using an HTTP POST request with the provided optional Body code, everything works great exept recording.
Snapshot is taken, box created. but its instantanious (no 30 secconds applied / automatically appears in past events).
Clip shows the following:
![image](https://github.com/blakeblackshear/frigate/assets/49870576/aa866943-9769-47da-8f24-4aab1d40e9d6)

I Usually have no recording issues with detected events on both my cams, but manually triggered events act differently.

**Side question**: When recording start, will my usual "buffer" time be included in the recording + the configured recording time?    (I have a 30 sec bufffer on my recordings..  so if the body of the manually triggered event is set to 30, will that create a 60 seconds recording that includes my buffer?

### Version

BETA: 0.13.0-E512406

### Frigate config file

```yaml
(body code)

{
    "sub_label": "My-Front-Doorbell",
    "duration": 30,
    "include_recording": true,
    "draw": {
        "boxes": [
            {
                "box": [
                    0.5,
                    0.5,
                    0.25,
                    0.25
                ],
                "color": [
                    255,
                    0,
                    0
                ],
                "score": 100
            }
        ]
    }
}
```

### Relevant log output

```shell
The media could not be loaded, either because the server or network failed or because the format is not supported.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1080,"width":1920},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest

**Comment by NickM-27** [comment]
This is covered in the docs, the recordings must still match the recording retention to be saved 

> Recording retention config still applies to manual events, if frigate is configured with mode: motion then the manual event will only keep recording segments when motion occurred.

**Comment by MrSiO** [comment]
> This is covered in the docs, the recordings must still match the recording retention to be saved
> 
> https://deploy-preview-6262--frigate-docs.netlify.app/integrations/api#post-apieventscamera_namelabelcreate
> 
> > Recording retention config still applies to manual events, if frigate is configured with mode: motion then the manual event will only keep recording segments when motion occurred.

Not the retention, but the Pre-Capture delay.
And type if type is object, not motion.

`ecord:
  enabled: True
  retain:
    days: 14
    mode: active_objects
  events:
    pre_capture: 15
    post_capture: 15    
    retain:
      default: 14
      mode: active_objects`

**Comment by NickM-27** [comment]
Exactly, you have set the retention type things active objects and since there were no active objects in the time frame of the manual event, no recordings were saved.

**Comment by MrSiO** [comment]
> Exactly, you have set the retention type as active objects and since there were no active objects in the time frame of the manual event, no recordings were saved.

Ho ok. I get it.
Then how do you suggest proceeding to force the 30 sec recording on event **even-if** there is not object detected?  (Want to record anyway)

**Comment by NickM-27** [comment]
If you want more than object recordings to be saved for events, change the event recording retention mode to motion

**Comment by MrSiO** [comment]
> If you want more than object recordings to be saved for events, change the event recording retention mode to motion

Ho I don't want to do that.
Object detection is now tweaked and working real good.  (exept for fast / running person).

So manually triggered recording without object or motion was my way to cope (using the doorbell trigger). 

I might try then to increase the 5 FPS on the detection video feed to try to capure fast passing by person.
Any other ideas?

**Comment by NickM-27** [comment]
> Ho I don't wish to do that.
Object detection is now tweaked and working real good. (exept for fast / running person rigning my doorbell).

I think you are misunderstanding what it actually means to change the event recording mode, it doesn't change that "events" are only objects. Literally the only thing that changes is what is recorded when an object is detected or when you create a custom event

**Comment by MrSiO** [comment]
> > Ho I don't wish to do that.
> > Object detection is now tweaked and working real good. (exept for fast / running person rigning my doorbell).
> 
> I think you are misunderstanding what it actually means to change the event recording mode, it doesn't change that "events" are only objects. Literally the only thing that changes is what is recorded when an object is detected or when you create a custom event

Ok.
I will try it out and give you feedback.  Thx!

**Comment by MrSiO** [comment]
It works!  
Thx. I did not clearly undestand the motion vs object retain setting.  Thx again!

**Comment by filipcoja** [comment]
So, do I understand that correctly that I cannot trigger a recording of a manual event (which does not include any motion or any object) without setting the recording: retain: mode: all??

**Comment by NickM-27** [comment]
A lot has changed since this issue which is one and a half years old

**Comment by NickM-27** [comment]
> until there is a feature in frigate that you can also keep recording on manual events

this is already how it works in Frigate 0.15. A manual event is just an alert, and there is special handling to ensure manual events recordings are kept

**Comment by filipcoja** [comment]
For me it is not working like this, I only can see the video if there was motion unless i go to mode: all in the first retain option like this:

Working:

```
record:
  enabled: true
  retain:
    days: 7
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
```

Not working:

```
record:
  enabled: true
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
```

**Comment by NickM-27** [comment]
there is no need to set the `mode` for continuous recording. Just change the `mode` from `motion` to `all` for `alerts`

**Comment by filipcoja** [comment]
Ahh, I see, didnt even know what mode: all for alerts meant.. @NickM-27
