### ISSUE TITLE
Deprecated Constant Use - WARNING 

### ISSUE THREAD

**Issue by def1149** [blakeblackshear/frigate#9102]
### Describe the problem you are having

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 10:09:09 AM (1 occurrences)
Last logged: 10:09:09 AM

TEMP_CELSIUS was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/blakeblackshear/frigate-hass-integration/issues

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 10:09:09 AM (1 occurrences)
Last logged: 10:09:09 AM

TEMP_CELSIUS was used from frigate, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/blakeblackshear/frigate-hass-integration/issues
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

HA 2024.1.0b0

**Comment by NickM-27** [comment]
Thanks, this is an integration issue and covered by https://github.com/blakeblackshear/frigate-hass-integration/issues/587
