### ISSUE TITLE
[Docs] Update Synology docs to reflect 0.13 changes

### ISSUE THREAD

**Issue by baylanger** [blakeblackshear/frigate#9128]
### Describe the problem you are having

I am working on a PR to update Synology the docs and images.

Uploading pictures in here so that the doc.md files can reference them. Unlike the current 0.12 example that shows a container already created, the new doc will show the creation from scratch. Will create a PR and reference this issue, give me a day or two.

<img width="640" alt="2023-12-29_23-58-33" src="https://github.com/blakeblackshear/frigate/assets/5240348/4532b6fc-3d47-4132-bd19-8b62586058d2">

<img width="729" alt="2023-12-30_00-01-00" src="https://github.com/blakeblackshear/frigate/assets/5240348/0b06e7c7-580c-4a00-b9e4-9ed2c9a4f21b">

<img width="726" alt="2023-12-30_00-03-40" src="https://github.com/blakeblackshear/frigate/assets/5240348/6197dcec-95b0-4e02-8500-1423353fb3c8">

<img width="727" alt="2023-12-30_00-04-01" src="https://github.com/blakeblackshear/frigate/assets/5240348/c5f04e3f-0285-4261-8804-acbb7f8768ca">

<img width="726" alt="2023-12-30_00-04-33" src="https://github.com/blakeblackshear/frigate/assets/5240348/437c8d68-ceef-4e35-adb0-697ccacf226b">

<img width="726" alt="2023-12-30_00-05-56" src="https://github.com/blakeblackshear/frigate/assets/5240348/efe2466e-49f5-4e3e-b5b2-f69082bede31">

### Version

0.13

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

### Any other information that may be helpful

-

**Comment by baylanger** [comment]
Somehow the images are accessible via https://private-user-images.githubusercontent.com/.... 

Currently in the doc it points to htps://user-images.githubusercontent.com/...

Perhaps I'm not doing this the right way, if so please let me know.

**Comment by baylanger** [comment]
And I see in the git repo `./docs/static/img` - it's past midnight here, when I'm back to work on this, I'll check the links in the latest doc and might use that instead.

**Comment by NickM-27** [comment]
generally would be best to make the PR hold the images in the /img folder directly

**Comment by baylanger** [comment]
On my Synology the instance is created using a `docker-compose.yml` file. The current Frigate docs uses the UI to show end users how to create the instance.

The UI has a lot of limitations. If I inspect the docker-compose.yml container with the UI created one:

- `Enable auto-restart` option sets the RestartPolicy to `always` , `unless-stopped` isn't available.
- `ShmSize` is set to `67108864` and can't be tuned.
- Mapping volumes outside of the docker installation volume , in my case `/volume1` , isn't possible. This prevents mounting `/dev/bus/usb` , `/dev/dri/renderD128` and `tmpfs`. `/dev/bus/usb` is needed for devices like Coral. `/dev/dri/renderD128` is needed for Intel hwaccel.

I am very tempted to drop the UI example and provide instructions based on a docker-compose.yml file.

Comments?

**Comment by NickM-27** [comment]
The current docs recommend using privileged mode which give access to the USB coral and hwaccel. docker compose example can be given but it needs to have images or be thorough enough that a more basic user can follow it

**Comment by baylanger** [comment]
I currently have the following entries for my NAS w/ an Intel J4125.

```
    devices:
      - "/dev/dri/renderD128" # for intel hwaccel
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      LIBVA_DRIVER_NAME: "i965"
```
The latest images might not require anymore the `devices` entry and the 2 volumes entries. If those were added to the frigate built image, they're likely not needed anymore. I plan to remove them all and tests. I'll make the appropriate changes based on the results. For sure, `LIBVA_DRIVER_NAME` is still required for the J4125.

The latest Synology UI allows to upload or paste the content of a `docker-compose.yml` via a new option "Project->Create". Unlike the old way to create an instance, the one currently in the Frigate doc, "Project" doesn't give the end-user the option to create a new directory for the path of the new instance. But using this method allows the end user to adjust the ShmSize.

Note that with the old way, the end user still needs to figure out how to create the `config` & `media` directories as well as upload a `config.yml` file. None of this is currently explained in the doc, my go to do this is ssh+vi but some would not consider that quite friendly :) 

Perhaps a simpler way to do this would be a script that the end user can paste in the `Task Scheduler` that allows the end user to run a script on the stop as root. At the top of the scripts, a few variables that can be edited. That script could create the required directories, download the latest default (blank) config file and then launch the docker instance.

That was longer to type that I originally thought.

**Comment by NickM-27** [comment]
> The latest images might not require anymore the devices entry and the 2 volumes entries. If those were added to the frigate built image, they're likely not needed anymore. I plan to remove them all and tests. I'll make the appropriate changes based on the results.

all of that is still required to be added in the users config, like the docs suggest.

**Comment by baylanger** [comment]
I'm running into more serious issues.

According to [this stackoverflow](https://stackoverflow.com/questions/73825556/adding-ghcr-github-docker-regustry-to-synology-docker-results-in-registry-ret) , it's not possible in via the UI to add the ghcr.io docker registry. That was confirmed by Synology.

```
2022-10-27 - Synology Support replied and the official statement is that the token authentication currently used by Github Container Registry is not supported on the DSM's Docker package GUI. Its possible to ssh to the DSM and use docker from the command line.
```

While searching on this topic, I stumble on [this blob](https://mariushosting.com/how-to-install-homarr-on-your-synology-nas/) - In Step 6, he does exactly what I've proposed above : use the "task scheduler" to launch the docker command that can fetch from ghcr.io.

The current doc for Synology doesn't mention how to add the registry and download the image...  but then, 0.12 was never published to the previous location `registry.hub.docker.com`. It's unclear if the current doc really helps someone with hardly no docker or CLI experiences. Perhaps most Synology users use the HA docker add on?

**Comment by NickM-27** [comment]
Yes sybology on HA OS VM is quite common

**Comment by baylanger** [comment]
FYI this is still in my head but found myself busy on a personal project. There's not much people complaining about the doc, I guess it's not so urgent to update 😄 but will still try to make it happen later.
