### ISSUE TITLE
MQTT and mosquitto not working

### ISSUE THREAD

**Issue by dmsviento** [blakeblackshear/frigate#9129]
### Describe the problem you are having

HI folks,

I'm obviously missing something here. So I have mosquitto install and for testing purposes have anonymous set to true in the conf
```
listener 1883
allow_anonymous true
```

I have mqtt enabled in frigate as follows:
```
mqtt:
  enabled: True
  host: <have ip of device hosting here>
  port: 1883
  topic_prefix: frigate
logger:
  default: debug
  logs:
    frigate.mqtt: debug
```

The frigate logs would seem to indicate that it is connected:

```
023-12-30 10:26:08.573840483  [2023-12-30 10:26:08] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-30 10:26:08.577452001  [2023-12-30 10:26:08] frigate.comms.mqtt             DEBUG   : MQTT connected
2023-12-30 10:26:08.607451589  [2023-12-30 10:26:08] detector.cpu                   INFO    : Starting detection process: 288
2023-12-30 10:26:08.608071623  [2023-12-30 10:26:08] frigate.app                    INFO    : Output process started: 290
```

However this is the only reference to mgtt in the logs. With debug logging enabled do mqtt post get logged? If I cause an event, I do not (or seem to not) get anything in mosguitto when listening with:

`mosquitto_sub -h <have ip of device hosting here> -t frigate`

Am I missing something spectacular
Many thanks

### Version

0.12.1-367d724

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
I would suggest using MQTT explorer to look at what is posted. 

You can't just watch on `frigate` because nothing is posted on that topic directly.

**Comment by dmsviento** [comment]
good shout, thank you
