### ISSUE TITLE
Events ending does not mean clips are ready, perhaps events should end when clips are ready.

### ISSUE THREAD

**Issue by borgqueenx** [blakeblackshear/frigate#9134]
**Describe what you are trying to accomplish and why in non technical terms**
Currently using telegram notifications to get notified when a event is going on and receive a clip of the event/action. I have a action to get the clip send to telegram, and also get a link to the event. Sometimes the video is not being posted, and most of the time the mp4 clip i open on frigate is not yet working, i have to try later to have it working.
The blueprint that's being used already waits for a event to end.
This is the blueprint that i use: https://gist.github.com/NdR91/5486a1e55101e062c48545395b7dd9a3
(i added a telegram send_message to the above blueprint that links to the clip file to watch it on the system, because often i do not get the video file in telegram)

**Describe the solution you'd like**
let frigate check if the event's clip/video is already available for being send and THEN complete the event ending, so the current silly delay solutions are not needed. Alternatively perhaps add a second event of when the clip is ready.

**Describe alternatives you've considered**
Adding a delay to the blueprint above helps, but still only to a certain extend. i still sometimes do not get videos send(could also be because file size supporter by telegram bot is exceeded), but when i get a video clip link, it should work immediately and be ready to watch.

**Additional context**
None.

Thanks for reading!

**Comment by NickM-27** [comment]
it doesn't make sense for the event to end after the event actually ended. If I want something to happen when a car leaves the camera view I don't want that action to be delayed because the clip is not ready.

There is a pinned request for a separate message when clips are done processing, closing this as a duplicate request of https://github.com/blakeblackshear/frigate/issues/2128
