### ISSUE TITLE
Health monitoring for go2rtc process

### ISSUE THREAD

**Issue by markfrancisonly** [blakeblackshear/frigate#9135]
**Describe the solution you'd like**
Rudimentary health monitoring of the go2rtc process and/or restream feeds, with the intention of recycling the go2rtc process if health check fails

**Additional context**
Today I caught the go2rtc 1.8.4 executable using 800% of my 24-cores in frigate 0.12.1 whilst go2rtc is typically using less than 50%. This is the first I've ever seen this happen. The result was 60% total cpu load when my debian host server is typically humming around 16% total cpu load.  

![cpu use](https://github.com/blakeblackshear/frigate/assets/12145270/f8d7bf79-756f-4ecb-87d9-bca88c1df87b)

Graphs show what looks like a memory leak which I now believe maybe go2rtc misbehaving in reaction to adding my 22nd frigate camera feed, a custom ffmpeg/go2rtc rtsp stream of my bambu labs x1c internal camera.

Experimented by opening a bash shell in the frigate container and 'pkill -n go2rtc' with good result. My cpu usage went back to normal and go2rtc was automatically restarted. Unfortunately I don't have a debug log to help troubleshoot go2rtc 1.8.4 

Acknowledging that go2rtc is essential

**Comment by NickM-27** [comment]
This already exists, frigate has an ongoing health check and restarts go2rtc if that fails 

https://github.com/blakeblackshear/frigate/tree/dev/docker/main/rootfs/etc/s6-overlay/s6-rc.d/go2rtc-healthcheck

**Comment by markfrancisonly** [comment]
I see. 

Yes the go2rtc process was restarted automatically when I killed it, but I'm unsure if the s6 component would have detected the run away cpu load and assume s6 won't address a frozen streams. 

In my bambu x1c camera streaming container, I use the following bash function to check the go2rtc api to determine if the feed has failed. In the case of frigate, recycling all camera feeds for a single feed doesn't immediately seem justifiable but the concept is applicable (sorry for the intentional doublespeak):

```
# Function to perform health check  
perform_health_check() {
    response=$(curl -s "http://localhost:1984/api/streams?src=bbl")
    timestamp=$(date +"%T.%3N")

    if [[ $(echo "$response" | jq '.producers | length') -eq 0 ]]; then
        pkill -f bambusource2raw
        echo "$timestamp Service has failed. bambusource2raw process killed" 
        rm -f "$CONNECTION_TIME_FILE"  # Remove the file when the service fails
    else
        
        received_bytes=$(echo "$response" | jq -r '.producers[0].recv')

        if [ -f "$CONNECTION_TIME_FILE" ]; then
            connection_start_time=$(stat -c %Y "$CONNECTION_TIME_FILE")            
            connection_duration=$(( $(date +%s) - connection_start_time ))
            received_bytes_init=$(cat "$CONNECTION_TIME_FILE")
            bit_rate=$(((received_bytes-received_bytes_init) / connection_duration * 8 / 1024))
            echo "$(format_timestamp) Streaming $(format_duration $connection_duration) average ${bit_rate}kb/s"
        else
            echo "$(format_timestamp) Connection established $received_bytes bytes received"
            echo "$received_bytes" > "$CONNECTION_TIME_FILE"
            connection_duration=0
        fi
    fi
}
```

**Comment by NickM-27** [comment]
The S6 process checks go2rtc api and if it does not receive a response then it will restart go2rtc, this can happen when it is killed or just when a process in go2rtc panics.
