### ISSUE TITLE
[Frigate Plus]:  any keyboard shortcut to hit SAVE (when Annotateing a bounding box) in Frigate+ webGUI (not frigate NVR)

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#9149]
### Describe the problem you are having

When adding bounding boxes over in frigate plus (plus.frigate.video),  Is there a keyboard shortcut for clicking the save button when modifying the annotation for a bounding box  (ie choosing: person, cat, dog etc)

I ask as I'm trying to do this as quick as possible and keep one hand on the mouse and one hand on the keyboard (but move through images quickly and efficiently)

btw- the web interface over there is EXCELLENT!  very fast , and very well thought out. (and very efficient!)

im referring to this (in photo below):
(The only keyboard shortcut I know of currently consists of 3x key presses:  ie  press tab twice then space bar, which moves the selector to the save button and space-bar presses it - But I was hoping for a single key to save).

it is also GREAT that you can hit P for person,  C for cat, or cycle though them (This might be a feature of the browser though in my case Firefox 120.x)

(another Option of course is to bind something specific in auto hotkey for those three key presses).

- If this keyboard shortcut does not exist, I think it's something that should definitely be implemented as it would speed up labeling quite a bit.  (Especially since the suggestion is that we label every object in a photo)
thanks
![image](https://github.com/blakeblackshear/frigate/assets/60830628/3019e720-e274-4de4-8002-33c60b83cdf6)

### Version

NA

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
NA
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA

**Comment by NickM-27** [comment]
I usually just do `tab + tab + space`, improvements are coming to the tool as well to make annotating more efficient
