### ISSUE TITLE
[Support]: Docs website does not match docs on GitHub

### ISSUE THREAD

**Issue by lindhe** [blakeblackshear/frigate#9156]
### Describe the problem you are having

It seems like the documentation available on https://docs.frigate.video does not match the documentation available here on GitHub. I assume GitHub is the most up-to-date, so the website should be updated accordingly.

### Examples

| <https://docs.frigate.video/configuration/#vscode-configuration-schema> | <https://github.com/blakeblackshear/frigate/blob/dev/docs/docs/configuration/index.md#vscode-configuration-schema> |
|--------|--------|
| ![Screenshot of website docs](https://github.com/blakeblackshear/frigate/assets/7773090/cb9ef66d-d1ee-4c6a-a323-ad7c43071e89) | ![Screenshot of GitHub docs](https://github.com/blakeblackshear/frigate/assets/7773090/b7dc47da-cc28-449c-8064-abb91c9e6636) |

**Comment by hawkeye217** [comment]
The docs on the `dev` branch are for 0.13 whereas the docs in `master` (and on docs.frigate.video) are for the current stable branch, 0.12.

**Comment by NickM-27** [comment]
0.13 docs are linked at the top of the release notes and available at https://deploy-preview-6262--frigate-docs.netlify.app/

**Comment by lindhe** [comment]
Ooops, missed that. :facepalm: Sorry.
