### ISSUE TITLE
[Support]: Clarify in docs if fields under `go2rtc` supports variable substitution

### ISSUE THREAD

**Issue by lindhe** [blakeblackshear/frigate#9162]
### Describe the problem you are having

In the `go2rtc` configuration, one can set default username and password for rtsp streams: <https://github.com/blakeblackshear/frigate/blob/49814b34d38730078e8412c924959c8fa06b6ac4/docs/docs/configuration/restream.md#securing-restream-with-authentication>

The docs states clearly that ["Frigate supports the use of environment variables starting with `FRIGATE_` only where specifically indicated in the configuration reference below"](https://github.com/blakeblackshear/frigate/blob/49814b34d38730078e8412c924959c8fa06b6ac4/docs/docs/configuration/index.md#environment-variable-substitution) and the [`go2rtc` field](https://github.com/blakeblackshear/frigate/blob/49814b34d38730078e8412c924959c8fa06b6ac4/docs/docs/configuration/index.md?plain=1#L437) has no mention of it. Therefore, it seems like variable substitution should not work for fields under `go2rtc`. Yet, it does! I tried it, and I found that at least for the list items under a stream object, variable substitution with with `FRIGATE_RTSP_USER` and `FRIGATE_RTSP_PASSWORD` works!

So I think the docs should be updated to clarify what the case is. And if we could clarify what holds for the `go2rtc.rtsp.username` and `go2rtc.rtsp.password`  fields too (which I have not tested), that would be great!

### Version

0.12.1

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

n/a

**Comment by Scrumplex** [comment]
I agree here. 

go2rtc also natively supports something like this, as stated here: https://github.com/AlexxIT/go2rtc/wiki/Configuration#environment-variables

So I initially tried `${ENV_VAR}` which resulted in `$<value>` as frigate already substituted the variable and left the $

**Comment by NickM-27** [comment]
This is covered in the docs at https://docs.frigate.video/configuration/#environment-variable-substitution
