### ISSUE TITLE
Add light control by ONVIF

### ISSUE THREAD

**Issue by mabed-fr** [blakeblackshear/frigate#9165]
Hello

I have just read and tested version 0.13.0 Release Candidate 1 and I am amazed by all the wonderful changes made!

the addition of onvif is great!

Do you think it would be possible to add support for turning on the camera spotlight manually (CONTROL PANEL) and automatically with configuration that would indicate what should turn on the light (object) as well? as to when to turn it off.

M.

**Comment by NickM-27** [comment]
LED control is not part of the onvif standard
