### ISSUE TITLE
Frigate+ stats

### ISSUE THREAD

**Issue by mabed-fr** [blakeblackshear/frigate#9170]
Hello,

With the output of the Frigate+ models, would it be possible to display in real time the number of elements as well as other statistics forming the frigate+ dataset/model? (on the frigate website ? user dashboard ?)

**Comment by NickM-27** [comment]
First off to be clear I don't work on frigate+ so the following is just based on my understanding. 

The frigate+ base model does not change in real time so real data wouldn't necessarily be relevant. 

This data may also be considered confidential and not want to be shared. 

In any case, frigate+ related requests should be directed to https://github.com/blakeblackshear/frigate/discussions/7932

**Comment by mabed-fr** [comment]
Perfect
