### ISSUE TITLE
[Support]: Incomplete documentation about restream (role)

### ISSUE THREAD

**Issue by lindhe** [blakeblackshear/frigate#9172]
### Describe the problem you are having

The current docs mentions "the new restream role":

https://github.com/blakeblackshear/frigate/blob/7b71c21c12c9ccb1d92580145fde92ec76a71d93/docs/docs/configuration/restream.md?plain=1#L39

Yet, there is no such role listed:

https://github.com/blakeblackshear/frigate/blob/7b71c21c12c9ccb1d92580145fde92ec76a71d93/docs/docs/configuration/cameras.md?plain=1#L12-L19

I don't know if it's simply a mistake calling it a "role", or if the table of available roles is out-of-date.

### Version

0.12.1

**Comment by NickM-27** [comment]
Early in 0.12 restream was a role and then it was changed to be a full go2rtc config, these docs just weren't updated

**Comment by lindhe** [comment]
Great. Thank you so much for the quick reply and fix!

Just want to note that your PR #9176 is towards the dev branch, and this should probably be changed in master too. I'm not familiar with your branching strategy, so you decide if that requires an additional PR or if dev gets merged/chery-picked into master.

**Comment by NickM-27** [comment]
I did it to master because (IMO) it is a relatively minor detail. 0.13 is in RC so when that becomes stable *soon* the docs will be updated on the main site as well

**Comment by lindhe** [comment]
I see. It took me a few hours of trial-and-error before I understood that the docs were misleading. Mind if I create a PR for it? Or is the 0.13.0 release so soon that it would be hard to merge it before?

**Comment by NickM-27** [comment]
I'm confused what is misleading? https://docs.frigate.video/configuration/restream#rtsp explains the restream and there is a guide on setting up go2rtc.
