### ISSUE TITLE
Remove/hide passwords from logs

### ISSUE THREAD

**Issue by JohannCR** [blakeblackshear/frigate#9174]
**Describe what you are trying to accomplish and why in non technical terms**
Can we remove or hide the passwords and usernames from the logs ? Obvious security risk^^

**Describe the solution you'd like**
config option to obfuscate values in logs or something similar

**Describe alternatives you've considered**
no idea

**Additional context**
none

**Comment by mabed-fr** [comment]
I use environment variables for the config, I would also like the logs to display them instead of the real identifiers.

**Comment by NickM-27** [comment]
What passwords do you see in logs? Frigate already obfuscates cameras user/pass

**Comment by JohannCR** [comment]
You're right in the frigate logs there are no camera passwords, but in the go2rtc logs there are... Do we need to take this up with AlexxIT ?

**Comment by NickM-27** [comment]
I would suggest making a request on the go2rtc repo that the go2rtc logs hide that information

**Comment by mabed-fr** [comment]
I also see in the API stats
/api/stats
