### ISSUE TITLE
Please add armv7 support in your GHCR image

### ISSUE THREAD

**Issue by nikp123** [blakeblackshear/frigate#9178]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use my OrangePi for Frigate.

**Describe the solution you'd like**
Since there used to be a DockerHub armv7 image, I'd like on for GHCR as well.

**Describe alternatives you've considered**
I can compile by hand or use the outdated DockerHub image, but that isn't a long term solution for users.

**Additional context**
none

**Comment by NickM-27** [comment]
Like it says in the 0.12 release notes, support for armv7 has ended for frigate. That said, orange pi should have no problems running a 64 bit OS, a handful of users are running on orange pi in 0.13 https://deploy-preview-6262--frigate-docs.netlify.app/frigate/hardware#rockchip-soc

**Comment by nikp123** [comment]
Thanks for the quick answer. I missed over that fact entirely.
