### ISSUE TITLE
[Documentation Fix]:  Jetson instructions point to wrong repo

### ISSUE THREAD

**Issue by isaacolsen94** [blakeblackshear/frigate#9182]
### Describe the problem you are having

From what I can tell the docs list the highlighted repo on dockerhub.
![image](https://github.com/blakeblackshear/frigate/assets/52682311/611c5508-67cd-42bf-9bdc-0b689a90d328)
But the repo is actually under @madsciencetist 

### Version

v0.13.0-rc1

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

Dev Board

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
> But the repo is actually under @madsciencetist

that is incorrect, the listed repo in the docs is correct, you can find the packages at https://github.com/blakeblackshear/frigate/pkgs/container/frigate

![Screen Shot 2024-01-02 at 11 27 48 AM](https://github.com/blakeblackshear/frigate/assets/14866235/e5ef603f-7212-4b98-8787-fcc1fe1a44a9)

**Comment by isaacolsen94** [comment]
> > But the repo is actually under @madsciencetist
> 
> that is incorrect, the listed repo in the docs is correct, you can find the packages at https://github.com/blakeblackshear/frigate/pkgs/container/frigate
> 
> ![Screen Shot 2024-01-02 at 11 27 48 AM](https://private-user-images.githubusercontent.com/14866235/293759178-e5ef603f-7212-4b98-8787-fcc1fe1a44a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjA0MDMsIm5iZiI6MTcwNDIyMDEwMywicGF0aCI6Ii8xNDg2NjIzNS8yOTM3NTkxNzgtZTVlZjYwM2YtNzIxMi00Yjk4LTg3ODctZmNjMWZlMWE0NGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE4MjgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzcxOWFkMjg4ZDlhNWEyODljNDIyZjUzZmVhNjZkZWYwMGJhNjkzMmJiZWM0NWMzOGJmMGMyY2IzY2Y2MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.797AXVEng-qds8DaiukgE0c9HXf7aDmtvtBMQrnDh_s)

Okay, then do you know why this error is being thrown? 
![image](https://github.com/blakeblackshear/frigate/assets/52682311/1262dc99-7433-4d57-a6f4-f902f2160419)

**Comment by isaacolsen94** [comment]
Okay I was able to get it to pull using: `docker pull ghcr.io/blakeblackshear/frigate:0.13.0-rc1-tensorrt-jp4`

Just me being an idiot. Thanks!

**Comment by NickM-27** [comment]
ah I see, the repo is correct but the image is wrong. https://deploy-preview-6262--frigate-docs.netlify.app/frigate/installation#docker shows the correct images once 0.13 is stable (and the release notes show the correct image)
