### ISSUE TITLE
[BUG] Connection already opened

### ISSUE THREAD

**Issue by thundergreen** [blakeblackshear/frigate#920]
**Describe the bug**
A clear and concise description of what your issue is.
After a while / restart or Home-Assistant I get a connection error. Does this mean it did not close the connection when restarting HASS?
**Version of frigate**
1.13
**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
not related```

**Frigate container logs**
```
https://pastebin.ddns.me/hoviyalasa.rb```

**Frigate stats**
```json
Internal Server Error```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Computer Hardware**
 - OS:  Ubuntu, 
 - Install method: Addon

 - Coral Version: PCIe
 - Network Setup: WiFi]

**Comment by edge360** [comment]
Seeing same here as well. Running docker - blakeblackshear/frigate:0.8.4-amd64
Restart does the trick, but it seems to pop up again within a few hours.

**Comment by Minglarn** [comment]
Seems that this is the same as: https://github.com/blakeblackshear/frigate/discussions/853

**Comment by erikarenhill** [comment]
I also started experiencing this, frigate stops working about once a day

**Comment by thundergreen** [comment]
I removed double take and no errors for 24 hours.well. must be related to either frigate or double take .

Another thing ..if frigate would support face recognition I wouldn't be needed to use double take ..well... We will see

**Comment by edge360** [comment]
I removed my automation that requests an the image via ha integration API and it slowed down the frequency of the crashes. I'll try and expose the images another way maybe. It It was recommended on #853 to downgrade, but I believe you'll have to downgrade both frigate and the ha add-on, which I didn't really want to do. Does anyone have a good method to catch the this particular crash and reboot via docker?

**Comment by Morphy99** [comment]
getting this too on docker amd64 stable. Tried downgrading to 0.8.1 but my config isn't valid:
`Error parsing config: extra keys not allowed @ data['cameras']['front']['ffmpeg']['input_args']`
