### ISSUE TITLE
Feature Request - Not autoplay clips 

### ISSUE THREAD

**Issue by akamel001** [blakeblackshear/frigate#921]
**Describe the Feature**
I'm trying to integrate clips that get generated from a doorbell camera (as a person / object gets detected) into home assistant as an iframe card. The integration works perfectly and i'm able to point the iframe to this url `https://HA_URL/api/frigate/notifications/<event-id>/<camera>/clip.mp4`. The issue is the video autoplays. So every time i pull up home assistant it autoplays the clip instead of waiting for me to hit the play button on the media player. 

Would it be possible to make this configurable? Or just disable autoplay in general for clips?

**Comment by paularmstrong** [comment]
This is the default behavior of a browser when it loads a video file directly. If you want to control this, you'll have to write your own HTML proxy page with something like:

```html
<video>
  <source src="https://HA_URL/api/frigate/notifications/<event-id>/<camera>/clip.mp4" type="video/mp4" />
</video>
```

**Comment by akamel001** [comment]
Ah, you are right, well that's rather annoying from the browser. I'll go ahead and close this feature request then. I think the best approach is to have the home assistant HACS integration create a camera entity with the latest clip if an event has one.
