### ISSUE TITLE
[Support]: Retention File Deletion Schedule

### ISSUE THREAD

**Issue by bugsysiegals** [blakeblackshear/frigate#9211]
### Describe the problem you are having

I keep my unRAID server with the HDD Array disks spun down to save energy; however, I've noticed they're spinning up every hour, it's recommended they do not spin up more than 5 times per day otherwise should never shut down, which is killing their lifespan.

I would like to set Frigate to run this process once per day rather than every hour ... how can I change this setting?

### Version

0.12.1-367D724

### Frigate config file

```yaml
abc
```

### Relevant log output

```shell
abc
```

### FFprobe output from your camera

```shell
abc
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
this is changed with the global expire_interval option which is in minutes

```
record:
  enabled: true
  expire_interval: 1440
```
