### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by muzzak123** [blakeblackshear/frigate#923]
Hi, I've been using Frigate for a few months now and it's very good. Well done.
I was just wondering if it was possible to use zone names in masks rather than the coordinates
eg I have these zones in my config
      driveway:
        coordinates: 1645,1080,1920,1080,1920,359,1328,318,1380,387,1452,398
      frontlawn:
        coordinates: 216,349,664,304,1279,298,1373,348,1366,456,1005,531,999,455,535,449,514,389,369,386,287,458,73,459
      steps:
        coordinates: 1248,1080,544,1080,896,448,1296,449
      toplawn:
        coordinates: 0,571,790,623,517,1080,0,1080

It's not possible for a car to be on the steps or toplawn so I was wondering if instead of something like 
      filters:
        car:
          mask:
            - 1248,1080,544,1080,896,448,1296,449
            - 0,571,790,623,517,1080,0,1080

I could have something more meaningful like 
      filters:
        car:
          mask:
            - steps
            - toplawn

I tried this example but I got 
"Error parsing config: invalid literal for int() with base 10: 'steps'"

**Comment by blakeblackshear** [comment]
This doesn't work as indicated by the error message. I think most users will want the coordinates for masks to be different than zones.
