### ISSUE TITLE
Run detection on API-created events

### ISSUE THREAD

**Issue by nwish** [blakeblackshear/frigate#9235]
**Describe what you are trying to accomplish and why in non technical terms**
**Describe the solution you'd like**
^^ I feel like these sort of mesh together here...

I'd like to see an HTTP API call payload option to run detection on the created event in any motion areas that are present at the time of the event creation.

**Describe alternatives you've considered**
None.

**Additional context**
I am triggering manual events via the API for doorbell button presses.  I also have detection set up across multiple zones, so by the time someone makes it to the doorbell to press the button, they're already the subject of an in-progress event.  However, I'd also like to see that detection occur on the manual event as well, so that it will show up in zone, label and sub-label filtering.

**Comment by NickM-27** [comment]
Why do this when an event for the person already exists? At that point the doorbell event is entirely redundant.

**Comment by nwish** [comment]
> Why do this when an event for the person already exists? At that point the doorbell event is entirely redundant.

100% redundant, but the beta docs do mention “doorbell press” as an example use case 🤷🏼‍♂️ I might be misunderstanding the purpose of the manually created events, because if someone is NOT using motion/detection to trigger events on their doorbell and relying solely on the button press, they won’t get detection at all, so no Double Take.

**Comment by NickM-27** [comment]
Manual events are not meant to replace running actual detection, it is for edge cases where you would want something to be saved that wouldn't normally be an event like doorbell press, some external motion sensor, garage door opening, etc. 

If face recognition is wanted then person detection should be used like normal.

**Comment by NickM-27** [comment]
Going to close this as I don't see what this would add outside of existing motion + object detection that frigate does. Other users can leave a 👍 and their use case, perhaps there's something that isn't being thought of right now.

**Comment by dugite-code** [comment]
Hi, my use case for this would be to enable flexible use of external sensors like a mmWave sensor or even a PIR sensor. I have a large amount of ferns in my yard that also cast a lot of shadow, This means I have had to be quite aggressive with motion masks. This is making the image based motion detection and object detection false positives quite terrible and unreliable. This is especially true with my front door where a I have so many false positives I've disabled motion detection altogether.

Being able to trigger an event and run it through object/person detection would allow a lot of flexibility others may wish to take advantage of, especially with indoor cameras.

**Comment by NickM-27** [comment]
There are existing solutions for reducing false positives, better models,  etc that are generally able to help with false positives. I think we would definitely have suggestions given examples.

Single momentary frame based detection is not how frigate is designed to work

**Comment by dugite-code** [comment]
> Single momentary frame based detection

I do understand that, but being able to "wake up" frigate to begin checking for motion and objects/persons is the general ask I and, from my reading, every one else is interested in.
