### ISSUE TITLE
Enhanced Comment Formatting

### ISSUE THREAD

**Issue by TiwariBro** [blakeblackshear/frigate#9241]
Description:
I want to be able to format comments more effectively so that I can improve the readability and organization of discussions within the project.

Solution:
I suggest introducing support for basic text formatting in comments, such as bold, italic, and bullet points. This would allow users to emphasize important points, highlight code snippets, or create structured lists within the comments.

Alternatives Considered:
An alternative could be integrating a Markdown-like syntax for comments, but a more straightforward solution might be to provide a toolbar with formatting options directly in the comment box.

Additional Context:
In many discussions, particularly those involving code reviews or detailed explanations, the ability to format comments would greatly enhance communication and comprehension. It would be helpful for users to convey their thoughts more clearly and create a more organized comment section.

**Comment by NickM-27** [comment]
GitHub supports all of this, unless I'm really misunderstanding this is not a frigate feature request
