### ISSUE TITLE
Adding a camera using the API

### ISSUE THREAD

**Issue by dan246** [blakeblackshear/frigate#9252]
I want to add a camera using API and automatically send and receive notifications. Is it possible, and if so, how can it be implemented?

thank you!

**Comment by NickM-27** [comment]
This is not possible directly, the config file can be edited via the api however. Can you elaborate why you'd want to do this? I don't think adding cameras in of itself makes sense via the api other than by creating a gui to add cameras.

**Comment by dan246** [comment]
> 這不可能直接實現，但是可以透過 api 編輯設定檔。您能詳細說明為什麼要這樣做嗎？我認為除了創建一個 gui 來添加相機之外，透過 api 添加相機本身沒有意義。
Hi Nick,
I want users to be able to quickly add cameras through an API. How can I modify the config file using an API? Thank you very much.

**Comment by NickM-27** [comment]
Right, but how would you use it and how would you expect that camera to be treated? I don't think this fits with the frigate use case. 

The existing api exists here https://github.com/blakeblackshear/frigate/blob/c5ccc0fb08cdcfd35d2dae534724103bfb7c82a8/frigate/http.py#L1288

**Comment by dan246** [comment]
> Right, but how would you use it and how would you expect that camera to be treated? I don't think this fits with the frigate use case.
> 
> The existing api exists here
> 
> https://github.com/blakeblackshear/frigate/blob/c5ccc0fb08cdcfd35d2dae534724103bfb7c82a8/frigate/http.py#L1288

I want users to be able to input basic settings such as camera_name, path (RTSP URL), objects, etc., and add a camera for the recognition they need. Is this feasible?

**Comment by dan246** [comment]
> Right, but how would you use it and how would you expect that camera to be treated? I don't think this fits with the frigate use case.
> 
> The existing api exists here
> 
> https://github.com/blakeblackshear/frigate/blob/c5ccc0fb08cdcfd35d2dae534724103bfb7c82a8/frigate/http.py#L1288

Hello, I used the /config/set API, but it doesn't seem to be working. I'd like to inquire about what might be wrong on my end

POSTMAN output：
<html>

<head>
    <title>405 Not Allowed</title>
</head>

<body>
    <script>
        window.baseUrl="/";
    </script>
    <center>
        <h1>405 Not Allowed</h1>
    </center>
    <hr>
    <center>nginx/1.22.1</center>
</body>

</html>

**Comment by NickM-27** [comment]
this api only exists in 0.13, not 0.12. 

I think this API should be used for this use case so going to close this feature request. Feel free to create a discussion if you have further questions about using the api

**Comment by dan246** [comment]
> this api only exists in 0.13, not 0.12.
> 
> I think this API should be used for this use case so going to close this feature request. Feel free to create a discussion if you have further questions about using the api

Hello, I tried updating to version 0.13 and called this API in Postman, but it doesn't seem to be working correctly. Could you provide an example to help me understand?

version
![image](https://github.com/blakeblackshear/frigate/assets/72447312/be994c2a-1546-4caa-b5a7-550a058b4a50)

thank you
