### ISSUE TITLE
[Question] Doorbell flow

### ISSUE THREAD

**Issue by petergerdes** [blakeblackshear/frigate#926]
First of all, thanks for the wonderful work on Frigate, absolutely well done!

I'm trying to setup a doorbell flow in Home-Assistant, something like: `Doorbell pressed -> Record 10 seconds video -> Send video through a service (e.g. push-notification/Telegram/etc)`. Since there is no manual record option (through MQTT), what would be a good flow to setup a doorbell situation? Using `stream` in Home-Assistant to record the RTSP stream doesn't consistently work. I was looking at an option like: Saving the last ID of recognised person and sending that clip, but the clip is not done saving after 10 seconds after doorbell is pressed. Any ideas are appreciated!

**Version of frigate**
`0.8.4-5043040`

**Computer Hardware**
 - OS: Synology DSM
 - Install method: Docker Compose
 - Virtualization: docker
 - Coral Version: none
 - Network Setup: wired

**Camera Info:**
 - Manufacturer: ReoLink
 - Model: RLC-410-5MP
 - Resolution: 2560
 - FPS: 5

**Comment by jressel01** [comment]
i use Node Red Flow.
If i get a MQTT move event i take the after ID and have the capture/snapshot and wait for the Ring event if i have both i send it to Telegram. if i dont get the ring event the flow do nothing and wait for the next.

**Comment by blakeblackshear** [comment]
I would suggest using the http endpoint for latest for best person images. The clip could be added to the notification once the event ends.

**Comment by SchmDan** [comment]
For this scenario and some others i would love to have an endpoint to trigger the recording. I imagine that the frigate detection isn't working or turned off, but some classic motion sensors detect motion or the doorbell is pressed, then i would love to have the recording in frigate too. Frigate would be a single point of source.
What do you think about this idea?
