### ISSUE TITLE
Increase nginx-vod-module MAX_CLIPS constant value

### ISSUE THREAD

**Issue by ogero** [blakeblackshear/frigate#9266]
I've been trying to download daily camera footage videos by combining `ffmpeg` and the vod api from https://github.com/blakeblackshear/frigate/blob/v0.12.1/frigate/http.py#L1144

But I keep hitting the ([patched](https://github.com/blakeblackshear/frigate/blob/c5ccc0fb08cdcfd35d2dae534724103bfb7c82a8/docker/main/build_nginx.sh#L31)) `MAX_CLIPS = 1080` [limit](https://github.com/kaltura/nginx-vod-module/blob/master/vod/media_set_parser.c#L244) of __nginx-vod-module__, unless I go down to timeframes of ~6hs.

Would you consider a PR increasing the `MAX_CLIPS` constant for __nginx-vod-module__ to something around `6000`?

**Comment by NickM-27** [comment]
the value will always be arbitrary and maybe increased for a different use case. In 0.13 the export api was created and this intelligently handles this scenario, I would suggest just using that

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/blob/c5ccc0fb08cdcfd35d2dae534724103bfb7c82a8/frigate/record/export.py#L86-L96
