### ISSUE TITLE
[Support]: Will Not Connect (yes that again)

### ISSUE THREAD

**Issue by mrmarria** [blakeblackshear/frigate#9279]
### Describe the problem you are having

I installed debian12 VM on FreeBSD 
in the VM install Home Assistant as a docker (no-compose) container
Also the HACS installation is a docker container. They see each other
Added Frigate Through HA Settings>Devices and services>Add integration>Frigate  and it fails connection
![Frigate Connect Fail](https://github.com/blakeblackshear/frigate/assets/119546672/a2bc906a-f035-4106-a90e-14502c5761e3)

### Version

4.1

### Frigate config file

```yaml
mqtt:
#  host: homeassistant
  host: 127.0.0.1
  user: XXXX
  password: XXXXXXXX

cameras:
  office_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:XXXXXXXXX@192.168.5.65:554
          roles:
            - detect
            - rtmp
#            rtmp:
#             enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920
      height: 1080
      fps: 5

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
                type: module
```

### Relevant log output

```shell
Logger: custom_components.frigate.api
Source: custom_components/frigate/api.py:227
Integration: Frigate (documentation, issues)
First occurred: January 5, 2024 at 2:52:21 PM (6 occurrences)
Last logged: 3:36:19 PM

    Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name does not resolve]
    Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [Name does not resolve]
    Error fetching information from http://192.168.5.10:5000/api/stats: Cannot connect to host 192.168.5.10:5000 ssl:default [Connect call failed ('192.168.5.10', 5000)]
    Error fetching information from http://127.0.0.1:5000/api/stats: Cannot connect to host 127.0.0.1:5000 ssl:default [Connect call failed ('127.0.0.1', 5000)]
```

### FFprobe output from your camera

```shell
run where
```

### Frigate stats

```json
unknown
```

### Operating system

HassOS

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Amcrest DB AD410 IP2M-836EW-AI-V2 ASH22-W IP2M-841B-V3

### Any other information that may be helpful

Tried reinstall on fresh VM a couple times - no progress over several weeks

Dahua integration works - opens all 4 Amcrest cameras

**Comment by NickM-27** [comment]
need to see the logs of frigate itself

**Comment by mrmarria** [comment]
That was quick!  Where are frigate logs outside of HA? Don't see in:
HA >  Settings > Devices > Frigate Card > Log Book
or on VM
 www/community/frigate-hass-card/    or
custom_components/frigate/

have full HA logs.....

**Comment by NickM-27** [comment]
In the frigate webui

**Comment by mrmarria** [comment]
cannot access that

**Comment by NickM-27** [comment]
Where do you have frigate itself installed?

**Comment by NickM-27** [comment]
Please read the top of this page https://docs.frigate.video/frigate/installation

**Comment by mrmarria** [comment]
/home/config/www/community/frigate-hass-card

**Comment by mrmarria** [comment]
first tried install through HACs  failed to connect
then tried adding as container - many errors
deleted container - went back to HACS integration
not sure what is happening

which method better success ??

**Comment by NickM-27** [comment]
The integration does not install frigate, it connects an existing frigate install to home assistant

**Comment by mrmarria** [comment]
OK, I know I could get logs from the docker frigate container, I will rip everything out and re-install as containers HA, MQTT , and Frigate and try again.

**Comment by mrmarria** [comment]
OK that done. Frigate set up as container - keeps restarting  - can't find config.yml
I tried copying frigate.yaml to config.yml based on This statement :
Configuration File

For Home Assistant Addon installations, the config file needs to be in the root of your Home Assistant config directory (same location as configuration.yaml). It can be named frigate.yml or frigate.yaml, but if both files exist frigate.yaml will be preferred and frigate.yml will be ignored.

For all other installation types, the config file should be mapped to /config/config.yml inside the container.

If I cannot enter the running container, because it keeps restarting the last part of that statement sounds like catch 22
[Last frigate.log](https://github.com/blakeblackshear/frigate/files/13907066/Last.frigate.log)

**Comment by NickM-27** [comment]
What is your docker config? You don't create the config inside the container you create it and mount it into the container.

**Comment by mrmarria** [comment]
docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --shm-size=64m \
  -v /home/config/storage/media/frigate:/media/frigate \
  -v /home/config/frigate:/config.yml \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='xxxxxxxx' \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  ghcr.io/blakeblackshear/frigate:stable

**Comment by NickM-27** [comment]
`-v /home/config/frigate:/config.yml` this is an incorrect mount, the folder should be mounted to /config/

**Comment by NickM-27** [comment]
you did not need to move the file, you needed to fix the docker run command, if your docker run command did not change then it is still wrong

**Comment by mrmarria** [comment]
You say -v /home/config/frigate:/config.yml this is an incorrect mount, the folder should be mounted to /config/
it should be -v /home/config:/config.yml ?

What am I missing here?

**Comment by NickM-27** [comment]
you are trying to mount a folder at the location `/home/config` to a **folder** called `/config.yml` 

you instead want to map the folder `/home/config` to a folder called `/config` as in `-v /home/config:/config`

**Comment by mrmarria** [comment]
this is straight off the https://docs.frigate.video/frigate/installation/
perhaps there is a typo error?

If you can't use docker compose, you can run the container with something similar to this:

docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  --shm-size=64m \
  -v /path/to/your/storage:/media/frigate \
  -v /path/to/your/config.yml:/config/config.yml \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='password' \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  ghcr.io/blakeblackshear/frigate:stable

**Comment by NickM-27** [comment]
this is what is in the installation docs

```
-v /path/to/your/config.yml:/config/config.yml
```

this is what you were using

```
-v /home/config/frigate:/config.yml
```

this is not the same, you should never change the right side of a volume mount

**Comment by mrmarria** [comment]
Weelll now I am more confused:

I changed the line to
  -v /home/config:/config \
and that error of not finding config.yml disappeared 

full run command :

docker run -d \
  --name frigate \
  --restart=unless-stopped \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --shm-size=64m \
  -v /home/config/storage/media/frigate:/media/frigate \
  -v /home/config:/config \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD='PASSWORD' \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  ghcr.io/blakeblackshear/frigate:stable

Logs show progress but I am still confused about the run line -v /home/config:/config \   seems right original was
[Newer Frigate.log](https://github.com/blakeblackshear/frigate/files/13922290/Newer.Frigate.log)
 -v /home/config:/config.yml \

**Comment by NickM-27** [comment]
```
-v /home/config:/config
```

this is taking the contents of /home/config and putting them in to /config in the frigate container which is exactly where frigate expects them

```
-v /home/config:/config.yml
```

this takes the contents of /home/config and puts them in to /config.yml folder which is wrong

**Comment by mrmarria** [comment]
so the website docs
this is straight off the https://docs.frigate.video/frigate/installation/
needs to be corrected, right?

**Comment by NickM-27** [comment]
no, the current docs are correct, the docs for 0.13 (the next version) already show this new method. It is simpler to tell new users to use the new method so it doesn't need to be changed after updating https://deploy-preview-6262--frigate-docs.netlify.app/frigate/installation#docker

**Comment by mrmarria** [comment]
the new docs don't have the .yml on the right side either
only the original
Are you saying originally there should be a directory called config.yml for the config.yml file to be placed into?

**Comment by NickM-27** [comment]
I think we need to restart because there is a clear misundersatnding here. 

In docker you map something from your host storage and that gets inserted into the container at the location specified.

what is on the left side of the `:` does not matter as long as it matches up with the correct location of your data. What is on the right side of the `:` should never change from what the docs tell you to do

the new docs tell you to map from /path/to/your/config and then have docker place all of the contents of that folder into /config in the container. The previous docs only had you map the config file but that is now wrong because more files are saved in that folder

**Comment by mrmarria** [comment]
OK. Thank you for the clarification.
Looking at the logs I need only to find out why it's not connecting to MQTT, I think...

2024-01-12 10:45:58.082063969  [INFO] Starting Frigate...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-01-12 10:45:58.098270786  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2024-01-12 10:45:58.468646690  [INFO] Starting go2rtc...
2024-01-12 10:45:58.590390935  10:45:58.590 INF go2rtc version 1.2.0 linux/amd64
2024-01-12 10:45:58.591200138  10:45:58.591 INF [api] listen addr=:1984
2024-01-12 10:45:58.591871294  10:45:58.591 INF [rtsp] listen addr=:8554
2024-01-12 10:45:58.592743142  10:45:58.592 INF [srtp] listen addr=:8443
2024-01-12 10:45:58.593616658  10:45:58.593 INF [webrtc] listen addr=:8555
2024-01-12 10:45:59.345847394  [2024-01-12 10:45:59] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2024-01-12 10:45:59.364493438  [2024-01-12 10:45:59] peewee_migrate                 INFO    : Starting migrations
2024-01-12 10:45:59.391876494  [2024-01-12 10:45:59] peewee_migrate                 INFO    : There is nothing to migrate
2024-01-12 10:45:59.428978857  [2024-01-12 10:45:59] frigate.app                    INFO    : Output process started: 180
2024-01-12 10:45:59.445423139  [2024-01-12 10:45:59] detector.cpu                   INFO    : Starting detection process: 179
2024-01-12 10:45:59.445440484  [2024-01-12 10:45:59] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-01-12 10:45:59.457351660  [2024-01-12 10:45:59] frigate.app                    INFO    : Camera processor started for office_cam: 184
2024-01-12 10:45:59.474390207  [2024-01-12 10:45:59] frigate.app                    INFO    : Capture process started for office_cam: 186
2024-01-12 10:46:01.311790468  [2024-01-12 10:46:01] frigate.comms.mqtt             ERROR   : Unable to publish to office_cam/all: client is not connected
2024-01-12 10:46:08.077794303  [INFO] Starting go2rtc healthcheck service...

**Comment by NickM-27** [comment]
frigate does not run in host mode, 127.0.0.1 can not be used

**Comment by mrmarria** [comment]
should frigate:5000 be accessible as web page?

**Comment by NickM-27** [comment]
yes assuming it has started

**Comment by mrmarria** [comment]
so yes it is! Thank you for your guidance
Shows camera image.
Pretty sure not communicating with MQTT - running a  eclipse-mosquitto container that the HA container connects with only on 127.0.0.1
Any problem known with that version, that I should change to another?

**Comment by NickM-27** [comment]
That should be configurable but if it's not then I'd just use mosquitto. You can also use the MQTT container hostname as the host in frigate config.

**Comment by mrmarria** [comment]
I get no IP on 2 containers, is this a result of the run line?:
  --network=host \

 docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
/mqtt -
/frigate - 172.17.0.2
/homeassistant -

**Comment by NickM-27** [comment]
Yes, you'd just use the host up at that point, though there's no reason to run mqtt as host

**Comment by mrmarria** [comment]
Well I have been struggling to comprehend why  mqtt ( removed net=host ) which I can ping on the 172.17.0.3 it gets, refuses connections and has error that maybe isn't significant. I have read that the ipv6 maybe is to blame for address not available, but don't seem to be able to stop that with suggested:
socket_domain ipv4

I don't know if this is the wrong forum for mqtt help, but frigate wants it so.....

1705358407: mosquitto version 2.0.18 starting
1705358407: Config loaded from /mosquitto/config/mosquitto.conf.
1705358407: Starting in local only mode. Connections will only be possible from clients running on this machine.
1705358407: Create a configuration file which defines a listener to allow remote access.
1705358407: For more details see https://mosquitto.org/documentation/authentication-methods/
1705358407: Opening ipv4 listen socket on port 1883.
1705358407: Opening ipv6 listen socket on port 1883.
1705358407: Error: Address not available
1705358407: mosquitto version 2.0.18 running

the mosquitto.conf has this
persistence true
persistence_location /home/config/storage/mosquitto/data/

user mosquitto

# Listen on all interfaces
socket_domain ipv4
listener 1883 0.0.0.0


# Allow connection without authentication
allow_anonymous true

log_dest file /home/config/storage/mosquitto/log/mosquitto.log
log_dest stdout

# create a password file
password_file /home/config/storage/mosquitto/credentials

**Comment by NickM-27** [comment]
if the frigate connection can get through then that will show in the mqtt logs, I would just set the host in frigate as device_ip:1883

**Comment by mrmarria** [comment]
Well, as all containers can ping each other by name, seems likely that since nobody can connect to mqtt - there in lay the issue
re-installed everything after making "my-net"
kind of stuck - any suggestions

[root@debian12VM 13:21:52 config]# docker network inspect --verbose 1d466fcece8fe7b546f8b36efab05bcae059a00b2fe90c6515be4f2c1ca93523
[
    {
        "Name": "my-net",
        "Id": "1d466fcece8fe7b546f8b36efab05bcae059a00b2fe90c6515be4f2c1ca93523",
        "Created": "2024-01-19T12:32:59.350780547-07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "4eb70cb8af5cda5cdd7d03b47b07dee40b968ae394d3f86cfad9469c4c9c2b0e": {
                "Name": "homeassistant",
                "EndpointID": "15f92c7ec756aaaaf9d4e4abeee192a42f580212d8307188a4900e41dccf3bca",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "db81c1f598c89f6fa34437e20fdd402ac56fe428d20faf95edc1f82410079f70": {
                "Name": "mqtt",
                "EndpointID": "e134e0b23d7a494bb97c17c3f475cfbb43687e6fff6e6e65e9f39263514b771c",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "eb22389817fd0d34bd748e42292d657edad02220354aec13b3188d720eb77377": {
                "Name": "frigate",
                "EndpointID": "0a7e7a81cf2a490dd9d143fd66afdca551bde7cf680a08be62933c59fe645de1",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
