### ISSUE TITLE
[Support]: API event snapshot does not honor bbox or crop 

### ISSUE THREAD

**Issue by donnievawter** [blakeblackshear/frigate#9292]
### Describe the problem you are having

msg.payload = "curl -s -u donvawter:xxxxx  https://frigate.vawter.com/api/events/" + msg.id + "/snapshot.jpg" + "?h=1000&bbox=1&crop=1&quality=100";

This is used immedieately after frigate/event message is received and is called only when type is "new" The id is the id in the "after" object. The event snapshot which is recorded in the frigate interface uses bbox and crop values from the configuration file but the image returned from the above call does not have a bounding box and is not cropped.

### Version

beta 13.7

### Frigate config file

```yaml
irrelevant frigate is running fine. It is only the api call that is an issue;
```

### Relevant log output

```shell
only logging errors so nothing
```

### FFprobe output from your camera

```shell
irrelevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

too many cameras to list. They are working fine.

**Comment by NickM-27** [comment]
You can't add query args to curl in this way. They should be added using `-d "parameter=value` and a `-G` so curl knows it's a get request

**Comment by donnievawter** [comment]
Doh!
Thank you very much
I have changed to your suggestion and it is working fine now.
You may close the ticket.
