### ISSUE TITLE
Add more metadata to the Event Clips to assist in Fine Tuning the configuration

### ISSUE THREAD

**Issue by Humancell** [blakeblackshear/frigate#9293]
**Describe what you are trying to accomplish and why in non technical terms**
When looking at my Events, I can see the object type and % confidence, but no additional details that will assist me with fine tuning.  I love the features in the Debug (although the font size of the numbers on the bounding box are FAR too small to read) to create the zones and masks, but this does not help with clips.

As I am growing my installation here is my problem:

1. I've got four cameras currently
2. I'm seeing lots of events, for example for a cat, that also show up as a bear and person.
3. I want to set, for example, the values of the min_area/max_area for various objects
4. There is no easy and convenient way that I have found that allow me to see the min_area/max_area for the detected object in an event clip so that I can set the values in my config.  For example, if I could see this for "person" I could begin to estimate a good min_area and max_area for person.  If I could see this for 'cat" then I could do the same.
5. Fine Tuning the object detection to clear up the false positives is obviously a constant topic, and any little improvements would really assist - even if I have to manually put these values into my config.

**Describe the solution you'd like**
I am hoping there might be a way to record some metadata about the detected objects when events are recorded.  Obviously in a clip the object size/bounding box could change numerous times, and so even having the min/max range for area across numerous frames would be incredibly helpful.  I could then take these values and tweak my config.  There might be other valuable information that I am not aware of, but anything that would allow me to more easily have values to work with.

I did find the doc about looping a clip frame to find these, but it is cumbersome.  Even if this could be more automated it would provide a huge amount of value.  https://docs.frigate.video/development/contributing/#setup

**Describe alternatives you've considered**
I did look at the docs above:  https://docs.frigate.video/development/contributing/#setup

**Additional context**
It's pretty straight forward, I'm trying to find ways to assist me in looking through my event clips, finding the ones that are "wrong" and then identifying the values that I might want to add to my config to filter out the false detections as much as possible.

**Comment by NickM-27** [comment]
this is already supported in 0.13 while viewing clips

**Comment by Humancell** [comment]
Thank you!  Sorry about that!  Where can I read or see the releases and issues being addressed in them?

**Comment by NickM-27** [comment]
https://github.com/blakeblackshear/frigate/releases
