### ISSUE TITLE
Selecting openvino or coral per camera as feature.

### ISSUE THREAD

**Issue by borgqueenx** [blakeblackshear/frigate#9298]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to select if a camera uses openvino or coral so that I can combine the load between both, and maximise the available detection FPS capability of the system. Or have frigate figure it out automatically.

**Describe the solution you'd like**
Supporting running openvino and coral at the same time.

**Describe alternatives you've considered**
Are there any?

**Additional context**
This would allow additional FPS on larger frigate systems where the single-tpu coral is getting heavy usage, if the system also has a integrated graphics card.

**Comment by NickM-27** [comment]
This is a difficult issue, different models often return different results and confidences which may be complicated for the user to know how to filter correctly.

**Comment by borgqueenx** [comment]
> This is a difficult issue, different models often return different results and confidences which may be complicated for the user to know how to filter correctly.

but that's per model? I am talking about using the same model. simply combining the coral and openvino for extra processing capacity.

**Comment by borgqueenx** [comment]
> The same model can't run on different hardware.

never? so even if frigate+ supports openvino in the future, then it can only run on either the coral or openvino?

**Comment by NickM-27** [comment]
you would need separate models (a .tflite for coral, and a .xml or .onnx for openvino) and it is possible that they would give identical results but given that openvino isn't supported by Frigate+ yet it so that is not known for sure. 

However, it would be complicated to build the feature in general given that in most cases there are not identical models available for multiple hardware platforms

**Comment by borgqueenx** [comment]
thanks, then this feature request is one for in the long future i suppose.
