### ISSUE TITLE
[HW Accel Support]:  Frigate streams breaks after ubuntu 22.04 update (Coral TPU PCIe driver fail) SOLVED

### ISSUE THREAD

**Issue by Leon-Sam** [blakeblackshear/frigate#9340]
### Describe the problem you are having

I previously had a fully functioning Frigate instance with GPU H264 decoding and Coral TPU (via pci-e) inference on an Ubuntu 22.04 Desktop machine. Everything is installed/configured via an Ansible playbook.

I updated/upgraded my apt packages and Frigate streams stopped working.  **After some digging I was able to solve the problem.** I'm not sure if this is the best place to document but I wanted to put this out in the world for others to find and use. 

**Root cause:**  Any Linux OS that use major kernel version 6.4+ will have failed TPU (pcie) gasket-dkmx package installs .

This snuck up on me, since Ubuntu Desktop 23.04.3 with HWE kernel will jump major Kernel versions 5-> 6 when running apt update/upgrade.

 "gasket-dkms" package is required for TPU driver installs as instructed  on the official TPU driver install page [LINK](https://coral.ai/docs/m2/get-started/#2-install-the-pcie-driver-and-edge-tpu-runtime)

**Options to fixing:**
Option 1. Install a Linux OS with a  kernel major version of 5 ie (Ubuntu Server 23.04 LTS) (I did this)
Option 2. Build "gasket-dkms" locally with the latest version in the Google Coral github repo [LINK](https://github.com/google/gasket-driver)
Option 3. Wait for Google to update the Coral TPU gasket apt repo to be updated with the latest mainline git changes

**References:**
[The exact commit on the TPU driver code base that fixes the issue.](https://github.com/google/gasket-driver/commit/8aca235839fb5ba4d5ef6cfbe783837667e381f1)
[Other people are having this issue too.](https://github.com/google-coral/edgetpu/issues/808#issuecomment-1886221260)

### Version

0.12.1-367d724

### Frigate config file

```yaml
n/a
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

n/a

**Comment by Mikescotland** [comment]
Same problem here. Reverted to CPU detection as TPU unusable. Reinstalling in my case seems to be too complicated and risky.
How to build the correct package for kernel 6.5?? (Option 2)
