### ISSUE TITLE
Download buttons on exports page

### ISSUE THREAD

**Issue by lloydsmart** [blakeblackshear/frigate#9352]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to download exported clips from a web browser, so I can easily share them without using SSH.

**Describe the solution you'd like**
Could we please add download buttons next to exports, like we have for events?

![image](https://github.com/blakeblackshear/frigate/assets/1096684/943e3beb-48f4-4c69-8079-4a9c20f0117b)

**Comment by mabed-fr** [comment]
A button would be nice, could it be included in the new UI of 0.14?

**Comment by mabed-fr** [comment]
> you can already download by pressing the blue text

This is not obvious ! A button would be better for the UX
