### ISSUE TITLE
Create "Submit to Frigate+" button on the debug camera view

### ISSUE THREAD

**Issue by rsteckler** [blakeblackshear/frigate#9363]
**Describe what you are trying to accomplish and why in non technical terms**
When creating a custom model, I want to submit a lot of true positives to Frigate+, but these are limited by what shows up in the events feed, which often have a different snapshot than the one I want to submit.  

**Describe the solution you'd like**
A button on the camera debug screen that allows me to submit the current frame to frigate+ (with or without annotations)

**Describe alternatives you've considered**
There is an upload button on Frigate+, so my current process is to right click the camera image, save as, then upload to frigate+.

**Comment by NickM-27** [comment]
I'm going to close this as a duplicate of https://github.com/blakeblackshear/frigate/issues/8038
