### ISSUE TITLE
[Camera Support / Bug report]: Mask and Zone Creator blanks out web page if config exists for a zone.

### ISSUE THREAD

**Issue by psilantropy** [blakeblackshear/frigate#9364]
### Describe the problem you are having

Hi,

I have a camera with some masks and zones created in the application;

```
    zones:
      path:
        coordinates:
        - 1280,720,1280,470,689,219,134,99,0,150,0,720
        objects:
        - person
        - dog
        - cat
        - rat
```

These were edited successfully, used, and viewed in the same version, probably a couple of weeks ago.

If I go to Cameras > Cam_Name > Debug > Show Options > Mask and Zone Creator

This causes an issue and presents a blank page as follows;

![image](https://github.com/blakeblackshear/frigate/assets/79955883/7423040a-5f41-4bbe-ba28-e6e0a79fbb2c)

If I remove the existing zone, the page loads fine. The only way out of the white screen is to F5. Clicking other pages results in the same blank screen, but the URL is changing on click, so F5 presents the page you intended to navigate to.

If I clear the zone from the config, then add a new zone via the application I am not presented with a blank screen, but the gui becomes unresponsive in the same manner during the saving of the zone. Various websocket errors and ERR CONNECTION REFUSED.

the zone however is saved into the config, but strange placement - and it doesn't show in the zone preview.

![image](https://github.com/blakeblackshear/frigate/assets/79955883/105d633c-3c55-49e4-9759-9ad3417710c2)

NOTE: I don't really care about this zone and i'll just delete it now. Just reporting a bug and offering assistance testing if interested in investigating the issue. I can replicate the issue no problem.

All my other cameras replicate this issue but are the same brand/series.

### Version

0.13.0-C35C7DA

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
MS Edge console log (also same issue in Chrome, don't have ff to test)

:5000/system:1 A soft navigation has been detected: http://ipaddress:5000/system
ipaddress/:1 A soft navigation has been detected: http://ipaddress:5000/
:5000/cameras/Laundry:1 A soft navigation has been detected: http://ipaddress:5000/cameras/Laundry
CameraMap-d1dc138e.js:16  Uncaught (in promise) TypeError: n.split is not a function
    at T (CameraMap-d1dc138e.js:16:874)
    at CameraMap-d1dc138e.js:1:426
    at Array.reduce (<anonymous>)
    at J.ve [as constructor] (CameraMap-d1dc138e.js:1:401)
    at J.Ra [as render] (index-37d6813a.js:1:9612)
    at ar (index-37d6813a.js:1:7096)
    at Uo (index-37d6813a.js:1:2601)
    at ar (index-37d6813a.js:1:7312)
    at jt (index-37d6813a.js:1:2216)
T @ CameraMap-d1dc138e.js:16
(anonymous) @ CameraMap-d1dc138e.js:1
ve @ CameraMap-d1dc138e.js:1
Ra @ index-37d6813a.js:1
ar @ index-37d6813a.js:1
Uo @ index-37d6813a.js:1
ar @ index-37d6813a.js:1
jt @ index-37d6813a.js:1
Promise.then (async)
Fn @ index-37d6813a.js:1
J.setState @ index-37d6813a.js:1
(anonymous) @ index-37d6813a.js:1
Promise.then (async)
(anonymous) @ index-37d6813a.js:1
loadComponent @ index-37d6813a.js:1
(anonymous) @ index-37d6813a.js:1
(anonymous) @ index-37d6813a.js:1
(anonymous) @ index-37d6813a.js:1
jo @ index-37d6813a.js:1
jt @ index-37d6813a.js:1
Promise.then (async)
Fn @ index-37d6813a.js:1
J.setState @ index-37d6813a.js:1
routeTo @ index-37d6813a.js:18
ya @ index-37d6813a.js:18
ma @ index-37d6813a.js:18
Ul @ index-37d6813a.js:18
ga @ index-37d6813a.js:18
Ir @ index-37d6813a.js:1
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua 5 series

### Any other information that may be helpful

My mqtt zone doesn't show any counts. This is either me removing/adding again today and clearing history or it never actually worked.

![image](https://github.com/blakeblackshear/frigate/assets/79955883/567e01fd-55ba-497e-8db4-34af6255882e)

**Comment by psilantropy** [comment]
Also, with ZONE and MOTION MASK checked in the debug screen and present in the config - the view never shows the zone. Only the motion mask.

**Comment by NickM-27** [comment]
What OS is this on and what version of chrome? We've not had any reports of this issue and I'm not able to reproduce

**Comment by psilantropy** [comment]
Hi Nick,

Edge: Version 120.0.2210.133 (Official build) (64-bit)
Windows 11.

I'll redeploy and see if it makes any difference unless you want any further data first?

**Comment by psilantropy** [comment]
Maybe fixed it. After editing with the gui, it inputs the above formatting into the config file, which breaks it for me.
I think fix the formatting (remove blank above, create blank below - just for my benefit) and the issue doesn't occur again.

If I add another one, it breaks again;

![image](https://github.com/blakeblackshear/frigate/assets/79955883/d14cd5c5-d4a4-4b35-9dec-c09af7a7b7b2)

**Comment by psilantropy** [comment]
Still happens on latest ver.
