### ISSUE TITLE
[Feature] Exports: Choice of timelapse acceleration factor and calculation of output video duration

### ISSUE THREAD

**Issue by mabed-fr** [blakeblackshear/frigate#9375]
Hi, 

Would it be possible to implement the functionality allowing you to choose your acceleration factor at the time of export and display to the user the duration of the output video according to its acceleration factor?

**Comment by NickM-27** [comment]
can you explain your use case as to why you would want to choose different rates of time lapses at different times?

**Comment by Plawasan** [comment]
Gets a +1 from me, it would be great if you're e.g. exporting a timelapse covering the whole day then you typically want a higher factor than if you're just exporting the last hour, I now play the exported timelapses at a speed of >1x (sometimes 8x) so being able to define that already at the time of export would be a plus.

**Comment by mabed-fr** [comment]
> pouvez-vous expliquer votre cas d'utilisation et pourquoi vous voudriez choisir différents taux de time lapse à différents moments ?

I would like to be able to adjust the speed to be able to quickly view a full day or more at a high speed so as not to spend too much time. Today 1 hour of timelapse is worth 2m20 of vision age, a factor of 25-30x to view a day it will still take around 48 minutes. I added the estimation functionality because it allows users to estimate the neighborhood duration of their sequence.

**Comment by Plawasan** [comment]
Honestly, the last one I ran was just a timelapse of the snow coming down over the course of the day, nothing to do with security :)
