### ISSUE TITLE
Compatibility with mini PCIe or M.2 Coral Modules?

### ISSUE THREAD

**Issue by nphil** [blakeblackshear/frigate#94]
Just wondering if Frigate works with [these](https://www.mouser.com/ProductDetail/Coral/G650-04528-01?qs=sGAEpiMZZMu3sxpa5v1qrr6044Dk0q4qkDM1TzdftPE%3D)  modules? Thinking of just ripping out the wifi module in my home automation box and swapping.

**Comment by blakeblackshear** [comment]
I haven't tested it, but I would expect it to work out of the box. If it doesn't, I will work with you to make whatever changes are needed.

**Comment by nphil** [comment]
Ordering one now, it's half the cost of the USB version. I'll let you know how it goes!

**Comment by nphil** [comment]
I got the module installed in my old WiFi card slot. Unsure of how to proceed from here. I'm using HassOS, so everything is a docker container. Could we chat on discord?

**Comment by blakeblackshear** [comment]
Do you have Ssh access to hassos? I don't run hassos, so I am not very familiar with it.

**Comment by blakeblackshear** [comment]
I haven't tested it, but it might be worth trying the addon described here: https://community.home-assistant.io/t/local-realtime-person-detection-for-rtsp-cameras/103107/814?u=blakeblackshear

**Comment by nphil** [comment]
Yes, I'm in a shell inside hassos. Doing an lspci gives:

03:00.0 Class 0000: 1ac1:089a

whch is the correct device id for the m.2 module. I'm not sure if the underlying kernel version has driver support for this.

**Comment by blakeblackshear** [comment]
If you can use the docker cli from your shell directly, I will look up a command to run and test the coral.

**Comment by nphil** [comment]
Yup, I'm able to do a docker cli directly, please let me know!

**Comment by nphil** [comment]
As per the docs [here](https://coral.ai/docs/m2/get-started/), it looks like I will need to install a driver. No clue how to do this on HassOS since it's a pretty stripped down OS with no package manager.

**Comment by blakeblackshear** [comment]
Try running this directly in HassOS:
```
docker run -it --privileged --rm blakeblackshear/frigate:0.4.0-beta python3 -u benchmark.py
```
The frigate container comes with all the drivers included.

**Comment by nphil** [comment]
Running that docker command on a debian VM. 

`RuntimeError: No Edge TPU device detected!`

**Comment by blakeblackshear** [comment]
Realized that the PCIe driver is different. See if you can get the example working in the tutorial from the link you posted. If you can get that to work, I'm sure frigate will too.

**Comment by nphil** [comment]
Hmm. Getting this to work is proving to be quite tricky. I followed the instructions, but I keep getting this in my dmesg:

`    6.967401] gasket: loading out-of-tree module taints kernel.
[    6.967483] gasket: module verification failed: signature and/or required key missing - tainting kernel
[    7.025909] apex 0000:0b:00.0: Page table init timed out
[    7.025938] apex 0000:0b:00.0: MSI-X table init timed out
[    7.026645] apex: probe of 0000:0b:00.0 failed with error -110`

**Comment by nphil** [comment]
Well good news and bad news. It works! Bad news - can't get it to work in a VM and passthrough no matter what I do. Tried in ESXi and Proxmox, just won't initialize. I'm working with Google's tech support to get this fixed, but a fix is unlikely.

I ended up switching to a normal debian install and set up hassio manually. Followed the instructions as per the instructions and everything is fine. Did a benchmark:

`Average inference time: 8.356423947811127`

Now to figure out how to setup frigate!

**Comment by Tuckie** [comment]
@nphil could you update this if you ever hear back? I would love to go with a M.2 + vm passthrough setup if possible.

**Comment by nphil** [comment]
@Tuckie 

Sorry, yes I heard back from a google Engineer who works on the project. Apparently, the issues is this line in my dmesg:

`[    1.215014] pci 0000:00:15.5: BAR 13: no space for [io  size 0x1000]  [    1.215017] pci 0000:00:15.5: BAR 13: failed to assign [io  size 0x1000]  `

which is causing the module to be unable to access host memory. It could be a hardware issue on my end, since I'm using a NUC-like mini PC. The engineer did mention that he's seen the issue with some other VM setups, so YMMV.

**Comment by Tuckie** [comment]
Thank you @nphil for the details. I'm probably going to give it a shot. My current docker stack is running on Proxmox via an LXC container so we'll see how that goes.

**Comment by JeremyBrownNZ** [comment]
@nphil, Did you ever get any further information from google? experiencing the same issue now with my ESXi passthrough setup.

**Comment by nphil** [comment]
Unfortunately, I haven’t. You could try reaching out to Google coral
support again, maybe they have a working solution by now.

**Comment by alex-savin** [comment]
I got the same Coral TPU m.2 card, will try to test it out or find a solution how to run it with that card support
