### ISSUE TITLE
[Config Support]: Configuring Frigate to store on network share

### ISSUE THREAD

**Issue by deathgr1n** [blakeblackshear/frigate#9427]
### Describe the problem you are having

Hello all,

I have read the docs but can't quite seem to figure out how to setup my docker compose yml file. I want to configure frigate to store all the recordings and clips on my samba network share. I am running into the "database locked" issue. I have tried to configure the yml file correctly where the database is on local ubuntu server 22 and media is all on network storage. Not sure if I am just misunderstanding or not. 

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: false
#Top portion of config.yml. This isn't where I am having issues as I have another frigate docker running fine with this config. Only difference is my system has an intel i5-9500t which should have qsv as far as I understand, hence the "preset-intel-qsv-h265" portion.
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h265
```

### Relevant log output

```shell
user@host:/opt/frigate$ sudo docker-compose -f frigate.yml up
[+] Running 1/1
 ✔ Container frigate  Created                                                                                                                    0.1s
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | 2024-01-24 04:10:15.642828266  [INFO] Preparing go2rtc config...
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-01-24 04:10:15.655886475  [INFO] Starting Frigate...
frigate  | 2024-01-24 04:10:15.668651948  [INFO] Starting NGINX...
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2024-01-24 04:10:15.829149525  [INFO] Starting go2rtc...
frigate  | 2024-01-24 04:10:15.904524187  04:10:15.904 INF go2rtc version 1.2.0 linux/amd64
frigate  | 2024-01-24 04:10:15.905061972  04:10:15.904 INF [api] listen addr=:1984
frigate  | 2024-01-24 04:10:15.905366208  04:10:15.905 INF [rtsp] listen addr=:8554
frigate  | 2024-01-24 04:10:15.905573994  04:10:15.905 INF [srtp] listen addr=:8443
frigate  | 2024-01-24 04:10:15.905849840  04:10:15.905 INF [webrtc] listen addr=:8555
frigate  | 2024-01-24 04:10:16.650954368  [2024-01-24 04:10:16] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
frigate  | 2024-01-24 04:10:16.706682990  [Errno 18] Invalid cross-device link: '/media/frigate/clips/frigate.db' -> '/media/frigate/frigate.db'
frigate  | 2024-01-24 04:10:17.776650807  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2024-01-24 04:10:17.786963276  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2024-01-24 04:10:17.863197646  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2024-01-24 04:10:17.866278507  exit OK
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2024-01-24 04:10:17.870625964  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

This is my frigate.yml docker-compose file. I have a ".env" file in the same directory and frigate/docker is able to successfully mount to the samba share. My issue is with the frigate database portion. Any help is very appreciated!:

user@host:/opt/frigate$ cat frigate.yml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "700mb"
    devices:
      - /dev/bus/usb/002/004:/dev/bus/usb/002/004 #passing through the specific port coral ai is plugged into
      #- /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128 #not sure if this needs to be changed regarding that I have an intel i5-9500t
    volumes:
      - /opt/frigate/config/config.yml:/config/config.yml:ro
      - samba-volume:/media/frigate/clips
      - samba-volume:/media/frigate/recordings
      - /opt/frigate/database:/media/frigate/frigate.db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

volumes:
  samba-volume:
    driver_opts:
      type: "cifs"
      o: "username=${SAMBA_USER},password=${SAMBA_PASS},vers=3.0"
      device: "//192.168.1.200/nvr"

**Comment by NickM-27** [comment]
you should define your docker volume as 

```
- /opt/frigate/database:/db/frigate.db
```

and then add

```
database:
  path: /db/frigate.db
```

to the frigate config

**Comment by deathgr1n** [comment]
@NickM-27 I tried what you recommended and I receive this error when trying to bring the docker container up now:

user@host:/opt/frigate$ sudo docker-compose -f frigate.yml up
validating /opt/frigate/frigate.yml: services.frigate Additional property database is not allowed

Here is my frigate.yml file:

user@host:/opt/frigate$ cat frigate.yml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "700mb"
    devices:
      - /dev/bus/usb/002/004:/dev/bus/usb/002/004 #passing through the specific port coral ai is plugged into
      #- /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /opt/frigate/config/config.yml:/config/config.yml:ro
      - samba-volume:/media/frigate/clips
      - samba-volume:/media/frigate/recordings
      - /opt/frigate/database:/db/frigate.db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    database:
      path: /db/frigate.db
    ports:
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

volumes:
  samba-volume:
    driver_opts:
      type: "cifs"
      o: "username=${SAMBA_USER},password=${SAMBA_PASS},vers=3.0"
      device: "//192.168.1.200/nvr"

**Comment by NickM-27** [comment]
```
database:
  path: /db/frigate.db
```

this is supposed to go in your frigate config, not docker compose

**Comment by deathgr1n** [comment]
@NickM-27 yep you definitely made that clear in the first post, my mistake! I updated each file accordingly and am now receiving this error: [Errno 18] Invalid cross-device link: '/media/frigate/clips/frigate.db' -> '/db/frigate.db'

I changed this portion of my docker compose:
    volumes:
      - /opt/frigate/config/config.yml:/config/config.yml:ro
      - samba-volume:/media/frigate
      #- samba-volume:/media/frigate/clips
      #- samba-volume:/media/frigate/recordings
      - /opt/frigate/database:/db/frigate.db

But now am seeing this line in the logs:
2024-01-24 18:38:36.200378634  unable to open database file

Here is my frigate config file (top portion):
mqtt:
  enabled: false

database:
  path: /db/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  #hwaccel_args: preset-vaapi
  hwaccel_args: preset-intel-qsv-h265

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous
  #width: 2592
  #height: 1944
  #quality: 15

**Comment by NickM-27** [comment]
what do you see at /opt/frigate/database (was that folder created before? it needed to be)

**Comment by deathgr1n** [comment]
Here is an ls, doesn't seem anything was created. The database directory is there though:
user@host:/opt/frigate$ ls -la database/
total 8
drwxr-xr-x 2 root root 4096 Jan 24 03:39 .
drwxr-xr-x 4 root root 4096 Jan 24 18:37 ..

**Comment by NickM-27** [comment]
oh that's my fault, the docker compose should be `- /opt/frigate/database:/db/`

**Comment by deathgr1n** [comment]
@NickM-27 That worked! thank you for all your help!
