### ISSUE TITLE
[Camera Support]: Reolink Doorbell - Camera Specific Configuration - 0.13 RC1

### ISSUE THREAD

**Issue by andregoncalvespires** [blakeblackshear/frigate#9431]
### Describe the problem you are having

Using the configuration suggested below for Reolink Video Doorbell, the detection flow does not start, returning the ffmpeg initialization error.

> go2rtc:
>    streams:
>      your_reolink_doorbell:
>        - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password#video=copy#audio=copy#audio=opus"
>        - rtsp://reolink_ip/Preview_01_sub
>      your_reolink_doorbell_sub:
>        - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=password"

The main stream and secondary stream could only be started after changing the secondary stream port to 80. The main stream also accepts port 80.

### Version

0.13

### Frigate config file

```yaml
just a suggestion to correct the documentation
```

### Relevant log output

```shell
just a suggestion to correct the documentation
```

### FFprobe output from your camera

```shell
just a suggestion to correct the documentation
```

### Frigate stats

```json
just a suggestion to correct the documentation
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink Video Doorbell

**Comment by NickM-27** [comment]
PRs are the way to suggest changes to documentation. Also, many users have confirmed the existing docs are working so this is likely to be an issue on your side
