### ISSUE TITLE
[Config Support]: How to mount a custom model

### ISSUE THREAD

**Issue by krustophenia** [blakeblackshear/frigate#9437]
### Describe the problem you are having

I want to mount a custom tensorflow model to see if there's any improvement and potentially to use frigate+ to get a reliable one.

### Version

0.12.1-367d724

### Frigate config file

```yaml
not needed
```

### Relevant log output

```shell
none
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
https://docs.frigate.video/configuration/advanced#model

**Comment by NickM-27** [comment]
You can include it in /config and mount the entire config directory like the docs for 0.13 show https://deploy-preview-6262--frigate-docs.netlify.app/frigate/installation#docker

**Comment by krustophenia** [comment]
I see a way to mount it unless you are using the home assistant addon, is this correct?
