### ISSUE TITLE
[HW Accel Support]: HWaccel  errors intel i7-11390H iRIS graphics

### ISSUE THREAD

**Issue by lorenzopiazzi** [blakeblackshear/frigate#9453]
### Describe the problem you are having

I don't manage to make hwaccel work: Frigate opens but ffmpeg errors occur. 
Without the following everything works but I'd like to use HW acceleration.
ffmpeg:
  hwaccel_args: preset-vaapi

### Version

Frigate (0.12.1-367d724)

### Frigate config file

```yaml
database:
  path: /db/frigate.db

mqtt:
  host: 192.168.1.***
  user: *****
  password: ****

ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  cpu_minipc:
    type: cpu
    num_threads: 8

cameras:
  reolink_soggiorno:
    ffmpeg:
      inputs:
        - path: rtsp://admin:*******@192.168.1.***:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:*******@192.168.1.***:554/h264Preview_01_main
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect:
      enabled: True        
      width: 1920
      height: 1072
      fps: 5
      max_disappeared: 25
    snapshots:
      enabled: True
      bounding_box: True
      timestamp: True
      retain:
        default: 15
    objects:
      track:
        - person
    motion:
    record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
      enabled: True
    # Optional: Number of minutes to wait between cleanup runs (default: shown below)
    # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
    # expire_interval: 60
    # Optional: Retention settings for recording
      retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
        days: 5
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
        mode: all #motion
    # Optional: Event recording settings
      events:
      # Optional: Maximum length of time to retain video during long events. (default: shown below)
      # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
      #       will be the last x seconds of the event unless retain->days under record is > 0.
#        max_seconds: 600
      # Optional: Number of seconds before the event to include (default: shown below)
        pre_capture: 10
      # Optional: Number of seconds after the event to include (default: shown below)
        post_capture: 5
      # Optional: Objects to save recordings for. (default: all tracked objects)
        objects:
          - person
      # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
      # required_zones: []
      # Optional: Retention settings for recordings of events
        retain:
        # Required: Default retention days (default: shown below)
          default: 10
        # Optional: Mode for retention. (default: shown below)
        #   all - save all recording segments for events regardless of activity
        #   motion - save all recordings segments for events with any detected motion
        #   active_objects - save all recording segments for event with active/moving objects
        #
        # NOTE: If the retain mode for the camera is more restrictive than the mode configured
        #       here, the segments will already be gone by the time this mode is applied.
        #       For example, if the camera retain mode is "motion", the segments without motion are
        #       never stored, so setting the mode to "all" here won't bring them back.
          mode: motion
        # Optional: Per object retention days
          objects:
            person: 15
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "180mb" # update for your cameras based on calculation above
    group_add:
      - "105"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /mnt/c/Docker/DockerDesktop/Frigate/config/config.yml:/config/config.yml
      - /mnt/d/frigate_storage/media/frigate:/media/frigate
      - /mnt/c/Docker/DockerDesktop/Frigate/config:/db
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5002:5000"
      - "1935:1935" # RTMP feeds
    environment:
      - LIBVA_DRIVER_NAME=iHD
```

### Relevant log output

```shell
Frigate log:
2024-01-26 17:43:20.152775171  [2024-01-26 17:43:20] frigate.video                  ERROR   : camera_ingresso: Unable to read frames from ffmpeg process.
2024-01-26 17:43:21.636382690  [2024-01-26 17:43:21] frigate.util                   ERROR   : Unable to poll intel GPU stats: No device filter specified and no discrete/integrated i915 devices found
2024-01-26 17:43:21.636385762  
2024-01-26 17:43:22.296352151  [2024-01-26 17:43:22] frigate.video                  ERROR   : reolink_soggiorno: Unable to read frames from ffmpeg process.
2024-01-26 17:43:22.296960356  [2024-01-26 17:43:22] frigate.video                  ERROR   : reolink_soggiorno: ffmpeg process is not running. exiting capture thread...
2024-01-26 17:43:37.897332793  [2024-01-26 17:43:37] watchdog.reolink_soggiorno     ERROR   : Ffmpeg process crashed unexpectedly for reolink_soggiorno.
2024-01-26 17:43:37.897444582  [2024-01-26 17:43:37] watchdog.reolink_soggiorno     ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-01-26 17:43:37.897528353  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
2024-01-26 17:43:37.897615617  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : Assuming 131072kB available aperture size.
2024-01-26 17:43:37.897689232  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : May lead to reduced performance or incorrect rendering.
2024-01-26 17:43:37.897753864  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : get chip id failed: -1 [22]
2024-01-26 17:43:37.897832361  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : param: 4, val: 0
2024-01-26 17:43:37.897905276  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : [AVHWDeviceContext @ 0x5639cf3eee00] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
2024-01-26 17:43:37.897968262  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : [AVHWDeviceContext @ 0x5639cf3eee00] Failed to initialise VAAPI connection: 18 (invalid parameter).
2024-01-26 17:43:37.898031924  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : Device creation failed: -5.
2024-01-26 17:43:37.898098883  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : [h264 @ 0x5639cf2d0340] No device available for decoder: device type vaapi needed for codec h264.
2024-01-26 17:43:37.898171945  [2024-01-26 17:43:37] ffmpeg.reolink_soggiorno.detect ERROR   : Device setup failed for decoder on input stream #0:0 : Input/output error

vainfo OUTPUT:
lorenzo@minipc:/usr/lib/x86_64-linux-gnu/dri$ vainfo
libva info: VA-API version 1.17.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
vaInitialize failed with error code 3 (invalid VADisplay),exit


lspci -v OUTPUT:
lorenzo@minipc:/usr/lib/x86_64-linux-gnu/dri$ lspci -v
7a57:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio 1.0 console (rev 01)
        Subsystem: Red Hat, Inc. Virtio 1.0 console
        Physical Slot: 214041273
        Flags: bus master, fast devsel, latency 64
        Memory at 9ffe00000 (64-bit, non-prefetchable) [size=4K]
        Memory at 9ffe01000 (64-bit, non-prefetchable) [size=4K]
        Memory at 9ffe02000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci
lspci: Unable to load libkmod resources: error -2

833a:00:00.0 3D controller: Microsoft Corporation Basic Render Driver
        Physical Slot: 600782237
        Flags: bus master, fast devsel, latency 0
        Capabilities: <access denied>
        Kernel driver in use: dxgkrnl

f5e4:00:00.0 System peripheral: Red Hat, Inc. Virtio file system (rev 01)
        Subsystem: Red Hat, Inc. Virtio file system
        Physical Slot: 1929952088
        Flags: bus master, fast devsel, latency 64
        Memory at e00000000 (64-bit, non-prefetchable) [size=4K]
        Memory at e00001000 (64-bit, non-prefetchable) [size=4K]
        Memory at c00000000 (64-bit, non-prefetchable) [size=8G]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci
```

### FFprobe output from your camera

```shell
not sure where I should run this command
```

### Operating system

Debian

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink RLC810A

**Comment by NickM-27** [comment]
looks like the driver on the host is not installed

**Comment by lorenzopiazzi** [comment]
thanks for your quick answer @NickM-27 , I thought I had all the needed driverse because of what I could read in this folder:

lorenzo@minipc:/usr/lib/x86_64-linux-gnu/dri$ ls
crocus_dri.so  i965_drv_video.so  kms_swrast_dri.so  r600_dri.so      virtio_gpu_dri.so
d3d12_dri.so   iHD_drv_video.so   nouveau_dri.so     radeonsi_dri.so  vmwgfx_dri.so
i915_dri.so    iris_dri.so        r300_dri.so        swrast_dri.so    zink_dri.so

Isn't it a issue related to my kernel driver in use? No idea if that's normal, I just noticed that it's different from i915 posted by askpet in the issue #5720 
Here is my lspci -v output:
833a:00:00.0 3D controller: Microsoft Corporation Basic Render Driver
        Physical Slot: 600782237
        Flags: bus master, fast devsel, latency 0
        Capabilities: <access denied>
        Kernel driver in use: dxgkrnl

If it's just a matter of missing drivers, may you suggest how to correctly install them? I am still a beginner at linux...

**Comment by NickM-27** [comment]
your vainfo shows

```
libva info: VA-API version 1.17.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
vaInitialize failed with error code 3 (invalid VADisplay),exit
```

which indicates that the drivers are not installed. If things were working correctly then you'd expect to see an output vaguely similar to 

```
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.10.0)
vainfo: Driver version: Mesa Gallium driver 22.3.6 for AMD Radeon Graphics (renoir, LLVM 15.0.6, DRM 3.49, 6.1.64-Unraid)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

if you are running debian then it should just be `apt-get update && apt-get install intel-media-va-driver`

**Comment by lorenzopiazzi** [comment]
Thanks you very much!
This is strange, I've run the drivers installation and it confirms that intel-media-va-driver is already there... but then again same output from vainfo:

root@minipc:/usr/lib/x86_64-linux-gnu/dri# apt-get update && apt-get install intel-media-va-driver
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
intel-media-va-driver is already the newest version (23.1.1+dfsg1-1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

root@minipc:/usr/lib/x86_64-linux-gnu/dri# vainfo
libva info: VA-API version 1.17.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
vaInitialize failed with error code 3 (invalid VADisplay),exit

I'm sorry to bother you, but I really appreciate your support!

**Comment by NickM-27** [comment]
trying installing `libva-drm2 intel-media-va-driver-non-free`

**Comment by lorenzopiazzi** [comment]
I took some time to make some checks but it keeps not working...
I still get the same situation from "vainfo" even after installing and reinstalling the packages you suggested above.
I don't understand: drivers are there but it seems wsl2 can't see them.

libva info: VA-API version 1.17.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
vaInitialize failed with error code 3 (invalid VADisplay),exit

This is happening in Debian WSL, but I tried also with Ubuntu in WSL and same issues. Also with Ubuntu in VM same problem... Is it possible it's my hardware wrong? I've a Geekom IT11 minipc

**Comment by lorenzopiazzi** [comment]
When the Ubuntu VM is booting this error appear:
<img width="469" alt="image" src="https://github.com/blakeblackshear/frigate/assets/76661289/32fbfbe7-26fe-4fbf-871c-3291398acd9a">

**Comment by stibbzy** [comment]
> I took some time to make some checks but it keeps not working... I still get the same situation from "vainfo" even after installing and reinstalling the packages you suggested above. I don't understand: drivers are there but it seems wsl2 can't see them.
> 
> libva info: VA-API version 1.17.0 libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null) vaInitialize failed with error code 3 (invalid VADisplay),exit
> 
> This is happening in Debian WSL, but I tried also with Ubuntu in WSL and same issues. Also with Ubuntu in VM same problem... Is it possible it's my hardware wrong? I've a Geekom IT11 minipc

@lorenzopiazzi Did you ever get this sorted? I have exactly the same issue even after installing the drivers suggested above.

**Comment by lorenzopiazzi** [comment]
Hi @stibbzy ,
Well I switched from WSL to the real Linux ecosystem (I installed Ubuntu instead of Windows) and everything went smoothly...
Also, before that, I had tried to install a Google Coral in WSL and I had problems again... My idea Is that WSL is at the moment not so able to share graphic drivers with Windows in the way we need, but I'm not expert at all so I don't exclude that it was just me not enough good at this kind of staff.
Anyway, in Linux everything works fine and for the few things I still need Windows I use it virtualized with Virtualbox inside Linux.
Let me know if you manage to solve this issue in Windows!
Lorenzo

**Comment by stibbzy** [comment]
@lorenzopiazzi Thanks for getting back to me! Ahh well, I’ll have to keep trying or live without acceleration. Unfortunately I need to keep this as a Windows box :(

**Comment by exmatador** [comment]
> @lorenzopiazzi Thanks for getting back to me! Ahh well, I’ll have to keep trying or live without acceleration. Unfortunately I need to keep this as a Windows box :(

Hi,
had the same problems with hardware acceleration in my geekom it12 pc.
I'm using windows11 with wsl/Ubuntu 22.04.
With this docker-compose all works fine, you can see the GPU-usage (iris-xe) in ArcControl.


Version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.15.0-beta1
    shm_size: "512mb" # update for your cameras based on calculation above
    cap_add:
      - CAP_PERFMON    
    
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral
      - /dev/dxgkrnl:/dev/dxgkrnl
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    
    volumes:
      - ./config:/config
      - \\wsl$$\Ubuntu-22.04\usr\lib\wsl:/usr/lib/wsl
      - \\wsl$$\Ubuntu-22.04\etc\localtime:/etc/localtime:ro
      - \\wsl$$\Ubuntu-22.04\home\exmatador\frigate\config.yml:/config/config.yml  # Copyy config.yml (Linux-Verz) ins Docker-Verzeichnis /config/
      - \\wsl$$\Ubuntu-22.04\home\exmatador\frigate\clips:/media/frigate           # Mapping Linux-Verzeichnis zu Docker-Verzeichnis
    
    ports:
      - "5000:5000"
      - "8554:8554/tcp" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    
    environment:
      LIBVA_DRIVER_NAME: d3d12
      LIBVA_DRIVERS_PATH: /usr/lib/x86_64-linux-gnu/dri
      LD_LIBRARY_PATH: /usr/lib/wsl/lib
`

One problem still left: The use of "intel_gpu_top" doesn't work - but this doesn't matter.
ExMatador
