### ISSUE TITLE
obfuscate sensitive values in the web interface's Config page

### ISSUE THREAD

**Issue by smarthusker** [blakeblackshear/frigate#9470]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to obfuscate sensitive string values the web interfaces configuration page so these values are protected and security is improved

**Describe the solution you'd like**
Add configuration options to the config.yaml to hide specific values, such as RTSP credentials MQTT credentials, that are shown in the web interface on the Config Page.  I am aware of the ability to pass in environment variables into config.yaml, but once these variables are evaluated, the web interfaces Config page displays those values.  The Config page should not display these values.

**Describe alternatives you've considered**
Other possibilities include with expected level of effort:
- removing the Config page entirely (small)
- supporting some limited role-based access control mechanism (very large)

**Additional context**
None.

**Comment by NickM-27** [comment]
> I am aware of the ability to pass in environment variables into config.yaml, but once these variables are evaluated, the web interfaces Config page displays those values. The Config page should not display these values.

That is incorrect, they show just the same and this is way it id recommended to do this 

![image](https://github.com/blakeblackshear/frigate/assets/14866235/aae10872-5e0d-401f-a018-27b9ba3e6c2d)
