### ISSUE TITLE
[Support]: Could there be/is there an official user group on Facebook/Discord?

### ISSUE THREAD

**Issue by apbarratt** [blakeblackshear/frigate#9478]
Not every question or idea I have about Frigate feels like it is worthy of opening a Github issue for.  Could a link be provided within the repo's readme and on the official website to a Discord Server and/or Facebook User Group for quick DM/ad-hoc discussions that don't feel well placed on Github issues? :)

**Comment by blakeblackshear** [comment]
The #cameras channel on the Home Assistant discord has many frigate users. There is also an unofficial frigate_nvr subreddit.

We don't really have the resources to moderate another support channel right now.

**Comment by NickM-27** [comment]
Keep in mind there are also GitHub discussions which are a good place for questions, ideas, show & tell, etc

**Comment by PrplHaz4** [comment]
> Keep in mind there are also GitHub discussions which are a good place for questions, ideas, show & tell, etc

and it's much more likely to be searchable (and less user-hostile) for a longer period of time than the others
