### ISSUE TITLE
[Support]: Frigate Addon not starting after update to release 0.13.0

### ISSUE THREAD

**Issue by msalessandro69** [blakeblackshear/frigate#9527]
### Describe the problem you are having

when I try to start the addon on home assistant with version 0.13.0 I get thrown the error message that `Can't create container from addon_ccab4aaf_frigate: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate: Bad Request ("invalid CapAdd: unknown capability: "CAP_PERFMON"")`

### Version

0.13.0

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
Can't create container from addon_ccab4aaf_frigate: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate: Bad Request ("invalid CapAdd: unknown capability: "CAP_PERFMON"")
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
It seems like you may be running an old version of docker / HA supervised?

**Comment by NickM-27** [comment]
@felipecrs any ideas here? I don't think other users have seen issues with this

**Comment by NickM-27** [comment]
and actually, I don't think this changed with 0.13 either

**Comment by felipecrs** [comment]
Oh. This is odd. But yes, it's new from 0.13.

Supposing this is a supervised installation, make sure your docker is up to date. At least v24.

**Comment by msalessandro69** [comment]
Docker is on v24.0.7 already

**Comment by NickM-27** [comment]
ah I see, it was reduced from admin https://github.com/blakeblackshear/frigate-hass-addons/commit/3323e7b3c696202787be7ef7b218dec362240207

**Comment by felipecrs** [comment]
This may be an issue with a too old kernel as well.

**Comment by msalessandro69** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/65624023/e3b284b3-29a0-4749-b103-9ac50c9594d1)
this is the kernel version I am running, for now I downgraded from 0.13.0 to 0.12.1

**Comment by msalessandro69** [comment]
are there any logs that you guys think would help for me to retrieve? @NickM-27 @felipecrs

**Comment by msalessandro69** [comment]
I will update the Kernel and come back if it worked, a system reboot has already been done, obrigado Felipe.

**Comment by JamesDilan** [comment]
Good day,

**Comment by felipecrs** [comment]
Update docker to the latest version, and update the kernel to the latest version. AFAIK latest kernel for Ubuntu 20.04 is 5.15 through HWE.

**Comment by JamesDilan** [comment]
Many thanks for pointing in right direction. Update Kernel to 5.15. Confirm it's working.

**Comment by msalessandro69** [comment]
hey @mack0352 I m not able to update my kernel, i am thinking abount doing a backup of my HA instance, doing a fresh debian install on the latest version, I am not a linux guy by trade so I am not sure if there is an easier way to update the kernel I am all ears

**Comment by felipecrs** [comment]
According to the requirements, Debian 11 is not supported for Home Assistant Supervised installations anyway: https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions

**Comment by mack0352** [comment]
I believe that. I installed Debian 11 in early 2022, and never really have kept it up to date or looked at new versions. I only have a few things running on this server, so I may also just do a fresh install on Debian 12 with a HA Backup. For now, nothing is broken on my end (still running Frigate 12.1).

**Comment by felipecrs** [comment]
From the Supervised documentation, it says:

> This method is considered advanced and should only be used if one is an expert in managing a Linux operating system, Docker and networking.

So, if you don't feel comfortable with it, I don't understand why using it at all. I personally use HAOS.

**Comment by msalessandro69** [comment]
@mack0352 I updated from Debian 11 to 12, now I have kernel version 6.1, and frigate 0.13.1 is working correctly

@felipecrs I actually am using debian because I have other services running alongside home assistant, such as a printer server, transmission, Arr suite, etc

**Comment by cpankonien** [comment]
I'm having the same issue on hassos install, frigate installed as add-on. frigate will not start. restored from backup to 12.1, works fine. None of the issues identified in this bug report seem to apply to my install.

**Comment by felipecrs** [comment]
What is your docker and kernel version?

**Comment by cpankonien** [comment]
yes, using haos.
 Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Comment by cpankonien** [comment]
none, it just hangs

**Comment by felipecrs** [comment]
No logs?

**Comment by cpankonien** [comment]
i'll try the upgrade again so the logs should be easier to follow

**Comment by felipecrs** [comment]
Here are my versions btw, which works:

Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

Very same as yours.

And if you don't find out that your logs contain `unknown capability: "CAP_PERFMON"`, please open a separate issue.

**Comment by Kwiatjk** [comment]
I have that same problem 
Core 2024.1.6
Supervisor 2023.12.1
Interfejs użytkownika 20240104.0

**Comment by Neneow** [comment]
Hello,

Same issue.

Core : 2024.2.0b7
Supervisor : 2024.01.1

Trying upgrade Debian 11 to 12, but always same error : 

"ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/ccab4aaf_frigate-fa/start - Can't create container from addon_ccab4aaf_frigate-fa: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate-fa: Bad Request ("invalid CapAdd: unknown capability: "CAP_PERFMON"")#033[0m"

Regards

**Comment by felipecrs** [comment]
Upgrade docker to the latest version and the Linux kernel to 5.15. That's the solution for this problem.

**Comment by Neneow** [comment]
Thanks @felipecrs .

I had previously mark hold containerd.io / docker-ce / docker-ce-cli package for compatibility. Just upgrade theses packages et now error is not present.

Now error in conf, but is other problem.

Thanks you

**Comment by FunkyKwak** [comment]
Hi,

I have the same issue since a few weeks : 
> Can't create container from addon_ccab4aaf_frigate: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_ccab4aaf_frigate: Bad Request ("invalid CapAdd: unknown capability: "CAP_PERFMON"")

I don't know how I could update the mentionned packages. My home assistant instance is runing on docker installed on a synology NAS, and the "Container Manager" Synology package is already up to date.

Thanks in advance for your help !

Regards,
Yann

**Comment by felipecrs** [comment]
You need to upgrade your operating system or your kernel as well.

**Comment by felipecrs** [comment]
You need to upgrade your operating system or your kernel as well.

**Comment by FunkyKwak** [comment]
I am runing on a Synology NAS, everything is up to date : operating system (DSM) and installed packages.
Frigate is the only addon I have having this issue.

**Comment by felipecrs** [comment]
What is the Linux version you have?

**Comment by felipecrs** [comment]
https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions

PS: Supervised is not supported on DSM.

**Comment by FunkyKwak** [comment]
The operating system is DSM (Disk Station Manager v7.2.1-69057) from Synology. It's Linux based, but that's all I know.

Docker is running via a Synology package [Container Manager](https://www.synology.com/fr-fr/releaseNote/ContainerManager), and the last update is from september 2023. Maybe the CAP_PERFMON is not there yet, I see [here](https://docs.frigate.video/configuration/hardware_acceleration/) that it's only with the latest versions.

Is there a way to start the addon without the CAP_PERFMON ?

**Comment by felipecrs** [comment]
As your system is not supported by supervisor, I would advise you to use docker compose to spin up Frigate. And then, if you want the Frigate panel in Hass you can use the Frigate proxy add-on.

**Comment by FunkyKwak** [comment]
I don't need the Frigate panel, I only use the card in order to have two-way audio and use it as an intercom.
So I add frigate to my docker compose with hassio-supervisor, and it will start the addon with home-assistant ?

**Comment by felipecrs** [comment]
Follow the installation guide: https://docs.frigate.video/frigate/installation/

**Comment by FunkyKwak** [comment]
Thank you, I will try that. But that would be nice to be able to start it like any other addon in home assistant, and like before the 0.13 version

**Comment by felipecrs** [comment]
Sorry friend, but in my opinion, you were not even supposed to be running home assistant supervised in your system.

They make it clear that only Debian 12 is supported. This enables add-ons developers to know what feature set they can use or not.

You can of course still run supervised on your system, just be aware that you'll be on your own. That's what "unsupported" means in this context.

I am not a maintainer of Frigate, so @NickM-27 and @blakeblackshear may have a different opinion.

**Comment by NickM-27** [comment]
The reason this occurs is because the system privilege level for the addon was dropped from admin to just performance. This is an improvement in security and reduces risk for the user so this is an objective improvement. 

Users are always encouraged to run supported systems

**Comment by FunkyKwak** [comment]
Ok thanks for your explanations (but I will keep using home assistant supervised 😄, hopefully DSM will get supported one day)

**Comment by felipecrs** [comment]
That's very unlikely, but yeah maybe someday DSM will upgrade the Linux kernel and Docker to a version that supports CAP_PERFMON.

**Comment by Kwiatjk** [comment]
Not will be .....
I change to normal version outside DSM

**Comment by hoombar** [comment]
> That's very unlikely, but yeah maybe someday DSM will upgrade the Linux kernel and Docker to a version that supports CAP_PERFMON.

I've read that Synology stick with the same kernel version for the life of the product 😞 

Found this thread because I'm in the same boat, where my DS224+ is running 4.4.302+ LTS kernel.

Frigate is running fine, and I've got it partly wired in to home assistant with the proxy addon, but I can't actually do anything with automations, because the addon won't load to provide the devices and entities.

**Comment by hoombar** [comment]
> But the add-on doesn't provide any device or entities. The integration that does it.

I realised that shortly after I posted the message 🤦  - thanks for clarifying so quickly though!

**Comment by felipecrs** [comment]
My 2-cents:

Assuming you can change your OS, I suggest you do it.

It is not anyhow beneficial to keep using an outdated Linux version, even from a user perspective.

It is already hard enough to keep Frigate compatible with old hardware, let alone old software.

For hardware, one can still use the e-waste point. The same doesn't generally apply to software, as you can change it.
