### ISSUE TITLE
Missing `http(s)://[hostname]:5000/live/webrtc/stream.html?src=[camera]&mode=[mode]` support in upgrade

### ISSUE THREAD

**Issue by neutralvibes** [blakeblackshear/frigate#9533]
### Describe the problem you are having

I used the go2rtc stream proxy via the url `http://[hostname]:5000/live/webrtc/stream.html?src=[camera]&mode=[mode]` to get access to the camera feeds for other purposes. Before I upgrading, this was working nicely. I've looked through the release notes and documentation, but can't find anything to say this facility has either been removed or describe the alternative. I apologise in advance if I missed something. 

### Version

0.13.0-01E2D20

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
n/a
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
I will update the breaking changes on the release notes, this was a breaking change. 

Due to security issues this was removed by default. You will need to map port 1984 and access go2rtc directly

**Comment by neutralvibes** [comment]
Thanks for info.

**Comment by neutralvibes** [comment]
Happy
