### ISSUE TITLE
Docker Compose Fails

### ISSUE THREAD

**Issue by mitchross** [blakeblackshear/frigate#956]
Dev Container on .9 branch fails for local dev

[2021-04-01T00:14:44.716Z] [PID 912] 
#3 [internal] load metadata for docker.io/library/frigate:latest
#3       digest: sha256:498af7afd08c730a91039bf361ab56c7db79a3e19399c48b4770fbaafb5dfb19
#3         name: "[internal] load metadata for docker.io/library/frigate:latest"
#3      started: 2021-04-01 00:14:44.6435797 +0000 UTC
[2021-04-01T00:14:45.434Z] [PID 912] failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repositor
y does not exist or may require authorization: server message: insufficient_scope: authorization failed
#3    completed: 2021-04-01 00:14:45.4432003 +0000 UTC
#3     duration: 799.6206ms
#3        error: "pull access denied, repository does not exist or may require authorization: server messag
e: insufficient_scope: authorization failed"

[2021-04-01T00:14:45.470Z] [PID 912] ERROR: Service 'dev' failed to build
[2021-04-01T00:14:45.533Z] [PID 912] [4894 ms] Command failed: docker-compose --project-name frigate -f c:\Users\vanillax\Documents\Programming\frigate\docker-compose.yml up -d --build

**Comment by blakeblackshear** [comment]
Did you build the container with the makefile described in step 1 of the contributing docs?

**Comment by mitchross** [comment]
> Did you build the container with the makefile described in step 1 of the contributing docs?

I see now that the .9 branch has updated docs, not on the official doc site

Also, for windows, users will need to do https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows

Trying this.....

**Comment by mitchross** [comment]
@blakeblackshear 

ok got to step 5 and seeing this error

![image](https://user-images.githubusercontent.com/6330506/113230884-f97df380-9267-11eb-9c12-fbb90a7737d2.png)

**Comment by blakeblackshear** [comment]
You probably have an error when running the make command. That is the step which creates the version. Most likely a windows specific issue.

**Comment by mitchross** [comment]
@blakeblackshear 
 
 I see the issue. When the make generates the version
 ie "echo "VERSION='0.9.0-$(COMMIT_HASH)'" > frigate/version.py"
 
 It creates this file on windows
![image](https://user-images.githubusercontent.com/6330506/113234909-351cbb80-9270-11eb-9378-e05ae95eeb72.png)

Switching to the following will fix the version error 
![image](https://user-images.githubusercontent.com/6330506/113235099-8036ce80-9270-11eb-83b9-960b911a84d7.png)

**Comment by mitchross** [comment]
@blakeblackshear 

Switched to my mac and reran everything as the doc states. Seeing issues connecting to mqtt and issues with API in docker.

1. did the make
2. opened vscode as a container
3. tried going to localhost:5000
4. tried re-running "python3 -m frigate"


<img width="917" alt="Screen Shot 2021-04-01 at 11 26 55 AM" src="https://user-images.githubusercontent.com/6330506/113317369-5071e000-92dd-11eb-9aa3-45abcb4148cc.png">
<img width="1435" alt="Screen Shot 2021-04-01 at 11 25 58 AM" src="https://user-images.githubusercontent.com/6330506/113317397-5667c100-92dd-11eb-95d6-b38f734314e5.png">
<img width="734" alt="Screen Shot 2021-04-01 at 10 44 40 AM" src="https://user-images.githubusercontent.com/6330506/113317433-5cf63880-92dd-11eb-832e-0ebab1f83878.png">

**Comment by HITChris** [comment]
You will need to point the config to an actual mqtt host

**Comment by mitchross** [comment]
> You will need to point the config to an actual mqtt host

mqtt is a hostname part of the docker compose scrip. if you goto the frigate docker container and ping mqtt it resolves.

**Comment by HITChris** [comment]
True, but for one reason or another I ended up having to paste my full 'prod' mqtt config in. Given your connection refused response, did you check your mqtt server's logs? maybe e.g., for an auth issue, given no credentials supplied (if req'd.)

**Comment by mitchross** [comment]
> True, but for one reason or another I ended up having to paste my full 'prod' mqtt config in. Given your connection refused response, did you check your mqtt server's logs? maybe e.g., for an auth issue, given no credentials supplied (if req'd.)

Are you using the development container? or the actual release container? I have no issues with the release container, strictly the dev container. 

I'll try your suggestion regardless and see what happens.

**Comment by mitchross** [comment]
@blakeblackshear 

what is the reason for this commented out line?

  dockerfile: docker/Dockerfile.amd64
      # dockerfile: docker/Dockerfile.core.dev

**Comment by mitchross** [comment]
@HITChris are you able to debug the python code running in the vs code container? If so how?

**Comment by mitchross** [comment]
solved
