### ISSUE TITLE
[Feature] Customize how cameras are stacked in Birdseye 

### ISSUE THREAD

**Issue by tliaresq** [blakeblackshear/frigate#9569]
Hello!

I have 4 RTSP streams that are 5120x960 and the way Birdseye is stacking the streams is not really user friendly since the streams are so wide and short. I think a great feature would be to allow customization for how the cameras are displayed on the Birdseye page. I think this could also be extended to scenarios where you have cameras with different resolutions/shape.

Image for reference:
![Untitled drawing (1)](https://github.com/blakeblackshear/frigate/assets/14988689/0fc2c2e8-3818-4077-a7cb-ffe3619dc84d)

**Comment by NickM-27** [comment]
labeling this as a duplicate of https://github.com/blakeblackshear/frigate/issues/5424

**Comment by NickM-27** [comment]
feel free to add these details to that issue.
