### ISSUE TITLE
[Support]: Some events start with empty current_zone, but the object is in a defineded zoe

### ISSUE THREAD

**Issue by FischLu** [blakeblackshear/frigate#9572]
### Describe the problem you are having

I updated to 0.13 yesterday and found a problem, because I automate some operations with MQTT messages, so when I read the logs of my MQTT program I found some new events start with empty current_zones, so I checked it with Frigate Webpage and found the related events and I can see that this person is detected but does not have the yellow dot at the bottom center, so is that why she is considered current_zones empty? 

_The following image is obtained by clicking on the event start button in the frigate webpage_
<img width="115" alt="image" src="https://github.com/blakeblackshear/frigate/assets/10261662/66878135-4ed9-405e-9334-be373b7b8b5c">
<img width="134" alt="image" src="https://github.com/blakeblackshear/frigate/assets/10261662/a0cd44d5-b57f-4cf4-8fb8-f4015a7e554a">

But after just two seconds she stands up and barely moves, the yellow dot appears and she is also considered to exist inside a zone (let's say x_road) I defined. 

_The following image is obtained by clicking on the button next to the start button in the frigate webpage_
<img width="122" alt="image" src="https://github.com/blakeblackshear/frigate/assets/10261662/62889963-1316-44eb-89e4-dbf1dc050069">

![image](https://github.com/blakeblackshear/frigate/assets/10261662/5ebdae87-d9db-4350-aa15-f09e9b9fa664)

The x_road zone is very large and the person's position is almost the middle of the zone, so it can't be an edge case, and I've set the inertia parameter of the zone to 1.
This happens about a 10 times a day (typically I have 200 events per day), is this a bug?

### Version

0.13

### Frigate config file

```yaml
zones:  
   x_road:
     coordinates: <some number>
     inertia: 1
```

### Relevant log output

```shell
no
```

### FFprobe output from your camera

```shell
no
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Reolink E1 zoom

**Comment by FischLu** [comment]
> This is not a bug, an object can not be in a zone until it is detected as a true positive

Doesn't the red border mean that the target has been detected? Or does it mean something else? But I checked the relevant MQTT logs, and the first message of this event already has the label=Person, which means that the frigate should have recognized the object at the time point.

**Comment by NickM-27** [comment]
> which means that the frigate should have recognized the object at the time point.

frigate detecting the object and the object being a true positive are different things. You can read more about that at https://docs.frigate.video/configuration/object_filters#object-scores

**Comment by FischLu** [comment]
> > which means that the frigate should have recognized the object at the time point.
> 
> frigate detecting the object and the object being a true positive are different things. You can read more about that at https://docs.frigate.video/configuration/object_filters#object-scores

Thanks, I see the difference, however, in MQTT docs there is sentence `The first message is published when the tracked object is no longer marked as a false_positive`, does `no longer marked as a false_positive` = true positive? or there are some states in between?

To sum up, is there a way to avoid MQTT message which has empty current_zones like my case, because it's not easy to distinguish whether the object is in a none zone area or it is not a true positive like you said. Maybe I have to create a "background zone" which covers the whole camera view as a workaround solution, then a empty current_zones means not a 
true positive case. Any better solution?

**Comment by NickM-27** [comment]
> because it's not easy to distinguish whether the object is in a none zone area or it is not a true positive like you said

not sure I understand. if you are using this for notifications then I would just suggest using a condition that before.entered_zones is empty and after.entered_zones is not emtpy

**Comment by FischLu** [comment]
> > because it's not easy to distinguish whether the object is in a none zone area or it is not a true positive like you said
> 
> not sure I understand. if you are using this for notifications then I would just suggest using a condition that before.entered_zones is empty and after.entered_zones is not emtpy

This is also a good solution, thanks!

**Comment by FischLu** [comment]
> > because it's not easy to distinguish whether the object is in a none zone area or it is not a true positive like you said
> 
> not sure I understand. if you are using this for notifications then I would just suggest using a condition that before.entered_zones is empty and after.entered_zones is not emtpy

Hi again, I've been working on this problem for two more days and I still can't understand how the very first error came about.

In the last two days, I added a zone called background, which covers all the area that the camera can see, meaning that the `current_zones` of any true positive object contains at least the background zone. Then the only possibility that `current_zones` is empty is that the object is not true positive yet, like you mentioned.

It turns out that I haven't observed a single case where `current_zones` is empty in these two days, but it happens more than 10 times before, and I think that the MQTT message should not be sent when an object is not true positive, as mentioned in the document:

`The first message is published when the tracked object is no longer marked as a false_positive`

so I don't get it!
