### ISSUE TITLE
M2 Coral with HassOS running in VM

### ISSUE THREAD

**Issue by B0ndo2** [blakeblackshear/frigate#9579]
### Describe the problem you are having

I have HA running in VM (KVM) with Frigate. I want to buy this [Coral](https://www.mouser.ca/ProductDetail/Coral/G650-04527-01?qs=sGAEpiMZZMu3sxpa5v1qrr6044Dk0q4qv2ZNGiPqW1g%3D) which is M2 PCIe to use for detection.
My question is this going to work (exposing the PCIe device from the host OS to the VM and inside Frigate container ?

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
Not relevant
```

### docker-compose file or Docker CLI command

```yaml
Not relevant
```

### Relevant log output

```shell
Not relevant
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Network connection

Wired

### Camera make and model

NA

**Comment by NickM-27** [comment]
it will be difficult to setup, you'll most likely need to do a PCIe passthrough to the VM and then the coral driver *should* pick it up

**Comment by B0ndo2** [comment]
The PCIe passthrough should be ok, am more worried about the container having access to it.
Have you tested it before ?
