### ISSUE TITLE
Is it possible to encode with nvidia?

### ISSUE THREAD

**Issue by tkffaul** [blakeblackshear/frigate#9580]
I know there are presets and i know some of the options in the output args, but is there an easy way to setup for using nvidia for both decode and encode? My record stream uses about 35% of 4 cores on encode, I'm just wondering if that could be offloaded? If it can can we get a preset to do it? I could probably figure out some custom args but i also don't need to break this trying to figure it out.

**Comment by NickM-27** [comment]
encoding using hardware is already possible, but to be clear by default frigate does not do any transcoding for recordings. It is possible you are misunderstanding what is using the CPU or you have manually configured a transcode of the stream

**Comment by tkffaul** [comment]
On the record stream using "preset-record-generic-audio-copy" if i view the System Page and look at GPU's I'm using 16% decode 0% encode but I'm using 35% CPU under the record panel. So it looks like I'm getting nvidia decode but I appear to be trans coding the record stream. Am I miss reading this?

**Comment by NickM-27** [comment]
> Am I miss reading this?

you are mis reading it, the decoding is being done for motion and object detection, not for recording

> but I'm using 35% CPU under the record panel

where do you see the record panel?

**Comment by NickM-27** [comment]
that CPU usage has nothing to do with the recording of the camera stream itself (ffmpeg), that has to do with the management of recordings like moving them from the cache to the file system.

Typically CPU usage on that process is very low unless `sync_recordings` is enabled which is generally not recommended except in specific cases. Can you show your config

**Comment by tkffaul** [comment]
I just checked this isn't on in my config... I see that its now bouncing... it dropped to roughly 10% and bounces up to 35% if this is expected behavior I'll just close this. Thank you for your time!
