### ISSUE TITLE
[Support]: Birdseye video left aligned

### ISSUE THREAD

**Issue by gkwok1** [blakeblackshear/frigate#9585]
### Describe the problem you are having

Video in Birdeyes is left aligned when there is only 1 or 4 video. It used to be center aligned in 0.12

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
None
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Various

**Comment by NickM-27** [comment]
0.12 used a grid, it wasn't align on the center. Can you provide an example of an issue you are seeing? otherwise not sure there is anything to be done here

**Comment by gkwok1** [comment]
My video is a 640 x 480 feed

![image](https://github.com/blakeblackshear/frigate/assets/51801924/20681985-6355-4a49-8707-383edf51df6a)

**Comment by NickM-27** [comment]
I see, if all of your camera streams are 4:3 then it would be best to change birdseye to be 4:3

**Comment by gkwok1** [comment]
I have some 4:3 and some 16:9 cameras.

**Comment by Newspaperman57** [comment]
Hi, i believe my issue is related to this.
I have cameras in both 4:3, 16:9 and 9:16, so i have some very different ratios :sweat_smile: 

After 0.13 some cameras are overlapped in the birdseye-view, they used to be "squished" into the aspect-ratio of the birdseye view, which was of course not ideal, but at least somewhat usable :) This image is from a right-click -> "copy image", so not a screenshot:
![image](https://github.com/blakeblackshear/frigate/assets/1321620/0cd7505c-bdf3-4329-b98a-5b1b80893124)

Note that i also have the same black padding on the right of the image as on gkwok1's example, but also a small bar on the left

My birdseye-config:
```
birdseye:
  enabled: True
  mode: continuous
```

Also, i think the overview looks a bit odd with all the padding, just to let you know :)
![image](https://github.com/blakeblackshear/frigate/assets/1321620/8da5bdaa-2dac-4c6d-a263-23efe65e252c)

**Comment by NickM-27** [comment]
this is an unrelated issue, portrait cameras are not handled correctly currently, it is a difficult issue

**Comment by felipecrs** [comment]
I don't know how to put my feedback in an issue, but:

![image](https://github.com/user-attachments/assets/5ad20fd2-0a54-4f5b-b55f-80272c9131ff)

1. It would indeed look better if center-aligned, both horizontally and vertically
2. It could use better the vertical space

**Comment by NickM-27** [comment]
this is handled for the single camera case in 0.14.1

multiple cameras will not be centered, that is working as expected. 

> It could use better the vertical space (the black strip at the bottom)

no it couldn't, because that would require scaling some cameras to be relatively larger than other cameras which breaks one of the birdseye rules
