### ISSUE TITLE
[Bug]: Mqtt binary sensors not changing.

### ISSUE THREAD

**Issue by borgqueenx** [blakeblackshear/frigate#9586]
### Describe the problem you are having

![Screenshot_20240201_230235_Home Assistant](https://github.com/blakeblackshear/frigate/assets/20416925/3916eeee-1cb4-408f-a329-e5fce4c06740)
![Screenshot_20240201_230145_Home Assistant](https://github.com/blakeblackshear/frigate/assets/20416925/446ccbfb-3584-43be-ada5-48e7989bef90)

See the above screenshots. Frigate shows a ongoing event of the car standing in the zone, but the binary sensor made by frigate is not reporting a car. It says nothing detected.
Restarting frigate solves this, but the issue will come back.

### Version

0.13.0

### Frigate config file

```yaml
Not related the logs i guess.
```

### Relevant log output

```shell
Dont see anything related to binary sensor, the zone or mqtt in logs.
```

### FFprobe output from your camera

```shell
Not important.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

.

### Any other information that may be helpful

Sometimes it seems my mossquitto broker or mqtt has more serious trouble and then frigate binary sensors and z2m entitys become unavailable. But during the above bug report the sensors are available. Restarting frigate fixes it, sensor of zones report the car then again. But the issue comes back.

**Comment by NickM-27** [comment]
please provide your config

**Comment by borgqueenx** [comment]
`database: path: /config/frigate.db mqtt: host: 192.168.1.184 user: MQTT password: tomaat66 topic_prefix: frigate # Optional: client id (default: shown below) # NOTE: must be unique if you are running multiple instances client_id: frigate #logger: # logs: # frigate.record.maintainer: debug detectors: coral: type: edgetpu device: usb model: path: plus://4eb978717be075de496b35bf02ff4a5b detect: max_disappeared: 80 objects: filters: person: min_score: 0.65 threshold: 0.82 dog: min_score: 0.65 threshold: 0.82 cat: min_score: 0.65 threshold: 0.82 car: min_score: 0.65 threshold: 0.9 birdseye: enabled: true mode: objects restream: true go2rtc: streams: kitchen-cam: - rtsp://n@192.168.1.216/live - ffmpeg:kitchen-cam#audio=aac backyard-tree: - rtsp://a@192.168.1.114:554/Streaming/Channels/101/ basement-cam: - rtsp://w@192.168.1.133/live - ffmpeg:basement-cam#audio=aac outdoor-arch: - rtsp://w@192.168.1.152/live - ffmpeg:outdoor-arch#audio=aac baby-box: - rtsp://t@192.168.1.185/stream1 - ffmpeg:baby-box#audio=aac naelis-place: - rtsp://t@192.168.1.166/stream1 - ffmpeg:naelis-place#audio=aac bedroom-top: - rtsp://t@192.168.1.172/stream1 - ffmpeg:bedroom-top#audio=aac house-corner-garden-view: - rtsp://ad@192.168.1.242:554/Streaming/Channels/101/ garage-door: - rtsp://a@192.168.1.218:554/Streaming/Channels/101/ poolpole-cam:@192.168.1.109:554/Streaming/Channels/101/ hallway-cam: - rtsp://a@192.168.1.170:554/cam/realmonitor?channel=1&subtype=0 living-room: - rtsp://ad@192.168.1.234:554/cam/realmonitor?channel=1&subtype=0 billiard-room: - rtsp://w@192.168.1.205/live - ffmpeg:billiard-room#audio=aac bedroom-floor: - rtsp://ta@192.168.1.102/stream1 - ffmpeg:bedroom-floor#audio=aac ffmpeg: hwaccel_args: preset-vaapi output_args: record: preset-record-generic-audio-aac cameras: kitchen-cam: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/kitchen-cam input_args: preset-rtsp-restream roles: - record - detect motion: threshold: 55 mask: - 1254,670,1250,720,1102,720,1106,674 - 534,62,586,60,629,394,586,427 - 620,225,972,210,964,90,608,106 - 339,413,493,297,472,174,297,234 - 1182,156,1178,236,1101,194,1098,134 zones: kitchen-excluding-doorway: coordinates: 1089,46,1185,720,261,720,131,71 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 basement-cam: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/basement-cam input_args: preset-rtsp-restream roles: - record - detect motion: threshold: 11 mask: - 465,49,473,188,327,262,293,68 - 1280,463,1280,720,1113,720 - 1000,335,1162,323,1153,228,1012,225 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 billiard-room: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/billiard-room input_args: preset-rtsp-restream roles: - record - detect motion: threshold: 122 mask: - 465,49,473,188,327,262,293,68 - 1280,463,1280,720,1113,720 - 1000,335,1162,323,1153,228,1012,225 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 hallway-cam: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/hallway-cam input_args: preset-rtsp-restream roles: - record - path: rtsp://a@192.168.1.170:554/cam/realmonitor?channel=1&subtype=1 roles: - detect - path: rtsp://192.168.1.184:8554/hallway-cam?audio input_args: preset-rtsp-restream roles: - audio motion: threshold: 35 mask: - 619,440,640,480,546,480,547,443 - 491,354,619,376,619,282,498,260 objects: track: - person - cat - dog detect: width: 640 height: 480 enabled: true audio: enabled: true listen: - bark - fire_alarm - scream - speech - yell record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 living-room: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/living-room input_args: preset-rtsp-restream roles: - record - path: rtsp://a@192.168.1.234:554/cam/realmonitor?channel=1&subtype=1 roles: - detect - path: rtsp://192.168.1.184:8554/living-room?audio input_args: preset-rtsp-restream roles: - audio motion: threshold: 65 mask: - 73,204,183,181,193,49,81,28 - 612,440,610,459,542,459,541,438 - 512,375,640,385,619,297,534,290 zones: living-room-entrances: coordinates: 566,42,570,190,463,243,471,43 objects: track: - person - cat - dog filters: cat: mask: - 65,211,190,200,196,35,70,26 dog: mask: - 65,211,190,200,196,35,70,26 person: mask: - 65,211,190,200,196,35,70,26 detect: width: 640 height: 480 enabled: true audio: enabled: true listen: - bark - fire_alarm - scream - speech - yell record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 poolpole-cam: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/poolpole-cam input_args: preset-rtsp-restream roles: - record - path: rtsp://a@192.168.1.109:554/Streaming/Channels/102/ roles: - detect motion: threshold: 42 mask: - 1280,655,1280,720,547,720,546,655 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 30 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 outdoor-arch: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/outdoor-arch input_args: preset-rtsp-restream roles: - record - detect motion: threshold: 55 mask: - 1249,672,1247,720,1111,720,1106,670 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 30 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 zones: bedroom: coordinates: 1142,145,1128,362,749,306,751,99 door: coordinates: 139,127,164,352,46,416,0,172 backyard-tree: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/backyard-tree input_args: preset-rtsp-restream roles: - record - path: rtsp://a@192.168.1.114:554/Streaming/Channels/102/ roles: - detect motion: threshold: 44 mask: - 879,720,957,343,823,338,601,720 - 968,684,1280,690,1280,657,980,657 - 1280,0,1280,221,1041,275,660,181,536,0 objects: track: - person - cat - dog - car detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 30 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion objects: car: 1 snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 garage-door: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/garage-door input_args: preset-rtsp-restream roles: - record - path: rtsp://a@192.168.1.218:554/Streaming/Channels/102/ roles: - detect motion: threshold: 54 mask: - 591,352,575,176,543,179,534,353 - 1200,492,1200,536,643,536,645,480 - 1200,536,1200,348,1143,292,916,536 - 640,238,606,36,542,41,540,270 - 658,536,452,536,527,371,676,383 - 581,352,575,176,543,179,534,353 zones: door_on_parkspot: coordinates: 567,536,293,536,368,330,561,311 door_in_garden: coordinates: 593,536,767,536,716,328,577,294 car_parking_spot: coordinates: 103,470,229,323,426,322,366,513 objects: track: - person - cat - dog - car detect: width: 1200 height: 536 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 30 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion objects: car: 1 snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 house-corner-garden-view: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/house-corner-garden-view input_args: preset-rtsp-restream roles: - record - path: rtsp://a@192.168.1.242:554/Streaming/Channels/102/ roles: - detect motion: threshold: 48 mask: - 1280,667,1280,720,725,720,728,664 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 30 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 baby-box: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/baby-box input_args: preset-rtsp-restream roles: - record - path: rtsp://t@192.168.1.185/stream2 roles: - detect motion: threshold: 120 mask: - 0,385,693,223,673,0,0,0 - 1244,677,1242,720,1107,720,1104,673 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 bedroom-top: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/bedroom-top input_args: preset-rtsp-restream roles: - record - path: rtsp://t@192.168.1.172/stream2 roles: - detect - path: rtsp://192.168.1.184:8554/bedroom-top?audio input_args: preset-rtsp-restream roles: - audio onvif: host: 192.168.1.172 port: 2020 user: motion: threshold: 80 mask: - 0,32,411,34,422,0,0,0 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true audio: enabled: true listen: - bark - fire_alarm - scream - speech - yell - whimper_dog - howl record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 naelis-place: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/naelis-place input_args: preset-rtsp-restream roles: - record - path: rtsp://te@192.168.1.166/stream2 roles: - detect - path: rtsp://192.168.1.184:8554/naelis-place?audio input_args: preset-rtsp-restream roles: - audio motion: threshold: 75 mask: - 415,0,423,32,227,30,226,0 objects: track: - person - cat - dog detect: width: 1280 height: 720 enabled: true audio: enabled: true listen: - bark - fire_alarm - scream - speech - yell - whimper_dog - howl record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60 bedroom-floor: ffmpeg: inputs: - path: rtsp://192.168.1.184:8554/bedroom-floor input_args: preset-rtsp-restream roles: - record - path: rtsp://s@192.168.1.102/stream2 roles: - detect - path: rtsp://192.168.1.184:8554/bedroom-floor?audio input_args: preset-rtsp-restream roles: - audio onvif: host: 192.168.1.102 port: 2020  motion: threshold: 112 mask: - 415,0,415,39,227,30,226,0 objects: track: - dog detect: width: 1280 height: 720 enabled: true audio: enabled: true listen: - bark - fire_alarm - scream - speech - yell - whimper_dog - howl record: enabled: true # Optional: Number of minutes to wait between cleanup runs (default: shown below) # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o expire_interval: 60 retain: days: 3 mode: all events: pre_capture: 5 post_capture: 10 retain: default: 60 mode: motion snapshots: enabled: true retain: # Required: Default retention days (default: shown below) default: 60`

**Comment by borgqueenx** [comment]
I dont know if above is properly visible, copied it on phone and pasted it here, trying to hide passwords.

**Comment by borgqueenx** [comment]
The binary sensor of the camera itself is showing car occupancy fine. The binary sensors of the zones by that camera are not showing occupancy.
In debug view, frigate also shows zone is in use.

**Comment by borgqueenx** [comment]
No, not just zones. Seem completely random.
Bedroom person occupancy binary sensor reports no person, yet frigate events page does....
I also drove away with the car and the binary sensor and frigate updated the binary sensor instantly....
Here again proof:
![image](https://github.com/blakeblackshear/frigate/assets/20416925/55551319-f799-4c4b-913a-2c5f44054b62)
![image](https://github.com/blakeblackshear/frigate/assets/20416925/180fe1c9-dc7c-45a5-ad00-b64ddbd39960)

**Comment by borgqueenx** [comment]
now, all binary sensors are no longer available, even after restarts of home assistant and the whole host pc.
I tried switching to a other broker (EMQX) with no luck. I am now fairly certain this has to do with frigate as my zigbee2mqtt network continues functioning as normal.
i think the zigbee2mqtt issue is where the co-ordinator also loses connection.

I also tried to play with mqtt config in the frigate config file. when i enter invalid data, it shows in frigate logs some mqtt errors. they do not show up with valid mqtt data. 

This bug makes all automations i made with frigate not working, i really hope this one can be fixed....

**Comment by NickM-27** [comment]
If the sensors are unavailable that's something else, means mqtt isn't working on the HA side

**Comment by borgqueenx** [comment]
the issue is solved, i indeed also had to re-configure the MQTT in home assistant itself, not just in the broker and frigate/z2m configuration.
Now using EMQX as a broker and issues seem solved, hopefully stays this way. maybe the issue was then with mosquitto....

Well if people find this thread and seem to have the same issues, first check home assistant mqtt itself, then try to use a other broker like EMQX instead of mosquitto.

**Comment by borgqueenx** [comment]
the issue came back. frigate detecting the car in the zone just fine, the entity created for it not showing presense of the car.
The only change made last days was updating home assistant. restarting frigate solved it.

Maybe it can be fixed by polling these mqtt entity's and updating them if they are false?
