### ISSUE TITLE
go2rtc dashboard stream info api - weird behaviour

### ISSUE THREAD

**Issue by Orion74C** [blakeblackshear/frigate#9594]
### Describe the problem you are having

I upgraded Frigate from 0.12.1 to 0.13 stable. Everything works just fine and my cameras are working as expected using **go2rtc**. However,  I'm experiencing an issue when I click **system > go2rtc 1.8.4 [streams info]**. The API <frigate_ip>:5000/api/go2rtc/streams used to show as it should in 0.12.1, but now all I see is text code, like the example below:

_{_"back_main":{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:37516","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6zoAoAPGQ==,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=15;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408; profile=1;\r\na=control:trackID=1\r\n","send":44025542,"senders":["96 H264, bytes=40656734, receivers=1","97 MPEG4-GENERIC/16000, bytes=3111480, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/back_main","user_agent":"FFmpeg Frigate/0.13.1-34fb1c2"}],"producers":[{"medias":["video, recvonly, H.264 High 5.1","audio, recvonly, MPEG4-GENERIC/16000"],"receivers":["96 H264, bytes=40656734, senders=1","97 MPEG4-GENERIC/16000, bytes=3111480, senders=1"],"recv":43968642,"remote_addr":"192.168.xxx.xxx:554","sdp":"v=0\r\no=- 1706367637355515 1 IN IP4 192.168.90.7\r\ns=Session streamed by \"preview\"\r\ni=h264Preview_01_main\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2013.04.08\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\na=x-qt-text-inf:h264Preview_01_main\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:500\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6zoAoAPGQ==,aO48sA==\r\na=control:trackID=1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:256\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=15;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408; profile=1;\r\na=control:trackID=2\r\n","type":"RTSP active producer","url":"rtsp://192.168.90.7/h264Preview_01_main/","user_agent":"go2rtc/1.8.4"}]},"back_sub":{"consumers":[{"medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC"],"remote_addr":"127.0.0.1:37490","sdp":"v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6zoCgPZ,aO48sA==\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=15;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408; profile=1;\r\na=control:trackID=1\r\n","send":8433938,"senders":["96 H264, bytes=5150018, receivers=1","97 MPEG4-GENERIC/16000, bytes=3114576, receivers=1"],"type":"RTSP passive consumer","url":"rtsp://127.0.0.1:8554/back_sub","user_agent":"FFmpeg Frigate/0.13.1-34fb1c2"}],"producers":[{"med__

... output truncated intentionally 

I'm sure I'm missing something silly.

Any help is really appreciated!

### Version

0.13

### Frigate config file

```yaml
...
```

### Relevant log output

```shell
...
```

### FFprobe output from your camera

```shell
...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

reolink/unifi

**Comment by NickM-27** [comment]
this was covered in the release notes, by default the go2rtc api is not available due to security issues. If you want to access the go2rtc dashboard and api directly then you need to map port 1984 and access it there

**Comment by Orion74C** [comment]
I guess the release notes are there for a reason. My bad. Appreciated!

**Comment by NickM-27** [comment]
feel free to create a new issue if something else comes up
