### ISSUE TITLE
[Support]: Storage after update 12 to 13 still full --> Old videos not availible 

### ISSUE THREAD

**Issue by eyeni** [blakeblackshear/frigate#9601]
### Describe the problem you are having

After updating with docker compose my old videos are gone and internal storage is still full. 
How can i browse my old video files and delte them? I tried to ssh into my frigate-machine but cant find any video-files... 

### Version

0.13

### Frigate config file

```yaml
Frigate in Docker Compose as a VM in Proxmox.
```

### Relevant log output

```shell
not relevant
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
not relevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

**Comment by NickM-27** [comment]
you've provided no info, there is no way to help. There is nothing in the 0.13 update that removes recordings. This would be caused by an incorrect configuration in docker most likely

**Comment by eyeni** [comment]
Well, i dont think this is something about docker. Can you tell me how to access the filesystem of frigate to browse the media files? New recordings are all good, just need to delete the old recordings...

**Comment by NickM-27** [comment]
frigate does not have a separate filesystem (that is the whole point of docker), it is just whatever you mounted the host storage to. and if you did not do it correctly then the recordings are kept in /docker/var/ which is a default docker behavior

**Comment by eyeni** [comment]
Ok, i really tried to understand this, but i cant find any solution to enter that location via ssh - can someone please give me a hint how to enter that location? 
Or is there a tutorial how to set up frigate in docker without an external storage, just inside the lxc? I did follow the tutotrial of "Home Automation Guy" and like he said i skipped the external-storage stuff - but the update of the docker seem not to work with this...

**Comment by cagivacode** [comment]
You have to shell into your lxc container (mine is named frigate) so lxc shell frigate...
then shell into the docker container (mine is also named frigate) so docker-compose exec frigate bash
