### ISSUE TITLE
Performance problems 0.13.1 with Wansview W5

### ISSUE THREAD

**Issue by Remko76** [blakeblackshear/frigate#9607]
### Describe the problem you are having

I am having performance issues ever since upgrading to 0.13.1 and have narrowed it down to a specific camera. My config is below. It is a Wansview W5 camera, connected through cabled network and is working absolutely perfect in 0.12.1. Recording, detection and streaming through Go2RTC is working very fast, I would say almost instant.
However, ever since I upgraded to 0.13.1 it is incredibly slow (stream start now has a delay of almost 10 seconds) and causing a very high cpu load, basically maxing it out as soon as I have motion detection turned on for this camera.

It offers 2 streams, a main and a sub. The sub stream (which I use for detection) has a resolution of 768x432 which I have also specified in the config (had this already in 0.12.1). I have read about some of the issues around high CPU load since the upgrade but have not been able to find anything to resolve this. I have multiple cameras with a 640x360 resolution and they do not seem to cause the same delay and cpu load.

Actually experiencing this issue on 2 systems, my dads an my own. He runs in HAOS, I run docker with Coral. I have posted config and log from him, since his setup is way easier and he only has 2 cameras, but the issue is the same on both systems.

Any ideas...?

### Version

0.13.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.10
  user: XXX
  password: XXX

ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

go2rtc:
  streams:
    garage:
      - rtsp://USER:PASS@192.168.178.100:554/live/ch0
      - ffmpeg:garage#audio=opus
    garage_sub:
      - rtsp://USER:PASS@192.168.178.100:554/live/ch1
      - ffmpeg:garage_sub#audio=opus
  webrtc:
    candidates:
    - 127.0.0.1:8555
    - stun:8555

cameras:
  garage:
    ffmpeg:
      inputs:
        #High Res
        - path: rtsp://127.0.0.1:8554/garage_main
          roles:
            - record
 #           - detect
        #Low Res    
        - path: rtsp://127.0.0.1:8554/garage_sub
          roles:
            - detect
#            - record
    detect:
      enabled: true
      width: 768
      height: 432
      fps: 15
    snapshots:
      enabled: true
    record:
      enabled: true
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 10
    objects:
      track:
        - person
        - cat
        - bird
```

### Relevant log output

```shell
2024-02-01 21:02:56.234334734  [2024-02-01 22:02:56] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-02-01 21:02:56.237348366  [2024-02-01 22:02:56] peewee_migrate                 INFO    : Starting migrations
2024-02-01 21:02:56.243269664  [2024-02-01 22:02:56] peewee_migrate                 INFO    : There is nothing to migrate
2024-02-01 21:02:56.266308027  [2024-02-01 22:02:56] detector.cpu                   INFO    : Starting detection process: 299
2024-02-01 21:02:56.272250336  [2024-02-01 22:02:56] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-02-01 21:02:56.274843485  [2024-02-01 22:02:56] frigate.app                    INFO    : Output process started: 301
2024-02-01 21:02:56.282092070  [2024-02-01 22:02:56] frigate.app                    INFO    : Camera processor started for garage: 304
2024-02-01 21:02:56.295280874  [2024-02-01 22:02:56] frigate.app                    INFO    : Camera processor started for achtertuin: 307
2024-02-01 21:02:56.303452206  [2024-02-01 22:02:56] frigate.app                    INFO    : Capture process started for garage: 308
2024-02-01 21:02:56.313997497  [2024-02-01 22:02:56] frigate.app                    INFO    : Capture process started for achtertuin: 310
2024-02-01 21:03:13.151553214  [2024-02-01 22:03:13] frigate.comms.dispatcher       INFO    : Turning off recordings for achtertuin
2024-02-01 21:03:13.880448881  [2024-02-01 22:03:13] frigate.comms.dispatcher       INFO    : Turning off snapshots for achtertuin
2024-02-01 21:03:15.894204147  [2024-02-01 22:03:15] frigate.comms.dispatcher       INFO    : Turning off recordings for garage
2024-02-01 21:03:16.569531434  [2024-02-01 22:03:16] frigate.comms.dispatcher       INFO    : Turning off snapshots for garage
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by Remko76** [comment]
Could you be a bit more specific about what you would change in the config? This is something I have struggled with in the beginning and found the config I use now to be the only one where I get the streams with audio.... Any recommendations on changes would be highly appreciated, because the ffmpeg topic is quite big and I struggle getting my head around all the options there.

However...as I mentioned...this all runs really smoothly in 0.12.1 on the same hardware (older core i5 mini pc) with about 10% CPU load. After the upgrade it is more around 80 to 90 % load, which makes me suspect something else is going on.

**Comment by Remko76** [comment]
Thanks for your quick reply by the way, greatly appreciated. I also saw your comment on my closed topic..thanks!

**Comment by NickM-27** [comment]
replace the global ffmpeg config with 

```
ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac
```

> However...as I mentioned...this all runs really smoothly in 0.12.1 on the same hardware (older core i5 mini pc) with about 10% CPU load. After the upgrade it is more around 80 to 90 % load, which makes me suspect something else is going on.

that's why I said "start by..."

**Comment by NickM-27** [comment]
after you do that we will want a screenshot of the system page

**Comment by Remko76** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/75678314/e3a72c02-a982-4363-8cce-b01259cff92a)


![image](https://github.com/blakeblackshear/frigate/assets/75678314/93f08237-e49e-49a9-9da8-78e9fd990d75)

**Comment by NickM-27** [comment]
your CPU is not able to keep up with detection, we highly recommend using a GPU for object detection. You could most likely use your iGPU with OpenVINO instead of the GPU.

the reason this happens on 0.13 is likely because motion detection is more sensitive by default

**Comment by Remko76** [comment]
For comparison, with the same config this is the CPU load with 0.12.1

![image](https://github.com/blakeblackshear/frigate/assets/75678314/92fcd72a-c9b9-4929-b3af-bcf42be2b71e)



As I mentioned, I have a coral in my own system but experience the same issue when updating to 0.13.1

**Comment by Remko76** [comment]
I will give that a try first and will create a seperate issue for my own system with those configs and screenshots. I will update this thread with the result of the openvino detector.

**Comment by Remko76** [comment]
![image](https://github.com/blakeblackshear/frigate/assets/75678314/1aa06f5f-765d-433c-ac0d-19dac05ed4f5)


Definetely a lot better this way. Altough it still has doubled the CPU load compared to 0.12.1, from 20 to now 40% average. But not nearly as bad as the initial configuration, so thanks for that tip. Still wondering what is the best option for this setup though. I think using 0.12.1 will be enough for him and it does reduce the stress on his system so maybe I will revert to that for him.

Now onto documenting my own issue... Maybe a bit more work with because of my docker setup...

**Comment by NickM-27** [comment]
the detect fps is 32 which is a lot. You probably just need to tune motion detection on his setup https://docs.frigate.video/configuration/motion_detection

**Comment by Remko76** [comment]
I used that fps because that is what the stream offered. Must have overread that 5 is the recommendation. Changed it now and that also makes a quite a difference. Thanks for that tip!!
![image](https://github.com/blakeblackshear/frigate/assets/75678314/417e861d-7f1f-4ff8-89e5-ec5334732c5a)

**Comment by NickM-27** [comment]
yes, to be clear the detect fps does not need to match the camera fps

**Comment by NickM-27** [comment]
will close this issue and you can create another for your use case
