### ISSUE TITLE
Frigate Plus Account creation not working (not receiving any code for email confirmation)

### ISSUE THREAD

**Issue by cho0p** [blakeblackshear/frigate#9610]
### Describe the problem you are having

It's probably the wrong channel for this kind of issue but I haven't found any other contact details. I like Frigate hence I wanted to sign up for Frigate Plus in order to support the development of this software. It's not possible right now to create an account with an email address. I tried it with two different email addresses with different domains and top-level domains but I have never received any of the confirmation codes which are needed to validate the email address (also checked the spam folder of course). 

### Version

-

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
You should email blake@frigate.video regarding this
