### ISSUE TITLE
With the implementation of PTZ I've noticed that you can also utilise the cameras "Preset" positioning too, which is great.  Is there a way that these can be utilised as individual entities to be used for automation in Home Assistant?  Thanks guys.

### ISSUE THREAD

**Issue by nethergatewws** [blakeblackshear/frigate#9640]

**Comment by hawkeye217** [comment]
There's no need for Frigate to provide this as it's already available with [Home Assistant's ONVIF integration](https://www.home-assistant.io/integrations/onvif/). You can call your camera's presets in an automation through a service call that way.

**Comment by NickM-27** [comment]
To be clear the frigate integration provides a ptz service

**Comment by nethergatewws** [comment]
Thanks Nick but that's not really what I asked.  Potentially lost in translation...

**Comment by nethergatewws** [comment]
> There's no need for Frigate to provide this as it's already available with [Home Assistant's ONVIF integration](https://www.home-assistant.io/integrations/onvif/). You can call your camera's presets in an automation through a service call that way.

Thanks.  Must just be that the Onif for my cameras doesn't expose the presets using that integration but it does when using the PTZ feature in Frigate.  Potentially I'm doing something wrong so I'll investigate it.  Be nice if it was all rolled up into Frigate so it can be used as an all in one NVR so to speak.  Thanks for the pointers though.  Appreciated

**Comment by nethergatewws** [comment]
> There's no need for Frigate to provide this as it's already available with [Home Assistant's ONVIF integration](https://www.home-assistant.io/integrations/onvif/). You can call your camera's presets in an automation through a service call that way.

Scrap my last! Too early for me to be thinking 🤣. I found it so thank you for your help.  👊🏻🙌🏻

**Comment by hawkeye217** [comment]
> > There's no need for Frigate to provide this as it's already available with [Home Assistant's ONVIF integration](https://www.home-assistant.io/integrations/onvif/). You can call your camera's presets in an automation through a service call that way.
> 
> Scrap my last! Too early for me to be thinking 🤣. I found it so thank you for your help. 👊🏻🙌🏻

Great, happy to help.

And to clarify, @NickM-27 was indicating a way to achieve the same thing as the HA onvif integration but through the Frigate HA integration, which offers a `frigate.ptz` service call that you can also use in automations.

**Comment by nethergatewws** [comment]
That now makes perfect sense and a better way too. Less connections to the cameras.  Thanks @NickM-27 too.
