### ISSUE TITLE
Trigger snapshot or detect color changes

### ISSUE THREAD

**Issue by Trainerbert** [blakeblackshear/frigate#9642]
Hey there,

I am using Frigate for my normal cameras and it is working really well. I would like to use Frigate to trigger a snapshot so that I can process that picture myself. Currently I use a Webcam to detect an error(simple red light) from my heating. I run this in a Windows VM which is really not efficient. It would be awesome if I could trigger a snapshot or even better detect color changes in certain pixel areas.
For my case this the idea wold be like this:
Define an area of pixel for example 16x16. Now set the averagy color value of that area.
If that pixel area changes the color out of the defined range pixel color range you will get an event which can than be used to trigger a notification or something else.

**Comment by NickM-27** [comment]
You can already trigger manual events, I don't think frigate is the right tool for color detection. There are other projects out there that are made for things like this
