### ISSUE TITLE
"Deselect All" on Events page for cameras, labels, and zones

### ISSUE THREAD

**Issue by murkumurdok** [blakeblackshear/frigate#9656]
**Describe what you are trying to accomplish and why in non technical terms**
When selecting either a camera, label, or zone for filtering in the events page, I would like the option to "Deselect All" including the already existing "Show All" Button. By default, the events page will have all cameras/labels/zones selected.  However, if I want to filter out only one particular type of event, I have to manually uncheck all of the other options.  This can become tedious because I have 8 cameras and almost twenty different zones.

**Describe the solution you'd like**
An additional option to deselect or uncheck all options in addition to the show all button

**Describe alternatives you've considered**
The only alternative is to manually deselect all other options if you want to filter Events to one particular camera/label/zone

**Additional context**
This is purely a time-saving/quality of life function--it would allow me to rapidly view events associated with only one particular camera or zone so that I can find a particular event more quickly.

**Comment by NickM-27** [comment]
This already exists, just press the focus button next to the label

**Comment by murkumurdok** [comment]
Oops, I had no idea what that button did.  Thanks!
