### ISSUE TITLE
Full Screen Exit Button

### ISSUE THREAD

**Issue by NexGen-3D-Printing** [blakeblackshear/frigate#9658]
**Describe what you are trying to accomplish and why in non technical terms**
If you are using a touch interface or only have a mouse connected to the display system, its difficult to exit out of a full screen view, the GUI works perfectly on a desktop PC, but if its on a display with not physical keyboad attached, like a Android Tablet, iPad, Surface Tablet or a large Touchscreen display it Gui works perfect except when it goes into a full screen view.

**Describe the solution you'd like**
Maybe add a full screen exit button on the lower right side of the full screen view.

**Describe alternatives you've considered**
I have tried all sorts of things, and the only easy way to exit out of Birdseye or any particular camera from a full screen view is to hit the escape key on a keyboard, some browsers will give you an "X" at the top to exit, but this is not all browsers, most tell you to hit "ESC" which is not possible if its a touchscreen device, in some cases you can swipe back if its a touch screen and it will exit, but it throws you back to a previous window, and not simply back from full screen.

I have moved over from Blueiris, and with the web interface with that software, there is a full screen exit button and made navigating on touch devices quite easy.

**Additional context**
Have tried the following browsers:

- Chrome
- Chromium
- Brave
- Safari
- Edge
- Vivaldi

Have tried on the following devices:

- iPad
- Samsung Tablet
- Surface Pro
- RPI with TouchScreen
- Generic PC with a large Touchscreen running, Windows, Linux and openFyde

Have also tried the internal window in HAOS, and the direct GUI (Port 5000)

Below is the button that we need added to the full screen view, this button takes you too full screen, but once there, the button is no longer available.

![Button](https://github.com/blakeblackshear/frigate/assets/20825418/4d59aecf-4f15-4717-9fe7-7629c67d1d9b)

**Comment by NickM-27** [comment]
The full screen button is there, you just move the mouse on desktop or touch on mobile to view the button

**Comment by NexGen-3D-Printing** [comment]
> The full screen button is there, you just move the mouse on desktop or touch on mobile to view the button

Is that with Birdseye view?

**Comment by NickM-27** [comment]
It is there with birdseye if you use mse or WebRTC. If using jsmpeg then you just click again to exit.

**Comment by NexGen-3D-Printing** [comment]
> It is there with birdseye if you use mse or WebRTC. If using jsmpeg then you just click again to exit.

Awesome, I have it working now, I had to add "restream: True" to the config, 

birdseye:
  enabled: True
  restream: True
  width: 1920
  height: 1080
  quality: 1
  mode: continuous

I assume without that, its using jsmpeg, and definately clicking again does not extit full screen, I nearly punched a hole in the dam thing trying to get out of full screen, I have tested across multiple platforms and devices, once its in full screen, I could not get out, I think the only system that did work was Fedora using Firfox, swiping down did exit the full screen, but could not reproduce this behavour on other systems.
