### ISSUE TITLE
Feature Request - possibility to move timestamp position on camera 

### ISSUE THREAD

**Issue by michelebossa** [blakeblackshear/frigate#968]
Hi,
I'd like if it is possible to decide the position of timestamp indication (maybe some configuration Up/Down/Right/Left) in my case one of camera the value it is not clear due the sky.

![image](https://user-images.githubusercontent.com/38975058/113740629-2cf5cd80-9701-11eb-8a77-2c333325d053.png)

Thanks.

**Comment by JasonSwindle** [comment]
An on top of this request, add shadowing / thin outline or stroke.

**Comment by quenthal** [comment]
..and capability to date time format.
