### ISSUE TITLE
[Bug]: Birdseye image is corrupt in 0.13 when using non-standard aspect ratios

### ISSUE THREAD

**Issue by sjkjs** [blakeblackshear/frigate#9692]
### Describe the problem you are having

This is a new bug introduced in 0.13, it did not occur in 0.12.

When using a non-standard aspect ratio for Birdseye, for example 2688x1520, the image on the Birdseye page will be corrupted.

The log files indicate that the resolution is being forced to 2688x1512 but this does not actually happen. If I modify the Frigate config to set the resolution to 2688x1512 and then restart, everything works as expected and the image looks normal.

My reason for originally using 2688x1520 was because it was the resolution of my cameras, so I figured it would make it easy to scale the images down (e.g. to fit 4 cameras in Birdseye would mean halving each camera resolution).

### Version

0.13.1

### Frigate config file

```yaml
birdseye:
  enabled: True
  mode: continuous
  quality: 10
  width: 2688
  height: 1520
```

### Relevant log output

```shell
2024-02-06 07:34:02.990197223 [2024-02-06 07:34:02] frigate.output WARNING : The birdseye resolution is a non-standard aspect ratio, forcing birdseye resolution to 2688 x 1512
2024-02-06 10:17:18.129225263 [2024-02-06 10:17:18] frigate.output WARNING : Unable to copy frame Courtyard1707168667.822514 to birdseye.
2024-02-06 10:17:18.129616200 [2024-02-06 10:17:18] frigate.output WARNING : Unable to copy frame Driveway1707168667.837917 to birdseye.
2024-02-06 10:17:18.136474920 [2024-02-06 10:17:18] frigate.output WARNING : Unable to copy frame Front_yard1707168667.726789 to birdseye.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
This is expected given the warning, I'd suggest just using a standard aspect ratio like 2560x1440

**Comment by sjkjs** [comment]
But the warning which says "forcing birdseye resolution to 2688 x 1512" should actually force the resolution to 2688x1512, which would have the same behaviour as manually setting it to 2688x1512 in the config, shouldn't it?

It seems that it prints the warning message but doesn't actually take the correct action implied by the warning.
