### ISSUE TITLE
Can this be used with Google Coral?

### ISSUE THREAD

**Issue by eroji** [blakeblackshear/frigate#97]
This is a general question and my apologies for my ignorance. I want to set up object recognition and person detection for video streams of my IP cameras. I have homelab infrastructure to do the heavy lifting. Is it possible to leverage frigate without using a Google Coral accelerator?

**Comment by blakeblackshear** [comment]
A future version will support running with and without a Coral. I would strongly recommend a Coral though. I get 10x the performance over a modern i7 processor on 5 watts of power. Why not get a Coral?

**Comment by eroji** [comment]
I'm trying to run it in a Kubernetes cluster on vSphere. The hosts do not have any GPU and having a USB device passed through would probably hinder vMotion.

**Comment by binarybucks** [comment]
Also passing through the USB or m.2 accelerator doesn't work unless there is a trick I haven't tried yet.

**Comment by eroji** [comment]
Though from the documentation, it appears the video device also needs to be a local dev. I probably need to use a different implementation to take a RTSP stream instead.

**Comment by blakeblackshear** [comment]
The video device is just to leverage hardware acceleration when decoding an RTSP stream. If you have a lot of spare CPU cycles to spare, then it will soon be possible. It may be worth having a bare metal node in your cluster that is labeled. I know @billimek is running frigate in k8s.

**Comment by billimek** [comment]
Frigate helm chart (for kubernetes) is [on helm hub](https://hub.helm.sh/charts/billimek/frigate)!

**Comment by mcondren** [comment]
> Also passing through the USB or m.2 accelerator doesn't work unless there is a trick I haven't tried yet.

I’m not sure if you are using VMware or not, but I was running a frigate docker container in a Debian VM in ESxi. I was using pass through for coral and it was working great.

**Comment by eroji** [comment]
I am using VMware ESXi but it's a cluster with vCenter with vMotion.

**Comment by eroji** [comment]
> Frigate helm chart (for kubernetes) is [on helm hub](https://hub.helm.sh/charts/billimek/frigate)!

Very cool

**Comment by binarybucks** [comment]
> I’m not sure if you are using VMware or not, but I was running a frigate docker container in a Debian VM in ESxi. I was using pass through for coral and it was working

Interesting, I tried passing through the USB device in ESXi 6.7 to a CentOS Docker host and a Ubuntu VM. Neither did work with Frigate or the Coral examples. It always reports the "failed allocating tensors" error and the Global Unichip device never becomes a Google Inc device. The Docker Container was running as privileged. 

Did you pass through the USB device to a VMware xhci USB controller in the VM or do you have a PCI passthrough capable USB controller on the host?

Could you post some details about the versions used and your setup?

**Comment by eroji** [comment]
Oh I did not even try. I figured there would be issues with passthrough/vMotion so I was hoping there is a version that just used CPU only which is why I created this ticket just to ask.

**Comment by mcondren** [comment]
> > I’m not sure if you are using VMware or not, but I was running a frigate docker container in a Debian VM in ESxi. I was using pass through for coral and it was working
> 
> Interesting, I tried passing through the USB device in ESXi 6.7 to a CentOS Docker host and a Ubuntu VM. Neither did work with Frigate or the Coral examples. It always reports the "failed allocating tensors" error and the Global Unichip device never becomes a Google Inc device. The Docker Container was running as privileged.
> 
> Did you pass through the USB device to a VMware xhci USB controller in the VM or do you have a PCI passthrough capable USB controller on the host?
> 
> Could you post some details about the versions used and your setup?

I have actually moved to a bare metal docker host now, so the details are just what I can remember. I set USB port to pass through in esxi, then I used a Debian based VM (coral only supports Debian-based Linux distros). I then ran the docker container in privileged mode so it could access the usb device on the VM and/or passed the /dev/bus/usb/ device explicitly in the docker config. I had to fiddle with it for a while.
