### ISSUE TITLE
Add motion sensor to HomeKit 

### ISSUE THREAD

**Issue by piscinas** [blakeblackshear/frigate#9705]
(https://github.com/AlexxIT/go2rtc/issues/812#issue-2034055363)
I have created this issue on AlexxIT repository, but now I think this could be done on frigate side.
It was a nice feature to implement.

**Comment by povlhp** [comment]
Can't you use the blueprint as a template, and instead of sending a message, then just flip a binary helper - you could likely make that a motion detector.

**Comment by NickM-27** [comment]
Frigate itself doesn't work with HomeKit, the only way that would work is if it was supported through go2rtc

**Comment by povlhp** [comment]
The integration to home assistant is there. To map the integration to something exposed to HomeKit integration is a pure HA task.

**Comment by piscinas** [comment]
I have my cameras integrated with HomeKit using go2rtc, but sensors are not passed down.
Since frigate use go2rtc it could passes binary sensors to go2rtc to attach to the camera, even if has a short delay…

**Comment by piscinas** [comment]
> The integration to home assistant is there. To map the integration to something exposed to HomeKit integration is a pure HA task.

Using HA to do it, is causing several issues and delays…
