### ISSUE TITLE
[FR] Show None in addition to Show All in filter lists

### ISSUE THREAD

**Issue by DorjeDorf** [blakeblackshear/frigate#9743]
**Describe what you are trying to accomplish and why in non technical terms**
When trying to look at events of a specific type, if you have more than one configured - you have to manually unclick all types and only leave the one you want selected. 

**Describe the solution you'd like**
There is a button to Show All. I would love it if there was a button to Show None to ease the process of unclicking all filters and speed this process up. This goes for events as well as zones and cameras. 

**Describe alternatives you've considered**
Manually unclicking everything each time, but to be honest - it's annoying and not great UX :)

**Comment by blakeblackshear** [comment]
![Screenshot_20240208-061150.png](https://github.com/blakeblackshear/frigate/assets/569905/37860cba-4b17-45ea-9678-a93c61f17ca3)

**Comment by blakeblackshear** [comment]
That icon will unselect all and select just the one label. Only takes one click rather than two with what you suggested.

**Comment by DorjeDorf** [comment]
I had a feeling that was too big of an omission, but had to try :) thanks for the hint.
