### ISSUE TITLE
redirect /events -> /history  (on new v14 web GUI) (feature suggestion)

### ISSUE THREAD

**Issue by bob454522** [blakeblackshear/frigate#9751]
Ive been running v13 for months with great results,  so recently i began testing the v14-dev releases and its clear lots of great work has been done (and is still going on!)  (thanks).

one idea / suggestion ,  It appears the "events" section from v13 is now called "history" in v14,  **So perhaps the path/url of  /events should be automatically redirected (HTTP rewrite) to /history,**  I suggest this as in my case I have several bookmarks (and ios home screen links) in different locations and gui interfaces (ie heimdal ect) that point directly to http://<frigateIP>/events  so Perhaps this will help make the transition a bit smoother for others once 14 is released eventually.

This is easy for me to change / adjust, however this may especially help those who are less tech savvy,  who may be only *viewing* someone else's frigate install via a link or bookmark or share)

thanks

**Comment by NickM-27** [comment]
we are not taking feedback on 0.14 right now
