### ISSUE TITLE
Gesture Detection

### ISSUE THREAD

**Issue by kmelihk** [blakeblackshear/frigate#9789]
I would like Frigate to be able to detect not only people but also gestures. Currently I use this project: https://github.com/mmcc-xx/gesturesensor for detecting gestures through Frigate. With gestures, I'm able to open/close garage doors for example.

 I understand this may be out of scope of a typical NVR solution, but since Frigate is intertwined with Home Assistant and home automation, it would make sense it could include features that would enrich automation within Home Assistant.

**Comment by msolomos** [comment]
Hi, have you managed to build the container for gesture sensor? I have many dependency problems
