### ISSUE TITLE
[HW Accel Support]: RK3588 RGA3 other than YUV420P

### ISSUE THREAD

**Issue by great9** [blakeblackshear/frigate#9814]
### Describe the problem you are having

Due to hardware design of the RK3588's RGA2 VPU there's a limitation to the amount of memory the the chip can access. The VPU can access more than 4GB of RAM if the output format is other than YUV420P. Is frigate YUV420P only?
The VPU reset's every time it hits the 4GB addressing limit, recordings are lost and CPU usage spikes tens of times per day for 4 cameras.

### Version

0.14 beta

### Frigate config file

```yaml
-
```

### docker-compose file or Docker CLI command

```yaml
-
```

### Relevant log output

```shell
-
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

dahua

**Comment by NickM-27** [comment]
0.14 is not in beta to be clear. And yes frigate requires yuv420p
