### ISSUE TITLE
[Support]: Howto label Frigate+ pictures with different labels

### ISSUE THREAD

**Issue by anduchs** [blakeblackshear/frigate#9824]
### Describe the problem you are having

I want to upload and label the German postal service "Deutsche Post" to Frigate+.
However I only have the limited choice of delivery companies (FedEx, UPS, Amazon).
Should I just label the logo of "Deutsch Post" as e.g. UPS or is there a way to have new labels be introduced ?

In the latter case, I'd like to propose the labels
- Post / DHL
- Hermes
- GLS
These are the most notable German delivery companies besides Amazon.

### Version

---

### Frigate config file

```yaml
---
```

### Relevant log output

```shell
---
```

### FFprobe output from your camera

```shell
---
```

### Frigate stats

```json
---
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

SV3C

**Comment by NickM-27** [comment]
label requests should use the frigate+ discussion https://github.com/blakeblackshear/frigate/discussions/7932
