### ISSUE TITLE
Include Audio in frigate/events

### ISSUE THREAD

**Issue by murkumurdok** [blakeblackshear/frigate#9825]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to tie clips/snapshots to certain audio events (that don't have motion) so that they are included in Home Assistant notifications, in the same way that the notification blueprint allows you to view the corresponding clip/snapshot of object detection events.

**Describe the solution you'd like**
I figure that the best way to accomplish this would be to include information about audio detector events in frigate/events topic, because now they only show up in the frigate/{camera}/audio/state topic, but I am admittedly not sure if this would work or if a better alternative exists.

**Describe alternatives you've considered**
I can't think of any other alternative to make this work

**Additional context**
I'm thinking this would be useful as a baby monitor for situations where frigate detects audio, but doesn't detect movement so as to trigger a motion event.  I would rather be notified by true audio event and be able to see a clip of the recorded audio than simply be notified of every motion event that occurs on the camera.

**Comment by NickM-27** [comment]
it would not make sense to include audio in that topic because the vast majority of the fields don't apply to audio and it would require refactoring of existing scripts. 

This request is handled by https://github.com/blakeblackshear/frigate/issues/8862

**Comment by murkumurdok** [comment]
Thanks, I couldn't find that feature request before.
