### ISSUE TITLE
[Support]: occupancy fires before image is ready in Home Assistant

### ISSUE THREAD

**Issue by p4r4ll4x** [blakeblackshear/frigate#9837]
### Describe the problem you are having

I have a Node Red flow that starts with *_occupancy going to on.
I send image.* to Telegram, but multiple times the image is not yet available.

I could start the flow when image.* changes, but maybe there are better ways or there is a bug?

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
Not relevant atm, can add if needed.
```

### Relevant log output

```shell
Not relevant atm, can add if needed.
```

### FFprobe output from your camera

```shell
Not relevant atm, can add if needed.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
the occupancy sensors in home assistant are not directly tied to any image being ready

**Comment by p4r4ll4x** [comment]
> the occupancy sensors in home assistant are not directly tied to any image being ready

Thx, i will approach it in 2 separate flows.

**Comment by NickM-27** [comment]
feel free to create a new issue if something else comes up
