### ISSUE TITLE
Named exports

### ISSUE THREAD

**Issue by SpangleLabs** [blakeblackshear/frigate#9838]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to name exported recordings so that I can more easily browse them in the UI, and remember why each recording was made, rather than having them sorted by just camera name then date.

**Describe the solution you'd like**
It would be great if I could specify a name when creating the export. I don't need (or necessarily want) it to be the filename, but to be able to see the names listed would be super helpful in understanding what and why each recording was made (like, timelapses, or wanting to capture an event from another angle.)

My particular example today was a fox that was detected as an event by one of my cctv cameras (as a bird), and I wanted to store the other views of the fox, so created some exports for the time periods on the other cameras. But looking back, I will not know which of the exports are that fox, and which ones are timelapses of bird boxes or whatever else.

**Describe alternatives you've considered**
I suppose I could just rename the files in the directory? I'm not sure whether they're just stored there, or whether there is actually data kept in the database about them.
If it's just filenames, then being able to specify that would also be acceptable to me, and I could do my own naming schemes to handle that.

**Additional context**
I love the new UI for the exports btw, thank you so much for adding that! I'm constantly amazed by how slick Frigate looks and how well the UI all works. Certainly soothed when I was struggling to get the hwacceleration working, and when I'm getting annoyed

Not sure whether to create a separate ticket, but it would also be amazing if I could configure additional presets to have different speeds of timelapse and such?

**Comment by NickM-27** [comment]
This has been implemented as part of the new ui
