### ISSUE TITLE
[Support]: db migrate fails when moving frigate.db onto itself

### ISSUE THREAD

**Issue by lordbah** [blakeblackshear/frigate#9857]
### Describe the problem you are having

Container doesn't start when trying to migrate from 0.12.? to 0.13.1.

### Version

0.13.1

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
frigate              | 2024-02-14 21:03:16.354265981  [INFO] Moving db from '/media/frigate/frigate.db' to the '/config' dir...
frigate              | mv: '/media/frigate/frigate.db' and '/config/frigate.db' are the same file
frigate              | 2024-02-14 21:03:16.365470308  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate              | s6-rc: info: service legacy-services: stopping
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

### Any other information that may be helpful

docker-compose.yaml volumes
```
      - /media/frigate/:/config/
      - /media/frigate:/media/frigate
```
On 0.12 the frigate.db was in /media/frigate while Frigate's config.yaml was elsewhere. (/media/frigate is an NFS mount on the NAS). With 0.13.1 we have to map the entire /config directory so it seemed easiest to me to move the config.yaml onto the NAS too.

The mv command fails because it is moving the frigate.db file on top of itself. This is not marked in the docker compose output with "[ERROR]" but it appears to be treated as an error because it exits, docker retries it, endless loop. However, if we can detect that it is in fact the same file we ought to treat it as successful (nothing to do) and continue.

**Comment by NickM-27** [comment]
The change was specifically done so the the DB is but run on network storage, this causes issues. I'd suggest keeping the config directory local

**Comment by Suzano-Sho** [comment]
I'm having this exact same error and my config directory is local.

**Comment by NickM-27** [comment]
it means you have a DB file in /config and /media/frigate. Delete one (the older one)
