### ISSUE TITLE
[Support]: Can I run two separate Frigate Docker instances referencing the same cameras with different retention policies?

### ISSUE THREAD

**Issue by csvke** [blakeblackshear/frigate#9861]
### Describe the problem you are having

I want to have a setup where I retain all camera footages locally at all times while another will only retain motion detected footages and subsequently upload them to the cloud. 
As I don’t think I can set such retention policy with a single Frigate instance, nor I can retain all footages at all times but the files will be split up and marked when motion is detected, I think running two Frigate is the only way?

All cameras will be on RTSP feeds.

### Version

N/A

### Frigate config file

```yaml
None
```

### Relevant log output

```shell
None
```

### FFprobe output from your camera

```shell
None
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Firefly CT36L

**Comment by NickM-27** [comment]
You could run a single frigate instance and just use the export feature to export periods of time where motion was detected.

**Comment by csvke** [comment]
Thanks for the reply. If I want to automate the export, say, exporting the motion detected files to an Amazon S3 bucket, where should I start looking?

**Comment by NickM-27** [comment]
export api or export service in home assistant
