### ISSUE TITLE
[Support]: Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa-beta:5000 ssl:default [Name has no usable address]

### ISSUE THREAD

**Issue by borgqueenx** [blakeblackshear/frigate#9867]
### Describe the problem you are having

As soon as i did a complete host restart, all frigate-made entity's (like occupancy) are not detecting anything. everything is available but on "nothing detected".
As soon as i then restart frigate, the occupancy sensor entity's are being correctly shown.
I figured the above log message from HA core has something to do with it.

### Version

0.13.1

### Frigate config file

```yaml
-
```

### Relevant log output

```shell
Error fetching information from http://ccab4aaf-frigate-fa-beta:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa-beta:5000 ssl:default [Name has no usable address]
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
how do i get these logs?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

### Any other information that may be helpful

Note that in the error, the first part is a actual link, the secondary is no link.

**Comment by NickM-27** [comment]
This just means frigate wasn't running.

**Comment by borgqueenx** [comment]
> This just means frigate wasn't running.

Frigate is at least running a little later and then not updating the entity's. Restarting solves it. Is it perhaps possible to make frigate the last add-on to start?

**Comment by NickM-27** [comment]
That is a docker feature, not sure if add-ons support it

**Comment by mathgim** [comment]
I have the same issue
