### ISSUE TITLE
[Support]: TRT Devcontainer Broken

### ISSUE THREAD

**Issue by alexyao2015** [blakeblackshear/frigate#9874]
### Describe the problem you are having

Since the split of the trt docker images, you no longer can use `devcontainer-trt` to use the [tensorrt devcontainer](https://github.com/blakeblackshear/frigate/blob/dev/docker-compose.yml). It seems to me that the workaround for this is to manually build the trt image then specify it in the `docker-compose.yml`. Is there a better way to do this?

### Version

dev

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
N/A
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

N/A

**Comment by kdill00** [comment]
I am not sure but i usually clone dev and build it locally and I get a message saying these early versions of v14 are not going to be released yet
