### ISSUE TITLE
[Support]: Unstable/experimental builds are not enabled, Frigate is exiting.

### ISSUE THREAD

**Issue by stigglitch** [blakeblackshear/frigate#9877]
### Describe the problem you are having

Dev versions are not working anymore?

The errorlog:

This build is not for public use. Please use Frigate stable.
Unstable/experimental builds are not enabled, Frigate is exiting.

dev-f6a4c2a works fine! The newer ones fail to start. Any way of getting access to early testbuilds?

### Version

0.14

### Frigate config file

```yaml
NN
```

### Relevant log output

```shell
This build is not for public use. Please use Frigate stable.
Unstable/experimental builds are not enabled, Frigate is exiting.
```

### FFprobe output from your camera

```shell
NN
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

NN

**Comment by blakeblackshear** [comment]
These builds are not ready for use. You can guarantee that changes at this point are going to be broken, missing features, and likely to corrupt the database sometimes.

If you aren't looking to do development and open a PR, we would rather you not use them. If you want to proceed anyway, you have to set an environment variable named `I_PROMISE_I_WONT_MAKE_AN_ISSUE_ON_GITHUB`, and you are completely on your own.

**Comment by stigglitch** [comment]
Great, thanks! I wont report anything unless I'm running a release version.

I assume a system variable and not in the frigate config?

0.14 is awesome!

**Comment by blakeblackshear** [comment]
Set it in your compose file.
