### ISSUE TITLE
When creating a zone, show other zones

### ISSUE THREAD

**Issue by andrey-skat** [blakeblackshear/frigate#9925]
I want to be able to see other zones borders while creating zone. Because it's hard to align zone borders without intersection if I can't see them all

**Comment by nwish** [comment]
Although I do like this suggestion and I hope they implement it, all my zones overlap a little and I don’t really think it negatively affects anything.

**Comment by djak250** [comment]
I just got back after roughing them out and match up the coordinates manually. In the config. Though I do agree that this would be nice
