### ISSUE TITLE
[Function adjustment] It should only display the gpu usage occupied by frigate

### ISSUE THREAD

**Issue by SeanChengN** [blakeblackshear/frigate#9955]
**Describe what you are trying to accomplish and why in non technical terms**
In the system page of frigate, the usage rate of intel-qsv seems to be the usage rate of all processes, not the usage rate of frigate itself, because it should only occupy about 2% normally.
![chrome_ewBdYvanjw](https://github.com/blakeblackshear/frigate/assets/20624068/0309abda-5cfb-41b5-a75e-fce8c2891b45)

![chrome_zrYuBBHWRz](https://github.com/blakeblackshear/frigate/assets/20624068/df9124d0-d8aa-4a9d-b461-a846b6f55061)
I don't know if it is possible to modify this function on a technical level, it should show the part used by frigate.

**Describe the solution you'd like**
It should show the part used by frigate.

**Describe alternatives you've considered**

**Additional context**
I'm using handbrake to transcode video files, so it's taking up a lot of gpu usage.
![chrome_1OGo0iky8z](https://github.com/blakeblackshear/frigate/assets/20624068/dc4ee4a3-0bce-4a87-92d8-bad289a7ab31)

**Comment by NickM-27** [comment]
None of the GPU utilities provide this information and Intel GPU top is the worst of them all, there is no way for this to be done with the tools working as they currently do.
