### ISSUE TITLE
After Update last Version Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.5', 5000)]

### ISSUE THREAD

**Issue by mrfrag1** [blakeblackshear/frigate#9973]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/9972

<div type='discussions-op-text'>

<sup>Originally posted by **mrfrag1** February 22, 2024</sup>
Hi,

after update in HACS on HA i have the issue:

Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Connect call failed ('172.30.33.5', 5000)]

The integration ist not loaded.

i have not change everything.

Thanks</div>

**Comment by NickM-27** [comment]
you should use discussions, this is not a feature request
